
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Royal-Black-38401',
        'Royal Black Police',
        'Royal',
        'for men',
        NULL,
        NULL,
        'Nutmeg, elemi, Bergamot and Lime',
        'Jasmine, Sage and Violet',
        'Cedar, Patchouli, Cashmirwood and White Amber',
        'woody,aromatic,fresh spicy,citrus,patchouli',
        'Royal BlackbyPoliceis a Woody Aromatic fragrance for men.Royal Blackwas launched during the 2010''s. Top notes are Nutmeg, elemi, Bergamot and Lime; middle notes are Jasmine, Sage and Violet; base notes are Cedar, Patchouli, Cashmirwood and White Amber.',
        3.67,
        6,
        NULL
      ),
(
        'Police-Potion-Absinthe-For-Him-89775',
        'Police Potion Absinthe For Him Police',
        'Police',
        'for men',
        NULL,
        NULL,
        'cannabis, Mandarin Orange and Black Pepper',
        'Star Anise, Artemisia and Sage',
        'Guaiac Wood, Vetiver and Cedar',
        'aromatic,herbal,cannabis,woody,soft spicy',
        'Police Potion Absinthe For HimbyPoliceis a fragrance for men.Police Potion Absinthe For Himwas launched in 2023. Top notes are cannabis, Mandarin Orange and Black Pepper; middle notes are Star Anise, Artemisia and Sage; base notes are Guaiac Wood, Vetiver and Cedar.',
        2.94,
        18,
        NULL
      ),
(
        'Police-Potion-Arsenic-For-Her-89772',
        'Police Potion Arsenic For Her Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Poison, Cinnamon and Coconut',
        'Orchid, Tobacco Leaf and Ylang-Ylang',
        'Tonka Bean, Myrrh and Patchouli',
        'sweet,warm spicy,amber,vanilla,cinnamon',
        'Police Potion Arsenic For HerbyPoliceis a fragrance for women.Police Potion Arsenic For Herwas launched in 2023. Top notes are Poison, Cinnamon and Coconut; middle notes are Orchid, Tobacco Leaf and Ylang-Ylang; base notes are Tonka Bean, Myrrh and Patchouli.',
        4.4,
        25,
        NULL
      ),
(
        'Police-Potion-For-Her-79352',
        'Police Potion For Her Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Red Apple, Red Berries and Bergamot',
        'White Peach, Magnolia, Damask Rose and Orange Blossom',
        'Caramel, Vanilla, Benzoin and Amber',
        'fruity,sweet,vanilla,amber,caramel',
        'Police Potion For HerbyPoliceis a Floral Fruity fragrance for women. This is a new fragrance.Police Potion For Herwas launched in 2023. Top notes are Red Apple, Red Berries and Bergamot; middle notes are White Peach, Magnolia, Damask Rose and Orange Blossom; base notes are Caramel, Vanilla, Benzoin and Amber.',
        4.21,
        86,
        NULL
      ),
(
        'Police-Potion-Love-For-Her-69214',
        'Police Potion Love For Her Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Sea Notes, Grapefruit and Bergamot',
        'Tuberose, Rose and Orange Blossom',
        'Peach, Ambrarome and Musk',
        'white floral,tuberose,citrus,fruity,balsamic',
        'Police Potion Love For HerbyPoliceis a fragrance for women.Police Potion Love For Herwas launched in 2021. Top notes are Sea Notes, Grapefruit and Bergamot; middle notes are Tuberose, Rose and Orange Blossom; base notes are Peach, Ambrarome and Musk.',
        4.2,
        105,
        NULL
      ),
(
        'Police-Potion-Power-For-Him-69213',
        'Police Potion Power For Him Police',
        'Police',
        'for men',
        NULL,
        NULL,
        'Orange Blossom, Lavender, Aromatic Spices, Bergamot and Cinnamon',
        'Solar Notes, Jasmine, Violet, Apple and Amber',
        'White Musk, Precious Woods and Tonka Bean',
        'white floral,musky,powdery,citrus,violet',
        'Police Potion Power For HimbyPoliceis a fragrance for men.Police Potion Power For Himwas launched in 2021. Top notes are Orange Blossom, Lavender, Aromatic Spices, Bergamot and Cinnamon; middle notes are Solar Notes, Jasmine, Violet, Apple and Amber; base notes are White Musk, Precious Woods and Tonka Bean.',
        3.91,
        76,
        NULL
      ),
(
        'Police-Dark-Women-13959',
        'Police Dark Women Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Black Currant, Violet, Bergamot and Mandarin Orange',
        'Iris, Gardenia, Rose and Jasmine',
        'Vanille, Resin, Sandalwood and Virginia Cedar',
        'woody,powdery,vanilla,violet,iris',
        'Police Dark WomenbyPoliceis a Amber Floral fragrance for women.Police Dark Womenwas launched in 2011. Top notes are Black Currant, Violet, Bergamot and Mandarin Orange; middle notes are Iris, Gardenia, Rose and Jasmine; base notes are Vanille, Resin, Sandalwood and Virginia Cedar.',
        3.98,
        267,
        NULL
      ),
(
        'Police-Daydream-55669',
        'Police Daydream Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Dew Drop, Peach, Green Leaves and Orange',
        'White Flowers',
        'Musk and Sandalwood',
        'white floral,musky,aquatic,powdery,green',
        'Police DaydreambyPoliceis a Floral Fruity fragrance for women. Top notes are Dew Drop, Peach, Green Leaves and Orange; middle note is White Flowers; base notes are Musk and Sandalwood.',
        4.04,
        26,
        NULL
      ),
(
        'Police-Exotic-38398',
        'Police Exotic Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Granny Smith apple and Orange',
        'Magnolia, Violet and Peach',
        'Sugar, Sandalwood, Musk and Cedar',
        'fruity,sweet,fresh,tropical,powdery',
        'Police ExoticbyPoliceis a Floral Fruity fragrance for women.Police Exoticwas launched in 2015. Top notes are Passionfruit, Granny Smith apple and Orange; middle notes are Magnolia, Violet and Peach; base notes are Sugar, Sandalwood, Musk and Cedar.',
        4.38,
        13,
        NULL
      ),
(
        'Police-Passion-8830',
        'Police Passion Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Granny Smith apple, Bergamot, Orange and Cassis',
        'Lotus, Freesia, Hawthorn and Sunflower',
        'Caramel, Vanille, Sandalwood, Tonka Bean, Virginia Cedar and Musk',
        'floral,vanilla,sweet,caramel,woody',
        'Police PassionbyPoliceis a Floral Fruity fragrance for women.Police Passionwas launched in 2010. Top notes are Granny Smith apple, Bergamot, Orange and Cassis; middle notes are Lotus, Freesia, Hawthorn and Sunflower; base notes are Caramel, Vanille, Sandalwood, Tonka Bean, Virginia Cedar and Musk.',
        3.93,
        165,
        NULL
      ),
(
        'Police-Patchouli-38399',
        'Police Patchouli Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Cinnamon and Lemon',
        'Patchouli and Heliotrope',
        'Tonka Bean, Vanilla and Musk',
        'vanilla,warm spicy,patchouli,powdery,woody',
        'Police PatchoulibyPoliceis a Chypre fragrance for women.Police Patchouliwas launched in 2016. Top notes are Cinnamon and Lemon; middle notes are Patchouli and Heliotrope; base notes are Tonka Bean, Vanilla and Musk.',
        3.89,
        9,
        NULL
      ),
(
        'Police-Sunscent-37257',
        'Police Sunscent Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Cassis, Apple, Bergamot and Green Leaves',
        'Rose, Water Lily and Cyclamen',
        'Musk, Cedar, Vetiver and Sandalwood',
        'floral,green,fresh,fruity,aromatic',
        'Police SunscentbyPoliceis a Floral Woody Musk fragrance for women.Police Sunscentwas launched in 2013. Top notes are Cassis, Apple, Bergamot and Green Leaves; middle notes are Rose, Water Lily and Cyclamen; base notes are Musk, Cedar, Vetiver and Sandalwood.',
        3,
        7,
        NULL
      ),
(
        'Police-Pure-New-York-Man-13961',
        'Police Pure New York Man Police',
        'Police',
        'for men',
        NULL,
        NULL,
        'Spices and Citruses',
        'Palisander Rosewood, Ylang-Ylang and Jasmine',
        'Musk, Amber and Precious Woods',
        'woody,warm spicy,amber,sweet,citrus',
        'Police Pure New York ManbyPoliceis a Amber Spicy fragrance for men.Police Pure New York Manwas launched in 2011. Top notes are Spices and Citruses; middle notes are Palisander Rosewood, Ylang-Ylang and Jasmine; base notes are Musk, Amber and Precious Woods.',
        4.17,
        6,
        NULL
      ),
(
        'Police-Pure-New-York-Woman-13960',
        'Police Pure New York Woman Police',
        'Police',
        'for women',
        NULL,
        NULL,
        'Cassis, Pineapple and Bergamot',
        'Mimosa, Apple Blossom and Lotus',
        'Vanille, Cotton Candy, Virginia Cedar and Musk',
        'sweet,fruity,vanilla,aromatic,powdery',
        'Police Pure New York WomanbyPoliceis a Floral Woody Musk fragrance for women.Police Pure New York Womanwas launched in 2011. Top notes are Cassis, Pineapple and Bergamot; middle notes are Mimosa, Apple Blossom and Lotus; base notes are Vanille, Cotton Candy, Virginia Cedar and Musk.',
        4,
        10,
        NULL
      ),
(
        'Pure-Man-4191',
        'Pure Man Police',
        'Pure',
        'for men',
        NULL,
        NULL,
        'Ivy, Ginger, Bergamot and Grapefruit',
        'Magnolia, Jasmine and Iris',
        'Musk, Cedar and Vetiver',
        'citrus,woody,floral,powdery,iris',
        'Pure ManbyPoliceis a fragrance for men.Pure Manwas launched in 2008. Top notes are Ivy, Ginger, Bergamot and Grapefruit; middle notes are Magnolia, Jasmine and Iris; base notes are Musk, Cedar and Vetiver.',
        4.29,
        21,
        NULL
      ),
(
        'Pure-Police-London-Femme-7366',
        'Pure Police London Femme Police',
        'Pure',
        'for women',
        NULL,
        'Drom',
        'Apple Blossom, Pear, Amalfi Lemon, Peach and Violet Leaf',
        'Green Notes, Freesia and Jasmine',
        'Musk, Virginia Cedar and Sandalwood',
        'floral,fruity,green,fresh,sweet',
        'Pure Police London FemmebyPoliceis a Floral Fruity fragrance for women.Pure Police London Femmewas launched in 2009. The nose behind this fragrance is Drom. Top notes are Apple Blossom, Pear, Amalfi Lemon, Peach and Violet Leaf; middle notes are Green Notes, Freesia and Jasmine; base notes are Musk, Virginia Cedar and Sandalwood.',
        3.53,
        15,
        NULL
      ),
(
        'Pure-Police-London-Homme-7367',
        'Pure Police London Homme Police',
        'Pure',
        'for men',
        NULL,
        'Drom',
        'Incense, Lavender and Ginger',
        'Amber, Cardamom and Patchouli',
        'Musk, Virginia Cedar and Sandalwood',
        'warm spicy,amber,woody,powdery,aromatic',
        'Pure Police London HommebyPoliceis a Amber Spicy fragrance for men.Pure Police London Hommewas launched in 2009. The nose behind this fragrance is Drom. Top notes are Incense, Lavender and Ginger; middle notes are Amber, Cardamom and Patchouli; base notes are Musk, Virginia Cedar and Sandalwood.',
        3.57,
        7,
        NULL
      ),
(
        'Pure-Police-Pure-DNA-Femme-7411',
        'Pure Police Pure DNA Femme Police',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Violet, Jasmine and Green Leaves',
        'Clove, Sandalwood and Patchouli',
        'Vanille, Musk and Virginia Cedar',
        'powdery,violet,woody,white floral,warm spicy',
        'Pure Police Pure DNA FemmebyPoliceis a Chypre Floral fragrance for women.Pure Police Pure DNA Femmewas launched in 2009. Top notes are Violet, Jasmine and Green Leaves; middle notes are Clove, Sandalwood and Patchouli; base notes are Vanille, Musk and Virginia Cedar.',
        3.47,
        34,
        NULL
      ),
(
        'Pure-Police-Pure-DNA-Homme-7410',
        'Pure Police Pure DNA Homme Police',
        'Pure',
        'for men',
        NULL,
        'Pierre-Constantin Guéros',
        'Virginia Cedar, Amalfi Lemon, Nutmeg, Cardamom and Bay Leaf',
        'Lavender, Cashmere Wood, Amber and Wormwood',
        'Tonka Bean, Vetyver, Patchouli, African Orange Flower, Incense and Sandalwood',
        'woody,aromatic,amber,lavender,warm spicy',
        'Pure Police Pure DNA HommebyPoliceis a Amber Spicy fragrance for men.Pure Police Pure DNA Hommewas launched in 2009. The nose behind this fragrance is Pierre-Constantin Guéros. Top notes are Virginia Cedar, Amalfi Lemon, Nutmeg, Cardamom and Bay Leaf; middle notes are Lavender, Cashmere Wood, Amber and Wormwood; base notes are Tonka Bean, Vetyver, Patchouli, African Orange Flower, Incense and Sandalwood.',
        4.25,
        20,
        NULL
      ),
(
        'Pure-Woman-4190',
        'Pure Woman Police',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Pear, Peach, Orange Blossom and Bergamot',
        'Jasmine, Tuberose and Rose',
        'Musk, Cedar, Oakmoss, Sandalwood and Vanilla',
        'white floral,woody,fruity,powdery,sweet',
        'Pure WomanbyPoliceis a Floral Fruity fragrance for women.Pure Womanwas launched in 2008. Top notes are Pear, Peach, Orange Blossom and Bergamot; middle notes are Jasmine, Tuberose and Rose; base notes are Musk, Cedar, Oakmoss, Sandalwood and Vanilla.',
        3.62,
        29,
        NULL
      ),
(
        'Shock-In-Scent-For-Men-53443',
        'Shock-In-Scent For Men Police',
        'Shock-In-Scent',
        'for men',
        NULL,
        NULL,
        'Bergamot, Pepper, Cardamom and Grapefruit',
        'Birch Leaf, Lavender, Cedar and Mint',
        'Patchouli, Tonka Bean and Musk',
        'fresh spicy,aromatic,woody,citrus,warm spicy',
        'Shock-In-Scent For MenbyPoliceis a Aromatic Fougere fragrance for men.Shock-In-Scent For Menwas launched in 2019. Top notes are Bergamot, Pepper, Cardamom and Grapefruit; middle notes are Birch Leaf, Lavender, Cedar and Mint; base notes are Patchouli, Tonka Bean and Musk.',
        3.79,
        38,
        NULL
      ),
(
        'Shock-In-Scent-For-Women-53442',
        'Shock-In-Scent For Women Police',
        'Shock-In-Scent',
        'for women',
        NULL,
        NULL,
        'Almond and Bergamot',
        'White Flowers, Jasmine and Ylang-Ylang',
        'Honey, Amber and Orris Root',
        'honey,sweet,white floral,floral,almond',
        'Shock-In-Scent For WomenbyPoliceis a Floral Fruity Gourmand fragrance for women.Shock-In-Scent For Womenwas launched in 2019. Top notes are Almond and Bergamot; middle notes are White Flowers, Jasmine and Ylang-Ylang; base notes are Honey, Amber and Orris Root.',
        4.02,
        289,
        NULL
      ),
(
        'Forbidden-for-Man-32613',
        'Forbidden for Man Police',
        'Forbidden',
        'for men',
        NULL,
        NULL,
        'Black Pepper and Bergamot',
        'Cardamom and Lavender',
        'Amber and Musk',
        'fresh spicy,warm spicy,aromatic,amber,lavender',
        'Forbidden for ManbyPoliceis a Aromatic Fougere fragrance for men.Forbidden for Manwas launched in 2016. Top notes are Black Pepper and Bergamot; middle notes are Cardamom and Lavender; base notes are Amber and Musk.',
        3.86,
        35,
        NULL
      ),
(
        'Forbidden-for-Woman-32580',
        'Forbidden for Woman Police',
        'Forbidden',
        'for women',
        NULL,
        NULL,
        'Almond, Almond Blossom and Lemon',
        'Caramel and Jasmine Sambac',
        'Vanilla and Sandalwood',
        'almond,sweet,vanilla,caramel,floral',
        'Forbidden for WomanbyPoliceis a Amber Vanilla fragrance for women.Forbidden for Womanwas launched in 2016. Top notes are Almond, Almond Blossom and Lemon; middle notes are Caramel and Jasmine Sambac; base notes are Vanilla and Sandalwood.',
        4.07,
        354,
        NULL
      ),
(
        'The-Sinner-23411',
        'The Sinner Police',
        'The',
        'for men',
        NULL,
        NULL,
        'Aromatic Spices and Herbal Notes',
        'Woodsy Notes',
        'Amber',
        'woody,green,amber,warm spicy',
        'The SinnerbyPoliceis a Amber Woody fragrance for men.The Sinnerwas launched in 2014. Top notes are Aromatic Spices and Herbal Notes; middle note is Woodsy Notes; base note is Amber.',
        3.35,
        49,
        NULL
      ),
(
        'The-Sinner-for-Women-28516',
        'The Sinner for Women Police',
        'The',
        'for women',
        NULL,
        NULL,
        'Black Currant and Apple',
        'Jasmine, Orange Blossom and Cyclamen',
        'Tonka Bean, Vanilla, Patchouli, Heliotrope and Cedar',
        'white floral,vanilla,fruity,woody,floral',
        'The Sinner for WomenbyPoliceis a Amber Floral fragrance for women.The Sinner for Womenwas launched in 2014. Top notes are Black Currant and Apple; middle notes are Jasmine, Orange Blossom and Cyclamen; base notes are Tonka Bean, Vanilla, Patchouli, Heliotrope and Cedar.',
        3.92,
        129,
        NULL
      ),
(
        'The-Illusionist-15179',
        'The Illusionist Police',
        'The',
        'for men',
        NULL,
        NULL,
        'Water Notes, Bergamot and Ivy',
        'Cedar, Sage and Iris',
        'Musk, Cashmere Wood and Moss',
        'woody,aquatic,citrus,musky,powdery',
        'The IllusionistbyPoliceis a Aromatic Fougere fragrance for men.The Illusionistwas launched in 2012. Top notes are Water Notes, Bergamot and Ivy; middle notes are Cedar, Sage and Iris; base notes are Musk, Cashmere Wood and Moss.',
        3.63,
        95,
        NULL
      ),
(
        'To-Be-12657',
        'To Be Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Grapefruit and Pepper',
        'Violet Leaf',
        'Amber, Virginia Cedar and Patchouli',
        'fresh spicy,ozonic,amber,citrus,woody',
        'To BebyPoliceis a Woody Spicy fragrance for men.To Bewas launched in 2011. Top notes are Grapefruit and Pepper; middle note is Violet Leaf; base notes are Amber, Virginia Cedar and Patchouli.',
        3.76,
        538,
        NULL
      ),
(
        'To-Be-Bad-Guy-59815',
        'To Be Bad Guy Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Blood Orange, Mint, Green Notes, Red Thyme and Nutmeg',
        'Green Apple, Sorbet, Geranium and White Flowers',
        'Caramel, Vanilla, Tonka Bean, Vetiver and Musk',
        'green,aromatic,fresh spicy,sweet,fruity',
        'To Be Bad GuybyPoliceis a Amber Fougere fragrance for men.To Be Bad Guywas launched in 2020. Top notes are Blood Orange, Mint, Green Notes, Red Thyme and Nutmeg; middle notes are Green Apple, Sorbet, Geranium and White Flowers; base notes are Caramel, Vanilla, Tonka Bean, Vetiver and Musk.',
        3.97,
        144,
        NULL
      ),
(
        'To-Be-Born-To-Shine-Men-74138',
        'To Be Born To Shine Men Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Apple, Mandarin Orange and Mint',
        'Cinnamon, Cardamom and Lavender',
        'Amber, Leather and Patchouli',
        'warm spicy,fruity,citrus,cinnamon,amber',
        'To Be Born To Shine MenbyPoliceis a Amber Fougere fragrance for men. This is a new fragrance.To Be Born To Shine Menwas launched in 2022. Top notes are Apple, Mandarin Orange and Mint; middle notes are Cinnamon, Cardamom and Lavender; base notes are Amber, Leather and Patchouli.',
        3.8,
        59,
        NULL
      ),
(
        'To-Be-Born-To-Shine-Woman-74139',
        'To Be Born To Shine Woman Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Cinnamon, Apple Blossom, Bergamot and Italian Mandarin',
        'Coffee, Jasmine, Plum and Damask Rose',
        'Vanilla, Patchouli, Sandalwood and Cashmere Wood',
        'warm spicy,vanilla,woody,coffee,powdery',
        'To Be Born To Shine WomanbyPoliceis a Amber Vanilla fragrance for women. This is a new fragrance.To Be Born To Shine Womanwas launched in 2022. Top notes are Cinnamon, Apple Blossom, Bergamot and Italian Mandarin; middle notes are Coffee, Jasmine, Plum and Damask Rose; base notes are Vanilla, Patchouli, Sandalwood and Cashmere Wood.',
        4.16,
        165,
        NULL
      ),
(
        'To-Be-Camouflage-31031',
        'To Be Camouflage Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Red Apple, Mint, Cardamom and Lemon',
        'Cinnamon, Rhubarb, Lavender, Ozonic notes, Solar Notes, Violet and Nutmeg',
        'Vanilla, Tonka Bean, Amber, Woodsy Notes, Haitian Vetiver, Cashmere Wood and Orange Blossom',
        'aromatic,green,vanilla,fruity,warm spicy',
        'To Be CamouflagebyPoliceis a Amber Fougere fragrance for men.To Be Camouflagewas launched in 2015. Top notes are Red Apple, Mint, Cardamom and Lemon; middle notes are Cinnamon, Rhubarb, Lavender, Ozonic notes, Solar Notes, Violet and Nutmeg; base notes are Vanilla, Tonka Bean, Amber, Woodsy Notes, Haitian Vetiver, Cashmere Wood and Orange Blossom.',
        3.65,
        168,
        NULL
      ),
(
        'To-Be-Camouflage-Pink-46210',
        'To Be Camouflage Pink Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Mango, Mandarin Orange, Green Apple, Grapefruit and Bergamot',
        'Orange Blossom, Jasmine, Cyclamen and Rose',
        'Vanilla, Hazelnut, Milk, Heliotrope, Tonka Bean, Patchouli and Cedar',
        'vanilla,sweet,woody,powdery,nutty',
        'To Be Camouflage PinkbyPoliceis a Floral Fruity Gourmand fragrance for women.To Be Camouflage Pinkwas launched in 2017. Top notes are Mango, Mandarin Orange, Green Apple, Grapefruit and Bergamot; middle notes are Orange Blossom, Jasmine, Cyclamen and Rose; base notes are Vanilla, Hazelnut, Milk, Heliotrope, Tonka Bean, Patchouli and Cedar.',
        3.91,
        45,
        NULL
      ),
(
        'To-Be-Exotic-Jungle-For-Man-55365',
        'To Be Exotic Jungle For Man Police',
        'To',
        'for men',
        NULL,
        'Olivier Pescheux',
        'Bergamot, Green Notes, Mandarin Orange and Pepper',
        'Apple and Rose',
        'Vetiver, Sandalwood, Cedar and Musk',
        'citrus,green,fruity,fresh spicy,woody',
        'To Be Exotic Jungle For ManbyPoliceis a Woody Spicy fragrance for men.To Be Exotic Jungle For Manwas launched in 2019. The nose behind this fragrance is Olivier Pescheux. Top notes are Bergamot, Green Notes, Mandarin Orange and Pepper; middle notes are Apple and Rose; base notes are Vetiver, Sandalwood, Cedar and Musk.',
        3.77,
        140,
        NULL
      ),
(
        'To-Be-Exotic-Jungle-For-Woman-55366',
        'To Be Exotic Jungle For Woman Police',
        'To',
        'for women',
        NULL,
        'Mathilde Bijaoui',
        'Plum, Black Currant and Lemon',
        'Heliotrope, Osmanthus and Jasmine',
        'Vanilla, Suede and Patchouli',
        'fruity,vanilla,powdery,floral,sweet',
        'To Be Exotic Jungle For WomanbyPoliceis a Amber Floral fragrance for women.To Be Exotic Jungle For Womanwas launched in 2019. The nose behind this fragrance is Mathilde Bijaoui. Top notes are Plum, Black Currant and Lemon; middle notes are Heliotrope, Osmanthus and Jasmine; base notes are Vanilla, Suede and Patchouli.',
        4.13,
        308,
        NULL
      ),
(
        'To-Be-Goodvibes-For-Her-65699',
        'To Be Goodvibes For Her Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Watery Notes, Sweet Orange, Grapefruit and Black Pepper',
        'Pear, Heliotrope and Peony',
        'Vanilla, Ambrarome and Patchouli',
        'vanilla,aquatic,citrus,sweet,fresh',
        'To Be Goodvibes For HerbyPoliceis a Floral Fruity fragrance for women.To Be Goodvibes For Herwas launched in 2021. Top notes are Watery Notes, Sweet Orange, Grapefruit and Black Pepper; middle notes are Pear, Heliotrope and Peony; base notes are Vanilla, Ambrarome and Patchouli.',
        4.07,
        158,
        NULL
      ),
(
        'To-Be-Goodvibes-For-Him-65700',
        'To Be Goodvibes For Him Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Clary Sage, Bergamot and Black Pepper',
        'Jasmine, Juniper and Magnolia',
        'Amberwood, Tobacco and Vetiver',
        'aromatic,fresh spicy,citrus,white floral,soft spicy',
        'To Be Goodvibes For HimbyPoliceis a Woody Aromatic fragrance for men.To Be Goodvibes For Himwas launched in 2021. Top notes are Clary Sage, Bergamot and Black Pepper; middle notes are Jasmine, Juniper and Magnolia; base notes are Amberwood, Tobacco and Vetiver.',
        3.23,
        26,
        NULL
      ),
(
        'To-Be-Green-69734',
        'To Be Green Police',
        'To',
        'for women and men',
        NULL,
        'Véronique Nyberg',
        'Cardamom, Mandarin Orange and Lemon',
        'Violet, Jasmine and Peony',
        'Vanilla, Cedar and Sandalwood',
        'citrus,warm spicy,aromatic,violet,powdery',
        'To Be GreenbyPoliceis a Woody Aromatic fragrance for women and men.To Be Greenwas launched in 2021. The nose behind this fragrance is Veronique Nyberg. Top notes are Cardamom, Mandarin Orange and Lemon; middle notes are Violet, Jasmine and Peony; base notes are Vanilla, Cedar and Sandalwood.',
        3.93,
        56,
        NULL
      ),
(
        'To-Be-Miss-Beat-42957',
        'To Be Miss Beat Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Black Currant, Lily-of-the-Valley and Coconut Blossom',
        'Heliotrope, White Peach and Rose',
        'Vanilla, Amber, Cashmere Wood and Woody Notes',
        'vanilla,woody,powdery,amber,fruity',
        'To Be Miss BeatbyPoliceis a Amber Floral fragrance for women.To Be Miss Beatwas launched in 2017. Top notes are Black Currant, Lily-of-the-Valley and Coconut Blossom; middle notes are Heliotrope, White Peach and Rose; base notes are Vanilla, Amber, Cashmere Wood and Woody Notes.',
        3.84,
        165,
        NULL
      ),
(
        'To-Be-Mr-Beat-42956',
        'To Be Mr Beat Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Apple, Bergamot and Cardamom',
        'Lavender, Sea Notes and Patchouli',
        'Vetiver, Leather and Cedar',
        'aromatic,woody,citrus,fresh spicy,warm spicy',
        'To Be Mr BeatbyPoliceis a Aromatic Fougere fragrance for men.To Be Mr Beatwas launched in 2017. Top notes are Apple, Bergamot and Cardamom; middle notes are Lavender, Sea Notes and Patchouli; base notes are Vetiver, Leather and Cedar.',
        3.69,
        67,
        NULL
      ),
(
        'To-Be-My-Avatar-for-Man-92457',
        'To Be My.Avatar for Man Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Guatemalan Cardamom, Italian Lemon and Resins',
        'Orange Blossom, Artemisia and Salt',
        'Guaiac Wood, Rum and Cacao',
        'woody,warm spicy,white floral,citrus,aromatic',
        'To Be My.Avatar for ManbyPoliceis a Woody Aromatic fragrance for men. This is a new fragrance.To Be My.Avatar for Manwas launched in 2024. Top notes are Guatemalan Cardamom, Italian Lemon and Resins; middle notes are Orange Blossom, Artemisia and Salt; base notes are Guaiac Wood, Rum and Cacao.',
        4.11,
        9,
        NULL
      ),
(
        'To-Be-My-Avatar-for-Woman-92458',
        'To Be My.Avatar for Woman Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Mango, Mandarin Orange and Italian Lemon',
        'Lotus, Musk, White Musk and Osmanthus',
        'Sugar Cane, Clearwood and Cedar',
        'sweet,fruity,floral,woody,tropical',
        'To Be My.Avatar for WomanbyPoliceis a Floral Fruity fragrance for women. This is a new fragrance.To Be My.Avatar for Womanwas launched in 2024. Top notes are Mango, Mandarin Orange and Italian Lemon; middle notes are Lotus, Musk, White Musk and Osmanthus; base notes are Sugar Cane, Clearwood and Cedar.',
        3.42,
        12,
        NULL
      ),
(
        'To-Be-Rebel-32579',
        'To Be Rebel Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Violet Leaf, Grapefruit, Black Pepper and Nutmeg',
        'Sea Notes, Orange Blossom and Sage',
        'White Musk, Amberwood and Vetiver',
        'aromatic,fresh spicy,marine,citrus,aquatic',
        'To Be RebelbyPoliceis a fragrance for men.To Be Rebelwas launched in 2016. Top notes are Violet Leaf, Grapefruit, Black Pepper and Nutmeg; middle notes are Sea Notes, Orange Blossom and Sage; base notes are White Musk, Amberwood and Vetiver.',
        3.82,
        105,
        NULL
      ),
(
        'To-Be-Rose-Blossom-32578',
        'To Be Rose Blossom Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Pear and Mandarin Orange',
        'Licorice, Heliotrope, Gardenia and Jasmine Sambac',
        'Vanilla, Cedar, Amber, Patchouli and Musk',
        'vanilla,powdery,soft spicy,sweet,woody',
        'To Be Rose BlossombyPoliceis a Chypre Floral fragrance for women.To Be Rose Blossomwas launched in 2016. Top notes are Pear and Mandarin Orange; middle notes are Licorice, Heliotrope, Gardenia and Jasmine Sambac; base notes are Vanilla, Cedar, Amber, Patchouli and Musk.',
        3.72,
        191,
        NULL
      ),
(
        'To-Be-Super-Pure-78330',
        'To Be Super (Pure) Police',
        'To',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Bigarane™ and Mandarin Orange',
        'Black Tea, Osmanthus and Mugane',
        'Driftwood, Davana and Woodsy Notes',
        'citrus,green,fresh spicy,floral,aromatic',
        'To Be Super (Pure)byPoliceis a fragrance for women and men. This is a new fragrance.To Be Super (Pure)was launched in 2022. Top notes are Bergamot, Bigarane™ and Mandarin Orange; middle notes are Black Tea, Osmanthus and Mugane; base notes are Driftwood, Davana and Woodsy Notes.',
        3.8,
        41,
        NULL
      ),
(
        'To-Be-Super-Natural-93511',
        'To Be Super[Natural] Police',
        'To',
        'for women and men',
        NULL,
        'Véronique Nyberg',
        'Lotus, Pink Pepper and Bergamot',
        'Freesia, Cardamom and Bourbon Geranium',
        'Lorenox, Cashmere Wood and Orcanox™',
        'floral,woody,aquatic,soft spicy,amber',
        'To Be Super[Natural]byPoliceis a Aromatic Spicy fragrance for women and men. This is a new fragrance.To Be Super[Natural]was launched in 2024. The nose behind this fragrance is Véronique Nyberg. Top notes are Lotus, Pink Pepper and Bergamot; middle notes are Freesia, Cardamom and Bourbon Geranium; base notes are Lorenox, Cashmere Wood and Orcanox™.',
        4,
        4,
        NULL
      ),
(
        'To-Be-Sweet-Girl-59814',
        'To Be Sweet Girl Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Black Currant, Orange and Bergamot',
        'Toffee, Cyclamen and Jasmine',
        'Patchouli, Cashmere Wood and Ambroxan',
        'sweet,fruity,woody,caramel,patchouli',
        'To Be Sweet GirlbyPoliceis a Floral Fruity Gourmand fragrance for women.To Be Sweet Girlwas launched in 2020. Top notes are Black Currant, Orange and Bergamot; middle notes are Toffee, Cyclamen and Jasmine; base notes are Patchouli, Cashmere Wood and Ambroxan.',
        3.79,
        178,
        NULL
      ),
(
        'To-Be-Tattooart-47138',
        'To Be Tattooart Police',
        'To',
        'for men',
        NULL,
        NULL,
        'Black Currant, Lemon Verbena and Cardamom',
        'Lavender and Clary Sage',
        'Tonka Bean, Ambroxan and Amberwood',
        'amber,aromatic,fruity,woody,warm spicy',
        'To Be TattooartbyPoliceis a Woody Aromatic fragrance for men.To Be Tattooartwas launched in 2017. Top notes are Black Currant, Lemon Verbena and Cardamom; middle notes are Lavender and Clary Sage; base notes are Tonka Bean, Ambroxan and Amberwood.',
        3.84,
        146,
        NULL
      ),
(
        'To-Be-Tattooart-47139',
        'To Be Tattooart Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Maple sap, Apple Blossom, Plum and Freesia',
        'Sweet Notes, Heliotrope, Violet, Wild Rose and Jasmine',
        'Marshmallow, Musk, Sandalwood and Cedar',
        'sweet,powdery,fruity,floral',
        'To Be TattooartbyPoliceis a Floral Fruity Gourmand fragrance for women.To Be Tattooartwas launched in 2017. Top notes are Maple sap, Apple Blossom, Plum and Freesia; middle notes are Sweet Notes, Heliotrope, Violet, Wild Rose and Jasmine; base notes are Marshmallow, Musk, Sandalwood and Cedar.',
        3.82,
        459,
        NULL
      ),
(
        'TO-BE-The-King-18799',
        'TO BE The King Police',
        'TO',
        'for men',
        NULL,
        'Pierre-Constantin Guéros',
        'Cardamom, Nutmeg, Cedar, Lemon and Bay Leaf',
        'Lavender, Cashmere Wood, Amber and Artemisia',
        'Woodsy Notes, Tonka Bean, Orange Blossom and Resins',
        'woody,amber,aromatic,fresh spicy,warm spicy',
        'TO BE The KingbyPoliceis a Amber Spicy fragrance for men.TO BE The Kingwas launched in 2013. The nose behind this fragrance is Pierre-Constantin Guéros. Top notes are Cardamom, Nutmeg, Cedar, Lemon and Bay Leaf; middle notes are Lavender, Cashmere Wood, Amber and Artemisia; base notes are Woodsy Notes, Tonka Bean, Orange Blossom and Resins.',
        3.62,
        282,
        NULL
      ),
(
        'TO-BE-The-Queen-18800',
        'TO BE The Queen Police',
        'TO',
        'for women',
        NULL,
        NULL,
        'Red Berries, Orange, Mandarin Orange and Petitgrain',
        'Pineapple, Peach, Jasmine and Violet',
        'Patchouli, Vanila, Musk and Cedar',
        'fruity,sweet,woody,patchouli,citrus',
        'TO BE The QueenbyPoliceis a Floral Fruity fragrance for women.TO BE The Queenwas launched in 2013. Top notes are Red Berries, Orange, Mandarin Orange and Petitgrain; middle notes are Pineapple, Peach, Jasmine and Violet; base notes are Patchouli, Vanila, Musk and Cedar.',
        3.63,
        487,
        NULL
      ),
(
        'To-Be-Woman-15180',
        'To Be Woman Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Granny Smith apple, Lime and Clementine',
        'Sweet Notes and White Flowers',
        'Musk and Woodsy Notes',
        'citrus,sweet,fruity,green,fresh',
        'To Be WomanbyPoliceis a Floral Fruity fragrance for women.To Be Womanwas launched in 2012. Top notes are Granny Smith apple, Lime and Clementine; middle notes are Sweet Notes and White Flowers; base notes are Musk and Woodsy Notes.',
        3.73,
        415,
        NULL
      ),
(
        'To-Be-Woman-Rose-Gold-Limited-Edition-69289',
        'To Be Woman Rose Gold Limited Edition Police',
        'To',
        'for women',
        NULL,
        NULL,
        'Granny Smith apple, Clementine and Lime',
        'Freesia, Jasmine and Sugar',
        'Cedar, Sandalwood and Musk',
        'woody,citrus,sweet,floral,powdery',
        'To Be Woman Rose Gold Limited EditionbyPoliceis a Floral Fruity fragrance for women.To Be Woman Rose Gold Limited Editionwas launched in 2021. Top notes are Granny Smith apple, Clementine and Lime; middle notes are Freesia, Jasmine and Sugar; base notes are Cedar, Sandalwood and Musk.',
        3.44,
        9,
        NULL
      ),
(
        'Police-Gold-Wings-7907',
        'Police Gold Wings Police',
        'Police',
        'for men',
        NULL,
        NULL,
        'Licorice, Bay Leaf, Nutmeg, Amalfi Lemon, Virginia Cedar and Cardamom',
        'Amber, Wormwood, Lavender, Cashmere Wood and Artemisia',
        'Patchouli, Tonka Bean, Resins, Orange Blossom, Vetyver and Sandalwood',
        'amber,aromatic,woody,fresh spicy,balsamic',
        'Police Gold WingsbyPoliceis a Amber Woody fragrance for men.Police Gold Wingswas launched in 2010. Top notes are Licorice, Bay Leaf, Nutmeg, Amalfi Lemon, Virginia Cedar and Cardamom; middle notes are Amber, Wormwood, Lavender, Cashmere Wood and Artemisia; base notes are Patchouli, Tonka Bean, Resins, Orange Blossom, Vetyver and Sandalwood.',
        3.91,
        23,
        NULL
      ),
(
        'Police-Titanium-Wings-13958',
        'Police Titanium Wings Police',
        'Police',
        'for men',
        NULL,
        NULL,
        'Watermelon, Green Accord, Mandarin Orange, Bergamot, Lemon and Apple',
        'Lily-of-the-Valley, Sea Notes, Rosemary, Palisander Rosewood, Jasmine and Cloves',
        'Musk, Vanilla, Cedar, Iris, Sandalwood, Amber and Tonka Bean',
        'citrus,woody,musky,aromatic,powdery',
        'Police Titanium WingsbyPoliceis a Woody Aromatic fragrance for men.Police Titanium Wingswas launched in 2011. Top notes are Watermelon, Green Accord, Mandarin Orange, Bergamot, Lemon and Apple; middle notes are Lily-of-the-Valley, Sea Notes, Rosemary, Palisander Rosewood, Jasmine and Cloves; base notes are Musk, Vanilla, Cedar, Iris, Sandalwood, Amber and Tonka Bean.',
        3.8,
        15,
        NULL
      ),
(
        'Silver-Wings-19205',
        'Silver Wings Police',
        'Silver',
        'for men',
        NULL,
        'Pierre-Constantin Guéros',
        'Lemon, Coriander, Violet, Apple Blossom and Nutmeg',
        'Woody Notes, Geranium, Lavender and Sage',
        'Amber, Woody Notes, White Musk and Tonka Bean',
        'citrus,aromatic,violet,powdery,fresh',
        'Silver WingsbyPoliceis a Woody Aromatic fragrance for men.Silver Wingswas launched in 2006. The nose behind this fragrance is Pierre-Constantin Guéros. Top notes are Lemon, Coriander, Violet, Apple Blossom and Nutmeg; middle notes are Woody Notes, Geranium, Lavender and Sage; base notes are Amber, Woody Notes, White Musk and Tonka Bean.',
        3.83,
        12,
        NULL
      ),
(
        'Wings-Blue-31088',
        'Wings Blue Police',
        'Wings',
        'for men',
        NULL,
        NULL,
        'Granny Smith apple, Bergamot and Black Pepper',
        'Orange Blossom, Cardamom and Nutmeg',
        'Tonka Bean, Vanilla, Cedar and Musk',
        'vanilla,white floral,sweet,fresh spicy,citrus',
        'Wings BluebyPoliceis a Amber Spicy fragrance for men.Wings Bluewas launched in 2015. Top notes are Granny Smith apple, Bergamot and Black Pepper; middle notes are Orange Blossom, Cardamom and Nutmeg; base notes are Tonka Bean, Vanilla, Cedar and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Wings-Femme-1530',
        'Wings Femme Police',
        'Wings',
        'for women',
        NULL,
        'Domitille Michalon Bertier',
        'Black Currant, Red Currant and Pear',
        'Peony, Rose and Iris',
        'Musk, Sandalwood and Vanille',
        'fruity,floral,rose,fresh,powdery',
        'Wings FemmebyPoliceis a Floral Green fragrance for women.Wings Femmewas launched in 2006. The nose behind this fragrance is Domitille Michalon Bertier. Top notes are Black Currant, Red Currant and Pear; middle notes are Peony, Rose and Iris; base notes are Musk, Sandalwood and Vanille.',
        3.89,
        44,
        NULL
      ),
(
        'Wings-Pour-Homme-1529',
        'Wings Pour Homme Police',
        'Wings',
        'for men',
        NULL,
        NULL,
        'Violet Leaf and Lemon',
        'Nutmeg, Lavender, Coriander and Geranium',
        'Sandalwood, Musk, Tonka Bean and Amber',
        'fresh spicy,aromatic,powdery,woody,lavender',
        'Wings Pour HommebyPoliceis a Amber Fougere fragrance for men.Wings Pour Hommewas launched in 2008. Top notes are Violet Leaf and Lemon; middle notes are Nutmeg, Lavender, Coriander and Geranium; base notes are Sandalwood, Musk, Tonka Bean and Amber.',
        3.93,
        41,
        NULL
      ),
(
        'Eau-Dadette-40890',
        'Eau Dadette Santi Burgas',
        'Eau',
        'for women and men',
        NULL,
        'Santi Burgas',
        NULL,
        NULL,
        NULL,
        'amber,powdery,woody,sweet,vanilla',
        'Eau DadettebySanti Burgasis a Floral fragrance for women and men.Eau Dadettewas launched in 2016. The nose behind this fragrance is Santi Burgas.',
        5,
        6,
        NULL
      ),
(
        'Eau-Dadette-Attar-Perfume-51496',
        'Eau Dadette Attar Perfume Santi Burgas',
        'Eau',
        'for women and men',
        NULL,
        'Santi Burgas',
        NULL,
        NULL,
        NULL,
        'amber,powdery,sweet,fruity,vanilla',
        'Eau Dadette Attar PerfumebySanti Burgasis a Amber Floral fragrance for women and men.Eau Dadette Attar Perfumewas launched in 2018. The nose behind this fragrance is Santi Burgas.',
        4.78,
        18,
        NULL
      ),
(
        'Santi-Burgas-Eau-de-Parfum-28926',
        'Santi Burgas Eau de Parfum Santi Burgas',
        'Santi',
        'for women and men',
        NULL,
        'Santi Burgas',
        'Mandarin Orange, Thyme, Sicilian Bergamot and Orange',
        'Leather, Geranium and Violet',
        'Benzoin, Amber, Patchouli, Madagascar Vanilla and Virginian Cedar',
        'amber,aromatic,fresh spicy,citrus,vanilla',
        'Santi Burgas Eau de ParfumbySanti Burgasis a Leather fragrance for women and men.Santi Burgas Eau de Parfumwas launched in 2010. The nose behind this fragrance is Santi Burgas. Top notes are Mandarin Orange, Thyme, Sicilian Bergamot and Orange; middle notes are Leather, Geranium and Violet; base notes are Benzoin, Amber, Patchouli, Madagascar Vanilla and Virginian Cedar.',
        4,
        16,
        NULL
      ),
(
        'LOANT-18051',
        'LOANT Santi Burgas',
        'LOANT',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'musky,amber,powdery,woody,fresh spicy',
        'LOANTbySanti Burgasis a fragrance for women and men.LOANTwas launched in 2013. LOANT was created by Blanca Dalmau and Chris Maurice.',
        3.76,
        37,
        NULL
      ),
(
        'LOBITT-18050',
        'LOBITT Santi Burgas',
        'LOBITT',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'citrus',
        'LOBITTbySanti Burgasis a Citrus Aromatic fragrance for women and men.LOBITTwas launched in 2013. LOBITT was created by Blanca Dalmau and Chris Maurice.',
        3.89,
        27,
        NULL
      ),
(
        'LOENCE-28943',
        'LOENCE Santi Burgas',
        'LOENCE',
        'for women and men',
        NULL,
        NULL,
        'Juniper Berries',
        'Cashmere Wood, Patchouli and Virginian Cedar',
        'Olibanum',
        'woody,amber,aromatic,fresh spicy,balsamic',
        'LOENCEbySanti Burgasis a Amber Woody fragrance for women and men.LOENCEwas launched in 2014. LOENCE was created by Blanca Dalmau, Santi Burgas and Chris Maurice. Top note is Juniper Berries; middle notes are Cashmere Wood, Patchouli and Virginian Cedar; base note is Olibanum.',
        3.96,
        26,
        NULL
      ),
(
        'LOJAZZ-18045',
        'LOJAZZ Santi Burgas',
        'LOJAZZ',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'white floral,floral,violet,citrus,powdery',
        'LOJAZZbySanti Burgasis a Floral fragrance for women and men.LOJAZZwas launched in 2013. LOJAZZ was created by Blanca Dalmau and Chris Maurice.',
        3.88,
        26,
        NULL
      ),
(
        'LOMUSK-18055',
        'LOMUSK Santi Burgas',
        'LOMUSK',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'musky,sweet,floral,powdery,fruity',
        'LOMUSKbySanti Burgasis a fragrance for women and men.LOMUSKwas launched in 2013. LOMUSK was created by Blanca Dalmau and Chris Maurice.',
        4.09,
        23,
        NULL
      ),
(
        'LOROSE-18048',
        'LOROSE Santi Burgas',
        'LOROSE',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'rose,fresh spicy,aromatic,patchouli,floral',
        'LOROSEbySanti Burgasis a Chypre Floral fragrance for women and men.LOROSEwas launched in 2013. LOROSE was created by Blanca Dalmau and Chris Maurice.',
        4.04,
        27,
        NULL
      ),
(
        'LOTREE-18053',
        'LOTREE Santi Burgas',
        'LOTREE',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'woody,leather,animalic',
        'LOTREEbySanti Burgasis a Woody fragrance for women and men.LOTREEwas launched in 2013. LOTREE was created by Blanca Dalmau and Chris Maurice.',
        3.95,
        22,
        NULL
      ),
(
        'LOVANN-18052',
        'LOVANN Santi Burgas',
        'LOVANN',
        'for women and men',
        NULL,
        'Blanca Dalmau',
        NULL,
        NULL,
        NULL,
        'vanilla,honey,sweet,fruity,powdery',
        'LOVANNbySanti Burgasis a Amber Vanilla fragrance for women and men.LOVANNwas launched in 2013. LOVANN was created by Blanca Dalmau and Chris Maurice.',
        4.11,
        64,
        NULL
      ),
(
        'Palindrome-I-43951',
        'Palindrome I Santi Burgas',
        'Palindrome',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'amber,balsamic,sweet,warm spicy,powdery',
        'Palindrome IbySanti Burgasis a Amber fragrance for women and men.Palindrome Iwas launched in 2017. Palindrome I was created by Santi Burgas and Rodrigo Flores-Roux.',
        4.33,
        87,
        NULL
      ),
(
        'Palindrome-II-43952',
        'Palindrome II Santi Burgas',
        'Palindrome',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'warm spicy,patchouli,woody,musky,amber',
        'Palindrome IIbySanti Burgasis a Citrus Aromatic fragrance for women and men.Palindrome IIwas launched in 2017. Palindrome II was created by Santi Burgas and Rodrigo Flores-Roux.',
        3.88,
        34,
        NULL
      ),
(
        'Palindrome-III-46636',
        'Palindrome III Santi Burgas',
        'Palindrome',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'floral,fruity,rose,herbal,woody',
        'Palindrome IIIbySanti Burgasis a Amber Floral fragrance for women and men.Palindrome IIIwas launched in 2017. Palindrome III was created by Rodrigo Flores-Roux and Santi Burgas.',
        4.05,
        39,
        NULL
      ),
(
        'Aroma-de-Hormiguero-51497',
        'Aroma de Hormiguero Santi Burgas',
        'Aroma',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'earthy,aromatic,woody,balsamic,aquatic',
        'Aroma de HormiguerobySanti Burgasis a Woody Chypre fragrance for women and men.Aroma de Hormiguerowas launched in 2018. Aroma de Hormiguero was created by Rodrigo Flores-Roux and Santi Burgas.',
        4.05,
        44,
        NULL
      ),
(
        'New-York-City-51498',
        'New York City Santi Burgas',
        'New',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'citrus,white floral,floral,aromatic,fresh spicy',
        'New York CitybySanti Burgasis a Citrus Aromatic fragrance for women and men.New York Citywas launched in 2018. The nose behind this fragrance is Rodrigo Flores-Roux.',
        4.29,
        35,
        NULL
      ),
(
        'Torroella-de-Montgri-51500',
        'Torroella de Montgrí Santi Burgas',
        'Torroella',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy',
        'Torroella de MontgríbySanti Burgasis a Woody Aromatic fragrance for women and men.Torroella de Montgríwas launched in 2018. Torroella de Montgrí was created by Rodrigo Flores-Roux and Santi Burgas.',
        4.12,
        59,
        NULL
      ),
(
        'Eau-Dada-32370',
        'Eau Dada Santi Burgas',
        'Eau',
        'for women and men',
        NULL,
        'Rosendo Mateu',
        NULL,
        NULL,
        NULL,
        'warm spicy,patchouli,amber,woody,balsamic',
        'Eau DadabySanti Burgasis a Amber Woody fragrance for women and men.Eau Dadawas launched in 2015. Eau Dada was created by Rosendo Mateu and Santi Burgas.',
        3.71,
        51,
        NULL
      ),
(
        'Egnaro-30613',
        'Egnaro Santi Burgas',
        'Egnaro',
        'for women and men',
        NULL,
        'Santi Burgas',
        NULL,
        NULL,
        NULL,
        'citrus,musky,animalic,anis,warm spicy',
        'EgnarobySanti Burgasis a Woody Spicy fragrance for women and men.Egnarowas launched in 2015. The nose behind this fragrance is Santi Burgas.',
        3.38,
        61,
        NULL
      ),
(
        'Flaming-Red-30615',
        'Flaming Red Santi Burgas',
        'Flaming',
        'for women and men',
        NULL,
        'Chris Maurice',
        NULL,
        NULL,
        NULL,
        'rose,oud,tropical,iris,fruity',
        'Flaming RedbySanti Burgasis a Amber Floral fragrance for women and men.Flaming Redwas launched in 2015. Flaming Red was created by Santi Burgas and Chris Maurice.',
        3.54,
        85,
        NULL
      ),
(
        'Miss-Betty-Vair-30614',
        'Miss Betty Vair Santi Burgas',
        'Miss',
        'for women and men',
        NULL,
        'Santi Burgas',
        NULL,
        NULL,
        NULL,
        'earthy,woody,musky,mossy,fresh spicy',
        'Miss Betty VairbySanti Burgasis a Woody Spicy fragrance for women and men.Miss Betty Vairwas launched in 2015. The nose behind this fragrance is Santi Burgas.',
        3.69,
        51,
        NULL
      ),
(
        'OIKB-37464',
        'ÔIKB Santi Burgas',
        'ÔIKB',
        'for women and men',
        NULL,
        'Santi Burgas',
        NULL,
        NULL,
        NULL,
        'iris,leather,powdery,musky,lavender',
        'ÔIKBbySanti Burgasis a Amber Spicy fragrance for women and men.ÔIKBwas launched in 2016. The nose behind this fragrance is Santi Burgas.',
        4.34,
        154,
        NULL
      ),
(
        'Oud-de-Burgas-30616',
        'Oud de Burgas Santi Burgas',
        'Oud',
        'for women and men',
        NULL,
        'Chris Maurice',
        NULL,
        NULL,
        NULL,
        'woody,oud,earthy,warm spicy,powdery',
        'Oud de BurgasbySanti Burgasis a Amber Woody fragrance for women and men.Oud de Burgaswas launched in 2015. Oud de Burgas was created by Santi Burgas and Chris Maurice.',
        3.83,
        78,
        NULL
      ),
(
        'Verdant-Delirivm-74675',
        'Verdant Delirivm Santi Burgas',
        'Verdant',
        'for women and men',
        NULL,
        'Santi Burgas',
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic,green,rose',
        'Verdant DelirivmbySanti Burgasis a Floral Fruity fragrance for women and men. This is a new fragrance.Verdant Delirivmwas launched in 2022. The nose behind this fragrance is Santi Burgas.',
        3.7,
        20,
        NULL
      ),
(
        'Acqua-Della-Regina-73280',
        'Acqua Della Regina Santa Maria Novella',
        'Acqua',
        'for women',
        NULL,
        NULL,
        'Citruses, Neroli and Petitgrain',
        'Neroli, Rosemary, Lavender and Cloves',
        'Musk and Patchouli',
        'citrus,aromatic,fresh spicy,fresh,lavender',
        'Acqua Della ReginabySanta Maria Novellais a fragrance for women. Top notes are Citruses, Neroli and Petitgrain; middle notes are Neroli, Rosemary, Lavender and Cloves; base notes are Musk and Patchouli.',
        3.78,
        185,
        NULL
      ),
(
        'Acqua-di-Colonia-11417',
        'Acqua di Colonia Santa Maria Novella',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Neroli, Amalfi Lemon and Tangerine',
        'Lavender, Petitgrain, Clove and Rosemary',
        'Benzoin',
        'citrus,aromatic,fresh spicy,warm spicy,lavender',
        'Acqua di ColoniabySanta Maria Novellais a Citrus Aromatic fragrance for women and men.Acqua di Coloniawas launched in 1533. Top notes are Bergamot, Neroli, Amalfi Lemon and Tangerine; middle notes are Lavender, Petitgrain, Clove and Rosemary; base note is Benzoin.',
        4.3,
        212,
        NULL
      ),
(
        'Acqua-di-Colonia-Cinquanta-31439',
        'Acqua di Colonia Cinquanta Santa Maria Novella',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Gardenia, Tiare Flower and Orange Blossom',
        'Green Tea, Woody Notes and Cashmere Wood',
        'White Musk, Woody Notes and Amber',
        'white floral,musky,woody,green,animalic',
        'Acqua di Colonia CinquantabySanta Maria Novellais a Floral Woody Musk fragrance for women and men.Acqua di Colonia Cinquantawas launched in 2015. Top notes are Gardenia, Tiare Flower and Orange Blossom; middle notes are Green Tea, Woody Notes and Cashmere Wood; base notes are White Musk, Woody Notes and Amber.',
        4.27,
        178,
        NULL
      ),
(
        'Acqua-di-Colonia-Lana-46925',
        'Acqua di Colonia Lana Santa Maria Novella',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,rose,aromatic,musky',
        'Acqua di Colonia LanabySanta Maria Novellais a Woody fragrance for women and men.Acqua di Colonia Lanawas launched in 2017.',
        4.09,
        86,
        NULL
      ),
(
        'Acqua-di-Cuba-11472',
        'Acqua di Cuba Santa Maria Novella',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Bitter Orange, Amalfi Lemon, Bergamot and Lavender',
        'White Honey, Tobacco, Spices and Clary Sage',
        'Leather, Vanille and Woody Notes',
        'citrus,sweet,honey,tobacco,aromatic',
        'Acqua di CubabySanta Maria Novellais a Aromatic Spicy fragrance for women and men.Acqua di Cubawas launched in 1998. Top notes are Bitter Orange, Amalfi Lemon, Bergamot and Lavender; middle notes are White Honey, Tobacco, Spices and Clary Sage; base notes are Leather, Vanille and Woody Notes.',
        4.16,
        201,
        NULL
      ),
(
        'Acqua-di-Sicilia-11473',
        'Acqua di Sicilia Santa Maria Novella',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Amalfi Lemon, Bergamot, Mandarin Orange, Neroli, Tangerine and Mango',
        'Petitgrain, Rosemary, Lavender and Clove',
        'Benzoin and Cypress',
        'citrus,aromatic,fresh spicy,woody',
        'Acqua di SiciliabySanta Maria Novellais a Citrus Aromatic fragrance for women and men.Acqua di Siciliawas launched in 1997. Top notes are Amalfi Lemon, Bergamot, Mandarin Orange, Neroli, Tangerine and Mango; middle notes are Petitgrain, Rosemary, Lavender and Clove; base notes are Benzoin and Cypress.',
        4.29,
        101,
        NULL
      ),
(
        'Alba-di-Seoul-17976',
        'Alba di Seoul Santa Maria Novella',
        'Alba',
        'for women and men',
        NULL,
        NULL,
        'Green Notes',
        'Pine Tree',
        'Woody Notes and Oriental notes',
        'woody,green,aromatic,warm spicy,amber',
        'Alba di SeoulbySanta Maria Novellais a Amber Woody fragrance for women and men.Alba di Seoulwas launched in 2012. Top note is Green Notes; middle note is Pine Tree; base notes are Woody Notes and Oriental notes.',
        3.97,
        117,
        NULL
      ),
(
        'Ambra-11463',
        'Ambra Santa Maria Novella',
        'Ambra',
        'for women and men',
        NULL,
        NULL,
        'Bitter Orange, Bergamot, Neroli and Amalfi Lemon',
        'Lavender, Rosemary and Jasmine',
        'Birch, Amber, Benzoin and Sandalwood',
        'amber,citrus,leather,woody,smoky',
        'AmbrabySanta Maria Novellais a Amber fragrance for women and men.Ambrawas launched in 1828. Top notes are Bitter Orange, Bergamot, Neroli and Amalfi Lemon; middle notes are Lavender, Rosemary and Jasmine; base notes are Birch, Amber, Benzoin and Sandalwood.',
        3.69,
        61,
        NULL
      ),
(
        'Angeli-di-Firenze-73661',
        'Angeli di Firenze Santa Maria Novella',
        'Angeli',
        'for women and men',
        NULL,
        NULL,
        'Jasmine, Cyclamen and Ylang-Ylang',
        'Melon, Iris, Peach and Black Currant',
        'White Musk, Vanilla and Precious Woods',
        'fruity,powdery,ozonic,aquatic,fresh',
        'Angeli di FirenzebySanta Maria Novellais a Floral Fruity fragrance for women and men.Angeli di Firenzewas launched in 2006. Top notes are Jasmine, Cyclamen and Ylang-Ylang; middle notes are Melon, Iris, Peach and Black Currant; base notes are White Musk, Vanilla and Precious Woods.',
        3.94,
        261,
        NULL
      ),
(
        'Angels-of-Florence-11420',
        'Angels of Florence Santa Maria Novella',
        'Angels',
        'for women',
        NULL,
        NULL,
        'Lime, Gardenia, African Orange Flower, Geranium, Lilac, Jasmine, Rose, Ylang-Ylang and Cyclamen',
        'Violet Leaf, Melon, Peach, Cassis and Plum',
        'Vetiver, Musk, Vanille and Sandalwood',
        'white floral,fruity,ozonic,aromatic,sweet',
        'Angels of FlorencebySanta Maria Novellais a Floral fragrance for women.Angels of Florencewas launched in 2006. Top notes are Lime, Gardenia, African Orange Flower, Geranium, Lilac, Jasmine, Rose, Ylang-Ylang and Cyclamen; middle notes are Violet Leaf, Melon, Peach, Cassis and Plum; base notes are Vetiver, Musk, Vanille and Sandalwood.',
        3.98,
        239,
        NULL
      ),
(
        'Cala-Rossa-25479',
        'Cala Rossa Santa Maria Novella',
        'Cala',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,herbal,lavender,amber',
        'Cala RossabySanta Maria Novellais a Aromatic Green fragrance for women and men.Cala Rossawas launched in 2014.',
        4.22,
        131,
        NULL
      ),
(
        'Calicantus-11474',
        'Calicantus Santa Maria Novella',
        'Calicantus',
        'for women',
        NULL,
        NULL,
        'Ylang-Ylang, African Orange Flower and Bergamot',
        'Carnation, Narcissus, Jasmine and Powdery Notes',
        'oak moss, Woodsy Notes, Amber, Peach and Vanilla',
        'yellow floral,woody,floral,white floral,mossy',
        'CalicantusbySanta Maria Novellais a Chypre Floral fragrance for women.Calicantuswas launched in 1999. Top notes are Ylang-Ylang, African Orange Flower and Bergamot; middle notes are Carnation, Narcissus, Jasmine and Powdery Notes; base notes are oak moss, Woodsy Notes, Amber, Peach and Vanilla.',
        4.02,
        52,
        NULL
      ),
(
        'Caprifoglio-Honeysuckle-11465',
        'Caprifoglio (Honeysuckle) Santa Maria Novella',
        'Caprifoglio',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Jasmine, Amalfi Lemon and Orange',
        'Honeysuckle, White Honey, Ylang-Ylang, Magnolia and Lotus',
        'oak moss and Benzoin',
        'citrus,white floral,floral,yellow floral,sweet',
        'Caprifoglio (Honeysuckle)bySanta Maria Novellais a Chypre Floral fragrance for women and men.Caprifoglio (Honeysuckle)was launched in 1997. Top notes are Bergamot, Jasmine, Amalfi Lemon and Orange; middle notes are Honeysuckle, White Honey, Ylang-Ylang, Magnolia and Lotus; base notes are oak moss and Benzoin.',
        3.89,
        114,
        NULL
      ),
(
        'Citta-di-Kyoto-11419',
        'Citta di Kyoto Santa Maria Novella',
        'Citta',
        'for women',
        NULL,
        NULL,
        'Hawthorn, Hyacinth, Bergamot, Ylang-Ylang, Orange, Jasmine and Rose',
        'Iris, Cypress, Birch, Lotus, Lavender, Plum, Peach and Cinnamon',
        'Incense, Ebony Wood, Guaiac Wood, Orris, Virginia Cedar, Sandalwood, Musk, Amber, Vanille and Patchouli',
        'woody,powdery,iris,floral,smoky',
        'Citta di KyotobySanta Maria Novellais a Floral Woody Musk fragrance for women.Citta di Kyotowas launched in 2005. Top notes are Hawthorn, Hyacinth, Bergamot, Ylang-Ylang, Orange, Jasmine and Rose; middle notes are Iris, Cypress, Birch, Lotus, Lavender, Plum, Peach and Cinnamon; base notes are Incense, Ebony Wood, Guaiac Wood, Orris, Virginia Cedar, Sandalwood, Musk, Amber, Vanille and Patchouli.',
        4.12,
        217,
        NULL
      ),
(
        'Colonia-Russa-11475',
        'Colonia Russa Santa Maria Novella',
        'Colonia',
        'for men',
        NULL,
        NULL,
        'Bergamot, Neroli, Amalfi Lemon, Bitter Orange and Rose',
        'Petitgrain, Lavender, Lemon Verbena, Clove and Rosemary',
        'Musk, Castoreum, Tolu Balsam, Civetta and Benzoin',
        'citrus,aromatic,fresh spicy,musky,warm spicy',
        'Colonia RussabySanta Maria Novellais a Aromatic Fougere fragrance for men.Colonia Russawas launched in 1913. Top notes are Bergamot, Neroli, Amalfi Lemon, Bitter Orange and Rose; middle notes are Petitgrain, Lavender, Lemon Verbena, Clove and Rosemary; base notes are Musk, Castoreum, Tolu Balsam, Civetta and Benzoin.',
        4.1,
        120,
        NULL
      ),
(
        'Eva-11421',
        'Eva Santa Maria Novella',
        'Eva',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Lemon',
        'Pepper and Spicy Notes',
        'Vetiver and Woody Notes',
        'citrus,woody,aromatic,fresh spicy,warm spicy',
        'EvabySanta Maria Novellais a Citrus Aromatic fragrance for women and men.Evawas launched in 2002. Top notes are Bergamot and Lemon; middle notes are Pepper and Spicy Notes; base notes are Vetiver and Woody Notes.',
        3.84,
        81,
        NULL
      ),
(
        'Fieno-Hay-11466',
        'Fieno (Hay) Santa Maria Novella',
        'Fieno',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Citruses',
        'Coumarin, Lavender, Hawthorn, Myrtle, Rose and Jasmine',
        'Hay, Benzoin, Vanille, Vetiver and Sandalwood',
        'aromatic,fresh spicy,vanilla,floral,herbal',
        'Fieno (Hay)bySanta Maria Novellais a Amber Floral fragrance for women and men.Fieno (Hay)was launched in 1886. Top notes are Bergamot and Citruses; middle notes are Coumarin, Lavender, Hawthorn, Myrtle, Rose and Jasmine; base notes are Hay, Benzoin, Vanille, Vetiver and Sandalwood.',
        3.95,
        112,
        NULL
      );
