
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Lucky-Number-15-20465',
        'Lucky Number 15 Dzintars',
        'Lucky',
        'for men',
        NULL,
        NULL,
        'Mint, Violet, Sea Notes, Orris Root, Mandarin Leaf and Citruses',
        'Galbanum, Thuja, Gardenia, Vetiver, Artemisia and Incense',
        'Pomegranate Seed, Mahogany, Musk, Ambergris and Sandalwood',
        'woody,aromatic,green,fresh spicy,powdery',
        'Lucky Number 15byDzintarsis a Woody Aquatic fragrance for men.Lucky Number 15was launched in 2004. Top notes are Mint, Violet, Sea Notes, Orris Root, Mandarin Leaf and Citruses; middle notes are Galbanum, Thuja, Gardenia, Vetiver, Artemisia and Incense; base notes are Pomegranate Seed, Mahogany, Musk, Ambergris and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Lucky-Number-15-20466',
        'Lucky Number 15 Dzintars',
        'Lucky',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,sweet,warm spicy,amber,fresh',
        'Lucky Number 15byDzintarsis a Floral fragrance for women.Lucky Number 15was launched in 2004.',
        2,
        1,
        NULL
      ),
(
        'Lucky-Number-3-20446',
        'Lucky Number 3 Dzintars',
        'Lucky',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Bergamot and Lemon',
        'Honeysuckle, Violet Leaf, Coriander and Clary Sage',
        'Crystal Amber, Sandalwood and Black Pepper',
        'citrus,aromatic,fresh spicy,soft spicy,woody',
        'Lucky Number 3byDzintarsis a Woody Aromatic fragrance for men.Lucky Number 3was launched in 2004. Top notes are Grapefruit, Bergamot and Lemon; middle notes are Honeysuckle, Violet Leaf, Coriander and Clary Sage; base notes are Crystal Amber, Sandalwood and Black Pepper.',
        4,
        1,
        NULL
      ),
(
        'Lucky-Number-3-20447',
        'Lucky Number 3 Dzintars',
        'Lucky',
        'for women',
        NULL,
        NULL,
        'White Tea, Magnolia and Lily',
        'Orchid, Melon and Honey',
        'Pink Pepper, Geranium, Amber and Lime',
        'citrus,fruity,fresh,sweet,floral',
        'Lucky Number 3byDzintarsis a Floral Fruity fragrance for women.Lucky Number 3was launched in 2004. Top notes are White Tea, Magnolia and Lily; middle notes are Orchid, Melon and Honey; base notes are Pink Pepper, Geranium, Amber and Lime.',
        3.67,
        3,
        NULL
      ),
(
        'Lucky-Number-5-92110',
        'Lucky Number 5 Dzintars',
        'Lucky',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,amber,vanilla,soft spicy,animalic',
        'Lucky Number 5byDzintarsis a Amber Floral fragrance for women.Lucky Number 5was launched in 2004.',
        NULL,
        NULL,
        NULL
      ),
(
        'Lucky-Number-5-92340',
        'Lucky Number 5 Dzintars',
        'Lucky',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,cinnamon,musky,patchouli,tobacco',
        'Lucky Number 5byDzintarsis a Woody Spicy fragrance for men.Lucky Number 5was launched in 2004.',
        5,
        2,
        NULL
      ),
(
        'Lucky-Number-7-20286',
        'Lucky Number 7 Dzintars',
        'Lucky',
        'for women',
        NULL,
        NULL,
        'Lily of the Valley, Tuberose and Freesia',
        'Violet, Iris and Tea Rose',
        'Pink Pepper, Sandalwood and White Musk',
        'violet,powdery,iris,floral,woody',
        'Lucky Number 7byDzintarsis a Floral Green fragrance for women.Lucky Number 7was launched in 2004. Top notes are Lily of the Valley, Tuberose and Freesia; middle notes are Violet, Iris and Tea Rose; base notes are Pink Pepper, Sandalwood and White Musk.',
        3.5,
        8,
        NULL
      ),
(
        'Lucky-Number-7-20459',
        'Lucky Number 7 Dzintars',
        'Lucky',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,fresh spicy,floral,warm spicy',
        'Lucky Number 7byDzintarsis a Woody Floral Musk fragrance for men.Lucky Number 7was launched in 2004.',
        3,
        2,
        NULL
      ),
(
        'Lucky-Number-9-92111',
        'Lucky Number 9 Dzintars',
        'Lucky',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,musky,woody,powdery',
        'Lucky Number 9byDzintarsis a Floral Woody Musk fragrance for women.Lucky Number 9was launched in 2004.',
        NULL,
        NULL,
        NULL
      ),
(
        'Elegant-Man-12367',
        'Elegant Man Dzintars',
        'Elegant',
        'for men',
        NULL,
        NULL,
        'Blood Orange, Bergamot, Amalfi Lemon and Ginger',
        'Vanille, Lavender, Cardamom, Basil, Vetiver and Pepper',
        'Cashmere Wood, Sandalwood, Tonka Bean and Amber',
        'citrus,woody,aromatic,amber,vanilla',
        'Elegant ManbyDzintarsis a Woody Aromatic fragrance for men.Elegant Manwas launched in 2010. Top notes are Blood Orange, Bergamot, Amalfi Lemon and Ginger; middle notes are Vanille, Lavender, Cardamom, Basil, Vetiver and Pepper; base notes are Cashmere Wood, Sandalwood, Tonka Bean and Amber.',
        3.6,
        20,
        NULL
      ),
(
        'Strong-Man-12368',
        'Strong Man Dzintars',
        'Strong',
        'for men',
        NULL,
        NULL,
        'Saffron, Geranium, Pink Pepper and Bergamot',
        'Leather, Clary Sage, Spices, Patchouli and Brazilian Rosewood',
        'Osmanthus, Cypress, Virginia Cedar, Anise, Nutmeg and Musk',
        'warm spicy,fresh spicy,aromatic,leather,woody',
        'Strong ManbyDzintarsis a Amber Woody fragrance for men.Strong Manwas launched in 2010. Top notes are Saffron, Geranium, Pink Pepper and Bergamot; middle notes are Leather, Clary Sage, Spices, Patchouli and Brazilian Rosewood; base notes are Osmanthus, Cypress, Virginia Cedar, Anise, Nutmeg and Musk.',
        4,
        23,
        NULL
      ),
(
        'Stylish-Man-12369',
        'Stylish Man Dzintars',
        'Stylish',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Petitgrain, Green Leaves, Violet, Iris and Mint',
        'Wormwood, Thuja, Galbanum, Incense, White Pepper, Gardenia and Vetiver',
        'Pomegranate, Amber, Musk and Brazilian Rosewood',
        'aromatic,green,woody,fresh spicy,citrus',
        'Stylish ManbyDzintarsis a Chypre fragrance for men.Stylish Manwas launched in 2010. Top notes are Mandarin Orange, Petitgrain, Green Leaves, Violet, Iris and Mint; middle notes are Wormwood, Thuja, Galbanum, Incense, White Pepper, Gardenia and Vetiver; base notes are Pomegranate, Amber, Musk and Brazilian Rosewood.',
        3.67,
        21,
        NULL
      ),
(
        'Miss-1-20230',
        'Miss 1 Dzintars',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Lily of the Valley, Apricot Blossom, Apple Tree Blossom and Aldehydes',
        'Mandarin Orange, Rose Petals, Hibiscus and Jasmine',
        'Musk, White Amber and Sandal',
        'white floral,fresh,citrus,fruity,green',
        'Miss 1byDzintarsis a Floral Fruity fragrance for women.Miss 1was launched in 2001. Top notes are Lily of the Valley, Apricot Blossom, Apple Tree Blossom and Aldehydes; middle notes are Mandarin Orange, Rose Petals, Hibiscus and Jasmine; base notes are Musk, White Amber and Sandal.',
        3.74,
        80,
        NULL
      ),
(
        'Miss-2-20231',
        'Miss 2 Dzintars',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Lily of the Valley, Litchi and Plum',
        'White Rose, Mimosa and Jasmine',
        'Musk, White Leather and Teak Wood',
        'white floral,fruity,warm spicy,amber,sweet',
        'Miss 2byDzintarsis a Amber Floral fragrance for women.Miss 2was launched in 2001. Top notes are Lily of the Valley, Litchi and Plum; middle notes are White Rose, Mimosa and Jasmine; base notes are Musk, White Leather and Teak Wood.',
        3.87,
        76,
        NULL
      ),
(
        'Miss-3-20232',
        'Miss 3 Dzintars',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Gardenia and Sweet Pea',
        'Vanilla Orchid, Rose and Lily of the Valley',
        'Sandalwood, Musk and Olive Tree',
        'citrus,white floral,fruity,sweet,lactonic',
        'Miss 3byDzintarsis a Floral Fruity fragrance for women.Miss 3was launched in 2004. Top notes are Mandarin Orange, Gardenia and Sweet Pea; middle notes are Vanilla Orchid, Rose and Lily of the Valley; base notes are Sandalwood, Musk and Olive Tree.',
        3.86,
        73,
        NULL
      ),
(
        'Miss-4-20233',
        'Miss 4 Dzintars',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Melon, Apple, Lily of the Valley and Lemon',
        'Cinnamon, Magnolia and Rose',
        'Musk, Ambergris and Osmanthus',
        'fruity,fresh,aquatic,ozonic,cinnamon',
        'Miss 4byDzintarsis a Floral Fruity fragrance for women.Miss 4was launched in 2004. Top notes are Melon, Apple, Lily of the Valley and Lemon; middle notes are Cinnamon, Magnolia and Rose; base notes are Musk, Ambergris and Osmanthus.',
        3.49,
        49,
        NULL
      ),
(
        'Miss-5-20295',
        'Miss 5 Dzintars',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Lemon, Lily of the Valley and Bellflower',
        'Carnation, Rose and Jasmine',
        'Amber, Bamboo and Tonka Bean',
        'floral,rose,warm spicy,citrus,aromatic',
        'Miss 5byDzintarsis a Floral fragrance for women.Miss 5was launched in 2007. Top notes are Lemon, Lily of the Valley and Bellflower; middle notes are Carnation, Rose and Jasmine; base notes are Amber, Bamboo and Tonka Bean.',
        3.68,
        72,
        NULL
      ),
(
        'Mits-1-Myth-1-20468',
        'Mīts 1 (Myth 1) Dzintars',
        'Mīts',
        'for men',
        NULL,
        NULL,
        'Lemon, Coriander and Mint',
        'Oakmoss, Mahogany and Currant buds',
        'Black Pepper, Cardamom and Amber',
        'aromatic,citrus,warm spicy,woody,soft spicy',
        'Mīts 1 (Myth 1)byDzintarsis a Woody Spicy fragrance for men.Mīts 1 (Myth 1)was launched in 2010. Top notes are Lemon, Coriander and Mint; middle notes are Oakmoss, Mahogany and Currant buds; base notes are Black Pepper, Cardamom and Amber.',
        3.64,
        11,
        NULL
      ),
(
        'Mits-2-Myth-2-20469',
        'Mīts 2 (Myth 2) Dzintars',
        'Mīts',
        'for men',
        NULL,
        NULL,
        'Orange and Grass',
        'Violet Leaf, Basil and Sandalwood',
        'Musk, Tonka Bean, Cedar, Amber and Moss',
        'green,citrus,musky,sweet,fresh',
        'Mīts 2 (Myth 2)byDzintarsis a Woody Aromatic fragrance for men.Mīts 2 (Myth 2)was launched in 2010. Top notes are Orange and Grass; middle notes are Violet Leaf, Basil and Sandalwood; base notes are Musk, Tonka Bean, Cedar, Amber and Moss.',
        3.88,
        16,
        NULL
      ),
(
        'Mits-3-Myth-3-20470',
        'Mīts 3 (Myth 3) Dzintars',
        'Mīts',
        'for men',
        NULL,
        NULL,
        'Tarragon, Sequoia and Coriander',
        'Lavender, Clary Sage and Vetiver',
        'Patchouli, Musk and Oakmoss',
        'aromatic,woody,soft spicy,lavender,earthy',
        'Mīts 3 (Myth 3)byDzintarsis a Aromatic Fougere fragrance for men.Mīts 3 (Myth 3)was launched in 2010. Top notes are Tarragon, Sequoia and Coriander; middle notes are Lavender, Clary Sage and Vetiver; base notes are Patchouli, Musk and Oakmoss.',
        3.2,
        10,
        NULL
      ),
(
        'Mits-4-Myth-4-20471',
        'Mīts 4 (Myth 4) Dzintars',
        'Mīts',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Lemon and Pepper',
        'Cypress, Lavender and Vetiver',
        'Sandalwood, Juniper Berries and Musk',
        'aromatic,woody,fresh spicy,citrus,lavender',
        'Mīts 4 (Myth 4)byDzintarsis a Aromatic Fougere fragrance for men.Mīts 4 (Myth 4)was launched in 2010. Top notes are Grapefruit, Lemon and Pepper; middle notes are Cypress, Lavender and Vetiver; base notes are Sandalwood, Juniper Berries and Musk.',
        3.43,
        14,
        NULL
      ),
(
        'My-Charm-Elegant-54331',
        'My Charm Elegant Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Fruits, Grapefruit and Lemon Leaf',
        'Jasmine Sambac, Japanese Cherry Blossom, White Rose and Narcissus',
        'Musk, Ambergris and Agarwood (Oud)',
        'fruity,floral,white floral,amber,musky',
        'My Charm ElegantbyDzintarsis a Floral Woody Musk fragrance for women.My Charm Elegantwas launched in 2019. Top notes are Fruits, Grapefruit and Lemon Leaf; middle notes are Jasmine Sambac, Japanese Cherry Blossom, White Rose and Narcissus; base notes are Musk, Ambergris and Agarwood (Oud).',
        4,
        17,
        NULL
      ),
(
        'My-Charm-Grace-54332',
        'My Charm Grace Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Pomelo, Grapefruit and Pink Pepper',
        'Gardenia, Frangipani, Violet and Peach',
        'Musk, Orris Root, Ambrette (Musk Mallow) and Sandalwood',
        'citrus,musky,fresh spicy,powdery',
        'My Charm GracebyDzintarsis a Floral fragrance for women.My Charm Gracewas launched in 2019. Top notes are Pomelo, Grapefruit and Pink Pepper; middle notes are Gardenia, Frangipani, Violet and Peach; base notes are Musk, Orris Root, Ambrette (Musk Mallow) and Sandalwood.',
        4.06,
        18,
        NULL
      ),
(
        'My-Charm-Special-54333',
        'My Charm Special Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Cinnamon, Saffron, Mandarin Orange and Coriander',
        'Patchouli, Coffee, Orange Blossom and Rose',
        'Cacao, Vanilla, Tonka Bean and Sugar Cane',
        'warm spicy,vanilla,cinnamon,sweet,cacao',
        'My Charm SpecialbyDzintarsis a Amber Vanilla fragrance for women.My Charm Specialwas launched in 2019. Top notes are Cinnamon, Saffron, Mandarin Orange and Coriander; middle notes are Patchouli, Coffee, Orange Blossom and Rose; base notes are Cacao, Vanilla, Tonka Bean and Sugar Cane.',
        4.38,
        45,
        NULL
      ),
(
        'My-Version-Actual-301-34985',
        'My Version Actual 301 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Bay Leaf, Watery Notes and Grapefruit',
        'Jasmine, Cedar and Cloves',
        'Patchouli, Amber and Oakmoss',
        'fresh spicy,white floral,aquatic,citrus,aromatic',
        'My Version Actual 301byDzintarsis a Woody Spicy fragrance for men.My Version Actual 301was launched in 2014. Top notes are Bay Leaf, Watery Notes and Grapefruit; middle notes are Jasmine, Cedar and Cloves; base notes are Patchouli, Amber and Oakmoss.',
        4.11,
        9,
        NULL
      ),
(
        'My-Version-Actual-302-83086',
        'My Version Actual 302 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Neroli, Lemon and Bergamot',
        'Hyacinth, Sage, Geranium and Cedar',
        'Amber and Musk',
        'citrus,aromatic,fresh spicy,musky,herbal',
        'My Version Actual 302byDzintarsis a Floral Green fragrance for men.My Version Actual 302was launched in 2014. Top notes are Neroli, Lemon and Bergamot; middle notes are Hyacinth, Sage, Geranium and Cedar; base notes are Amber and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'My-Version-Actual-905-34979',
        'My Version Actual 905 Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Pineapple, Citruses, Peach and Violet',
        'Lily, Jasmine and Ylang-Ylang',
        'Styrax, Orchid, Cedar and Amber',
        'fruity,sweet,citrus,white floral,fresh',
        'My Version Actual 905byDzintarsis a Floral Fruity fragrance for women.My Version Actual 905was launched in 2014. Top notes are Pineapple, Citruses, Peach and Violet; middle notes are Lily, Jasmine and Ylang-Ylang; base notes are Styrax, Orchid, Cedar and Amber.',
        4.18,
        11,
        NULL
      ),
(
        'My-Version-Modern-201-34982',
        'My Version Modern 201 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Mint, Grapefruit, Lemon and Mandarin Orange',
        'Spicy Notes, Cinnamon and Rose',
        'Patchouli, Amber, Leather and Musk',
        'warm spicy,citrus,aromatic,green,cinnamon',
        'My Version Modern 201byDzintarsis a Citrus fragrance for men.My Version Modern 201was launched in 2014. Top notes are Mint, Grapefruit, Lemon and Mandarin Orange; middle notes are Spicy Notes, Cinnamon and Rose; base notes are Patchouli, Amber, Leather and Musk.',
        4,
        6,
        NULL
      ),
(
        'My-Version-Modern-202-34983',
        'My Version Modern 202 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Plum, Apple and Citruses',
        'Cloves, Geranium and Cinnamon',
        'Vanilla, Sandalwood, Vetiver and Cedar',
        'fruity,woody,warm spicy,vanilla,sweet',
        'My Version Modern 202byDzintarsis a Amber Woody fragrance for men.My Version Modern 202was launched in 2014. Top notes are Plum, Apple and Citruses; middle notes are Cloves, Geranium and Cinnamon; base notes are Vanilla, Sandalwood, Vetiver and Cedar.',
        3.67,
        9,
        NULL
      ),
(
        'My-Version-Modern-203-34984',
        'My Version Modern 203 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Lime, Orange, Neroli and Bergamot',
        'Sea water, Violet, Freesia, Rosemary and Hyacinth',
        'Cedar, Oakmoss, Patchouli and Musk',
        'citrus,fresh spicy,aromatic,woody,floral',
        'My Version Modern 203byDzintarsis a Aromatic Fougere fragrance for men.My Version Modern 203was launched in 2014. Top notes are Lime, Orange, Neroli and Bergamot; middle notes are Sea water, Violet, Freesia, Rosemary and Hyacinth; base notes are Cedar, Oakmoss, Patchouli and Musk.',
        3.33,
        3,
        NULL
      ),
(
        'My-Version-Modern-204-83087',
        'My Version Modern 204 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Pear, Violet and Bergamot',
        'Vetiver, Cedar and Sandalwood',
        'Honey, Musk, Tonka Bean and Cardamom',
        'woody,powdery,aromatic,warm spicy,sweet',
        'My Version Modern 204byDzintarsis a Woody Aromatic fragrance for men.My Version Modern 204was launched in 2014. Top notes are Pear, Violet and Bergamot; middle notes are Vetiver, Cedar and Sandalwood; base notes are Honey, Musk, Tonka Bean and Cardamom.',
        4,
        2,
        NULL
      ),
(
        'My-Version-Modern-205-83088',
        'My Version Modern 205 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Pineapple, Lavender and Bergamot',
        'Apple, Rose, Dried Plum, Geranium and Oakmoss',
        'Sandalwood and Tonka Bean',
        'fruity,fresh spicy,aromatic,sweet,rose',
        'My Version Modern 205byDzintarsis a Aromatic Fruity fragrance for men.My Version Modern 205was launched in 2014. Top notes are Pineapple, Lavender and Bergamot; middle notes are Apple, Rose, Dried Plum, Geranium and Oakmoss; base notes are Sandalwood and Tonka Bean.',
        4.5,
        2,
        NULL
      ),
(
        'My-Version-Modern-701-34975',
        'My Version Modern 701 Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Cyclamen, Rose and Bergamot',
        'Coriander, Sandalwood and Musk',
        'Vetiver, Musk and Vanilla',
        'aromatic,woody,powdery,floral,citrus',
        'My Version Modern 701byDzintarsis a Floral Woody Musk fragrance for women.My Version Modern 701was launched in 2014. Top notes are Orange Blossom, Cyclamen, Rose and Bergamot; middle notes are Coriander, Sandalwood and Musk; base notes are Vetiver, Musk and Vanilla.',
        3.64,
        22,
        NULL
      ),
(
        'My-Version-Modern-702-34976',
        'My Version Modern 702 Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Litchi, Orange, Pear and Pink Pepper',
        'Jasmine, Freesia, Lily, Honey and Agarwood (Oud)',
        'Ginger, Vanilla, Tonka Bean, Cloves and Amber',
        'white floral,warm spicy,fruity,fresh,vanilla',
        'My Version Modern 702byDzintarsis a Amber Floral fragrance for women.My Version Modern 702was launched in 2014. Top notes are Litchi, Orange, Pear and Pink Pepper; middle notes are Jasmine, Freesia, Lily, Honey and Agarwood (Oud); base notes are Ginger, Vanilla, Tonka Bean, Cloves and Amber.',
        4.06,
        18,
        NULL
      ),
(
        'My-Version-Modern-703-34977',
        'My Version Modern 703 Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Fruity Notes',
        'Tuberose, Rose, Jasmine and Lily-of-the-Valley',
        'Vanilla, Sandalwood and Musk',
        'vanilla,powdery,woody,white floral,sweet',
        'My Version Modern 703byDzintarsis a Amber Floral fragrance for women.My Version Modern 703was launched in 2014. Top note is Fruity Notes; middle notes are Tuberose, Rose, Jasmine and Lily-of-the-Valley; base notes are Vanilla, Sandalwood and Musk.',
        4.03,
        35,
        NULL
      ),
(
        'My-Version-Modern-705-34978',
        'My Version Modern 705 Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Peach, Mandarin Orange and Pink Pepper',
        'Peony, Geranium and Lilac',
        'Amber, Musk and Patchouli',
        'musky,amber,floral,fruity,powdery',
        'My Version Modern 705byDzintarsis a Amber Floral fragrance for women.My Version Modern 705was launched in 2014. Top notes are Peach, Mandarin Orange and Pink Pepper; middle notes are Peony, Geranium and Lilac; base notes are Amber, Musk and Patchouli.',
        3.56,
        9,
        NULL
      ),
(
        'My-Version-Retro-101-34980',
        'My Version Retro 101 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Lavender, Nutmeg, Bergamot and Lemon',
        'Cloves, Cedar and Patchouli',
        'Sandalwood, Vetiver, Tonka Bean and Musk',
        'woody,fresh spicy,aromatic,lavender,warm spicy',
        'My Version Retro 101byDzintarsis a Amber Woody fragrance for men.My Version Retro 101was launched in 2014. Top notes are Lavender, Nutmeg, Bergamot and Lemon; middle notes are Cloves, Cedar and Patchouli; base notes are Sandalwood, Vetiver, Tonka Bean and Musk.',
        4.06,
        16,
        NULL
      ),
(
        'My-Version-Retro-102-34981',
        'My Version Retro 102 Dzintars',
        'My',
        'for men',
        NULL,
        NULL,
        'Citruses, Ginger, Rosemary and Basil',
        'Jasmine, Coriander, Juniper, Patchouli and Cardamom',
        'Vetiver, Sandalwood, Musk and Amber',
        'aromatic,fresh spicy,woody,citrus,warm spicy',
        'My Version Retro 102byDzintarsis a Aromatic Fougere fragrance for men.My Version Retro 102was launched in 2014. Top notes are Citruses, Ginger, Rosemary and Basil; middle notes are Jasmine, Coriander, Juniper, Patchouli and Cardamom; base notes are Vetiver, Sandalwood, Musk and Amber.',
        3.67,
        18,
        NULL
      ),
(
        'My-Version-Retro-505-34974',
        'My Version Retro 505 Dzintars',
        'My',
        'for women',
        NULL,
        NULL,
        'Aldehydes, Neroli and Lemon',
        'Jasmine, Rose, Violet Root and Iris',
        'Vanilla, Musk, Civet and Sandalwood',
        'white floral,fresh,aldehydic,powdery,vanilla',
        'My Version Retro 505byDzintarsis a Floral Aldehyde fragrance for women.My Version Retro 505was launched in 2014. Top notes are Aldehydes, Neroli and Lemon; middle notes are Jasmine, Rose, Violet Root and Iris; base notes are Vanilla, Musk, Civet and Sandalwood.',
        4,
        21,
        NULL
      ),
(
        'Opera-20263',
        'Opera Dzintars',
        'Opera',
        'for women',
        NULL,
        NULL,
        'Green Notes and Lemon Blossom',
        'Lily, Freesia and Jasmine',
        'Cloves, Peru Balsam, Sandalwood and Musk',
        'white floral,green,floral,warm spicy,woody',
        'OperabyDzintarsis a Floral Woody Musk fragrance for women.Operawas launched in 2012. Top notes are Green Notes and Lemon Blossom; middle notes are Lily, Freesia and Jasmine; base notes are Cloves, Peru Balsam, Sandalwood and Musk.',
        3.78,
        165,
        NULL
      ),
(
        'Opera-Classic-22733',
        'Opera Classic Dzintars',
        'Opera',
        'for women',
        NULL,
        NULL,
        'Neroli, Orange and Red Berries',
        'Gardenia, Magnolia and Pink Peony',
        'Honey, Blackwood and Patchouli',
        'floral,white floral,woody,honey,citrus',
        'Opera ClassicbyDzintarsis a Floral Fruity Gourmand fragrance for women.Opera Classicwas launched in 2013. Top notes are Neroli, Orange and Red Berries; middle notes are Gardenia, Magnolia and Pink Peony; base notes are Honey, Blackwood and Patchouli.',
        3.84,
        102,
        NULL
      ),
(
        'Opera-Night-22734',
        'Opera Night Dzintars',
        'Opera',
        'for women',
        NULL,
        NULL,
        'Black Currant, Pear and Orange Blossom',
        'Orchid, Iris, Freesia and Jasmine',
        'Vanilla, Cloves and Musk',
        'fruity,floral,powdery,vanilla,sweet',
        'Opera NightbyDzintarsis a Floral Fruity Gourmand fragrance for women.Opera Nightwas launched in 2013. Top notes are Black Currant, Pear and Orange Blossom; middle notes are Orchid, Iris, Freesia and Jasmine; base notes are Vanilla, Cloves and Musk.',
        4.02,
        140,
        NULL
      ),
(
        'Opera-Rock-80401',
        'Opera Rock Dzintars',
        'Opera',
        'for women and men',
        NULL,
        NULL,
        'Clementine, Black Currant and Pink Pepper',
        'Pineapple blossom, Hortensia and Moroccan Rose',
        'Musk, Sandalwood, Peru Balsam and Cloves',
        'floral,fruity,woody,warm spicy,musky',
        'Opera RockbyDzintarsis a Amber Floral fragrance for women and men.Opera Rockwas launched in 2019. Top notes are Clementine, Black Currant and Pink Pepper; middle notes are Pineapple blossom, Hortensia and Moroccan Rose; base notes are Musk, Sandalwood, Peru Balsam and Cloves.',
        4.5,
        6,
        NULL
      ),
(
        'Riga-82532',
        'Rīga Dzintars',
        'Rīga',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,white floral,musky,powdery,green',
        'RīgabyDzintarsis a Floral Woody Musk fragrance for women and men.Rīgawas launched in 1973.',
        3.8,
        5,
        NULL
      ),
(
        'Riga-82611',
        'Riga Dzintars',
        'Riga',
        'for men',
        NULL,
        NULL,
        'Bergamot, Citruses and Aldehydes',
        'Vetiver, Iris, Violet, Floral Notes and Oriental notes',
        'Oakmoss, Musk, Civet and Amber',
        'powdery,musky,amber,citrus,earthy',
        'RigabyDzintarsis a Woody Chypre fragrance for men.Rigawas launched in 1950. Riga was created by Bronislava Schwarzman, Marta Irbena and F. Pauche. Top notes are Bergamot, Citruses and Aldehydes; middle notes are Vetiver, Iris, Violet, Floral Notes and Oriental notes; base notes are Oakmoss, Musk, Civet and Amber.',
        5,
        2,
        NULL
      ),
(
        'Riga-82612',
        'Riga Dzintars',
        'Riga',
        'for women',
        NULL,
        NULL,
        'Bergamot, Neroli and Aldehydes',
        'Vetiver, Iris, Violet, Rose, Lavender, Lilac, Cinnamon, Ylang Ylang, Jasmine, Myrrh, Caraway, Costus and Oriental notes',
        'Oakmoss, Musk, Civet, Amber and Powdery Notes',
        'powdery,amber,floral,aromatic,earthy',
        'RigabyDzintarsis a Chypre Floral fragrance for women.Rigawas launched in 1958. Riga was created by Bronislava Schwarzman, Marta Irbena and F. Pauche. Top notes are Bergamot, Neroli and Aldehydes; middle notes are Vetiver, Iris, Violet, Rose, Lavender, Lilac, Cinnamon, Ylang Ylang, Jasmine, Myrrh, Caraway, Costus and Oriental notes; base notes are Oakmoss, Musk, Civet, Amber and Powdery Notes.',
        5,
        2,
        NULL
      ),
(
        'Lilac-of-Riga-Rizskaa-Siren-2021-70902',
        'Lilac of Riga (Рижская Сирень, 2021) Dzintars',
        'Lilac',
        'for women',
        NULL,
        NULL,
        'Lilac, Cyclamen and Lily-of-the-Valley',
        'Heliotrope, Cinnamon and Vanilla',
        'Amber and Musk',
        'floral,fresh,powdery,green,vanilla',
        'Lilac of Riga (Рижская Сирень, 2021)byDzintarsis a Floral fragrance for women.Lilac of Riga (Рижская Сирень, 2021)was launched in 2021. Top notes are Lilac, Cyclamen and Lily-of-the-Valley; middle notes are Heliotrope, Cinnamon and Vanilla; base notes are Amber and Musk.',
        4.14,
        14,
        NULL
      ),
(
        'Lilac-of-Riga-Rizskaa-Siren-2022-76485',
        'Lilac of Riga (Рижская Сирень, 2022) Dzintars',
        'Lilac',
        'for women',
        NULL,
        'Artyushkova M.L.',
        'Lilac, Citrus Blossom and Cyclamen',
        'Heliotrope, Jasmine, Plum and Patchouli',
        'Tobacco, Cinnamon, Amber, Labdanum and Sandalwood',
        'floral,fresh,tobacco,sweet,cinnamon',
        'Lilac of Riga (Рижская Сирень, 2022)byDzintarsis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Lilac of Riga (Рижская Сирень, 2022)was launched in 2022. The nose behind this fragrance is Artyushkova M.L.. Top notes are Lilac, Citrus Blossom and Cyclamen; middle notes are Heliotrope, Jasmine, Plum and Patchouli; base notes are Tobacco, Cinnamon, Amber, Labdanum and Sandalwood.',
        3.68,
        41,
        NULL
      ),
(
        'Rigas-Cerini-Rizskaa-Siren-2000-12404',
        'Rigas Cerini (Рижская Сирень, 2000) Dzintars',
        'Rigas',
        'for women',
        NULL,
        'Artyushkova M.L.',
        'Lilac, Cyclamen and Lily of the Valley',
        'Cinnamon, Heliotrope and Vanilla',
        'Amber and Musk',
        'floral,fresh,cinnamon,warm spicy,powdery',
        'Rigas Cerini (Рижская Сирень, 2000)byDzintarsis a Floral fragrance for women.Rigas Cerini (Рижская Сирень, 2000)was launched in 2000. The nose behind this fragrance is Artyushkova M.L.. Top notes are Lilac, Cyclamen and Lily of the Valley; middle notes are Cinnamon, Heliotrope and Vanilla; base notes are Amber and Musk.',
        3.9,
        486,
        NULL
      ),
(
        'Rigas-cerini-Rizskaa-siren-83010',
        'Rīgas cēriņi (Рижская сирень) Dzintars',
        'Rīgas',
        'for women',
        NULL,
        'Artyushkova M.L.',
        'Lilac, Aldehydes and Jasmine',
        'Heliotrope, Cinnamon, Vanilla and Ylang Ylang',
        'Powdery Notes, Civet, Musk and Amber',
        'powdery,floral,vanilla,cinnamon,musky',
        'Rīgas cēriņi (Рижская сирень)byDzintarsis a Floral fragrance for women.Rīgas cēriņi (Рижская сирень)was launched in 1952. The nose behind this fragrance is Artyushkova M.L.. Top notes are Lilac, Aldehydes and Jasmine; middle notes are Heliotrope, Cinnamon, Vanilla and Ylang Ylang; base notes are Powdery Notes, Civet, Musk and Amber.',
        4.75,
        16,
        NULL
      ),
(
        'Ridziniece-Rizanka-41059',
        'Rīdziniece (Рижанка) Dzintars',
        'Rīdziniece',
        'for women',
        NULL,
        'Bronislava Schwarzman',
        'Aldehydes, Lily-of-the-Valley, Lilac and Mandarin Orange',
        'Gardenia, Hyacinth, Carnation and Jasmine',
        'Heliotrope, Civet and Musk',
        'white floral,floral,powdery,green,musky',
        'Rīdziniece (Рижанка)byDzintarsis a Floral Aldehyde fragrance for women.Rīdziniece (Рижанка)was launched in 1965. The nose behind this fragrance is Bronislava Schwarzman. Top notes are Aldehydes, Lily-of-the-Valley, Lilac and Mandarin Orange; middle notes are Gardenia, Hyacinth, Carnation and Jasmine; base notes are Heliotrope, Civet and Musk.',
        4.37,
        30,
        NULL
      ),
(
        'Ridzinieks-Rizanin-41140',
        'Rīdzinieks (Рижанин) Dzintars',
        'Rīdzinieks',
        'for men',
        NULL,
        'Bronislava Schwarzman',
        'Bergamot, Orange, Orange Blossom and Petitgrain',
        'Cloves, Vetiver, Sandalwood and Lavender',
        'Oakmoss, Amber and Musk',
        'warm spicy,mossy,earthy,woody,citrus',
        'Rīdzinieks (Рижанин)byDzintarsis a Amber Woody fragrance for men.Rīdzinieks (Рижанин)was launched in 1965. The nose behind this fragrance is Bronislava Schwarzman. Top notes are Bergamot, Orange, Orange Blossom and Petitgrain; middle notes are Cloves, Vetiver, Sandalwood and Lavender; base notes are Oakmoss, Amber and Musk.',
        4.14,
        22,
        NULL
      ),
(
        'Pergolese-3548',
        'Pergolese Dzintars',
        'Pergolese',
        'for women',
        NULL,
        NULL,
        'Bergamot, Freesia, Black Currant and Peony',
        'Tea, Magnolia, Lily, Jasmine and Red Berries',
        'Musk, Vanilla, Apricot and Amber',
        'floral,citrus,fruity,white floral,green',
        'PergolesebyDzintarsis a Floral Fruity fragrance for women.Pergolesewas launched in 1996. Top notes are Bergamot, Freesia, Black Currant and Peony; middle notes are Tea, Magnolia, Lily, Jasmine and Red Berries; base notes are Musk, Vanilla, Apricot and Amber.',
        4.13,
        432,
        NULL
      ),
(
        'Rue-Pergolese-Gold-22921',
        'Rue Pergolese Gold Dzintars',
        'Rue',
        'for women',
        NULL,
        NULL,
        'Raspberry, Amalfi Lemon and Neroli',
        'Gardenia, Jasmine and Orange Blossom',
        'White Honey and Patchouli',
        'white floral,sweet,honey,citrus,patchouli',
        'Rue Pergolese GoldbyDzintarsis a Amber Floral fragrance for women. Top notes are Raspberry, Amalfi Lemon and Neroli; middle notes are Gardenia, Jasmine and Orange Blossom; base notes are White Honey and Patchouli.',
        3.86,
        36,
        NULL
      ),
(
        'Rue-Pergolese-Night-22922',
        'Rue Pergolese Night Dzintars',
        'Rue',
        'for women',
        NULL,
        NULL,
        'Litchi, Kiwi and Quince',
        'White Chocolate, Orchid and Jasmine',
        'White Musk, Orris and Precious Woods',
        'sweet,fruity,musky,powdery,tropical',
        'Rue Pergolese NightbyDzintarsis a Floral Fruity Gourmand fragrance for women. Top notes are Litchi, Kiwi and Quince; middle notes are White Chocolate, Orchid and Jasmine; base notes are White Musk, Orris and Precious Woods.',
        3.79,
        33,
        NULL
      ),
(
        'Souvenir-Green-20299',
        'Souvenir Green Dzintars',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,green,soft spicy,sour',
        'Souvenir GreenbyDzintarsis a fragrance for women.Souvenir Greenwas launched in 2011.',
        3.5,
        2,
        NULL
      ),
(
        'Souvenir-Orange-20300',
        'Souvenir Orange Dzintars',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,sweet,tropical,vanilla',
        'Souvenir OrangebyDzintarsis a Floral Fruity Gourmand fragrance for women.Souvenir Orangewas launched in 2011.',
        3,
        2,
        NULL
      ),
(
        'Souvenir-Purple-20301',
        'Souvenir Purple Dzintars',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,woody,sweet,white floral',
        'Souvenir PurplebyDzintarsis a Floral Fruity fragrance for women.Souvenir Purplewas launched in 2011.',
        4.2,
        5,
        NULL
      ),
(
        'Souvenir-1-54708',
        'Souvenir 1 Dzintars',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        'Honey, Orange, Wild Berries and Neroli',
        'Pink Peony, Nerium Oleander, Magnolia and Rose',
        'Vanila, Amber, Cashmeran and Tonka Bean',
        'floral,vanilla,amber,sweet,rose',
        'Souvenir 1byDzintarsis a Floral Fruity Gourmand fragrance for women.Souvenir 1was launched in 2018. Top notes are Honey, Orange, Wild Berries and Neroli; middle notes are Pink Peony, Nerium Oleander, Magnolia and Rose; base notes are Vanila, Amber, Cashmeran and Tonka Bean.',
        3.7,
        27,
        NULL
      ),
(
        'Souvenir-2-54709',
        'Souvenir 2 Dzintars',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        'Rum, Pomegranate, Ginger and Orange Blossom',
        'Tuberose, Jasmine and Ylang-Ylang',
        'Siam Benzoin, Tonka Bean and Musk',
        'white floral,tuberose,amber,warm spicy,woody',
        'Souvenir 2byDzintarsis a Floral Fruity Gourmand fragrance for women.Souvenir 2was launched in 2018. Top notes are Rum, Pomegranate, Ginger and Orange Blossom; middle notes are Tuberose, Jasmine and Ylang-Ylang; base notes are Siam Benzoin, Tonka Bean and Musk.',
        3.94,
        32,
        NULL
      ),
(
        'Souvenir-3-54710',
        'Souvenir 3 Dzintars',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        'Cardamom, Coffee and Violet',
        'Patchouli, Orchid and Hiacynth',
        'Saffron, Vetiver and Amber',
        'warm spicy,floral,patchouli,woody,earthy',
        'Souvenir 3byDzintarsis a Chypre Floral fragrance for women.Souvenir 3was launched in 2018. Top notes are Cardamom, Coffee and Violet; middle notes are Patchouli, Orchid and Hiacynth; base notes are Saffron, Vetiver and Amber.',
        3.74,
        27,
        NULL
      ),
(
        'Sport-Game-20478',
        'Sport Game Dzintars',
        'Sport',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot, Geranium and Wormwood',
        'Cassis, Lavender, Petitgrain, Patchouli and Vetiver',
        'Tonka Bean, Ginger, Oakmoss and Musk',
        'aromatic,citrus,green,woody,fresh spicy',
        'Sport GamebyDzintarsis a Aromatic Fougere fragrance for men.Sport Gamewas launched in 2010. Top notes are Lemon, Bergamot, Geranium and Wormwood; middle notes are Cassis, Lavender, Petitgrain, Patchouli and Vetiver; base notes are Tonka Bean, Ginger, Oakmoss and Musk.',
        3,
        5,
        NULL
      ),
(
        'Sport-Goal-20480',
        'Sport Goal Dzintars',
        'Sport',
        'for men',
        NULL,
        NULL,
        'Artemisia, Fig Leaf and Calamus',
        'Cacao, Cedar, Marjoram and Thyme',
        'Patchouli, Amber and Vetiver',
        'woody,warm spicy,aromatic,cacao,herbal',
        'Sport GoalbyDzintarsis a Aromatic fragrance for men.Sport Goalwas launched in 2010. Top notes are Artemisia, Fig Leaf and Calamus; middle notes are Cacao, Cedar, Marjoram and Thyme; base notes are Patchouli, Amber and Vetiver.',
        2,
        1,
        NULL
      ),
(
        'Sport-Record-20479',
        'Sport Record Dzintars',
        'Sport',
        'for men',
        NULL,
        NULL,
        'Lime, Grapefruit and Tangerine',
        'Clary Sage, Fern, Juniper and Basil',
        'Musk, Labdanum and Sandalwood',
        'aromatic,citrus,fresh spicy,soft spicy,woody',
        'Sport RecordbyDzintarsis a Aromatic Fougere fragrance for men.Sport Recordwas launched in 2010. Top notes are Lime, Grapefruit and Tangerine; middle notes are Clary Sage, Fern, Juniper and Basil; base notes are Musk, Labdanum and Sandalwood.',
        3.33,
        6,
        NULL
      ),
(
        'Titaniks-20475',
        'Titāniks Dzintars',
        'Titāniks',
        'for men',
        NULL,
        NULL,
        'Watery Notes, Bergamot and Grapefruit',
        'Seaweed, Myrtle and Iris',
        'Pine Tree, Woody Notes and Amber',
        'aromatic,woody,aquatic,marine,fresh spicy',
        'TitāniksbyDzintarsis a Aromatic Aquatic fragrance for men.Titānikswas launched in 2000. Top notes are Watery Notes, Bergamot and Grapefruit; middle notes are Seaweed, Myrtle and Iris; base notes are Pine Tree, Woody Notes and Amber.',
        2.86,
        56,
        NULL
      ),
(
        'Titaniks-Gold-20476',
        'Titāniks Gold Dzintars',
        'Titāniks',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Orange and Petitgrain',
        'Patchouli, Vetiver and Sandalwood',
        'Cashmere Wood and Amber',
        'woody,citrus,patchouli,balsamic,amber',
        'Titāniks GoldbyDzintarsis a Woody Aromatic fragrance for men.Titāniks Goldwas launched in 2007. Top notes are Grapefruit, Orange and Petitgrain; middle notes are Patchouli, Vetiver and Sandalwood; base notes are Cashmere Wood and Amber.',
        3,
        6,
        NULL
      ),
(
        'Titaniks-Silver-20477',
        'Titāniks Silver Dzintars',
        'Titāniks',
        'for men',
        NULL,
        NULL,
        'Watery Notes, Lemon and Grapefruit',
        'Vetiver, Lavender and Juniper',
        'Sandalwood, Amber and Galbanum',
        'aquatic,woody,fresh,earthy',
        'Titāniks SilverbyDzintarsis a Woody Aquatic fragrance for men.Titāniks Silverwas launched in 2007. Top notes are Watery Notes, Lemon and Grapefruit; middle notes are Vetiver, Lavender and Juniper; base notes are Sandalwood, Amber and Galbanum.',
        2.47,
        15,
        NULL
      ),
(
        'Es-81880',
        'Es Dzintars',
        'Es',
        'for women',
        NULL,
        'Bronislava Schwarzman',
        'Aldehydes, Bergamot and Lilac',
        'Jasmine, Iris, Carnation, Patchouli, Labdanum and Tonka Bean',
        'Musk, Civet, Ambergris, Peru Balsam, Sandalwood and Oakmoss',
        'amber,woody,musky,floral,balsamic',
        'EsbyDzintarsis a Chypre Floral fragrance for women.Eswas launched in 1965. The nose behind this fragrance is Bronislava Schwarzman. Top notes are Aldehydes, Bergamot and Lilac; middle notes are Jasmine, Iris, Carnation, Patchouli, Labdanum and Tonka Bean; base notes are Musk, Civet, Ambergris, Peru Balsam, Sandalwood and Oakmoss.',
        5,
        2,
        NULL
      ),
(
        'Tu-81879',
        'Tu Dzintars',
        'Tu',
        'for men',
        NULL,
        'Bronislava Schwarzman',
        'Aldehydes, Bergamot and Lilac',
        'Iris, Carnation, Patchouli, Labdanum and Vetiver',
        'Musk, Civet, Ambergris and Oakmoss',
        'musky,amber,woody,earthy,floral',
        'TubyDzintarsis a Chypre fragrance for men.Tuwas launched in 1965. The nose behind this fragrance is Bronislava Schwarzman. Top notes are Aldehydes, Bergamot and Lilac; middle notes are Iris, Carnation, Patchouli, Labdanum and Vetiver; base notes are Musk, Civet, Ambergris and Oakmoss.',
        5,
        2,
        NULL
      ),
(
        'Voile-Leger-Bleu-41278',
        'Voile Léger Bleu Dzintars',
        'Voile',
        'for women and men',
        NULL,
        NULL,
        'Red Berries, Mint and Violet',
        'Lotus, Orchid, Hyacinth and Magnolia',
        'Musk, Amber and Vanilla',
        'fruity,sweet,powdery,floral,musky',
        'Voile Léger BleubyDzintarsis a Floral fragrance for women and men.Voile Léger Bleuwas launched in 2014. Top notes are Red Berries, Mint and Violet; middle notes are Lotus, Orchid, Hyacinth and Magnolia; base notes are Musk, Amber and Vanilla.',
        3.89,
        27,
        NULL
      ),
(
        'Voile-Leger-Lilas-41279',
        'Voile Léger Lilas Dzintars',
        'Voile',
        'for women',
        NULL,
        NULL,
        'Bergamot, Orange Oil and Orange Blossom',
        'Rose, Jasmine, Ylang-Ylang and Magnolia',
        'Patchouli, Vanilla, Vetiver and Tonka Bean',
        'citrus,woody,white floral,floral,vanilla',
        'Voile Léger LilasbyDzintarsis a Floral fragrance for women.Voile Léger Lilaswas launched in 2014. Top notes are Bergamot, Orange Oil and Orange Blossom; middle notes are Rose, Jasmine, Ylang-Ylang and Magnolia; base notes are Patchouli, Vanilla, Vetiver and Tonka Bean.',
        4.02,
        41,
        NULL
      ),
(
        'Voile-Leger-Orange-41280',
        'Voile Léger Orange Dzintars',
        'Voile',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Honey and Neroli',
        'Jasmine, Caramel and Nerium Oleander',
        'Amber, Musk and Cashmere Wood',
        'white floral,sweet,floral,amber,honey',
        'Voile Léger OrangebyDzintarsis a Floral Woody Musk fragrance for women.Voile Léger Orangewas launched in 2014. Top notes are Orange Blossom, Honey and Neroli; middle notes are Jasmine, Caramel and Nerium Oleander; base notes are Amber, Musk and Cashmere Wood.',
        4.02,
        44,
        NULL
      ),
(
        'Fruit-Wind-20296',
        'Fruit Wind Dzintars',
        'Fruit',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,woody,violet,fruity,vanilla',
        'Fruit WindbyDzintarsis a Floral Fruity Gourmand fragrance for women.Fruit Windwas launched in 2010.',
        3.33,
        9,
        NULL
      ),
(
        'Spring-Wind-20298',
        'Spring Wind Dzintars',
        'Spring',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,floral,powdery,white floral,fruity',
        'Spring WindbyDzintarsis a Floral Green fragrance for women.Spring Windwas launched in 2010.',
        3.67,
        15,
        NULL
      ),
(
        'Tropical-Wind-20297',
        'Tropical Wind Dzintars',
        'Tropical',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,yellow floral,powdery,woody,sweet',
        'Tropical WindbyDzintarsis a Floral fragrance for women.Tropical Windwas launched in 2010.',
        3.56,
        9,
        NULL
      ),
(
        'Laudis-Ludi-60548',
        'Ļaudis (Люди) Dzintars',
        'Ļaudis',
        'for women',
        NULL,
        NULL,
        'Lilac, Ylang Ylang and Rose',
        'Leather, Tobacco, Tobacco Blossom and Sandalwood',
        'Patchouli, Tonka Bean and Amber',
        'woody,amber,sweet,floral,leather',
        'Ļaudis (Люди)byDzintarsis a Floral Woody Musk fragrance for women.Ļaudis (Люди)was launched in 1965. Top notes are Lilac, Ylang Ylang and Rose; middle notes are Leather, Tobacco, Tobacco Blossom and Sandalwood; base notes are Patchouli, Tonka Bean and Amber.',
        5,
        2,
        NULL
      ),
(
        'Zeme-Zemla-60547',
        'Zeme (Земля) Dzintars',
        'Zeme',
        'for women and men',
        NULL,
        NULL,
        'Aldehydes, Lilac and Geranium',
        'Jasmine, Peony, Hawthorn, Iris and Powdery Notes',
        'Sandalwood, Amber and Musk',
        'floral,powdery,fresh,fresh spicy,aldehydic',
        'Zeme (Земля)byDzintarsis a Floral Aldehyde fragrance for women and men.Zeme (Земля)was launched in 1965. Top notes are Aldehydes, Lilac and Geranium; middle notes are Jasmine, Peony, Hawthorn, Iris and Powdery Notes; base notes are Sandalwood, Amber and Musk.',
        4.67,
        3,
        NULL
      ),
(
        'Avventurina-54213',
        'Avventurina Dolce Fiore',
        'Avventurina',
        'for women and men',
        NULL,
        'Jordi Fernández',
        'Bergamot, Green Tea and Neroli',
        'Sandalwood, Cedar and Pomarose',
        'Tonka Bean and Ambergris',
        'woody,amber,citrus,aromatic,green',
        'AvventurinabyDolce Fioreis a Woody Aromatic fragrance for women and men.Avventurinawas launched in 2019. The nose behind this fragrance is Jórdi Fernandez. Top notes are Bergamot, Green Tea and Neroli; middle notes are Sandalwood, Cedar and Pomarose; base notes are Tonka Bean and Ambergris.',
        NULL,
        NULL,
        NULL
      ),
(
        'Cameo-54219',
        'Cameo Dolce Fiore',
        'Cameo',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Rose, Artemisia and Cardamom',
        'Sage, Amber, Cypriol Oil or Nagarmotha, Orris and Red Fruits',
        'Musk, Vanilla, Woody Notes and Agarwood (Oud)',
        'woody,aromatic,herbal,powdery,musky',
        'CameobyDolce Fioreis a Amber Floral fragrance for women and men.Cameowas launched in 2019. The nose behind this fragrance is Chris Maurice. Top notes are Rose, Artemisia and Cardamom; middle notes are Sage, Amber, Cypriol Oil or Nagarmotha, Orris and Red Fruits; base notes are Musk, Vanilla, Woody Notes and Agarwood (Oud).',
        4.8,
        5,
        NULL
      ),
(
        'Fenicio-54217',
        'Fenicio Dolce Fiore',
        'Fenicio',
        'for women and men',
        NULL,
        'Rosendo Mateu',
        'Passionfruit and Apple',
        'Chocolate, Jasmine, Pepper and Violet',
        'Amber, Sandalwood, Agarwood (Oud) and Vanilla',
        'amber,fruity,fresh,sweet,tropical',
        'FeniciobyDolce Fioreis a Amber Floral fragrance for women and men.Feniciowas launched in 2019. The nose behind this fragrance is Rosendo Mateu. Top notes are Passionfruit and Apple; middle notes are Chocolate, Jasmine, Pepper and Violet; base notes are Amber, Sandalwood, Agarwood (Oud) and Vanilla.',
        4.5,
        2,
        NULL
      ),
(
        'Filigrana-54214',
        'Filigrana Dolce Fiore',
        'Filigrana',
        'for women and men',
        NULL,
        'Jordi Fernández',
        'Italian Mandarin and Juniper',
        'Freesia, Orris Root and Vetiver',
        'Amber and Musk',
        'citrus,aromatic,woody,powdery,floral',
        'FiligranabyDolce Fioreis a Floral Woody Musk fragrance for women and men.Filigranawas launched in 2019. The nose behind this fragrance is Jórdi Fernandez. Top notes are Italian Mandarin and Juniper; middle notes are Freesia, Orris Root and Vetiver; base notes are Amber and Musk.',
        5,
        3,
        NULL
      ),
(
        'Incalmo-54215',
        'Incalmo Dolce Fiore',
        'Incalmo',
        'for women and men',
        NULL,
        'Olivier Pescheux',
        'Coriander and Angelica',
        'Magnolan and Sesame',
        'Ambrette (Musk Mallow), White Musk and Vanilla',
        'musky,floral,powdery,fresh,aromatic',
        'IncalmobyDolce Fioreis a Floral Woody Musk fragrance for women and men.Incalmowas launched in 2019. The nose behind this fragrance is Olivier Pescheux. Top notes are Coriander and Angelica; middle notes are Magnolan and Sesame; base notes are Ambrette (Musk Mallow), White Musk and Vanilla.',
        5,
        5,
        NULL
      ),
(
        'Lattimo-54216',
        'Lattimo Dolce Fiore',
        'Lattimo',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Bergamot, Mandarin Orange and Cassis',
        'Passionfruit, Raspberry, Ylang-Ylang and Amber',
        'Musk, Patchouli, Vanilla and Woody Notes',
        'fruity,sweet,citrus,woody,musky',
        'LattimobyDolce Fioreis a Floral Fruity fragrance for women and men.Lattimowas launched in 2019. The nose behind this fragrance is Chris Maurice. Top notes are Bergamot, Mandarin Orange and Cassis; middle notes are Passionfruit, Raspberry, Ylang-Ylang and Amber; base notes are Musk, Patchouli, Vanilla and Woody Notes.',
        5,
        1,
        NULL
      ),
(
        'Murrine-54218',
        'Murrine Dolce Fiore',
        'Murrine',
        'for women and men',
        NULL,
        'Jordi Fernández',
        'Saffron, Blood Orange and Carnation',
        'Akigalawood and Woodsy Notes',
        'Amber, Oakmoss, Patchouli and Praline',
        'woody,warm spicy,earthy,sweet,amber',
        'MurrinebyDolce Fioreis a Woody Chypre fragrance for women and men.Murrinewas launched in 2019. The nose behind this fragrance is Jórdi Fernandez. Top notes are Saffron, Blood Orange and Carnation; middle notes are Akigalawood and Woodsy Notes; base notes are Amber, Oakmoss, Patchouli and Praline.',
        5,
        2,
        NULL
      ),
(
        'Dark-42292',
        'Dark Desigual',
        'Dark',
        'for men',
        NULL,
        NULL,
        'Saffron, Cinnamon, Ginger, Black Pepper and Nutmeg',
        'Vetiver, Orange Blossom, Patchouli and Driftwood',
        'Black Vanilla Husk, Tonka Bean, Oakmoss, Amber, Tobacco and Musk',
        'warm spicy,vanilla,woody,sweet,fresh spicy',
        'DarkbyDesigualis a Amber Spicy fragrance for men.Darkwas launched in 2015. Top notes are Saffron, Cinnamon, Ginger, Black Pepper and Nutmeg; middle notes are Vetiver, Orange Blossom, Patchouli and Driftwood; base notes are Black Vanilla Husk, Tonka Bean, Oakmoss, Amber, Tobacco and Musk.',
        3.54,
        79,
        NULL
      ),
(
        'Dark-Fresh-30501',
        'Dark Fresh Desigual',
        'Dark',
        'for men',
        NULL,
        NULL,
        'Sea Notes, Neroli, Citruses, Spices and Green Leaves',
        'Flowers and Orange',
        'Amber, Woodsy Notes, Vanilla, Musk and Moss',
        'citrus,marine,amber,woody,aromatic',
        'Dark FreshbyDesigualis a Aromatic Fruity fragrance for men.Dark Freshwas launched in 2015. Top notes are Sea Notes, Neroli, Citruses, Spices and Green Leaves; middle notes are Flowers and Orange; base notes are Amber, Woodsy Notes, Vanilla, Musk and Moss.',
        3.59,
        115,
        NULL
      ),
(
        'Dark-Fresh-Festival-Man-54293',
        'Dark Fresh Festival Man Desigual',
        'Dark',
        'for men',
        NULL,
        NULL,
        'Black Pepper, Lemon and Coriander',
        'Lavender, Sea Notes and Green Apple',
        'Haitian Vetiver, Amber and Moss',
        'aromatic,fresh spicy,lavender,marine,citrus',
        'Dark Fresh Festival ManbyDesigualis a Woody Aromatic fragrance for men.Dark Fresh Festival Manwas launched in 2019. Top notes are Black Pepper, Lemon and Coriander; middle notes are Lavender, Sea Notes and Green Apple; base notes are Haitian Vetiver, Amber and Moss.',
        3.31,
        16,
        NULL
      ),
(
        'Fresh-30500',
        'Fresh Desigual',
        'Fresh',
        'for women',
        NULL,
        'Sonia Constant',
        'Lemon, Yuzu, Fruits and Mint',
        'Green Apple, Lotus and Magnolia',
        'Cedar, Musk, Amber, Sandalwood and Vanilla',
        'citrus,fruity,green,floral,aromatic',
        'FreshbyDesigualis a Floral Woody Musk fragrance for women.Freshwas launched in 2015. The nose behind this fragrance is Sonia Constant. Top notes are Lemon, Yuzu, Fruits and Mint; middle notes are Green Apple, Lotus and Magnolia; base notes are Cedar, Musk, Amber, Sandalwood and Vanilla.',
        3.81,
        244,
        NULL
      ),
(
        'Fresh-Bloom-46051',
        'Fresh Bloom Desigual',
        'Fresh',
        'for women',
        NULL,
        'Véronique Nyberg',
        'Raspberry and Mangosteen',
        'May Rose and Jasmine Sambac',
        'Cedar and Sandalwood',
        'fruity,rose,sweet,tropical,woody',
        'Fresh BloombyDesigualis a Floral Fruity fragrance for women.Fresh Bloomwas launched in 2017. Fresh Bloom was created by Violaine Collas and Veronique Nyberg. Top notes are Raspberry and Mangosteen; middle notes are May Rose and Jasmine Sambac; base notes are Cedar and Sandalwood.',
        3.56,
        93,
        NULL
      ),
(
        'Fresh-Festival-Woman-54294',
        'Fresh Festival Woman Desigual',
        'Fresh',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Ginger and Neroli',
        'Peony and Orange Blossom',
        'Raspberry and Patchouli',
        'fruity,citrus,sweet,patchouli,warm spicy',
        'Fresh Festival WomanbyDesigualis a Floral Fruity fragrance for women.Fresh Festival Womanwas launched in 2019. Top notes are Mandarin Orange, Ginger and Neroli; middle notes are Peony and Orange Blossom; base notes are Raspberry and Patchouli.',
        3.84,
        32,
        NULL
      ),
(
        'Fresh-World-51200',
        'Fresh World Desigual',
        'Fresh',
        'for women',
        NULL,
        'Juliette Karagueuzoglou',
        'Apple, Cassis and Pineapple',
        'Cacao, Iris and Egyptian Jasmine',
        'Patchouli, Amber, Vanilla, Musk and Sandalwood',
        'cacao,warm spicy,fruity,woody,sweet',
        'Fresh WorldbyDesigualis a Amber Floral fragrance for women.Fresh Worldwas launched in 2018. The nose behind this fragrance is Juliette Karagueuzoglou. Top notes are Apple, Cassis and Pineapple; middle notes are Cacao, Iris and Egyptian Jasmine; base notes are Patchouli, Amber, Vanilla, Musk and Sandalwood.',
        3.7,
        71,
        NULL
      ),
(
        'Fun-21943',
        'Fun Desigual',
        'Fun',
        'for women',
        NULL,
        'Christophe Raynaud',
        'White Peach, Cranberry and Pear',
        'Passionfruit, Violet and Peony',
        'Teak Wood and Sandalwood',
        'fruity,sweet,fresh,tropical,powdery',
        'FunbyDesigualis a Floral Fruity fragrance for women.Funwas launched in 2014. The nose behind this fragrance is Christophe Raynaud. Top notes are White Peach, Cranberry and Pear; middle notes are Passionfruit, Violet and Peony; base notes are Teak Wood and Sandalwood.',
        3.71,
        85,
        NULL
      ),
(
        'Love-21942',
        'Love Desigual',
        'Love',
        'for women',
        NULL,
        'Fabrice Pellegrin',
        'Black Currant and Blueberry',
        'Orange, Grapefruit and Benzoin',
        'Praline, Tonka Bean and Sandalwood',
        'sweet,fruity,citrus,woody,amber',
        'LovebyDesigualis a Floral Fruity Gourmand fragrance for women.Lovewas launched in 2014. The nose behind this fragrance is Fabrice Pellegrin. Top notes are Black Currant and Blueberry; middle notes are Orange, Grapefruit and Benzoin; base notes are Praline, Tonka Bean and Sandalwood.',
        3.31,
        55,
        NULL
      ),
(
        'Sex-21941',
        'Sex Desigual',
        'Sex',
        'for women',
        NULL,
        'Daphné Bugey',
        'Red Berries, Rhubarb and Soybean',
        'Indian Tuberose, Jasmine and Grapefruit blossom',
        'Musk, Vanilla and Woodsy Notes',
        'white floral,fruity,tuberose,green,sweet',
        'SexbyDesigualis a Floral Fruity fragrance for women.Sexwas launched in 2014. The nose behind this fragrance is Daphné Bugey. Top notes are Red Berries, Rhubarb and Soybean; middle notes are Indian Tuberose, Jasmine and Grapefruit blossom; base notes are Musk, Vanilla and Woodsy Notes.',
        3.58,
        98,
        NULL
      ),
(
        'You-32617',
        'You Desigual',
        'You',
        'for women',
        NULL,
        'Olivier Cresp',
        'Bergamot, Mandarin Orange, Rhubarb, Grapefruit and Violet',
        'Tonka Bean, Benzoin, Cedar, Musk and Orange Blossom',
        'Praline, Coffee, Cardamom and Jasmine',
        'citrus,warm spicy,sweet,aromatic,amber',
        'YoubyDesigualis a Amber Floral fragrance for women.Youwas launched in 2015. The nose behind this fragrance is Olivier Cresp. Top notes are Bergamot, Mandarin Orange, Rhubarb, Grapefruit and Violet; middle notes are Tonka Bean, Benzoin, Cedar, Musk and Orange Blossom; base notes are Praline, Coffee, Cardamom and Jasmine.',
        3.64,
        165,
        NULL
      ),
(
        'Cashmere-Musk-32619',
        'Cashmere Musk Desigual',
        'Cashmere',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Cashmere MuskbyDesigualis a Amber fragrance for women and men.Cashmere Muskwas launched in 2015.',
        4,
        3,
        NULL
      ),
(
        'Oriental-Velvet-32621',
        'Oriental Velvet Desigual',
        'Oriental',
        'for women and men',
        NULL,
        'Christian Carbonnel',
        'Passionfruit and Apple',
        'Chocolate, Jasmine, Violet and Pepper',
        'Amber, Vanilla, Agarwood (Oud) and Sandalwood',
        'fruity,sweet,chocolate,warm spicy,fresh',
        'Oriental VelvetbyDesigualis a Amber fragrance for women and men.Oriental Velvetwas launched in 2015. Oriental Velvet was created by Christian Carbonnel and Rosendo Mateu. Top notes are Passionfruit and Apple; middle notes are Chocolate, Jasmine, Violet and Pepper; base notes are Amber, Vanilla, Agarwood (Oud) and Sandalwood.',
        3.5,
        6,
        NULL
      ),
(
        'Oud-Organza-32618',
        'Oud Organza Desigual',
        'Oud',
        'for women and men',
        NULL,
        'Christian Carbonnel',
        'Rose and Bergamot',
        'Cedar, Fruity Notes, Cinnamon and Cypriol Oil or Nagarmotha',
        'Patchouli, Tobacco, Vanilla and Incense',
        'woody,rose,patchouli,warm spicy,tobacco',
        'Oud OrganzabyDesigualis a Amber fragrance for women and men.Oud Organzawas launched in 2015. Oud Organza was created by Christian Carbonnel and Rosendo Mateu. Top notes are Rose and Bergamot; middle notes are Cedar, Fruity Notes, Cinnamon and Cypriol Oil or Nagarmotha; base notes are Patchouli, Tobacco, Vanilla and Incense.',
        3.38,
        8,
        NULL
      ),
(
        'Satin-Secrets-32620',
        'Satin Secrets Desigual',
        'Satin',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Satin SecretsbyDesigualis a Amber fragrance for women and men.Satin Secretswas launched in 2015.',
        4.4,
        10,
        NULL
      ),
(
        'Silk-Rose-32622',
        'Silk Rose Desigual',
        'Silk',
        'for women and men',
        NULL,
        'Olivier Cresp',
        NULL,
        NULL,
        NULL,
        NULL,
        'Silk RosebyDesigualis a Amber fragrance for women and men.Silk Rosewas launched in 2015. The nose behind this fragrance is Olivier Cresp.',
        4.33,
        3,
        NULL
      );
