
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Irresistible-Givenchy-Rose-Velvet-78480',
        'Irrésistible Givenchy Rose Velvet Givenchy',
        'Irrésistible',
        'for women',
        NULL,
        NULL,
        'Black Currant',
        'Rose Water, Rose and Iris',
        'Patchouli and Woodsy Notes',
        'rose,woody,iris,fruity,floral',
        'Irrésistible Givenchy Rose VelvetbyGivenchyis a fragrance for women. This is a new fragrance.Irrésistible Givenchy Rose Velvetwas launched in 2022. Irrésistible Givenchy Rose Velvet was created by Anne Flipo, Dominique Ropion and Fanny Bal. Top note is Black Currant; middle notes are Rose Water, Rose and Iris; base notes are Patchouli and Woodsy Notes.',
        3.81,
        654,
        NULL
      ),
(
        'Irresistible-Givenchy-Very-Floral-88896',
        'Irresistible Givenchy Very Floral Givenchy',
        'Irresistible',
        'for women',
        NULL,
        NULL,
        'Coconut Water, Black Currant and Bergamot',
        'Rose, Grasse Rose, Ylang Ylang, Iris and Jasmine Sambac',
        'Ambrette, Solar Notes, Ambrettolide, Sinfonide and Cedarwood',
        'floral,rose,musky,woody,amber',
        'Irresistible Givenchy Very FloralbyGivenchyis a Floral fragrance for women. This is a new fragrance.Irresistible Givenchy Very Floralwas launched in 2024. Irresistible Givenchy Very Floral was created by Anne Flipo, Dominique Ropion, Fanny Bal and Caroline Dumur. Top notes are Coconut Water, Black Currant and Bergamot; middle notes are Rose, Grasse Rose, Ylang Ylang, Iris and Jasmine Sambac; base notes are Ambrette, Solar Notes, Ambrettolide, Sinfonide and Cedarwood.',
        3.85,
        237,
        NULL
      ),
(
        'Irresistible-Hair-Mist-72811',
        'Irresistible Hair Mist Givenchy',
        'Irresistible',
        'for women',
        NULL,
        NULL,
        'Pear and Ambrette (Musk Mallow)',
        'Rose and Iris',
        'Virginia Cedar and Musk',
        'rose,musky,fruity,floral,powdery',
        'Irresistible Hair MistbyGivenchyis a Floral Woody Musk fragrance for women. This is a new fragrance.Irresistible Hair Mistwas launched in 2022. Irresistible Hair Mist was created by Anne Flipo, Dominique Ropion and Fanny Bal. Top notes are Pear and Ambrette (Musk Mallow); middle notes are Rose and Iris; base notes are Virginia Cedar and Musk.',
        4.43,
        14,
        NULL
      ),
(
        'L-Interdit-4695',
        'L''Interdit Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        'Francis Fabron',
        'Aldehydes, Strawberry, Spices, Peach, Bergamot and Mandarin Orange',
        'Iris, Violet, Narcissus, Orris Root, Rose, Ylang-Ylang, Jasmine and Lily-of-the-Valley',
        'Sandalwood, Amber, Musk, Benzoin, Vetiver and Tonka Bean',
        'powdery,woody,iris,amber,violet',
        'L''InterditbyGivenchyis a Floral Aldehyde fragrance for women.L''Interditwas launched in 1957. The nose behind this fragrance is Francis Fabron. Top notes are Aldehydes, Strawberry, Spices, Peach, Bergamot and Mandarin Orange; middle notes are Iris, Violet, Narcissus, Orris Root, Rose, Ylang-Ylang, Jasmine and Lily-of-the-Valley; base notes are Sandalwood, Amber, Musk, Benzoin, Vetiver and Tonka Bean.',
        4.17,
        591,
        NULL
      ),
(
        'L-Interdit-2-16785',
        'L''Interdit 2 Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Big Strawberry',
        'Violet, Sunflower, Bulgarian Rose, Jasmine, Freesia and Ylang-Ylang',
        'Sandalwood, Musk and Incense',
        'floral,powdery,sweet,violet,woody',
        'L''Interdit 2byGivenchyis a Floral fragrance for women.L''Interdit 2was launched in 1993. Top note is Big Strawberry; middle notes are Violet, Sunflower, Bulgarian Rose, Jasmine, Freesia and Ylang-Ylang; base notes are Sandalwood, Musk and Incense.',
        3.85,
        40,
        NULL
      ),
(
        'L-Interdit-2003-855',
        'L''Interdit 2003 Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Violet Leaf, Peony, Honeysuckle, Osmanthus, Bulgarian Rose and Peach',
        'Rose, Heliotrope, Peach, Tuberose, Plum, Orange Blossom and Strawberry',
        'Sandalwood, Oakmoss, Amber, Cedar, Patchouli and Musk',
        'fruity,floral,white floral,woody,powdery',
        'L''Interdit 2003byGivenchyis a Floral Fruity fragrance for women.L''Interdit 2003was launched in 2003. Top notes are Violet Leaf, Peony, Honeysuckle, Osmanthus, Bulgarian Rose and Peach; middle notes are Rose, Heliotrope, Peach, Tuberose, Plum, Orange Blossom and Strawberry; base notes are Sandalwood, Oakmoss, Amber, Cedar, Patchouli and Musk.',
        3.87,
        178,
        NULL
      ),
(
        'L-Interdit-Burning-Neroli-79235',
        'L''Interdit Burning Neroli Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Neroli',
        'Patchouli',
        'Vetiver',
        'woody,patchouli,citrus,white floral,earthy',
        'L''Interdit Burning NerolibyGivenchyis a Amber Floral fragrance for women. This is a new fragrance.L''Interdit Burning Neroliwas launched in 2023. Top note is Neroli; middle note is Patchouli; base note is Vetiver.',
        4.1,
        109,
        NULL
      ),
(
        'L-Interdit-Eau-de-Parfum-51488',
        'L''Interdit Eau de Parfum Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Pear and Bergamot',
        'Tuberose, Orange Blossom and Jasmine Sambac',
        'Patchouli, Vanilla, Ambroxan and Vetiver',
        'white floral,tuberose,sweet,woody,citrus',
        'L''Interdit Eau de ParfumbyGivenchyis a Amber Floral fragrance for women.L''Interdit Eau de Parfumwas launched in 2018. L''Interdit Eau de Parfum was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top notes are Pear and Bergamot; middle notes are Tuberose, Orange Blossom and Jasmine Sambac; base notes are Patchouli, Vanilla, Ambroxan and Vetiver.',
        3.96,
        10,
        NULL
      ),
(
        'L-Interdit-Eau-de-Parfum-Intense-62491',
        'L''Interdit Eau de Parfum Intense Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Black Pepper',
        'Tuberose, Sesame and Orange Blossom',
        'Madagascar Vanilla, Patchouli and Vetiver',
        'white floral,vanilla,tuberose,patchouli,woody',
        'L''Interdit Eau de Parfum IntensebyGivenchyis a Amber Floral fragrance for women.L''Interdit Eau de Parfum Intensewas launched in 2020. L''Interdit Eau de Parfum Intense was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top note is Black Pepper; middle notes are Tuberose, Sesame and Orange Blossom; base notes are Madagascar Vanilla, Patchouli and Vetiver.',
        4.16,
        3,
        NULL
      ),
(
        'L-Interdit-Eau-de-Parfum-Rouge-68404',
        'L''Interdit Eau de Parfum Rouge Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Ginger and Blood Orange',
        'Tuberose, Jasmine and Pimento Leaf',
        'Sandalwood, Patchouli and Vetiver',
        'warm spicy,white floral,woody,tuberose,citrus',
        'L''Interdit Eau de Parfum RougebyGivenchyis a Amber Floral fragrance for women.L''Interdit Eau de Parfum Rougewas launched in 2021. L''Interdit Eau de Parfum Rouge was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top notes are Ginger and Blood Orange; middle notes are Tuberose, Jasmine and Pimento Leaf; base notes are Sandalwood, Patchouli and Vetiver.',
        4.17,
        5,
        NULL
      ),
(
        'L-Interdit-Eau-de-Parfum-Rouge-Ultime-83865',
        'L''Interdit Eau de Parfum Rouge Ultime Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Tunisian Orange Blossom, Jasmine Sambac and Tunisian Neroli',
        'Indian Tuberose and Cacao Pod',
        'Indonesian Patchouli Leaf, Ambroxan, Haitian Vetiver and Tobacco',
        'white floral,tuberose,cacao,warm spicy,citrus',
        'L''Interdit Eau de Parfum Rouge UltimebyGivenchyis a Amber Floral fragrance for women. This is a new fragrance.L''Interdit Eau de Parfum Rouge Ultimewas launched in 2023. L''Interdit Eau de Parfum Rouge Ultime was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top notes are Tunisian Orange Blossom, Jasmine Sambac and Tunisian Neroli; middle notes are Indian Tuberose and Cacao Pod; base notes are Indonesian Patchouli Leaf, Ambroxan, Haitian Vetiver and Tobacco.',
        4.11,
        960,
        NULL
      ),
(
        'L-Interdit-Eau-de-Toilette-56144',
        'L''Interdit Eau de Toilette Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Poppy',
        'Tuberose, Orange Blossom and Musk',
        'Patchouli and Vetiver',
        'white floral,tuberose,woody,musky,animalic',
        'L''Interdit Eau de ToilettebyGivenchyis a Floral Woody Musk fragrance for women.L''Interdit Eau de Toilettewas launched in 2019. L''Interdit Eau de Toilette was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top note is Poppy; middle notes are Tuberose, Orange Blossom and Musk; base notes are Patchouli and Vetiver.',
        4.01,
        1,
        NULL
      ),
(
        'L-Interdit-Eau-de-Toilette-2022-75822',
        'L''Interdit Eau de Toilette (2022) Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Bitter Orange, Orange, Bergamot and Mandarin Orange',
        'Tuberose, Orange Blossom and Jasmine',
        'Musk, Cistus Incanus, Indonesian Patchouli Leaf, Sandalwood and Vetiver',
        'citrus,white floral,tuberose,woody,musky',
        'L''Interdit Eau de Toilette (2022)byGivenchyis a Floral fragrance for women. This is a new fragrance.L''Interdit Eau de Toilette (2022)was launched in 2022. Top notes are Bitter Orange, Orange, Bergamot and Mandarin Orange; middle notes are Tuberose, Orange Blossom and Jasmine; base notes are Musk, Cistus Incanus, Indonesian Patchouli Leaf, Sandalwood and Vetiver.',
        3.91,
        457,
        NULL
      ),
(
        'L-Interdit-Edition-Couture-53460',
        'L''Interdit Edition Couture Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Pear and Bergamot',
        'Tuberose, Tunisian Orange Blossom and Jasmine',
        'Vanilla, Patchouli, Ambroxan and Vetiver',
        'white floral,vanilla,tuberose,sweet,fruity',
        'L''Interdit Edition CouturebyGivenchyis a Amber Floral fragrance for women.L''Interdit Edition Couturewas launched in 2019. L''Interdit Edition Couture was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top notes are Pear and Bergamot; middle notes are Tuberose, Tunisian Orange Blossom and Jasmine; base notes are Vanilla, Patchouli, Ambroxan and Vetiver.',
        4.1,
        155,
        NULL
      ),
(
        'L-Interdit-Edition-Couture-2020-59335',
        'L''Interdit Edition Couture 2020 Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Pear and Bergamot',
        'Tuberose, Orange Blossom and Jasmine',
        'Patchouli, Ambroxan, Vanilla and Vetiver',
        'white floral,tuberose,citrus,patchouli,sweet',
        'L''Interdit Edition Couture 2020byGivenchyis a Chypre Floral fragrance for women.L''Interdit Edition Couture 2020was launched in 2020. L''Interdit Edition Couture 2020 was created by Dominique Ropion, Anne Flipo and Fanny Bal. Top notes are Pear and Bergamot; middle notes are Tuberose, Orange Blossom and Jasmine; base notes are Patchouli, Ambroxan, Vanilla and Vetiver.',
        4.33,
        105,
        NULL
      ),
(
        'L-Interdit-Edition-Millesime-64933',
        'L''Interdit Édition Millésime Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Bitter Orange and Ginger',
        'Orange Blossom, Tuberose and Neroli',
        'Almond Milk, Musk, Vetiver and Patchouli',
        'white floral,citrus,tuberose,warm spicy,fresh',
        'L''Interdit Édition MillésimebyGivenchyis a Amber Floral fragrance for women.L''Interdit Édition Millésimewas launched in 2021. L''Interdit Édition Millésime was created by Anne Flipo, Dominique Ropion and Fanny Bal. Top notes are Bitter Orange and Ginger; middle notes are Orange Blossom, Tuberose and Neroli; base notes are Almond Milk, Musk, Vetiver and Patchouli.',
        4.1,
        274,
        NULL
      ),
(
        'L-Interdit-Hair-Mist-59419',
        'L''Interdit Hair Mist Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Bergamot and Pear',
        'Tuberose, Orange Blossom and Jasmine',
        'Patchouli, Vanilla, Ambroxan and Vetiver',
        'white floral,citrus,patchouli,tuberose,woody',
        'L''Interdit Hair MistbyGivenchyis a Amber Floral fragrance for women.L''Interdit Hair Mistwas launched in 2020. L''Interdit Hair Mist was created by Dominique Ropion, Fanny Bal and Anne Flipo. Top notes are Bergamot and Pear; middle notes are Tuberose, Orange Blossom and Jasmine; base notes are Patchouli, Vanilla, Ambroxan and Vetiver.',
        4.35,
        75,
        NULL
      ),
(
        'L-Interdit-Nocturnal-Jasmine-71273',
        'L''Interdit Nocturnal Jasmine Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Indian Jasmine',
        'Vetiver',
        'Patchouli',
        'white floral,patchouli,woody,earthy,warm spicy',
        'L''Interdit Nocturnal JasminebyGivenchyis a Chypre Floral fragrance for women. This is a new fragrance.L''Interdit Nocturnal Jasminewas launched in 2022. Top note is Indian Jasmine; middle note is Vetiver; base note is Patchouli.',
        4.13,
        201,
        NULL
      ),
(
        'L-Interdit-Tubereuse-Noire-90200',
        'L''Interdit Tubéreuse Noire Givenchy',
        'L''Interdit',
        'for women',
        NULL,
        NULL,
        'Tuberose',
        'Tuberose and Orange Blossom',
        'Precious Woods, Coffee CO2, Patchouli and Vetiver',
        'white floral,tuberose,woody,animalic',
        'L''Interdit Tubéreuse NoirebyGivenchyis a Woody Floral Musk fragrance for women. This is a new fragrance.L''Interdit Tubéreuse Noirewas launched in 2024. Top note is Tuberose; middle notes are Tuberose and Orange Blossom; base notes are Precious Woods, Coffee CO2, Patchouli and Vetiver.',
        4.11,
        89,
        NULL
      ),
(
        'Ambre-Tigre-24592',
        'Ambre Tigré Givenchy',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,vanilla,powdery',
        'Ambre TigrébyGivenchyis a Amber fragrance for women and men.Ambre Tigréwas launched in 2014.',
        4.32,
        257,
        NULL
      ),
(
        'Ambre-Tigre-by-Anna-Borowski-49815',
        'Ambre Tigré by Anna Borowski Givenchy',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        'Amber',
        'Labdanum',
        'Vanilla',
        'amber,musky,woody,balsamic',
        'Ambre Tigré by Anna BorowskibyGivenchyis a Amber fragrance for women and men.Ambre Tigré by Anna Borowskiwas launched in 2018. Top note is Amber; middle note is Labdanum; base note is Vanilla.',
        5,
        3,
        NULL
      ),
(
        'Bois-Martial-24593',
        'Bois Martial Givenchy',
        'Bois',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,sweet,coconut,fruity,tropical',
        'Bois MartialbyGivenchyis a Woody fragrance for women and men.Bois Martialwas launched in 2014.',
        3.93,
        83,
        NULL
      ),
(
        'Chypre-Caresse-24595',
        'Chypre Caresse Givenchy',
        'Chypre',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,musky,amber,white floral,powdery',
        'Chypre CaressebyGivenchyis a Chypre fragrance for women and men.Chypre Caressewas launched in 2014.',
        4.27,
        158,
        NULL
      ),
(
        'Cuir-Blanc-24594',
        'Cuir Blanc Givenchy',
        'Cuir',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'leather,musky,fresh spicy,animalic,powdery',
        'Cuir BlancbyGivenchyis a Leather fragrance for women and men.Cuir Blancwas launched in 2014.',
        4.18,
        131,
        NULL
      ),
(
        'Encens-Divin-49606',
        'Encens Divin Givenchy',
        'Encens',
        'for women and men',
        NULL,
        'Joelle Lerioux Patris',
        'Ginger, Pink Pepper and Black Pepper',
        'Incense, Labdanum, Rose, Atlas Cedar, Texas Cedar and Cypriol Oil or Nagarmotha',
        'Tolu Balsam, Benzoin, Vanilla, Amberwood and Agarwood (Oud)',
        'amber,warm spicy,woody,balsamic,smoky',
        'Encens DivinbyGivenchyis a Amber Spicy fragrance for women and men.Encens Divinwas launched in 2018. Encens Divin was created by Nicolas Bonneville and Joelle Lerioux Patris. Top notes are Ginger, Pink Pepper and Black Pepper; middle notes are Incense, Labdanum, Rose, Atlas Cedar, Texas Cedar and Cypriol Oil or Nagarmotha; base notes are Tolu Balsam, Benzoin, Vanilla, Amberwood and Agarwood (Oud).',
        4.3,
        125,
        NULL
      ),
(
        'Gaiac-Mystique-31888',
        'Gaiac Mystique Givenchy',
        'Gaiac',
        'for women and men',
        NULL,
        NULL,
        'Iris Flower',
        'Guaiac Wood',
        'Tonka Bean and Incense',
        'woody,amber,iris,smoky,vanilla',
        'Gaiac MystiquebyGivenchyis a Woody fragrance for women and men.Gaiac Mystiquewas launched in 2015. Top note is Iris Flower; middle note is Guaiac Wood; base notes are Tonka Bean and Incense.',
        4.08,
        119,
        NULL
      ),
(
        'Immortelle-Tribal-31291',
        'Immortelle Tribal Givenchy',
        'Immortelle',
        'for women and men',
        NULL,
        'Alexandra Carlin',
        'Fig Leaf',
        'Immortelle',
        'Sandalwood',
        'herbal,warm spicy,woody,sweet,green',
        'Immortelle TribalbyGivenchyis a Amber Floral fragrance for women and men.Immortelle Tribalwas launched in 2015. The nose behind this fragrance is Alexandra Carlin. Top note is Fig Leaf; middle note is Immortelle; base note is Sandalwood.',
        4.14,
        176,
        NULL
      ),
(
        'Iris-Harmonique-38327',
        'Iris Harmonique Givenchy',
        'Iris',
        'for women and men',
        NULL,
        NULL,
        'Angelica, Immortelle, Ylang-Ylang and Tunisian Neroli',
        'White Iris, Leather, Amber, Coconut and Coumarin',
        'Guaiac Wood, Agarwood (Oud), Cedar, Tonka Bean and Sandalwood',
        'woody,powdery,amber,sweet,iris',
        'Iris HarmoniquebyGivenchyis a Amber Floral fragrance for women and men.Iris Harmoniquewas launched in 2016. Top notes are Angelica, Immortelle, Ylang-Ylang and Tunisian Neroli; middle notes are White Iris, Leather, Amber, Coconut and Coumarin; base notes are Guaiac Wood, Agarwood (Oud), Cedar, Tonka Bean and Sandalwood.',
        3.98,
        84,
        NULL
      ),
(
        'Myrrhe-Carmin-54108',
        'Myrrhe Carmin Givenchy',
        'Myrrhe',
        'for women and men',
        NULL,
        'Pierre-Constantin Guéros',
        'Ginger and Bergamot',
        'Myrrh and Bulgarian Rose',
        'Vanilla Absolute, Peru Balsam and Copahu Balm',
        'amber,balsamic,warm spicy,vanilla,rose',
        'Myrrhe CarminbyGivenchyis a Amber Spicy fragrance for women and men.Myrrhe Carminwas launched in 2019. The nose behind this fragrance is Pierre-Constantin Guéros. Top notes are Ginger and Bergamot; middle notes are Myrrh and Bulgarian Rose; base notes are Vanilla Absolute, Peru Balsam and Copahu Balm.',
        4.58,
        31,
        NULL
      ),
(
        'Neroli-Originel-24597',
        'Néroli Originel Givenchy',
        'Néroli',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,iris,vanilla,musky,white floral',
        'Néroli OriginelbyGivenchyis a Floral Woody Musk fragrance for women and men.Néroli Originelwas launched in 2014.',
        4.07,
        98,
        NULL
      ),
(
        'Oud-Flamboyant-24596',
        'Oud Flamboyant Givenchy',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,amber,leather,musky,animalic',
        'Oud FlamboyantbyGivenchyis a Amber fragrance for women and men.Oud Flamboyantwas launched in 2014.',
        4.27,
        141,
        NULL
      ),
(
        'Patchouli-de-Minuit-55790',
        'Patchouli de Minuit Givenchy',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Olibanum and Saffron',
        'Lavender and Davana',
        'Patchouli, Cashmeran and Tonka Bean',
        'woody,patchouli,warm spicy,amber,aromatic',
        'Patchouli de MinuitbyGivenchyis a Amber Woody fragrance for women and men.Patchouli de Minuitwas launched in 2019. Top notes are Olibanum and Saffron; middle notes are Lavender and Davana; base notes are Patchouli, Cashmeran and Tonka Bean.',
        4.14,
        14,
        NULL
      ),
(
        'Rose-Ardente-43973',
        'Rose Ardente Givenchy',
        'Rose',
        'for women',
        NULL,
        'Joelle Lerioux Patris',
        'Black Currant and Bergamot',
        'Rose',
        'Amber, Honey, Vanilla and Patchouli',
        'rose,floral,amber,honey,fruity',
        'Rose ArdentebyGivenchyis a Chypre Floral fragrance for women.Rose Ardentewas launched in 2017. Rose Ardente was created by Nicolas Bonneville and Joelle Lerioux Patris. Top notes are Black Currant and Bergamot; middle note is Rose; base notes are Amber, Honey, Vanilla and Patchouli.',
        4.17,
        109,
        NULL
      ),
(
        'Ylang-Austral-24598',
        'Ylang Austral Givenchy',
        'Ylang',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,yellow floral,sweet,powdery,aromatic',
        'Ylang AustralbyGivenchyis a Floral fragrance for women and men.Ylang Australwas launched in 2014.',
        4.11,
        111,
        NULL
      ),
(
        'Accord-Particulier-60357',
        'Accord Particulier Givenchy',
        'Accord',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,earthy,rose,musky',
        'Accord ParticulierbyGivenchyis a Chypre Floral fragrance for women and men.Accord Particulierwas launched in 2020.',
        4.12,
        122,
        NULL
      ),
(
        'Coeur-Fou-91126',
        'Cœur Fou Givenchy',
        'Cœur',
        'for women and men',
        NULL,
        'Alexandra Monet',
        'Cassis and Basil',
        'Bulgarian Rose, Turkish Rose and Damask Rose',
        'Indonesian Patchouli Leaf and Moss',
        'rose,aromatic,green,fruity,soft spicy',
        'Cœur FoubyGivenchyis a Chypre Floral fragrance for women and men. This is a new fragrance.Cœur Fouwas launched in 2024. The nose behind this fragrance is Alexandra Monet. Top notes are Cassis and Basil; middle notes are Bulgarian Rose, Turkish Rose and Damask Rose; base notes are Indonesian Patchouli Leaf and Moss.',
        4.14,
        14,
        NULL
      ),
(
        'Desinvolte-68973',
        'Dèsinvolte Givenchy',
        'Dèsinvolte',
        'for women and men',
        NULL,
        NULL,
        'Tuberose and Haitian Vetiver',
        'Jasmine and Orange Blossom',
        'Ambroxan',
        'white floral,tuberose,amber,animalic',
        'DèsinvoltebyGivenchyis a Amber Floral fragrance for women and men.Dèsinvoltewas launched in 2021. Top notes are Tuberose and Haitian Vetiver; middle notes are Jasmine and Orange Blossom; base note is Ambroxan.',
        4.22,
        58,
        NULL
      ),
(
        'Enflamme-60358',
        'Enflammé Givenchy',
        'Enflammé',
        'for women and men',
        NULL,
        'Amandine Clerc-Marie',
        NULL,
        NULL,
        NULL,
        'tobacco,vanilla,sweet,coffee,warm spicy',
        'EnflammébyGivenchyis a Amber Vanilla fragrance for women and men.Enflamméwas launched in 2020. The nose behind this fragrance is Amandine Clerc-Marie.',
        4.37,
        174,
        NULL
      ),
(
        'Equivoque-73010',
        'Équivoque Givenchy',
        'Équivoque',
        'for women and men',
        NULL,
        NULL,
        'Guatemalan Cardamom',
        'Atlas Cedar, Virginian Cedar and Guaiac Wood',
        'Agarwood (Oud)',
        'oud,warm spicy,woody,aromatic',
        'ÉquivoquebyGivenchyis a Woody Spicy fragrance for women and men. This is a new fragrance.Équivoquewas launched in 2022. Top note is Guatemalan Cardamom; middle notes are Atlas Cedar, Virginian Cedar and Guaiac Wood; base note is Agarwood (Oud).',
        4.2,
        81,
        NULL
      ),
(
        'Fantasque-89991',
        'Fantasque Givenchy',
        'Fantasque',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,balsamic,warm spicy,smoky,sweet',
        'FantasquebyGivenchyis a Woody Aromatic fragrance for women and men. This is a new fragrance.Fantasquewas launched in 2024.',
        4.22,
        27,
        NULL
      ),
(
        'Faux-Semblant-79157',
        'Faux Semblant Givenchy',
        'Faux',
        'for women and men',
        NULL,
        NULL,
        'Olibanum and Angelica',
        'Orange Blossom, Honey, Patchouli, Amber and Spanish Labdanum',
        'Agarwood (Oud) and White Sandalwood',
        'amber,white floral,honey,sweet,woody',
        'Faux SemblantbyGivenchyis a Amber Woody fragrance for women and men. This is a new fragrance.Faux Semblantwas launched in 2023. Top notes are Olibanum and Angelica; middle notes are Orange Blossom, Honey, Patchouli, Amber and Spanish Labdanum; base notes are Agarwood (Oud) and White Sandalwood.',
        3.98,
        53,
        NULL
      ),
(
        'Foudroyant-73009',
        'Foudroyant Givenchy',
        'Foudroyant',
        'for women and men',
        NULL,
        NULL,
        'Cedar',
        'Tolu Balsam and Labdanum',
        'Agarwood (Oud)',
        'amber,powdery,oud,woody,balsamic',
        'FoudroyantbyGivenchyis a Amber Woody fragrance for women and men. This is a new fragrance.Foudroyantwas launched in 2022. Top note is Cedar; middle notes are Tolu Balsam and Labdanum; base note is Agarwood (Oud).',
        4.35,
        89,
        NULL
      ),
(
        'Garcon-Manque-60356',
        'Garçon Manqué Givenchy',
        'Garçon',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'leather,floral,fruity,animalic,smoky',
        'Garçon ManquébyGivenchyis a Leather fragrance for women and men.Garçon Manquéwas launched in 2020.',
        4.18,
        189,
        NULL
      ),
(
        'Indompte-60355',
        'Indompté Givenchy',
        'Indompté',
        'for women and men',
        NULL,
        'Olivier Cresp',
        NULL,
        NULL,
        NULL,
        'leather,citrus,animalic,oud,smoky',
        'IndomptébyGivenchyis a Leather fragrance for women and men.Indomptéwas launched in 2020. The nose behind this fragrance is Olivier Cresp.',
        4.43,
        93,
        NULL
      ),
(
        'MMW-74819',
        'MMW Givenchy',
        'MMW',
        'for women and men',
        NULL,
        NULL,
        'Guatemalan Cardamom',
        'Palo Santo',
        'Ambroxan, Atlas Cedar, Virginia Cedar, Iso E Super and Haitian Vetiver',
        'woody,amber,musky,aromatic',
        'MMWbyGivenchyis a Woody fragrance for women and men. This is a new fragrance.MMWwas launched in 2022. Top note is Guatemalan Cardamom; middle note is Palo Santo; base notes are Ambroxan, Atlas Cedar, Virginia Cedar, Iso E Super and Haitian Vetiver.',
        3.92,
        95,
        NULL
      ),
(
        'Noctambule-73012',
        'Noctambule Givenchy',
        'Noctambule',
        'for women and men',
        NULL,
        'Ane Ayo',
        'Grasse Rose, Pink Pepper and Cumin',
        'Papyrus',
        'Agarwood (Oud)',
        'rose,oud,fresh spicy,floral,soft spicy',
        'NoctambulebyGivenchyis a Amber Floral fragrance for women and men. This is a new fragrance.Noctambulewas launched in 2022. The nose behind this fragrance is Ane Ayo. Top notes are Grasse Rose, Pink Pepper and Cumin; middle note is Papyrus; base note is Agarwood (Oud).',
        4.04,
        96,
        NULL
      ),
(
        'Oiseau-Rare-60353',
        'Oiseau Rare Givenchy',
        'Oiseau',
        'for women and men',
        NULL,
        'Olivier Cresp',
        NULL,
        NULL,
        NULL,
        'white floral,sweet,fresh spicy',
        'Oiseau RarebyGivenchyis a Floral fragrance for women and men.Oiseau Rarewas launched in 2020. The nose behind this fragrance is Olivier Cresp.',
        3.92,
        62,
        NULL
      ),
(
        'Peur-de-Rien-60354',
        'Peur de Rien Givenchy',
        'Peur',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'yellow floral,citrus,green,sweet,aromatic',
        'Peur de RienbyGivenchyis a Floral Fruity fragrance for women and men.Peur de Rienwas launched in 2020.',
        4.1,
        42,
        NULL
      ),
(
        'Sans-Artifice-60352',
        'Sans Artifice Givenchy',
        'Sans',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,warm spicy,fresh,ozonic,citrus',
        'Sans ArtificebyGivenchyis a Aromatic Spicy fragrance for women and men.Sans Artificewas launched in 2020.',
        4.1,
        42,
        NULL
      ),
(
        'Sans-Merci-60351',
        'Sans Merci Givenchy',
        'Sans',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,green,woody,earthy,balsamic',
        'Sans MercibyGivenchyis a Amber Woody fragrance for women and men.Sans Merciwas launched in 2020.',
        4.04,
        67,
        NULL
      ),
(
        'Temeraire-83647',
        'Téméraire Givenchy',
        'Téméraire',
        'for women and men',
        NULL,
        'Nicolas Bonneville',
        'Clove Leaf and Cardamom',
        'Tuberose, Jasmine and Iris',
        'Ink, Cade oil and Benzoin',
        'white floral,aromatic,tuberose,woody,warm spicy',
        'TémérairebyGivenchyis a Amber Floral fragrance for women and men. This is a new fragrance.Témérairewas launched in 2023. The nose behind this fragrance is Nicolas Bonneville. Top notes are Clove Leaf and Cardamom; middle notes are Tuberose, Jasmine and Iris; base notes are Ink, Cade oil and Benzoin.',
        4.13,
        38,
        NULL
      ),
(
        'Trouble-Fete-60350',
        'Trouble-Fête Givenchy',
        'Trouble-Fête',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,fresh,fruity,sweet,woody',
        'Trouble-FêtebyGivenchyis a Aromatic Fruity fragrance for women and men.Trouble-Fêtewas launched in 2020.',
        4.22,
        142,
        NULL
      ),
(
        'Les-Creations-Couture-Ange-Ou-Demon-Le-Secret-Lace-Edition-14967',
        'Les Creations Couture Ange Ou Demon Le Secret Lace Edition Givenchy',
        'Les',
        'for women',
        NULL,
        NULL,
        'Lemon and Green Tea',
        'Jasmine and Lily-of-the-Valley',
        'Woody Notes and Patchouli',
        'woody,white floral,patchouli,citrus,fresh',
        'Les Creations Couture Ange Ou Demon Le Secret Lace EditionbyGivenchyis a Floral fragrance for women.Les Creations Couture Ange Ou Demon Le Secret Lace Editionwas launched in 2012. Top notes are Lemon and Green Tea; middle notes are Jasmine and Lily-of-the-Valley; base notes are Woody Notes and Patchouli.',
        4.27,
        48,
        NULL
      ),
(
        'Les-Creations-Couture-Organza-Lace-Edition-14968',
        'Les Creations Couture Organza Lace Edition Givenchy',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,woody,vanilla,nutty,fresh spicy',
        'Les Creations Couture Organza Lace EditionbyGivenchyis a Amber Floral fragrance for women.Les Creations Couture Organza Lace Editionwas launched in 2012.',
        4.19,
        80,
        NULL
      ),
(
        'Les-Creations-Couture-Pi-Leather-Edition-14970',
        'Les Creations Couture Pi Leather Edition Givenchy',
        'Les',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,fresh spicy,sweet,vanilla',
        'Les Creations Couture Pi Leather EditionbyGivenchyis a Amber fragrance for men.Les Creations Couture Pi Leather Editionwas launched in 2012.',
        4.04,
        25,
        NULL
      ),
(
        'Les-Creations-Couture-Play-For-Him-Leather-Edition-14969',
        'Les Creations Couture Play For Him Leather Edition Givenchy',
        'Les',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,warm spicy,coffee,fresh spicy',
        'Les Creations Couture Play For Him Leather EditionbyGivenchyis a Woody fragrance for men.Les Creations Couture Play For Him Leather Editionwas launched in 2012.',
        4.41,
        46,
        NULL
      ),
(
        'Les-Creations-Couture-Very-Irresistible-Givenchy-Lace-Edition-14966',
        'Les Creations Couture Very Irresistible Givenchy Lace Edition Givenchy',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,rose,anis,soft spicy,fruity',
        'Les Creations Couture Very Irresistible Givenchy Lace EditionbyGivenchyis a Floral fragrance for women.Les Creations Couture Very Irresistible Givenchy Lace Editionwas launched in 2012.',
        4.38,
        40,
        NULL
      ),
(
        'Live-Irresistible-31294',
        'Live Irrésistible Givenchy',
        'Live',
        'for women',
        NULL,
        'Dominique Ropion',
        'Pineapple, Rose Petals, Tangerine and Grapefruit',
        'Passionfruit, Pepper and Rose',
        'Praline, Vanilla, Patchouli, Amber, Musk and Orris',
        'sweet,fruity,tropical,fresh spicy,fresh',
        'Live IrrésistiblebyGivenchyis a Floral Fruity fragrance for women.Live Irrésistiblewas launched in 2015. The nose behind this fragrance is Dominique Ropion. Top notes are Pineapple, Rose Petals, Tangerine and Grapefruit; middle notes are Passionfruit, Pepper and Rose; base notes are Praline, Vanilla, Patchouli, Amber, Musk and Orris.',
        3.77,
        1,
        NULL
      ),
(
        'Live-Irresistible-Blossom-Crush-48253',
        'Live Irrésistible Blossom Crush Givenchy',
        'Live',
        'for women',
        NULL,
        'Dominique Ropion',
        'Bitter Orange and Bergamot',
        'Peony, Apple, Black Currant, Raspberry and Rose',
        'Cacao, Vanilla, Cashmeran, Musk and Amberwood',
        'fruity,floral,fresh,rose,cacao',
        'Live Irrésistible Blossom CrushbyGivenchyis a Floral Fruity fragrance for women.Live Irrésistible Blossom Crushwas launched in 2018. The nose behind this fragrance is Dominique Ropion. Top notes are Bitter Orange and Bergamot; middle notes are Peony, Apple, Black Currant, Raspberry and Rose; base notes are Cacao, Vanilla, Cashmeran, Musk and Amberwood.',
        3.85,
        961,
        NULL
      ),
(
        'Live-Irresistible-Delicieuse-43336',
        'Live Irrésistible Délicieuse Givenchy',
        'Live',
        'for women',
        NULL,
        'Dominique Ropion',
        'French pastries and Cherry',
        'Rose and Orange Blossom',
        'Caramel, Bitter Almond, Vanilla and Orris Root',
        'sweet,almond,cherry,caramel,fruity',
        'Live Irrésistible DélicieusebyGivenchyis a Floral Fruity Gourmand fragrance for women.Live Irrésistible Délicieusewas launched in 2017. The nose behind this fragrance is Dominique Ropion. Top notes are French pastries and Cherry; middle notes are Rose and Orange Blossom; base notes are Caramel, Bitter Almond, Vanilla and Orris Root.',
        4.11,
        887,
        NULL
      ),
(
        'Live-Irresistible-Eau-de-Toilette-36351',
        'Live Irrésistible Eau de Toilette Givenchy',
        'Live',
        'for women',
        NULL,
        'Dominique Ropion',
        'Raspberry, Pear, Pineapple, Grapefruit and Lemon',
        'Red Berries, Peach, Pepper, Rose, Green Notes and Lily-of-the-Valley',
        'Caramel, Vanilla, Musk, Amberwood, Patchouli, Violet and White Woods',
        'fruity,sweet,caramel,fresh,vanilla',
        'Live Irrésistible Eau de ToilettebyGivenchyis a Floral Fruity fragrance for women.Live Irrésistible Eau de Toilettewas launched in 2016. The nose behind this fragrance is Dominique Ropion. Top notes are Raspberry, Pear, Pineapple, Grapefruit and Lemon; middle notes are Red Berries, Peach, Pepper, Rose, Green Notes and Lily-of-the-Valley; base notes are Caramel, Vanilla, Musk, Amberwood, Patchouli, Violet and White Woods.',
        3.86,
        605,
        NULL
      ),
(
        'Live-Irresistible-Rosy-Crush-53032',
        'Live Irrésistible Rosy Crush Givenchy',
        'Live',
        'for women',
        NULL,
        'Dominique Ropion',
        'Goji Berries, Pink Pepper, Orange, Lemon and Bergamot',
        'Rose and Peony',
        'Musk, Patchouli, Vanilla and Ambroxan',
        'rose,floral,musky,citrus,fresh',
        'Live Irrésistible Rosy CrushbyGivenchyis a Chypre Floral fragrance for women.Live Irrésistible Rosy Crushwas launched in 2019. Live Irrésistible Rosy Crush was created by Dominique Ropion and Fanny Bal. Top notes are Goji Berries, Pink Pepper, Orange, Lemon and Bergamot; middle notes are Rose and Peony; base notes are Musk, Patchouli, Vanilla and Ambroxan.',
        3.85,
        605,
        NULL
      ),
(
        'Oblique-Fast-Forward-2977',
        'Oblique Fast Forward Givenchy',
        'Oblique',
        'for women and men',
        NULL,
        'Alberto Morillas',
        'Sea water, Melon and Green Notes',
        'Jasmine and Sichuan Pepper',
        'Cedar and Musk',
        'marine,aquatic,aromatic,ozonic,salty',
        'Oblique Fast ForwardbyGivenchyis a Floral Green fragrance for women and men.Oblique Fast Forwardwas launched in 2000. Oblique Fast Forward was created by Ilias Ermenidis and Alberto Morillas. Top notes are Sea water, Melon and Green Notes; middle notes are Jasmine and Sichuan Pepper; base notes are Cedar and Musk.',
        4.23,
        592,
        NULL
      ),
(
        'Oblique-Play-2978',
        'Oblique Play Givenchy',
        'Oblique',
        'for women and men',
        NULL,
        'Jean Claude Delville',
        'Lemon, Bergamot and Gardenia',
        'Praline, White Pepper and Rose',
        'Sandalwood and White Musk',
        'citrus,fresh spicy,sweet,aromatic,white floral',
        'Oblique PlaybyGivenchyis a Floral Fruity fragrance for women and men.Oblique Playwas launched in 2000. Oblique Play was created by Jean Claude Delville and Pascal Gaurin. Top notes are Lemon, Bergamot and Gardenia; middle notes are Praline, White Pepper and Rose; base notes are Sandalwood and White Musk.',
        4.09,
        385,
        NULL
      ),
(
        'Oblique-Rewind-2979',
        'Oblique Rewind Givenchy',
        'Oblique',
        'for women and men',
        NULL,
        'Nathalie Lorson',
        'Cherry, Pistachio and Bergamot',
        'Honey, Cashmere Wood and Jasmine',
        'Patchouli, Amber, Sandalwood and Cedar',
        'woody,cherry,sweet,honey,patchouli',
        'Oblique RewindbyGivenchyis a Amber fragrance for women and men.Oblique Rewindwas launched in 2000. The nose behind this fragrance is Nathalie Lorson. Top notes are Cherry, Pistachio and Bergamot; middle notes are Honey, Cashmere Wood and Jasmine; base notes are Patchouli, Amber, Sandalwood and Cedar.',
        4.14,
        292,
        NULL
      ),
(
        'Organza-4',
        'Organza Givenchy',
        'Organza',
        'for women',
        NULL,
        'Sophie Labbé',
        'Nutmeg, Gardenia, African Orange Flower, Green Notes and Bergamot',
        'Tuberose, Jasmine, Honeysuckle, Iris, Peony and Mace',
        'Vanilla, Amber, Woodsy Notes, Guaiac Wood and Virginia Cedar',
        'white floral,fresh spicy,woody,vanilla,tuberose',
        'OrganzabyGivenchyis a Amber Floral fragrance for women.Organzawas launched in 1996. The nose behind this fragrance is Sophie Labbe. Top notes are Nutmeg, Gardenia, African Orange Flower, Green Notes and Bergamot; middle notes are Tuberose, Jasmine, Honeysuckle, Iris, Peony and Mace; base notes are Vanilla, Amber, Woodsy Notes, Guaiac Wood and Virginia Cedar.',
        3.95,
        10,
        NULL
      ),
(
        'Organza-Eau-d-Ete-Parfumee-42011',
        'Organza Eau d''Été Parfumée Givenchy',
        'Organza',
        'for women',
        NULL,
        NULL,
        'Green Notes, Bergamot, Gardenia, Grapes and Neroli',
        'Walnut, Tuberose, Peony, Jasmine, Honeysuckle and Iris',
        'Woody Notes, Vanilla, Amber, Guaiac Wood and Cedar',
        'woody,white floral,green,floral,nutty',
        'Organza Eau d''Été ParfuméebyGivenchyis a Floral fragrance for women. Top notes are Green Notes, Bergamot, Gardenia, Grapes and Neroli; middle notes are Walnut, Tuberose, Peony, Jasmine, Honeysuckle and Iris; base notes are Woody Notes, Vanilla, Amber, Guaiac Wood and Cedar.',
        4.2,
        55,
        NULL
      ),
(
        'Organza-Eau-de-Toilette-du-Desert-41907',
        'Organza Eau de Toilette du Desert Givenchy',
        'Organza',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,powdery,amber,fresh spicy,vanilla',
        'Organza Eau de Toilette du DesertbyGivenchyis a Amber fragrance for women and men.Organza Eau de Toilette du Desertwas launched in 2001.',
        4.21,
        42,
        NULL
      ),
(
        'Organza-First-Light-559',
        'Organza First Light Givenchy',
        'Organza',
        'for women',
        NULL,
        'Sophie Labbé',
        'Honeysuckle, Lemon and Lily-of-the-Valley',
        'Gardenia, Ylang-Ylang and Jasmine',
        'Vanilla, Benzoin and Woodsy Notes',
        'white floral,yellow floral,vanilla,woody,amber',
        'Organza First LightbyGivenchyis a Amber Floral fragrance for women.Organza First Lightwas launched in 2004. The nose behind this fragrance is Sophie Labbe. Top notes are Honeysuckle, Lemon and Lily-of-the-Valley; middle notes are Gardenia, Ylang-Ylang and Jasmine; base notes are Vanilla, Benzoin and Woodsy Notes.',
        3.91,
        406,
        NULL
      ),
(
        'Organza-Gold-Collection-10-Years-Anniversary-Limited-Edition-40467',
        'Organza Gold Collection (10 Years Anniversary Limited Edition) Givenchy',
        'Organza',
        'for women',
        NULL,
        'Sophie Labbé',
        'Tuberose and Ylang-Ylang',
        'Jasmine and Honeysuckle',
        'Vanilla, Amber, Sandalwood and Cedar',
        'white floral,woody,tuberose,vanilla,amber',
        'Organza Gold Collection (10 Years Anniversary Limited Edition)byGivenchyis a fragrance for women.Organza Gold Collection (10 Years Anniversary Limited Edition)was launched in 2006. The nose behind this fragrance is Sophie Labbe. Top notes are Tuberose and Ylang-Ylang; middle notes are Jasmine and Honeysuckle; base notes are Vanilla, Amber, Sandalwood and Cedar.',
        4.08,
        24,
        NULL
      ),
(
        'Organza-Indecence-560',
        'Organza Indécence Givenchy',
        'Organza',
        'for women',
        NULL,
        'Jean Claude Delville',
        'Brazilian Rosewood and Patchouli',
        'Ceylon Cinnamon and Plum',
        'Vanilla, Amber and Musk',
        'warm spicy,cinnamon,vanilla,amber,woody',
        'Organza IndécencebyGivenchyis a Amber Woody fragrance for women.Organza Indécencewas launched in 1999. Organza Indécence was created by Norbert Bijaoui and Jean Claude Delville. Top notes are Brazilian Rosewood and Patchouli; middle notes are Ceylon Cinnamon and Plum; base notes are Vanilla, Amber and Musk.',
        4.4,
        2,
        NULL
      ),
(
        'Organza-Indecence-Eau-de-Toilette-du-Desert-42010',
        'Organza Indecence Eau de Toilette du Desert Givenchy',
        'Organza',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange',
        'Spicy Notes and Plum',
        'Amber and Musk',
        'fruity,amber,citrus,warm spicy,sweet',
        'Organza Indecence Eau de Toilette du DesertbyGivenchyis a Amber fragrance for women.Organza Indecence Eau de Toilette du Desertwas launched in 2006. Top note is Mandarin Orange; middle notes are Spicy Notes and Plum; base notes are Amber and Musk.',
        4.63,
        30,
        NULL
      ),
(
        'Organza-Indian-Jasmin-851',
        'Organza Indian Jasmin Givenchy',
        'Organza',
        'for women',
        NULL,
        NULL,
        'Honeysuckle',
        'Jasmine',
        'Nutmeg, Vanilla and Cedar',
        'white floral,fresh spicy,vanilla,woody,powdery',
        'Organza Indian JasminbyGivenchyis a Amber Floral fragrance for women.Organza Indian Jasminwas launched in 2005. Top note is Honeysuckle; middle note is Jasmine; base notes are Nutmeg, Vanilla and Cedar.',
        4.22,
        175,
        NULL
      ),
(
        'Organza-Legere-Eau-de-Toilette-13610',
        'Organza Legere (Eau de Toilette) Givenchy',
        'Organza',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,vanilla,amber,fresh spicy,lactonic',
        'Organza Legere (Eau de Toilette)byGivenchyis a Amber Floral fragrance for women.Organza Legere (Eau de Toilette)was launched in 2011.',
        3.92,
        154,
        NULL
      ),
(
        'Givenchy-Play-Eau-de-Toilette-3906',
        'Givenchy Play Eau de Toilette Givenchy',
        'Givenchy',
        'for men',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Bitter Orange, Grapefruit, Bergamot and Mandarin Orange',
        'Coffee, Pepper, Amyris and Tobacco Blossom',
        'Vetyver and Patchouli',
        'citrus,fresh spicy,warm spicy,woody,aromatic',
        'Givenchy Play Eau de ToilettebyGivenchyis a Citrus Aromatic fragrance for men.Givenchy Play Eau de Toilettewas launched in 2008. Givenchy Play Eau de Toilette was created by Emilie Bevierre-Coppermann and Lucas Sieuzac. Top notes are Bitter Orange, Grapefruit, Bergamot and Mandarin Orange; middle notes are Coffee, Pepper, Amyris and Tobacco Blossom; base notes are Vetyver and Patchouli.',
        3.9,
        1,
        NULL
      ),
(
        'Givenchy-Play-Intense-3907',
        'Givenchy Play Intense Givenchy',
        'Givenchy',
        'for men',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Mandarin Orange and Bergamot',
        'Coffee, Pink Pepper and Amyris',
        'Tonka Bean, Patchouli, Vetyver and French labdanum',
        'coffee,warm spicy,woody,aromatic,amber',
        'Givenchy Play IntensebyGivenchyis a Amber Fougere fragrance for men.Givenchy Play Intensewas launched in 2008. Givenchy Play Intense was created by Emilie Bevierre-Coppermann and Lucas Sieuzac. Top notes are Mandarin Orange and Bergamot; middle notes are Coffee, Pink Pepper and Amyris; base notes are Tonka Bean, Patchouli, Vetyver and French labdanum.',
        4.21,
        2,
        NULL
      ),
(
        'Play-For-Her-9369',
        'Play For Her Givenchy',
        'Play',
        'for women',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Pink Pepper, Peach, Orange Blossom, Sweet Pea and Bergamot',
        'Orchid, Tiare Flower, Amyris and Magnolia',
        'Tonka Bean, Sandalwood, Musk, Patchouli and Benzoin',
        'sweet,floral,white floral,woody,powdery',
        'Play For HerbyGivenchyis a Amber Floral fragrance for women.Play For Herwas launched in 2010. Play For Her was created by Emilie Bevierre-Coppermann and Lucas Sieuzac. Top notes are Pink Pepper, Peach, Orange Blossom, Sweet Pea and Bergamot; middle notes are Orchid, Tiare Flower, Amyris and Magnolia; base notes are Tonka Bean, Sandalwood, Musk, Patchouli and Benzoin.',
        3.73,
        3,
        NULL
      ),
(
        'Play-For-Her-Eau-de-Toilette-19050',
        'Play For Her Eau de Toilette Givenchy',
        'Play',
        'for women',
        NULL,
        NULL,
        'White Currant and Peach',
        'Licorice, Amyris and White Iris',
        'Musk',
        'fruity,sweet,soft spicy,powdery,musky',
        'Play For Her Eau de ToilettebyGivenchyis a Floral Fruity fragrance for women.Play For Her Eau de Toilettewas launched in 2013. Top notes are White Currant and Peach; middle notes are Licorice, Amyris and White Iris; base note is Musk.',
        3.84,
        319,
        NULL
      ),
(
        'Play-For-Her-Intense-10225',
        'Play For Her Intense Givenchy',
        'Play',
        'for women',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Pink Pepper, Peach and Orange Blossom',
        'Orchid, Tiare Flower, Magnolia and Amyris',
        'Tonka Bean, Benzoin, Patchouli and Sandalwood',
        'sweet,woody,amber,warm spicy,floral',
        'Play For Her IntensebyGivenchyis a Amber Floral fragrance for women.Play For Her Intensewas launched in 2010. Play For Her Intense was created by Emilie Bevierre-Coppermann and Lucas Sieuzac. Top notes are Pink Pepper, Peach and Orange Blossom; middle notes are Orchid, Tiare Flower, Magnolia and Amyris; base notes are Tonka Bean, Benzoin, Patchouli and Sandalwood.',
        3.98,
        1,
        NULL
      ),
(
        'Play-in-the-City-for-Her-17503',
        'Play in the City for Her Givenchy',
        'Play',
        'for women',
        NULL,
        NULL,
        'Red Berries and Licorice',
        'Amyris, Tiare Flower and Iris',
        'Vanilla, Musk and Sandalwood',
        'fruity,sweet,woody,soft spicy,balsamic',
        'Play in the City for HerbyGivenchyis a Amber Floral fragrance for women.Play in the City for Herwas launched in 2013. Top notes are Red Berries and Licorice; middle notes are Amyris, Tiare Flower and Iris; base notes are Vanilla, Musk and Sandalwood.',
        3.67,
        84,
        NULL
      ),
(
        'Play-in-the-City-for-Him-17504',
        'Play in the City for Him Givenchy',
        'Play',
        'for men',
        NULL,
        NULL,
        'Licorice and Citruses',
        'Amyris and Iris',
        'Amber and Woody Notes',
        'woody,soft spicy,amber,citrus,iris',
        'Play in the City for HimbyGivenchyis a Woody Spicy fragrance for men.Play in the City for Himwas launched in 2013. Top notes are Licorice and Citruses; middle notes are Amyris and Iris; base notes are Amber and Woody Notes.',
        3.62,
        65,
        NULL
      ),
(
        'Play-Sport-14596',
        'Play Sport Givenchy',
        'Play',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot, Ginger flower and Mint',
        'Amyris and Pepper',
        'Musk',
        'citrus,aromatic,fresh spicy,warm spicy,green',
        'Play SportbyGivenchyis a Citrus Aromatic fragrance for men.Play Sportwas launched in 2012. Top notes are Lemon, Bergamot, Ginger flower and Mint; middle notes are Amyris and Pepper; base note is Musk.',
        3.74,
        405,
        NULL
      ),
(
        'Play-Summer-Vibrations-8196',
        'Play Summer Vibrations Givenchy',
        'Play',
        'for men',
        NULL,
        NULL,
        'Citruses and Coriander',
        'Sea water and Pepper',
        'Amyris',
        'aromatic,citrus,marine,woody,fresh spicy',
        'Play Summer VibrationsbyGivenchyis a Woody Aquatic fragrance for men.Play Summer Vibrationswas launched in 2010. Top notes are Citruses and Coriander; middle notes are Sea water and Pepper; base note is Amyris.',
        3.91,
        67,
        NULL
      ),
(
        'Very-Irresistible-33',
        'Very Irresistible Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'Cassia, Lemon Verbena and Star Anise',
        'Rose, Peony and Magnolia',
        'Taif Rose, Musk, Vanilla and Patchouli',
        'rose,floral,fresh,citrus,aromatic',
        'Very IrresistiblebyGivenchyis a Floral Fruity fragrance for women.Very Irresistiblewas launched in 2003. Very Irresistible was created by Dominique Ropion, Sophie Labbe and Carlos Benaim. Top notes are Cassia, Lemon Verbena and Star Anise; middle notes are Rose, Peony and Magnolia; base notes are Taif Rose, Musk, Vanilla and Patchouli.',
        3.89,
        6,
        NULL
      ),
(
        'Very-Irresistible-Bulgarian-Rose-867',
        'Very Irresistible Bulgarian Rose Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,anis,soft spicy,floral,warm spicy',
        'Very Irresistible Bulgarian RosebyGivenchyis a Floral fragrance for women.Very Irresistible Bulgarian Rosewas launched in 2005.',
        4.26,
        72,
        NULL
      ),
(
        'Very-Irresistible-Collector-Edition-18662',
        'Very Irresistible Collector Edition Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral,musky,anis,sweet',
        'Very Irresistible Collector EditionbyGivenchyis a Floral fragrance for women.Very Irresistible Collector Editionwas launched in 2013.',
        4,
        143,
        NULL
      ),
(
        'Very-Irresistible-Eau-d-Ete-Summer-Fragrance-2065',
        'Very Irresistible Eau d''Ete Summer Fragrance Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'Star Anise and Lemon',
        'Tangerine and Lily-of-the-Valley',
        'Peony and Lemon Verbena',
        'citrus,floral,fresh,anis,soft spicy',
        'Very Irresistible Eau d''Ete Summer FragrancebyGivenchyis a Floral Fruity fragrance for women.Very Irresistible Eau d''Ete Summer Fragrancewas launched in 2005. Top notes are Star Anise and Lemon; middle notes are Tangerine and Lily-of-the-Valley; base notes are Peony and Lemon Verbena.',
        3.75,
        103,
        NULL
      ),
(
        'Very-Irresistible-Eau-de-Parfum-40155',
        'Very Irresistible Eau de Parfum Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'Star Anise, Pear and Green Apple',
        'Liv Tyler Rose, Rose, Peony and Magnolia',
        'Rose, Vanilla and Patchouli',
        'floral,rose,anis,soft spicy,fresh',
        'Very Irresistible Eau de ParfumbyGivenchyis a Floral fragrance for women.Very Irresistible Eau de Parfumwas launched in 2005. Very Irresistible Eau de Parfum was created by Dominique Ropion, Sophie Labbe and Carlos Benaim. Top notes are Star Anise, Pear and Green Apple; middle notes are Liv Tyler Rose, Rose, Peony and Magnolia; base notes are Rose, Vanilla and Patchouli.',
        4.28,
        608,
        NULL
      ),
(
        'Very-Irresistible-Eau-de-Toilette-17516',
        'Very Irresistible Eau de Toilette Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,anis,soft spicy,floral,citrus',
        'Very Irresistible Eau de ToilettebyGivenchyis a Floral fragrance for women.Very Irresistible Eau de Toilettewas launched in 2012.',
        3.89,
        1,
        NULL
      ),
(
        'Very-Irresistible-for-men-34',
        'Very Irresistible',
        'Very',
        'for men',
        NULL,
        NULL,
        'Mint and Grapefruit',
        'Coffee and Sesame',
        'Hazelnut and Virginia Cedar',
        'woody,nutty,coffee,aromatic,green',
        'Very Irresistible for menbyGivenchyis a Amber Woody fragrance for men.Very Irresistible for menwas launched in 2005. Very Irresistible for men was created by Pierre Wargnye, Alain Astori, Carlos Benaim and Juliette Karagueuzoglou. Top notes are Mint and Grapefruit; middle notes are Coffee and Sesame; base notes are Hazelnut and Virginia Cedar.',
        4.2,
        1,
        NULL
      ),
(
        'Very-Irresistible-Fresh-Attitude-Summer-Sorbet-5771',
        'Very Irresistible Fresh Attitude Summer Sorbet Givenchy',
        'Very',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,green,citrus,coffee',
        'Very Irresistible Fresh Attitude Summer SorbetbyGivenchyis a Aromatic fragrance for men.Very Irresistible Fresh Attitude Summer Sorbetwas launched in 2009.',
        4.28,
        58,
        NULL
      ),
(
        'Very-Irresistible-Givenchy-Edition-Croisiere-17860',
        'Very Irresistible Givenchy Edition Croisiere Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'Salt, Magnolia and Bergamot',
        'Gardenia, Rose and Pink Peony',
        'Driftwood, Frangipani and Musk',
        'floral,salty,citrus,marine,rose',
        'Very Irresistible Givenchy Edition CroisierebyGivenchyis a Floral Aquatic fragrance for women.Very Irresistible Givenchy Edition Croisierewas launched in 2013. Top notes are Salt, Magnolia and Bergamot; middle notes are Gardenia, Rose and Pink Peony; base notes are Driftwood, Frangipani and Musk.',
        3.99,
        235,
        NULL
      ),
(
        'Very-Irresistible-Givenchy-Electric-Rose-14537',
        'Very Irresistible Givenchy Electric Rose Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'Blueberry, Lemon, Lemon Verbena and Basil',
        'Rose, Violet and Anise',
        'Musk and Cedar',
        'citrus,rose,fruity,aromatic,powdery',
        'Very Irresistible Givenchy Electric RosebyGivenchyis a Floral Green fragrance for women.Very Irresistible Givenchy Electric Rosewas launched in 2012. Top notes are Blueberry, Lemon, Lemon Verbena and Basil; middle notes are Rose, Violet and Anise; base notes are Musk and Cedar.',
        3.66,
        695,
        NULL
      ),
(
        'Very-Irresistible-Givenchy-Fresh-Attitude-965',
        'Very Irresistible Givenchy Fresh Attitude Givenchy',
        'Very',
        'for men',
        NULL,
        'Anne Flipo',
        'Mint, Grapefruit, Bergamot and Coriander',
        'Lavender and Basil',
        'Coffee and Cedar',
        'aromatic,fresh spicy,citrus,green,coffee',
        'Very Irresistible Givenchy Fresh AttitudebyGivenchyis a Woody Aromatic fragrance for men.Very Irresistible Givenchy Fresh Attitudewas launched in 2007. Very Irresistible Givenchy Fresh Attitude was created by Anne Flipo and Pierre Wargnye. Top notes are Mint, Grapefruit, Bergamot and Coriander; middle notes are Lavender and Basil; base notes are Coffee and Cedar.',
        4.11,
        458,
        NULL
      ),
(
        'Very-Irresistible-Givenchy-L-Intense-10888',
        'Very Irresistible Givenchy L’Intense Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'Plum',
        'Rose',
        'Patchouli and Musk',
        'fruity,rose,patchouli,sweet,musky',
        'Very Irresistible Givenchy L’IntensebyGivenchyis a Chypre Floral fragrance for women.Very Irresistible Givenchy L’Intensewas launched in 2011. Top note is Plum; middle note is Rose; base notes are Patchouli and Musk.',
        4.06,
        2,
        NULL
      ),
(
        'Very-Irresistible-Givenchy-Summer-Cocktail-Fresh-Attitude-for-Men-2008-2841',
        'Very Irresistible Givenchy Summer Cocktail - Fresh Attitude for Men 2008 Givenchy',
        'Very',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,green,citrus,anis',
        'Very Irresistible Givenchy Summer Cocktail - Fresh Attitude for Men 2008byGivenchyis a Aromatic fragrance for men.Very Irresistible Givenchy Summer Cocktail - Fresh Attitude for Men 2008was launched in 2008.',
        4.12,
        64,
        NULL
      ),
(
        'Very-Irresistible-Givenchy-Summer-Cocktail-for-Women-2008-2842',
        'Very Irresistible Givenchy Summer Cocktail for Women 2008 Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,soft spicy,aromatic,anis,rose',
        'Very Irresistible Givenchy Summer Cocktail for Women 2008byGivenchyis a Aromatic fragrance for women.Very Irresistible Givenchy Summer Cocktail for Women 2008was launched in 2008.',
        3.96,
        112,
        NULL
      ),
(
        'Very-Irresistible-L-Eau-en-Rose-22975',
        'Very Irresistible L''Eau en Rose Givenchy',
        'Very',
        'for women',
        NULL,
        'Carlos Benaim',
        'Blackberry',
        'Rose',
        'Musk',
        'rose,musky,fruity,floral,powdery',
        'Very Irresistible L''Eau en RosebyGivenchyis a Floral fragrance for women.Very Irresistible L''Eau en Rosewas launched in 2014. The nose behind this fragrance is Carlos Benaim. Top note is Blackberry; middle note is Rose; base note is Musk.',
        3.7,
        449,
        NULL
      ),
(
        'Very-Irresistible-Mes-Envies-29313',
        'Very Irrésistible Mes Envies Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,rose,anis,soft spicy,fresh',
        'Very Irrésistible Mes EnviesbyGivenchyis a Floral fragrance for women.Very Irrésistible Mes Envieswas launched in 2015.',
        4.23,
        60,
        NULL
      ),
(
        'Very-Irresistible-Poesie-d-un-Parfum-d-Hiver-13607',
        'Very Irresistible Poesie d’un Parfum d’Hiver Givenchy',
        'Very',
        'for women',
        NULL,
        NULL,
        'White Honey, Candied Orange and Gingerbread',
        'Cinnamon, Star Anise and Rose',
        'Vanille',
        'warm spicy,cinnamon,citrus,sweet,anis',
        'Very Irresistible Poesie d’un Parfum d’HiverbyGivenchyis a Floral Fruity Gourmand fragrance for women.Very Irresistible Poesie d’un Parfum d’Hiverwas launched in 2011. Top notes are White Honey, Candied Orange and Gingerbread; middle notes are Cinnamon, Star Anise and Rose; base note is Vanille.',
        4.12,
        328,
        NULL
      );
