
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'New-York-Gardenia-92072',
        'New York Gardenia Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Tuberose, Peony and Jasmine',
        'Gardenia and Rose',
        'Vanilla and Vetiver',
        'white floral,rose,tuberose,floral,vanilla',
        'New York GardeniabyBond No 9is a Floral fragrance for women and men. This is a new fragrance.New York Gardeniawas launched in 2024. Top notes are Tuberose, Peony and Jasmine; middle notes are Gardenia and Rose; base notes are Vanilla and Vetiver.',
        4.69,
        13,
        NULL
      ),
(
        'New-York-Nights-46057',
        'New York Nights Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Gardenia, Carnation and Jasmine',
        'Patchouli, Flowers, Sandalwood and Sea Notes',
        'Caramel and Coffee',
        'caramel,warm spicy,coffee,woody,floral',
        'New York NightsbyBond No 9is a Amber Vanilla fragrance for women and men.New York Nightswas launched in 2017. Top notes are Gardenia, Carnation and Jasmine; middle notes are Patchouli, Flowers, Sandalwood and Sea Notes; base notes are Caramel and Coffee.',
        4.27,
        858,
        NULL
      ),
(
        'New-York-Nights-Amphora-50215',
        'New York Nights Amphora Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Gardenia, Carnation and Jasmine',
        'Floral Notes, Sea Notes, Patchouli and Sandalwood',
        'Coffee and Caramel',
        'warm spicy,white floral,floral,woody,aromatic',
        'New York Nights AmphorabyBond No 9is a Amber Vanilla fragrance for women and men.New York Nights Amphorawas launched in 2017. Top notes are Gardenia, Carnation and Jasmine; middle notes are Floral Notes, Sea Notes, Patchouli and Sandalwood; base notes are Coffee and Caramel.',
        4,
        1,
        NULL
      ),
(
        'New-York-Nights-Made-With-Swarovski-50217',
        'New York Nights Made With Swarovski Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Gardenia, Carnation and Jasmine',
        'Sea Notes, Floral Notes, Patchouli and Sandalwood',
        'Coffee and Caramel',
        'warm spicy,white floral,floral,caramel,coffee',
        'New York Nights Made With SwarovskibyBond No 9is a Amber Vanilla fragrance for women and men.New York Nights Made With Swarovskiwas launched in 2017. Top notes are Gardenia, Carnation and Jasmine; middle notes are Sea Notes, Floral Notes, Patchouli and Sandalwood; base notes are Coffee and Caramel.',
        4.2,
        5,
        NULL
      ),
(
        'New-York-Nights-Solo-Skyline-Edition-50216',
        'New York Nights Solo Skyline Edition Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Gardenia, Carnation and Jasmine',
        'Floral Notes, Patchouli, Sea Notes and Sandalwood',
        'Coffee and Caramel',
        'warm spicy,floral,white floral,woody,coffee',
        'New York Nights Solo Skyline EditionbyBond No 9is a Amber Vanilla fragrance for women and men.New York Nights Solo Skyline Editionwas launched in 2017. Top notes are Gardenia, Carnation and Jasmine; middle notes are Floral Notes, Patchouli, Sea Notes and Sandalwood; base notes are Coffee and Caramel.',
        4.6,
        5,
        NULL
      ),
(
        'Nolita-43635',
        'Nolita Bond No 9',
        'Nolita',
        'for women',
        NULL,
        NULL,
        'Tangerine and Freesia',
        'Lily, Jasmine Sambac and Rose',
        'Musk, Amber and Sandalwood',
        'white floral,citrus,floral,musky,powdery',
        'NolitabyBond No 9is a Floral Woody Musk fragrance for women.Nolitawas launched in 2017. Top notes are Tangerine and Freesia; middle notes are Lily, Jasmine Sambac and Rose; base notes are Musk, Amber and Sandalwood.',
        3.95,
        301,
        NULL
      ),
(
        'NoMad-69735',
        'NoMad Bond No 9',
        'NoMad',
        'for women and men',
        NULL,
        'Miroslav Petkov',
        'Pear, Black Currant and Quince',
        'Rose, Agarwood (Oud), Violet Leaves and Orris',
        'Amber, Vanilla and Sandalwood',
        'fruity,rose,oud,sweet,floral',
        'NoMadbyBond No 9is a Amber Floral fragrance for women and men.NoMadwas launched in 2021. The nose behind this fragrance is Miroslav Petkov. Top notes are Pear, Black Currant and Quince; middle notes are Rose, Agarwood (Oud), Violet Leaves and Orris; base notes are Amber, Vanilla and Sandalwood.',
        4.27,
        270,
        NULL
      ),
(
        'Nouveau-Bowery-7168',
        'Nouveau Bowery Bond No 9',
        'Nouveau',
        'for women',
        NULL,
        'Robertet',
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,woody,green',
        'Nouveau BowerybyBond No 9is a Citrus Aromatic fragrance for women.Nouveau Bowerywas launched in 2003. The nose behind this fragrance is Robertet.',
        3.84,
        80,
        NULL
      ),
(
        'Nuits-de-Noho-3425',
        'Nuits de Noho Bond No 9',
        'Nuits',
        'for women',
        NULL,
        'Robertet',
        'Pineapple Leaf, Mandarin Orange and Bergamot',
        'Jasmine and Brazilian Rosewood',
        'Patchouli, Vanilla and Musk',
        'patchouli,woody,sweet,vanilla,fruity',
        'Nuits de NohobyBond No 9is a Floral Woody Musk fragrance for women.Nuits de Nohowas launched in 2003. The nose behind this fragrance is Robertet. Top notes are Pineapple Leaf, Mandarin Orange and Bergamot; middle notes are Jasmine and Brazilian Rosewood; base notes are Patchouli, Vanilla and Musk.',
        3.98,
        694,
        NULL
      ),
(
        'Off-Broadway-64662',
        'Off-Broadway Bond No 9',
        'Off-Broadway',
        'for women and men',
        NULL,
        NULL,
        'Black Currant and Grapefruit blossom',
        'Nutmeg, Lily and Osmanthus',
        'Musk, Vetiver, Patchouli and Sandalwood',
        'fruity,fresh spicy,woody,aromatic,white floral',
        'Off-BroadwaybyBond No 9is a Amber Floral fragrance for women and men.Off-Broadwaywas launched in 2021. Top notes are Black Currant and Grapefruit blossom; middle notes are Nutmeg, Lily and Osmanthus; base notes are Musk, Vetiver, Patchouli and Sandalwood.',
        4.12,
        26,
        NULL
      ),
(
        'Park-Avenue-South-29969',
        'Park Avenue South Bond No 9',
        'Park',
        'for women',
        NULL,
        NULL,
        'Green Apple',
        'Peach and Jasmine',
        'Musk and Amber',
        'fruity,fresh,musky,powdery,green',
        'Park Avenue SouthbyBond No 9is a Floral fragrance for women.Park Avenue Southwas launched in 2015. Top note is Green Apple; middle notes are Peach and Jasmine; base notes are Musk and Amber.',
        3.61,
        153,
        NULL
      ),
(
        'Perfumista-Avenue-18962',
        'Perfumista Avenue Bond No 9',
        'Perfumista',
        'for women',
        NULL,
        NULL,
        'Saffron, Plum, Nutmeg and Artemisia',
        'Rose, Rose Water, Peony and Jasmine',
        'Musk, Patchouli, Amber and Mate',
        'rose,floral,warm spicy,fresh spicy,musky',
        'Perfumista AvenuebyBond No 9is a Amber Floral fragrance for women.Perfumista Avenuewas launched in 2013. Top notes are Saffron, Plum, Nutmeg and Artemisia; middle notes are Rose, Rose Water, Peony and Jasmine; base notes are Musk, Patchouli, Amber and Mate.',
        3.4,
        314,
        NULL
      ),
(
        'Queen-Elizabeth-II-15181',
        'Queen Elizabeth II Bond No 9',
        'Queen',
        'for women',
        NULL,
        NULL,
        'Dates, Mace and Lantana leaves',
        'Tuberose, Rose and Orris Root',
        'Musk and Amber',
        'sweet,tuberose,powdery,rose,musky',
        'Queen Elizabeth IIbyBond No 9is a Floral fragrance for women.Queen Elizabeth IIwas launched in 2012. Top notes are Dates, Mace and Lantana leaves; middle notes are Tuberose, Rose and Orris Root; base notes are Musk and Amber.',
        3.44,
        18,
        NULL
      ),
(
        'Queens-27427',
        'Queens Bond No 9',
        'Queens',
        'for women and men',
        NULL,
        'Laurent Le Guernec',
        'Blackberry, Cardamom and Bergamot',
        'Tuberose, Champaca and Osmanthus',
        'Musk, Sandalwood, Benzoin and Amber',
        'floral,fruity,tuberose,warm spicy,amber',
        'QueensbyBond No 9is a Amber Floral fragrance for women and men.Queenswas launched in 2014. The nose behind this fragrance is Laurent Le Guernec. Top notes are Blackberry, Cardamom and Bergamot; middle notes are Tuberose, Champaca and Osmanthus; base notes are Musk, Sandalwood, Benzoin and Amber.',
        4.07,
        317,
        NULL
      ),
(
        'Sag-Harbor-15263',
        'Sag Harbor Bond No 9',
        'Sag',
        'for women and men',
        NULL,
        NULL,
        'Ivy, Bergamot and Bay Leaf',
        'Peony, Magnolia, Grapes and Honeysuckle',
        'Amber, Sandalwood and Agarwood (Oud)',
        'floral,fresh,fruity,citrus,green',
        'Sag HarborbyBond No 9is a Amber Floral fragrance for women and men.Sag Harborwas launched in 2012. Top notes are Ivy, Bergamot and Bay Leaf; middle notes are Peony, Magnolia, Grapes and Honeysuckle; base notes are Amber, Sandalwood and Agarwood (Oud).',
        3.86,
        189,
        NULL
      ),
(
        'Saks-En-Rose-9232',
        'Saks En Rose Bond No 9',
        'Saks',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tuberose,powdery,rose,white floral,musky',
        'Saks En RosebyBond No 9is a fragrance for women.Saks En Rosewas launched in 2010.',
        3.77,
        60,
        NULL
      ),
(
        'Saks-Fifth-Ave-Las-Vegas-11277',
        'Saks Fifth Ave. Las Vegas Bond No 9',
        'Saks',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,vanilla,amber,white floral',
        'Saks Fifth Ave. Las VegasbyBond No 9is a Amber Floral fragrance for women and men.Saks Fifth Ave. Las Vegaswas launched in 2010.',
        4.55,
        11,
        NULL
      ),
(
        'Saks-Fifth-Avenue-for-Her-1677',
        'Saks Fifth Avenue for Her Bond No 9',
        'Saks',
        'for women',
        NULL,
        'Michel Almairac',
        NULL,
        NULL,
        NULL,
        'white floral,tuberose,animalic,vanilla',
        'Saks Fifth Avenue for HerbyBond No 9is a Floral fragrance for women.Saks Fifth Avenue for Herwas launched in 2007. The nose behind this fragrance is Michel Almairac.',
        4.15,
        223,
        NULL
      ),
(
        'Saks-Fifth-Avenue-for-Him-1678',
        'Saks Fifth Avenue for Him Bond No 9',
        'Saks',
        'for men',
        NULL,
        'Michel Almairac',
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,fresh spicy,woody,aromatic',
        'Saks Fifth Avenue for HimbyBond No 9is a Woody Aquatic fragrance for men.Saks Fifth Avenue for Himwas launched in 2007. The nose behind this fragrance is Michel Almairac.',
        4.05,
        91,
        NULL
      ),
(
        'Saks-Fifth-Avenue-Miami-Dade-28850',
        'Saks Fifth Avenue Miami-Dade Bond No 9',
        'Saks',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,musky,powdery,amber',
        'Saks Fifth Avenue Miami-DadebyBond No 9is a Woody Floral Musk fragrance for women and men.Saks Fifth Avenue Miami-Dadewas launched in 2014.',
        4.14,
        7,
        NULL
      ),
(
        'Saks-New-York-Oud-22822',
        'Saks New York Oud Bond No 9',
        'Saks',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Bergamot and Nutmeg',
        'Jasmine and Palisander Rosewood',
        'Agarwood (Oud), Musk, Amber and Vanilla',
        'amber,white floral,fresh spicy,oud,warm spicy',
        'Saks New York OudbyBond No 9is a Amber Woody fragrance for women and men.Saks New York Oudwas launched in 2013. Top notes are Saffron, Bergamot and Nutmeg; middle notes are Jasmine and Palisander Rosewood; base notes are Agarwood (Oud), Musk, Amber and Vanilla.',
        3.93,
        15,
        NULL
      ),
(
        'Shelter-Island-24608',
        'Shelter Island Bond No 9',
        'Shelter',
        'for women and men',
        NULL,
        NULL,
        'Lemon and Black Pepper',
        'Seaweed and White Lily',
        'Agarwood (Oud), Musk, Sandalwood, Amber and Myrhh',
        'marine,citrus,aromatic,white floral,oud',
        'Shelter IslandbyBond No 9is a Woody Aquatic fragrance for women and men.Shelter Islandwas launched in 2014. Top notes are Lemon and Black Pepper; middle notes are Seaweed and White Lily; base notes are Agarwood (Oud), Musk, Sandalwood, Amber and Myrhh.',
        4.1,
        219,
        NULL
      ),
(
        'Soho-40208',
        'Soho Bond No 9',
        'Soho',
        'for women and men',
        NULL,
        NULL,
        'Sweet Orange, Petitgrain and Cassis',
        'Orange Blossom, Jasmine and Orris Root',
        'Moss, Cedar, Vetiver and Amber',
        'woody,white floral,citrus,earthy,aromatic',
        'SohobyBond No 9is a Floral Woody Musk fragrance for women and men.Sohowas launched in 2016. Top notes are Sweet Orange, Petitgrain and Cassis; middle notes are Orange Blossom, Jasmine and Orris Root; base notes are Moss, Cedar, Vetiver and Amber.',
        3.76,
        131,
        NULL
      ),
(
        'Spring-Fling-48561',
        'Spring Fling Bond No 9',
        'Spring',
        'for women',
        NULL,
        NULL,
        'Fruity Notes, Passion Flower and Lily-of-the-Valley',
        'Honeysuckle, Jasmine and Freesia',
        'Musk, Amber and Teak Wood',
        'white floral,fruity,floral,musky,sweet',
        'Spring FlingbyBond No 9is a Floral fragrance for women.Spring Flingwas launched in 2018. Top notes are Fruity Notes, Passion Flower and Lily-of-the-Valley; middle notes are Honeysuckle, Jasmine and Freesia; base notes are Musk, Amber and Teak Wood.',
        3.61,
        77,
        NULL
      ),
(
        'Spring-Fling-Mother-s-Day-Limited-Edition-50219',
        'Spring Fling Mother’s Day Limited Edition Bond No 9',
        'Spring',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley, Passion Flower and Fruity Notes',
        'Honeysuckle, Jasmine and Freesia',
        'Amber, Musk and Teak Wood',
        'white floral,floral,fruity,amber,musky',
        'Spring Fling Mother’s Day Limited EditionbyBond No 9is a Floral fragrance for women.Spring Fling Mother’s Day Limited Editionwas launched in 2017. Top notes are Lily-of-the-Valley, Passion Flower and Fruity Notes; middle notes are Honeysuckle, Jasmine and Freesia; base notes are Amber, Musk and Teak Wood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Spring-Fling-Swarovski-50218',
        'Spring Fling Swarovski Bond No 9',
        'Spring',
        'for women',
        NULL,
        NULL,
        'Fruity Notes, Lily-of-the-Valley and Passion Flower',
        'Honeysuckle, Jasmine and Freesia',
        'Musk, Teak Wood and Amber',
        'white floral,floral,fruity,musky,sweet',
        'Spring Fling SwarovskibyBond No 9is a Floral fragrance for women.Spring Fling Swarovskiwas launched in 2018. Top notes are Fruity Notes, Lily-of-the-Valley and Passion Flower; middle notes are Honeysuckle, Jasmine and Freesia; base notes are Musk, Teak Wood and Amber.',
        4,
        1,
        NULL
      ),
(
        'Success-17806',
        'Success Bond No 9',
        'Success',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Coriander, Mandarin Orange and Lemon',
        'Tuberose, Pimento, Plum and Rose',
        'Vanila, Amber and Patchouli',
        'warm spicy,vanilla,amber,aromatic,tuberose',
        'SuccessbyBond No 9is a Amber Vanilla fragrance for women and men.Successwas launched in 2013. Top notes are Cardamom, Coriander, Mandarin Orange and Lemon; middle notes are Tuberose, Pimento, Plum and Rose; base notes are Vanila, Amber and Patchouli.',
        3.99,
        118,
        NULL
      ),
(
        'Sutton-Place-41010',
        'Sutton Place Bond No 9',
        'Sutton',
        'for women and men',
        NULL,
        NULL,
        'Cassis, Pineapple, Bergamot, Pink Pepper and Tangerine',
        'Patchouli, Jasmine and Lily',
        'Leather, Musk, Amber and Vanilla',
        'fruity,citrus,soft spicy,sweet,leather',
        'Sutton PlacebyBond No 9is a Amber Vanilla fragrance for women and men.Sutton Placewas launched in 2016. Top notes are Cassis, Pineapple, Bergamot, Pink Pepper and Tangerine; middle notes are Patchouli, Jasmine and Lily; base notes are Leather, Musk, Amber and Vanilla.',
        3.72,
        215,
        NULL
      ),
(
        'Swarovski-Crystallized-Amphora-4883',
        'Swarovski Crystallized Amphora Bond No 9',
        'Swarovski',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Swarovski Crystallized AmphorabyBond No 9is a fragrance for women and men.Swarovski Crystallized Amphorawas launched in 2008.',
        4,
        7,
        NULL
      ),
(
        'Texas-10093',
        'Texas Bond No 9',
        'Texas',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Pineapple, Black Currant and Bergamot',
        'Gardenia, Neroli, Jasmine, Hedione and Lily-of-the-Valley',
        'Vanille, Musk, oak moss, Vetyver and Cardamom',
        'white floral,fruity,citrus,sweet,fresh',
        'TexasbyBond No 9is a Citrus fragrance for women and men.Texaswas launched in 2010. Top notes are Mandarin Orange, Pineapple, Black Currant and Bergamot; middle notes are Gardenia, Neroli, Jasmine, Hedione and Lily-of-the-Valley; base notes are Vanille, Musk, oak moss, Vetyver and Cardamom.',
        4.16,
        31,
        NULL
      ),
(
        'The-Scent-Of-Peace-1304',
        'The Scent Of Peace Bond No 9',
        'The',
        'for women',
        NULL,
        'Michel Almairac',
        'Black Currant and Grapefruit',
        'Lily-of-the-Valley',
        'Musk and Virginia Cedar',
        'fruity,citrus,woody,musky,white floral',
        'The Scent Of PeacebyBond No 9is a Floral Woody Musk fragrance for women.The Scent Of Peacewas launched in 2006. The nose behind this fragrance is Michel Almairac. Top notes are Black Currant and Grapefruit; middle note is Lily-of-the-Valley; base notes are Musk and Virginia Cedar.',
        3.95,
        865,
        NULL
      ),
(
        'The-Scent-of-Peace-for-Him-20551',
        'The Scent of Peace for Him Bond No 9',
        'The',
        'for men',
        NULL,
        NULL,
        'Pineapple, Juniper Berries and Bergamot',
        'Currant buds',
        'Cedar and Vetiver',
        'aromatic,woody,fruity,fresh spicy,sweet',
        'The Scent of Peace for HimbyBond No 9is a Woody Aromatic fragrance for men.The Scent of Peace for Himwas launched in 2013. Top notes are Pineapple, Juniper Berries and Bergamot; middle note is Currant buds; base notes are Cedar and Vetiver.',
        4.11,
        1,
        NULL
      ),
(
        'TriBeCa-59904',
        'TriBeCa Bond No 9',
        'TriBeCa',
        'for women and men',
        NULL,
        'Michel Almairac',
        'Hazelnut and Cacao',
        'Jasmine Sambac and Cedar',
        'Ambroxan, Caramel and Moss',
        'amber,caramel,woody,nutty,white floral',
        'TriBeCabyBond No 9is a Amber Vanilla fragrance for women and men.TriBeCawas launched in 2020. The nose behind this fragrance is Michel Almairac. Top notes are Hazelnut and Cacao; middle notes are Jasmine Sambac and Cedar; base notes are Ambroxan, Caramel and Moss.',
        4.16,
        639,
        NULL
      ),
(
        'TriBeCa-Swarovski-59911',
        'TriBeCa Swarovski Bond No 9',
        'TriBeCa',
        'for women and men',
        NULL,
        'Michel Almairac',
        'Hazelnut and Cacao',
        'Cedar and Jasmine Sambac',
        'Ambroxan, Moss and Caramel',
        'amber,woody,nutty,musky,cacao',
        'TriBeCa SwarovskibyBond No 9is a Amber Vanilla fragrance for women and men.TriBeCa Swarovskiwas launched in 2020. The nose behind this fragrance is Michel Almairac. Top notes are Hazelnut and Cacao; middle notes are Cedar and Jasmine Sambac; base notes are Ambroxan, Moss and Caramel.',
        3.22,
        9,
        NULL
      ),
(
        'Union-Square-17816',
        'Union Square Bond No 9',
        'Union',
        'for women',
        NULL,
        'Stephen Nilsen',
        'Grass and Lily-of-the-Valley',
        'Freesia and Birch',
        'Musk and Amber',
        'green,fresh,floral,white floral,musky',
        'Union SquarebyBond No 9is a Floral Green fragrance for women.Union Squarewas launched in 2013. The nose behind this fragrance is Stephen Nilsen. Top notes are Grass and Lily-of-the-Valley; middle notes are Freesia and Birch; base notes are Musk and Amber.',
        3.73,
        84,
        NULL
      ),
(
        'Wall-Street-3260',
        'Wall Street Bond No 9',
        'Wall',
        'for women and men',
        NULL,
        'David Apel',
        NULL,
        NULL,
        NULL,
        'aquatic,citrus,aromatic,ozonic,marine',
        'Wall StreetbyBond No 9is a Aromatic Aquatic fragrance for women and men.Wall Streetwas launched in 2004. The nose behind this fragrance is David Apel.',
        3.72,
        772,
        NULL
      ),
(
        'Washington-Square-9650',
        'Washington Square Bond No 9',
        'Washington',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,rose,fresh spicy,citrus,musky',
        'Washington SquarebyBond No 9is a Floral Woody Musk fragrance for women and men.Washington Squarewas launched in 2010.',
        4.15,
        326,
        NULL
      ),
(
        'West-Broadway-6821',
        'West Broadway Bond No 9',
        'West',
        'for women and men',
        NULL,
        'Robertet',
        NULL,
        NULL,
        NULL,
        'citrus,musky,powdery,white floral,green',
        'West BroadwaybyBond No 9is a fragrance for women and men.West Broadwaywas launched in 2003. The nose behind this fragrance is Robertet.',
        3.96,
        110,
        NULL
      ),
(
        'West-Side-1298',
        'West Side Bond No 9',
        'West',
        'for women and men',
        NULL,
        'Michel Almairac',
        NULL,
        NULL,
        NULL,
        'rose,floral,powdery,vanilla,woody',
        'West SidebyBond No 9is a Floral Woody Musk fragrance for women and men.West Sidewas launched in 2006. The nose behind this fragrance is Michel Almairac.',
        4.02,
        832,
        NULL
      ),
(
        'Andy-Warhol-13630',
        'Andy Warhol Bond No 9',
        'Andy',
        'for women and men',
        NULL,
        NULL,
        'plum, Cypress, Citruses and Bergamot',
        'Agarwood (Oud), French labdanum, Rose, Patchouli and Jasmine',
        'Vanille, Sandalwood, Olibanum and Musk',
        'woody,fruity,amber,vanilla,sweet',
        'Andy WarholbyBond No 9is a Woody Aromatic fragrance for women and men.Andy Warholwas launched in 2011. Top notes are plum, Cypress, Citruses and Bergamot; middle notes are Agarwood (Oud), French labdanum, Rose, Patchouli and Jasmine; base notes are Vanille, Sandalwood, Olibanum and Musk.',
        4.51,
        272,
        NULL
      ),
(
        'Andy-Warhol-Lexington-Avenue-4138',
        'Andy Warhol Lexington Avenue Bond No 9',
        'Andy',
        'for women and men',
        NULL,
        'Claude Dir',
        'Star Anise, Fennel, Cypress and Cardamom',
        'Creme Brulee, Almond, Orris Root and Peony',
        'Sandalwood and Patchouli',
        'sweet,soft spicy,anis,woody,aromatic',
        'Andy Warhol Lexington AvenuebyBond No 9is a Chypre fragrance for women and men.Andy Warhol Lexington Avenuewas launched in 2008. The nose behind this fragrance is Claude Dir. Top notes are Star Anise, Fennel, Cypress and Cardamom; middle notes are Creme Brulee, Almond, Orris Root and Peony; base notes are Sandalwood and Patchouli.',
        4.23,
        318,
        NULL
      ),
(
        'Andy-Warhol-Montauk-8669',
        'Andy Warhol Montauk Bond No 9',
        'Andy',
        'for women and men',
        NULL,
        'Laurent Le Guernec',
        'Blueberry, Bergamot and Bay Leaf',
        'Hyacinth, Honeysuckle and Lily-of-the-Valley',
        'Maple, Oak, Driftwood and Amber',
        'woody,fresh spicy,fruity,green,floral',
        'Andy Warhol MontaukbyBond No 9is a fragrance for women and men.Andy Warhol Montaukwas launched in 2010. The nose behind this fragrance is Laurent Le Guernec. Top notes are Blueberry, Bergamot and Bay Leaf; middle notes are Hyacinth, Honeysuckle and Lily-of-the-Valley; base notes are Maple, Oak, Driftwood and Amber.',
        3.84,
        115,
        NULL
      ),
(
        'Andy-Warhol-Silver-Factory-1297',
        'Andy Warhol Silver Factory Bond No 9',
        'Andy',
        'for women and men',
        NULL,
        'Aurélien Guichard',
        'Lavender, Bergamot and Grapefruit',
        'Incense, Iris, Violet and Jasmine',
        'Resins, Cedar and Amber',
        'amber,woody,balsamic,smoky,powdery',
        'Andy Warhol Silver FactorybyBond No 9is a Woody Floral Musk fragrance for women and men.Andy Warhol Silver Factorywas launched in 2007. The nose behind this fragrance is Aurélien Guichard. Top notes are Lavender, Bergamot and Grapefruit; middle notes are Incense, Iris, Violet and Jasmine; base notes are Resins, Cedar and Amber.',
        4.25,
        449,
        NULL
      ),
(
        'Andy-Warhol-Success-is-a-Job-in-New-York-6526',
        'Andy Warhol Success is a Job in New York Bond No 9',
        'Andy',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Coriander, Nutmeg, Mandarin Orange and Bergamot',
        'Plum, Tuberose, Jasmine, Iris, Pimento and May Rose',
        'Vanilla, Benzoin and Patchouli',
        'warm spicy,vanilla,white floral,aromatic,amber',
        'Andy Warhol Success is a Job in New YorkbyBond No 9is a Amber Spicy fragrance for women and men.Andy Warhol Success is a Job in New Yorkwas launched in 2009. Top notes are Cardamom, Coriander, Nutmeg, Mandarin Orange and Bergamot; middle notes are Plum, Tuberose, Jasmine, Iris, Pimento and May Rose; base notes are Vanilla, Benzoin and Patchouli.',
        4.14,
        320,
        NULL
      ),
(
        'Andy-Warhol-Union-Square-2693',
        'Andy Warhol Union Square Bond No 9',
        'Andy',
        'for women',
        NULL,
        'Stephen Nilsen',
        'Lily-of-the-Valley and Green Grass',
        'Freesia and Birch',
        'Musk and Amber',
        'green,fresh,floral,white floral,leather',
        'Andy Warhol Union SquarebyBond No 9is a Floral Green fragrance for women.Andy Warhol Union Squarewas launched in 2008. The nose behind this fragrance is Stephen Nilsen. Top notes are Lily-of-the-Valley and Green Grass; middle notes are Freesia and Birch; base notes are Musk and Amber.',
        3.77,
        163,
        NULL
      ),
(
        'Dubai-Amber-37909',
        'Dubai Amber Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Saffron, Bergamot and Raspberry',
        'Gurjan balsam, Guaiac Wood, Bulgarian Rose and Jasmine',
        'Amber, Cedar and Vanilla',
        'woody,amber,soft spicy,rose,powdery',
        'Dubai AmberbyBond No 9is a Amber fragrance for women and men.Dubai Amberwas launched in 2016. Top notes are Pink Pepper, Saffron, Bergamot and Raspberry; middle notes are Gurjan balsam, Guaiac Wood, Bulgarian Rose and Jasmine; base notes are Amber, Cedar and Vanilla.',
        3.97,
        90,
        NULL
      ),
(
        'Dubai-Amethyst-37908',
        'Dubai Amethyst Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Rose and Lily',
        'Jasmine and Tonka Bean',
        'Tobacco, Ambroxan and Patchouli Leaf',
        'amber,white floral,tobacco,sweet,rose',
        'Dubai AmethystbyBond No 9is a Amber Floral fragrance for women and men.Dubai Amethystwas launched in 2016. Top notes are Rose and Lily; middle notes are Jasmine and Tonka Bean; base notes are Tobacco, Ambroxan and Patchouli Leaf.',
        3.72,
        82,
        NULL
      ),
(
        'Dubai-Black-Sapphire-41011',
        'Dubai Black Sapphire Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Beeswax, Honey and Neroli',
        'Gurjan balsam, Turkish Rose, Cedar and Pepper',
        'Tolu Balsam, Siam Benzoin, Vetiver and Sandalwood',
        'amber,warm spicy,woody,powdery,rose',
        'Dubai Black SapphirebyBond No 9is a Amber Floral fragrance for women and men.Dubai Black Sapphirewas launched in 2016. Top notes are Saffron, Beeswax, Honey and Neroli; middle notes are Gurjan balsam, Turkish Rose, Cedar and Pepper; base notes are Tolu Balsam, Siam Benzoin, Vetiver and Sandalwood.',
        3.57,
        77,
        NULL
      ),
(
        'Dubai-Blue-Diamond-63908',
        'Dubai Blue Diamond Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Ginger and Grapefruit',
        'Tonka Bean, Orchid and Orris',
        'Sandalwood, Patchouli, Amber and Leather',
        'warm spicy,woody,powdery,amber,citrus',
        'Dubai Blue DiamondbyBond No 9is a Chypre Floral fragrance for women and men.Dubai Blue Diamondwas launched in 2020. Top notes are Ginger and Grapefruit; middle notes are Tonka Bean, Orchid and Orris; base notes are Sandalwood, Patchouli, Amber and Leather.',
        3.25,
        4,
        NULL
      ),
(
        'Dubai-Citrine-37910',
        'Dubai Citrine Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Red Berries, Bergamot, Balsam Fir and Seaweed',
        'Marigold, Magnolia, Geranium and Lily',
        'Musk, Vetiver, Amber and Oakmoss',
        'aromatic,fresh spicy,citrus,floral,sweet',
        'Dubai CitrinebyBond No 9is a Woody Floral Musk fragrance for women and men.Dubai Citrinewas launched in 2016. Top notes are Red Berries, Bergamot, Balsam Fir and Seaweed; middle notes are Marigold, Magnolia, Geranium and Lily; base notes are Musk, Vetiver, Amber and Oakmoss.',
        4.02,
        51,
        NULL
      ),
(
        'Dubai-Diamond-57407',
        'Dubai Diamond Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Rose',
        'Patchouli and Jasmine',
        'Musk and Amber',
        'warm spicy,rose,metallic,leather,patchouli',
        'Dubai DiamondbyBond No 9is a Amber Floral fragrance for women and men.Dubai Diamondwas launched in 2019. Top notes are Saffron and Rose; middle notes are Patchouli and Jasmine; base notes are Musk and Amber.',
        3.83,
        6,
        NULL
      ),
(
        'Dubai-Diamond-Collection-In-Jet-Crystal-77300',
        'Dubai Diamond Collection In Jet & Crystal Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon',
        'Patchouli and Vanilla',
        'Ambreine, Moss and Labdanum',
        'earthy,mossy,woody,patchouli,vanilla',
        'Dubai Diamond Collection In Jet & CrystalbyBond No 9is a fragrance for women and men. This is a new fragrance.Dubai Diamond Collection In Jet & Crystalwas launched in 2022. Top note is Cinnamon; middle notes are Patchouli and Vanilla; base notes are Ambreine, Moss and Labdanum.',
        2,
        2,
        NULL
      ),
(
        'Dubai-Diamond-Ruby-77301',
        'Dubai Diamond Ruby Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Davana, Bergamot and Saffron',
        'Geranium, Rose and Magnolia',
        'Amber, Sandalwood, Myrrh, Cypriol Oil or Nagarmotha and Civet',
        'amber,aromatic,woody,warm spicy,fresh spicy',
        'Dubai Diamond RubybyBond No 9is a fragrance for women and men. This is a new fragrance.Dubai Diamond Rubywas launched in 2022. Top notes are Davana, Bergamot and Saffron; middle notes are Geranium, Rose and Magnolia; base notes are Amber, Sandalwood, Myrrh, Cypriol Oil or Nagarmotha and Civet.',
        3,
        2,
        NULL
      ),
(
        'Dubai-Emerald-31550',
        'Dubai Emerald Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Hyssop',
        'Rose and Gurjan balsam',
        'Leather, Cypriol Oil or Nagarmotha, Amber, Patchouli and Sandalwood',
        'woody,leather,warm spicy,rose,earthy',
        'Dubai EmeraldbyBond No 9is a Leather fragrance for women and men.Dubai Emeraldwas launched in 2015. Top notes are Saffron and Hyssop; middle notes are Rose and Gurjan balsam; base notes are Leather, Cypriol Oil or Nagarmotha, Amber, Patchouli and Sandalwood.',
        3.71,
        97,
        NULL
      ),
(
        'Dubai-Emerald-Swarovski-Edition-70371',
        'Dubai Emerald Swarovski Edition Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon',
        'Patchouli and Vanilla',
        'Musk, Amber and Labdanum',
        'amber,musky,warm spicy,cinnamon,patchouli',
        'Dubai Emerald Swarovski EditionbyBond No 9is a Amber Floral fragrance for women and men.Dubai Emerald Swarovski Editionwas launched in 2021. Top note is Cinnamon; middle notes are Patchouli and Vanilla; base notes are Musk, Amber and Labdanum.',
        4.5,
        2,
        NULL
      ),
(
        'Dubai-Garnet-41013',
        'Dubai Garnet Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Blackberry, Pink Pepper, Bergamot, Seaweed and Cardamom',
        'Rose, Plum, Magnolia, Jasmine, Cumin and Lavender',
        'Vetiver, Musk, Oakmoss, Amber and Myrhh',
        'fruity,aromatic,sweet,rose,floral',
        'Dubai GarnetbyBond No 9is a Floral fragrance for women and men.Dubai Garnetwas launched in 2016. Top notes are Blackberry, Pink Pepper, Bergamot, Seaweed and Cardamom; middle notes are Rose, Plum, Magnolia, Jasmine, Cumin and Lavender; base notes are Vetiver, Musk, Oakmoss, Amber and Myrhh.',
        3.94,
        48,
        NULL
      ),
(
        'Dubai-Gold-46558',
        'Dubai Gold Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Brandy, Saffron and Bitter Orange',
        'Cedar, Guaiac Wood and Ginger',
        'Sandalwood, Amber, Musk and Patchouli',
        'woody,warm spicy,powdery,amber',
        'Dubai GoldbyBond No 9is a Amber Spicy fragrance for women and men.Dubai Goldwas launched in 2017. Top notes are Brandy, Saffron and Bitter Orange; middle notes are Cedar, Guaiac Wood and Ginger; base notes are Sandalwood, Amber, Musk and Patchouli.',
        3.97,
        70,
        NULL
      ),
(
        'Dubai-Indigo-31551',
        'Dubai Indigo Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Litchi, Peach and Bergamot',
        'Peony, Jasmine and Orange Blossom',
        'White Musk, Amber, Agarwood (Oud) and Oakmoss',
        'white floral,fruity,fresh,floral,citrus',
        'Dubai IndigobyBond No 9is a Amber Floral fragrance for women and men.Dubai Indigowas launched in 2015. Top notes are Litchi, Peach and Bergamot; middle notes are Peony, Jasmine and Orange Blossom; base notes are White Musk, Amber, Agarwood (Oud) and Oakmoss.',
        4.05,
        141,
        NULL
      ),
(
        'Dubai-Jade-41012',
        'Dubai Jade Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Violet Leaf, Raspberry and Cumin',
        'Rose, Jasmine, Lily and Cedar',
        'Musk, Agarwood (Oud), Birch, Amber and Ambrette (Musk Mallow)',
        'white floral,musky,rose,woody,ozonic',
        'Dubai JadebyBond No 9is a Amber Floral fragrance for women and men.Dubai Jadewas launched in 2016. Top notes are Violet Leaf, Raspberry and Cumin; middle notes are Rose, Jasmine, Lily and Cedar; base notes are Musk, Agarwood (Oud), Birch, Amber and Ambrette (Musk Mallow).',
        4.06,
        62,
        NULL
      ),
(
        'Dubai-Platinum-51743',
        'Dubai Platinum Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Incense, Cardamom and Pink Pepper',
        'Atlas Cedar, Labdanum, Vanilla and Ginger',
        'Agarwood (Oud), Papyrus and Cashmere Wood',
        'amber,woody,warm spicy,smoky,balsamic',
        'Dubai PlatinumbyBond No 9is a Woody Spicy fragrance for women and men.Dubai Platinumwas launched in 2018. Top notes are Incense, Cardamom and Pink Pepper; middle notes are Atlas Cedar, Labdanum, Vanilla and Ginger; base notes are Agarwood (Oud), Papyrus and Cashmere Wood.',
        3.84,
        51,
        NULL
      ),
(
        'Dubai-Ruby-31552',
        'Dubai Ruby Bond No 9',
        'Dubai',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Bergamot and Artemisia',
        'Rose, Geranium and Magnolia',
        'Civet, Sandalwood, Myrhh, Amber and Cypriol Oil or Nagarmotha',
        'rose,warm spicy,amber,woody,aromatic',
        'Dubai RubybyBond No 9is a Amber Floral fragrance for women and men.Dubai Rubywas launched in 2015. Top notes are Saffron, Bergamot and Artemisia; middle notes are Rose, Geranium and Magnolia; base notes are Civet, Sandalwood, Myrhh, Amber and Cypriol Oil or Nagarmotha.',
        3.81,
        93,
        NULL
      ),
(
        'Bond-No-9-x-Harrods-175-Anniversary-Edition-95201',
        'Bond No. 9 x Harrods 175 Anniversary Edition Bond No 9',
        'Bond',
        'for women and men',
        NULL,
        NULL,
        'Vanila, Blackcurrant, Rose and Spicy Notes',
        'Honey, Cinnamon and Amber',
        'Labdanum and Musk',
        'vanilla,honey,warm spicy,sweet,amber',
        'Bond No. 9 x Harrods 175 Anniversary EditionbyBond No 9is a Amber Floral fragrance for women and men. This is a new fragrance.Bond No. 9 x Harrods 175 Anniversary Editionwas launched in 2024. Top notes are Vanila, Blackcurrant, Rose and Spicy Notes; middle notes are Honey, Cinnamon and Amber; base notes are Labdanum and Musk.',
        4,
        2,
        NULL
      ),
(
        'Harrods-Agarwood-18650',
        'Harrods Agarwood Bond No 9',
        'Harrods',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Black Tea and Nutmeg',
        'Patchouli, Suede and Violet',
        'Agarwood (Oud), Amber, Sandalwood, Labdanum and Musk',
        'warm spicy,woody,oud,amber,powdery',
        'Harrods AgarwoodbyBond No 9is a Amber Spicy fragrance for women and men.Harrods Agarwoodwas launched in 2013. Top notes are Saffron, Black Tea and Nutmeg; middle notes are Patchouli, Suede and Violet; base notes are Agarwood (Oud), Amber, Sandalwood, Labdanum and Musk.',
        4.48,
        56,
        NULL
      ),
(
        'Harrods-Amber-12578',
        'Harrods Amber Bond No 9',
        'Harrods',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Nutmeg, Bergamot and Pepper',
        'Jasmine, Rose and Osmanthus',
        'Amber, Myrhh, Benzoin, Musk, Agarwood (Oud) and Sandalwood',
        'amber,warm spicy,fresh spicy,floral,powdery',
        'Harrods AmberbyBond No 9is a Amber Spicy fragrance for women and men.Harrods Amberwas launched in 2011. Top notes are Saffron, Nutmeg, Bergamot and Pepper; middle notes are Jasmine, Rose and Osmanthus; base notes are Amber, Myrhh, Benzoin, Musk, Agarwood (Oud) and Sandalwood.',
        4.12,
        52,
        NULL
      ),
(
        'Harrods-for-Her-7164',
        'Harrods for Her Bond No 9',
        'Harrods',
        'for women',
        NULL,
        'Laurent Le Guernec',
        NULL,
        NULL,
        NULL,
        'aromatic,leather,white floral,fresh spicy,tuberose',
        'Harrods for HerbyBond No 9is a Floral fragrance for women.Harrods for Herwas launched in 2009. The nose behind this fragrance is Laurent Le Guernec.',
        3.7,
        33,
        NULL
      ),
(
        'Harrods-for-Him-7165',
        'Harrods for Him Bond No 9',
        'Harrods',
        'for men',
        NULL,
        'Laurent Le Guernec',
        NULL,
        NULL,
        NULL,
        'aromatic,woody,lavender,herbal,leather',
        'Harrods for HimbyBond No 9is a fragrance for men.Harrods for Himwas launched in 2009. The nose behind this fragrance is Laurent Le Guernec.',
        4.3,
        60,
        NULL
      ),
(
        'Harrods-Oud-42154',
        'Harrods Oud Bond No 9',
        'Harrods',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,amber,oud,aromatic,warm spicy',
        'Harrods OudbyBond No 9is a Amber Woody fragrance for women and men.',
        4.24,
        21,
        NULL
      ),
(
        'Harrods-Oud-Patchouli-15958',
        'Harrods Oud Patchouli Bond No 9',
        'Harrods',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,woody,leather,aromatic',
        'Harrods Oud PatchoulibyBond No 9is a Amber Woody fragrance for women and men.Harrods Oud Patchouliwas launched in 2012.',
        4.31,
        49,
        NULL
      ),
(
        'Harrods-Rose-9231',
        'Harrods Rose Bond No 9',
        'Harrods',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,rose,tuberose,floral,yellow floral',
        'Harrods RosebyBond No 9is a Floral fragrance for women.Harrods Rosewas launched in 2010.',
        4.25,
        72,
        NULL
      ),
(
        'Harrods-Royal-Rose-27420',
        'Harrods Royal Rose Bond No 9',
        'Harrods',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'yellow floral,rose,white floral,floral,green',
        'Harrods Royal RosebyBond No 9is a Floral fragrance for women.Harrods Royal Rosewas launched in 2014.',
        3.82,
        28,
        NULL
      ),
(
        'Harrods-Swarovski-Limited-Edition-7166',
        'Harrods Swarovski Limited Edition Bond No 9',
        'Harrods',
        'for women and men',
        NULL,
        'Laurent Le Guernec',
        NULL,
        NULL,
        NULL,
        'fresh spicy,amber,oud,aromatic,warm spicy',
        'Harrods Swarovski Limited EditionbyBond No 9is a Amber fragrance for women and men.Harrods Swarovski Limited Editionwas launched in 2009. The nose behind this fragrance is Laurent Le Guernec.',
        4.32,
        62,
        NULL
      ),
(
        'Le-Parfum-Du-Salon-52454',
        'Le Parfum Du Salon Bond No 9',
        'Le',
        'for women and men',
        NULL,
        NULL,
        'Dates, Lantana leaves and Mace',
        'Rose, Tuberose and Orris',
        'Amber, Sandalwood and Musk',
        'powdery,sweet,rose,tuberose,woody',
        'Le Parfum Du SalonbyBond No 9is a Amber Floral fragrance for women and men.Le Parfum Du Salonwas launched in 2018. Top notes are Dates, Lantana leaves and Mace; middle notes are Rose, Tuberose and Orris; base notes are Amber, Sandalwood and Musk.',
        4,
        5,
        NULL
      ),
(
        'New-York-Forever-87172',
        'New York Forever Bond No 9',
        'New',
        'for women and men',
        NULL,
        'Domitille Michalon Bertier',
        'Cinnamon',
        'Patchouli and Vanilla',
        'Earthy Notes, Amber, Labdanum, Honey, Moss and Musk',
        'earthy,amber,warm spicy,cinnamon,patchouli',
        'New York ForeverbyBond No 9is a fragrance for women and men. This is a new fragrance.New York Foreverwas launched in 2023. The nose behind this fragrance is Domitille Michalon Bertier. Top note is Cinnamon; middle notes are Patchouli and Vanilla; base notes are Earthy Notes, Amber, Labdanum, Honey, Moss and Musk.',
        4.08,
        40,
        NULL
      ),
(
        'New-York-Forever-Limited-Edition-86898',
        'New York Forever Limited Edition Bond No 9',
        'New',
        'for women and men',
        NULL,
        'Domitille Michalon Bertier',
        'Cinnamon',
        'Vanilla and Patchouli',
        'Amber, Honey, Moss, Labdanum, Earthy Notes and Musk',
        'amber,woody,warm spicy,earthy,cinnamon',
        'New York Forever Limited EditionbyBond No 9is a fragrance for women and men. This is a new fragrance.New York Forever Limited Editionwas launched in 2023. The nose behind this fragrance is Domitille Michalon Bertier. Top note is Cinnamon; middle notes are Vanilla and Patchouli; base notes are Amber, Honey, Moss, Labdanum, Earthy Notes and Musk.',
        4.55,
        11,
        NULL
      ),
(
        'New-York-Forever-x-Disco-Fever-87558',
        'New York Forever x “Disco Fever” Bond No 9',
        'New',
        'for women and men',
        NULL,
        'Domitille Michalon Bertier',
        'Cinnamon',
        'Patchouli and Vanilla',
        'Earthy Notes, Honey, Labdanum, Amber, Musk and Moss',
        'earthy,honey,amber,sweet,musky',
        'New York Forever x “Disco Fever”byBond No 9is a fragrance for women and men. This is a new fragrance.New York Forever x “Disco Fever”was launched in 2023. The nose behind this fragrance is Domitille Michalon Bertier. Top note is Cinnamon; middle notes are Patchouli and Vanilla; base notes are Earthy Notes, Honey, Labdanum, Amber, Musk and Moss.',
        4.5,
        2,
        NULL
      ),
(
        'New-York-Amber-13631',
        'New York Amber Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,fresh spicy,warm spicy,rose,oud',
        'New York AmberbyBond No 9is a Amber Woody fragrance for women and men.New York Amberwas launched in 2011.',
        3.92,
        532,
        NULL
      ),
(
        'New-York-Musk-16394',
        'New York Musk Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Black Currant and Grapefruit blossom',
        'Green Lily, Nutmeg and Osmanthus',
        'Musk, Sandalwood, Patchouli and Vetiver',
        'woody,musky,powdery,fruity,white floral',
        'New York MuskbyBond No 9is a Floral Woody Musk fragrance for women and men.New York Muskwas launched in 2012. Top notes are Black Currant and Grapefruit blossom; middle notes are Green Lily, Nutmeg and Osmanthus; base notes are Musk, Sandalwood, Patchouli and Vetiver.',
        3.71,
        272,
        NULL
      ),
(
        'New-York-Oud-11234',
        'New York Oud Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Plum, Saffron and Orange',
        'Rose, Agarwood (Oud), Patchouli and Orris Root',
        'Musk, White Honey and Vetiver',
        'rose,oud,fruity,sweet,warm spicy',
        'New York OudbyBond No 9is a Amber fragrance for women and men.New York Oudwas launched in 2011. Top notes are Plum, Saffron and Orange; middle notes are Rose, Agarwood (Oud), Patchouli and Orris Root; base notes are Musk, White Honey and Vetiver.',
        4.08,
        740,
        NULL
      ),
(
        'New-York-Patchouli-20552',
        'New York Patchouli Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Litchi and Rose Water',
        'Lilac, Patchouli and Lily',
        'Atlas Cedar, Musk, Sandalwood and Amber',
        'woody,floral,citrus,powdery,musky',
        'New York PatchoulibyBond No 9is a Amber Floral fragrance for women and men.New York Patchouliwas launched in 2013. Top notes are Bergamot, Litchi and Rose Water; middle notes are Lilac, Patchouli and Lily; base notes are Atlas Cedar, Musk, Sandalwood and Amber.',
        3.58,
        151,
        NULL
      ),
(
        'New-York-Sandalwood-28530',
        'New York Sandalwood Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Orris, Carrot and Cardamom',
        'Sandalowood, Fig and Papyrus',
        'Amber, Musk and Oakmoss',
        'woody,powdery,warm spicy,iris,earthy',
        'New York SandalwoodbyBond No 9is a Amber Woody fragrance for women and men.New York Sandalwoodwas launched in 2014. Top notes are Orris, Carrot and Cardamom; middle notes are Sandalowood, Fig and Papyrus; base notes are Amber, Musk and Oakmoss.',
        3.72,
        140,
        NULL
      ),
(
        'NoMad-Tanzanite-87559',
        'NoMad Tanzanite Bond No 9',
        'NoMad',
        'for women and men',
        NULL,
        'Miroslav Petkov',
        'Black Currant, Quince and Pear',
        'Violet Leaves, Agarwood, Orris and Rose',
        'Sandalwood, Vanilla and Amber',
        'fruity,sweet,woody,vanilla,fresh',
        'NoMad TanzanitebyBond No 9is a fragrance for women and men. This is a new fragrance.NoMad Tanzanitewas launched in 2023. The nose behind this fragrance is Miroslav Petkov. Top notes are Black Currant, Quince and Pear; middle notes are Violet Leaves, Agarwood, Orris and Rose; base notes are Sandalwood, Vanilla and Amber.',
        5,
        2,
        NULL
      ),
(
        'Chelsea-Flowers-2874',
        'Chelsea Flowers Bond No 9',
        'Chelsea',
        'for women',
        NULL,
        'Laurent Le Guernec',
        NULL,
        NULL,
        NULL,
        'floral,rose,green,fresh',
        'Chelsea FlowersbyBond No 9is a Floral fragrance for women.Chelsea Flowerswas launched in 2003. The nose behind this fragrance is Laurent Le Guernec.',
        3.64,
        295,
        NULL
      ),
(
        'New-Haarlem-3258',
        'New Haarlem Bond No 9',
        'New',
        'for women and men',
        NULL,
        'Maurice Roucel',
        'Lavender, Bergamot and Green Leaves',
        'Coffee and Cedar',
        'Vanilla, Patchouli, Tonka Bean and Amber',
        'coffee,warm spicy,vanilla,lavender,woody',
        'New HaarlembyBond No 9is a Amber Woody fragrance for women and men.New Haarlemwas launched in 2003. The nose behind this fragrance is Maurice Roucel. Top notes are Lavender, Bergamot and Green Leaves; middle notes are Coffee and Cedar; base notes are Vanilla, Patchouli, Tonka Bean and Amber.',
        4.21,
        1,
        NULL
      ),
(
        'Park-Avenue-3503',
        'Park Avenue Bond No 9',
        'Park',
        'for women',
        NULL,
        'Laurent Le Guernec',
        NULL,
        NULL,
        NULL,
        'yellow floral,floral,powdery,herbal,rose',
        'Park AvenuebyBond No 9is a Floral fragrance for women.Park Avenuewas launched in 2003. The nose behind this fragrance is Laurent Le Guernec.',
        3.85,
        202,
        NULL
      ),
(
        'Riverside-Drive-3491',
        'Riverside Drive Bond No 9',
        'Riverside',
        'for men',
        NULL,
        'Maurice Roucel',
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,powdery,aromatic,violet',
        'Riverside DrivebyBond No 9is a Woody fragrance for men.Riverside Drivewas launched in 2003. The nose behind this fragrance is Maurice Roucel.',
        4.02,
        324,
        NULL
      ),
(
        'So-New-York-7162',
        'So New York Bond No 9',
        'So',
        'for women and men',
        NULL,
        NULL,
        'Mirabelle Plum',
        'Coffee',
        'Cacao and Powdery Notes',
        'warm spicy,cacao,fruity,coffee,sweet',
        'So New YorkbyBond No 9is a fragrance for women and men.So New Yorkwas launched in 2003. Top note is Mirabelle Plum; middle note is Coffee; base notes are Cacao and Powdery Notes.',
        3.98,
        506,
        NULL
      ),
(
        'B9-The-1001-Nights-Solo-Superstar-32983',
        'B9 The 1001 Nights Solo Superstar Bond No 9',
        'B9',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,musky,warm spicy,white floral,powdery',
        'B9 The 1001 Nights Solo SuperstarbyBond No 9is a Amber Spicy fragrance for women and men.B9 The 1001 Nights Solo Superstarwas launched in 2015.',
        3.86,
        7,
        NULL
      ),
(
        'Bond-No-9-Perfume-Swarovski-Edition-42271',
        'Bond No 9 Perfume Swarovski Edition Bond No 9',
        'Bond',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,rose,musky,vanilla,amber',
        'Bond No 9 Perfume Swarovski EditionbyBond No 9is a Amber Floral fragrance for women and men.Bond No 9 Perfume Swarovski Editionwas launched in 2016.',
        3.5,
        6,
        NULL
      ),
(
        'Greenwich-Village-Swarovski-Edition-70370',
        'Greenwich Village Swarovski Edition Bond No 9',
        'Greenwich',
        'for women and men',
        NULL,
        NULL,
        'Litchi, Cassis and Mandarin Orange',
        'Water Lily, Peony and Jasmine',
        'Ambroxan, Vanilla, Praline, Musk and Oakmoss',
        'amber,musky,fresh,vanilla,sweet',
        'Greenwich Village Swarovski EditionbyBond No 9is a Amber Floral fragrance for women and men.Greenwich Village Swarovski Editionwas launched in 2021. Top notes are Litchi, Cassis and Mandarin Orange; middle notes are Water Lily, Peony and Jasmine; base notes are Ambroxan, Vanilla, Praline, Musk and Oakmoss.',
        4.67,
        3,
        NULL
      ),
(
        'New-York-Musk-Emerald-Swarovski-Shooting-Star-17194',
        'New York Musk Emerald Swarovski Shooting Star Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        'Black Currant and Grapefruit blossom',
        'Green Lily, Nutmeg and Osmanthus',
        'Musk, Patchouli, Sandalwood and Vetiver',
        'woody,fruity,white floral,musky,floral',
        'New York Musk Emerald Swarovski Shooting StarbyBond No 9is a Floral Woody Musk fragrance for women and men.New York Musk Emerald Swarovski Shooting Starwas launched in 2012. Top notes are Black Currant and Grapefruit blossom; middle notes are Green Lily, Nutmeg and Osmanthus; base notes are Musk, Patchouli, Sandalwood and Vetiver.',
        4.33,
        3,
        NULL
      ),
(
        'Nuits-de-Noho-Chandelier-22195',
        'Nuits de Noho Chandelier Bond No 9',
        'Nuits',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,patchouli,vanilla,woody,warm spicy',
        'Nuits de Noho ChandelierbyBond No 9is a Chypre Floral fragrance for women and men.Nuits de Noho Chandelierwas launched in 2010.',
        3.83,
        6,
        NULL
      ),
(
        'Perfumista-Avenue-Swarovski-Solo-Stunner-22193',
        'Perfumista Avenue Swarovski Solo Stunner Bond No 9',
        'Perfumista',
        'for women and men',
        NULL,
        NULL,
        'Plum, Saffron, Artemisia and Nutmeg',
        'Rose Oil, Rose Water, Peony and Jasmine',
        'Patchouli, Amber, Musk and Mate',
        'warm spicy,floral,rose,fruity,patchouli',
        'Perfumista Avenue Swarovski Solo StunnerbyBond No 9is a Amber Floral fragrance for women and men.Perfumista Avenue Swarovski Solo Stunnerwas launched in 2013. Top notes are Plum, Saffron, Artemisia and Nutmeg; middle notes are Rose Oil, Rose Water, Peony and Jasmine; base notes are Patchouli, Amber, Musk and Mate.',
        3.22,
        9,
        NULL
      ),
(
        'Soho-Swarovski-Edition-42272',
        'Soho Swarovski Edition Bond No 9',
        'Soho',
        'for women and men',
        NULL,
        NULL,
        'Petitgrain, Sweet Orange and Cassis',
        'Orange Blossom, Jasmine and Orris',
        'Amber, Moss, Cedar and Vetiver',
        'woody,white floral,citrus,aromatic,earthy',
        'Soho Swarovski EditionbyBond No 9is a Floral Woody Musk fragrance for women and men.Soho Swarovski Editionwas launched in 2016. Top notes are Petitgrain, Sweet Orange and Cassis; middle notes are Orange Blossom, Jasmine and Orris; base notes are Amber, Moss, Cedar and Vetiver.',
        4,
        2,
        NULL
      ),
(
        'The-Scent-Of-Peace-Swarovski-Edition-42273',
        'The Scent Of Peace Swarovski Edition Bond No 9',
        'The',
        'for women and men',
        NULL,
        NULL,
        'Black Currant and Grapefruit',
        'Lily-of-the-Valley',
        'Musk and Cedar',
        'woody,musky,fruity,citrus,white floral',
        'The Scent Of Peace Swarovski EditionbyBond No 9is a Floral Woody Musk fragrance for women and men.The Scent Of Peace Swarovski Editionwas launched in 2015. Top notes are Black Currant and Grapefruit; middle note is Lily-of-the-Valley; base notes are Musk and Cedar.',
        3.9,
        10,
        NULL
      ),
(
        'The-Scent-of-Peace-The-Incandescent-Shooting-Super-Star-17195',
        'The Scent of Peace The Incandescent Shooting Super Star Bond No 9',
        'The',
        'for women',
        NULL,
        NULL,
        'Grapefruit and Black Currant',
        'Lily-of-the-Valley',
        'Musk and Cedar',
        'woody,white floral,citrus,musky,fruity',
        'The Scent of Peace The Incandescent Shooting Super StarbyBond No 9is a Floral Woody Musk fragrance for women.The Scent of Peace The Incandescent Shooting Super Starwas launched in 2012. Top notes are Grapefruit and Black Currant; middle note is Lily-of-the-Valley; base notes are Musk and Cedar.',
        4,
        4,
        NULL
      ),
(
        'The-Scent-Of-Peace-Natural-72402',
        'The Scent Of Peace Natural Bond No 9',
        'The',
        'for women and men',
        NULL,
        'Michel Almairac',
        'Lemon, Petitgrain and Black Currant Blossom',
        'Raspberry and Damask Rose',
        'Ambroxan, Cedar and Musk',
        'fruity,citrus,sweet,amber,rose',
        'The Scent Of Peace NaturalbyBond No 9is a Aromatic fragrance for women and men. This is a new fragrance.The Scent Of Peace Naturalwas launched in 2022. The Scent Of Peace Natural was created by Michel Almairac and Romain Almairac. Top notes are Lemon, Petitgrain and Black Currant Blossom; middle notes are Raspberry and Damask Rose; base notes are Ambroxan, Cedar and Musk.',
        4.33,
        72,
        NULL
      ),
(
        'Bond-No9-Harrods-Agarwood-Pure-Tola-Oil-29021',
        'Bond No9 Harrods Agarwood Pure Tola Oil Bond No 9',
        'Bond',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bond No9 Harrods Agarwood Pure Tola OilbyBond No 9is a Amber Woody fragrance for women and men.Bond No9 Harrods Agarwood Pure Tola Oilwas launched in 2014.',
        3.83,
        6,
        NULL
      ),
(
        'Bond-No9-Harrods-Oud-Pure-Tola-Oil-29022',
        'Bond No9 Harrods Oud Pure Tola Oil Bond No 9',
        'Bond',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Bond No9 Harrods Oud Pure Tola OilbyBond No 9is a Amber Woody fragrance for women and men.Bond No9 Harrods Oud Pure Tola Oilwas launched in 2014.',
        4.17,
        6,
        NULL
      ),
(
        'Bond-No9-Perfume-Pure-Tola-Oil-29018',
        'Bond No9 Perfume Pure Tola Oil Bond No 9',
        'Bond',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,musky,vanilla,oud,powdery',
        'Bond No9 Perfume Pure Tola OilbyBond No 9is a Amber Floral fragrance for women and men.Bond No9 Perfume Pure Tola Oilwas launched in 2014.',
        4.29,
        7,
        NULL
      ),
(
        'New-York-Amber-Pure-Tola-Oil-29019',
        'New York Amber Pure Tola Oil Bond No 9',
        'New',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,warm spicy,fresh spicy,floral,powdery',
        'New York Amber Pure Tola OilbyBond No 9is a Amber fragrance for women and men.New York Amber Pure Tola Oilwas launched in 2014.',
        4,
        4,
        NULL
      );
