
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Infinite-Rich-Warm-92679',
        'Infinite Rich Warm Zara',
        'Infinite',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,rum,floral,fresh,powdery',
        'Infinite Rich WarmbyZarais a Amber Vanilla fragrance for women and men. This is a new fragrance.Infinite Rich Warmwas launched in 2024.',
        4.2,
        46,
        NULL
      ),
(
        'Tobacco-Collection-Intense-Dark-Exclusive-40450',
        'Tobacco Collection Intense Dark Exclusive Zara',
        'Tobacco',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,green,tobacco,sweet',
        'Tobacco Collection Intense Dark ExclusivebyZarais a fragrance for men.Tobacco Collection Intense Dark Exclusivewas launched in 2016.',
        3.96,
        835,
        NULL
      ),
(
        'Tobacco-Collection-Intense-Dark-Exclusive-2018-52184',
        'Tobacco Collection Intense Dark Exclusive 2018 Zara',
        'Tobacco',
        'for men',
        NULL,
        NULL,
        'Apple',
        'Black Pepper',
        'Tonka Bean',
        'vanilla,fresh spicy,fruity,amber,warm spicy',
        'Tobacco Collection Intense Dark Exclusive 2018byZarais a Amber fragrance for men.Tobacco Collection Intense Dark Exclusive 2018was launched in 2018. Top note is Apple; middle note is Black Pepper; base note is Tonka Bean.',
        3.91,
        161,
        NULL
      ),
(
        'Tobacco-Collection-Intense-Dark-Exclusive-2021-69135',
        'Tobacco Collection Intense Dark Exclusive 2021 Zara',
        'Tobacco',
        'for men',
        NULL,
        NULL,
        'Apple',
        'Black Pepper',
        'Tonka Bean',
        'fresh spicy,fruity,vanilla,warm spicy,amber',
        'Tobacco Collection Intense Dark Exclusive 2021byZarais a Amber Spicy fragrance for men.Tobacco Collection Intense Dark Exclusive 2021was launched in 2021. Top note is Apple; middle note is Black Pepper; base note is Tonka Bean.',
        4.06,
        502,
        NULL
      ),
(
        'Tobacco-Collection-Rich-Warm-Addictive-40449',
        'Tobacco Collection Rich Warm Addictive Zara',
        'Tobacco',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,honey,coconut,tobacco,woody',
        'Tobacco Collection Rich Warm AddictivebyZarais a fragrance for men.Tobacco Collection Rich Warm Addictivewas launched in 2016.',
        4.26,
        2,
        NULL
      ),
(
        'Tobacco-Collection-Rich-Warm-Addictive-2018-52183',
        'Tobacco Collection Rich Warm Addictive 2018 Zara',
        'Tobacco',
        'for men',
        NULL,
        NULL,
        'Rum',
        'Peony',
        'Bourbon Vanilla',
        'vanilla,rum,floral,fresh,powdery',
        'Tobacco Collection Rich Warm Addictive 2018byZarais a Amber fragrance for men.Tobacco Collection Rich Warm Addictive 2018was launched in 2018. Top note is Rum; middle note is Peony; base note is Bourbon Vanilla.',
        4.24,
        618,
        NULL
      ),
(
        'Tobacco-Collection-Rich-Warm-Addictive-2021-69134',
        'Tobacco Collection Rich Warm Addictive 2021 Zara',
        'Tobacco',
        'for men',
        NULL,
        NULL,
        'Rum',
        'Peony',
        'Bourbon Vanilla',
        'vanilla,rum,powdery,sweet,woody',
        'Tobacco Collection Rich Warm Addictive 2021byZarais a Amber Vanilla fragrance for men.Tobacco Collection Rich Warm Addictive 2021was launched in 2021. Top note is Rum; middle note is Peony; base note is Bourbon Vanilla.',
        4.34,
        1,
        NULL
      ),
(
        'Tobacco-Collection-Unexpected-Fresh-Spicy-57764',
        'Tobacco Collection Unexpected Fresh Spicy Zara',
        'Tobacco',
        'for men',
        NULL,
        'Marine Ipert',
        'Cinnamon, Whiskey and Bergamot',
        'Patchouli, Tobacco and Iris',
        'Sandalwood, Tonka Bean, Vanilla and Benzoin',
        'warm spicy,cinnamon,woody,whiskey,patchouli',
        'Tobacco Collection Unexpected Fresh SpicybyZarais a Woody Spicy fragrance for men.Tobacco Collection Unexpected Fresh Spicywas launched in 2019. The nose behind this fragrance is Marine Ipert. Top notes are Cinnamon, Whiskey and Bergamot; middle notes are Patchouli, Tobacco and Iris; base notes are Sandalwood, Tonka Bean, Vanilla and Benzoin.',
        4.44,
        231,
        NULL
      ),
(
        'Flower-Please-93491',
        '(Flower Please) Zara',
        '(Flower',
        'for men',
        NULL,
        NULL,
        'Linen',
        'Aldehydes and Jasmine',
        'White Musk and Amber',
        'musky,aldehydic,fresh,powdery,white floral',
        '(Flower Please)byZarais a Floral Aldehyde fragrance for men. This is a new fragrance.(Flower Please)was launched in 2024. Top note is Linen; middle notes are Aldehydes and Jasmine; base notes are White Musk and Amber.',
        4.13,
        84,
        NULL
      ),
(
        'Leather-Fever-93492',
        '(Leather Fever) Zara',
        '(Leather',
        'for men',
        NULL,
        'Amandine Galliano',
        'Pear, Violet Leaf and Citrus',
        'Cedarwood',
        'Sandalwood, Vetiver, Musk and Moss',
        'aquatic,fruity,woody,sweet,ozonic',
        '(Leather Fever)byZarais a Woody Aromatic fragrance for men. This is a new fragrance.(Leather Fever)was launched in 2024. The nose behind this fragrance is Amandine Galliano. Top notes are Pear, Violet Leaf and Citrus; middle note is Cedarwood; base notes are Sandalwood, Vetiver, Musk and Moss.',
        3.95,
        78,
        NULL
      ),
(
        'Metamber-93493',
        '(Metamber) Zara',
        '(Metamber)',
        'for men',
        NULL,
        NULL,
        'Black Pepper',
        'White Amber',
        'Musk and Moss',
        'amber,musky,powdery,animalic,fresh spicy',
        '(Metamber)byZarais a Amber Woody fragrance for men. This is a new fragrance.(Metamber)was launched in 2024. Top note is Black Pepper; middle note is White Amber; base notes are Musk and Moss.',
        3.34,
        41,
        NULL
      ),
(
        'Shamanilla-93494',
        '(Shamanilla) Zara',
        '(Shamanilla)',
        'for men',
        NULL,
        NULL,
        'Coconut Water, Cardamom and Bergamot',
        'Sandalwood, Peach Blossom and Carrot',
        'Vanilla, Cotton Candy and Amyris',
        'vanilla,sweet,powdery,woody,warm spicy',
        '(Shamanilla)byZarais a Floral fragrance for men. This is a new fragrance.(Shamanilla)was launched in 2024. Top notes are Coconut Water, Cardamom and Bergamot; middle notes are Sandalwood, Peach Blossom and Carrot; base notes are Vanilla, Cotton Candy and Amyris.',
        4.11,
        173,
        NULL
      ),
(
        'Vetiverich-93495',
        '(Vetiverich) Zara',
        '(Vetiverich)',
        'for men',
        NULL,
        NULL,
        'Saffron, Pear and Bergamot',
        'Violet Leaf and Jasmine Leaf',
        'Vetiver and Cedarwood',
        'woody,ozonic,aromatic,aquatic,earthy',
        '(Vetiverich)byZarais a Woody Aromatic fragrance for men. This is a new fragrance.(Vetiverich)was launched in 2024. Top notes are Saffron, Pear and Bergamot; middle notes are Violet Leaf and Jasmine Leaf; base notes are Vetiver and Cedarwood.',
        4.09,
        69,
        NULL
      ),
(
        'Wood-Legacy-93496',
        '(Wood Legacy) Zara',
        '(Wood',
        'for women and men',
        NULL,
        'Alexis Dadier',
        'Dark Chocolate, Oak and Black Pepper',
        'Cedarwood and Tonka Bean',
        'Patchouli, Amber, Vanilla, Musk and Moss',
        'woody,warm spicy,amber,chocolate,vanilla',
        '(Wood Legacy)byZarais a Amber Woody fragrance for women and men. This is a new fragrance.(Wood Legacy)was launched in 2024. The nose behind this fragrance is Alexis Dadier. Top notes are Dark Chocolate, Oak and Black Pepper; middle notes are Cedarwood and Tonka Bean; base notes are Patchouli, Amber, Vanilla, Musk and Moss.',
        3.85,
        66,
        NULL
      ),
(
        'In-Fiji-72634',
        'In Fiji Zara',
        'In',
        'for men',
        NULL,
        NULL,
        'Clementine and Bitter Orange',
        'Sichuan Pepper',
        'Amber and Woody Notes',
        'citrus,fresh spicy,amber,woody',
        'In FijibyZarais a Citrus Aromatic fragrance for men. This is a new fragrance.In Fijiwas launched in 2022. Top notes are Clementine and Bitter Orange; middle note is Sichuan Pepper; base notes are Amber and Woody Notes.',
        4.03,
        37,
        NULL
      ),
(
        'In-St-Tropez-72632',
        'In St Tropez Zara',
        'In',
        'for men',
        NULL,
        NULL,
        'Citruses and Pepper',
        'Bellini, Olibanum and Geranium',
        'Salt and Woodsy Notes',
        'fresh spicy,fruity,vanilla,citrus,salty',
        'In St TropezbyZarais a fragrance for men. This is a new fragrance.In St Tropezwas launched in 2022. Top notes are Citruses and Pepper; middle notes are Bellini, Olibanum and Geranium; base notes are Salt and Woodsy Notes.',
        4.21,
        128,
        NULL
      ),
(
        'In-Tulum-72633',
        'In Tulum Zara',
        'In',
        'for men',
        NULL,
        NULL,
        'Ginger',
        'Watermelon',
        'Sea water',
        'aquatic,marine,ozonic,warm spicy,aromatic',
        'In TulumbyZarais a Aromatic Aquatic fragrance for men. This is a new fragrance.In Tulumwas launched in 2022. Top note is Ginger; middle note is Watermelon; base note is Sea water.',
        4.11,
        45,
        NULL
      ),
(
        'Vibrant-Leather-41963',
        'Vibrant Leather Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Lemon and Bergamot',
        'Leather and Bamboo',
        'Patchouli',
        'citrus,woody,leather,patchouli,aromatic',
        'Vibrant LeatherbyZarais a Woody fragrance for men.Vibrant Leatherwas launched in 2016. The nose behind this fragrance is Jérôme Epinette. Top notes are Lemon and Bergamot; middle notes are Leather and Bamboo; base note is Patchouli.',
        4.17,
        613,
        NULL
      ),
(
        'Vibrant-Leather-Bogoss-66891',
        'Vibrant Leather Bogoss Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Lemon, Bergamot and Grapefruit',
        'Pineapple',
        'Cedar, Leather and Patchouli',
        'fruity,sweet,tropical,fresh,citrus',
        'Vibrant Leather BogossbyZarais a Woody Aromatic fragrance for men.Vibrant Leather Bogosswas launched in 2021. The nose behind this fragrance is Jérôme Epinette. Top notes are Lemon, Bergamot and Grapefruit; middle note is Pineapple; base notes are Cedar, Leather and Patchouli.',
        4.3,
        860,
        NULL
      ),
(
        'Vibrant-Leather-Bogoss-Summer-92831',
        'Vibrant Leather Bogoss Summer Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,fruity,sweet,tropical',
        'Vibrant Leather Bogoss SummerbyZarais a Aromatic Fruity fragrance for men. This is a new fragrance.Vibrant Leather Bogoss Summerwas launched in 2024. The nose behind this fragrance is Jérôme Epinette.',
        4.51,
        77,
        NULL
      ),
(
        'Vibrant-Leather-Boise-66890',
        'Vibrant Leather Boise Zara',
        'Vibrant',
        'for men',
        NULL,
        NULL,
        'Labdanum',
        'Incense',
        'Palo Santo and Leather',
        'amber,woody,smoky,balsamic,leather',
        'Vibrant Leather BoisebyZarais a Woody fragrance for men.Vibrant Leather Boisewas launched in 2021. Top note is Labdanum; middle note is Incense; base notes are Palo Santo and Leather.',
        4.08,
        182,
        NULL
      ),
(
        'Vibrant-Leather-Cologne-55086',
        'Vibrant Leather Cologne Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Bergamot',
        'Ginger',
        'Cedar',
        'citrus,warm spicy,fresh spicy,woody,aromatic',
        'Vibrant Leather ColognebyZarais a Woody Spicy fragrance for men.Vibrant Leather Colognewas launched in 2019. The nose behind this fragrance is Jérôme Epinette. Top note is Bergamot; middle note is Ginger; base note is Cedar.',
        4.37,
        312,
        NULL
      ),
(
        'Vibrant-Leather-Eau-de-Parfum-50122',
        'Vibrant Leather Eau de Parfum Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Bergamot',
        'Bamboo',
        'Leather',
        'citrus,leather,fresh spicy,woody,aromatic',
        'Vibrant Leather Eau de ParfumbyZarais a Leather fragrance for men.Vibrant Leather Eau de Parfumwas launched in 2018. The nose behind this fragrance is Jérôme Epinette. Top note is Bergamot; middle note is Bamboo; base note is Leather.',
        4.22,
        2,
        NULL
      ),
(
        'Vibrant-Leather-Eclat-de-Bergamote-66893',
        'Vibrant Leather Eclat de Bergamote Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Orange, Bergamot and Pink Pepper',
        'Tonka Bean',
        'Leather and Woodsy Notes',
        'citrus,leather,sweet,fresh spicy,vanilla',
        'Vibrant Leather Eclat de BergamotebyZarais a Citrus Aromatic fragrance for men.Vibrant Leather Eclat de Bergamotewas launched in 2021. The nose behind this fragrance is Jérôme Epinette. Top notes are Orange, Bergamot and Pink Pepper; middle note is Tonka Bean; base notes are Leather and Woodsy Notes.',
        4.22,
        175,
        NULL
      ),
(
        'Vibrant-Leather-Encens-72724',
        'Vibrant Leather Encens Zara',
        'Vibrant',
        'for men',
        NULL,
        NULL,
        'Peruvian Pepper',
        'Olibanum',
        'Elemi resin',
        'amber,fresh spicy,aromatic,warm spicy,balsamic',
        'Vibrant Leather EncensbyZarais a Leather fragrance for men. This is a new fragrance.Vibrant Leather Encenswas launched in 2022. Top note is Peruvian Pepper; middle note is Olibanum; base note is Elemi resin.',
        3.96,
        55,
        NULL
      ),
(
        'Vibrant-Leather-Epice-66892',
        'Vibrant Leather Epice Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Cardamom',
        'Rose and Nutmeg',
        'Leather',
        'rose,leather,warm spicy,fresh spicy,floral',
        'Vibrant Leather EpicebyZarais a Woody Spicy fragrance for men.Vibrant Leather Epicewas launched in 2021. The nose behind this fragrance is Jérôme Epinette. Top note is Cardamom; middle notes are Rose and Nutmeg; base note is Leather.',
        4.29,
        63,
        NULL
      ),
(
        'Vibrant-Leather-Explosion-92814',
        'Vibrant Leather Explosion Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Bergamot and Black Pepper',
        'Bamboo and Violet Leaf',
        'Cotton Candy, Black Amber and Patchouli',
        'citrus,sweet,fresh spicy,woody,caramel',
        'Vibrant Leather ExplosionbyZarais a Leather fragrance for men. This is a new fragrance.Vibrant Leather Explosionwas launched in 2024. The nose behind this fragrance is Jérôme Epinette. Top notes are Bergamot and Black Pepper; middle notes are Bamboo and Violet Leaf; base notes are Cotton Candy, Black Amber and Patchouli.',
        4.38,
        85,
        NULL
      ),
(
        'Vibrant-Leather-for-Her-47918',
        'Vibrant Leather for Her Zara',
        'Vibrant',
        'for women',
        NULL,
        NULL,
        'Lemon, Bergamot and Pear',
        'Leather, Bamboo and Floral Notes',
        'Papyrus, Patchouli, Vanila and Sweet Notes',
        'woody,leather,citrus,patchouli,sweet',
        'Vibrant Leather for HerbyZarais a Chypre Floral fragrance for women.Vibrant Leather for Herwas launched in 2017. Top notes are Lemon, Bergamot and Pear; middle notes are Leather, Bamboo and Floral Notes; base notes are Papyrus, Patchouli, Vanila and Sweet Notes.',
        4.25,
        32,
        NULL
      ),
(
        'Vibrant-Leather-for-Her-2018-49766',
        'Vibrant Leather for Her 2018 Zara',
        'Vibrant',
        'for women',
        NULL,
        NULL,
        'Pear, Bergamot and Lemon',
        'Leather, Flowers and Bamboo',
        'Sweet Notes, Papyrus, Patchouli and Vanilla',
        'leather,woody,sweet,citrus,floral',
        'Vibrant Leather for Her 2018byZarais a Leather fragrance for women.Vibrant Leather for Her 2018was launched in 2018. Top notes are Pear, Bergamot and Lemon; middle notes are Leather, Flowers and Bamboo; base notes are Sweet Notes, Papyrus, Patchouli and Vanilla.',
        4.05,
        62,
        NULL
      ),
(
        'Vibrant-Leather-For-Her-2020-62357',
        'Vibrant Leather For Her 2020 Zara',
        'Vibrant',
        'for women',
        NULL,
        NULL,
        'Red Currant',
        'Leather',
        'Patchouli',
        'fruity,patchouli,leather,soft spicy,woody',
        'Vibrant Leather For Her 2020byZarais a Leather fragrance for women.Vibrant Leather For Her 2020was launched in 2020. Top note is Red Currant; middle note is Leather; base note is Patchouli.',
        4.11,
        28,
        NULL
      ),
(
        'Vibrant-Leather-for-Her-2021-66974',
        'Vibrant Leather for Her 2021 Zara',
        'Vibrant',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,patchouli,leather,soft spicy,woody',
        'Vibrant Leather for Her 2021byZarais a Chypre Floral fragrance for women.Vibrant Leather for Her 2021was launched in 2021.',
        4.07,
        214,
        NULL
      ),
(
        'Vibrant-Leather-Intense-67174',
        'Vibrant Leather Intense Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Woody Notes',
        'Papyrus',
        'Sandalwood',
        'woody',
        'Vibrant Leather IntensebyZarais a Woody fragrance for men.Vibrant Leather Intensewas launched in 2021. The nose behind this fragrance is Jérôme Epinette. Top note is Woody Notes; middle note is Papyrus; base note is Sandalwood.',
        4,
        147,
        NULL
      ),
(
        'Vibrant-Leather-Metal-63085',
        'Vibrant Leather Metal Zara',
        'Vibrant',
        'for men',
        NULL,
        'Daphné Bugey',
        NULL,
        NULL,
        NULL,
        'warm spicy,woody',
        'Vibrant Leather MetalbyZarais a Woody Spicy fragrance for men.Vibrant Leather Metalwas launched in 2020. The nose behind this fragrance is Daphné Bugey.',
        3.98,
        83,
        NULL
      ),
(
        'Vibrant-Leather-Oud-53691',
        'Vibrant Leather Oud Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Bergamot',
        'Incense and Woody Notes',
        'Agarwood (Oud) and Amber',
        'amber,citrus,woody,fresh spicy,smoky',
        'Vibrant Leather OudbyZarais a Woody fragrance for men.Vibrant Leather Oudwas launched in 2019. The nose behind this fragrance is Jérôme Epinette. Top note is Bergamot; middle notes are Incense and Woody Notes; base notes are Agarwood (Oud) and Amber.',
        4.09,
        1,
        NULL
      ),
(
        'Vibrant-Leather-Parfum-de-Liberte-66894',
        'Vibrant Leather Parfum de Liberte Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Grapefruit',
        'Pepper',
        'Leather',
        'citrus,fresh spicy,leather,aromatic,animalic',
        'Vibrant Leather Parfum de LibertebyZarais a Leather fragrance for men.Vibrant Leather Parfum de Libertewas launched in 2021. The nose behind this fragrance is Jérôme Epinette. Top note is Grapefruit; middle note is Pepper; base note is Leather.',
        4.18,
        55,
        NULL
      ),
(
        'Vibrant-Leather-Platinum-63086',
        'Vibrant Leather Platinum Zara',
        'Vibrant',
        'for men',
        NULL,
        'Marc Zini',
        NULL,
        NULL,
        NULL,
        'woody,amber',
        'Vibrant Leather PlatinumbyZarais a Amber Woody fragrance for men.Vibrant Leather Platinumwas launched in 2020. The nose behind this fragrance is Marc Zini.',
        4.02,
        112,
        NULL
      ),
(
        'Vibrant-Leather-Summer-59363',
        'Vibrant Leather Summer Zara',
        'Vibrant',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        'Ginger',
        'Cedar',
        'citrus,warm spicy,fresh spicy,woody,aromatic',
        'Vibrant Leather SummerbyZarais a Woody Aromatic fragrance for men.Vibrant Leather Summerwas launched in 2020. Top note is Bergamot; middle note is Ginger; base note is Cedar.',
        4.34,
        395,
        NULL
      ),
(
        'Vibrant-Leather-Warm-63084',
        'Vibrant Leather Warm Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Ambrette (Musk Mallow)',
        'Iris',
        'Woodsy Notes',
        'iris,musky,floral,woody,powdery',
        'Vibrant Leather WarmbyZarais a Woody Spicy fragrance for men.Vibrant Leather Warmwas launched in 2020. The nose behind this fragrance is Jérôme Epinette. Top note is Ambrette (Musk Mallow); middle note is Iris; base note is Woodsy Notes.',
        3.95,
        136,
        NULL
      ),
(
        'Vibrant-Leather-Winter-63087',
        'Vibrant Leather Winter Zara',
        'Vibrant',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy',
        'Vibrant Leather WinterbyZarais a Woody fragrance for men.Vibrant Leather Winterwas launched in 2020.',
        4.41,
        58,
        NULL
      ),
(
        'Vibrant-Leather-Sandalwood-Elixir-91436',
        'Vibrant Leather & Sandalwood Elixir Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Cardamom',
        'Carrot Seeds',
        'Sandalwood and Woody Notes',
        'woody,warm spicy,powdery,aromatic',
        'Vibrant Leather & Sandalwood ElixirbyZarais a fragrance for men. This is a new fragrance.Vibrant Leather & Sandalwood Elixirwas launched in 2024. The nose behind this fragrance is Jérôme Epinette. Top note is Cardamom; middle note is Carrot Seeds; base notes are Sandalwood and Woody Notes.',
        4.07,
        67,
        NULL
      ),
(
        'Vibrant-Leather-Tobacco-Elixir-91437',
        'Vibrant Leather & Tobacco Elixir Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        'Black Leather',
        'Tobacco',
        'Vanilla',
        'vanilla,tobacco,sweet,powdery',
        'Vibrant Leather & Tobacco ElixirbyZarais a fragrance for men. This is a new fragrance.Vibrant Leather & Tobacco Elixirwas launched in 2024. The nose behind this fragrance is Jérôme Epinette. Top note is Black Leather; middle note is Tobacco; base note is Vanilla.',
        4.46,
        104,
        NULL
      ),
(
        'Vibrant-Leather-Violet-Elixir-91438',
        'Vibrant Leather & Violet Elixir Zara',
        'Vibrant',
        'for men',
        NULL,
        'Jérôme Epinette',
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,leather,musky,green',
        'Vibrant Leather & Violet ElixirbyZarais a fragrance for men. This is a new fragrance.Vibrant Leather & Violet Elixirwas launched in 2024. The nose behind this fragrance is Jérôme Epinette.',
        4.02,
        42,
        NULL
      ),
(
        'Friday-Freaking-Gorgeous-83877',
        'Friday - Freaking Gorgeous Zara',
        'Friday',
        'for women and men',
        NULL,
        NULL,
        'Bitter Almond and Bergamot',
        'Sandalwood, Lily of the Valley and Rose',
        'Vanilla, Musk and Tonka',
        'vanilla,almond,powdery,sweet,nutty',
        'Friday - Freaking GorgeousbyZarais a fragrance for women and men. This is a new fragrance.Friday - Freaking Gorgeouswas launched in 2023. Top notes are Bitter Almond and Bergamot; middle notes are Sandalwood, Lily of the Valley and Rose; base notes are Vanilla, Musk and Tonka.',
        3.99,
        103,
        NULL
      ),
(
        'Monday-No-Drama-Allowed-83873',
        'Monday - No Drama Allowed Zara',
        'Monday',
        'for women and men',
        NULL,
        NULL,
        'Rose Water, Pink Pepper and Spices',
        'Rose, Rose Jam and Raspberry',
        'White Musk, Amber and Leather',
        'rose,musky,sweet,soft spicy,floral',
        'Monday - No Drama AllowedbyZarais a fragrance for women and men. This is a new fragrance.Monday - No Drama Allowedwas launched in 2023. Top notes are Rose Water, Pink Pepper and Spices; middle notes are Rose, Rose Jam and Raspberry; base notes are White Musk, Amber and Leather.',
        3.92,
        78,
        NULL
      ),
(
        'Thursday-No-Valentines-But-Flowers-83876',
        'Thursday - No Valentines But Flowers Zara',
        'Thursday',
        'for women and men',
        NULL,
        'Coralie Spicher',
        'Litchi, Rhubarb and Bergamot',
        'Raspberry, Peony and Pink Pepper',
        'White Musk, Vanilla, Praline and Cedar',
        'fruity,sweet,fresh,musky,floral',
        'Thursday - No Valentines But FlowersbyZarais a fragrance for women and men. This is a new fragrance.Thursday - No Valentines But Flowerswas launched in 2023. The nose behind this fragrance is Coralie Spicher. Top notes are Litchi, Rhubarb and Bergamot; middle notes are Raspberry, Peony and Pink Pepper; base notes are White Musk, Vanilla, Praline and Cedar.',
        4.07,
        99,
        NULL
      ),
(
        'Tuesday-Totally-Terrific-83874',
        'Tuesday - Totally Terrific Zara',
        'Tuesday',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Lemon',
        'Iris and Cardamom',
        'Vanilla and Whipped Cream',
        'iris,vanilla,powdery,warm spicy,citrus',
        'Tuesday - Totally TerrificbyZarais a fragrance for women and men. This is a new fragrance.Tuesday - Totally Terrificwas launched in 2023. Top notes are Bergamot and Lemon; middle notes are Iris and Cardamom; base notes are Vanilla and Whipped Cream.',
        3.82,
        123,
        NULL
      ),
(
        'Wednesday-I-m-Most-Grateful-83875',
        'Wednesday - I''m Most Grateful Zara',
        'Wednesday',
        'for women and men',
        NULL,
        NULL,
        'Pear, Freesia and Pink Pepper',
        'Apple Blossom, Violet and Orchid',
        'Sandalwood, Vanilla and Cedar',
        'floral,powdery,fruity,woody,sweet',
        'Wednesday - I''m Most GratefulbyZarais a fragrance for women and men. This is a new fragrance.Wednesday - I''m Most Gratefulwas launched in 2023. Top notes are Pear, Freesia and Pink Pepper; middle notes are Apple Blossom, Violet and Orchid; base notes are Sandalwood, Vanilla and Cedar.',
        4.16,
        104,
        NULL
      ),
(
        'Man-Silver-Winter-56291',
        'Man Silver Winter Zara',
        'Man',
        'for men',
        NULL,
        NULL,
        'Mint',
        'Amber',
        'Sandalowood',
        'green,amber,aromatic,fresh spicy,woody',
        'Man Silver WinterbyZarais a Woody Aromatic fragrance for men.Man Silver Winterwas launched in 2019. Top note is Mint; middle note is Amber; base note is Sandalowood.',
        3.86,
        29,
        NULL
      ),
(
        'Seoul-532-8-Sinsa-Dong-Gangnam-Gu-Winter-56292',
        'Seoul 532-8 Sinsa Dong Gangnam-Gu Winter Zara',
        'Seoul',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Apple',
        'Woody Notes',
        'fruity,citrus,fresh,green,woody',
        'Seoul 532-8 Sinsa Dong Gangnam-Gu WinterbyZarais a Aromatic Fruity fragrance for men.Seoul 532-8 Sinsa Dong Gangnam-Gu Winterwas launched in 2019. Top note is Mandarin Orange; middle note is Apple; base note is Woody Notes.',
        3.99,
        149,
        NULL
      ),
(
        'Winter-Collection-51213',
        'Winter Collection Zara',
        'Winter',
        'for men',
        NULL,
        NULL,
        'Pepper, Bergamot and Tangerine',
        'Eucalyptus and Lavender',
        'Cypress, Amber, Cedar, Orange Blossom and Patchouli',
        'woody,aromatic,fresh spicy,citrus,amber',
        'Winter CollectionbyZarais a Woody Aromatic fragrance for men.Winter Collectionwas launched in 2018. Top notes are Pepper, Bergamot and Tangerine; middle notes are Eucalyptus and Lavender; base notes are Cypress, Amber, Cedar, Orange Blossom and Patchouli.',
        3.96,
        70,
        NULL
      ),
(
        'Femme-Winter-56285',
        'Femme Winter Zara',
        'Femme',
        'for women',
        NULL,
        NULL,
        'Peony',
        'Almond',
        'Vanilla',
        'almond,vanilla,floral,nutty,sweet',
        'Femme WinterbyZarais a Amber Floral fragrance for women.Femme Winterwas launched in 2019. Top note is Peony; middle note is Almond; base note is Vanilla.',
        3.88,
        56,
        NULL
      ),
(
        'Pink-Flambe-Winter-56284',
        'Pink Flambe Winter Zara',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Pear',
        'Violet',
        'Praline',
        'sweet,violet,fruity,powdery,fresh',
        'Pink Flambe WinterbyZarais a Floral Fruity Gourmand fragrance for women.Pink Flambe Winterwas launched in 2019. Top note is Pear; middle note is Violet; base note is Praline.',
        3.81,
        68,
        NULL
      ),
(
        'Tuberose-Winter-56283',
        'Tuberose Winter Zara',
        'Tuberose',
        'for women',
        NULL,
        NULL,
        'Iris',
        'Tuberose',
        'Vanilla',
        'iris,tuberose,powdery,white floral,vanilla',
        'Tuberose WinterbyZarais a Amber Floral fragrance for women.Tuberose Winterwas launched in 2019. Top note is Iris; middle note is Tuberose; base note is Vanilla.',
        3.86,
        59,
        NULL
      ),
(
        'Twilight-Mauve-Winter-56282',
        'Twilight Mauve Winter Zara',
        'Twilight',
        'for women',
        NULL,
        NULL,
        'Red Apple',
        'Freesia',
        'Coffee',
        'fruity,coffee,floral,warm spicy,sweet',
        'Twilight Mauve WinterbyZarais a Floral Fruity Gourmand fragrance for women.Twilight Mauve Winterwas launched in 2019. Top note is Red Apple; middle note is Freesia; base note is Coffee.',
        4.11,
        44,
        NULL
      ),
(
        'WO-01-Somewoody-87740',
        'WO/01 Somewoody Zara',
        'WO/01',
        'for men',
        NULL,
        NULL,
        'Lavender and Cinnamon',
        'Musk, Cedarwood and White Flowers',
        'Woody Notes, Vanilla and Amber',
        'woody,lavender,powdery,musky,vanilla',
        'WO/01 SomewoodybyZarais a Amber Woody fragrance for men. This is a new fragrance.WO/01 Somewoodywas launched in 2023. Top notes are Lavender and Cinnamon; middle notes are Musk, Cedarwood and White Flowers; base notes are Woody Notes, Vanilla and Amber.',
        4.23,
        232,
        NULL
      ),
(
        'WO-02-Wood-Street-87741',
        'WO/02 Wood Street Zara',
        'WO/02',
        'for men',
        NULL,
        NULL,
        'Black Pepper and Frankincense',
        'Cedar, Guaiac Wood and Rum',
        'Vetiver, Leather and Vanilla',
        'woody,fresh spicy,amber,warm spicy,aromatic',
        'WO/02 Wood StreetbyZarais a Leather fragrance for men. This is a new fragrance.WO/02 Wood Streetwas launched in 2023. Top notes are Black Pepper and Frankincense; middle notes are Cedar, Guaiac Wood and Rum; base notes are Vetiver, Leather and Vanilla.',
        3.86,
        169,
        NULL
      ),
(
        'WO-03-Cafe-Et-Cedre-87742',
        'WO/03 Café Et Cèdre Zara',
        'WO/03',
        'for men',
        NULL,
        NULL,
        'Black Pepper, Bergamot and Coffee',
        'Orris Root, Frankincense and Clary Sage',
        'Amberwood, Palo Santo, Tonka Bean and Cashmeran',
        'woody,amber,iris,powdery,aromatic',
        'WO/03 Café Et CèdrebyZarais a Woody fragrance for men. This is a new fragrance.WO/03 Café Et Cèdrewas launched in 2023. Top notes are Black Pepper, Bergamot and Coffee; middle notes are Orris Root, Frankincense and Clary Sage; base notes are Amberwood, Palo Santo, Tonka Bean and Cashmeran.',
        4.33,
        245,
        NULL
      ),
(
        'Fresh-Sandalwood-56288',
        'Fresh Sandalwood Zara',
        'Fresh',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        'Sandalwood',
        'Musk',
        'woody,powdery,citrus,musky,warm spicy',
        'Fresh SandalwoodbyZarais a Woody Aromatic fragrance for men.Fresh Sandalwoodwas launched in 2019. Top note is Bergamot; middle note is Sandalwood; base note is Musk.',
        4,
        66,
        NULL
      ),
(
        'Noble-Palo-Santo-56290',
        'Noble Palo Santo Zara',
        'Noble',
        'for men',
        NULL,
        NULL,
        'Kumquat',
        'Black Pepper',
        'Palo Santo',
        'citrus,woody,fresh spicy,aromatic,warm spicy',
        'Noble Palo SantobyZarais a Woody Spicy fragrance for men.Noble Palo Santowas launched in 2019. Top note is Kumquat; middle note is Black Pepper; base note is Palo Santo.',
        4.19,
        150,
        NULL
      ),
(
        'Raw-Vetiver-56287',
        'Raw Vetiver Zara',
        'Raw',
        'for men',
        NULL,
        NULL,
        'Ginger',
        'Iris',
        'Vetiver',
        'warm spicy,earthy,iris,woody,aromatic',
        'Raw VetiverbyZarais a Woody Spicy fragrance for men.Raw Vetiverwas launched in 2019. Top note is Ginger; middle note is Iris; base note is Vetiver.',
        3.8,
        75,
        NULL
      ),
(
        'Sublime-Cedar-56289',
        'Sublime Cedar Zara',
        'Sublime',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Sublime CedarbyZarais a Amber Woody fragrance for men.Sublime Cedarwas launched in 2019.',
        4.28,
        54,
        NULL
      ),
(
        'Kilsbergen-47977',
        'Kilsbergen Zara',
        'Kilsbergen',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        'Orange Blossom',
        'Tonka Bean',
        'citrus,white floral,vanilla,sweet,aromatic',
        'KilsbergenbyZarais a Woody Aromatic fragrance for men.Kilsbergenwas launched in 2017. Top note is Bergamot; middle note is Orange Blossom; base note is Tonka Bean.',
        4.09,
        35,
        NULL
      ),
(
        'Norrland-47975',
        'Norrland Zara',
        'Norrland',
        'for men',
        NULL,
        NULL,
        'Grapefruit',
        'Pepper',
        'Vetiver',
        'fresh spicy,aromatic,citrus,woody,earthy',
        'NorrlandbyZarais a Woody Spicy fragrance for men.Norrlandwas launched in 2017. Top note is Grapefruit; middle note is Pepper; base note is Vetiver.',
        4.3,
        63,
        NULL
      ),
(
        'Tiveden-47980',
        'Tiveden Zara',
        'Tiveden',
        'for men',
        NULL,
        NULL,
        'Cardamom',
        'Sandalwood',
        'Leather and Musk',
        'warm spicy,woody,leather,powdery,animalic',
        'TivedenbyZarais a Amber Woody fragrance for men.Tivedenwas launched in 2017. Top note is Cardamom; middle note is Sandalwood; base notes are Leather and Musk.',
        4.22,
        105,
        NULL
      ),
(
        'Z-1975-Blue-Spirit-34478',
        'Z - 1975 Blue Spirit Zara',
        'Z',
        'for men',
        NULL,
        NULL,
        'Tangerine',
        'Lavender, Ylang-Ylang, Nutmeg and Pepper',
        'Leather and Amber',
        'lavender,citrus,leather,fresh spicy,animalic',
        'Z - 1975 Blue SpiritbyZarais a Woody Spicy fragrance for men.Z - 1975 Blue Spiritwas launched in 2015. Top note is Tangerine; middle notes are Lavender, Ylang-Ylang, Nutmeg and Pepper; base notes are Leather and Amber.',
        4.23,
        13,
        NULL
      ),
(
        'Z-1975-Casual-Spice-34477',
        'Z - 1975 Casual Spice Zara',
        'Z',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        'Pink Pepper, Pepper and Lavender',
        'Vanilla, Tonka Bean and Musk',
        'vanilla,fresh spicy,musky,sweet,soft spicy',
        'Z - 1975 Casual SpicebyZarais a Amber Spicy fragrance for men.Z - 1975 Casual Spicewas launched in 2015. Top note is Bergamot; middle notes are Pink Pepper, Pepper and Lavender; base notes are Vanilla, Tonka Bean and Musk.',
        4.38,
        13,
        NULL
      ),
(
        'Accord-No-1-Floral-45382',
        'Accord No 1 Floral Zara',
        'Accord',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Jasmine, Lotus and Honeysuckle',
        'Vanilla',
        'white floral,floral,citrus,vanilla,fresh spicy',
        'Accord No 1 FloralbyZarais a Floral fragrance for women.Accord No 1 Floralwas launched in 2017. Top note is Bergamot; middle notes are Jasmine, Lotus and Honeysuckle; base note is Vanilla.',
        4.2,
        44,
        NULL
      ),
(
        'Accord-No-2-Oriental-45383',
        'Accord No 2 Oriental Zara',
        'Accord',
        'for women',
        NULL,
        NULL,
        'Geranium, Rose and Lily-of-the-Valley',
        'Chocolate, Walnut and Hawthorn',
        'Vanilla, Tonka Bean, Cedar and Amber',
        'vanilla,woody,sweet,nutty,amber',
        'Accord No 2 OrientalbyZarais a Amber fragrance for women.Accord No 2 Orientalwas launched in 2017. Top notes are Geranium, Rose and Lily-of-the-Valley; middle notes are Chocolate, Walnut and Hawthorn; base notes are Vanilla, Tonka Bean, Cedar and Amber.',
        3.82,
        135,
        NULL
      ),
(
        'Accord-No-3-Woody-45384',
        'Accord No 3 Woody Zara',
        'Accord',
        'for women',
        NULL,
        NULL,
        'Violet Leaf, Freesia and Apple',
        'Cedar, Violet and Ambroxan',
        'Mate, Ambrette (Musk Mallow) and Spices',
        'floral,woody,ozonic,aquatic,musky',
        'Accord No 3 WoodybyZarais a Woody Spicy fragrance for women.Accord No 3 Woodywas launched in 2017. Top notes are Violet Leaf, Freesia and Apple; middle notes are Cedar, Violet and Ambroxan; base notes are Mate, Ambrette (Musk Mallow) and Spices.',
        4.35,
        151,
        NULL
      ),
(
        'Accord-No-4-Chypre-45385',
        'Accord No 4 Chypre Zara',
        'Accord',
        'for women',
        NULL,
        NULL,
        'Peony and Pomegranate',
        'Rose and Apricot',
        'Patchouli and Musk',
        'rose,patchouli,musky,woody,floral',
        'Accord No 4 ChyprebyZarais a Chypre fragrance for women.Accord No 4 Chyprewas launched in 2017. Top notes are Peony and Pomegranate; middle notes are Rose and Apricot; base notes are Patchouli and Musk.',
        4.2,
        66,
        NULL
      ),
(
        'Femme-Aqua-48601',
        'Femme Aqua Zara',
        'Femme',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,woody,citrus,fresh,powdery',
        'Femme AquabyZarais a Amber Floral fragrance for women.Femme Aquawas launched in 2018.',
        3.87,
        15,
        NULL
      ),
(
        'Forget-Me-Not-Aqua-48598',
        'Forget Me Not Aqua Zara',
        'Forget',
        'for women',
        NULL,
        NULL,
        'Green Apple',
        'Hyacinth',
        'Musk, Cedar and Amber',
        'green,fruity,musky,fresh spicy,amber',
        'Forget Me Not AquabyZarais a Floral Woody Musk fragrance for women.Forget Me Not Aquawas launched in 2018. Top note is Green Apple; middle note is Hyacinth; base notes are Musk, Cedar and Amber.',
        4,
        17,
        NULL
      ),
(
        'Tuberose-Aqua-48599',
        'Tuberose Aqua Zara',
        'Tuberose',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,powdery,woody,vanilla,musky',
        'Tuberose AquabyZarais a Floral Fruity fragrance for women.Tuberose Aquawas launched in 2018.',
        4.06,
        18,
        NULL
      ),
(
        'Twilight-Mauve-Aqua-48600',
        'Twilight Mauve Aqua Zara',
        'Twilight',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,aquatic,ozonic,violet',
        'Twilight Mauve AquabyZarais a Floral Fruity fragrance for women.Twilight Mauve Aquawas launched in 2018.',
        3.68,
        19,
        NULL
      ),
(
        'Caramelos-Artesanos-en-Barcelona-44761',
        'Caramelos Artesanos en Barcelona Zara',
        'Caramelos',
        'for women',
        NULL,
        NULL,
        'Raspberry',
        'Peony',
        'Sandalwood',
        'fruity,sweet,floral,rose,fresh',
        'Caramelos Artesanos en BarcelonabyZarais a Amber Vanilla fragrance for women.Caramelos Artesanos en Barcelonawas launched in 2017. Top note is Raspberry; middle note is Peony; base note is Sandalwood.',
        4.08,
        106,
        NULL
      ),
(
        'Fleuriste-A-Paris-44744',
        'Fleuriste A Paris Zara',
        'Fleuriste',
        'for women',
        NULL,
        NULL,
        'Green Notes, Bergamot and Citruses',
        'Amyl Salicylate and Peony',
        'Musk and Chocolate',
        'floral,green,fresh,fruity,citrus',
        'Fleuriste A ParisbyZarais a Citrus Aromatic fragrance for women.Fleuriste A Pariswas launched in 2017. Top notes are Green Notes, Bergamot and Citruses; middle notes are Amyl Salicylate and Peony; base notes are Musk and Chocolate.',
        4.15,
        89,
        NULL
      ),
(
        'Laboratori-Di-Saponi-In-Roma-44746',
        'Laboratori Di Saponi In Roma Zara',
        'Laboratori',
        'for women',
        NULL,
        NULL,
        'Bergamot, Lemon, Mandarin Orange and Orange',
        'Rose, Freesia, Wild Berries and Reseda',
        'Cedar, Patchouli and Amber',
        'citrus,floral,woody,rose,fresh spicy',
        'Laboratori Di Saponi In RomabyZarais a Chypre Floral fragrance for women.Laboratori Di Saponi In Romawas launched in 2017. Top notes are Bergamot, Lemon, Mandarin Orange and Orange; middle notes are Rose, Freesia, Wild Berries and Reseda; base notes are Cedar, Patchouli and Amber.',
        4.09,
        66,
        NULL
      ),
(
        'Wood-Boards-Studio-In-Melbourne-44745',
        'Wood Boards Studio In Melbourne Zara',
        'Wood',
        'for women',
        NULL,
        NULL,
        'Bergamot, Peach and Apple',
        'Tiare Flower and Ginger',
        'Cedar, Musk and Amber',
        'citrus,fruity,white floral,woody,fresh spicy',
        'Wood Boards Studio In MelbournebyZarais a Woody Floral Musk fragrance for women.Wood Boards Studio In Melbournewas launched in 2017. Top notes are Bergamot, Peach and Apple; middle notes are Tiare Flower and Ginger; base notes are Cedar, Musk and Amber.',
        3.9,
        58,
        NULL
      ),
(
        '590-Collins-Avenue-Miami-25576',
        '590 Collins Avenue Miami Zara',
        '590',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,tropical',
        '590 Collins Avenue MiamibyZarais a Aromatic Fruity fragrance for women.590 Collins Avenue Miamiwas launched in 2014.',
        3.44,
        25,
        NULL
      ),
(
        '6902-Hollywood-Boulevard-Los-Angeles-25577',
        '6902 Hollywood Boulevard Los Angeles Zara',
        '6902',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,fruity',
        '6902 Hollywood Boulevard Los AngelesbyZarais a Floral Fruity fragrance for women.6902 Hollywood Boulevard Los Angeleswas launched in 2014.',
        4.18,
        84,
        NULL
      ),
(
        'Zara-Av-Bartomeu-Vicent-Ramon-12-16-Ibiza-31152',
        'Zara Av. Bartomeu Vicent Ramon 12-16 Ibiza Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        'Pomelo and Orange',
        'Violet',
        'Sandalwood and Cedar',
        'woody,powdery,violet,citrus,warm spicy',
        'Zara Av. Bartomeu Vicent Ramon 12-16 IbizabyZarais a Floral Fruity fragrance for women.Zara Av. Bartomeu Vicent Ramon 12-16 Ibizawas launched in 2015. Top notes are Pomelo and Orange; middle note is Violet; base notes are Sandalwood and Cedar.',
        3.38,
        13,
        NULL
      ),
(
        'Zara-Av-Das-Americas-4666-Rio-De-Janeiro-31151',
        'Zara Av. Das Americas 4666 Rio De Janeiro Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        'Red Berries',
        'Watermelon',
        'Sugar and Woody Notes',
        'sweet,ozonic,fruity,aquatic,vanilla',
        'Zara Av. Das Americas 4666 Rio De JaneirobyZarais a Aromatic Fruity fragrance for women.Zara Av. Das Americas 4666 Rio De Janeirowas launched in 2015. Top note is Red Berries; middle note is Watermelon; base notes are Sugar and Woody Notes.',
        3.58,
        33,
        NULL
      ),
(
        'Zara-Miami-21468',
        'Zara Miami Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Zara MiamibyZarais a fragrance for women.',
        3.63,
        19,
        NULL
      ),
(
        'Gardenia-Eau-de-Parfum-93281',
        'Gardenia Eau de Parfum Zara',
        'Gardenia',
        'for women',
        NULL,
        NULL,
        'Peach, Raspberry and Bergamot',
        'Orange Blossom, Gardenia and Coffee',
        'Patchouli, Vanilla and Musk',
        'white floral,fruity,sweet,citrus,warm spicy',
        'Gardenia Eau de ParfumbyZarais a Amber Floral fragrance for women.Gardenia Eau de Parfumwas launched in 2022. Top notes are Peach, Raspberry and Bergamot; middle notes are Orange Blossom, Gardenia and Coffee; base notes are Patchouli, Vanilla and Musk.',
        4.33,
        9,
        NULL
      ),
(
        'N001-White-Flower-Posy-67760',
        'N°01 White Flower Posy Zara',
        'N°01',
        'for women',
        NULL,
        'Jo Malone',
        'Green Mandarin and Mandarin Orange',
        'Jasmine and Neroli',
        'Amber and Musk',
        'white floral,citrus,amber,musky,powdery',
        'N°01 White Flower PosybyZarais a Floral fragrance for women.N°01 White Flower Posywas launched in 2021. The nose behind this fragrance is Jo Malone. Top notes are Green Mandarin and Mandarin Orange; middle notes are Jasmine and Neroli; base notes are Amber and Musk.',
        4.12,
        66,
        NULL
      ),
(
        'N002-Cerise-Peonies-67761',
        'N°02 Cerise Peonies Zara',
        'N°02',
        'for women',
        NULL,
        NULL,
        'Bergamot and Pink Pepper',
        'Peony',
        'Musk and White Woods',
        'floral,fresh,citrus,rose,musky',
        'N°02 Cerise PeoniesbyZarais a Floral fragrance for women.N°02 Cerise Peonieswas launched in 2021. Top notes are Bergamot and Pink Pepper; middle note is Peony; base notes are Musk and White Woods.',
        3.73,
        55,
        NULL
      ),
(
        'N003-Waterfall-Brume-67762',
        'N°03 Waterfall Brume Zara',
        'N°03',
        'for women',
        NULL,
        'Jo Malone',
        'Grapefruit and Mandarin Orange',
        'Magnolia and Jasmine',
        'Musk',
        'citrus,floral,musky,white floral,powdery',
        'N°03 Waterfall BrumebyZarais a Floral Aquatic fragrance for women.N°03 Waterfall Brumewas launched in 2021. The nose behind this fragrance is Jo Malone. Top notes are Grapefruit and Mandarin Orange; middle notes are Magnolia and Jasmine; base note is Musk.',
        3.82,
        61,
        NULL
      ),
(
        'N004-Spring-Blossom-Cascade-67763',
        'N°04 Spring Blossom Cascade Zara',
        'N°04',
        'for women',
        NULL,
        'Jo Malone',
        'Bergamot and Peony',
        'Honeysuckle and Ylang-Ylang',
        'Sandalwood',
        'white floral,floral,citrus,yellow floral,fresh',
        'N°04 Spring Blossom CascadebyZarais a Floral fragrance for women.N°04 Spring Blossom Cascadewas launched in 2021. The nose behind this fragrance is Jo Malone. Top notes are Bergamot and Peony; middle notes are Honeysuckle and Ylang-Ylang; base note is Sandalwood.',
        3.84,
        44,
        NULL
      ),
(
        'Zara-LXXXV-Woman-Intense-45770',
        'Zara LXXXV Woman Intense Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        'Bamboo and Bergamot',
        'Rose and Tea',
        'Musk and Sandalwood',
        'rose,woody,musky,powdery,floral',
        'Zara LXXXV Woman IntensebyZarais a Floral Woody Musk fragrance for women.Zara LXXXV Woman Intensewas launched in 2017. Top notes are Bamboo and Bergamot; middle notes are Rose and Tea; base notes are Musk and Sandalwood.',
        4.5,
        14,
        NULL
      ),
(
        'Zara-Woman-L-Eau-23427',
        'Zara Woman L''Eau Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fruity,sweet,rose,yellow floral',
        'Zara Woman L''EaubyZarais a Floral Fruity fragrance for women.Zara Woman L''Eauwas launched in 2013.',
        4.05,
        88,
        NULL
      ),
(
        'Zara-Women-Eau-de-Parfum-23428',
        'Zara Women Eau de Parfum Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange',
        'Rose and Peony',
        'Vanilla',
        'rose,floral,citrus,vanilla,fresh',
        'Zara Women Eau de ParfumbyZarais a Floral fragrance for women.Zara Women Eau de Parfumwas launched in 2014. Top note is Mandarin Orange; middle notes are Rose and Peony; base note is Vanilla.',
        3.76,
        49,
        NULL
      ),
(
        'Wonder-Rose-Obsession-72828',
        'Wonder Rose Obsession Zara',
        'Wonder',
        'for women',
        NULL,
        NULL,
        'Litchi, Blackberry and Cassis',
        'Rose and Tuberose',
        'Vanilla, Vetiver and Amber',
        'fruity,rose,vanilla,aromatic,tuberose',
        'Wonder Rose ObsessionbyZarais a Floral Fruity fragrance for women. This is a new fragrance.Wonder Rose Obsessionwas launched in 2022. Top notes are Litchi, Blackberry and Cassis; middle notes are Rose and Tuberose; base notes are Vanilla, Vetiver and Amber.',
        4.22,
        80,
        NULL
      ),
(
        'Wonder-Rose-So-Intense-72829',
        'Wonder Rose So Intense Zara',
        'Wonder',
        'for women',
        NULL,
        NULL,
        'Granny Smith apple',
        'Daisy',
        'Vanilla',
        'fruity,green,floral,fresh,sweet',
        'Wonder Rose So IntensebyZarais a Floral Fruity fragrance for women. This is a new fragrance.Wonder Rose So Intensewas launched in 2022. Top note is Granny Smith apple; middle note is Daisy; base note is Vanilla.',
        3.88,
        42,
        NULL
      ),
(
        'Wonder-Rose-Sublime-72830',
        'Wonder Rose Sublime Zara',
        'Wonder',
        'for women',
        NULL,
        NULL,
        'Grapefruit blossom, Green Tea and Pink Pepper',
        'Peony, Rose and Lily-of-the-Valley',
        'Vanilla, Cedar and Musk',
        'fresh,floral,rose,white floral,green',
        'Wonder Rose SublimebyZarais a Floral Green fragrance for women. This is a new fragrance.Wonder Rose Sublimewas launched in 2022. Top notes are Grapefruit blossom, Green Tea and Pink Pepper; middle notes are Peony, Rose and Lily-of-the-Valley; base notes are Vanilla, Cedar and Musk.',
        4.02,
        50,
        NULL
      ),
(
        'L-Lily-Pad-63247',
        'L Lily Pad Zara',
        'L',
        'for women',
        NULL,
        NULL,
        'Red Fruits',
        'Lily',
        'Praline',
        'sweet,white floral,fruity,lactonic,soft spicy',
        'L Lily PadbyZarais a Floral Fruity Gourmand fragrance for women.L Lily Padwas launched in 2020. Top note is Red Fruits; middle note is Lily; base note is Praline.',
        3.89,
        37,
        NULL
      ),
(
        'R-Rose-63248',
        'R Rose Zara',
        'R',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral,fresh,fruity',
        'R RosebyZarais a Floral fragrance for women.R Rosewas launched in 2020.',
        4,
        7,
        NULL
      ),
(
        'W-White-63250',
        'W White Zara',
        'W',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,tropical,fresh,aquatic',
        'W WhitebyZarais a Floral Fruity fragrance for women.W Whitewas launched in 2020.',
        4,
        5,
        NULL
      ),
(
        'Y-Yellow-Sun-63249',
        'Y Yellow Sun Zara',
        'Y',
        'for women',
        NULL,
        NULL,
        'Apple',
        'Apricot',
        'Coconut',
        'fruity,fresh,green',
        'Y Yellow SunbyZarais a Aromatic Fruity fragrance for women.Y Yellow Sunwas launched in 2020. Top note is Apple; middle note is Apricot; base note is Coconut.',
        3.65,
        23,
        NULL
      ),
(
        'Zara-Rose-Eau-de-Toilette-16589',
        'Zara Rose Eau de Toilette Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fresh,fruity,rose',
        'Zara Rose Eau de ToilettebyZarais a Floral fragrance for women.',
        3.98,
        158,
        NULL
      ),
(
        'Zara-White-Eau-de-Toilette-16588',
        'Zara White Eau de Toilette Zara',
        'Zara',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,white floral,amber',
        'Zara White Eau de ToilettebyZarais a Floral fragrance for women.',
        3.94,
        203,
        NULL
      );
