
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Regularly-Irregular-69361',
        'Regularly Irregular Regalien',
        'Regularly',
        'for women and men',
        NULL,
        'Firmenich',
        'Pineapple, Apple, Raspberry, Lemon and Bergamot',
        'Lily-of-the-Valley, Rose, Birch and Sichuan Pepper',
        'Oakmoss, White Musk, Ambroxan, Amber and Patchouli',
        'fruity,sweet,fresh,mossy,musky',
        'Regularly IrregularbyRegalienis a Amber fragrance for women and men.Regularly Irregularwas launched in 2019. Regularly Irregular was created by MG Gulcicek and Firmenich. Top notes are Pineapple, Apple, Raspberry, Lemon and Bergamot; middle notes are Lily-of-the-Valley, Rose, Birch and Sichuan Pepper; base notes are Oakmoss, White Musk, Ambroxan, Amber and Patchouli.',
        3.35,
        23,
        NULL
      ),
(
        'Ala-69368',
        'Ala Regalien',
        'Ala',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Cinnamon, Cognac, Apricot, Whiskey and Coriander',
        'Honey, Turkish Rose, Geranium and Rosemary',
        'Labdanum, Vanilla, Benzoin, Amber, Tonka Bean and Natural Musk',
        'amber,warm spicy,woody,sweet,vanilla',
        'AlabyRegalienis a Amber Spicy fragrance for women and men.Alawas launched in 2021. The nose behind this fragrance is Koray Sevinç. Top notes are Cinnamon, Cognac, Apricot, Whiskey and Coriander; middle notes are Honey, Turkish Rose, Geranium and Rosemary; base notes are Labdanum, Vanilla, Benzoin, Amber, Tonka Bean and Natural Musk.',
        4.33,
        88,
        NULL
      ),
(
        'Hatir-77386',
        'Hatir Regalien',
        'Hatir',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,sweet,coffee,amber,vanilla',
        'HatirbyRegalienis a Amber Vanilla fragrance for women and men. This is a new fragrance.Hatirwas launched in 2022.',
        3.94,
        54,
        NULL
      ),
(
        'Meftun-69365',
        'Meftun Regalien',
        'Meftun',
        'for women and men',
        NULL,
        'Jorge Lee',
        'Coriander, Cognac, Rum and Cinnamon',
        'Wormwood, Birch Leaf, Cinnamon, Red Berries, Angelica and Ginger',
        'Incense, Ambrette (Musk Mallow), Patchouli and Sandalwood',
        'woody,warm spicy,aromatic,smoky,amber',
        'MeftunbyRegalienis a Amber Woody fragrance for women and men.Meftunwas launched in 2021. The nose behind this fragrance is Jorge Lee. Top notes are Coriander, Cognac, Rum and Cinnamon; middle notes are Wormwood, Birch Leaf, Cinnamon, Red Berries, Angelica and Ginger; base notes are Incense, Ambrette (Musk Mallow), Patchouli and Sandalwood.',
        4.3,
        46,
        NULL
      ),
(
        'Nazen-69367',
        'Nazen Regalien',
        'Nazen',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Peach, Green Notes and Bergamot',
        'Tuberose, Gardenia, Jasmine, Lily and Ylang-Ylang',
        'Coconut, Vanilla, Butter and White Musk',
        'white floral,tuberose,coconut,lactonic,sweet',
        'NazenbyRegalienis a Floral fragrance for women and men.Nazenwas launched in 2021. The nose behind this fragrance is Koray Sevinç. Top notes are Peach, Green Notes and Bergamot; middle notes are Tuberose, Gardenia, Jasmine, Lily and Ylang-Ylang; base notes are Coconut, Vanilla, Butter and White Musk.',
        4.12,
        49,
        NULL
      ),
(
        'Sah-69366',
        'Sah Regalien',
        'Sah',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Mineral notes and Ozonic notes',
        'Saffron, Turkish Rose, Nutmeg, Cloves and Geranium',
        'Cambodian Oud, Patchouli and Cedar',
        'warm spicy,woody,fresh spicy,animalic,rose',
        'SahbyRegalienis a Woody Spicy fragrance for women and men.Sahwas launched in 2021. The nose behind this fragrance is Koray Sevinç. Top notes are Mineral notes and Ozonic notes; middle notes are Saffron, Turkish Rose, Nutmeg, Cloves and Geranium; base notes are Cambodian Oud, Patchouli and Cedar.',
        4.18,
        57,
        NULL
      ),
(
        'Turkuaz-69425',
        'Turkuaz Regalien',
        'Turkuaz',
        'for women and men',
        NULL,
        'Firmenich',
        'Sea water, Saffron, Ozonic notes and Artemisia',
        'Seaweed, Cassis and Turkish Rose',
        'Oakmoss, Ambroxan and Amber',
        'marine,aromatic,aquatic,amber,mossy',
        'TurkuazbyRegalienis a Woody Aquatic fragrance for women and men.Turkuazwas launched in 2021. Turkuaz was created by MG Gulcicek and Firmenich. Top notes are Sea water, Saffron, Ozonic notes and Artemisia; middle notes are Seaweed, Cassis and Turkish Rose; base notes are Oakmoss, Ambroxan and Amber.',
        4.28,
        120,
        NULL
      ),
(
        'Clubs-Of-Iris-55013',
        'Clubs Of Iris Regalien',
        'Clubs',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Violet Leaf, Raspberry, Grapefruit and Bergamot',
        'Orris Root, Anise, Carnation and Rose',
        'Java vetiver oil, Cedar, Patchouli, Amber and Musk',
        'woody,iris,earthy,powdery,aromatic',
        'Clubs Of IrisbyRegalienis a fragrance for women and men.Clubs Of Iriswas launched in 2019. The nose behind this fragrance is Koray Sevinç. Top notes are Violet Leaf, Raspberry, Grapefruit and Bergamot; middle notes are Orris Root, Anise, Carnation and Rose; base notes are Java vetiver oil, Cedar, Patchouli, Amber and Musk.',
        3.95,
        42,
        NULL
      ),
(
        'Diamond-Of-Velvet-55015',
        'Diamond Of Velvet Regalien',
        'Diamond',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Saffron, Peach, Violet Leaf and Orange',
        'Heliotrope, Osmanthus, Iris, Ginger and Nard Himalayan (Jatamansi)',
        'Leather, Tonka Bean, Styrax, Birch Tar, Ambrette (Musk Mallow) and Patchouli',
        'leather,warm spicy,powdery,floral,fruity',
        'Diamond Of VelvetbyRegalienis a fragrance for women and men.Diamond Of Velvetwas launched in 2019. The nose behind this fragrance is Koray Sevinç. Top notes are Saffron, Peach, Violet Leaf and Orange; middle notes are Heliotrope, Osmanthus, Iris, Ginger and Nard Himalayan (Jatamansi); base notes are Leather, Tonka Bean, Styrax, Birch Tar, Ambrette (Musk Mallow) and Patchouli.',
        4.16,
        55,
        NULL
      ),
(
        'Heart-Of-Rose-55016',
        'Heart Of Rose Regalien',
        'Heart',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Pineapple, Watermelon and Orange',
        'Turkish Rose, Neroli, Violet, Lily, Coriander, Nutmeg and Cinnamon',
        'White Chocolate, Musk, Vetiver, Patchouli and Amber',
        'sweet,rose,fruity,musky,powdery',
        'Heart Of RosebyRegalienis a fragrance for women and men.Heart Of Rosewas launched in 2019. The nose behind this fragrance is Koray Sevinç. Top notes are Pineapple, Watermelon and Orange; middle notes are Turkish Rose, Neroli, Violet, Lily, Coriander, Nutmeg and Cinnamon; base notes are White Chocolate, Musk, Vetiver, Patchouli and Amber.',
        3.94,
        52,
        NULL
      ),
(
        'Spade-Of-Vetiver-55014',
        'Spade Of Vetiver Regalien',
        'Spade',
        'for women and men',
        NULL,
        'Koray Sevinç',
        'Sea Notes, Ozonic notes, Earthy Notes, Grapefruit and Cardamom',
        'Salt, Cypress, Clary Sage and Geranium',
        'Haitian Vetiver, Java vetiver oil, Incense, Patchouli and Opoponax',
        'aromatic,woody,earthy,marine,salty',
        'Spade Of VetiverbyRegalienis a fragrance for women and men.Spade Of Vetiverwas launched in 2019. The nose behind this fragrance is Koray Sevinç. Top notes are Sea Notes, Ozonic notes, Earthy Notes, Grapefruit and Cardamom; middle notes are Salt, Cypress, Clary Sage and Geranium; base notes are Haitian Vetiver, Java vetiver oil, Incense, Patchouli and Opoponax.',
        3.89,
        44,
        NULL
      ),
(
        'Antidote-69426',
        'Antidote Regalien',
        'Antidote',
        'for women and men',
        NULL,
        'Firmenich',
        'Nutmeg, Geranium and Rose Leaf',
        'Honey, Mimosa, Jasmine and Sage',
        'Tobacco, Vanilla, Patchouli, Amber and Musk',
        'sweet,tobacco,honey,vanilla,powdery',
        'AntidotebyRegalienis a Amber Floral fragrance for women and men.Antidotewas launched in 2018. Antidote was created by MG Gulcicek and Firmenich. Top notes are Nutmeg, Geranium and Rose Leaf; middle notes are Honey, Mimosa, Jasmine and Sage; base notes are Tobacco, Vanilla, Patchouli, Amber and Musk.',
        4.37,
        46,
        NULL
      ),
(
        'Musk-Barrel-43840',
        'Musk Barrel Regalien',
        'Musk',
        'for men',
        NULL,
        'Cara Sylvain',
        'Black Pepper, Cumin and Saffron',
        'Honeysuckle and Jasmine',
        'Musk, Sandalwood, Amber, Atlas Cedar and Patchouli',
        'woody,warm spicy,fresh spicy,powdery,musky',
        'Musk BarrelbyRegalienis a Amber Woody fragrance for men.Musk Barrelwas launched in 2018. The nose behind this fragrance is Cara Sylvain. Top notes are Black Pepper, Cumin and Saffron; middle notes are Honeysuckle and Jasmine; base notes are Musk, Sandalwood, Amber, Atlas Cedar and Patchouli.',
        3.81,
        26,
        NULL
      ),
(
        'Mystic-69427',
        'Mystic Regalien',
        'Mystic',
        'for women and men',
        NULL,
        'Firmenich',
        'Cedar Needles, Sage, Palisander Rosewood and Bergamot',
        'Lavender and Pepper',
        'Sandalwood, White Musk, Vanilla, Agarwood (Oud), Gurjan balsam, Tonka Bean and Amber',
        'woody,aromatic,lavender,powdery,fresh spicy',
        'MysticbyRegalienis a Amber Woody fragrance for women and men.Mysticwas launched in 2018. Mystic was created by MG Gulcicek and Firmenich. Top notes are Cedar Needles, Sage, Palisander Rosewood and Bergamot; middle notes are Lavender and Pepper; base notes are Sandalwood, White Musk, Vanilla, Agarwood (Oud), Gurjan balsam, Tonka Bean and Amber.',
        4.02,
        46,
        NULL
      ),
(
        'Vanity-Oud-43842',
        'Vanity Oud Regalien',
        'Vanity',
        'for women',
        NULL,
        'Cara Sylvain',
        'Plum, Litchi and Raspberry',
        'Orchid, Frangipani, Lotus and Jasmine',
        'Ambergris, Agarwood (Oud), Vanilla and Cedar',
        'floral,fruity,sweet,tropical,amber',
        'Vanity OudbyRegalienis a Floral Fruity fragrance for women.Vanity Oudwas launched in 2018. The nose behind this fragrance is Cara Sylvain. Top notes are Plum, Litchi and Raspberry; middle notes are Orchid, Frangipani, Lotus and Jasmine; base notes are Ambergris, Agarwood (Oud), Vanilla and Cedar.',
        4.03,
        37,
        NULL
      ),
(
        'White-Gold-43838',
        'White Gold Regalien',
        'White',
        'for women',
        NULL,
        'Cara Sylvain',
        'Pear, Plum, Ozonic notes and Bergamot',
        'Rose, Orris Root and Jasmine',
        'Caramel, Tonka Bean, Dark Chocolate, Labdanum and Patchouli',
        'sweet,fruity,caramel,rose,amber',
        'White GoldbyRegalienis a Amber Woody fragrance for women.White Goldwas launched in 2018. The nose behind this fragrance is Cara Sylvain. Top notes are Pear, Plum, Ozonic notes and Bergamot; middle notes are Rose, Orris Root and Jasmine; base notes are Caramel, Tonka Bean, Dark Chocolate, Labdanum and Patchouli.',
        3.88,
        32,
        NULL
      ),
(
        'Amber-Salude-43843',
        'Amber Salude Regalien',
        'Amber',
        'for women and men',
        NULL,
        'Cara Sylvain',
        'Mandarin Orange, Bergamot, Cloves and Grapefruit',
        'Heliotrope, Orange Blossom and Honeysuckle',
        'Amber, Tonka Bean, Cotton Candy, Cashmere Wood and Siberian Pine',
        'amber,citrus,sweet,woody,white floral',
        'Amber SaludebyRegalienis a Woody Chypre fragrance for women and men.Amber Saludewas launched in 2016. The nose behind this fragrance is Cara Sylvain. Top notes are Mandarin Orange, Bergamot, Cloves and Grapefruit; middle notes are Heliotrope, Orange Blossom and Honeysuckle; base notes are Amber, Tonka Bean, Cotton Candy, Cashmere Wood and Siberian Pine.',
        4.08,
        24,
        NULL
      ),
(
        'Aqua-Notte-43837',
        'Aqua Notte Regalien',
        'Aqua',
        'for men',
        NULL,
        'Cara Sylvain',
        'Bergamot, Sea Notes and Neroli',
        'Orange Blossom, Ylang-Ylang and Orris Root',
        'Vetiver, Oakmoss, Cedar and Patchouli',
        'woody,citrus,aromatic,earthy,white floral',
        'Aqua NottebyRegalienis a Amber Spicy fragrance for men.Aqua Nottewas launched in 2016. The nose behind this fragrance is Cara Sylvain. Top notes are Bergamot, Sea Notes and Neroli; middle notes are Orange Blossom, Ylang-Ylang and Orris Root; base notes are Vetiver, Oakmoss, Cedar and Patchouli.',
        4.26,
        19,
        NULL
      ),
(
        'Babel-s-Heaven-43839',
        'Babel''s Heaven Regalien',
        'Babel''s',
        'for women and men',
        NULL,
        'Cara Sylvain',
        'Pear, Peach, Mandarin Orange and Bergamot',
        'Rose, Magnolia, Freesia and Cloves',
        'Amber, Musk and Patchouli',
        'fruity,floral,sweet,rose,aquatic',
        'Babel''s HeavenbyRegalienis a Floral Fruity fragrance for women and men.Babel''s Heavenwas launched in 2016. The nose behind this fragrance is Cara Sylvain. Top notes are Pear, Peach, Mandarin Orange and Bergamot; middle notes are Rose, Magnolia, Freesia and Cloves; base notes are Amber, Musk and Patchouli.',
        4.03,
        29,
        NULL
      ),
(
        'Be-Bold-69326',
        'Be Bold Regalien',
        'Be',
        'for women and men',
        NULL,
        'Firmenich',
        'Raspberry, Cumin, Black Currant and Grapes',
        'Rose, Iris and Incense',
        'Ambroxan, Patchouli, White Musk and Earthy Notes',
        'amber,musky,fruity,earthy,woody',
        'Be BoldbyRegalienis a fragrance for women and men.Be Boldwas launched in 2018. Be Bold was created by MG Gulcicek and Firmenich. Top notes are Raspberry, Cumin, Black Currant and Grapes; middle notes are Rose, Iris and Incense; base notes are Ambroxan, Patchouli, White Musk and Earthy Notes.',
        4.5,
        2,
        NULL
      ),
(
        'Overdose-69330',
        'Overdose Regalien',
        'Overdose',
        'for women and men',
        NULL,
        'Firmenich',
        'Coriander, Pink Pepper, Bergamot and Neroli',
        'Orange Blossom, Honeysuckle, Rose, Jasmine and Iris',
        'Labdanum, Musk, Vanilla, Sugar, Caramel and Civet',
        'white floral,musky,sweet,citrus,powdery',
        'OverdosebyRegalienis a fragrance for women and men.Overdosewas launched in 2018. Overdose was created by MG Gulcicek and Firmenich. Top notes are Coriander, Pink Pepper, Bergamot and Neroli; middle notes are Orange Blossom, Honeysuckle, Rose, Jasmine and Iris; base notes are Labdanum, Musk, Vanilla, Sugar, Caramel and Civet.',
        3.71,
        7,
        NULL
      ),
(
        'Prestige-69357',
        'Prestige Regalien',
        'Prestige',
        'for women and men',
        NULL,
        'Firmenich',
        'Lemon, Bergamot, Orange, Cloves and Galbanum',
        'Rose, Jasmine, Ylang-Ylang and Gardenia',
        'Oakmoss, Vanilla, Labdanum, Patchouli, Amber and Tolu Balsam',
        'citrus,amber,white floral,warm spicy,woody',
        'PrestigebyRegalienis a fragrance for women and men.Prestigewas launched in 2018. Prestige was created by MG Gulcicek and Firmenich. Top notes are Lemon, Bergamot, Orange, Cloves and Galbanum; middle notes are Rose, Jasmine, Ylang-Ylang and Gardenia; base notes are Oakmoss, Vanilla, Labdanum, Patchouli, Amber and Tolu Balsam.',
        4,
        2,
        NULL
      ),
(
        'Sandal-Harmony-7-43841',
        'Sandal Harmony 7 Regalien',
        'Sandal',
        'for men',
        NULL,
        'Cara Sylvain',
        'Nutmeg, Cardamom, Ginger and Bergamot',
        'Violet, Orris Root and Lily-of-the-Valley',
        'Natural Musk, Benzoin, Virginia Cedar and Amber',
        'warm spicy,fresh spicy,powdery,musky,aromatic',
        'Sandal Harmony 7byRegalienis a Woody Spicy fragrance for men.Sandal Harmony 7was launched in 2016. The nose behind this fragrance is Cara Sylvain. Top notes are Nutmeg, Cardamom, Ginger and Bergamot; middle notes are Violet, Orris Root and Lily-of-the-Valley; base notes are Natural Musk, Benzoin, Virginia Cedar and Amber.',
        4.07,
        14,
        NULL
      ),
(
        '80-48005',
        '80 Reflexion',
        '80',
        'for women',
        NULL,
        'Eugene Firsanov',
        'Turkish Rose and Lemon',
        'Magnolia, Jasmine and White Rose',
        'Honey, Champaca and Musk',
        'floral,citrus,honey,rose,white floral',
        '80byReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov. Top notes are Turkish Rose and Lemon; middle notes are Magnolia, Jasmine and White Rose; base notes are Honey, Champaca and Musk.',
        4,
        2,
        NULL
      ),
(
        'Cafe-48033',
        'Café Reflexion',
        'Café',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'sweet,coffee,warm spicy,nutty,woody',
        'CafébyReflexionis a fragrance for women and men. The nose behind this fragrance is Eugene Firsanov.',
        3.73,
        11,
        NULL
      ),
(
        'Chagrin-48027',
        'Chagrin Reflexion',
        'Chagrin',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Leather and Tonka Bean',
        'Leather, Almond and White Tobacco',
        'Leather and Musk',
        'leather,almond,animalic,sweet,vanilla',
        'ChagrinbyReflexionis a Leather fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Leather and Tonka Bean; middle notes are Leather, Almond and White Tobacco; base notes are Leather and Musk.',
        3.33,
        3,
        NULL
      ),
(
        'Chypre-Lumiere-48026',
        'Chypre Lumière Reflexion',
        'Chypre',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Lemon, Bergamot and Citron',
        'Green Notes, Tulip and Jasmine',
        'Oakmoss, Musk and Patchouli',
        'citrus,green,mossy,earthy,floral',
        'Chypre LumièrebyReflexionis a Chypre fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Lemon, Bergamot and Citron; middle notes are Green Notes, Tulip and Jasmine; base notes are Oakmoss, Musk and Patchouli.',
        3.71,
        7,
        NULL
      ),
(
        'Degel-66416',
        'Dégel Reflexion',
        'Dégel',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'fresh,aquatic,citrus,green,ozonic',
        'DégelbyReflexionis a Aromatic Aquatic fragrance for women and men.Dégelwas launched in 2020. The nose behind this fragrance is Eugene Firsanov.',
        4,
        6,
        NULL
      ),
(
        'Dore-66413',
        'Doré Reflexion',
        'Doré',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'white floral,animalic,sweet,honey,powdery',
        'DorébyReflexionis a Floral fragrance for women.Doréwas launched in 2021. The nose behind this fragrance is Eugene Firsanov.',
        4,
        3,
        NULL
      ),
(
        'Equilibre-48028',
        'Équilibre Reflexion',
        'Équilibre',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Tea Rose and Palisander Rosewood',
        'Guaiac Wood and Cedar',
        'Woody Notes and Vanilla',
        'woody,rose',
        'ÉquilibrebyReflexionis a Woody Floral Musk fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Tea Rose and Palisander Rosewood; middle notes are Guaiac Wood and Cedar; base notes are Woody Notes and Vanilla.',
        4.4,
        5,
        NULL
      ),
(
        'Fatalys-66414',
        'Fatalys Reflexion',
        'Fatalys',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'amber,powdery,warm spicy,musky,white floral',
        'FatalysbyReflexionis a Floral fragrance for women.Fatalyswas launched in 2021. The nose behind this fragrance is Eugene Firsanov.',
        5,
        1,
        NULL
      ),
(
        'Foret-Absolue-48035',
        'Forêt Absolue Reflexion',
        'Forêt',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,earthy,green,mossy',
        'Forêt AbsoluebyReflexionis a Woody Chypre fragrance for women and men. The nose behind this fragrance is Eugene Firsanov.',
        4.3,
        10,
        NULL
      ),
(
        'Foret-Du-Nord-48039',
        'Forêt Du Nord Reflexion',
        'Forêt',
        'for men',
        NULL,
        'Eugene Firsanov',
        'Fir and Woody Notes',
        'Woody Notes, Leather and Ozonic notes',
        'Oakmoss and Amber',
        'woody,fresh spicy,ozonic,leather,aromatic',
        'Forêt Du NordbyReflexionis a Woody fragrance for men. The nose behind this fragrance is Eugene Firsanov. Top notes are Fir and Woody Notes; middle notes are Woody Notes, Leather and Ozonic notes; base notes are Oakmoss and Amber.',
        4.75,
        4,
        NULL
      ),
(
        'Freesia-48051',
        'Freesia Reflexion',
        'Freesia',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'floral',
        'FreesiabyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4,
        6,
        NULL
      ),
(
        'Heliotrope-48006',
        'Héliotrope Reflexion',
        'Héliotrope',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Heliotrope, Palisander Rosewood and Rose',
        'Heliotrope, Vanilla and Almond',
        'Heliotrope and Raspberry',
        'vanilla,powdery,almond,fruity,sweet',
        'HéliotropebyReflexionis a fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Heliotrope, Palisander Rosewood and Rose; middle notes are Heliotrope, Vanilla and Almond; base notes are Heliotrope and Raspberry.',
        4,
        3,
        NULL
      ),
(
        'ICS-75707',
        'ICS Reflexion',
        'ICS',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Cherry and Liquor',
        'Spices',
        'Balsamic Notes, Tobacco and Labdanum',
        'cherry,sweet,alcohol,amber,tobacco',
        'ICSbyReflexionis a Amber Vanilla fragrance for women and men. This is a new fragrance.ICSwas launched in 2022. The nose behind this fragrance is Eugene Firsanov. Top notes are Cherry and Liquor; middle note is Spices; base notes are Balsamic Notes, Tobacco and Labdanum.',
        4,
        2,
        NULL
      ),
(
        'Idylle-48025',
        'Idylle Reflexion',
        'Idylle',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Jasmine, Cassis and Bergamot',
        'Black Tea, Green Tea, Black Currant and Rose',
        'Tea, Ozonic notes and Woody Notes',
        'white floral,green,fruity,aromatic,fresh',
        'IdyllebyReflexionis a Floral Woody Musk fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Jasmine, Cassis and Bergamot; middle notes are Black Tea, Green Tea, Black Currant and Rose; base notes are Tea, Ozonic notes and Woody Notes.',
        4.23,
        13,
        NULL
      ),
(
        'Immortelle-66415',
        'Immortelle Reflexion',
        'Immortelle',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'sweet,green,honey,herbal,warm spicy',
        'ImmortellebyReflexionis a Floral fragrance for women.Immortellewas launched in 2021. The nose behind this fragrance is Eugene Firsanov.',
        5,
        2,
        NULL
      ),
(
        'Iris-48052',
        'Iris Reflexion',
        'Iris',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'powdery,iris,violet,earthy,musky',
        'IrisbyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4.25,
        4,
        NULL
      ),
(
        'Jacinthe-66417',
        'Jacinthe Reflexion',
        'Jacinthe',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'green,floral,fruity,fresh spicy',
        'JacinthebyReflexionis a Floral fragrance for women.Jacinthewas launched in 2019. The nose behind this fragrance is Eugene Firsanov.',
        4.5,
        2,
        NULL
      ),
(
        'La-Cerisaie-57308',
        'La Cerisaie Reflexion',
        'La',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'powdery,musky,ozonic,floral,fresh',
        'La CerisaiebyReflexionis a fragrance for women.La Cerisaiewas launched in 2019. The nose behind this fragrance is Eugene Firsanov.',
        4.67,
        6,
        NULL
      ),
(
        'La-Fete-48024',
        'La Fête Reflexion',
        'La',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Dark Chocolate and Praline',
        'Chocolate, Tobacco, Rum and Caramel',
        'Tobacco, Labdanum and Amber',
        'sweet,amber,tobacco,chocolate,warm spicy',
        'La FêtebyReflexionis a fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Dark Chocolate and Praline; middle notes are Chocolate, Tobacco, Rum and Caramel; base notes are Tobacco, Labdanum and Amber.',
        4.33,
        9,
        NULL
      ),
(
        'Lavande-Sauvage-48053',
        'Lavande Sauvage Reflexion',
        'Lavande',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'powdery,woody,violet,amber,iris',
        'Lavande SauvagebyReflexionis a Floral Woody Musk fragrance for women and men. The nose behind this fragrance is Eugene Firsanov.',
        4.33,
        3,
        NULL
      ),
(
        'Mimosa-48044',
        'Mimosa Reflexion',
        'Mimosa',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'powdery,yellow floral,green,floral,sweet',
        'MimosabyReflexionis a Floral Green fragrance for women and men. The nose behind this fragrance is Eugene Firsanov.',
        3.73,
        11,
        NULL
      ),
(
        'Muguet-48050',
        'Muguet Reflexion',
        'Muguet',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        NULL,
        'MuguetbyReflexionis a Floral Green fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4,
        10,
        NULL
      ),
(
        'Neige-Encens-48038',
        'Neige Encens Reflexion',
        'Neige',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Olibanum and Snow',
        'Olibanum and Ozonic notes',
        'Olibanum and Musk',
        'ozonic,amber,musky,fresh,fresh spicy',
        'Neige EncensbyReflexionis a fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Olibanum and Snow; middle notes are Olibanum and Ozonic notes; base notes are Olibanum and Musk.',
        4,
        2,
        NULL
      ),
(
        'Osmanthus-48054',
        'Osmanthus Reflexion',
        'Osmanthus',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'fruity,floral,sweet,green',
        'OsmanthusbyReflexionis a Floral Fruity fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        3.64,
        14,
        NULL
      ),
(
        'Patchouli-48055',
        'Patchouli Reflexion',
        'Patchouli',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'woody,patchouli,sweet,warm spicy,chocolate',
        'PatchoulibyReflexionis a Woody fragrance for women and men. The nose behind this fragrance is Eugene Firsanov.',
        4,
        6,
        NULL
      ),
(
        'Petunia-66412',
        'Pétunia Reflexion',
        'Pétunia',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'musky,floral,powdery,white floral',
        'PétuniabyReflexionis a Floral fragrance for women.Pétuniawas launched in 2021. The nose behind this fragrance is Eugene Firsanov.',
        4.17,
        6,
        NULL
      ),
(
        'Pivoine-48048',
        'Pivoine Reflexion',
        'Pivoine',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'floral,fresh,rose,aquatic',
        'PivoinebyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4.38,
        48,
        NULL
      ),
(
        'Pour-Femme-48040',
        'Pour Femme Reflexion',
        'Pour',
        'for women',
        NULL,
        'Eugene Firsanov',
        'Tuberose, Gardenia and Lilac',
        'Vanilla, Gardenia and Jasmine',
        'Whipped Cream, White Flowers and Musk',
        'white floral,vanilla,tuberose,sweet,animalic',
        'Pour FemmebyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov. Top notes are Tuberose, Gardenia and Lilac; middle notes are Vanilla, Gardenia and Jasmine; base notes are Whipped Cream, White Flowers and Musk.',
        4,
        8,
        NULL
      ),
(
        'Pour-Homme-48037',
        'Pour Homme Reflexion',
        'Pour',
        'for men',
        NULL,
        'Eugene Firsanov',
        'Bergamot and Lime',
        'Juniper, Cedar and Ozonic notes',
        'Ozonic notes and Amber',
        'citrus,fresh spicy,woody,aromatic,ozonic',
        'Pour HommebyReflexionis a fragrance for men. The nose behind this fragrance is Eugene Firsanov. Top notes are Bergamot and Lime; middle notes are Juniper, Cedar and Ozonic notes; base notes are Ozonic notes and Amber.',
        4,
        1,
        NULL
      ),
(
        'Pryanik-48034',
        'Pryanik Reflexion',
        'Pryanik',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Cinnamon, Brown sugar and Agarwood (Oud)',
        'Honey, Maple sap and Tonka Bean',
        'Bourbon Vanilla, Amber and Peru Balsam',
        'sweet,vanilla,honey,cinnamon,warm spicy',
        'PryanikbyReflexionis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Cinnamon, Brown sugar and Agarwood (Oud); middle notes are Honey, Maple sap and Tonka Bean; base notes are Bourbon Vanilla, Amber and Peru Balsam.',
        4.43,
        21,
        NULL
      ),
(
        'Reveurs-57307',
        'Rêveurs Reflexion',
        'Rêveurs',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'white floral,sweet,fruity,green',
        'RêveursbyReflexionis a fragrance for women.Rêveurswas launched in 2019. The nose behind this fragrance is Eugene Firsanov.',
        4.3,
        10,
        NULL
      ),
(
        'Sabotage-48003',
        'Sabotage Reflexion',
        'Sabotage',
        'for women',
        NULL,
        'Eugene Firsanov',
        'Citron, Magnolia and Butter',
        'Champaca, Vanilla and Exotic Fruits',
        'Powdery Notes and Musk',
        'floral,citrus,powdery,sweet,vanilla',
        'SabotagebyReflexionis a Floral Fruity Gourmand fragrance for women. The nose behind this fragrance is Eugene Firsanov. Top notes are Citron, Magnolia and Butter; middle notes are Champaca, Vanilla and Exotic Fruits; base notes are Powdery Notes and Musk.',
        3.7,
        10,
        NULL
      ),
(
        'Santal-48056',
        'Santal Reflexion',
        'Santal',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy,sweet',
        'SantalbyReflexionis a Woody fragrance for women and men. The nose behind this fragrance is Eugene Firsanov.',
        4.5,
        4,
        NULL
      ),
(
        'Soie-47994',
        'Soie Reflexion',
        'Soie',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Aldehydes, Citron, Lemon and Bergamot',
        'Carnation, Tiare Flower, Ylang-Ylang, Iris, Jasmine and Milk',
        'Sandalwood and Musk',
        'powdery,woody,warm spicy,iris,musky',
        'SoiebyReflexionis a fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Aldehydes, Citron, Lemon and Bergamot; middle notes are Carnation, Tiare Flower, Ylang-Ylang, Iris, Jasmine and Milk; base notes are Sandalwood and Musk.',
        3.86,
        7,
        NULL
      ),
(
        'Sous-La-Lune-48004',
        'Sous La Lune Reflexion',
        'Sous',
        'for women',
        NULL,
        'Eugene Firsanov',
        'Jasmine and Palisander Rosewood',
        'Jasmine, Berry Fruits and Orange Blossom',
        'Benzoin and Musk',
        'white floral,fruity,sweet,amber,musky',
        'Sous La LunebyReflexionis a fragrance for women. The nose behind this fragrance is Eugene Firsanov. Top notes are Jasmine and Palisander Rosewood; middle notes are Jasmine, Berry Fruits and Orange Blossom; base notes are Benzoin and Musk.',
        5,
        1,
        NULL
      ),
(
        'Tabac-Ambre-48036',
        'Tabac Ambre Reflexion',
        'Tabac',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        'Tobacco and Dried Fruits',
        'Tobacco, Cherry and Amber',
        'Labdanum and Benzoin',
        'tobacco,sweet,fruity,amber,cherry',
        'Tabac AmbrebyReflexionis a fragrance for women and men. The nose behind this fragrance is Eugene Firsanov. Top notes are Tobacco and Dried Fruits; middle notes are Tobacco, Cherry and Amber; base notes are Labdanum and Benzoin.',
        4.38,
        8,
        NULL
      ),
(
        'Rada-48057',
        'Rada Reflexion',
        'Rada',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'white floral,fruity,sweet,musky,tuberose',
        'RadabyReflexionis a fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        3.5,
        2,
        NULL
      ),
(
        'Cassis-57310',
        'Cassis Reflexion',
        'Cassis',
        'for women and men',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'fruity,soft spicy,woody,floral',
        'CassisbyReflexionis a Aromatic Fruity fragrance for women and men.Cassiswas launched in 2019. The nose behind this fragrance is Eugene Firsanov.',
        3.75,
        8,
        NULL
      ),
(
        'Gardenia-48041',
        'Gardénia Reflexion',
        'Gardénia',
        'for women',
        NULL,
        'Eugene Firsanov',
        'Gardenia and Pear',
        'Tuberose, Gardenia and Jasmine',
        'Gardenia and Musk',
        'white floral,tuberose,animalic',
        'GardéniabyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov. Top notes are Gardenia and Pear; middle notes are Tuberose, Gardenia and Jasmine; base notes are Gardenia and Musk.',
        3.89,
        9,
        NULL
      ),
(
        'Jasmin-48043',
        'Jasmin Reflexion',
        'Jasmin',
        'for women',
        NULL,
        'Eugene Firsanov',
        'Jasmine and Strawberry',
        'Jasmine',
        'Jasmine and Benzoin',
        'white floral,fruity,sweet',
        'JasminbyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov. Top notes are Jasmine and Strawberry; middle note is Jasmine; base notes are Jasmine and Benzoin.',
        4,
        3,
        NULL
      ),
(
        'Jonquille-48045',
        'Jonquille Reflexion',
        'Jonquille',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'yellow floral,green,powdery,white floral,aromatic',
        'JonquillebyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4.09,
        11,
        NULL
      ),
(
        'Lilas-48049',
        'Lilas Reflexion',
        'Lilas',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'floral,green,fresh,powdery,white floral',
        'LilasbyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4,
        14,
        NULL
      ),
(
        'Rose-Blanche-48046',
        'Rose Blanche Reflexion',
        'Rose',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Rose BlanchebyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        4,
        11,
        NULL
      ),
(
        'Tilleul-48047',
        'Tilleul Reflexion',
        'Tilleul',
        'for women',
        NULL,
        'Eugene Firsanov',
        NULL,
        NULL,
        NULL,
        'sweet,honey,yellow floral,floral,herbal',
        'TilleulbyReflexionis a Floral fragrance for women. The nose behind this fragrance is Eugene Firsanov.',
        3.95,
        22,
        NULL
      ),
(
        '1809-21875',
        '1809 Refan',
        '1809',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh,green,fresh spicy',
        '1809byRefanis a Citrus Aromatic fragrance for women and men.',
        4,
        4,
        NULL
      ),
(
        '192-Light-21876',
        '192 Light Refan',
        '192',
        'for women',
        NULL,
        NULL,
        'Citruses',
        'Gardenia, Orange Blossom and Jasmine',
        'Patchouli, Amber and Musk',
        'patchouli,white floral,woody,warm spicy,earthy',
        '192 LightbyRefanis a Floral Woody Musk fragrance for women. Top note is Citruses; middle notes are Gardenia, Orange Blossom and Jasmine; base notes are Patchouli, Amber and Musk.',
        3.42,
        12,
        NULL
      ),
(
        'Black-Patchouli-21877',
        'Black Patchouli Refan',
        'Black',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'patchouli,woody,warm spicy,earthy,balsamic',
        'Black PatchoulibyRefanis a Woody fragrance for women and men.',
        3.57,
        7,
        NULL
      ),
(
        'Black-Rose-For-Men-21878',
        'Black Rose For Men Refan',
        'Black',
        'for men',
        NULL,
        NULL,
        'Mint and Coffee',
        'Rose and Geranium',
        'Agarwood (Oud), Sandalwood and Amber',
        'rose,oud,woody,floral,warm spicy',
        'Black Rose For MenbyRefanis a Amber Floral fragrance for men. Top notes are Mint and Coffee; middle notes are Rose and Geranium; base notes are Agarwood (Oud), Sandalwood and Amber.',
        4.25,
        4,
        NULL
      ),
(
        'Black-Rose-For-Women-21879',
        'Black Rose For Women Refan',
        'Black',
        'for women',
        NULL,
        NULL,
        'Saffron and Pepper',
        'Agarwood (Oud), Rose and Jasmine',
        'Patchouli, Amber and Labdanum',
        'oud,warm spicy,rose,fresh spicy,amber',
        'Black Rose For WomenbyRefanis a Amber Floral fragrance for women. Top notes are Saffron and Pepper; middle notes are Agarwood (Oud), Rose and Jasmine; base notes are Patchouli, Amber and Labdanum.',
        4,
        13,
        NULL
      ),
(
        'Brown-Leather-21880',
        'Brown Leather Refan',
        'Brown',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'leather,violet,woody,aromatic,powdery',
        'Brown LeatherbyRefanis a Leather fragrance for women and men.',
        4.33,
        12,
        NULL
      ),
(
        'Chrysantheme-21881',
        'Chrysantheme Refan',
        'Chrysantheme',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,woody,fresh,green,herbal',
        'ChrysanthemebyRefanis a Floral Woody Musk fragrance for women.',
        3,
        4,
        NULL
      ),
(
        'Coca-Pura-21882',
        'Coca Pura Refan',
        'Coca',
        'for men',
        NULL,
        NULL,
        'Lemon and Pineapple',
        'Cedar',
        'Sandalwood',
        'woody,citrus,fruity,sweet,fresh',
        'Coca PurabyRefanis a Woody fragrance for men. Top notes are Lemon and Pineapple; middle note is Cedar; base note is Sandalwood.',
        4,
        1,
        NULL
      ),
(
        'Davana-21883',
        'Davana Refan',
        'Davana',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'herbal,white floral,amber,warm spicy,aromatic',
        'DavanabyRefanis a fragrance for women and men.',
        4.5,
        2,
        NULL
      ),
(
        'Fleur-d-Oranger-21884',
        'Fleur d''Oranger Refan',
        'Fleur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,tuberose',
        'Fleur d''OrangerbyRefanis a Floral fragrance for women.',
        4.25,
        4,
        NULL
      ),
(
        'Flor-Negra-Eau-de-Attraction-21885',
        'Flor Negra Eau de Attraction Refan',
        'Flor',
        'for men',
        NULL,
        NULL,
        'Bergamot and Grapefruit',
        'Beeswax and Gardenia',
        'Cedar and Patchouli',
        'citrus,woody,white floral,patchouli,fresh spicy',
        'Flor Negra Eau de AttractionbyRefanis a fragrance for men. Top notes are Bergamot and Grapefruit; middle notes are Beeswax and Gardenia; base notes are Cedar and Patchouli.',
        NULL,
        NULL,
        NULL
      ),
(
        'Lucha-Libre-Eau-de-Reaction-21886',
        'Lucha Libre Eau de Reaction Refan',
        'Lucha',
        'for men',
        NULL,
        NULL,
        'Cardamom and Pepper',
        'Nutmeg and Guaiac Wood',
        'Cedar and Sandalwood',
        'woody,fresh spicy,warm spicy,powdery,aromatic',
        'Lucha Libre Eau de ReactionbyRefanis a Woody Spicy fragrance for men. Top notes are Cardamom and Pepper; middle notes are Nutmeg and Guaiac Wood; base notes are Cedar and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Magnolia-21887',
        'Magnolia Refan',
        'Magnolia',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,white floral,ozonic,patchouli,rose',
        'MagnoliabyRefanis a Floral fragrance for women.',
        4.5,
        2,
        NULL
      ),
(
        'Moroccan-Rose-21888',
        'Moroccan Rose Refan',
        'Moroccan',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Moroccan RosebyRefanis a Floral fragrance for women.',
        4.29,
        7,
        NULL
      ),
(
        'Musc-21889',
        'Musc Refan',
        'Musc',
        'for women and men',
        NULL,
        NULL,
        'Aldehydes',
        'Rose and Jasmine',
        'Musk',
        'musky,aldehydic,powdery,fresh,rose',
        'MuscbyRefanis a fragrance for women and men. Top note is Aldehydes; middle notes are Rose and Jasmine; base note is Musk.',
        4.25,
        4,
        NULL
      ),
(
        'Orange-Elixir-21890',
        'Orange Elixir Refan',
        'Orange',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,musky,woody,fresh,powdery',
        'Orange ElixirbyRefanis a Citrus Aromatic fragrance for women and men.',
        4.67,
        3,
        NULL
      ),
(
        'Oriental-Rose-21891',
        'Oriental Rose Refan',
        'Oriental',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,warm spicy,amber,floral',
        'Oriental RosebyRefanis a Amber Floral fragrance for women.',
        4.14,
        7,
        NULL
      ),
(
        'Passion-Fruit-21873',
        'Passion Fruit Refan',
        'Passion',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,tropical,sweet,floral,fresh',
        'Passion FruitbyRefanis a Floral Fruity fragrance for women.',
        4.05,
        19,
        NULL
      ),
(
        'Refan-6-21874',
        'Refan 6 Refan',
        'Refan',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,musky,fruity,floral,fresh',
        'Refan 6byRefanis a Floral Fruity fragrance for women.Refan 6was launched in 2012.',
        4,
        2,
        NULL
      ),
(
        'Refan-69-21892',
        'Refan 69 Refan',
        'Refan',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,fresh,woody,balsamic',
        'Refan 69byRefanis a Woody Aromatic fragrance for women and men.',
        4.33,
        3,
        NULL
      ),
(
        'Refan-9-21893',
        'Refan 9 Refan',
        'Refan',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,citrus,green,patchouli',
        'Refan 9byRefanis a Woody Aromatic fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ron-Y-Menta-Eau-de-Temptation-21894',
        'Ron Y Menta Eau de Temptation Refan',
        'Ron',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon and Apple',
        'Plum and Wormwood',
        'Cedar, Sandalwood and Leather',
        'woody,citrus,fruity,aromatic,fresh spicy',
        'Ron Y Menta Eau de TemptationbyRefanis a fragrance for men. Top notes are Bergamot, Lemon and Apple; middle notes are Plum and Wormwood; base notes are Cedar, Sandalwood and Leather.',
        NULL,
        NULL,
        NULL
      ),
(
        'Rosa-Alba-21895',
        'Rosa Alba Refan',
        'Rosa',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Rosa AlbabyRefanis a Floral fragrance for women.',
        4.17,
        18,
        NULL
      ),
(
        'Rosa-Centifolia-21902',
        'Rosa Centifolia Refan',
        'Rosa',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Rosa CentifoliabyRefanis a Floral fragrance for women.',
        3.88,
        8,
        NULL
      ),
(
        'Rosa-Damascena-21896',
        'Rosa Damascena Refan',
        'Rosa',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Rosa DamascenabyRefanis a Floral fragrance for women.',
        3.88,
        16,
        NULL
      ),
(
        'Rose-21901',
        'Rose Refan',
        'Rose',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'RosebyRefanis a Floral fragrance for women.',
        4.17,
        12,
        NULL
      ),
(
        'Rose-Touch-21897',
        'Rose Touch Refan',
        'Rose',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Rose TouchbyRefanis a Floral fragrance for women.',
        4.33,
        9,
        NULL
      ),
(
        'Soft-Rose-21898',
        'Soft Rose Refan',
        'Soft',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Soft RosebyRefanis a Floral fragrance for women.',
        3.75,
        8,
        NULL
      ),
(
        'Sweet-Vanilla-21899',
        'Sweet Vanilla Refan',
        'Sweet',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,powdery',
        'Sweet VanillabyRefanis a fragrance for women.',
        3.45,
        11,
        NULL
      ),
(
        'Viva-La-Revolution-Eau-de-Revolucion-21900',
        'Viva La Revolution! Eau de Revolución Refan',
        'Viva',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange and Bergamot',
        'Cloves and Styrax',
        'Ambergris and Labdanum',
        'amber,citrus,warm spicy,animalic,balsamic',
        'Viva La Revolution! Eau de RevoluciónbyRefanis a Amber Spicy fragrance for men. Top notes are Mandarin Orange and Bergamot; middle notes are Cloves and Styrax; base notes are Ambergris and Labdanum.',
        4,
        3,
        NULL
      ),
(
        'Arabs-of-AlUla-89356',
        'Arabs of AlUla Reef Perfumes',
        'Arabs',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit',
        'Patchouli',
        'Leather',
        'citrus,leather,patchouli,woody,animalic',
        'Arabs of AlUlabyReef Perfumesis a fragrance for women and men. Top note is Grapefruit; middle note is Patchouli; base note is Leather.',
        5,
        2,
        NULL
      ),
(
        'Arabs-of-Diriyah-89271',
        'Arabs of Diriyah Reef Perfumes',
        'Arabs',
        'for men',
        NULL,
        NULL,
        'Saffron',
        'Agarwood (Oud)',
        'Tonka Bean',
        'oud,warm spicy,vanilla,amber,metallic',
        'Arabs of DiriyahbyReef Perfumesis a Chypre fragrance for men.Arabs of Diriyahwas launched in 2024. Top note is Saffron; middle note is Agarwood (Oud); base note is Tonka Bean.',
        4.14,
        7,
        NULL
      ),
(
        'Reef-01-89275',
        'Reef 01 Reef Perfumes',
        'Reef',
        'for women',
        NULL,
        NULL,
        'Orange Oil',
        'Rose',
        'Cashmeran',
        'citrus,rose,woody,musky,powdery',
        'Reef 01byReef Perfumesis a Woody Aromatic fragrance for women.Reef 01was launched in 2024. Top note is Orange Oil; middle note is Rose; base note is Cashmeran.',
        5,
        1,
        NULL
      );
