
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Tony-Iommi-Monkey-Special-70789',
        'Tony Iommi Monkey Special Xerjoff',
        'Tony',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Rum, Passionfruit, Bergamot and Geranium',
        'Singapore Patchouli, Cinnamon, Leather and Bulgarian Rose',
        'Caramel, Vanilla, Tonka Bean, Sandalwood, Labdanum, Ambergris and Musk',
        'warm spicy,woody,sweet,vanilla,patchouli',
        'Tony Iommi Monkey SpecialbyXerjoffis a fragrance for women and men.Tony Iommi Monkey Specialwas launched in 2021. The nose behind this fragrance is Chris Maurice. Top notes are Rum, Passionfruit, Bergamot and Geranium; middle notes are Singapore Patchouli, Cinnamon, Leather and Bulgarian Rose; base notes are Caramel, Vanilla, Tonka Bean, Sandalwood, Labdanum, Ambergris and Musk.',
        4.33,
        2,
        NULL
      ),
(
        'Tony-Iommi-Signed-Crystal-70788',
        'Tony Iommi Signed Crystal Xerjoff',
        'Tony',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Rum, Passionfruit, Bergamot and Geranium',
        'Singapore Patchouli, Leather, Cinnamon and Bulgarian Rose',
        'Caramel, Tonka Bean, Vanilla, Sandalwood, Labdanum, Musk and Ambergris',
        'warm spicy,woody,sweet,caramel,rum',
        'Tony Iommi Signed CrystalbyXerjoffis a fragrance for women and men.Tony Iommi Signed Crystalwas launched in 2021. The nose behind this fragrance is Chris Maurice. Top notes are Rum, Passionfruit, Bergamot and Geranium; middle notes are Singapore Patchouli, Leather, Cinnamon and Bulgarian Rose; base notes are Caramel, Tonka Bean, Vanilla, Sandalwood, Labdanum, Musk and Ambergris.',
        3.94,
        53,
        NULL
      ),
(
        'Damarose-11702',
        'Damarose Xerjoff',
        'Damarose',
        'for women',
        NULL,
        NULL,
        'Red Berries, Freesia, Lime and Bergamot',
        'Turkish Rose, Ylang-Ylang, Jasmine, Lily-of-the-Valley and Iris',
        'Amber, Musk, Vanilla, Sandalwood, Vetiver, Patchouli and Egyptian Rosewood',
        'rose,woody,floral,sweet,fruity',
        'DamarosebyXerjoffis a Chypre Floral fragrance for women.Damarosewas launched in 2010. Top notes are Red Berries, Freesia, Lime and Bergamot; middle notes are Turkish Rose, Ylang-Ylang, Jasmine, Lily-of-the-Valley and Iris; base notes are Amber, Musk, Vanilla, Sandalwood, Vetiver, Patchouli and Egyptian Rosewood.',
        4.15,
        240,
        NULL
      ),
(
        'Elle-6298',
        'Elle Xerjoff',
        'Elle',
        'for women',
        NULL,
        NULL,
        'Citruses, African Orange Flower and Galbanum',
        'Iris, Birch, Woodsy Notes and Patchouli',
        'Benzoin, Opoponax, Musk and Amber',
        'amber,citrus,woody,white floral,balsamic',
        'EllebyXerjoffis a Amber Floral fragrance for women.Ellewas launched in 2007. Top notes are Citruses, African Orange Flower and Galbanum; middle notes are Iris, Birch, Woodsy Notes and Patchouli; base notes are Benzoin, Opoponax, Musk and Amber.',
        4.19,
        355,
        NULL
      ),
(
        'Elle-Anniversary-88612',
        'Elle Anniversary Xerjoff',
        'Elle',
        'for women',
        NULL,
        NULL,
        'Red Fruits, Litchi, Green Apple and Bergamot',
        'Cashmere Wood, Jasmine, Peony and Licorice',
        'Sandalwood, Musk, Amber and Patchouli',
        'woody,musky,fruity,fresh,amber',
        'Elle AnniversarybyXerjoffis a fragrance for women. This is a new fragrance.Elle Anniversarywas launched in 2023. Top notes are Red Fruits, Litchi, Green Apple and Bergamot; middle notes are Cashmere Wood, Jasmine, Peony and Licorice; base notes are Sandalwood, Musk, Amber and Patchouli.',
        4.08,
        26,
        NULL
      ),
(
        'Homme-6299',
        'Homme Xerjoff',
        'Homme',
        'for men',
        NULL,
        NULL,
        'Spices and Citruses',
        'Lavender, Clove and Ylang-Ylang',
        'Leather, Vetiver and Woodsy Notes',
        'leather,woody,warm spicy,aromatic,lavender',
        'HommebyXerjoffis a Woody fragrance for men.Hommewas launched in 2007. Top notes are Spices and Citruses; middle notes are Lavender, Clove and Ylang-Ylang; base notes are Leather, Vetiver and Woodsy Notes.',
        4.08,
        284,
        NULL
      ),
(
        'Homme-Anniversary-94591',
        'Homme Anniversary Xerjoff',
        'Homme',
        'for women and men',
        NULL,
        NULL,
        'Tarragon, Bergamot and Lemon',
        'Orange Blossom, Clove, Leather and Tonka Bean',
        'Candied Fruits, Styrax, Vanilla and Moss',
        'citrus,sweet,aromatic,amber,warm spicy',
        'Homme AnniversarybyXerjoffis a Leather fragrance for women and men. This is a new fragrance.Homme Anniversarywas launched in 2024. Top notes are Tarragon, Bergamot and Lemon; middle notes are Orange Blossom, Clove, Leather and Tonka Bean; base notes are Candied Fruits, Styrax, Vanilla and Moss.',
        4.75,
        16,
        NULL
      ),
(
        'Irisss-11704',
        'Irisss Xerjoff',
        'Irisss',
        'for women',
        NULL,
        NULL,
        'Carrot Seeds, Carnation and Bergamot',
        'Iris, Violet, Rose and Jasmine',
        'Musk, Vetiver, Cedar and Incense',
        'powdery,violet,iris,woody,musky',
        'IrisssbyXerjoffis a Floral fragrance for women.Irissswas launched in 2008. Top notes are Carrot Seeds, Carnation and Bergamot; middle notes are Iris, Violet, Rose and Jasmine; base notes are Musk, Vetiver, Cedar and Incense.',
        3.96,
        388,
        NULL
      ),
(
        'Lunosa-62614',
        'Lunosa Xerjoff',
        'Lunosa',
        'for women and men',
        NULL,
        NULL,
        'Cypriol Oil or Nagarmotha and Neroli',
        'Indian Tuberose, Gardenia and Sandalwood',
        'Tobacco, Agarwood (Oud) and Haitian Vetiver',
        'woody,white floral,tobacco,earthy,oud',
        'LunosabyXerjoffis a Amber Floral fragrance for women and men.Lunosawas launched in 2020. Top notes are Cypriol Oil or Nagarmotha and Neroli; middle notes are Indian Tuberose, Gardenia and Sandalwood; base notes are Tobacco, Agarwood (Oud) and Haitian Vetiver.',
        3.84,
        62,
        NULL
      ),
(
        'Pikovaya-Dama-2018-49504',
        'Pikovaya Dama 2018 Xerjoff',
        'Pikovaya',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Aldehydes, Neroli, Bergamot, Rose and Lemon',
        'Iris, Incense, Coriander, Cedar and Nutmeg',
        'Musk, Vanilla, Sandalwood and Patchouli',
        'powdery,aldehydic,citrus,woody,fresh',
        'Pikovaya Dama 2018byXerjoffis a Floral Aldehyde fragrance for women and men.Pikovaya Dama 2018was launched in 2018. The nose behind this fragrance is Chris Maurice. Top notes are Aldehydes, Neroli, Bergamot, Rose and Lemon; middle notes are Iris, Incense, Coriander, Cedar and Nutmeg; base notes are Musk, Vanilla, Sandalwood and Patchouli.',
        4.3,
        805,
        NULL
      ),
(
        'Richwood-11703',
        'Richwood Xerjoff',
        'Richwood',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, Bergamot and Grapefruit',
        'Damask Rose and Black Currant',
        'Patchouli, Sandalwood, Vanilla, Labdanum and Musk',
        'woody,patchouli,citrus,warm spicy,powdery',
        'RichwoodbyXerjoffis a Woody Chypre fragrance for women and men.Richwoodwas launched in 2010. Top notes are Tangerine, Bergamot and Grapefruit; middle notes are Damask Rose and Black Currant; base notes are Patchouli, Sandalwood, Vanilla, Labdanum and Musk.',
        4.31,
        1,
        NULL
      ),
(
        'Symphonium-59707',
        'Symphonium Xerjoff',
        'Symphonium',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Orange and Mandarin Orange',
        'Chocolate and Cardamom',
        'Madagascar Vanilla, Laotian Oud, Thailand Oud and Musk',
        'citrus,warm spicy,sweet,oud,chocolate',
        'SymphoniumbyXerjoffis a Amber Vanilla fragrance for women and men.Symphoniumwas launched in 2020. The nose behind this fragrance is Chris Maurice. Top notes are Orange and Mandarin Orange; middle notes are Chocolate and Cardamom; base notes are Madagascar Vanilla, Laotian Oud, Thailand Oud and Musk.',
        4,
        524,
        NULL
      ),
(
        'Symphonium-2015-41210',
        'Symphonium 2015 Xerjoff',
        'Symphonium',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Orange and Mandarin Orange',
        'Chocolate and Cardamom',
        'Laotian Oud, Thailand Oud, Madagascar Vanilla and White Musk',
        'citrus,oud,warm spicy,sweet,chocolate',
        'Symphonium 2015byXerjoffis a Amber Vanilla fragrance for women and men.Symphonium 2015was launched in 2015. The nose behind this fragrance is Chris Maurice. Top notes are Orange and Mandarin Orange; middle notes are Chocolate and Cardamom; base notes are Laotian Oud, Thailand Oud, Madagascar Vanilla and White Musk.',
        4.34,
        41,
        NULL
      ),
(
        'Symphonium-Parfum-66677',
        'Symphonium Parfum Xerjoff',
        'Symphonium',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Orange and Mandarin Orange',
        'Chocolate and Cardamom',
        'Vanilla, Laotian Oud, Musk and Thailand Oud',
        'citrus,sweet,chocolate,warm spicy,vanilla',
        'Symphonium ParfumbyXerjoffis a Amber Vanilla fragrance for women and men.Symphonium Parfumwas launched in 2021. The nose behind this fragrance is Chris Maurice. Top notes are Orange and Mandarin Orange; middle notes are Chocolate and Cardamom; base notes are Vanilla, Laotian Oud, Musk and Thailand Oud.',
        4.14,
        237,
        NULL
      ),
(
        'XXY-11706',
        'XXY Xerjoff',
        'XXY',
        'for women and men',
        NULL,
        NULL,
        'Peach, Bergamot and Grapefruit',
        'Iris, Ylang-Ylang, Black Pepper and Jasmine',
        'Patchouli, Vanilla, Sandalwood, Vetiver, Musk and Labdanum',
        'woody,powdery,citrus,fresh spicy,earthy',
        'XXYbyXerjoffis a Amber Floral fragrance for women and men.XXYwas launched in 2008. Top notes are Peach, Bergamot and Grapefruit; middle notes are Iris, Ylang-Ylang, Black Pepper and Jasmine; base notes are Patchouli, Vanilla, Sandalwood, Vetiver, Musk and Labdanum.',
        3.9,
        150,
        NULL
      ),
(
        'Damarose-Perfume-Extract-52159',
        'Damarose Perfume Extract Xerjoff',
        'Damarose',
        'for women',
        NULL,
        'Chris Maurice',
        'Red Berries, Bergamot, Lime and Freesia',
        'Turkish Rose, Jasmine, Iris, Lily-of-the-Valley and Ylang-Ylang',
        'Patchouli, Vanilla, Sandalwood, Palisander Rosewood, Amber, Vetiver and Musk',
        'woody,powdery,white floral,amber,sweet',
        'Damarose Perfume ExtractbyXerjoffis a Chypre Floral fragrance for women. The nose behind this fragrance is Chris Maurice. Top notes are Red Berries, Bergamot, Lime and Freesia; middle notes are Turkish Rose, Jasmine, Iris, Lily-of-the-Valley and Ylang-Ylang; base notes are Patchouli, Vanilla, Sandalwood, Palisander Rosewood, Amber, Vetiver and Musk.',
        4.22,
        9,
        NULL
      ),
(
        'Elle-Perfume-Extract-52160',
        'Elle Perfume Extract Xerjoff',
        'Elle',
        'for women',
        NULL,
        'Chris Maurice',
        'Citruses, Orange Blossom and Galbanum',
        'Patchouli, Birch, Iris and Woody Notes',
        'Benzoin, Musk, Opoponax and Amber',
        'amber,woody,citrus,warm spicy,balsamic',
        'Elle Perfume ExtractbyXerjoffis a Amber Floral fragrance for women. The nose behind this fragrance is Chris Maurice. Top notes are Citruses, Orange Blossom and Galbanum; middle notes are Patchouli, Birch, Iris and Woody Notes; base notes are Benzoin, Musk, Opoponax and Amber.',
        4.43,
        7,
        NULL
      ),
(
        'Homme-Perfume-Extract-52161',
        'Homme Perfume Extract Xerjoff',
        'Homme',
        'for men',
        NULL,
        NULL,
        'Spices and Citruses',
        'Ylang-Ylang, Cloves and Lavender',
        'Vetiver, Leather and Woody Notes',
        'woody,warm spicy,leather,aromatic,citrus',
        'Homme Perfume ExtractbyXerjoffis a Woody fragrance for men. Top notes are Spices and Citruses; middle notes are Ylang-Ylang, Cloves and Lavender; base notes are Vetiver, Leather and Woody Notes.',
        4,
        6,
        NULL
      ),
(
        'Irisss-Perfume-Extract-52162',
        'Irisss Perfume Extract Xerjoff',
        'Irisss',
        'for women',
        NULL,
        'Chris Maurice',
        'Carnation, Bergamot and Carrot Seeds',
        'Iris, Violet, Ylang-Ylang, Rose and Jasmine',
        'Cedar, Benzoin, Musk, Vetiver and Incense',
        'powdery,woody,violet,floral,iris',
        'Irisss Perfume ExtractbyXerjoffis a Floral fragrance for women. The nose behind this fragrance is Chris Maurice. Top notes are Carnation, Bergamot and Carrot Seeds; middle notes are Iris, Violet, Ylang-Ylang, Rose and Jasmine; base notes are Cedar, Benzoin, Musk, Vetiver and Incense.',
        3.83,
        6,
        NULL
      ),
(
        'Richwood-Perfume-Extract-52163',
        'Richwood Perfume Extract Xerjoff',
        'Richwood',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Tangerine, Bergamot and Grapefruit',
        'Damask Rose and Black Currant',
        'Sandalwood, Patchouli, Labdanum, Vanilla and Musk',
        'citrus,woody,powdery,musky,patchouli',
        'Richwood Perfume ExtractbyXerjoffis a Woody Chypre fragrance for women and men. The nose behind this fragrance is Chris Maurice. Top notes are Tangerine, Bergamot and Grapefruit; middle notes are Damask Rose and Black Currant; base notes are Sandalwood, Patchouli, Labdanum, Vanilla and Musk.',
        4.14,
        7,
        NULL
      ),
(
        'XXY-Perfume-Extract-52164',
        'XXY Perfume Extract Xerjoff',
        'XXY',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Bergamot, Grapefruit and Peach',
        'Ylang-Ylang, Jasmine, Iris and Black Pepper',
        'Vanilla, Patchouli, Sandalwood, Vetiver, Labdanum and Musk',
        'woody,powdery,vanilla,citrus,fresh spicy',
        'XXY Perfume ExtractbyXerjoffis a Amber Floral fragrance for women and men. The nose behind this fragrance is Chris Maurice. Top notes are Bergamot, Grapefruit and Peach; middle notes are Ylang-Ylang, Jasmine, Iris and Black Pepper; base notes are Vanilla, Patchouli, Sandalwood, Vetiver, Labdanum and Musk.',
        2.67,
        9,
        NULL
      ),
(
        'XJ-1861-Decas-66198',
        'XJ 1861 Decas Xerjoff',
        'XJ',
        'for women and men',
        NULL,
        'Chris Maurice',
        'Calabrian Mandarin, Tuberose and Tobacco',
        'Benzoin, Opoponax and Italian Orris Root',
        'Resin, Bourbon Vanilla and Musk',
        'amber,citrus,vanilla,balsamic,sweet',
        'XJ 1861 DecasbyXerjoffis a Amber Floral fragrance for women and men.XJ 1861 Decaswas launched in 2021. The nose behind this fragrance is Chris Maurice. Top notes are Calabrian Mandarin, Tuberose and Tobacco; middle notes are Benzoin, Opoponax and Italian Orris Root; base notes are Resin, Bourbon Vanilla and Musk.',
        4.04,
        740,
        NULL
      ),
(
        'XJ-1861-Naxos-30529',
        'XJ 1861 Naxos Xerjoff',
        'XJ',
        'for women and men',
        NULL,
        NULL,
        'Lavender, Bergamot and Lemon',
        'Honey, Cinnamon, Cashmeran and Jasmine Sambac',
        'Tobacco Leaf, Vanilla and Tonka Bean',
        'sweet,vanilla,honey,tobacco,lavender',
        'XJ 1861 NaxosbyXerjoffis a Citrus Gourmand fragrance for women and men.XJ 1861 Naxoswas launched in 2015. Top notes are Lavender, Bergamot and Lemon; middle notes are Honey, Cinnamon, Cashmeran and Jasmine Sambac; base notes are Tobacco Leaf, Vanilla and Tonka Bean.',
        4.51,
        9,
        NULL
      ),
(
        'XJ-1861-Renaissance-12126',
        'XJ 1861 Renaissance Xerjoff',
        'XJ',
        'for women and men',
        NULL,
        NULL,
        'Amalfi Lemon, Tangerine, Bergamot and Petitgrain',
        'Mint, Lily-of-the-Valley and Rose',
        'Musk, Virginia Cedar, Amber and Patchouli',
        'citrus,green,aromatic,fresh spicy,woody',
        'XJ 1861 RenaissancebyXerjoffis a Citrus Aromatic fragrance for women and men.XJ 1861 Renaissancewas launched in 2011. Top notes are Amalfi Lemon, Tangerine, Bergamot and Petitgrain; middle notes are Mint, Lily-of-the-Valley and Rose; base notes are Musk, Virginia Cedar, Amber and Patchouli.',
        4.3,
        2,
        NULL
      ),
(
        'XJ-1861-Zefiro-30530',
        'XJ 1861 Zefiro Xerjoff',
        'XJ',
        'for women and men',
        NULL,
        'Mathieu Nardin',
        'Elemi resin, White Wine, Artemisia and Bergamot',
        'Cardamom, Cinnamon, Carnation and Iris',
        'Incense, Woodsy Notes, Amber and Honey',
        'warm spicy,aromatic,amber,woody,balsamic',
        'XJ 1861 ZefirobyXerjoffis a Amber Spicy fragrance for women and men.XJ 1861 Zefirowas launched in 2015. The nose behind this fragrance is Mathieu Nardin. Top notes are Elemi resin, White Wine, Artemisia and Bergamot; middle notes are Cardamom, Cinnamon, Carnation and Iris; base notes are Incense, Woodsy Notes, Amber and Honey.',
        4.23,
        1,
        NULL
      ),
(
        '8e-Jour-8857',
        '8e Jour Yves Rocher',
        '8e',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,warm spicy,cinnamon,honey,amber',
        '8e JourbyYves Rocheris a Amber Floral fragrance for women.8e Jourwas launched in 1993.',
        4.17,
        607,
        NULL
      ),
(
        'Altika-9456',
        'Altika Yves Rocher',
        'Altika',
        'for men',
        NULL,
        'Annick Menardo',
        NULL,
        'Mint',
        'Virginia Cedar',
        'green,woody,aromatic,fresh spicy,powdery',
        'AltikabyYves Rocheris a Woody Aromatic fragrance for men.Altikawas launched in 2006. The nose behind this fragrance is Annick Menardo. middle note is Mint; base note is Virginia Cedar.',
        3.73,
        103,
        NULL
      ),
(
        'Antartic-4365',
        'Antartic Yves Rocher',
        'Antartic',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,citrus,woody,green',
        'AntarticbyYves Rocheris a Aromatic Aquatic fragrance for men.Antarticwas launched in 1990.',
        4.02,
        132,
        NULL
      ),
(
        'Aquarelles-Vegetales-Eau-Fruitee-pour-L-Ete-8744',
        'Aquarelles Végétales Eau Fruitee pour L''Ete Yves Rocher',
        'Aquarelles',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,floral,sweet,fruity',
        'Aquarelles Végétales Eau Fruitee pour L''EtebyYves Rocheris a Floral Fruity fragrance for women.Aquarelles Végétales Eau Fruitee pour L''Etewas launched in 2010.',
        3.85,
        246,
        NULL
      ),
(
        'Aztek-9985',
        'Aztek Yves Rocher',
        'Aztek',
        'for men',
        NULL,
        NULL,
        'Lavender, Artemisia, Bergamot and Tarragon',
        'Caraway, Rose, Clove and Pepper',
        'Sandalwood, Tonka Bean and Vanille',
        'fresh spicy,aromatic,warm spicy,woody,vanilla',
        'AztekbyYves Rocheris a Amber Spicy fragrance for men.Aztekwas launched in 1993. Top notes are Lavender, Artemisia, Bergamot and Tarragon; middle notes are Caraway, Rose, Clove and Pepper; base notes are Sandalwood, Tonka Bean and Vanille.',
        3.98,
        127,
        NULL
      ),
(
        'Babiflore-40831',
        'Babiflore Yves Rocher',
        'Babiflore',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,almond,nutty,fruity,sweet',
        'BabiflorebyYves Rocheris a Floral fragrance for women and men.Babiflorewas launched in 1986.',
        2.67,
        3,
        NULL
      ),
(
        'Babinours-40834',
        'Babinours Yves Rocher',
        'Babinours',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,vanilla,woody,powdery',
        'BabinoursbyYves Rocheris a fragrance for women and men.Babinourswas launched in 1990.',
        4.25,
        20,
        NULL
      ),
(
        'Bleu-Vegetal-32731',
        'Bleu Végétal Yves Rocher',
        'Bleu',
        'for women',
        NULL,
        'Annick Menardo',
        NULL,
        NULL,
        NULL,
        'white floral,citrus,fresh spicy,floral,aromatic',
        'Bleu VégétalbyYves Rocheris a Floral Aquatic fragrance for women.Bleu Végétalwas launched in 2015. The nose behind this fragrance is Annick Menardo.',
        3.55,
        119,
        NULL
      ),
(
        'Cantate-7900',
        'Cantate Yves Rocher',
        'Cantate',
        'for women',
        NULL,
        NULL,
        'Tincture of Rose, Iris and Jasmine',
        'Cinnamon, Spices and Osmanthus',
        'Sandalwood, Tonka Bean, Vanille and Virginia Cedar',
        'warm spicy,woody,vanilla,cinnamon,rose',
        'CantatebyYves Rocheris a Floral Woody Musk fragrance for women.Cantatewas launched in 1995. Top notes are Tincture of Rose, Iris and Jasmine; middle notes are Cinnamon, Spices and Osmanthus; base notes are Sandalwood, Tonka Bean, Vanille and Virginia Cedar.',
        4.07,
        563,
        NULL
      ),
(
        'Chevrefeuille-9908',
        'Chevrefeuille Yves Rocher',
        'Chevrefeuille',
        'for women',
        NULL,
        NULL,
        'Amalfi Lemon and Orange',
        'Honeysuckle and Jasmine',
        'Virginia Cedar and Myrhh',
        'white floral,citrus,fruity,woody,amber',
        'ChevrefeuillebyYves Rocheris a Floral Green fragrance for women.Chevrefeuillewas launched in 1976. Top notes are Amalfi Lemon and Orange; middle notes are Honeysuckle and Jasmine; base notes are Virginia Cedar and Myrhh.',
        3.99,
        281,
        NULL
      ),
(
        'Clea-4907',
        'Clea Yves Rocher',
        'Clea',
        'for women',
        NULL,
        'Francoise Caron',
        NULL,
        NULL,
        NULL,
        'white floral,woody,yellow floral,amber,rose',
        'CleabyYves Rocheris a Amber Floral fragrance for women.Cleawas launched in 1980. The nose behind this fragrance is Francoise Caron.',
        3.79,
        796,
        NULL
      ),
(
        'Coeur-de-Nature-40835',
        'Coeur de Nature Yves Rocher',
        'Coeur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,floral',
        'Coeur de NaturebyYves Rocheris a Floral Green fragrance for women.Coeur de Naturewas launched during the 1980''s.',
        3.55,
        20,
        NULL
      ),
(
        'Collection-Ete-24723',
        'Collection Été Yves Rocher',
        'Collection',
        'for women',
        NULL,
        'Francis Kurkdjian',
        'Mandarin Orange, Lemon and Bergamot',
        'Citrus Blossom',
        'Woody Notes',
        'citrus,woody,white floral',
        'Collection ÉtébyYves Rocheris a Citrus Aromatic fragrance for women.Collection Étéwas launched in 2014. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mandarin Orange, Lemon and Bergamot; middle note is Citrus Blossom; base note is Woody Notes.',
        3.8,
        249,
        NULL
      ),
(
        'Collection-Ete-2017-44910',
        'Collection Ete 2017 Yves Rocher',
        'Collection',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,citrus,green,fresh spicy,sweet',
        'Collection Ete 2017byYves Rocheris a Aromatic Fruity fragrance for women.Collection Ete 2017was launched in 2017.',
        3.48,
        145,
        NULL
      ),
(
        'Desir-de-Nature-3388',
        'Desir de Nature Yves Rocher',
        'Desir',
        'for women',
        NULL,
        NULL,
        'Mint and Mandarin Orange',
        'Lily-of-the-Valley',
        'Oakmoss and Juniper',
        'white floral,aromatic,green,mossy,fresh spicy',
        'Desir de NaturebyYves Rocheris a Floral Green fragrance for women.Desir de Naturewas launched in 1981. Top notes are Mint and Mandarin Orange; middle note is Lily-of-the-Valley; base notes are Oakmoss and Juniper.',
        3.37,
        1,
        NULL
      ),
(
        'Diamella-9174',
        'Diamella Yves Rocher',
        'Diamella',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,mossy,floral,earthy,aldehydic',
        'DiamellabyYves Rocheris a Chypre Floral fragrance for women.Diamellawas launched in 1984.',
        4.2,
        131,
        NULL
      ),
(
        'Eau-de-Juillet-27274',
        'Eau de Juillet Yves Rocher',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,floral,green',
        'Eau de JuilletbyYves Rocheris a Citrus fragrance for women.Eau de Juilletwas launched in 1989.',
        3.91,
        11,
        NULL
      ),
(
        'Eau-de-Lavande-39410',
        'Eau de Lavande Yves Rocher',
        'Eau',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lavender,aromatic,fresh spicy',
        'Eau de LavandebyYves Rocheris a fragrance for women and men.Eau de Lavandewas launched during the 1980''s.',
        4.12,
        8,
        NULL
      ),
(
        'Eau-De-Vetyver-47858',
        'Eau De Vetyver Yves Rocher',
        'Eau',
        'for men',
        NULL,
        'Raymond Chaillan',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,earthy',
        'Eau De VetyverbyYves Rocheris a fragrance for men.Eau De Vetyverwas launched in 1982. The nose behind this fragrance is Raymond Chaillan.',
        4,
        9,
        NULL
      ),
(
        'Eau-Fraiche-Cedrat-34740',
        'Eau Fraiche Cedrat Yves Rocher',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,sweet',
        'Eau Fraiche CedratbyYves Rocheris a Citrus fragrance for women.',
        4.12,
        17,
        NULL
      ),
(
        'Eglantine-27246',
        'Eglantine Yves Rocher',
        'Eglantine',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,green,citrus,fresh',
        'EglantinebyYves Rocheris a Floral fragrance for women.Eglantinewas launched in 1979.',
        3.64,
        14,
        NULL
      ),
(
        'En-Avril-Un-Soir-13615',
        'En Avril Un Soir Yves Rocher',
        'En',
        'for women',
        NULL,
        NULL,
        'Aldehydes, Ylang-Ylang, African Orange Flower and Bergamot',
        'Jasmine, Rose and Freesia',
        'oak moss, Sandalwood, Iris, Musk, Virginia Cedar and Patchouli',
        'woody,white floral,floral,aldehydic,powdery',
        'En Avril Un SoirbyYves Rocheris a Chypre Floral fragrance for women.En Avril Un Soirwas launched in 1976. Top notes are Aldehydes, Ylang-Ylang, African Orange Flower and Bergamot; middle notes are Jasmine, Rose and Freesia; base notes are oak moss, Sandalwood, Iris, Musk, Virginia Cedar and Patchouli.',
        4.26,
        93,
        NULL
      ),
(
        'Eryo-9454',
        'Eryo Yves Rocher',
        'Eryo',
        'for men',
        NULL,
        NULL,
        'Bergamot and Mint',
        'Rosemary',
        'Vanille, Benzoin, Ginger and Patchouli',
        'warm spicy,aromatic,vanilla,fresh spicy,woody',
        'EryobyYves Rocheris a Amber Spicy fragrance for men.Eryowas launched in 2002. Top notes are Bergamot and Mint; middle note is Rosemary; base notes are Vanille, Benzoin, Ginger and Patchouli.',
        4.01,
        167,
        NULL
      ),
(
        'Eryo-Blue-9455',
        'Eryo Blue Yves Rocher',
        'Eryo',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,aromatic,woody,fresh spicy,citrus',
        'Eryo BluebyYves Rocheris a Woody Aquatic fragrance for men.Eryo Bluewas launched in 2004.',
        3.8,
        51,
        NULL
      ),
(
        'Fleur-de-The-38282',
        'Fleur de Thé Yves Rocher',
        'Fleur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,floral',
        'Fleur de ThébyYves Rocheris a Floral Green fragrance for women.Fleur de Théwas launched in 1998.',
        4.1,
        31,
        NULL
      ),
(
        'Fleur-Tendre-27247',
        'Fleur Tendre Yves Rocher',
        'Fleur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'almond,floral,musky,sweet,nutty',
        'Fleur TendrebyYves Rocheris a Floral fragrance for women.Fleur Tendrewas launched in 2008.',
        3.64,
        73,
        NULL
      ),
(
        'Fleureter-40832',
        'Fleureter Yves Rocher',
        'Fleureter',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,floral,woody,powdery',
        'FleureterbyYves Rocheris a Floral fragrance for women.Fleureterwas launched in 1976.',
        3,
        2,
        NULL
      ),
(
        'Fleurs-des-Sentiers-82143',
        'Fleurs des Sentiers Yves Rocher',
        'Fleurs',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,herbal,aromatic,rose,fresh spicy',
        'Fleurs des SentiersbyYves Rocheris a Floral fragrance for women and men. This is a new fragrance.Fleurs des Sentierswas launched in 2023.',
        3.73,
        80,
        NULL
      ),
(
        'Flowers-in-the-City-74110',
        'Flowers in the City Yves Rocher',
        'Flowers',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,rose,fresh spicy,floral,aromatic',
        'Flowers in the CitybyYves Rocheris a Floral fragrance for women. This is a new fragrance.Flowers in the Citywas launched in 2022.',
        3.6,
        50,
        NULL
      ),
(
        'Frisson-d-Eau-47857',
        'Frisson d''Eau Yves Rocher',
        'Frisson',
        'for women and men',
        NULL,
        'Raymond Chaillan',
        NULL,
        NULL,
        NULL,
        NULL,
        'Frisson d''EaubyYves Rocheris a fragrance for women and men.Frisson d''Eauwas launched in 1982. The nose behind this fragrance is Raymond Chaillan.',
        1,
        1,
        NULL
      ),
(
        'Fruit-de-Noel-13692',
        'Fruit de Noel Yves Rocher',
        'Fruit',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,almond,sweet,fruity,nutty',
        'Fruit de NoelbyYves Rocheris a Citrus Gourmand fragrance for women.Fruit de Noelwas launched in 2011.',
        3.62,
        132,
        NULL
      ),
(
        'Fruits-de-Noel-Orange-Amande-10497',
        'Fruits de Noel Orange & Amande Yves Rocher',
        'Fruits',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,almond,fruity,nutty',
        'Fruits de Noel Orange & AmandebyYves Rocheris a Citrus Gourmand fragrance for women.Fruits de Noel Orange & Amandewas launched in 2010.',
        3.93,
        83,
        NULL
      ),
(
        'Fruits-de-Noel-Orange-Chocolat-10498',
        'Fruits de Noel Orange & Chocolat Yves Rocher',
        'Fruits',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,cacao,warm spicy,sweet,fresh spicy',
        'Fruits de Noel Orange & ChocolatbyYves Rocheris a Citrus Gourmand fragrance for women.Fruits de Noel Orange & Chocolatwas launched in 2010.',
        3.97,
        164,
        NULL
      ),
(
        'Fruits-Noirs-Blackberries-28574',
        'Fruits Noirs Blackberries Yves Rocher',
        'Fruits',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,violet',
        'Fruits Noirs BlackberriesbyYves Rocheris a Aromatic Fruity fragrance for women.Fruits Noirs Blackberrieswas launched in 2014.',
        3.42,
        115,
        NULL
      ),
(
        'Gaelle-33162',
        'Gaelle Yves Rocher',
        'Gaelle',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,white floral,herbal,fresh spicy',
        'GaellebyYves Rocheris a fragrance for women.Gaellewas launched in 1978.',
        3.5,
        4,
        NULL
      ),
(
        'Green-Summer-6059',
        'Green Summer Yves Rocher',
        'Green',
        'for women',
        NULL,
        NULL,
        'Mango, Clementine, Orange and Lime',
        'Nectarine, Cyclamen, Hibiscus and Freesia',
        'Raspberry, Musk and Lime (Linden Blossom)',
        'fruity,sweet,citrus,floral,tropical',
        'Green SummerbyYves Rocheris a Floral Fruity fragrance for women.Green Summerwas launched in 2009. Top notes are Mango, Clementine, Orange and Lime; middle notes are Nectarine, Cyclamen, Hibiscus and Freesia; base notes are Raspberry, Musk and Lime (Linden Blossom).',
        3.81,
        252,
        NULL
      ),
(
        'Hello-Printemps-60442',
        'Hello Printemps Yves Rocher',
        'Hello',
        'for women and men',
        NULL,
        NULL,
        'Cassis and Citruses',
        'Palmarosa and Ginger',
        'Rhubarb and Cedar',
        'green,aromatic,fruity,fresh,woody',
        'Hello PrintempsbyYves Rocheris a Citrus Aromatic fragrance for women and men.Hello Printempswas launched in 2020. Top notes are Cassis and Citruses; middle notes are Palmarosa and Ginger; base notes are Rhubarb and Cedar.',
        3.81,
        222,
        NULL
      ),
(
        'Homme-Nature-3389',
        'Homme Nature Yves Rocher',
        'Homme',
        'for men',
        NULL,
        NULL,
        'Cucumber and Bergamot',
        'Ivy, Mint and Carnation',
        'Sage, Oakmoss and Sandalwood',
        'green,aromatic,ozonic,woody,fresh spicy',
        'Homme NaturebyYves Rocheris a Aromatic fragrance for men.Homme Naturewas launched in 1999. Top notes are Cucumber and Bergamot; middle notes are Ivy, Mint and Carnation; base notes are Sage, Oakmoss and Sandalwood.',
        3.96,
        457,
        NULL
      ),
(
        'Ispahan-4421',
        'Ispahan Yves Rocher',
        'Ispahan',
        'for women',
        NULL,
        'Maurice Roucel',
        'Bergamot, Mandarin Orange, Aldehydes and Fruity Notes',
        'Ylang-Ylang, Mimosa, Rose, Jasmine, Lily-of-the-Valley, Clove and Cinnamon',
        'Nutmeg, Benzoin, Vanilla, Tonka Bean, Frankincense, Patchouli, Sandalwood, Tolu Balsam, Amber and Musk',
        'yellow floral,amber,vanilla,fresh spicy,sweet',
        'IspahanbyYves Rocheris a Amber Spicy fragrance for women.Ispahanwas launched in 1977. The nose behind this fragrance is Maurice Roucel. Top notes are Bergamot, Mandarin Orange, Aldehydes and Fruity Notes; middle notes are Ylang-Ylang, Mimosa, Rose, Jasmine, Lily-of-the-Valley, Clove and Cinnamon; base notes are Nutmeg, Benzoin, Vanilla, Tonka Bean, Frankincense, Patchouli, Sandalwood, Tolu Balsam, Amber and Musk.',
        3.95,
        2,
        NULL
      ),
(
        'Ispahan-Parfum-78602',
        'Ispahan Parfum Yves Rocher',
        'Ispahan',
        'for women',
        NULL,
        'Maurice Roucel',
        'Bergamot and Mandarin Orange',
        'Rose, Ylang-Ylang, Jasmine, Mimosa and Lily-of-the-Valley',
        'Nutmeg, Benzoin, Vanilla and Tonka Bean',
        'vanilla,fresh spicy,rose,citrus,amber',
        'Ispahan ParfumbyYves Rocheris a Amber Spicy fragrance for women.Ispahan Parfumwas launched in 1977. The nose behind this fragrance is Maurice Roucel. Top notes are Bergamot and Mandarin Orange; middle notes are Rose, Ylang-Ylang, Jasmine, Mimosa and Lily-of-the-Valley; base notes are Nutmeg, Benzoin, Vanilla and Tonka Bean.',
        4.5,
        26,
        NULL
      ),
(
        'Jardin-des-Nymphes-12217',
        'Jardin des Nymphes Yves Rocher',
        'Jardin',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aquatic,floral,fresh',
        'Jardin des NymphesbyYves Rocheris a Floral Aquatic fragrance for women.Jardin des Nympheswas launched in 2011.',
        3.74,
        441,
        NULL
      ),
(
        'Lavande-40552',
        'Lavande Yves Rocher',
        'Lavande',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lavender,aromatic,fresh spicy',
        'LavandebyYves Rocheris a fragrance for women and men.Lavandewas launched in 1998.',
        4,
        10,
        NULL
      ),
(
        'Magnolia-935',
        'Magnolia Yves Rocher',
        'Magnolia',
        'for women',
        NULL,
        NULL,
        'Magnolia and Apple',
        'Lily, Gardenia, Tuberose and Jasmine',
        'Oakmoss, Cedar, Musk, Sandalwood, Patchouli and Vanilla',
        'white floral,floral,woody,citrus,mossy',
        'MagnoliabyYves Rocheris a Floral fragrance for women.Magnoliawas launched in 1983. Top notes are Magnolia and Apple; middle notes are Lily, Gardenia, Tuberose and Jasmine; base notes are Oakmoss, Cedar, Musk, Sandalwood, Patchouli and Vanilla.',
        3.88,
        1,
        NULL
      ),
(
        'Mauves-Cristallisees-16874',
        'Mauves Cristallisées Yves Rocher',
        'Mauves',
        'for women',
        NULL,
        NULL,
        'Sweet Almond',
        'Rose Mallow and Rose',
        'Tonka Bean and White Musk',
        'almond,musky,floral,sweet,nutty',
        'Mauves CristalliséesbyYves Rocheris a Floral fragrance for women.Mauves Cristalliséeswas launched in 2012. Top note is Sweet Almond; middle notes are Rose Mallow and Rose; base notes are Tonka Bean and White Musk.',
        3.81,
        189,
        NULL
      ),
(
        'Milrose-9176',
        'Milrose Yves Rocher',
        'Milrose',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,aldehydic,fresh,floral,soapy',
        'MilrosebyYves Rocheris a Floral Aldehyde fragrance for women.Milrosewas launched in 1985.',
        3.97,
        120,
        NULL
      ),
(
        'Moment-de-Bonheur-13041',
        'Moment de Bonheur Yves Rocher',
        'Moment',
        'for women',
        NULL,
        'Annick Menardo',
        'Green Notes and Geranium',
        'Rose',
        'Virginia Cedar and Patchouli',
        'rose,green,fresh spicy,woody,aromatic',
        'Moment de BonheurbyYves Rocheris a Floral fragrance for women.Moment de Bonheurwas launched in 2011. The nose behind this fragrance is Annick Menardo. Top notes are Green Notes and Geranium; middle note is Rose; base notes are Virginia Cedar and Patchouli.',
        3.53,
        3,
        NULL
      ),
(
        'Moment-de-Bonheur-L-Eau-23334',
        'Moment de Bonheur L''Eau Yves Rocher',
        'Moment',
        'for women',
        NULL,
        'Annick Menardo',
        'Apple',
        'Rose',
        'Virginia Cedar',
        'fruity,fresh,rose,green,woody',
        'Moment de Bonheur L''EaubyYves Rocheris a Floral Fruity fragrance for women.Moment de Bonheur L''Eauwas launched in 2014. The nose behind this fragrance is Annick Menardo. Top note is Apple; middle note is Rose; base note is Virginia Cedar.',
        3.71,
        883,
        NULL
      ),
(
        'Muguet-des-Bois-40551',
        'Muguet des Bois Yves Rocher',
        'Muguet',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,fresh,green,soapy',
        'Muguet des BoisbyYves Rocheris a fragrance for women and men.Muguet des Boiswas launched in 1998.',
        4,
        40,
        NULL
      ),
(
        'My-Green-Summer-55803',
        'My Green Summer Yves Rocher',
        'My',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,green,fresh spicy',
        'My Green SummerbyYves Rocheris a Citrus Aromatic fragrance for women and men.My Green Summerwas launched in 2019.',
        3.7,
        113,
        NULL
      ),
(
        'My-Kiwi-Kiss-67140',
        'My Kiwi Kiss Yves Rocher',
        'My',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,warm spicy,fresh',
        'My Kiwi KissbyYves Rocheris a Citrus fragrance for women and men.My Kiwi Kisswas launched in 2021.',
        3.66,
        103,
        NULL
      ),
(
        'My-Shiny-Vanilla-76585',
        'My Shiny Vanilla Yves Rocher',
        'My',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,woody,balsamic,warm spicy',
        'My Shiny VanillabyYves Rocheris a Amber Vanilla fragrance for women. This is a new fragrance.My Shiny Vanillawas launched in 2022.',
        3.93,
        147,
        NULL
      ),
(
        'My-Vanilla-Garden-70190',
        'My Vanilla Garden Yves Rocher',
        'My',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,citrus,sweet,fruity,powdery',
        'My Vanilla GardenbyYves Rocheris a Floral Fruity Gourmand fragrance for women and men.My Vanilla Gardenwas launched in 2021.',
        3.8,
        195,
        NULL
      ),
(
        'Nature-7901',
        'Nature Yves Rocher',
        'Nature',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,green,floral,mossy,fresh',
        'NaturebyYves Rocheris a Floral Green fragrance for women.Naturewas launched in 1993.',
        3.74,
        877,
        NULL
      ),
(
        'Nature-Millenaire-9831',
        'Nature Millenaire Yves Rocher',
        'Nature',
        'for women',
        NULL,
        'Olivier Cresp',
        NULL,
        NULL,
        NULL,
        'woody,amber,powdery,warm spicy,iris',
        'Nature MillenairebyYves Rocheris a Amber Woody fragrance for women.Nature Millenairewas launched in 2000. The nose behind this fragrance is Olivier Cresp.',
        4.35,
        847,
        NULL
      ),
(
        'Nature-Millenaire-pour-Homme-4364',
        'Nature Millenaire pour Homme Yves Rocher',
        'Nature',
        'for men',
        NULL,
        'Christophe Raynaud',
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,aromatic,cinnamon,woody',
        'Nature Millenaire pour HommebyYves Rocheris a Woody Spicy fragrance for men.Nature Millenaire pour Hommewas launched in 2000. The nose behind this fragrance is Christophe Raynaud.',
        4.34,
        107,
        NULL
      ),
(
        'Naturelle-3116',
        'Naturelle Yves Rocher',
        'Naturelle',
        'for women',
        NULL,
        NULL,
        'Lemon, Green Apple, Bergamot and Tagetes',
        'Peach Blossom and Jasmine',
        'Cedar, Musk and Amber',
        'citrus,aromatic,fruity,fresh spicy,fresh',
        'NaturellebyYves Rocheris a Floral Green fragrance for women.Naturellewas launched in 2008. Top notes are Lemon, Green Apple, Bergamot and Tagetes; middle notes are Peach Blossom and Jasmine; base notes are Cedar, Musk and Amber.',
        3.68,
        3,
        NULL
      ),
(
        'Naturelle-Osmanthus-30157',
        'Naturelle Osmanthus Yves Rocher',
        'Naturelle',
        'for women',
        NULL,
        'Michel Girard',
        'Lemon',
        'Osmanthus and Jasmine',
        'Cedar',
        'floral,citrus,fruity,white floral,woody',
        'Naturelle OsmanthusbyYves Rocheris a Floral fragrance for women.Naturelle Osmanthuswas launched in 2015. The nose behind this fragrance is Michel Girard. Top note is Lemon; middle notes are Osmanthus and Jasmine; base note is Cedar.',
        3.66,
        831,
        NULL
      ),
(
        'No-1-40833',
        'No. 1 Yves Rocher',
        'No.',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,amber,green',
        'No. 1byYves Rocheris a Floral Green fragrance for women.No. 1was launched during the 1970''s.',
        1,
        1,
        NULL
      ),
(
        'Nuit-d-Orchidee-5511',
        'Nuit d''Orchidee Yves Rocher',
        'Nuit',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,sweet,powdery,lactonic',
        'Nuit d''OrchideebyYves Rocheris a Floral fragrance for women.Nuit d''Orchideewas launched in 1990.',
        4.15,
        576,
        NULL
      ),
(
        'Nuit-Vanille-51854',
        'Nuit Vanille Yves Rocher',
        'Nuit',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Orange Blossom, Rose and Jasmine',
        'Vanilla, Caramel, Cedar and Cloves',
        'vanilla,caramel,sweet,woody,powdery',
        'Nuit VanillebyYves Rocheris a Amber Vanilla fragrance for women.Nuit Vanillewas launched in 2018. Top note is Bergamot; middle notes are Orange Blossom, Rose and Jasmine; base notes are Vanilla, Caramel, Cedar and Cloves.',
        3.99,
        354,
        NULL
      ),
(
        'Orchidee-4918',
        'Orchidee Yves Rocher',
        'Orchidee',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fresh spicy,vanilla,green,warm spicy',
        'OrchideebyYves Rocheris a Floral fragrance for women.Orchideewas launched in 1988.',
        3.98,
        647,
        NULL
      ),
(
        'Philtre-Ensorcelant-15659',
        'Philtre Ensorcelant Yves Rocher',
        'Philtre',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet',
        'Philtre EnsorcelantbyYves Rocheris a Aromatic Fruity fragrance for women.Philtre Ensorcelantwas launched in 2006.',
        4.12,
        16,
        NULL
      ),
(
        'Pivoine-9175',
        'Pivoine Yves Rocher',
        'Pivoine',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fresh,rose',
        'PivoinebyYves Rocheris a Floral fragrance for women.Pivoinewas launched in 1993.',
        3.86,
        615,
        NULL
      ),
(
        'Pomme-d-Api-15674',
        'Pomme d''Api Yves Rocher',
        'Pomme',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,green',
        'Pomme d''ApibyYves Rocheris a Aromatic Fruity fragrance for women.Pomme d''Apiwas launched in 1990.',
        3.71,
        145,
        NULL
      ),
(
        'Pomme-de-Reinette-Mon-Eau-Fraiche-15284',
        'Pomme de Reinette Mon Eau Fraiche Yves Rocher',
        'Pomme',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,fresh,green',
        'Pomme de Reinette Mon Eau FraichebyYves Rocheris a Floral Fruity fragrance for women.Pomme de Reinette Mon Eau Fraichewas launched in 2000.',
        3.9,
        80,
        NULL
      ),
(
        'Pop-Exotic-37193',
        'Pop Exotic Yves Rocher',
        'Pop',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,tropical,floral',
        'Pop ExoticbyYves Rocheris a Floral Fruity fragrance for women.Pop Exoticwas launched in 2016.',
        3.46,
        132,
        NULL
      ),
(
        'Retropical-18182',
        'Retropical Yves Rocher',
        'Retropical',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sand,fresh spicy',
        'RetropicalbyYves Rocheris a Floral Fruity fragrance for women.Retropicalwas launched in 2013.',
        3.58,
        332,
        NULL
      ),
(
        'Rose-Ispahan-8856',
        'Rose Ispahan Yves Rocher',
        'Rose',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,rose,warm spicy,powdery,amber',
        'Rose IspahanbyYves Rocheris a Amber Floral fragrance for women.Rose Ispahanwas launched in 1996.',
        4.27,
        493,
        NULL
      ),
(
        'Salsa-14788',
        'Salsa Yves Rocher',
        'Salsa',
        'for women',
        NULL,
        NULL,
        'Litchi and Fig',
        'Freesia, Jasmine and Neroli',
        'Sandalwood, Beeswax, Vanilla and Musk',
        'fruity,woody,floral,white floral,powdery',
        'SalsabyYves Rocheris a Floral Fruity fragrance for women.Salsawas launched in 2001. Top notes are Litchi and Fig; middle notes are Freesia, Jasmine and Neroli; base notes are Sandalwood, Beeswax, Vanilla and Musk.',
        3.77,
        66,
        NULL
      ),
(
        'Samarkande-10170',
        'Samarkande Yves Rocher',
        'Samarkande',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,woody,aromatic,warm spicy,lavender',
        'SamarkandebyYves Rocheris a Aromatic fragrance for men.Samarkandewas launched in 1990.',
        4.32,
        139,
        NULL
      ),
(
        'Shafali-Fleur-Rare-8858',
        'Shafali Fleur Rare Yves Rocher',
        'Shafali',
        'for women',
        NULL,
        NULL,
        'Floral Notes and Citruses',
        'White Flowers and Jasmine',
        'Resin and Vanille',
        'white floral,amber,floral,vanilla,balsamic',
        'Shafali Fleur RarebyYves Rocheris a Amber Floral fragrance for women.Shafali Fleur Rarewas launched in 1996. Top notes are Floral Notes and Citruses; middle notes are White Flowers and Jasmine; base notes are Resin and Vanille.',
        4.05,
        782,
        NULL
      ),
(
        'Tel-Quel-10515',
        'Tel Quel Yves Rocher',
        'Tel',
        'for men',
        NULL,
        NULL,
        'Tea and Neroli',
        'Nutmeg and Coriander',
        'Amber, Vanille, Sandalwood and Virginia Cedar',
        'woody,fresh spicy,powdery,vanilla,amber',
        'Tel QuelbyYves Rocheris a Aromatic Spicy fragrance for men.Tel Quelwas launched in 1995. Top notes are Tea and Neroli; middle notes are Nutmeg and Coriander; base notes are Amber, Vanille, Sandalwood and Virginia Cedar.',
        4.24,
        70,
        NULL
      ),
(
        'Temps-Frais-33163',
        'Temps Frais Yves Rocher',
        'Temps',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,camphor,fresh spicy,citrus',
        'Temps FraisbyYves Rocheris a fragrance for women and men.',
        4.09,
        11,
        NULL
      ),
(
        'Tradition-Eau-de-Cologne-Naturelle-33164',
        'Tradition Eau de Cologne Naturelle Yves Rocher',
        'Tradition',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus',
        'Tradition Eau de Cologne NaturellebyYves Rocheris a Citrus fragrance for women and men.',
        2.5,
        2,
        NULL
      ),
(
        'Transat-9457',
        'Transat Yves Rocher',
        'Transat',
        'for men',
        NULL,
        NULL,
        'Rosemary',
        'Sea water',
        'Woodsy Notes and Amber',
        'aromatic,woody,marine,fresh spicy,salty',
        'TransatbyYves Rocheris a Aromatic Aquatic fragrance for men.Transatwas launched in 2005. Top note is Rosemary; middle note is Sea water; base notes are Woodsy Notes and Amber.',
        3.8,
        261,
        NULL
      );
