
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        '1960-16740',
        '1960 Bogner',
        '1960',
        'for men',
        NULL,
        NULL,
        'Lime, Mandarin Orange and Mint',
        'Nutmeg, Cardamom and Lavender',
        'Amber, Moss, Vanilla and Cedar',
        'citrus,fresh spicy,aromatic,green,warm spicy',
        '1960byBogneris a Amber fragrance for men.1960was launched in 2012. Top notes are Lime, Mandarin Orange and Mint; middle notes are Nutmeg, Cardamom and Lavender; base notes are Amber, Moss, Vanilla and Cedar.',
        4.2,
        5,
        NULL
      ),
(
        '2012-16741',
        '2012 Bogner',
        '2012',
        'for men',
        NULL,
        NULL,
        'Ginger, Mandarin Orange and Cardamon',
        'Violet, Plum and Rose',
        'Leather, Vetiver, Pine Tree and Moss',
        'warm spicy,woody,aromatic,violet,earthy',
        '2012byBogneris a Chypre fragrance for men.2012was launched in 2012. Top notes are Ginger, Mandarin Orange and Cardamon; middle notes are Violet, Plum and Rose; base notes are Leather, Vetiver, Pine Tree and Moss.',
        4,
        4,
        NULL
      ),
(
        'Beautiful-Blossoms-68739',
        'Beautiful Blossoms Bodycology',
        'Beautiful',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,fresh',
        'Beautiful BlossomsbyBodycologyis a Floral fragrance for women.Beautiful Blossomswas launched in 2013.',
        4.11,
        18,
        NULL
      ),
(
        'Cherry-Blossom-68737',
        'Cherry Blossom Bodycology',
        'Cherry',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,fresh,woody,sweet',
        'Cherry BlossombyBodycologyis a Floral fragrance for women.Cherry Blossomwas launched in 2013.',
        3.83,
        59,
        NULL
      ),
(
        'Coconut-Hibiscus-68738',
        'Coconut Hibiscus Bodycology',
        'Coconut',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'coconut,floral,sweet,lactonic,tropical',
        'Coconut HibiscusbyBodycologyis a Aromatic Fruity fragrance for women.Coconut Hibiscuswas launched in 2013.',
        4.22,
        87,
        NULL
      ),
(
        'Cozy-Fireside-S-more-71257',
        'Cozy Fireside S''more Bodycology',
        'Cozy',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,powdery,warm spicy,chocolate,woody',
        'Cozy Fireside S''morebyBodycologyis a Amber fragrance for women and men.Cozy Fireside S''morewas launched in 2020.',
        4.32,
        134,
        NULL
      ),
(
        'Cucumber-Melon-68745',
        'Cucumber Melon Bodycology',
        'Cucumber',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,fresh,fruity',
        'Cucumber MelonbyBodycologyis a Aromatic Green fragrance for women.Cucumber Melonwas launched in 2013.',
        4.02,
        41,
        NULL
      ),
(
        'Dark-Cherry-Orchid-68741',
        'Dark Cherry Orchid Bodycology',
        'Dark',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,floral,fruity,cherry,powdery',
        'Dark Cherry OrchidbyBodycologyis a Floral Fruity fragrance for women.Dark Cherry Orchidwas launched in 2013.',
        3.75,
        40,
        NULL
      ),
(
        'Irresistibly-Lovely-71163',
        'Irresistibly Lovely Bodycology',
        'Irresistibly',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,floral,fresh,rose',
        'Irresistibly LovelybyBodycologyis a Floral Fruity fragrance for women.Irresistibly Lovelywas launched in 2013.',
        2.5,
        2,
        NULL
      ),
(
        'Island-Beach-Paradise-68744',
        'Island Beach Paradise Bodycology',
        'Island',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tropical,coconut,marine,fruity,aromatic',
        'Island Beach ParadisebyBodycologyis a Aromatic Aquatic fragrance for women.Island Beach Paradisewas launched in 2013.',
        4,
        3,
        NULL
      ),
(
        'Picnic-Breeze-68742',
        'Picnic Breeze Bodycology',
        'Picnic',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,floral,fruity,sweet,fresh',
        'Picnic BreezebyBodycologyis a Citrus Aromatic fragrance for women.Picnic Breezewas launched in 2013.',
        4.12,
        16,
        NULL
      ),
(
        'Pink-Vanilla-Wish-68746',
        'Pink Vanilla Wish Bodycology',
        'Pink',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,vanilla,fresh,almond,rose',
        'Pink Vanilla WishbyBodycologyis a Amber Vanilla fragrance for women.Pink Vanilla Wishwas launched in 2013.',
        4.29,
        129,
        NULL
      ),
(
        'Pure-White-Gardenia-68740',
        'Pure White Gardenia Bodycology',
        'Pure',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,green,floral,lactonic,animalic',
        'Pure White GardeniabyBodycologyis a Floral fragrance for women.Pure White Gardeniawas launched in 2013.',
        4.03,
        63,
        NULL
      ),
(
        'Sweet-Love-68743',
        'Sweet Love Bodycology',
        'Sweet',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,floral,vanilla,lactonic',
        'Sweet LovebyBodycologyis a Floral fragrance for women.Sweet Lovewas launched in 2013.',
        4.23,
        83,
        NULL
      ),
(
        'Toasted-Sugar-68272',
        'Toasted Sugar Bodycology',
        'Toasted',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,sweet,vanilla,powdery,animalic',
        'Toasted SugarbyBodycologyis a Amber Vanilla fragrance for women.Toasted Sugarwas launched in 2013.',
        3.83,
        47,
        NULL
      ),
(
        'Twilight-Mist-68747',
        'Twilight Mist Bodycology',
        'Twilight',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,coconut,sweet,powdery,lactonic',
        'Twilight MistbyBodycologyis a Floral Fruity fragrance for women.Twilight Mistwas launched in 2013.',
        4.38,
        16,
        NULL
      ),
(
        'Watermelon-Splash-68274',
        'Watermelon Splash Bodycology',
        'Watermelon',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,fruity,sweet',
        'Watermelon SplashbyBodycologyis a Aromatic Fruity fragrance for women.Watermelon Splashwas launched in 2013.',
        4,
        32,
        NULL
      ),
(
        'Whipped-Vanilla-68273',
        'Whipped Vanilla Bodycology',
        'Whipped',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,floral,powdery',
        'Whipped VanillabyBodycologyis a Floral fragrance for women.Whipped Vanillawas launched in 2013.',
        3.88,
        84,
        NULL
      ),
(
        'Wild-Poppy-95217',
        'Wild Poppy Bodycology',
        'Wild',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'soft spicy,fruity,sour,fresh,sweet',
        'Wild PoppybyBodycologyis a Floral Fruity fragrance for women. This is a new fragrance.Wild Poppywas launched in 2024.',
        3.5,
        4,
        NULL
      ),
(
        'Big-Dreams-95212',
        'Big Dreams Bodycology',
        'Big',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,vanilla,floral,powdery,sweet',
        'Big DreamsbyBodycologyis a Floral fragrance for women. This is a new fragrance.Big Dreamswas launched in 2024.',
        4,
        1,
        NULL
      ),
(
        'Blue-Denim-95213',
        'Blue Denim Bodycology',
        'Blue',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,citrus,violet,powdery',
        'Blue DenimbyBodycologyis a Floral Fruity fragrance for women. This is a new fragrance.Blue Denimwas launched in 2024.',
        3.6,
        5,
        NULL
      ),
(
        'Floating-On-A-Cloud-95218',
        'Floating On A Cloud Bodycology',
        'Floating',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,white floral,fruity,sweet,powdery',
        'Floating On A CloudbyBodycologyis a Floral fragrance for women. This is a new fragrance.Floating On A Cloudwas launched in 2024.',
        3.43,
        7,
        NULL
      ),
(
        'Fresh-Raspberries-95214',
        'Fresh Raspberries Bodycology',
        'Fresh',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,citrus,vanilla',
        'Fresh RaspberriesbyBodycologyis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Fresh Raspberrieswas launched in 2024.',
        4.17,
        6,
        NULL
      ),
(
        'Hawaiian-Beach-95215',
        'Hawaiian Beach Bodycology',
        'Hawaiian',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'coconut,white floral,sweet,woody,lactonic',
        'Hawaiian BeachbyBodycologyis a Aromatic Fruity fragrance for women. This is a new fragrance.Hawaiian Beachwas launched in 2024.',
        3.5,
        4,
        NULL
      ),
(
        'Sun-Kissed-Lemons-95216',
        'Sun Kissed Lemons Bodycology',
        'Sun',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,aromatic',
        'Sun Kissed LemonsbyBodycologyis a Citrus fragrance for women. This is a new fragrance.Sun Kissed Lemonswas launched in 2024.',
        3.71,
        7,
        NULL
      ),
(
        'Cozy-Gingerbread-58603',
        'Cozy Gingerbread Body Fantasies',
        'Cozy',
        'for women',
        NULL,
        NULL,
        'Gingerbread',
        'Spices',
        'Vanilla',
        'vanilla,warm spicy,sweet,cinnamon,powdery',
        'Cozy GingerbreadbyBody Fantasiesis a Amber Vanilla fragrance for women.Cozy Gingerbreadwas launched in 2018. Top note is Gingerbread; middle note is Spices; base note is Vanilla.',
        4.57,
        7,
        NULL
      ),
(
        'Cupcake-Swirl-83149',
        'Cupcake Swirl Body Fantasies',
        'Cupcake',
        'for women',
        NULL,
        NULL,
        'Buttercream, Ginger and Clove',
        'Cookie and Butter',
        'Vanilla, Coconut and Musk',
        'sweet,vanilla,coconut,lactonic,warm spicy',
        'Cupcake SwirlbyBody Fantasiesis a Floral Fruity Gourmand fragrance for women. Top notes are Buttercream, Ginger and Clove; middle notes are Cookie and Butter; base notes are Vanilla, Coconut and Musk.',
        4.07,
        72,
        NULL
      ),
(
        'Hearts-Daisies-58608',
        'Hearts & Daisies Body Fantasies',
        'Hearts',
        'for women',
        NULL,
        NULL,
        'Apple, Watery Notes, Melon and Pear',
        'Lily-of-the-Valley and Pink Peony',
        'Woodsy Notes and Vanilla',
        'fresh,aquatic,fruity,white floral,green',
        'Hearts & DaisiesbyBody Fantasiesis a Floral Fruity fragrance for women.Hearts & Daisieswas launched in 2018. Top notes are Apple, Watery Notes, Melon and Pear; middle notes are Lily-of-the-Valley and Pink Peony; base notes are Woodsy Notes and Vanilla.',
        4.04,
        24,
        NULL
      ),
(
        'Magical-Escape-58605',
        'Magical Escape Body Fantasies',
        'Magical',
        'for women',
        NULL,
        NULL,
        'Blackberry, Pear and Tangerine',
        'Plum Blossom, Coconut and Mango',
        'Whipped Cream, Brown sugar, Vanilla and Amber',
        'sweet,fruity,vanilla,floral,fresh',
        'Magical EscapebyBody Fantasiesis a Floral Fruity fragrance for women.Magical Escapewas launched in 2018. Top notes are Blackberry, Pear and Tangerine; middle notes are Plum Blossom, Coconut and Mango; base notes are Whipped Cream, Brown sugar, Vanilla and Amber.',
        3.57,
        7,
        NULL
      ),
(
        'Night-Musk-58609',
        'Night Musk Body Fantasies',
        'Night',
        'for women',
        NULL,
        NULL,
        'Black Orchid and Apple',
        'Violet and Heliotrope',
        'Velvet, Praline, Musk and Sandalowood',
        'powdery,sweet,floral,musky,violet',
        'Night MuskbyBody Fantasiesis a Floral Fruity fragrance for women.Night Muskwas launched in 2018. Top notes are Black Orchid and Apple; middle notes are Violet and Heliotrope; base notes are Velvet, Praline, Musk and Sandalowood.',
        4.23,
        22,
        NULL
      ),
(
        'Pink-Vanilla-Kiss-58612',
        'Pink Vanilla Kiss Body Fantasies',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Wild Berries, Coconut, Coconut Milk and Grapefruit',
        'Vanilla, Peony and Tiare Flower',
        'Tahitian Vanilla, Caramel, Musk and Sandalowood',
        'vanilla,sweet,fruity,caramel,woody',
        'Pink Vanilla KissbyBody Fantasiesis a Floral Fruity fragrance for women.Pink Vanilla Kisswas launched in 2018. Top notes are Wild Berries, Coconut, Coconut Milk and Grapefruit; middle notes are Vanilla, Peony and Tiare Flower; base notes are Tahitian Vanilla, Caramel, Musk and Sandalowood.',
        4.1,
        199,
        NULL
      ),
(
        'Pure-Sunshine-58606',
        'Pure Sunshine Body Fantasies',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Carambola (Star Fruit), Solar Notes, Citruses and Nectarine',
        'Whipped Cream, Strawberry, Jasmine and Honeysuckle',
        'Musk, Vanilla Bean and Amber',
        'fruity,citrus,sweet,fresh,tropical',
        'Pure SunshinebyBody Fantasiesis a Floral Aldehyde fragrance for women.Pure Sunshinewas launched in 2018. Top notes are Carambola (Star Fruit), Solar Notes, Citruses and Nectarine; middle notes are Whipped Cream, Strawberry, Jasmine and Honeysuckle; base notes are Musk, Vanilla Bean and Amber.',
        3.58,
        26,
        NULL
      ),
(
        'Romance-Dreams-58611',
        'Romance & Dreams Body Fantasies',
        'Romance',
        'for women',
        NULL,
        NULL,
        'Blackcurrant Syrup, Bergamot, Passionfruit and Peach',
        'Pink Peony, Rose Petals, Magnolia and Freesia',
        'Musk, Vanilla Orchid, Cedar and Amber',
        'floral,rose,fresh,musky,citrus',
        'Romance & DreamsbyBody Fantasiesis a Floral Fruity fragrance for women.Romance & Dreamswas launched in 2018. Top notes are Blackcurrant Syrup, Bergamot, Passionfruit and Peach; middle notes are Pink Peony, Rose Petals, Magnolia and Freesia; base notes are Musk, Vanilla Orchid, Cedar and Amber.',
        3.99,
        70,
        NULL
      ),
(
        'Secret-Crush-58610',
        'Secret Crush Body Fantasies',
        'Secret',
        'for women',
        NULL,
        NULL,
        'Red Fruits, Pineapple and Cassis',
        'Green Apple, Star Jasmine and Lily-of-the-Valley',
        'Sugar, Musk and Cashmeran',
        'fruity,sweet,fresh,musky,white floral',
        'Secret CrushbyBody Fantasiesis a Floral Fruity fragrance for women.Secret Crushwas launched in 2018. Top notes are Red Fruits, Pineapple and Cassis; middle notes are Green Apple, Star Jasmine and Lily-of-the-Valley; base notes are Sugar, Musk and Cashmeran.',
        4.16,
        37,
        NULL
      ),
(
        'Signature-Dreamy-Pomegranate-92764',
        'Signature Dreamy Pomegranate Body Fantasies',
        'Signature',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,woody,amber,fresh spicy,sour',
        'Signature Dreamy PomegranatebyBody Fantasiesis a Floral Fruity fragrance for women. This is a new fragrance.Signature Dreamy Pomegranatewas launched in 2024.',
        4.33,
        3,
        NULL
      ),
(
        'Sugar-Peach-58604',
        'Sugar Peach Body Fantasies',
        'Sugar',
        'for women',
        NULL,
        NULL,
        'Peach, Pear, Raspberry and Honeysuckle',
        'Mango, Jasmine and Orange Blossom',
        'Sugar Cane, Musk and Coconut',
        'fruity,sweet,white floral,tropical',
        'Sugar PeachbyBody Fantasiesis a Floral Fruity fragrance for women.Sugar Peachwas launched in 2018. Top notes are Peach, Pear, Raspberry and Honeysuckle; middle notes are Mango, Jasmine and Orange Blossom; base notes are Sugar Cane, Musk and Coconut.',
        4.05,
        37,
        NULL
      ),
(
        'Sweet-Sunrise-58607',
        'Sweet Sunrise Body Fantasies',
        'Sweet',
        'for women',
        NULL,
        NULL,
        'Peach, Mandarin Orange and Wild Berries',
        'Gardenia, Coconut, Jasmine and Orchid',
        'Caramel, Whipped Cream, Vanilla, Amber and Woodsy Notes',
        'sweet,fruity,vanilla,citrus,white floral',
        'Sweet SunrisebyBody Fantasiesis a Floral Fruity fragrance for women.Sweet Sunrisewas launched in 2018. Top notes are Peach, Mandarin Orange and Wild Berries; middle notes are Gardenia, Coconut, Jasmine and Orchid; base notes are Caramel, Whipped Cream, Vanilla, Amber and Woodsy Notes.',
        4.14,
        155,
        NULL
      ),
(
        '01-Sweet-Wood-Desire-35621',
        '01 Sweet Wood Desire Body Conjure',
        '01',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,amber,aromatic,oud',
        '01 Sweet Wood DesirebyBody Conjureis a Amber Woody fragrance for women and men.01 Sweet Wood Desirewas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        3.75,
        4,
        NULL
      ),
(
        '02-Like-His-Body-35622',
        '02 Like His Body Body Conjure',
        '02',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,earthy,patchouli,mossy',
        '02 Like His BodybyBody Conjureis a Aromatic fragrance for women and men.02 Like His Bodywas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        4,
        1,
        NULL
      ),
(
        '03-Arbol-de-la-Noche-35656',
        '03 Arbol de la Noche Body Conjure',
        '03',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'woody,amber,white floral,balsamic,warm spicy',
        '03 Arbol de la NochebyBody Conjureis a Floral Woody Musk fragrance for women and men.03 Arbol de la Nochewas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        4.33,
        3,
        NULL
      ),
(
        '04-Hidden-Promises-35657',
        '04 Hidden Promises Body Conjure',
        '04',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'citrus,vanilla,fruity,powdery,aromatic',
        '04 Hidden PromisesbyBody Conjureis a Chypre Floral fragrance for women and men.04 Hidden Promiseswas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        5,
        1,
        NULL
      ),
(
        '05-And-Tonight-35658',
        '05 And Tonight Body Conjure',
        '05',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,woody,herbal',
        '05 And TonightbyBody Conjureis a Woody Aromatic fragrance for women and men.05 And Tonightwas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        NULL,
        NULL,
        NULL
      ),
(
        '06-Tempt-Fate-35661',
        '06 Tempt Fate Body Conjure',
        '06',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'citrus,woody,aromatic,white floral,earthy',
        '06 Tempt FatebyBody Conjureis a Amber Fougere fragrance for women and men.06 Tempt Fatewas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        4,
        4,
        NULL
      ),
(
        '07-Dirty-Sinner-35660',
        '07 Dirty Sinner Body Conjure',
        '07',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,woody,white floral,green',
        '07 Dirty SinnerbyBody Conjureis a Chypre Floral fragrance for women and men.07 Dirty Sinnerwas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        3.33,
        6,
        NULL
      ),
(
        '08-Still-Smell-Her-35662',
        '08 Still Smell Her Body Conjure',
        '08',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'citrus,lavender,vanilla,aromatic,sweet',
        '08 Still Smell HerbyBody Conjureis a Floral fragrance for women and men.08 Still Smell Herwas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        4.5,
        2,
        NULL
      ),
(
        '09-Clear-Space-35663',
        '09 Clear Space Body Conjure',
        '09',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,warm spicy,aromatic,woody',
        '09 Clear SpacebyBody Conjureis a Aromatic Fruity fragrance for women and men.09 Clear Spacewas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        5,
        1,
        NULL
      ),
(
        '10-Not-for-Long-35664',
        '10 Not for Long Body Conjure',
        '10',
        'for women and men',
        NULL,
        'Greg Wharton',
        NULL,
        NULL,
        NULL,
        'aromatic,woody,amber,fresh spicy,lavender',
        '10 Not for LongbyBody Conjureis a Amber Fougere fragrance for women and men.10 Not for Longwas launched in 2016. The nose behind this fragrance is Greg Wharton.',
        5,
        1,
        NULL
      ),
(
        'B-Blumarine-54619',
        'B. Blumarine Blumarine',
        'B.',
        'for women',
        NULL,
        'Marie Salamagne',
        'Pink Grapefruit, Pear and Cassis',
        'Jasmine, May Rose and Passion Flower',
        'Musk, Cedar and Sandalwood',
        'fruity,citrus,musky,white floral,rose',
        'B. BlumarinebyBlumarineis a Floral Fruity fragrance for women.B. Blumarinewas launched in 2019. The nose behind this fragrance is Marie Salamagne. Top notes are Pink Grapefruit, Pear and Cassis; middle notes are Jasmine, May Rose and Passion Flower; base notes are Musk, Cedar and Sandalwood.',
        3.48,
        95,
        NULL
      ),
(
        'Blu-2805',
        'Blu Blumarine',
        'Blu',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,powdery,warm spicy,woody,white floral',
        'BlubyBlumarineis a Floral fragrance for women.Bluwas launched in 1996.',
        3.98,
        80,
        NULL
      ),
(
        'Blumarine-13554',
        'Blumarine Blumarine',
        'Blumarine',
        'for women',
        NULL,
        'IFF',
        'Aldehydes, Hyacinth, Bergamot, Mandarin Orange, Green Notes and Amalfi Lemon',
        'Rose, Lily-of-the-Valley, Jasmine, Ylang-Ylang and Orris Root',
        'Sandalwood, Musk, Virginia Cedar, Vetiver, Tonka Bean and Amber',
        'citrus,woody,green,floral,rose',
        'BlumarinebyBlumarineis a Floral Aldehyde fragrance for women.Blumarinewas launched in 1988. The nose behind this fragrance is IFF. Top notes are Aldehydes, Hyacinth, Bergamot, Mandarin Orange, Green Notes and Amalfi Lemon; middle notes are Rose, Lily-of-the-Valley, Jasmine, Ylang-Ylang and Orris Root; base notes are Sandalwood, Musk, Virginia Cedar, Vetiver, Tonka Bean and Amber.',
        3.86,
        35,
        NULL
      ),
(
        'Blumarine-II-139',
        'Blumarine II Blumarine',
        'Blumarine',
        'for women',
        NULL,
        NULL,
        'Lotus, Brazilian Rosewood and Ivy',
        'Orchid, Ylang-Ylang and Rose',
        'Sandalwood, White Musk, Labdanum and Cedar',
        'woody,floral,sweet,powdery,musky',
        'Blumarine IIbyBlumarineis a Floral Aldehyde fragrance for women.Blumarine IIwas launched in 2000. Top notes are Lotus, Brazilian Rosewood and Ivy; middle notes are Orchid, Ylang-Ylang and Rose; base notes are Sandalwood, White Musk, Labdanum and Cedar.',
        3.9,
        80,
        NULL
      ),
(
        'Dange-Rose-46173',
        'Dange-Rose Blumarine',
        'Dange-Rose',
        'for women',
        NULL,
        'Pierre-Constantin Guéros',
        'Basil, Pink Pepper and Pear',
        'Rose, Freesia and Magnolia',
        'Cashmere Wood, Patchouli and White Amber',
        'rose,floral,fresh spicy,woody,aromatic',
        'Dange-RosebyBlumarineis a Floral Woody Musk fragrance for women.Dange-Rosewas launched in 2017. The nose behind this fragrance is Pierre-Constantin Guéros. Top notes are Basil, Pink Pepper and Pear; middle notes are Rose, Freesia and Magnolia; base notes are Cashmere Wood, Patchouli and White Amber.',
        3.85,
        567,
        NULL
      ),
(
        'Let-You-Love-Me-59824',
        'Let You Love Me Blumarine',
        'Let',
        'for women',
        NULL,
        'Véronique Nyberg',
        'Lavender, Black Pepper and Ylang-Ylang',
        'Orange Blossom, Geranium and Mugane',
        'Vanilla, Patchouli and Lorenox',
        'fresh spicy,lavender,vanilla,woody,sweet',
        'Let You Love MebyBlumarineis a Amber fragrance for women.Let You Love Mewas launched in 2020. Let You Love Me was created by Veronique Nyberg and Violaine Collas. Top notes are Lavender, Black Pepper and Ylang-Ylang; middle notes are Orange Blossom, Geranium and Mugane; base notes are Vanilla, Patchouli and Lorenox.',
        3.84,
        289,
        NULL
      ),
(
        'Vintage-140',
        'Vintage Blumarine',
        'Vintage',
        'for women',
        NULL,
        NULL,
        'Bergamot, Lemon and Peach',
        'Peony, Water Lily, Rose, Lily and Jasmine',
        'Sandalwood, Musk, Amber and Iris',
        'citrus,floral,fresh,powdery,rose',
        'VintagebyBlumarineis a Floral Fruity fragrance for women.Vintagewas launched in 2004. Top notes are Bergamot, Lemon and Peach; middle notes are Peony, Water Lily, Rose, Lily and Jasmine; base notes are Sandalwood, Musk, Amber and Iris.',
        3.54,
        26,
        NULL
      ),
(
        'Bellissima-6796',
        'Bellissima Blumarine',
        'Bellissima',
        'for women',
        NULL,
        'Celine Barel',
        'Orange, Grapefruit, Water Notes and Ginger',
        'Peony and Passion Flower',
        'Vanilla, Cashmere Wood, Sandalwood and Musk',
        'citrus,floral,fresh,woody,musky',
        'BellissimabyBlumarineis a Floral Woody Musk fragrance for women.Bellissimawas launched in 2009. Bellissima was created by Sophie Labbe and Celine Barel. Top notes are Orange, Grapefruit, Water Notes and Ginger; middle notes are Peony and Passion Flower; base notes are Vanilla, Cashmere Wood, Sandalwood and Musk.',
        3.74,
        567,
        NULL
      ),
(
        'Bellissima-Acqua-di-Primavera-11849',
        'Bellissima Acqua di Primavera Blumarine',
        'Bellissima',
        'for women',
        NULL,
        'Sophie Labbé',
        'Raspberry and Bergamot',
        'Violet, Pansy and Passion Flower',
        'Musk, Woodsy Notes and Sandalwood',
        'powdery,floral,sweet,woody,fruity',
        'Bellissima Acqua di PrimaverabyBlumarineis a Floral Fruity fragrance for women.Bellissima Acqua di Primaverawas launched in 2011. The nose behind this fragrance is Sophie Labbe. Top notes are Raspberry and Bergamot; middle notes are Violet, Pansy and Passion Flower; base notes are Musk, Woodsy Notes and Sandalwood.',
        3.83,
        355,
        NULL
      ),
(
        'Bellissima-Parfum-Intense-10006',
        'Bellissima Parfum Intense Blumarine',
        'Bellissima',
        'for women',
        NULL,
        'Sophie Labbé',
        'Ginger, Orange and Grapefruit',
        'Passion Flower, Peony and Jasmine',
        'Cashmere Wood, Heliotrope, Orchid, Musk and Sandalwood',
        'floral,powdery,woody,musky,citrus',
        'Bellissima Parfum IntensebyBlumarineis a Amber Floral fragrance for women.Bellissima Parfum Intensewas launched in 2010. The nose behind this fragrance is Sophie Labbe. Top notes are Ginger, Orange and Grapefruit; middle notes are Passion Flower, Peony and Jasmine; base notes are Cashmere Wood, Heliotrope, Orchid, Musk and Sandalwood.',
        3.94,
        511,
        NULL
      ),
(
        'Blugirl-Jus-de-Fleurs-12340',
        'Blugirl Jus de Fleurs Blumarine',
        'Blugirl',
        'for women',
        NULL,
        'Nathalie Lorson',
        'Guava and Bergamot',
        'African Orange Flower, Frangipani and Gardenia',
        'Vanille, Sandalwood and Musk',
        'white floral,tropical,citrus,fruity,floral',
        'Blugirl Jus de FleursbyBlumarineis a Floral Fruity fragrance for women.Blugirl Jus de Fleurswas launched in 2011. The nose behind this fragrance is Nathalie Lorson. Top notes are Guava and Bergamot; middle notes are African Orange Flower, Frangipani and Gardenia; base notes are Vanille, Sandalwood and Musk.',
        3.42,
        158,
        NULL
      ),
(
        'Blugirl-Jus-No-1-8281',
        'Blugirl Jus No.1 Blumarine',
        'Blugirl',
        'for women',
        NULL,
        'Christine Nagel',
        'Grapefruit, Amalfi Lemon, Pear, Litchi and Mandarin Orange',
        'Sea water, Champagne, Jasmine, Freesia and Magnolia',
        'Musk, Sandalwood, Vanille and Amber',
        'citrus,marine,aromatic,floral,aquatic',
        'Blugirl Jus No.1byBlumarineis a Floral fragrance for women.Blugirl Jus No.1was launched in 2010. The nose behind this fragrance is Christine Nagel. Top notes are Grapefruit, Amalfi Lemon, Pear, Litchi and Mandarin Orange; middle notes are Sea water, Champagne, Jasmine, Freesia and Magnolia; base notes are Musk, Sandalwood, Vanille and Amber.',
        3.55,
        328,
        NULL
      ),
(
        'Innamorata-14815',
        'Innamorata Blumarine',
        'Innamorata',
        'for women',
        NULL,
        'Olivier Polge',
        'Passionfruit, Mandarin Orange and Bergamot',
        'Frangipani, Magnolia, Grapefruit blossom and Ylang-Ylang',
        'Cashmere Wood, Musk and Benzoin',
        'citrus,floral,tropical,musky,sweet',
        'InnamoratabyBlumarineis a Amber Floral fragrance for women.Innamoratawas launched in 2012. Innamorata was created by Sophie Labbe and Olivier Polge. Top notes are Passionfruit, Mandarin Orange and Bergamot; middle notes are Frangipani, Magnolia, Grapefruit blossom and Ylang-Ylang; base notes are Cashmere Wood, Musk and Benzoin.',
        3.83,
        480,
        NULL
      ),
(
        'Innamorata-Lovely-Rose-17560',
        'Innamorata Lovely Rose Blumarine',
        'Innamorata',
        'for women',
        NULL,
        'Francis Kurkdjian',
        'Green Apple, Bergamot, Lemon, Raspberry and Lime',
        'Rose Petals, Freesia and Gardenia',
        'Musk, Cedar and Amber',
        'rose,citrus,floral,fruity,musky',
        'Innamorata Lovely RosebyBlumarineis a Floral Fruity fragrance for women.Innamorata Lovely Rosewas launched in 2013. Innamorata Lovely Rose was created by Francis Kurkdjian and Philippe Bousseton. Top notes are Green Apple, Bergamot, Lemon, Raspberry and Lime; middle notes are Rose Petals, Freesia and Gardenia; base notes are Musk, Cedar and Amber.',
        3.71,
        241,
        NULL
      ),
(
        'Cheers-On-The-Terrace-61391',
        'Cheers On The Terrace Blumarine',
        'Cheers',
        'for women',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Litchi, Blueberry and Grapefruit',
        'Champagne, Rose and Lily-of-the-Valley',
        'Patchouli, Musk and Cedar',
        'fruity,rose,Champagne,citrus,fresh',
        'Cheers On The TerracebyBlumarineis a Chypre Floral fragrance for women.Cheers On The Terracewas launched in 2020. Cheers On The Terrace was created by Emilie Bevierre-Coppermann and Leslie Gauthier. Top notes are Litchi, Blueberry and Grapefruit; middle notes are Champagne, Rose and Lily-of-the-Valley; base notes are Patchouli, Musk and Cedar.',
        3.42,
        40,
        NULL
      ),
(
        'Kiss-Me-On-The-Lips-61392',
        'Kiss Me On The Lips Blumarine',
        'Kiss',
        'for women',
        NULL,
        'Jordi Fernández',
        'Bergamot, Black Currant, Pink Pepper and Orange',
        'Caramel, Orris, Jasmine and Peony',
        'Vanilla, Powdery Notes, Patchouli and Musk',
        'powdery,caramel,citrus,vanilla,sweet',
        'Kiss Me On The LipsbyBlumarineis a Amber Floral fragrance for women.Kiss Me On The Lipswas launched in 2020. The nose behind this fragrance is Jórdi Fernandez. Top notes are Bergamot, Black Currant, Pink Pepper and Orange; middle notes are Caramel, Orris, Jasmine and Peony; base notes are Vanilla, Powdery Notes, Patchouli and Musk.',
        3.66,
        59,
        NULL
      ),
(
        'Mon-Bouquet-Blanc-61393',
        'Mon Bouquet Blanc Blumarine',
        'Mon',
        'for women',
        NULL,
        'Véronique Nyberg',
        'Confetti (Sugared Almonds), Aldehydes, Watery Notes, Green Notes and Citruses',
        'May Rose, Ylang-Ylang and Osmanthus',
        'Tonka Bean, Cypriol Oil or Nagarmotha and Patchouli',
        'sweet,aldehydic,fresh,yellow floral,rose',
        'Mon Bouquet BlancbyBlumarineis a Floral Aldehyde fragrance for women.Mon Bouquet Blancwas launched in 2020. The nose behind this fragrance is Veronique Nyberg. Top notes are Confetti (Sugared Almonds), Aldehydes, Watery Notes, Green Notes and Citruses; middle notes are May Rose, Ylang-Ylang and Osmanthus; base notes are Tonka Bean, Cypriol Oil or Nagarmotha and Patchouli.',
        3.95,
        88,
        NULL
      ),
(
        'Mon-Petit-Chou-73544',
        'Mon Petit Chou Blumarine',
        'Mon',
        'for women',
        NULL,
        'Jérôme di Marino',
        'Coconut, Mandarin Orange and Bergamot',
        'Freesia, Lily-of-the-Valley and Jasmine',
        'Cereals, Vanilla, Musk and Cedar',
        'vanilla,coconut,sweet,powdery,lactonic',
        'Mon Petit ChoubyBlumarineis a fragrance for women. This is a new fragrance.Mon Petit Chouwas launched in 2022. The nose behind this fragrance is Jérôme di Marino. Top notes are Coconut, Mandarin Orange and Bergamot; middle notes are Freesia, Lily-of-the-Valley and Jasmine; base notes are Cereals, Vanilla, Musk and Cedar.',
        3.8,
        80,
        NULL
      ),
(
        'Shine-Like-A-Night-73543',
        'Shine Like A Night Blumarine',
        'Shine',
        'for women',
        NULL,
        'Alex Lee',
        'Yellow Mandarin, Pink Pepper and Bergamot',
        'Frangipani, Mugane and Ginger',
        'Tonka Bean, Lorenox and Ambroxan',
        'floral,tropical,citrus,vanilla,amber',
        'Shine Like A NightbyBlumarineis a Amber Floral fragrance for women. This is a new fragrance.Shine Like A Nightwas launched in 2022. The nose behind this fragrance is Alex Lee. Top notes are Yellow Mandarin, Pink Pepper and Bergamot; middle notes are Frangipani, Mugane and Ginger; base notes are Tonka Bean, Lorenox and Ambroxan.',
        3.5,
        28,
        NULL
      ),
(
        'Anna-24030',
        'Anna Blumarine',
        'Anna',
        'for women',
        NULL,
        'Alexandra Carlin',
        'Apple, Fruity Notes and Peach',
        'Peony, Rose, Magnolia and Jasmine',
        'Musk, Vanilla, Sandalwood and Cashmere Wood',
        'fruity,floral,fresh,rose,sweet',
        'AnnabyBlumarineis a Floral fragrance for women.Annawas launched in 2014. Anna was created by Alexandra Carlin and Maurice Roucel. Top notes are Apple, Fruity Notes and Peach; middle notes are Peony, Rose, Magnolia and Jasmine; base notes are Musk, Vanilla, Sandalwood and Cashmere Wood.',
        3.81,
        428,
        NULL
      ),
(
        'Blumarine-Rosa-36591',
        'Blumarine Rosa Blumarine',
        'Blumarine',
        'for women',
        NULL,
        'Sophie Labbé',
        'Sesame, Freesia and Bergamot',
        'Tuberose, Rose Petals and White Lily',
        'Vanilla, Musk and Patchouli',
        'vanilla,white floral,tuberose,rose,powdery',
        'Blumarine RosabyBlumarineis a Amber Floral fragrance for women.Blumarine Rosawas launched in 2016. The nose behind this fragrance is Sophie Labbe. Top notes are Sesame, Freesia and Bergamot; middle notes are Tuberose, Rose Petals and White Lily; base notes are Vanilla, Musk and Patchouli.',
        3.89,
        414,
        NULL
      ),
(
        'Ninfea-30163',
        'Ninfea Blumarine',
        'Ninfea',
        'for women',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Lotus, Pepper, Gardenia and Orange',
        'Water Lily, Lavender, Orchid and Jasmine',
        'Ambergris, Sandalwood, Vanilla and Musk',
        'floral,aquatic,white floral,fresh spicy,amber',
        'NinfeabyBlumarineis a Floral fragrance for women.Ninfeawas launched in 2015. The nose behind this fragrance is Emilie Bevierre-Coppermann. Top notes are Lotus, Pepper, Gardenia and Orange; middle notes are Water Lily, Lavender, Orchid and Jasmine; base notes are Ambergris, Sandalwood, Vanilla and Musk.',
        3.62,
        294,
        NULL
      ),
(
        'Bergamot-49892',
        'Bergamot Blue Scents',
        'Bergamot',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Mandarin Orange and Cardamom',
        'Orange Blossom and Artemisia',
        'White Musk and Woody Notes',
        'citrus,white floral,aromatic',
        'BergamotbyBlue Scentsis a fragrance for women and men.Bergamotwas launched in 2016. Top notes are Lemon, Mandarin Orange and Cardamom; middle notes are Orange Blossom and Artemisia; base notes are White Musk and Woody Notes.',
        4.4,
        5,
        NULL
      ),
(
        'Bergamot-Amberwood-62044',
        'Bergamot & Amberwood Blue Scents',
        'Bergamot',
        'for men',
        NULL,
        NULL,
        'Bergamot, Grapefruit and Cardamom',
        'Cinnamon, Cloves and Labdanum',
        'Tonka Bean, Patchouli and Amberwood',
        'warm spicy,amber,citrus,woody,aromatic',
        'Bergamot & AmberwoodbyBlue Scentsis a fragrance for men.Bergamot & Amberwoodwas launched in 2020. Top notes are Bergamot, Grapefruit and Cardamom; middle notes are Cinnamon, Cloves and Labdanum; base notes are Tonka Bean, Patchouli and Amberwood.',
        4.5,
        6,
        NULL
      ),
(
        'Black-Infusion-49893',
        'Black Infusion Blue Scents',
        'Black',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Lemon and Green Tea',
        'Green Tea Flower, Jasmine, Peony and Cardamom',
        'Musk, White Cedar Extract and Guaiac Wood',
        'musky,green,woody,citrus,powdery',
        'Black InfusionbyBlue Scentsis a fragrance for women and men.Black Infusionwas launched in 2016. Top notes are Bergamot, Lemon and Green Tea; middle notes are Green Tea Flower, Jasmine, Peony and Cardamom; base notes are Musk, White Cedar Extract and Guaiac Wood.',
        4,
        1,
        NULL
      ),
(
        'Cardamom-Vanilla-62045',
        'Cardamom & Vanilla Blue Scents',
        'Cardamom',
        'for men',
        NULL,
        NULL,
        'Cinnamon, Cypress, Pepper and Lavender',
        'Cedar, Jasmine and Cardamom',
        'Tobacco, Vanilla, Incense and Resins',
        'warm spicy,woody,aromatic,amber,fresh spicy',
        'Cardamom & VanillabyBlue Scentsis a fragrance for men.Cardamom & Vanillawas launched in 2020. Top notes are Cinnamon, Cypress, Pepper and Lavender; middle notes are Cedar, Jasmine and Cardamom; base notes are Tobacco, Vanilla, Incense and Resins.',
        4.42,
        12,
        NULL
      ),
(
        'Dark-Cherry-49894',
        'Dark Cherry Blue Scents',
        'Dark',
        'for women and men',
        NULL,
        NULL,
        'Cypress, Red Currant, Raspberry and Green Notes',
        'Honey, Rose, Melon and Water Hyacinth',
        'Amber and Peach',
        'amber,fruity,sweet,honey,woody',
        'Dark CherrybyBlue Scentsis a fragrance for women and men.Dark Cherrywas launched in 2016. Top notes are Cypress, Red Currant, Raspberry and Green Notes; middle notes are Honey, Rose, Melon and Water Hyacinth; base notes are Amber and Peach.',
        4.2,
        10,
        NULL
      ),
(
        'Freesia-Osmanthus-62046',
        'Freesia & Osmanthus Blue Scents',
        'Freesia',
        'for women and men',
        NULL,
        NULL,
        'Tea Leaf and Cardamom',
        'Freesia',
        'Musk and Powdery Notes',
        'powdery,floral,musky,warm spicy,green',
        'Freesia & OsmanthusbyBlue Scentsis a fragrance for women and men.Freesia & Osmanthuswas launched in 2020. Top notes are Tea Leaf and Cardamom; middle note is Freesia; base notes are Musk and Powdery Notes.',
        4.5,
        4,
        NULL
      ),
(
        'Gardenia-49895',
        'Gardenia Blue Scents',
        'Gardenia',
        'for women and men',
        NULL,
        NULL,
        'Ylang-Ylang, Palisander Rosewood and Rose',
        'Gardenia, Tuberose and Carnation',
        'Jasmine, Orange Blossom and Musk',
        'white floral,tuberose,animalic',
        'GardeniabyBlue Scentsis a fragrance for women and men.Gardeniawas launched in 2016. Top notes are Ylang-Ylang, Palisander Rosewood and Rose; middle notes are Gardenia, Tuberose and Carnation; base notes are Jasmine, Orange Blossom and Musk.',
        4.8,
        5,
        NULL
      ),
(
        'Golden-Honey-Argan-Oil-93784',
        'Golden Honey & Argan Oil Blue Scents',
        'Golden',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Blood Orange and Freesia',
        'Honey, Jasmine and Argan',
        'Gourmand Accord, Patchouli and Musk',
        'sweet,honey,floral,white floral,citrus',
        'Golden Honey & Argan OilbyBlue Scentsis a fragrance for women and men.Golden Honey & Argan Oilwas launched in 2024. Top notes are Orange Blossom, Blood Orange and Freesia; middle notes are Honey, Jasmine and Argan; base notes are Gourmand Accord, Patchouli and Musk.',
        5,
        1,
        NULL
      ),
(
        'Iris-49896',
        'Iris Blue Scents',
        'Iris',
        'for women and men',
        NULL,
        NULL,
        'Violet, Red Currant and Raspberry',
        'Orange Blossom, Rose and Orris Root',
        'Heliotrope, Tonka Bean and Vanilla',
        'vanilla,powdery,sweet,fruity,rose',
        'IrisbyBlue Scentsis a fragrance for women and men.Iriswas launched in 2016. Top notes are Violet, Red Currant and Raspberry; middle notes are Orange Blossom, Rose and Orris Root; base notes are Heliotrope, Tonka Bean and Vanilla.',
        4.25,
        4,
        NULL
      ),
(
        'Juicy-Lemon-62047',
        'Juicy Lemon Blue Scents',
        'Juicy',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Basil and Mandarin Orange',
        'Blood Orange and Grapefruit',
        'Sandalwood, Musk and Black Currant',
        'citrus,fresh spicy,aromatic,woody,powdery',
        'Juicy LemonbyBlue Scentsis a fragrance for women and men.Juicy Lemonwas launched in 2020. Top notes are Lemon, Basil and Mandarin Orange; middle notes are Blood Orange and Grapefruit; base notes are Sandalwood, Musk and Black Currant.',
        5,
        3,
        NULL
      ),
(
        'Mandarin-49908',
        'Mandarin Blue Scents',
        'Mandarin',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, Bergamot and Green Tea',
        'Green Tea Flower, Jasmine and Peony',
        'Cedar and Musk',
        'citrus,green,floral,white floral,fresh',
        'MandarinbyBlue Scentsis a fragrance for women and men.Mandarinwas launched in 2016. Top notes are Tangerine, Bergamot and Green Tea; middle notes are Green Tea Flower, Jasmine and Peony; base notes are Cedar and Musk.',
        5,
        2,
        NULL
      ),
(
        'Neroli-49897',
        'Neroli Blue Scents',
        'Neroli',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Neroli and Lavender',
        'Musk',
        'citrus,fresh spicy,white floral,aromatic,lavender',
        'NerolibyBlue Scentsis a fragrance for women and men.Neroliwas launched in 2016. Top notes are Bergamot and Mandarin Orange; middle notes are Neroli and Lavender; base note is Musk.',
        4,
        2,
        NULL
      ),
(
        'Night-Jasmine-49898',
        'Night Jasmine Blue Scents',
        'Night',
        'for women and men',
        NULL,
        NULL,
        'Ylang-Ylang, Citruses and Lemon',
        'Cloves, Jasmine and Orris Root',
        'Cedar, Patchouli and Amber',
        'woody,warm spicy,white floral,patchouli,citrus',
        'Night JasminebyBlue Scentsis a fragrance for women and men.Night Jasminewas launched in 2016. Top notes are Ylang-Ylang, Citruses and Lemon; middle notes are Cloves, Jasmine and Orris Root; base notes are Cedar, Patchouli and Amber.',
        4.32,
        34,
        NULL
      ),
(
        'Ocean-Bliss-49899',
        'Ocean Bliss Blue Scents',
        'Ocean',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Green Notes',
        'Water Lily, Rose, Violet and Carnation',
        'Water Hyacinth, Melon, Musk and Vanilla',
        'floral,aquatic,fresh,ozonic,green',
        'Ocean BlissbyBlue Scentsis a fragrance for women and men.Ocean Blisswas launched in 2016. Top notes are Bergamot and Green Notes; middle notes are Water Lily, Rose, Violet and Carnation; base notes are Water Hyacinth, Melon, Musk and Vanilla.',
        3.67,
        3,
        NULL
      ),
(
        'Peony-49900',
        'Peony Blue Scents',
        'Peony',
        'for women and men',
        NULL,
        NULL,
        'White Flowers, Peony and Grapefruit',
        'Peony, Violet and Rose',
        'Peony, Musk and Red Fruits',
        'white floral,floral,fresh,musky,powdery',
        'PeonybyBlue Scentsis a fragrance for women and men.Peonywas launched in 2016. Top notes are White Flowers, Peony and Grapefruit; middle notes are Peony, Violet and Rose; base notes are Peony, Musk and Red Fruits.',
        4.33,
        6,
        NULL
      ),
(
        'Pink-Infusion-62048',
        'Pink Infusion Blue Scents',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Lemon, Black Currant, Rose and Violet Leaf',
        'Peony, Plum and Lily',
        'Vanilla, Musk and Amberwood',
        'fruity,floral,rose,fresh,sweet',
        'Pink InfusionbyBlue Scentsis a fragrance for women.Pink Infusionwas launched in 2020. Top notes are Lemon, Black Currant, Rose and Violet Leaf; middle notes are Peony, Plum and Lily; base notes are Vanilla, Musk and Amberwood.',
        3,
        2,
        NULL
      ),
(
        'Pomegranate-49901',
        'Pomegranate Blue Scents',
        'Pomegranate',
        'for women and men',
        NULL,
        NULL,
        'Citrus Blossom, Passionfruit and Cassis',
        'Pomegranate, Peony and Water Lily',
        'Sandalwood, Musk and Jasmine',
        'white floral,floral,woody,fresh,fruity',
        'PomegranatebyBlue Scentsis a fragrance for women and men.Pomegranatewas launched in 2016. Top notes are Citrus Blossom, Passionfruit and Cassis; middle notes are Pomegranate, Peony and Water Lily; base notes are Sandalwood, Musk and Jasmine.',
        4.44,
        9,
        NULL
      ),
(
        'Pomegranate-Violet-62050',
        'Pomegranate & Violet Blue Scents',
        'Pomegranate',
        'for women and men',
        NULL,
        NULL,
        'Rose Petals and Spices',
        'Raspberry, Red Fruits and Peony',
        'Violet, White Musk and Vanilla',
        'powdery,violet,fruity,sweet,musky',
        'Pomegranate & VioletbyBlue Scentsis a fragrance for women and men.Pomegranate & Violetwas launched in 2020. Top notes are Rose Petals and Spices; middle notes are Raspberry, Red Fruits and Peony; base notes are Violet, White Musk and Vanilla.',
        4,
        3,
        NULL
      ),
(
        'Pure-49905',
        'Pure Blue Scents',
        'Pure',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Orris Root, Incense, Cedar and Jasmine',
        'White Musk, Heliotrope, Patchouli and Vetiver',
        'powdery,musky,iris,woody,earthy',
        'PurebyBlue Scentsis a fragrance for women and men.Purewas launched in 2016. Top note is Mandarin Orange; middle notes are Orris Root, Incense, Cedar and Jasmine; base notes are White Musk, Heliotrope, Patchouli and Vetiver.',
        3.67,
        9,
        NULL
      ),
(
        'Pure-Elixir-65737',
        'Pure Elixir Blue Scents',
        'Pure',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Iris and Peony',
        'Lily-of-the-Valley, Tea and Rose',
        'Musk, Woody Notes and Sandalwood',
        'fresh,white floral,green,woody,floral',
        'Pure ElixirbyBlue Scentsis a fragrance for women and men. Top notes are Lemon, Iris and Peony; middle notes are Lily-of-the-Valley, Tea and Rose; base notes are Musk, Woody Notes and Sandalwood.',
        3.67,
        3,
        NULL
      ),
(
        'Salt-Sun-62051',
        'Salt & Sun Blue Scents',
        'Salt',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes, Orange and Lavender',
        'Lily-of-the-Valley, Freesia, Rose and Orangewood',
        'Seaweed, Oakmoss, Amber and Solar Notes',
        'marine,aromatic,floral,white floral,aquatic',
        'Salt & SunbyBlue Scentsis a fragrance for women and men.Salt & Sunwas launched in 2020. Top notes are Sea Notes, Orange and Lavender; middle notes are Lily-of-the-Valley, Freesia, Rose and Orangewood; base notes are Seaweed, Oakmoss, Amber and Solar Notes.',
        4.42,
        12,
        NULL
      ),
(
        'Violet-49907',
        'Violet Blue Scents',
        'Violet',
        'for women and men',
        NULL,
        NULL,
        'Iris and Orange Blossom',
        'Violet and Raspberry',
        'Vanilla and Musk',
        'powdery,violet,vanilla,iris,sweet',
        'VioletbyBlue Scentsis a fragrance for women and men.Violetwas launched in 2016. Top notes are Iris and Orange Blossom; middle notes are Violet and Raspberry; base notes are Vanilla and Musk.',
        4.25,
        4,
        NULL
      ),
(
        'White-Infusion-49906',
        'White Infusion Blue Scents',
        'White',
        'for women and men',
        NULL,
        NULL,
        'Citruses, Bergamot and Mandarin Orange',
        'Tea, Rose and Orris Root',
        'Musk and Powdery Notes',
        'citrus,powdery,rose,musky,iris',
        'White InfusionbyBlue Scentsis a fragrance for women and men.White Infusionwas launched in 2016. Top notes are Citruses, Bergamot and Mandarin Orange; middle notes are Tea, Rose and Orris Root; base notes are Musk and Powdery Notes.',
        4.2,
        5,
        NULL
      ),
(
        '0-11738',
        '0 Blood Concept',
        '0',
        'for women and men',
        NULL,
        NULL,
        'Raspberry and Caraway',
        'Cyperus esculentus and Rose',
        'Leather, Metallic notes, Birch and Virginia Cedar',
        'leather,metallic,fruity,smoky,woody',
        '0byBlood Conceptis a Leather fragrance for women and men.0was launched in 2011. Top notes are Raspberry and Caraway; middle notes are Cyperus esculentus and Rose; base notes are Leather, Metallic notes, Birch and Virginia Cedar.',
        3.81,
        160,
        NULL
      ),
(
        'A-11735',
        'A Blood Concept',
        'A',
        'for women and men',
        NULL,
        NULL,
        'Green Notes',
        'Tomato Leaf and Basil',
        'Metallic notes and Star Anise',
        'green,aromatic,fresh spicy,metallic,anis',
        'AbyBlood Conceptis a Aromatic Green fragrance for women and men.Awas launched in 2011. Top note is Green Notes; middle notes are Tomato Leaf and Basil; base notes are Metallic notes and Star Anise.',
        3.51,
        120,
        NULL
      ),
(
        'AB-11737',
        'AB Blood Concept',
        'AB',
        'for women and men',
        NULL,
        NULL,
        'Aluminum and Aldehydes',
        'Slate, Pebbles and Water Notes',
        'Metallic notes and Virginia Cedar',
        'metallic,mineral,fresh,aldehydic,aquatic',
        'ABbyBlood Conceptis a Aromatic Aquatic fragrance for women and men.ABwas launched in 2011. Top notes are Aluminum and Aldehydes; middle notes are Slate, Pebbles and Water Notes; base notes are Metallic notes and Virginia Cedar.',
        3.53,
        186,
        NULL
      ),
(
        'B-11736',
        'B Blood Concept',
        'B',
        'for women and men',
        NULL,
        NULL,
        'Cherry and Red Apple',
        'Pepper, Pomegranate, Artemisia and Tea',
        'Metallic notes, Patchouli and Teak Wood',
        'woody,metallic,cherry,fresh spicy,fruity',
        'BbyBlood Conceptis a Woody Aromatic fragrance for women and men.Bwas launched in 2011. Top notes are Cherry and Red Apple; middle notes are Pepper, Pomegranate, Artemisia and Tea; base notes are Metallic notes, Patchouli and Teak Wood.',
        3.97,
        110,
        NULL
      ),
(
        'XX-Metro-Velvet-41036',
        'XX Metro Velvet Blood Concept',
        'XX',
        'for women',
        NULL,
        NULL,
        'Saffron and Orange',
        'Rose, Immortelle, Incense and Lily-of-the-Valley',
        'Patchouli, Guaiac Wood, Styrax and Vanilla',
        'warm spicy,woody,amber,rose,patchouli',
        'XX Metro VelvetbyBlood Conceptis a Woody Chypre fragrance for women.XX Metro Velvetwas launched in 2016. Top notes are Saffron and Orange; middle notes are Rose, Immortelle, Incense and Lily-of-the-Valley; base notes are Patchouli, Guaiac Wood, Styrax and Vanilla.',
        3.88,
        8,
        NULL
      ),
(
        'XY-Nude-Wood-41037',
        'XY Nude Wood Blood Concept',
        'XY',
        'for men',
        NULL,
        NULL,
        'Cedar Needles, Cinnamon and Coconut Blossom',
        'Leather, Tonka Bean and Lily-of-the-Valley',
        'Sandalwood, Cedar, Benzoin, Vetiver, Labdanum and Cypriol Oil or Nagarmotha',
        'woody,amber,warm spicy,coconut,vanilla',
        'XY Nude WoodbyBlood Conceptis a Amber Woody fragrance for men.XY Nude Woodwas launched in 2016. Top notes are Cedar Needles, Cinnamon and Coconut Blossom; middle notes are Leather, Tonka Bean and Lily-of-the-Valley; base notes are Sandalwood, Cedar, Benzoin, Vetiver, Labdanum and Cypriol Oil or Nagarmotha.',
        4,
        10,
        NULL
      ),
(
        'Black-Collection-0-18090',
        'Black Collection 0 Blood Concept',
        'Black',
        'for women and men',
        NULL,
        NULL,
        'Blood Orange and Yuzu',
        'cannabis and Carrot Seeds',
        'Leather, dark woodsy notes and Amber',
        'leather,woody,cannabis,animalic,smoky',
        'Black Collection 0byBlood Conceptis a Leather fragrance for women and men.Black Collection 0was launched in 2013. Top notes are Blood Orange and Yuzu; middle notes are cannabis and Carrot Seeds; base notes are Leather, dark woodsy notes and Amber.',
        3.83,
        82,
        NULL
      ),
(
        'Black-Collection-A-18091',
        'Black Collection A Blood Concept',
        'Black',
        'for women and men',
        NULL,
        NULL,
        'Coffee and Ginger',
        'Angelica',
        'Amber, Sandalwood and Benzoin',
        'amber,warm spicy,coffee,powdery,woody',
        'Black Collection AbyBlood Conceptis a Amber Spicy fragrance for women and men.Black Collection Awas launched in 2013. Top notes are Coffee and Ginger; middle note is Angelica; base notes are Amber, Sandalwood and Benzoin.',
        3.97,
        64,
        NULL
      );
