
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Impulse-86288',
        'Impulse The Dua Brand',
        'Impulse',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,powdery,soft spicy,aromatic,woody',
        'ImpulsebyThe Dua Brandis a Amber Spicy fragrance for men.Impulsewas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'In-The-Dark-86289',
        'In The Dark The Dua Brand',
        'In',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,musky,amber,warm spicy',
        'In The DarkbyThe Dua Brandis a Woody Floral Musk fragrance for women and men.In The Darkwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        'In-Your-Feels-86290',
        'In Your Feels The Dua Brand',
        'In',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,green,leather,ozonic,fruity',
        'In Your FeelsbyThe Dua Brandis a Woody Aromatic fragrance for women and men.In Your Feelswas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Incense-of-the-Noble-86291',
        'Incense of the Noble The Dua Brand',
        'Incense',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,powdery,fresh spicy,musky',
        'Incense of the NoblebyThe Dua Brandis a Woody Floral Musk fragrance for women and men.Incense of the Noblewas launched in 2022.',
        3,
        2,
        NULL
      ),
(
        'Inception-86292',
        'Inception The Dua Brand',
        'Inception',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,vanilla,woody,earthy,amber',
        'InceptionbyThe Dua Brandis a Chypre fragrance for men.Inceptionwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Indochina-Forest-86293',
        'Indochina Forest The Dua Brand',
        'Indochina',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,powdery,warm spicy,fresh spicy',
        'Indochina ForestbyThe Dua Brandis a Woody Floral Musk fragrance for women and men.Indochina Forestwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        'Inertia-86294',
        'Inertia The Dua Brand',
        'Inertia',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,powdery,woody,rose,musky',
        'InertiabyThe Dua Brandis a Floral fragrance for women and men.Inertiawas launched in 2021.',
        4,
        1,
        NULL
      ),
(
        'Infatuated-86295',
        'Infatuated The Dua Brand',
        'Infatuated',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,citrus,caramel,floral,patchouli',
        'InfatuatedbyThe Dua Brandis a Floral fragrance for women and men.Infatuatedwas launched in 2022.',
        4,
        4,
        NULL
      ),
(
        'Infused-Iris-86296',
        'Infused Iris The Dua Brand',
        'Infused',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,amber,white floral,green',
        'Infused IrisbyThe Dua Brandis a Floral fragrance for women and men.Infused Iriswas launched in 2020.',
        4.5,
        2,
        NULL
      ),
(
        'Infused-Wood-86297',
        'Infused Wood The Dua Brand',
        'Infused',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,lavender,patchouli,oud',
        'Infused WoodbyThe Dua Brandis a Woody Aromatic fragrance for women and men.Infused Woodwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Inimitable-Personality-86298',
        'Inimitable Personality The Dua Brand',
        'Inimitable',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,woody,warm spicy,aromatic,rose',
        'Inimitable PersonalitybyThe Dua Brandis a Amber fragrance for women.Inimitable Personalitywas launched in 2020.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intense-Black-Oud-86299',
        'Intense Black Oud The Dua Brand',
        'Intense',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aldehydic,leather,mossy,oud,sweet',
        'Intense Black OudbyThe Dua Brandis a Leather fragrance for women and men.Intense Black Oudwas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intense-Eau-Homme-86300',
        'Intense Eau Homme The Dua Brand',
        'Intense',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,iris,aromatic,powdery,woody',
        'Intense Eau HommebyThe Dua Brandis a Woody Aromatic fragrance for men.Intense Eau Hommewas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intense-Homme-86301',
        'Intense Homme The Dua Brand',
        'Intense',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,aromatic,earthy,vanilla',
        'Intense HommebyThe Dua Brandis a Woody Floral Musk fragrance for men.Intense Hommewas launched in 2020.',
        4.83,
        6,
        NULL
      ),
(
        'Intense-Homme-Attar-86302',
        'Intense Homme Attar The Dua Brand',
        'Intense',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,citrus,rose,oud',
        'Intense Homme AttarbyThe Dua Brandis a Leather fragrance for men.Intense Homme Attarwas launched in 2020.',
        4.8,
        5,
        NULL
      ),
(
        'Intense-Homme-Sport-86303',
        'Intense Homme Sport The Dua Brand',
        'Intense',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,citrus,fresh spicy,warm spicy',
        'Intense Homme SportbyThe Dua Brandis a Floral fragrance for men.Intense Homme Sportwas launched in 2020.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intense-Leather-86304',
        'Intense Leather The Dua Brand',
        'Intense',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,yellow floral,sweet,musky',
        'Intense LeatherbyThe Dua Brandis a Leather fragrance for men.Intense Leatherwas launched in 2020.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intense-Play-With-Dua-86305',
        'Intense Play With Dua The Dua Brand',
        'Intense',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,aromatic,amber,warm spicy',
        'Intense Play With DuabyThe Dua Brandis a Amber Fougere fragrance for men.Intense Play With Duawas launched in 2021.',
        3.5,
        4,
        NULL
      ),
(
        'Intensely-Liberated-86306',
        'Intensely Liberated The Dua Brand',
        'Intensely',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,aromatic,vanilla,amber',
        'Intensely LiberatedbyThe Dua Brandis a Amber Fougere fragrance for women.Intensely Liberatedwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intensified-Vanillac-Ruby-86307',
        'Intensified Vanillac Ruby The Dua Brand',
        'Intensified',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,vanilla,almond,patchouli',
        'Intensified Vanillac RubybyThe Dua Brandis a Amber fragrance for women and men.Intensified Vanillac Rubywas launched in 2022.',
        4.67,
        3,
        NULL
      ),
(
        'Intensified-Vanillac-Ruby-Neroli-86308',
        'Intensified Vanillac Ruby: Neroli The Dua Brand',
        'Intensified',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,citrus,woody,white floral,lavender',
        'Intensified Vanillac Ruby: NerolibyThe Dua Brandis a Floral Fruity fragrance for women and men.Intensified Vanillac Ruby: Neroliwas launched in 2022.',
        4,
        1,
        NULL
      ),
(
        'Into-The-Woods-86309',
        'Into The Woods The Dua Brand',
        'Into',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,lavender,musky,warm spicy,woody',
        'Into The WoodsbyThe Dua Brandis a Citrus fragrance for men.Into The Woodswas launched in 2022.',
        4.33,
        3,
        NULL
      ),
(
        'Intoxicating-Tabac-86310',
        'Intoxicating Tabac The Dua Brand',
        'Intoxicating',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,patchouli,tobacco,warm spicy,woody',
        'Intoxicating TabacbyThe Dua Brandis a Amber Woody fragrance for women and men.Intoxicating Tabacwas launched in 2023.',
        3,
        2,
        NULL
      ),
(
        'Intuition-Vision-86311',
        'Intuition Vision The Dua Brand',
        'Intuition',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,warm spicy,marine,woody',
        'Intuition VisionbyThe Dua Brandis a Aromatic Aquatic fragrance for men.Intuition Visionwas launched in 2021.',
        4,
        1,
        NULL
      ),
(
        'Invasion-of-the-Barbers-86312',
        'Invasion of the Barbers The Dua Brand',
        'Invasion',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,warm spicy,lavender,fresh spicy,citrus',
        'Invasion of the BarbersbyThe Dua Brandis a Amber Fougere fragrance for men.Invasion of the Barberswas launched in 2018.',
        3.44,
        9,
        NULL
      ),
(
        'Invisibility-86783',
        'Invisibility The Dua Brand',
        'Invisibility',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,musky,white floral,floral',
        'InvisibilitybyThe Dua Brandis a Floral fragrance for women and men.Invisibilitywas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Iris-Cafe-86313',
        'Iris Cafe The Dua Brand',
        'Iris',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,powdery,amber,aromatic,citrus',
        'Iris CafebyThe Dua Brandis a Amber Floral fragrance for women and men.Iris Cafewas launched in 2021.',
        3.8,
        5,
        NULL
      ),
(
        'Italian-Bouquet-86314',
        'Italian Bouquet The Dua Brand',
        'Italian',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,floral,sweet,amber',
        'Italian BouquetbyThe Dua Brandis a Floral Fruity fragrance for women and men.Italian Bouquetwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Italian-Decorum-86315',
        'Italian Decorum The Dua Brand',
        'Italian',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,green,fresh spicy,earthy',
        'Italian DecorumbyThe Dua Brandis a Woody Aromatic fragrance for women and men.Italian Decorumwas launched in 2017.',
        5,
        2,
        NULL
      ),
(
        'Italian-Water-II-86316',
        'Italian Water II The Dua Brand',
        'Italian',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,aromatic,fresh spicy,warm spicy',
        'Italian Water IIbyThe Dua Brandis a Woody Aromatic fragrance for men.Italian Water IIwas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Italian-Waters-V-86317',
        'Italian Waters V The Dua Brand',
        'Italian',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,woody,fresh spicy,warm spicy',
        'Italian Waters VbyThe Dua Brandis a Woody Aromatic fragrance for women and men.Italian Waters Vwas launched in 2020.',
        2.5,
        2,
        NULL
      ),
(
        'Japanese-Agar-Byakudan-86318',
        'Japanese Agar Byakudan The Dua Brand',
        'Japanese',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,woody,powdery,warm spicy,balsamic',
        'Japanese Agar ByakudanbyThe Dua Brandis a Woody fragrance for women and men.Japanese Agar Byakudanwas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Japanese-Blossom-86319',
        'Japanese Blossom The Dua Brand',
        'Japanese',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,floral,musky,white floral,soft spicy',
        'Japanese BlossombyThe Dua Brandis a Floral fragrance for women and men.Japanese Blossomwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Jazz-86320',
        'Jazz The Dua Brand',
        'Jazz',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tobacco,sweet,rum,aromatic,woody',
        'JazzbyThe Dua Brandis a Amber fragrance for women and men.Jazzwas launched in 2023.',
        5,
        2,
        NULL
      ),
(
        'Jump-Kiss-86321',
        'Jump & Kiss The Dua Brand',
        'Jump',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,leather,animalic',
        'Jump & KissbyThe Dua Brandis a Leather fragrance for women and men.Jump & Kisswas launched in 2022.',
        5,
        1,
        NULL
      ),
(
        'Killer-Instinct-86322',
        'Killer Instinct The Dua Brand',
        'Killer',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy,amber,citrus',
        'Killer InstinctbyThe Dua Brandis a Amber fragrance for men.Killer Instinctwas launched in 2020.',
        4.67,
        6,
        NULL
      ),
(
        'King-of-Judea-Attar-86821',
        'King of Judea Attar The Dua Brand',
        'King',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,vanilla,tobacco,warm spicy,cinnamon',
        'King of Judea AttarbyThe Dua Brandis a Woody Spicy fragrance for men.King of Judea Attarwas launched in 2020.',
        4.71,
        7,
        NULL
      ),
(
        'King-of-Oudhania-86323',
        'King of Oudhania The Dua Brand',
        'King',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,aromatic,powdery,green',
        'King of OudhaniabyThe Dua Brandis a Citrus fragrance for men.King of Oudhaniawas launched in 2019.',
        4.33,
        3,
        NULL
      ),
(
        'King-s-Precious-Iris-Oud-86324',
        'King''s Precious Iris & Oud The Dua Brand',
        'King''s',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,fresh spicy,aromatic,powdery',
        'King''s Precious Iris & OudbyThe Dua Brandis a Amber Woody fragrance for men.King''s Precious Iris & Oudwas launched in 2020.',
        5,
        1,
        NULL
      ),
(
        'King-s-Vetiver-86325',
        'King''s Vetiver The Dua Brand',
        'King''s',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,amber,citrus,anis',
        'King''s VetiverbyThe Dua Brandis a Amber Woody fragrance for women and men.King''s Vetiverwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Kingdom-of-Oman-86326',
        'Kingdom of Oman The Dua Brand',
        'Kingdom',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy,aromatic,citrus',
        'Kingdom of OmanbyThe Dua Brandis a Floral fragrance for women and men.Kingdom of Omanwas launched in 2020.',
        1,
        1,
        NULL
      ),
(
        'Kologne-Of-Protection-86327',
        'Kologne Of Protection The Dua Brand',
        'Kologne',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,citrus,fresh spicy',
        'Kologne Of ProtectionbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.Kologne Of Protectionwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'L-eau-D-Dua-Pour-Homme-86363',
        'L’eau D’Dua Pour Homme The Dua Brand',
        'L’eau',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,woody,fresh spicy,floral',
        'L’eau D’Dua Pour HommebyThe Dua Brandis a Woody Aquatic fragrance for men.L’eau D’Dua Pour Hommewas launched in 2021.',
        3,
        1,
        NULL
      ),
(
        'L-Nuit-D-Dua-86364',
        'L’Nuit D’Dua The Dua Brand',
        'L’Nuit',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,citrus,fresh spicy,aromatic',
        'L’Nuit D’DuabyThe Dua Brandis a Woody Spicy fragrance for men.L’Nuit D’Duawas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'La-Spezia-Lime-86329',
        'La Spezia Lime The Dua Brand',
        'La',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,warm spicy,fresh spicy,metallic,leather',
        'La Spezia LimebyThe Dua Brandis a Citrus fragrance for women and men.La Spezia Limewas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Lady-Elixir-86330',
        'Lady Elixir The Dua Brand',
        'Lady',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,woody,fruity,sweet,white floral',
        'Lady ElixirbyThe Dua Brandis a Floral fragrance for women.Lady Elixirwas launched in 2019.',
        4.75,
        4,
        NULL
      ),
(
        'Land-Of-Aqua-86331',
        'Land Of Aqua The Dua Brand',
        'Land',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,white floral,citrus,vanilla,sweet',
        'Land Of AquabyThe Dua Brandis a Amber fragrance for women and men.Land Of Aquawas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Late-Night-Venom-86332',
        'Late Night Venom The Dua Brand',
        'Late',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,vanilla,rose,patchouli',
        'Late Night VenombyThe Dua Brandis a Woody Chypre fragrance for women.Late Night Venomwas launched in 2021.',
        4,
        5,
        NULL
      ),
(
        'Latin-Tabacum-86333',
        'Latin Tabacum The Dua Brand',
        'Latin',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,citrus,floral,amber',
        'Latin TabacumbyThe Dua Brandis a Leather fragrance for women and men.Latin Tabacumwas launched in 2020.',
        5,
        1,
        NULL
      ),
(
        'Latin-Tabacum-Cuba-Edition-86334',
        'Latin Tabacum: Cuba Edition The Dua Brand',
        'Latin',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,floral,amber,vanilla',
        'Latin Tabacum: Cuba EditionbyThe Dua Brandis a Woody Aromatic fragrance for women and men.Latin Tabacum: Cuba Editionwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Le-Musc-4-1-86335',
        'Le Musc 4.1 The Dua Brand',
        'Le',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,musky,amber,powdery',
        'Le Musc 4.1byThe Dua Brandis a Woody Chypre fragrance for women and men.Le Musc 4.1was launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Le-Puy-En-Velay-4-86336',
        'Le Puy En Velay 4 The Dua Brand',
        'Le',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,warm spicy,amber,woody,musky',
        'Le Puy En Velay 4byThe Dua Brandis a fragrance for women and men.Le Puy En Velay 4was launched in 2020.',
        4.5,
        2,
        NULL
      ),
(
        'Le-Puy-En-Velay-6-86337',
        'Le Puy En Velay 6 The Dua Brand',
        'Le',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,amber,woody,fresh spicy,warm spicy',
        'Le Puy En Velay 6byThe Dua Brandis a Woody Spicy fragrance for women and men.Le Puy En Velay 6was launched in 2020.',
        NULL,
        NULL,
        NULL
      ),
(
        'Le-Puy-En-Velay-16-86338',
        'Le-Puy-En-Velay 16 The Dua Brand',
        'Le-Puy-En-Velay',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,green,powdery,white floral,aromatic',
        'Le-Puy-En-Velay 16byThe Dua Brandis a Floral Fruity fragrance for women and men.Le-Puy-En-Velay 16was launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Le-Puy-En-Velay-Rarity-86339',
        'Le-Puy-En-Velay Rarity The Dua Brand',
        'Le-Puy-En-Velay',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,earthy,aromatic,powdery',
        'Le-Puy-En-Velay RaritybyThe Dua Brandis a Chypre fragrance for women and men.Le-Puy-En-Velay Raritywas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Leather-for-the-Ages-86340',
        'Leather for the Ages The Dua Brand',
        'Leather',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,fruity,oud,warm spicy,smoky',
        'Leather for the AgesbyThe Dua Brandis a Leather fragrance for men.Leather for the Ageswas launched in 2020.',
        5,
        3,
        NULL
      ),
(
        'Leather-of-Istanbul-86341',
        'Leather of Istanbul The Dua Brand',
        'Leather',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,sweet,leather,animalic,smoky',
        'Leather of IstanbulbyThe Dua Brandis a Leather fragrance for women and men.Leather of Istanbulwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Leather-Supremacy-86342',
        'Leather Supremacy The Dua Brand',
        'Leather',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,vanilla,amber,sweet,earthy',
        'Leather SupremacybyThe Dua Brandis a Leather fragrance for women and men.Leather Supremacywas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Leather-Vetiver-Harmony-86343',
        'Leather Vetiver Harmony The Dua Brand',
        'Leather',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,warm spicy,woody,earthy,animalic',
        'Leather Vetiver HarmonybyThe Dua Brandis a Woody Aromatic fragrance for men.Leather Vetiver Harmonywas launched in 2023.',
        3,
        2,
        NULL
      ),
(
        'Leave-It-To-Chance-86344',
        'Leave It To Chance The Dua Brand',
        'Leave',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'earthy,patchouli,citrus,musky,woody',
        'Leave It To ChancebyThe Dua Brandis a Chypre Floral fragrance for women.Leave It To Chancewas launched in 2022.',
        5,
        2,
        NULL
      ),
(
        'Leedys-86345',
        'Leedys The Dua Brand',
        'Leedys',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,citrus,fresh spicy,warm spicy',
        'LeedysbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.Leedyswas launched in 2019.',
        5,
        4,
        NULL
      ),
(
        'Legacy-86346',
        'Legacy The Dua Brand',
        'Legacy',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,floral,oud,white floral',
        'LegacybyThe Dua Brandis a Amber Floral fragrance for women and men.Legacywas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Legendary-86347',
        'Legendary The Dua Brand',
        'Legendary',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,citrus,fresh spicy,tobacco',
        'LegendarybyThe Dua Brandis a Amber Fougere fragrance for women and men.Legendarywas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Legendary-Knight-86348',
        'Legendary Knight The Dua Brand',
        'Legendary',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,warm spicy,powdery,woody',
        'Legendary KnightbyThe Dua Brandis a Citrus Aromatic fragrance for men.Legendary Knightwas launched in 2020.',
        4.67,
        3,
        NULL
      ),
(
        'Let-s-Burn-Calories-86350',
        'Let’s Burn Calories The Dua Brand',
        'Let’s',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lactonic,sweet,vanilla,green,white floral',
        'Let’s Burn CaloriesbyThe Dua Brandis a Amber Vanilla fragrance for women and men.Let’s Burn Calorieswas launched in 2021.',
        4,
        2,
        NULL
      ),
(
        'Lethal-86349',
        'Lethal The Dua Brand',
        'Lethal',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,green,citrus,powdery',
        'LethalbyThe Dua Brandis a Leather fragrance for men.Lethalwas launched in 2020.',
        NULL,
        NULL,
        NULL
      ),
(
        'Liberty-Town-86351',
        'Liberty Town The Dua Brand',
        'Liberty',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,amber,citrus,woody',
        'Liberty TownbyThe Dua Brandis a Amber fragrance for women and men.Liberty Townwas launched in 2022.',
        4,
        1,
        NULL
      ),
(
        'Libra-Rendezvous-86352',
        'Libra Rendezvous The Dua Brand',
        'Libra',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,soft spicy,woody,powdery',
        'Libra RendezvousbyThe Dua Brandis a Woody Spicy fragrance for women and men.Libra Rendezvouswas launched in 2020.',
        3,
        1,
        NULL
      ),
(
        'Life-In-Cairo-86353',
        'Life In Cairo The Dua Brand',
        'Life',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,patchouli,vanilla,rose',
        'Life In CairobyThe Dua Brandis a Amber Floral fragrance for women and men.Life In Cairowas launched in 2022.',
        5,
        1,
        NULL
      ),
(
        'Lion-of-Dua-86822',
        'Lion of Dua The Dua Brand',
        'Lion',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,citrus,powdery,musky',
        'Lion of DuabyThe Dua Brandis a Leather fragrance for women and men.Lion of Duawas launched in 2021.',
        5,
        5,
        NULL
      ),
(
        'Little-Sweetheart-86784',
        'Little Sweetheart The Dua Brand',
        'Little',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fresh,green,fruity,sweet',
        'Little SweetheartbyThe Dua Brandis a Floral fragrance for women.Little Sweetheartwas launched in 2023.',
        4.5,
        2,
        NULL
      ),
(
        'Living-The-Dream-86354',
        'Living The Dream The Dua Brand',
        'Living',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,fresh spicy,rose,herbal',
        'Living The DreambyThe Dua Brandis a Woody Aromatic fragrance for men.Living The Dreamwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        'Lone-Star-86355',
        'Lone Star The Dua Brand',
        'Lone',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,citrus,fruity,fresh,aromatic',
        'Lone StarbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.Lone Starwas launched in 2018.',
        3,
        1,
        NULL
      ),
(
        'Lost-in-Translation-86356',
        'Lost in Translation The Dua Brand',
        'Lost',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,vanilla,fresh spicy,oud,warm spicy',
        'Lost in TranslationbyThe Dua Brandis a Woody fragrance for men.Lost in Translationwas launched in 2019.',
        NULL,
        NULL,
        NULL
      ),
(
        'Love-From-Afar-86357',
        'Love From Afar The Dua Brand',
        'Love',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,green,amber,coconut,musky',
        'Love From AfarbyThe Dua Brandis a Floral fragrance for women and men.Love From Afarwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Love-It-For-Him-86358',
        'Love It For Him The Dua Brand',
        'Love',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,fresh spicy,aromatic,powdery',
        'Love It For HimbyThe Dua Brandis a Amber fragrance for men.Love It For Himwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Luminous-Charm-86359',
        'Luminous Charm The Dua Brand',
        'Luminous',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,amber,white floral,fresh spicy',
        'Luminous CharmbyThe Dua Brandis a Amber Floral fragrance for women and men.Luminous Charmwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Luminous-Heat-86823',
        'Luminous Heat The Dua Brand',
        'Luminous',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,white floral,warm spicy,floral,woody',
        'Luminous HeatbyThe Dua Brandis a Amber fragrance for women and men.Luminous Heatwas launched in 2020.',
        5,
        1,
        NULL
      ),
(
        'Lush-Blend-86360',
        'Lush Blend The Dua Brand',
        'Lush',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,amber,warm spicy,balsamic,floral',
        'Lush BlendbyThe Dua Brandis a Amber Woody fragrance for women and men.Lush Blendwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Luxurious-Couple-86361',
        'Luxurious Couple The Dua Brand',
        'Luxurious',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,woody,tuberose,white floral',
        'Luxurious CouplebyThe Dua Brandis a Floral fragrance for women and men.Luxurious Couplewas launched in 2021.',
        4.5,
        2,
        NULL
      ),
(
        'Luxurious-For-Him-86362',
        'Luxurious For Him The Dua Brand',
        'Luxurious',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy,citrus,rose',
        'Luxurious For HimbyThe Dua Brandis a Woody fragrance for men.Luxurious For Himwas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ma-Parfum-86365',
        'Ma Parfum The Dua Brand',
        'Ma',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,nutty,patchouli,rose,white floral',
        'Ma ParfumbyThe Dua Brandis a Floral fragrance for women and men.Ma Parfumwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Magic-Of-Hibiscus-86366',
        'Magic Of Hibiscus The Dua Brand',
        'Magic',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,aromatic,green,leather,vanilla',
        'Magic Of HibiscusbyThe Dua Brandis a Amber Floral fragrance for women and men.Magic Of Hibiscuswas launched in 2023.',
        4,
        4,
        NULL
      ),
(
        'Magical-Ballet-86367',
        'Magical Ballet The Dua Brand',
        'Magical',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,vanilla,powdery,sweet,rose',
        'Magical BalletbyThe Dua Brandis a Amber Floral fragrance for women.Magical Balletwas launched in 2023.',
        4.12,
        8,
        NULL
      ),
(
        'Magical-Milan-86368',
        'Magical Milan The Dua Brand',
        'Magical',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,woody,powdery',
        'Magical MilanbyThe Dua Brandis a Floral fragrance for women and men.Magical Milanwas launched in 2023.',
        4,
        1,
        NULL
      ),
(
        'Magnetic-Moon-86369',
        'Magnetic Moon The Dua Brand',
        'Magnetic',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,warm spicy,balsamic,musky',
        'Magnetic MoonbyThe Dua Brandis a Amber Vanilla fragrance for women and men.Magnetic Moonwas launched in 2022.',
        3,
        2,
        NULL
      ),
(
        'Magnificent-Istria-86370',
        'Magnificent Istria The Dua Brand',
        'Magnificent',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,woody,fresh spicy,sweet',
        'Magnificent IstriabyThe Dua Brandis a Aromatic fragrance for women and men.Magnificent Istriawas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Majestic-Santal-86371',
        'Majestic Santal The Dua Brand',
        'Majestic',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,white floral,vanilla,green,powdery',
        'Majestic SantalbyThe Dua Brandis a Amber fragrance for women and men.Majestic Santalwas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Majestic-Taif-86372',
        'Majestic Taif The Dua Brand',
        'Majestic',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,warm spicy,woody,musky,vanilla',
        'Majestic TaifbyThe Dua Brandis a Floral Aldehyde fragrance for women and men.Majestic Taifwas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Majesty-s-Leather-86373',
        'Majesty’s Leather The Dua Brand',
        'Majesty’s',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,fruity,floral,sweet,smoky',
        'Majesty’s LeatherbyThe Dua Brandis a Leather fragrance for women and men.Majesty’s Leatherwas launched in 2022.',
        5,
        1,
        NULL
      ),
(
        'Man-Card-86374',
        'Man Card The Dua Brand',
        'Man',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,amber,fresh spicy,warm spicy',
        'Man CardbyThe Dua Brandis a Woody Spicy fragrance for men.Man Cardwas launched in 2021.',
        5,
        2,
        NULL
      ),
(
        'Man-Card-VIP-86375',
        'Man Card VIP The Dua Brand',
        'Man',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,fresh spicy,ozonic,cinnamon,citrus',
        'Man Card VIPbyThe Dua Brandis a Woody Spicy fragrance for men.Man Card VIPwas launched in 2021.',
        4,
        5,
        NULL
      ),
(
        'Man-of-Tom-86824',
        'Man of Tom The Dua Brand',
        'Man',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,citrus,fresh spicy,aromatic,fruity',
        'Man of TombyThe Dua Brandis a Citrus Aromatic fragrance for men.Man of Tomwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Mandarin-Molecule-1-0-86376',
        'Mandarin Molecule 1.0 The Dua Brand',
        'Mandarin',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus',
        'Mandarin Molecule 1.0byThe Dua Brandis a Citrus fragrance for women and men.Mandarin Molecule 1.0was launched in 2021.',
        3,
        4,
        NULL
      ),
(
        'Mango-Flesh-86377',
        'Mango Flesh The Dua Brand',
        'Mango',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,musky,tropical,powdery,floral',
        'Mango FleshbyThe Dua Brandis a Floral fragrance for women and men.Mango Fleshwas launched in 2021.',
        4.75,
        4,
        NULL
      ),
(
        'Manifest-For-Her-86378',
        'Manifest For Her The Dua Brand',
        'Manifest',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,white floral,vanilla,green,powdery',
        'Manifest For HerbyThe Dua Brandis a Amber fragrance for women.Manifest For Herwas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Marama-86379',
        'Marama The Dua Brand',
        'Marama',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,woody,oud,tuberose,tobacco',
        'MaramabyThe Dua Brandis a Amber Floral fragrance for women and men.Maramawas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Marshmallow-Vanilla-86380',
        'Marshmallow Vanilla The Dua Brand',
        'Marshmallow',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,vanilla,powdery,sweet',
        'Marshmallow VanillabyThe Dua Brandis a Floral fragrance for women and men.Marshmallow Vanillawas launched in 2022.',
        4.8,
        5,
        NULL
      ),
(
        'Massoia-Resin-86381',
        'Massoia Resin The Dua Brand',
        'Massoia',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,sweet,floral,amber,lactonic',
        'Massoia ResinbyThe Dua Brandis a Woody fragrance for women and men.Massoia Resinwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Matchalicious-86382',
        'Matchalicious The Dua Brand',
        'Matchalicious',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,woody,sweet,aromatic',
        'MatchaliciousbyThe Dua Brandis a Aromatic fragrance for women and men.Matchaliciouswas launched in 2021.',
        4.33,
        3,
        NULL
      );
