
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Tulipano-Nero-32167',
        'Tulipano Nero I Profumi di Firenze',
        'Tulipano',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley, Mandarin Orange and Bergamot',
        'Ylang-Ylang, Vanilla Orchid and Rose',
        'Myrrh and Vetiver',
        'citrus,sweet,amber,aromatic,woody',
        'Tulipano NerobyI Profumi di Firenzeis a Floral Woody Musk fragrance for women. Top notes are Lily-of-the-Valley, Mandarin Orange and Bergamot; middle notes are Ylang-Ylang, Vanilla Orchid and Rose; base notes are Myrrh and Vetiver.',
        4.23,
        22,
        NULL
      ),
(
        'Tuscania-12743',
        'Tuscania I Profumi di Firenze',
        'Tuscania',
        'for women and men',
        NULL,
        'Giovanni Di Massimo',
        'Petitgrain, Amalfi Lemon, Bergamot and Mandarin Orange',
        'Coriander and Lily-of-the-Valley',
        'Musk, Vanille, Patchouli and Sandalwood',
        'aromatic,citrus,musky,powdery,vanilla',
        'TuscaniabyI Profumi di Firenzeis a Citrus Aromatic fragrance for women and men.Tuscaniawas launched in 2008. The nose behind this fragrance is Giovanni Di Massimo. Top notes are Petitgrain, Amalfi Lemon, Bergamot and Mandarin Orange; middle notes are Coriander and Lily-of-the-Valley; base notes are Musk, Vanille, Patchouli and Sandalwood.',
        3.7,
        10,
        NULL
      ),
(
        'Vaniglia-del-Madagascar-9755',
        'Vaniglia del Madagascar I Profumi di Firenze',
        'Vaniglia',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,white floral,powdery,fresh',
        'Vaniglia del MadagascarbyI Profumi di Firenzeis a Amber Vanilla fragrance for women.Vaniglia del Madagascarwas launched during the 2000''s.',
        4.35,
        196,
        NULL
      ),
(
        'Vaniglia-e-Fichi-35987',
        'Vaniglia e Fichi I Profumi di Firenze',
        'Vaniglia',
        'for women',
        NULL,
        'Giovanni Di Massimo',
        'Green Leaves and Orange',
        'Fig, Lilac, Cyclamen, Tonka Bean and Jasmine',
        'Vanilla, White Musk, Sandalwood and Woody Notes',
        'vanilla,sweet,powdery,fruity,woody',
        'Vaniglia e FichibyI Profumi di Firenzeis a Floral fragrance for women. The nose behind this fragrance is Giovanni Di Massimo. Top notes are Green Leaves and Orange; middle notes are Fig, Lilac, Cyclamen, Tonka Bean and Jasmine; base notes are Vanilla, White Musk, Sandalwood and Woody Notes.',
        4.05,
        39,
        NULL
      ),
(
        'Vaniglia-e-Zenzero-9762',
        'Vaniglia e Zenzero I Profumi di Firenze',
        'Vaniglia',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Sicilian Lemon, Mandarin Orange and Basil',
        'Lavender, Nutmeg, Violet, Cloves, Neroli, Lily-of-the-Valley, Geranium and Cypress',
        'Madagascar Vanilla, Ginger, Patchouli, Oakmoss and Vetiver',
        'vanilla,citrus,powdery,fresh spicy,warm spicy',
        'Vaniglia e ZenzerobyI Profumi di Firenzeis a Amber Spicy fragrance for women and men.Vaniglia e Zenzerowas launched during the 2000''s. Top notes are Bergamot, Sicilian Lemon, Mandarin Orange and Basil; middle notes are Lavender, Nutmeg, Violet, Cloves, Neroli, Lily-of-the-Valley, Geranium and Cypress; base notes are Madagascar Vanilla, Ginger, Patchouli, Oakmoss and Vetiver.',
        4.19,
        21,
        NULL
      ),
(
        'Vento-di-Eros-30681',
        'Vento di Eros I Profumi di Firenze',
        'Vento',
        'for women and men',
        NULL,
        NULL,
        'Bitter Orange, Bergamot, Lemon and Mandarin Orange',
        'Lily-of-the-Valley, Carnation, Geranium, Nutmeg, Rose, Lavender, Pepper, Cinnamon, Jasmine and Neroli',
        'Musk, Patchouli, Vanilla, Vetiver, Myrhh and Benzoin',
        'white floral,warm spicy,fresh spicy,aromatic,floral',
        'Vento di ErosbyI Profumi di Firenzeis a Amber Floral fragrance for women and men. Top notes are Bitter Orange, Bergamot, Lemon and Mandarin Orange; middle notes are Lily-of-the-Valley, Carnation, Geranium, Nutmeg, Rose, Lavender, Pepper, Cinnamon, Jasmine and Neroli; base notes are Musk, Patchouli, Vanilla, Vetiver, Myrhh and Benzoin.',
        4,
        3,
        NULL
      ),
(
        'Verde-Bosco-9763',
        'Verde Bosco I Profumi di Firenze',
        'Verde',
        'for women and men',
        NULL,
        'Giovanni Di Massimo',
        'Basil, Lavender, Grapefruit and Mandarin Orange',
        'Cassis, Pineapple, Geranium, Lily, Rose and Lily-of-the-Valley',
        'Oakmoss, Vetiver, Cedar, Moss and Ambergris',
        'aromatic,woody,green,fresh,fresh spicy',
        'Verde BoscobyI Profumi di Firenzeis a Woody Chypre fragrance for women and men.Verde Boscowas launched in 2008. The nose behind this fragrance is Giovanni Di Massimo. Top notes are Basil, Lavender, Grapefruit and Mandarin Orange; middle notes are Cassis, Pineapple, Geranium, Lily, Rose and Lily-of-the-Valley; base notes are Oakmoss, Vetiver, Cedar, Moss and Ambergris.',
        3.67,
        3,
        NULL
      ),
(
        'Verso-Andromeda-26437',
        'Verso Andromeda I Profumi di Firenze',
        'Verso',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Coriander and Tangerine',
        'Magnolia, Jasmine, Wild Orchid and Honeysuckle',
        'Cedar and Sandalwood',
        'soft spicy,floral,white floral,aromatic,sweet',
        'Verso AndromedabyI Profumi di Firenzeis a Floral Woody Musk fragrance for women.Verso Andromedawas launched in 2014. Top notes are Pink Pepper, Coriander and Tangerine; middle notes are Magnolia, Jasmine, Wild Orchid and Honeysuckle; base notes are Cedar and Sandalwood.',
        4.75,
        4,
        NULL
      ),
(
        'Vetiver-di-Giava-30682',
        'Vetiver di Giava I Profumi di Firenze',
        'Vetiver',
        'for women and men',
        NULL,
        NULL,
        'Pine, Bergamot, Lemon and Cumin',
        'Geranium, Thyme, Lavender, Spices and White Flowers',
        'Vetiver, Elemi resin, Sandalwood and Cedar',
        'aromatic,woody,fresh spicy,conifer,citrus',
        'Vetiver di GiavabyI Profumi di Firenzeis a Amber Fougere fragrance for women and men. Top notes are Pine, Bergamot, Lemon and Cumin; middle notes are Geranium, Thyme, Lavender, Spices and White Flowers; base notes are Vetiver, Elemi resin, Sandalwood and Cedar.',
        4.12,
        8,
        NULL
      ),
(
        'Violetta-di-Bosco-28890',
        'Violetta di Bosco I Profumi di Firenze',
        'Violetta',
        'for women',
        NULL,
        NULL,
        'Anise',
        'Violet, Iris, Peach and Lily-of-the-Valley',
        'Benzoin, Heliotrope and Vetiver',
        'powdery,violet,floral,woody,anis',
        'Violetta di BoscobyI Profumi di Firenzeis a Floral fragrance for women. Top note is Anise; middle notes are Violet, Iris, Peach and Lily-of-the-Valley; base notes are Benzoin, Heliotrope and Vetiver.',
        4.17,
        35,
        NULL
      ),
(
        'Zagara-Neroli-Flor-28886',
        'Zagara Neroli Flor I Profumi di Firenze',
        'Zagara',
        'for women and men',
        NULL,
        NULL,
        'Orange and Lemon',
        'Orange Blossom, Tuberose and Rose',
        'Petitgrain',
        'citrus,white floral',
        'Zagara Neroli FlorbyI Profumi di Firenzeis a Floral fragrance for women and men. Top notes are Orange and Lemon; middle notes are Orange Blossom, Tuberose and Rose; base note is Petitgrain.',
        2.78,
        9,
        NULL
      ),
(
        'Zefiro-30664',
        'Zefiro I Profumi di Firenze',
        'Zefiro',
        'for women and men',
        NULL,
        NULL,
        'Honeysuckle, Lemon, Bergamot, Mandarin Orange, Sage and Rosemary',
        'Coriander and Nutmeg',
        'White Musk, Sandalwood and Patchouli',
        'citrus,aromatic,white floral,fresh spicy,woody',
        'ZefirobyI Profumi di Firenzeis a Citrus Aromatic fragrance for women and men. Top notes are Honeysuckle, Lemon, Bergamot, Mandarin Orange, Sage and Rosemary; middle notes are Coriander and Nutmeg; base notes are White Musk, Sandalwood and Patchouli.',
        4.36,
        11,
        NULL
      ),
(
        'Zenzero-12739',
        'Zenzero I Profumi di Firenze',
        'Zenzero',
        'for women and men',
        NULL,
        'Giovanni Di Massimo',
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,musky,woody,sweet',
        'ZenzerobyI Profumi di Firenzeis a Aromatic Spicy fragrance for women and men. The nose behind this fragrance is Giovanni Di Massimo.',
        4.33,
        9,
        NULL
      ),
(
        '1941-80502',
        '1941 I Profumi di Firenze',
        '1941',
        'for women and men',
        NULL,
        'Dr. Giovanni Di Massimo',
        'Cardamom, Mint and Cedar',
        'Musk, Coriander, Lavender and Patchouli',
        'Cypress, Vanilla, Sandalwood, Iso E Super and Incense',
        'aromatic,woody,warm spicy,musky,powdery',
        '1941byI Profumi di Firenzeis a Woody Aromatic fragrance for women and men. The nose behind this fragrance is Dr. Giovanni Di Massimo. Top notes are Cardamom, Mint and Cedar; middle notes are Musk, Coriander, Lavender and Patchouli; base notes are Cypress, Vanilla, Sandalwood, Iso E Super and Incense.',
        4.33,
        6,
        NULL
      ),
(
        'Mudan-84983',
        'Mudan I Profumi di Firenze',
        'Mudan',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Peach, Lemon and Pear',
        'Peony and Rose',
        'Tonka Bean, Vanilla, Cedar and Oud',
        'vanilla,rose,fruity,sweet,floral',
        'MudanbyI Profumi di Firenzeis a fragrance for women and men. Top notes are Cardamom, Peach, Lemon and Pear; middle notes are Peony and Rose; base notes are Tonka Bean, Vanilla, Cedar and Oud.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ame-Toscane-1216',
        'Ame Toscane ID Parfums',
        'Ame',
        'for women',
        NULL,
        NULL,
        'Peach, Osmanthus, Cassia, Orange and Bergamot',
        'Tuscan Iris, Magnolia and Freesia',
        'Vanilla, Musk and Sandalwood',
        'fruity,powdery,floral,iris,woody',
        'Ame ToscanebyID Parfumsis a Floral Woody Musk fragrance for women.Ame Toscanewas launched in 1996. Top notes are Peach, Osmanthus, Cassia, Orange and Bergamot; middle notes are Tuscan Iris, Magnolia and Freesia; base notes are Vanilla, Musk and Sandalwood.',
        3.72,
        717,
        NULL
      ),
(
        'Ame-Toscane-Fantaisie-Baroque-10672',
        'Ame Toscane Fantaisie Baroque ID Parfums',
        'Ame',
        'for women',
        NULL,
        NULL,
        'Peach',
        'Iris, Magnolia and Orris Root',
        'Vanille, Musk and Sandalwood',
        'powdery,iris,vanilla,fruity,floral',
        'Ame Toscane Fantaisie BaroquebyID Parfumsis a Floral Woody Musk fragrance for women.Ame Toscane Fantaisie Baroquewas launched in 2009. Top note is Peach; middle notes are Iris, Magnolia and Orris Root; base notes are Vanille, Musk and Sandalwood.',
        3.79,
        76,
        NULL
      ),
(
        'Ame-Toscane-Intense-43925',
        'Ame Toscane Intense ID Parfums',
        'Ame',
        'for women',
        NULL,
        'Nicolas Beaulieu',
        'Apricot, Litchi and Mandarin Orange',
        'Iris, Raspberry and Rose',
        'White Cedar Extract, Musk and Vanilla',
        'fruity,powdery,iris,sweet,woody',
        'Ame Toscane IntensebyID Parfumsis a Floral Fruity fragrance for women.Ame Toscane Intensewas launched in 2017. The nose behind this fragrance is Nicolas Beaulieu. Top notes are Apricot, Litchi and Mandarin Orange; middle notes are Iris, Raspberry and Rose; base notes are White Cedar Extract, Musk and Vanilla.',
        3.91,
        44,
        NULL
      ),
(
        'Ame-Toscane-Reflet-d-Iris-3753',
        'Ame Toscane Reflet d’Iris ID Parfums',
        'Ame',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Angelica and Cardamom',
        'Iris, Violet and Lily-of-the-Valley',
        'Musk and Amber',
        'powdery,violet,iris,musky,amber',
        'Ame Toscane Reflet d’IrisbyID Parfumsis a Floral Woody Musk fragrance for women.Ame Toscane Reflet d’Iriswas launched in 2008. Top notes are Mandarin Orange, Angelica and Cardamom; middle notes are Iris, Violet and Lily-of-the-Valley; base notes are Musk and Amber.',
        3.91,
        183,
        NULL
      ),
(
        'Ame-Toscane-Renaissance-23914',
        'Ame Toscane Renaissance ID Parfums',
        'Ame',
        'for women',
        NULL,
        NULL,
        'Peach',
        'Tuscan Iris and Magnolia',
        'Vanilla and Musk',
        'powdery,iris,fruity,vanilla,violet',
        'Ame Toscane RenaissancebyID Parfumsis a Floral Fruity fragrance for women. Top note is Peach; middle notes are Tuscan Iris and Magnolia; base notes are Vanilla and Musk.',
        3.89,
        119,
        NULL
      ),
(
        'Andalucia-1219',
        'Andalucia ID Parfums',
        'Andalucia',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Bergamot, Rosemary, Caraway and Coriander',
        'Neroli',
        'Sandalwood, Labdanum and Cedar',
        'citrus,aromatic,fresh spicy,woody,white floral',
        'AndaluciabyID Parfumsis a Chypre Fruity fragrance for women. Top notes are Mandarin Orange, Bergamot, Rosemary, Caraway and Coriander; middle note is Neroli; base notes are Sandalwood, Labdanum and Cedar.',
        3.75,
        238,
        NULL
      ),
(
        'Andalucia-Sensuelle-4765',
        'Andalucia Sensuelle ID Parfums',
        'Andalucia',
        'for women',
        NULL,
        NULL,
        'Bitter Orange and Mandarin Orange',
        'Orange Blossom and White Flowers',
        'Patchouli and Salt',
        'citrus,white floral,patchouli',
        'Andalucia SensuellebyID Parfumsis a Chypre Fruity fragrance for women. Top notes are Bitter Orange and Mandarin Orange; middle notes are Orange Blossom and White Flowers; base notes are Patchouli and Salt.',
        3.6,
        247,
        NULL
      ),
(
        'Autour-de-Minuit-33190',
        'Autour de Minuit ID Parfums',
        'Autour',
        'for women',
        NULL,
        NULL,
        'Pink Pepper and Mandarin Orange',
        'Raspberry, Incense, Rose and Saffron',
        'Agarwood (Oud), Sandalwood, Patchouli and Vanilla',
        'warm spicy,woody,oud,fruity,sweet',
        'Autour de MinuitbyID Parfumsis a Amber fragrance for women.Autour de Minuitwas launched in 2015. Top notes are Pink Pepper and Mandarin Orange; middle notes are Raspberry, Incense, Rose and Saffron; base notes are Agarwood (Oud), Sandalwood, Patchouli and Vanilla.',
        3.62,
        118,
        NULL
      ),
(
        'Cap-Verde-25784',
        'Cap Verde ID Parfums',
        'Cap',
        'for men',
        NULL,
        'Benoist Lapouza',
        'Bergamot, Clary Sage and Mandarin Orange',
        'Citruses, Lavender and Star Anise',
        'Vetiver, Patchouli and Musk',
        'citrus,aromatic,fresh spicy,lavender,soft spicy',
        'Cap VerdebyID Parfumsis a Woody Aromatic fragrance for men. Cap Verde was created by Delphine Lebeau and Benoist Lapouza. Top notes are Bergamot, Clary Sage and Mandarin Orange; middle notes are Citruses, Lavender and Star Anise; base notes are Vetiver, Patchouli and Musk.',
        3.83,
        18,
        NULL
      ),
(
        'Charleston-14488',
        'Charleston ID Parfums',
        'Charleston',
        'for women',
        NULL,
        NULL,
        'Violet Leaf, Apricot and Bergamot',
        'Jasmine, Narcissus, Tuberose and Clove',
        'Sandalwood, Vetiver, Patchouli and Musk',
        'white floral,tuberose,green,yellow floral,woody',
        'CharlestonbyID Parfumsis a Floral Woody Musk fragrance for women.Charlestonwas launched in 2004. Top notes are Violet Leaf, Apricot and Bergamot; middle notes are Jasmine, Narcissus, Tuberose and Clove; base notes are Sandalwood, Vetiver, Patchouli and Musk.',
        4.26,
        53,
        NULL
      ),
(
        'Eclat-d-Orient-6173',
        'Eclat d''Orient ID Parfums',
        'Eclat',
        'for women',
        NULL,
        'Karine Dubreuil-Sereni',
        'Yuzu, Freesia and Bergamot',
        'Almond Blossom, Rice, Bamboo and Wild Jasmine',
        'White Musk and Sandalwood',
        'floral,woody,sweet,citrus,musky',
        'Eclat d''OrientbyID Parfumsis a Floral Aldehyde fragrance for women.Eclat d''Orientwas launched in 2009. The nose behind this fragrance is Karine Dubreuil-Sereni. Top notes are Yuzu, Freesia and Bergamot; middle notes are Almond Blossom, Rice, Bamboo and Wild Jasmine; base notes are White Musk and Sandalwood.',
        3.89,
        208,
        NULL
      ),
(
        'Eclat-Eternel-14570',
        'Eclat Eternel ID Parfums',
        'Eclat',
        'for women',
        NULL,
        'Véronique Nyberg',
        'Bergamot and Grapefruit',
        'Jasmine and Tuberose',
        'Cashmere Wood and Vanilla',
        'white floral,tuberose,citrus',
        'Eclat EternelbyID Parfumsis a Floral fragrance for women.Eclat Eternelwas launched in 2012. The nose behind this fragrance is Veronique Nyberg. Top notes are Bergamot and Grapefruit; middle notes are Jasmine and Tuberose; base notes are Cashmere Wood and Vanilla.',
        3.51,
        249,
        NULL
      ),
(
        'Elixir-de-Mimosa-25786',
        'Elixir de Mimosa ID Parfums',
        'Elixir',
        'for women',
        NULL,
        NULL,
        'Violet Leaf and Almond Blossom',
        'Mimosa absolute',
        'Heliotrope and Musk',
        'powdery,yellow floral,floral,sweet,vanilla',
        'Elixir de MimosabyID Parfumsis a Floral fragrance for women.Elixir de Mimosawas launched in 2014. Top notes are Violet Leaf and Almond Blossom; middle note is Mimosa absolute; base notes are Heliotrope and Musk.',
        3.91,
        43,
        NULL
      ),
(
        'Elixir-de-Muguet-18303',
        'Elixir de Muguet ID Parfums',
        'Elixir',
        'for women',
        NULL,
        'Philippe Bousseton',
        'Bergamot and Grapefruit',
        'Lily-of-the-Valley',
        'Ylang-Ylang and Musk',
        'white floral,citrus,fresh,green,yellow floral',
        'Elixir de MuguetbyID Parfumsis a Floral Green fragrance for women.Elixir de Muguetwas launched in 2013. The nose behind this fragrance is Philippe Bousseton. Top notes are Bergamot and Grapefruit; middle note is Lily-of-the-Valley; base notes are Ylang-Ylang and Musk.',
        3.9,
        30,
        NULL
      ),
(
        'Elixir-de-Rose-33392',
        'Elixir de Rose ID Parfums',
        'Elixir',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Rose and Turkish Rose',
        'White Woods',
        'rose,woody,citrus,floral',
        'Elixir de RosebyID Parfumsis a Floral fragrance for women. Top note is Bergamot; middle notes are Rose and Turkish Rose; base note is White Woods.',
        3.71,
        41,
        NULL
      ),
(
        'Exterieur-Nuit-1222',
        'Exterieur Nuit ID Parfums',
        'Exterieur',
        'for men',
        NULL,
        NULL,
        'Pepper and Coriander',
        'Cinnamon Flower, Neroli and White Musk',
        'Coumarin, Vetiver and Sandalwood',
        'aromatic,warm spicy,fresh spicy,woody,cinnamon',
        'Exterieur NuitbyID Parfumsis a Woody Floral Musk fragrance for men. Top notes are Pepper and Coriander; middle notes are Cinnamon Flower, Neroli and White Musk; base notes are Coumarin, Vetiver and Sandalwood.',
        4.3,
        23,
        NULL
      ),
(
        'Fleurs-de-Kyoto-45234',
        'Fleurs de Kyoto ID Parfums',
        'Fleurs',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,fresh,sweet,aquatic',
        'Fleurs de KyotobyID Parfumsis a Floral Fruity fragrance for women.Fleurs de Kyotowas launched in 2017.',
        3.83,
        46,
        NULL
      ),
(
        'Folie-Rouge-22199',
        'Folie Rouge ID Parfums',
        'Folie',
        'for women',
        NULL,
        'Delphine Jelk',
        'Red Thyme and Bergamot',
        'Violet, Rice and Orange Blossom',
        'Tonka Bean, White Musk and Patchouli',
        'aromatic,powdery,violet,sweet,musky',
        'Folie RougebyID Parfumsis a Floral Woody Musk fragrance for women.Folie Rougewas launched in 2013. The nose behind this fragrance is Delphine Jelk. Top notes are Red Thyme and Bergamot; middle notes are Violet, Rice and Orange Blossom; base notes are Tonka Bean, White Musk and Patchouli.',
        3.4,
        176,
        NULL
      ),
(
        'Gandali-17016',
        'Gandali ID Parfums',
        'Gandali',
        'for women',
        NULL,
        'Emilie Bouge',
        'Raspberry, Pomegranate and Passionfruit',
        'Jasmine',
        'Sandalwood, Vanilla and Patchouli',
        'fruity,woody,sweet,white floral,tropical',
        'GandalibyID Parfumsis a Floral Fruity fragrance for women.Gandaliwas launched in 2009. The nose behind this fragrance is Emilie Bouge. Top notes are Raspberry, Pomegranate and Passionfruit; middle note is Jasmine; base notes are Sandalwood, Vanilla and Patchouli.',
        3.59,
        133,
        NULL
      ),
(
        'Iguazu-25785',
        'Iguazù ID Parfums',
        'Iguazù',
        'for men',
        NULL,
        'Claire Chambert',
        'Cardamom, Mandarin Orange and Bergamot',
        'Ginger, Coriander and Iris',
        'Vetiver and Australian Sandalwood',
        'warm spicy,aromatic,citrus,woody,earthy',
        'IguazùbyID Parfumsis a Woody Spicy fragrance for men. The nose behind this fragrance is Claire Chambert. Top notes are Cardamom, Mandarin Orange and Bergamot; middle notes are Ginger, Coriander and Iris; base notes are Vetiver and Australian Sandalwood.',
        4.11,
        36,
        NULL
      ),
(
        'Ilaya-4766',
        'Ilaya ID Parfums',
        'Ilaya',
        'for women',
        NULL,
        'Jérôme Epinette',
        'Cardamom and Ginger',
        'Ylang-Ylang and Jasmine',
        'Coffee, Incense, Benzoin and Myrhh',
        'warm spicy,amber,coffee,yellow floral,balsamic',
        'IlayabyID Parfumsis a Amber Woody fragrance for women.Ilayawas launched in 2007. The nose behind this fragrance is Jérôme Epinette. Top notes are Cardamom and Ginger; middle notes are Ylang-Ylang and Jasmine; base notes are Coffee, Incense, Benzoin and Myrhh.',
        4.13,
        359,
        NULL
      ),
(
        'Jardin-d-Andalousie-37547',
        'Jardin d''Andalousie ID Parfums',
        'Jardin',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Citruses',
        'Orange Blossom and Jasmine',
        'White Musk and Woody Notes',
        'citrus,white floral,musky,sweet',
        'Jardin d''AndalousiebyID Parfumsis a Citrus fragrance for women. Top notes are Mandarin Orange and Citruses; middle notes are Orange Blossom and Jasmine; base notes are White Musk and Woody Notes.',
        3.5,
        44,
        NULL
      ),
(
        'Jardin-d-Antalya-22201',
        'Jardin d''Antalya ID Parfums',
        'Jardin',
        'for women',
        NULL,
        'Vincent Ricord',
        'Cardamom and Coriander',
        'Damask Rose and Violet',
        'Vanilla and Patchouli',
        'warm spicy,vanilla,aromatic,rose,powdery',
        'Jardin d''AntalyabyID Parfumsis a Floral fragrance for women.Jardin d''Antalyawas launched in 2011. The nose behind this fragrance is Vincent Ricord. Top notes are Cardamom and Coriander; middle notes are Damask Rose and Violet; base notes are Vanilla and Patchouli.',
        3.38,
        66,
        NULL
      ),
(
        'Jardin-de-Bali-22202',
        'Jardin de Bali ID Parfums',
        'Jardin',
        'for women',
        NULL,
        'Cecile Matton',
        'Cloves and Bergamot',
        'Tuberose and Ylang-Ylang',
        'Licorice, Vanilla and Benzoin',
        'warm spicy,tuberose,yellow floral,white floral,sweet',
        'Jardin de BalibyID Parfumsis a Floral fragrance for women. The nose behind this fragrance is Cecile Matton. Top notes are Cloves and Bergamot; middle notes are Tuberose and Ylang-Ylang; base notes are Licorice, Vanilla and Benzoin.',
        3.28,
        60,
        NULL
      ),
(
        'Jardin-de-Madagascar-22200',
        'Jardin de Madagascar ID Parfums',
        'Jardin',
        'for women',
        NULL,
        'Vincent Ricord',
        'Ylang-Ylang and Tamarind',
        'Honey and Peru Balsam',
        'Vanilla and Tonka Bean',
        'honey,sweet,vanilla,yellow floral,floral',
        'Jardin de MadagascarbyID Parfumsis a Floral fragrance for women. The nose behind this fragrance is Vincent Ricord. Top notes are Ylang-Ylang and Tamarind; middle notes are Honey and Peru Balsam; base notes are Vanilla and Tonka Bean.',
        3.57,
        7,
        NULL
      ),
(
        'Jardin-de-Sicile-9833',
        'Jardin de Sicile ID Parfums',
        'Jardin',
        'for women',
        NULL,
        'Vincent Ricord',
        'Bitter Orange, Amalfi Lemon and Petitgrain',
        'Petitgrain, Lemon Blossom and Violet',
        'White Honey, Vanille and Patchouli',
        'citrus,honey,sweet,fresh',
        'Jardin de SicilebyID Parfumsis a Citrus Gourmand fragrance for women. The nose behind this fragrance is Vincent Ricord. Top notes are Bitter Orange, Amalfi Lemon and Petitgrain; middle notes are Petitgrain, Lemon Blossom and Violet; base notes are White Honey, Vanille and Patchouli.',
        3.52,
        56,
        NULL
      ),
(
        'Kachgar-10609',
        'Kachgar ID Parfums',
        'Kachgar',
        'for men',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Cardamom and Cinnamon',
        'Sandalwood, Amber, Vanille and Patchouli',
        'warm spicy,woody,aromatic,citrus,powdery',
        'KachgarbyID Parfumsis a Amber Spicy fragrance for men.Kachgarwas launched during the 2000''s. Top notes are Bergamot and Mandarin Orange; middle notes are Cardamom and Cinnamon; base notes are Sandalwood, Amber, Vanille and Patchouli.',
        4,
        55,
        NULL
      ),
(
        'Le-Monde-des-Reves-1220',
        'Le Monde des Rêves ID Parfums',
        'Le',
        'for women',
        NULL,
        NULL,
        NULL,
        'Peony and Osmanthus',
        'Musk',
        'floral,fresh,fruity,rose',
        'Le Monde des RêvesbyID Parfumsis a Floral Green fragrance for women.Le Monde des Rêveswas launched in 1998. middle notes are Peony and Osmanthus; base note is Musk.',
        4,
        9,
        NULL
      ),
(
        'Le-Secret-de-la-Rose-4768',
        'Le Secret de la Rose ID Parfums',
        'Le',
        'for women',
        NULL,
        'Anne Flipo',
        'Black Currant and Aldehydes',
        'Rose and Geranium',
        'Cedar and Vanilla',
        'rose,floral,fruity',
        'Le Secret de la RosebyID Parfumsis a Floral Aldehyde fragrance for women.Le Secret de la Rosewas launched in 2001. The nose behind this fragrance is Anne Flipo. Top notes are Black Currant and Aldehydes; middle notes are Rose and Geranium; base notes are Cedar and Vanilla.',
        4.04,
        23,
        NULL
      ),
(
        'Le-Temps-de-Reines-4767',
        'Le Temps de Reines ID Parfums',
        'Le',
        'for women',
        NULL,
        'Christopher Sheldrake',
        'Geranium and Spices',
        'Patchouli',
        'Sandalwood and Benzoin',
        'warm spicy,woody,amber,fresh spicy,aromatic',
        'Le Temps de ReinesbyID Parfumsis a Amber Woody fragrance for women.Le Temps de Reineswas launched in 1998. The nose behind this fragrance is Christopher Sheldrake. Top notes are Geranium and Spices; middle note is Patchouli; base notes are Sandalwood and Benzoin.',
        4.19,
        77,
        NULL
      ),
(
        'Les-Fantaisies-Fantaisie-Gourmande-28899',
        'Les Fantaisies - Fantaisie Gourmande ID Parfums',
        'Les',
        'for women',
        NULL,
        NULL,
        'Clementine and Sugar',
        'Meringue, Rose and Neroli',
        'Vanilla, Tonka Bean and Musk',
        'sweet,vanilla,citrus,powdery,rose',
        'Les Fantaisies - Fantaisie GourmandebyID Parfumsis a Amber Vanilla fragrance for women.Les Fantaisies - Fantaisie Gourmandewas launched in 2011. Top notes are Clementine and Sugar; middle notes are Meringue, Rose and Neroli; base notes are Vanilla, Tonka Bean and Musk.',
        3.8,
        25,
        NULL
      ),
(
        'Les-Fantaisies-Fantasie-Florale-28898',
        'Les Fantaisies - Fantasie Florale ID Parfums',
        'Les',
        'for women',
        NULL,
        NULL,
        'Plum Blossom, Pink Pepper and Anise',
        'Magnolia, White Rose and Tuberose',
        'Tonka Bean, Amber and Woody Notes',
        'floral,rose,tuberose,white floral,fresh',
        'Les Fantaisies - Fantasie FloralebyID Parfumsis a Amber Floral fragrance for women. Top notes are Plum Blossom, Pink Pepper and Anise; middle notes are Magnolia, White Rose and Tuberose; base notes are Tonka Bean, Amber and Woody Notes.',
        3.88,
        26,
        NULL
      ),
(
        'Lettre-a-Anna-1217',
        'Lettre a Anna ID Parfums',
        'Lettre',
        'for women',
        NULL,
        NULL,
        'Orange, Lemon and Mandarin Orange',
        'Rose, Coriander and Ylang-Ylang',
        'Oakmoss, Vetiver and Patchouli',
        'woody,aromatic,earthy,citrus,rose',
        'Lettre a AnnabyID Parfumsis a Chypre Floral fragrance for women.Lettre a Annawas launched in 1996. Top notes are Orange, Lemon and Mandarin Orange; middle notes are Rose, Coriander and Ylang-Ylang; base notes are Oakmoss, Vetiver and Patchouli.',
        4.14,
        85,
        NULL
      ),
(
        'Lettre-a-Anna-Delicate-4764',
        'Lettre a Anna Delicate ID Parfums',
        'Lettre',
        'for women',
        NULL,
        NULL,
        'Pear, Coriander and Bergamot',
        'Rose and Lily-of-the-Valley',
        'Oakmoss, Amber and Patchouli',
        'aromatic,rose,earthy,amber,mossy',
        'Lettre a Anna DelicatebyID Parfumsis a Chypre Floral fragrance for women. Top notes are Pear, Coriander and Bergamot; middle notes are Rose and Lily-of-the-Valley; base notes are Oakmoss, Amber and Patchouli.',
        3.82,
        127,
        NULL
      ),
(
        'Madras-10610',
        'Madras ID Parfums',
        'Madras',
        'for men',
        NULL,
        NULL,
        'Pepper and Pink Pepper',
        'Nutmeg, Cinnamon and Coffee',
        'Sandalwood, Tonka Bean and Guaiac Wood',
        'fresh spicy,warm spicy,woody,cinnamon,coffee',
        'MadrasbyID Parfumsis a Amber Spicy fragrance for men.Madraswas launched during the 2000''s. Top notes are Pepper and Pink Pepper; middle notes are Nutmeg, Cinnamon and Coffee; base notes are Sandalwood, Tonka Bean and Guaiac Wood.',
        4.15,
        61,
        NULL
      ),
(
        'Mei-Li-9832',
        'Mei Li ID Parfums',
        'Mei',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,rose,green,lactonic',
        'Mei LibyID Parfumsis a Floral Green fragrance for women.',
        4.15,
        27,
        NULL
      ),
(
        'Ode-a-l-Amour-42293',
        'Ode а l''Amour ID Parfums',
        'Ode',
        'for women',
        NULL,
        'Angeline Poubeau Leporini',
        'Plum, Litchi and Mandarin Orange',
        'Patchouli, Rose and Jasmine Sambac',
        'Vanilla, Sandalwood and Cashmere Wood',
        'fruity,woody,sweet,patchouli,vanilla',
        'Ode а l''AmourbyID Parfumsis a Floral Fruity fragrance for women.Ode а l''Amourwas launched in 2016. The nose behind this fragrance is Angeline Poubeau Leporini. Top notes are Plum, Litchi and Mandarin Orange; middle notes are Patchouli, Rose and Jasmine Sambac; base notes are Vanilla, Sandalwood and Cashmere Wood.',
        3.73,
        80,
        NULL
      ),
(
        'Oh-Delice-32547',
        'Oh Délice! ID Parfums',
        'Oh',
        'for women',
        NULL,
        'Claire Chambert',
        'Cherry and Pink Pepper',
        'Rose and Star Jasmine',
        'Praline, Tonka Bean, Vanilla and Osmanthus',
        'sweet,vanilla,cherry,rose,soft spicy',
        'Oh Délice!byID Parfumsis a Chypre Floral fragrance for women.Oh Délice!was launched in 2014. The nose behind this fragrance is Claire Chambert. Top notes are Cherry and Pink Pepper; middle notes are Rose and Star Jasmine; base notes are Praline, Tonka Bean, Vanilla and Osmanthus.',
        3.66,
        106,
        NULL
      ),
(
        'Passion-Latine-67656',
        'Passion Latine ID Parfums',
        'Passion',
        'for women',
        NULL,
        'Vincent Ricord',
        'Mandarin Orange and Ginger',
        'Coffee, Vanilla Flower and Jasmine Sambac',
        'Tonka Bean, Sandalwood and Cacao',
        'warm spicy,citrus,vanilla,coffee,sweet',
        'Passion LatinebyID Parfumsis a Citrus Gourmand fragrance for women.Passion Latinewas launched in 2018. The nose behind this fragrance is Vincent Ricord. Top notes are Mandarin Orange and Ginger; middle notes are Coffee, Vanilla Flower and Jasmine Sambac; base notes are Tonka Bean, Sandalwood and Cacao.',
        3.8,
        44,
        NULL
      ),
(
        'Pour-L-Amour-de-L-Inde-1218',
        'Pour L''Amour de L''Inde ID Parfums',
        'Pour',
        'for women',
        NULL,
        NULL,
        'Pepper, Tagetes and Rose',
        'Cardamom, Sandalwood and Jasmine',
        'Vanilla and Cedar',
        'warm spicy,fresh spicy,aromatic,woody,vanilla',
        'Pour L''Amour de L''IndebyID Parfumsis a Amber Floral fragrance for women.Pour L''Amour de L''Indewas launched in 1996. Top notes are Pepper, Tagetes and Rose; middle notes are Cardamom, Sandalwood and Jasmine; base notes are Vanilla and Cedar.',
        4.03,
        173,
        NULL
      ),
(
        'Reve-de-Bahia-25783',
        'Rêve de Bahia ID Parfums',
        'Rêve',
        'for women',
        NULL,
        'Angeline Poubeau Leporini',
        'Lime, Sugar Cane, Lemon Peel and Bitter Orange',
        'Coconut Nectar, Lily and Jasmine Sambac',
        'Vanilla and Exotic Woods',
        'citrus,sweet,vanilla,coconut,white floral',
        'Rêve de BahiabyID Parfumsis a Floral Fruity fragrance for women. The nose behind this fragrance is Angeline Poubeau Leporini. Top notes are Lime, Sugar Cane, Lemon Peel and Bitter Orange; middle notes are Coconut Nectar, Lily and Jasmine Sambac; base notes are Vanilla and Exotic Woods.',
        3.35,
        107,
        NULL
      ),
(
        'Rose-Divine-1221',
        'Rose Divine ID Parfums',
        'Rose',
        'for women',
        NULL,
        'Celine Ellena',
        NULL,
        NULL,
        NULL,
        'rose,fruity,amber,warm spicy,woody',
        'Rose DivinebyID Parfumsis a Floral Woody Musk fragrance for women.Rose Divinewas launched in 2006. The nose behind this fragrance is Celine Ellena.',
        4.05,
        152,
        NULL
      ),
(
        'Secrets-de-Hammam-4735',
        'Secrets de Hammam ID Parfums',
        'Secrets',
        'for women',
        NULL,
        'Alexandra Kosinski',
        'Pink Pepper, Bergamot and Mandarin Orange',
        'Cedar, Ylang-Ylang, Jasmine and White Flowers',
        'Amber, Benzoin, Sandalwood, Sweet Notes, Patchouli and Musk',
        'woody,citrus,sweet,amber,white floral',
        'Secrets de HammambyID Parfumsis a Woody Floral Musk fragrance for women.Secrets de Hammamwas launched in 2008. The nose behind this fragrance is Alexandra Kosinski. Top notes are Pink Pepper, Bergamot and Mandarin Orange; middle notes are Cedar, Ylang-Ylang, Jasmine and White Flowers; base notes are Amber, Benzoin, Sandalwood, Sweet Notes, Patchouli and Musk.',
        3.85,
        121,
        NULL
      ),
(
        'Secrets-de-Volupte-17015',
        'Secrets de Volupte ID Parfums',
        'Secrets',
        'for women',
        NULL,
        'Alexandra Kosinski',
        'Pear, Bergamot and Freesia',
        'Magnolia and Jasmine',
        'Musk, Cedar and Amber',
        'floral,fruity,citrus,sweet,aquatic',
        'Secrets de VoluptebyID Parfumsis a Floral Fruity fragrance for women. The nose behind this fragrance is Alexandra Kosinski. Top notes are Pear, Bergamot and Freesia; middle notes are Magnolia and Jasmine; base notes are Musk, Cedar and Amber.',
        3.61,
        170,
        NULL
      ),
(
        'Siam-Flamboyant-17013',
        'Siam Flamboyant ID Parfums',
        'Siam',
        'for women',
        NULL,
        'Anne Flipo',
        'White Pepper and Mandarin Orange',
        'Frangipani and Orange Blossom',
        'Bourbon Vanilla and Benzoin',
        'vanilla,citrus,floral,amber,tropical',
        'Siam FlamboyantbyID Parfumsis a Amber Floral fragrance for women.Siam Flamboyantwas launched in 2012. Siam Flamboyant was created by Nicolas Beaulieu and Anne Flipo. Top notes are White Pepper and Mandarin Orange; middle notes are Frangipani and Orange Blossom; base notes are Bourbon Vanilla and Benzoin.',
        3.77,
        199,
        NULL
      ),
(
        'Sorrentina-32501',
        'Sorrentina ID Parfums',
        'Sorrentina',
        'for women',
        NULL,
        'Delphine Lebeau',
        'Bergamot, Lemon and Lily-of-the-Valley',
        'Fig, Violet Leaf, Magnolia and Cyclamen',
        'Heliotrope, Cedar and White Musk',
        'citrus,fruity,woody,floral,powdery',
        'SorrentinabyID Parfumsis a Floral Fruity fragrance for women.Sorrentinawas launched in 2015. The nose behind this fragrance is Delphine Lebeau. Top notes are Bergamot, Lemon and Lily-of-the-Valley; middle notes are Fig, Violet Leaf, Magnolia and Cyclamen; base notes are Heliotrope, Cedar and White Musk.',
        3.7,
        103,
        NULL
      ),
(
        'Tentation-de-Violettes-17014',
        'Tentation de Violettes ID Parfums',
        'Tentation',
        'for women',
        NULL,
        'Anne Flipo',
        'Raspberry, Black Currant and Pink Pepper',
        'Violet and Wisteria',
        'Iris, Sandalwood and Heliotrope',
        'powdery,violet,fruity,floral,woody',
        'Tentation de ViolettesbyID Parfumsis a Floral Woody Musk fragrance for women. Tentation de Violettes was created by Anne Flipo and Veronique Nyberg. Top notes are Raspberry, Black Currant and Pink Pepper; middle notes are Violet and Wisteria; base notes are Iris, Sandalwood and Heliotrope.',
        3.5,
        149,
        NULL
      ),
(
        'Terre-Inca-67655',
        'Terre Inca ID Parfums',
        'Terre',
        'for men',
        NULL,
        'Vincent Ricord',
        'Lemon, Bergamot and Grapefruit',
        'Cacao and Coffee',
        'Vetiver, Patchouli and Cedar',
        'citrus,woody,warm spicy,aromatic,cacao',
        'Terre IncabyID Parfumsis a Woody Spicy fragrance for men.Terre Incawas launched in 2017. The nose behind this fragrance is Vincent Ricord. Top notes are Lemon, Bergamot and Grapefruit; middle notes are Cacao and Coffee; base notes are Vetiver, Patchouli and Cedar.',
        4,
        10,
        NULL
      ),
(
        'Vertige-10637',
        'Vertige ID Parfums',
        'Vertige',
        'for women',
        NULL,
        'Claire Chambert',
        'Black Currant, Red Apple, Grapefruit and Mandarin Orange',
        'Rose, Iris and Freesia',
        'Sandalwood, Patchouli, Musk and Benzoin',
        'fruity,woody,citrus,floral,powdery',
        'VertigebyID Parfumsis a Chypre Fruity fragrance for women. The nose behind this fragrance is Claire Chambert. Top notes are Black Currant, Red Apple, Grapefruit and Mandarin Orange; middle notes are Rose, Iris and Freesia; base notes are Sandalwood, Patchouli, Musk and Benzoin.',
        3.49,
        219,
        NULL
      ),
(
        'Ambra-Nera-51799',
        'Ambra Nera Il Profumiere',
        'Ambra',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'amber',
        'Ambra NerabyIl Profumiereis a Amber fragrance for women and men.Ambra Nerawas launched in 2007. The nose behind this fragrance is Massimiliano Torti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ambroxine-51800',
        'Ambroxine Il Profumiere',
        'Ambroxine',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'amber,musky',
        'AmbroxinebyIl Profumiereis a Amber fragrance for women and men.Ambroxinewas launched in 2008. The nose behind this fragrance is Massimiliano Torti.',
        4,
        7,
        NULL
      ),
(
        'Amyas-Marakesh-51801',
        'Amyas Marakesh Il Profumiere',
        'Amyas',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        NULL,
        'Amyas MarakeshbyIl Profumiereis a fragrance for women and men.Amyas Marakeshwas launched in 2012. The nose behind this fragrance is Massimiliano Torti.',
        3.5,
        2,
        NULL
      ),
(
        'Anice-Galbano-83565',
        'Anice Galbano Il Profumiere',
        'Anice',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        'Star Anise, Bergamot, Nutmeg, Fennel, Green Notes and Galbanum',
        'Cashmere Wood, Lavender, Cloves and Cedar',
        'White Musk, Patchouli, Woody Notes, Cedar and Amber',
        'woody,green,fresh spicy,soft spicy,musky',
        'Anice GalbanobyIl Profumiereis a fragrance for women and men.Anice Galbanowas launched in 2021. The nose behind this fragrance is Massimiliano Torti. Top notes are Star Anise, Bergamot, Nutmeg, Fennel, Green Notes and Galbanum; middle notes are Cashmere Wood, Lavender, Cloves and Cedar; base notes are White Musk, Patchouli, Woody Notes, Cedar and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Arabian-Nektar-51802',
        'Arabian Nektar Il Profumiere',
        'Arabian',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        NULL,
        'Arabian NektarbyIl Profumiereis a Amber fragrance for women and men.Arabian Nektarwas launched in 2008. The nose behind this fragrance is Massimiliano Torti.',
        4.29,
        7,
        NULL
      ),
(
        'Black-Land-51803',
        'Black Land Il Profumiere',
        'Black',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        NULL,
        'Black LandbyIl Profumiereis a fragrance for women and men.Black Landwas launched in 2010. The nose behind this fragrance is Massimiliano Torti.',
        4,
        1,
        NULL
      ),
(
        'Bois-De-Cedrat-51804',
        'Bois De Cedrat Il Profumiere',
        'Bois',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'woody',
        'Bois De CedratbyIl Profumiereis a Woody fragrance for women and men.Bois De Cedratwas launched in 2012. The nose behind this fragrance is Massimiliano Torti.',
        3.5,
        2,
        NULL
      ),
(
        'Cacao-Bianco-d-Arabia-51295',
        'Cacao Bianco d''Arabia Il Profumiere',
        'Cacao',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        'White Chocolate',
        'Vanilla, Milk, Incense and Heliotrope',
        'Cacao, Arabian Spices, Natural Vanilla and Amber',
        'warm spicy,sweet,cacao,amber,vanilla',
        'Cacao Bianco d''ArabiabyIl Profumiereis a Amber Spicy fragrance for women and men.Cacao Bianco d''Arabiawas launched in 2012. The nose behind this fragrance is Massimiliano Torti. Top note is White Chocolate; middle notes are Vanilla, Milk, Incense and Heliotrope; base notes are Cacao, Arabian Spices, Natural Vanilla and Amber.',
        3.69,
        13,
        NULL
      ),
(
        'Caramel-Vanille-51805',
        'Caramel Vanille Il Profumiere',
        'Caramel',
        'for women',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'caramel,sweet,vanilla',
        'Caramel VanillebyIl Profumiereis a Amber Vanilla fragrance for women.Caramel Vanillewas launched in 2016. The nose behind this fragrance is Massimiliano Torti.',
        3.83,
        6,
        NULL
      ),
(
        'Cioccolato-Amaro-e-Patchouli-35434',
        'Cioccolato Amaro e Patchouli Il Profumiere',
        'Cioccolato',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'warm spicy,balsamic,woody,chocolate,patchouli',
        'Cioccolato Amaro e PatchoulibyIl Profumiereis a Amber Woody fragrance for women and men.Cioccolato Amaro e Patchouliwas launched in 2009. The nose behind this fragrance is Massimiliano Torti.',
        3.5,
        2,
        NULL
      ),
(
        'Cox-Royale-51806',
        'Cox Royale Il Profumiere',
        'Cox',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        NULL,
        'Cox RoyalebyIl Profumiereis a fragrance for women and men.Cox Royalewas launched in 2015. The nose behind this fragrance is Massimiliano Torti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Cumino-Garofano-51807',
        'Cumino Garofano Il Profumiere',
        'Cumino',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'floral,fresh spicy,warm spicy,animalic,aromatic',
        'Cumino GarofanobyIl Profumiereis a Aromatic Spicy fragrance for women and men.Cumino Garofanowas launched in 2018. The nose behind this fragrance is Massimiliano Torti.',
        3.33,
        3,
        NULL
      ),
(
        'Dolci-Sottoboschi-51808',
        'Dolci Sottoboschi Il Profumiere',
        'Dolci',
        'for women',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'sweet',
        'Dolci SottoboschibyIl Profumiereis a Amber Vanilla fragrance for women.Dolci Sottoboschiwas launched in 2017. The nose behind this fragrance is Massimiliano Torti.',
        4.18,
        11,
        NULL
      ),
(
        'Gambo-di-Rosa-51809',
        'Gambo di Rosa Il Profumiere',
        'Gambo',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'green,rose,floral',
        'Gambo di RosabyIl Profumiereis a Floral Green fragrance for women and men.Gambo di Rosawas launched in 2014. The nose behind this fragrance is Massimiliano Torti.',
        4,
        3,
        NULL
      ),
(
        'Gommoresina-Araba-51810',
        'Gommoresina Araba Il Profumiere',
        'Gommoresina',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        NULL,
        'Gommoresina ArababyIl Profumiereis a fragrance for women and men.Gommoresina Arabawas launched in 2010. The nose behind this fragrance is Massimiliano Torti.',
        3.25,
        4,
        NULL
      ),
(
        'Hot-Rhum-51811',
        'Hot Rhum Il Profumiere',
        'Hot',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'rum,woody,warm spicy',
        'Hot RhumbyIl Profumiereis a fragrance for women and men.Hot Rhumwas launched in 2009. The nose behind this fragrance is Massimiliano Torti.',
        2,
        1,
        NULL
      ),
(
        'Incenso-Copaiba-83566',
        'Incenso Copaiba Il Profumiere',
        'Incenso',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        'Incense and Thyme',
        'Labdanum, Copahu Balm and Incense',
        'Oriental notes and Woody Notes',
        'amber,warm spicy,woody,balsamic,aromatic',
        'Incenso CopaibabyIl Profumiereis a fragrance for women and men.Incenso Copaibawas launched in 2020. The nose behind this fragrance is Massimiliano Torti. Top notes are Incense and Thyme; middle notes are Labdanum, Copahu Balm and Incense; base notes are Oriental notes and Woody Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'Incenso-Grigio-Acciaio-83567',
        'Incenso Grigio Acciaio Il Profumiere',
        'Incenso',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Petitgrain, Bergamot and Orange',
        'Olibanum Sacra Resin Green, Palisander Rosewood and Rose',
        'Olibanum Sacra Resin Green, Frankincense, Ambergris and Sandalwood',
        'citrus,amber,woody,fresh spicy,aromatic',
        'Incenso Grigio AcciaiobyIl Profumiereis a fragrance for women and men.Incenso Grigio Acciaiowas launched in 2022. Top notes are Grapefruit, Petitgrain, Bergamot and Orange; middle notes are Olibanum Sacra Resin Green, Palisander Rosewood and Rose; base notes are Olibanum Sacra Resin Green, Frankincense, Ambergris and Sandalwood.',
        5,
        2,
        NULL
      ),
(
        'Jamila-35586',
        'Jamila Il Profumiere',
        'Jamila',
        'for women',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'powdery,white floral,vanilla,floral,citrus',
        'JamilabyIl Profumiereis a Floral fragrance for women.Jamilawas launched in 2013. The nose behind this fragrance is Massimiliano Torti.',
        3.8,
        5,
        NULL
      ),
(
        'Jour-De-Rose-51812',
        'Jour De Rose Il Profumiere',
        'Jour',
        'for women',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Jour De RosebyIl Profumiereis a Floral fragrance for women.Jour De Rosewas launched in 2014. The nose behind this fragrance is Massimiliano Torti.',
        4,
        3,
        NULL
      ),
(
        'Lemon-Bah-51813',
        'Lemon-Bah Il Profumiere',
        'Lemon-Bah',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'citrus,aromatic',
        'Lemon-BahbyIl Profumiereis a fragrance for women and men.Lemon-Bahwas launched in 2009. The nose behind this fragrance is Massimiliano Torti.',
        2,
        1,
        NULL
      ),
(
        'Limone-Fougere-83564',
        'Limone Fougère Il Profumiere',
        'Limone',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        'Mandarin Orange, Orange Blossom, Lemongrass, Bergamot and Lemon',
        'Lily of the Valley, Geranium, Jasmine, Rose, Iris and Ozonic notes',
        'Resins, Sandalwood, Tonka Bean, Vetiver, Cedar and Amber',
        'citrus,woody,white floral,aromatic,amber',
        'Limone FougèrebyIl Profumiereis a fragrance for women and men. This is a new fragrance.Limone Fougèrewas launched in 2023. The nose behind this fragrance is Massimiliano Torti. Top notes are Mandarin Orange, Orange Blossom, Lemongrass, Bergamot and Lemon; middle notes are Lily of the Valley, Geranium, Jasmine, Rose, Iris and Ozonic notes; base notes are Resins, Sandalwood, Tonka Bean, Vetiver, Cedar and Amber.',
        5,
        1,
        NULL
      ),
(
        'Liquirizia-Amara-77061',
        'Liquirizia Amara Il Profumiere',
        'Liquirizia',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        'Lemon, Bergamot, Artemisia, Lavender and Licorice',
        'Licorice, Spun Sugar, Labdanum, Cumin and Violet',
        'Vanilla, Chocolate, Coconut, Tiare Flower and Amber',
        'sweet,amber,citrus,fresh spicy,aromatic',
        'Liquirizia AmarabyIl Profumiereis a fragrance for women and men.Liquirizia Amarawas launched in 2021. The nose behind this fragrance is Massimiliano Torti. Top notes are Lemon, Bergamot, Artemisia, Lavender and Licorice; middle notes are Licorice, Spun Sugar, Labdanum, Cumin and Violet; base notes are Vanilla, Chocolate, Coconut, Tiare Flower and Amber.',
        4,
        2,
        NULL
      ),
(
        'Mandarine-Mousse-35588',
        'Mandarine Mousse Il Profumiere',
        'Mandarine',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'citrus,white floral',
        'Mandarine MoussebyIl Profumiereis a Chypre Floral fragrance for women and men.Mandarine Moussewas launched in 2007. The nose behind this fragrance is Massimiliano Torti.',
        4.17,
        6,
        NULL
      ),
(
        'Mexican-Lyme-35589',
        'Mexican Lyme Il Profumiere',
        'Mexican',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'citrus,woody',
        'Mexican LymebyIl Profumiereis a Citrus Aromatic fragrance for women and men.Mexican Lymewas launched in 2010. The nose behind this fragrance is Massimiliano Torti.',
        4.2,
        5,
        NULL
      ),
(
        'Miele-Amaro-35675',
        'Miele Amaro Il Profumiere',
        'Miele',
        'for women',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'fruity,fresh spicy,almond,sweet,honey',
        'Miele AmarobyIl Profumiereis a Amber Vanilla fragrance for women.Miele Amarowas launched in 2007. The nose behind this fragrance is Massimiliano Torti.',
        3.94,
        17,
        NULL
      ),
(
        'Muschio-04-in-Sintesi-83568',
        'Muschio 04 in Sintesi Il Profumiere',
        'Muschio',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        'Black Currant, Raspberry and Bergamot',
        'Geranium, Jasmine, Nutmeg and Ylang Ylang',
        'Tonka Bean, Amber, Musk and Iris',
        'fresh spicy,fruity,sweet,aromatic,amber',
        'Muschio 04 in SintesibyIl Profumiereis a fragrance for women and men. The nose behind this fragrance is Massimiliano Torti. Top notes are Black Currant, Raspberry and Bergamot; middle notes are Geranium, Jasmine, Nutmeg and Ylang Ylang; base notes are Tonka Bean, Amber, Musk and Iris.',
        NULL,
        NULL,
        NULL
      ),
(
        'Olibanum-Della-Somalia-51814',
        'Olibanum Della Somalia Il Profumiere',
        'Olibanum',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'amber,fresh spicy,warm spicy,woody',
        'Olibanum Della SomaliabyIl Profumiereis a Amber fragrance for women and men.Olibanum Della Somaliawas launched in 2010. The nose behind this fragrance is Massimiliano Torti.',
        3.75,
        4,
        NULL
      ),
(
        'Orange-Douce-35676',
        'Orange Douce Il Profumiere',
        'Orange',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'citrus,amber,sweet,white floral,musky',
        'Orange DoucebyIl Profumiereis a Citrus Gourmand fragrance for women and men.Orange Doucewas launched in 2009. The nose behind this fragrance is Massimiliano Torti.',
        3,
        1,
        NULL
      ),
(
        'Oud-Extreme-51815',
        'Oud Extreme Il Profumiere',
        'Oud',
        'for men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'oud,fresh spicy',
        'Oud ExtremebyIl Profumiereis a Amber Woody fragrance for men.Oud Extremewas launched in 2009. The nose behind this fragrance is Massimiliano Torti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Patchouly-Secco-Indonesia-51841',
        'Patchouly Secco Indonesia Il Profumiere',
        'Patchouly',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'patchouli,woody,warm spicy,earthy,balsamic',
        'Patchouly Secco IndonesiabyIl Profumiereis a Woody fragrance for women and men.Patchouly Secco Indonesiawas launched in 2000. The nose behind this fragrance is Massimiliano Torti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Payago-51842',
        'Payago Il Profumiere',
        'Payago',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        NULL,
        'PayagobyIl Profumiereis a fragrance for women and men.Payagowas launched in 2016. The nose behind this fragrance is Massimiliano Torti.',
        3,
        2,
        NULL
      ),
(
        'Pepe-Bianco-e-Aoud-35700',
        'Pepe Bianco e Aoud Il Profumiere',
        'Pepe',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'woody,amber,aromatic,balsamic,warm spicy',
        'Pepe Bianco e AoudbyIl Profumiereis a Woody Aromatic fragrance for women and men.Pepe Bianco e Aoudwas launched in 2005. The nose behind this fragrance is Massimiliano Torti.',
        3,
        3,
        NULL
      ),
(
        'Pimento-Spice-51843',
        'Pimento Spice Il Profumiere',
        'Pimento',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'warm spicy,fresh',
        'Pimento SpicebyIl Profumiereis a Aromatic Spicy fragrance for women and men.Pimento Spicewas launched in 2018. The nose behind this fragrance is Massimiliano Torti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Radica-Aoud-35702',
        'Radica Aoud Il Profumiere',
        'Radica',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'woody,amber,fresh spicy,warm spicy,smoky',
        'Radica AoudbyIl Profumiereis a Woody Aromatic fragrance for women and men.Radica Aoudwas launched in 2005. The nose behind this fragrance is Massimiliano Torti.',
        4,
        5,
        NULL
      ),
(
        'Radice-Verde-di-Vetyver-35703',
        'Radice Verde di Vetyver Il Profumiere',
        'Radice',
        'for women and men',
        NULL,
        'Massimiliano Torti',
        NULL,
        NULL,
        NULL,
        'woody,green,aromatic,fresh,warm spicy',
        'Radice Verde di VetyverbyIl Profumiereis a Woody Chypre fragrance for women and men.Radice Verde di Vetyverwas launched in 2008. The nose behind this fragrance is Massimiliano Torti.',
        NULL,
        NULL,
        NULL
      );
