
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Majmua-e-Kamil-41922',
        'Majmua-e-Kamil Junaid Jamshed',
        'Majmua-e-Kamil',
        'for men',
        NULL,
        NULL,
        'Raspberry, Toffee and Orange',
        'Jasmine, Violet, Patchouli and Rose',
        'Amber, Musk and Vanilla',
        'white floral,fruity,sweet,powdery,violet',
        'Majmua-e-KamilbyJunaid Jamshedis a Amber Woody fragrance for men.Majmua-e-Kamilwas launched in 2016. Top notes are Raspberry, Toffee and Orange; middle notes are Jasmine, Violet, Patchouli and Rose; base notes are Amber, Musk and Vanilla.',
        4.25,
        4,
        NULL
      ),
(
        'Musk-e-Shaheer-41921',
        'Musk-e-Shaheer Junaid Jamshed',
        'Musk-e-Shaheer',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,citrus,woody,powdery,sweet',
        'Musk-e-ShaheerbyJunaid Jamshedis a Aromatic fragrance for men.Musk-e-Shaheerwas launched in 2016.',
        4.4,
        20,
        NULL
      ),
(
        'Musky-Rose-41927',
        'Musky Rose Junaid Jamshed',
        'Musky',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,musky,rose,white floral,powdery',
        'Musky RosebyJunaid Jamshedis a Amber Floral fragrance for men.Musky Rosewas launched in 2015.',
        5,
        2,
        NULL
      ),
(
        'Pure-Essence-63664',
        'Pure Essence Junaid Jamshed',
        'Pure',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh,sweet,aldehydic,citrus,floral',
        'Pure EssencebyJunaid Jamshedis a Floral Woody Musk fragrance for men.Pure Essencewas launched in 2015.',
        4,
        1,
        NULL
      ),
(
        'Ziya-Gold-56872',
        'Ziya Gold Junaid Jamshed',
        'Ziya',
        'for men',
        NULL,
        NULL,
        'Lemon and Cardamom',
        'Agarwood (Oud) and Violet',
        'Musk and Amber',
        'citrus,oud,powdery,violet,amber',
        'Ziya GoldbyJunaid Jamshedis a Amber fragrance for men.Ziya Goldwas launched in 2019. Top notes are Lemon and Cardamom; middle notes are Agarwood (Oud) and Violet; base notes are Musk and Amber.',
        5,
        1,
        NULL
      ),
(
        'Ziya-Platinum-56870',
        'Ziya Platinum Junaid Jamshed',
        'Ziya',
        'for men',
        NULL,
        NULL,
        'Aldehydes and Bergamot',
        'White Flowers',
        'Musk',
        'aldehydic,citrus,musky,white floral,fresh',
        'Ziya PlatinumbyJunaid Jamshedis a Floral fragrance for men.Ziya Platinumwas launched in 2019. Top notes are Aldehydes and Bergamot; middle note is White Flowers; base note is Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ziya-Silver-56873',
        'Ziya Silver Junaid Jamshed',
        'Ziya',
        'for men',
        NULL,
        NULL,
        'Lemon',
        'Rose and Magnolia',
        'Woody Notes and Musk',
        'citrus,floral,musky,rose,woody',
        'Ziya SilverbyJunaid Jamshedis a Floral fragrance for men.Ziya Silverwas launched in 2019. Top note is Lemon; middle notes are Rose and Magnolia; base notes are Woody Notes and Musk.',
        3,
        2,
        NULL
      ),
(
        'J-Adore-56856',
        'J. Adore Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        'Bergamot, Grapefruit, Mandarin Orange and Green Leaves',
        'Jasmine Sambac, Lily-of-the-Valley, Orris Root, Rose, Milk and White Flowers',
        'Musk, Cedar, Sandalwood, Vanilla, Patchouli, Vetiver and Oakmoss',
        'woody,citrus,white floral,powdery,earthy',
        'J. AdorebyJunaid Jamshedis a Amber Floral fragrance for women.J. Adorewas launched in 2019. Top notes are Bergamot, Grapefruit, Mandarin Orange and Green Leaves; middle notes are Jasmine Sambac, Lily-of-the-Valley, Orris Root, Rose, Milk and White Flowers; base notes are Musk, Cedar, Sandalwood, Vanilla, Patchouli, Vetiver and Oakmoss.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Burn-56874',
        'J. Burn Junaid Jamshed',
        'J.',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. BurnbyJunaid Jamshedis a fragrance for men.J. Burnwas launched in 2014.',
        4,
        2,
        NULL
      ),
(
        'J-Colors-56854',
        'J. Colors Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. ColorsbyJunaid Jamshedis a fragrance for women.J. Colorswas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Ecstasy-56852',
        'J. Ecstasy Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        'Bergamot, Green Leaves, Pear, Apple and Melon',
        'Raspberry, Jasmine, Lily-of-the-Valley, Palisander Rosewood and Ylang-Ylang',
        'Musk, Cedar and Patchouli',
        'woody,fruity,sweet,white floral,green',
        'J. EcstasybyJunaid Jamshedis a Chypre Floral fragrance for women.J. Ecstasywas launched in 2019. Top notes are Bergamot, Green Leaves, Pear, Apple and Melon; middle notes are Raspberry, Jasmine, Lily-of-the-Valley, Palisander Rosewood and Ylang-Ylang; base notes are Musk, Cedar and Patchouli.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Fantasy-56851',
        'J. Fantasy Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        'Passionfruit and Raspberry',
        'Floral Notes, Jasmine, Cyclamen, Orange Blossom and Violet',
        'Musk, Sandalwood, Amber and Vanilla',
        'floral,powdery,white floral,fruity,sweet',
        'J. FantasybyJunaid Jamshedis a Floral Fruity fragrance for women.J. Fantasywas launched in 2019. Top notes are Passionfruit and Raspberry; middle notes are Floral Notes, Jasmine, Cyclamen, Orange Blossom and Violet; base notes are Musk, Sandalwood, Amber and Vanilla.',
        4.5,
        2,
        NULL
      ),
(
        'J-Forever-56859',
        'J. Forever Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. ForeverbyJunaid Jamshedis a fragrance for women.J. Foreverwas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Fresh-56855',
        'J. Fresh Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. FreshbyJunaid Jamshedis a fragrance for women.J. Freshwas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Mark-56875',
        'J. Mark Junaid Jamshed',
        'J.',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. MarkbyJunaid Jamshedis a fragrance for men.J. Markwas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Pleasant-56853',
        'J. Pleasant Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        'Citruses, Lemon, Green Leaves and Orange',
        'Floral Notes, Jasmine, Palisander Rosewood, Ylang-Ylang and Cyclamen',
        'Woody Notes, Cedar, Musk, Patchouli and Vanilla',
        'woody,citrus,floral,sweet,fresh',
        'J. PleasantbyJunaid Jamshedis a Amber Floral fragrance for women.J. Pleasantwas launched in 2019. Top notes are Citruses, Lemon, Green Leaves and Orange; middle notes are Floral Notes, Jasmine, Palisander Rosewood, Ylang-Ylang and Cyclamen; base notes are Woody Notes, Cedar, Musk, Patchouli and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Senses-56858',
        'J. Senses Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. SensesbyJunaid Jamshedis a fragrance for women.J. Senseswas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Shine-56876',
        'J. Shine Junaid Jamshed',
        'J.',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. ShinebyJunaid Jamshedis a fragrance for men.J. Shinewas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Spell-56850',
        'J. Spell Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        'Citruses, Bergamot and Green Leaves',
        'Floral Notes, Jasmine and Palisander Rosewood',
        'Resin, Woody Notes, Vanilla, Cedar and Sandalwood',
        'woody,citrus,floral,amber,green',
        'J. SpellbyJunaid Jamshedis a Floral Green fragrance for women.J. Spellwas launched in 2019. Top notes are Citruses, Bergamot and Green Leaves; middle notes are Floral Notes, Jasmine and Palisander Rosewood; base notes are Resin, Woody Notes, Vanilla, Cedar and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-Surprise-Me-56860',
        'J. Surprise Me Junaid Jamshed',
        'J.',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'J. Surprise MebyJunaid Jamshedis a fragrance for women.J. Surprise Mewas launched in 2014.',
        4,
        1,
        NULL
      ),
(
        'Citrine-29206',
        'Citrine Junaid Jamshed',
        'Citrine',
        'for women',
        NULL,
        NULL,
        'Litchi, Kiwi and Quince',
        'White Chocolate and Jasmine',
        'Orris Root, Musk and Woody Notes',
        'fruity,sweet,tropical,white floral,fresh',
        'CitrinebyJunaid Jamshedis a Floral Fruity Gourmand fragrance for women.Citrinewas launched in 2014. Top notes are Litchi, Kiwi and Quince; middle notes are White Chocolate and Jasmine; base notes are Orris Root, Musk and Woody Notes.',
        5,
        3,
        NULL
      ),
(
        'Emerald-29210',
        'Emerald Junaid Jamshed',
        'Emerald',
        'for women',
        NULL,
        NULL,
        'Fruity Notes and Sour Cherry',
        'Almond, Sweet Notes and Marshmallow',
        'Woody Notes and Powdery Notes',
        'fruity,sweet,almond,woody,nutty',
        'EmeraldbyJunaid Jamshedis a Floral Fruity Gourmand fragrance for women.Emeraldwas launched in 2014. Top notes are Fruity Notes and Sour Cherry; middle notes are Almond, Sweet Notes and Marshmallow; base notes are Woody Notes and Powdery Notes.',
        4,
        1,
        NULL
      ),
(
        'Ruby-29207',
        'Ruby Junaid Jamshed',
        'Ruby',
        'for women',
        NULL,
        NULL,
        'Ambrette (Musk Mallow), Pear and Grapefruit',
        'Turkish Rose, Ylang-Ylang, Dried Plum and Plum',
        'Amber, Patchouli, Musk, Madagascar Vanilla and Cashmere Wood',
        'musky,amber,floral,woody,sweet',
        'RubybyJunaid Jamshedis a Floral Woody Musk fragrance for women.Rubywas launched in 2014. Top notes are Ambrette (Musk Mallow), Pear and Grapefruit; middle notes are Turkish Rose, Ylang-Ylang, Dried Plum and Plum; base notes are Amber, Patchouli, Musk, Madagascar Vanilla and Cashmere Wood.',
        4.5,
        2,
        NULL
      ),
(
        'Sapphire-29209',
        'Sapphire Junaid Jamshed',
        'Sapphire',
        'for women',
        NULL,
        NULL,
        'Litchi and Ambrette (Musk Mallow)',
        'Iris and Osmanthus',
        'Amber, Patchouli and Musk',
        'fruity,musky,tropical,floral,fresh',
        'SapphirebyJunaid Jamshedis a Floral Woody Musk fragrance for women.Sapphirewas launched in 2014. Top notes are Litchi and Ambrette (Musk Mallow); middle notes are Iris and Osmanthus; base notes are Amber, Patchouli and Musk.',
        4.75,
        4,
        NULL
      ),
(
        'Topaz-29208',
        'Topaz Junaid Jamshed',
        'Topaz',
        'for women',
        NULL,
        NULL,
        'Punch, Mandarin Orange and Pear',
        'Honeysuckle, Peach and Orange Blossom',
        'Honey, Vanilla and Woody Notes',
        'fruity,white floral,sweet,citrus,honey',
        'TopazbyJunaid Jamshedis a Floral Fruity fragrance for women.Topazwas launched in 2014. Top notes are Punch, Mandarin Orange and Pear; middle notes are Honeysuckle, Peach and Orange Blossom; base notes are Honey, Vanilla and Woody Notes.',
        5,
        3,
        NULL
      ),
(
        'Elegant-52390',
        'Elegant Junaid Jamshed',
        'Elegant',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,earthy,white floral,citrus,fruity',
        'ElegantbyJunaid Jamshedis a Chypre Floral fragrance for women.Elegantwas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Inspire-52389',
        'Inspire Junaid Jamshed',
        'Inspire',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,aromatic,woody,citrus,yellow floral',
        'InspirebyJunaid Jamshedis a Floral fragrance for women.Inspirewas launched in 2018.',
        4,
        1,
        NULL
      ),
(
        'Paradise-52391',
        'Paradise Junaid Jamshed',
        'Paradise',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,vanilla,rose,powdery',
        'ParadisebyJunaid Jamshedis a Floral Fruity fragrance for women.Paradisewas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Evolution-29193',
        'Evolution Junaid Jamshed',
        'Evolution',
        'for men',
        NULL,
        NULL,
        'Yuzu and Lemon',
        'Lotus, Green Notes, Water Mint and Water Notes',
        'White Musk and Cedar',
        'green,citrus,aquatic,aromatic,woody',
        'EvolutionbyJunaid Jamshedis a Aromatic Aquatic fragrance for men.Evolutionwas launched in 2014. Top notes are Yuzu and Lemon; middle notes are Lotus, Green Notes, Water Mint and Water Notes; base notes are White Musk and Cedar.',
        NULL,
        NULL,
        NULL
      ),
(
        'Fateh-29242',
        'Fateh Junaid Jamshed',
        'Fateh',
        'for men',
        NULL,
        NULL,
        'Citruses',
        'Spicy Notes',
        'Woody Notes',
        'citrus,woody,warm spicy,fresh',
        'FatehbyJunaid Jamshedis a Woody Aromatic fragrance for men.Fatehwas launched in 2014. Top note is Citruses; middle note is Spicy Notes; base note is Woody Notes.',
        4,
        1,
        NULL
      ),
(
        'Mehak-29191',
        'Mehak Junaid Jamshed',
        'Mehak',
        'for women',
        NULL,
        NULL,
        'Sweet Notes and Rose',
        'Floral Notes and Patchouli',
        'Woody Notes',
        'woody,floral,patchouli,rose,sweet',
        'MehakbyJunaid Jamshedis a Floral Woody Musk fragrance for women.Mehakwas launched in 2014. Top notes are Sweet Notes and Rose; middle notes are Floral Notes and Patchouli; base note is Woody Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'Remo-29187',
        'Remo Junaid Jamshed',
        'Remo',
        'for men',
        NULL,
        NULL,
        'Cinnamon, Artemisia, Bergamot and Gardenia',
        'Vetiver, Pelargonium, Patchouli and Sandalwood',
        'Oakmoss, Amber and Leather',
        'woody,earthy,aromatic,mossy,warm spicy',
        'RemobyJunaid Jamshedis a Amber Woody fragrance for men.Remowas launched in 2014. Top notes are Cinnamon, Artemisia, Bergamot and Gardenia; middle notes are Vetiver, Pelargonium, Patchouli and Sandalwood; base notes are Oakmoss, Amber and Leather.',
        4.25,
        4,
        NULL
      ),
(
        'Saba-29204',
        'Saba Junaid Jamshed',
        'Saba',
        'for women',
        NULL,
        NULL,
        'Sweet Notes and Lily',
        'Saffron and Floral Notes',
        'Sandalwood',
        'sweet,woody,warm spicy,white floral,powdery',
        'SababyJunaid Jamshedis a Floral fragrance for women.Sabawas launched in 2014. Top notes are Sweet Notes and Lily; middle notes are Saffron and Floral Notes; base note is Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Tabeen-29188',
        'Tabeen Junaid Jamshed',
        'Tabeen',
        'for women',
        NULL,
        NULL,
        'Violet Leaf, Ylang-Ylang, Tuberose and Orange Blossom',
        'Peach, Plum, Narcissus and Jasmine',
        'Sandalwood, Vetiver, Vanilla, Amber and Musk',
        'white floral,woody,sweet,yellow floral,fruity',
        'TabeenbyJunaid Jamshedis a Floral Woody Musk fragrance for women.Tabeenwas launched in 2014. Top notes are Violet Leaf, Ylang-Ylang, Tuberose and Orange Blossom; middle notes are Peach, Plum, Narcissus and Jasmine; base notes are Sandalwood, Vetiver, Vanilla, Amber and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Homme-Noir-82833',
        'Homme Noir Just Jack',
        'Homme',
        'for men',
        NULL,
        NULL,
        'Pink Pepper and Bergamot',
        'Spicy Notes, Rosemary and Geranium',
        'Patchouli, Balsamic Notes, Leather and Amber',
        'warm spicy,patchouli,woody,fresh spicy,leather',
        'Homme NoirbyJust Jackis a Leather fragrance for men. Top notes are Pink Pepper and Bergamot; middle notes are Spicy Notes, Rosemary and Geranium; base notes are Patchouli, Balsamic Notes, Leather and Amber.',
        4,
        50,
        NULL
      ),
(
        'Italian-Leather-82834',
        'Italian Leather Just Jack',
        'Italian',
        'for women and men',
        NULL,
        NULL,
        'Raspberry and Saffron',
        'Night Blooming Jasmine, Thyme and Olibanum',
        'Suede and Amberwood',
        'leather,fruity,musky,sweet,warm spicy',
        'Italian LeatherbyJust Jackis a Leather fragrance for women and men. Top notes are Raspberry and Saffron; middle notes are Night Blooming Jasmine, Thyme and Olibanum; base notes are Suede and Amberwood.',
        3.71,
        80,
        NULL
      ),
(
        'Lady-Noir-82835',
        'Lady Noir Just Jack',
        'Lady',
        'for women',
        NULL,
        NULL,
        'Bergamot and Orange',
        'Jasmine and Rose',
        'Amber, Sandalwood and Vanilla',
        'citrus,amber,woody,powdery,vanilla',
        'Lady NoirbyJust Jackis a Amber Floral fragrance for women. Top notes are Bergamot and Orange; middle notes are Jasmine and Rose; base notes are Amber, Sandalwood and Vanilla.',
        4.11,
        36,
        NULL
      ),
(
        'Neroli-82830',
        'Neroli Just Jack',
        'Neroli',
        'for men',
        NULL,
        NULL,
        'Sicilian Lemon, Bergamot, Neroli, Bitter Orange, Tangerine, Lavender, Rosemary and Myrtle',
        'Neroli, Jasmine, Orange Blossom and Pitosporum',
        'Angelica, Ambrette and Amber',
        'citrus,white floral,aromatic,fresh spicy',
        'NerolibyJust Jackis a fragrance for men. Top notes are Sicilian Lemon, Bergamot, Neroli, Bitter Orange, Tangerine, Lavender, Rosemary and Myrtle; middle notes are Neroli, Jasmine, Orange Blossom and Pitosporum; base notes are Angelica, Ambrette and Amber.',
        3.67,
        57,
        NULL
      ),
(
        'Noir-Endurance-83690',
        'Noir Endurance Just Jack',
        'Noir',
        'for women',
        NULL,
        NULL,
        'Clove, Cardamom, Strawberry, Pink Pepper, Citruses and Neroli',
        'Iris, Lily of the Valley and Jasmine',
        'Vanilla, Amber, Sandalwood and Musk',
        'warm spicy,powdery,vanilla,amber,sweet',
        'Noir EndurancebyJust Jackis a fragrance for women.Noir Endurancewas launched in 2021. Top notes are Clove, Cardamom, Strawberry, Pink Pepper, Citruses and Neroli; middle notes are Iris, Lily of the Valley and Jasmine; base notes are Vanilla, Amber, Sandalwood and Musk.',
        4.24,
        80,
        NULL
      ),
(
        'Orchid-Noir-82839',
        'Orchid Noir Just Jack',
        'Orchid',
        'for women',
        NULL,
        NULL,
        'Black Currant, Bergamot, Ylang-Ylang and Orange',
        'Spicy Notes, Fruity Notes, Jasmine and Gardenia',
        'Patchouli, Incense, Vanilla, Amber and Musk',
        'warm spicy,amber,patchouli,woody,balsamic',
        'Orchid NoirbyJust Jackis a Amber Floral fragrance for women. Top notes are Black Currant, Bergamot, Ylang-Ylang and Orange; middle notes are Spicy Notes, Fruity Notes, Jasmine and Gardenia; base notes are Patchouli, Incense, Vanilla, Amber and Musk.',
        4.11,
        74,
        NULL
      ),
(
        'Oud-Oak-82832',
        'Oud Oak Just Jack',
        'Oud',
        'for men',
        NULL,
        NULL,
        'Cardamom and Pepper',
        'Oud, Vanilla and Amber',
        'Vetiver, Sandalwood and Tonka',
        'warm spicy,oud,aromatic,woody,fresh spicy',
        'Oud OakbyJust Jackis a Woody Aromatic fragrance for men. Top notes are Cardamom and Pepper; middle notes are Oud, Vanilla and Amber; base notes are Vetiver, Sandalwood and Tonka.',
        4,
        40,
        NULL
      ),
(
        'Patchouli-82837',
        'Patchouli Just Jack',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, White Flowers and Peony',
        'Rose and Jasmine',
        'Patchouli and Woody Notes',
        'patchouli,woody,rose,citrus,warm spicy',
        'PatchoulibyJust Jackis a Chypre Floral fragrance for women and men. Top notes are Bergamot, White Flowers and Peony; middle notes are Rose and Jasmine; base notes are Patchouli and Woody Notes.',
        4.41,
        22,
        NULL
      ),
(
        'Simply-Blanc-82838',
        'Simply Blanc Just Jack',
        'Simply',
        'for women and men',
        NULL,
        NULL,
        'Ylang-Ylang, Bergamot, Cardamom and Pepper',
        'Tuberose and Jasmine',
        'Amber and Benzoin',
        'white floral,yellow floral,amber,tuberose,warm spicy',
        'Simply BlancbyJust Jackis a Amber Floral fragrance for women and men. Top notes are Ylang-Ylang, Bergamot, Cardamom and Pepper; middle notes are Tuberose and Jasmine; base notes are Amber and Benzoin.',
        4.18,
        97,
        NULL
      ),
(
        'Tobacco-Leaf-82831',
        'Tobacco Leaf Just Jack',
        'Tobacco',
        'for women and men',
        NULL,
        NULL,
        'Tobacco and Spicy Notes',
        'Tobacco, Vanilla, Tonka and Cacao',
        'Dried Fruits and Woody Notes',
        'sweet,vanilla,tobacco,warm spicy,fruity',
        'Tobacco LeafbyJust Jackis a Woody Aromatic fragrance for women and men. Top notes are Tobacco and Spicy Notes; middle notes are Tobacco, Vanilla, Tonka and Cacao; base notes are Dried Fruits and Woody Notes.',
        4.1,
        206,
        NULL
      ),
(
        'Vetiver-83032',
        'Vetiver Just Jack',
        'Vetiver',
        'for men',
        NULL,
        NULL,
        'Grapefruit and African Orange Flower',
        'Vetiver, Orris, Sage and Nutmeg',
        'Amberwood, oak moss and Pimento',
        'woody,aromatic,citrus,earthy,white floral',
        'VetiverbyJust Jackis a fragrance for men.Vetiverwas launched in 2019. Top notes are Grapefruit and African Orange Flower; middle notes are Vetiver, Orris, Sage and Nutmeg; base notes are Amberwood, oak moss and Pimento.',
        4.3,
        92,
        NULL
      ),
(
        'Wild-Orchid-82836',
        'Wild Orchid Just Jack',
        'Wild',
        'for women',
        NULL,
        NULL,
        'Honey, Bergamot and Orange',
        'Turkish Rose, Orange Blossom and Jasmine',
        'Myrrh, Balsamic Notes, Sandalwood and Labdanum',
        'amber,citrus,white floral,rose,sweet',
        'Wild OrchidbyJust Jackis a Amber Floral fragrance for women. Top notes are Honey, Bergamot and Orange; middle notes are Turkish Rose, Orange Blossom and Jasmine; base notes are Myrrh, Balsamic Notes, Sandalwood and Labdanum.',
        3.6,
        35,
        NULL
      ),
(
        'Amalfi-Coast-82840',
        'Amalfi Coast Just Jack',
        'Amalfi',
        'for women and men',
        NULL,
        NULL,
        'Citron, Grapefruit, Mint, Black Currant and Tarragon',
        'Orange Blossom, Jasmine, Black Pepper and Coriander',
        'Musk, Vetiver, Labdanum and Amber',
        'citrus,aromatic,white floral,fresh spicy,green',
        'Amalfi CoastbyJust Jackis a fragrance for women and men. Top notes are Citron, Grapefruit, Mint, Black Currant and Tarragon; middle notes are Orange Blossom, Jasmine, Black Pepper and Coriander; base notes are Musk, Vetiver, Labdanum and Amber.',
        3.78,
        54,
        NULL
      ),
(
        'Fanta-Fab-82841',
        'Fanta Fab Just Jack',
        'Fanta',
        'for women and men',
        NULL,
        NULL,
        'Leather and Almond',
        'Clary Sage, Lavender and Tonka',
        'White Woods, Amber, Orris, Vanilla and Cashmeran',
        'aromatic,woody,lavender,leather,amber',
        'Fanta FabbyJust Jackis a Woody Aromatic fragrance for women and men. Top notes are Leather and Almond; middle notes are Clary Sage, Lavender and Tonka; base notes are White Woods, Amber, Orris, Vanilla and Cashmeran.',
        3.97,
        33,
        NULL
      ),
(
        'London-Eye-82844',
        'London Eye Just Jack',
        'London',
        'for women and men',
        NULL,
        NULL,
        'Cumin, Black Pepper, Saffron, Coriander, Cardamom and Coffee',
        'Frankincense, Jasmine and Geranium',
        'Oud, Musk, Woody Notes, Cedar and Birch',
        'fresh spicy,oud,warm spicy,musky,woody',
        'London EyebyJust Jackis a Woody Aromatic fragrance for women and men. Top notes are Cumin, Black Pepper, Saffron, Coriander, Cardamom and Coffee; middle notes are Frankincense, Jasmine and Geranium; base notes are Oud, Musk, Woody Notes, Cedar and Birch.',
        3.67,
        30,
        NULL
      ),
(
        'Santal-Bloom-82846',
        'Santal Bloom Just Jack',
        'Santal',
        'for women',
        NULL,
        NULL,
        'Carrot Seeds, Fenugreek, Cinnamon, Spices and Cumin',
        'Ylang-Ylang, Jasmine and Rose',
        'Sandalwood, Benzoin, Cedar, Musk and Oud',
        'woody,warm spicy,powdery,fresh spicy,musky',
        'Santal BloombyJust Jackis a Amber Spicy fragrance for women. Top notes are Carrot Seeds, Fenugreek, Cinnamon, Spices and Cumin; middle notes are Ylang-Ylang, Jasmine and Rose; base notes are Sandalwood, Benzoin, Cedar, Musk and Oud.',
        3.62,
        13,
        NULL
      ),
(
        'Scarlet-Jas-82843',
        'Scarlet Jas Just Jack',
        'Scarlet',
        'for women',
        NULL,
        NULL,
        'White Pepper, Black Pepper, Cinnamon, Bergamot, Cardamom, Ginger and Sicilian Mandarin',
        'Ylang-Ylang, Jasmine Sambac, Clary Sage and Neroli',
        'Woody Notes, Amber, Labdanum and Leather',
        'yellow floral,white floral,woody,sweet,warm spicy',
        'Scarlet JasbyJust Jackis a Amber Floral fragrance for women. Top notes are White Pepper, Black Pepper, Cinnamon, Bergamot, Cardamom, Ginger and Sicilian Mandarin; middle notes are Ylang-Ylang, Jasmine Sambac, Clary Sage and Neroli; base notes are Woody Notes, Amber, Labdanum and Leather.',
        4.36,
        25,
        NULL
      ),
(
        'The-Dark-82845',
        'The Dark Just Jack',
        'The',
        'for women and men',
        NULL,
        NULL,
        'Rose and Saffron',
        'Oud',
        'Frankincense and Sandalwood',
        'oud,amber,fresh spicy,warm spicy,rose',
        'The DarkbyJust Jackis a Woody Aromatic fragrance for women and men. Top notes are Rose and Saffron; middle note is Oud; base notes are Frankincense and Sandalwood.',
        3.82,
        11,
        NULL
      ),
(
        'X-Version-82842',
        'X Version Just Jack',
        'X',
        'for women and men',
        NULL,
        NULL,
        'Ginger, Pink Pepper and Cardamom',
        'Orris, Jasmine Sambac and Hedione',
        'Cinnamon, Vetiver and Moss',
        'warm spicy,earthy,cinnamon,iris,aromatic',
        'X VersionbyJust Jackis a Woody Aromatic fragrance for women and men. Top notes are Ginger, Pink Pepper and Cardamom; middle notes are Orris, Jasmine Sambac and Hedione; base notes are Cinnamon, Vetiver and Moss.',
        3.6,
        15,
        NULL
      ),
(
        'Black-Tuxedo-82849',
        'Black Tuxedo Just Jack',
        'Black',
        'for men',
        NULL,
        NULL,
        'Apple Blossom and Peach',
        'Pineapple blossom',
        'Patchouli, Wild Rose and Musk',
        'fruity,floral,patchouli,musky,rose',
        'Black TuxedobyJust Jackis a Floral Fruity fragrance for men. Top notes are Apple Blossom and Peach; middle note is Pineapple blossom; base notes are Patchouli, Wild Rose and Musk.',
        4.71,
        7,
        NULL
      ),
(
        'Classic-82827',
        'Classic Just Jack',
        'Classic',
        'for women and men',
        NULL,
        NULL,
        'Black Currant, Raspberry, Cinnamon and Rose',
        'Patchouli and Incense',
        'Sandalwood, Benzoin, Amber and Musk',
        'amber,warm spicy,woody,fruity,balsamic',
        'ClassicbyJust Jackis a fragrance for women and men. This is a new fragrance.Classicwas launched in 2023. Top notes are Black Currant, Raspberry, Cinnamon and Rose; middle notes are Patchouli and Incense; base notes are Sandalwood, Benzoin, Amber and Musk.',
        5,
        1,
        NULL
      ),
(
        'Just-Oud-82848',
        'Just Oud Just Jack',
        'Just',
        'for men',
        NULL,
        NULL,
        'Labdanum',
        'Patchouli, Saffron and Rose',
        'Agarwood, Sandalwood and Cedar',
        'oud,woody,warm spicy,patchouli,rose',
        'Just OudbyJust Jackis a Amber Woody fragrance for men. Top note is Labdanum; middle notes are Patchouli, Saffron and Rose; base notes are Agarwood, Sandalwood and Cedar.',
        4.57,
        7,
        NULL
      ),
(
        'Mystery-82847',
        'Mystery Just Jack',
        'Mystery',
        'for men',
        NULL,
        NULL,
        'Saffron',
        'Vanilla and Rose',
        'Oud and Chocolate',
        'vanilla,rose,oud,warm spicy,chocolate',
        'MysterybyJust Jackis a Woody Aromatic fragrance for men. Top note is Saffron; middle notes are Vanilla and Rose; base notes are Oud and Chocolate.',
        4,
        5,
        NULL
      ),
(
        'Niveau-82829',
        'Niveau Just Jack',
        'Niveau',
        'for women',
        NULL,
        NULL,
        'Artemisia and Saffron',
        'Sea Notes and Rose',
        'Sandalwood, Vanilla, Amber and Cypriol Oil or Nagarmotha',
        'woody,aromatic,warm spicy,vanilla,rose',
        'NiveaubyJust Jackis a fragrance for women. This is a new fragrance.Niveauwas launched in 2023. Top notes are Artemisia and Saffron; middle notes are Sea Notes and Rose; base notes are Sandalwood, Vanilla, Amber and Cypriol Oil or Nagarmotha.',
        NULL,
        NULL,
        NULL
      ),
(
        'Vintage-82828',
        'Vintage Just Jack',
        'Vintage',
        'for women and men',
        NULL,
        NULL,
        'Black Tea and Cardamom',
        'Spicy Notes',
        'Sandalwood, Vetiver and Tonka',
        'warm spicy,woody,aromatic,green,vanilla',
        'VintagebyJust Jackis a fragrance for women and men. This is a new fragrance.Vintagewas launched in 2023. Top notes are Black Tea and Cardamom; middle note is Spicy Notes; base notes are Sandalwood, Vetiver and Tonka.',
        5,
        1,
        NULL
      ),
(
        'Adventure-for-Her-82850',
        'Adventure for Her Just Jack',
        'Adventure',
        'for women',
        NULL,
        NULL,
        'Bergamot, Lemon, Violet, Green Apple, Pink Pepper and Patchouli',
        'Musk, Sandalwood, Styrax and Rose',
        'Black Currant, Ylang-Ylang, Lilac, Amber and Peach',
        'citrus,powdery,musky,fresh spicy,aromatic',
        'Adventure for HerbyJust Jackis a Floral Fruity fragrance for women. Top notes are Bergamot, Lemon, Violet, Green Apple, Pink Pepper and Patchouli; middle notes are Musk, Sandalwood, Styrax and Rose; base notes are Black Currant, Ylang-Ylang, Lilac, Amber and Peach.',
        3.78,
        9,
        NULL
      ),
(
        '1-Superiore-82851',
        '1 Superiore Just Jack',
        '1',
        'for men',
        NULL,
        NULL,
        'Pine, Bergamot, Citruses and Apple',
        'Benzoin, Vetiver, Jasmine and Iris',
        'Cedar, Woodsy Notes, Sandalwood, Labdanum, Amber and Vanilla',
        'woody,amber,aromatic',
        '1 SuperiorebyJust Jackis a fragrance for men. Top notes are Pine, Bergamot, Citruses and Apple; middle notes are Benzoin, Vetiver, Jasmine and Iris; base notes are Cedar, Woodsy Notes, Sandalwood, Labdanum, Amber and Vanilla.',
        4,
        14,
        NULL
      ),
(
        'Homme-Noir-Eau-de-Parfum-93147',
        'Homme Noir Eau de Parfum Just Jack',
        'Homme',
        'for men',
        NULL,
        NULL,
        'Pink Pepper and Bergamot',
        'Spicy Notes, Rosemary and Geranium',
        'Balsamic Notes, Patchouli, Leather and Amber',
        'aromatic,fresh spicy,warm spicy,woody,soft spicy',
        'Homme Noir Eau de ParfumbyJust Jackis a Woody Spicy fragrance for men. This is a new fragrance.Homme Noir Eau de Parfumwas launched in 2024. Top notes are Pink Pepper and Bergamot; middle notes are Spicy Notes, Rosemary and Geranium; base notes are Balsamic Notes, Patchouli, Leather and Amber.',
        5,
        1,
        NULL
      ),
(
        'Italian-Leather-Eau-de-Parfum-93148',
        'Italian Leather Eau de Parfum Just Jack',
        'Italian',
        'for women and men',
        NULL,
        NULL,
        'Spicy Notes and Saffron',
        'Jasmine',
        'Woody Notes, Amber and Leather',
        'warm spicy,amber,white floral,woody,leather',
        'Italian Leather Eau de ParfumbyJust Jackis a Leather fragrance for women and men. This is a new fragrance.Italian Leather Eau de Parfumwas launched in 2024. Top notes are Spicy Notes and Saffron; middle note is Jasmine; base notes are Woody Notes, Amber and Leather.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-82852',
        'J Just Jack',
        'J',
        'for men',
        NULL,
        NULL,
        'Citron, Grapefruit and Orange',
        'Red Pepper',
        'Cedar, Patchouli and Vetiver',
        'citrus,warm spicy,fresh',
        'JbyJust Jackis a Woody Spicy fragrance for men. Top notes are Citron, Grapefruit and Orange; middle note is Red Pepper; base notes are Cedar, Patchouli and Vetiver.',
        4,
        4,
        NULL
      ),
(
        'Mistica-82854',
        'Mistica Just Jack',
        'Mistica',
        'for men',
        NULL,
        NULL,
        'White Flowers, Peony and Bergamot',
        'Jasmine and Rose',
        'Patchouli and Woody Notes',
        'woody,patchouli,white floral,floral,rose',
        'MisticabyJust Jackis a Woody Chypre fragrance for men. Top notes are White Flowers, Peony and Bergamot; middle notes are Jasmine and Rose; base notes are Patchouli and Woody Notes.',
        4.17,
        6,
        NULL
      ),
(
        'Neroli-Eau-de-Parfum-93151',
        'Neroli Eau de Parfum Just Jack',
        'Neroli',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Lavender, Orange and Lemon',
        'Neroli and Jasmine',
        'Amber and Woody Notes',
        'citrus,white floral,fresh spicy,aromatic,fresh',
        'Neroli Eau de ParfumbyJust Jackis a Citrus Aromatic fragrance for women and men. This is a new fragrance.Neroli Eau de Parfumwas launched in 2024. Top notes are Bergamot, Lavender, Orange and Lemon; middle notes are Neroli and Jasmine; base notes are Amber and Woody Notes.',
        4.25,
        4,
        NULL
      ),
(
        'Noir-Endurance-Eau-de-Parfum-93153',
        'Noir Endurance Eau de Parfum Just Jack',
        'Noir',
        'for women and men',
        NULL,
        NULL,
        'Strawberry, Cardamom, Citruses, Neroli, Clove and Pink Pepper',
        'Lily of the Valley, Jasmine and Iris',
        'Amber, Vanilla, Musk and Sandalwood',
        'amber,warm spicy,powdery,white floral,musky',
        'Noir Endurance Eau de ParfumbyJust Jackis a Amber Floral fragrance for women and men. This is a new fragrance.Noir Endurance Eau de Parfumwas launched in 2024. Top notes are Strawberry, Cardamom, Citruses, Neroli, Clove and Pink Pepper; middle notes are Lily of the Valley, Jasmine and Iris; base notes are Amber, Vanilla, Musk and Sandalwood.',
        3.67,
        3,
        NULL
      ),
(
        'Orchid-Noir-Eau-de-Parfum-93154',
        'Orchid Noir Eau de Parfum Just Jack',
        'Orchid',
        'for women and men',
        NULL,
        NULL,
        'Black Currant, Ylang Ylang, Bergamot and Orange',
        'Gardenia, Jasmine, Fruity Notes and Spices',
        'Patchouli, Vanilla, Incense, Amber and Musk',
        'white floral,citrus,fruity,amber,warm spicy',
        'Orchid Noir Eau de ParfumbyJust Jackis a Amber Floral fragrance for women and men. This is a new fragrance.Orchid Noir Eau de Parfumwas launched in 2024. Top notes are Black Currant, Ylang Ylang, Bergamot and Orange; middle notes are Gardenia, Jasmine, Fruity Notes and Spices; base notes are Patchouli, Vanilla, Incense, Amber and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Oud-Oak-Eau-de-Parfum-93146',
        'Oud Oak Eau de Parfum Just Jack',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Pepper and Cardamom',
        'Oud, Vanilla and Amber',
        'Sandalwood, Tonka Bean and Vetiver',
        'fresh spicy,oud,warm spicy,aromatic,vanilla',
        'Oud Oak Eau de ParfumbyJust Jackis a Amber Woody fragrance for women and men. This is a new fragrance.Oud Oak Eau de Parfumwas launched in 2024. Top notes are Pepper and Cardamom; middle notes are Oud, Vanilla and Amber; base notes are Sandalwood, Tonka Bean and Vetiver.',
        NULL,
        NULL,
        NULL
      ),
(
        'Patchouli-Eau-de-Parfum-93149',
        'Patchouli Eau de Parfum Just Jack',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Peony and White Flowers',
        'Jasmine and Rose',
        'Woody Notes and Patchouli',
        'white floral,woody,floral,rose,citrus',
        'Patchouli Eau de ParfumbyJust Jackis a Chypre Floral fragrance for women and men. This is a new fragrance.Patchouli Eau de Parfumwas launched in 2024. Top notes are Bergamot, Peony and White Flowers; middle notes are Jasmine and Rose; base notes are Woody Notes and Patchouli.',
        NULL,
        NULL,
        NULL
      ),
(
        'T-Rose-82853',
        'T''Rose Just Jack',
        'T''Rose',
        'for men',
        NULL,
        NULL,
        'Saffron and Black Pepper',
        'Bulgarian Rose, Turkish Rose and Coffee',
        'Patchouli, Incense, Amber and Sandalwood',
        'warm spicy,rose,amber,woody,coffee',
        'T''RosebyJust Jackis a Woody Spicy fragrance for men. Top notes are Saffron and Black Pepper; middle notes are Bulgarian Rose, Turkish Rose and Coffee; base notes are Patchouli, Incense, Amber and Sandalwood.',
        4.1,
        10,
        NULL
      ),
(
        'Tobbaco-Leaf-Eau-de-Parfum-93155',
        'Tobbaco Leaf Eau de Parfum Just Jack',
        'Tobbaco',
        'for women and men',
        NULL,
        NULL,
        'Spices',
        'Tonka Bean and Tobacco',
        'Woody Notes and Vanilla',
        'vanilla,sweet,tobacco,woody,warm spicy',
        'Tobbaco Leaf Eau de ParfumbyJust Jackis a Woody Spicy fragrance for women and men. This is a new fragrance.Tobbaco Leaf Eau de Parfumwas launched in 2024. Top note is Spices; middle notes are Tonka Bean and Tobacco; base notes are Woody Notes and Vanilla.',
        4.5,
        4,
        NULL
      ),
(
        'Vetiver-Eau-de-Parfum-93152',
        'Vetiver Eau de Parfum Just Jack',
        'Vetiver',
        'for women and men',
        NULL,
        NULL,
        'Grapes and Orange Blossom',
        'Nutmeg, Orris and Spices',
        'Oakmoss, Vetiver and Amber',
        'fruity,earthy,sweet,woody,iris',
        'Vetiver Eau de ParfumbyJust Jackis a Woody Spicy fragrance for women and men. This is a new fragrance.Vetiver Eau de Parfumwas launched in 2024. Top notes are Grapes and Orange Blossom; middle notes are Nutmeg, Orris and Spices; base notes are Oakmoss, Vetiver and Amber.',
        5,
        1,
        NULL
      ),
(
        'Wild-Orchid-Eau-de-Parfum-93150',
        'Wild Orchid Eau de Parfum Just Jack',
        'Wild',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Orange and Honey',
        'Orange Blossom, Jasmine and Rose',
        'Balsamic Notes, Myrrh, Sandalwood and Labdanum',
        'amber,citrus,white floral,sweet,woody',
        'Wild Orchid Eau de ParfumbyJust Jackis a Amber Floral fragrance for women and men. This is a new fragrance.Wild Orchid Eau de Parfumwas launched in 2024. Top notes are Bergamot, Orange and Honey; middle notes are Orange Blossom, Jasmine and Rose; base notes are Balsamic Notes, Myrrh, Sandalwood and Labdanum.',
        NULL,
        NULL,
        NULL
      ),
(
        'Heart-of-Sevastopol-Serdce-Sevastopola-82341',
        'Heart of Sevastopol (Сердце Севастополя) Kamila Robinson',
        'Heart',
        'for women',
        NULL,
        'Kamila Robinson',
        'Pine Tree, Cypress and Almond',
        'Grapes, Hazelnut and Honeysuckle',
        'Incense and Amber',
        'woody,aromatic,amber,balsamic,conifer',
        'Heart of Sevastopol (Сердце Севастополя)byKamila Robinsonis a Woody fragrance for women.Heart of Sevastopol (Сердце Севастополя)was launched in 2022. The nose behind this fragrance is Kamila Robinson. Top notes are Pine Tree, Cypress and Almond; middle notes are Grapes, Hazelnut and Honeysuckle; base notes are Incense and Amber.',
        2,
        4,
        NULL
      ),
(
        'L-ete-a-Astrakhan-Leto-v-Astrahani-82340',
        'L''été à Astrakhan (Лето в Астрахани) Kamila Robinson',
        'L''été',
        'for women',
        NULL,
        'Kamila Robinson',
        'Green Apple, Water Notes and Yuzu',
        'Green Grass, Tagetes, Palo Santo and Cedarwood',
        'Vetiver, Musk and Patchouli',
        'green,fresh,aromatic,fruity,aquatic',
        'L''été à Astrakhan (Лето в Астрахани)byKamila Robinsonis a Aromatic Green fragrance for women.L''été à Astrakhan (Лето в Астрахани)was launched in 2022. The nose behind this fragrance is Kamila Robinson. Top notes are Green Apple, Water Notes and Yuzu; middle notes are Green Grass, Tagetes, Palo Santo and Cedarwood; base notes are Vetiver, Musk and Patchouli.',
        2.33,
        3,
        NULL
      ),
(
        'Autunno-atmosferico-Atmosfernaa-osen-59302',
        'Autunno atmosferico (Атмосферная осень) Kamila Robinson',
        'Autunno',
        'for women',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'fruity,ozonic,green,sweet,aquatic',
        'Autunno atmosferico (Атмосферная осень)byKamila Robinsonis a Floral Fruity fragrance for women.Autunno atmosferico (Атмосферная осень)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.39,
        18,
        NULL
      ),
(
        'Flamenco-rosa-Rozovyj-flamingo-82345',
        'Flamenco rosa (Розовый фламинго) Kamila Robinson',
        'Flamenco',
        'for women',
        NULL,
        'Kamila Robinson',
        'Dew Drop, Green Notes and Peony',
        'Peony and Rose Petals',
        'Musk and Amber',
        'rose,floral,amber,green,musky',
        'Flamenco rosa (Розовый фламинго)byKamila Robinsonis a Floral fragrance for women.Flamenco rosa (Розовый фламинго)was launched in 2023. The nose behind this fragrance is Kamila Robinson. Top notes are Dew Drop, Green Notes and Peony; middle notes are Peony and Rose Petals; base notes are Musk and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sensual-rain-Cuvstvennyj-dozd-59301',
        'Sensual rain (Чувственный дождь) Kamila Robinson',
        'Sensual',
        'for women and men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'aquatic,ozonic,anis,aromatic,fresh spicy',
        'Sensual rain (Чувственный дождь)byKamila Robinsonis a fragrance for women and men.Sensual rain (Чувственный дождь)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.78,
        18,
        NULL
      ),
(
        'Sparkling-Pina-Solada-Iskrasaasa-Pina-Kolada-59305',
        'Sparkling Pina Сolada (Искрящаяся Пина Колада) Kamila Robinson',
        'Sparkling',
        'for women',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'coconut,sweet,tropical,rum,metallic',
        'Sparkling Pina Сolada (Искрящаяся Пина Колада)byKamila Robinsonis a Floral Fruity fragrance for women.Sparkling Pina Сolada (Искрящаяся Пина Колада)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.45,
        11,
        NULL
      ),
(
        'Afrodite-75303',
        'Afrodite Kamila Robinson',
        'Afrodite',
        'for women',
        NULL,
        'Kamila Robinson',
        'Black Currant and Dew Drop',
        'Rose and Tuberose',
        'Musk, Sandalwood, Amber and Vanilla',
        'fruity,woody,powdery,rose,musky',
        'AfroditebyKamila Robinsonis a Floral Green fragrance for women.Afroditewas launched in 2021. The nose behind this fragrance is Kamila Robinson. Top notes are Black Currant and Dew Drop; middle notes are Rose and Tuberose; base notes are Musk, Sandalwood, Amber and Vanilla.',
        4,
        7,
        NULL
      ),
(
        'Via-Lateea-75304',
        'Via Lateea Kamila Robinson',
        'Via',
        'for women',
        NULL,
        'Kamila Robinson',
        'Yogurt, Pear, Pineapple and pink tulip',
        'Whipped Cream, Peach, Blueberry, Apricot and Jasmine',
        'Hortensia, Musk and Labdanum',
        'lactonic,sweet,fruity,vanilla,sour',
        'Via LateeabyKamila Robinsonis a Floral Fruity fragrance for women.Via Lateeawas launched in 2021. The nose behind this fragrance is Kamila Robinson. Top notes are Yogurt, Pear, Pineapple and pink tulip; middle notes are Whipped Cream, Peach, Blueberry, Apricot and Jasmine; base notes are Hortensia, Musk and Labdanum.',
        4.12,
        8,
        NULL
      ),
(
        'Sin-Cherry-75305',
        'Sin Cherry Kamila Robinson',
        'Sin',
        'for women',
        NULL,
        'Kamila Robinson',
        'Cognac, Ginger and Pink Pepper',
        'Cacao Pod, Dark Chocolate and Cherry',
        'Blackwood, Patchouli, Animal notes, Tonka Bean and Amber',
        'warm spicy,woody,cacao,sweet,chocolate',
        'Sin CherrybyKamila Robinsonis a Amber Vanilla fragrance for women.Sin Cherrywas launched in 2021. The nose behind this fragrance is Kamila Robinson. Top notes are Cognac, Ginger and Pink Pepper; middle notes are Cacao Pod, Dark Chocolate and Cherry; base notes are Blackwood, Patchouli, Animal notes, Tonka Bean and Amber.',
        4,
        4,
        NULL
      ),
(
        'Swallow-75306',
        'Swallow Kamila Robinson',
        'Swallow',
        'for women',
        NULL,
        'Kamila Robinson',
        'Champagne, Bitter Almond and Lemon',
        'Chocolate, Cacao Pod and Strawberry',
        'Chrysanthemum, Musk and Agarwood (Oud)',
        'cacao,warm spicy,sweet,chocolate,almond',
        'SwallowbyKamila Robinsonis a Citrus Gourmand fragrance for women.Swallowwas launched in 2021. The nose behind this fragrance is Kamila Robinson. Top notes are Champagne, Bitter Almond and Lemon; middle notes are Chocolate, Cacao Pod and Strawberry; base notes are Chrysanthemum, Musk and Agarwood (Oud).',
        3.62,
        8,
        NULL
      ),
(
        'Tentazione-Lunar-75307',
        'Tentazione Lunar Kamila Robinson',
        'Tentazione',
        'for women',
        NULL,
        'Kamila Robinson',
        'Champaca, Black Pepper and Cinnamon',
        'White Chocolate, Hazelnut, Orchid and Chocolate',
        'Bourbon Vanilla, Musk and Iris',
        'sweet,floral,powdery,vanilla,chocolate',
        'Tentazione LunarbyKamila Robinsonis a Amber Vanilla fragrance for women.Tentazione Lunarwas launched in 2021. The nose behind this fragrance is Kamila Robinson. Top notes are Champaca, Black Pepper and Cinnamon; middle notes are White Chocolate, Hazelnut, Orchid and Chocolate; base notes are Bourbon Vanilla, Musk and Iris.',
        3.67,
        3,
        NULL
      ),
(
        'Pirate-carib-63232',
        'Pirate carib Kamila Robinson',
        'Pirate',
        'for women and men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,coffee,amber,nutty',
        'Pirate caribbyKamila Robinsonis a Amber Spicy fragrance for women and men.Pirate caribwas launched in 2020. The nose behind this fragrance is Kamila Robinson.',
        4.71,
        7,
        NULL
      ),
(
        'Spring-s-allegory-63233',
        'Spring''s allegory Kamila Robinson',
        'Spring''s',
        'for women and men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'green,floral,warm spicy,iris,powdery',
        'Spring''s allegorybyKamila Robinsonis a Floral fragrance for women and men.Spring''s allegorywas launched in 2020. The nose behind this fragrance is Kamila Robinson.',
        3.57,
        7,
        NULL
      ),
(
        'Caramel-Angel-Karamel-nyj-angel-59303',
        'Caramel Angel (Карамельный ангел) Kamila Robinson',
        'Caramel',
        'for women',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'sweet,lactonic,caramel,Champagne,vanilla',
        'Caramel Angel (Карамельный ангел)byKamila Robinsonis a Amber Vanilla fragrance for women.Caramel Angel (Карамельный ангел)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.68,
        22,
        NULL
      ),
(
        'Mattine-du-Provanza-Utro-v-Provanse-59298',
        'Mattine du Provanza (Утро в Провансе) Kamila Robinson',
        'Mattine',
        'for women and men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'green,citrus,aromatic,woody,musky',
        'Mattine du Provanza (Утро в Провансе)byKamila Robinsonis a Woody Aromatic fragrance for women and men.Mattine du Provanza (Утро в Провансе)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.6,
        10,
        NULL
      ),
(
        'Ombre-de-cafe-Ten-ot-kofe-59304',
        'Ombré dе café (Тень от кофе) Kamila Robinson',
        'Ombré',
        'for women',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'coffee,warm spicy,citrus,white floral,vanilla',
        'Ombré dе café (Тень от кофе)byKamila Robinsonis a Floral Woody Musk fragrance for women.Ombré dе café (Тень от кофе)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.5,
        10,
        NULL
      ),
(
        'Woody-waterfall-Drevesnyj-vodopad-59299',
        'Woody waterfall (Древесный водопад) Kamila Robinson',
        'Woody',
        'for men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'woody,marine,aromatic,green,salty',
        'Woody waterfall (Древесный водопад)byKamila Robinsonis a Aromatic Aquatic fragrance for men.Woody waterfall (Древесный водопад)was launched in 2019. The nose behind this fragrance is Kamila Robinson.',
        3.14,
        14,
        NULL
      ),
(
        'Brutal-man-63230',
        'Brutal man Kamila Robinson',
        'Brutal',
        'for men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'woody,amber,green,fresh,powdery',
        'Brutal manbyKamila Robinsonis a Woody Spicy fragrance for men.Brutal manwas launched in 2020. The nose behind this fragrance is Kamila Robinson.',
        4,
        4,
        NULL
      ),
(
        'Gold-muskus-63228',
        'Gold muskus Kamila Robinson',
        'Gold',
        'for women',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'fruity,yellow floral,musky,fresh,sweet',
        'Gold muskusbyKamila Robinsonis a Floral Woody Musk fragrance for women.Gold muskuswas launched in 2020. The nose behind this fragrance is Kamila Robinson.',
        4.25,
        4,
        NULL
      ),
(
        'King-of-ocean-63231',
        'King of ocean Kamila Robinson',
        'King',
        'for women and men',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'citrus,amber,aromatic,woody,salty',
        'King of oceanbyKamila Robinsonis a Woody Spicy fragrance for women and men.King of oceanwas launched in 2020. The nose behind this fragrance is Kamila Robinson.',
        4.33,
        3,
        NULL
      ),
(
        'Ocean-s-flower-63229',
        'Оcean’s flower Kamila Robinson',
        'Оcean’s',
        'for women',
        NULL,
        'Kamila Robinson',
        NULL,
        NULL,
        NULL,
        'fresh,floral,fresh spicy,musky,warm spicy',
        'Оcean’s flowerbyKamila Robinsonis a Floral Green fragrance for women.Оcean’s flowerwas launched in 2020. The nose behind this fragrance is Kamila Robinson.',
        4,
        3,
        NULL
      ),
(
        'Paramaribo-Paramaribo-82339',
        'Paramaribo (Парамарибо) Kamila Robinson',
        'Paramaribo',
        'for women',
        NULL,
        'Kamila Robinson',
        'Pineapple and Pink Grapefruit',
        'Coffee, Smoke, Jasmine and Cognac',
        'Balsam Fir, Labdanum, Amber and Musk',
        'amber,woody,fresh spicy,musky,smoky',
        'Paramaribo (Парамарибо)byKamila Robinsonis a Amber Spicy fragrance for women.Paramaribo (Парамарибо)was launched in 2022. The nose behind this fragrance is Kamila Robinson. Top notes are Pineapple and Pink Grapefruit; middle notes are Coffee, Smoke, Jasmine and Cognac; base notes are Balsam Fir, Labdanum, Amber and Musk.',
        3.5,
        2,
        NULL
      ),
(
        'Lake-Maden-Deva-Ozera-82344',
        'Lake Maden (Дева Озера) Kamila Robinson',
        'Lake',
        'for women',
        NULL,
        'Kamila Robinson',
        'Ice, Water Notes and Floral Notes',
        'China Rose, Sandal, Milk and Lavender',
        'Patchouli and Musk',
        'fresh,aquatic,patchouli,woody,musky',
        'Lake Maden (Дева Озера)byKamila Robinsonis a Floral Aquatic fragrance for women.Lake Maden (Дева Озера)was launched in 2023. The nose behind this fragrance is Kamila Robinson. Top notes are Ice, Water Notes and Floral Notes; middle notes are China Rose, Sandal, Milk and Lavender; base notes are Patchouli and Musk.',
        3.75,
        4,
        NULL
      ),
(
        'Sun-in-Aslaug-Solnce-v-Aslaug-82342',
        'Sun in Aslaug (Солнце в Аслауг) Kamila Robinson',
        'Sun',
        'for women',
        NULL,
        'Kamila Robinson',
        'Water Notes and Grapefruit',
        'Frangipani, Honeysuckle, Gardenia and Gorse',
        'Saffron, Amber and Musk',
        'white floral,floral,tropical,lactonic,aquatic',
        'Sun in Aslaug (Солнце в Аслауг)byKamila Robinsonis a Floral Green fragrance for women.Sun in Aslaug (Солнце в Аслауг)was launched in 2023. The nose behind this fragrance is Kamila Robinson. Top notes are Water Notes and Grapefruit; middle notes are Frangipani, Honeysuckle, Gardenia and Gorse; base notes are Saffron, Amber and Musk.',
        3.5,
        2,
        NULL
      ),
(
        'Vicino-a-AEthelstan-Blizost-Etel-stana-82343',
        'Vicino a Æthelstan (Близость Этельстана) Kamila Robinson',
        'Vicino',
        'for women and men',
        NULL,
        'Kamila Robinson',
        'Birch Leaf, Aquatic notes, Metallic notes and Dew Drop',
        'Poppy, Chamomile and Pine needles',
        'Amber and Musk',
        'leather,smoky,woody,amber,aromatic',
        'Vicino a Æthelstan (Близость Этельстана)byKamila Robinsonis a Woody Aquatic fragrance for women and men.Vicino a Æthelstan (Близость Этельстана)was launched in 2023. The nose behind this fragrance is Kamila Robinson. Top notes are Birch Leaf, Aquatic notes, Metallic notes and Dew Drop; middle notes are Poppy, Chamomile and Pine needles; base notes are Amber and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        '266st-Pontiff-s-Harley-75315',
        '266st Pontiff''s Harley Kamila Robinson',
        '266st',
        'for men',
        NULL,
        'Kamila Robinson',
        'Gasoline, gunpowder, Nutmeg, Black Pepper and Bitter Orange',
        'Leather, Tagetes, Teak Wood, Mastic or Lentisque, Sandalwood, Hyacinth and Jasmine',
        'Incense and gunpowder',
        'smoky,amber,balsamic,woody,gasoline',
        '266st Pontiff''s HarleybyKamila Robinsonis a Leather fragrance for men.266st Pontiff''s Harleywas launched in 2021. The nose behind this fragrance is Kamila Robinson. Top notes are Gasoline, gunpowder, Nutmeg, Black Pepper and Bitter Orange; middle notes are Leather, Tagetes, Teak Wood, Mastic or Lentisque, Sandalwood, Hyacinth and Jasmine; base notes are Incense and gunpowder.',
        4.8,
        5,
        NULL
      );
