
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Assam-24125',
        'Assam Neil Morris',
        'Assam',
        'for women and men',
        NULL,
        'Neil Morris',
        'elemi and Bergamot',
        'Black Tea, Mango, Carnation and Red Currant',
        'Incense, Musk, Benzoin, Agarwood (Oud) and Woody Notes',
        'aromatic,balsamic,conifer',
        'AssambyNeil Morrisis a Amber fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are elemi and Bergamot; middle notes are Black Tea, Mango, Carnation and Red Currant; base notes are Incense, Musk, Benzoin, Agarwood (Oud) and Woody Notes.',
        3.88,
        16,
        NULL
      ),
(
        'Gandhara-24126',
        'Gandhara Neil Morris',
        'Gandhara',
        'for women and men',
        NULL,
        'Neil Morris',
        'Mimosa',
        'Geranium, Jasmine, Lotus and Fig',
        'Castoreum and Patchouli',
        'leather,fresh spicy,smoky,woody,aromatic',
        'GandharabyNeil Morrisis a Floral fragrance for women and men. The nose behind this fragrance is Neil Morris. Top note is Mimosa; middle notes are Geranium, Jasmine, Lotus and Fig; base notes are Castoreum and Patchouli.',
        2.62,
        8,
        NULL
      ),
(
        'Rose-of-Kali-12554',
        'Rose of Kali Neil Morris',
        'Rose',
        'for women and men',
        NULL,
        'Neil Morris',
        'Rose and Pear',
        'Taif Rose',
        'Mexican chocolate, Patchouli, Incense, Benzoin, Myrhh, Musk, Agarwood (Oud) and French labdanum',
        'rose,warm spicy,amber,sweet,balsamic',
        'Rose of KalibyNeil Morrisis a Amber Floral fragrance for women and men.Rose of Kaliwas launched during the 2000''s. The nose behind this fragrance is Neil Morris. Top notes are Rose and Pear; middle note is Taif Rose; base notes are Mexican chocolate, Patchouli, Incense, Benzoin, Myrhh, Musk, Agarwood (Oud) and French labdanum.',
        3.74,
        27,
        NULL
      ),
(
        'Taj-24128',
        'Taj Neil Morris',
        'Taj',
        'for women and men',
        NULL,
        'Neil Morris',
        'Green Tea, Cinnamon and Mandarin Orange',
        'White Tea, Rose and Ylang-Ylang',
        'Olibanum, Agarwood (Oud), Chocolate, Patchouli and Cedar',
        'warm spicy,woody,amber,cinnamon,green',
        'TajbyNeil Morrisis a Amber fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Green Tea, Cinnamon and Mandarin Orange; middle notes are White Tea, Rose and Ylang-Ylang; base notes are Olibanum, Agarwood (Oud), Chocolate, Patchouli and Cedar.',
        4,
        9,
        NULL
      ),
(
        'Aegean-4399',
        'Aegean Neil Morris',
        'Aegean',
        'for women and men',
        NULL,
        'Neil Morris',
        'Basil and Mandarin Orange',
        'Lavender and Quince',
        'Sandalwood, Musk and Benzoin',
        'lavender,fresh spicy,aromatic,fruity,woody',
        'AegeanbyNeil Morrisis a Aromatic Fruity fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Basil and Mandarin Orange; middle notes are Lavender and Quince; base notes are Sandalwood, Musk and Benzoin.',
        4,
        16,
        NULL
      ),
(
        'Afire-4400',
        'Afire Neil Morris',
        'Afire',
        'for women and men',
        NULL,
        'Neil Morris',
        'Citruses',
        'Caramel and Red Berries',
        'Incense, Woodsy Notes and Vanilla',
        'citrus,caramel,sweet,fresh,fruity',
        'AfirebyNeil Morrisis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Neil Morris. Top note is Citruses; middle notes are Caramel and Red Berries; base notes are Incense, Woodsy Notes and Vanilla.',
        3.74,
        62,
        NULL
      ),
(
        'Clear-4401',
        'Clear Neil Morris',
        'Clear',
        'for women and men',
        NULL,
        'Neil Morris',
        'Lime (Linden) Blossom and Grapefruit',
        'Mint and Resin',
        'Musk and Cedar',
        'yellow floral,citrus,green,sweet,aromatic',
        'ClearbyNeil Morrisis a Woody Floral Musk fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Lime (Linden) Blossom and Grapefruit; middle notes are Mint and Resin; base notes are Musk and Cedar.',
        3.67,
        18,
        NULL
      ),
(
        'Coral-4402',
        'Coral Neil Morris',
        'Coral',
        'for women and men',
        NULL,
        'Neil Morris',
        'Bergamot and Pomegranate',
        'Sweet Pea, Fig and Rose',
        'Incense, Sandalwood and Musk',
        'woody,floral,sweet,fruity,citrus',
        'CoralbyNeil Morrisis a Floral Fruity fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Bergamot and Pomegranate; middle notes are Sweet Pea, Fig and Rose; base notes are Incense, Sandalwood and Musk.',
        3.62,
        21,
        NULL
      ),
(
        'Gotham-4403',
        'Gotham Neil Morris',
        'Gotham',
        'for women and men',
        NULL,
        'Neil Morris',
        'Yuzu and Pepper',
        'Rose and Narcissus',
        'Leather, Amber, Myrhh and French labdanum',
        'amber,leather,animalic,citrus,fresh spicy',
        'GothambyNeil Morrisis a Floral Woody Musk fragrance for women and men.Gothamwas launched in 2008. The nose behind this fragrance is Neil Morris. Top notes are Yuzu and Pepper; middle notes are Rose and Narcissus; base notes are Leather, Amber, Myrhh and French labdanum.',
        4,
        33,
        NULL
      ),
(
        'Rainflower-4404',
        'Rainflower Neil Morris',
        'Rainflower',
        'for women and men',
        NULL,
        'Neil Morris',
        'Jasmine and Freesia',
        'Lilac, Hyacinth, Tulip and Gardenia',
        'Musk',
        'floral,green,white floral,fresh spicy',
        'RainflowerbyNeil Morrisis a Floral fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Jasmine and Freesia; middle notes are Lilac, Hyacinth, Tulip and Gardenia; base note is Musk.',
        4.05,
        43,
        NULL
      ),
(
        'Storm-4405',
        'Storm Neil Morris',
        'Storm',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        NULL,
        'StormbyNeil Morrisis a Woody Floral Musk fragrance for women and men.Stormwas launched in 2007. The nose behind this fragrance is Neil Morris.',
        3.72,
        29,
        NULL
      ),
(
        'Zephyr-4406',
        'Zephyr Neil Morris',
        'Zephyr',
        'for women and men',
        NULL,
        'Neil Morris',
        'Tangerine and Papaya',
        'Honeysuckle, Casablanca Lily and White Tea',
        'Musk, Sandalwood and Amber',
        'white floral,citrus,fruity,musky,powdery',
        'ZephyrbyNeil Morrisis a Floral Fruity fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Tangerine and Papaya; middle notes are Honeysuckle, Casablanca Lily and White Tea; base notes are Musk, Sandalwood and Amber.',
        4.12,
        24,
        NULL
      ),
(
        'Burnt-Amber-24088',
        'Burnt Amber Neil Morris',
        'Burnt',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'amber,woody,floral,animalic,leather',
        'Burnt AmberbyNeil Morrisis a Amber fragrance for women and men. The nose behind this fragrance is Neil Morris.',
        4.25,
        16,
        NULL
      ),
(
        'Cafe-22932',
        'Café Neil Morris',
        'Café',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'sweet,warm spicy,coffee,chocolate,vanilla',
        'CafébyNeil Morrisis a Amber Vanilla fragrance for women and men.Caféwas launched in 2008. The nose behind this fragrance is Neil Morris.',
        3.82,
        28,
        NULL
      ),
(
        'Cathedral-24089',
        'Cathedral Neil Morris',
        'Cathedral',
        'for women and men',
        NULL,
        'Neil Morris',
        'Green Tea and Black Pepper',
        'Narcissus and Ylang-Ylang',
        'Incense, Labdanum, Leather, Amyris, Cedar and Oak',
        'amber,woody,smoky,balsamic,yellow floral',
        'CathedralbyNeil Morrisis a Amber fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Green Tea and Black Pepper; middle notes are Narcissus and Ylang-Ylang; base notes are Incense, Labdanum, Leather, Amyris, Cedar and Oak.',
        3.88,
        17,
        NULL
      ),
(
        'Chasing-Autumn-28118',
        'Chasing Autumn Neil Morris',
        'Chasing',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,earthy',
        'Chasing AutumnbyNeil Morrisis a Amber Woody fragrance for women and men.Chasing Autumnwas launched in 2014. The nose behind this fragrance is Neil Morris.',
        4.62,
        21,
        NULL
      ),
(
        'City-Rain-24090',
        'City Rain Neil Morris',
        'City',
        'for women and men',
        NULL,
        'Neil Morris',
        'Green Tea and Watery Notes',
        'Heliotrope and Honeysuckle',
        'Patchouli Leaf, Musk and Soil Tincture',
        'patchouli,musky,earthy,woody,powdery',
        'City RainbyNeil Morrisis a Floral Green fragrance for women and men.City Rainwas launched in 2009. The nose behind this fragrance is Neil Morris. Top notes are Green Tea and Watery Notes; middle notes are Heliotrope and Honeysuckle; base notes are Patchouli Leaf, Musk and Soil Tincture.',
        3.75,
        4,
        NULL
      ),
(
        'Dark-Season-24091',
        'Dark Season Neil Morris',
        'Dark',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'woody,amber,warm spicy,balsamic,earthy',
        'Dark SeasonbyNeil Morrisis a Amber fragrance for women and men.Dark Seasonwas launched in 2008. The nose behind this fragrance is Neil Morris.',
        4.56,
        27,
        NULL
      ),
(
        'Drifting-24092',
        'Drifting Neil Morris',
        'Drifting',
        'for women and men',
        NULL,
        'Neil Morris',
        'Mandarin Orange and Water Lily',
        'Fig and Rhododendron',
        'Sweet Notes, Woody Notes, Musk, Amber, Myrtle and Fruity Notes',
        'fruity,citrus,sweet,woody,floral',
        'DriftingbyNeil Morrisis a Floral Woody Musk fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Mandarin Orange and Water Lily; middle notes are Fig and Rhododendron; base notes are Sweet Notes, Woody Notes, Musk, Amber, Myrtle and Fruity Notes.',
        3.75,
        4,
        NULL
      ),
(
        'Earthtones-1-Dark-Earth-24093',
        'Earthtones #1: Dark Earth Neil Morris',
        'Earthtones',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'amber,earthy,musky,warm spicy,woody',
        'Earthtones #1: Dark EarthbyNeil Morrisis a Amber Woody fragrance for women and men.Earthtones #1: Dark Earthwas launched in 2008. The nose behind this fragrance is Neil Morris.',
        4.27,
        11,
        NULL
      ),
(
        'Earthtones-2-Desert-Wind-24094',
        'Earthtones #2: Desert Wind Neil Morris',
        'Earthtones',
        'for women and men',
        NULL,
        'Neil Morris',
        'Aldehydes and Black Pepper',
        'Hortensia, White Lily, West Indian Bay, White Flowers and Rum',
        'Cedar, Ambergris, Woody Notes and White Amber',
        'woody,fresh,aldehydic,floral,amber',
        'Earthtones #2: Desert WindbyNeil Morrisis a Floral Woody Musk fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Aldehydes and Black Pepper; middle notes are Hortensia, White Lily, West Indian Bay, White Flowers and Rum; base notes are Cedar, Ambergris, Woody Notes and White Amber.',
        3,
        5,
        NULL
      ),
(
        'Earthtones-3-North-Woods-24095',
        'Earthtones #3: North Woods Neil Morris',
        'Earthtones',
        'for women and men',
        NULL,
        'Neil Morris',
        'Basil and heather',
        'Fir, Grass, Sweet Pea and Fig',
        'Oakmoss, Vetiver, Cedar, Oak, Myrrh, California Redwood and Labdanum',
        'woody,aromatic,fresh spicy,green,fresh',
        'Earthtones #3: North WoodsbyNeil Morrisis a Woody Aromatic fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Basil and heather; middle notes are Fir, Grass, Sweet Pea and Fig; base notes are Oakmoss, Vetiver, Cedar, Oak, Myrrh, California Redwood and Labdanum.',
        4.25,
        20,
        NULL
      ),
(
        'Earthtones-4-Red-Sky-24096',
        'Earthtones #4: Red Sky Neil Morris',
        'Earthtones',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'musky,mossy,citrus,earthy,powdery',
        'Earthtones #4: Red SkybyNeil Morrisis a Aromatic Fougere fragrance for women and men.Earthtones #4: Red Skywas launched in 2009. The nose behind this fragrance is Neil Morris.',
        3.56,
        9,
        NULL
      ),
(
        'Fetish-9190',
        'Fetish Neil Morris',
        'Fetish',
        'for men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'amber,leather,warm spicy,oud,animalic',
        'FetishbyNeil Morrisis a Leather fragrance for men.Fetishwas launched during the 2000''s. The nose behind this fragrance is Neil Morris.',
        4.25,
        32,
        NULL
      ),
(
        'Flowers-for-men-Gardenia-24097',
        'Flowers',
        'Flowers',
        'for men',
        NULL,
        'Neil Morris',
        'Lime, Bergamot and elemi',
        'Gardenia, Grass and Hay',
        'Musk, Patchouli, Myrrh and Agarwood (Oud)',
        'green,white floral,citrus,fresh spicy,lactonic',
        'Flowers for men: GardeniabyNeil Morrisis a Floral Woody Musk fragrance for men. The nose behind this fragrance is Neil Morris. Top notes are Lime, Bergamot and elemi; middle notes are Gardenia, Grass and Hay; base notes are Musk, Patchouli, Myrrh and Agarwood (Oud).',
        4.33,
        6,
        NULL
      ),
(
        'Flowers-for-men-Lilac-24098',
        'Flowers',
        'Flowers',
        'for men',
        NULL,
        'Neil Morris',
        'Petitgrain and Tangerine',
        'Lilac and White Hyacinth',
        'Vetiver, Virginia Cedar, Palisander Rosewood, Leather, Musk and Labdanum',
        'woody,aromatic,floral,green,earthy',
        'Flowers for men: LilacbyNeil Morrisis a Floral Woody Musk fragrance for men. The nose behind this fragrance is Neil Morris. Top notes are Petitgrain and Tangerine; middle notes are Lilac and White Hyacinth; base notes are Vetiver, Virginia Cedar, Palisander Rosewood, Leather, Musk and Labdanum.',
        3.5,
        2,
        NULL
      ),
(
        'Flowers-for-men-Rose-24099',
        'Flowers',
        'Flowers',
        'for men',
        NULL,
        'Neil Morris',
        'Bergamot, Watery Notes and Floral Notes',
        'Bulgarian Rose and White Rose',
        'Musk, Amber, Patchouli, Sandalwood and Oakmoss',
        'rose,musky,powdery,woody,amber',
        'Flowers for men: RosebyNeil Morrisis a Chypre Floral fragrance for men. The nose behind this fragrance is Neil Morris. Top notes are Bergamot, Watery Notes and Floral Notes; middle notes are Bulgarian Rose and White Rose; base notes are Musk, Amber, Patchouli, Sandalwood and Oakmoss.',
        3.33,
        3,
        NULL
      ),
(
        'Hippie-9191',
        'Hippie Neil Morris',
        'Hippie',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,amber,aromatic,balsamic',
        'HippiebyNeil Morrisis a Woody Aromatic fragrance for women and men.Hippiewas launched during the 2000''s. The nose behind this fragrance is Neil Morris.',
        3.7,
        10,
        NULL
      ),
(
        'Hologram-9192',
        'Hologram Neil Morris',
        'Hologram',
        'for women',
        NULL,
        'Neil Morris',
        'Yuzu and Black Currant',
        'Violet, Fig and Seaweed',
        'Amber, Incense and Musk',
        'fruity,violet,amber,powdery,citrus',
        'HologrambyNeil Morrisis a Chypre Fruity fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Yuzu and Black Currant; middle notes are Violet, Fig and Seaweed; base notes are Amber, Incense and Musk.',
        3.5,
        8,
        NULL
      ),
(
        'Hula-24100',
        'Hula Neil Morris',
        'Hula',
        'for women and men',
        NULL,
        'Neil Morris',
        'Papaya and Mandarin Orange',
        'Gardenia, Heliotrope, Frangipani, Green Tea and White Ginger',
        'Tonka Bean, Island Musk and Musk',
        'tropical,citrus,vanilla,floral,white floral',
        'HulabyNeil Morrisis a Floral Fruity fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Papaya and Mandarin Orange; middle notes are Gardenia, Heliotrope, Frangipani, Green Tea and White Ginger; base notes are Tonka Bean, Island Musk and Musk.',
        4,
        8,
        NULL
      ),
(
        'Intimate-Gardenia-24101',
        'Intimate Gardenia Neil Morris',
        'Intimate',
        'for women',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'white floral,lactonic',
        'Intimate GardeniabyNeil Morrisis a Floral fragrance for women. The nose behind this fragrance is Neil Morris.',
        3.8,
        5,
        NULL
      ),
(
        'Intimate-Jasmine-13767',
        'Intimate Jasmine Neil Morris',
        'Intimate',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'mossy,earthy,white floral,citrus,woody',
        'Intimate JasminebyNeil Morrisis a Chypre Floral fragrance for women and men.Intimate Jasminewas launched in 2011. The nose behind this fragrance is Neil Morris.',
        NULL,
        NULL,
        NULL
      ),
(
        'Intimate-Lily-24102',
        'Intimate Lily Neil Morris',
        'Intimate',
        'for women',
        NULL,
        'Neil Morris',
        'Water Lily and Aldehydes',
        'Casablanca Lily and Lily-of-the-Valley',
        'Vanilla, Sandalwood and White Musk',
        'white floral,floral,fresh,aquatic,soft spicy',
        'Intimate LilybyNeil Morrisis a Floral Aldehyde fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Water Lily and Aldehydes; middle notes are Casablanca Lily and Lily-of-the-Valley; base notes are Vanilla, Sandalwood and White Musk.',
        4.25,
        4,
        NULL
      ),
(
        'Intimate-Wisteria-24103',
        'Intimate Wisteria Neil Morris',
        'Intimate',
        'for women and men',
        NULL,
        'Neil Morris',
        'Bergamot',
        'Wisteria',
        'Island Musk and White Amber',
        'floral,fresh,musky,fresh spicy,amber',
        'Intimate WisteriabyNeil Morrisis a Floral fragrance for women and men. The nose behind this fragrance is Neil Morris. Top note is Bergamot; middle note is Wisteria; base notes are Island Musk and White Amber.',
        3.75,
        4,
        NULL
      ),
(
        'Izmir-24104',
        'Izmir Neil Morris',
        'Izmir',
        'for women and men',
        NULL,
        'Neil Morris',
        'Cinnamon, Papaya and Orange',
        'Geranium, Coffee, Rose and Fig',
        'Patchouli, Vanilla, Sea Notes and Agarwood (Oud)',
        'warm spicy,fresh spicy,coffee,aromatic,rose',
        'IzmirbyNeil Morrisis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Cinnamon, Papaya and Orange; middle notes are Geranium, Coffee, Rose and Fig; base notes are Patchouli, Vanilla, Sea Notes and Agarwood (Oud).',
        3.2,
        20,
        NULL
      ),
(
        'Le-Parfum-d-Ida-24107',
        'Le Parfum d''Ida Neil Morris',
        'Le',
        'for women',
        NULL,
        'Neil Morris',
        'Aldehydes, Cloves, elemi and Blackberry',
        'Hyacinth, Geranium, Narcissus, Ylang-Ylang and Gardenia',
        'Russian Leather, Civet, Oakmoss, Agarwood (Oud), Vetiver, Orris, Nard Himalayan (Jatamansi) and Myrrh',
        'fresh spicy,animalic,earthy,leather,aromatic',
        'Le Parfum d''IdabyNeil Morrisis a Chypre Floral fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Aldehydes, Cloves, elemi and Blackberry; middle notes are Hyacinth, Geranium, Narcissus, Ylang-Ylang and Gardenia; base notes are Russian Leather, Civet, Oakmoss, Agarwood (Oud), Vetiver, Orris, Nard Himalayan (Jatamansi) and Myrrh.',
        4.17,
        6,
        NULL
      ),
(
        'Le-Parfum-d-Odette-24108',
        'Le Parfum d''Odette Neil Morris',
        'Le',
        'for women',
        NULL,
        'Neil Morris',
        'Aldehydes and Green Tea',
        'Narcissus, Tuberose, Lilac and Honeysuckle',
        'Guaiac Wood, Musk and Amber',
        'white floral,green,yellow floral,fresh,aldehydic',
        'Le Parfum d''OdettebyNeil Morrisis a Floral Green fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Aldehydes and Green Tea; middle notes are Narcissus, Tuberose, Lilac and Honeysuckle; base notes are Guaiac Wood, Musk and Amber.',
        3.91,
        11,
        NULL
      ),
(
        'Le-Parfum-C-est-Ma-Vie-24106',
        'Le Parfum, C''est Ma Vie Neil Morris',
        'Le',
        'for women',
        NULL,
        'Neil Morris',
        'Aldehydes and Raspberry',
        'Plum Blossom, Rose Petals, Lotus, Narcissus and Peony',
        'Musk and Amber',
        'fruity,aldehydic,musky,fresh,sweet',
        'Le Parfum, C''est Ma ViebyNeil Morrisis a Floral Aldehyde fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Aldehydes and Raspberry; middle notes are Plum Blossom, Rose Petals, Lotus, Narcissus and Peony; base notes are Musk and Amber.',
        4,
        6,
        NULL
      ),
(
        'Leather-Garden-24105',
        'Leather Garden Neil Morris',
        'Leather',
        'for women and men',
        NULL,
        'Neil Morris',
        'Blackberry and Basil',
        'Narcissus, Hyacinth, Peony, Lily-of-the-Valley and Rose',
        'Leather, Agarwood (Oud), Vetiver and Palisander Rosewood',
        'floral,green,rose,leather,fresh',
        'Leather GardenbyNeil Morrisis a Floral Woody Musk fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Blackberry and Basil; middle notes are Narcissus, Hyacinth, Peony, Lily-of-the-Valley and Rose; base notes are Leather, Agarwood (Oud), Vetiver and Palisander Rosewood.',
        4.33,
        9,
        NULL
      ),
(
        'Mariner-24109',
        'Mariner Neil Morris',
        'Mariner',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,aromatic,powdery,citrus',
        'MarinerbyNeil Morrisis a Woody Floral Musk fragrance for women and men.Marinerwas launched in 2009. The nose behind this fragrance is Neil Morris.',
        4,
        1,
        NULL
      ),
(
        'Midnight-Flower-9188',
        'Midnight Flower Neil Morris',
        'Midnight',
        'for women',
        NULL,
        'Neil Morris',
        'Aldehydes and Sweet Orange',
        'Ylang-Ylang, Frangipani, Gardenia, Jasmine Sambac, Fig and Green Tea',
        'Amber, Patchouli and Musk',
        'white floral,amber,floral,yellow floral,woody',
        'Midnight FlowerbyNeil Morrisis a Floral Aldehyde fragrance for women.Midnight Flowerwas launched during the 2000''s. The nose behind this fragrance is Neil Morris. Top notes are Aldehydes and Sweet Orange; middle notes are Ylang-Ylang, Frangipani, Gardenia, Jasmine Sambac, Fig and Green Tea; base notes are Amber, Patchouli and Musk.',
        4.14,
        7,
        NULL
      ),
(
        'Midnight-Forest-24110',
        'Midnight Forest Neil Morris',
        'Midnight',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,green,musky,amber',
        'Midnight ForestbyNeil Morrisis a Woody fragrance for women and men.Midnight Forestwas launched in 2009. The nose behind this fragrance is Neil Morris.',
        3.83,
        6,
        NULL
      ),
(
        'Midnight-Moon-24111',
        'Midnight Moon Neil Morris',
        'Midnight',
        'for women and men',
        NULL,
        'Neil Morris',
        'Citron and Ivy',
        'Lotus, Lily-of-the-Valley and Jasmine',
        'Sandalwood and Myrrh',
        'white floral,fresh,green,woody,floral',
        'Midnight MoonbyNeil Morrisis a Floral Green fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Citron and Ivy; middle notes are Lotus, Lily-of-the-Valley and Jasmine; base notes are Sandalwood and Myrrh.',
        3,
        2,
        NULL
      ),
(
        'Midnight-Sea-24112',
        'Midnight Sea Neil Morris',
        'Midnight',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'patchouli,marine,musky,aquatic,aromatic',
        'Midnight SeabyNeil Morrisis a Floral Aquatic fragrance for women and men. The nose behind this fragrance is Neil Morris.',
        4.14,
        7,
        NULL
      ),
(
        'Midnight-Shadows-13765',
        'Midnight Shadows Neil Morris',
        'Midnight',
        'for women',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'tuberose,white floral,caramel,animalic,sweet',
        'Midnight ShadowsbyNeil Morrisis a Amber Vanilla fragrance for women.Midnight Shadowswas launched in 2011. The nose behind this fragrance is Neil Morris.',
        3.33,
        3,
        NULL
      ),
(
        'Midnight-Star-24113',
        'Midnight Star Neil Morris',
        'Midnight',
        'for women',
        NULL,
        'Neil Morris',
        'Aldehydes',
        'Mimosa, Lime (Linden) Blossom, Honeysuckle and Jasmine Sambac',
        'White Musk, Musk and Sandalwood',
        'yellow floral,aldehydic,powdery,sweet,fresh',
        'Midnight StarbyNeil Morrisis a Floral Aldehyde fragrance for women.Midnight Starwas launched in 2013. The nose behind this fragrance is Neil Morris. Top note is Aldehydes; middle notes are Mimosa, Lime (Linden) Blossom, Honeysuckle and Jasmine Sambac; base notes are White Musk, Musk and Sandalwood.',
        3.12,
        8,
        NULL
      ),
(
        'Midnight-Tryst-24114',
        'Midnight Tryst Neil Morris',
        'Midnight',
        'for women',
        NULL,
        'Neil Morris',
        'Cloves and Cinnamon',
        'Magnolia, French Narcissus, Gardenia and Rose',
        'Amber, Castoreum, Musk, Civet, Patchouli, Benzoin and Vanilla',
        'warm spicy,musky,amber,animalic,leather',
        'Midnight TrystbyNeil Morrisis a Amber Floral fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Cloves and Cinnamon; middle notes are Magnolia, French Narcissus, Gardenia and Rose; base notes are Amber, Castoreum, Musk, Civet, Patchouli, Benzoin and Vanilla.',
        4.07,
        15,
        NULL
      ),
(
        'Mystic-Dragon-24116',
        'Mystic Dragon Neil Morris',
        'Mystic',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'chocolate,warm spicy,patchouli,woody,sweet',
        'Mystic DragonbyNeil Morrisis a Amber Vanilla fragrance for women and men.Mystic Dragonwas launched in 2009. The nose behind this fragrance is Neil Morris.',
        3.9,
        10,
        NULL
      ),
(
        'October-9189',
        'October Neil Morris',
        'October',
        'for women',
        NULL,
        'Neil Morris',
        'Red Apple and Green Leaves',
        'Pine, Pumpkin, Carnation and Bitter Orange',
        'Cinnamon, Myrhh, Caramel, Olibanum and Patchouli',
        'warm spicy,cinnamon,amber,woody,sweet',
        'OctoberbyNeil Morrisis a Amber Spicy fragrance for women.Octoberwas launched during the 2000''s. The nose behind this fragrance is Neil Morris. Top notes are Red Apple and Green Leaves; middle notes are Pine, Pumpkin, Carnation and Bitter Orange; base notes are Cinnamon, Myrhh, Caramel, Olibanum and Patchouli.',
        4.04,
        97,
        NULL
      ),
(
        'Posh-24117',
        'Posh Neil Morris',
        'Posh',
        'for women',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'floral,fruity,patchouli,fresh,sweet',
        'PoshbyNeil Morrisis a Floral Fruity fragrance for women. The nose behind this fragrance is Neil Morris.',
        3.7,
        10,
        NULL
      ),
(
        'Prowl-15455',
        'Prowl Neil Morris',
        'Prowl',
        'for women and men',
        NULL,
        'Neil Morris',
        'Black Pepper and Green Tea',
        'Honeysuckle, Ylang-Ylang, Night blooming Cereus, Jasmine Sambac and Tuberose',
        'Civet, Oakmoss, Musk, Patchouli, Amber and Vanilla',
        'white floral,musky,animalic,yellow floral,powdery',
        'ProwlbyNeil Morrisis a Amber Woody fragrance for women and men.Prowlwas launched in 2009. The nose behind this fragrance is Neil Morris. Top notes are Black Pepper and Green Tea; middle notes are Honeysuckle, Ylang-Ylang, Night blooming Cereus, Jasmine Sambac and Tuberose; base notes are Civet, Oakmoss, Musk, Patchouli, Amber and Vanilla.',
        3.57,
        7,
        NULL
      ),
(
        'Quest-24118',
        'Quest Neil Morris',
        'Quest',
        'for women and men',
        NULL,
        'Neil Morris',
        'Watery Notes and Calabrian bergamot',
        'Grass and Heliotrope',
        'Myrrh, Patchouli and Precious Woods',
        'amber,woody,fresh,green,warm spicy',
        'QuestbyNeil Morrisis a Woody Aromatic fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Watery Notes and Calabrian bergamot; middle notes are Grass and Heliotrope; base notes are Myrrh, Patchouli and Precious Woods.',
        3.62,
        8,
        NULL
      ),
(
        'Rumi-24119',
        'Rumi Neil Morris',
        'Rumi',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'amber,patchouli,rose,warm spicy,woody',
        'RumibyNeil Morrisis a Amber fragrance for women and men.Rumiwas launched in 2009. The nose behind this fragrance is Neil Morris.',
        4.57,
        7,
        NULL
      ),
(
        'Scrumptious-13764',
        'Scrumptious Neil Morris',
        'Scrumptious',
        'for women and men',
        NULL,
        'Neil Morris',
        'Mandarin Orange, Pear, Bergamot and Rose',
        'Green Tea, Jasmine and Lavender',
        'Vanille and White Amber',
        'citrus,vanilla,fruity,sweet,amber',
        'ScrumptiousbyNeil Morrisis a Amber Floral fragrance for women and men.Scrumptiouswas launched in 2011. The nose behind this fragrance is Neil Morris. Top notes are Mandarin Orange, Pear, Bergamot and Rose; middle notes are Green Tea, Jasmine and Lavender; base notes are Vanille and White Amber.',
        4.11,
        18,
        NULL
      ),
(
        'Spectral-Violet-13836',
        'Spectral Violet Neil Morris',
        'Spectral',
        'for women',
        NULL,
        'Neil Morris',
        'Galbanum, Lime and Raspberry',
        'Violet',
        'Orris Root, Vetiver, Sandalwood, Musk and Seaweed',
        'powdery,woody,aromatic,green,iris',
        'Spectral VioletbyNeil Morrisis a Floral Woody Musk fragrance for women.Spectral Violetwas launched during the 2000''s. The nose behind this fragrance is Neil Morris. Top notes are Galbanum, Lime and Raspberry; middle note is Violet; base notes are Orris Root, Vetiver, Sandalwood, Musk and Seaweed.',
        3.36,
        14,
        NULL
      ),
(
        'Spirit-of-Water-24120',
        'Spirit of Water Neil Morris',
        'Spirit',
        'for women and men',
        NULL,
        'Neil Morris',
        'Wisteria and Water Lily',
        'Jasmine and Poppy',
        'Tonka Bean and Musk',
        'floral,white floral,fresh,fresh spicy',
        'Spirit of WaterbyNeil Morrisis a Floral Aquatic fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Wisteria and Water Lily; middle notes are Jasmine and Poppy; base notes are Tonka Bean and Musk.',
        3.6,
        5,
        NULL
      ),
(
        'Summer-of-Love-15456',
        'Summer of Love Neil Morris',
        'Summer',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'amber,patchouli,woody,animalic,musky',
        'Summer of LovebyNeil Morrisis a Chypre fragrance for women and men. The nose behind this fragrance is Neil Morris.',
        3.83,
        18,
        NULL
      ),
(
        'Swoon-24121',
        'Swoon Neil Morris',
        'Swoon',
        'for women and men',
        NULL,
        'Neil Morris',
        'Orange and Fruity Notes',
        'Green Notes, Honeysuckle, Jasmine Sambac, Peony, Narcissus, Tomato Leaf and Black Tea',
        'Civet, Oakmoss, Musk, Agarwood (Oud) and Patchouli',
        'white floral,musky,green,fruity,animalic',
        'SwoonbyNeil Morrisis a Chypre Floral fragrance for women and men. The nose behind this fragrance is Neil Morris. Top notes are Orange and Fruity Notes; middle notes are Green Notes, Honeysuckle, Jasmine Sambac, Peony, Narcissus, Tomato Leaf and Black Tea; base notes are Civet, Oakmoss, Musk, Agarwood (Oud) and Patchouli.',
        3.08,
        13,
        NULL
      ),
(
        'Trance-24122',
        'Trance Neil Morris',
        'Trance',
        'for women',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'amber,sweet,aldehydic,fresh,fruity',
        'TrancebyNeil Morrisis a Floral Fruity fragrance for women. The nose behind this fragrance is Neil Morris.',
        3.86,
        7,
        NULL
      ),
(
        'Vanille-Rose-24123',
        'Vanille Rose Neil Morris',
        'Vanille',
        'for women',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'vanilla,rose,powdery,floral,green',
        'Vanille RosebyNeil Morrisis a Amber Vanilla fragrance for women.Vanille Rosewas launched in 2009. The nose behind this fragrance is Neil Morris.',
        3.44,
        9,
        NULL
      ),
(
        'Vapor-24124',
        'Vapor Neil Morris',
        'Vapor',
        'for women and men',
        NULL,
        'Neil Morris',
        NULL,
        NULL,
        NULL,
        'aldehydic,amber,fresh,musky,powdery',
        'VaporbyNeil Morrisis a fragrance for women and men.Vaporwas launched in 2009. The nose behind this fragrance is Neil Morris.',
        3.29,
        7,
        NULL
      ),
(
        'Woodland-Strawberries-21463',
        'Woodland Strawberries Neil Morris',
        'Woodland',
        'for women',
        NULL,
        'Neil Morris',
        'Sweet Pea, Galbanum and Black Pepper',
        'Black currant leaf, Big Strawberry and Geranium',
        'Woody Notes, Oak and Sandalwood',
        'woody,fruity,green,fresh spicy,aromatic',
        'Woodland StrawberriesbyNeil Morrisis a Floral Fruity fragrance for women. The nose behind this fragrance is Neil Morris. Top notes are Sweet Pea, Galbanum and Black Pepper; middle notes are Black currant leaf, Big Strawberry and Geranium; base notes are Woody Notes, Oak and Sandalwood.',
        3.53,
        17,
        NULL
      ),
(
        'Amber-Eau-de-Parfum-78606',
        'Amber Eau de Parfum Nemat International',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber',
        'Amber Eau de ParfumbyNemat Internationalis a Amber fragrance for women and men.Amber Eau de Parfumwas launched in 2019.',
        4.06,
        17,
        NULL
      ),
(
        'Amber-Eau-De-Parfum-43494',
        'Amber Eau De Parfum Nemat International',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber',
        'Amber Eau De ParfumbyNemat Internationalis a Amber fragrance for women and men.Amber Eau De Parfumwas launched in 2016.',
        4.19,
        43,
        NULL
      ),
(
        'Sandalwood-Eau-de-Parfum-78605',
        'Sandalwood Eau de Parfum Nemat International',
        'Sandalwood',
        'for women and men',
        NULL,
        NULL,
        'Precious Woods',
        'Sandalwood',
        'Custard',
        'woody,powdery,warm spicy',
        'Sandalwood Eau de ParfumbyNemat Internationalis a Woody fragrance for women and men.Sandalwood Eau de Parfumwas launched in 2019. Top note is Precious Woods; middle note is Sandalwood; base note is Custard.',
        4,
        2,
        NULL
      ),
(
        'Vanilla-Musk-Eau-de-Parfum-78604',
        'Vanilla Musk Eau de Parfum Nemat International',
        'Vanilla',
        'for women',
        NULL,
        NULL,
        'Vanilla',
        'Cake',
        'Musk',
        'vanilla,powdery,musky,sweet',
        'Vanilla Musk Eau de ParfumbyNemat Internationalis a Amber Vanilla fragrance for women.Vanilla Musk Eau de Parfumwas launched in 2019. Top note is Vanilla; middle note is Cake; base note is Musk.',
        4.51,
        47,
        NULL
      ),
(
        'Amber-Fragrance-Oil-43495',
        'Amber Fragrance Oil Nemat International',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber',
        'Amber Fragrance OilbyNemat Internationalis a Amber fragrance for women and men.Amber Fragrance Oilwas launched in 1991.',
        4.52,
        698,
        NULL
      ),
(
        'Arabian-Wood-43496',
        'Arabian Wood Nemat International',
        'Arabian',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,fresh spicy',
        'Arabian WoodbyNemat Internationalis a Woody fragrance for women and men.Arabian Woodwas launched in 1991.',
        4.04,
        26,
        NULL
      ),
(
        'Egyptian-Musk-38908',
        'Egyptian Musk Nemat International',
        'Egyptian',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,musky,citrus,fresh',
        'Egyptian MuskbyNemat Internationalis a Amber fragrance for women and men.Egyptian Muskwas launched in 1991.',
        4.3,
        166,
        NULL
      ),
(
        'Gardenia-43497',
        'Gardenia Nemat International',
        'Gardenia',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,powdery',
        'GardeniabyNemat Internationalis a Floral fragrance for women and men.Gardeniawas launched in 1991.',
        3.52,
        21,
        NULL
      ),
(
        'Himalayan-Musk-43499',
        'Himalayan Musk Nemat International',
        'Himalayan',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,earthy,powdery',
        'Himalayan MuskbyNemat Internationalis a Aromatic fragrance for women and men.Himalayan Muskwas launched in 1991.',
        4,
        38,
        NULL
      ),
(
        'Jannatul-Firdaus-43500',
        'Jannatul Firdaus Nemat International',
        'Jannatul',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,fresh',
        'Jannatul FirdausbyNemat Internationalis a Citrus fragrance for women and men.Jannatul Firdauswas launched in 1991.',
        4.28,
        36,
        NULL
      ),
(
        'Jasmine-43501',
        'Jasmine Nemat International',
        'Jasmine',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral',
        'JasminebyNemat Internationalis a Floral fragrance for women and men.Jasminewas launched in 1991.',
        4,
        17,
        NULL
      ),
(
        'Lavender-43502',
        'Lavender Nemat International',
        'Lavender',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lavender,aromatic,fresh spicy',
        'LavenderbyNemat Internationalis a Floral fragrance for women and men.Lavenderwas launched in 1991.',
        3.25,
        8,
        NULL
      ),
(
        'Lotus-43527',
        'Lotus Nemat International',
        'Lotus',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,aquatic,ozonic,sweet',
        'LotusbyNemat Internationalis a Floral Fruity fragrance for women and men.Lotuswas launched in 1991.',
        3.19,
        16,
        NULL
      ),
(
        'Majmua-43532',
        'Majmua Nemat International',
        'Majmua',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,floral,musky,powdery',
        'MajmuabyNemat Internationalis a Floral Woody Musk fragrance for women and men.Majmuawas launched in 1991.',
        3.89,
        54,
        NULL
      ),
(
        'Mogra-43540',
        'Mogra Nemat International',
        'Mogra',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral',
        'MograbyNemat Internationalis a Floral fragrance for women and men.Mograwas launched in 1991.',
        3.6,
        15,
        NULL
      ),
(
        'Musk-Amber-43542',
        'Musk Amber Nemat International',
        'Musk',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,earthy,musky,sweet,powdery',
        'Musk AmberbyNemat Internationalis a Aromatic fragrance for women and men.Musk Amberwas launched in 1991.',
        4.09,
        147,
        NULL
      ),
(
        'Nag-Champa-43544',
        'Nag Champa Nemat International',
        'Nag',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,floral',
        'Nag ChampabyNemat Internationalis a Floral Green fragrance for women and men.Nag Champawas launched in 1991.',
        3.65,
        20,
        NULL
      ),
(
        'Narcissus-43546',
        'Narcissus Nemat International',
        'Narcissus',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,yellow floral,aromatic',
        'NarcissusbyNemat Internationalis a Floral fragrance for women and men.Narcissuswas launched in 1991.',
        3.86,
        28,
        NULL
      ),
(
        'Patchouli-43550',
        'Patchouli Nemat International',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'patchouli,woody,warm spicy,earthy,balsamic',
        'PatchoulibyNemat Internationalis a Woody fragrance for women and men.Patchouliwas launched in 1991.',
        3.67,
        24,
        NULL
      ),
(
        'Ruh-Gulab-43551',
        'Ruh Gulab Nemat International',
        'Ruh',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Ruh GulabbyNemat Internationalis a Floral fragrance for women and men.Ruh Gulabwas launched in 1991.',
        4.05,
        22,
        NULL
      ),
(
        'Sandal-Wood-43552',
        'Sandal Wood Nemat International',
        'Sandal',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy',
        'Sandal WoodbyNemat Internationalis a Woody fragrance for women and men.Sandal Woodwas launched in 1991.',
        4.09,
        78,
        NULL
      ),
(
        'Tropical-Bouquet-43553',
        'Tropical Bouquet Nemat International',
        'Tropical',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'earthy,woody,floral,amber',
        'Tropical BouquetbyNemat Internationalis a Floral Woody Musk fragrance for women and men.Tropical Bouquetwas launched in 1991.',
        2.71,
        7,
        NULL
      ),
(
        'Vanilla-Musk-43554',
        'Vanilla Musk Nemat International',
        'Vanilla',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,musky,sweet',
        'Vanilla MuskbyNemat Internationalis a Amber Vanilla fragrance for women and men.Vanilla Muskwas launched in 1991.',
        4.49,
        712,
        NULL
      ),
(
        'White-Musk-38909',
        'White Musk Nemat International',
        'White',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,woody,powdery',
        'White MuskbyNemat Internationalis a Floral Woody Musk fragrance for women and men.White Muskwas launched in 1991.',
        4.22,
        86,
        NULL
      ),
(
        'Candy-Cancan-74016',
        'Candy Cancan New Brand Parfums',
        'Candy',
        'for women',
        NULL,
        NULL,
        'Rose, Orange Blossom and Jasmine',
        'Cassis, Iris and Apple',
        'Musk, Vanilla and Amber',
        'powdery,white floral,rose,iris,musky',
        'Candy CancanbyNew Brand Parfumsis a Amber Vanilla fragrance for women.Candy Cancanwas launched in 2016. Top notes are Rose, Orange Blossom and Jasmine; middle notes are Cassis, Iris and Apple; base notes are Musk, Vanilla and Amber.',
        4,
        11,
        NULL
      ),
(
        'Chic-n-Glam-Elixir-74050',
        'Chic ''n Glam Elixir New Brand Parfums',
        'Chic',
        'for women',
        NULL,
        NULL,
        'Bitter Orange, Nasturtium and Neroli',
        'Peach, Datura and Rose',
        'Vanilla and Amber',
        'vanilla,citrus,fruity,sweet,powdery',
        'Chic ''n Glam ElixirbyNew Brand Parfumsis a Amber Floral fragrance for women.Chic ''n Glam Elixirwas launched in 2017. Top notes are Bitter Orange, Nasturtium and Neroli; middle notes are Peach, Datura and Rose; base notes are Vanilla and Amber.',
        4.1,
        10,
        NULL
      ),
(
        'Chic-n-Glam-Luxe-Edition-Tigress-84835',
        'Chic ''n Glam Luxe Edition Tigress New Brand Parfums',
        'Chic',
        'for women',
        NULL,
        NULL,
        'Bergamot, Almond, Coffee and Lemon',
        'Jasmine, Tuberose, Rose, Orange Blossom and Orris Root',
        'Tonka Bean, Vanilla, Cacao and Sandalwood',
        'white floral,citrus,warm spicy,vanilla,powdery',
        'Chic ''n Glam Luxe Edition TigressbyNew Brand Parfumsis a Floral fragrance for women.Chic ''n Glam Luxe Edition Tigresswas launched in 2019. Top notes are Bergamot, Almond, Coffee and Lemon; middle notes are Jasmine, Tuberose, Rose, Orange Blossom and Orris Root; base notes are Tonka Bean, Vanilla, Cacao and Sandalwood.',
        5,
        1,
        NULL
      ),
(
        'Classic-Oud-61182',
        'Classic Oud New Brand Parfums',
        'Classic',
        'for women',
        NULL,
        NULL,
        'Raspberry and Pear',
        'Damask Rose and Orange Blossom',
        'Agarwood (Oud), Patchouli and Amber',
        'fruity,rose,oud,sweet,patchouli',
        'Classic OudbyNew Brand Parfumsis a Amber Woody fragrance for women.Classic Oudwas launched in 2018. Top notes are Raspberry and Pear; middle notes are Damask Rose and Orange Blossom; base notes are Agarwood (Oud), Patchouli and Amber.',
        4.28,
        32,
        NULL
      ),
(
        'Club-No-1-74007',
        'Club Nº 1 New Brand Parfums',
        'Club',
        'for men',
        NULL,
        NULL,
        'Plum, Red Apple, Lemon and Bergamot',
        'Jasmine, Rose, Cinnamon and Cardamom',
        'Amber, Musk, Vanilla and Cedar',
        'fruity,citrus,white floral,rose,sweet',
        'Club Nº 1byNew Brand Parfumsis a Aromatic Fruity fragrance for men.Club Nº 1was launched in 2015. Top notes are Plum, Red Apple, Lemon and Bergamot; middle notes are Jasmine, Rose, Cinnamon and Cardamom; base notes are Amber, Musk, Vanilla and Cedar.',
        4.75,
        4,
        NULL
      ),
(
        'Cool-Woman-59119',
        'Cool Woman New Brand Parfums',
        'Cool',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,vanilla,sweet,powdery',
        'Cool WomanbyNew Brand Parfumsis a Amber Floral fragrance for women.Cool Womanwas launched in 2018.',
        3.95,
        19,
        NULL
      ),
(
        'Daily-60920',
        'Daily New Brand Parfums',
        'Daily',
        'for women',
        NULL,
        NULL,
        'Orange Blossom',
        'Bitter Orange Blossom',
        'Patchouli, Cedar and Honey',
        'white floral,woody,citrus,sweet,patchouli',
        'DailybyNew Brand Parfumsis a Amber Floral fragrance for women.Dailywas launched in 2018. Top note is Orange Blossom; middle note is Bitter Orange Blossom; base notes are Patchouli, Cedar and Honey.',
        4.14,
        21,
        NULL
      ),
(
        'Ego-Gold-74008',
        'Ego Gold New Brand Parfums',
        'Ego',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon and Pepper',
        'Lavender, Mint, Geranium and Rosemary',
        'Musk and Sandalwood',
        'fresh spicy,aromatic,citrus,woody,green',
        'Ego GoldbyNew Brand Parfumsis a Aromatic fragrance for men.Ego Goldwas launched in 2018. Top notes are Bergamot, Lemon and Pepper; middle notes are Lavender, Mint, Geranium and Rosemary; base notes are Musk and Sandalwood.',
        3.71,
        7,
        NULL
      ),
(
        'Ego-Silver-74009',
        'Ego Silver New Brand Parfums',
        'Ego',
        'for men',
        NULL,
        NULL,
        'Bergamot, Black Currant and Pineapple',
        'Jasmine, Patchouli and Red Fruits',
        'Oakmoss, Amber and Musk',
        'woody,earthy,fruity,mossy,white floral',
        'Ego SilverbyNew Brand Parfumsis a Amber Woody fragrance for men.Ego Silverwas launched in 2017. Top notes are Bergamot, Black Currant and Pineapple; middle notes are Jasmine, Patchouli and Red Fruits; base notes are Oakmoss, Amber and Musk.',
        3.82,
        11,
        NULL
      ),
(
        'Exceed-74010',
        'Exceed New Brand Parfums',
        'Exceed',
        'for men',
        NULL,
        NULL,
        'Bergamot and Lavender',
        'Clove, Sandalwood, Nutmeg and Lily-of-the-Valley',
        'Vetiver, Musk, Amber and Tonka Bean',
        'aromatic,woody,fresh spicy,warm spicy,amber',
        'ExceedbyNew Brand Parfumsis a Aromatic Spicy fragrance for men.Exceedwas launched in 2013. Top notes are Bergamot and Lavender; middle notes are Clove, Sandalwood, Nutmeg and Lily-of-the-Valley; base notes are Vetiver, Musk, Amber and Tonka Bean.',
        4.25,
        4,
        NULL
      ),
(
        'Extasia-Men-56242',
        'Extasia Men New Brand Parfums',
        'Extasia',
        'for men',
        NULL,
        NULL,
        'Ginger, Pepper and Tangerine',
        'Sage, Rain Notes, Cedar, Nutmeg and Basil',
        'Suede, Woody Notes, Patchouli and Amber',
        'aromatic,aquatic,herbal,fresh spicy,woody',
        'Extasia MenbyNew Brand Parfumsis a Woody Aromatic fragrance for men. Top notes are Ginger, Pepper and Tangerine; middle notes are Sage, Rain Notes, Cedar, Nutmeg and Basil; base notes are Suede, Woody Notes, Patchouli and Amber.',
        4,
        17,
        NULL
      ),
(
        'Extreme-Power-64626',
        'Extreme Power New Brand Parfums',
        'Extreme',
        'for men',
        NULL,
        NULL,
        'Red Apple and Tangerine',
        'Sage and Pepper',
        'Tobacco, Benzoin, Woodsy Notes and Patchouli',
        'woody,fruity,sweet,amber,tobacco',
        'Extreme PowerbyNew Brand Parfumsis a Aromatic fragrance for men.Extreme Powerwas launched in 2020. Top notes are Red Apple and Tangerine; middle notes are Sage and Pepper; base notes are Tobacco, Benzoin, Woodsy Notes and Patchouli.',
        3,
        4,
        NULL
      ),
(
        'French-Cancan-60921',
        'French Cancan New Brand Parfums',
        'French',
        'for women',
        NULL,
        NULL,
        'Star Anise, Orange Blossom, Pear, Rose, Mandarin Orange and Bergamot',
        'Iris, Tuberose, Orchid, Ylang-Ylang, Ginger and Plum',
        'Vanilla, Sandalowood, Musk, Cinnamon and Amber',
        'powdery,soft spicy,woody,warm spicy,vanilla',
        'French CancanbyNew Brand Parfumsis a Amber Floral fragrance for women.French Cancanwas launched in 2013. Top notes are Star Anise, Orange Blossom, Pear, Rose, Mandarin Orange and Bergamot; middle notes are Iris, Tuberose, Orchid, Ylang-Ylang, Ginger and Plum; base notes are Vanilla, Sandalowood, Musk, Cinnamon and Amber.',
        4.06,
        34,
        NULL
      ),
(
        'Gold-60973',
        'Gold New Brand Parfums',
        'Gold',
        'for men',
        NULL,
        NULL,
        'Mint, Blood Orange and Grapefruit',
        'Cinnamon, Rose and Coriander',
        'Woodsy Notes, Russian Leather, Styrax and Singapore Patchouli',
        'woody,aromatic,warm spicy,citrus,cinnamon',
        'GoldbyNew Brand Parfumsis a Amber Floral fragrance for men.Goldwas launched in 2016. Top notes are Mint, Blood Orange and Grapefruit; middle notes are Cinnamon, Rose and Coriander; base notes are Woodsy Notes, Russian Leather, Styrax and Singapore Patchouli.',
        3.83,
        23,
        NULL
      );
