
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Fontana-di-Trevi-XVI-40409',
        'Fontana di Trevi XVI Acqua di Genova',
        'Fontana',
        'for women',
        NULL,
        NULL,
        'Lilac and Tea Rose',
        'Geranium and Iris',
        'Ambergris, Musk and Vanilla',
        'rose,floral,powdery,amber,vanilla',
        'Fontana di Trevi XVIbyAcqua di Genovais a fragrance for women. Top notes are Lilac and Tea Rose; middle notes are Geranium and Iris; base notes are Ambergris, Musk and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Fontana-di-Trevi-XVIII-40406',
        'Fontana di Trevi XVIII Acqua di Genova',
        'Fontana',
        'for women',
        NULL,
        NULL,
        'Aldehydes',
        'Ylang-Ylang and Rose',
        'Whipped Cream, White Musk, Ambergris and Vanilla',
        'sweet,vanilla,yellow floral,musky,rose',
        'Fontana di Trevi XVIIIbyAcqua di Genovais a fragrance for women. Top note is Aldehydes; middle notes are Ylang-Ylang and Rose; base notes are Whipped Cream, White Musk, Ambergris and Vanilla.',
        3.8,
        5,
        NULL
      ),
(
        'Fresh-40408',
        'Fresh Acqua di Genova',
        'Fresh',
        'for women and men',
        NULL,
        'Stefano Frecceri',
        'Lime, Bergamot and Grapefruit',
        'Jasmine, Ginger, Orange Blossom and Lavender',
        'Patchouli, Vetiver, Ambergris and Musk',
        'citrus,white floral,aromatic,woody,fresh spicy',
        'FreshbyAcqua di Genovais a fragrance for women and men.Freshwas launched in 2011. The nose behind this fragrance is Stefano Frecceri. Top notes are Lime, Bergamot and Grapefruit; middle notes are Jasmine, Ginger, Orange Blossom and Lavender; base notes are Patchouli, Vetiver, Ambergris and Musk.',
        3.83,
        6,
        NULL
      ),
(
        'Genes-12209',
        'Genes Acqua di Genova',
        'Genes',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Amalfi Lemon, Neroli, Orange and Rosemary',
        'Jasmine, Rose and African Orange Flower',
        'Musk, Sandalwood, Patchouli and Amber',
        'citrus,aromatic,fresh spicy,white floral',
        'GenesbyAcqua di Genovais a Citrus Aromatic fragrance for women and men.Geneswas launched in 1853. Top notes are Bergamot, Amalfi Lemon, Neroli, Orange and Rosemary; middle notes are Jasmine, Rose and African Orange Flower; base notes are Musk, Sandalwood, Patchouli and Amber.',
        4.2,
        30,
        NULL
      ),
(
        'Gold-5263',
        'Gold Acqua di Genova',
        'Gold',
        'for women and men',
        NULL,
        'Stefano Frecceri',
        'Bergamot, Amalfi Lemon, Lotus and Cardamom',
        'Violet and Rose',
        'Almond Blossom and Musk',
        'floral,citrus,powdery,violet,rose',
        'GoldbyAcqua di Genovais a Floral fragrance for women and men.Goldwas launched in 1853. The nose behind this fragrance is Stefano Frecceri. Top notes are Bergamot, Amalfi Lemon, Lotus and Cardamom; middle notes are Violet and Rose; base notes are Almond Blossom and Musk.',
        4.13,
        31,
        NULL
      ),
(
        'Gold-2-40410',
        'Gold 2 Acqua di Genova',
        'Gold',
        'for women and men',
        NULL,
        NULL,
        'Anise and Geranium',
        'Ylang-Ylang, Rosemary and Vanilla',
        'Amber and White Musk',
        'aromatic,fresh spicy,anis,sweet,yellow floral',
        'Gold 2byAcqua di Genovais a fragrance for women and men. Top notes are Anise and Geranium; middle notes are Ylang-Ylang, Rosemary and Vanilla; base notes are Amber and White Musk.',
        4.22,
        23,
        NULL
      ),
(
        'Gold-Plate-City-of-New-York-1974-15065',
        'Gold Plate City of New York 1974 Acqua di Genova',
        'Gold',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Bergamot, Lemon and Bitter Orange',
        'Lavender, Rose, Rosemary and Jasmine',
        'Ambergris, Musk, Sandalwood and Patchouli',
        'aromatic,amber,rose,lavender,fresh spicy',
        'Gold Plate City of New York 1974byAcqua di Genovais a Floral fragrance for women. Top notes are Orange Blossom, Bergamot, Lemon and Bitter Orange; middle notes are Lavender, Rose, Rosemary and Jasmine; base notes are Ambergris, Musk, Sandalwood and Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Silver-5262',
        'Silver Acqua di Genova',
        'Silver',
        'for women and men',
        NULL,
        'Stefano Frecceri',
        'Pear, Bergamot, Green Notes, Green Apple and Red Berries',
        'Violet, Rose, Lavender and Geranium',
        'Musk, Woodsy Notes and Sandalwood',
        'fruity,green,fresh,powdery,sweet',
        'SilverbyAcqua di Genovais a Floral Fruity fragrance for women and men.Silverwas launched in 1853. The nose behind this fragrance is Stefano Frecceri. Top notes are Pear, Bergamot, Green Notes, Green Apple and Red Berries; middle notes are Violet, Rose, Lavender and Geranium; base notes are Musk, Woodsy Notes and Sandalwood.',
        4.46,
        26,
        NULL
      ),
(
        'Silver-2-40411',
        'Silver 2 Acqua di Genova',
        'Silver',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, Orange Blossom and Pepper',
        'Jasmine, Rose and Carnation',
        'Tonka Bean, Vanilla and Patchouli',
        'citrus,white floral,sweet,vanilla,warm spicy',
        'Silver 2byAcqua di Genovais a fragrance for women and men. Top notes are Tangerine, Orange Blossom and Pepper; middle notes are Jasmine, Rose and Carnation; base notes are Tonka Bean, Vanilla and Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Contessa-di-Castiglione-Lady-Gold-45103',
        'Contessa di Castiglione Lady Gold Acqua di Genova',
        'Contessa',
        'for women',
        NULL,
        NULL,
        'Black Currant, White Peach and Freesia',
        'Coconut, Hazelnut, Jasmine and Rose',
        'Patchouli, Amber and Musk',
        'nutty,woody,coconut,sweet,patchouli',
        'Contessa di Castiglione Lady GoldbyAcqua di Genovais a Floral Fruity fragrance for women.Contessa di Castiglione Lady Goldwas launched during the 2010''s. Top notes are Black Currant, White Peach and Freesia; middle notes are Coconut, Hazelnut, Jasmine and Rose; base notes are Patchouli, Amber and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Contessa-di-Castiglione-Lady-Silver-45102',
        'Contessa di Castiglione Lady Silver Acqua di Genova',
        'Contessa',
        'for women',
        NULL,
        NULL,
        'Lemon Peel, Bergamot, Cardamom and Lotus',
        'Turkish Rose, Red Currant and Violet',
        'Almond Blossom and White Musk',
        'floral,citrus,rose,powdery,sweet',
        'Contessa di Castiglione Lady SilverbyAcqua di Genovais a Floral fragrance for women.Contessa di Castiglione Lady Silverwas launched during the 2010''s. Top notes are Lemon Peel, Bergamot, Cardamom and Lotus; middle notes are Turkish Rose, Red Currant and Violet; base notes are Almond Blossom and White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Bougainvellea-15051',
        'Bougainvellea Acqua di Genova',
        'Bougainvellea',
        'for women',
        NULL,
        'Stefano Frecceri',
        'Grapefruit, Mandarin Orange and Orange',
        'Violet, Bougainvillea, Peony, Rose, Lily-of-the-Valley and Jasmine',
        'Amber and Musk',
        'floral,citrus,fresh,violet,powdery',
        'BougainvelleabyAcqua di Genovais a Floral fragrance for women.Bougainvelleawas launched in 2008. The nose behind this fragrance is Stefano Frecceri. Top notes are Grapefruit, Mandarin Orange and Orange; middle notes are Violet, Bougainvillea, Peony, Rose, Lily-of-the-Valley and Jasmine; base notes are Amber and Musk.',
        4,
        18,
        NULL
      ),
(
        'Mora-Di-Gelso-15061',
        'Mora Di Gelso Acqua di Genova',
        'Mora',
        'for women and men',
        NULL,
        'Stefano Frecceri',
        'Grapefruit and Black Currant',
        'mulberry, Hyacinth, Rose and Lilac',
        'Vanilla and Woodsy Notes',
        'fruity,citrus,woody,floral,fresh spicy',
        'Mora Di GelsobyAcqua di Genovais a Floral Fruity fragrance for women and men.Mora Di Gelsowas launched in 2008. The nose behind this fragrance is Stefano Frecceri. Top notes are Grapefruit and Black Currant; middle notes are mulberry, Hyacinth, Rose and Lilac; base notes are Vanilla and Woodsy Notes.',
        4.12,
        16,
        NULL
      ),
(
        'Mughetto-15053',
        'Mughetto Acqua di Genova',
        'Mughetto',
        'for women',
        NULL,
        'Stefano Frecceri',
        'Bergamot and Peach',
        'Lily-of-the-Valley and Peony',
        'Iris and Musk',
        'fresh,floral,white floral,iris,powdery',
        'MughettobyAcqua di Genovais a Floral Green fragrance for women.Mughettowas launched in 2008. The nose behind this fragrance is Stefano Frecceri. Top notes are Bergamot and Peach; middle notes are Lily-of-the-Valley and Peony; base notes are Iris and Musk.',
        3.69,
        13,
        NULL
      ),
(
        'Rovo-Nero-15062',
        'Rovo Nero Acqua di Genova',
        'Rovo',
        'for women',
        NULL,
        'Stefano Frecceri',
        'Lime, Bergamot and Lemon',
        'Rose, Violet, Lily-of-the-Valley, Bougainvillea and Lily',
        'Wisteria, Vetiver, Sandalwood, Boletus edulis, Patchouli and Musk',
        'floral,woody,earthy,citrus,fresh',
        'Rovo NerobyAcqua di Genovais a Floral Fruity fragrance for women.Rovo Nerowas launched in 2008. The nose behind this fragrance is Stefano Frecceri. Top notes are Lime, Bergamot and Lemon; middle notes are Rose, Violet, Lily-of-the-Valley, Bougainvillea and Lily; base notes are Wisteria, Vetiver, Sandalwood, Boletus edulis, Patchouli and Musk.',
        3.88,
        16,
        NULL
      ),
(
        'Tuberosa-15060',
        'Tuberosa Acqua di Genova',
        'Tuberosa',
        'for women and men',
        NULL,
        'Stefano Frecceri',
        'Cloves',
        'Tuberose and Ylang-Ylang',
        'Musk and Sandalwood',
        'tuberose,warm spicy,woody,white floral,musky',
        'TuberosabyAcqua di Genovais a Amber Floral fragrance for women and men.Tuberosawas launched in 2008. The nose behind this fragrance is Stefano Frecceri. Top note is Cloves; middle notes are Tuberose and Ylang-Ylang; base notes are Musk and Sandalwood.',
        3.71,
        17,
        NULL
      ),
(
        'Violetta-Extreme-15052',
        'Violetta Extreme Acqua di Genova',
        'Violetta',
        'for women',
        NULL,
        'Stefano Frecceri',
        'Mirabelle and Neroli',
        'Violet and Jasmine',
        'Sandalwood and Amber',
        'powdery,white floral,violet,woody,floral',
        'Violetta ExtremebyAcqua di Genovais a Floral Fruity fragrance for women.Violetta Extremewas launched in 2008. The nose behind this fragrance is Stefano Frecceri. Top notes are Mirabelle and Neroli; middle notes are Violet and Jasmine; base notes are Sandalwood and Amber.',
        4.17,
        23,
        NULL
      ),
(
        '369-90813',
        '369 Acqua di Portofino',
        '369',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Orchid and Clementine',
        'Chamomile, Jasmine and Powdery Notes',
        'Amber, Tonka Bean, Musk and Vanilla',
        'powdery,sweet,soft spicy,amber,floral',
        '369byAcqua di Portofinois a Floral Woody Musk fragrance for women and men. This is a new fragrance.369was launched in 2024. Top notes are Pink Pepper, Orchid and Clementine; middle notes are Chamomile, Jasmine and Powdery Notes; base notes are Amber, Tonka Bean, Musk and Vanilla.',
        5,
        1,
        NULL
      ),
(
        'Baia-90814',
        'Baia Acqua di Portofino',
        'Baia',
        'for women and men',
        NULL,
        NULL,
        'Roasted Coffee Beans, Freesia and Lily of the Valley',
        'Sugar, Ambrette and Jasmine',
        'Vanilla, Musk, Amberwood, Milk Cream and Oakmoss',
        'amber,coffee,vanilla,warm spicy,sweet',
        'BaiabyAcqua di Portofinois a Floral Aquatic fragrance for women and men. This is a new fragrance.Baiawas launched in 2024. Top notes are Roasted Coffee Beans, Freesia and Lily of the Valley; middle notes are Sugar, Ambrette and Jasmine; base notes are Vanilla, Musk, Amberwood, Milk Cream and Oakmoss.',
        4.5,
        2,
        NULL
      ),
(
        'Borgo-18809',
        'Borgo Acqua di Portofino',
        'Borgo',
        'for women',
        NULL,
        'Maurizio Cerizza',
        'Bergamot, Lemon and Cherry',
        'White Flowers, Jasmine, Pitosporum and Ylang-Ylang',
        'Patchouli, Vanila, Musk, Cedar and Amber',
        'white floral,citrus,woody,patchouli,sweet',
        'BorgobyAcqua di Portofinois a Floral Woody Musk fragrance for women.Borgowas launched in 2013. The nose behind this fragrance is Maurizio Cerizza. Top notes are Bergamot, Lemon and Cherry; middle notes are White Flowers, Jasmine, Pitosporum and Ylang-Ylang; base notes are Patchouli, Vanila, Musk, Cedar and Amber.',
        3.94,
        32,
        NULL
      ),
(
        'Falo-90815',
        'Falo Acqua di Portofino',
        'Falo',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Incense and Smoke',
        'Jasmine, Iris, Cedarwood, Patchouli and Oud',
        'Amber, Sandalwood, Oakmoss, Leather and Vetiver',
        'iris,white floral,powdery,amber,violet',
        'FalobyAcqua di Portofinois a Amber Woody fragrance for women and men. This is a new fragrance.Falowas launched in 2024. Top notes are Saffron, Incense and Smoke; middle notes are Jasmine, Iris, Cedarwood, Patchouli and Oud; base notes are Amber, Sandalwood, Oakmoss, Leather and Vetiver.',
        5,
        1,
        NULL
      ),
(
        'Insolito-90817',
        'Insolito Acqua di Portofino',
        'Insolito',
        'for women and men',
        NULL,
        NULL,
        'Incense, Bergamot, Sweet Orange and Mugwort',
        'Spices, Amyris, Myrrh and Patchouli',
        'Precious Woods, Amber, Musk, Vetiver and Oakmoss',
        'amber,woody,warm spicy,aromatic,balsamic',
        'InsolitobyAcqua di Portofinois a Amber Woody fragrance for women and men. This is a new fragrance.Insolitowas launched in 2024. Top notes are Incense, Bergamot, Sweet Orange and Mugwort; middle notes are Spices, Amyris, Myrrh and Patchouli; base notes are Precious Woods, Amber, Musk, Vetiver and Oakmoss.',
        4,
        1,
        NULL
      ),
(
        'Levante-90816',
        'Levante Acqua di Portofino',
        'Levante',
        'for women and men',
        NULL,
        NULL,
        'Nectarine, Apricot, Citruses and Honey',
        'Davana, Osmanthus, Peony, Ylang-Ylang and Patchouli',
        'Musk, Amber, Vanilla, Cedarwood, Sandalwood and Benzoin',
        'fruity,musky,aromatic,green,powdery',
        'LevantebyAcqua di Portofinois a Woody Floral Musk fragrance for women and men. This is a new fragrance.Levantewas launched in 2024. Top notes are Nectarine, Apricot, Citruses and Honey; middle notes are Davana, Osmanthus, Peony, Ylang-Ylang and Patchouli; base notes are Musk, Amber, Vanilla, Cedarwood, Sandalwood and Benzoin.',
        4,
        1,
        NULL
      ),
(
        'Maremosso-90818',
        'Maremosso Acqua di Portofino',
        'Maremosso',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Black Currant, Marine notes and Rosemary',
        'Water Lily, Basil, Lavender and Damask Rose',
        'Musk, Cedarwood, Sandalwood and Ambrette',
        'aromatic,woody,fresh spicy,citrus,musky',
        'MaremossobyAcqua di Portofinois a Aromatic Aquatic fragrance for women and men. This is a new fragrance.Maremossowas launched in 2024. Top notes are Grapefruit, Black Currant, Marine notes and Rosemary; middle notes are Water Lily, Basil, Lavender and Damask Rose; base notes are Musk, Cedarwood, Sandalwood and Ambrette.',
        5,
        4,
        NULL
      ),
(
        'Notte-30548',
        'Notte Acqua di Portofino',
        'Notte',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Sea water, Olive Tree, Sea Salt and Lemon',
        'Water Jasmine, Pitosporum and Honeysuckle',
        'Olive Tree, Amber and Musk',
        'white floral,marine,salty,aromatic,amber',
        'NottebyAcqua di Portofinois a Floral Woody Musk fragrance for women and men.Nottewas launched in 2015. The nose behind this fragrance is Maurizio Cerizza. Top notes are Sea water, Olive Tree, Sea Salt and Lemon; middle notes are Water Jasmine, Pitosporum and Honeysuckle; base notes are Olive Tree, Amber and Musk.',
        4.16,
        32,
        NULL
      ),
(
        'Acqua-di-Portofino-3703',
        'Acqua di Portofino Acqua di Portofino',
        'Acqua',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Tangerine, Lemon and Tarragon',
        'Pitosporum, Lavender, Nutmeg, Coriander and Cardamom',
        'Vetiver, Musk and Patchouli',
        'aromatic,citrus,white floral,fresh spicy,lavender',
        'Acqua di PortofinobyAcqua di Portofinois a Woody Aromatic fragrance for women and men.Acqua di Portofinowas launched in 2000. The nose behind this fragrance is Maurizio Cerizza. Top notes are Tangerine, Lemon and Tarragon; middle notes are Pitosporum, Lavender, Nutmeg, Coriander and Cardamom; base notes are Vetiver, Musk and Patchouli.',
        4.06,
        47,
        NULL
      ),
(
        'Acqua-di-Portofino-Uomo-19399',
        'Acqua di Portofino Uomo Acqua di Portofino',
        'Acqua',
        'for men',
        NULL,
        'Francesca Casiraghi',
        'Basil, Olive Tree, Grapefruit, Star Anise, Lavender and Black Currant',
        'Jasmine, Watery Notes, Nutmeg, Magnolia, Pepper and Pimento',
        'Sandalwood, Vetiver and Musk',
        'fresh spicy,woody,aromatic,floral,powdery',
        'Acqua di Portofino UomobyAcqua di Portofinois a Aromatic Spicy fragrance for men. Acqua di Portofino Uomo was created by Francesca Casiraghi and Maurizio Cerizza. Top notes are Basil, Olive Tree, Grapefruit, Star Anise, Lavender and Black Currant; middle notes are Jasmine, Watery Notes, Nutmeg, Magnolia, Pepper and Pimento; base notes are Sandalwood, Vetiver and Musk.',
        4.1,
        10,
        NULL
      ),
(
        'Donna-3666',
        'Donna Acqua di Portofino',
        'Donna',
        'for women',
        NULL,
        'Francesca Casiraghi',
        'Lime, Red Apple and Olive Tree',
        'Ginger, Magnolia and Jasmine',
        'White Musk, Cedar and Sandalwood',
        'citrus,woody,warm spicy,floral,fruity',
        'DonnabyAcqua di Portofinois a Floral Woody Musk fragrance for women.Donnawas launched in 2008. Donna was created by Francesca Casiraghi and Maurizio Cerizza. Top notes are Lime, Red Apple and Olive Tree; middle notes are Ginger, Magnolia and Jasmine; base notes are White Musk, Cedar and Sandalwood.',
        4,
        76,
        NULL
      ),
(
        'Faro-49360',
        'Faro Acqua di Portofino',
        'Faro',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Grapefruit, Lime, Ginger and Calabrian bergamot',
        'Olive Tree, Watery Notes, Mineral notes and Magnolia',
        'Amber, Patchouli and White Musk',
        'citrus,fresh spicy,warm spicy,woody',
        'FarobyAcqua di Portofinois a Citrus Aromatic fragrance for women and men.Farowas launched in 2018. The nose behind this fragrance is Maurizio Cerizza. Top notes are Grapefruit, Lime, Ginger and Calabrian bergamot; middle notes are Olive Tree, Watery Notes, Mineral notes and Magnolia; base notes are Amber, Patchouli and White Musk.',
        4.02,
        62,
        NULL
      ),
(
        'R-Osa-Eau-de-Parfum-Sensuelle-37731',
        'R''Osa Eau de Parfum Sensuelle Acqua di Portofino',
        'R''Osa',
        'for women',
        NULL,
        'Maurizio Cerizza',
        'Mango, Pink Pepper, Yellow Mandarin and Bergamot',
        'Heliotrope, Damask Rose and Jasmine Sambac',
        'Vanilla, Amber, Musk and Amberwood',
        'vanilla,powdery,amber,rose,musky',
        'R''Osa Eau de Parfum SensuellebyAcqua di Portofinois a Amber Floral fragrance for women.R''Osa Eau de Parfum Sensuellewas launched in 2016. The nose behind this fragrance is Maurizio Cerizza. Top notes are Mango, Pink Pepper, Yellow Mandarin and Bergamot; middle notes are Heliotrope, Damask Rose and Jasmine Sambac; base notes are Vanilla, Amber, Musk and Amberwood.',
        3.67,
        43,
        NULL
      ),
(
        'Sail-17036',
        'Sail Acqua di Portofino',
        'Sail',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Watery Notes and Eucalyptus',
        'Geranium, Thyme and Jasmine',
        'White Musk and Patchouli',
        'aromatic,aquatic,woody,fresh spicy,camphor',
        'SailbyAcqua di Portofinois a Aromatic Spicy fragrance for women and men.Sailwas launched in 2012. The nose behind this fragrance is Maurizio Cerizza. Top notes are Watery Notes and Eucalyptus; middle notes are Geranium, Thyme and Jasmine; base notes are White Musk and Patchouli.',
        4.08,
        148,
        NULL
      ),
(
        'Acqua-di-Sardegna-Man-Eau-de-Parfum-41823',
        'Acqua di Sardegna Man Eau de Parfum Acqua di Sardegna',
        'Acqua',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot, Tangerine and Petitgrain',
        'Orange Blossom, Ginger and Rose',
        'Vetiver, Musk and Amber',
        'citrus,aromatic,white floral',
        'Acqua di Sardegna Man Eau de ParfumbyAcqua di Sardegnais a Woody Floral Musk fragrance for men.Acqua di Sardegna Man Eau de Parfumwas launched in 2008. Top notes are Lemon, Bergamot, Tangerine and Petitgrain; middle notes are Orange Blossom, Ginger and Rose; base notes are Vetiver, Musk and Amber.',
        4,
        14,
        NULL
      ),
(
        'Acqua-di-Sardegna-Man-Eau-de-Toilette-41824',
        'Acqua di Sardegna Man Eau de Toilette Acqua di Sardegna',
        'Acqua',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Tangerine and Petitgrain',
        'Ginger, Rose and Orange Blossom',
        'Musk, Vetiver and Amber',
        'citrus,aromatic,musky,white floral',
        'Acqua di Sardegna Man Eau de ToilettebyAcqua di Sardegnais a Woody Floral Musk fragrance for men.Acqua di Sardegna Man Eau de Toilettewas launched in 2008. Top notes are Bergamot, Lemon, Tangerine and Petitgrain; middle notes are Ginger, Rose and Orange Blossom; base notes are Musk, Vetiver and Amber.',
        3.67,
        3,
        NULL
      ),
(
        'Acqua-di-Sardegna-Unisex-Eau-de-Parfum-41827',
        'Acqua di Sardegna Unisex Eau de Parfum Acqua di Sardegna',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, Grapefruit, Lemon and Petitgrain',
        'Star Anise, Rosemary, Lavender and Fruits',
        'Vetiver, Musk, Coumarin and Amber',
        'citrus,aromatic,woody,fresh spicy,sweet',
        'Acqua di Sardegna Unisex Eau de ParfumbyAcqua di Sardegnais a Citrus Aromatic fragrance for women and men.Acqua di Sardegna Unisex Eau de Parfumwas launched in 2014. Top notes are Tangerine, Grapefruit, Lemon and Petitgrain; middle notes are Star Anise, Rosemary, Lavender and Fruits; base notes are Vetiver, Musk, Coumarin and Amber.',
        4,
        10,
        NULL
      ),
(
        'Acqua-di-Sardegna-Unisex-Eau-de-Toilette-41828',
        'Acqua di Sardegna Unisex Eau de Toilette Acqua di Sardegna',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Petitgrain, Tangerine and Lemon',
        'Lavender, Rosemary, Star Anise and Fruits',
        'Coumarin, Amber, Vetiver and Musk',
        'aromatic,citrus,woody,fresh spicy,sweet',
        'Acqua di Sardegna Unisex Eau de ToilettebyAcqua di Sardegnais a Citrus Aromatic fragrance for women and men.Acqua di Sardegna Unisex Eau de Toilettewas launched in 2014. Top notes are Grapefruit, Petitgrain, Tangerine and Lemon; middle notes are Lavender, Rosemary, Star Anise and Fruits; base notes are Coumarin, Amber, Vetiver and Musk.',
        5,
        2,
        NULL
      ),
(
        'Acqua-di-Sardegna-Woman-Eau-de-Parfum-41821',
        'Acqua di Sardegna Woman Eau de Parfum Acqua di Sardegna',
        'Acqua',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley, Bergamot, Orange and Mint',
        'White Flowers, Almond and Rose',
        'Cedar, Musk and Amber',
        'white floral,citrus,fresh,almond,green',
        'Acqua di Sardegna Woman Eau de ParfumbyAcqua di Sardegnais a Amber Floral fragrance for women.Acqua di Sardegna Woman Eau de Parfumwas launched in 2008. Top notes are Lily-of-the-Valley, Bergamot, Orange and Mint; middle notes are White Flowers, Almond and Rose; base notes are Cedar, Musk and Amber.',
        3.59,
        17,
        NULL
      ),
(
        'Acqua-di-Sardegna-Woman-Eau-de-Toilette-41822',
        'Acqua di Sardegna Woman Eau de Toilette Acqua di Sardegna',
        'Acqua',
        'for women',
        NULL,
        NULL,
        'Orange, Bergamot, Lily-of-the-Valley and Mint',
        'Almond, Rose and White Flowers',
        'Musk, Cedar and Amber',
        'citrus,white floral,green,fresh spicy,woody',
        'Acqua di Sardegna Woman Eau de ToilettebyAcqua di Sardegnais a Amber Floral fragrance for women.Acqua di Sardegna Woman Eau de Toilettewas launched in 2008. Top notes are Orange, Bergamot, Lily-of-the-Valley and Mint; middle notes are Almond, Rose and White Flowers; base notes are Musk, Cedar and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Desvelos-Unisex-Eau-de-Parfum-41833',
        'Desvélos Unisex Eau de Parfum Acqua di Sardegna',
        'Desvélos',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes, Lavender and Heliotrope',
        'Myrtle, Costus and Cedar',
        'Patchouli, Amber and Vetiver',
        'aromatic,woody,earthy,fresh spicy,patchouli',
        'Desvélos Unisex Eau de ParfumbyAcqua di Sardegnais a Aromatic Aquatic fragrance for women and men.Desvélos Unisex Eau de Parfumwas launched in 2016. Top notes are Sea Notes, Lavender and Heliotrope; middle notes are Myrtle, Costus and Cedar; base notes are Patchouli, Amber and Vetiver.',
        4.38,
        21,
        NULL
      ),
(
        'Hirvu-Free-Island-55846',
        'Hirvu Free Island Acqua di Sardegna',
        'Hirvu',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Cardamom, Carrot Seeds and Sea Notes',
        'Violet, Dew Drop, Laminaria and Coriander',
        'Incense, Vanilla, Vetiver and Patchouli',
        'powdery,citrus,violet,aquatic,warm spicy',
        'Hirvu Free IslandbyAcqua di Sardegnais a Aromatic Spicy fragrance for women and men.Hirvu Free Islandwas launched in 2019. Top notes are Bergamot, Cardamom, Carrot Seeds and Sea Notes; middle notes are Violet, Dew Drop, Laminaria and Coriander; base notes are Incense, Vanilla, Vetiver and Patchouli.',
        4.13,
        15,
        NULL
      ),
(
        'Maijda-Man-Eau-de-Parfum-41826',
        'Maijda Man Eau de Parfum Acqua di Sardegna',
        'Maijda',
        'for men',
        NULL,
        NULL,
        'Lemon, Grapefruit and Orange',
        'Black Currant, Pink Pepper, Myrtle and Lilac',
        'Amber, Patchouli and Cedar',
        'citrus,fruity,soft spicy,aromatic,woody',
        'Maijda Man Eau de ParfumbyAcqua di Sardegnais a Aromatic Fruity fragrance for men.Maijda Man Eau de Parfumwas launched in 2010. Top notes are Lemon, Grapefruit and Orange; middle notes are Black Currant, Pink Pepper, Myrtle and Lilac; base notes are Amber, Patchouli and Cedar.',
        3.87,
        15,
        NULL
      ),
(
        'Maijda-Woman-Eau-de-Parfum-41825',
        'Maijda Woman Eau de Parfum Acqua di Sardegna',
        'Maijda',
        'for women',
        NULL,
        NULL,
        'Bergamot, Grapefruit, Lily-of-the-Valley and Lemon',
        'Myrtle, Thyme, White Peach, Magnolia, Peony and Rose',
        'White Musk, Vanilla, Patchouli and Cedar',
        'aromatic,citrus,fresh spicy,floral,herbal',
        'Maijda Woman Eau de ParfumbyAcqua di Sardegnais a Chypre Floral fragrance for women.Maijda Woman Eau de Parfumwas launched in 2010. Top notes are Bergamot, Grapefruit, Lily-of-the-Valley and Lemon; middle notes are Myrtle, Thyme, White Peach, Magnolia, Peony and Rose; base notes are White Musk, Vanilla, Patchouli and Cedar.',
        3.83,
        23,
        NULL
      ),
(
        'Nois-Unisex-Eau-de-Parfum-41832',
        'Nòis Unisex Eau de Parfum Acqua di Sardegna',
        'Nòis',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Neroli, Lemon and Grapefruit',
        'Rhubarb, Orange Blossom, Night Blooming Jasmine, Rosemary and Iris',
        'Cedar, Musk, Vetiver, Ambrette (Musk Mallow) and Patchouli',
        'citrus,aromatic,fresh spicy,white floral,woody',
        'Nòis Unisex Eau de ParfumbyAcqua di Sardegnais a Floral Woody Musk fragrance for women and men.Nòis Unisex Eau de Parfumwas launched in 2016. Top notes are Bergamot, Neroli, Lemon and Grapefruit; middle notes are Rhubarb, Orange Blossom, Night Blooming Jasmine, Rosemary and Iris; base notes are Cedar, Musk, Vetiver, Ambrette (Musk Mallow) and Patchouli.',
        4.43,
        14,
        NULL
      ),
(
        'Scalo-Porto-Cervo-Man-Eau-de-Parfum-41830',
        'Scalo Porto Cervo Man Eau de Parfum Acqua di Sardegna',
        'Scalo',
        'for men',
        NULL,
        NULL,
        'Lemon, Coffee, Styrax and Labdanum',
        'Lavender, Cedar, Patchouli, May Rose and Vetiver',
        'Amberwood, Leather, Vanila, Amber and Lorenox',
        'amber,woody,warm spicy,leather,citrus',
        'Scalo Porto Cervo Man Eau de ParfumbyAcqua di Sardegnais a Amber Woody fragrance for men.Scalo Porto Cervo Man Eau de Parfumwas launched in 2014. Top notes are Lemon, Coffee, Styrax and Labdanum; middle notes are Lavender, Cedar, Patchouli, May Rose and Vetiver; base notes are Amberwood, Leather, Vanila, Amber and Lorenox.',
        3.77,
        13,
        NULL
      ),
(
        'Scalo-Porto-Cervo-Woman-Eau-de-Parfum-41829',
        'Scalo Porto Cervo Woman Eau de Parfum Acqua di Sardegna',
        'Scalo',
        'for women',
        NULL,
        NULL,
        'Red Fruits, Peach and Bergamot',
        'Rose, Jasmine, Pink Pepper and Violet',
        'Vetiver, Patchouli, Powdery Notes and Leather',
        'fruity,rose,citrus,powdery,woody',
        'Scalo Porto Cervo Woman Eau de ParfumbyAcqua di Sardegnais a Chypre Floral fragrance for women.Scalo Porto Cervo Woman Eau de Parfumwas launched in 2014. Top notes are Red Fruits, Peach and Bergamot; middle notes are Rose, Jasmine, Pink Pepper and Violet; base notes are Vetiver, Patchouli, Powdery Notes and Leather.',
        3.38,
        21,
        NULL
      ),
(
        'Smeralda-Woman-Eau-de-Parfum-41831',
        'Smeralda Woman Eau de Parfum Acqua di Sardegna',
        'Smeralda',
        'for women',
        NULL,
        NULL,
        'Bergamot, Tangerine and Lemon',
        'Almond Blossom, Mimosa, Violet and Jasmine',
        'Tonka Bean, Vanilla, Musk and Sandalwood',
        'citrus,powdery,vanilla,floral,sweet',
        'Smeralda Woman Eau de ParfumbyAcqua di Sardegnais a Citrus Gourmand fragrance for women.Smeralda Woman Eau de Parfumwas launched in 2016. Top notes are Bergamot, Tangerine and Lemon; middle notes are Almond Blossom, Mimosa, Violet and Jasmine; base notes are Tonka Bean, Vanilla, Musk and Sandalwood.',
        4.07,
        27,
        NULL
      ),
(
        'Acqua-di-Stresa-6556',
        'Acqua di Stresa Acqua di Stresa',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Osmanthus, Pomegranate and Hyacinth',
        'Rose, Camelia and Jasmine',
        'Musk, Virginia Cedar and Amber',
        'floral,fruity,woody,rose,fresh spicy',
        'Acqua di StresabyAcqua di Stresais a Floral Fruity fragrance for women and men.Acqua di Stresawas launched in 2002. Top notes are Osmanthus, Pomegranate and Hyacinth; middle notes are Rose, Camelia and Jasmine; base notes are Musk, Virginia Cedar and Amber.',
        4.14,
        14,
        NULL
      ),
(
        'Acqua-di-Stresa-fresh-touch-6557',
        'Acqua di Stresa fresh touch Acqua di Stresa',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Osmanthus, Amalfi Lemon, Orange, Bergamot and Bitter Orange',
        'Camelia, Jasmine and African Orange Flower',
        'Amber, Virginia Cedar and Vetiver',
        'citrus,floral,white floral,woody,amber',
        'Acqua di Stresa fresh touchbyAcqua di Stresais a Citrus Aromatic fragrance for women and men.Acqua di Stresa fresh touchwas launched in 2005. Top notes are Osmanthus, Amalfi Lemon, Orange, Bergamot and Bitter Orange; middle notes are Camelia, Jasmine and African Orange Flower; base notes are Amber, Virginia Cedar and Vetiver.',
        4.2,
        5,
        NULL
      ),
(
        'Aroma-Reale-76865',
        'Aroma Reale Acqua di Stresa',
        'Aroma',
        'for women',
        NULL,
        NULL,
        'Peach and Lemon',
        'Rose, Magnolia and Jasmine',
        'Vanilla and Cedar',
        'floral,citrus,woody,white floral,vanilla',
        'Aroma RealebyAcqua di Stresais a fragrance for women. Top notes are Peach and Lemon; middle notes are Rose, Magnolia and Jasmine; base notes are Vanilla and Cedar.',
        NULL,
        NULL,
        NULL
      ),
(
        'Calycanthus-Brumae-28903',
        'Calycanthus Brumae Acqua di Stresa',
        'Calycanthus',
        'for women and men',
        NULL,
        NULL,
        'Honeysuckle',
        'Ginger and Pepper',
        'Incense and Nutmeg',
        'warm spicy,fresh spicy,white floral,amber,smoky',
        'Calycanthus BrumaebyAcqua di Stresais a Aromatic Spicy fragrance for women and men. Top note is Honeysuckle; middle notes are Ginger and Pepper; base notes are Incense and Nutmeg.',
        3.43,
        23,
        NULL
      ),
(
        'Camellia-Soliflor-28902',
        'Camellia Soliflor Acqua di Stresa',
        'Camellia',
        'for women',
        NULL,
        NULL,
        'Grass and Citruses',
        'Floral Notes and Camellia',
        'Spicy Notes and Woody Notes',
        'floral,warm spicy,fresh,woody,green',
        'Camellia SoliflorbyAcqua di Stresais a Floral fragrance for women. Top notes are Grass and Citruses; middle notes are Floral Notes and Camellia; base notes are Spicy Notes and Woody Notes.',
        3.77,
        22,
        NULL
      ),
(
        'Dianthus-40323',
        'Dianthus Acqua di Stresa',
        'Dianthus',
        'for women and men',
        NULL,
        NULL,
        'Citron, Lavender and Galbanum',
        'Sea Notes, Carnation and Rose de Mai',
        'Styrax, Benzoin, Cashmere Wood and Musk',
        'aromatic,amber,citrus,marine,floral',
        'DianthusbyAcqua di Stresais a Citrus Aromatic fragrance for women and men.Dianthuswas launched in 2016. Top notes are Citron, Lavender and Galbanum; middle notes are Sea Notes, Carnation and Rose de Mai; base notes are Styrax, Benzoin, Cashmere Wood and Musk.',
        4,
        7,
        NULL
      ),
(
        'Fiori-di-Stresa-6558',
        'Fiori di Stresa Acqua di Stresa',
        'Fiori',
        'for women',
        NULL,
        NULL,
        'African Orange Flower and Camelia',
        'Geranium, Heliotrope and Violet',
        'Pepper, Woodsy Notes and Musk',
        'fresh spicy,powdery,floral,aromatic,white floral',
        'Fiori di StresabyAcqua di Stresais a Floral Fruity fragrance for women.Fiori di Stresawas launched in 2009. Top notes are African Orange Flower and Camelia; middle notes are Geranium, Heliotrope and Violet; base notes are Pepper, Woodsy Notes and Musk.',
        3,
        2,
        NULL
      ),
(
        'Lotus-40325',
        'Lotus Acqua di Stresa',
        'Lotus',
        'for women',
        NULL,
        NULL,
        'Tea, Lemon and Cardamom',
        'Bamboo, Water Lily and Jasmine',
        'Sandalwood and Musk',
        'woody,warm spicy,fresh,citrus,floral',
        'LotusbyAcqua di Stresais a fragrance for women.Lotuswas launched in 2016. Top notes are Tea, Lemon and Cardamom; middle notes are Bamboo, Water Lily and Jasmine; base notes are Sandalwood and Musk.',
        3.4,
        5,
        NULL
      ),
(
        'Mentha-Citrata-28901',
        'Mentha Citrata Acqua di Stresa',
        'Mentha',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,green,citrus',
        'Mentha CitratabyAcqua di Stresais a Citrus Aromatic fragrance for women and men.Mentha Citratawas launched in 2012.',
        4.1,
        20,
        NULL
      ),
(
        'Osmanthus-40326',
        'Osmanthus Acqua di Stresa',
        'Osmanthus',
        'for women',
        NULL,
        NULL,
        'Peach Blossom, Ylang-Ylang and Bergamot',
        'Osmanthus and Jasmine',
        'Vanilla, Sandalwood and White Musk',
        'floral,fruity,woody,yellow floral,powdery',
        'OsmanthusbyAcqua di Stresais a fragrance for women.Osmanthuswas launched in 2016. Top notes are Peach Blossom, Ylang-Ylang and Bergamot; middle notes are Osmanthus and Jasmine; base notes are Vanilla, Sandalwood and White Musk.',
        3.82,
        11,
        NULL
      ),
(
        'Osmanthus-Fragrans-28900',
        'Osmanthus Fragrans Acqua di Stresa',
        'Osmanthus',
        'for women',
        NULL,
        NULL,
        'Osmanthus and Pomegranate',
        'Rose, Camellia, Jasmine and Hyacinth',
        'Musk and Amber',
        'floral,fruity,rose,powdery,lactonic',
        'Osmanthus FragransbyAcqua di Stresais a Floral Fruity fragrance for women. Top notes are Osmanthus and Pomegranate; middle notes are Rose, Camellia, Jasmine and Hyacinth; base notes are Musk and Amber.',
        3.18,
        33,
        NULL
      ),
(
        'Profumo-di-Stresa-10688',
        'Profumo di Stresa Acqua di Stresa',
        'Profumo',
        'for women',
        NULL,
        NULL,
        'Tangerine and Magnolia',
        'Osmanthus, Jasmine, African Orange Flower and Peach',
        'Woodsy Notes and Green Notes',
        'floral,white floral,citrus,fruity,sweet',
        'Profumo di StresabyAcqua di Stresais a Floral Fruity fragrance for women.Profumo di Stresawas launched in 2010. Top notes are Tangerine and Magnolia; middle notes are Osmanthus, Jasmine, African Orange Flower and Peach; base notes are Woodsy Notes and Green Notes.',
        4.25,
        4,
        NULL
      ),
(
        'Roburis-40327',
        'Roburis Acqua di Stresa',
        'Roburis',
        'for women and men',
        NULL,
        NULL,
        'Juniper, elemi, Cinnamon and Black Currant',
        'Cloves, Myrrh, Violet and Cedar',
        'Incense, Leather, Ambrette (Musk Mallow) and Tonka Bean',
        'warm spicy,aromatic,amber,woody,balsamic',
        'RoburisbyAcqua di Stresais a fragrance for women and men.Roburiswas launched in 2016. Top notes are Juniper, elemi, Cinnamon and Black Currant; middle notes are Cloves, Myrrh, Violet and Cedar; base notes are Incense, Leather, Ambrette (Musk Mallow) and Tonka Bean.',
        3.9,
        10,
        NULL
      ),
(
        'Verbena-Absoluta-18088',
        'Verbena Absoluta Acqua di Stresa',
        'Verbena',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Verbena',
        'Woody Notes and Musk',
        'citrus,fresh,woody',
        'Verbena AbsolutabyAcqua di Stresais a Citrus Aromatic fragrance for women and men.Verbena Absolutawas launched in 2013. Top note is Citruses; middle note is Verbena; base notes are Woody Notes and Musk.',
        4.06,
        16,
        NULL
      ),
(
        'Verbenis-40328',
        'Verbenis Acqua di Stresa',
        'Verbenis',
        'for women and men',
        NULL,
        NULL,
        'Lemon Verbena, Orange and Citron',
        'Freesia, Geranium and Neroli',
        'Sandalwood and Musk',
        'citrus,fresh spicy,aromatic,floral,woody',
        'VerbenisbyAcqua di Stresais a fragrance for women and men.Verbeniswas launched in 2016. Top notes are Lemon Verbena, Orange and Citron; middle notes are Freesia, Geranium and Neroli; base notes are Sandalwood and Musk.',
        3.4,
        5,
        NULL
      ),
(
        'Virens-40324',
        'Virens Acqua di Stresa',
        'Virens',
        'for men',
        NULL,
        NULL,
        'Artemisia, Cinnamon and Saffron',
        'Floral Notes, Patchouli and Ambergris',
        'Agarwood (Oud), Vanilla and Benzoin',
        'warm spicy,amber,floral,vanilla,patchouli',
        'VirensbyAcqua di Stresais a fragrance for men.Virenswas launched in 2016. Top notes are Artemisia, Cinnamon and Saffron; middle notes are Floral Notes, Patchouli and Ambergris; base notes are Agarwood (Oud), Vanilla and Benzoin.',
        3.57,
        7,
        NULL
      ),
(
        'Darkest-Hour-57418',
        'Darkest Hour Acqua di Stresa',
        'Darkest',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Darkest HourbyAcqua di Stresais a fragrance for women and men.Darkest Hourwas launched in 2019.',
        4,
        1,
        NULL
      ),
(
        'Diamonds-Rain-57415',
        'Diamonds Rain Acqua di Stresa',
        'Diamonds',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,rose,fruity,woody,fresh spicy',
        'Diamonds RainbyAcqua di Stresais a Floral Woody Musk fragrance for women and men.Diamonds Rainwas launched in 2019.',
        5,
        1,
        NULL
      ),
(
        'Macomber-57417',
        'Macomber Acqua di Stresa',
        'Macomber',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'MacomberbyAcqua di Stresais a fragrance for women and men.Macomberwas launched in 2019.',
        5,
        3,
        NULL
      ),
(
        'The-Queen-57416',
        'The Queen Acqua di Stresa',
        'The',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'The QueenbyAcqua di Stresais a fragrance for women and men.The Queenwas launched in 2019.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ambra-di-Venezia-27001',
        'Ambra di Venezia Acque di Italia',
        'Ambra',
        'for women and men',
        NULL,
        NULL,
        'Sweet Orange, Coriander and Bergamot',
        'Labdanum, Jasmine and Olibanum',
        'Ambergris, Benzoin, Vanilla and Styrax',
        'amber,citrus,vanilla,balsamic,animalic',
        'Ambra di VeneziabyAcque di Italiais a Amber fragrance for women and men. Top notes are Sweet Orange, Coriander and Bergamot; middle notes are Labdanum, Jasmine and Olibanum; base notes are Ambergris, Benzoin, Vanilla and Styrax.',
        3.95,
        20,
        NULL
      ),
(
        'Cedro-di-Pantelleria-27000',
        'Cedro di Pantelleria Acque di Italia',
        'Cedro',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Ginger, Water Notes, Bergamot, Italian Lemon and Orange',
        'Cedar, Cashmere Wood, Cinnamon and Violet',
        'Haitian Vetiver, Indonesian Patchouli Leaf, Sandalwood, Ambergris and White Musk',
        'woody,citrus,warm spicy,powdery,musky',
        'Cedro di PantelleriabyAcque di Italiais a Citrus Aromatic fragrance for women and men. Top notes are Pink Pepper, Ginger, Water Notes, Bergamot, Italian Lemon and Orange; middle notes are Cedar, Cashmere Wood, Cinnamon and Violet; base notes are Haitian Vetiver, Indonesian Patchouli Leaf, Sandalwood, Ambergris and White Musk.',
        3.75,
        8,
        NULL
      ),
(
        'Giglio-di-Sardegna-27002',
        'Giglio di Sardegna Acque di Italia',
        'Giglio',
        'for women',
        NULL,
        NULL,
        'Sweet Orange, Cedar, Tangerine and Bitter Orange',
        'Orange Blossom, Jasmine and Water Lily',
        'Amber, Cedar, Honey, Vanilla and Vetiver',
        'citrus,white floral,sweet,amber,floral',
        'Giglio di SardegnabyAcque di Italiais a Floral fragrance for women. Top notes are Sweet Orange, Cedar, Tangerine and Bitter Orange; middle notes are Orange Blossom, Jasmine and Water Lily; base notes are Amber, Cedar, Honey, Vanilla and Vetiver.',
        4.15,
        20,
        NULL
      ),
(
        'Gran-Bouquet-Italiano-27003',
        'Gran Bouquet Italiano Acque di Italia',
        'Gran',
        'for women and men',
        NULL,
        NULL,
        'Olive Blossom, Mint, Lemon and Rosemary',
        'Gardenia, Lavender, Coriander and White Pepper',
        'Amber, Olive Tree and Cedar',
        'aromatic,fresh spicy,woody,green,amber',
        'Gran Bouquet ItalianobyAcque di Italiais a Aromatic Green fragrance for women and men. Top notes are Olive Blossom, Mint, Lemon and Rosemary; middle notes are Gardenia, Lavender, Coriander and White Pepper; base notes are Amber, Olive Tree and Cedar.',
        4,
        1,
        NULL
      ),
(
        'Iris-di-Toscana-27004',
        'Iris di Toscana Acque di Italia',
        'Iris',
        'for women',
        NULL,
        NULL,
        'Aldehydes, Chamomile, Green Notes and Violet Leaf',
        'Iris, Mimosa and Ylang-Ylang',
        'Vetiver, Musk, Guaiac Wood and Cedar',
        'woody,aldehydic,powdery,iris,green',
        'Iris di ToscanabyAcque di Italiais a Floral fragrance for women. Top notes are Aldehydes, Chamomile, Green Notes and Violet Leaf; middle notes are Iris, Mimosa and Ylang-Ylang; base notes are Vetiver, Musk, Guaiac Wood and Cedar.',
        4.14,
        21,
        NULL
      ),
(
        'Muschio-del-Trentino-26999',
        'Muschio del Trentino Acque di Italia',
        'Muschio',
        'for women and men',
        NULL,
        NULL,
        'Carrot Seeds, Cypress and Moss',
        'Hyacinth, Rhododendron and Cyclamen',
        'White Musk, Vetiver and Sandalwood',
        'woody,powdery,aromatic,musky,earthy',
        'Muschio del TrentinobyAcque di Italiais a Aromatic Green fragrance for women and men. Top notes are Carrot Seeds, Cypress and Moss; middle notes are Hyacinth, Rhododendron and Cyclamen; base notes are White Musk, Vetiver and Sandalwood.',
        4.67,
        3,
        NULL
      ),
(
        'Oleandro-di-Panarea-26998',
        'Oleandro di Panarea Acque di Italia',
        'Oleandro',
        'for women',
        NULL,
        NULL,
        'Gardenia, Water Lily and Water Notes',
        'Nerium Oleander, Rose, Orchid, Magnolia and Champaca',
        'Amber, Vetiver and Cedar',
        'floral,aquatic,white floral,sweet,fresh',
        'Oleandro di PanareabyAcque di Italiais a Floral Aquatic fragrance for women. Top notes are Gardenia, Water Lily and Water Notes; middle notes are Nerium Oleander, Rose, Orchid, Magnolia and Champaca; base notes are Amber, Vetiver and Cedar.',
        2.5,
        2,
        NULL
      ),
(
        'Peonia-di-Amalfi-27005',
        'Peonia di Amalfi Acque di Italia',
        'Peonia',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley and Green Notes',
        'Peony, Lily, Jasmine and Orchid',
        'White Musk',
        'white floral,fresh,floral,green,musky',
        'Peonia di AmalfibyAcque di Italiais a Floral Green fragrance for women. Top notes are Lily-of-the-Valley and Green Notes; middle notes are Peony, Lily, Jasmine and Orchid; base note is White Musk.',
        4.5,
        8,
        NULL
      ),
(
        'Rosa-di-Portofino-27007',
        'Rosa di Portofino Acque di Italia',
        'Rosa',
        'for women',
        NULL,
        NULL,
        'Rose, Mandarin Orange and Water Notes',
        'White Rose, Lily, Orange Blossom and Carnation',
        'White Musk, Amber and Exotic Woods',
        'white floral,rose,citrus,floral,musky',
        'Rosa di PortofinobyAcque di Italiais a Floral Aquatic fragrance for women. Top notes are Rose, Mandarin Orange and Water Notes; middle notes are White Rose, Lily, Orange Blossom and Carnation; base notes are White Musk, Amber and Exotic Woods.',
        3.86,
        7,
        NULL
      ),
(
        'Zagara-di-Sicilia-27006',
        'Zagara di Sicilia Acque di Italia',
        'Zagara',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Tangerine, Citruses and Bergamot',
        'Orange Blossom, Rosemary, Lavender and Clary Sage',
        'Cedar, Vetiver, Musk, Sandalwood and Patchouli',
        'citrus,aromatic,woody,white floral,fresh spicy',
        'Zagara di SiciliabyAcque di Italiais a Citrus Aromatic fragrance for women and men. Top notes are Orange Blossom, Tangerine, Citruses and Bergamot; middle notes are Orange Blossom, Rosemary, Lavender and Clary Sage; base notes are Cedar, Vetiver, Musk, Sandalwood and Patchouli.',
        4.6,
        5,
        NULL
      ),
(
        'Mioritic-Green-Edition-Extrait-de-Folklore-83953',
        'Mioritic Green Edition - Extrait de Folklore Adi Ale Van',
        'Mioritic',
        'for women and men',
        NULL,
        NULL,
        'Basil, elemi and Pink Pepper',
        'Fig, Grapefruit and Incense',
        'White Musk, Patchouli and Dry Wood',
        'aromatic,fresh spicy,woody,musky,balsamic',
        'Mioritic Green Edition - Extrait de FolklorebyAdi Ale Vanis a Woody Aromatic fragrance for women and men. Top notes are Basil, elemi and Pink Pepper; middle notes are Fig, Grapefruit and Incense; base notes are White Musk, Patchouli and Dry Wood.',
        3.4,
        5,
        NULL
      ),
(
        'U-M-B-R-E-70787',
        '.U.M.B.R.E. Adi Ale Van',
        '.U.M.B.R.E.',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Animal notes and Davana',
        'Coffee, Benzoin and Cypriol Oil or Nagarmotha',
        'Myrrh and Tobacco',
        'amber,warm spicy,coffee,tobacco,balsamic',
        '.U.M.B.R.E.byAdi Ale Vanis a fragrance for women and men..U.M.B.R.E.was launched in 2021. The nose behind this fragrance is Jimmy Bodin. Top notes are Animal notes and Davana; middle notes are Coffee, Benzoin and Cypriol Oil or Nagarmotha; base notes are Myrrh and Tobacco.',
        4.13,
        79,
        NULL
      ),
(
        'Dark-Weed-Extrait-Rudimentar-73798',
        'Dark Weed - Extrait Rudimentar Adi Ale Van',
        'Dark',
        'for women and men',
        NULL,
        'Flavius Calaj',
        'Black Currant, Metallic notes, Rose and Bergamot',
        'cannabis, Rhubarb and Rose',
        'Tobacco, Fir, Incense, Civet and Patchouli',
        'aromatic,fruity,green,cannabis,woody',
        'Dark Weed - Extrait RudimentarbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Dark Weed - Extrait Rudimentarwas launched in 2022. The nose behind this fragrance is Flavius Calaj. Top notes are Black Currant, Metallic notes, Rose and Bergamot; middle notes are cannabis, Rhubarb and Rose; base notes are Tobacco, Fir, Incense, Civet and Patchouli.',
        3.73,
        41,
        NULL
      ),
(
        'Decembrie-89-Freedom-elixir-88793',
        'Decembrie 89 - Freedom elixir Adi Ale Van',
        'Decembrie',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Apple, Orange and Lemon',
        'Vanilla Bean and Hazelnut',
        'Madagascar Vanilla, Vanilla Absolute and Rum',
        'vanilla,nutty,woody,citrus,sweet',
        'Decembrie 89 - Freedom elixirbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Decembrie 89 - Freedom elixirwas launched in 2023. The nose behind this fragrance is Jimmy Bodin. Top notes are Apple, Orange and Lemon; middle notes are Vanilla Bean and Hazelnut; base notes are Madagascar Vanilla, Vanilla Absolute and Rum.',
        4.43,
        44,
        NULL
      ),
(
        'Diamonitirion-elixir-atonit-90283',
        'Diamonitirion - elixir atonit Adi Ale Van',
        'Diamonitirion',
        'for women and men',
        NULL,
        'Giovanni Festa',
        'Pink Pepper, Lime and Cardamom',
        'Candle Wax, Old Books, Opoponax, Olibanum and Myrrh',
        'Resin, Amber and Musk',
        'amber,balsamic,sweet',
        'Diamonitirion - elixir atonitbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Diamonitirion - elixir atonitwas launched in 2024. The nose behind this fragrance is Giovanni Festa. Top notes are Pink Pepper, Lime and Cardamom; middle notes are Candle Wax, Old Books, Opoponax, Olibanum and Myrrh; base notes are Resin, Amber and Musk.',
        4.8,
        15,
        NULL
      ),
(
        'Dilema-68886',
        'Dilema Adi Ale Van',
        'Dilema',
        'for women and men',
        NULL,
        'Anne-Sophie Behaghel',
        'Saffron and Bergamot',
        'Myrrh and Licorice',
        'Leather, Papyrus, Woody Notes and Patchouli',
        'woody,leather,warm spicy,amber,patchouli',
        'DilemabyAdi Ale Vanis a Woody fragrance for women and men.Dilemawas launched in 2021. Dilema was created by Anne-Sophie Behaghel and Camille Chemardin. Top notes are Saffron and Bergamot; middle notes are Myrrh and Licorice; base notes are Leather, Papyrus, Woody Notes and Patchouli.',
        4.04,
        51,
        NULL
      ),
(
        'Gethsemane-Elixir-of-Faith-79956',
        'Gethsemane - Elixir of Faith Adi Ale Van',
        'Gethsemane',
        'for women and men',
        NULL,
        'David-Lev Jipa-Slivinschi',
        'Olive Tree, Cloves, Bay Leaf and Basil',
        'Metallic notes, Nard Himalayan (Jatamansi), Olibanum, Elemi resin, Ambrette (Musk Mallow), Pine Tree, Gurjan balsam, Cedar and Cypress',
        'Castoreum, Salt, Leather, Agarwood (Oud), Cypriol Oil or Nagarmotha and Vetiver',
        'leather,smoky,metallic,salty,animalic',
        'Gethsemane - Elixir of FaithbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Gethsemane - Elixir of Faithwas launched in 2023. The nose behind this fragrance is David-Lev Jipa-Slivinschi. Top notes are Olive Tree, Cloves, Bay Leaf and Basil; middle notes are Metallic notes, Nard Himalayan (Jatamansi), Olibanum, Elemi resin, Ambrette (Musk Mallow), Pine Tree, Gurjan balsam, Cedar and Cypress; base notes are Castoreum, Salt, Leather, Agarwood (Oud), Cypriol Oil or Nagarmotha and Vetiver.',
        4.12,
        17,
        NULL
      ),
(
        'Glie-Elixir-Rural-92121',
        'Glie - Elixir Rural Adi Ale Van',
        'Glie',
        'for women and men',
        NULL,
        'Giovanni Festa',
        'Earthy Notes, Sage, Bitter Orange and Lavender',
        'Angelica, Grass, Green Notes, Galbanum, Thyme and Orris',
        'Amber and Musk',
        'green,aromatic,musky,amber,powdery',
        'Glie - Elixir RuralbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Glie - Elixir Ruralwas launched in 2024. The nose behind this fragrance is Giovanni Festa. Top notes are Earthy Notes, Sage, Bitter Orange and Lavender; middle notes are Angelica, Grass, Green Notes, Galbanum, Thyme and Orris; base notes are Amber and Musk.',
        3.86,
        7,
        NULL
      ),
(
        'Grapa-r-fume-1-84790',
        'Grapa r fume 1 Adi Ale Van',
        'Grapa',
        'for women and men',
        NULL,
        'David-Lev Jipa-Slivinschi',
        'Bread, Mushroom, Narcissus and Gardenia',
        'Earthy Notes, Dried Fallen Leaves, Rose and Fruity Notes',
        'Wood barrel, Fir Resin, Vetiver and Leather',
        'earthy,savory,mossy',
        'Grapa r fume 1byAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Grapa r fume 1was launched in 2023. The nose behind this fragrance is David-Lev Jipa-Slivinschi. Top notes are Bread, Mushroom, Narcissus and Gardenia; middle notes are Earthy Notes, Dried Fallen Leaves, Rose and Fruity Notes; base notes are Wood barrel, Fir Resin, Vetiver and Leather.',
        3.67,
        12,
        NULL
      ),
(
        'Grapa-r-fume-2-84791',
        'Grapa r fume 2 Adi Ale Van',
        'Grapa',
        'for women and men',
        NULL,
        'David-Lev Jipa-Slivinschi',
        'Grass, Mountain Air, Wild Berries, Green Apple and Mango',
        'Bourgeonal, Chamomile, Tuberose and Jasmine',
        'Metallic notes, Leather, Hay and Sugar Cane',
        'green,metallic,fresh,leather,mineral',
        'Grapa r fume 2byAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Grapa r fume 2was launched in 2023. The nose behind this fragrance is David-Lev Jipa-Slivinschi. Top notes are Grass, Mountain Air, Wild Berries, Green Apple and Mango; middle notes are Bourgeonal, Chamomile, Tuberose and Jasmine; base notes are Metallic notes, Leather, Hay and Sugar Cane.',
        3.55,
        11,
        NULL
      ),
(
        'Gruia-Childhood-Elixir-79476',
        'Gruia - Childhood Elixir Adi Ale Van',
        'Gruia',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Lavender, Nutmeg and Clove Leaf',
        'Tobacco, Violet Leaf, Copaiba balm and Incense',
        'Soil Tincture, Cypriol Oil or Nagarmotha, Musk, Opoponax and Woody Notes',
        'earthy,woody,lavender,fresh spicy,tobacco',
        'Gruia - Childhood ElixirbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Gruia - Childhood Elixirwas launched in 2023. The nose behind this fragrance is Jimmy Bodin. Top notes are Lavender, Nutmeg and Clove Leaf; middle notes are Tobacco, Violet Leaf, Copaiba balm and Incense; base notes are Soil Tincture, Cypriol Oil or Nagarmotha, Musk, Opoponax and Woody Notes.',
        3.14,
        14,
        NULL
      ),
(
        'Hai-Hui-Flower-Power-Extrait-73364',
        'Hai Hui Flower Power Extrait Adi Ale Van',
        'Hai',
        'for women and men',
        NULL,
        'Anne-Sophie Behaghel',
        'Mint, Cardamom, Black Pepper and Pineapple',
        'elemi, Fig and Almond',
        'Vetiver, Papyrus and Woody Notes',
        'woody,aromatic,green,fresh spicy,warm spicy',
        'Hai Hui Flower Power ExtraitbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Hai Hui Flower Power Extraitwas launched in 2022. The nose behind this fragrance is Anne-Sophie Behaghel. Top notes are Mint, Cardamom, Black Pepper and Pineapple; middle notes are elemi, Fig and Almond; base notes are Vetiver, Papyrus and Woody Notes.',
        3.79,
        43,
        NULL
      ),
(
        'Journey-of-Life-Extrait-of-Dreams-76591',
        'Journey of Life - Extrait of Dreams Adi Ale Van',
        'Journey',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Grapes and Clary Sage',
        'Plum and Cypriol Oil or Nagarmotha',
        'Castoreum, Cacao and Vetiver',
        'woody,leather,fruity,cacao,smoky',
        'Journey of Life - Extrait of DreamsbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Journey of Life - Extrait of Dreamswas launched in 2022. The nose behind this fragrance is Jimmy Bodin. Top notes are Grapes and Clary Sage; middle notes are Plum and Cypriol Oil or Nagarmotha; base notes are Castoreum, Cacao and Vetiver.',
        3.5,
        42,
        NULL
      ),
(
        'Mioritic-Extrait-de-Folklore-72275',
        'Mioritic - Extrait de Folklore Adi Ale Van',
        'Mioritic',
        'for women and men',
        NULL,
        'Anne-Sophie Behaghel',
        'elemi, Pink Pepper and Basil',
        'Fig, Incense and Grapefruit',
        'Patchouli, Woody Notes and White Musk',
        'woody,aromatic,balsamic,fresh spicy,fruity',
        'Mioritic - Extrait de FolklorebyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Mioritic - Extrait de Folklorewas launched in 2022. The nose behind this fragrance is Anne-Sophie Behaghel. Top notes are elemi, Pink Pepper and Basil; middle notes are Fig, Incense and Grapefruit; base notes are Patchouli, Woody Notes and White Musk.',
        4.23,
        35,
        NULL
      ),
(
        'My-Judgement-Day-Elixirul-Vecerniei-82357',
        'My Judgement Day - Elixirul Vecerniei Adi Ale Van',
        'My',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Benzoin, Frankincense and Lavender',
        'Benzoin, Cistus Incanus and Frankincense',
        'Labdanum, Oakmoss, Vetiver, Myrrh and Cypriol Oil or Nagarmotha',
        'amber,woody,earthy,mossy,warm spicy',
        'My Judgement Day - Elixirul VecernieibyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.My Judgement Day - Elixirul Vecernieiwas launched in 2023. The nose behind this fragrance is Jimmy Bodin. Top notes are Benzoin, Frankincense and Lavender; middle notes are Benzoin, Cistus Incanus and Frankincense; base notes are Labdanum, Oakmoss, Vetiver, Myrrh and Cypriol Oil or Nagarmotha.',
        3.86,
        21,
        NULL
      ),
(
        'Odaie-Vintage-Potion-92122',
        'Odaie - Vintage Potion Adi Ale Van',
        'Odaie',
        'for women and men',
        NULL,
        'Giovanni Festa',
        'Old House, Turkish Rose and Black Cherry',
        'Black Currant and Madagascar Vanilla',
        'Oud and Woody Notes',
        'cherry,rose,fruity,woody,oud',
        'Odaie - Vintage PotionbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Odaie - Vintage Potionwas launched in 2024. The nose behind this fragrance is Giovanni Festa. Top notes are Old House, Turkish Rose and Black Cherry; middle notes are Black Currant and Madagascar Vanilla; base notes are Oud and Woody Notes.',
        4.29,
        7,
        NULL
      ),
(
        'Origini-Extrait-de-Hotaru-75134',
        'Origini - Extrait de Hotaru Adi Ale Van',
        'Origini',
        'for women and men',
        NULL,
        'Anne-Sophie Behaghel',
        'Coconut, Sage and Black Pepper',
        'cannabis, Orange Blossom and Myrrh',
        'Patchouli, Cashmere Wood and Woody Notes',
        'aromatic,woody,herbal,cannabis,coconut',
        'Origini - Extrait de HotarubyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Origini - Extrait de Hotaruwas launched in 2022. The nose behind this fragrance is Anne-Sophie Behaghel. Top notes are Coconut, Sage and Black Pepper; middle notes are cannabis, Orange Blossom and Myrrh; base notes are Patchouli, Cashmere Wood and Woody Notes.',
        3.61,
        23,
        NULL
      ),
(
        'Perseide-Elixir-of-Stars-Dust-77819',
        'Perseide - Elixir of Stars Dust Adi Ale Van',
        'Perseide',
        'for women and men',
        NULL,
        'Giovanni Festa',
        'Indian Tuberose, Orange Blossom and Bulgarian Rose',
        'Egyptian Jasmine, Geranium and Leather',
        'Musk, Sandalwood and Agarwood (Oud)',
        'white floral,tuberose,animalic,rose,fresh spicy',
        'Perseide - Elixir of Stars DustbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Perseide - Elixir of Stars Dustwas launched in 2022. The nose behind this fragrance is Giovanni Festa. Top notes are Indian Tuberose, Orange Blossom and Bulgarian Rose; middle notes are Egyptian Jasmine, Geranium and Leather; base notes are Musk, Sandalwood and Agarwood (Oud).',
        3.58,
        19,
        NULL
      ),
(
        'Saints-Tears-Extrait-of-Forgiveness-71497',
        'Saints Tears - Extrait of Forgiveness Adi Ale Van',
        'Saints',
        'for women and men',
        NULL,
        'Camille Chemardin',
        'elemi and Incense',
        'Myrrh and Labdanum',
        'Oakmoss, Atlas Cedar, Virginian Cedar and Woody Notes',
        'amber,woody,balsamic,aromatic,mossy',
        'Saints Tears - Extrait of ForgivenessbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Saints Tears - Extrait of Forgivenesswas launched in 2022. Saints Tears - Extrait of Forgiveness was created by Camille Chemardin and Elia Chiche. Top notes are elemi and Incense; middle notes are Myrrh and Labdanum; base notes are Oakmoss, Atlas Cedar, Virginian Cedar and Woody Notes.',
        3.76,
        45,
        NULL
      ),
(
        'Searching-for-faith-rare-elixir-84789',
        'Searching for faith - rare elixir Adi Ale Van',
        'Searching',
        'for women and men',
        NULL,
        'Adi ale Van',
        NULL,
        NULL,
        NULL,
        'amber,fruity,woody,sweet,balsamic',
        'Searching for faith - rare elixirbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Searching for faith - rare elixirwas launched in 2023. The nose behind this fragrance is Adi ale Van.',
        4.5,
        10,
        NULL
      ),
(
        'Serafimi-elixir-of-faith-79957',
        'Serafimi - elixir of faith Adi Ale Van',
        'Serafimi',
        'for women and men',
        NULL,
        'David-Lev Jipa-Slivinschi',
        'Earthy Notes, Nard Himalayan (Jatamansi), Stone, Gurjan balsam, Coal Tar, Patchouli, Civet, Woody Notes, Amber, Green Leaves and Ambergris',
        NULL,
        NULL,
        'earthy,woody,herbal,fresh spicy,mineral',
        'Serafimi - elixir of faithbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Serafimi - elixir of faithwas launched in 2023. The nose behind this fragrance is David-Lev Jipa-Slivinschi. Top notes are Earthy Notes, Nard Himalayan (Jatamansi), Stone, Gurjan balsam, Coal Tar, Patchouli, Civet, Woody Notes, Amber, Green Leaves and Ambergris;',
        3.08,
        24,
        NULL
      ),
(
        'Soul-Tattoo-outlaw-s-elixir-78340',
        'Soul Tattoo - outlaw''s elixir Adi Ale Van',
        'Soul',
        'for women and men',
        NULL,
        'David-Lev Jipa-Slivinschi',
        'Cardamom, Camphor, Nutmeg and Maple',
        'Pine, Lavender, Tobacco, Heliotrope, Sandalwood and Tolu Balsam',
        'Milk, Ebony Wood, Cacao, Tonka Bean, Benzoin, Musk and Vanilla',
        'woody,warm spicy,aromatic,camphor,sweet',
        'Soul Tattoo - outlaw''s elixirbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Soul Tattoo - outlaw''s elixirwas launched in 2022. The nose behind this fragrance is David-Lev Jipa-Slivinschi. Top notes are Cardamom, Camphor, Nutmeg and Maple; middle notes are Pine, Lavender, Tobacco, Heliotrope, Sandalwood and Tolu Balsam; base notes are Milk, Ebony Wood, Cacao, Tonka Bean, Benzoin, Musk and Vanilla.',
        3.41,
        27,
        NULL
      ),
(
        'The-book-of-wisdom-Elixir-fatal-88794',
        'The book of wisdom - Elixir fatal Adi Ale Van',
        'The',
        'for women and men',
        NULL,
        'Giovanni Festa',
        'Raspberry, Bulgarian Rose, Turkish Rose, Damask Rose, Olibanum and Tobacco',
        'Oud and Leather',
        'Musk and Oakmoss',
        'oud,musky,fruity,sweet,rose',
        'The book of wisdom - Elixir fatalbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.The book of wisdom - Elixir fatalwas launched in 2023. The nose behind this fragrance is Giovanni Festa. Top notes are Raspberry, Bulgarian Rose, Turkish Rose, Damask Rose, Olibanum and Tobacco; middle notes are Oud and Leather; base notes are Musk and Oakmoss.',
        3.75,
        16,
        NULL
      ),
(
        'The-Summer-of-83-Memories-Potion-83016',
        'The Summer of 83 - Memories Potion Adi Ale Van',
        'The',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Yuzu and Mushroom',
        'Lavender, Woody Notes and Tobacco Leaf',
        'Violet Leaf, Indonesian Patchouli Leaf and Soil Tincture',
        'earthy,woody,ozonic,patchouli,lavender',
        'The Summer of 83 - Memories PotionbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.The Summer of 83 - Memories Potionwas launched in 2023. The nose behind this fragrance is Jimmy Bodin. Top notes are Yuzu and Mushroom; middle notes are Lavender, Woody Notes and Tobacco Leaf; base notes are Violet Leaf, Indonesian Patchouli Leaf and Soil Tincture.',
        3.38,
        16,
        NULL
      ),
(
        'Triodul-Elixirul-Patimilor-82359',
        'Triodul - Elixirul Patimilor Adi Ale Van',
        'Triodul',
        'for women and men',
        NULL,
        'Jimmy Bodin',
        'Incense, Myrrh and Olibanum',
        'Leather, Papyrus, White Woods and Mushroom',
        'Styrax, Opoponax, Benzoin, Sandalwood and Patchouli',
        'amber,woody,balsamic,warm spicy,leather',
        'Triodul - Elixirul PatimilorbyAdi Ale Vanis a fragrance for women and men. This is a new fragrance.Triodul - Elixirul Patimilorwas launched in 2023. The nose behind this fragrance is Jimmy Bodin. Top notes are Incense, Myrrh and Olibanum; middle notes are Leather, Papyrus, White Woods and Mushroom; base notes are Styrax, Opoponax, Benzoin, Sandalwood and Patchouli.',
        4.07,
        15,
        NULL
      );
