
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Memories-31180',
        'Memories Perfume and Skin',
        'Memories',
        'for women',
        NULL,
        NULL,
        'Black Currant and Pear',
        'Iris, Jasmine and Orange Blossom',
        'Praline, Vanilla, Patchouli and Tonka Bean',
        'sweet,vanilla,fruity,white floral,woody',
        'MemoriesbyPerfume and Skinis a Aromatic Spicy fragrance for women.Memorieswas launched in 2015. Top notes are Black Currant and Pear; middle notes are Iris, Jasmine and Orange Blossom; base notes are Praline, Vanilla, Patchouli and Tonka Bean.',
        NULL,
        NULL,
        NULL
      ),
(
        'Moxie-Man-31139',
        'Moxie Man Perfume and Skin',
        'Moxie',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Mint and Blood Mandarin',
        'Cinnamon, Rose and Spicy Notes',
        'Indian Patchouli, Leather, Amber and White Woods',
        'warm spicy,cinnamon,rose,patchouli,woody',
        'Moxie ManbyPerfume and Skinis a Woody Chypre fragrance for men.Moxie Manwas launched in 2013. Top notes are Grapefruit, Mint and Blood Mandarin; middle notes are Cinnamon, Rose and Spicy Notes; base notes are Indian Patchouli, Leather, Amber and White Woods.',
        NULL,
        NULL,
        NULL
      ),
(
        'Moxie-Woman-31140',
        'Moxie Woman Perfume and Skin',
        'Moxie',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Pink Pepper',
        'Lilac, Peach and Geranium',
        'Amber and Patchouli',
        'floral,fresh,fruity,soft spicy,sweet',
        'Moxie WomanbyPerfume and Skinis a Chypre Floral fragrance for women.Moxie Womanwas launched in 2013. Top notes are Mandarin Orange and Pink Pepper; middle notes are Lilac, Peach and Geranium; base notes are Amber and Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Navagio-31179',
        'Navagio Perfume and Skin',
        'Navagio',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Neroli, Grapefruit and Petitgrain',
        'Seaweed, Rosemary and Water Notes',
        'Virginia Cedar and Amber',
        'citrus,aromatic,aquatic,woody,fresh spicy',
        'NavagiobyPerfume and Skinis a Aromatic Aquatic fragrance for men.Navagiowas launched in 2015. Top notes are Mandarin Orange, Neroli, Grapefruit and Petitgrain; middle notes are Seaweed, Rosemary and Water Notes; base notes are Virginia Cedar and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Nude-Lush-31228',
        'Nude Lush Perfume and Skin',
        'Nude',
        'for women',
        NULL,
        NULL,
        'Champagne and Fruity Notes',
        'Peach Blossom',
        'Woody Notes and White Musk',
        'musky,woody,fruity,floral,powdery',
        'Nude LushbyPerfume and Skinis a Floral Woody Musk fragrance for women.Nude Lushwas launched in 2015. Top notes are Champagne and Fruity Notes; middle note is Peach Blossom; base notes are Woody Notes and White Musk.',
        5,
        2,
        NULL
      ),
(
        'Sunset-Passion-31142',
        'Sunset Passion Perfume and Skin',
        'Sunset',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,white floral,sweet,rum,powdery',
        'Sunset PassionbyPerfume and Skinis a Amber Floral fragrance for women.Sunset Passionwas launched in 2014.',
        3,
        2,
        NULL
      ),
(
        'Sweet-Temptation-31143',
        'Sweet Temptation Perfume and Skin',
        'Sweet',
        'for women',
        NULL,
        NULL,
        'Japanese Osmanthus, Apple Leaf and Indian Mandarin',
        'Magnolia, Boronia and Yellow Freesia',
        'Musk and White Iris',
        'floral,fruity,citrus,powdery,iris',
        'Sweet TemptationbyPerfume and Skinis a Aromatic fragrance for women.Sweet Temptationwas launched in 2014. Top notes are Japanese Osmanthus, Apple Leaf and Indian Mandarin; middle notes are Magnolia, Boronia and Yellow Freesia; base notes are Musk and White Iris.',
        3.33,
        3,
        NULL
      ),
(
        'Tough-31144',
        'Tough Perfume and Skin',
        'Tough',
        'for men',
        NULL,
        NULL,
        'Fir, Petitgrain, Cardamom, Orange and Lemon',
        'Rosemary, Jasmine, Rose and Lily-of-the-Valley',
        'Oakmoss, Brazilian Rosewood, Vetiver and Musk',
        'woody,aromatic,fresh spicy,fresh,conifer',
        'ToughbyPerfume and Skinis a Woody Chypre fragrance for men.Toughwas launched in 2014. Top notes are Fir, Petitgrain, Cardamom, Orange and Lemon; middle notes are Rosemary, Jasmine, Rose and Lily-of-the-Valley; base notes are Oakmoss, Brazilian Rosewood, Vetiver and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Trigger-31154',
        'Trigger Perfume and Skin',
        'Trigger',
        'for men',
        NULL,
        NULL,
        'Plum, Bergamot, Lime and Red Apple',
        'Jasmine, Cinnamon, Rose and Cardamom',
        'Vanilla, Amber, Musk, Cedar and Amyris',
        'fruity,citrus,vanilla,sweet,warm spicy',
        'TriggerbyPerfume and Skinis a Amber Fougere fragrance for men.Triggerwas launched in 2012. Top notes are Plum, Bergamot, Lime and Red Apple; middle notes are Jasmine, Cinnamon, Rose and Cardamom; base notes are Vanilla, Amber, Musk, Cedar and Amyris.',
        5,
        1,
        NULL
      ),
(
        'Trigger-31153',
        'Trigger Perfume and Skin',
        'Trigger',
        'for women',
        NULL,
        NULL,
        'Pomegranate, Persimmon and Green Notes',
        'Black Orchid, Champaca and Lotus',
        'Amber, Mahogany, Black Violet and Musk',
        'floral,woody,sweet,powdery,fruity',
        'TriggerbyPerfume and Skinis a Amber Floral fragrance for women.Triggerwas launched in 2012. Top notes are Pomegranate, Persimmon and Green Notes; middle notes are Black Orchid, Champaca and Lotus; base notes are Amber, Mahogany, Black Violet and Musk.',
        4,
        2,
        NULL
      ),
(
        'Unexpected-31155',
        'Unexpected Perfume and Skin',
        'Unexpected',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,citrus,fresh spicy,amber',
        'UnexpectedbyPerfume and Skinis a Amber Fougere fragrance for men.Unexpectedwas launched in 2014.',
        1,
        1,
        NULL
      ),
(
        'Unexpected-Blue-31227',
        'Unexpected Blue Perfume and Skin',
        'Unexpected',
        'for men',
        NULL,
        NULL,
        'Melon, Mandarin Orange and Cucumber',
        'Basil, Sage and Geranium',
        'Musk, Woodsy Notes and Suede',
        'aromatic,fresh spicy,musky,ozonic,herbal',
        'Unexpected BluebyPerfume and Skinis a Aromatic Aquatic fragrance for men.Unexpected Bluewas launched in 2015. Top notes are Melon, Mandarin Orange and Cucumber; middle notes are Basil, Sage and Geranium; base notes are Musk, Woodsy Notes and Suede.',
        NULL,
        NULL,
        NULL
      ),
(
        'Athletic-Planet-Energy-31134',
        'Athletic Planet Energy Perfume and Skin',
        'Athletic',
        'for women',
        NULL,
        NULL,
        'Cedar, Granny Smith apple and Bellflower',
        'White Rose, Bamboo and Jasmine',
        'Cedar, Musk and Amber',
        'woody,floral,rose,musky,powdery',
        'Athletic Planet EnergybyPerfume and Skinis a Floral Fruity fragrance for women.Athletic Planet Energywas launched in 2012. Top notes are Cedar, Granny Smith apple and Bellflower; middle notes are White Rose, Bamboo and Jasmine; base notes are Cedar, Musk and Amber.',
        4,
        1,
        NULL
      ),
(
        'Athletic-Planet-Impact-31135',
        'Athletic Planet Impact Perfume and Skin',
        'Athletic',
        'for men',
        NULL,
        NULL,
        'Yuzu, Bergamot, Tarragon and Lemon',
        'Nutmeg, Water Lily, Lily-of-the-Valley and Mignonette',
        'Cedar, Sandalwood, Vetiver and Musk',
        'citrus,woody,floral,aromatic,fresh spicy',
        'Athletic Planet ImpactbyPerfume and Skinis a Woody Spicy fragrance for men.Athletic Planet Impactwas launched in 2012. Top notes are Yuzu, Bergamot, Tarragon and Lemon; middle notes are Nutmeg, Water Lily, Lily-of-the-Valley and Mignonette; base notes are Cedar, Sandalwood, Vetiver and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Athletic-Planet-Spirit-31131',
        'Athletic Planet Spirit Perfume and Skin',
        'Athletic',
        'for women',
        NULL,
        NULL,
        'Bergamot, Litchi, Mandarin Orange and Peach',
        'Jasmine, Plum, Lily and Lily-of-the-Valley',
        'Amber, Musk and Vetiver',
        'white floral,fruity,citrus,amber,musky',
        'Athletic Planet SpiritbyPerfume and Skinis a Amber Floral fragrance for women.Athletic Planet Spiritwas launched in 2012. Top notes are Bergamot, Litchi, Mandarin Orange and Peach; middle notes are Jasmine, Plum, Lily and Lily-of-the-Valley; base notes are Amber, Musk and Vetiver.',
        NULL,
        NULL,
        NULL
      ),
(
        'Athletic-Planet-Strength-31132',
        'Athletic Planet Strength Perfume and Skin',
        'Athletic',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Coriander and Basil',
        'Cardamom, Orange Blossom and Ginger',
        'Cedar, Amber and Tobacco',
        'aromatic,warm spicy,citrus,fresh spicy,amber',
        'Athletic Planet StrengthbyPerfume and Skinis a Amber Woody fragrance for men.Athletic Planet Strengthwas launched in 2012. Top notes are Grapefruit, Coriander and Basil; middle notes are Cardamom, Orange Blossom and Ginger; base notes are Cedar, Amber and Tobacco.',
        NULL,
        NULL,
        NULL
      ),
(
        'Dazzle-15140',
        'Dazzle Paris Hilton',
        'Dazzle',
        'for women',
        NULL,
        'Frank Voelkl',
        'Sour Cherry, Red Apple and Peach',
        'Orchid, Violet and Orange Blossom',
        'Vanilla, Champagne, Patchouli and Musk',
        'sweet,fruity,cherry,vanilla,powdery',
        'DazzlebyParis Hiltonis a Floral Fruity fragrance for women.Dazzlewas launched in 2012. The nose behind this fragrance is Frank Voelkl. Top notes are Sour Cherry, Red Apple and Peach; middle notes are Orchid, Violet and Orange Blossom; base notes are Vanilla, Champagne, Patchouli and Musk.',
        4.16,
        861,
        NULL
      ),
(
        'Electrify-57357',
        'Electrify Paris Hilton',
        'Electrify',
        'for women',
        NULL,
        'Yves Cassar',
        'Red Apple, Ozonic notes, Cyclamen and Mandarin Orange',
        'Red Poppy, Peony, Turkish Rose and Magnolia',
        'Vanilla Absolute, Coconut, Sandalwood and Patchouli',
        'floral,vanilla,sweet,coconut,fresh',
        'ElectrifybyParis Hiltonis a Amber Floral fragrance for women.Electrifywas launched in 2019. The nose behind this fragrance is Yves Cassar. Top notes are Red Apple, Ozonic notes, Cyclamen and Mandarin Orange; middle notes are Red Poppy, Peony, Turkish Rose and Magnolia; base notes are Vanilla Absolute, Coconut, Sandalwood and Patchouli.',
        4.01,
        164,
        NULL
      ),
(
        'Fairy-Dust-4740',
        'Fairy Dust Paris Hilton',
        'Fairy',
        'for women',
        NULL,
        'Mane',
        'Peony and Orange Blossom',
        'Gardenia, Peach and Lotus',
        'Musk, Vanilla and Patchouli',
        'white floral,floral,musky,powdery,lactonic',
        'Fairy DustbyParis Hiltonis a Floral fragrance for women.Fairy Dustwas launched in 2008. The nose behind this fragrance is Mane. Top notes are Peony and Orange Blossom; middle notes are Gardenia, Peach and Lotus; base notes are Musk, Vanilla and Patchouli.',
        3.25,
        1,
        NULL
      ),
(
        'Siren-6193',
        'Siren Paris Hilton',
        'Siren',
        'for women',
        NULL,
        'Honorine Blanc',
        'Apricot, Frangipani, Peach and Mandarin Orange',
        'Honeysuckle, Orchid and Lotus',
        'Vanilla, Musk and Sandalwood',
        'floral,fruity,powdery,lactonic,vanilla',
        'SirenbyParis Hiltonis a Amber Floral fragrance for women.Sirenwas launched in 2009. The nose behind this fragrance is Honorine Blanc. Top notes are Apricot, Frangipani, Peach and Mandarin Orange; middle notes are Honeysuckle, Orchid and Lotus; base notes are Vanilla, Musk and Sandalwood.',
        3.96,
        1,
        NULL
      ),
(
        'Tease-8908',
        'Tease Paris Hilton',
        'Tease',
        'for women',
        NULL,
        'Steve DeMercado',
        'Red Apple, Peach and Bergamot',
        'Tuberose, Jasmine and Frangipani',
        'Sand, Woodsy Notes and Amber',
        'white floral,tuberose,fruity,floral,sand',
        'TeasebyParis Hiltonis a Chypre Floral fragrance for women.Teasewas launched in 2010. The nose behind this fragrance is Steve DeMercado. Top notes are Red Apple, Peach and Bergamot; middle notes are Tuberose, Jasmine and Frangipani; base notes are Sand, Woodsy Notes and Amber.',
        3.73,
        816,
        NULL
      ),
(
        'With-Love-28218',
        'With Love Paris Hilton',
        'With',
        'for women',
        NULL,
        NULL,
        'Green Apple, Kiwi and Bergamot',
        'Lily-of-the-Valley, Orchid and Wild Jasmine',
        'Musk and Woodsy Notes',
        'fruity,fresh,white floral,citrus,green',
        'With LovebyParis Hiltonis a Floral Fruity fragrance for women.With Lovewas launched in 2014. Top notes are Green Apple, Kiwi and Bergamot; middle notes are Lily-of-the-Valley, Orchid and Wild Jasmine; base notes are Musk and Woodsy Notes.',
        3.81,
        173,
        NULL
      ),
(
        'Can-Can-Bling-Edition-45518',
        'Can Can Bling Edition Paris Hilton',
        'Can',
        'for women',
        NULL,
        NULL,
        'Clementine, Nectarine and Black Currant',
        'Wild Orchid and Orange Blossom',
        'Amber, Musk and Woody Notes',
        'fruity,sweet,citrus,floral,powdery',
        'Can Can Bling EditionbyParis Hiltonis a fragrance for women.Can Can Bling Editionwas launched in 2017. Top notes are Clementine, Nectarine and Black Currant; middle notes are Wild Orchid and Orange Blossom; base notes are Amber, Musk and Woody Notes.',
        4.58,
        31,
        NULL
      ),
(
        'Heiress-Limited-Edition-32365',
        'Heiress Limited Edition Paris Hilton',
        'Heiress',
        'for women',
        NULL,
        NULL,
        'Champagne, Passionfruit, Peach, Mimosa and Orange',
        'Dewberry, Grenadine, Honeysuckle, Ylang-Ylang, Star Jasmine and Tiare Flower',
        'Violet Leaf, White Wood, Tonka Bean and Vetiver',
        'fruity,sweet,white floral,yellow floral,woody',
        'Heiress Limited EditionbyParis Hiltonis a Floral Fruity fragrance for women.Heiress Limited Editionwas launched in 2016. Top notes are Champagne, Passionfruit, Peach, Mimosa and Orange; middle notes are Dewberry, Grenadine, Honeysuckle, Ylang-Ylang, Star Jasmine and Tiare Flower; base notes are Violet Leaf, White Wood, Tonka Bean and Vetiver.',
        4.13,
        86,
        NULL
      ),
(
        'Paris-Hilton-Limited-Edition-Anniversary-Fragrance-30356',
        'Paris Hilton Limited Edition Anniversary Fragrance Paris Hilton',
        'Paris',
        'for women',
        NULL,
        'Steve DeMercado',
        'Red Apple, Peach and Lily-of-the-Valley',
        'Freesia, Mimosa, Tuberose and Jasmine Sambac',
        'Ylang-Ylang, Sandalwood, Oakmoss and Musk',
        'white floral,yellow floral,floral,sweet,fruity',
        'Paris Hilton Limited Edition Anniversary FragrancebyParis Hiltonis a Floral Fruity fragrance for women.Paris Hilton Limited Edition Anniversary Fragrancewas launched in 2015. The nose behind this fragrance is Steve DeMercado. Top notes are Red Apple, Peach and Lily-of-the-Valley; middle notes are Freesia, Mimosa, Tuberose and Jasmine Sambac; base notes are Ylang-Ylang, Sandalwood, Oakmoss and Musk.',
        4.22,
        72,
        NULL
      ),
(
        'Can-Can-1202',
        'Can Can Paris Hilton',
        'Can',
        'for women',
        NULL,
        'Jean Claude Delville',
        'Nectarine, Black Currant and Clementine',
        'Wild Orchid and Orange Blossom',
        'Amber, Musk and Woodsy Notes',
        'fruity,sweet,amber,powdery,citrus',
        'Can CanbyParis Hiltonis a Floral Fruity fragrance for women.Can Canwas launched in 2007. The nose behind this fragrance is Jean Claude Delville. Top notes are Nectarine, Black Currant and Clementine; middle notes are Wild Orchid and Orange Blossom; base notes are Amber, Musk and Woodsy Notes.',
        3.9,
        2,
        NULL
      ),
(
        'Can-Can-Burlesque-24464',
        'Can Can Burlesque Paris Hilton',
        'Can',
        'for women',
        NULL,
        NULL,
        'Raspberry, Nectarine, Cassis and Clementine',
        'Wild Orchid and Orange Blossom',
        'Musk and White Woods',
        'fruity,sweet,powdery,floral,musky',
        'Can Can BurlesquebyParis Hiltonis a Floral Fruity fragrance for women.Can Can Burlesquewas launched in 2014. Top notes are Raspberry, Nectarine, Cassis and Clementine; middle notes are Wild Orchid and Orange Blossom; base notes are Musk and White Woods.',
        4.1,
        296,
        NULL
      ),
(
        'Heir-1430',
        'Heir Paris Hilton',
        'Heir',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,fresh spicy,aromatic,lavender',
        'HeirbyParis Hiltonis a Aromatic fragrance for men.Heirwas launched in 2006.',
        3.27,
        177,
        NULL
      ),
(
        'Heiress-1431',
        'Heiress Paris Hilton',
        'Heiress',
        'for women',
        NULL,
        'Fragrance Resources',
        'Champagne, Passionfruit, Peach, Orange and Mimosa',
        'Grenadine, Tiare Flower, Ylang-Ylang, Honeysuckle and Star Jasmine',
        'Tonka Bean, Violet Leaf and White Woods',
        'fruity,sweet,Champagne,tropical,citrus',
        'HeiressbyParis Hiltonis a Floral Fruity fragrance for women.Heiresswas launched in 2006. Heiress was created by Steve DeMercado and Fragrance Resources. Top notes are Champagne, Passionfruit, Peach, Orange and Mimosa; middle notes are Grenadine, Tiare Flower, Ylang-Ylang, Honeysuckle and Star Jasmine; base notes are Tonka Bean, Violet Leaf and White Woods.',
        3.96,
        2,
        NULL
      ),
(
        'Just-Me-1432',
        'Just Me Paris Hilton',
        'Just',
        'for women',
        NULL,
        'Steve DeMercado',
        'Pink Pepper, Raspberry, Violet and Bergamot',
        'White Rose, Freesia, Iris, Lily-of-the-Valley and Ylang-Ylang',
        'Woodsy Notes, Sandalwood, Musk and Tahitian Vanilla',
        'woody,sweet,powdery,floral,rose',
        'Just MebyParis Hiltonis a Floral Fruity fragrance for women.Just Mewas launched in 2005. The nose behind this fragrance is Steve DeMercado. Top notes are Pink Pepper, Raspberry, Violet and Bergamot; middle notes are White Rose, Freesia, Iris, Lily-of-the-Valley and Ylang-Ylang; base notes are Woodsy Notes, Sandalwood, Musk and Tahitian Vanilla.',
        3.33,
        880,
        NULL
      ),
(
        'Just-Me-for-Men-1433',
        'Just Me for Men Paris Hilton',
        'Just',
        'for men',
        NULL,
        'Jean-Louis Grauby',
        'Lime, Bergamot, Lemon, Black Currant, Tangerine and Green Grass',
        'Sea Notes, Sage, Lotus, Cloves and Nutmeg',
        'Mahogany, Incense, Oakmoss, Patchouli and Crystal Amber',
        'citrus,aromatic,marine,woody,fruity',
        'Just Me for MenbyParis Hiltonis a Aromatic Aquatic fragrance for men.Just Me for Menwas launched in 2006. The nose behind this fragrance is Jean-Louis Grauby. Top notes are Lime, Bergamot, Lemon, Black Currant, Tangerine and Green Grass; middle notes are Sea Notes, Sage, Lotus, Cloves and Nutmeg; base notes are Mahogany, Incense, Oakmoss, Patchouli and Crystal Amber.',
        4.09,
        593,
        NULL
      ),
(
        'Paris-Hilton-1434',
        'Paris Hilton Paris Hilton',
        'Paris',
        'for women',
        NULL,
        'James Krivda',
        'Melon, Apple and Peach',
        'Freesia, Mimosa, Jasmine, Lily-of-the-Valley, Lily and Tuberose',
        'Musk, Ylang-Ylang, Sandalwood and Oakmoss',
        'fruity,white floral,fresh,floral,powdery',
        'Paris HiltonbyParis Hiltonis a Floral Fruity fragrance for women.Paris Hiltonwas launched in 2005. Paris Hilton was created by Steve DeMercado and James Krivda. Top notes are Melon, Apple and Peach; middle notes are Freesia, Mimosa, Jasmine, Lily-of-the-Valley, Lily and Tuberose; base notes are Musk, Ylang-Ylang, Sandalwood and Oakmoss.',
        3.7,
        2,
        NULL
      ),
(
        'Paris-Hilton-for-Men-1435',
        'Paris Hilton for Men Paris Hilton',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tropical,green,aromatic,fruity,sweet',
        'Paris Hilton for MenbyParis Hiltonis a Woody Aromatic fragrance for men.Paris Hilton for Menwas launched in 2005.',
        4.04,
        957,
        NULL
      ),
(
        'Paris-Hilton-Sheer-14562',
        'Paris Hilton Sheer Paris Hilton',
        'Paris',
        'for women',
        NULL,
        NULL,
        'Water Notes and Red Apple',
        'Freesia, Jasmine, Lily-of-the-Valley and Mimosa',
        'Musk, Ylang-Ylang and Sandalwood',
        'fresh,floral,white floral,aquatic,yellow floral',
        'Paris Hilton SheerbyParis Hiltonis a Floral Fruity fragrance for women.Paris Hilton Sheerwas launched in 2005. Top notes are Water Notes and Red Apple; middle notes are Freesia, Jasmine, Lily-of-the-Valley and Mimosa; base notes are Musk, Ylang-Ylang and Sandalwood.',
        3.66,
        196,
        NULL
      ),
(
        'Passport-Paris-10580',
        'Passport Paris Paris Hilton',
        'Passport',
        'for women',
        NULL,
        NULL,
        'Peach, Red Berries and Mandarin Orange',
        'Jasmine, Honeysuckle and Peony',
        'Vanille, Musk, Patchouli and Amber',
        'fruity,vanilla,sweet,powdery,white floral',
        'Passport ParisbyParis Hiltonis a Floral Fruity fragrance for women.Passport Pariswas launched in 2010. Top notes are Peach, Red Berries and Mandarin Orange; middle notes are Jasmine, Honeysuckle and Peony; base notes are Vanille, Musk, Patchouli and Amber.',
        4.03,
        546,
        NULL
      ),
(
        'Passport-South-Beach-10582',
        'Passport South Beach Paris Hilton',
        'Passport',
        'for women',
        NULL,
        NULL,
        'Nectarine, Lotus and Freesia',
        'Marigold, Osmanthus and Jasmine',
        'Musk, Woodsy Notes and Sandalwood',
        'floral,fruity,sweet,powdery,woody',
        'Passport South BeachbyParis Hiltonis a Floral Woody Musk fragrance for women.Passport South Beachwas launched in 2010. Top notes are Nectarine, Lotus and Freesia; middle notes are Marigold, Osmanthus and Jasmine; base notes are Musk, Woodsy Notes and Sandalwood.',
        3.88,
        344,
        NULL
      ),
(
        'Passport-St-Moritz-13443',
        'Passport St. Moritz Paris Hilton',
        'Passport',
        'for women',
        NULL,
        NULL,
        'Water Notes, Mountain Air, Amalfi Lemon, Green Notes, Ivy and Pear',
        'Red Poppy, Lily-of-the-Valley, Jasmine, Freesia and Peony',
        'Musk, Sandalwood and Amber',
        'fresh,green,aquatic,floral,ozonic',
        'Passport St. MoritzbyParis Hiltonis a Floral Green fragrance for women.Passport St. Moritzwas launched in 2011. Top notes are Water Notes, Mountain Air, Amalfi Lemon, Green Notes, Ivy and Pear; middle notes are Red Poppy, Lily-of-the-Valley, Jasmine, Freesia and Peony; base notes are Musk, Sandalwood and Amber.',
        3.5,
        147,
        NULL
      ),
(
        'Passport-Tokyo-10581',
        'Passport Tokyo Paris Hilton',
        'Passport',
        'for women',
        NULL,
        NULL,
        'Amalfi Lemon and Red Apple',
        'Frangipani, African Orange Flower, Iris and Jasmine',
        'Virginia Cedar, Sandalwood and Musk',
        'woody,citrus,powdery,white floral,fruity',
        'Passport TokyobyParis Hiltonis a Floral Woody Musk fragrance for women.Passport Tokyowas launched in 2010. Top notes are Amalfi Lemon and Red Apple; middle notes are Frangipani, African Orange Flower, Iris and Jasmine; base notes are Virginia Cedar, Sandalwood and Musk.',
        3.49,
        309,
        NULL
      ),
(
        'Gold-Rush-39568',
        'Gold Rush Paris Hilton',
        'Gold',
        'for women',
        NULL,
        NULL,
        'Nectarine, Lemon and Bergamot',
        'Orchid, Violet and Rose Petals',
        'Praline, Vanilla and Cashmere Wood',
        'sweet,vanilla,powdery,lactonic',
        'Gold RushbyParis Hiltonis a Floral Fruity Gourmand fragrance for women.Gold Rushwas launched in 2016. Top notes are Nectarine, Lemon and Bergamot; middle notes are Orchid, Violet and Rose Petals; base notes are Praline, Vanilla and Cashmere Wood.',
        4.04,
        630,
        NULL
      ),
(
        'Gold-Rush-Man-41567',
        'Gold Rush Man Paris Hilton',
        'Gold',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Cardamom and Bergamot',
        'Lavender, Geranium and Sage',
        'Vanilla, Amber and Tonka Bean',
        'vanilla,aromatic,amber,citrus,warm spicy',
        'Gold Rush ManbyParis Hiltonis a Amber Fougere fragrance for men.Gold Rush Manwas launched in 2017. Top notes are Mandarin Orange, Cardamom and Bergamot; middle notes are Lavender, Geranium and Sage; base notes are Vanilla, Amber and Tonka Bean.',
        4.35,
        264,
        NULL
      ),
(
        'Love-Rush-77610',
        'Love Rush Paris Hilton',
        'Love',
        'for women',
        NULL,
        'Clement Gavarry',
        'Bergamot, Mandarin Orange and Apricot',
        'Gardenia, Tunisian Orange Blossom and Dahlia',
        'Musk, Sandalwood and Vanilla Orchid',
        'white floral,musky,powdery,citrus,woody',
        'Love RushbyParis Hiltonis a Floral fragrance for women. This is a new fragrance.Love Rushwas launched in 2022. The nose behind this fragrance is Clement Gavarry. Top notes are Bergamot, Mandarin Orange and Apricot; middle notes are Gardenia, Tunisian Orange Blossom and Dahlia; base notes are Musk, Sandalwood and Vanilla Orchid.',
        3.57,
        56,
        NULL
      ),
(
        'Luxe-Rush-63918',
        'Luxe Rush Paris Hilton',
        'Luxe',
        'for women',
        NULL,
        'Michelle DeFina',
        'Sicilian Bergamot and Pink Peony',
        'Tyger Lily, Tuberose and Frangipani',
        'Patchouli, Milk Mousse and Sandalwood',
        'white floral,woody,patchouli,lactonic,floral',
        'Luxe RushbyParis Hiltonis a Amber Floral fragrance for women.Luxe Rushwas launched in 2019. The nose behind this fragrance is Michelle DeFina. Top notes are Sicilian Bergamot and Pink Peony; middle notes are Tyger Lily, Tuberose and Frangipani; base notes are Patchouli, Milk Mousse and Sandalwood.',
        4.1,
        89,
        NULL
      ),
(
        'Pink-Rush-64068',
        'Pink Rush Paris Hilton',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Goji Berries, Quince, Nashi Pear and Bergamot',
        'Osmanthus, Hibiscus, Pink Peony and Turkish Rose',
        'Vanilla, Musk, Cashmere Wood, Amber and Tonka Bean',
        'floral,fruity,rose,fresh,musky',
        'Pink RushbyParis Hiltonis a fragrance for women.Pink Rushwas launched in 2019. Top notes are Goji Berries, Quince, Nashi Pear and Bergamot; middle notes are Osmanthus, Hibiscus, Pink Peony and Turkish Rose; base notes are Vanilla, Musk, Cashmere Wood, Amber and Tonka Bean.',
        3.82,
        77,
        NULL
      ),
(
        'Platinum-Rush-50794',
        'Platinum Rush Paris Hilton',
        'Platinum',
        'for women',
        NULL,
        'Frank Voelkl',
        'Pear, Mango and Red Apple',
        'Watery Notes, Magnolia, Green Accord, Lily-of-the-Valley and Floral Notes',
        'Cashmere Musk, Amber and Patchouli',
        'fruity,aquatic,sweet,fresh,tropical',
        'Platinum RushbyParis Hiltonis a fragrance for women.Platinum Rushwas launched in 2018. The nose behind this fragrance is Frank Voelkl. Top notes are Pear, Mango and Red Apple; middle notes are Watery Notes, Magnolia, Green Accord, Lily-of-the-Valley and Floral Notes; base notes are Cashmere Musk, Amber and Patchouli.',
        3.91,
        252,
        NULL
      ),
(
        'Rose-Rush-45571',
        'Rosé Rush Paris Hilton',
        'Rosé',
        'for women',
        NULL,
        'Richard Herpin',
        'Rose Petals, Litchi and Neroli',
        'May Rose, Peony and Papaya',
        'White Musk, Amber and Cedar',
        'rose,tropical,floral,fresh,fruity',
        'Rosé RushbyParis Hiltonis a Floral Fruity fragrance for women.Rosé Rushwas launched in 2017. The nose behind this fragrance is Richard Herpin. Top notes are Rose Petals, Litchi and Neroli; middle notes are May Rose, Peony and Papaya; base notes are White Musk, Amber and Cedar.',
        3.97,
        451,
        NULL
      ),
(
        'Ruby-Rush-70551',
        'Ruby Rush Paris Hilton',
        'Ruby',
        'for women',
        NULL,
        NULL,
        'Cherry, Hibiscus and Whipped Cream',
        'Raspberry Bloom, Dahlia and Water Lily',
        'Vanilla, Musk and Sandalwood',
        'floral,sweet,vanilla,cherry,musky',
        'Ruby RushbyParis Hiltonis a Floral Fruity fragrance for women. This is a new fragrance.Ruby Rushwas launched in 2022. Top notes are Cherry, Hibiscus and Whipped Cream; middle notes are Raspberry Bloom, Dahlia and Water Lily; base notes are Vanilla, Musk and Sandalwood.',
        4.06,
        190,
        NULL
      ),
(
        'Amber-Caviar-56944',
        'Amber Caviar Paris Elysees',
        'Amber',
        'for men',
        NULL,
        NULL,
        'Rhubarb Leaf, Bergamot and Sea Notes',
        'Ginger, Sage and Lavender',
        'Vetiver, Moss and Sandalowood',
        'aromatic,woody,warm spicy,citrus,green',
        'Amber CaviarbyParis Elyseesis a Woody Aromatic fragrance for men.Amber Caviarwas launched in 2017. Top notes are Rhubarb Leaf, Bergamot and Sea Notes; middle notes are Ginger, Sage and Lavender; base notes are Vetiver, Moss and Sandalowood.',
        4.05,
        66,
        NULL
      ),
(
        'Amour-TouJours-37694',
        'Amour TouJours Paris Elysees',
        'Amour',
        'for women',
        NULL,
        NULL,
        'Cassis and Tangerine',
        'Peach, Jasmine, Orange Blossom and Lily-of-the-Valley',
        'Vanilla, Amber, Moss and Patchouli',
        'fruity,white floral,citrus,green,vanilla',
        'Amour TouJoursbyParis Elyseesis a Floral Fruity fragrance for women.Amour TouJourswas launched in 2015. Top notes are Cassis and Tangerine; middle notes are Peach, Jasmine, Orange Blossom and Lily-of-the-Valley; base notes are Vanilla, Amber, Moss and Patchouli.',
        3.91,
        125,
        NULL
      ),
(
        'Attimo-69970',
        'Attimo Paris Elysees',
        'Attimo',
        'for men',
        NULL,
        NULL,
        'Lemon and Thyme',
        'Nutmeg, Juniper and Jasmine',
        'Moss, Sandalwood and Amber',
        'woody,mossy,fresh spicy,aromatic,earthy',
        'AttimobyParis Elyseesis a Aromatic Spicy fragrance for men.Attimowas launched in 2017. Top notes are Lemon and Thyme; middle notes are Nutmeg, Juniper and Jasmine; base notes are Moss, Sandalwood and Amber.',
        3.91,
        33,
        NULL
      ),
(
        'Black-Caviar-For-Men-38122',
        'Black Caviar For Men Paris Elysees',
        'Black',
        'for men',
        NULL,
        NULL,
        'Bergamot, Cedar and Lemon',
        'Anise, Herbal Notes and Olive Blossom',
        'Tonka Bean and Guaiac Wood',
        'citrus,woody,aromatic,vanilla,anis',
        'Black Caviar For MenbyParis Elyseesis a Amber Fougere fragrance for men.Black Caviar For Menwas launched in 2013. Top notes are Bergamot, Cedar and Lemon; middle notes are Anise, Herbal Notes and Olive Blossom; base notes are Tonka Bean and Guaiac Wood.',
        4.03,
        275,
        NULL
      ),
(
        'Black-Caviar-Woman-37697',
        'Black Caviar Woman Paris Elysees',
        'Black',
        'for women',
        NULL,
        NULL,
        'African Orange Flower and Italian Orange',
        'Tunisian Orange Blossom and Jasmine',
        'Madagascar Vanilla and Honey',
        'white floral,citrus,sweet,vanilla,honey',
        'Black Caviar WomanbyParis Elyseesis a Floral fragrance for women.Black Caviar Womanwas launched in 2009. Top notes are African Orange Flower and Italian Orange; middle notes are Tunisian Orange Blossom and Jasmine; base notes are Madagascar Vanilla and Honey.',
        4.02,
        128,
        NULL
      ),
(
        'Black-Is-Black-58878',
        'Black Is Black Paris Elysees',
        'Black',
        'for men',
        NULL,
        NULL,
        'Lavender and Lemon',
        'Juniper and Patchouli',
        'Oakmoss and Balsam Fir',
        'mossy,woody,aromatic,earthy,fresh spicy',
        'Black Is BlackbyParis Elyseesis a Aromatic Fougere fragrance for men.Black Is Blackwas launched in 2014. Top notes are Lavender and Lemon; middle notes are Juniper and Patchouli; base notes are Oakmoss and Balsam Fir.',
        3.8,
        10,
        NULL
      ),
(
        'Black-Shark-38192',
        'Black Shark Paris Elysees',
        'Black',
        'for men',
        NULL,
        NULL,
        'Lemon and Sage',
        'Patchouli and Cedar',
        'Patchouli and Brazilian Rosewood',
        'woody,patchouli,balsamic,warm spicy,aromatic',
        'Black SharkbyParis Elyseesis a Woody fragrance for men.Black Sharkwas launched in 2015. Top notes are Lemon and Sage; middle notes are Patchouli and Cedar; base notes are Patchouli and Brazilian Rosewood.',
        3.69,
        52,
        NULL
      ),
(
        'Blue-Caviar-For-Men-71294',
        'Blue Caviar For Men Paris Elysees',
        'Blue',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Tangerine and Neroli',
        'Sage, Lavender and Pepper',
        'Cedar, Tonka Bean and Amber',
        'citrus,aromatic,fresh spicy,amber,woody',
        'Blue Caviar For MenbyParis Elyseesis a Aromatic Fougere fragrance for men.Blue Caviar For Menwas launched in 2017. Top notes are Bergamot, Lemon, Tangerine and Neroli; middle notes are Sage, Lavender and Pepper; base notes are Cedar, Tonka Bean and Amber.',
        3.3,
        10,
        NULL
      ),
(
        'Blue-Melody-71085',
        'Blue Melody Paris Elysees',
        'Blue',
        'for women',
        NULL,
        NULL,
        'Lemon, Green Notes, Apple and Lime',
        'Jasmine, Cinnamon, Freesia and Rose',
        'Musk, Cedar and Amber',
        'citrus,green,fresh,musky,woody',
        'Blue MelodybyParis Elyseesis a Floral fragrance for women.Blue Melodywas launched in 2021. Top notes are Lemon, Green Notes, Apple and Lime; middle notes are Jasmine, Cinnamon, Freesia and Rose; base notes are Musk, Cedar and Amber.',
        4.4,
        48,
        NULL
      ),
(
        'BLUE-Spirit-37692',
        'BLUE Spirit Paris Elysees',
        'BLUE',
        'for women',
        NULL,
        NULL,
        'Coconut, Green Notes, Blackcurrant Syrup, Blackberry, Strawberry and Bergamot',
        'Honey, Jasmine, Orchid, Rose and Lily-of-the-Valley',
        'Patchouli, Caramel, Moss, Vanilla, Tonka Bean, Amber and Sandalowood',
        'sweet,patchouli,woody,honey,caramel',
        'BLUE SpiritbyParis Elyseesis a Amber Floral fragrance for women.BLUE Spiritwas launched in 2012. Top notes are Coconut, Green Notes, Blackcurrant Syrup, Blackberry, Strawberry and Bergamot; middle notes are Honey, Jasmine, Orchid, Rose and Lily-of-the-Valley; base notes are Patchouli, Caramel, Moss, Vanilla, Tonka Bean, Amber and Sandalowood.',
        3.45,
        119,
        NULL
      ),
(
        'Cool-Madam-56404',
        'Cool Madam Paris Elysees',
        'Cool',
        'for women',
        NULL,
        NULL,
        'Orange and Tangerine',
        'Turkey Red Rose, Jasmine, Mimosa and Ylang-Ylang',
        'Patchouli, Vetiver, White Musk and Vanille',
        'citrus,woody,patchouli,earthy,rose',
        'Cool MadambyParis Elyseesis a Chypre fragrance for women.Cool Madamwas launched in 2016. Top notes are Orange and Tangerine; middle notes are Turkey Red Rose, Jasmine, Mimosa and Ylang-Ylang; base notes are Patchouli, Vetiver, White Musk and Vanille.',
        4,
        45,
        NULL
      ),
(
        'Cosa-Nostra-Platinium-38121',
        'Cosa Nostra Platinium Paris Elysees',
        'Cosa',
        'for men',
        NULL,
        NULL,
        'Rosemary, Lavender, Petitgrain and Neroli',
        'Sage, Geranium, Galbanum and Jasmine',
        'Oakmoss, Vetiver, Sandalowood, Cedar and Amber',
        'aromatic,fresh spicy,woody,herbal,lavender',
        'Cosa Nostra PlatiniumbyParis Elyseesis a Woody Floral Musk fragrance for men.Cosa Nostra Platiniumwas launched in 1994. Top notes are Rosemary, Lavender, Petitgrain and Neroli; middle notes are Sage, Geranium, Galbanum and Jasmine; base notes are Oakmoss, Vetiver, Sandalowood, Cedar and Amber.',
        3.48,
        21,
        NULL
      ),
(
        'Daniella-Sabrini-37695',
        'Daniella Sabrini Paris Elysees',
        'Daniella',
        'for women',
        NULL,
        NULL,
        'Aldehydes and Bergamot',
        'Jasmine, Orange, Orange Blossom and Lily-of-the-Valley',
        'Vanilla, Sandalowood, Tonka Bean and Patchouli',
        'white floral,aldehydic,vanilla,fresh,woody',
        'Daniella SabrinibyParis Elyseesis a Floral fragrance for women.Daniella Sabriniwas launched in 2010. Top notes are Aldehydes and Bergamot; middle notes are Jasmine, Orange, Orange Blossom and Lily-of-the-Valley; base notes are Vanilla, Sandalowood, Tonka Bean and Patchouli.',
        3.56,
        18,
        NULL
      ),
(
        'Dollar-45009',
        'Dollar Paris Elysees',
        'Dollar',
        'for men',
        NULL,
        NULL,
        'Green Notes, Sage and Bergamot',
        'Juniper, Lavender, Artemisia and Thyme',
        'Moss, Patchouli and Cedar',
        'aromatic,woody,fresh spicy,mossy,earthy',
        'DollarbyParis Elyseesis a Aromatic Fougere fragrance for men.Dollarwas launched in 1991. Top notes are Green Notes, Sage and Bergamot; middle notes are Juniper, Lavender, Artemisia and Thyme; base notes are Moss, Patchouli and Cedar.',
        3.74,
        50,
        NULL
      ),
(
        'Euro-73852',
        'Euro Paris Elysees',
        'Euro',
        'for men',
        NULL,
        NULL,
        'Coriander, Bergamot and Artemisia',
        'Carnation, Patchouli and Jasmine',
        'Incense, Musk, Oakmoss and Vanilla',
        'warm spicy,amber,smoky,floral,musky',
        'EurobyParis Elyseesis a Aromatic Fougere fragrance for men.Eurowas launched in 2016. Top notes are Coriander, Bergamot and Artemisia; middle notes are Carnation, Patchouli and Jasmine; base notes are Incense, Musk, Oakmoss and Vanilla.',
        3.32,
        28,
        NULL
      ),
(
        'Handsome-38120',
        'Handsome Paris Elysees',
        'Handsome',
        'for men',
        NULL,
        NULL,
        'Pine, Eucalyptus, Coriander and Lavender',
        'Cedar, Vetiver, Artemisia and Pepper',
        'Tobacco, Oakmoss, Leather and Patchouli',
        'woody,aromatic,earthy,tobacco,mossy',
        'HandsomebyParis Elyseesis a Chypre fragrance for men.Handsomewas launched during the 2000''s. Top notes are Pine, Eucalyptus, Coriander and Lavender; middle notes are Cedar, Vetiver, Artemisia and Pepper; base notes are Tobacco, Oakmoss, Leather and Patchouli.',
        3.98,
        86,
        NULL
      ),
(
        'Handsome-Black-38119',
        'Handsome Black Paris Elysees',
        'Handsome',
        'for men',
        NULL,
        NULL,
        'Mango, Tangerine, Aldehydes and Lemon',
        'Moss, Sea Notes, Amber and Violet',
        'Cedar and Cardamon',
        'tropical,fruity,woody,sweet,citrus',
        'Handsome BlackbyParis Elyseesis a Woody Aromatic fragrance for men.Handsome Blackwas launched in 2015. Top notes are Mango, Tangerine, Aldehydes and Lemon; middle notes are Moss, Sea Notes, Amber and Violet; base notes are Cedar and Cardamon.',
        3.56,
        41,
        NULL
      ),
(
        'Hibernatus-36142',
        'Hibernatus Paris Elysees',
        'Hibernatus',
        'for men',
        NULL,
        NULL,
        'Carnation, Cumin, Rose, Galbanum and Geranium',
        'Tarragon, Orange and Bergamot',
        'Tobacco, Honey, Patchouli and Vetiver',
        'floral,sweet,tobacco,aromatic,honey',
        'HibernatusbyParis Elyseesis a Aromatic Spicy fragrance for men.Hibernatuswas launched in 1998. Top notes are Carnation, Cumin, Rose, Galbanum and Geranium; middle notes are Tarragon, Orange and Bergamot; base notes are Tobacco, Honey, Patchouli and Vetiver.',
        3.84,
        81,
        NULL
      ),
(
        'It-s-Life-37693',
        'It''s Life Paris Elysees',
        'It''s',
        'for women',
        NULL,
        NULL,
        'Kiwi, Litchi and Quince',
        'White Chocolate, Orchid and Jasmine',
        'Moss and Woody Notes',
        'sweet,fruity,floral,tropical,fresh',
        'It''s LifebyParis Elyseesis a Floral Fruity Gourmand fragrance for women.It''s Lifewas launched in 2013. Top notes are Kiwi, Litchi and Quince; middle notes are White Chocolate, Orchid and Jasmine; base notes are Moss and Woody Notes.',
        3.82,
        91,
        NULL
      ),
(
        'Max-58880',
        'Max Paris Elysees',
        'Max',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint, Artemisia and Bergamot',
        'Orange Blossom, Cinnamon, Cardamom and Cumin',
        'Vanilla, Sandalwood, Amber, Tonka Bean, Moss and Cedar',
        'aromatic,warm spicy,vanilla,fresh spicy,woody',
        'MaxbyParis Elyseesis a Amber Fougere fragrance for men.Maxwas launched in 2015. Top notes are Lavender, Mint, Artemisia and Bergamot; middle notes are Orange Blossom, Cinnamon, Cardamom and Cumin; base notes are Vanilla, Sandalwood, Amber, Tonka Bean, Moss and Cedar.',
        3.75,
        48,
        NULL
      ),
(
        'Mezzo-58879',
        'Mezzo Paris Elysees',
        'Mezzo',
        'for men',
        NULL,
        NULL,
        'Thyme and Lime',
        'Juniper, Jasmine and Nutmeg',
        'Moss, Amber and Sandalowood',
        'aromatic,fresh spicy,woody,mossy,amber',
        'MezzobyParis Elyseesis a Aromatic fragrance for men.Mezzowas launched in 2014. Top notes are Thyme and Lime; middle notes are Juniper, Jasmine and Nutmeg; base notes are Moss, Amber and Sandalowood.',
        4.39,
        18,
        NULL
      ),
(
        'Miss-Elysees-60978',
        'Miss Elysées Paris Elysees',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Jasmine, Ylang-Ylang and Rose',
        'Plum, Orange and Fruity Notes',
        'Sandalowood, Woodsy Notes, Amber and Vanilla',
        'woody,powdery,yellow floral,white floral,rose',
        'Miss ElyséesbyParis Elyseesis a Floral Aldehyde fragrance for women.Miss Elyséeswas launched in 1997. Top notes are Jasmine, Ylang-Ylang and Rose; middle notes are Plum, Orange and Fruity Notes; base notes are Sandalowood, Woodsy Notes, Amber and Vanilla.',
        3.74,
        31,
        NULL
      ),
(
        'Mister-Caviar-67431',
        'Mister Caviar Paris Elysees',
        'Mister',
        'for men',
        NULL,
        NULL,
        'Herbal Notes, Lemon and Tangerine',
        'Nutmeg and Cardamom',
        'Vetiver and Sandalwood',
        'citrus,green,aromatic,woody,fresh spicy',
        'Mister CaviarbyParis Elyseesis a Woody Aromatic fragrance for men.Mister Caviarwas launched in 2020. Top notes are Herbal Notes, Lemon and Tangerine; middle notes are Nutmeg and Cardamom; base notes are Vetiver and Sandalwood.',
        4.03,
        101,
        NULL
      ),
(
        'Moon-Light-36145',
        'Moon Light Paris Elysees',
        'Moon',
        'for men',
        NULL,
        NULL,
        'Lavender, Avocado, Mint, Coriander and Bergamot',
        'Avocado, Orange Blossom, Geranium, Jasmine and Violet',
        'Chocolate, Sandalwood, Vanilla, Amber, Vetiver and Musk',
        'aromatic,chocolate,green,warm spicy,sweet',
        'Moon LightbyParis Elyseesis a Aromatic fragrance for men. Top notes are Lavender, Avocado, Mint, Coriander and Bergamot; middle notes are Avocado, Orange Blossom, Geranium, Jasmine and Violet; base notes are Chocolate, Sandalwood, Vanilla, Amber, Vetiver and Musk.',
        3.83,
        12,
        NULL
      ),
(
        'Night-Caviar-70583',
        'Night Caviar Paris Elysees',
        'Night',
        'for men',
        NULL,
        NULL,
        'Absinthe, Fennel and Anise',
        'Lavender',
        'Black Vanilla Husk and Musk',
        'aromatic,soft spicy,lavender,vanilla,anis',
        'Night CaviarbyParis Elyseesis a Amber fragrance for men.Night Caviarwas launched in 2021. Top notes are Absinthe, Fennel and Anise; middle note is Lavender; base notes are Black Vanilla Husk and Musk.',
        4.13,
        134,
        NULL
      ),
(
        'Number-One-58881',
        'Number One Paris Elysees',
        'Number',
        'for men',
        NULL,
        NULL,
        'Cardamom and Bergamot',
        'Lemon and Pineapple',
        'Papaya',
        'citrus,tropical,warm spicy,aromatic,sweet',
        'Number OnebyParis Elyseesis a Aromatic fragrance for men.Number Onewas launched in 1991. Top notes are Cardamom and Bergamot; middle notes are Lemon and Pineapple; base note is Papaya.',
        4.01,
        92,
        NULL
      ),
(
        'NYSE-73854',
        'NYSE Paris Elysees',
        'NYSE',
        'for men',
        NULL,
        NULL,
        'Green Notes and Citrus Leaf',
        'Green Pepper and Ginger',
        'Oakmoss, Guaiac Wood, Amber and Woodsy Notes',
        'green,aromatic',
        'NYSEbyParis Elyseesis a Aromatic Spicy fragrance for men.NYSEwas launched in 2011. Top notes are Green Notes and Citrus Leaf; middle notes are Green Pepper and Ginger; base notes are Oakmoss, Guaiac Wood, Amber and Woodsy Notes.',
        3.93,
        27,
        NULL
      ),
(
        'Petit-Bisou-37701',
        'Petit Bisou Paris Elysees',
        'Petit',
        'for women',
        NULL,
        NULL,
        'Plum, Violet, Star Anise, Spicy Notes and Blackcurrant Syrup',
        'Tuberose, Ylang-Ylang, Orange Blossom and Lily-of-the-Valley',
        'Vanilla, Benzoin, Tonka Bean and Moss',
        'white floral,fruity,tuberose,sweet,vanilla',
        'Petit BisoubyParis Elyseesis a Amber Floral fragrance for women.Petit Bisouwas launched in 2011. Top notes are Plum, Violet, Star Anise, Spicy Notes and Blackcurrant Syrup; middle notes are Tuberose, Ylang-Ylang, Orange Blossom and Lily-of-the-Valley; base notes are Vanilla, Benzoin, Tonka Bean and Moss.',
        4,
        128,
        NULL
      ),
(
        'Pink-58877',
        'Pink Paris Elysees',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Cedar, Bamboo and Apple Leaf',
        'White Rose and Jasmine',
        'Citruses, Musk and Amber',
        'citrus,woody,fresh,musky,powdery',
        'PinkbyParis Elyseesis a Floral Fruity fragrance for women.Pinkwas launched in 2003. Top notes are Cedar, Bamboo and Apple Leaf; middle notes are White Rose and Jasmine; base notes are Citruses, Musk and Amber.',
        3.77,
        13,
        NULL
      ),
(
        'Red-Garden-37696',
        'Red Garden Paris Elysees',
        'Red',
        'for women',
        NULL,
        NULL,
        'Parma Violet, Wild Rose, Bulgarian Rose and Acácia',
        'Bourbon Vanilla and White Musk',
        'Vanilla, Herbal Notes and Almond',
        'powdery,violet,floral,vanilla,rose',
        'Red GardenbyParis Elyseesis a Amber Floral fragrance for women.Red Gardenwas launched in 2015. Top notes are Parma Violet, Wild Rose, Bulgarian Rose and Acácia; middle notes are Bourbon Vanilla and White Musk; base notes are Vanilla, Herbal Notes and Almond.',
        4.09,
        11,
        NULL
      ),
(
        'Y2K-4Men-78534',
        'Y2K 4Men Paris Elysees',
        'Y2K',
        'for men',
        NULL,
        NULL,
        'Spices, Lavender, Bergamot, Grapefruit, Green Accord and Petitgrain',
        'Sage, Ginger, Green Pepper, Violet and Gardenia',
        'Musk, Sandalwood, Guaiac Wood, Labdanum, Vetiver and Incense',
        'woody,aromatic,warm spicy,musky,powdery',
        'Y2K 4MenbyParis Elyseesis a Woody fragrance for men.Y2K 4Menwas launched in 2006. Top notes are Spices, Lavender, Bergamot, Grapefruit, Green Accord and Petitgrain; middle notes are Sage, Ginger, Green Pepper, Violet and Gardenia; base notes are Musk, Sandalwood, Guaiac Wood, Labdanum, Vetiver and Incense.',
        3.54,
        13,
        NULL
      ),
(
        'Billion-Dollar-35090',
        'Billion Dollar Paris Elysees',
        'Billion',
        'for men',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Clove, Nutmeg and Rose',
        'Amber and White Wood',
        'amber,fresh spicy,warm spicy,woody,rose',
        'Billion DollarbyParis Elyseesis a Woody Spicy fragrance for men.Billion Dollarwas launched in 2008. Top notes are Bergamot and Mandarin Orange; middle notes are Clove, Nutmeg and Rose; base notes are Amber and White Wood.',
        3.85,
        124,
        NULL
      ),
(
        'Billion-Dollar-Blue-Jack-35094',
        'Billion Dollar Blue Jack Paris Elysees',
        'Billion',
        'for men',
        NULL,
        NULL,
        'Lemon, Watery Notes and Mint',
        'Lavender, Rosemary, Rose and Geranium',
        'Musk, Moss, Sandalowood and Tonka Bean',
        'aromatic,fresh spicy,citrus,rose,musky',
        'Billion Dollar Blue JackbyParis Elyseesis a Aromatic fragrance for men.Billion Dollar Blue Jackwas launched in 2015. Top notes are Lemon, Watery Notes and Mint; middle notes are Lavender, Rosemary, Rose and Geranium; base notes are Musk, Moss, Sandalowood and Tonka Bean.',
        4,
        21,
        NULL
      ),
(
        'Billion-Dollar-Collection-35091',
        'Billion Dollar Collection Paris Elysees',
        'Billion',
        'for men',
        NULL,
        NULL,
        'Orange Blossom and Bergamot',
        'Lavender, Nutmeg, Coriander and Rosemary',
        'Tonka Bean and Woody Notes',
        'aromatic,fresh spicy,lavender,citrus,white floral',
        'Billion Dollar CollectionbyParis Elyseesis a Amber fragrance for men.Billion Dollar Collectionwas launched in 2006. Top notes are Orange Blossom and Bergamot; middle notes are Lavender, Nutmeg, Coriander and Rosemary; base notes are Tonka Bean and Woody Notes.',
        4.07,
        137,
        NULL
      ),
(
        'Billion-Dollar-Green-Bond-35093',
        'Billion Dollar Green Bond Paris Elysees',
        'Billion',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Tangerine and Lavender',
        'Mint, Cedar, Guaiac Wood, Clove and Nutmeg',
        'Amber, Tonka Bean, Patchouli and Sandalowood',
        'citrus,aromatic,green,woody,fresh spicy',
        'Billion Dollar Green BondbyParis Elyseesis a Woody Aromatic fragrance for men.Billion Dollar Green Bondwas launched in 2015. Top notes are Bergamot, Lemon, Tangerine and Lavender; middle notes are Mint, Cedar, Guaiac Wood, Clove and Nutmeg; base notes are Amber, Tonka Bean, Patchouli and Sandalowood.',
        3.78,
        23,
        NULL
      ),
(
        'Billion-Dollar-Night-70581',
        'Billion Dollar Night Paris Elysees',
        'Billion',
        'for men',
        NULL,
        NULL,
        'Ginger and Sicilian Lemon',
        'Juniper and Cardamom',
        'Amber, Vanilla and Tonka Bean',
        'amber,vanilla,aromatic,warm spicy,citrus',
        'Billion Dollar NightbyParis Elyseesis a Aromatic fragrance for men.Billion Dollar Nightwas launched in 2021. Top notes are Ginger and Sicilian Lemon; middle notes are Juniper and Cardamom; base notes are Amber, Vanilla and Tonka Bean.',
        4.37,
        46,
        NULL
      ),
(
        'Billion-Dollar-Red-Bond-35092',
        'Billion Dollar Red Bond Paris Elysees',
        'Billion',
        'for men',
        NULL,
        NULL,
        'Apple and Cardamom',
        'Spicy Notes and Water Notes',
        'Vetiver, Cedar and Musk',
        'warm spicy,aquatic,fresh,fruity,woody',
        'Billion Dollar Red BondbyParis Elyseesis a Aromatic fragrance for men.Billion Dollar Red Bondwas launched in 2015. Top notes are Apple and Cardamom; middle notes are Spicy Notes and Water Notes; base notes are Vetiver, Cedar and Musk.',
        3.54,
        26,
        NULL
      ),
(
        'Silver-Caviar-71796',
        'Silver Caviar Paris Elysees',
        'Silver',
        'for men',
        NULL,
        NULL,
        'Orange and Lemon',
        'Lavender, Nutmeg and Chinese Cedar',
        'Moss, Exotic Woods and Incense',
        'citrus,lavender,fresh spicy,aromatic,woody',
        'Silver CaviarbyParis Elyseesis a Woody Aromatic fragrance for men.Silver Caviarwas launched in 2017. Top notes are Orange and Lemon; middle notes are Lavender, Nutmeg and Chinese Cedar; base notes are Moss, Exotic Woods and Incense.',
        4.11,
        19,
        NULL
      ),
(
        'Style-Caviar-71797',
        'Style Caviar Paris Elysees',
        'Style',
        'for men',
        NULL,
        NULL,
        'Orange, Tangerine and Peach',
        'Oriental Woodsy notes, Rose and Jasmine',
        'Vetiver, Vanilla and Labdanum',
        'citrus,woody,white floral,rose,sweet',
        'Style CaviarbyParis Elyseesis a Aromatic fragrance for men.Style Caviarwas launched in 2017. Top notes are Orange, Tangerine and Peach; middle notes are Oriental Woodsy notes, Rose and Jasmine; base notes are Vetiver, Vanilla and Labdanum.',
        2.23,
        13,
        NULL
      ),
(
        'Billion-Woman-35076',
        'Billion Woman Paris Elysees',
        'Billion',
        'for women',
        NULL,
        NULL,
        'Orange and Mandarin Orange',
        'White Flowers and Rose',
        'Amber and Patchouli',
        'white floral,amber,citrus,patchouli,animalic',
        'Billion WomanbyParis Elyseesis a Chypre fragrance for women.Billion Womanwas launched in 2010. Top notes are Orange and Mandarin Orange; middle notes are White Flowers and Rose; base notes are Amber and Patchouli.',
        3.95,
        185,
        NULL
      ),
(
        'Billion-Woman-Love-35081',
        'Billion Woman Love Paris Elysees',
        'Billion',
        'for women',
        NULL,
        NULL,
        'Orange',
        'Floral Notes and Violet',
        'Caramel, Vanilla and Moss',
        'caramel,vanilla,sweet,citrus,powdery',
        'Billion Woman LovebyParis Elyseesis a Floral Fruity Gourmand fragrance for women.Billion Woman Lovewas launched in 2015. Top note is Orange; middle notes are Floral Notes and Violet; base notes are Caramel, Vanilla and Moss.',
        4.08,
        455,
        NULL
      ),
(
        'Billion-Woman-Night-75289',
        'Billion Woman Night Paris Elysees',
        'Billion',
        'for women',
        NULL,
        NULL,
        'Litchi, Currant buds, Raspberry and Calabrian bergamot',
        'Jasmine, Sandalwood, Rose and Gardenia',
        'Cedar, Benzoin and Amber',
        'woody,fruity,white floral,fresh,aromatic',
        'Billion Woman NightbyParis Elyseesis a Amber Floral fragrance for women. This is a new fragrance.Billion Woman Nightwas launched in 2022. Top notes are Litchi, Currant buds, Raspberry and Calabrian bergamot; middle notes are Jasmine, Sandalwood, Rose and Gardenia; base notes are Cedar, Benzoin and Amber.',
        4.33,
        24,
        NULL
      ),
(
        'Gaby-35079',
        'Gaby Paris Elysees',
        'Gaby',
        'for women',
        NULL,
        NULL,
        'Mimosa and Mandarin Orange',
        'Jasmine',
        'Sandalowood and Vanilla',
        'powdery,woody,white floral,yellow floral,vanilla',
        'GabybyParis Elyseesis a Amber Floral fragrance for women.Gabywas launched in 1992. Top notes are Mimosa and Mandarin Orange; middle note is Jasmine; base notes are Sandalowood and Vanilla.',
        3.67,
        80,
        NULL
      ),
(
        'I-love-P-E-35078',
        'I love P. E. Paris Elysees',
        'I',
        'for women',
        NULL,
        NULL,
        'Water Notes and Bergamot',
        'White Flowers, Orange Blossom, Rose and Violet',
        'Musk and Amber',
        'white floral,citrus,aquatic,animalic,powdery',
        'I love P. E.byParis Elyseesis a Floral Fruity fragrance for women.I love P. E.was launched in 2008. Top notes are Water Notes and Bergamot; middle notes are White Flowers, Orange Blossom, Rose and Violet; base notes are Musk and Amber.',
        3.84,
        135,
        NULL
      ),
(
        'Illusion-35087',
        'Illusion Paris Elysees',
        'Illusion',
        'for women',
        NULL,
        NULL,
        'Bergamot and Orange',
        'Mimosa and Jasmine',
        'Vanilla and Vetiver',
        'yellow floral,powdery,vanilla,white floral,floral',
        'IllusionbyParis Elyseesis a Floral Fruity fragrance for women.Illusionwas launched in 2005. Top notes are Bergamot and Orange; middle notes are Mimosa and Jasmine; base notes are Vanilla and Vetiver.',
        3.5,
        8,
        NULL
      ),
(
        'Nuits-Mauves-35082',
        'Nuits Mauves Paris Elysees',
        'Nuits',
        'for women',
        NULL,
        NULL,
        'Ginger, Peony and Tangerine',
        'Jasmine and Red Fruits',
        'Patchouli and Musk',
        'warm spicy,fresh,floral,patchouli,citrus',
        'Nuits MauvesbyParis Elyseesis a Floral fragrance for women.Nuits Mauveswas launched in 2013. Top notes are Ginger, Peony and Tangerine; middle notes are Jasmine and Red Fruits; base notes are Patchouli and Musk.',
        3.79,
        28,
        NULL
      ),
(
        'Pink-Topaz-35083',
        'Pink Topaz Paris Elysees',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Pink Pepper and Bergamot',
        'Rose, Violet, Star Anise, Ylang-Ylang and Raspberry',
        'Cedar, White Musk, Powdery Notes and Vanilla',
        'rose,powdery,woody,floral,soft spicy',
        'Pink TopazbyParis Elyseesis a Floral fragrance for women.Pink Topazwas launched in 2006. Top notes are Pink Pepper and Bergamot; middle notes are Rose, Violet, Star Anise, Ylang-Ylang and Raspberry; base notes are Cedar, White Musk, Powdery Notes and Vanilla.',
        3.53,
        32,
        NULL
      ),
(
        'Rich-and-Pretty-35084',
        'Rich and Pretty Paris Elysees',
        'Rich',
        'for women',
        NULL,
        NULL,
        'Rhubarb and Bergamot',
        'Tincture of Rose, Tuberose and Datura',
        'Sandalowood and Musk',
        'white floral,rose,green,woody,aromatic',
        'Rich and PrettybyParis Elyseesis a Floral fragrance for women.Rich and Prettywas launched in 2009. Top notes are Rhubarb and Bergamot; middle notes are Tincture of Rose, Tuberose and Datura; base notes are Sandalowood and Musk.',
        3.85,
        34,
        NULL
      ),
(
        'Sexy-Woman-35077',
        'Sexy Woman Paris Elysees',
        'Sexy',
        'for women',
        NULL,
        NULL,
        'Bergamot and Cardamom',
        'Violet and Licorice',
        'Sandalowood, Musk, Vanilla and Patchouli',
        'powdery,woody,warm spicy,vanilla,musky',
        'Sexy WomanbyParis Elyseesis a Floral fragrance for women.Sexy Womanwas launched in 2004. Top notes are Bergamot and Cardamom; middle notes are Violet and Licorice; base notes are Sandalowood, Musk, Vanilla and Patchouli.',
        3.66,
        145,
        NULL
      ),
(
        'Sexy-Woman-Love-71795',
        'Sexy Woman Love Paris Elysees',
        'Sexy',
        'for women',
        NULL,
        NULL,
        'Almond and Sweet Orange',
        'Vanilla and Cherry',
        'Honey and Caramel',
        'sweet,honey,caramel,vanilla,almond',
        'Sexy Woman LovebyParis Elyseesis a Floral Fruity fragrance for women.Sexy Woman Lovewas launched in 2021. Top notes are Almond and Sweet Orange; middle notes are Vanilla and Cherry; base notes are Honey and Caramel.',
        4.14,
        35,
        NULL
      ),
(
        'Sexy-Woman-Night-35085',
        'Sexy Woman Night Paris Elysees',
        'Sexy',
        'for women',
        NULL,
        NULL,
        'Fig, Orange and Bergamot',
        'Orange Blossom and Heliotrope',
        'Vanilla, Sandalowood, Patchouli, Amber, White Musk and Vetiver',
        'woody,vanilla,powdery,sweet,citrus',
        'Sexy Woman NightbyParis Elyseesis a Amber Woody fragrance for women.Sexy Woman Nightwas launched in 2005. Top notes are Fig, Orange and Bergamot; middle notes are Orange Blossom and Heliotrope; base notes are Vanilla, Sandalowood, Patchouli, Amber, White Musk and Vetiver.',
        3.94,
        259,
        NULL
      ),
(
        'Sweet-and-Strong-35080',
        'Sweet and Strong Paris Elysees',
        'Sweet',
        'for women',
        NULL,
        NULL,
        'Citruses, Mandarin Orange and Orange',
        'Peach, White Flowers, Rose, Ylang-Ylang and Clove',
        'Vanilla and Woody Notes',
        'fruity,white floral,sweet,citrus,vanilla',
        'Sweet and StrongbyParis Elyseesis a Floral fragrance for women.Sweet and Strongwas launched in 2006. Top notes are Citruses, Mandarin Orange and Orange; middle notes are Peach, White Flowers, Rose, Ylang-Ylang and Clove; base notes are Vanilla and Woody Notes.',
        3.54,
        48,
        NULL
      ),
(
        'Sweet-Girl-35086',
        'Sweet Girl Paris Elysees',
        'Sweet',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Green Notes',
        'Jasmine and Rose',
        'Patchouli, Amber and Musk',
        'patchouli,woody,warm spicy,amber,citrus',
        'Sweet GirlbyParis Elyseesis a Chypre fragrance for women.Sweet Girlwas launched in 2012. Top notes are Mandarin Orange and Green Notes; middle notes are Jasmine and Rose; base notes are Patchouli, Amber and Musk.',
        3.83,
        6,
        NULL
      ),
(
        'Dolce-Sense-Choco-Menthe-67180',
        'Dolce & Sense Choco/Menthe Paris Elysees',
        'Dolce',
        'for women',
        NULL,
        NULL,
        'Caramel, Orange Oil and Fruits',
        'Mint and Chocolate',
        'Vanilla, Moss and Tonka Bean',
        'sweet,caramel,green,aromatic,vanilla',
        'Dolce & Sense Choco/MenthebyParis Elyseesis a Aromatic Green fragrance for women.Dolce & Sense Choco/Menthewas launched in 2019. Top notes are Caramel, Orange Oil and Fruits; middle notes are Mint and Chocolate; base notes are Vanilla, Moss and Tonka Bean.',
        3.6,
        35,
        NULL
      );
