
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Anymus-35173',
        'Anymus Triquetra',
        'Anymus',
        'for women and men',
        NULL,
        NULL,
        'Yellow Mandarin, Green Mandarin and Bergamot',
        'Orange Blossom and Tangerine',
        'White Woods and Incense',
        'citrus,white floral',
        'AnymusbyTriquetrais a Citrus Aromatic fragrance for women and men.Anymuswas launched in 2014. Top notes are Yellow Mandarin, Green Mandarin and Bergamot; middle notes are Orange Blossom and Tangerine; base notes are White Woods and Incense.',
        4.14,
        7,
        NULL
      ),
(
        'Anymus-la-Sera-35174',
        'Anymus la Sera Triquetra',
        'Anymus',
        'for women and men',
        NULL,
        NULL,
        'Petitgrain and Fig Leaf',
        'Cardamom, Fig and Broom',
        'Fig and Sandalwood',
        'warm spicy,green,aromatic,woody,sweet',
        'Anymus la SerabyTriquetrais a Aromatic Fougere fragrance for women and men.Anymus la Serawas launched in 2015. Top notes are Petitgrain and Fig Leaf; middle notes are Cardamom, Fig and Broom; base notes are Fig and Sandalwood.',
        3.88,
        8,
        NULL
      ),
(
        'Mystico-35175',
        'Mystico Triquetra',
        'Mystico',
        'for women and men',
        NULL,
        NULL,
        'Cypress',
        'Incense, Coriander and Cardamom',
        'Agarwood (Oud)',
        'amber,warm spicy,smoky,aromatic,balsamic',
        'MysticobyTriquetrais a Woody Spicy fragrance for women and men.Mysticowas launched in 2015. Top note is Cypress; middle notes are Incense, Coriander and Cardamom; base note is Agarwood (Oud).',
        4,
        5,
        NULL
      ),
(
        'Tuerkan-No-1-Epice-78694',
        'Türkan No/1 Épicé Türkan',
        'Türkan',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Pink Pepper',
        'Cinnamon',
        'Leather and Vetiver',
        'aromatic,leather,citrus,cinnamon,warm spicy',
        'Türkan No/1 ÉpicébyTürkanis a fragrance for women and men.Türkan No/1 Épicéwas launched in 2021. Top notes are Bergamot and Pink Pepper; middle note is Cinnamon; base notes are Leather and Vetiver.',
        3.2,
        5,
        NULL
      ),
(
        'Tuerkan-No-4-Boise-78695',
        'Türkan No/4 Boisé Türkan',
        'Türkan',
        'for women and men',
        NULL,
        NULL,
        'cannabis',
        'Tobacco and Coffee',
        'Agarwood (Oud) and Sandalwood',
        'tobacco,cannabis,coffee,oud,sweet',
        'Türkan No/4 BoisébyTürkanis a fragrance for women and men.Türkan No/4 Boiséwas launched in 2021. Top note is cannabis; middle notes are Tobacco and Coffee; base notes are Agarwood (Oud) and Sandalwood.',
        3.33,
        6,
        NULL
      ),
(
        'Tuerkan-No-7-Agrumes-78696',
        'Türkan No/7 Agrumes Türkan',
        'Türkan',
        'for women and men',
        NULL,
        NULL,
        'Black Currant',
        'Jasmine and Lavender',
        'Cedar and Ambergris',
        'woody,amber,white floral,lavender,fruity',
        'Türkan No/7 AgrumesbyTürkanis a fragrance for women and men.Türkan No/7 Agrumeswas launched in 2021. Top note is Black Currant; middle notes are Jasmine and Lavender; base notes are Cedar and Ambergris.',
        4,
        3,
        NULL
      ),
(
        'Tuerkan-No-8-Floraison-78697',
        'Türkan No/8 Floraison Türkan',
        'Türkan',
        'for women and men',
        NULL,
        NULL,
        'Black Pepper and Truffle',
        'Lily-of-the-Valley and Musk',
        'Patchouli and Amber',
        'earthy,amber,white floral,patchouli,musky',
        'Türkan No/8 FloraisonbyTürkanis a fragrance for women and men.Türkan No/8 Floraisonwas launched in 2021. Top notes are Black Pepper and Truffle; middle notes are Lily-of-the-Valley and Musk; base notes are Patchouli and Amber.',
        4,
        1,
        NULL
      ),
(
        'Tuerkan-No-7-Agrumes-Eau-de-Parfum-92368',
        'Türkan No/7 Agrumes Eau de Parfum Türkan',
        'Türkan',
        'for women and men',
        NULL,
        NULL,
        'Black Currant',
        'Lavender and Jasmine',
        'Ambergris and Cedar',
        'woody,amber,white floral,lavender,fruity',
        'Türkan No/7 Agrumes Eau de ParfumbyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/7 Agrumes Eau de Parfumwas launched in 2024. Top note is Black Currant; middle notes are Lavender and Jasmine; base notes are Ambergris and Cedar.',
        NULL,
        NULL,
        NULL
      ),
(
        'Tuerkan-No-8-Floraison-Eau-de-Parfum-92371',
        'Türkan No/8 Floraison Eau de Parfum Türkan',
        'Türkan',
        'for women and men',
        NULL,
        NULL,
        'Black Pepper and Truffle',
        'Lily of the Valley and Musk',
        'Patchouli and Amber',
        'earthy,amber,white floral,patchouli,musky',
        'Türkan No/8 Floraison Eau de ParfumbyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/8 Floraison Eau de Parfumwas launched in 2024. Top notes are Black Pepper and Truffle; middle notes are Lily of the Valley and Musk; base notes are Patchouli and Amber.',
        4,
        1,
        NULL
      ),
(
        'Tuerkan-No-10-Noblesse-78701',
        'Türkan No/10 Noblesse Türkan',
        'Türkan',
        'for women and men',
        NULL,
        'Olaf Larsen',
        'Plum, Mandarin Orange and Pink Pepper',
        'Jasmine, Tobacco, Rum, Coffee and Cloves',
        'Vanilla, Peru Balsam, Patchouli and Leather',
        'fruity,sweet,white floral,vanilla,warm spicy',
        'Türkan No/10 NoblessebyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/10 Noblessewas launched in 2022. The nose behind this fragrance is Olaf Larsen. Top notes are Plum, Mandarin Orange and Pink Pepper; middle notes are Jasmine, Tobacco, Rum, Coffee and Cloves; base notes are Vanilla, Peru Balsam, Patchouli and Leather.',
        4.5,
        6,
        NULL
      ),
(
        'Tuerkan-No-2-Equilibre-78698',
        'Türkan No/2 Équilibre Türkan',
        'Türkan',
        'for women and men',
        NULL,
        'Elodie Bernard',
        'Timur and Grapefruit Peel',
        'Orris Root, Orange Blossom and Cyclamen',
        'Vetiver and Musk',
        'powdery,earthy,white floral,iris,musky',
        'Türkan No/2 ÉquilibrebyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/2 Équilibrewas launched in 2022. The nose behind this fragrance is Elodie Bernard. Top notes are Timur and Grapefruit Peel; middle notes are Orris Root, Orange Blossom and Cyclamen; base notes are Vetiver and Musk.',
        3,
        1,
        NULL
      ),
(
        'Tuerkan-No-3-Ambre-89117',
        'Türkan No/3 Ambre Türkan',
        'Türkan',
        'for women and men',
        NULL,
        'Julia Rodriguez Pastor',
        'Red Fruits and Apple',
        'Patchouli, Leather and Vetiver',
        'Ambergris and Moss',
        'earthy,woody,fruity,animalic,leather',
        'Türkan No/3 AmbrebyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/3 Ambrewas launched in 2024. The nose behind this fragrance is Julia Rodriguez Pastor. Top notes are Red Fruits and Apple; middle notes are Patchouli, Leather and Vetiver; base notes are Ambergris and Moss.',
        4.6,
        5,
        NULL
      ),
(
        'Tuerkan-No-6-Charme-78699',
        'Türkan No/6 Charme Türkan',
        'Türkan',
        'for women and men',
        NULL,
        'Türkan Doğrulatan Turan',
        'Plum, Rose and Grapes',
        'Geranium and Peony',
        'White Musk and Cedar',
        'rose,fruity,floral,fresh spicy,musky',
        'Türkan No/6 CharmebyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/6 Charmewas launched in 2022. The nose behind this fragrance is Türkan Doğrulatan Turan. Top notes are Plum, Rose and Grapes; middle notes are Geranium and Peony; base notes are White Musk and Cedar.',
        3.5,
        2,
        NULL
      ),
(
        'Tuerkan-No-9-Mystique-78700',
        'Türkan No/9 Mystique Türkan',
        'Türkan',
        'for women and men',
        NULL,
        'Angeline Poubeau Leporini',
        'Cardamom, Saffron and Cinnamon',
        'Cypriol Oil or Nagarmotha, Rose and Tonka Bean',
        'Leather, Patchouli and Labdanum',
        'warm spicy,woody,amber,leather,earthy',
        'Türkan No/9 MystiquebyTürkanis a fragrance for women and men. This is a new fragrance.Türkan No/9 Mystiquewas launched in 2022. The nose behind this fragrance is Angeline Poubeau Leporini. Top notes are Cardamom, Saffron and Cinnamon; middle notes are Cypriol Oil or Nagarmotha, Rose and Tonka Bean; base notes are Leather, Patchouli and Labdanum.',
        4.4,
        5,
        NULL
      ),
(
        'Femme-by-Usher-52226',
        'Femme by Usher Usher',
        'Femme',
        'for women',
        NULL,
        NULL,
        'Red Berries, Pear and Bergamot',
        'White Rose, Jasmine and Iris',
        'Patchouli, Musk and Cedar',
        'fruity,sweet,patchouli,fresh,citrus',
        'Femme by UsherbyUsheris a Chypre Floral fragrance for women.Femme by Usherwas launched in 2018. Top notes are Red Berries, Pear and Bergamot; middle notes are White Rose, Jasmine and Iris; base notes are Patchouli, Musk and Cedar.',
        3.86,
        28,
        NULL
      ),
(
        'Homme-by-Usher-52225',
        'Homme by Usher Usher',
        'Homme',
        'for men',
        NULL,
        NULL,
        'Saffron, Apple, Cardamom and Mandarin Orange',
        'Rosemary, Geranium, Jasmine and Ginger',
        'Tonka Bean, Musk, Woodsy Notes and Ambroxan',
        'warm spicy,aromatic,musky,woody,fresh spicy',
        'Homme by UsherbyUsheris a Amber Spicy fragrance for men.Homme by Usherwas launched in 2018. Top notes are Saffron, Apple, Cardamom and Mandarin Orange; middle notes are Rosemary, Geranium, Jasmine and Ginger; base notes are Tonka Bean, Musk, Woodsy Notes and Ambroxan.',
        4,
        41,
        NULL
      ),
(
        'UR-for-Men-4634',
        'UR for Men Usher',
        'UR',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,woody,marine,fruity',
        'UR for MenbyUsheris a Aromatic Fruity fragrance for men.UR for Menwas launched in 2008.',
        3.48,
        176,
        NULL
      ),
(
        'UR-for-Women-4635',
        'UR for Women Usher',
        'UR',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,white floral,sweet,fresh',
        'UR for WomenbyUsheris a Floral Fruity fragrance for women.UR for Womenwas launched in 2008.',
        3.75,
        266,
        NULL
      ),
(
        'Usher-He-1515',
        'Usher He Usher',
        'Usher',
        'for men',
        NULL,
        'Honorine Blanc',
        'Melon, Pineapple and Lemon Verbena',
        'White Pepper, Blue Lavender, Vetiver and Violet Leaf',
        'Suede, Sandalwood, Guaiac Wood, Musk and Amber',
        'woody,fresh spicy,fruity,sweet,ozonic',
        'Usher HebyUsheris a Woody Aromatic fragrance for men.Usher Hewas launched in 2007. Usher He was created by Richard Herpin and Honorine Blanc. Top notes are Melon, Pineapple and Lemon Verbena; middle notes are White Pepper, Blue Lavender, Vetiver and Violet Leaf; base notes are Suede, Sandalwood, Guaiac Wood, Musk and Amber.',
        3.94,
        428,
        NULL
      ),
(
        'Usher-She-1516',
        'Usher She Usher',
        'Usher',
        'for women',
        NULL,
        'Honorine Blanc',
        'Apple Tree Blossom, Red Currant and Pink Freesia',
        'Apricot, Frangipani, Jasmine and Rose',
        'Musk, Amber, Cashmere Wood, Orchid and Incense',
        'floral,fruity,amber,musky,powdery',
        'Usher ShebyUsheris a Floral Fruity fragrance for women.Usher Shewas launched in 2007. Usher She was created by Honorine Blanc and Richard Herpin. Top notes are Apple Tree Blossom, Red Currant and Pink Freesia; middle notes are Apricot, Frangipani, Jasmine and Rose; base notes are Musk, Amber, Cashmere Wood, Orchid and Incense.',
        3.38,
        257,
        NULL
      ),
(
        'Usher-VIP-7221',
        'Usher VIP Usher',
        'Usher',
        'for men',
        NULL,
        NULL,
        'Kumquat, Bergamot and Tangerine',
        'Saffron, Violet Leaf, Nutmeg and Lotus',
        'Suede, Woodsy Notes, Oakmoss and Vetiver',
        'citrus,leather,woody,fresh spicy,ozonic',
        'Usher VIPbyUsheris a Woody Spicy fragrance for men.Usher VIPwas launched in 2009. Top notes are Kumquat, Bergamot and Tangerine; middle notes are Saffron, Violet Leaf, Nutmeg and Lotus; base notes are Suede, Woodsy Notes, Oakmoss and Vetiver.',
        3.64,
        228,
        NULL
      ),
(
        'Auramber-69905',
        'Auramber Vertus',
        'Auramber',
        'for women and men',
        NULL,
        NULL,
        'Amber, Smoke and Animal notes',
        'Amber and Dry Wood',
        'Amber, Patchouli and Labdanum',
        'amber,woody,animalic,patchouli,smoky',
        'AuramberbyVertusis a Amber Woody fragrance for women and men.Auramberwas launched in 2021. Top notes are Amber, Smoke and Animal notes; middle notes are Amber and Dry Wood; base notes are Amber, Patchouli and Labdanum.',
        3.6,
        43,
        NULL
      ),
(
        'Chaos-69904',
        'Chaos Vertus',
        'Chaos',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes and Lemon',
        'Patchouli, White Flowers and Jasmine',
        'Ambergris, Woody Notes and Oakmoss',
        'marine,woody,amber,aromatic,citrus',
        'ChaosbyVertusis a Woody Floral Musk fragrance for women and men.Chaoswas launched in 2021. Top notes are Sea Notes and Lemon; middle notes are Patchouli, White Flowers and Jasmine; base notes are Ambergris, Woody Notes and Oakmoss.',
        3.78,
        162,
        NULL
      ),
(
        'Oriental-Rose-31877',
        'Oriental Rose Vertus',
        'Oriental',
        'for women and men',
        NULL,
        NULL,
        'Lavender, Cardamom, Olibanum, Saffron and Lemon',
        'Orris, Rose, Violet, Patchouli, Guaiac Wood and Cloves',
        'Amber, Vetiver, Sandalwood, Musk, Cedar and Vanilla',
        'woody,warm spicy,powdery,amber,aromatic',
        'Oriental RosebyVertusis a Amber Floral fragrance for women and men.Oriental Rosewas launched in 2015. Top notes are Lavender, Cardamom, Olibanum, Saffron and Lemon; middle notes are Orris, Rose, Violet, Patchouli, Guaiac Wood and Cloves; base notes are Amber, Vetiver, Sandalwood, Musk, Cedar and Vanilla.',
        3.61,
        41,
        NULL
      ),
(
        'Oud-Noir-31887',
        'Oud Noir Vertus',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Plum, Apple, Saffron, Rhubarb, Grapefruit and Lemon',
        'Rose, Geranium, Cedar, Carnation, Cyclamen, Orris, Amber and Magnolia',
        'Agarwood (Oud), Guaiac Wood, Vetiver, Sandalwood, Vanilla, Musk, Patchouli and Castoreum',
        'woody,fruity,aromatic,warm spicy,rose',
        'Oud NoirbyVertusis a Woody fragrance for women and men.Oud Noirwas launched in 2015. Top notes are Plum, Apple, Saffron, Rhubarb, Grapefruit and Lemon; middle notes are Rose, Geranium, Cedar, Carnation, Cyclamen, Orris, Amber and Magnolia; base notes are Agarwood (Oud), Guaiac Wood, Vetiver, Sandalwood, Vanilla, Musk, Patchouli and Castoreum.',
        3.96,
        76,
        NULL
      ),
(
        'Rose-Morroco-31881',
        'Rose Morroco Vertus',
        'Rose',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Apple and Cardamom',
        'Rose, Cashmere Wood, Geranium, Peach, Violet, Cedar, Magnolia and Lily',
        'Tonka Bean, Vanilla, Agarwood (Oud), Musk, Sandalwood, Patchouli, Amber and Vetiver',
        'woody,rose,warm spicy,aromatic,musky',
        'Rose MorrocobyVertusis a Amber Floral fragrance for women and men.Rose Morrocowas launched in 2015. Top notes are Saffron, Apple and Cardamom; middle notes are Rose, Cashmere Wood, Geranium, Peach, Violet, Cedar, Magnolia and Lily; base notes are Tonka Bean, Vanilla, Agarwood (Oud), Musk, Sandalwood, Patchouli, Amber and Vetiver.',
        3.69,
        54,
        NULL
      ),
(
        'Rose-Prive-31884',
        'Rose Prive Vertus',
        'Rose',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Lemon, Melon, Ginger and Apple',
        'Rose, Cashmere Wood, Orris, Amber, Patchouli, Jasmine, Lily and Cedar',
        'Guaiac Wood, Raspberry, Benzoin, Vanilla, Sandalwood and Musk',
        'woody,rose,warm spicy,amber,powdery',
        'Rose PrivebyVertusis a Chypre Floral fragrance for women and men.Rose Privewas launched in 2015. Top notes are Saffron, Lemon, Melon, Ginger and Apple; middle notes are Rose, Cashmere Wood, Orris, Amber, Patchouli, Jasmine, Lily and Cedar; base notes are Guaiac Wood, Raspberry, Benzoin, Vanilla, Sandalwood and Musk.',
        3.75,
        67,
        NULL
      ),
(
        'Sole-Patchouli-47929',
        'Sole Patchouli Vertus',
        'Sole',
        'for women and men',
        NULL,
        NULL,
        'Patchouli, Green Notes and Orris Root',
        'Patchouli and Mimosa',
        'Patchouli, Marshmallow and Civet',
        'patchouli,powdery,green,woody,earthy',
        'Sole PatchoulibyVertusis a fragrance for women and men.Sole Patchouliwas launched in 2017. Top notes are Patchouli, Green Notes and Orris Root; middle notes are Patchouli and Mimosa; base notes are Patchouli, Marshmallow and Civet.',
        4.29,
        362,
        NULL
      ),
(
        'Vanilla-Oud-31885',
        'Vanilla Oud Vertus',
        'Vanilla',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Rhubarb, Apple and Bergamot',
        'Agarwood (Oud), Saffron, Cashmere Wood, Rose, Jasmine, Cyclamen and Violet',
        'Vanilla, Agarwood (Oud), Caramel, Tonka Bean, Guaiac Wood, Cedar, Sandalwood, Patchouli, Musk and Vetiver',
        'woody,vanilla,oud,warm spicy,caramel',
        'Vanilla OudbyVertusis a Amber Woody fragrance for women and men.Vanilla Oudwas launched in 2015. Top notes are Saffron, Rhubarb, Apple and Bergamot; middle notes are Agarwood (Oud), Saffron, Cashmere Wood, Rose, Jasmine, Cyclamen and Violet; base notes are Vanilla, Agarwood (Oud), Caramel, Tonka Bean, Guaiac Wood, Cedar, Sandalwood, Patchouli, Musk and Vetiver.',
        4.31,
        328,
        NULL
      ),
(
        'Majeste-47925',
        'Majeste Vertus',
        'Majeste',
        'for women and men',
        NULL,
        NULL,
        'Orange, Petitgrain, Bergamot and Lemon',
        'Cedar, Ylang-Ylang and Patchouli',
        'Woody Notes, Powdery Notes, Animal notes and Vanilla',
        'woody,powdery,citrus,animalic,vanilla',
        'MajestebyVertusis a fragrance for women and men.Majestewas launched in 2017. Top notes are Orange, Petitgrain, Bergamot and Lemon; middle notes are Cedar, Ylang-Ylang and Patchouli; base notes are Woody Notes, Powdery Notes, Animal notes and Vanilla.',
        2.92,
        24,
        NULL
      ),
(
        'Royal-Orris-47928',
        'Royal Orris Vertus',
        'Royal',
        'for women and men',
        NULL,
        NULL,
        'Violet, Sweet Notes, Mandarin Orange and Cloves',
        'Iris, Jasmine and Heliotrope',
        'Musk, Vetiver, Woody Notes and Benzoin',
        'powdery,violet,woody,iris,musky',
        'Royal OrrisbyVertusis a Floral Woody Musk fragrance for women and men.Royal Orriswas launched in 2017. Top notes are Violet, Sweet Notes, Mandarin Orange and Cloves; middle notes are Iris, Jasmine and Heliotrope; base notes are Musk, Vetiver, Woody Notes and Benzoin.',
        4,
        35,
        NULL
      ),
(
        '1001-31883',
        '1001 Vertus',
        '1001',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon, Cardamom, Saffron, Bergamot, Ginger and Lime',
        'Violet, Damask Rose, Magnolia, Mimosa, Carnation, Orris and Tuberose',
        'Amber, Cedar, Patchouli, Vanilla, Vetiver, Sandalwood, Cashmere Wood, Oakmoss and Musk',
        'warm spicy,woody,powdery,citrus,aromatic',
        '1001byVertusis a Amber Floral fragrance for women and men.1001was launched in 2015. Top notes are Cinnamon, Cardamom, Saffron, Bergamot, Ginger and Lime; middle notes are Violet, Damask Rose, Magnolia, Mimosa, Carnation, Orris and Tuberose; base notes are Amber, Cedar, Patchouli, Vanilla, Vetiver, Sandalwood, Cashmere Wood, Oakmoss and Musk.',
        3.88,
        77,
        NULL
      ),
(
        'ANKA-90473',
        'ANKA Vertus',
        'ANKA',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Grapefruit and Peach',
        'Clove, Cistus Incanus, Nutmeg and Carrot Seeds',
        'Amber, Sandalwood, Fir and Oakmoss',
        'warm spicy,woody,citrus,fresh spicy,powdery',
        'ANKAbyVertusis a fragrance for women and men. This is a new fragrance.ANKAwas launched in 2024. Top notes are Saffron, Grapefruit and Peach; middle notes are Clove, Cistus Incanus, Nutmeg and Carrot Seeds; base notes are Amber, Sandalwood, Fir and Oakmoss.',
        4,
        24,
        NULL
      ),
(
        'Bengal-80553',
        'Bengal Vertus',
        'Bengal',
        'for women and men',
        NULL,
        NULL,
        'Davana, Bergamot and Ginger',
        'Leather, Patchouli and Rose',
        'Amber, Vanilla, Sandalwood and Suede',
        'leather,amber,woody,warm spicy,powdery',
        'BengalbyVertusis a Leather fragrance for women and men. This is a new fragrance.Bengalwas launched in 2023. Top notes are Davana, Bergamot and Ginger; middle notes are Leather, Patchouli and Rose; base notes are Amber, Vanilla, Sandalwood and Suede.',
        4.25,
        69,
        NULL
      ),
(
        'Bois-et-Cuir-31879',
        'Bois et Cuir Vertus',
        'Bois',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Ivy, Apple, Bergamot and Clary Sage',
        'Cedar, Lavender, Cyclamen, Patchouli, Amber and Jasmine',
        'Leather, Balsam Fir, Sandalwood, Vanilla, Oakmoss, Musk, Tonka Bean and Agarwood (Oud)',
        'woody,aromatic,citrus,fresh,fresh spicy',
        'Bois et CuirbyVertusis a Leather fragrance for women and men.Bois et Cuirwas launched in 2015. Top notes are Grapefruit, Ivy, Apple, Bergamot and Clary Sage; middle notes are Cedar, Lavender, Cyclamen, Patchouli, Amber and Jasmine; base notes are Leather, Balsam Fir, Sandalwood, Vanilla, Oakmoss, Musk, Tonka Bean and Agarwood (Oud).',
        4.07,
        117,
        NULL
      ),
(
        'Monarch-47924',
        'Monarch Vertus',
        'Monarch',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Juniper and Pepper',
        'Cypress, Cloves and Jasmine',
        'Woody Notes, Resins, Oakmoss and Musk',
        'woody,aromatic,fresh spicy,warm spicy,citrus',
        'MonarchbyVertusis a fragrance for women and men.Monarchwas launched in 2017. Top notes are Lemon, Juniper and Pepper; middle notes are Cypress, Cloves and Jasmine; base notes are Woody Notes, Resins, Oakmoss and Musk.',
        4.31,
        205,
        NULL
      ),
(
        'Narcos-is-47923',
        'Narcos''is Vertus',
        'Narcos''is',
        'for women and men',
        NULL,
        NULL,
        'Rhubarb, Cardamom, Coffee and Mandarin Orange',
        'Mango, Ginger and Amber',
        'Vetiver, Ambergris and Peach',
        'fruity,warm spicy,aromatic,sweet,tropical',
        'Narcos''isbyVertusis a fragrance for women and men.Narcos''iswas launched in 2017. Top notes are Rhubarb, Cardamom, Coffee and Mandarin Orange; middle notes are Mango, Ginger and Amber; base notes are Vetiver, Ambergris and Peach.',
        3.75,
        1,
        NULL
      ),
(
        'Night-Dose-31878',
        'Night Dose Vertus',
        'Night',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Mirabelle, Plum, Apple and Grapefruit',
        'Damask Rose, Coconut, Peach, Orris Root, Heliotrope, Lily-of-the-Valley and Jasmine',
        'Sandalwood, Musk, Amber, Oakmoss, Patchouli, Cedar, Tobacco and Tonka Bean',
        'fruity,warm spicy,sweet,woody,powdery',
        'Night DosebyVertusis a Amber Floral fragrance for women and men.Night Dosewas launched in 2015. Top notes are Saffron, Mirabelle, Plum, Apple and Grapefruit; middle notes are Damask Rose, Coconut, Peach, Orris Root, Heliotrope, Lily-of-the-Valley and Jasmine; base notes are Sandalwood, Musk, Amber, Oakmoss, Patchouli, Cedar, Tobacco and Tonka Bean.',
        3.58,
        76,
        NULL
      ),
(
        'Ombre-40555',
        'Ombre Vertus',
        'Ombre',
        'for women and men',
        NULL,
        NULL,
        'Oregano and Bergamot',
        'Vanilla, Labdanum, Patchouli and Cedar',
        'Agarwood (Oud), Sandalwood, Woody Notes and Musk',
        'woody,fresh spicy,oud,powdery,vanilla',
        'OmbrebyVertusis a fragrance for women and men.Ombrewas launched in 2016. Top notes are Oregano and Bergamot; middle notes are Vanilla, Labdanum, Patchouli and Cedar; base notes are Agarwood (Oud), Sandalwood, Woody Notes and Musk.',
        3.67,
        83,
        NULL
      ),
(
        'Paradox-47926',
        'Paradox Vertus',
        'Paradox',
        'for women and men',
        NULL,
        NULL,
        'Fruity and Spicy Notes and Green Notes',
        'Pepper, Rose, Lily-of-the-Valley and Jasmine',
        'Labdanum, Sandalwood, Vetiver and Vanilla',
        'woody,fresh spicy,amber,fruity,green',
        'ParadoxbyVertusis a fragrance for women and men.Paradoxwas launched in 2017. Top notes are Fruity and Spicy Notes and Green Notes; middle notes are Pepper, Rose, Lily-of-the-Valley and Jasmine; base notes are Labdanum, Sandalwood, Vetiver and Vanilla.',
        3.51,
        35,
        NULL
      ),
(
        'Silhouette-47927',
        'Silhouette Vertus',
        'Silhouette',
        'for women and men',
        NULL,
        NULL,
        'Aldehydes, Citruses and Fruity Notes',
        'Violet, Neroli and Jasmine',
        'Leather, Patchouli, Incense and Sandalwood',
        'woody,leather,fresh,warm spicy,smoky',
        'SilhouettebyVertusis a fragrance for women and men.Silhouettewas launched in 2017. Top notes are Aldehydes, Citruses and Fruity Notes; middle notes are Violet, Neroli and Jasmine; base notes are Leather, Patchouli, Incense and Sandalwood.',
        3.93,
        27,
        NULL
      ),
(
        'Eau-de-Cyan-40554',
        'Eau de Cyan Vertus',
        'Eau',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes, Cypress, Sage and Galbanum',
        'Seaweed, Gardenia and Jasmine',
        'Oakmoss, Musk, Patchouli and Amber',
        'aromatic,marine,aquatic,woody,mossy',
        'Eau de CyanbyVertusis a fragrance for women and men.Eau de Cyanwas launched in 2016. Top notes are Sea Notes, Cypress, Sage and Galbanum; middle notes are Seaweed, Gardenia and Jasmine; base notes are Oakmoss, Musk, Patchouli and Amber.',
        3.6,
        77,
        NULL
      ),
(
        'Fresh-Orient-31886',
        'Fresh Orient Vertus',
        'Fresh',
        'for women and men',
        NULL,
        NULL,
        'Green Leaves, Bergamot, Black Currant and Grapefruit',
        'Magnolia, Jasmine, Lily and Cashmere Wood',
        'Vetiver, Musk, Amber and Cedar',
        'citrus,woody,green,floral,aromatic',
        'Fresh OrientbyVertusis a Woody Aromatic fragrance for women and men.Fresh Orientwas launched in 2015. Top notes are Green Leaves, Bergamot, Black Currant and Grapefruit; middle notes are Magnolia, Jasmine, Lily and Cashmere Wood; base notes are Vetiver, Musk, Amber and Cedar.',
        3.71,
        65,
        NULL
      ),
(
        'Amber-Elixir-31880',
        'Amber Elixir Vertus',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        'Dried Fruits, Rum, Black Pepper, Grapefruit and Artemisia',
        'Amber, Saffron, Labdanum, Cashmere Wood and Cedar',
        'Teak Wood, Sandalwood, Musk, Tonka Bean and Castoreum',
        'woody,amber,warm spicy,musky,fruity',
        'Amber ElixirbyVertusis a Woody Spicy fragrance for women and men.Amber Elixirwas launched in 2015. Top notes are Dried Fruits, Rum, Black Pepper, Grapefruit and Artemisia; middle notes are Amber, Saffron, Labdanum, Cashmere Wood and Cedar; base notes are Teak Wood, Sandalwood, Musk, Tonka Bean and Castoreum.',
        3.85,
        172,
        NULL
      ),
(
        'XXIV-Carat-Gold-31882',
        'XXIV Carat Gold Vertus',
        'XXIV',
        'for women and men',
        NULL,
        NULL,
        'Cypress, Juniper Berries and Aldehydes',
        'Pink Pepper and Violet',
        'Vetiver, Sandalwood, Cedar, Tobacco and Musk',
        'woody,aromatic,fresh spicy,earthy,powdery',
        'XXIV Carat GoldbyVertusis a Woody Spicy fragrance for women and men.XXIV Carat Goldwas launched in 2015. Top notes are Cypress, Juniper Berries and Aldehydes; middle notes are Pink Pepper and Violet; base notes are Vetiver, Sandalwood, Cedar, Tobacco and Musk.',
        3.84,
        101,
        NULL
      ),
(
        'Amore-25814',
        'Amore Vince Camuto',
        'Amore',
        'for women',
        NULL,
        'Laurent Le Guernec',
        'Passionfruit, Clementine, Cassis and Bergamot',
        'Orchid, Lotus, Freesia and Lily-of-the-Valley',
        'Cashmere Wood, Musk, Crystal Amber and Sandalowood',
        'floral,citrus,sweet,fruity,woody',
        'AmorebyVince Camutois a Floral Fruity fragrance for women.Amorewas launched in 2014. The nose behind this fragrance is Laurent Le Guernec. Top notes are Passionfruit, Clementine, Cassis and Bergamot; middle notes are Orchid, Lotus, Freesia and Lily-of-the-Valley; base notes are Cashmere Wood, Musk, Crystal Amber and Sandalowood.',
        3.75,
        432,
        NULL
      ),
(
        'Bella-29202',
        'Bella Vince Camuto',
        'Bella',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Nectarine blossom and Jasmine',
        'White Amber',
        'amber,floral,citrus,white floral,fresh spicy',
        'BellabyVince Camutois a Floral fragrance for women.Bellawas launched in 2014. Top note is Bergamot; middle notes are Nectarine blossom and Jasmine; base note is White Amber.',
        3.98,
        455,
        NULL
      ),
(
        'Bella-Notte-81634',
        'Bella Notte Vince Camuto',
        'Bella',
        'for women',
        NULL,
        'Yves Cassar',
        'Blackberry, Black Currant and Pear',
        'Rose, Orange and Orris',
        'Patchouli, Caramel and Sandalwood',
        'fruity,sweet,rose,woody,citrus',
        'Bella NottebyVince Camutois a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Bella Nottewas launched in 2023. The nose behind this fragrance is Yves Cassar. Top notes are Blackberry, Black Currant and Pear; middle notes are Rose, Orange and Orris; base notes are Patchouli, Caramel and Sandalwood.',
        4.27,
        15,
        NULL
      ),
(
        'Brilliante-62674',
        'Brilliante Vince Camuto',
        'Brilliante',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'BrilliantebyVince Camutois a Floral Fruity fragrance for women.Brilliantewas launched in 2020.',
        3.68,
        38,
        NULL
      ),
(
        'Capri-34770',
        'Capri Vince Camuto',
        'Capri',
        'for women',
        NULL,
        NULL,
        'Citruses',
        'Violet and Peach Blossom',
        'Musk and Vanilla',
        'powdery,floral,violet,citrus,fresh',
        'CapribyVince Camutois a Floral Fruity fragrance for women.Capriwas launched in 2015. Top note is Citruses; middle notes are Violet and Peach Blossom; base notes are Musk and Vanilla.',
        3.79,
        280,
        NULL
      ),
(
        'Ciao-41563',
        'Ciao Vince Camuto',
        'Ciao',
        'for women',
        NULL,
        NULL,
        'Wild Strawberry, Blackberry, Italian Mandarin and Pink Grapefruit',
        'Peony, Rose, Passion Flower, Honeysuckle, Lily-of-the-Valley and Pink Jasmine',
        'Amaretto, Cashmeran, Amber, Indonesian Patchouli Leaf and Sandalwood',
        'fruity,sweet,woody,floral,white floral',
        'CiaobyVince Camutois a Floral Fruity fragrance for women.Ciaowas launched in 2016. Top notes are Wild Strawberry, Blackberry, Italian Mandarin and Pink Grapefruit; middle notes are Peony, Rose, Passion Flower, Honeysuckle, Lily-of-the-Valley and Pink Jasmine; base notes are Amaretto, Cashmeran, Amber, Indonesian Patchouli Leaf and Sandalwood.',
        3.85,
        311,
        NULL
      ),
(
        'Divina-48847',
        'Divina Vince Camuto',
        'Divina',
        'for women',
        NULL,
        'Caroline Sabas',
        'Grapefruit, Aldehydes and Black Currant',
        'Mimosa, Sunflower and Violet',
        'Musk, Sandalwood and Heliotrope',
        'powdery,floral,yellow floral,sweet,citrus',
        'DivinabyVince Camutois a Floral Fruity fragrance for women.Divinawas launched in 2018. The nose behind this fragrance is Caroline Sabas. Top notes are Grapefruit, Aldehydes and Black Currant; middle notes are Mimosa, Sunflower and Violet; base notes are Musk, Sandalwood and Heliotrope.',
        3.51,
        178,
        NULL
      ),
(
        'Fiori-17833',
        'Fiori Vince Camuto',
        'Fiori',
        'for women',
        NULL,
        NULL,
        'Nectarine, Bellini and Pink Grapefruit',
        'Freesia, Iris and Jasmine',
        'Musk, Sandalwood, Cedar and Amber',
        'fruity,powdery,sweet,citrus,floral',
        'FioribyVince Camutois a Floral fragrance for women.Fioriwas launched in 2013. Top notes are Nectarine, Bellini and Pink Grapefruit; middle notes are Freesia, Iris and Jasmine; base notes are Musk, Sandalwood, Cedar and Amber.',
        3.94,
        694,
        NULL
      ),
(
        'Floreale-70544',
        'Floreale Vince Camuto',
        'Floreale',
        'for women',
        NULL,
        NULL,
        'Pomelo and Pink Pepper',
        'Pink Peony and Orchid',
        'Vanilla and Cedar',
        'vanilla,floral,sweet,powdery,citrus',
        'FlorealebyVince Camutois a Floral Fruity Gourmand fragrance for women.Florealewas launched in 2021. Top notes are Pomelo and Pink Pepper; middle notes are Pink Peony and Orchid; base notes are Vanilla and Cedar.',
        3.76,
        70,
        NULL
      ),
(
        'Riviera-84574',
        'Riviera Vince Camuto',
        'Riviera',
        'for men',
        NULL,
        'Yves Cassar',
        'Black Pepper, Italian Lemon and Basil Leaf',
        'Thyme, Lavender and Petitgrain',
        'Musk, Oakmoss and Patchouli',
        'fresh spicy,aromatic,citrus,herbal,lavender',
        'RivierabyVince Camutois a Aromatic Fougere fragrance for men. This is a new fragrance.Rivierawas launched in 2023. The nose behind this fragrance is Yves Cassar. Top notes are Black Pepper, Italian Lemon and Basil Leaf; middle notes are Thyme, Lavender and Petitgrain; base notes are Musk, Oakmoss and Patchouli.',
        4,
        17,
        NULL
      ),
(
        'Smoked-Oud-46984',
        'Smoked Oud Vince Camuto',
        'Smoked',
        'for men',
        NULL,
        'Steve DeMercado',
        'Rose, Smoke, Juniper Berries and Davana',
        'Rose, Incense and Spices',
        'Amber, Agarwood (Oud) and Tonka Bean',
        'amber,smoky,rose,warm spicy,aromatic',
        'Smoked OudbyVince Camutois a Amber Woody fragrance for men.Smoked Oudwas launched in 2017. The nose behind this fragrance is Steve DeMercado. Top notes are Rose, Smoke, Juniper Berries and Davana; middle notes are Rose, Incense and Spices; base notes are Amber, Agarwood (Oud) and Tonka Bean.',
        4.4,
        139,
        NULL
      ),
(
        'Terra-41565',
        'Terra Vince Camuto',
        'Terra',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,vanilla,aromatic,citrus,sweet',
        'TerrabyVince Camutois a Woody Aquatic fragrance for men.Terrawas launched in 2017.',
        3.88,
        195,
        NULL
      ),
(
        'Terra-Extreme-62726',
        'Terra Extreme Vince Camuto',
        'Terra',
        'for men',
        NULL,
        NULL,
        'Cinnamon, Mandarin Orange, Grapefruit and Sicilian Bergamot',
        'Rum, Orange Blossom and Geranium',
        'Vanilla, Tonka Bean, Ambroxan, Sandalwood and Benzoin',
        'vanilla,amber,citrus,warm spicy,woody',
        'Terra ExtremebyVince Camutois a Amber Vanilla fragrance for men.Terra Extremewas launched in 2020. Top notes are Cinnamon, Mandarin Orange, Grapefruit and Sicilian Bergamot; middle notes are Rum, Orange Blossom and Geranium; base notes are Vanilla, Tonka Bean, Ambroxan, Sandalwood and Benzoin.',
        4.08,
        95,
        NULL
      ),
(
        'Vince-Camuto-13018',
        'Vince Camuto Vince Camuto',
        'Vince',
        'for women',
        NULL,
        'Steve DeMercado',
        'Rum and Osmanthus',
        'Leather, Jasmine and Rose',
        'Patchouli, Vanille, Amber and Musk',
        'patchouli,rum,woody,floral,vanilla',
        'Vince CamutobyVince Camutois a Chypre Floral fragrance for women.Vince Camutowas launched in 2011. The nose behind this fragrance is Steve DeMercado. Top notes are Rum and Osmanthus; middle notes are Leather, Jasmine and Rose; base notes are Patchouli, Vanille, Amber and Musk.',
        4.07,
        1,
        NULL
      ),
(
        'Vince-Camuto-Eterno-36604',
        'Vince Camuto Eterno Vince Camuto',
        'Vince',
        'for men',
        NULL,
        NULL,
        'Mint and Citruses',
        'Saffron and Bourbon Pepper',
        'Cedar and Patchouli',
        'warm spicy,fresh spicy,woody,green,aromatic',
        'Vince Camuto EternobyVince Camutois a Woody Spicy fragrance for men.Vince Camuto Eternowas launched in 2016. Top notes are Mint and Citruses; middle notes are Saffron and Bourbon Pepper; base notes are Cedar and Patchouli.',
        4.06,
        207,
        NULL
      ),
(
        'Vince-Camuto-Femme-23016',
        'Vince Camuto Femme Vince Camuto',
        'Vince',
        'for women',
        NULL,
        NULL,
        'Citruses and Pink Pepper',
        'Iris, Jasmine and Rose',
        'Vetiver, Musk, Patchouli, Amber and Vanilla',
        'woody,citrus,earthy,musky,powdery',
        'Vince Camuto FemmebyVince Camutois a Amber Floral fragrance for women.Vince Camuto Femmewas launched in 2013. Top notes are Citruses and Pink Pepper; middle notes are Iris, Jasmine and Rose; base notes are Vetiver, Musk, Patchouli, Amber and Vanilla.',
        3.45,
        355,
        NULL
      ),
(
        'Vince-Camuto-for-Men-15942',
        'Vince Camuto for Men Vince Camuto',
        'Vince',
        'for men',
        NULL,
        'Harry Fremont',
        'Bergamot, Black Pepper and Mandarin Orange',
        'Leather, Lavender and Nutmeg',
        'Woody Notes, Musk, Vetiver and Patchouli',
        'fresh spicy,citrus,leather,woody,aromatic',
        'Vince Camuto for MenbyVince Camutois a Woody Aromatic fragrance for men.Vince Camuto for Menwas launched in 2012. The nose behind this fragrance is Harry Fremont. Top notes are Bergamot, Black Pepper and Mandarin Orange; middle notes are Leather, Lavender and Nutmeg; base notes are Woody Notes, Musk, Vetiver and Patchouli.',
        3.95,
        435,
        NULL
      ),
(
        'Vince-Camuto-Homme-24792',
        'Vince Camuto Homme Vince Camuto',
        'Vince',
        'for men',
        NULL,
        'Steve DeMercado',
        'Gin, Lemon and Ozonic notes',
        'Juniper Berries, Cypress, Lavender and Fennel',
        'Atlas Cedar, Birch, Artemisia and Musk',
        'aromatic,woody,fresh spicy,herbal,citrus',
        'Vince Camuto HommebyVince Camutois a Woody Aromatic fragrance for men.Vince Camuto Hommewas launched in 2014. The nose behind this fragrance is Steve DeMercado. Top notes are Gin, Lemon and Ozonic notes; middle notes are Juniper Berries, Cypress, Lavender and Fennel; base notes are Atlas Cedar, Birch, Artemisia and Musk.',
        3.84,
        285,
        NULL
      ),
(
        'Vince-Camuto-Homme-Intenso-70549',
        'Vince Camuto Homme Intenso Vince Camuto',
        'Vince',
        'for men',
        NULL,
        NULL,
        'Citron and Ozonic notes',
        'Ginger and Artemisia',
        'Woody Notes',
        'citrus,woody,herbal,warm spicy,fresh',
        'Vince Camuto Homme IntensobyVince Camutois a Woody Aromatic fragrance for men.Vince Camuto Homme Intensowas launched in 2021. Top notes are Citron and Ozonic notes; middle notes are Ginger and Artemisia; base note is Woody Notes.',
        4.16,
        43,
        NULL
      ),
(
        'Vince-Camuto-Oud-39668',
        'Vince Camuto Oud Vince Camuto',
        'Vince',
        'for men',
        NULL,
        NULL,
        'Saffron, Pink Pepper, Nutmeg and Sage',
        'Agarwood (Oud), Cedar, Musk and Patchouli',
        'Leather, Sandalowood and Amber',
        'woody,oud,leather,warm spicy,powdery',
        'Vince Camuto OudbyVince Camutois a Leather fragrance for men.Vince Camuto Oudwas launched in 2016. Top notes are Saffron, Pink Pepper, Nutmeg and Sage; middle notes are Agarwood (Oud), Cedar, Musk and Patchouli; base notes are Leather, Sandalowood and Amber.',
        4.12,
        88,
        NULL
      ),
(
        'Vince-Camuto-Solare-30117',
        'Vince Camuto Solare Vince Camuto',
        'Vince',
        'for men',
        NULL,
        'Claude Dir',
        'Mandarin Orange',
        'Cardamom and Pimento',
        'Cashmere Wood and Musk',
        'warm spicy,citrus,musky,woody,aromatic',
        'Vince Camuto SolarebyVince Camutois a Amber Woody fragrance for men.Vince Camuto Solarewas launched in 2015. The nose behind this fragrance is Claude Dir. Top note is Mandarin Orange; middle notes are Cardamom and Pimento; base notes are Cashmere Wood and Musk.',
        3.53,
        309,
        NULL
      ),
(
        'Virtu-51235',
        'Virtu Vince Camuto',
        'Virtu',
        'for men',
        NULL,
        'Laurent Le Guernec',
        'Pepper, Papyrus and Cardamom',
        'Birch, Haitian Vetiver and Moss',
        'Sandalwood, Leather, Cedar and Musk',
        'woody,leather,warm spicy,powdery,aromatic',
        'VirtubyVince Camutois a Leather fragrance for men.Virtuwas launched in 2018. The nose behind this fragrance is Laurent Le Guernec. Top notes are Pepper, Papyrus and Cardamom; middle notes are Birch, Haitian Vetiver and Moss; base notes are Sandalwood, Leather, Cedar and Musk.',
        3.83,
        160,
        NULL
      ),
(
        'Wonderbloom-91929',
        'Wonderbloom Vince Camuto',
        'Wonderbloom',
        'for women',
        NULL,
        'Clement Gavarry',
        'Almond Milk, Rhubarb and Pear Leaf',
        'Freesia, Sage and Fig',
        'Labdanum, Praline and Australian Sandalwood',
        'sweet,fruity,woody,green,aromatic',
        'WonderbloombyVince Camutois a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Wonderbloomwas launched in 2024. The nose behind this fragrance is Clement Gavarry. Top notes are Almond Milk, Rhubarb and Pear Leaf; middle notes are Freesia, Sage and Fig; base notes are Labdanum, Praline and Australian Sandalwood.',
        4.4,
        5,
        NULL
      ),
(
        'Illuminare-56211',
        'Illuminare Vince Camuto',
        'Illuminare',
        'for women',
        NULL,
        'Christine Hassan',
        'Bergamot, Pomelo and Plum Blossom',
        'Magnolia, Osmanthus and Red Rose',
        'Musk, Cedar, Suede and Tonka Bean',
        'citrus,floral,fresh spicy,musky,fruity',
        'IlluminarebyVince Camutois a Amber Floral fragrance for women.Illuminarewas launched in 2019. The nose behind this fragrance is Christine Hassan. Top notes are Bergamot, Pomelo and Plum Blossom; middle notes are Magnolia, Osmanthus and Red Rose; base notes are Musk, Cedar, Suede and Tonka Bean.',
        3.76,
        259,
        NULL
      ),
(
        'Illuminare-Intensa-64828',
        'Illuminare Intensa Vince Camuto',
        'Illuminare',
        'for women',
        NULL,
        NULL,
        'Plum, Bergamot and Pink Pepper',
        'Plum Blossom, Orchid, Rose and Iris',
        'Vanilla, Sandalwood, Musk and Amber',
        'floral,fruity,sweet,powdery,citrus',
        'Illuminare IntensabyVince Camutois a Amber Floral fragrance for women.Illuminare Intensawas launched in 2021. Top notes are Plum, Bergamot and Pink Pepper; middle notes are Plum Blossom, Orchid, Rose and Iris; base notes are Vanilla, Sandalwood, Musk and Amber.',
        3.85,
        142,
        NULL
      ),
(
        'Aura-83068',
        'Aura Vollmens',
        'Aura',
        'for women and men',
        NULL,
        'Alfredo Monteiro Filho',
        'Citrus and Floral Notes and Mountain Air',
        'Transparent Flowers and Powdery Notes',
        'White Musk and Amber',
        'powdery,fresh,amber,citrus,musky',
        'AurabyVollmensis a Floral Woody Musk fragrance for women and men.Aurawas launched in 2023. The nose behind this fragrance is Alfredo Monteiro Filho. Top notes are Citrus and Floral Notes and Mountain Air; middle notes are Transparent Flowers and Powdery Notes; base notes are White Musk and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Infinitus-83071',
        'Infinitus Vollmens',
        'Infinitus',
        'for women and men',
        NULL,
        'Luciana Bergamasco',
        'Passionfruit, Tangerine, Rum and Brandy',
        'Lactones, Iris, Whiskey, Leather and Oak',
        'Vanilla, Caramel, Sandalwood, Amber, Vetiver and Gasoline',
        'sweet,powdery,vanilla,caramel,iris',
        'InfinitusbyVollmensis a Amber Spicy fragrance for women and men.Infinituswas launched in 2023. The nose behind this fragrance is Luciana Bergamasco. Top notes are Passionfruit, Tangerine, Rum and Brandy; middle notes are Lactones, Iris, Whiskey, Leather and Oak; base notes are Vanilla, Caramel, Sandalwood, Amber, Vetiver and Gasoline.',
        1,
        1,
        NULL
      ),
(
        'Solis-83069',
        'Solis Vollmens',
        'Solis',
        'for women and men',
        NULL,
        'Paulo Cesar Fonseca',
        'Sicilian Lemon and Bergamot',
        'White Flowers and Sand',
        'Vetiver, Patchouli and Amber',
        'citrus,woody,aromatic,amber,earthy',
        'SolisbyVollmensis a fragrance for women and men.Soliswas launched in 2023. The nose behind this fragrance is Paulo Cesar Fonseca. Top notes are Sicilian Lemon and Bergamot; middle notes are White Flowers and Sand; base notes are Vetiver, Patchouli and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Venusta-83067',
        'Venusta Vollmens',
        'Venusta',
        'for women and men',
        NULL,
        'Juliana Tolotti',
        'Bergamot, Cherry and Pink Pepper',
        'White Flowers, Rose and Heliotrope',
        'Sandal, Praline and Amber',
        'sweet,powdery,amber,woody,rose',
        'VenustabyVollmensis a Amber Floral fragrance for women and men.Venustawas launched in 2023. The nose behind this fragrance is Juliana Tolotti. Top notes are Bergamot, Cherry and Pink Pepper; middle notes are White Flowers, Rose and Heliotrope; base notes are Sandal, Praline and Amber.',
        1,
        1,
        NULL
      ),
(
        'Vitrium-83070',
        'Vitrium Vollmens',
        'Vitrium',
        'for women and men',
        NULL,
        'Edison Fujita',
        'Apple, Yuzu and Pomelo',
        'Mountain Air, Hamanasu and Snow',
        'Amber, Cedar, Patchouli, Musk and Tonka',
        'fresh,citrus,woody,amber,rose',
        'VitriumbyVollmensis a Citrus Aromatic fragrance for women and men.Vitriumwas launched in 2023. The nose behind this fragrance is Edison Fujita. Top notes are Apple, Yuzu and Pomelo; middle notes are Mountain Air, Hamanasu and Snow; base notes are Amber, Cedar, Patchouli, Musk and Tonka.',
        NULL,
        NULL,
        NULL
      ),
(
        'Just-Fly-77147',
        'Just Fly Who Am I',
        'Just',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit',
        'Orris Root',
        'Cedar',
        'citrus,woody,iris,fresh spicy,powdery',
        'Just FlybyWho Am Iis a Aromatic fragrance for women and men.Just Flywas launched in 2020. Top note is Grapefruit; middle note is Orris Root; base note is Cedar.',
        4.35,
        17,
        NULL
      ),
(
        'Just-Right-79597',
        'Just Right Who Am I',
        'Just',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        'Sea Notes',
        'Oakmoss',
        'citrus,marine,mossy,aromatic,earthy',
        'Just RightbyWho Am Iis a Citrus fragrance for men.Just Rightwas launched in 2020. Top note is Bergamot; middle note is Sea Notes; base note is Oakmoss.',
        5,
        1,
        NULL
      ),
(
        'Just-Wow-79598',
        'Just Wow Who Am I',
        'Just',
        'for women and men',
        NULL,
        NULL,
        'Cardamom',
        'Peony',
        'Sandalwood',
        'warm spicy,floral,woody,fresh,aromatic',
        'Just WowbyWho Am Iis a Amber Floral fragrance for women and men.Just Wowwas launched in 2020. Top note is Cardamom; middle note is Peony; base note is Sandalwood.',
        4,
        1,
        NULL
      ),
(
        'Just-Yes-79599',
        'Just Yes Who Am I',
        'Just',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper',
        'Ylang-Ylang',
        'Amber',
        'amber,yellow floral,soft spicy,sweet,woody',
        'Just YesbyWho Am Iis a Floral Woody Musk fragrance for women and men.Just Yeswas launched in 2020. Top note is Pink Pepper; middle note is Ylang-Ylang; base note is Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Black-Amber-43269',
        'Black Amber Womo',
        'Black',
        'for men',
        NULL,
        NULL,
        'Cherry, Artemisia and Buchu or Agathosma',
        'Artemisia, Bitter Almond and Cacao',
        'Tobacco, Amber and Vanilla',
        'sweet,cherry,tobacco,almond,amber',
        'Black AmberbyWomois a Amber Vanilla fragrance for men.Black Amberwas launched in 2014. Top notes are Cherry, Artemisia and Buchu or Agathosma; middle notes are Artemisia, Bitter Almond and Cacao; base notes are Tobacco, Amber and Vanilla.',
        3.94,
        17,
        NULL
      ),
(
        'Black-Cologne-43268',
        'Black Cologne Womo',
        'Black',
        'for men',
        NULL,
        NULL,
        'Bergamot, Anise and Licorice',
        'Jasmine, Clary Sage and Juniper',
        'Vetiver, Iris and ebony tree',
        'woody,aromatic,earthy,soft spicy,white floral',
        'Black ColognebyWomois a Woody Chypre fragrance for men.Black Colognewas launched in 2014. Top notes are Bergamot, Anise and Licorice; middle notes are Jasmine, Clary Sage and Juniper; base notes are Vetiver, Iris and ebony tree.',
        3.71,
        7,
        NULL
      ),
(
        'Black-Oud-43270',
        'Black Oud Womo',
        'Black',
        'for men',
        NULL,
        NULL,
        'Saffron, Myrtle and Black Pepper',
        'Olibanum, Coffee and Jasmine',
        'Agarwood (Oud), Sandalwood and Patchouli',
        'warm spicy,oud,woody,fresh spicy,amber',
        'Black OudbyWomois a Amber Woody fragrance for men.Black Oudwas launched in 2014. Top notes are Saffron, Myrtle and Black Pepper; middle notes are Olibanum, Coffee and Jasmine; base notes are Agarwood (Oud), Sandalwood and Patchouli.',
        4.13,
        15,
        NULL
      ),
(
        'Black-Powder-43266',
        'Black Powder Womo',
        'Black',
        'for men',
        NULL,
        NULL,
        'Iris, Violet Leaf and Pink Pepper',
        'Leather, Jasmine and Carnation',
        'Vanilla, Tonka Bean and White Musk',
        'vanilla,iris,leather,ozonic,powdery',
        'Black PowderbyWomois a Amber Spicy fragrance for men.Black Powderwas launched in 2014. Top notes are Iris, Violet Leaf and Pink Pepper; middle notes are Leather, Jasmine and Carnation; base notes are Vanilla, Tonka Bean and White Musk.',
        4,
        3,
        NULL
      ),
(
        'Black-Spice-43267',
        'Black Spice Womo',
        'Black',
        'for men',
        NULL,
        NULL,
        'Cardamom, Black Pepper and Ginger',
        'Cloves, Nutmeg and Sandalwood',
        'Patchouli, ebony tree and Tonka Bean',
        'warm spicy,woody,patchouli,fresh spicy,aromatic',
        'Black SpicebyWomois a Woody Spicy fragrance for men.Black Spicewas launched in 2014. Top notes are Cardamom, Black Pepper and Ginger; middle notes are Cloves, Nutmeg and Sandalwood; base notes are Patchouli, ebony tree and Tonka Bean.',
        4.2,
        5,
        NULL
      ),
(
        'Black-Tobacco-43265',
        'Black Tobacco Womo',
        'Black',
        'for men',
        NULL,
        NULL,
        'Tobacco Blossom and Cumin',
        'Tobacco Leaf, Honey and Coriander',
        'Tolu Balsam, Vanilla and Cacao Pod',
        'sweet,powdery,amber,tobacco,warm spicy',
        'Black TobaccobyWomois a Amber fragrance for men.Black Tobaccowas launched in 2014. Top notes are Tobacco Blossom and Cumin; middle notes are Tobacco Leaf, Honey and Coriander; base notes are Tolu Balsam, Vanilla and Cacao Pod.',
        4.3,
        20,
        NULL
      ),
(
        'UnXpected-43259',
        'UnXpected Womo',
        'UnXpected',
        'for men',
        NULL,
        NULL,
        'Citruses, Basil, Sage and Marjoram',
        'Ginger, Pepper and Nutmeg',
        'Cedar, Cashmere Wood, Patchouli and Amber',
        'fresh spicy,woody,aromatic,herbal,citrus',
        'UnXpectedbyWomois a Woody Spicy fragrance for men. Top notes are Citruses, Basil, Sage and Marjoram; middle notes are Ginger, Pepper and Nutmeg; base notes are Cedar, Cashmere Wood, Patchouli and Amber.',
        4.33,
        3,
        NULL
      ),
(
        'Xcel-43261',
        'Xcel Womo',
        'Xcel',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Orange, Bergamot and Neroli',
        'Geranium, Orange Blossom and Cardamom',
        'Labdanum, Leather, Vanilla, Sandalwood, Saffron, Vetiver and Myrrh',
        'citrus,warm spicy,aromatic,woody,amber',
        'XcelbyWomois a Woody Spicy fragrance for men. Top notes are Mandarin Orange, Orange, Bergamot and Neroli; middle notes are Geranium, Orange Blossom and Cardamom; base notes are Labdanum, Leather, Vanilla, Sandalwood, Saffron, Vetiver and Myrrh.',
        4,
        1,
        NULL
      ),
(
        'Xcentric-43258',
        'Xcentric Womo',
        'Xcentric',
        'for men',
        NULL,
        NULL,
        'Bergamot, Mint and Lavender',
        'Fig Leaf, Iris, Black Pepper, Violet and Jasmine',
        'Cedar, Patchouli, White Musk and Oakmoss',
        'woody,green,fresh spicy,powdery,fresh',
        'XcentricbyWomois a Aromatic Spicy fragrance for men. Top notes are Bergamot, Mint and Lavender; middle notes are Fig Leaf, Iris, Black Pepper, Violet and Jasmine; base notes are Cedar, Patchouli, White Musk and Oakmoss.',
        3.5,
        2,
        NULL
      ),
(
        'Xcite-43260',
        'Xcite Womo',
        'Xcite',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Fruity Notes, Watery Notes, Sage, Lemon and Bergamot',
        'Mango, Artemisia and Jasmine',
        'Patchouli, Sandalwood and Tonka Bean',
        'citrus,aromatic,fruity,woody,herbal',
        'XcitebyWomois a Citrus Aromatic fragrance for men. Top notes are Mandarin Orange, Fruity Notes, Watery Notes, Sage, Lemon and Bergamot; middle notes are Mango, Artemisia and Jasmine; base notes are Patchouli, Sandalwood and Tonka Bean.',
        NULL,
        NULL,
        NULL
      ),
(
        'Xplore-43262',
        'Xplore Womo',
        'Xplore',
        'for men',
        NULL,
        NULL,
        'Mint, Kumquat, Pink Pepper, Lavender and Sage',
        'Freesia, Nutmeg, Coriander, Juniper, Jasmine, Pineapple and Cardamom',
        'Coumarin, Vanilla, Teak Wood and Leather',
        'aromatic,vanilla,sweet,woody,fresh spicy',
        'XplorebyWomois a Aromatic Fougere fragrance for men. Top notes are Mint, Kumquat, Pink Pepper, Lavender and Sage; middle notes are Freesia, Nutmeg, Coriander, Juniper, Jasmine, Pineapple and Cardamom; base notes are Coumarin, Vanilla, Teak Wood and Leather.',
        4,
        3,
        NULL
      ),
(
        'Xpressive-43257',
        'Xpressive Womo',
        'Xpressive',
        'for men',
        NULL,
        NULL,
        'Artemisia, Lavender and Bergamot',
        'Nutmeg, Pepper, Jasmine and Angelica',
        'Leather, Sandalwood, Amber, Guaiac Wood and Tobacco',
        'fresh spicy,woody,amber,powdery,aromatic',
        'XpressivebyWomois a Amber Fougere fragrance for men. Top notes are Artemisia, Lavender and Bergamot; middle notes are Nutmeg, Pepper, Jasmine and Angelica; base notes are Leather, Sandalwood, Amber, Guaiac Wood and Tobacco.',
        4.29,
        7,
        NULL
      ),
(
        'Blue-Linen-29425',
        'Blue Linen Womo',
        'Blue',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Lime, Rhubarb and Sea Notes',
        'Nutmeg and Cloves',
        'Moss and Amber',
        'citrus,mossy,aromatic,fresh spicy,warm spicy',
        'Blue LinenbyWomois a Amber Spicy fragrance for women and men.Blue Linenwas launched in 2014. Blue Linen was created by Luca Maffei and Maurizio Cerizza. Top notes are Lime, Rhubarb and Sea Notes; middle notes are Nutmeg and Cloves; base notes are Moss and Amber.',
        4.75,
        4,
        NULL
      ),
(
        'Green-Tweed-30244',
        'Green Tweed Womo',
        'Green',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Juniper, Clary Sage and Black Pepper',
        'Mastic or Lentisque, Siberian Pine and Cassis',
        'Cedar, Patchouli and White Musk',
        'aromatic,woody,fresh spicy,soft spicy,balsamic',
        'Green TweedbyWomois a Woody Chypre fragrance for women and men.Green Tweedwas launched in 2014. Green Tweed was created by Luca Maffei and Maurizio Cerizza. Top notes are Juniper, Clary Sage and Black Pepper; middle notes are Mastic or Lentisque, Siberian Pine and Cassis; base notes are Cedar, Patchouli and White Musk.',
        4,
        4,
        NULL
      ),
(
        'Red-Velvet-29426',
        'Red Velvet Womo',
        'Red',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Jasmine and Artemisia',
        'Leather, Labdanum and Tobacco',
        'Guaiac Wood, Amber and Patchouli',
        'amber,leather,woody,animalic,tobacco',
        'Red VelvetbyWomois a Leather fragrance for women and men.Red Velvetwas launched in 2014. The nose behind this fragrance is Luca Maffei. Top notes are Jasmine and Artemisia; middle notes are Leather, Labdanum and Tobacco; base notes are Guaiac Wood, Amber and Patchouli.',
        4,
        5,
        NULL
      ),
(
        'Blow-In-43275',
        'Blow In Womo',
        'Blow',
        'for men',
        NULL,
        NULL,
        'Green Pepper, Red Pepper and Black Pepper',
        'elemi, Vetiver and Cardamom',
        'Patchouli, Blackwood and Oak',
        'woody,aromatic,warm spicy,earthy,fresh spicy',
        'Blow InbyWomois a Woody Spicy fragrance for men. Top notes are Green Pepper, Red Pepper and Black Pepper; middle notes are elemi, Vetiver and Cardamom; base notes are Patchouli, Blackwood and Oak.',
        4,
        1,
        NULL
      ),
(
        'Cool-Down-43272',
        'Cool Down Womo',
        'Cool',
        'for men',
        NULL,
        NULL,
        'Violet Leaf and Water Notes',
        'Cedar and White Woods',
        'Amber, Patchouli, White Musk and Vetiver',
        'woody,aquatic,amber,earthy,musky',
        'Cool DownbyWomois a Woody Aromatic fragrance for men. Top notes are Violet Leaf and Water Notes; middle notes are Cedar and White Woods; base notes are Amber, Patchouli, White Musk and Vetiver.',
        NULL,
        NULL,
        NULL
      ),
(
        'Splash-Out-43305',
        'Splash Out Womo',
        'Splash',
        'for men',
        NULL,
        NULL,
        'Bitter Orange, Yuzu, Sea Notes and Kumquat',
        'Geranium, Cardamom, Violet Leaf, Water Lily, Pink Pepper and White Pepper',
        'Patchouli, White Woods and Musk',
        'citrus,fresh spicy,aromatic,warm spicy,woody',
        'Splash OutbyWomois a Aromatic Aquatic fragrance for men. Top notes are Bitter Orange, Yuzu, Sea Notes and Kumquat; middle notes are Geranium, Cardamom, Violet Leaf, Water Lily, Pink Pepper and White Pepper; base notes are Patchouli, White Woods and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Stand-Up-43274',
        'Stand Up Womo',
        'Stand',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Bergamot and Lime',
        'Basil and Juniper Berries',
        'Sandalwood, Amber, Vetiver, Musk and Iris',
        'citrus,aromatic,woody,fresh spicy,powdery',
        'Stand UpbyWomois a Citrus Aromatic fragrance for men. Top notes are Mandarin Orange, Bergamot and Lime; middle notes are Basil and Juniper Berries; base notes are Sandalwood, Amber, Vetiver, Musk and Iris.',
        NULL,
        NULL,
        NULL
      ),
(
        'Warm-Up-43306',
        'Warm Up Womo',
        'Warm',
        'for men',
        NULL,
        NULL,
        'Lime, Mandarin Leaf, Bergamot and Ozonic notes',
        'Watery Cyclamen, Nutmeg, Coriander and Hyacinth',
        'Amber, Patchouli, Cedar and White Woods',
        'woody,citrus,fresh spicy,floral,aromatic',
        'Warm UpbyWomois a Citrus Aromatic fragrance for men. Top notes are Lime, Mandarin Leaf, Bergamot and Ozonic notes; middle notes are Watery Cyclamen, Nutmeg, Coriander and Hyacinth; base notes are Amber, Patchouli, Cedar and White Woods.',
        NULL,
        NULL,
        NULL
      ),
(
        'Work-Out-43273',
        'Work Out Womo',
        'Work',
        'for men',
        NULL,
        NULL,
        'Mint, Jasmine and Water Notes',
        'Galbanum, Black Pepper and Ginger',
        'Sandalwood, Vetiver, Cedar and Musk',
        'woody,aromatic,green,warm spicy,fresh spicy',
        'Work OutbyWomois a Aromatic Green fragrance for men. Top notes are Mint, Jasmine and Water Notes; middle notes are Galbanum, Black Pepper and Ginger; base notes are Sandalwood, Vetiver, Cedar and Musk.',
        NULL,
        NULL,
        NULL
      );
