
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Cote-des-Palmes-72649',
        'Côte des Palmes Le Monde Gourmand',
        'Côte',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,fresh,green,fruity',
        'Côte des PalmesbyLe Monde Gourmandis a Floral Fruity fragrance for women and men.Côte des Palmeswas launched in 2015.',
        4,
        4,
        NULL
      ),
(
        'Creme-Brulee-73667',
        'Crème Brûlée Le Monde Gourmand',
        'Crème',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,caramel,powdery',
        'Crème BrûléebyLe Monde Gourmandis a Amber Vanilla fragrance for women.Crème Brûléewas launched in 2016.',
        3.8,
        126,
        NULL
      ),
(
        'Creme-de-Violette-93519',
        'Crème de Violette Le Monde Gourmand',
        'Crème',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,herbal,lavender,fresh spicy',
        'Crème de ViolettebyLe Monde Gourmandis a Woody Floral Musk fragrance for women. This is a new fragrance.Crème de Violettewas launched in 2023.',
        4,
        7,
        NULL
      ),
(
        'Creme-Vanille-72647',
        'Crème Vanille Le Monde Gourmand',
        'Crème',
        'for women and men',
        NULL,
        NULL,
        'Apricot',
        'Jasmine',
        'Brown sugar and Amber',
        'sweet,amber,powdery,fruity,animalic',
        'Crème VanillebyLe Monde Gourmandis a Amber Floral fragrance for women and men.Crème Vanillewas launched in 2015. Top note is Apricot; middle note is Jasmine; base notes are Brown sugar and Amber.',
        3.86,
        177,
        NULL
      ),
(
        'Extreme-Epice-78121',
        'Extrême Épicé Le Monde Gourmand',
        'Extrême',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'cinnamon,warm spicy,lactonic,coconut,sweet',
        'Extrême ÉpicébyLe Monde Gourmandis a Aromatic fragrance for women. This is a new fragrance.Extrême Épicéwas launched in 2022.',
        3.78,
        9,
        NULL
      ),
(
        'Figue-du-Foret-43569',
        'Figue du Forêt Le Monde Gourmand',
        'Figue',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,almond,green,woody',
        'Figue du ForêtbyLe Monde Gourmandis a Floral Green fragrance for women.Figue du Forêtwas launched in 2015.',
        3.83,
        121,
        NULL
      ),
(
        'Fleur-de-Blonde-76881',
        'Fleur de Blonde Le Monde Gourmand',
        'Fleur',
        'for women',
        NULL,
        NULL,
        'Ambrette (Musk Mallow)',
        'Violet',
        'Cashmere Musk',
        'musky,floral,powdery,violet',
        'Fleur de BlondebyLe Monde Gourmandis a Amber Floral fragrance for women. Top note is Ambrette (Musk Mallow); middle note is Violet; base note is Cashmere Musk.',
        4.39,
        111,
        NULL
      ),
(
        'Fleur-de-Solaire-94353',
        'Fleur de Solaire Le Monde Gourmand',
        'Fleur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,soft spicy,woody',
        'Fleur de SolairebyLe Monde Gourmandis a Floral fragrance for women. This is a new fragrance.Fleur de Solairewas launched in 2024.',
        4.5,
        2,
        NULL
      ),
(
        'Fleur-Monoi-72650',
        'Fleur Monoï Le Monde Gourmand',
        'Fleur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,coconut,lactonic,sweet,tropical',
        'Fleur MonoïbyLe Monde Gourmandis a Floral fragrance for women.Fleur Monoïwas launched in 2015.',
        3.98,
        53,
        NULL
      ),
(
        'Fraise-Fouettee-92330',
        'Fraise Fouettée Le Monde Gourmand',
        'Fraise',
        'for women',
        NULL,
        NULL,
        'Strawberry, Banana and California Orange',
        'Butter, Heliotrope and Coconut Water',
        'Sugar and Vanilla',
        'sweet,fruity,vanilla,powdery',
        'Fraise FouettéebyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Fraise Fouettéewas launched in 2024. Top notes are Strawberry, Banana and California Orange; middle notes are Butter, Heliotrope and Coconut Water; base notes are Sugar and Vanilla.',
        3.66,
        44,
        NULL
      ),
(
        'Fruit-du-Dragon-72651',
        'Fruit du Dragon Le Monde Gourmand',
        'Fruit',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,tropical,floral',
        'Fruit du DragonbyLe Monde Gourmandis a Floral Fruity fragrance for women.Fruit du Dragonwas launched in 2015.',
        3.9,
        144,
        NULL
      ),
(
        'Hazelnut-L-Hun-72652',
        'Hazelnut L''Hun Le Monde Gourmand',
        'Hazelnut',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,cacao,vanilla,warm spicy,sweet',
        'Hazelnut L''HunbyLe Monde Gourmandis a Woody Aromatic fragrance for women.Hazelnut L''Hunwas launched in 2015.',
        4.09,
        66,
        NULL
      ),
(
        'Herbe-Naturelle-75168',
        'Herbe Naturelle Le Monde Gourmand',
        'Herbe',
        'for women',
        NULL,
        NULL,
        'Pear',
        'Grass',
        'Woodsy Notes and Musk',
        'green,fresh,fruity,sweet',
        'Herbe NaturellebyLe Monde Gourmandis a Aromatic Fruity fragrance for women. This is a new fragrance.Herbe Naturellewas launched in 2022. Top note is Pear; middle note is Grass; base notes are Woodsy Notes and Musk.',
        3.91,
        22,
        NULL
      ),
(
        'Jus-de-Kiwi-72654',
        'Jus de Kiwi Le Monde Gourmand',
        'Jus',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,tropical,sweet,fresh',
        'Jus de KiwibyLe Monde Gourmandis a Aromatic Green fragrance for women.Jus de Kiwiwas launched in 2015.',
        4.28,
        18,
        NULL
      ),
(
        'L-Appletini-81928',
        'L’Appletini Le Monde Gourmand',
        'L’Appletini',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,violet,powdery,green',
        'L’AppletinibyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.L’Appletiniwas launched in 2023.',
        4,
        17,
        NULL
      ),
(
        'La-Vie-Positano-72655',
        'La Vie Positano Le Monde Gourmand',
        'La',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,salty,floral,marine,vanilla',
        'La Vie PositanobyLe Monde Gourmandis a Floral Aquatic fragrance for women.La Vie Positanowas launched in 2015.',
        4.46,
        13,
        NULL
      ),
(
        'Lait-de-Coco-43572',
        'Lait de Coco Le Monde Gourmand',
        'Lait',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Coconut',
        'Vanilla and Praline',
        'coconut,vanilla,sweet,lactonic,tropical',
        'Lait de CocobyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women.Lait de Cocowas launched in 2016. Top note is Bergamot; middle note is Coconut; base notes are Vanilla and Praline.',
        4.02,
        525,
        NULL
      ),
(
        'Latte-D-Or-76817',
        'Latte D''Or Le Monde Gourmand',
        'Latte',
        'for women and men',
        NULL,
        NULL,
        'Ginger',
        'Coconut',
        'Sandalwood',
        'warm spicy,coconut,woody,powdery,sweet',
        'Latte D''OrbyLe Monde Gourmandis a fragrance for women and men. Top note is Ginger; middle note is Coconut; base note is Sandalwood.',
        3.85,
        39,
        NULL
      ),
(
        'Lavande-Citron-93517',
        'Lavande Citron Le Monde Gourmand',
        'Lavande',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,citrus,aromatic,lavender,floral',
        'Lavande CitronbyLe Monde Gourmandis a Citrus Aromatic fragrance for women. This is a new fragrance.Lavande Citronwas launched in 2023.',
        4.25,
        4,
        NULL
      ),
(
        'Le-Beach-72656',
        'Le Beach Le Monde Gourmand',
        'Le',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'yellow floral,sweet,woody,vanilla',
        'Le BeachbyLe Monde Gourmandis a Floral fragrance for women.Le Beachwas launched in 2020.',
        4,
        23,
        NULL
      ),
(
        'Le-Bubble-Pop-72660',
        'Le Bubble Pop Le Monde Gourmand',
        'Le',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,sweet,citrus,fruity,fresh',
        'Le Bubble PopbyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Le Bubble Popwas launched in 2022.',
        3.73,
        45,
        NULL
      ),
(
        'Le-Soleil-Brille-93518',
        'Le Soleil Brille Le Monde Gourmand',
        'Le',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'coconut,floral,woody,marine,sweet',
        'Le Soleil BrillebyLe Monde Gourmandis a Floral fragrance for women. This is a new fragrance.Le Soleil Brillewas launched in 2023.',
        5,
        1,
        NULL
      ),
(
        'Limoncello-Sorbet-76815',
        'Limoncello Sorbet Le Monde Gourmand',
        'Limoncello',
        'for women and men',
        NULL,
        NULL,
        'Lemon Peel and Candied Fruits',
        'Whipped Cream',
        'Vanilla Bean',
        'citrus,vanilla,sweet,aromatic,fruity',
        'Limoncello SorbetbyLe Monde Gourmandis a Citrus Gourmand fragrance for women and men. Top notes are Lemon Peel and Candied Fruits; middle note is Whipped Cream; base note is Vanilla Bean.',
        4,
        29,
        NULL
      ),
(
        'Macaron-Rose-43567',
        'Macaron Rosé Le Monde Gourmand',
        'Macaron',
        'for women',
        NULL,
        NULL,
        'Loukhoum',
        'Rose Water',
        'Sugar Cane',
        'rose,floral,sweet',
        'Macaron RosébyLe Monde Gourmandis a Floral fragrance for women.Macaron Roséwas launched in 2014. Top note is Loukhoum; middle note is Rose Water; base note is Sugar Cane.',
        3.45,
        206,
        NULL
      ),
(
        'Mais-Souffle-81930',
        'Mais Souffle Le Monde Gourmand',
        'Mais',
        'for women and men',
        NULL,
        NULL,
        'Apple',
        'Popcorn',
        'Butter',
        'fruity,lactonic,fresh,green',
        'Mais SoufflebyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Mais Soufflewas launched in 2023. Top note is Apple; middle note is Popcorn; base note is Butter.',
        3.46,
        59,
        NULL
      ),
(
        'Melon-d-Eau-66323',
        'Melon d''Eau Le Monde Gourmand',
        'Melon',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,fruity,aquatic,sweet,citrus',
        'Melon d''EaubyLe Monde Gourmandis a Aromatic Fruity fragrance for women.Melon d''Eauwas launched in 2020.',
        4.33,
        9,
        NULL
      ),
(
        'Menthe-Maroc-43568',
        'Menthe Maroc Le Monde Gourmand',
        'Menthe',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,citrus,sweet,aromatic,fresh spicy',
        'Menthe MarocbyLe Monde Gourmandis a Citrus Aromatic fragrance for women.Menthe Marocwas launched in 2017.',
        4.17,
        12,
        NULL
      ),
(
        'Meringue-Magique-87778',
        'Meringue Magique Le Monde Gourmand',
        'Meringue',
        'for women and men',
        NULL,
        NULL,
        'Orange and Bigarade',
        'Gardenia',
        'Whipped Cream and Praline',
        'sweet,citrus,lactonic,vanilla,white floral',
        'Meringue MagiquebyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Meringue Magiquewas launched in 2023. Top notes are Orange and Bigarade; middle note is Gardenia; base notes are Whipped Cream and Praline.',
        3.93,
        15,
        NULL
      ),
(
        'Miel-Bebe-72657',
        'Miel Bébé Le Monde Gourmand',
        'Miel',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange',
        'Honey',
        'Praline and Sandalwood',
        'sweet,citrus,honey,woody,powdery',
        'Miel BébébyLe Monde Gourmandis a Woody Aromatic fragrance for women.Miel Bébéwas launched in 2018. Top note is Mandarin Orange; middle note is Honey; base notes are Praline and Sandalwood.',
        4.04,
        338,
        NULL
      ),
(
        'Miel-Bourbon-85515',
        'Miel Bourbon Le Monde Gourmand',
        'Miel',
        'for women and men',
        NULL,
        'Erwan Raguenes',
        'Bitter Orange and Bourbon Whiskey',
        'Honey',
        'Vanilla Orchid and Patchouli',
        'warm spicy,woody,citrus,floral,honey',
        'Miel BourbonbyLe Monde Gourmandis a Amber Vanilla fragrance for women and men. This is a new fragrance.Miel Bourbonwas launched in 2023. The nose behind this fragrance is Erwan Raguenes. Top notes are Bitter Orange and Bourbon Whiskey; middle note is Honey; base notes are Vanilla Orchid and Patchouli.',
        2.2,
        15,
        NULL
      ),
(
        'Noir-Distille-68167',
        'Noir Distillé Le Monde Gourmand',
        'Noir',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,amber,whiskey,coconut,powdery',
        'Noir DistillébyLe Monde Gourmandis a Aromatic fragrance for women and men.Noir Distilléwas launched in 2017.',
        4.19,
        107,
        NULL
      ),
(
        'Oud-Sahara-43573',
        'Oud Sahara Le Monde Gourmand',
        'Oud',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,smoky,balsamic,warm spicy',
        'Oud SaharabyLe Monde Gourmandis a Amber fragrance for women.Oud Saharawas launched in 2015.',
        4.27,
        155,
        NULL
      ),
(
        'Paradis-Tropique-76919',
        'Paradis Tropique Le Monde Gourmand',
        'Paradis',
        'for women and men',
        NULL,
        NULL,
        'Blood Orange',
        'Lily-of-the-Valley and Tiare Flower',
        'Sandalwood',
        'white floral,citrus,woody,fresh,fruity',
        'Paradis TropiquebyLe Monde Gourmandis a fragrance for women and men. Top note is Blood Orange; middle notes are Lily-of-the-Valley and Tiare Flower; base note is Sandalwood.',
        4.2,
        15,
        NULL
      ),
(
        'Peche-Delicieuse-93230',
        'Pêche Délicieuse Le Monde Gourmand',
        'Pêche',
        'for women and men',
        NULL,
        NULL,
        'Peach, Cinnamon and Orange',
        'Caramel, White Rose and Cocoa',
        'Vanilla',
        'fruity,sweet,vanilla,caramel,powdery',
        'Pêche DélicieusebyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Pêche Délicieusewas launched in 2024. Top notes are Peach, Cinnamon and Orange; middle notes are Caramel, White Rose and Cocoa; base note is Vanilla.',
        4.26,
        43,
        NULL
      ),
(
        'Petale-Ephemere-93515',
        'Pétale Éphémère Le Monde Gourmand',
        'Pétale',
        'for women',
        NULL,
        NULL,
        'White Peach',
        'Orange Blossom and Rose',
        'Marshmallow',
        'sweet,fruity,white floral,powdery,rose',
        'Pétale ÉphémèrebyLe Monde Gourmandis a fragrance for women. This is a new fragrance.Pétale Éphémèrewas launched in 2024. Top note is White Peach; middle notes are Orange Blossom and Rose; base note is Marshmallow.',
        4.09,
        32,
        NULL
      ),
(
        'Pistachio-Brulee-43575',
        'Pistachio Brûlée Le Monde Gourmand',
        'Pistachio',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,lactonic,sweet,woody,nutty',
        'Pistachio BrûléebyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women.Pistachio Brûléewas launched in 2014.',
        3.84,
        322,
        NULL
      ),
(
        'Pumpkin-Creme-76816',
        'Pumpkin Creme Le Monde Gourmand',
        'Pumpkin',
        'for women and men',
        NULL,
        NULL,
        'Spices and Pumpkin',
        'Nutmeg',
        'Sandalwood',
        'warm spicy,woody,fresh spicy,powdery,sweet',
        'Pumpkin CremebyLe Monde Gourmandis a fragrance for women and men. Top notes are Spices and Pumpkin; middle note is Nutmeg; base note is Sandalwood.',
        3.71,
        59,
        NULL
      ),
(
        'Punch-Aux-Fruits-76882',
        'Punch Aux Fruits Le Monde Gourmand',
        'Punch',
        'for women',
        NULL,
        NULL,
        'Pitahaya',
        'Jasmine',
        'Amber',
        'amber,white floral,tropical,fruity,floral',
        'Punch Aux FruitsbyLe Monde Gourmandis a Floral Fruity fragrance for women. Top note is Pitahaya; middle note is Jasmine; base note is Amber.',
        3.82,
        22,
        NULL
      ),
(
        'Rose-Chocolat-89053',
        'Rose Chocolat Le Monde Gourmand',
        'Rose',
        'for women',
        NULL,
        'Mathieu Nardin',
        NULL,
        NULL,
        NULL,
        'musky,powdery,woody,warm spicy',
        'Rose ChocolatbyLe Monde Gourmandis a Floral fragrance for women. This is a new fragrance.Rose Chocolatwas launched in 2023. The nose behind this fragrance is Mathieu Nardin.',
        4.27,
        48,
        NULL
      ),
(
        'Rum-Tropique-85518',
        'Rum Tropique Le Monde Gourmand',
        'Rum',
        'for women and men',
        NULL,
        NULL,
        'Coconut',
        'Pineapple and Milk',
        'Rum and Caramel',
        'sweet,fruity,lactonic,rum,tropical',
        'Rum TropiquebyLe Monde Gourmandis a Floral Fruity fragrance for women and men. This is a new fragrance.Rum Tropiquewas launched in 2023. Top note is Coconut; middle notes are Pineapple and Milk; base notes are Rum and Caramel.',
        4.08,
        13,
        NULL
      ),
(
        'Santal-Supreme-76829',
        'Santal Supreme Le Monde Gourmand',
        'Santal',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,aromatic,musky,violet',
        'Santal SupremebyLe Monde Gourmandis a fragrance for women and men.',
        3.83,
        169,
        NULL
      ),
(
        'Sel-Caramel-75428',
        'Sel Caramel Le Monde Gourmand',
        'Sel',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,citrus,caramel,lactonic',
        'Sel CaramelbyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Sel Caramelwas launched in 2022.',
        3.96,
        26,
        NULL
      ),
(
        'Sel-Ocean-43571',
        'Sel Océan Le Monde Gourmand',
        'Sel',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,salty,fruity,marine,yellow floral',
        'Sel OcéanbyLe Monde Gourmandis a Floral Aquatic fragrance for women.Sel Océanwas launched in 2016.',
        4.05,
        152,
        NULL
      ),
(
        'Sucre-d-Amande-93516',
        'Sucre d''Amande Le Monde Gourmand',
        'Sucre',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,nutty,musky,almond,warm spicy',
        'Sucre d''AmandebyLe Monde Gourmandis a Aromatic fragrance for women. This is a new fragrance.Sucre d''Amandewas launched in 2023.',
        4.29,
        7,
        NULL
      ),
(
        'Sucre-de-Coton-81929',
        'Sucre de Coton Le Monde Gourmand',
        'Sucre',
        'for women and men',
        NULL,
        NULL,
        'Red Berries',
        'Cyclamen',
        'Vanilla and Sugar',
        'sweet,vanilla,fruity,fresh,powdery',
        'Sucre de CotonbyLe Monde Gourmandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Sucre de Cotonwas launched in 2023. Top note is Red Berries; middle note is Cyclamen; base notes are Vanilla and Sugar.',
        3.7,
        93,
        NULL
      ),
(
        'Tache-de-Cafe-93231',
        'Tache de Café Le Monde Gourmand',
        'Tache',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Dark Chocolate and Black Pepper',
        'Tonka, Milk, Ink and Rose',
        'Vanilla, Cedarwood, Amber, Musk and Patchouli',
        'warm spicy,vanilla,aromatic,amber,sweet',
        'Tache de CafébyLe Monde Gourmandis a Amber Woody fragrance for women and men. This is a new fragrance.Tache de Caféwas launched in 2024. Top notes are Saffron, Dark Chocolate and Black Pepper; middle notes are Tonka, Milk, Ink and Rose; base notes are Vanilla, Cedarwood, Amber, Musk and Patchouli.',
        4.5,
        12,
        NULL
      ),
(
        'The-Matcha-43574',
        'Thé Matcha Le Monde Gourmand',
        'Thé',
        'for men',
        NULL,
        NULL,
        'Green Tea',
        'Freesia',
        'Amber',
        'citrus,fresh,white floral,green,fresh spicy',
        'Thé MatchabyLe Monde Gourmandis a Aromatic fragrance for men.Thé Matchawas launched in 2015. Top note is Green Tea; middle note is Freesia; base note is Amber.',
        3.67,
        270,
        NULL
      ),
(
        'Tres-Pine-76847',
        'Très Pine Le Monde Gourmand',
        'Très',
        'for women and men',
        NULL,
        NULL,
        'Caramel, Rum, Graperfuit and Nutmeg',
        'Red Rose, Davana and Neroli',
        'Balsam Fir, Sandalwood and Oakmoss',
        'woody,caramel,aromatic,fresh spicy,sweet',
        'Très PinebyLe Monde Gourmandis a fragrance for women and men. Top notes are Caramel, Rum, Graperfuit and Nutmeg; middle notes are Red Rose, Davana and Neroli; base notes are Balsam Fir, Sandalwood and Oakmoss.',
        3.96,
        53,
        NULL
      ),
(
        'Vanille-Brillante-78554',
        'Vanille Brillante Le Monde Gourmand',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Jasmine',
        'Amber, Palo Santo and Vanilla',
        'amber,citrus,vanilla,white floral,woody',
        'Vanille BrillantebyLe Monde Gourmandis a Amber Floral fragrance for women. This is a new fragrance.Vanille Brillantewas launched in 2022. Top note is Bergamot; middle note is Jasmine; base notes are Amber, Palo Santo and Vanilla.',
        4.08,
        12,
        NULL
      ),
(
        'Empower-22204',
        'Empower Le Monde Gourmand',
        'Empower',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic,green',
        'EmpowerbyLe Monde Gourmandis a Citrus Aromatic fragrance for women and men.Empowerwas launched in 2013.',
        NULL,
        NULL,
        NULL
      ),
(
        'Envision-22205',
        'Envision Le Monde Gourmand',
        'Envision',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Pink Pepper, Brazilian Orange and Lime',
        'Lavender',
        'Woody Notes, Madagascar Vanilla and Patchouli',
        'citrus,woody,lavender,fresh spicy,vanilla',
        'EnvisionbyLe Monde Gourmandis a Aromatic Fougere fragrance for women and men.Envisionwas launched in 2013. Top notes are Bergamot, Pink Pepper, Brazilian Orange and Lime; middle note is Lavender; base notes are Woody Notes, Madagascar Vanilla and Patchouli.',
        4.5,
        2,
        NULL
      ),
(
        'Together-22206',
        'Together Le Monde Gourmand',
        'Together',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes',
        'Freesia, Violet and Jasmine',
        'Woody Notes',
        'floral,woody,violet,fruity,powdery',
        'TogetherbyLe Monde Gourmandis a Floral Fruity fragrance for women and men.Togetherwas launched in 2013. Top note is Fruity Notes; middle notes are Freesia, Violet and Jasmine; base note is Woody Notes.',
        3.5,
        2,
        NULL
      ),
(
        'Bonbon-Cola-56128',
        'Bonbon Cola Les Petits Plaisirs',
        'Bonbon',
        'for women',
        NULL,
        NULL,
        'Lime, Mint and Orange',
        'Orange Blossom',
        'Vanilla and Musk',
        'vanilla,green,citrus,aromatic,fresh spicy',
        'Bonbon ColabyLes Petits Plaisirsis a Floral Fruity Gourmand fragrance for women. Top notes are Lime, Mint and Orange; middle note is Orange Blossom; base notes are Vanilla and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Bubble-Gum-30494',
        'Bubble Gum Les Petits Plaisirs',
        'Bubble',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet',
        'Bubble GumbyLes Petits Plaisirsis a Aromatic fragrance for women.',
        4.43,
        7,
        NULL
      ),
(
        'Caramel-30493',
        'Caramel Les Petits Plaisirs',
        'Caramel',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'caramel,sweet',
        'CaramelbyLes Petits Plaisirsis a Aromatic Spicy fragrance for women.',
        4.06,
        36,
        NULL
      ),
(
        'Chevrefeuille-30485',
        'Chevrefeuille Les Petits Plaisirs',
        'Chevrefeuille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,fruity,yellow floral',
        'ChevrefeuillebyLes Petits Plaisirsis a Floral fragrance for women.',
        4,
        17,
        NULL
      ),
(
        'Fraise-Acidulee-30488',
        'Fraise Acidulee Les Petits Plaisirs',
        'Fraise',
        'for women',
        NULL,
        NULL,
        'Lemon and Bergamot',
        'Wild Strawberry and Violet',
        'Vanilla, Heliotrope and Cedar',
        'vanilla,fruity,powdery,sweet,woody',
        'Fraise AciduleebyLes Petits Plaisirsis a Floral Fruity Gourmand fragrance for women. Top notes are Lemon and Bergamot; middle notes are Wild Strawberry and Violet; base notes are Vanilla, Heliotrope and Cedar.',
        3.75,
        4,
        NULL
      ),
(
        'Fraise-des-Bois-30487',
        'Fraise des Bois Les Petits Plaisirs',
        'Fraise',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet',
        'Fraise des BoisbyLes Petits Plaisirsis a Aromatic Fruity fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'Fraise-Litchi-14340',
        'Fraise Litchi Les Petits Plaisirs',
        'Fraise',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,tropical,sweet,fresh',
        'Fraise LitchibyLes Petits Plaisirsis a Floral Fruity fragrance for women.Fraise Litchiwas launched in 2008.',
        4,
        3,
        NULL
      ),
(
        'Marshmallow-30489',
        'Marshmallow Les Petits Plaisirs',
        'Marshmallow',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,musky,powdery,caramel,sweet',
        'MarshmallowbyLes Petits Plaisirsis a Floral Fruity Gourmand fragrance for women.',
        4.45,
        11,
        NULL
      ),
(
        'Muguet-30483',
        'Muguet Les Petits Plaisirs',
        'Muguet',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,fresh,green,soapy',
        'MuguetbyLes Petits Plaisirsis a Floral fragrance for women.',
        5,
        3,
        NULL
      ),
(
        'Mure-Mystique-8155',
        'Mure Mystique Les Petits Plaisirs',
        'Mure',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,woody,powdery,floral,musky',
        'Mure MystiquebyLes Petits Plaisirsis a Floral Fruity fragrance for women.Mure Mystiquewas launched in 2008.',
        4.2,
        5,
        NULL
      ),
(
        'Patchouli-30486',
        'Patchouli Les Petits Plaisirs',
        'Patchouli',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'patchouli,woody,warm spicy,earthy,balsamic',
        'PatchoulibyLes Petits Plaisirsis a Woody Aromatic fragrance for women.',
        3.8,
        10,
        NULL
      ),
(
        'Patchouli-Envoutant-8154',
        'Patchouli Envoutant Les Petits Plaisirs',
        'Patchouli',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'patchouli,warm spicy,amber,chocolate,woody',
        'Patchouli EnvoutantbyLes Petits Plaisirsis a Amber Vanilla fragrance for women.Patchouli Envoutantwas launched in 2008.',
        4.5,
        10,
        NULL
      ),
(
        'Vanille-Ambre-56130',
        'Vanille & Ambre Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Tonka Bean',
        'Musk',
        'Vanilla',
        'vanilla,sweet,amber,powdery',
        'Vanille & AmbrebyLes Petits Plaisirsis a Amber fragrance for women. Top note is Tonka Bean; middle note is Musk; base note is Vanilla.',
        3.88,
        8,
        NULL
      ),
(
        'Vanille-Santal-56132',
        'Vanille & Santal Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Tea',
        'Sandalwood',
        'Vanilla and Musk',
        'vanilla,woody,powdery,warm spicy,balsamic',
        'Vanille & SantalbyLes Petits Plaisirsis a Amber Woody fragrance for women. Top note is Tea; middle note is Sandalwood; base notes are Vanilla and Musk.',
        4,
        4,
        NULL
      ),
(
        'Vanille-Ylang-56131',
        'Vanille & Ylang Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Ylang-Ylang',
        'Tahitian Vanilla',
        'vanilla,yellow floral,sweet,woody,citrus',
        'Vanille & YlangbyLes Petits Plaisirsis a Amber Floral fragrance for women. Top note is Bergamot; middle note is Ylang-Ylang; base note is Tahitian Vanilla.',
        4.25,
        4,
        NULL
      ),
(
        'Vanille-Cassis-14341',
        'Vanille Cassis Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,fruity,soft spicy,powdery,woody',
        'Vanille CassisbyLes Petits Plaisirsis a Amber Vanilla fragrance for women.Vanille Cassiswas launched in 2008.',
        4.5,
        4,
        NULL
      ),
(
        'Vanille-Framboise-30492',
        'Vanille Framboise Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,vanilla,powdery,rose',
        'Vanille FramboisebyLes Petits Plaisirsis a Floral Fruity fragrance for women.',
        3.73,
        33,
        NULL
      ),
(
        'Vanille-Gourmande-30490',
        'Vanille Gourmande Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,sweet',
        'Vanille GourmandebyLes Petits Plaisirsis a Amber Vanilla fragrance for women.',
        3.84,
        37,
        NULL
      ),
(
        'Vanille-Monoi-30491',
        'Vanille Monoi Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,vanilla,sweet,fruity',
        'Vanille MonoibyLes Petits Plaisirsis a Amber Floral fragrance for women.',
        3.69,
        16,
        NULL
      ),
(
        'Vanille-Mure-30495',
        'Vanille Mure Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,vanilla,sweet,powdery',
        'Vanille MurebyLes Petits Plaisirsis a Aromatic Spicy fragrance for women.',
        3.83,
        6,
        NULL
      ),
(
        'Vanille-Troublante-8156',
        'Vanille Troublante Les Petits Plaisirs',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,patchouli,balsamic,powdery,woody',
        'Vanille TroublantebyLes Petits Plaisirsis a Amber Vanilla fragrance for women.Vanille Troublantewas launched in 2008.',
        4.6,
        5,
        NULL
      ),
(
        'Violette-Macaron-30484',
        'Violette Macaron Les Petits Plaisirs',
        'Violette',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,violet,powdery,almond,vanilla',
        'Violette MacaronbyLes Petits Plaisirsis a Floral Fruity Gourmand fragrance for women.',
        4,
        21,
        NULL
      ),
(
        'Carmel-Snow-39003',
        'Carmel Snow Libertin Louison Technique Indiscrete',
        'Carmel',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Peach, Fruits, Lime, Bergamot, Petitgrain and Orange Blossom',
        'Floral Notes, Green Grass, Violet, Lily-of-the-Valley and Saffron',
        'Sweet Notes, Dried Fruits, Musk, Amber, Cedar, Haitian Vetiver and Woody Notes',
        'fruity,sweet,musky,powdery',
        'Carmel SnowbyLibertin Louison Technique Indiscreteis a Floral Fruity Gourmand fragrance for women and men.Carmel Snowwas launched in 2015. The nose behind this fragrance is Libertin Louison. Top notes are Peach, Fruits, Lime, Bergamot, Petitgrain and Orange Blossom; middle notes are Floral Notes, Green Grass, Violet, Lily-of-the-Valley and Saffron; base notes are Sweet Notes, Dried Fruits, Musk, Amber, Cedar, Haitian Vetiver and Woody Notes.',
        3.43,
        21,
        NULL
      ),
(
        'Centenaire-46592',
        'Centenaire Libertin Louison Technique Indiscrete',
        'Centenaire',
        'for women and men',
        NULL,
        'Libertin Louison',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy',
        'CentenairebyLibertin Louison Technique Indiscreteis a Woody fragrance for women and men.Centenairewas launched in 2017. The nose behind this fragrance is Libertin Louison.',
        3.07,
        14,
        NULL
      ),
(
        'Delivre-Moi-11287',
        'Delivre Moi Libertin Louison Technique Indiscrete',
        'Delivre',
        'for women',
        NULL,
        'Libertin Louison',
        'Eucalyptus and Anise',
        'Heliotrope, Geranium and Jasmine',
        'White Honey, Almond, Cypress and Musk',
        'honey,sweet,woody,almond,floral',
        'Delivre MoibyLibertin Louison Technique Indiscreteis a Aromatic Spicy fragrance for women.Delivre Moiwas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Eucalyptus and Anise; middle notes are Heliotrope, Geranium and Jasmine; base notes are White Honey, Almond, Cypress and Musk.',
        3.74,
        54,
        NULL
      ),
(
        'Eau-d-Anvers-39004',
        'Eau d''Anvers Libertin Louison Technique Indiscrete',
        'Eau',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Orange Blossom and Apple Blossom',
        'Honey, Rose, Indonesian Patchouli Leaf, Tobacco and Spices',
        'Myrrh, Spanish Labdanum, Madagascar Vanilla and Musk',
        'sweet,amber,warm spicy,honey,floral',
        'Eau d''AnversbyLibertin Louison Technique Indiscreteis a Amber Floral fragrance for women and men. The nose behind this fragrance is Libertin Louison. Top notes are Orange Blossom and Apple Blossom; middle notes are Honey, Rose, Indonesian Patchouli Leaf, Tobacco and Spices; base notes are Myrrh, Spanish Labdanum, Madagascar Vanilla and Musk.',
        3.5,
        14,
        NULL
      ),
(
        'Eau-de-Bruxelles-39005',
        'Eau de Bruxelles Libertin Louison Technique Indiscrete',
        'Eau',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Peach, Calabrian bergamot and Sicilian Lemon',
        'Peach, Apple, Cinnamon and Black Pepper',
        'Leather, Patchouli, Cedar and Vetiver',
        'woody,leather,patchouli,warm spicy,animalic',
        'Eau de BruxellesbyLibertin Louison Technique Indiscreteis a Aromatic Fruity fragrance for women and men. The nose behind this fragrance is Libertin Louison. Top notes are Peach, Calabrian bergamot and Sicilian Lemon; middle notes are Peach, Apple, Cinnamon and Black Pepper; base notes are Leather, Patchouli, Cedar and Vetiver.',
        3.41,
        22,
        NULL
      ),
(
        'Figure-Libre-39007',
        'Figure Libre Libertin Louison Technique Indiscrete',
        'Figure',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Bergamot and Lemon',
        'Jasmine, Rose and Violet',
        'Ambrette (Musk Mallow), Musk, Patchouli, Vanilla, Vetiver and Civet',
        'citrus,woody,floral,aromatic,powdery',
        'Figure LibrebyLibertin Louison Technique Indiscreteis a Floral fragrance for women and men. The nose behind this fragrance is Libertin Louison. Top notes are Bergamot and Lemon; middle notes are Jasmine, Rose and Violet; base notes are Ambrette (Musk Mallow), Musk, Patchouli, Vanilla, Vetiver and Civet.',
        2.33,
        6,
        NULL
      ),
(
        'Fleur-de-Papier-46593',
        'Fleur de Papier Libertin Louison Technique Indiscrete',
        'Fleur',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Orange Blossom and Floral Notes',
        'Carnation, Clove, Spices, Rose and Jasmine',
        'Benzoin, Vanilla, Woody Notes and Cedar',
        'warm spicy,floral,white floral,woody,vanilla',
        'Fleur de PapierbyLibertin Louison Technique Indiscreteis a Floral fragrance for women and men.Fleur de Papierwas launched in 2017. The nose behind this fragrance is Libertin Louison. Top notes are Orange Blossom and Floral Notes; middle notes are Carnation, Clove, Spices, Rose and Jasmine; base notes are Benzoin, Vanilla, Woody Notes and Cedar.',
        3.89,
        19,
        NULL
      ),
(
        'Forever-Amber-39008',
        'Forever Amber Libertin Louison Technique Indiscrete',
        'Forever',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Bergamot and Orange Blossom',
        'Apple and Jasmine',
        'Amber, Incense, Patchouli, Tonka Bean, Vanilla and White Musk',
        'amber,white floral,vanilla,citrus,warm spicy',
        'Forever AmberbyLibertin Louison Technique Indiscreteis a Amber fragrance for women and men. The nose behind this fragrance is Libertin Louison. Top notes are Bergamot and Orange Blossom; middle notes are Apple and Jasmine; base notes are Amber, Incense, Patchouli, Tonka Bean, Vanilla and White Musk.',
        3.65,
        17,
        NULL
      ),
(
        'Gravitations-39009',
        'Gravitations Libertin Louison Technique Indiscrete',
        'Gravitations',
        'for women and men',
        NULL,
        'Libertin Louison',
        NULL,
        NULL,
        NULL,
        NULL,
        'GravitationsbyLibertin Louison Technique Indiscreteis a fragrance for women and men.Gravitationswas launched in 2016. The nose behind this fragrance is Libertin Louison.',
        2,
        4,
        NULL
      ),
(
        'Indiscrete-11281',
        'Indiscrete Libertin Louison Technique Indiscrete',
        'Indiscrete',
        'for women',
        NULL,
        'Libertin Louison',
        'Fruity Notes, Mandarin Orange and Bergamot',
        'Jasmine, Tuberose and Rose',
        'Caramel, Vanille, oak moss, Musk and Woodsy Notes',
        'citrus,white floral,fruity,sweet,caramel',
        'IndiscretebyLibertin Louison Technique Indiscreteis a Chypre Floral fragrance for women.Indiscretewas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Fruity Notes, Mandarin Orange and Bergamot; middle notes are Jasmine, Tuberose and Rose; base notes are Caramel, Vanille, oak moss, Musk and Woodsy Notes.',
        3.59,
        41,
        NULL
      ),
(
        'Jerusalem-62947',
        'Jérusalem Libertin Louison Technique Indiscrete',
        'Jérusalem',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Bergamot and Orange',
        'Cedar, Geranium, Patchouli, Sandalwood, Star Anise, Lavender and Clove',
        'Olive Tree, Woody Notes, Benzoin, Smoke, Moss, Vanilla and Musk',
        'woody,citrus,warm spicy,aromatic,fresh spicy',
        'JérusalembyLibertin Louison Technique Indiscreteis a Woody Spicy fragrance for women and men.Jérusalemwas launched in 2017. Top notes are Lemon, Bergamot and Orange; middle notes are Cedar, Geranium, Patchouli, Sandalwood, Star Anise, Lavender and Clove; base notes are Olive Tree, Woody Notes, Benzoin, Smoke, Moss, Vanilla and Musk.',
        4,
        3,
        NULL
      ),
(
        'Monarchy-13590',
        'Monarchy Libertin Louison Technique Indiscrete',
        'Monarchy',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Bergamot and Lemongrass',
        'Lavender, Clover, Cashmere Wood, Rose, Geranium and Lily-of-the-Valley',
        'Sandalwood, Vanille, Virginia Cedar, Coumarin, Amber, Woodsy Notes, Ambrette (Musk Mallow) and Musk',
        'woody,vanilla,aromatic,powdery,floral',
        'MonarchybyLibertin Louison Technique Indiscreteis a Amber Woody fragrance for women and men.Monarchywas launched in 2011. The nose behind this fragrance is Libertin Louison. Top notes are Bergamot and Lemongrass; middle notes are Lavender, Clover, Cashmere Wood, Rose, Geranium and Lily-of-the-Valley; base notes are Sandalwood, Vanille, Virginia Cedar, Coumarin, Amber, Woodsy Notes, Ambrette (Musk Mallow) and Musk.',
        3.67,
        42,
        NULL
      ),
(
        'My-Burning-Secret-13589',
        'My Burning Secret Libertin Louison Technique Indiscrete',
        'My',
        'for men',
        NULL,
        'Libertin Louison',
        'Sea Notes, Amalfi Lemon and Bergamot',
        'Lavender, Geranium and Green Notes',
        'Vetiver, Clove, Pine, Amber, Tonka Bean and Musk',
        'aromatic,fresh spicy,citrus,green,woody',
        'My Burning SecretbyLibertin Louison Technique Indiscreteis a Aromatic Fougere fragrance for men.My Burning Secretwas launched in 2011. The nose behind this fragrance is Libertin Louison. Top notes are Sea Notes, Amalfi Lemon and Bergamot; middle notes are Lavender, Geranium and Green Notes; base notes are Vetiver, Clove, Pine, Amber, Tonka Bean and Musk.',
        3.56,
        25,
        NULL
      ),
(
        'Omnipresence-39001',
        'Omnipresence Libertin Louison Technique Indiscrete',
        'Omnipresence',
        'for women and men',
        NULL,
        NULL,
        'Red Apple, Pear and Pineapple',
        'Lily-of-the-Valley, Iris and Floral Notes',
        'Musk, Cashmere Wood, Cedar and Vanilla',
        'fruity,sweet,fresh,white floral,iris',
        'OmnipresencebyLibertin Louison Technique Indiscreteis a Floral Woody Musk fragrance for women and men. Top notes are Red Apple, Pear and Pineapple; middle notes are Lily-of-the-Valley, Iris and Floral Notes; base notes are Musk, Cashmere Wood, Cedar and Vanilla.',
        3.5,
        18,
        NULL
      ),
(
        'Paname-Paname-11282',
        'Paname Paname Libertin Louison Technique Indiscrete',
        'Paname',
        'for women',
        NULL,
        'Libertin Louison',
        'Caraway, Bergamot and Mandarin Orange',
        'Red Apple, Cupcake, Lotus and Jasmine',
        'oak moss, Vetiver, Amber and Musk',
        'fresh spicy,citrus,aromatic,sweet,earthy',
        'Paname PanamebyLibertin Louison Technique Indiscreteis a Chypre Floral fragrance for women.Paname Panamewas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Caraway, Bergamot and Mandarin Orange; middle notes are Red Apple, Cupcake, Lotus and Jasmine; base notes are oak moss, Vetiver, Amber and Musk.',
        3.64,
        50,
        NULL
      ),
(
        'Plaisir-d-Amour-11283',
        'Plaisir d'' Amour Libertin Louison Technique Indiscrete',
        'Plaisir',
        'for women',
        NULL,
        'Libertin Louison',
        'Kumquat and Bergamot',
        'Lily-of-the-Valley, Rose, Jasmine and African Orange Flower',
        'oak moss, Musk, Patchouli and Vetiver',
        'citrus,white floral,earthy,mossy,woody',
        'Plaisir d'' AmourbyLibertin Louison Technique Indiscreteis a Chypre Floral fragrance for women.Plaisir d'' Amourwas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Kumquat and Bergamot; middle notes are Lily-of-the-Valley, Rose, Jasmine and African Orange Flower; base notes are oak moss, Musk, Patchouli and Vetiver.',
        4.06,
        36,
        NULL
      ),
(
        'Safran-Nobile-11286',
        'Safran Nobile Libertin Louison Technique Indiscrete',
        'Safran',
        'for women',
        NULL,
        'Libertin Louison',
        'Amalfi Lemon and Orange',
        'Saffron, Anise, Cardamom and Jasmine',
        'Vanille, Benzoin and Patchouli',
        'warm spicy,vanilla,anis,amber,soft spicy',
        'Safran NobilebyLibertin Louison Technique Indiscreteis a Amber Spicy fragrance for women.Safran Nobilewas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Amalfi Lemon and Orange; middle notes are Saffron, Anise, Cardamom and Jasmine; base notes are Vanille, Benzoin and Patchouli.',
        4.09,
        64,
        NULL
      ),
(
        'Sainte-Extase-39006',
        'Sainte Extase Libertin Louison Technique Indiscrete',
        'Sainte',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Green Notes and Wildflowers',
        'Clove and Spanish Labdanum',
        'Texas Cedar, Precious Woods, Oakmoss and Haitian Vetiver',
        'woody,warm spicy,earthy,green',
        'Sainte ExtasebyLibertin Louison Technique Indiscreteis a Aromatic fragrance for women and men. The nose behind this fragrance is Libertin Louison. Top notes are Green Notes and Wildflowers; middle notes are Clove and Spanish Labdanum; base notes are Texas Cedar, Precious Woods, Oakmoss and Haitian Vetiver.',
        3.14,
        7,
        NULL
      ),
(
        'Sanguis-Terrae-46594',
        'Sanguis Terrae Libertin Louison Technique Indiscrete',
        'Sanguis',
        'for women and men',
        NULL,
        'Libertin Louison',
        NULL,
        NULL,
        NULL,
        NULL,
        'Sanguis TerraebyLibertin Louison Technique Indiscreteis a fragrance for women and men.Sanguis Terraewas launched in 2017. The nose behind this fragrance is Libertin Louison.',
        3.57,
        14,
        NULL
      ),
(
        'Santa-Subita-11285',
        'Santa Subita Libertin Louison Technique Indiscrete',
        'Santa',
        'for women',
        NULL,
        'Libertin Louison',
        'Orange, Bergamot and Amalfi Lemon',
        'Patchouli, Sandalwood and Virginia Cedar',
        'Benzoin, Vanille, Musk and oak moss',
        'woody,warm spicy,patchouli,amber,vanilla',
        'Santa SubitabyLibertin Louison Technique Indiscreteis a Amber Woody fragrance for women.Santa Subitawas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Orange, Bergamot and Amalfi Lemon; middle notes are Patchouli, Sandalwood and Virginia Cedar; base notes are Benzoin, Vanille, Musk and oak moss.',
        3.96,
        45,
        NULL
      ),
(
        'Veloutine-11284',
        'Veloutine Libertin Louison Technique Indiscrete',
        'Veloutine',
        'for women',
        NULL,
        'Libertin Louison',
        'Violet Leaf and Red Berries',
        'Violet and Rose',
        'Leather and Musk',
        'violet,powdery,ozonic,leather,aquatic',
        'VeloutinebyLibertin Louison Technique Indiscreteis a Floral fragrance for women.Veloutinewas launched in 2008. The nose behind this fragrance is Libertin Louison. Top notes are Violet Leaf and Red Berries; middle notes are Violet and Rose; base notes are Leather and Musk.',
        3.8,
        49,
        NULL
      ),
(
        'Vert-de-Chypre-57629',
        'Vert de Chypre Libertin Louison Technique Indiscrete',
        'Vert',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Lemon and Bergamot',
        'Thyme, Petitgrain, Basil, Cardamom, Lavender, Herbal Notes and Flowers',
        'oak moss, Labdanum, Patchouli, Woody Notes and Atlas Cedar',
        'aromatic,citrus,fresh spicy,woody,green',
        'Vert de ChyprebyLibertin Louison Technique Indiscreteis a Chypre fragrance for women and men.Vert de Chyprewas launched in 2019. The nose behind this fragrance is Libertin Louison. Top notes are Lemon and Bergamot; middle notes are Thyme, Petitgrain, Basil, Cardamom, Lavender, Herbal Notes and Flowers; base notes are oak moss, Labdanum, Patchouli, Woody Notes and Atlas Cedar.',
        2.75,
        4,
        NULL
      ),
(
        'Vierges-Folles-39002',
        'Vierges Folles Libertin Louison Technique Indiscrete',
        'Vierges',
        'for women and men',
        NULL,
        'Libertin Louison',
        NULL,
        NULL,
        NULL,
        NULL,
        'Vierges FollesbyLibertin Louison Technique Indiscreteis a fragrance for women and men.Vierges Folleswas launched in 2015. The nose behind this fragrance is Libertin Louison.',
        2,
        2,
        NULL
      ),
(
        'Cedrat-672-52142',
        'Cedrat 672 Libertin Louison Technique Indiscrete',
        'Cedrat',
        'for women and men',
        NULL,
        'Libertin Louison',
        NULL,
        NULL,
        NULL,
        'citrus',
        'Cedrat 672byLibertin Louison Technique Indiscreteis a Citrus fragrance for women and men.Cedrat 672was launched in 2011. The nose behind this fragrance is Libertin Louison.',
        4.25,
        4,
        NULL
      ),
(
        'Lavandor-52143',
        'Lavandor Libertin Louison Technique Indiscrete',
        'Lavandor',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Italian Lemon and Sage',
        'Lavender and Floral Notes',
        'Musk, Woodsy Notes and Fern',
        'aromatic,musky,floral,woody,citrus',
        'LavandorbyLibertin Louison Technique Indiscreteis a fragrance for women and men. The nose behind this fragrance is Libertin Louison. Top notes are Italian Lemon and Sage; middle notes are Lavender and Floral Notes; base notes are Musk, Woodsy Notes and Fern.',
        3.5,
        4,
        NULL
      ),
(
        'Lonicera-52144',
        'Lonicera Libertin Louison Technique Indiscrete',
        'Lonicera',
        'for women and men',
        NULL,
        'Libertin Louison',
        'Petitgrain and Bergamot',
        'Jasmine, White Flowers and Rose',
        'Woody Notes and Almond',
        'white floral,citrus,woody,rose,almond',
        'LonicerabyLibertin Louison Technique Indiscreteis a Citrus Aromatic fragrance for women and men.Lonicerawas launched in 2011. The nose behind this fragrance is Libertin Louison. Top notes are Petitgrain and Bergamot; middle notes are Jasmine, White Flowers and Rose; base notes are Woody Notes and Almond.',
        2,
        1,
        NULL
      );
