
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Pink-Happiness-Delicate-Moments-8900',
        'Pink Happiness Delicate Moments Revlon',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Bamboo, Tea, Red Berries and Bergamot',
        'Cotton Candy, Jasmine, Lily and Freesia',
        'Mexican chocolate, Patchouli, Sandalwood, Vanille and Musk',
        'sweet,woody,powdery,caramel,warm spicy',
        'Pink Happiness Delicate MomentsbyRevlonis a Floral Fruity Gourmand fragrance for women. Top notes are Bamboo, Tea, Red Berries and Bergamot; middle notes are Cotton Candy, Jasmine, Lily and Freesia; base notes are Mexican chocolate, Patchouli, Sandalwood, Vanille and Musk.',
        4.14,
        28,
        NULL
      ),
(
        'Pink-Happiness-Little-Secrets-8899',
        'Pink Happiness Little Secrets Revlon',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Black Currant',
        'Jasmine, Cardamom and Rose',
        'Patchouli, Virginia Cedar and Guaiac Wood',
        'woody,warm spicy,patchouli,fruity,citrus',
        'Pink Happiness Little SecretsbyRevlonis a Floral Fruity fragrance for women. Top notes are Mandarin Orange and Black Currant; middle notes are Jasmine, Cardamom and Rose; base notes are Patchouli, Virginia Cedar and Guaiac Wood.',
        4.29,
        14,
        NULL
      ),
(
        'Pub-11496',
        'Pub Revlon',
        'Pub',
        'for men',
        NULL,
        NULL,
        'Geranium, Star Anise, Amalfi Lemon, Tarragon and Basil',
        'Heliotrope, Lavender and Lily-of-the-Valley',
        'Musk, Vanille, Sandalwood, Patchouli and oak moss',
        'powdery,vanilla,aromatic,musky,woody',
        'PubbyRevlonis a Woody Aromatic fragrance for men. Top notes are Geranium, Star Anise, Amalfi Lemon, Tarragon and Basil; middle notes are Heliotrope, Lavender and Lily-of-the-Valley; base notes are Musk, Vanille, Sandalwood, Patchouli and oak moss.',
        4,
        12,
        NULL
      ),
(
        'Reflections-8905',
        'Reflections Revlon',
        'Reflections',
        'for women',
        NULL,
        NULL,
        'Ylang-Ylang, Freesia and Pineapple',
        'Jasmine, Lily-of-the-Valley, Tuberose and Peach',
        'Patchouli, Musk, Almond and Sugar',
        'white floral,sweet,yellow floral,floral,woody',
        'ReflectionsbyRevlonis a Floral Fruity Gourmand fragrance for women.Reflectionswas launched during the 2000''s. Top notes are Ylang-Ylang, Freesia and Pineapple; middle notes are Jasmine, Lily-of-the-Valley, Tuberose and Peach; base notes are Patchouli, Musk, Almond and Sugar.',
        3.45,
        11,
        NULL
      ),
(
        'Reign-On-70661',
        'Reign On Revlon',
        'Reign',
        'for women',
        NULL,
        NULL,
        'Lemon and Bamboo Leaf',
        'Water Lily, Jasmine and Butterfly Orchid',
        'Musk, Salt, White Woods and Moss',
        'floral,woody,citrus,white floral,fresh',
        'Reign OnbyRevlonis a Floral fragrance for women.Reign Onwas launched in 2021. Top notes are Lemon and Bamboo Leaf; middle notes are Water Lily, Jasmine and Butterfly Orchid; base notes are Musk, Salt, White Woods and Moss.',
        3.25,
        12,
        NULL
      ),
(
        'Rhapsody-15722',
        'Rhapsody Revlon',
        'Rhapsody',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Peach and Pineapple',
        'Orchid, Lily and Tiare Flower',
        'Amber, Vanilla, Sandalwood and Cedar',
        'amber,white floral,powdery,woody,vanilla',
        'RhapsodybyRevlonis a Amber Floral fragrance for women.Rhapsodywas launched during the 2000''s. Top notes are Orange Blossom, Peach and Pineapple; middle notes are Orchid, Lily and Tiare Flower; base notes are Amber, Vanilla, Sandalwood and Cedar.',
        4,
        1,
        NULL
      ),
(
        'Rouge-de-Revlon-3140',
        'Rouge de Revlon Revlon',
        'Rouge',
        'for women',
        NULL,
        'Judith Cross',
        'Ylang-Ylang and Bergamot',
        'Gardenia, Red Peony, Violet, Rose and Lily-of-the-Valley',
        'Pink Pepper, Sandalwood, Cedar and Peach',
        'woody,floral,white floral,yellow floral,powdery',
        'Rouge de RevlonbyRevlonis a Floral Green fragrance for women.Rouge de Revlonwas launched in 2000. The nose behind this fragrance is Judith Cross. Top notes are Ylang-Ylang and Bergamot; middle notes are Gardenia, Red Peony, Violet, Rose and Lily-of-the-Valley; base notes are Pink Pepper, Sandalwood, Cedar and Peach.',
        4.02,
        57,
        NULL
      ),
(
        'Scoundrel-14143',
        'Scoundrel Revlon',
        'Scoundrel',
        'for women',
        NULL,
        NULL,
        'Aldehydes, Marigold, Artemisia, Bergamot, Pineapple and Mint',
        'Tuberose, Mimosa, Hyacinth, Jasmine, Peach, Rose, Lily-of-the-Valley and Cyclamen',
        'oak moss, Cypress, Raspberry, Musk and Virginia Cedar',
        'aromatic,floral,fresh spicy,sweet,white floral',
        'ScoundrelbyRevlonis a Amber Floral fragrance for women.Scoundrelwas launched in 1980. Top notes are Aldehydes, Marigold, Artemisia, Bergamot, Pineapple and Mint; middle notes are Tuberose, Mimosa, Hyacinth, Jasmine, Peach, Rose, Lily-of-the-Valley and Cyclamen; base notes are oak moss, Cypress, Raspberry, Musk and Virginia Cedar.',
        4.08,
        65,
        NULL
      ),
(
        'Scoundrel-Musk-14144',
        'Scoundrel Musk Revlon',
        'Scoundrel',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,musky,woody,powdery',
        'Scoundrel MuskbyRevlonis a Floral Woody Musk fragrance for women.Scoundrel Muskwas launched in 1985.',
        4,
        14,
        NULL
      ),
(
        'She-11988',
        'She Revlon',
        'She',
        'for women',
        NULL,
        NULL,
        'Champagne, Grapefruit, Ginger and Mandarin Orange',
        'Honeysuckle, Rose, Cyclamen, Cardamom and Magnolia',
        'Musk, Woodsy Notes and Sandalwood',
        'citrus,warm spicy,Champagne,floral,aldehydic',
        'ShebyRevlonis a Floral Woody Musk fragrance for women.Shewas launched in 1997. Top notes are Champagne, Grapefruit, Ginger and Mandarin Orange; middle notes are Honeysuckle, Rose, Cyclamen, Cardamom and Magnolia; base notes are Musk, Woodsy Notes and Sandalwood.',
        3.51,
        49,
        NULL
      ),
(
        'Simply-Enchanting-12316',
        'Simply Enchanting Revlon',
        'Simply',
        'for women',
        NULL,
        NULL,
        'Bergamot, Tangerine, Pineapple and Grapefruit',
        'Rose, Violet, Jasmine, Freesia and Neroli',
        'Amber, Sandalwood, Vanille, Patchouli and Musk',
        'powdery,woody,floral,rose,amber',
        'Simply EnchantingbyRevlonis a Floral Woody Musk fragrance for women.Simply Enchantingwas launched in 2009. Top notes are Bergamot, Tangerine, Pineapple and Grapefruit; middle notes are Rose, Violet, Jasmine, Freesia and Neroli; base notes are Amber, Sandalwood, Vanille, Patchouli and Musk.',
        4,
        13,
        NULL
      ),
(
        'Skinlights-11989',
        'Skinlights Revlon',
        'Skinlights',
        'for women',
        NULL,
        NULL,
        'Clementine, Lavender, Ginger, Bergamot, Holly and Cypress',
        'Sage, Osmanthus and Cyclamen',
        'Cardamom and Musk',
        'aromatic,citrus,floral,warm spicy,fresh spicy',
        'SkinlightsbyRevlonis a Citrus Aromatic fragrance for women.Skinlightswas launched in 2001. Top notes are Clementine, Lavender, Ginger, Bergamot, Holly and Cypress; middle notes are Sage, Osmanthus and Cyclamen; base notes are Cardamom and Musk.',
        3.92,
        12,
        NULL
      ),
(
        'Splendid-15608',
        'Splendid Revlon',
        'Splendid',
        'for women',
        NULL,
        NULL,
        'Peony, Black Pepper and Freesia',
        'Rose Oil, Red Berries and Ylang-Ylang',
        'Patchouli, Powdery Notes, Musk, Vanilla and Moss',
        'floral,rose,fresh,fruity,powdery',
        'SplendidbyRevlonis a Amber Floral fragrance for women.Splendidwas launched in 2012. Top notes are Peony, Black Pepper and Freesia; middle notes are Rose Oil, Red Berries and Ylang-Ylang; base notes are Patchouli, Powdery Notes, Musk, Vanilla and Moss.',
        4.21,
        19,
        NULL
      ),
(
        'Splendid-Life-31185',
        'Splendid Life Revlon',
        'Splendid',
        'for women',
        NULL,
        NULL,
        'Bergamot, Jasmine and Sweet Orange',
        'Magnolia, Gardenia, Orange Blossom and Ylang-Ylang',
        'Vanilla, Sandalwood, White Musk and Woody Notes',
        'citrus,white floral,woody,powdery,floral',
        'Splendid LifebyRevlonis a Floral fragrance for women.Splendid Lifewas launched in 2011. Top notes are Bergamot, Jasmine and Sweet Orange; middle notes are Magnolia, Gardenia, Orange Blossom and Ylang-Ylang; base notes are Vanilla, Sandalwood, White Musk and Woody Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'That-Man-20404',
        'That Man Revlon',
        'That',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Petitgrain and Lavender',
        'Geranium, Cedar, Carnation and Spices',
        'Oakmoss, Musk, Tonka Bean and Amber',
        'citrus,aromatic,warm spicy,fresh spicy,woody',
        'That ManbyRevlonis a Aromatic Fougere fragrance for men.That Manwas launched in 1958. Top notes are Bergamot, Lemon, Petitgrain and Lavender; middle notes are Geranium, Cedar, Carnation and Spices; base notes are Oakmoss, Musk, Tonka Bean and Amber.',
        4.42,
        31,
        NULL
      ),
(
        'Ultima-17404',
        'Ultima Revlon',
        'Ultima',
        'for women',
        NULL,
        NULL,
        'Spices, Aldehydes, Bergamot, Apple and Fruity Notes',
        'Cinnamon, Carnation, Pimento, Rose, Jasmine and Orchid',
        'Opoponax, Sandalwood, Civet, Amber, Benzoin, Patchouli and Vanilla',
        'warm spicy,amber,woody,balsamic,powdery',
        'UltimabyRevlonis a Amber Spicy fragrance for women.Ultimawas launched in 1961. Top notes are Spices, Aldehydes, Bergamot, Apple and Fruity Notes; middle notes are Cinnamon, Carnation, Pimento, Rose, Jasmine and Orchid; base notes are Opoponax, Sandalwood, Civet, Amber, Benzoin, Patchouli and Vanilla.',
        4.59,
        59,
        NULL
      ),
(
        'Unforgettable-8904',
        'Unforgettable Revlon',
        'Unforgettable',
        'for women',
        NULL,
        NULL,
        'African Orange Flower, Lily-of-the-Valley and Freesia',
        'Iris, Orris Root and Jasmine',
        'Amber and Musk',
        'white floral,iris,powdery,amber,musky',
        'UnforgettablebyRevlonis a Floral fragrance for women.Unforgettablewas launched in 1990. Top notes are African Orange Flower, Lily-of-the-Valley and Freesia; middle notes are Iris, Orris Root and Jasmine; base notes are Amber and Musk.',
        4.29,
        122,
        NULL
      ),
(
        'Whimsical-10669',
        'Whimsical Revlon',
        'Whimsical',
        'for women',
        NULL,
        NULL,
        'Violet Leaf, Geranium, Black Currant, Pepper and Mignonette',
        'Iris, Lily-of-the-Valley, Rose, Jasmine and Ylang-Ylang',
        'Musk, Amber, Vanille and Resin',
        'iris,white floral,powdery,floral,ozonic',
        'WhimsicalbyRevlonis a Floral Green fragrance for women.Whimsicalwas launched in 2005. Top notes are Violet Leaf, Geranium, Black Currant, Pepper and Mignonette; middle notes are Iris, Lily-of-the-Valley, Rose, Jasmine and Ylang-Ylang; base notes are Musk, Amber, Vanille and Resin.',
        3.82,
        11,
        NULL
      ),
(
        'Wild-Heart-12485',
        'Wild Heart Revlon',
        'Wild',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral',
        'Wild HeartbyRevlonis a Floral fragrance for women.Wild Heartwas launched in 1992.',
        3.57,
        21,
        NULL
      ),
(
        'Xia-Xiang-4600',
        'Xia Xiang Revlon',
        'Xia',
        'for women',
        NULL,
        NULL,
        'Tangerine, Bergamot and Amalfi Lemon',
        'Rose, Ylang-Ylang, African Orange Flower, Jasmine, Gardenia and Lily-of-the-Valley',
        'oak moss, Sandalwood, Chamomile, Patchouli, Peach, Tonka Bean, plum and Vanille',
        'white floral,woody,sweet,citrus,fruity',
        'Xia XiangbyRevlonis a Amber Floral fragrance for women.Xia Xiangwas launched in 1987. Top notes are Tangerine, Bergamot and Amalfi Lemon; middle notes are Rose, Ylang-Ylang, African Orange Flower, Jasmine, Gardenia and Lily-of-the-Valley; base notes are oak moss, Sandalwood, Chamomile, Patchouli, Peach, Tonka Bean, plum and Vanille.',
        4.42,
        202,
        NULL
      ),
(
        'Regia-1928-41015',
        'Regia 1928 Regia',
        'Regia',
        'for women',
        NULL,
        NULL,
        'Orange Blossom and Hyacinth',
        'Jasmine, Rose and Iris Flower',
        'Oakmoss, Patchouli, Sandalwood, Musk, Amber and Vanilla',
        'white floral,citrus,woody,powdery,floral',
        'Regia 1928byRegiais a Chypre Floral fragrance for women.Regia 1928was launched in 2015. Top notes are Orange Blossom and Hyacinth; middle notes are Jasmine, Rose and Iris Flower; base notes are Oakmoss, Patchouli, Sandalwood, Musk, Amber and Vanilla.',
        4.5,
        2,
        NULL
      ),
(
        'Ambre-Loup-14926',
        'Ambre Loup Rania J',
        'Ambre',
        'for women and men',
        NULL,
        'Rania Jouaneh',
        'Spices and Cloves',
        'Labdanum, Vanilla Absolute and Peru Balsam',
        'Guaiac Wood, Agarwood (Oud) and Cedar',
        'woody,amber,warm spicy,balsamic,vanilla',
        'Ambre LoupbyRania Jis a Amber Woody fragrance for women and men.Ambre Loupwas launched in 2012. The nose behind this fragrance is Rania Jouaneh. Top notes are Spices and Cloves; middle notes are Labdanum, Vanilla Absolute and Peru Balsam; base notes are Guaiac Wood, Agarwood (Oud) and Cedar.',
        4.37,
        906,
        NULL
      ),
(
        'Cuir-Andalou-37732',
        'Cuir Andalou Rania J',
        'Cuir',
        'for women and men',
        NULL,
        'Rania Jouaneh',
        NULL,
        NULL,
        NULL,
        'leather,woody,smoky,violet,powdery',
        'Cuir AndaloubyRania Jis a Leather fragrance for women and men.Cuir Andalouwas launched in 2016. The nose behind this fragrance is Rania Jouaneh.',
        4.03,
        178,
        NULL
      ),
(
        'Jasmin-Kama-18026',
        'Jasmin Kama Rania J',
        'Jasmin',
        'for women',
        NULL,
        'Rania Jouaneh',
        'Damask Rose and Bergamot',
        'Egyptian Jasmine',
        'Patchouli, Heliotrope, Musk, Sandalwood and Vanilla',
        'white floral,powdery,woody,vanilla,floral',
        'Jasmin KamabyRania Jis a Chypre Floral fragrance for women.Jasmin Kamawas launched in 2013. The nose behind this fragrance is Rania Jouaneh. Top notes are Damask Rose and Bergamot; middle note is Egyptian Jasmine; base notes are Patchouli, Heliotrope, Musk, Sandalwood and Vanilla.',
        4.01,
        224,
        NULL
      ),
(
        'Lavande-44-14928',
        'Lavande 44 Rania J',
        'Lavande',
        'for women and men',
        NULL,
        'Rania Jouaneh',
        'Petitgrain and Bergamot',
        'Lavender',
        'Tonka Bean, Vetiver, Patchouli, Labdanum, Agarwood (Oud) and Musk',
        'lavender,aromatic,woody,amber,fresh spicy',
        'Lavande 44byRania Jis a Aromatic Spicy fragrance for women and men.Lavande 44was launched in 2012. The nose behind this fragrance is Rania Jouaneh. Top notes are Petitgrain and Bergamot; middle note is Lavender; base notes are Tonka Bean, Vetiver, Patchouli, Labdanum, Agarwood (Oud) and Musk.',
        4.13,
        328,
        NULL
      ),
(
        'Musc-Moschus-54877',
        'Musc Moschus Rania J',
        'Musc',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,woody,vanilla,musky,fruity',
        'Musc MoschusbyRania Jis a fragrance for women and men.Musc Moschuswas launched in 2019.',
        4.24,
        204,
        NULL
      ),
(
        'Oud-Assam-18027',
        'Oud Assam Rania J',
        'Oud',
        'for women and men',
        NULL,
        'Rania Jouaneh',
        'Bitter Orange, Sweet Orange and Bergamot',
        'Indian Oud',
        'Olibanum, Vetiver, Tonka Bean, Cedar, Black Pepper and Musk',
        'oud,fresh spicy,woody,citrus,amber',
        'Oud AssambyRania Jis a Amber Woody fragrance for women and men.Oud Assamwas launched in 2013. The nose behind this fragrance is Rania Jouaneh. Top notes are Bitter Orange, Sweet Orange and Bergamot; middle note is Indian Oud; base notes are Olibanum, Vetiver, Tonka Bean, Cedar, Black Pepper and Musk.',
        4.03,
        327,
        NULL
      ),
(
        'Rose-Ishtar-14927',
        'Rose Ishtar Rania J',
        'Rose',
        'for women',
        NULL,
        'Rania Jouaneh',
        'Cassis and Bergamot',
        'Damask Rose and Bulgarian Rose',
        'Patchouli, Musk, Heliotrope, Sandalwood and Vanilla',
        'rose,woody,powdery,vanilla,floral',
        'Rose IshtarbyRania Jis a Amber Floral fragrance for women.Rose Ishtarwas launched in 2012. The nose behind this fragrance is Rania Jouaneh. Top notes are Cassis and Bergamot; middle notes are Damask Rose and Bulgarian Rose; base notes are Patchouli, Musk, Heliotrope, Sandalwood and Vanilla.',
        3.82,
        203,
        NULL
      ),
(
        'Shah-ryar-83767',
        'Shah''ryar Rania J',
        'Shah''ryar',
        'for women and men',
        NULL,
        'Rania Jouaneh',
        'Caramel, Osmanthus and Bergamot',
        'Plum and Labdanum',
        'Agarwood (Oud), Beeswax, Hay, Sandalwood, Vanilla, Vetiver, Cedar, Oakmoss and Musk',
        'fruity,woody,oud,sweet,caramel',
        'Shah''ryarbyRania Jis a Amber fragrance for women and men. This is a new fragrance.Shah''ryarwas launched in 2023. The nose behind this fragrance is Rania Jouaneh. Top notes are Caramel, Osmanthus and Bergamot; middle notes are Plum and Labdanum; base notes are Agarwood (Oud), Beeswax, Hay, Sandalwood, Vanilla, Vetiver, Cedar, Oakmoss and Musk.',
        4.2,
        56,
        NULL
      ),
(
        'T-Habanero-24664',
        'T. Habanero Rania J',
        'T.',
        'for women and men',
        NULL,
        'Rania Jouaneh',
        'Cardamom, Black Pepper and Pink Pepper',
        'Tobacco',
        'Agarwood (Oud), Myrhh, Leather, Incense and Sandalwood',
        'warm spicy,tobacco,oud,amber,sweet',
        'T. HabanerobyRania Jis a Amber Spicy fragrance for women and men.T. Habanerowas launched in 2014. The nose behind this fragrance is Rania Jouaneh. Top notes are Cardamom, Black Pepper and Pink Pepper; middle note is Tobacco; base notes are Agarwood (Oud), Myrhh, Leather, Incense and Sandalwood.',
        4,
        254,
        NULL
      ),
(
        '1101-23138',
        '1101 Queen B',
        '1101',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,citrus,fresh',
        '1101byQueen Bis a Amber Spicy fragrance for women and men.',
        4,
        1,
        NULL
      ),
(
        'A-Secret-B-23123',
        'A Secret B Queen B',
        'A',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,musky,amber,powdery,green',
        'A Secret BbyQueen Bis a Amber fragrance for women and men.',
        4,
        19,
        NULL
      ),
(
        'Absolute-Queen-B-44013',
        'Absolute Queen B Queen B',
        'Absolute',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Absolute Queen BbyQueen Bis a fragrance for women and men.Absolute Queen Bwas launched in 2015.',
        2,
        1,
        NULL
      ),
(
        'Amber-Blue-23130',
        'Amber Blue Queen B',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,fresh,woody,warm spicy',
        'Amber BluebyQueen Bis a Amber fragrance for women and men.Amber Bluewas launched in 2012.',
        3.87,
        15,
        NULL
      ),
(
        'Basha-Khan-23135',
        'Basha Khan Queen B',
        'Basha',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'patchouli,amber,musky,woody,green',
        'Basha KhanbyQueen Bis a Citrus Aromatic fragrance for women and men.Basha Khanwas launched in 2013.',
        4.75,
        4,
        NULL
      ),
(
        'Black-Apple-23129',
        'Black Apple Queen B',
        'Black',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,fresh,warm spicy,amber',
        'Black ApplebyQueen Bis a Amber Vanilla fragrance for women and men.',
        3.67,
        54,
        NULL
      ),
(
        'Black-Lilly-23128',
        'Black Lilly Queen B',
        'Black',
        'for women',
        NULL,
        NULL,
        'Mango, Fruity Notes, Peach, Apple and Red Berries',
        'Lily, Spicy Notes and Floral Notes',
        'Oriental notes',
        'fruity,white floral,warm spicy,sweet,tropical',
        'Black LillybyQueen Bis a Floral Fruity Gourmand fragrance for women. Top notes are Mango, Fruity Notes, Peach, Apple and Red Berries; middle notes are Lily, Spicy Notes and Floral Notes; base note is Oriental notes.',
        3.87,
        53,
        NULL
      ),
(
        'Corc-Groseille-23127',
        'Corc Groseille Queen B',
        'Corc',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy',
        'Corc GroseillebyQueen Bis a Citrus fragrance for women and men.',
        3.67,
        3,
        NULL
      ),
(
        'Dark-Moscow-23142',
        'Dark Moscow Queen B',
        'Dark',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,warm spicy,smoky,woody,fruity',
        'Dark MoscowbyQueen Bis a Amber fragrance for women and men.',
        2.5,
        4,
        NULL
      ),
(
        'Desert-Liwa-23141',
        'Desert Liwa Queen B',
        'Desert',
        'for women and men',
        NULL,
        NULL,
        'Blackberry and Fruits',
        'Peony, Fruity Notes and Rose',
        'Amber, Resins, Spicy Notes and Powdery Notes',
        'amber,fruity,floral,rose,fresh',
        'Desert LiwabyQueen Bis a fragrance for women and men. Top notes are Blackberry and Fruits; middle notes are Peony, Fruity Notes and Rose; base notes are Amber, Resins, Spicy Notes and Powdery Notes.',
        4.5,
        2,
        NULL
      ),
(
        'Follow-Me-44008',
        'Follow Me Queen B',
        'Follow',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,floral,fresh spicy,aromatic,rose',
        'Follow MebyQueen Bis a Aromatic Spicy fragrance for women and men.Follow Mewas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'French-Mastic-23126',
        'French Mastic Queen B',
        'French',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'balsamic,tobacco,woody,patchouli,aromatic',
        'French MasticbyQueen Bis a Amber fragrance for women and men.',
        4.67,
        3,
        NULL
      ),
(
        'Gray-Oud-23133',
        'Gray Oud Queen B',
        'Gray',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Citruses',
        'Agarwood (Oud), Leather, Spicy Notes and Jasmine',
        'Patchouli, Oriental notes, Musk and Vanilla',
        'warm spicy,oud,patchouli,leather,musky',
        'Gray OudbyQueen Bis a Amber Woody fragrance for women and men. Top notes are Bergamot and Citruses; middle notes are Agarwood (Oud), Leather, Spicy Notes and Jasmine; base notes are Patchouli, Oriental notes, Musk and Vanilla.',
        4.2,
        5,
        NULL
      ),
(
        'Lady-Wag-Wag-23140',
        'Lady Wag Wag Queen B',
        'Lady',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,warm spicy,amber,floral,fresh',
        'Lady Wag WagbyQueen Bis a Amber Floral fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Last-Night-in-Paris-44010',
        'Last Night in Paris Queen B',
        'Last',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Last Night in ParisbyQueen Bis a fragrance for women and men.Last Night in Pariswas launched in 2015.',
        NULL,
        NULL,
        NULL
      ),
(
        'Lucky-44006',
        'Lucky Queen B',
        'Lucky',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,warm spicy,woody,amber,musky',
        'LuckybyQueen Bis a Floral fragrance for women and men.Luckywas launched in 2015.',
        4,
        1,
        NULL
      ),
(
        'M-Leather-23122',
        'M Leather Queen B',
        'M',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tobacco,leather,sweet,vanilla,animalic',
        'M LeatherbyQueen Bis a Amber Woody fragrance for women and men.M Leatherwas launched in 2012.',
        3.75,
        8,
        NULL
      ),
(
        'Meli-Melo-23131',
        'Meli Melo Queen B',
        'Meli',
        'for women and men',
        NULL,
        NULL,
        'Orange, Mandarin Orange, Lemon, Grapefruit and Bergamot',
        'Orange Blossom, Citruses, Lime and Herbal Notes',
        'Oriental notes and Spicy Notes',
        'citrus,warm spicy,amber,white floral,sweet',
        'Meli MelobyQueen Bis a Citrus Aromatic fragrance for women and men. Top notes are Orange, Mandarin Orange, Lemon, Grapefruit and Bergamot; middle notes are Orange Blossom, Citruses, Lime and Herbal Notes; base notes are Oriental notes and Spicy Notes.',
        3.6,
        10,
        NULL
      ),
(
        'Midnight-Blue-44007',
        'Midnight Blue Queen B',
        'Midnight',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes',
        'Oriental notes and Spicy Notes',
        'Powdery Notes',
        'warm spicy,floral,powdery,amber',
        'Midnight BluebyQueen Bis a Amber Floral fragrance for women and men.Midnight Bluewas launched in 2014. Top note is Floral Notes; middle notes are Oriental notes and Spicy Notes; base note is Powdery Notes.',
        1,
        1,
        NULL
      ),
(
        'Midnight-Oud-23121',
        'Midnight Oud Queen B',
        'Midnight',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,rose,patchouli,musky,woody',
        'Midnight OudbyQueen Bis a Amber fragrance for women and men.',
        4,
        4,
        NULL
      ),
(
        'Moon-Raker-23139',
        'Moon Raker Queen B',
        'Moon',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Floral Notes, Green Leaves and Spicy Notes',
        'Amber, Musk, Resins and Woody Notes',
        'amber,woody,citrus,floral,green',
        'Moon RakerbyQueen Bis a fragrance for women and men. Top note is Citruses; middle notes are Floral Notes, Green Leaves and Spicy Notes; base notes are Amber, Musk, Resins and Woody Notes.',
        5,
        1,
        NULL
      ),
(
        'Not-Tonight-44012',
        'Not Tonight Queen B',
        'Not',
        'for women and men',
        NULL,
        NULL,
        'Pear',
        'Rose',
        'Musk and Agarwood (Oud)',
        'musky,oud,rose,fruity,sweet',
        'Not TonightbyQueen Bis a Floral Woody Musk fragrance for women and men. Top note is Pear; middle note is Rose; base notes are Musk and Agarwood (Oud).',
        5,
        2,
        NULL
      ),
(
        'Oud-Arab-London-44009',
        'Oud Arab London Queen B',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Oriental notes and Spicy Notes',
        'Rose',
        'Agarwood (Oud) and Woody Notes',
        'warm spicy,oud,rose,woody,amber',
        'Oud Arab LondonbyQueen Bis a Amber Woody fragrance for women and men.Oud Arab Londonwas launched in 2014. Top notes are Oriental notes and Spicy Notes; middle note is Rose; base notes are Agarwood (Oud) and Woody Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'Patchouli-23134',
        'Patchouli Queen B',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,patchouli,amber,woody,earthy',
        'PatchoulibyQueen Bis a Amber Woody fragrance for women and men.',
        4.17,
        6,
        NULL
      ),
(
        'Pouder-d-Oeillet-44004',
        'Pouder d''Oeillet Queen B',
        'Pouder',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,musky',
        'Pouder d''OeilletbyQueen Bis a Aromatic fragrance for women and men.Pouder d''Oeilletwas launched in 2015.',
        3.33,
        3,
        NULL
      ),
(
        'Queen-B-23124',
        'Queen B Queen B',
        'Queen',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,powdery,amber,vanilla',
        'Queen BbyQueen Bis a Amber Vanilla fragrance for women.',
        4.22,
        37,
        NULL
      ),
(
        'Rainbow-Orchid-44011',
        'Rainbow Orchid Queen B',
        'Rainbow',
        'for women and men',
        NULL,
        NULL,
        'Saffron',
        'Floral Notes',
        'Musk and Agarwood (Oud)',
        'musky,oud,floral,powdery,warm spicy',
        'Rainbow OrchidbyQueen Bis a Floral Woody Musk fragrance for women and men. Top note is Saffron; middle note is Floral Notes; base notes are Musk and Agarwood (Oud).',
        NULL,
        NULL,
        NULL
      ),
(
        'Red-Death-44014',
        'Red Death Queen B',
        'Red',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,amber,musky,oud',
        'Red DeathbyQueen Bis a Woody fragrance for women and men.Red Deathwas launched in 2015.',
        1,
        1,
        NULL
      ),
(
        'Rose-23143',
        'Rose Queen B',
        'Rose',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,rose,woody,warm spicy,floral',
        'RosebyQueen Bis a Amber Floral fragrance for women.',
        3,
        3,
        NULL
      ),
(
        'Royalty-23125',
        'Royalty Queen B',
        'Royalty',
        'for women and men',
        NULL,
        NULL,
        'Vetiver',
        'Orris Root, Patchouli and Amber',
        'Woody Notes, Fruity Notes and Vanilla',
        'woody,earthy,fruity,iris,patchouli',
        'RoyaltybyQueen Bis a Amber fragrance for women and men. Top note is Vetiver; middle notes are Orris Root, Patchouli and Amber; base notes are Woody Notes, Fruity Notes and Vanilla.',
        3.62,
        8,
        NULL
      ),
(
        'So-Cool-44021',
        'So Cool Queen B',
        'So',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'So CoolbyQueen Bis a fragrance for women and men.So Coolwas launched in 2015.',
        NULL,
        NULL,
        NULL
      ),
(
        'Spirit-Oud-23145',
        'Spirit Oud Queen B',
        'Spirit',
        'for women and men',
        NULL,
        NULL,
        'Rose, Floral Notes and Woody Notes',
        'Jasmine, Saffron and Woody Notes',
        'Cedar and Musk',
        'floral,rose,woody,musky,white floral',
        'Spirit OudbyQueen Bis a Floral Woody Musk fragrance for women and men.Spirit Oudwas launched in 2014. Top notes are Rose, Floral Notes and Woody Notes; middle notes are Jasmine, Saffron and Woody Notes; base notes are Cedar and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sultan-Desire-23132',
        'Sultan Desire Queen B',
        'Sultan',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,patchouli,tobacco,musky,woody',
        'Sultan DesirebyQueen Bis a Amber fragrance for men.Sultan Desirewas launched in 2012.',
        4,
        5,
        NULL
      ),
(
        'Taif-23144',
        'Taif Queen B',
        'Taif',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,leather,rose,warm spicy,woody',
        'TaifbyQueen Bis a Amber fragrance for women and men.',
        2,
        1,
        NULL
      ),
(
        'Thanoon-44005',
        'Thanoon Queen B',
        'Thanoon',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'leather,warm spicy,animalic,fresh spicy,smoky',
        'ThanoonbyQueen Bis a Amber Spicy fragrance for women and men.Thanoonwas launched in 2015.',
        4,
        2,
        NULL
      ),
(
        'Tora-Bora-23137',
        'Tora Bora Queen B',
        'Tora',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tropical,floral,fruity,warm spicy,amber',
        'Tora BorabyQueen Bis a Amber Vanilla fragrance for women and men.',
        3.8,
        5,
        NULL
      ),
(
        'Noble-George-86909',
        'Noble George Privezarah',
        'Noble',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,vanilla,warm spicy,woody,sweet',
        'Noble GeorgebyPrivezarahis a Amber fragrance for men.Noble Georgewas launched in 2020.',
        3.75,
        12,
        NULL
      ),
(
        'Ombre-de-Louis-86907',
        'Ombre de Louis Privezarah',
        'Ombre',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,rose,fruity,oud,amber',
        'Ombre de LouisbyPrivezarahis a Woody Spicy fragrance for men.Ombre de Louiswas launched in 2020.',
        4,
        9,
        NULL
      ),
(
        'Superior-86908',
        'Superior Privezarah',
        'Superior',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,fresh spicy,aromatic,musky',
        'SuperiorbyPrivezarahis a Aromatic Spicy fragrance for men.Superiorwas launched in 2020.',
        3.67,
        3,
        NULL
      ),
(
        'Why-86906',
        'Why Privezarah',
        'Why',
        'for men',
        NULL,
        NULL,
        'Apple, Bergamot and Ginger',
        'Juniper Berries, Sage and Geranium',
        'Olibanum, Vetiver, Cedar, Amber and Tonka',
        'aromatic,fresh spicy,woody,warm spicy,amber',
        'WhybyPrivezarahis a Aromatic Fougere fragrance for men.Whywas launched in 2020. Top notes are Apple, Bergamot and Ginger; middle notes are Juniper Berries, Sage and Geranium; base notes are Olibanum, Vetiver, Cedar, Amber and Tonka.',
        4.22,
        9,
        NULL
      ),
(
        'Amber-Night-86905',
        'Amber Night Privezarah',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit and Bergamot',
        'Rose and Pink Pepper',
        'Ambergris, Cedar, Guaiac Wood and Patchouli',
        'woody,amber,rose,animalic,citrus',
        'Amber NightbyPrivezarahis a Amber fragrance for women and men.Amber Nightwas launched in 2020. Top notes are Grapefruit and Bergamot; middle notes are Rose and Pink Pepper; base notes are Ambergris, Cedar, Guaiac Wood and Patchouli.',
        4.25,
        8,
        NULL
      ),
(
        'Aoud-Desert-86901',
        'Aoud Desert Privezarah',
        'Aoud',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,smoky',
        'Aoud DesertbyPrivezarahis a Aromatic fragrance for women and men.Aoud Desertwas launched in 2020.',
        4.5,
        6,
        NULL
      ),
(
        'Blend-Afgano-86900',
        'Blend Afgano Privezarah',
        'Blend',
        'for men',
        NULL,
        NULL,
        'cannabis and Green Notes',
        'Tobacco, Resins and Coffee',
        'Oud and Incense',
        'oud,amber,smoky,cannabis,aromatic',
        'Blend AfganobyPrivezarahis a Woody Aquatic fragrance for men.Blend Afganowas launched in 2020. Top notes are cannabis and Green Notes; middle notes are Tobacco, Resins and Coffee; base notes are Oud and Incense.',
        4.2,
        15,
        NULL
      ),
(
        'Bois-Dores-86903',
        'Bois Dorès Privezarah',
        'Bois',
        'for women and men',
        NULL,
        NULL,
        'Olibanum',
        'Orris, Patchouli and Myrrh',
        'Woody Notes, Honey, White Musk, Leather and Amber',
        'iris,woody,amber,powdery,earthy',
        'Bois DorèsbyPrivezarahis a Amber fragrance for women and men.Bois Dorèswas launched in 2020. Top note is Olibanum; middle notes are Orris, Patchouli and Myrrh; base notes are Woody Notes, Honey, White Musk, Leather and Amber.',
        4.75,
        4,
        NULL
      ),
(
        'Grey-Mountain-86902',
        'Grey Mountain Privezarah',
        'Grey',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit and Bergamot',
        'Orange Blossom, Jasmine, Rose, Ylang-Ylang and Strawberry',
        'Sandalwood, White Musk, Patchouli, Oakmoss, Cedar and Amber',
        'woody,citrus,white floral,sweet,powdery',
        'Grey MountainbyPrivezarahis a Amber Floral fragrance for women and men.Grey Mountainwas launched in 2020. Top notes are Grapefruit and Bergamot; middle notes are Orange Blossom, Jasmine, Rose, Ylang-Ylang and Strawberry; base notes are Sandalwood, White Musk, Patchouli, Oakmoss, Cedar and Amber.',
        4.44,
        9,
        NULL
      ),
(
        'Oud-Highness-86899',
        'Oud Highness Privezarah',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Labdanum',
        'Patchouli',
        'Sandalwood, Agarwood and Rose',
        'woody,amber,oud,patchouli,rose',
        'Oud HighnessbyPrivezarahis a Woody fragrance for women and men.Oud Highnesswas launched in 2020. Top note is Labdanum; middle note is Patchouli; base notes are Sandalwood, Agarwood and Rose.',
        3.43,
        7,
        NULL
      ),
(
        'Black-Edition-83677',
        'Black Edition Portus Cale',
        'Black',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Black EditionbyPortus Caleis a Amber Woody fragrance for men.',
        4.6,
        5,
        NULL
      ),
(
        'Gold-Blue-83678',
        'Gold & Blue Portus Cale',
        'Gold',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,soft spicy,musky,sweet',
        'Gold & BluebyPortus Caleis a Floral fragrance for women.',
        4.67,
        3,
        NULL
      ),
(
        'AM-PM-87145',
        'AM-PM Playboy',
        'AM-PM',
        'for men',
        NULL,
        'Paul Guerlain',
        'Lemon, Cardamom and Ginger',
        'Clary Sage, Cinnamon and Geranium',
        'Vanilla, Amber Xtreme and Patchouli',
        'aromatic,warm spicy,citrus,vanilla,soft spicy',
        'AM-PMbyPlayboyis a Woody Aquatic fragrance for men. This is a new fragrance.AM-PMwas launched in 2023. The nose behind this fragrance is Paul Guerlain. Top notes are Lemon, Cardamom and Ginger; middle notes are Clary Sage, Cinnamon and Geranium; base notes are Vanilla, Amber Xtreme and Patchouli.',
        3.9,
        10,
        NULL
      ),
(
        'Berlin-14102',
        'Berlin Playboy',
        'Berlin',
        'for men',
        NULL,
        'Lucas Sieuzac',
        'Gin, Orange and Spices',
        'Red Apple, Cranberry and Geranium',
        'Sandalwood, Ambrette (Musk Mallow) and oak moss',
        'aromatic,woody,citrus,fruity,fresh spicy',
        'BerlinbyPlayboyis a Aromatic Fruity fragrance for men.Berlinwas launched in 2012. Berlin was created by Lucas Sieuzac and Nathalie Feisthauer. Top notes are Gin, Orange and Spices; middle notes are Red Apple, Cranberry and Geranium; base notes are Sandalwood, Ambrette (Musk Mallow) and oak moss.',
        3.79,
        70,
        NULL
      ),
(
        'Endless-Night-For-Her-51276',
        'Endless Night For Her Playboy',
        'Endless',
        'for women',
        NULL,
        'Julien Rasquinet',
        'Champagne, Pink Pepper and Orange',
        'Artemisia, Rose and Orange Blossom',
        'Patchouli, Musk and Sandalwood',
        'herbal,Champagne,citrus,aldehydic,woody',
        'Endless Night For HerbyPlayboyis a Chypre Floral fragrance for women.Endless Night For Herwas launched in 2018. Endless Night For Her was created by Nicolas Beaulieu and Julien Rasquinet. Top notes are Champagne, Pink Pepper and Orange; middle notes are Artemisia, Rose and Orange Blossom; base notes are Patchouli, Musk and Sandalwood.',
        3.71,
        59,
        NULL
      ),
(
        'Endless-Night-For-Him-51277',
        'Endless Night For Him Playboy',
        'Endless',
        'for men',
        NULL,
        'Juliette Karagueuzoglou',
        'Guatemalan Cardamom, Saffron and Italian Lemon',
        'Cinnamon, Violet Leaf and Night Blooming Jasmine',
        'Leather, Patchouli and Virginia Cedar',
        'warm spicy,leather,woody,cinnamon,patchouli',
        'Endless Night For HimbyPlayboyis a Woody Spicy fragrance for men.Endless Night For Himwas launched in 2018. The nose behind this fragrance is Juliette Karagueuzoglou. Top notes are Guatemalan Cardamom, Saffron and Italian Lemon; middle notes are Cinnamon, Violet Leaf and Night Blooming Jasmine; base notes are Leather, Patchouli and Virginia Cedar.',
        3.82,
        72,
        NULL
      ),
(
        'Game-Changer-87150',
        'Game Changer Playboy',
        'Game',
        'for men',
        NULL,
        'Alexandra Monet',
        'Guatemalan Cardamom, Apple and Pink Pepper',
        'Lavender, Orange Blossom and Salt',
        'Vanilla, Indonesian Patchouli Leaf and Labdanum',
        'sweet,balsamic,citrus,fresh,warm spicy',
        'Game ChangerbyPlayboyis a Amber Floral fragrance for men. This is a new fragrance.Game Changerwas launched in 2023. The nose behind this fragrance is Alexandra Monet. Top notes are Guatemalan Cardamom, Apple and Pink Pepper; middle notes are Lavender, Orange Blossom and Salt; base notes are Vanilla, Indonesian Patchouli Leaf and Labdanum.',
        4.5,
        6,
        NULL
      ),
(
        'Goddess-Complex-87143',
        'Goddess Complex Playboy',
        'Goddess',
        'for women',
        NULL,
        'Alexandra Monet',
        'White Peach, Pear and Bergamot',
        'Peony, Pink Pepper and Lily of the Valley',
        'Indonesian Patchouli Leaf, Praline, Vanilla, Haitian Vetiver and Ambroxan',
        'sweet,fruity,fresh,floral,woody',
        'Goddess ComplexbyPlayboyis a Amber Vanilla fragrance for women. This is a new fragrance.Goddess Complexwas launched in 2023. The nose behind this fragrance is Alexandra Monet. Top notes are White Peach, Pear and Bergamot; middle notes are Peony, Pink Pepper and Lily of the Valley; base notes are Indonesian Patchouli Leaf, Praline, Vanilla, Haitian Vetiver and Ambroxan.',
        3.67,
        9,
        NULL
      ),
(
        'Golden-Era-87144',
        'Golden Era Playboy',
        'Golden',
        'for women and men',
        NULL,
        'Alexandra Monet',
        'Apricot, Kumquat and Salt',
        'Jasmine Sambac, Ylang Ylang and Coconut',
        'Vanilla, Musk and Tonka Bean',
        'vanilla,sweet,powdery,yellow floral,coconut',
        'Golden ErabyPlayboyis a Amber Floral fragrance for women and men. This is a new fragrance.Golden Erawas launched in 2023. The nose behind this fragrance is Alexandra Monet. Top notes are Apricot, Kumquat and Salt; middle notes are Jasmine Sambac, Ylang Ylang and Coconut; base notes are Vanilla, Musk and Tonka Bean.',
        4.67,
        3,
        NULL
      ),
(
        'Gravity-Zero-87155',
        'Gravity Zero Playboy',
        'Gravity',
        'for men',
        NULL,
        'Jean-Christophe Hérault',
        'Lemon, Violet Leaf and Apple',
        'Clary Sage and Geranium',
        'Cedar, Amber Xtreme and Musk',
        'aromatic,woody,fresh spicy,citrus,amber',
        'Gravity ZerobyPlayboyis a Amber Fougere fragrance for men. This is a new fragrance.Gravity Zerowas launched in 2023. The nose behind this fragrance is Jean-Christophe Hérault. Top notes are Lemon, Violet Leaf and Apple; middle notes are Clary Sage and Geranium; base notes are Cedar, Amber Xtreme and Musk.',
        5,
        3,
        NULL
      ),
(
        'Ibiza-7519',
        'Ibiza Playboy',
        'Ibiza',
        'for men',
        NULL,
        NULL,
        'Water Notes, Kiwi, Citruses and Red Berries',
        'Green Notes, Lavender, Artemisia and Tarragon',
        'Nutmeg, Suede, Black Tea and Woodsy Notes',
        'fresh,fruity,green,aquatic,fresh spicy',
        'IbizabyPlayboyis a Aromatic fragrance for men.Ibizawas launched in 2009. Top notes are Water Notes, Kiwi, Citruses and Red Berries; middle notes are Green Notes, Lavender, Artemisia and Tarragon; base notes are Nutmeg, Suede, Black Tea and Woodsy Notes.',
        3.88,
        98,
        NULL
      ),
(
        'Keep-it-Real-87139',
        'Keep it Real Playboy',
        'Keep',
        'for women',
        NULL,
        'Nelly Hachem-Ruiz',
        'Mandarin Orange, Blueberry and Bergamot',
        'Jasmine Sambac, Hibiscus and Peony',
        'Vanilla, Musk and Sandalwood',
        'floral,citrus,fruity,white floral,fresh',
        'Keep it RealbyPlayboyis a Floral Fruity fragrance for women. This is a new fragrance.Keep it Realwas launched in 2023. The nose behind this fragrance is Nelly Hachem-Ruiz. Top notes are Mandarin Orange, Blueberry and Bergamot; middle notes are Jasmine Sambac, Hibiscus and Peony; base notes are Vanilla, Musk and Sandalwood.',
        4,
        5,
        NULL
      ),
(
        'King-of-the-Game-39747',
        'King of the Game Playboy',
        'King',
        'for men',
        NULL,
        NULL,
        'Cardamom, Black Pepper and Lemon',
        'Granny Smith apple and Coffee',
        'Vanilla, Patchouli and Cedar',
        'warm spicy,fresh spicy,woody,aromatic,vanilla',
        'King of the GamebyPlayboyis a Aromatic Spicy fragrance for men.King of the Gamewas launched in 2016. Top notes are Cardamom, Black Pepper and Lemon; middle notes are Granny Smith apple and Coffee; base notes are Vanilla, Patchouli and Cedar.',
        3.8,
        88,
        NULL
      ),
(
        'London-12522',
        'London Playboy',
        'London',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Galbanum and Grapefruit',
        'Cinnamon, Anise, Saffron, Opoponax, Green Notes and Myrtle',
        'Cognac, Tonka Bean and Virginia Cedar',
        'warm spicy,woody,citrus,cinnamon,sweet',
        'LondonbyPlayboyis a Aromatic Spicy fragrance for men.Londonwas launched in 2011. Top notes are Mandarin Orange, Galbanum and Grapefruit; middle notes are Cinnamon, Anise, Saffron, Opoponax, Green Notes and Myrtle; base notes are Cognac, Tonka Bean and Virginia Cedar.',
        3.87,
        279,
        NULL
      ),
(
        'Make-The-Cover-For-Her-61170',
        'Make The Cover For Her Playboy',
        'Make',
        'for women',
        NULL,
        NULL,
        'Peach, Pineapple and Bergamot',
        'Jasmine Sambac, Lily-of-the-Valley and Rose',
        'Sandalwood, Ambroxan and White Cedar Extract',
        'fruity,sweet,white floral,woody,fresh',
        'Make The Cover For HerbyPlayboyis a Floral Fruity fragrance for women.Make The Cover For Herwas launched in 2020. Top notes are Peach, Pineapple and Bergamot; middle notes are Jasmine Sambac, Lily-of-the-Valley and Rose; base notes are Sandalwood, Ambroxan and White Cedar Extract.',
        3.49,
        72,
        NULL
      ),
(
        'Make-The-Cover-For-Him-61171',
        'Make The Cover For Him Playboy',
        'Make',
        'for men',
        NULL,
        NULL,
        'Green Apple, Cardamom and Bergamot',
        'Lavender, Violet and Fruits',
        'Ambroxan, Woodsy Notes, Patchouli and Tonka Bean',
        'lavender,amber,aromatic,musky,fruity',
        'Make The Cover For HimbyPlayboyis a Amber Fougere fragrance for men.Make The Cover For Himwas launched in 2020. Top notes are Green Apple, Cardamom and Bergamot; middle notes are Lavender, Violet and Fruits; base notes are Ambroxan, Woodsy Notes, Patchouli and Tonka Bean.',
        3.87,
        54,
        NULL
      ),
(
        'My-Rules-87156',
        'My Rules Playboy',
        'My',
        'for men',
        NULL,
        'Coralie Spicher',
        'Black Pepper, Bergamot, Mint and Artemisia',
        'Lavender, Tonka Bean, Hazelnut, Clearwood and Salt',
        'Amberwood, Patchouli, Moss and Cashmere Wood',
        'amber,woody,warm spicy',
        'My RulesbyPlayboyis a Woody Aromatic fragrance for men. This is a new fragrance.My Ruleswas launched in 2023. The nose behind this fragrance is Coralie Spicher. Top notes are Black Pepper, Bergamot, Mint and Artemisia; middle notes are Lavender, Tonka Bean, Hazelnut, Clearwood and Salt; base notes are Amberwood, Patchouli, Moss and Cashmere Wood.',
        4.4,
        5,
        NULL
      ),
(
        'My-VIP-Story-For-Men-51275',
        'My VIP Story For Men Playboy',
        'My',
        'for men',
        NULL,
        NULL,
        'Lemongrass, Bergamot and Grapefruit',
        'Cedar Essence, Green Apple and Jasmine',
        'Amber, Leather and Musk',
        'citrus,fresh spicy,woody,aromatic,powdery',
        'My VIP Story For MenbyPlayboyis a Woody Aromatic fragrance for men.My VIP Story For Menwas launched in 2018. Top notes are Lemongrass, Bergamot and Grapefruit; middle notes are Cedar Essence, Green Apple and Jasmine; base notes are Amber, Leather and Musk.',
        3.5,
        22,
        NULL
      ),
(
        'Play-It-Lovely-10021',
        'Play It Lovely Playboy',
        'Play',
        'for women',
        NULL,
        NULL,
        'Blackberry, Citruses and Pear',
        'Orchid, Night blooming Cereus and Tuberose',
        'Tonka Bean, Amber and Patchouli',
        'fruity,sweet,white floral,citrus,amber',
        'Play It LovelybyPlayboyis a Floral Fruity fragrance for women.Play It Lovelywas launched in 2010. Top notes are Blackberry, Citruses and Pear; middle notes are Orchid, Night blooming Cereus and Tuberose; base notes are Tonka Bean, Amber and Patchouli.',
        3.8,
        637,
        NULL
      ),
(
        'Play-It-Pin-Up-17159',
        'Play It Pin Up Playboy',
        'Play',
        'for women',
        NULL,
        NULL,
        'Pineapple, Peach and Bergamot',
        'Cotton Candy, Wild Rose and Star Jasmine',
        'Praline, Patchouli, Sandalwood and Benzoin',
        'sweet,fruity,caramel',
        'Play It Pin UpbyPlayboyis a Floral Fruity Gourmand fragrance for women.Play It Pin Upwas launched in 2013. Top notes are Pineapple, Peach and Bergamot; middle notes are Cotton Candy, Wild Rose and Star Jasmine; base notes are Praline, Patchouli, Sandalwood and Benzoin.',
        3.84,
        205,
        NULL
      ),
(
        'Play-It-Pin-Up-2014-31488',
        'Play It Pin Up 2014 Playboy',
        'Play',
        'for women',
        NULL,
        NULL,
        'Poppy, Pear and Grapefruit',
        'Piña Colada, Strawberry and Orange Blossom',
        'Vanilla, Musk and Cedar',
        'fruity,sweet,coconut,vanilla,citrus',
        'Play It Pin Up 2014byPlayboyis a Floral Fruity Gourmand fragrance for women.Play It Pin Up 2014was launched in 2014. Top notes are Poppy, Pear and Grapefruit; middle notes are Piña Colada, Strawberry and Orange Blossom; base notes are Vanilla, Musk and Cedar.',
        3.76,
        68,
        NULL
      ),
(
        'Play-It-Rock-13004',
        'Play It Rock Playboy',
        'Play',
        'for women',
        NULL,
        'Guillaume Flavigny',
        'Blood Orange, Candy Apple and Saffron',
        'Passion Flower, Frangipani and African Orange Flower',
        'Vanilla, Patchouli, Ebony Wood and Leather',
        'fruity,floral,citrus,sweet,vanilla',
        'Play It RockbyPlayboyis a Amber Floral fragrance for women.Play It Rockwas launched in 2011. The nose behind this fragrance is Guillaume Flavigny. Top notes are Blood Orange, Candy Apple and Saffron; middle notes are Passion Flower, Frangipani and African Orange Flower; base notes are Vanilla, Patchouli, Ebony Wood and Leather.',
        3.96,
        426,
        NULL
      ),
(
        'Play-It-Sexy-10022',
        'Play It Sexy Playboy',
        'Play',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Mandarin Orange and Grapefruit',
        'Licorice, Jasmine and Osmanthus',
        'Vanille, Tonka Bean, Patchouli and Sandalwood',
        'vanilla,soft spicy,sweet,citrus,woody',
        'Play It SexybyPlayboyis a Amber Vanilla fragrance for women.Play It Sexywas launched in 2010. Top notes are Pink Pepper, Mandarin Orange and Grapefruit; middle notes are Licorice, Jasmine and Osmanthus; base notes are Vanille, Tonka Bean, Patchouli and Sandalwood.',
        3.73,
        785,
        NULL
      ),
(
        'Play-it-Sexy-2023-87142',
        'Play it Sexy (2023) Playboy',
        'Play',
        'for women',
        NULL,
        'Nathalie Lorson',
        'Grapefruit, Pink Pepper and Mandarin Orange',
        'Jasmine Tea, Osmanthus and Licorice',
        'Vanilla, Patchouli, Sandalwood and Tonka',
        'floral,soft spicy,woody,vanilla,fresh',
        'Play it Sexy (2023)byPlayboyis a Amber Vanilla fragrance for women. This is a new fragrance.Play it Sexy (2023)was launched in 2023. The nose behind this fragrance is Nathalie Lorson. Top notes are Grapefruit, Pink Pepper and Mandarin Orange; middle notes are Jasmine Tea, Osmanthus and Licorice; base notes are Vanilla, Patchouli, Sandalwood and Tonka.',
        4.14,
        7,
        NULL
      );
