
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Claudiae-13371',
        'Claudiae Sigilli',
        'Claudiae',
        'for women',
        NULL,
        'Enrico Buccella',
        'Tomato Leaf and Red Poppy',
        'Green Notes, Galbanum and Rose',
        'Patchouli and Musk',
        'green,aromatic,fresh spicy,patchouli,floral',
        'ClaudiaebySigilliis a Floral Green fragrance for women.Claudiaewas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top notes are Tomato Leaf and Red Poppy; middle notes are Green Notes, Galbanum and Rose; base notes are Patchouli and Musk.',
        3.88,
        17,
        NULL
      ),
(
        'Ea-13377',
        'Ea Sigilli',
        'Ea',
        'for women',
        NULL,
        'Enrico Buccella',
        'Water Lily, Narcissus and Quince',
        'Sea water, Water Notes and Orchid',
        'Patchouli and Musk',
        'aquatic,floral,marine,fresh,aromatic',
        'EabySigilliis a Floral Aquatic fragrance for women.Eawas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top notes are Water Lily, Narcissus and Quince; middle notes are Sea water, Water Notes and Orchid; base notes are Patchouli and Musk.',
        3.28,
        18,
        NULL
      ),
(
        'Electra-13378',
        'Electra Sigilli',
        'Electra',
        'for women and men',
        NULL,
        'Enrico Buccella',
        'Sage',
        'Benzoin, Leather, Amber and Woodsy Notes',
        'Incense, French labdanum, Patchouli and Musk',
        'amber,aromatic,herbal,warm spicy,smoky',
        'ElectrabySigilliis a Amber fragrance for women and men.Electrawas launched in 2011. The nose behind this fragrance is Enrico Buccella. Top note is Sage; middle notes are Benzoin, Leather, Amber and Woodsy Notes; base notes are Incense, French labdanum, Patchouli and Musk.',
        4.3,
        20,
        NULL
      ),
(
        'Ferfaen-13376',
        'Ferfaen Sigilli',
        'Ferfaen',
        'for women and men',
        NULL,
        'Enrico Buccella',
        'Lemon Verbena and Mint',
        'Tobacco',
        'Musk and Vanille',
        'citrus,green,aromatic,fresh spicy,herbal',
        'FerfaenbySigilliis a Citrus Aromatic fragrance for women and men.Ferfaenwas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top notes are Lemon Verbena and Mint; middle note is Tobacco; base notes are Musk and Vanille.',
        4,
        10,
        NULL
      ),
(
        'Hesperia-13375',
        'Hesperia Sigilli',
        'Hesperia',
        'for women and men',
        NULL,
        'Enrico Buccella',
        'Citruses',
        'Carnation, African Orange Flower, Bay Leaf and Violet',
        'Woodsy Notes',
        'citrus,fresh,white floral,woody,floral',
        'HesperiabySigilliis a Citrus Aromatic fragrance for women and men.Hesperiawas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top note is Citruses; middle notes are Carnation, African Orange Flower, Bay Leaf and Violet; base note is Woodsy Notes.',
        4.2,
        5,
        NULL
      ),
(
        'Hymba-14939',
        'Hymba Sigilli',
        'Hymba',
        'for women and men',
        NULL,
        'Enrico Buccella',
        'Myrtle and Citruses',
        'Resins and Vanilla',
        'Sandalwood, Cedar, Amber and Birch',
        'aromatic,amber,fresh spicy,herbal,citrus',
        'HymbabySigilliis a Amber fragrance for women and men.Hymbawas launched in 2012. The nose behind this fragrance is Enrico Buccella. Top notes are Myrtle and Citruses; middle notes are Resins and Vanilla; base notes are Sandalwood, Cedar, Amber and Birch.',
        4.09,
        22,
        NULL
      ),
(
        'Khanbaliq-24269',
        'Khanbaliq Sigilli',
        'Khanbaliq',
        'for women and men',
        NULL,
        NULL,
        'Coriander, Ginger, Cinnamon and Bitter Orange',
        'Peony, Pine Tree, Cloves, Fir and Plum',
        'Peony, Ambergris and Violet',
        'warm spicy,aromatic,fresh,woody,floral',
        'KhanbaliqbySigilliis a Amber fragrance for women and men.Khanbaliqwas launched in 2013. Top notes are Coriander, Ginger, Cinnamon and Bitter Orange; middle notes are Peony, Pine Tree, Cloves, Fir and Plum; base notes are Peony, Ambergris and Violet.',
        3.91,
        11,
        NULL
      ),
(
        'Pyrgos-13370',
        'Pyrgos Sigilli',
        'Pyrgos',
        'for men',
        NULL,
        'Enrico Buccella',
        'Watercress, Bergamot and Lavender',
        'Anise, Oregano and Cinnamon',
        'Spices',
        'fresh spicy,anis,soft spicy,aromatic,warm spicy',
        'PyrgosbySigilliis a Aromatic Spicy fragrance for men.Pyrgoswas launched during the 2011''s. The nose behind this fragrance is Enrico Buccella. Top notes are Watercress, Bergamot and Lavender; middle notes are Anise, Oregano and Cinnamon; base note is Spices.',
        3.59,
        17,
        NULL
      ),
(
        'Thu-13369',
        'Thu Sigilli',
        'Thu',
        'for men',
        NULL,
        'Enrico Buccella',
        'Anise and Lavender',
        'Sage, Galbanum and Green Notes',
        'Musk',
        'soft spicy,anis,aromatic,musky,green',
        'ThubySigilliis a Aromatic fragrance for men.Thuwas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top notes are Anise and Lavender; middle notes are Sage, Galbanum and Green Notes; base note is Musk.',
        4.75,
        4,
        NULL
      ),
(
        'Tuscia-13373',
        'Tuscia Sigilli',
        'Tuscia',
        'for women',
        NULL,
        'Enrico Buccella',
        'Spicy Notes',
        'Powdery Notes and Floral Notes',
        'Powdery Notes and Musk',
        'powdery,floral,musky,warm spicy',
        'TusciabySigilliis a Floral Woody Musk fragrance for women.Tusciawas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top note is Spicy Notes; middle notes are Powdery Notes and Floral Notes; base notes are Powdery Notes and Musk.',
        4.58,
        12,
        NULL
      ),
(
        'Tyrsenoi-13372',
        'Tyrsenoi Sigilli',
        'Tyrsenoi',
        'for men',
        NULL,
        'Enrico Buccella',
        'Sea water',
        'Tobacco, Red Poppy and Dyer’s Greenweed',
        'Green Notes and Musk',
        'marine,green,tobacco,sweet,musky',
        'TyrsenoibySigilliis a Aromatic Aquatic fragrance for men.Tyrsenoiwas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top note is Sea water; middle notes are Tobacco, Red Poppy and Dyer’s Greenweed; base notes are Green Notes and Musk.',
        3.25,
        4,
        NULL
      ),
(
        'Volumna-13368',
        'Volumna Sigilli',
        'Volumna',
        'for women',
        NULL,
        'Enrico Buccella',
        'Mango, Hibiscus and Black Currant',
        'Tuberose, Coconut, Almond, Red Poppy and Rose',
        'Vanille, Musk and Sandalwood',
        'fruity,sweet,floral,tropical,tuberose',
        'VolumnabySigilliis a Floral Fruity fragrance for women.Volumnawas launched during the 2000''s. The nose behind this fragrance is Enrico Buccella. Top notes are Mango, Hibiscus and Black Currant; middle notes are Tuberose, Coconut, Almond, Red Poppy and Rose; base notes are Vanille, Musk and Sandalwood.',
        4.02,
        42,
        NULL
      ),
(
        'Amber-19189',
        'Amber Six Scents',
        'Amber',
        'for women and men',
        NULL,
        'Darryl Do',
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,green,woody,amber',
        'AmberbySix Scentsis a Amber Fougere fragrance for women and men.Amberwas launched in 2011. The nose behind this fragrance is Darryl Do.',
        4.2,
        5,
        NULL
      ),
(
        'Six-Scents-1-Alexandre-Herchcovitch-Urban-Tropicalia-5173',
        'Six Scents 1 Alexandre Herchcovitch: Urban Tropicalia Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Joachim Correl',
        NULL,
        NULL,
        NULL,
        'fruity,aromatic,green,floral,fresh',
        'Six Scents 1 Alexandre Herchcovitch: Urban TropicaliabySix Scentsis a fragrance for women and men.Six Scents 1 Alexandre Herchcovitch: Urban Tropicaliawas launched in 2008. The nose behind this fragrance is Joachim Correl.',
        4.64,
        22,
        NULL
      ),
(
        'Six-Scents-2-Bernhard-Willhelm-Wicken-3000-5174',
        'Six Scents 2 Bernhard Willhelm: Wicken 3000 Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Symrise',
        NULL,
        NULL,
        NULL,
        'musky,marine,powdery,aromatic,salty',
        'Six Scents 2 Bernhard Willhelm: Wicken 3000bySix Scentsis a fragrance for women and men.Six Scents 2 Bernhard Willhelm: Wicken 3000was launched in 2008. The nose behind this fragrance is Symrise.',
        3.47,
        15,
        NULL
      ),
(
        'Six-Scents-3-Cosmic-Wonder-Spirit-of-Wood-5175',
        'Six Scents 3 Cosmic Wonder: Spirit of Wood Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Symrise',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy,green',
        'Six Scents 3 Cosmic Wonder: Spirit of WoodbySix Scentsis a fragrance for women and men.Six Scents 3 Cosmic Wonder: Spirit of Woodwas launched in 2008. The nose behind this fragrance is Symrise.',
        4.5,
        20,
        NULL
      ),
(
        'Six-Scents-4-Gareth-Pugh-Diagonal-5176',
        'Six Scents 4 Gareth Pugh: Diagonal Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Symrise',
        NULL,
        NULL,
        NULL,
        'fresh spicy,green,woody,musky,aromatic',
        'Six Scents 4 Gareth Pugh: DiagonalbySix Scentsis a fragrance for women and men.Six Scents 4 Gareth Pugh: Diagonalwas launched in 2008. The nose behind this fragrance is Symrise.',
        3.78,
        23,
        NULL
      ),
(
        'Six-Scents-5-Jeremy-Scott-Illicit-Sex-5177',
        'Six Scents 5 Jeremy Scott: Illicit Sex Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Philippe Roques',
        NULL,
        NULL,
        NULL,
        'rose,fresh spicy,aldehydic,woody,musky',
        'Six Scents 5 Jeremy Scott: Illicit SexbySix Scentsis a fragrance for women and men.Six Scents 5 Jeremy Scott: Illicit Sexwas launched in 2008. The nose behind this fragrance is Philippe Roques.',
        3.79,
        19,
        NULL
      ),
(
        'Six-Scents-6-Preen-Teen-Spirit-5178',
        'Six Scents 6 Preen: Teen Spirit Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Mark Buxton',
        'Calabrian bergamot, Magnolia, Turkish Rose and Sea Notes',
        'Rhubarb, Green Leaves, Hazelnut and Red Pepper',
        'Sandalwood, Musk and Violet Woodsorrel',
        'citrus,floral,green,aromatic,woody',
        'Six Scents 6 Preen: Teen SpiritbySix Scentsis a fragrance for women and men.Six Scents 6 Preen: Teen Spiritwas launched in 2008. The nose behind this fragrance is Mark Buxton. Top notes are Calabrian bergamot, Magnolia, Turkish Rose and Sea Notes; middle notes are Rhubarb, Green Leaves, Hazelnut and Red Pepper; base notes are Sandalwood, Musk and Violet Woodsorrel.',
        4.57,
        14,
        NULL
      ),
(
        'Six-Scents-Series-Two-1-3-1-Phillip-Lim-Collage-7006',
        'Six Scents Series Two 1 3.1 Phillip Lim: Collage Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Natalie Gracia-Cetto',
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,citrus,aromatic,warm spicy',
        'Six Scents Series Two 1 3.1 Phillip Lim: CollagebySix Scentsis a Woody Aromatic fragrance for women and men.Six Scents Series Two 1 3.1 Phillip Lim: Collagewas launched in 2009. The nose behind this fragrance is Natalie Gracia-Cetto.',
        4.17,
        6,
        NULL
      ),
(
        'Six-Scents-Series-Two-2-Damir-Doma-Ende-Anfang-7007',
        'Six Scents Series Two 2 Damir Doma: Ende / Anfang Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Yann Vasnier',
        NULL,
        NULL,
        NULL,
        'woody,amber,warm spicy,aromatic,balsamic',
        'Six Scents Series Two 2 Damir Doma: Ende / AnfangbySix Scentsis a Amber Woody fragrance for women and men.Six Scents Series Two 2 Damir Doma: Ende / Anfangwas launched in 2009. The nose behind this fragrance is Yann Vasnier.',
        4.24,
        25,
        NULL
      ),
(
        'Six-Scents-Series-Two-3-Henrik-Vibskov-Solar-Donkey-Power-7008',
        'Six Scents Series Two 3 Henrik Vibskov: Solar Donkey Power Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Louise Turner',
        NULL,
        NULL,
        NULL,
        'aromatic,woody,herbal,citrus,earthy',
        'Six Scents Series Two 3 Henrik Vibskov: Solar Donkey PowerbySix Scentsis a Chypre fragrance for women and men.Six Scents Series Two 3 Henrik Vibskov: Solar Donkey Powerwas launched in 2009. The nose behind this fragrance is Louise Turner.',
        3.92,
        12,
        NULL
      ),
(
        'Six-Scents-Series-Two-4-House-of-Holland-Smell-7009',
        'Six Scents Series Two 4 House of Holland: Smell Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Stephen Nilsen',
        NULL,
        NULL,
        NULL,
        'musky,woody,powdery,aromatic,yellow floral',
        'Six Scents Series Two 4 House of Holland: SmellbySix Scentsis a Floral Green fragrance for women and men.Six Scents Series Two 4 House of Holland: Smellwas launched in 2009. The nose behind this fragrance is Stephen Nilsen.',
        4.5,
        6,
        NULL
      ),
(
        'Six-Scents-Series-Two-5-Richard-Nicoll-Nicoll-17-7010',
        'Six Scents Series Two 5 Richard Nicoll: Nicoll 17 Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'fresh spicy,green,musky,aromatic,powdery',
        'Six Scents Series Two 5 Richard Nicoll: Nicoll 17bySix Scentsis a Aromatic Spicy fragrance for women and men.Six Scents Series Two 5 Richard Nicoll: Nicoll 17was launched in 2009. The nose behind this fragrance is Rodrigo Flores-Roux.',
        4.44,
        16,
        NULL
      ),
(
        'Six-Scents-Series-Two-6-Toga-Whiskey-Caramelise-7011',
        'Six Scents Series Two 6 Toga: Whiskey Caramelise Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Alexandra Kosinski',
        NULL,
        NULL,
        NULL,
        'fruity,citrus,patchouli,woody,fresh spicy',
        'Six Scents Series Two 6 Toga: Whiskey CaramelisebySix Scentsis a Aromatic Fruity fragrance for women and men.Six Scents Series Two 6 Toga: Whiskey Caramelisewas launched in 2009. The nose behind this fragrance is Alexandra Kosinski.',
        4.54,
        13,
        NULL
      ),
(
        'Six-Scents-Series-Three-1-Alex-Mabille-Beau-Bow-10600',
        'Six Scents Series Three 1 Alex Mabille: Beau Bow Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        'Bergamot, Citron, Basil, Violet Leaf, Lavender, Galbanum, Bitter Orange, Mint and Mandarin Orange',
        'Rose, Honeysuckle, Magnolia, Jasmine, Cyclamen and Mastic or Lentisque',
        'Vetiver, Kephalis, oak moss and Iris',
        'citrus,aromatic,fresh spicy,green,woody',
        'Six Scents Series Three 1 Alex Mabille: Beau BowbySix Scentsis a Chypre fragrance for women and men.Six Scents Series Three 1 Alex Mabille: Beau Bowwas launched in 2010. The nose behind this fragrance is Rodrigo Flores-Roux. Top notes are Bergamot, Citron, Basil, Violet Leaf, Lavender, Galbanum, Bitter Orange, Mint and Mandarin Orange; middle notes are Rose, Honeysuckle, Magnolia, Jasmine, Cyclamen and Mastic or Lentisque; base notes are Vetiver, Kephalis, oak moss and Iris.',
        3.86,
        22,
        NULL
      ),
(
        'Six-Scents-Series-Three-2-Mary-Katrantzou-Trompe-L-Oleil-10601',
        'Six Scents Series Three 2 Mary Katrantzou: Trompe L''Oleil Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Shyamala Maisondieu',
        'Neroli, Peach, Bitter Orange and Mandarin Orange',
        'Mimosa, Ylang-Ylang, Orris Root, Rose and Tuberose',
        'Tonka Bean, Amyris, Vanille and Ambrette (Musk Mallow)',
        'yellow floral,sweet,powdery,floral,vanilla',
        'Six Scents Series Three 2 Mary Katrantzou: Trompe L''OleilbySix Scentsis a Amber Floral fragrance for women and men.Six Scents Series Three 2 Mary Katrantzou: Trompe L''Oleilwas launched in 2010. The nose behind this fragrance is Shyamala Maisondieu. Top notes are Neroli, Peach, Bitter Orange and Mandarin Orange; middle notes are Mimosa, Ylang-Ylang, Orris Root, Rose and Tuberose; base notes are Tonka Bean, Amyris, Vanille and Ambrette (Musk Mallow).',
        4.09,
        32,
        NULL
      ),
(
        'Six-Scents-Series-Three-3-Junn-J-Can-t-Smell-Fear-10602',
        'Six Scents Series Three 3 Junn.J: Can''t Smell Fear Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Natalie Gracia-Cetto',
        'Nutmeg, Pink Pepper, Bergamot and Mandarin Orange',
        'Virginia Cedar, Ambrette (Musk Mallow), Incense and Orris Root',
        'Leather, Sandalwood, Amber and Musk',
        'woody,leather,fresh spicy,musky,powdery',
        'Six Scents Series Three 3 Junn.J: Can''t Smell FearbySix Scentsis a Woody Spicy fragrance for women and men.Six Scents Series Three 3 Junn.J: Can''t Smell Fearwas launched in 2010. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Nutmeg, Pink Pepper, Bergamot and Mandarin Orange; middle notes are Virginia Cedar, Ambrette (Musk Mallow), Incense and Orris Root; base notes are Leather, Sandalwood, Amber and Musk.',
        4.04,
        23,
        NULL
      ),
(
        'Six-Scents-Series-Three-4-Rad-Hourani-Ascent-10603',
        'Six Scents Series Three 4 Rad Hourani: Ascent Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Christophe Raynaud',
        'Peach and Violet Leaf',
        'Virginia Cedar, Rose, Leather and Ylang-Ylang',
        'Powdery Notes, Musk, Incense, Tonka Bean and Benzoin',
        'powdery,musky,amber,smoky,warm spicy',
        'Six Scents Series Three 4 Rad Hourani: AscentbySix Scentsis a Amber fragrance for women and men.Six Scents Series Three 4 Rad Hourani: Ascentwas launched in 2010. The nose behind this fragrance is Christophe Raynaud. Top notes are Peach and Violet Leaf; middle notes are Virginia Cedar, Rose, Leather and Ylang-Ylang; base notes are Powdery Notes, Musk, Incense, Tonka Bean and Benzoin.',
        4,
        33,
        NULL
      ),
(
        'Six-Scents-Series-Three-5-N-Hoolywood-087-10604',
        'Six Scents Series Three 5 . N.Hoolywood: #087 Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Stephen Nilsen',
        'Green Notes, Cypress and Woody Notes',
        'Rosemary, Sea water, Salt and Nutmeg',
        'Hinoki Wood, Balsam Fir and Sandalwood',
        'woody,aromatic,fresh spicy,green,marine',
        'Six Scents Series Three 5 . N.Hoolywood: #087bySix Scentsis a Aromatic Aquatic fragrance for women and men.Six Scents Series Three 5 . N.Hoolywood: #087was launched in 2010. The nose behind this fragrance is Stephen Nilsen. Top notes are Green Notes, Cypress and Woody Notes; middle notes are Rosemary, Sea water, Salt and Nutmeg; base notes are Hinoki Wood, Balsam Fir and Sandalwood.',
        4.47,
        38,
        NULL
      ),
(
        'Six-Scents-Series-Three-6-Ohne-Titel-M-10605',
        'Six Scents Series Three 6 Ohne Titel: M Six Scents',
        'Six',
        'for women and men',
        NULL,
        'Yann Vasnier',
        'Cardamom',
        'Plum and Virginia Cedar',
        'Musk, Powdery Notes, Tonka Bean, Castoreum and Civetta',
        'musky,powdery,sweet,fruity,warm spicy',
        'Six Scents Series Three 6 Ohne Titel: MbySix Scentsis a Amber fragrance for women and men.Six Scents Series Three 6 Ohne Titel: Mwas launched in 2010. The nose behind this fragrance is Yann Vasnier. Top note is Cardamom; middle notes are Plum and Virginia Cedar; base notes are Musk, Powdery Notes, Tonka Bean, Castoreum and Civetta.',
        4.33,
        48,
        NULL
      ),
(
        'No-1-Crust-24522',
        'No. 1 Crust Six Scents',
        'No.',
        'for women and men',
        NULL,
        'Shyamala Maisondieu',
        NULL,
        NULL,
        NULL,
        'citrus,woody,fresh,leather',
        'No. 1 CrustbySix Scentsis a Woody fragrance for women and men. The nose behind this fragrance is Shyamala Maisondieu.',
        4.6,
        5,
        NULL
      ),
(
        'No-2-Modesty-24523',
        'No. 2 Modesty Six Scents',
        'No.',
        'for women and men',
        NULL,
        'Rodrigo Flores-Roux',
        NULL,
        NULL,
        NULL,
        'amber,woody,balsamic,metallic,mineral',
        'No. 2 ModestybySix Scentsis a Amber Fougere fragrance for women and men. The nose behind this fragrance is Rodrigo Flores-Roux.',
        4,
        4,
        NULL
      ),
(
        'No-3-Buk-24524',
        'No. 3 Buk Six Scents',
        'No.',
        'for women and men',
        NULL,
        'Guillaume Flavigny',
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,amber,fresh spicy,white floral',
        'No. 3 BukbySix Scentsis a Amber Floral fragrance for women and men. The nose behind this fragrance is Guillaume Flavigny.',
        4.5,
        4,
        NULL
      ),
(
        'No-4-Nappa-Noir-24525',
        'No. 4 Nappa Noir Six Scents',
        'No.',
        'for women and men',
        NULL,
        'Calice Becker',
        NULL,
        NULL,
        NULL,
        'leather,powdery,violet,iris,smoky',
        'No. 4 Nappa NoirbySix Scentsis a Amber fragrance for women and men. The nose behind this fragrance is Calice Becker.',
        3.9,
        30,
        NULL
      ),
(
        'No-5-Second-Skin-24526',
        'No. 5 Second Skin Six Scents',
        'No.',
        'for women and men',
        NULL,
        'Marypierre Julien',
        NULL,
        NULL,
        NULL,
        'fruity,powdery,musky,tropical,woody',
        'No. 5 Second SkinbySix Scentsis a fragrance for women and men. The nose behind this fragrance is Marypierre Julien.',
        3.25,
        4,
        NULL
      ),
(
        'No-6-Un-Beaute-Accidentelle-24527',
        'No. 6 Un Beaute Accidentelle Six Scents',
        'No.',
        'for women and men',
        NULL,
        'Nadège Le Garlantezec',
        NULL,
        NULL,
        NULL,
        'woody,citrus,fresh spicy,aromatic,vanilla',
        'No. 6 Un Beaute AccidentellebySix Scentsis a Woody Aromatic fragrance for women and men. The nose behind this fragrance is Nadège Le Garlantezec.',
        5,
        1,
        NULL
      ),
(
        'Incense-by-the-Sea-19188',
        'Incense by the Sea Six Scents',
        'Incense',
        'for women and men',
        NULL,
        'David Apel',
        NULL,
        NULL,
        NULL,
        'marine,woody,salty,amber,green',
        'Incense by the SeabySix Scentsis a Woody Aquatic fragrance for women and men.Incense by the Seawas launched in 2011. The nose behind this fragrance is David Apel.',
        4.4,
        5,
        NULL
      ),
(
        'Verde-19187',
        'Verde Six Scents',
        'Verde',
        'for women and men',
        NULL,
        'David Apel',
        'Palm Leaf, Silk Vine or Milk Broom, Seaweed, Shiso, Bergamot and Lemon',
        'Galbanum, Orchid, Jasmine, Fern and White Flowers',
        'Orris Root and Woody Notes',
        'aromatic,green,white floral,citrus,fresh spicy',
        'VerdebySix Scentsis a Floral Green fragrance for women and men.Verdewas launched in 2011. The nose behind this fragrance is David Apel. Top notes are Palm Leaf, Silk Vine or Milk Broom, Seaweed, Shiso, Bergamot and Lemon; middle notes are Galbanum, Orchid, Jasmine, Fern and White Flowers; base notes are Orris Root and Woody Notes.',
        4,
        1,
        NULL
      ),
(
        'Authentic-Maroussia-5375',
        'Authentic Maroussia Slava Zaitsev',
        'Authentic',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,mossy,yellow floral,earthy',
        'Authentic MaroussiabySlava Zaitsevis a fragrance for women.Authentic Maroussiawas launched in 1996.',
        3.91,
        292,
        NULL
      ),
(
        'Lumia-12993',
        'Lumia Slava Zaitsev',
        'Lumia',
        'for women',
        NULL,
        NULL,
        'Cherry',
        'Floral Notes',
        'Patchouli',
        'patchouli,floral,cherry,woody,warm spicy',
        'LumiabySlava Zaitsevis a Chypre Floral fragrance for women.Lumiawas launched in 2009. Top note is Cherry; middle note is Floral Notes; base note is Patchouli.',
        3.56,
        16,
        NULL
      ),
(
        'Maroussia-1196',
        'Maroussia Slava Zaitsev',
        'Maroussia',
        'for women',
        NULL,
        NULL,
        'Aldehydes, Orange Blossom, Peach and Bergamot',
        'Carnation, Ylang-Ylang, Tuberose, Heliotrope, Iris, Jasmine, Rose, Orchid and Lily-of-the-Valley',
        'Civet, Sandalwood, Amber, Benzoin, Vanilla, Musk, Tonka Bean and Cedar',
        'powdery,amber,woody,vanilla,warm spicy',
        'MaroussiabySlava Zaitsevis a Amber Floral fragrance for women.Maroussiawas launched in 1992. Top notes are Aldehydes, Orange Blossom, Peach and Bergamot; middle notes are Carnation, Ylang-Ylang, Tuberose, Heliotrope, Iris, Jasmine, Rose, Orchid and Lily-of-the-Valley; base notes are Civet, Sandalwood, Amber, Benzoin, Vanilla, Musk, Tonka Bean and Cedar.',
        3.7,
        2,
        NULL
      ),
(
        'Nikita-5376',
        'Nikita Slava Zaitsev',
        'Nikita',
        'for women',
        NULL,
        NULL,
        'Paprika, Ginger and Mandarin Orange',
        'Tiare Flower',
        'Vanilla, Sandalwood, Amber and Musk',
        'warm spicy,white floral,powdery,vanilla,amber',
        'NikitabySlava Zaitsevis a Amber Floral fragrance for women.Nikitawas launched in 2007. Top notes are Paprika, Ginger and Mandarin Orange; middle note is Tiare Flower; base notes are Vanilla, Sandalwood, Amber and Musk.',
        3.94,
        187,
        NULL
      ),
(
        'Balade-Imaginaire-73578',
        'Balade Imaginaire Slava Zaitsev',
        'Balade',
        'for women and men',
        NULL,
        'Robertet',
        'Incense, Rum, Wormwood and Pink Pepper',
        'Cypress and Sage',
        'Incense, Smoke, Leather and Tobacco',
        'smoky,aromatic,woody,amber,leather',
        'Balade ImaginairebySlava Zaitsevis a Leather fragrance for women and men.Balade Imaginairewas launched in 2021. The nose behind this fragrance is Robertet. Top notes are Incense, Rum, Wormwood and Pink Pepper; middle notes are Cypress and Sage; base notes are Incense, Smoke, Leather and Tobacco.',
        4.09,
        11,
        NULL
      ),
(
        'Blanc-Eternel-73573',
        'Blanc Eternel Slava Zaitsev',
        'Blanc',
        'for women',
        NULL,
        'Robertet',
        'Maple sap and Wormwood',
        'Licorice and Pine',
        'Sandalwood, Vetiver and Amber',
        'woody,sweet,aromatic,soft spicy,powdery',
        'Blanc EternelbySlava Zaitsevis a Amber Vanilla fragrance for women.Blanc Eternelwas launched in 2021. The nose behind this fragrance is Robertet. Top notes are Maple sap and Wormwood; middle notes are Licorice and Pine; base notes are Sandalwood, Vetiver and Amber.',
        3.6,
        15,
        NULL
      ),
(
        'Parfum-de-Soie-73574',
        'Parfum de Soie Slava Zaitsev',
        'Parfum',
        'for women',
        NULL,
        'Robertet',
        'Rose and Grapefruit',
        'Saffron, Sandalwood, Cashmere Wood, Pepper, Nutmeg and Cumin',
        'Amber, Incense, Leather and Agarwood (Oud)',
        'amber,warm spicy,woody,fresh spicy,leather',
        'Parfum de SoiebySlava Zaitsevis a Amber Floral fragrance for women.Parfum de Soiewas launched in 2021. The nose behind this fragrance is Robertet. Top notes are Rose and Grapefruit; middle notes are Saffron, Sandalwood, Cashmere Wood, Pepper, Nutmeg and Cumin; base notes are Amber, Incense, Leather and Agarwood (Oud).',
        3.4,
        10,
        NULL
      ),
(
        'Secret-du-Style-73575',
        'Secret du Style Slava Zaitsev',
        'Secret',
        'for women',
        NULL,
        'Robertet',
        'Pink Pepper and Grapefruit',
        'Rose, Iris and Jasmine',
        'Patchouli, Tonka Bean, Vanilla, Musk and Praline',
        'vanilla,sweet,musky,powdery,patchouli',
        'Secret du StylebySlava Zaitsevis a Chypre Floral fragrance for women.Secret du Stylewas launched in 2021. The nose behind this fragrance is Robertet. Top notes are Pink Pepper and Grapefruit; middle notes are Rose, Iris and Jasmine; base notes are Patchouli, Tonka Bean, Vanilla, Musk and Praline.',
        4.33,
        6,
        NULL
      ),
(
        'Soiree-Parisienne-73576',
        'Soirée Parisienne Slava Zaitsev',
        'Soirée',
        'for women and men',
        NULL,
        'Robertet',
        'Grapefruit, Apple, Mandarin Orange, Pink Pepper and Saffron',
        'Lily-of-the-Valley, Nutmeg and Violet',
        'Moss, Musk, Incense, Cedar and Amber',
        'citrus,mossy,fruity,fresh,earthy',
        'Soirée ParisiennebySlava Zaitsevis a fragrance for women and men.Soirée Parisiennewas launched in 2021. The nose behind this fragrance is Robertet. Top notes are Grapefruit, Apple, Mandarin Orange, Pink Pepper and Saffron; middle notes are Lily-of-the-Valley, Nutmeg and Violet; base notes are Moss, Musk, Incense, Cedar and Amber.',
        4.17,
        12,
        NULL
      ),
(
        'Velours-Gourmand-73577',
        'Velours Gourmand Slava Zaitsev',
        'Velours',
        'for women and men',
        NULL,
        'Robertet',
        'Hazelnut, Almond and Blood Orange',
        'Cacao and Chocolate',
        'Patchouli, Vetiver and Brown sugar',
        'warm spicy,cacao,woody,sweet,nutty',
        'Velours GourmandbySlava Zaitsevis a Amber Vanilla fragrance for women and men.Velours Gourmandwas launched in 2021. The nose behind this fragrance is Robertet. Top notes are Hazelnut, Almond and Blood Orange; middle notes are Cacao and Chocolate; base notes are Patchouli, Vetiver and Brown sugar.',
        3.81,
        36,
        NULL
      ),
(
        'Aura-89444',
        'Aura Sophia Mae',
        'Aura',
        'for women and men',
        NULL,
        NULL,
        'Cotton Flower',
        'Jasmine',
        'Musk and Amber',
        'powdery,amber,musky,white floral,floral',
        'AurabySophia Maeis a Floral Woody Musk fragrance for women and men. This is a new fragrance.Aurawas launched in 2023. Top note is Cotton Flower; middle note is Jasmine; base notes are Musk and Amber.',
        3.8,
        5,
        NULL
      ),
(
        'Golden-Mirage-89446',
        'Golden Mirage Sophia Mae',
        'Golden',
        'for women and men',
        NULL,
        NULL,
        'Clementine and Calabrian bergamot',
        'Orange Blossom',
        'Amber, Musk and Patchouli',
        'citrus,sweet',
        'Golden MiragebySophia Maeis a Amber Floral fragrance for women and men. This is a new fragrance.Golden Miragewas launched in 2023. Top notes are Clementine and Calabrian bergamot; middle note is Orange Blossom; base notes are Amber, Musk and Patchouli.',
        4,
        2,
        NULL
      ),
(
        'Mystic-Escape-89447',
        'Mystic Escape Sophia Mae',
        'Mystic',
        'for women and men',
        NULL,
        NULL,
        'Raspberry, Bergamot and Grapefruit',
        'Rose, Neroli and Violet',
        'Vanilla, Benzoin and Musk',
        'rose,citrus,fruity,sweet,powdery',
        'Mystic EscapebySophia Maeis a Amber Floral fragrance for women and men. This is a new fragrance.Mystic Escapewas launched in 2023. Top notes are Raspberry, Bergamot and Grapefruit; middle notes are Rose, Neroli and Violet; base notes are Vanilla, Benzoin and Musk.',
        4.67,
        3,
        NULL
      ),
(
        'Circa-91-66303',
        'Circa 91 ST. Rose',
        'Circa',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Lemon',
        'Iris, Patchouli and Jasmine',
        'Cedar and Sandalwood',
        'woody,citrus,powdery,iris,aromatic',
        'Circa 91byST. Roseis a Citrus fragrance for women and men.Circa 91was launched in 2020. Top notes are Bergamot and Lemon; middle notes are Iris, Patchouli and Jasmine; base notes are Cedar and Sandalwood.',
        3.4,
        5,
        NULL
      ),
(
        'Desert-Nomad-66304',
        'Desert Nomad ST. Rose',
        'Desert',
        'for women and men',
        NULL,
        NULL,
        'Ginger, Bergamot and Neroli',
        'Pepper, Iris and Clary Sage',
        'Sandalwood, Palo Santo and Vetiver',
        'woody,aromatic,citrus,warm spicy,fresh spicy',
        'Desert NomadbyST. Roseis a Woody fragrance for women and men.Desert Nomadwas launched in 2020. Top notes are Ginger, Bergamot and Neroli; middle notes are Pepper, Iris and Clary Sage; base notes are Sandalwood, Palo Santo and Vetiver.',
        4,
        5,
        NULL
      ),
(
        'Flower-Tuxedo-79371',
        'Flower Tuxedo ST. Rose',
        'Flower',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Neroli',
        'Jasmine and Orris',
        'Sandalwood and Vetiver',
        'woody,citrus,white floral,aromatic,powdery',
        'Flower TuxedobyST. Roseis a Floral Woody Musk fragrance for women and men. This is a new fragrance.Flower Tuxedowas launched in 2022. Top notes are Bergamot and Neroli; middle notes are Jasmine and Orris; base notes are Sandalwood and Vetiver.',
        3.5,
        2,
        NULL
      ),
(
        'Gipsy-Cowboy-66306',
        'Gipsy Cowboy ST. Rose',
        'Gipsy',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Ginger and Mandarin Orange',
        'Rose and Olibanum',
        'Sandalwood, Benzoin and Oakmoss',
        'warm spicy,amber,woody,citrus,rose',
        'Gipsy CowboybyST. Roseis a Aromatic Spicy fragrance for women and men.Gipsy Cowboywas launched in 2020. Top notes are Pink Pepper, Ginger and Mandarin Orange; middle notes are Rose and Olibanum; base notes are Sandalwood, Benzoin and Oakmoss.',
        3.29,
        7,
        NULL
      ),
(
        'Grand-Larceny-66305',
        'Grand Larceny ST. Rose',
        'Grand',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Clary Sage',
        'Rose and Lemon',
        'Sandalwood and Bourbon Vetiver',
        'aromatic,citrus,woody,rose,earthy',
        'Grand LarcenybyST. Roseis a Floral fragrance for women and men.Grand Larcenywas launched in 2020. Top notes are Bergamot and Clary Sage; middle notes are Rose and Lemon; base notes are Sandalwood and Bourbon Vetiver.',
        3.4,
        5,
        NULL
      ),
(
        'Juliet-in-White-66307',
        'Juliet in White ST. Rose',
        'Juliet',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, White Pepper and Pepper',
        'Rose, Bergamot and Jasmine Sambac',
        'Ambrette (Musk Mallow) and Sandalwood',
        'citrus,floral,fresh spicy,rose,musky',
        'Juliet in WhitebyST. Roseis a Floral Woody Musk fragrance for women and men.Juliet in Whitewas launched in 2020. Top notes are Tangerine, White Pepper and Pepper; middle notes are Rose, Bergamot and Jasmine Sambac; base notes are Ambrette (Musk Mallow) and Sandalwood.',
        4.15,
        13,
        NULL
      ),
(
        'Terre-Rouge-79370',
        'Terre Rouge ST. Rose',
        'Terre',
        'for women and men',
        NULL,
        NULL,
        'Cypress, Cardamom and White Musk',
        'Amyris and Eucalyptus',
        'Sandalwood, Amber and Orris',
        'woody,powdery,aromatic,warm spicy',
        'Terre RougebyST. Roseis a Amber Woody fragrance for women and men. This is a new fragrance.Terre Rougewas launched in 2022. Top notes are Cypress, Cardamom and White Musk; middle notes are Amyris and Eucalyptus; base notes are Sandalwood, Amber and Orris.',
        4,
        2,
        NULL
      ),
(
        'Vigilante-66308',
        'Vigilante ST. Rose',
        'Vigilante',
        'for women and men',
        NULL,
        NULL,
        'Cypress and Bergamot',
        'Ylang-Ylang, Jasmine and Rose',
        'Sandalwood, Atlas Cedar, Labdanum and Patchouli',
        'woody,powdery,aromatic,warm spicy',
        'VigilantebyST. Roseis a Woody fragrance for women and men.Vigilantewas launched in 2020. Top notes are Cypress and Bergamot; middle notes are Ylang-Ylang, Jasmine and Rose; base notes are Sandalwood, Atlas Cedar, Labdanum and Patchouli.',
        4.62,
        8,
        NULL
      ),
(
        '5th-Ave-61482',
        '5th Ave Strada',
        '5th',
        'for women and men',
        NULL,
        'Christian Carbonnel',
        'Jasmine and Saffron',
        'Amber and Caramel',
        'Agarwood (Oud) and Oakmoss',
        'oud,white floral',
        '5th AvebyStradais a Amber Floral fragrance for women and men.5th Avewas launched in 2020. The nose behind this fragrance is Christian Carbonnel. Top notes are Jasmine and Saffron; middle notes are Amber and Caramel; base notes are Agarwood (Oud) and Oakmoss.',
        3.33,
        6,
        NULL
      ),
(
        'Avenue-Montaigne-61481',
        'Avenue Montaigne Strada',
        'Avenue',
        'for women and men',
        NULL,
        'Cyrille Carles',
        'Bergamot, Saffron and Jasmine',
        'Amberwood, Ambergris, Moroccan Jasmine, Rose and Birch',
        'Fir Resin, Cedar, Musk and Vanilla',
        'woody,amber,leather,fresh spicy,warm spicy',
        'Avenue MontaignebyStradais a Woody Floral Musk fragrance for women and men.Avenue Montaignewas launched in 2020. The nose behind this fragrance is Cyrille Carles. Top notes are Bergamot, Saffron and Jasmine; middle notes are Amberwood, Ambergris, Moroccan Jasmine, Rose and Birch; base notes are Fir Resin, Cedar, Musk and Vanilla.',
        3.75,
        4,
        NULL
      ),
(
        'Sloane-St-61483',
        'Sloane St Strada',
        'Sloane',
        'for women and men',
        NULL,
        'Christian Carbonnel',
        'Turkish Rose, Leather and Pink Pepper',
        'Rose',
        'Agarwood (Oud) and Amber',
        'oud,rose,leather,animalic,amber',
        'Sloane StbyStradais a Amber Floral fragrance for women and men.Sloane Stwas launched in 2020. The nose behind this fragrance is Christian Carbonnel. Top notes are Turkish Rose, Leather and Pink Pepper; middle note is Rose; base notes are Agarwood (Oud) and Amber.',
        2.2,
        5,
        NULL
      ),
(
        'Via-Veneto-61480',
        'Via Veneto Strada',
        'Via',
        'for women and men',
        NULL,
        'Moellhausen',
        'Iris, Jasmine, Neroli and Damask Rose',
        'Ginger, Tuberose, Cashmere Musk, Myrrh and Clary Sage',
        'Patchouli, Amber, Woodsy Notes and Cypriol Oil or Nagarmotha',
        'warm spicy,white floral,woody,patchouli,amber',
        'Via VenetobyStradais a Floral Woody Musk fragrance for women and men.Via Venetowas launched in 2020. The nose behind this fragrance is Moellhausen. Top notes are Iris, Jasmine, Neroli and Damask Rose; middle notes are Ginger, Tuberose, Cashmere Musk, Myrrh and Clary Sage; base notes are Patchouli, Amber, Woodsy Notes and Cypriol Oil or Nagarmotha.',
        4,
        1,
        NULL
      ),
(
        '1723-80298',
        '1723 Superz.',
        '1723',
        'for men',
        NULL,
        'Gökhan Şimşek',
        NULL,
        NULL,
        NULL,
        'woody,lavender,powdery,floral,patchouli',
        '1723bySuperz.is a Amber Woody fragrance for men. This is a new fragrance.1723was launched in 2022. The nose behind this fragrance is Gökhan Şimşek.',
        4.1,
        58,
        NULL
      ),
(
        'Abu-Dhabi-79425',
        'Abu Dhabi Superz.',
        'Abu',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'vanilla,amber,rose,oud,powdery',
        'Abu DhabibySuperz.is a Amber Vanilla fragrance for women and men. This is a new fragrance.Abu Dhabiwas launched in 2022. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.95,
        132,
        NULL
      ),
(
        'Aishah-80310',
        'Aishah Superz.',
        'Aishah',
        'for women',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'fruity,citrus,sweet,fresh,floral',
        'AishahbySuperz.is a Floral fragrance for women.Aishahwas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.88,
        34,
        NULL
      ),
(
        'Amber-Vanille-91329',
        'Amber & Vanille Superz.',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,sweet,coffee,vanilla,powdery',
        'Amber & VanillebySuperz.is a Amber Vanilla fragrance for women and men. This is a new fragrance.Amber & Vanillewas launched in 2024.',
        4.6,
        10,
        NULL
      ),
(
        'Amber-Woods-91376',
        'Amber & Woods Superz.',
        'Amber',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'musky,caramel,citrus,sweet,warm spicy',
        'Amber & WoodsbySuperz.is a Amber Woody fragrance for women and men. This is a new fragrance.Amber & Woodswas launched in 2024. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.32,
        19,
        NULL
      ),
(
        'Aura-91375',
        'Aura Superz.',
        'Aura',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,woody,powdery,white floral,oud',
        'AurabySuperz.is a Amber Vanilla fragrance for women and men. This is a new fragrance.Aurawas launched in 2024.',
        4.17,
        23,
        NULL
      ),
(
        'Butterfly-80311',
        'Butterfly Superz.',
        'Butterfly',
        'for women',
        NULL,
        'Gökhan Şimşek',
        NULL,
        NULL,
        NULL,
        'amber,fruity,citrus,powdery,musky',
        'ButterflybySuperz.is a Amber Floral fragrance for women.Butterflywas launched in 2021. The nose behind this fragrance is Gökhan Şimşek.',
        3.61,
        23,
        NULL
      ),
(
        'Caesar-79415',
        'Caesar Superz.',
        'Caesar',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'citrus,green,aromatic,woody,white floral',
        'CaesarbySuperz.is a Aromatic Spicy fragrance for men.Caesarwas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.95,
        74,
        NULL
      ),
(
        'Caesar-Ultra-91374',
        'Caesar Ultra Superz.',
        'Caesar',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'woody,patchouli,warm spicy,citrus,earthy',
        'Caesar UltrabySuperz.is a Amber Floral fragrance for men. This is a new fragrance.Caesar Ultrawas launched in 2024. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.46,
        59,
        NULL
      ),
(
        'Candy-87780',
        'Candy Superz.',
        'Candy',
        'for women',
        NULL,
        'Hüseyin Erdoğmuş',
        'Orange, Marshmallow and Apple',
        'Iris, Jasmine, Caramel, Tonka Bean and Sandalwood',
        'Cacao, Woody Notes, Amber, Vanilla and Musk',
        'cacao,iris,white floral,woody,warm spicy',
        'CandybySuperz.is a fragrance for women. This is a new fragrance.Candywas launched in 2023. The nose behind this fragrance is Hüseyin Erdoğmuş. Top notes are Orange, Marshmallow and Apple; middle notes are Iris, Jasmine, Caramel, Tonka Bean and Sandalwood; base notes are Cacao, Woody Notes, Amber, Vanilla and Musk.',
        4.06,
        34,
        NULL
      ),
(
        'Chambord-79416',
        'Chambord Superz.',
        'Chambord',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'lavender,amber,cinnamon,iris,warm spicy',
        'ChambordbySuperz.is a Amber Woody fragrance for men.Chambordwas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.24,
        50,
        NULL
      ),
(
        'Coco-Loco-80312',
        'Coco Loco Superz.',
        'Coco',
        'for women',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'powdery,white floral,vanilla,coconut,sweet',
        'Coco LocobySuperz.is a Aromatic fragrance for women.Coco Locowas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4,
        36,
        NULL
      ),
(
        'Colors-91331',
        'Colors Superz.',
        'Colors',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,caramel,vanilla,warm spicy',
        'ColorsbySuperz.is a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Colorswas launched in 2024.',
        4.77,
        13,
        NULL
      ),
(
        'Dominance-79418',
        'Dominance Superz.',
        'Dominance',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'woody,marine,patchouli,citrus,earthy',
        'DominancebySuperz.is a Amber Woody fragrance for men.Dominancewas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.04,
        93,
        NULL
      ),
(
        'Dominance-Gold-79419',
        'Dominance Gold Superz.',
        'Dominance',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'vanilla,citrus,sweet,cinnamon,warm spicy',
        'Dominance GoldbySuperz.is a Aromatic fragrance for men. This is a new fragrance.Dominance Goldwas launched in 2022. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.24,
        88,
        NULL
      ),
(
        'Endless-Love-91373',
        'Endless Love Superz.',
        'Endless',
        'for women',
        NULL,
        'Gökhan Şimşek',
        NULL,
        NULL,
        NULL,
        'marine,white floral,iris,aromatic,powdery',
        'Endless LovebySuperz.is a Floral Aquatic fragrance for women. This is a new fragrance.Endless Lovewas launched in 2024. The nose behind this fragrance is Gökhan Şimşek.',
        4.64,
        25,
        NULL
      ),
(
        'Endless-Sea-79420',
        'Endless Sea Superz.',
        'Endless',
        'for men',
        NULL,
        'Gökhan Şimşek',
        NULL,
        NULL,
        NULL,
        'citrus,woody,marine,aromatic,earthy',
        'Endless SeabySuperz.is a Amber Woody fragrance for men. This is a new fragrance.Endless Seawas launched in 2022. The nose behind this fragrance is Gökhan Şimşek.',
        3.94,
        116,
        NULL
      ),
(
        'Feel-80299',
        'Feel Superz.',
        'Feel',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'powdery,musky,iris,violet',
        'FeelbySuperz.is a Woody Aromatic fragrance for women and men.Feelwas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.69,
        39,
        NULL
      ),
(
        'Finom-Istallo-91333',
        'Finom Istallo Superz.',
        'Finom',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,rose,fresh spicy,leather',
        'Finom IstallobySuperz.is a Leather fragrance for men. This is a new fragrance.Finom Istallowas launched in 2024.',
        4.68,
        19,
        NULL
      ),
(
        'Flamingo-Fizz-87782',
        'Flamingo Fizz Superz.',
        'Flamingo',
        'for women',
        NULL,
        'Hüseyin Erdoğmuş',
        'Champagne, Grapefruit, Lemon and Wild Berries',
        'Orange Blossom, Rose and Jasmine',
        'Benzoin, Olibanum, Vetiver, Musk and Amber',
        'citrus,amber,aromatic,woody,Champagne',
        'Flamingo FizzbySuperz.is a fragrance for women. This is a new fragrance.Flamingo Fizzwas launched in 2023. The nose behind this fragrance is Hüseyin Erdoğmuş. Top notes are Champagne, Grapefruit, Lemon and Wild Berries; middle notes are Orange Blossom, Rose and Jasmine; base notes are Benzoin, Olibanum, Vetiver, Musk and Amber.',
        4.22,
        51,
        NULL
      ),
(
        'Gentleman-80300',
        'Gentleman Superz.',
        'Gentleman',
        'for men',
        NULL,
        'Ayşe Sirkecioğlu',
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,sweet,tobacco,woody',
        'GentlemanbySuperz.is a Aromatic fragrance for men.Gentlemanwas launched in 2021. The nose behind this fragrance is Ayşe Sirkecioğlu.',
        4,
        36,
        NULL
      ),
(
        'Gold-Dust-80301',
        'Gold Dust Superz.',
        'Gold',
        'for men',
        NULL,
        'Özge Erdoğmuş Altınel',
        NULL,
        NULL,
        NULL,
        'smoky,powdery,vanilla,amber,woody',
        'Gold DustbySuperz.is a Amber Spicy fragrance for men.Gold Dustwas launched in 2021. The nose behind this fragrance is Özge Erdoğmuş Altınel.',
        3.85,
        39,
        NULL
      ),
(
        'Happiness-79421',
        'Happiness Superz.',
        'Happiness',
        'for women',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'patchouli,citrus,woody,warm spicy,earthy',
        'HappinessbySuperz.is a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Happinesswas launched in 2022. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.76,
        25,
        NULL
      ),
(
        'Hello-Baby-80313',
        'Hello Baby Superz.',
        'Hello',
        'for women',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'white floral,warm spicy,sweet,woody,powdery',
        'Hello BabybySuperz.is a Floral fragrance for women.Hello Babywas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.71,
        21,
        NULL
      ),
(
        'Immortalis-91338',
        'Immortalis Superz.',
        'Immortalis',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'warm spicy,musky,mossy,mineral,earthy',
        'ImmortalisbySuperz.is a Woody Spicy fragrance for women and men. This is a new fragrance.Immortaliswas launched in 2024. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.41,
        39,
        NULL
      ),
(
        'Khalifa-91372',
        'Khalifa Superz.',
        'Khalifa',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'amber,musky,oud,powdery,warm spicy',
        'KhalifabySuperz.is a Leather fragrance for men. This is a new fragrance.Khalifawas launched in 2024. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.55,
        29,
        NULL
      ),
(
        'KHAMZAT-Smesh-87775',
        'KHAMZAT Smesh Superz.',
        'KHAMZAT',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        'Lavender, Blood Orange and Neroli',
        'Cashmeran, Spices and Cinnamon',
        'Vetiver, Moss, Tonka Bean, Vanilla, Amber and Cedarwood',
        'woody,aromatic,earthy,lavender,amber',
        'KHAMZAT SmeshbySuperz.is a Woody Spicy fragrance for women and men. This is a new fragrance.KHAMZAT Smeshwas launched in 2023. The nose behind this fragrance is Hüseyin Erdoğmuş. Top notes are Lavender, Blood Orange and Neroli; middle notes are Cashmeran, Spices and Cinnamon; base notes are Vetiver, Moss, Tonka Bean, Vanilla, Amber and Cedarwood.',
        3.78,
        98,
        NULL
      ),
(
        'KHAMZAT-The-Wolf-87776',
        'KHAMZAT The Wolf Superz.',
        'KHAMZAT',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        'Apple, Raspberry, Cardamom and Saffron',
        'Lily of the Valley, White Flowers, Violet and Cinnamon',
        'Leather, Musk, Woody Notes and Amber',
        'white floral,leather,musky,fruity,fresh',
        'KHAMZAT The WolfbySuperz.is a Amber Spicy fragrance for women and men. This is a new fragrance.KHAMZAT The Wolfwas launched in 2023. The nose behind this fragrance is Hüseyin Erdoğmuş. Top notes are Apple, Raspberry, Cardamom and Saffron; middle notes are Lily of the Valley, White Flowers, Violet and Cinnamon; base notes are Leather, Musk, Woody Notes and Amber.',
        3.87,
        71,
        NULL
      ),
(
        'La-Boheme-80302',
        'La Bohéme Superz.',
        'La',
        'for men',
        NULL,
        'Özge Erdoğmuş Altınel',
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,woody,amber',
        'La BohémebySuperz.is a Amber fragrance for men.La Bohémewas launched in 2021. The nose behind this fragrance is Özge Erdoğmuş Altınel.',
        3.54,
        52,
        NULL
      ),
(
        'Lake-Balaton-91337',
        'Lake Balaton Superz.',
        'Lake',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,earthy,woody,aromatic,mossy',
        'Lake BalatonbySuperz.is a fragrance for women and men. This is a new fragrance.Lake Balatonwas launched in 2024.',
        4.33,
        49,
        NULL
      ),
(
        'Memories-79426',
        'Memories Superz.',
        'Memories',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,sweet,amber,cinnamon',
        'MemoriesbySuperz.is a Aromatic fragrance for women and men. This is a new fragrance.Memorieswas launched in 2022. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        4.03,
        61,
        NULL
      ),
(
        'Memories-Gold-91336',
        'Memories Gold Superz.',
        'Memories',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,vanilla,sweet,powdery,honey',
        'Memories GoldbySuperz.is a Amber Vanilla fragrance for women and men. This is a new fragrance.Memories Goldwas launched in 2024.',
        4.47,
        75,
        NULL
      ),
(
        'Morocco-80303',
        'Morocco Superz.',
        'Morocco',
        'for men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'sweet,almond,fruity,nutty,warm spicy',
        'MoroccobySuperz.is a Amber Spicy fragrance for men.Moroccowas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.98,
        107,
        NULL
      ),
(
        'Mystery-Saffron-79427',
        'Mystery Saffron Superz.',
        'Mystery',
        'for women and men',
        NULL,
        'Ayşe Sirkecioğlu',
        NULL,
        NULL,
        NULL,
        'warm spicy,sweet,leather,vanilla,rose',
        'Mystery SaffronbySuperz.is a Aromatic Spicy fragrance for women and men. This is a new fragrance.Mystery Saffronwas launched in 2022. The nose behind this fragrance is Ayşe Sirkecioğlu.',
        4.4,
        53,
        NULL
      ),
(
        'Noble-79428',
        'Noble Superz.',
        'Noble',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'warm spicy,floral,amber,caramel,leather',
        'NoblebySuperz.is a Leather fragrance for women and men. This is a new fragrance.Noblewas launched in 2022. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.94,
        53,
        NULL
      ),
(
        'Oud-Alfateh-80307',
        'Oud Alfateh Superz.',
        'Oud',
        'for women and men',
        NULL,
        'Hüseyin Erdoğmuş',
        NULL,
        NULL,
        NULL,
        'aromatic,mossy,earthy,fresh spicy,woody',
        'Oud AlfatehbySuperz.is a Leather fragrance for women and men.Oud Alfatehwas launched in 2021. The nose behind this fragrance is Hüseyin Erdoğmuş.',
        3.97,
        31,
        NULL
      );
