
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Laundry-Day-94333',
        'Laundry Day Abel',
        'Laundry',
        'for women and men',
        NULL,
        'Isaac Sinclair',
        'Aldehydes and Grass',
        'Lime and Passionfruit',
        'Vetiver',
        'fresh,aldehydic,citrus,green,aromatic',
        'Laundry DaybyAbelis a Citrus fragrance for women and men. This is a new fragrance.Laundry Daywas launched in 2024. The nose behind this fragrance is Isaac Sinclair. Top notes are Aldehydes and Grass; middle notes are Lime and Passionfruit; base note is Vetiver.',
        4,
        3,
        NULL
      ),
(
        'Nurture-49903',
        'Nurture Abel',
        'Nurture',
        'for women and men',
        NULL,
        'Fanny Grau',
        'Mastic or Lentisque, Orange Blossom and Bulgarian Rose',
        'Ginger and Jasmine Sambac',
        'Sandalwood',
        'white floral,warm spicy,woody,rose,balsamic',
        'NurturebyAbelis a Floral Woody Musk fragrance for women and men.Nurturewas launched in 2018. The nose behind this fragrance is Fanny Grau. Top notes are Mastic or Lentisque, Orange Blossom and Bulgarian Rose; middle notes are Ginger and Jasmine Sambac; base note is Sandalwood.',
        3.82,
        56,
        NULL
      ),
(
        'Pause-77090',
        'Pause Abel',
        'Pause',
        'for women',
        NULL,
        'Fanny Grau',
        NULL,
        NULL,
        NULL,
        'yellow floral,green,powdery,floral,ozonic',
        'PausebyAbelis a Floral fragrance for women. This is a new fragrance.Pausewas launched in 2022. The nose behind this fragrance is Fanny Grau.',
        3.84,
        19,
        NULL
      ),
(
        'Pink-Iris-55326',
        'Pink Iris Abel',
        'Pink',
        'for women and men',
        NULL,
        'Isaac Sinclair',
        'Raspberry Leaf, Sichuan Pepper and Basil',
        'Italian Orris Root, Rose and Jasmine',
        'Musk and Vanilla',
        'powdery,iris,fruity,fresh spicy,sweet',
        'Pink IrisbyAbelis a Floral fragrance for women and men.Pink Iriswas launched in 2019. The nose behind this fragrance is Isaac Sinclair. Top notes are Raspberry Leaf, Sichuan Pepper and Basil; middle notes are Italian Orris Root, Rose and Jasmine; base notes are Musk and Vanilla.',
        3.77,
        154,
        NULL
      ),
(
        'Red-Santal-42979',
        'Red Santal Abel',
        'Red',
        'for women and men',
        NULL,
        'Isaac Sinclair',
        'Cloves and Black and Pink Pepper',
        'Ginger, Thyme and Bergamot',
        'Sandalwood and Australian Sandalwood',
        'warm spicy,fresh spicy,woody,aromatic,citrus',
        'Red SantalbyAbelis a Woody fragrance for women and men.Red Santalwas launched in 2016. The nose behind this fragrance is Isaac Sinclair. Top notes are Cloves and Black and Pink Pepper; middle notes are Ginger, Thyme and Bergamot; base notes are Sandalwood and Australian Sandalwood.',
        3.54,
        80,
        NULL
      ),
(
        'Tonic-42978',
        'Tonic Abel',
        'Tonic',
        'for women and men',
        NULL,
        'Isaac Sinclair',
        NULL,
        NULL,
        NULL,
        'green,aromatic,citrus,woody,fresh spicy',
        'TonicbyAbelis a Citrus Aromatic fragrance for women and men.Tonicwas launched in 2015. The nose behind this fragrance is Isaac Sinclair.',
        3.88,
        8,
        NULL
      ),
(
        'Vintage-13-42977',
        'Vintage''13 Abel',
        'Vintage''13',
        'for women and men',
        NULL,
        'Isaac Sinclair',
        NULL,
        NULL,
        NULL,
        'warm spicy,fresh spicy,aromatic,woody,citrus',
        'Vintage''13byAbelis a Amber Spicy fragrance for women and men.Vintage''13was launched in 2013. The nose behind this fragrance is Isaac Sinclair.',
        3.45,
        11,
        NULL
      ),
(
        'White-Vetiver-42975',
        'White Vetiver Abel',
        'White',
        'for women and men',
        NULL,
        'Isaac Sinclair',
        'Lime, Bergamot and Peppermint',
        'Ginger and Palmarosa',
        'Vetiver, Vanilla and Ambergris',
        'citrus,aromatic,green,woody,fresh spicy',
        'White VetiverbyAbelis a Citrus Aromatic fragrance for women and men.White Vetiverwas launched in 2016. The nose behind this fragrance is Isaac Sinclair. Top notes are Lime, Bergamot and Peppermint; middle notes are Ginger and Palmarosa; base notes are Vetiver, Vanilla and Ambergris.',
        4.01,
        113,
        NULL
      ),
(
        'Black-Femme-68557',
        'Black Femme Abelha Rainha',
        'Black',
        'for women',
        NULL,
        NULL,
        'Peach and Litchi',
        'Lily-of-the-Valley',
        'Amber and Vanilla',
        'amber,vanilla,fruity,powdery,white floral',
        'Black FemmebyAbelha Rainhais a Amber Floral fragrance for women.Black Femmewas launched in 2018. Top notes are Peach and Litchi; middle note is Lily-of-the-Valley; base notes are Amber and Vanilla.',
        3,
        3,
        NULL
      ),
(
        'Black-Uomo-61353',
        'Black Uomo Abelha Rainha',
        'Black',
        'for men',
        NULL,
        NULL,
        'Green Apple, Lemon and Bergamot',
        'Basil, Cinnamon and Pepper',
        'Sandalwood and Amber',
        'fresh spicy,citrus,warm spicy,aromatic,woody',
        'Black UomobyAbelha Rainhais a Amber Fougere fragrance for men.Black Uomowas launched in 2019. Top notes are Green Apple, Lemon and Bergamot; middle notes are Basil, Cinnamon and Pepper; base notes are Sandalwood and Amber.',
        1,
        1,
        NULL
      ),
(
        'Black-Vulcano-74256',
        'Black Vulcano Abelha Rainha',
        'Black',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Cedar',
        'Oakmoss',
        'woody,citrus,mossy,earthy',
        'Black VulcanobyAbelha Rainhais a Citrus Aromatic fragrance for men.Black Vulcanowas launched in 2019. Top note is Mandarin Orange; middle note is Cedar; base note is Oakmoss.',
        4.5,
        2,
        NULL
      ),
(
        'Cacador-74259',
        'Caçador Abelha Rainha',
        'Caçador',
        'for men',
        NULL,
        NULL,
        'Patchouli',
        'Sandalwood',
        'Vetiver',
        'woody,earthy,patchouli,warm spicy,aromatic',
        'CaçadorbyAbelha Rainhais a Woody Aromatic fragrance for men.Caçadorwas launched in 2020. Top note is Patchouli; middle note is Sandalwood; base note is Vetiver.',
        5,
        1,
        NULL
      ),
(
        'Confidence-Carmim-74255',
        'Confidence Carmim Abelha Rainha',
        'Confidence',
        'for women',
        NULL,
        NULL,
        'Pear',
        'Ginger flower',
        'Vanilla',
        'vanilla,warm spicy,fruity,sweet,fresh',
        'Confidence CarmimbyAbelha Rainhais a Amber Vanilla fragrance for women.Confidence Carmimwas launched in 2017. Top note is Pear; middle note is Ginger flower; base note is Vanilla.',
        4.33,
        3,
        NULL
      ),
(
        'Diamond-Rose-74260',
        'Diamond Rosé Abelha Rainha',
        'Diamond',
        'for women',
        NULL,
        NULL,
        'White Chocolate and Pink Pepper',
        'Peach and Ylang-Ylang',
        'Musk',
        'sweet,musky,yellow floral,fruity,powdery',
        'Diamond RosébyAbelha Rainhais a Floral fragrance for women.Diamond Roséwas launched in 2017. Top notes are White Chocolate and Pink Pepper; middle notes are Peach and Ylang-Ylang; base note is Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Duny-74249',
        'Duny Abelha Rainha',
        'Duny',
        'for women',
        NULL,
        NULL,
        'Cassis, Petitgrain and Tangerine',
        'Lavender, Orange Blossom and Jasmine',
        'Vanilla, Musk, Cedar and Ambergris',
        'white floral,vanilla,lavender,powdery,aromatic',
        'DunybyAbelha Rainhais a Amber Fougere fragrance for women. This is a new fragrance.Dunywas launched in 2022. Top notes are Cassis, Petitgrain and Tangerine; middle notes are Lavender, Orange Blossom and Jasmine; base notes are Vanilla, Musk, Cedar and Ambergris.',
        4,
        1,
        NULL
      ),
(
        'Enigma-Ela-74252',
        'Enigma Ela Abelha Rainha',
        'Enigma',
        'for women',
        NULL,
        NULL,
        'Tangerine',
        'Jasmine',
        'Vanilla',
        'white floral,citrus,vanilla,sweet,fruity',
        'Enigma ElabyAbelha Rainhais a Floral fragrance for women.Enigma Elawas launched in 2016. Top note is Tangerine; middle note is Jasmine; base note is Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Enigma-Ele-74251',
        'Enigma Ele Abelha Rainha',
        'Enigma',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        'Lily-of-the-Valley',
        'Precious Woods',
        'woody,citrus,white floral,fresh,fresh spicy',
        'Enigma ElebyAbelha Rainhais a Aromatic Fougere fragrance for men.Enigma Elewas launched in 2016. Top note is Bergamot; middle note is Lily-of-the-Valley; base note is Precious Woods.',
        NULL,
        NULL,
        NULL
      ),
(
        'Floralle-71311',
        'Floralle Abelha Rainha',
        'Floralle',
        'for women',
        NULL,
        NULL,
        'White Flowers',
        'Almond',
        'Sandalwood',
        'almond,white floral,woody,nutty,fruity',
        'FlorallebyAbelha Rainhais a Amber Floral fragrance for women.Florallewas launched in 2019. Top note is White Flowers; middle note is Almond; base note is Sandalwood.',
        4.33,
        3,
        NULL
      ),
(
        'Floralle-Mystery-71312',
        'Floralle Mystery Abelha Rainha',
        'Floralle',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,amber,warm spicy,musky',
        'Floralle MysterybyAbelha Rainhais a Amber Floral fragrance for women.Floralle Mysterywas launched in 2021.',
        4.33,
        3,
        NULL
      ),
(
        'Fofa-74261',
        'Fofa! Abelha Rainha',
        'Fofa!',
        'for women',
        NULL,
        NULL,
        'Bergamot, Wild Strawberry, Raspberry and Blackberry',
        'Grapes, Peony and Lily-of-the-Valley',
        'Sandalwood, Musk, Amber and Tonka Bean',
        'fruity,sweet,woody,amber,fresh',
        'Fofa!byAbelha Rainhais a Floral Fruity fragrance for women.Fofa!was launched in 2010. Top notes are Bergamot, Wild Strawberry, Raspberry and Blackberry; middle notes are Grapes, Peony and Lily-of-the-Valley; base notes are Sandalwood, Musk, Amber and Tonka Bean.',
        NULL,
        NULL,
        NULL
      ),
(
        'Hero-61354',
        'Hero Abelha Rainha',
        'Hero',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange and Lavender',
        'Jasmine and Basil',
        'Amber and Sandalowood',
        'fresh spicy,aromatic,amber,woody,white floral',
        'HerobyAbelha Rainhais a Aromatic Fougere fragrance for men.Herowas launched in 2016. Top notes are Mandarin Orange and Lavender; middle notes are Jasmine and Basil; base notes are Amber and Sandalowood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ibizza-71310',
        'Ibizza Abelha Rainha',
        'Ibizza',
        'for women',
        NULL,
        NULL,
        'Pear and Red Fruits',
        'Peony and Jasmine',
        'Vanilla and Amber',
        'fruity,fresh,floral,amber,vanilla',
        'IbizzabyAbelha Rainhais a Chypre Floral fragrance for women.Ibizzawas launched in 2020. Top notes are Pear and Red Fruits; middle notes are Peony and Jasmine; base notes are Vanilla and Amber.',
        3,
        3,
        NULL
      ),
(
        'Lendario-74253',
        'Lendário Abelha Rainha',
        'Lendário',
        'for women and men',
        NULL,
        NULL,
        'Pepper',
        'Sea Notes',
        'Cashmere Wood',
        'fresh spicy,marine,woody,aromatic,musky',
        'LendáriobyAbelha Rainhais a Aromatic Fougere fragrance for women and men.Lendáriowas launched in 2020. Top note is Pepper; middle note is Sea Notes; base note is Cashmere Wood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Love-Colors-61355',
        'Love Colors Abelha Rainha',
        'Love',
        'for women',
        NULL,
        NULL,
        'Raspberry, Bergamot and Sicilian Lemon',
        'Gardenia, Jasmine and Rose',
        'Tonka Bean, Sandalowood and Benzoin',
        'citrus,white floral,sweet,fruity,woody',
        'Love ColorsbyAbelha Rainhais a Floral Fruity fragrance for women.Love Colorswas launched in 2019. Top notes are Raspberry, Bergamot and Sicilian Lemon; middle notes are Gardenia, Jasmine and Rose; base notes are Tonka Bean, Sandalowood and Benzoin.',
        4,
        3,
        NULL
      ),
(
        'Madeira-do-Oriente-Intense-74257',
        'Madeira do Oriente Intense Abelha Rainha',
        'Madeira',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Sandalwood',
        'Amberwood',
        'woody,amber,citrus,warm spicy,powdery',
        'Madeira do Oriente IntensebyAbelha Rainhais a Chypre Floral fragrance for women.Madeira do Oriente Intensewas launched in 2020. Top note is Bergamot; middle note is Sandalwood; base note is Amberwood.',
        3,
        1,
        NULL
      ),
(
        'Marcelle-61356',
        'Marcelle Abelha Rainha',
        'Marcelle',
        'for women',
        NULL,
        NULL,
        'Pear',
        'Jasmine',
        'Sandalowood and Hazelnut',
        'white floral,woody,fruity,sweet,nutty',
        'MarcellebyAbelha Rainhais a Floral Fruity fragrance for women.Marcellewas launched in 2018. Top note is Pear; middle note is Jasmine; base notes are Sandalowood and Hazelnut.',
        4.43,
        7,
        NULL
      ),
(
        'Narcizo-61357',
        'Narcizo Abelha Rainha',
        'Narcizo',
        'for men',
        NULL,
        NULL,
        'Black Pepper',
        'Cacao and Sage',
        'Amber and Woodsy Notes',
        'amber,cacao,fresh spicy,warm spicy,aromatic',
        'NarcizobyAbelha Rainhais a Amber Spicy fragrance for men.Narcizowas launched in 2019. Top note is Black Pepper; middle notes are Cacao and Sage; base notes are Amber and Woodsy Notes.',
        3.5,
        4,
        NULL
      ),
(
        'Rubi-Glamour-74254',
        'Rubi Glamour Abelha Rainha',
        'Rubi',
        'for women',
        NULL,
        NULL,
        'Blackberry',
        'Ylang-Ylang',
        'Patchouli',
        'fruity,patchouli,woody,yellow floral,sweet',
        'Rubi GlamourbyAbelha Rainhais a Floral Fruity fragrance for women.Rubi Glamourwas launched in 2017. Top note is Blackberry; middle note is Ylang-Ylang; base note is Patchouli.',
        4.4,
        5,
        NULL
      ),
(
        'Sense-Man-61359',
        'Sense Man Abelha Rainha',
        'Sense',
        'for men',
        NULL,
        NULL,
        'Pomelo, Mint and Mandarin Orange',
        'Cinnamon, Indian Spices and Rose',
        'Leather, Velvet, White Woods and Indonesian Patchouli Leaf',
        'warm spicy,woody,cinnamon,citrus,patchouli',
        'Sense ManbyAbelha Rainhais a Amber Woody fragrance for men.Sense Manwas launched in 2019. Top notes are Pomelo, Mint and Mandarin Orange; middle notes are Cinnamon, Indian Spices and Rose; base notes are Leather, Velvet, White Woods and Indonesian Patchouli Leaf.',
        4,
        3,
        NULL
      ),
(
        'Sense-Woman-61358',
        'Sense Woman Abelha Rainha',
        'Sense',
        'for women',
        NULL,
        NULL,
        'Bergamot, Sage and Lemon',
        'Basil, Pepper, Cypress and Cardamom',
        'Sandalowood, Amber, Cedar, Musk and Vetiver',
        'woody,aromatic,fresh spicy,citrus,amber',
        'Sense WomanbyAbelha Rainhais a Floral fragrance for women.Sense Womanwas launched in 2019. Top notes are Bergamot, Sage and Lemon; middle notes are Basil, Pepper, Cypress and Cardamom; base notes are Sandalowood, Amber, Cedar, Musk and Vetiver.',
        4,
        2,
        NULL
      ),
(
        'Vegas-74258',
        'Vegas Abelha Rainha',
        'Vegas',
        'for men',
        NULL,
        NULL,
        'Citruses and Orange',
        'Black Pepper',
        'Patchouli and Sandalwood',
        'citrus,woody,fresh spicy,warm spicy,patchouli',
        'VegasbyAbelha Rainhais a Woody Aromatic fragrance for men.Vegaswas launched in 2020. Top notes are Citruses and Orange; middle note is Black Pepper; base notes are Patchouli and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Volupia-61360',
        'Volúpia Abelha Rainha',
        'Volúpia',
        'for women',
        NULL,
        NULL,
        'Tangerine and Pear',
        'Rose and Jasmine',
        'Sandalwood, Hazelnut, Patchouli and Vanilla',
        'woody,nutty,citrus,patchouli,warm spicy',
        'VolúpiabyAbelha Rainhais a Floral fragrance for women.Volúpiawas launched in 2020. Top notes are Tangerine and Pear; middle notes are Rose and Jasmine; base notes are Sandalwood, Hazelnut, Patchouli and Vanilla.',
        3.5,
        6,
        NULL
      ),
(
        'K-sual-63445',
        'K|sual Abelha Rainha',
        'K|sual',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Bergamot and Grapefruit',
        'Rosemary, Orange Blossom, Lavender and Thyme',
        'Mimosa, Musk and Sandalwood',
        'citrus,aromatic,fresh spicy,powdery,woody',
        'K|sualbyAbelha Rainhais a Citrus fragrance for women and men.K|sualwas launched in 2008. Top notes are Mandarin Orange, Bergamot and Grapefruit; middle notes are Rosemary, Orange Blossom, Lavender and Thyme; base notes are Mimosa, Musk and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'K-sual-Ela-63447',
        'K|sual Ela Abelha Rainha',
        'K|sual',
        'for women',
        NULL,
        NULL,
        'Citruses and Passion Flower',
        'Passionfruit, Pineapple and Flowers',
        'Sandalwood and Vanilla',
        'fruity,floral,sweet,tropical,fresh',
        'K|sual ElabyAbelha Rainhais a Floral fragrance for women.K|sual Elawas launched in 2010. Top notes are Citruses and Passion Flower; middle notes are Passionfruit, Pineapple and Flowers; base notes are Sandalwood and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'K-sual-Ele-63446',
        'K|sual Ele Abelha Rainha',
        'K|sual',
        'for men',
        NULL,
        NULL,
        'Lavender and Citruses',
        'Thyme and Geranium',
        'Woodsy Notes and Amber',
        'aromatic,fresh spicy,amber,citrus,lavender',
        'K|sual ElebyAbelha Rainhais a Citrus Aromatic fragrance for men.K|sual Elewas launched in 2016. Top notes are Lavender and Citruses; middle notes are Thyme and Geranium; base notes are Woodsy Notes and Amber.',
        1,
        1,
        NULL
      ),
(
        'Madeira-do-Oriente-Classic-63370',
        'Madeira do Oriente Classic Abelha Rainha',
        'Madeira',
        'for men',
        NULL,
        NULL,
        'Oriental notes and Spices',
        'Pepper, Myrrh and Woodsy Notes',
        'Cedar, Musk, Amber and Guaiac Wood',
        'woody,musky,warm spicy,fresh spicy,amber',
        'Madeira do Oriente ClassicbyAbelha Rainhais a Woody fragrance for men.Madeira do Oriente Classicwas launched in 2019. Top notes are Oriental notes and Spices; middle notes are Pepper, Myrrh and Woodsy Notes; base notes are Cedar, Musk, Amber and Guaiac Wood.',
        3.5,
        8,
        NULL
      ),
(
        'Klark-70320',
        'Klark Acqua Di Capri',
        'Klark',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,white floral,aromatic,earthy,powdery',
        'KlarkbyAcqua Di Capriis a fragrance for women and men.',
        3,
        1,
        NULL
      ),
(
        'Lady-70304',
        'Lady Acqua Di Capri',
        'Lady',
        'for women',
        NULL,
        NULL,
        'Pink Pepper and Bergamot',
        'Iris, Palisander Rosewood, Orange Blossom, Jasmine and Frosting [Glacé]',
        'Patchouli and Musk',
        'white floral,sweet,woody,citrus,musky',
        'LadybyAcqua Di Capriis a fragrance for women. Top notes are Pink Pepper and Bergamot; middle notes are Iris, Palisander Rosewood, Orange Blossom, Jasmine and Frosting [Glacé]; base notes are Patchouli and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Creosote-Time-54350',
        'Creosote Time Acidica Perfumes',
        'Creosote',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'smoky,animalic,leather,metallic,fresh',
        'Creosote TimebyAcidica Perfumesis a fragrance for women and men.Creosote Timewas launched in 2016. The nose behind this fragrance is Elena Markova.',
        3.81,
        16,
        NULL
      ),
(
        'Indian-Summer-54355',
        'Indian Summer Acidica Perfumes',
        'Indian',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,herbal,fresh spicy,patchouli',
        'Indian SummerbyAcidica Perfumesis a fragrance for women and men.Indian Summerwas launched in 2016. The nose behind this fragrance is Elena Markova.',
        4.67,
        3,
        NULL
      ),
(
        'Violet-Iris-72592',
        'Violet Iris Acidica Perfumes',
        'Violet',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'powdery,violet,floral,amber,fruity',
        'Violet IrisbyAcidica Perfumesis a Amber Vanilla fragrance for women and men. This is a new fragrance.Violet Iriswas launched in 2022. The nose behind this fragrance is Elena Markova.',
        4,
        11,
        NULL
      ),
(
        '911-54234',
        '911 Acidica Perfumes',
        '911',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,sweet,warm spicy,coffee,cinnamon',
        '911byAcidica Perfumesis a fragrance for women and men.911was launched in 2017. The nose behind this fragrance is Elena Markova.',
        4,
        2,
        NULL
      ),
(
        'Mesoamerica-54235',
        'Mesoamerica Acidica Perfumes',
        'Mesoamerica',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'rose,cacao,warm spicy,woody,amber',
        'MesoamericabyAcidica Perfumesis a fragrance for women and men.Mesoamericawas launched in 2016. The nose behind this fragrance is Elena Markova.',
        4.62,
        8,
        NULL
      ),
(
        'Rosa-Mystica-54237',
        'Rosa Mystica Acidica Perfumes',
        'Rosa',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,amber,rose,soft spicy,fresh spicy',
        'Rosa MysticabyAcidica Perfumesis a Floral Green fragrance for women and men.Rosa Mysticawas launched in 2012. The nose behind this fragrance is Elena Markova.',
        4,
        2,
        NULL
      ),
(
        'Air-Vozduh-54009',
        'Air (Воздух) Acidica Perfumes',
        'Air',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,powdery,rose,white floral',
        'Air (Воздух)byAcidica Perfumesis a Amber Floral fragrance for women and men.Air (Воздух)was launched in 2018. The nose behind this fragrance is Elena Markova.',
        3.71,
        7,
        NULL
      ),
(
        'Blade-Klinok-54142',
        'Blade (Клинок) Acidica Perfumes',
        'Blade',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,woody,citrus,herbal',
        'Blade (Клинок)byAcidica Perfumesis a Citrus fragrance for women and men.Blade (Клинок)was launched in 2018. The nose behind this fragrance is Elena Markova.',
        3.57,
        7,
        NULL
      ),
(
        'Earth-Zemla-54007',
        'Earth (Земля) Acidica Perfumes',
        'Earth',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'clay,earthy,woody,warm spicy,aromatic',
        'Earth (Земля)byAcidica Perfumesis a Woody Aromatic fragrance for women and men.Earth (Земля)was launched in 2018. The nose behind this fragrance is Elena Markova.',
        4,
        7,
        NULL
      ),
(
        'Fire-Ogon-54008',
        'Fire (Огонь) Acidica Perfumes',
        'Fire',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,smoky,aromatic,earthy,amber',
        'Fire (Огонь)byAcidica Perfumesis a Woody Floral Musk fragrance for women and men.Fire (Огонь)was launched in 2018. The nose behind this fragrance is Elena Markova.',
        4,
        5,
        NULL
      ),
(
        'Tree-Derevo-57495',
        'Tree (Дерево) Acidica Perfumes',
        'Tree',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,green,aromatic,balsamic,patchouli',
        'Tree (Дерево)byAcidica Perfumesis a Woody fragrance for women and men.Tree (Дерево)was launched in 2019. The nose behind this fragrance is Elena Markova.',
        4,
        4,
        NULL
      ),
(
        'Water-Voda-54010',
        'Water (Вода) Acidica Perfumes',
        'Water',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,balsamic,conifer,fresh spicy,amber',
        'Water (Вода)byAcidica Perfumesis a Floral Aquatic fragrance for women and men.Water (Вода)was launched in 2018. The nose behind this fragrance is Elena Markova.',
        3.75,
        4,
        NULL
      ),
(
        'Hygge-New-Year-23-78972',
        'Hygge New Year 23 Acidica Perfumes',
        'Hygge',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,fresh,aromatic,aquatic,conifer',
        'Hygge New Year 23byAcidica Perfumesis a Woody fragrance for women and men. This is a new fragrance.Hygge New Year 23was launched in 2023. The nose behind this fragrance is Elena Markova.',
        4,
        1,
        NULL
      ),
(
        'Hygge-New-Year-F-73366',
        'Hygge New Year F Acidica Perfumes',
        'Hygge',
        'for women',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fruity,amber,sweet,sour,fresh',
        'Hygge New Year FbyAcidica Perfumesis a Amber Floral fragrance for women. This is a new fragrance.Hygge New Year Fwas launched in 2022. The nose behind this fragrance is Elena Markova.',
        3,
        1,
        NULL
      ),
(
        'Hygge-New-Year-M-73367',
        'Hygge New Year М Acidica Perfumes',
        'Hygge',
        'for men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,fruity,amber,aromatic,almond',
        'Hygge New Year МbyAcidica Perfumesis a Amber Woody fragrance for men. This is a new fragrance.Hygge New Year Мwas launched in 2022. The nose behind this fragrance is Elena Markova.',
        4,
        3,
        NULL
      ),
(
        'Wings-of-Spring-54342',
        'Wings of Spring Acidica Perfumes',
        'Wings',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,citrus,powdery,musky,white floral',
        'Wings of SpringbyAcidica Perfumesis a fragrance for women and men.Wings of Springwas launched in 2018. The nose behind this fragrance is Elena Markova.',
        3.75,
        4,
        NULL
      ),
(
        'Hygge-New-Year-2023-78970',
        'Hygge New Year (2023) Acidica Perfumes',
        'Hygge',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,animalic,leather,whiskey,sweet',
        'Hygge New Year (2023)byAcidica Perfumesis a Amber Woody fragrance for women and men. This is a new fragrance.Hygge New Year (2023)was launched in 2023. The nose behind this fragrance is Elena Markova.',
        NULL,
        NULL,
        NULL
      ),
(
        'Merowingen-91753',
        'Merowingen Acidica Perfumes',
        'Merowingen',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'powdery,amber,musky,vanilla,ozonic',
        'MerowingenbyAcidica Perfumesis a Aromatic Green fragrance for women and men. This is a new fragrance.Merowingenwas launched in 2024. The nose behind this fragrance is Elena Markova.',
        5,
        2,
        NULL
      ),
(
        'Misty-Samhain-54210',
        'Misty Samhain Acidica Perfumes',
        'Misty',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,soft spicy,green,musky',
        'Misty SamhainbyAcidica Perfumesis a fragrance for women and men.Misty Samhainwas launched in 2011. The nose behind this fragrance is Elena Markova.',
        4.4,
        10,
        NULL
      ),
(
        'Moon-of-Honey-54231',
        'Moon of Honey Acidica Perfumes',
        'Moon',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'sweet,herbal,fresh spicy,floral,amber',
        'Moon of HoneybyAcidica Perfumesis a fragrance for women and men.Moon of Honeywas launched in 2016. The nose behind this fragrance is Elena Markova.',
        4.12,
        8,
        NULL
      ),
(
        'Northern-Magic-54228',
        'Northern Magic Acidica Perfumes',
        'Northern',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'anis,fruity,fresh,soft spicy,fresh spicy',
        'Northern MagicbyAcidica Perfumesis a fragrance for women and men.Northern Magicwas launched in 2017. The nose behind this fragrance is Elena Markova.',
        3.8,
        5,
        NULL
      ),
(
        'Roads-of-Ladoga-54229',
        'Roads of Ladoga Acidica Perfumes',
        'Roads',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fresh spicy,woody,amber,musky,aromatic',
        'Roads of LadogabyAcidica Perfumesis a fragrance for women and men.Roads of Ladogawas launched in 2016. The nose behind this fragrance is Elena Markova.',
        3.83,
        12,
        NULL
      ),
(
        'The-Dark-Path-54230',
        'The Dark Path Acidica Perfumes',
        'The',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'lavender,amber,musky,powdery,aromatic',
        'The Dark PathbyAcidica Perfumesis a fragrance for women and men.The Dark Pathwas launched in 2016. The nose behind this fragrance is Elena Markova.',
        3.71,
        7,
        NULL
      ),
(
        'Tree-s-Blood-54233',
        'Tree''s Blood Acidica Perfumes',
        'Tree''s',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,green,fresh spicy,herbal,soft spicy',
        'Tree''s BloodbyAcidica Perfumesis a fragrance for women and men.Tree''s Bloodwas launched in 2017. The nose behind this fragrance is Elena Markova.',
        4.07,
        15,
        NULL
      ),
(
        'Amber-Labyrinth-63372',
        'Amber Labyrinth Acidica Perfumes',
        'Amber',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'lactonic,amber,vanilla,powdery,sweet',
        'Amber LabyrinthbyAcidica Perfumesis a Amber Floral fragrance for women and men.Amber Labyrinthwas launched in 2020. The nose behind this fragrance is Elena Markova.',
        4,
        6,
        NULL
      ),
(
        'Helleborus-58661',
        'Helleborus Acidica Perfumes',
        'Helleborus',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fresh,green,white floral,citrus,floral',
        'HelleborusbyAcidica Perfumesis a Floral Woody Musk fragrance for women and men.Helleboruswas launched in 2019. The nose behind this fragrance is Elena Markova.',
        4.27,
        11,
        NULL
      ),
(
        'Monarda-Obscura-63371',
        'Monarda Obscura Acidica Perfumes',
        'Monarda',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'rose,aromatic,green,citrus,fruity',
        'Monarda ObscurabyAcidica Perfumesis a Floral Fruity fragrance for women and men.Monarda Obscurawas launched in 2020. The nose behind this fragrance is Elena Markova.',
        3.86,
        7,
        NULL
      ),
(
        'Rose-Cider-58662',
        'Rose Cider Acidica Perfumes',
        'Rose',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'rose,wine,floral,fruity,sweet',
        'Rose CiderbyAcidica Perfumesis a Floral Fruity fragrance for women and men.Rose Ciderwas launched in 2019. The nose behind this fragrance is Elena Markova.',
        4.14,
        7,
        NULL
      ),
(
        'Summer-is-Back-57496',
        'Summer is Back Acidica Perfumes',
        'Summer',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'lactonic,green,ozonic,fresh,fruity',
        'Summer is BackbyAcidica Perfumesis a Aromatic Green fragrance for women and men.Summer is Backwas launched in 2019. The nose behind this fragrance is Elena Markova.',
        4,
        10,
        NULL
      ),
(
        'Winter-Forest-Zimnij-les-59091',
        'Winter Forest (Зимний лес) Acidica Perfumes',
        'Winter',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,aquatic,aromatic,green,fruity',
        'Winter Forest (Зимний лес)byAcidica Perfumesis a Woody Aromatic fragrance for women and men.Winter Forest (Зимний лес)was launched in 2020. The nose behind this fragrance is Elena Markova.',
        4.19,
        16,
        NULL
      ),
(
        '8-Jewels-Tea-54209',
        '8 Jewels Tea Acidica Perfumes',
        '8',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fruity,floral,green,fresh,lactonic',
        '8 Jewels TeabyAcidica Perfumesis a fragrance for women and men.8 Jewels Teawas launched in 2017. The nose behind this fragrance is Elena Markova.',
        3.6,
        5,
        NULL
      ),
(
        'Boston-Tea-Party-54208',
        'Boston Tea Party Acidica Perfumes',
        'Boston',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'smoky,leather,woody,animalic',
        'Boston Tea PartybyAcidica Perfumesis a fragrance for women and men.Boston Tea Partywas launched in 2016. The nose behind this fragrance is Elena Markova.',
        4.33,
        6,
        NULL
      ),
(
        'Ginger-Tea-54207',
        'Ginger Tea Acidica Perfumes',
        'Ginger',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'citrus,floral,warm spicy,woody,soft spicy',
        'Ginger TeabyAcidica Perfumesis a fragrance for women and men.Ginger Teawas launched in 2016. The nose behind this fragrance is Elena Markova.',
        4.55,
        11,
        NULL
      ),
(
        'Marsala-Shai-54143',
        'Marsala Сhai Acidica Perfumes',
        'Marsala',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'citrus,woody,sweet,powdery,vanilla',
        'Marsala СhaibyAcidica Perfumesis a Amber fragrance for women and men.Marsala Сhaiwas launched in 2016. The nose behind this fragrance is Elena Markova.',
        4.25,
        4,
        NULL
      ),
(
        'Alba-54238',
        'Alba Acidica Perfumes',
        'Alba',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'white floral,yellow floral,sweet,woody,floral',
        'AlbabyAcidica Perfumesis a fragrance for women and men.Albawas launched in 2018. The nose behind this fragrance is Elena Markova.',
        4,
        5,
        NULL
      ),
(
        'Harem-54330',
        'Harem Acidica Perfumes',
        'Harem',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'warm spicy,yellow floral,white floral,woody,sweet',
        'HarembyAcidica Perfumesis a Amber fragrance for women and men.Haremwas launched in 2018. The nose behind this fragrance is Elena Markova.',
        4,
        7,
        NULL
      ),
(
        'In-Love-54339',
        'In Love Acidica Perfumes',
        'In',
        'for women',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'white floral,lactonic,tuberose,animalic',
        'In LovebyAcidica Perfumesis a Floral fragrance for women.In Lovewas launched in 2018. The nose behind this fragrance is Elena Markova.',
        4.67,
        6,
        NULL
      ),
(
        'Slovenian-Wine-54341',
        'Slovenian Wine Acidica Perfumes',
        'Slovenian',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fruity,woody,sweet,aromatic,green',
        'Slovenian WinebyAcidica Perfumesis a fragrance for women and men.Slovenian Winewas launched in 2018. The nose behind this fragrance is Elena Markova.',
        4,
        6,
        NULL
      ),
(
        'Vrema-kreozota-2021-78962',
        'Время креозота (2021) Acidica Perfumes',
        'Время',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'metallic,mineral,smoky,fresh,earthy',
        'Время креозота (2021)byAcidica Perfumesis a Leather fragrance for women and men.Время креозота (2021)was launched in 2021. The nose behind this fragrance is Elena Markova.',
        4,
        3,
        NULL
      ),
(
        'Love-U-Kill-U-91759',
        'Love U/Kill U Acidica Perfumes',
        'Love',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'citrus,amber,vanilla,powdery,musky',
        'Love U/Kill UbyAcidica Perfumesis a fragrance for women and men. This is a new fragrance.Love U/Kill Uwas launched in 2023. The nose behind this fragrance is Elena Markova.',
        4.2,
        5,
        NULL
      ),
(
        'Vladyka-cernykh-vod-91754',
        'Владыка черных вод Acidica Perfumes',
        'Владыка',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,aquatic,conifer,green',
        'Владыка черных водbyAcidica Perfumesis a fragrance for women and men. This is a new fragrance.Владыка черных водwas launched in 2024. The nose behind this fragrance is Elena Markova.',
        3.2,
        5,
        NULL
      ),
(
        'Zabud-o-sozaleniakh-91755',
        'Забудь о сожалениях Acidica Perfumes',
        'Забудь',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,green,floral,citrus,powdery',
        'Забудь о сожаленияхbyAcidica Perfumesis a fragrance for women and men. This is a new fragrance.Забудь о сожаленияхwas launched in 2023. The nose behind this fragrance is Elena Markova.',
        4,
        4,
        NULL
      ),
(
        'Neprevzojdennyj-ogurec-91757',
        'Непревзойденный огурец Acidica Perfumes',
        'Непревзойденный',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,green,ozonic,aromatic,aquatic',
        'Непревзойденный огурецbyAcidica Perfumesis a fragrance for women and men. This is a new fragrance.Непревзойденный огурецwas launched in 2024.',
        3.67,
        3,
        NULL
      ),
(
        'Obrazcovyj-nastavnik-91756',
        'Образцовый наставник Acidica Perfumes',
        'Образцовый',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'musky,almond,floral,green,powdery',
        'Образцовый наставникbyAcidica Perfumesis a fragrance for women and men. This is a new fragrance.Образцовый наставникwas launched in 2023. The nose behind this fragrance is Elena Markova.',
        3.5,
        2,
        NULL
      ),
(
        'Etot-Dostopoctennyj-91758',
        'Этот Достопочтенный Acidica Perfumes',
        'Этот',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'metallic,mineral,musky,vanilla,powdery',
        'Этот ДостопочтенныйbyAcidica Perfumesis a fragrance for women and men. This is a new fragrance.Этот Достопочтенныйwas launched in 2023. The nose behind this fragrance is Elena Markova.',
        2.5,
        2,
        NULL
      ),
(
        'Ginger-tea-2021-78963',
        'Ginger tea (2021) Acidica Perfumes',
        'Ginger',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'citrus,green,floral,woody,white floral',
        'Ginger tea (2021)byAcidica Perfumesis a Aromatic Green fragrance for women and men.Ginger tea (2021)was launched in 2021. The nose behind this fragrance is Elena Markova.',
        NULL,
        NULL,
        NULL
      ),
(
        'Mesoamerica-2021-78965',
        'Mesoamerica (2021) Acidica Perfumes',
        'Mesoamerica',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fresh spicy,citrus,woody,rose,musky',
        'Mesoamerica (2021)byAcidica Perfumesis a Amber Vanilla fragrance for women and men.Mesoamerica (2021)was launched in 2021. The nose behind this fragrance is Elena Markova.',
        NULL,
        NULL,
        NULL
      ),
(
        'Dorogi-Ladogi-Roads-of-Ladoga-2022-78968',
        'Дороги Ладоги (Roads of Ladoga) (2022) Acidica Perfumes',
        'Дороги',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,amber,aromatic,green,fresh spicy',
        'Дороги Ладоги (Roads of Ladoga) (2022)byAcidica Perfumesis a Woody Aromatic fragrance for women and men. This is a new fragrance.Дороги Ладоги (Roads of Ladoga) (2022)was launched in 2022. The nose behind this fragrance is Elena Markova.',
        3.67,
        3,
        NULL
      ),
(
        'Misticeskaa-roza-Rosa-mystica-2022-78969',
        'Мистическая роза (Rosa mystica) (2022) Acidica Perfumes',
        'Мистическая',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'warm spicy,fruity,woody,floral,rose',
        'Мистическая роза (Rosa mystica) (2022)byAcidica Perfumesis a Amber Floral fragrance for women and men. This is a new fragrance.Мистическая роза (Rosa mystica) (2022)was launched in 2022. The nose behind this fragrance is Elena Markova.',
        3.33,
        3,
        NULL
      ),
(
        'Tumany-Samajna-Misty-Samhain-2021-78964',
        'Туманы Самайна (Misty Samhain) (2021) Acidica Perfumes',
        'Туманы',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,citrus,aromatic,musky,fresh spicy',
        'Туманы Самайна (Misty Samhain) (2021)byAcidica Perfumesis a Amber Woody fragrance for women and men.Туманы Самайна (Misty Samhain) (2021)was launched in 2021. The nose behind this fragrance is Elena Markova.',
        4.33,
        3,
        NULL
      ),
(
        'Caj-8-dragocennostej-8-jewels-tea-2022-78967',
        'Чай 8 драгоценностей (8 jewels tea) (2022) Acidica Perfumes',
        'Чай',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'fruity,woody,sweet,floral,amber',
        'Чай 8 драгоценностей (8 jewels tea) (2022)byAcidica Perfumesis a Aromatic Fruity fragrance for women and men. This is a new fragrance.Чай 8 драгоценностей (8 jewels tea) (2022)was launched in 2022. The nose behind this fragrance is Elena Markova.',
        3,
        2,
        NULL
      ),
(
        'Avenue-of-Desires-54351',
        'Avenue of Desires Acidica Perfumes',
        'Avenue',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,fresh spicy,conifer,fresh',
        'Avenue of DesiresbyAcidica Perfumesis a fragrance for women and men.Avenue of Desireswas launched in 2017. The nose behind this fragrance is Elena Markova.',
        4.5,
        2,
        NULL
      ),
(
        'Hygge-New-Year-58957',
        'Hygge New Year Acidica Perfumes',
        'Hygge',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'sweet,leather,woody,balsamic,honey',
        'Hygge New YearbyAcidica Perfumesis a Amber Vanilla fragrance for women and men.Hygge New Yearwas launched in 2019. The nose behind this fragrance is Elena Markova.',
        4.67,
        9,
        NULL
      ),
(
        'Ice-And-Flames-54356',
        'Ice And Flames Acidica Perfumes',
        'Ice',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        NULL,
        'Ice And FlamesbyAcidica Perfumesis a fragrance for women and men.Ice And Flameswas launched in 2018. The nose behind this fragrance is Elena Markova.',
        4,
        1,
        NULL
      ),
(
        'La-Femme-Amoureuse-54354',
        'La Femme Amoureuse Acidica Perfumes',
        'La',
        'for women',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,woody,amber,yellow floral',
        'La Femme AmoureusebyAcidica Perfumesis a fragrance for women.La Femme Amoureusewas launched in 2016. The nose behind this fragrance is Elena Markova.',
        5,
        1,
        NULL
      ),
(
        'Petals-of-pale-rose-58959',
        'Petals of pale rose Acidica Perfumes',
        'Petals',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,fresh spicy,powdery,woody',
        'Petals of pale rosebyAcidica Perfumesis a Floral Woody Musk fragrance for women and men.Petals of pale rosewas launched in 2019. The nose behind this fragrance is Elena Markova.',
        4,
        3,
        NULL
      ),
(
        'Second-Skin-54236',
        'Second Skin Acidica Perfumes',
        'Second',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,amber,iris,rose,powdery',
        'Second SkinbyAcidica Perfumesis a fragrance for women and men.Second Skinwas launched in 2017. The nose behind this fragrance is Elena Markova.',
        3.67,
        3,
        NULL
      ),
(
        'Snowless-winter-Bessneznaa-zima-58958',
        'Snowless winter (Бесснежная зима) Acidica Perfumes',
        'Snowless',
        'for women and men',
        NULL,
        'Elena Markova',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,green,patchouli,citrus',
        'Snowless winter (Бесснежная зима)byAcidica Perfumesis a Woody Aromatic fragrance for women and men.Snowless winter (Бесснежная зима)was launched in 2019. The nose behind this fragrance is Elena Markova.',
        4,
        4,
        NULL
      ),
(
        'Acqua-Fiorentina-56133',
        'Acqua Fiorentina Acqua di Firenze',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Angelica and Pink Pepper',
        'Violet, Iris, Freesia, Rose, Acácia, Gardenia, Verbena and Orchid',
        'Patchouli, Labdanum and Musk',
        'floral,powdery,musky,citrus,amber',
        'Acqua FiorentinabyAcqua di Firenzeis a Chypre Floral fragrance for women and men. Top notes are Bergamot, Angelica and Pink Pepper; middle notes are Violet, Iris, Freesia, Rose, Acácia, Gardenia, Verbena and Orchid; base notes are Patchouli, Labdanum and Musk.',
        2,
        3,
        NULL
      ),
(
        'Anima-Mundi-56134',
        'Anima Mundi Acqua di Firenze',
        'Anima',
        'for women and men',
        NULL,
        NULL,
        'Pink Grapefruit, elemi and Pink Pepper',
        'Lotus, Rose, Water Lily, Peach Blossom, Cornflower or Sultan seeds, Lemon Verbena, Broom and Sweet Orange',
        'Sandalwood, Cashmere Wood, Haitian Vetiver, White Amber and Musk',
        'floral,citrus,woody,aromatic,musky',
        'Anima MundibyAcqua di Firenzeis a Floral Woody Musk fragrance for women and men. Top notes are Pink Grapefruit, elemi and Pink Pepper; middle notes are Lotus, Rose, Water Lily, Peach Blossom, Cornflower or Sultan seeds, Lemon Verbena, Broom and Sweet Orange; base notes are Sandalwood, Cashmere Wood, Haitian Vetiver, White Amber and Musk.',
        1,
        2,
        NULL
      ),
(
        'Bacio-56135',
        'Bacio Acqua di Firenze',
        'Bacio',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Carnation and Labdanum',
        'Rose, Lemon Verbena, Carnation, Gardenia, Peony, Violet, Jasmine and Orchid',
        'Sandalwood, Leather, Musk, Vetiver, Patchouli and Amber',
        'citrus,rose,floral,aromatic,woody',
        'BaciobyAcqua di Firenzeis a Floral Woody Musk fragrance for women and men. Top notes are Lemon, Carnation and Labdanum; middle notes are Rose, Lemon Verbena, Carnation, Gardenia, Peony, Violet, Jasmine and Orchid; base notes are Sandalwood, Leather, Musk, Vetiver, Patchouli and Amber.',
        2.8,
        5,
        NULL
      ),
(
        'Homo-Novus-56136',
        'Homo Novus Acqua di Firenze',
        'Homo',
        'for women and men',
        NULL,
        NULL,
        'Cypriol Oil or Nagarmotha, Labdanum, Liquidambar and Bergamot',
        'Rose, Iris, Gardenia, Acácia, Ylang-Ylang, Jasmine, Violet and Carnation',
        'Agarwood (Oud), Sandalwood, Amber, Guaiac Wood, Patchouli, Vetiver, Brandy and Musk',
        'woody,amber,oud,earthy,powdery',
        'Homo NovusbyAcqua di Firenzeis a Woody Floral Musk fragrance for women and men. Top notes are Cypriol Oil or Nagarmotha, Labdanum, Liquidambar and Bergamot; middle notes are Rose, Iris, Gardenia, Acácia, Ylang-Ylang, Jasmine, Violet and Carnation; base notes are Agarwood (Oud), Sandalwood, Amber, Guaiac Wood, Patchouli, Vetiver, Brandy and Musk.',
        3.56,
        9,
        NULL
      );
