
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Majestic-Femme-27371',
        'Majestic Femme Afnan',
        'Majestic',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Majestic FemmebyAfnanis a fragrance for women.Majestic Femmewas launched in 2014.',
        4,
        1,
        NULL
      ),
(
        'Vanille-23445',
        'Vanille Adopt Parfums',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,sweet',
        'VanillebyAdopt Parfumsis a Amber Vanilla fragrance for women.',
        3.57,
        47,
        NULL
      ),
(
        'Attar-Mubakhar-Silver-19858',
        'Attar Mubakhar Silver Al Haramain Perfumes',
        'Attar',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,floral,powdery,woody,musky',
        'Attar Mubakhar SilverbyAl Haramain Perfumesis a Amber fragrance for men.',
        4.25,
        4,
        NULL
      ),
(
        'Aqua-di-Fiori-Hypnotique-51116',
        'Aqua di Fiori Hypnotique Parfums Genty',
        'Aqua',
        'for women',
        NULL,
        NULL,
        'Peony, Tea and Peach',
        'Musk, Lilac and Amber',
        'Osmanthus and Cedar',
        'floral,fresh,green,rose,musky',
        'Aqua di Fiori HypnotiquebyParfums Gentyis a Floral Fruity fragrance for women. Top notes are Peony, Tea and Peach; middle notes are Musk, Lilac and Amber; base notes are Osmanthus and Cedar.',
        3.66,
        35,
        NULL
      ),
(
        'Santo-Domingo-16193',
        'Santo Domingo Oscar de la Renta',
        'Santo',
        'for women and men',
        NULL,
        'Calice Becker',
        NULL,
        NULL,
        NULL,
        'tobacco,warm spicy,aromatic,patchouli,sweet',
        'Santo DomingobyOscar de la Rentais a Woody Spicy fragrance for women and men.Santo Domingowas launched in 2012. The nose behind this fragrance is Calice Becker.',
        4.25,
        64,
        NULL
      ),
(
        'Baby-Rose-19863',
        'Baby Rose Al Haramain Perfumes',
        'Baby',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,woody,fruity,amber,powdery',
        'Baby RosebyAl Haramain Perfumesis a Floral fragrance for women.',
        3.33,
        9,
        NULL
      ),
(
        'La-Fleur-Bouquet-70707',
        'La Fleur Bouquet Afnan',
        'La',
        'for women',
        NULL,
        NULL,
        'White Flowers and Flowers',
        'Fruits, Citruses and Musk',
        'Sweet Notes, Powdery Notes, Rose and Exotic Woods',
        'sweet,fruity,floral,white floral,powdery',
        'La Fleur BouquetbyAfnanis a Floral fragrance for women.La Fleur Bouquetwas launched in 2021. Top notes are White Flowers and Flowers; middle notes are Fruits, Citruses and Musk; base notes are Sweet Notes, Powdery Notes, Rose and Exotic Woods.',
        3.98,
        167,
        NULL
      ),
(
        'Souvenir-Floral-Bouquet-71179',
        'Souvenir Floral Bouquet Afnan',
        'Souvenir',
        'for women',
        NULL,
        NULL,
        'Rhubarb, Litchi and Bergamot',
        'Rose, Vanilla, Peony and Lily-of-the-Valley',
        'Musk, Amber and Cashmere Wood',
        'rose,musky,floral,fruity,fresh',
        'Souvenir Floral BouquetbyAfnanis a Floral Fruity fragrance for women.Souvenir Floral Bouquetwas launched in 2020. Top notes are Rhubarb, Litchi and Bergamot; middle notes are Rose, Vanilla, Peony and Lily-of-the-Valley; base notes are Musk, Amber and Cashmere Wood.',
        3.86,
        287,
        NULL
      ),
(
        'Al-Haramain-Collection-Gold-19854',
        'Al Haramain Collection Gold Al Haramain Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,vanilla,powdery,floral,oud',
        'Al Haramain Collection GoldbyAl Haramain Perfumesis a fragrance for women and men.',
        4.11,
        19,
        NULL
      ),
(
        'Red-Dress-59938',
        'Red Dress Adopt Parfums',
        'Red',
        'for women',
        NULL,
        NULL,
        'Tangerine, Freesia and Black Currant',
        'Patchouli and May Rose',
        'Vanilla and White Woods',
        'patchouli,woody,citrus,floral,fruity',
        'Red DressbyAdopt Parfumsis a fragrance for women. Top notes are Tangerine, Freesia and Black Currant; middle notes are Patchouli and May Rose; base notes are Vanilla and White Woods.',
        4.04,
        23,
        NULL
      ),
(
        'Soleil-de-Minuit-48995',
        'Soleil de Minuit Ed Pinaud',
        'Soleil',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Citron and Petitgrain',
        'Orange Blossom, Almond and Juniper',
        'Cypress, Galbanum and Cedar',
        'aromatic,citrus,woody,fresh spicy,green',
        'Soleil de MinuitbyEd Pinaudis a fragrance for women and men.Soleil de Minuitwas launched in 2018. Top notes are Bergamot, Citron and Petitgrain; middle notes are Orange Blossom, Almond and Juniper; base notes are Cypress, Galbanum and Cedar.',
        NULL,
        NULL,
        NULL
      ),
(
        'Maryam-51825',
        'Maryam Al Haramain Perfumes',
        'Maryam',
        'for women',
        NULL,
        NULL,
        'Black Pepper, Cardamom and Saffron',
        'Driftwood, Sandalwood and Magnolia',
        'Musk and Amber',
        'warm spicy,fresh spicy,woody,musky,powdery',
        'MaryambyAl Haramain Perfumesis a Amber Floral fragrance for women.Maryamwas launched in 2018. Top notes are Black Pepper, Cardamom and Saffron; middle notes are Driftwood, Sandalwood and Magnolia; base notes are Musk and Amber.',
        3.67,
        30,
        NULL
      ),
(
        'Peach-78928',
        'Peach Max Philip',
        'Peach',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,fruity,warm spicy,citrus,sweet',
        'PeachbyMax Philipis a Woody Floral Musk fragrance for women and men. This is a new fragrance.Peachwas launched in 2022.',
        3.31,
        74,
        NULL
      ),
(
        'Intimate-Vanilla-9187',
        'Intimate Vanilla Neil Morris',
        'Intimate',
        'for women and men',
        NULL,
        'Neil Morris',
        'Lotus and Bergamot',
        'Green Tea and Jasmine',
        'Vanille, Madagascar Vanilla, Incense, Musk and Amber',
        'floral,vanilla,ozonic,white floral,aquatic',
        'Intimate VanillabyNeil Morrisis a Amber Vanilla fragrance for women and men.Intimate Vanillawas launched in 2000. The nose behind this fragrance is Neil Morris. Top notes are Lotus and Bergamot; middle notes are Green Tea and Jasmine; base notes are Vanille, Madagascar Vanilla, Incense, Musk and Amber.',
        4.06,
        16,
        NULL
      ),
(
        'Oceanic-Hotel-Nice-16357',
        'Oceanic Hotel Nice Outremer',
        'Oceanic',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,citrus,marine,aromatic,fresh',
        'Oceanic Hotel NicebyOutremeris a Citrus Aromatic fragrance for women and men.',
        3.6,
        5,
        NULL
      ),
(
        'Rose-Jasmin-23448',
        'Rose Jasmin Adopt Parfums',
        'Rose',
        'for women',
        NULL,
        NULL,
        'Rose and Jasmine',
        'Rose and Jasmine',
        'Vanilla',
        'rose,white floral,floral,vanilla',
        'Rose JasminbyAdopt Parfumsis a Floral fragrance for women. Top notes are Rose and Jasmine; middle notes are Rose and Jasmine; base note is Vanilla.',
        3.4,
        5,
        NULL
      ),
(
        'Otto-Kern-Man-2185',
        'Otto Kern Man Otto Kern',
        'Otto',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange and Neroli',
        'Ginger, Orange Blossom and Pepper',
        'Sandalwood, Musk and Vetiver',
        'citrus,woody,warm spicy,white floral,fresh spicy',
        'Otto Kern ManbyOtto Kernis a Aromatic Spicy fragrance for men.Otto Kern Manwas launched in 2006. Top notes are Mandarin Orange and Neroli; middle notes are Ginger, Orange Blossom and Pepper; base notes are Sandalwood, Musk and Vetiver.',
        4,
        5,
        NULL
      ),
(
        'Constellation-13207',
        'Constellation Paloma Picasso',
        'Constellation',
        'for women',
        NULL,
        NULL,
        'Neroli, Citruses and Bergamot',
        'Rose, Jasmine, Ylang-Ylang and Coriander',
        'oak moss, Patchouli, Vetiver and Amber',
        'woody,rose,earthy,white floral,aromatic',
        'ConstellationbyPaloma Picassois a Chypre Floral fragrance for women. Top notes are Neroli, Citruses and Bergamot; middle notes are Rose, Jasmine, Ylang-Ylang and Coriander; base notes are oak moss, Patchouli, Vetiver and Amber.',
        4.32,
        41,
        NULL
      ),
(
        'Al-Quimmah-19856',
        'Al Quimmah Al Haramain Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,woody,rose,powdery,warm spicy',
        'Al QuimmahbyAl Haramain Perfumesis a Amber fragrance for women and men.',
        4.33,
        3,
        NULL
      ),
(
        'Kaheela-Platinum-95266',
        'Kaheela Platinum Paris Corner',
        'Kaheela',
        'for women and men',
        NULL,
        NULL,
        'Mint, Bergamot and Lemon',
        'Lavender, Orange Blossom and Cardamom',
        'Tonka Bean, Vanilla and Amber',
        'green,aromatic,fresh spicy,citrus',
        'Kaheela PlatinumbyParis Corneris a fragrance for women and men. Top notes are Mint, Bergamot and Lemon; middle notes are Lavender, Orange Blossom and Cardamom; base notes are Tonka Bean, Vanilla and Amber.',
        4.6,
        10,
        NULL
      ),
(
        'Bare-Vanilla-Candied-89298',
        'Bare Vanilla Candied Victoria''s Secret',
        'Bare',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,powdery,fruity',
        'Bare Vanilla CandiedbyVictoria''s Secretis a Amber Vanilla fragrance for women. This is a new fragrance.Bare Vanilla Candiedwas launched in 2023.',
        4.48,
        66,
        NULL
      ),
(
        'Otto-Kern-Intense-88149',
        'Otto Kern Intense Otto Kern',
        'Otto',
        'for men',
        NULL,
        NULL,
        'Apple, Cardamom and Lemon',
        'Lavender, Pimento Seeds and Geranium',
        'Vanilla, Chestnut and Sandalwood',
        'warm spicy,lavender,aromatic,vanilla,fruity',
        'Otto Kern IntensebyOtto Kernis a Woody Spicy fragrance for men. This is a new fragrance.Otto Kern Intensewas launched in 2023. Top notes are Apple, Cardamom and Lemon; middle notes are Lavender, Pimento Seeds and Geranium; base notes are Vanilla, Chestnut and Sandalwood.',
        4,
        5,
        NULL
      ),
(
        'Oud-75218',
        'Oud Naseem',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Agarwood (Oud), Lavender and Spicy Notes',
        'Floral Notes, Incense and Cedar',
        'Agarwood (Oud), Moss and Ambergris',
        'oud,floral,amber,woody,fresh spicy',
        'OudbyNaseemis a Amber Floral fragrance for women and men. This is a new fragrance.Oudwas launched in 2022. Top notes are Agarwood (Oud), Lavender and Spicy Notes; middle notes are Floral Notes, Incense and Cedar; base notes are Agarwood (Oud), Moss and Ambergris.',
        4.57,
        14,
        NULL
      ),
(
        'Marjan-19812',
        'Marjan Al Haramain Perfumes',
        'Marjan',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,aromatic,amber,floral',
        'MarjanbyAl Haramain Perfumesis a Woody Spicy fragrance for women and men.',
        3.53,
        30,
        NULL
      ),
(
        'Supremacy-Gala-92430',
        'Supremacy Gala Afnan',
        'Supremacy',
        'for women',
        NULL,
        NULL,
        'Pear Blossom, Mandarin Orange and Red Berries',
        'Frangipani, Gardenia and Honeysuckle',
        'Patchouli, Caramel, Praline, Brown sugar and Vanilla',
        'floral,white floral,lactonic,patchouli,sweet',
        'Supremacy GalabyAfnanis a Amber Floral fragrance for women. This is a new fragrance.Supremacy Galawas launched in 2023. Top notes are Pear Blossom, Mandarin Orange and Red Berries; middle notes are Frangipani, Gardenia and Honeysuckle; base notes are Patchouli, Caramel, Praline, Brown sugar and Vanilla.',
        4.09,
        11,
        NULL
      ),
(
        'Rose-Taifi-19822',
        'Rose Taifi Al Haramain Perfumes',
        'Rose',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,powdery',
        'Rose TaifibyAl Haramain Perfumesis a Floral fragrance for women and men.',
        4.3,
        20,
        NULL
      ),
(
        'C-Style-40785',
        'C Style Oud Elite',
        'C',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'C StylebyOud Eliteis a fragrance for men.C Stylewas launched during the 2010''s.',
        4,
        4,
        NULL
      ),
(
        'Highness-IX-78432',
        'Highness IX Afnan',
        'Highness',
        'for women and men',
        NULL,
        NULL,
        'Musk, Nutmeg and Rose',
        'Powdery Notes, Amber and Orange Blossom',
        'Pineapple blossom, Peach and Apple Blossom',
        'powdery,musky,fruity,floral,amber',
        'Highness IXbyAfnanis a Floral Woody Musk fragrance for women and men.Highness IXwas launched during the 2010''s. Top notes are Musk, Nutmeg and Rose; middle notes are Powdery Notes, Amber and Orange Blossom; base notes are Pineapple blossom, Peach and Apple Blossom.',
        3.67,
        6,
        NULL
      ),
(
        'A-Chaos-In-The-Ocean-84528',
        'A Chaos In The Ocean Paris Corner',
        'A',
        'for men',
        NULL,
        NULL,
        'Bergamot and Lemon',
        'Seaweed, Calone and Hedione',
        'Musk, Ambroxan and Cedar',
        'musky,marine,fresh,aquatic,citrus',
        'A Chaos In The OceanbyParis Corneris a Aromatic Aquatic fragrance for men. This is a new fragrance.A Chaos In The Oceanwas launched in 2023. Top notes are Bergamot and Lemon; middle notes are Seaweed, Calone and Hedione; base notes are Musk, Ambroxan and Cedar.',
        4.01,
        126,
        NULL
      ),
(
        'The-Vert-23446',
        'Thé Vert Adopt Parfums',
        'Thé',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Lemon, Orange and Anise',
        'Green Tea and Rose',
        'Tobacco and Woody Notes',
        'citrus,green,fresh,fresh spicy,ozonic',
        'Thé VertbyAdopt Parfumsis a Citrus Aromatic fragrance for women and men. Top notes are Grapefruit, Lemon, Orange and Anise; middle notes are Green Tea and Rose; base notes are Tobacco and Woody Notes.',
        3.85,
        65,
        NULL
      ),
(
        'Ma-Joie-Camille-75916',
        'Ma Joie Camille Antos Cosmesi Naturale',
        'Ma',
        'for women',
        NULL,
        NULL,
        'Rose',
        'Violet and Jasmine',
        'Peach Blossom',
        'floral,rose,violet,white floral,powdery',
        'Ma Joie CamillebyAntos Cosmesi Naturaleis a fragrance for women. Top note is Rose; middle notes are Violet and Jasmine; base note is Peach Blossom.',
        NULL,
        NULL,
        NULL
      ),
(
        'Alto-Mare-24036',
        'Alto Mare Parfums Genty',
        'Alto',
        'for men',
        NULL,
        NULL,
        'Ginger and Pepper',
        'Basil, Sage and Cedar',
        'Suede, Palisander Rosewood, Patchouli and Amber',
        'warm spicy,woody,fresh spicy,aromatic,herbal',
        'Alto MarebyParfums Gentyis a Aromatic Fougere fragrance for men.Alto Marewas launched in 2007. Top notes are Ginger and Pepper; middle notes are Basil, Sage and Cedar; base notes are Suede, Palisander Rosewood, Patchouli and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Otto-Kern-Woman-2184',
        'Otto Kern Woman Otto Kern',
        'Otto',
        'for women',
        NULL,
        NULL,
        'Rhubarb, Cardamom and Bergamot',
        'Orange Blossom and Heliotrope',
        'Amber, Tonka Bean and Vanilla',
        'aromatic,vanilla,green,sweet,white floral',
        'Otto Kern WomanbyOtto Kernis a Amber Floral fragrance for women.Otto Kern Womanwas launched in 2006. Top notes are Rhubarb, Cardamom and Bergamot; middle notes are Orange Blossom and Heliotrope; base notes are Amber, Tonka Bean and Vanilla.',
        4,
        14,
        NULL
      ),
(
        'Treewitch-Appalachia-78242',
        'Treewitch Appalachia TRNP',
        'Treewitch',
        'for women and men',
        NULL,
        'Teone Reinthal',
        NULL,
        NULL,
        NULL,
        'woody,amber,aromatic,balsamic,warm spicy',
        'Treewitch AppalachiabyTRNPis a fragrance for women and men. The nose behind this fragrance is Teone Reinthal.',
        4.33,
        9,
        NULL
      ),
(
        'Mouse-King-52746',
        'Mouse King Latherati',
        'Mouse',
        'for women and men',
        NULL,
        'Julie Grogan',
        NULL,
        NULL,
        NULL,
        'aldehydic,citrus,fresh,amber,musky',
        'Mouse KingbyLatheratiis a Chypre Fruity fragrance for women and men.Mouse Kingwas launched in 2018. The nose behind this fragrance is Julie Grogan.',
        4,
        2,
        NULL
      ),
(
        'Areej-Al-Oud-70374',
        'Areej Al Oud Al Haramain Perfumes',
        'Areej',
        'for women and men',
        NULL,
        NULL,
        'Rose, Geranium and Saffron',
        'Cypriol Oil or Nagarmotha, Patchouli and Guaiac Wood',
        'Musk and Sandalwood',
        'woody,earthy,warm spicy,patchouli,rose',
        'Areej Al OudbyAl Haramain Perfumesis a Amber Woody fragrance for women and men.Areej Al Oudwas launched in 2021. Top notes are Rose, Geranium and Saffron; middle notes are Cypriol Oil or Nagarmotha, Patchouli and Guaiac Wood; base notes are Musk and Sandalwood.',
        3.5,
        10,
        NULL
      ),
(
        'Mukhallath-Shuyookhi-19851',
        'Mukhallath Shuyookhi Al Haramain Perfumes',
        'Mukhallath',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,floral,cacao,sweet',
        'Mukhallath ShuyookhibyAl Haramain Perfumesis a Amber fragrance for women and men.',
        3.28,
        25,
        NULL
      ),
(
        'Mystique-Bouquet-92434',
        'Mystique Bouquet Afnan',
        'Mystique',
        'for women',
        NULL,
        NULL,
        'White Peach, Mandarin Orange, Bergamot and Litchi',
        'Peony, Orange Blossom, Mahonia and Vetiver',
        'Musk, Ambroxan, oak moss and Vanilla',
        'citrus,musky,fruity,powdery,amber',
        'Mystique BouquetbyAfnanis a Floral Fruity fragrance for women. This is a new fragrance.Mystique Bouquetwas launched in 2024. Top notes are White Peach, Mandarin Orange, Bergamot and Litchi; middle notes are Peony, Orange Blossom, Mahonia and Vetiver; base notes are Musk, Ambroxan, oak moss and Vanilla.',
        4.22,
        210,
        NULL
      ),
(
        'Oudh-al-Amiri-27366',
        'Oudh al Amiri Afnan',
        'Oudh',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,fresh spicy',
        'Oudh al AmiribyAfnanis a Amber fragrance for women and men.',
        NULL,
        NULL,
        NULL
      ),
(
        'C-Style-40786',
        'C Style Oud Elite',
        'C',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'C StylebyOud Eliteis a fragrance for women.C Stylewas launched during the 2010''s.',
        3.5,
        2,
        NULL
      ),
(
        'Al-Fares-85004',
        'Al Fares Adyan',
        'Al',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Mandarin Orange, Bergamot and Juniper',
        'Woody Notes, Black Pepper and Rosemary',
        'Musk, Incense and Oakmoss',
        'citrus,fresh spicy,woody,aromatic,musky',
        'Al FaresbyAdyanis a Aromatic Spicy fragrance for men.Al Fareswas launched in 2021. Top notes are Grapefruit, Mandarin Orange, Bergamot and Juniper; middle notes are Woody Notes, Black Pepper and Rosemary; base notes are Musk, Incense and Oakmoss.',
        4.25,
        4,
        NULL
      ),
(
        'Azlan-Oud-Blue-Edition-83047',
        'Azlan Oud Blue Edition Al Haramain Perfumes',
        'Azlan',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Cardamom and Cinnamon',
        'Patchouli and Lavender',
        'Amber, Sandalwood, Haitian Vetiver and Licorice',
        'warm spicy,woody,aromatic,citrus,patchouli',
        'Azlan Oud Blue EditionbyAl Haramain Perfumesis a fragrance for women and men. This is a new fragrance.Azlan Oud Blue Editionwas launched in 2023. Top notes are Grapefruit, Cardamom and Cinnamon; middle notes are Patchouli and Lavender; base notes are Amber, Sandalwood, Haitian Vetiver and Licorice.',
        4.22,
        27,
        NULL
      ),
(
        'Vetiver-Royale-Absolute-32735',
        'Vetiver Royale Absolute Perry Ellis',
        'Vetiver',
        'for women and men',
        NULL,
        NULL,
        'Haitian Vetiver, Black Pepper and Juniper',
        'Agarwood (Oud)',
        'Indonesian Patchouli Leaf and Atlas Cedar',
        'woody,aromatic,fresh spicy,earthy,oud',
        'Vetiver Royale AbsolutebyPerry Ellisis a Amber fragrance for women and men.Vetiver Royale Absolutewas launched in 2015. Top notes are Haitian Vetiver, Black Pepper and Juniper; middle note is Agarwood (Oud); base notes are Indonesian Patchouli Leaf and Atlas Cedar.',
        3.99,
        71,
        NULL
      ),
(
        'Naseej-Al-Ehsaas-78626',
        'Naseej Al Ehsaas Afnan',
        'Naseej',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Rose and Lily-of-the-Valley',
        'Agarwood (Oud) and Dry Wood',
        'oud,citrus,fresh spicy,woody,rose',
        'Naseej Al EhsaasbyAfnanis a Floral fragrance for women and men.Naseej Al Ehsaaswas launched in 2021. Top notes are Bergamot and Mandarin Orange; middle notes are Rose and Lily-of-the-Valley; base notes are Agarwood (Oud) and Dry Wood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Vanille-Coco-34808',
        'Vanille Coco Adopt Parfums',
        'Vanille',
        'for women and men',
        NULL,
        'Dominique Monlun',
        'Anise and Coriander',
        'Coconut, Tobacco Leaf and Jasmine',
        'Vanilla and Benzoin',
        'vanilla,coconut,sweet,amber,soft spicy',
        'Vanille CocobyAdopt Parfumsis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Dominique Monlun. Top notes are Anise and Coriander; middle notes are Coconut, Tobacco Leaf and Jasmine; base notes are Vanilla and Benzoin.',
        3.7,
        57,
        NULL
      ),
(
        'Terra-Firma-50299',
        'Terra Firma Latherati',
        'Terra',
        'for women and men',
        NULL,
        'Julie Grogan',
        NULL,
        NULL,
        NULL,
        'earthy,sweet,tobacco,floral,fruity',
        'Terra FirmabyLatheratiis a fragrance for women and men. The nose behind this fragrance is Julie Grogan.',
        NULL,
        NULL,
        NULL
      ),
(
        'Faris-52426',
        'Faris Al Haramain Perfumes',
        'Faris',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Chamomile and Lemon',
        'Cedar, Patchouli, Geranium and Thyme',
        'Sandalwood, Saffron, Leather and Vetiver',
        'woody,aromatic,citrus,warm spicy,earthy',
        'FarisbyAl Haramain Perfumesis a Amber Spicy fragrance for women and men.Fariswas launched in 2018. Top notes are Bergamot, Chamomile and Lemon; middle notes are Cedar, Patchouli, Geranium and Thyme; base notes are Sandalwood, Saffron, Leather and Vetiver.',
        3.67,
        9,
        NULL
      ),
(
        'Fakhr-Al-Jammal-27358',
        'Fakhr Al Jammal Afnan',
        'Fakhr',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Fakhr Al JammalbyAfnanis a fragrance for women and men.',
        3.96,
        24,
        NULL
      ),
(
        'Fakhrul-Arab-Silver-19937',
        'Fakhrul Arab Silver Al Haramain Perfumes',
        'Fakhrul',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,amber,warm spicy,fresh spicy,vanilla',
        'Fakhrul Arab SilverbyAl Haramain Perfumesis a Amber fragrance for men.',
        2.86,
        7,
        NULL
      ),
(
        'Khaltath-19951',
        'Khaltath Al Haramain Perfumes',
        'Khaltath',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'mossy,yellow floral,musky,lavender,earthy',
        'KhaltathbyAl Haramain Perfumesis a Amber Fougere fragrance for women and men.',
        3.71,
        38,
        NULL
      ),
(
        'Flagship-III-80770',
        'Flagship III The Dua Brand',
        'Flagship',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,fresh spicy,white floral,woody',
        'Flagship IIIbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.Flagship IIIwas launched in 2021.',
        4.5,
        2,
        NULL
      ),
(
        'Basma-Bleu-48227',
        'Basma Bleu Al Haramain Perfumes',
        'Basma',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Basma BleubyAl Haramain Perfumesis a Amber fragrance for women and men.',
        1,
        1,
        NULL
      ),
(
        'Hide-And-Seek-40238',
        'Hide And Seek Otoori',
        'Hide',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Orange, Mandarin Orange and Bergamot',
        'Mimosa, Jasmine, Turkish Rose and Ylang-Ylang',
        'Tonka Bean, Vanilla, Patchouli, Vetiver and White Musk',
        'citrus,sweet,white floral,yellow floral,woody',
        'Hide And SeekbyOtooriis a Chypre Floral fragrance for women and men.Hide And Seekwas launched in 2016. Top notes are Orange Blossom, Orange, Mandarin Orange and Bergamot; middle notes are Mimosa, Jasmine, Turkish Rose and Ylang-Ylang; base notes are Tonka Bean, Vanilla, Patchouli, Vetiver and White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Omniya-Silver-27364',
        'Omniya Silver Afnan',
        'Omniya',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,lavender,green,floral',
        'Omniya SilverbyAfnanis a Woody Aromatic fragrance for men.',
        4.18,
        11,
        NULL
      ),
(
        'Precious-Black-27372',
        'Precious Black Afnan',
        'Precious',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Precious BlackbyAfnanis a fragrance for women.Precious Blackwas launched in 2014.',
        4.33,
        9,
        NULL
      ),
(
        'Dehnal-Oudh-Ateeq-Eau-De-Parfum-26552',
        'Dehnal Oudh Ateeq Eau De Parfum Al Haramain Perfumes',
        'Dehnal',
        'for men',
        NULL,
        NULL,
        'Geranium, Bergamot and Orange',
        'Agarwood (Oud), Cloves, Saffron and Floral Notes',
        'Cedar, Amber, Musk and Sandalwood',
        'woody,warm spicy,oud,fresh spicy,powdery',
        'Dehnal Oudh Ateeq Eau De ParfumbyAl Haramain Perfumesis a Amber Woody fragrance for men. Top notes are Geranium, Bergamot and Orange; middle notes are Agarwood (Oud), Cloves, Saffron and Floral Notes; base notes are Cedar, Amber, Musk and Sandalwood.',
        3.85,
        26,
        NULL
      ),
(
        'The-Man-Of-Sport-59772',
        'The Man Of Sport Otto Kern',
        'The',
        'for men',
        NULL,
        NULL,
        'Black Pepper, Watery Notes and Ginger',
        'Violet, Lavender and Clary Sage',
        'Pepperwood or Hercules Club, Patchouli, Sandalwood and Cypriol Oil or Nagarmotha',
        'woody,warm spicy,aromatic,fresh spicy,powdery',
        'The Man Of SportbyOtto Kernis a Woody Aquatic fragrance for men.The Man Of Sportwas launched in 2019. Top notes are Black Pepper, Watery Notes and Ginger; middle notes are Violet, Lavender and Clary Sage; base notes are Pepperwood or Hercules Club, Patchouli, Sandalwood and Cypriol Oil or Nagarmotha.',
        3,
        2,
        NULL
      ),
(
        'Vetyver-16349',
        'Vetyver Outremer',
        'Vetyver',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,woody,earthy,fresh',
        'VetyverbyOutremeris a Woody Aromatic fragrance for women and men.',
        4,
        12,
        NULL
      ),
(
        'Turathi-Brown-84403',
        'Turathi Brown Afnan',
        'Turathi',
        'for men',
        NULL,
        NULL,
        'Amber, Patchouli, Woody Notes and Ozonic notes',
        'Spicy Notes, Aromatic Spices and Vanilla',
        'Balsamic Notes, Rose and Aquatic notes',
        'warm spicy,amber,woody,vanilla,patchouli',
        'Turathi BrownbyAfnanis a Woody Spicy fragrance for men. This is a new fragrance.Turathi Brownwas launched in 2023. Top notes are Amber, Patchouli, Woody Notes and Ozonic notes; middle notes are Spicy Notes, Aromatic Spices and Vanilla; base notes are Balsamic Notes, Rose and Aquatic notes.',
        4.52,
        304,
        NULL
      ),
(
        'Sugar-Plum-Fairy-52743',
        'Sugar Plum Fairy Latherati',
        'Sugar',
        'for women',
        NULL,
        'Julie Grogan',
        NULL,
        NULL,
        NULL,
        'sweet,fruity,vanilla,powdery,musky',
        'Sugar Plum FairybyLatheratiis a Citrus Gourmand fragrance for women.Sugar Plum Fairywas launched in 2018. The nose behind this fragrance is Julie Grogan.',
        3,
        3,
        NULL
      ),
(
        'Wild-Musk-52865',
        'Wild Musk Adopt Parfums',
        'Wild',
        'for men',
        NULL,
        'Dominique Monlun',
        'Lavender',
        'Cashmere Wood and Sandalwood',
        'Oakmoss and Musk',
        'musky,woody,mossy,earthy,powdery',
        'Wild MuskbyAdopt Parfumsis a fragrance for men. The nose behind this fragrance is Dominique Monlun. Top note is Lavender; middle notes are Cashmere Wood and Sandalwood; base notes are Oakmoss and Musk.',
        4.09,
        11,
        NULL
      ),
(
        'Like-Kiss-46769',
        'Like Kiss Parfums Genty',
        'Like',
        'for women',
        NULL,
        NULL,
        'Mango, Passionfruit and Grapefruit',
        'Jasmine and Violet',
        'Raspberry, Musk and Amber',
        'fruity,sweet,tropical',
        'Like KissbyParfums Gentyis a Floral Fruity fragrance for women. Top notes are Mango, Passionfruit and Grapefruit; middle notes are Jasmine and Violet; base notes are Raspberry, Musk and Amber.',
        3.33,
        18,
        NULL
      ),
(
        'Faris-Aswad-51821',
        'Faris Aswad Al Haramain Perfumes',
        'Faris',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Pineapple',
        'Patchouli, Jasmine and Cedar',
        'Moss and Amber',
        'woody,white floral,patchouli,earthy,amber',
        'Faris AswadbyAl Haramain Perfumesis a Woody Aromatic fragrance for women and men.Faris Aswadwas launched in 2018. Top notes are Bergamot and Pineapple; middle notes are Patchouli, Jasmine and Cedar; base notes are Moss and Amber.',
        3.5,
        2,
        NULL
      ),
(
        'White-Misk-39500',
        'White Misk Otoori',
        'White',
        'for women and men',
        NULL,
        NULL,
        'Ylang-Ylang',
        'Woody Notes and Rose',
        'Musk, Gardenia and Lotus',
        'musky,woody,yellow floral,floral,powdery',
        'White MiskbyOtooriis a fragrance for women and men.White Miskwas launched in 2010. Top note is Ylang-Ylang; middle notes are Woody Notes and Rose; base notes are Musk, Gardenia and Lotus.',
        4,
        8,
        NULL
      ),
(
        'Mirus-II-30133',
        'Mirus II Lanoe',
        'Mirus',
        'for men',
        NULL,
        'Simone Schmelzer',
        NULL,
        NULL,
        NULL,
        NULL,
        'Mirus IIbyLanoeis a Aromatic fragrance for men.Mirus IIwas launched in 2015. The nose behind this fragrance is Simone Schmelzer.',
        NULL,
        NULL,
        NULL
      ),
(
        'Mukhallath-Hind-19815',
        'Mukhallath Hind Al Haramain Perfumes',
        'Mukhallath',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,vanilla,amber,floral,metallic',
        'Mukhallath HindbyAl Haramain Perfumesis a Amber Woody fragrance for women and men.',
        3.5,
        8,
        NULL
      ),
(
        'Detour-Noir-Exclusif-92659',
        'Detour Noir Exclusif Al Haramain Perfumes',
        'Detour',
        'for women and men',
        NULL,
        NULL,
        'Almond, Mandarin Orange, Watery Notes and Bergamot',
        'Civet, Rose, Water Lily, Geranium and Gardenia',
        'Guaiac Wood, Laotian Oud, Vanilla, Sandalwood, Coffee, Amber, Indonesian Patchouli Leaf, Pink Pepper and Oakmoss',
        'woody,oud,vanilla,powdery,animalic',
        'Detour Noir ExclusifbyAl Haramain Perfumesis a Amber Floral fragrance for women and men. Top notes are Almond, Mandarin Orange, Watery Notes and Bergamot; middle notes are Civet, Rose, Water Lily, Geranium and Gardenia; base notes are Guaiac Wood, Laotian Oud, Vanilla, Sandalwood, Coffee, Amber, Indonesian Patchouli Leaf, Pink Pepper and Oakmoss.',
        4.21,
        48,
        NULL
      ),
(
        'Musk-Al-Haramain-70378',
        'Musk Al Haramain Al Haramain Perfumes',
        'Musk',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes',
        'Rose, Violet and Lily-of-the-Valley',
        'Musk, Cedar, Vanilla and Amber',
        'powdery,musky,rose,violet,floral',
        'Musk Al HaramainbyAl Haramain Perfumesis a Floral Woody Musk fragrance for women and men.Musk Al Haramainwas launched in 2021. Top note is Fruity Notes; middle notes are Rose, Violet and Lily-of-the-Valley; base notes are Musk, Cedar, Vanilla and Amber.',
        4.15,
        41,
        NULL
      ),
(
        'Shabab-75222',
        'Shabab Naseem',
        'Shabab',
        'for women and men',
        NULL,
        NULL,
        'Pineapple, Bergamot and Black Currant',
        'Birch, Patchouli and Jasmine',
        'Ambergris, Musk and Vanilla',
        'fruity,sweet,woody,citrus,leather',
        'ShababbyNaseemis a Woody fragrance for women and men. This is a new fragrance.Shababwas launched in 2022. Top notes are Pineapple, Bergamot and Black Currant; middle notes are Birch, Patchouli and Jasmine; base notes are Ambergris, Musk and Vanilla.',
        4.6,
        5,
        NULL
      ),
(
        'Haramain-Oud-Cambodi-Intense-53254',
        'Haramain Oud Cambodi Intense Al Haramain Perfumes',
        'Haramain',
        'for women and men',
        NULL,
        NULL,
        'Castoreum and Agarwood (Oud)',
        'Cashmere Wood',
        'Animal notes, Musk and Sandalwood',
        'musky,animalic,woody,leather,oud',
        'Haramain Oud Cambodi IntensebyAl Haramain Perfumesis a Amber Woody fragrance for women and men. Top notes are Castoreum and Agarwood (Oud); middle note is Cashmere Wood; base notes are Animal notes, Musk and Sandalwood.',
        4.16,
        31,
        NULL
      ),
(
        'Mirsaal-With-Love-66848',
        'Mirsaal With Love Afnan',
        'Mirsaal',
        'for women',
        NULL,
        NULL,
        'Caramel, Herbal Notes and Green Notes',
        'Agarwood (Oud), Woodsy Notes and Floral Notes',
        'Moss, Amber and Musk',
        'oud,caramel,woody,mossy,amber',
        'Mirsaal With LovebyAfnanis a Woody Aromatic fragrance for women.Mirsaal With Lovewas launched in 2020. Top notes are Caramel, Herbal Notes and Green Notes; middle notes are Agarwood (Oud), Woodsy Notes and Floral Notes; base notes are Moss, Amber and Musk.',
        3.94,
        68,
        NULL
      ),
(
        'The-Man-Of-Luxury-59771',
        'The Man Of Luxury Otto Kern',
        'The',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Ginger and Apple',
        'Black Pepper, Lavender and Mineral notes',
        'Vetiver, Ambroxan and Woody Notes',
        'fresh spicy,woody,aromatic,warm spicy,citrus',
        'The Man Of LuxurybyOtto Kernis a Woody Aromatic fragrance for men.The Man Of Luxurywas launched in 2019. Top notes are Grapefruit, Ginger and Apple; middle notes are Black Pepper, Lavender and Mineral notes; base notes are Vetiver, Ambroxan and Woody Notes.',
        3,
        1,
        NULL
      ),
(
        'Wildii-71897',
        'Wildii TRNP',
        'Wildii',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,warm spicy,vanilla,aromatic',
        'WildiibyTRNPis a fragrance for women and men.Wildiiwas launched in 2021.',
        4.12,
        16,
        NULL
      ),
(
        'White-30112',
        'White Lanoe',
        'White',
        'for women',
        NULL,
        'Simone Schmelzer',
        'Litchi, Plum and Pear',
        'Mimosa, Violet, Poppy and Jasmine',
        'Amber, Tonka Bean, Vanilla and Teak Wood',
        'fruity,sweet,vanilla,amber,powdery',
        'WhitebyLanoeis a Floral Fruity fragrance for women.Whitewas launched in 2011. The nose behind this fragrance is Simone Schmelzer. Top notes are Litchi, Plum and Pear; middle notes are Mimosa, Violet, Poppy and Jasmine; base notes are Amber, Tonka Bean, Vanilla and Teak Wood.',
        3.83,
        6,
        NULL
      ),
(
        'Chateau-De-La-Haramain-D-Or-53248',
        'Chateau De La Haramain D’Or Al Haramain Perfumes',
        'Chateau',
        'for women',
        NULL,
        NULL,
        'Lemon, Orange, Bergamot and Rose',
        'Jasmine, Geranium, Green Notes and Fruity Notes',
        'Tonka Bean, Patchouli, Oakmoss and Musk',
        'aromatic,citrus,fresh spicy,white floral,rose',
        'Chateau De La Haramain D’OrbyAl Haramain Perfumesis a Chypre Floral fragrance for women. Top notes are Lemon, Orange, Bergamot and Rose; middle notes are Jasmine, Geranium, Green Notes and Fruity Notes; base notes are Tonka Bean, Patchouli, Oakmoss and Musk.',
        4,
        1,
        NULL
      ),
(
        'Violet-Firefly-45669',
        'Violet Firefly TRNP',
        'Violet',
        'for women and men',
        NULL,
        'Teone Reinthal',
        NULL,
        NULL,
        NULL,
        'iris,leather,powdery,ozonic,violet',
        'Violet FireflybyTRNPis a Chypre fragrance for women and men. The nose behind this fragrance is Teone Reinthal.',
        4.29,
        21,
        NULL
      ),
(
        'Fawah-44518',
        'Fawah Al Haramain Perfumes',
        'Fawah',
        'for women',
        NULL,
        NULL,
        'Raspberry, Strawberry and Peach',
        'Orris Root, Jasmine and Rose',
        'Coconut, Vanilla and Musk',
        'fruity,sweet,vanilla,coconut',
        'FawahbyAl Haramain Perfumesis a Floral Fruity fragrance for women. Top notes are Raspberry, Strawberry and Peach; middle notes are Orris Root, Jasmine and Rose; base notes are Coconut, Vanilla and Musk.',
        4.21,
        42,
        NULL
      ),
(
        'Melograno-Pomegranate-11480',
        'Melograno (Pomegranate) Santa Maria Novella',
        'Melograno',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Spices and Bitter Orange',
        'Pomegranate, Ylang-Ylang and Rose',
        'Oakmoss, Labdanum, Patchouli and Musk',
        'woody,mossy,earthy,amber,citrus',
        'Melograno (Pomegranate)bySanta Maria Novellais a Chypre fragrance for women and men.Melograno (Pomegranate)was launched in 1965. Top notes are Bergamot, Spices and Bitter Orange; middle notes are Pomegranate, Ylang-Ylang and Rose; base notes are Oakmoss, Labdanum, Patchouli and Musk.',
        4.1,
        722,
        NULL
      ),
(
        'Majestic-Gold-27369',
        'Majestic Gold Afnan',
        'Majestic',
        'for men',
        NULL,
        NULL,
        'Blackberry, Blueberry and Patchouli',
        'Leather, Agarwood (Oud), Lily and Rose',
        'Amber, Resins and Musk',
        'fruity,amber,leather,sweet,patchouli',
        'Majestic GoldbyAfnanis a fragrance for men.Majestic Goldwas launched in 2014. Top notes are Blackberry, Blueberry and Patchouli; middle notes are Leather, Agarwood (Oud), Lily and Rose; base notes are Amber, Resins and Musk.',
        4.26,
        23,
        NULL
      ),
(
        'Manar-19871',
        'Manar Al Haramain Perfumes',
        'Manar',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,honey,sweet,musky,citrus',
        'ManarbyAl Haramain Perfumesis a Amber Vanilla fragrance for women and men.',
        3.61,
        18,
        NULL
      ),
(
        'Montana-Sky-90390',
        'Montana Sky Pacifica',
        'Montana',
        'for women and men',
        NULL,
        'Brook Harvey-Taylor',
        'Black Pepper, Petitgrain and Black Elder',
        'Cedar, Olibanum, Sage and Cumin',
        'Vetiver, Cypress and Sandal',
        'woody,aromatic,fresh spicy,amber,earthy',
        'Montana SkybyPacificais a Woody Spicy fragrance for women and men. This is a new fragrance.Montana Skywas launched in 2024. The nose behind this fragrance is Brook Harvey-Taylor. Top notes are Black Pepper, Petitgrain and Black Elder; middle notes are Cedar, Olibanum, Sage and Cumin; base notes are Vetiver, Cypress and Sandal.',
        3.7,
        23,
        NULL
      ),
(
        'Peche-Abricot-23449',
        'Pêche Abricot Adopt Parfums',
        'Pêche',
        'for women',
        NULL,
        NULL,
        'Peach',
        'Apricot and Coconut',
        'Vanilla and Musk',
        'fruity,powdery,sweet,vanilla,lactonic',
        'Pêche AbricotbyAdopt Parfumsis a Floral Fruity Gourmand fragrance for women. Top note is Peach; middle notes are Apricot and Coconut; base notes are Vanilla and Musk.',
        3.7,
        43,
        NULL
      ),
(
        'Suggestion-Eau-d-Argent-1994-2387',
        'Suggestion Eau d''Argent 1994 Montana',
        'Suggestion',
        'for women',
        NULL,
        'Max Gavarry',
        'Green Notes, Bergamot, Violet, Brazilian Rosewood, Mandarin Orange and Peach',
        'Lily, Cyclamen, Orchid, Lily-of-the-Valley, Jasmine and Rose',
        'Musk, Sandalwood and Amber',
        'white floral,floral,powdery,green,musky',
        'Suggestion Eau d''Argent 1994byMontanais a Floral fragrance for women.Suggestion Eau d''Argent 1994was launched in 1994. The nose behind this fragrance is Max Gavarry. Top notes are Green Notes, Bergamot, Violet, Brazilian Rosewood, Mandarin Orange and Peach; middle notes are Lily, Cyclamen, Orchid, Lily-of-the-Valley, Jasmine and Rose; base notes are Musk, Sandalwood and Amber.',
        3.91,
        66,
        NULL
      ),
(
        'Lak-Qalbi-85014',
        'Lak Qalbi Adyan',
        'Lak',
        'for women and men',
        NULL,
        NULL,
        'Jasmine',
        'Tuberose and White Flowers',
        'Musk and Honeysuckle',
        'white floral,musky,tuberose,animalic',
        'Lak QalbibyAdyanis a Floral Woody Musk fragrance for women and men.Lak Qalbiwas launched in 2021. Top note is Jasmine; middle notes are Tuberose and White Flowers; base notes are Musk and Honeysuckle.',
        4,
        4,
        NULL
      ),
(
        'Portrait-Abstract-92432',
        'Portrait - Abstract Afnan',
        'Portrait',
        'for women and men',
        NULL,
        NULL,
        'Incense, Vetiver and Rhubarb',
        'Tonka Bean and Rose',
        'Leather, Amber, Cedar and Sandalwood',
        'amber,leather,smoky,woody,animalic',
        'Portrait - AbstractbyAfnanis a Amber Fougere fragrance for women and men. This is a new fragrance.Portrait - Abstractwas launched in 2023. Top notes are Incense, Vetiver and Rhubarb; middle notes are Tonka Bean and Rose; base notes are Leather, Amber, Cedar and Sandalwood.',
        4.55,
        11,
        NULL
      ),
(
        'Amira-Gold-19838',
        'Amira Gold Al Haramain Perfumes',
        'Amira',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,powdery,citrus,oud,vanilla',
        'Amira GoldbyAl Haramain Perfumesis a Amber fragrance for women.',
        3.94,
        212,
        NULL
      ),
(
        'Sadaf-70383',
        'Sadaf Al Haramain Perfumes',
        'Sadaf',
        'for women and men',
        NULL,
        NULL,
        'Rose, Bergamot and Orange',
        'Saffron, Orris, Cedar and Geranium',
        'Saffron, Orris, Cedar and Geranium',
        'rose,citrus,warm spicy,iris,woody',
        'SadafbyAl Haramain Perfumesis a Amber Spicy fragrance for women and men.Sadafwas launched in 2021. Top notes are Rose, Bergamot and Orange; middle notes are Saffron, Orris, Cedar and Geranium; base notes are Saffron, Orris, Cedar and Geranium.',
        3.86,
        7,
        NULL
      ),
(
        'Tobacco-Rush-75682',
        'Tobacco Rush Afnan',
        'Tobacco',
        'for women and men',
        NULL,
        NULL,
        'Tobacco, Spicy Notes and Woody Notes',
        'Spicy Notes, Sweet Notes and Lavender',
        'Agarwood (Oud), Amber and Cedar',
        'tobacco,woody,sweet,warm spicy,oud',
        'Tobacco RushbyAfnanis a Leather fragrance for women and men. This is a new fragrance.Tobacco Rushwas launched in 2022. Top notes are Tobacco, Spicy Notes and Woody Notes; middle notes are Spicy Notes, Sweet Notes and Lavender; base notes are Agarwood (Oud), Amber and Cedar.',
        4.24,
        164,
        NULL
      ),
(
        'Gold-Wood-27346',
        'Gold Wood Afnan',
        'Gold',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Gold WoodbyAfnanis a Woody fragrance for women and men.',
        4.27,
        11,
        NULL
      ),
(
        'Atlantis-16356',
        'Atlantis Outremer',
        'Atlantis',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,marine,aromatic,citrus,fresh spicy',
        'AtlantisbyOutremeris a Citrus fragrance for women and men.',
        3.67,
        9,
        NULL
      ),
(
        'Otto-Kern-Soft-Contrast-49149',
        'Otto Kern Soft Contrast Otto Kern',
        'Otto',
        'for women',
        NULL,
        NULL,
        'Apricot, Raspberry and Grapefruit',
        'Jasmine, Tiare Flower and Gardenia',
        'Vanilla and Sandalwood',
        'white floral,fruity,vanilla,powdery,sweet',
        'Otto Kern Soft ContrastbyOtto Kernis a Floral Fruity fragrance for women.Otto Kern Soft Contrastwas launched in 2018. Top notes are Apricot, Raspberry and Grapefruit; middle notes are Jasmine, Tiare Flower and Gardenia; base notes are Vanilla and Sandalwood.',
        3.83,
        12,
        NULL
      ),
(
        'Legacy-of-Oud-85015',
        'Legacy of Oud Adyan',
        'Legacy',
        'for women and men',
        NULL,
        NULL,
        'Agarwood (Oud), Raspberry and Incense',
        'Rose and Benzoin',
        'Amberwood, Saffron and Birch Tar',
        'amber,warm spicy,oud,rose,fruity',
        'Legacy of OudbyAdyanis a Woody fragrance for women and men.Legacy of Oudwas launched in 2020. Top notes are Agarwood (Oud), Raspberry and Incense; middle notes are Rose and Benzoin; base notes are Amberwood, Saffron and Birch Tar.',
        4.5,
        2,
        NULL
      ),
(
        'Polo-Red-Pride-Edition-62728',
        'Polo Red Pride Edition Ralph Lauren',
        'Polo',
        'for men',
        NULL,
        'Olivier Gillotin',
        'Cranberry, Pink Grapefruit and Citron',
        'Clary Sage, Lavender and Saffron',
        'Amberwood, Brazilian Redwood and Coffee',
        'woody,amber,citrus,warm spicy,aromatic',
        'Polo Red Pride EditionbyRalph Laurenis a Woody Spicy fragrance for men.Polo Red Pride Editionwas launched in 2020. The nose behind this fragrance is Olivier Gillotin. Top notes are Cranberry, Pink Grapefruit and Citron; middle notes are Clary Sage, Lavender and Saffron; base notes are Amberwood, Brazilian Redwood and Coffee.',
        2.05,
        107,
        NULL
      ),
(
        'The-Path-71907',
        'The Path TRNP',
        'The',
        'for women and men',
        NULL,
        NULL,
        'Fir, Black Spruce and Elemi resin',
        'Styrax, Labdanum and Texas Cedar',
        'Agarwood (Oud), Haitian Vetiver and Sandalwood',
        'woody,aromatic,amber,oud,balsamic',
        'The PathbyTRNPis a Woody fragrance for women and men.The Pathwas launched in 2020. Top notes are Fir, Black Spruce and Elemi resin; middle notes are Styrax, Labdanum and Texas Cedar; base notes are Agarwood (Oud), Haitian Vetiver and Sandalwood.',
        4.27,
        15,
        NULL
      ),
(
        'Deep-in-The-Wild-40178',
        'Deep in The Wild Otoori',
        'Deep',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes and Citruses',
        'Spicy Notes, Woody Notes, Rose and Green Notes',
        'Earthy Notes, Amber and Musk',
        'citrus,green,woody,rose,musky',
        'Deep in The WildbyOtooriis a Chypre Fruity fragrance for women and men.Deep in The Wildwas launched in 2016. Top notes are Fruity Notes and Citruses; middle notes are Spicy Notes, Woody Notes, Rose and Green Notes; base notes are Earthy Notes, Amber and Musk.',
        4,
        1,
        NULL
      ),
(
        'Life-Circle-Blossom-33006',
        'Life Circle Blossom Oriflame',
        'Life',
        'for women',
        NULL,
        NULL,
        'Orange Leaf and Lemon',
        'Jasmine',
        'Musk',
        'white floral,citrus,musky,aromatic,green',
        'Life Circle BlossombyOriflameis a Floral fragrance for women.Life Circle Blossomwas launched during the 2000''s. Top notes are Orange Leaf and Lemon; middle note is Jasmine; base note is Musk.',
        3.7,
        33,
        NULL
      ),
(
        'Tea-Rose-Mimosa-Limited-Edition-71901',
        'Tea Rose Mimosa - Limited Edition TRNP',
        'Tea',
        'for women and men',
        NULL,
        NULL,
        'Yuzu, Lavender, Chamomile and Tea Rose',
        'Mimosa, Lime (Linden) Blossom and Hyacinth',
        'Australian Sandalwood, Orris, Amyris and Ambergris',
        'floral,woody,powdery,yellow floral,green',
        'Tea Rose Mimosa - Limited EditionbyTRNPis a fragrance for women and men.Tea Rose Mimosa - Limited Editionwas launched in 2021. Top notes are Yuzu, Lavender, Chamomile and Tea Rose; middle notes are Mimosa, Lime (Linden) Blossom and Hyacinth; base notes are Australian Sandalwood, Orris, Amyris and Ambergris.',
        4.33,
        6,
        NULL
      ),
(
        'Mon-Parfum-6044',
        'Mon Parfum Paloma Picasso',
        'Mon',
        'for women',
        NULL,
        'Creations Aromatiques',
        'Rose, Angelica, Hiacynth, Ylang-Ylang, Bergamot and Lemon',
        'Rose, Coriander, Mimosa and Jasmine',
        'Oakmoss, Honey, Sandalwood, Patchouli, Amber, Musk and Iris',
        'powdery,woody,floral,earthy,musky',
        'Mon ParfumbyPaloma Picassois a Chypre fragrance for women.Mon Parfumwas launched in 1985. The nose behind this fragrance is Creations Aromatiques. Top notes are Rose, Angelica, Hiacynth, Ylang-Ylang, Bergamot and Lemon; middle notes are Rose, Coriander, Mimosa and Jasmine; base notes are Oakmoss, Honey, Sandalwood, Patchouli, Amber, Musk and Iris.',
        4.35,
        433,
        NULL
      ),
(
        'Summer-Snow-58998',
        'Summer Snow NSHQ',
        'Summer',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,powdery,vanilla,sweet,musky',
        'Summer SnowbyNSHQis a fragrance for women and men.Summer Snowwas launched in 2019.',
        NULL,
        NULL,
        NULL
      ),
(
        'Tease-Heartbreaker-55996',
        'Tease Heartbreaker Victoria''s Secret',
        'Tease',
        'for women',
        NULL,
        NULL,
        'Carambola (Star Fruit)',
        'Pink Lotus',
        'Whipped Cream, Vanilla and Tonka Bean',
        'vanilla,sweet,fruity,tropical,floral',
        'Tease HeartbreakerbyVictoria''s Secretis a Amber Floral fragrance for women.Tease Heartbreakerwas launched in 2019. Top note is Carambola (Star Fruit); middle note is Pink Lotus; base notes are Whipped Cream, Vanilla and Tonka Bean.',
        3.85,
        110,
        NULL
      );
