
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Classique-Rock-Star-2846',
        'Classique Rock Star Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Neroli and Star Anise',
        'Ginger and Rose',
        'Vanilla and Amber',
        'vanilla,soft spicy,anis,rose,floral',
        'Classique Rock StarbyJean Paul Gaultieris a Amber Floral fragrance for women.Classique Rock Starwas launched in 2005. Top notes are Neroli and Star Anise; middle notes are Ginger and Rose; base notes are Vanilla and Amber.',
        4.51,
        65,
        NULL
      ),
(
        'Classique-Silver-My-Skin-13147',
        'Classique Silver My Skin Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'African Orange Flower, Rose, Pear, Mandarin Orange and Star Anise',
        'Orchid, Iris, Ylang-Ylang, plum and Ginger',
        'Vanille, Musk and Amber',
        'sweet,powdery,floral,citrus,fruity',
        'Classique Silver My SkinbyJean Paul Gaultieris a Amber Floral fragrance for women.Classique Silver My Skinwas launched in 2011. The nose behind this fragrance is Jacques Cavallier. Top notes are African Orange Flower, Rose, Pear, Mandarin Orange and Star Anise; middle notes are Orchid, Iris, Ylang-Ylang, plum and Ginger; base notes are Vanille, Musk and Amber.',
        4.34,
        56,
        NULL
      ),
(
        'Classique-Summer-2010-8144',
        'Classique Summer 2010 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Amalfi Lemon, Clementine and African Orange Flower',
        'Ylang-Ylang, Iris, Lily-of-the-Valley, Woodsy Notes and Jasmine',
        'Vanille, Musk and Amber',
        'citrus,white floral,sweet,woody,yellow floral',
        'Classique Summer 2010byJean Paul Gaultieris a Floral fragrance for women.Classique Summer 2010was launched in 2010. Top notes are Amalfi Lemon, Clementine and African Orange Flower; middle notes are Ylang-Ylang, Iris, Lily-of-the-Valley, Woodsy Notes and Jasmine; base notes are Vanille, Musk and Amber.',
        3.92,
        74,
        NULL
      ),
(
        'Classique-Summer-2011-11597',
        'Classique Summer 2011 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'African Orange Flower and Rose',
        'Jasmine and Ylang-Ylang',
        'Musk and Vanille',
        'white floral,rose,sweet,yellow floral,musky',
        'Classique Summer 2011byJean Paul Gaultieris a Floral fragrance for women.Classique Summer 2011was launched in 2011. Top notes are African Orange Flower and Rose; middle notes are Jasmine and Ylang-Ylang; base notes are Musk and Vanille.',
        3.9,
        96,
        NULL
      ),
(
        'Classique-Summer-2012-14647',
        'Classique Summer 2012 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Clementine and Rose',
        'Ylang-Ylang, Jasmine, Iris and Lily-of-the-Valley',
        'Vanilla, Musk and Amber',
        'white floral,citrus,sweet,yellow floral,powdery',
        'Classique Summer 2012byJean Paul Gaultieris a Floral fragrance for women.Classique Summer 2012was launched in 2012. Top notes are Orange Blossom, Clementine and Rose; middle notes are Ylang-Ylang, Jasmine, Iris and Lily-of-the-Valley; base notes are Vanilla, Musk and Amber.',
        3.94,
        129,
        NULL
      ),
(
        'Classique-Summer-2013-17822',
        'Classique Summer 2013 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Clementine and Sicilian Lemon',
        'Jasmine Sambac, Ylang-Ylang, White Iris and Rose',
        'Vanilla, Amber and Musk',
        'citrus,white floral,sweet,powdery,vanilla',
        'Classique Summer 2013byJean Paul Gaultieris a Floral fragrance for women.Classique Summer 2013was launched in 2013. Top notes are Orange Blossom, Clementine and Sicilian Lemon; middle notes are Jasmine Sambac, Ylang-Ylang, White Iris and Rose; base notes are Vanilla, Amber and Musk.',
        3.93,
        133,
        NULL
      ),
(
        'Classique-Summer-2015-29800',
        'Classique Summer 2015 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Mandarin Orange, Lemon, Clementine and Rose',
        'Ylang-Ylang, Iris, Lily-of-the-Valley and Jasmine Sambac',
        'Vanilla, Musk and Amber',
        'white floral,citrus,sweet,powdery,yellow floral',
        'Classique Summer 2015byJean Paul Gaultieris a Amber Floral fragrance for women.Classique Summer 2015was launched in 2015. Top notes are Orange Blossom, Mandarin Orange, Lemon, Clementine and Rose; middle notes are Ylang-Ylang, Iris, Lily-of-the-Valley and Jasmine Sambac; base notes are Vanilla, Musk and Amber.',
        3.88,
        80,
        NULL
      ),
(
        'Classique-Summer-Edition-2014-24065',
        'Classique Summer Edition 2014 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Rose, Mandarin Orange, Orange Blossom, Lemon and Clementine',
        'White Iris, Jasmine Sambac, Ylang-Ylang and Lily-of-the-Valley',
        'Vanilla Absolute, Amber and Musk',
        'citrus,white floral,rose,sweet,powdery',
        'Classique Summer Edition 2014byJean Paul Gaultieris a Amber Floral fragrance for women.Classique Summer Edition 2014was launched in 2014. Top notes are Rose, Mandarin Orange, Orange Blossom, Lemon and Clementine; middle notes are White Iris, Jasmine Sambac, Ylang-Ylang and Lily-of-the-Valley; base notes are Vanilla Absolute, Amber and Musk.',
        3.76,
        87,
        NULL
      ),
(
        'Classique-Summer-Fragrance-2008-3052',
        'Classique Summer Fragrance 2008 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Clementine, Rose, Orange Blossom and Lemon',
        'Ylang-Ylang, Jasmine, Lily-of-the-Valley and Iris',
        'Vanilla, Amber and Musk',
        'white floral,citrus,sweet,rose,floral',
        'Classique Summer Fragrance 2008byJean Paul Gaultieris a Amber Floral fragrance for women.Classique Summer Fragrance 2008was launched in 2008. Top notes are Clementine, Rose, Orange Blossom and Lemon; middle notes are Ylang-Ylang, Jasmine, Lily-of-the-Valley and Iris; base notes are Vanilla, Amber and Musk.',
        3.81,
        58,
        NULL
      ),
(
        'Classique-Summer-Fragrance-2009-5788',
        'Classique Summer Fragrance 2009 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Clementine, African Orange Flower, Amalfi Lemon, Star Anise and Rose',
        'Ylang-Ylang, Ginger, Jasmine, Orchid, Lily-of-the-Valley and Iris',
        'Vanilla and Amber',
        'citrus,white floral,sweet,floral,powdery',
        'Classique Summer Fragrance 2009byJean Paul Gaultieris a Floral Fruity fragrance for women.Classique Summer Fragrance 2009was launched in 2009. Top notes are Clementine, African Orange Flower, Amalfi Lemon, Star Anise and Rose; middle notes are Ylang-Ylang, Ginger, Jasmine, Orchid, Lily-of-the-Valley and Iris; base notes are Vanilla and Amber.',
        3.77,
        95,
        NULL
      ),
(
        'Classique-Wonder-Woman-Eau-Fraiche-43711',
        'Classique Wonder Woman Eau Fraiche Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Daphné Bugey',
        'Sorbet, Ginger, Sugar Cane and Lemon',
        'Orange Blossom, Tiare Flower and Jasmine',
        'Vanilla, Musk and Labdanum',
        'white floral,sweet,citrus,vanilla,warm spicy',
        'Classique Wonder Woman Eau FraichebyJean Paul Gaultieris a Amber Floral fragrance for women.Classique Wonder Woman Eau Fraichewas launched in 2017. The nose behind this fragrance is Daphné Bugey. Top notes are Sorbet, Ginger, Sugar Cane and Lemon; middle notes are Orange Blossom, Tiare Flower and Jasmine; base notes are Vanilla, Musk and Labdanum.',
        4.11,
        367,
        NULL
      ),
(
        'Classique-X-7800',
        'Classique X Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'Bergamot and Mandarin Orange',
        'African Orange Flower, Iris and Peony',
        'Virginia Cedar and Vanille',
        'citrus,white floral,floral,powdery,woody',
        'Classique XbyJean Paul Gaultieris a Floral fragrance for women.Classique Xwas launched in 2010. The nose behind this fragrance is Jacques Cavallier. Top notes are Bergamot and Mandarin Orange; middle notes are African Orange Flower, Iris and Peony; base notes are Virginia Cedar and Vanille.',
        3.97,
        827,
        NULL
      ),
(
        'Classique-X-Eau-de-Parfum-15337',
        'Classique X Eau de Parfum Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Raspberry and Bergamot',
        'Orange Blossom and Rose',
        'Vanille and Iris',
        'citrus,sweet,fruity,white floral,rose',
        'Classique X Eau de ParfumbyJean Paul Gaultieris a Amber Floral fragrance for women.Classique X Eau de Parfumwas launched in 2012. Top notes are Raspberry and Bergamot; middle notes are Orange Blossom and Rose; base notes are Vanille and Iris.',
        4.01,
        89,
        NULL
      ),
(
        'Classique-X-Extrait-9602',
        'Classique X Extrait Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        NULL,
        'Rose',
        'African Orange Flower and Tuberose',
        'Vanille and Amber',
        'white floral,rose,tuberose,vanilla,citrus',
        'Classique X ExtraitbyJean Paul Gaultieris a Amber Floral fragrance for women.Classique X Extraitwas launched in 2010. Top note is Rose; middle notes are African Orange Flower and Tuberose; base notes are Vanille and Amber.',
        4,
        51,
        NULL
      ),
(
        'Classique-X-Jewel-Edition-2011-11756',
        'Classique X Jewel Edition 2011 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'Bergamot and Mandarin Orange',
        'African Orange Flower, Iris and Peony',
        'Virginia Cedar and Vanille',
        'citrus,woody,floral,powdery,white floral',
        'Classique X Jewel Edition 2011byJean Paul Gaultieris a Floral fragrance for women.Classique X Jewel Edition 2011was launched in 2011. The nose behind this fragrance is Jacques Cavallier. Top notes are Bergamot and Mandarin Orange; middle notes are African Orange Flower, Iris and Peony; base notes are Virginia Cedar and Vanille.',
        4.04,
        23,
        NULL
      ),
(
        'Classique-X-L-Eau-14568',
        'Classique X L''Eau Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'Neroli and Bergamot',
        'Orange Blossom and Peony',
        'Orris Root and Vanilla',
        'citrus,white floral,floral,fresh,iris',
        'Classique X L''EaubyJean Paul Gaultieris a Floral fragrance for women.Classique X L''Eauwas launched in 2012. The nose behind this fragrance is Jacques Cavallier. Top notes are Neroli and Bergamot; middle notes are Orange Blossom and Peony; base notes are Orris Root and Vanilla.',
        3.91,
        78,
        NULL
      ),
(
        'Classique-X-Love-Actually-11357',
        'Classique X Love Actually Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'Bergamot and Mandarin Orange',
        'Orange Blossom and Peony',
        'Vanilla, Woodsy Notes and Iris',
        'citrus,white floral,woody,floral,vanilla',
        'Classique X Love ActuallybyJean Paul Gaultieris a Floral fragrance for women.Classique X Love Actuallywas launched in 2011. The nose behind this fragrance is Jacques Cavallier. Top notes are Bergamot and Mandarin Orange; middle notes are Orange Blossom and Peony; base notes are Vanilla, Woodsy Notes and Iris.',
        4.33,
        36,
        NULL
      ),
(
        'Classique-Xmas-Limited-Edition-87349',
        'Classique Xmas Limited Edition Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'Ginger',
        'Orange Blossom',
        'Vanilla',
        'vanilla,white floral,sweet,citrus,powdery',
        'Classique Xmas Limited EditionbyJean Paul Gaultieris a Amber Vanilla fragrance for women. This is a new fragrance.Classique Xmas Limited Editionwas launched in 2023. The nose behind this fragrance is Jacques Cavallier. Top note is Ginger; middle note is Orange Blossom; base note is Vanilla.',
        3.43,
        21,
        NULL
      ),
(
        'Classique-Xmas-Limited-Edition-2021-70256',
        'Classique Xmas Limited Edition 2021 Jean Paul Gaultier',
        'Classique',
        'for women',
        NULL,
        'Jacques Cavallier',
        'Orange Blossom, Star Anise, Rose, Mandarin Orange, Bergamot and Pear',
        'Ylang-Ylang, Ginger, Tuberose, Plum, Orchid and Iris',
        'Musk, Vanilla, Amber, Sandalwood and Cinnamon',
        'citrus,white floral,powdery,sweet,warm spicy',
        'Classique Xmas Limited Edition 2021byJean Paul Gaultieris a Amber Floral fragrance for women.Classique Xmas Limited Edition 2021was launched in 2021. The nose behind this fragrance is Jacques Cavallier. Top notes are Orange Blossom, Star Anise, Rose, Mandarin Orange, Bergamot and Pear; middle notes are Ylang-Ylang, Ginger, Tuberose, Plum, Orchid and Iris; base notes are Musk, Vanilla, Amber, Sandalwood and Cinnamon.',
        3.67,
        9,
        NULL
      ),
(
        'Jean-Paul-Gaultier-Summer-2848',
        'Jean Paul Gaultier Summer Jean Paul Gaultier',
        'Jean',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Jean Paul Gaultier SummerbyJean Paul Gaultieris a Amber Floral fragrance for women.Jean Paul Gaultier Summerwas launched in 1997.',
        4.25,
        61,
        NULL
      ),
(
        'Gaultier-Divine-83889',
        'Gaultier Divine Jean Paul Gaultier',
        'Gaultier',
        'for women',
        NULL,
        'Quentin Bisch',
        'Calypsone, Red Berries and Bergamot',
        'Lily, Ylang-Ylang and Jasmine',
        'Meringue, Musk and Patchouli',
        'white floral,sweet,aquatic,marine,aromatic',
        'Gaultier DivinebyJean Paul Gaultieris a Amber Floral fragrance for women. This is a new fragrance.Gaultier Divinewas launched in 2023. The nose behind this fragrance is Quentin Bisch. Top notes are Calypsone, Red Berries and Bergamot; middle notes are Lily, Ylang-Ylang and Jasmine; base notes are Meringue, Musk and Patchouli.',
        3.69,
        2,
        NULL
      ),
(
        'Gaultier-Divine-Le-Parfum-93887',
        'Gaultier Divine Le Parfum Jean Paul Gaultier',
        'Gaultier',
        'for women',
        NULL,
        NULL,
        'Solar Notes and Lily',
        'Frangipani and Sea Salt',
        'Amber and Benzoin',
        'amber,white floral,floral,aldehydic,tropical',
        'Gaultier Divine Le ParfumbyJean Paul Gaultieris a Amber Floral fragrance for women. This is a new fragrance.Gaultier Divine Le Parfumwas launched in 2024. Top notes are Solar Notes and Lily; middle notes are Frangipani and Sea Salt; base notes are Amber and Benzoin.',
        3.07,
        30,
        NULL
      ),
(
        'Fragile-434',
        'Fragile Jean Paul Gaultier',
        'Fragile',
        'for women',
        NULL,
        'Francis Kurkdjian',
        'Tunisian Orange Blossom, Ginger, Italian Tangerine, Star Anise, Coriander, Bulgarian Rose and Bergamot',
        'Tuberose, Jasmine, Indian Ginger, Ylang-Ylang, Carnation, Iris and Rose',
        'Amber, Vanilla, Cinnamon, Musk and Cedar',
        'white floral,tuberose,citrus,warm spicy,floral',
        'FragilebyJean Paul Gaultieris a Floral fragrance for women.Fragilewas launched in 1999. The nose behind this fragrance is Francis Kurkdjian. Top notes are Tunisian Orange Blossom, Ginger, Italian Tangerine, Star Anise, Coriander, Bulgarian Rose and Bergamot; middle notes are Tuberose, Jasmine, Indian Ginger, Ylang-Ylang, Carnation, Iris and Rose; base notes are Amber, Vanilla, Cinnamon, Musk and Cedar.',
        4.09,
        1,
        NULL
      ),
(
        'Fragile-Eau-de-Toilette-436',
        'Fragile Eau de Toilette Jean Paul Gaultier',
        'Fragile',
        'for women',
        NULL,
        'Francis Kurkdjian',
        'Mandarin Orange, Orange, Raspberry, Pink Pepper and Lemon',
        'Tuberose and Orange Blossom',
        'Musk and Woodsy Notes',
        'citrus,white floral,tuberose,sweet,fruity',
        'Fragile Eau de ToilettebyJean Paul Gaultieris a Floral fragrance for women.Fragile Eau de Toilettewas launched in 2001. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mandarin Orange, Orange, Raspberry, Pink Pepper and Lemon; middle notes are Tuberose and Orange Blossom; base notes are Musk and Woodsy Notes.',
        4.15,
        607,
        NULL
      ),
(
        'Gaultier-2-433',
        'Gaultier 2 Jean Paul Gaultier',
        'Gaultier',
        'for women and men',
        NULL,
        'Francis Kurkdjian',
        NULL,
        NULL,
        NULL,
        'amber,vanilla,powdery,musky,animalic',
        'Gaultier 2byJean Paul Gaultieris a Amber Vanilla fragrance for women and men.Gaultier 2was launched in 2005. The nose behind this fragrance is Francis Kurkdjian.',
        4.13,
        2,
        NULL
      ),
(
        'Gaultier-2-Eau-d-Amour-2205',
        'Gaultier 2 Eau d''Amour Jean Paul Gaultier',
        'Gaultier',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,vanilla,citrus,powdery,musky',
        'Gaultier 2 Eau d''AmourbyJean Paul Gaultieris a Amber Vanilla fragrance for women and men.Gaultier 2 Eau d''Amourwas launched in 2008.',
        4,
        264,
        NULL
      ),
(
        'Gaultier2-76519',
        'Gaultier² Jean Paul Gaultier',
        'Gaultier²',
        'for women and men',
        NULL,
        NULL,
        'Jasmine',
        'Sandalwood',
        'Ambergris',
        'white floral,woody,amber,powdery,animalic',
        'Gaultier²byJean Paul Gaultieris a Amber Woody fragrance for women and men. This is a new fragrance.Gaultier²was launched in 2022. Top note is Jasmine; middle note is Sandalwood; base note is Ambergris.',
        4.11,
        167,
        NULL
      ),
(
        'Kokorico-12711',
        'Kokorico Jean Paul Gaultier',
        'Kokorico',
        'for men',
        NULL,
        'Annick Menardo',
        'Fig Leaf',
        'Cacao and Patchouli',
        'Vetiver and Virginia Cedar',
        'woody,warm spicy,cacao,green,patchouli',
        'KokoricobyJean Paul Gaultieris a Woody Aromatic fragrance for men.Kokoricowas launched in 2011. Kokorico was created by Olivier Cresp and Annick Menardo. Top note is Fig Leaf; middle notes are Cacao and Patchouli; base notes are Vetiver and Virginia Cedar.',
        3.84,
        2,
        NULL
      ),
(
        'Kokorico-by-Night-15471',
        'Kokorico by Night Jean Paul Gaultier',
        'Kokorico',
        'for men',
        NULL,
        'Annick Menardo',
        'Bergamot',
        'Cacao Pod, Fig Leaf and Rhubarb',
        'Tonka Bean and Woody Notes',
        'green,cacao,sweet,warm spicy,woody',
        'Kokorico by NightbyJean Paul Gaultieris a Amber Vanilla fragrance for men.Kokorico by Nightwas launched in 2012. Kokorico by Night was created by Olivier Cresp and Annick Menardo. Top note is Bergamot; middle notes are Cacao Pod, Fig Leaf and Rhubarb; base notes are Tonka Bean and Woody Notes.',
        3.82,
        349,
        NULL
      ),
(
        'La-Belle-55786',
        'La Belle Jean Paul Gaultier',
        'La',
        'for women',
        NULL,
        'Quentin Bisch',
        'Pear and Bergamot',
        'Floral Notes and Leather',
        'Vanilla, Vetiver, Amber and Musk',
        'vanilla,fruity,sweet,powdery,aquatic',
        'La BellebyJean Paul Gaultieris a Amber Vanilla fragrance for women.La Bellewas launched in 2019. La Belle was created by Quentin Bisch and Sonia Constant. Top notes are Pear and Bergamot; middle notes are Floral Notes and Leather; base notes are Vanilla, Vetiver, Amber and Musk.',
        4.15,
        6,
        NULL
      ),
(
        'La-Belle-Fleur-Terrible-71822',
        'La Belle Fleur Terrible Jean Paul Gaultier',
        'La',
        'for women',
        NULL,
        'Quentin Bisch',
        'Water Lily',
        'Iris',
        'Vanilla',
        'floral,iris,vanilla,powdery,aquatic',
        'La Belle Fleur TerriblebyJean Paul Gaultieris a Floral Aquatic fragrance for women. This is a new fragrance.La Belle Fleur Terriblewas launched in 2022. The nose behind this fragrance is Quentin Bisch. Top note is Water Lily; middle note is Iris; base note is Vanilla.',
        4.08,
        743,
        NULL
      ),
(
        'La-Belle-Le-Parfum-65175',
        'La Belle Le Parfum Jean Paul Gaultier',
        'La',
        'for women',
        NULL,
        'Quentin Bisch',
        'Pear',
        'Tonka Bean and Jasmine',
        'Vanilla',
        'vanilla,sweet,fruity,amber',
        'La Belle Le ParfumbyJean Paul Gaultieris a Amber Vanilla fragrance for women.La Belle Le Parfumwas launched in 2021. La Belle Le Parfum was created by Quentin Bisch and Sonia Constant. Top note is Pear; middle notes are Tonka Bean and Jasmine; base note is Vanilla.',
        4.19,
        3,
        NULL
      ),
(
        'La-Belle-Le-Parfum-2024-93892',
        'La Belle Le Parfum (2024) Jean Paul Gaultier',
        'La',
        'for women',
        NULL,
        NULL,
        'Pear',
        'Vanilla',
        'Tonka',
        'vanilla,sweet,fruity,amber,aquatic',
        'La Belle Le Parfum (2024)byJean Paul Gaultieris a Amber Vanilla fragrance for women. This is a new fragrance.La Belle Le Parfum (2024)was launched in 2024. Top note is Pear; middle note is Vanilla; base note is Tonka.',
        3.6,
        42,
        NULL
      ),
(
        'La-Belle-Paradise-Garden-88873',
        'La Belle Paradise Garden Jean Paul Gaultier',
        'La',
        'for women',
        NULL,
        'Quentin Bisch',
        'Blue Lotus',
        'Iris',
        'Vanilla',
        'vanilla,floral,powdery,iris,aquatic',
        'La Belle Paradise GardenbyJean Paul Gaultieris a Floral fragrance for women. This is a new fragrance.La Belle Paradise Gardenwas launched in 2024. The nose behind this fragrance is Quentin Bisch. Top note is Blue Lotus; middle note is Iris; base note is Vanilla.',
        4.05,
        426,
        NULL
      ),
(
        'Le-Beau-55785',
        'Le Beau Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Quentin Bisch',
        'Bergamot',
        'Coconut',
        'Tonka Bean',
        'coconut,vanilla,sweet,citrus,lactonic',
        'Le BeaubyJean Paul Gaultieris a Woody Aromatic fragrance for men.Le Beauwas launched in 2019. Le Beau was created by Quentin Bisch and Sonia Constant. Top note is Bergamot; middle note is Coconut; base note is Tonka Bean.',
        4.31,
        6,
        NULL
      ),
(
        'Le-Beau-Le-Parfum-72158',
        'Le Beau Le Parfum Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Quentin Bisch',
        'Pineapple, Iris, Ginger and Cypress',
        'Coconut and Woodsy Notes',
        'Tonka Bean, Sandalwood, Amber and Ambergris',
        'sweet,woody,coconut,amber,vanilla',
        'Le Beau Le ParfumbyJean Paul Gaultieris a Amber Woody fragrance for men. This is a new fragrance.Le Beau Le Parfumwas launched in 2022. The nose behind this fragrance is Quentin Bisch. Top notes are Pineapple, Iris, Ginger and Cypress; middle notes are Coconut and Woodsy Notes; base notes are Tonka Bean, Sandalwood, Amber and Ambergris.',
        4.56,
        7,
        NULL
      ),
(
        'Le-Beau-Male-17222',
        'Le Beau Male Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint and Wormwood',
        'Lavender, Orange Blossom and Sage',
        'Musk',
        'aromatic,fresh spicy,green,lavender,musky',
        'Le Beau MalebyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Beau Malewas launched in 2013. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mint and Wormwood; middle notes are Lavender, Orange Blossom and Sage; base note is Musk.',
        3.57,
        1,
        NULL
      ),
(
        'Le-Beau-Male-Capitaine-Collector-25585',
        'Le Beau Male Capitaine Collector Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lavender,aromatic,musky,white floral,green',
        'Le Beau Male Capitaine CollectorbyJean Paul Gaultieris a Aromatic fragrance for men.Le Beau Male Capitaine Collectorwas launched in 2014.',
        3.85,
        39,
        NULL
      ),
(
        'Le-Beau-Male-Edition-Collector-23580',
        'Le Beau Male Edition Collector Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint and Wormwood',
        'Sage, Orange Blossom and Lavender',
        'Musk',
        'aromatic,musky,fresh spicy,green,white floral',
        'Le Beau Male Edition CollectorbyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Beau Male Edition Collectorwas launched in 2014. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mint and Wormwood; middle notes are Sage, Orange Blossom and Lavender; base note is Musk.',
        4,
        17,
        NULL
      ),
(
        'Le-Beau-Male-Summer-2014-24067',
        'Le Beau Male Summer 2014 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Mint and Lavender',
        'Violet',
        'Sandalwood and Vanilla',
        'powdery,aromatic,woody,green,lavender',
        'Le Beau Male Summer 2014byJean Paul Gaultieris a Woody Aromatic fragrance for men.Le Beau Male Summer 2014was launched in 2014. Top notes are Mint and Lavender; middle note is Violet; base notes are Sandalwood and Vanilla.',
        4,
        44,
        NULL
      ),
(
        'Le-Beau-Paradise-Garden-88836',
        'Le Beau Paradise Garden Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Quentin Bisch',
        'Green Notes, Watery Notes, Mint and Ginger',
        'Coconut, Fig and Salt',
        'Tonka Bean and Sandalwood',
        'green,coconut,sweet,aquatic,vanilla',
        'Le Beau Paradise GardenbyJean Paul Gaultieris a fragrance for men. This is a new fragrance.Le Beau Paradise Gardenwas launched in 2024. The nose behind this fragrance is Quentin Bisch. Top notes are Green Notes, Watery Notes, Mint and Ginger; middle notes are Coconut, Fig and Salt; base notes are Tonka Bean and Sandalwood.',
        4.32,
        3,
        NULL
      ),
(
        'Cologne-Tonique-Le-Male-Summer-2008-3053',
        'Cologne Tonique Le Male Summer 2008 Jean Paul Gaultier',
        'Cologne',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,aromatic,vanilla,warm spicy,fresh spicy',
        'Cologne Tonique Le Male Summer 2008byJean Paul Gaultieris a Amber Fougere fragrance for men.Cologne Tonique Le Male Summer 2008was launched in 2008.',
        3.84,
        62,
        NULL
      ),
(
        'Fleur-du-Male-889',
        'Fleur du Mâle Jean Paul Gaultier',
        'Fleur',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Petitgrain',
        'Neroli',
        'Chamomile and Basil',
        'herbal,aromatic,fresh spicy,citrus,green',
        'Fleur du MâlebyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Fleur du Mâlewas launched in 2007. The nose behind this fragrance is Francis Kurkdjian. Top note is Petitgrain; middle note is Neroli; base notes are Chamomile and Basil.',
        4.13,
        2,
        NULL
      ),
(
        'La-Cologne-Fleur-du-Male-2716',
        'La Cologne Fleur du Male Jean Paul Gaultier',
        'La',
        'for men',
        NULL,
        'Francis Kurkdjian',
        NULL,
        NULL,
        NULL,
        'fresh spicy,white floral,citrus,aromatic,sweet',
        'La Cologne Fleur du MalebyJean Paul Gaultieris a Aromatic Fougere fragrance for men.La Cologne Fleur du Malewas launched in 2008. The nose behind this fragrance is Francis Kurkdjian.',
        3.99,
        498,
        NULL
      ),
(
        'Le-Male-430',
        'Le Male Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Mint, Cardamom, Bergamot and Artemisia',
        'Cinnamon, Orange Blossom and Caraway',
        'Vanilla, Tonka Bean, Amber, Sandalwood and Cedar',
        'aromatic,vanilla,fresh spicy,lavender,warm spicy',
        'Le MalebyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Malewas launched in 1995. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Mint, Cardamom, Bergamot and Artemisia; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Vanilla, Tonka Bean, Amber, Sandalwood and Cedar.',
        4.01,
        18,
        NULL
      ),
(
        'Le-Male-Aviator-58770',
        'Le Male Aviator Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Mint',
        'Violet Leaf',
        'Woodsy Notes',
        'green,ozonic,woody,aquatic,aromatic',
        'Le Male AviatorbyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Aviatorwas launched in 2020. Top note is Mint; middle note is Violet Leaf; base note is Woodsy Notes.',
        4.05,
        355,
        NULL
      ),
(
        'Le-Male-Capitaine-Collector-25584',
        'Le Male Capitaine Collector Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,aromatic,green,lavender,fresh spicy',
        'Le Male Capitaine CollectorbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Capitaine Collectorwas launched in 2014.',
        4.18,
        49,
        NULL
      ),
(
        'Le-Male-Collector-Edition-2017-47202',
        'Le Male Collector Edition 2017 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint, Cardamom, Artemisia and Bergamot',
        'Cinnamon, Orange Blossom and Caraway',
        'Vanilla, Tonka Bean, Amber, Sandalwood and Cedar',
        'aromatic,vanilla,fresh spicy,lavender,warm spicy',
        'Le Male Collector Edition 2017byJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Collector Edition 2017was launched in 2017. Top notes are Lavender, Mint, Cardamom, Artemisia and Bergamot; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Vanilla, Tonka Bean, Amber, Sandalwood and Cedar.',
        4.61,
        51,
        NULL
      ),
(
        'Le-Male-Collector-Edition-2018-51775',
        'Le Male Collector Edition 2018 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Artemisia, Mint, Cardamom and Bergamot',
        'Cinnamon, Orange Blossom and Cumin',
        'Vanilla, Tonka Bean, Amber, Sandalwood and Cedar',
        'vanilla,aromatic,amber,lavender,warm spicy',
        'Le Male Collector Edition 2018byJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Collector Edition 2018was launched in 2018. Top notes are Lavender, Artemisia, Mint, Cardamom and Bergamot; middle notes are Cinnamon, Orange Blossom and Cumin; base notes are Vanilla, Tonka Bean, Amber, Sandalwood and Cedar.',
        4.71,
        31,
        NULL
      ),
(
        'Le-Male-Collector-Edition-2022-76518',
        'Le Male Collector Edition 2022 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Artemisia, Lavender, Mint, Cardamom and Bergamot',
        'Caraway, Cinnamon and Orange Blossom',
        'Vanilla, Tonka Bean, Amber, Sandalwood and Cedar',
        'fresh spicy,herbal,aromatic,bitter',
        'Le Male Collector Edition 2022byJean Paul Gaultieris a Amber Fougere fragrance for men. This is a new fragrance.Le Male Collector Edition 2022was launched in 2022. The nose behind this fragrance is Francis Kurkdjian. Top notes are Artemisia, Lavender, Mint, Cardamom and Bergamot; middle notes are Caraway, Cinnamon and Orange Blossom; base notes are Vanilla, Tonka Bean, Amber, Sandalwood and Cedar.',
        4.11,
        18,
        NULL
      ),
(
        'Le-Male-Collector-s-Snow-Globe-57184',
        'Le Male Collector''s Snow Globe Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Cardamom, Mint, Bergamot and Artemisia',
        'Orange Blossom, Cinnamon and Caraway',
        'Vanilla, Tonka Bean, Sandalwood, Amber and Cedar',
        'aromatic,vanilla,warm spicy,amber,woody',
        'Le Male Collector''s Snow GlobebyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Collector''s Snow Globewas launched in 2019. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Cardamom, Mint, Bergamot and Artemisia; middle notes are Orange Blossom, Cinnamon and Caraway; base notes are Vanilla, Tonka Bean, Sandalwood, Amber and Cedar.',
        4.7,
        54,
        NULL
      ),
(
        'Le-Male-Couple-18825',
        'Le Male Couple Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint, Bergamot, Artemisia and Cardamom',
        'Orange Blossom, Cinnamon and Caraway',
        'Vanilla, Cedar, Sandalwood, Amber and Tonka Bean',
        'aromatic,woody,vanilla,fresh spicy,lavender',
        'Le Male CouplebyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Couplewas launched in 2013. Top notes are Lavender, Mint, Bergamot, Artemisia and Cardamom; middle notes are Orange Blossom, Cinnamon and Caraway; base notes are Vanilla, Cedar, Sandalwood, Amber and Tonka Bean.',
        4.13,
        67,
        NULL
      ),
(
        'Le-Male-Eau-d-Ete-2004-6022',
        'Le Male Eau d''Ete 2004 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Mint, Bergamot, Cardamom, Artemisia and Ginger',
        'Lavender, Orange Blossom, Cinnamon, Caraway and Ginseng',
        'Vanilla, Tonka Bean, Amber, Sandalwood and Cedar',
        'aromatic,vanilla,warm spicy,fresh spicy,green',
        'Le Male Eau d''Ete 2004byJean Paul Gaultieris a fragrance for men.Le Male Eau d''Ete 2004was launched in 2004. Top notes are Mint, Bergamot, Cardamom, Artemisia and Ginger; middle notes are Lavender, Orange Blossom, Cinnamon, Caraway and Ginseng; base notes are Vanilla, Tonka Bean, Amber, Sandalwood and Cedar.',
        4.09,
        22,
        NULL
      ),
(
        'Le-Male-Eau-de-Toilette-Airlines-60944',
        'Le Male Eau de Toilette Airlines Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint, Cardamom, Lavender, Bergamot and Artemisia',
        'Cinnamon, Orange Blossom and Caraway',
        'Vanilla, Tonka Bean, Cedar, Sandalwood and Amber',
        'aromatic,warm spicy,fresh spicy,vanilla,woody',
        'Le Male Eau de Toilette AirlinesbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Eau de Toilette Airlineswas launched in 2020. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mint, Cardamom, Lavender, Bergamot and Artemisia; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Vanilla, Tonka Bean, Cedar, Sandalwood and Amber.',
        4.35,
        142,
        NULL
      ),
(
        'Le-Male-Eau-Fraiche-Andre-Edition-48898',
        'Le Mâle Eau Fraîche André Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Mint, Aldehydes and Neroli',
        'Amber, Sage, Geranium, Clary Sage and Woody Notes',
        'Vanilla, Tonka Bean, Iso E Super and Sandalwood',
        'aromatic,vanilla,amber,green,woody',
        'Le Mâle Eau Fraîche André EditionbyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Mâle Eau Fraîche André Editionwas launched in 2018. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Mint, Aldehydes and Neroli; middle notes are Amber, Sage, Geranium, Clary Sage and Woody Notes; base notes are Vanilla, Tonka Bean, Iso E Super and Sandalwood.',
        4.15,
        256,
        NULL
      ),
(
        'Le-Male-Eau-Fraiche-Gaultier-Airlines-48905',
        'Le Mâle Eau Fraîche Gaultier Airlines Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Mint, Neroli and Aldehydes',
        'Clary Sage, Sage, Woody Notes and Amber',
        'Vanilla, Tonka Bean and Sandalwood',
        'aromatic,vanilla,green,fresh spicy,woody',
        'Le Mâle Eau Fraîche Gaultier AirlinesbyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Mâle Eau Fraîche Gaultier Airlineswas launched in 2018. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Mint, Neroli and Aldehydes; middle notes are Clary Sage, Sage, Woody Notes and Amber; base notes are Vanilla, Tonka Bean and Sandalwood.',
        4.03,
        101,
        NULL
      ),
(
        'Le-Male-Edition-Collector-23579',
        'Le Male Edition Collector Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Cardamom, Mint, Bergamot and Artemisia',
        'Orange Blossom, Cinnamon and Caraway',
        'Tonka Bean, Sandalwood, Cedar, Amber and Vanilla',
        'aromatic,warm spicy,fresh spicy,woody,citrus',
        'Le Male Edition CollectorbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Edition Collectorwas launched in 2014. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Cardamom, Mint, Bergamot and Artemisia; middle notes are Orange Blossom, Cinnamon and Caraway; base notes are Tonka Bean, Sandalwood, Cedar, Amber and Vanilla.',
        3.6,
        15,
        NULL
      ),
(
        'Le-Male-Elixir-81642',
        'Le Male Elixir Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Quentin Bisch',
        'Lavender and Mint',
        'Vanilla and Benzoin',
        'Honey, Tonka Bean and Tobacco',
        'vanilla,sweet,honey,amber,aromatic',
        'Le Male ElixirbyJean Paul Gaultieris a Amber Fougere fragrance for men. This is a new fragrance.Le Male Elixirwas launched in 2023. The nose behind this fragrance is Quentin Bisch. Top notes are Lavender and Mint; middle notes are Vanilla and Benzoin; base notes are Honey, Tonka Bean and Tobacco.',
        4.56,
        10,
        NULL
      ),
(
        'Le-Male-Essence-de-Parfum-39583',
        'Le Male Essence de Parfum Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Quentin Bisch',
        'Cardamom, Pepper, Bergamot and Artemisia',
        'Leather, Lavender, Cinnamon and Sage',
        'Vanilla, Coumarin, Amberwood, Musk and Costus',
        'warm spicy,aromatic,leather,vanilla,lavender',
        'Le Male Essence de ParfumbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Essence de Parfumwas launched in 2016. The nose behind this fragrance is Quentin Bisch. Top notes are Cardamom, Pepper, Bergamot and Artemisia; middle notes are Leather, Lavender, Cinnamon and Sage; base notes are Vanilla, Coumarin, Amberwood, Musk and Costus.',
        4.21,
        1,
        NULL
      ),
(
        'Le-Male-Gladiator-15558',
        'Le Male Gladiator Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Mint',
        'Lavender and Mint',
        'Vanilla, Tonka Bean and Amber',
        'vanilla,aromatic,lavender,green,amber',
        'Le Male GladiatorbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Gladiatorwas launched in 2012. Top note is Mint; middle notes are Lavender and Mint; base notes are Vanilla, Tonka Bean and Amber.',
        3.96,
        50,
        NULL
      ),
(
        'Le-Male-In-The-Navy-51058',
        'Le Male In The Navy Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Mint and Watery Notes',
        'Sea Notes',
        'Vanilla and Ambergris',
        'aromatic,marine,green,vanilla,aquatic',
        'Le Male In The NavybyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male In The Navywas launched in 2018. Le Male In The Navy was created by Quentin Bisch and Natalie Gracia-Cetto. Top notes are Mint and Watery Notes; middle note is Sea Notes; base notes are Vanilla and Ambergris.',
        4.07,
        705,
        NULL
      ),
(
        'Le-Male-Jean-Paul-Cool-17671',
        'Le Male Jean Paul Cool Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Le Male Jean Paul CoolbyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Jean Paul Coolwas launched in 2003.',
        2.96,
        52,
        NULL
      ),
(
        'Le-Male-Kilt-6021',
        'Le Male Kilt Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,warm spicy,lavender,vanilla',
        'Le Male KiltbyJean Paul Gaultieris a fragrance for men.Le Male Kiltwas launched in 2006.',
        4.09,
        22,
        NULL
      ),
(
        'Le-Male-Le-Parfum-61856',
        'Le Male Le Parfum Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Cardamom',
        'Lavender and Iris',
        'Vanilla, Oriental notes and Woodsy Notes',
        'warm spicy,vanilla,lavender,aromatic,powdery',
        'Le Male Le ParfumbyJean Paul Gaultieris a Amber fragrance for men.Le Male Le Parfumwas launched in 2020. Le Male Le Parfum was created by Quentin Bisch and Natalie Gracia-Cetto. Top note is Cardamom; middle notes are Lavender and Iris; base notes are Vanilla, Oriental notes and Woodsy Notes.',
        4.6,
        13,
        NULL
      ),
(
        'Le-Male-Les-d-Ete-2005-431',
        'Le Male Les d''Ete 2005 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Bergamot and Mint',
        'Ginseng, Lavender and Ginger',
        'Vanilla, Tonka Bean, Amber, Musk and Woody Notes',
        'vanilla,aromatic,fresh spicy,green,amber',
        'Le Male Les d''Ete 2005byJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Les d''Ete 2005was launched in 2005. The nose behind this fragrance is Francis Kurkdjian. Top notes are Bergamot and Mint; middle notes are Ginseng, Lavender and Ginger; base notes are Vanilla, Tonka Bean, Amber, Musk and Woody Notes.',
        4.21,
        42,
        NULL
      ),
(
        'Le-Male-Limited-Edition-2009-7186',
        'Le Male Limited Edition 2009 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Mint and Bergamot',
        'African Orange Flower, Caraway and Cinnamon',
        'Vanille, Sandalwood, Virginia Cedar and Tonka Bean',
        'aromatic,fresh spicy,citrus,woody,white floral',
        'Le Male Limited Edition 2009byJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Limited Edition 2009was launched in 2009. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Mint and Bergamot; middle notes are African Orange Flower, Caraway and Cinnamon; base notes are Vanille, Sandalwood, Virginia Cedar and Tonka Bean.',
        4,
        14,
        NULL
      ),
(
        'Le-Male-Love-Actually-11358',
        'Le Male Love Actually Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Artemisia, Lavender, Mint, Bergamot and Cardamom',
        'Cinnamon, Orange Blossom and Caraway',
        'Amber, Sandalwood, Tonka Bean, Vanilla and Cedar',
        'warm spicy,aromatic,amber,cinnamon,woody',
        'Le Male Love ActuallybyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Love Actuallywas launched in 2011. The nose behind this fragrance is Francis Kurkdjian. Top notes are Artemisia, Lavender, Mint, Bergamot and Cardamom; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Amber, Sandalwood, Tonka Bean, Vanilla and Cedar.',
        4.22,
        46,
        NULL
      ),
(
        'Le-Male-Lover-89720',
        'Le Male Lover Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'White Pepper and Finger Lime',
        'Ambergris, Musk and Sea Notes',
        'Vanilla and Woody Notes',
        'vanilla,amber,fresh spicy,powdery,animalic',
        'Le Male LoverbyJean Paul Gaultieris a Amber Vanilla fragrance for men. This is a new fragrance.Le Male Loverwas launched in 2024. Le Male Lover was created by Natalie Gracia-Cetto and Quentin Bisch. Top notes are White Pepper and Finger Lime; middle notes are Ambergris, Musk and Sea Notes; base notes are Vanilla and Woody Notes.',
        3.89,
        586,
        NULL
      ),
(
        'Le-Male-On-Board-65595',
        'Le Male On Board Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Christophe Raynaud',
        'Bergamot',
        'Tonka Bean and Geranium',
        'Amber',
        'fresh spicy,aromatic,amber,citrus,vanilla',
        'Le Male On BoardbyJean Paul Gaultieris a fragrance for men.Le Male On Boardwas launched in 2021. The nose behind this fragrance is Christophe Raynaud. Top note is Bergamot; middle notes are Tonka Bean and Geranium; base note is Amber.',
        4.1,
        328,
        NULL
      ),
(
        'Le-Male-Pin-Up-Collectors-Edition-28007',
        'Le Male Pin-Up Collectors Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint, Bergamot, Cardamom and Artemisia',
        'Cumin, Orange Blossom and Cinnamon',
        'Vanilla, Sandalwood, Tonka Bean, Amber and Cedar',
        'vanilla,aromatic,fresh spicy,green,powdery',
        'Le Male Pin-Up Collectors EditionbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Pin-Up Collectors Editionwas launched in 2014. Top notes are Lavender, Mint, Bergamot, Cardamom and Artemisia; middle notes are Cumin, Orange Blossom and Cinnamon; base notes are Vanilla, Sandalwood, Tonka Bean, Amber and Cedar.',
        4.28,
        18,
        NULL
      ),
(
        'Le-Male-Pirate-Edition-29797',
        'Le Male Pirate Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint, Lavender, Cardamom, Artemisia and Bergamot',
        'Cinnamon, Orange Blossom and Caraway',
        'Tonka Bean, Vanilla, Sandalwood, Amber and Cedar',
        'aromatic,warm spicy,fresh spicy,vanilla,green',
        'Le Male Pirate EditionbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Pirate Editionwas launched in 2015. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mint, Lavender, Cardamom, Artemisia and Bergamot; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Tonka Bean, Vanilla, Sandalwood, Amber and Cedar.',
        3.53,
        32,
        NULL
      ),
(
        'Le-Male-Popeye-Eau-Fraiche-36636',
        'Le Male Popeye Eau Fraiche Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Mint, Aldehydes and Neroli',
        'Sage and Sclarene',
        'Vanilla, Tonka Bean and Sandalwood',
        'vanilla,aromatic,green,aldehydic,fresh spicy',
        'Le Male Popeye Eau FraichebyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Popeye Eau Fraichewas launched in 2016. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Mint, Aldehydes and Neroli; middle notes are Sage and Sclarene; base notes are Vanilla, Tonka Bean and Sandalwood.',
        4.25,
        782,
        NULL
      ),
(
        'Le-Male-Prestige-Edition-55679',
        'Le Male Prestige Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Bergamot, Artemisia, Mint and Cardamom',
        'Orange Blossom, Caraway and Cinnamon',
        'Vanilla, Sandalwood, Tonka Bean, Amber and Cedar',
        'vanilla,aromatic,lavender,fresh spicy,powdery',
        'Le Male Prestige EditionbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Prestige Editionwas launched in 2010. Top notes are Lavender, Bergamot, Artemisia, Mint and Cardamom; middle notes are Orange Blossom, Caraway and Cinnamon; base notes are Vanilla, Sandalwood, Tonka Bean, Amber and Cedar.',
        4.15,
        13,
        NULL
      ),
(
        'Le-Male-Pride-2023-81774',
        'Le Male Pride 2023 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Yuzu and Blood Orange',
        'Neroli and Orange Blossom',
        'Musk and White Woods',
        'citrus,white floral,sweet,fresh spicy,green',
        'Le Male Pride 2023byJean Paul Gaultieris a fragrance for men. This is a new fragrance.Le Male Pride 2023was launched in 2023. Top notes are Yuzu and Blood Orange; middle notes are Neroli and Orange Blossom; base notes are Musk and White Woods.',
        1.95,
        531,
        NULL
      ),
(
        'Le-Male-Pride-2024-90393',
        'Le Male Pride 2024 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Citruses and Yuzu',
        'Neroli and Orange Blossom',
        'Woodsy Notes and Musk',
        'white floral,citrus,fresh,soapy',
        'Le Male Pride 2024byJean Paul Gaultieris a Citrus fragrance for men. This is a new fragrance.Le Male Pride 2024was launched in 2024. Top notes are Citruses and Yuzu; middle notes are Neroli and Orange Blossom; base notes are Woodsy Notes and Musk.',
        1.95,
        285,
        NULL
      ),
(
        'Le-Male-Pride-Collector-60765',
        'Le Mâle Pride Collector Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint, Lavender, Cardamom, Artemisia and Bergamot',
        'Caraway, Cinnamon and Orange Blossom',
        'Vanilla, Sandalwood, Amber, Cedar and Tonka Bean',
        'aromatic,warm spicy,fresh spicy,cinnamon,vanilla',
        'Le Mâle Pride CollectorbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Mâle Pride Collectorwas launched in 2020. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mint, Lavender, Cardamom, Artemisia and Bergamot; middle notes are Caraway, Cinnamon and Orange Blossom; base notes are Vanilla, Sandalwood, Amber, Cedar and Tonka Bean.',
        1.93,
        632,
        NULL
      ),
(
        'Le-Male-Pride-Edition-73607',
        'Le Male Pride Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Blood Orange and Yuzu',
        'Neroli and Orange Blossom',
        'Musk and White Woods',
        'citrus,white floral,fresh spicy,sweet,musky',
        'Le Male Pride EditionbyJean Paul Gaultieris a Citrus Aromatic fragrance for men. This is a new fragrance.Le Male Pride Editionwas launched in 2022. Le Male Pride Edition was created by Natalie Gracia-Cetto and Quentin Bisch. Top notes are Blood Orange and Yuzu; middle notes are Neroli and Orange Blossom; base notes are Musk and White Woods.',
        2.53,
        662,
        NULL
      ),
(
        'Le-Male-Scuba-Diver-2849',
        'Le Male Scuba Diver Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Mint and Bergamot',
        'Spices and Lavender',
        'Vanilla, Tonka Bean and Woodsy Notes',
        'vanilla,aromatic,warm spicy,green,lavender',
        'Le Male Scuba DiverbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Scuba Diverwas launched in 2007. Top notes are Mint and Bergamot; middle notes are Spices and Lavender; base notes are Vanilla, Tonka Bean and Woodsy Notes.',
        4.4,
        35,
        NULL
      ),
(
        'Le-Male-Shaker-Limited-Edition-11348',
        'Le Male Shaker Limited Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Artemisia, Mint, Bergamot and Cardamom',
        'Orange Blossom, Caraway and Cinnamon',
        'Sandalwood, Tonka Bean, Amber, Vanilla and Cedar',
        'aromatic,fresh spicy,white floral,lavender,citrus',
        'Le Male Shaker Limited EditionbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Shaker Limited Editionwas launched in 2011. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Artemisia, Mint, Bergamot and Cardamom; middle notes are Orange Blossom, Caraway and Cinnamon; base notes are Sandalwood, Tonka Bean, Amber, Vanilla and Cedar.',
        4.42,
        24,
        NULL
      ),
(
        'Le-Male-Silver-My-Skin-13148',
        'Le Male Silver My Skin Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Mint, Artemisia, Cardamom and Bergamot',
        'Cinnamon, Caraway and African Orange Flower',
        'Vanille, Tonka Bean, Sandalwood, Amber and Virginia Cedar',
        'aromatic,vanilla,fresh spicy,lavender,warm spicy',
        'Le Male Silver My SkinbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Silver My Skinwas launched in 2011. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Mint, Artemisia, Cardamom and Bergamot; middle notes are Cinnamon, Caraway and African Orange Flower; base notes are Vanille, Tonka Bean, Sandalwood, Amber and Virginia Cedar.',
        4.45,
        55,
        NULL
      ),
(
        'Le-Male-Stimulating-Body-Spray-2006-432',
        'Le Male Stimulating Body Spray 2006 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Mint and Bergamot',
        'Cinnamon and Thyme',
        'Vanilla',
        'vanilla,aromatic,lavender,fresh spicy,green',
        'Le Male Stimulating Body Spray 2006byJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Stimulating Body Spray 2006was launched in 2006. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Mint and Bergamot; middle notes are Cinnamon and Thyme; base note is Vanilla.',
        3.79,
        28,
        NULL
      ),
(
        'Le-Male-Summer-2010-8145',
        'Le Male Summer 2010 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,warm spicy,aromatic,herbal,fresh spicy',
        'Le Male Summer 2010byJean Paul Gaultieris a Aromatic fragrance for men.Le Male Summer 2010was launched in 2010.',
        3.8,
        56,
        NULL
      ),
(
        'Le-Male-Summer-2011-11598',
        'Le Male Summer 2011 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint and Cardamom',
        'African Orange Flower',
        'Vanille, Sandalwood and Musk',
        'vanilla,powdery,white floral,aromatic,lavender',
        'Le Male Summer 2011byJean Paul Gaultieris a Aromatic fragrance for men.Le Male Summer 2011was launched in 2011. Top notes are Lavender, Mint and Cardamom; middle note is African Orange Flower; base notes are Vanille, Sandalwood and Musk.',
        4.28,
        82,
        NULL
      ),
(
        'Le-Male-Summer-2012-14648',
        'Le Male Summer 2012 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint and Cardamom',
        'Grass and Green Notes',
        'Vanilla, Musk and Sandalwood',
        'green,aromatic,vanilla,lavender,powdery',
        'Le Male Summer 2012byJean Paul Gaultieris a Aromatic fragrance for men.Le Male Summer 2012was launched in 2012. Top notes are Lavender, Mint and Cardamom; middle notes are Grass and Green Notes; base notes are Vanilla, Musk and Sandalwood.',
        4.17,
        118,
        NULL
      ),
(
        'Le-Male-Summer-2013-17823',
        'Le Male Summer 2013 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint and Cardamom',
        'Green Leaves and Grass',
        'Vanilla, Sandalwood and Musk',
        'green,aromatic,lavender,vanilla,powdery',
        'Le Male Summer 2013byJean Paul Gaultieris a Aromatic fragrance for men.Le Male Summer 2013was launched in 2013. Top notes are Lavender, Mint and Cardamom; middle notes are Green Leaves and Grass; base notes are Vanilla, Sandalwood and Musk.',
        4.31,
        87,
        NULL
      ),
(
        'Le-Male-Summer-2014-24066',
        'Le Male Summer 2014 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint and Cardamom',
        'Grass and Green Leaves',
        'Vanila, Musk and Sandalwood',
        'green,vanilla,aromatic,lavender,powdery',
        'Le Male Summer 2014byJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Summer 2014was launched in 2014. Top notes are Lavender, Mint and Cardamom; middle notes are Grass and Green Leaves; base notes are Vanila, Musk and Sandalwood.',
        4.15,
        62,
        NULL
      ),
(
        'Le-Male-Summer-2015-29801',
        'Le Male Summer 2015 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Lavender, Cardamom and Mint',
        'Grass and Green Notes',
        'Vanilla, Sandalwood and Musk',
        'aromatic,warm spicy,lavender,vanilla,green',
        'Le Male Summer 2015byJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Summer 2015was launched in 2015. Top notes are Lavender, Cardamom and Mint; middle notes are Grass and Green Notes; base notes are Vanilla, Sandalwood and Musk.',
        3.95,
        73,
        NULL
      ),
(
        'Le-Male-Summer-Fragrance-2009-5789',
        'Le Male Summer Fragrance 2009 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,warm spicy,vanilla,green',
        'Le Male Summer Fragrance 2009byJean Paul Gaultieris a Aromatic Aquatic fragrance for men.Le Male Summer Fragrance 2009was launched in 2009.',
        3.91,
        68,
        NULL
      ),
(
        'Le-Male-Superman-Eau-Fraiche-43712',
        'Le Male Superman Eau Fraiche Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Mint, Aldehydes and Neroli',
        'Sage, Clary Sage, Amber and Woody Notes',
        'Vanilla, Tonka Bean and Sandalwood',
        'aromatic,vanilla,green,aldehydic,amber',
        'Le Male Superman Eau FraichebyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Superman Eau Fraichewas launched in 2017. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Mint, Aldehydes and Neroli; middle notes are Sage, Clary Sage, Amber and Woody Notes; base notes are Vanilla, Tonka Bean and Sandalwood.',
        4.25,
        807,
        NULL
      ),
(
        'Le-Male-Supreme-Edition-55678',
        'Le Male Supreme Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint, Artemisia, Lavender, Bergamot and Cardamom',
        'Caraway, Orange Blossom and Cinnamon',
        'Vanilla, Cedar, Sandalwood, Tonka Bean and Amber',
        'aromatic,fresh spicy,warm spicy,green,herbal',
        'Le Male Supreme EditionbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Supreme Editionwas launched in 2019. The nose behind this fragrance is Francis Kurkdjian. Top notes are Mint, Artemisia, Lavender, Bergamot and Cardamom; middle notes are Caraway, Orange Blossom and Cinnamon; base notes are Vanilla, Cedar, Sandalwood, Tonka Bean and Amber.',
        3.24,
        17,
        NULL
      ),
(
        'Le-Male-Terrible-9502',
        'Le Male Terrible Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Aurélien Guichard',
        'Grapefruit and Pink Pepper',
        'Lavender and Vetyver',
        'Vanille and Amber',
        'lavender,vanilla,aromatic,citrus,soft spicy',
        'Le Male TerriblebyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Terriblewas launched in 2010. The nose behind this fragrance is Aurélien Guichard. Top notes are Grapefruit and Pink Pepper; middle notes are Lavender and Vetyver; base notes are Vanille and Amber.',
        4.11,
        991,
        NULL
      ),
(
        'Le-Male-Terrible-Shaker-11349',
        'Le Male Terrible Shaker Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Aurélien Guichard',
        'Grapefruit and Pink Pepper',
        'Lavender and Vetiver',
        'Amber and Vanille',
        'citrus,fresh spicy,lavender,aromatic,vanilla',
        'Le Male Terrible ShakerbyJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Terrible Shakerwas launched in 2011. The nose behind this fragrance is Aurélien Guichard. Top notes are Grapefruit and Pink Pepper; middle notes are Lavender and Vetiver; base notes are Amber and Vanille.',
        4,
        23,
        NULL
      ),
(
        'Le-Male-Tonique-Cologne-945',
        'Le Male Tonique Cologne Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        NULL,
        'Mint',
        'Ginger',
        'Lavender and Vanilla',
        'lavender,aromatic,vanilla,green,warm spicy',
        'Le Male Tonique ColognebyJean Paul Gaultieris a Aromatic Fougere fragrance for men.Le Male Tonique Colognewas launched in 2007. Top note is Mint; middle note is Ginger; base notes are Lavender and Vanilla.',
        4.33,
        30,
        NULL
      ),
(
        'Le-Male-X-Mas-Edition-2020-64055',
        'Le Male X-Mas Edition 2020 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Cardamom, Mint, Artemisia and Bergamot',
        'Cinnamon, Orange Blossom and Caraway',
        'Sandalwood, Vanilla, Tonka Bean, Cedar and Amber',
        'warm spicy,aromatic,woody,vanilla,lavender',
        'Le Male X-Mas Edition 2020byJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male X-Mas Edition 2020was launched in 2020. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Cardamom, Mint, Artemisia and Bergamot; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Sandalwood, Vanilla, Tonka Bean, Cedar and Amber.',
        4.53,
        53,
        NULL
      ),
(
        'Le-Male-Xmas-Limited-Edition-87350',
        'Le Male Xmas Limited Edition Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Mint',
        'Lavender',
        'Vanilla',
        'lavender,vanilla,aromatic,fresh spicy,green',
        'Le Male Xmas Limited EditionbyJean Paul Gaultieris a Aromatic fragrance for men. This is a new fragrance.Le Male Xmas Limited Editionwas launched in 2023. The nose behind this fragrance is Francis Kurkdjian. Top note is Mint; middle note is Lavender; base note is Vanilla.',
        3.22,
        83,
        NULL
      ),
(
        'Le-Male-Xmas-Limited-Edition-2021-70255',
        'Le Male Xmas Limited Edition 2021 Jean Paul Gaultier',
        'Le',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Lavender, Mint, Artemisia, Cardamom and Bergamot',
        'Cinnamon, Orange Blossom and Caraway',
        'Vanilla, Tonka Bean, Amber, Sandalwood and Cedar',
        'aromatic,vanilla,woody,fresh spicy,warm spicy',
        'Le Male Xmas Limited Edition 2021byJean Paul Gaultieris a Amber Fougere fragrance for men.Le Male Xmas Limited Edition 2021was launched in 2021. The nose behind this fragrance is Francis Kurkdjian. Top notes are Lavender, Mint, Artemisia, Cardamom and Bergamot; middle notes are Cinnamon, Orange Blossom and Caraway; base notes are Vanilla, Tonka Bean, Amber, Sandalwood and Cedar.',
        4.75,
        12,
        NULL
      ),
(
        'Super-Le-Male-Collector-53063',
        'Super Le Male Collector Jean Paul Gaultier',
        'Super',
        'for men',
        NULL,
        NULL,
        'Lavender, Mint, Bergamot, Artemisia and Cardamom',
        'Cinnamon, Caraway and Orange Blossom',
        'Amber, Vanilla, Sandalwood, Tonka Bean and Cedar',
        'vanilla,amber,aromatic,fresh spicy,green',
        'Super Le Male CollectorbyJean Paul Gaultieris a Amber Fougere fragrance for men.Super Le Male Collectorwas launched in 2010. Top notes are Lavender, Mint, Bergamot, Artemisia and Cardamom; middle notes are Cinnamon, Caraway and Orange Blossom; base notes are Amber, Vanilla, Sandalwood, Tonka Bean and Cedar.',
        4.14,
        7,
        NULL
      ),
(
        'Ultra-Male-30947',
        'Ultra Male Jean Paul Gaultier',
        'Ultra',
        'for men',
        NULL,
        'Francis Kurkdjian',
        'Pear, Lavender, Mint, Bergamot and Lemon',
        'Cinnamon, Clary Sage and Caraway',
        'Black Vanilla Husk, Amber, Patchouli and Cedar',
        'vanilla,fruity,sweet,aromatic,cinnamon',
        'Ultra MalebyJean Paul Gaultieris a Amber Fougere fragrance for men.Ultra Malewas launched in 2015. The nose behind this fragrance is Francis Kurkdjian. Top notes are Pear, Lavender, Mint, Bergamot and Lemon; middle notes are Cinnamon, Clary Sage and Caraway; base notes are Black Vanilla Husk, Amber, Patchouli and Cedar.',
        4.44,
        12,
        NULL
      ),
(
        'Ma-Dame-3681',
        'Ma Dame Jean Paul Gaultier',
        'Ma',
        'for women',
        NULL,
        'Francis Kurkdjian',
        'Orange',
        'Grenadine and Rose',
        'Musk and Virginia Cedar',
        'sweet,fruity,citrus,rose,musky',
        'Ma DamebyJean Paul Gaultieris a Floral fragrance for women.Ma Damewas launched in 2008. The nose behind this fragrance is Francis Kurkdjian. Top note is Orange; middle notes are Grenadine and Rose; base notes are Musk and Virginia Cedar.',
        3.76,
        2,
        NULL
      ),
(
        'Ma-Dame-Eau-de-Parfum-8001',
        'Ma Dame Eau de Parfum Jean Paul Gaultier',
        'Ma',
        'for women',
        NULL,
        NULL,
        'Pink Pepper and Orange',
        'Rose and Patchouli',
        'Musk and Virginia Cedar',
        'woody,rose,musky,patchouli,soft spicy',
        'Ma Dame Eau de ParfumbyJean Paul Gaultieris a Chypre Floral fragrance for women.Ma Dame Eau de Parfumwas launched in 2010. Top notes are Pink Pepper and Orange; middle notes are Rose and Patchouli; base notes are Musk and Virginia Cedar.',
        3.93,
        688,
        NULL
      );
