
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'English-Sun-82042',
        'English Sun Bibliothèque de Parfum',
        'English',
        'for women and men',
        NULL,
        NULL,
        'Lily of the Valley and Tahitian Vanilla',
        'Madagascar Vanilla and Jasmine',
        'Amber, Oud and Ambergris',
        'white floral,amber,oud,vanilla,animalic',
        'English SunbyBibliothèque de Parfumis a Amber Spicy fragrance for women and men.English Sunwas launched in 2019. Top notes are Lily of the Valley and Tahitian Vanilla; middle notes are Madagascar Vanilla and Jasmine; base notes are Amber, Oud and Ambergris.',
        1,
        1,
        NULL
      ),
(
        'I-Want-82043',
        'I Want Bibliothèque de Parfum',
        'I',
        'for women and men',
        NULL,
        NULL,
        'Bitter Almond, Cherry and Liquor',
        'Cherry, Plum, Turkish Rose and Jasmine Sambac',
        'Sandalwood, Vetiver, Cloves, Cedar, Tonka, Benzoin, Peru Balsam, Cinnamon, Patchouli and Vanilla',
        'woody,amber,warm spicy,almond,fruity',
        'I WantbyBibliothèque de Parfumis a Floral Fruity Gourmand fragrance for women and men.I Wantwas launched in 2019. Top notes are Bitter Almond, Cherry and Liquor; middle notes are Cherry, Plum, Turkish Rose and Jasmine Sambac; base notes are Sandalwood, Vetiver, Cloves, Cedar, Tonka, Benzoin, Peru Balsam, Cinnamon, Patchouli and Vanilla.',
        4,
        18,
        NULL
      ),
(
        'Icy-Wave-82050',
        'Icy Wave Bibliothèque de Parfum',
        'Icy',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, Bergamot and Lime',
        'Green Tea, Black Currant and Herbal Notes',
        'Sandalwood, Petitgrain, Galbanum and Musk',
        'green,citrus,woody,aromatic,fruity',
        'Icy WavebyBibliothèque de Parfumis a Citrus Aromatic fragrance for women and men.Icy Wavewas launched in 2019. Top notes are Tangerine, Bergamot and Lime; middle notes are Green Tea, Black Currant and Herbal Notes; base notes are Sandalwood, Petitgrain, Galbanum and Musk.',
        4,
        1,
        NULL
      ),
(
        'Leather-Bliss-82040',
        'Leather Bliss Bibliothèque de Parfum',
        'Leather',
        'for women and men',
        NULL,
        NULL,
        'Vanilla, Leather and Tomato Leaf',
        'Tomato Leaf, Labdanum, Galbanum, Nutmeg, Sage and Orris Root',
        'Opoponax, Vanilla, Benzoin, Leather, Sandal, Musk, Myrrh and Tolu Balsam',
        'amber,powdery,aromatic,balsamic,warm spicy',
        'Leather BlissbyBibliothèque de Parfumis a Leather fragrance for women and men.Leather Blisswas launched in 2019. Top notes are Vanilla, Leather and Tomato Leaf; middle notes are Tomato Leaf, Labdanum, Galbanum, Nutmeg, Sage and Orris Root; base notes are Opoponax, Vanilla, Benzoin, Leather, Sandal, Musk, Myrrh and Tolu Balsam.',
        4.67,
        3,
        NULL
      ),
(
        'Lost-In-Bali-82057',
        'Lost In Bali Bibliothèque de Parfum',
        'Lost',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Bergamot, Cardamom and Pistachio',
        'Ylang-Ylang, Tuberose and Jasmine',
        'Benzoin, Coconut, Amber and Tonka',
        'amber,white floral,warm spicy,sweet,vanilla',
        'Lost In BalibyBibliothèque de Parfumis a Citrus Aromatic fragrance for women and men.Lost In Baliwas launched in 2019. Top notes are Pink Pepper, Bergamot, Cardamom and Pistachio; middle notes are Ylang-Ylang, Tuberose and Jasmine; base notes are Benzoin, Coconut, Amber and Tonka.',
        4.5,
        4,
        NULL
      ),
(
        'Love-Catcher-82056',
        'Love Catcher Bibliothèque de Parfum',
        'Love',
        'for women and men',
        NULL,
        NULL,
        'Tangerine, Bergamot, Pink Pepper, Magnolia and Spices',
        'Freesia, Wildflowers, Rose, Osmanthus and Tiare Flower',
        'Virginian Cedar, Musk, Sandalwood and Cashmeran',
        'floral,citrus,woody,musky,powdery',
        'Love CatcherbyBibliothèque de Parfumis a Citrus Aromatic fragrance for women and men.Love Catcherwas launched in 2019. Top notes are Tangerine, Bergamot, Pink Pepper, Magnolia and Spices; middle notes are Freesia, Wildflowers, Rose, Osmanthus and Tiare Flower; base notes are Virginian Cedar, Musk, Sandalwood and Cashmeran.',
        4,
        2,
        NULL
      ),
(
        'Love-Is-A-Drug-82049',
        'Love Is A Drug Bibliothèque de Parfum',
        'Love',
        'for women',
        NULL,
        NULL,
        'Osmanthus, Jasmine and Rose de Mai',
        'Indian Tuberose and Narcissus',
        'Amber and Cedar',
        'white floral,amber,tuberose,floral,fruity',
        'Love Is A DrugbyBibliothèque de Parfumis a Floral fragrance for women.Love Is A Drugwas launched in 2019. Top notes are Osmanthus, Jasmine and Rose de Mai; middle notes are Indian Tuberose and Narcissus; base notes are Amber and Cedar.',
        3.4,
        5,
        NULL
      ),
(
        'Memoirs-of-Geisha-82048',
        'Memoirs of Geisha Bibliothèque de Parfum',
        'Memoirs',
        'for women and men',
        NULL,
        NULL,
        'Water Jasmine, Ylang-Ylang, Bergamot and Grass',
        'Lily, White Heliotrope, Violet Leaves, Damask Rose, Peach and Pear Blossom',
        'Amber, Cashmere Wood, Coconut, Ebony, Vanilla, Sugar and Tonka',
        'white floral,yellow floral,woody,floral,amber',
        'Memoirs of GeishabyBibliothèque de Parfumis a Floral fragrance for women and men.Memoirs of Geishawas launched in 2019. Top notes are Water Jasmine, Ylang-Ylang, Bergamot and Grass; middle notes are Lily, White Heliotrope, Violet Leaves, Damask Rose, Peach and Pear Blossom; base notes are Amber, Cashmere Wood, Coconut, Ebony, Vanilla, Sugar and Tonka.',
        3.17,
        6,
        NULL
      ),
(
        'Nirvana-82045',
        'Nirvana Bibliothèque de Parfum',
        'Nirvana',
        'for women and men',
        NULL,
        NULL,
        'Jasmine',
        'Iris',
        'Iso E Super and Ambroxan',
        'amber,musky,woody,iris,white floral',
        'NirvanabyBibliothèque de Parfumis a Floral fragrance for women and men.Nirvanawas launched in 2019. Top note is Jasmine; middle note is Iris; base notes are Iso E Super and Ambroxan.',
        4.17,
        6,
        NULL
      ),
(
        'P-S-82053',
        'P.S. Bibliothèque de Parfum',
        'P.S.',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Litchi and Peach',
        'Orange Blossom, Jasmine and Peony',
        'Woody Notes, Musk and Moss',
        'white floral,citrus,floral,fresh,woody',
        'P.S.byBibliothèque de Parfumis a Floral fragrance for women and men.P.S.was launched in 2019. Top notes are Bergamot, Litchi and Peach; middle notes are Orange Blossom, Jasmine and Peony; base notes are Woody Notes, Musk and Moss.',
        4,
        2,
        NULL
      ),
(
        'Page-69-82054',
        'Page 69 Bibliothèque de Parfum',
        'Page',
        'for women and men',
        NULL,
        NULL,
        'Bitter Orange, Red Berries, Caramel and Tobacco',
        'Tuberose, Orchid and Lily',
        'Patchouli, Vanilla and Monoi Oil',
        'white floral,sweet,fruity,caramel,citrus',
        'Page 69byBibliothèque de Parfumis a Floral fragrance for women and men.Page 69was launched in 2019. Top notes are Bitter Orange, Red Berries, Caramel and Tobacco; middle notes are Tuberose, Orchid and Lily; base notes are Patchouli, Vanilla and Monoi Oil.',
        3.86,
        7,
        NULL
      ),
(
        'Play-With-Me-82051',
        'Play With Me! Bibliothèque de Parfum',
        'Play',
        'for women and men',
        NULL,
        NULL,
        'Sapodilla and Ambrette',
        'Magnolia, Violet and Sandalwood',
        'Ambergris and Amber',
        'amber,floral,powdery,woody,violet',
        'Play With Me!byBibliothèque de Parfumis a Amber Woody fragrance for women and men.Play With Me!was launched in 2019. Top notes are Sapodilla and Ambrette; middle notes are Magnolia, Violet and Sandalwood; base notes are Ambergris and Amber.',
        3,
        1,
        NULL
      ),
(
        'Polar-Lights-82059',
        'Polar Lights Bibliothèque de Parfum',
        'Polar',
        'for women and men',
        NULL,
        NULL,
        'Black Orchid, Black Elder, Champagne and Apricot',
        'Green Tea, Peach and Aldehydes',
        'Whipped Cream, Blackwood and Mahogany',
        'sweet,woody,aldehydic,floral,fruity',
        'Polar LightsbyBibliothèque de Parfumis a Citrus Aromatic fragrance for women and men.Polar Lightswas launched in 2019. Top notes are Black Orchid, Black Elder, Champagne and Apricot; middle notes are Green Tea, Peach and Aldehydes; base notes are Whipped Cream, Blackwood and Mahogany.',
        4.6,
        5,
        NULL
      ),
(
        'Rose-Suede-82039',
        'Rose Suede Bibliothèque de Parfum',
        'Rose',
        'for women',
        NULL,
        NULL,
        'Suede, Rose Water and Lime',
        'Pink Pepper, White Musk, Juniper and Sage',
        'Vetiver, Cedar and Resin',
        'aromatic,woody,musky,rose,leather',
        'Rose SuedebyBibliothèque de Parfumis a Leather fragrance for women.Rose Suedewas launched in 2019. Top notes are Suede, Rose Water and Lime; middle notes are Pink Pepper, White Musk, Juniper and Sage; base notes are Vetiver, Cedar and Resin.',
        4,
        2,
        NULL
      ),
(
        'Sensual-Rebellion-82058',
        'Sensual Rebellion Bibliothèque de Parfum',
        'Sensual',
        'for women and men',
        NULL,
        NULL,
        'Juniper Berries and Vanilla',
        'Coriander and Nutmeg',
        'Spices, Cedar, Amber, Musk and Woodsy Notes',
        'vanilla,aromatic,warm spicy,fresh spicy',
        'Sensual RebellionbyBibliothèque de Parfumis a Floral Fruity Gourmand fragrance for women and men.Sensual Rebellionwas launched in 2019. Top notes are Juniper Berries and Vanilla; middle notes are Coriander and Nutmeg; base notes are Spices, Cedar, Amber, Musk and Woodsy Notes.',
        2.2,
        5,
        NULL
      ),
(
        'Silence-82046',
        'Silence Bibliothèque de Parfum',
        'Silence',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Osmanthus and Bergamot',
        'Orange Blossom, Osmanthus and Bergamot',
        'Patchouli, Vanilla and Vetiver',
        'citrus,woody,floral,aromatic,white floral',
        'SilencebyBibliothèque de Parfumis a Floral fragrance for women and men.Silencewas launched in 2019. Top notes are Orange Blossom, Osmanthus and Bergamot; middle notes are Orange Blossom, Osmanthus and Bergamot; base notes are Patchouli, Vanilla and Vetiver.',
        3,
        5,
        NULL
      ),
(
        'Story-of-Passion-82052',
        'Story of Passion Bibliothèque de Parfum',
        'Story',
        'for women and men',
        NULL,
        NULL,
        'Peach, Pear, Sand and Black currant leaf',
        'Lily of the Valley',
        'Heliotrope, Patchouli, Vanilla, Sandal and Musk',
        'powdery,fruity,vanilla,woody,green',
        'Story of PassionbyBibliothèque de Parfumis a Chypre Floral fragrance for women and men.Story of Passionwas launched in 2019. Top notes are Peach, Pear, Sand and Black currant leaf; middle note is Lily of the Valley; base notes are Heliotrope, Patchouli, Vanilla, Sandal and Musk.',
        3,
        1,
        NULL
      ),
(
        'Taste-of-Illusions-82044',
        'Taste of Illusions Bibliothèque de Parfum',
        'Taste',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Lemon, Fern and Black Currant',
        'Lily of the Valley, Tea Rose and Cloves',
        'Sandal, Tonka and Musk',
        'aromatic,warm spicy,fruity,woody,fresh',
        'Taste of IllusionsbyBibliothèque de Parfumis a Floral fragrance for women.Taste of Illusionswas launched in 2019. Top notes are Passionfruit, Lemon, Fern and Black Currant; middle notes are Lily of the Valley, Tea Rose and Cloves; base notes are Sandal, Tonka and Musk.',
        4.25,
        4,
        NULL
      ),
(
        'Top-Secret-82041',
        'Top Secret Bibliothèque de Parfum',
        'Top',
        'for women and men',
        NULL,
        NULL,
        'Spices and Tobacco Leaf',
        'Vanilla, Tonka, Cacao and Tobacco Blossom',
        'Dried Fruits and Woody Notes',
        'vanilla,sweet,warm spicy,woody,cacao',
        'Top SecretbyBibliothèque de Parfumis a Amber Spicy fragrance for women and men.Top Secretwas launched in 2019. Top notes are Spices and Tobacco Leaf; middle notes are Vanilla, Tonka, Cacao and Tobacco Blossom; base notes are Dried Fruits and Woody Notes.',
        2.8,
        5,
        NULL
      ),
(
        'Ultimatum-82047',
        'Ultimatum Bibliothèque de Parfum',
        'Ultimatum',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Jasmine',
        'Amberwood and Ambergris',
        'Resin and White Cedar Extract',
        'amber,woody,warm spicy,balsamic,metallic',
        'UltimatumbyBibliothèque de Parfumis a Amber Spicy fragrance for women and men.Ultimatumwas launched in 2019. Top notes are Saffron and Jasmine; middle notes are Amberwood and Ambergris; base notes are Resin and White Cedar Extract.',
        3.8,
        5,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-1-Pour-Femme-56675',
        'Beverly Hills Polo Club Sport 1 Pour Femme Beverly Hills Polo Club',
        'Beverly',
        'for women',
        NULL,
        NULL,
        'Orange, Lime, Bergamot and Petitgrain',
        'Tuberose, Gardenia and Violet',
        'Patchouli, Honey and Vanilla',
        'citrus,patchouli,white floral,honey,sweet',
        'Beverly Hills Polo Club Sport 1 Pour FemmebyBeverly Hills Polo Clubis a Floral Fruity Gourmand fragrance for women.Beverly Hills Polo Club Sport 1 Pour Femmewas launched in 2018. Top notes are Orange, Lime, Bergamot and Petitgrain; middle notes are Tuberose, Gardenia and Violet; base notes are Patchouli, Honey and Vanilla.',
        4,
        15,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-2-Pour-Femme-56676',
        'Beverly Hills Polo Club Sport 2 Pour Femme Beverly Hills Polo Club',
        'Beverly',
        'for women',
        NULL,
        NULL,
        'Lavender',
        'Neroli, Watery Notes and Lily-of-the-Valley',
        'Amber, Sandalwood and Moss',
        'lavender,fresh,white floral,amber,aquatic',
        'Beverly Hills Polo Club Sport 2 Pour FemmebyBeverly Hills Polo Clubis a Aromatic Fougere fragrance for women.Beverly Hills Polo Club Sport 2 Pour Femmewas launched in 2018. Top note is Lavender; middle notes are Neroli, Watery Notes and Lily-of-the-Valley; base notes are Amber, Sandalwood and Moss.',
        3.93,
        14,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-8-Pour-Femme-56678',
        'Beverly Hills Polo Club Sport 8 Pour Femme Beverly Hills Polo Club',
        'Beverly',
        'for women',
        NULL,
        NULL,
        'Citruses and Passionfruit',
        'Water Jasmine, Water Lily and Violet Leaves',
        'Cedar, Vanilla and Musk',
        'fresh,citrus,white floral,tropical,floral',
        'Beverly Hills Polo Club Sport 8 Pour FemmebyBeverly Hills Polo Clubis a Floral Fruity fragrance for women.Beverly Hills Polo Club Sport 8 Pour Femmewas launched in 2018. Top notes are Citruses and Passionfruit; middle notes are Water Jasmine, Water Lily and Violet Leaves; base notes are Cedar, Vanilla and Musk.',
        4.19,
        16,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-9-Pour-Femme-56677',
        'Beverly Hills Polo Club Sport 9 Pour Femme Beverly Hills Polo Club',
        'Beverly',
        'for women',
        NULL,
        NULL,
        'Raspberry, Blood Orange and Sorbet',
        'Orange Blossom, Honeysuckle and Osmanthus',
        'Musk, Amber, Vanilla and Cashmere Wood',
        'white floral,fruity,musky,sweet,citrus',
        'Beverly Hills Polo Club Sport 9 Pour FemmebyBeverly Hills Polo Clubis a Floral Fruity fragrance for women.Beverly Hills Polo Club Sport 9 Pour Femmewas launched in 2018. Top notes are Raspberry, Blood Orange and Sorbet; middle notes are Orange Blossom, Honeysuckle and Osmanthus; base notes are Musk, Amber, Vanilla and Cashmere Wood.',
        3.73,
        41,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-1-56671',
        'Beverly Hills Polo Club Sport 1 Beverly Hills Polo Club',
        'Beverly',
        'for men',
        NULL,
        NULL,
        'Rose de Mai, Rosemary and Pimento',
        'Jasmine, Orris and Neroli',
        'Cedar, Sandalwood, Vetiver and Patchouli',
        'woody,rose,aromatic,warm spicy,powdery',
        'Beverly Hills Polo Club Sport 1byBeverly Hills Polo Clubis a Woody Floral Musk fragrance for men.Beverly Hills Polo Club Sport 1was launched in 2018. Top notes are Rose de Mai, Rosemary and Pimento; middle notes are Jasmine, Orris and Neroli; base notes are Cedar, Sandalwood, Vetiver and Patchouli.',
        3.78,
        41,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-2-56674',
        'Beverly Hills Polo Club Sport 2 Beverly Hills Polo Club',
        'Beverly',
        'for men',
        NULL,
        NULL,
        'Saffron, Cardamom, Nutmeg and Pink Pepper',
        'Myrhh and Geranium',
        'Incense, Agarwood (Oud), Patchouli and Leather',
        'warm spicy,amber,balsamic,aromatic,fresh spicy',
        'Beverly Hills Polo Club Sport 2byBeverly Hills Polo Clubis a Amber Spicy fragrance for men.Beverly Hills Polo Club Sport 2was launched in 2018. Top notes are Saffron, Cardamom, Nutmeg and Pink Pepper; middle notes are Myrhh and Geranium; base notes are Incense, Agarwood (Oud), Patchouli and Leather.',
        4.18,
        28,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-8-56673',
        'Beverly Hills Polo Club Sport 8 Beverly Hills Polo Club',
        'Beverly',
        'for men',
        NULL,
        NULL,
        'Precious Woods',
        'Spices',
        'Smoke',
        'smoky,woody,warm spicy',
        'Beverly Hills Polo Club Sport 8byBeverly Hills Polo Clubis a Woody Spicy fragrance for men.Beverly Hills Polo Club Sport 8was launched in 2018. Top note is Precious Woods; middle note is Spices; base note is Smoke.',
        3.55,
        22,
        NULL
      ),
(
        'Beverly-Hills-Polo-Club-Sport-9-56672',
        'Beverly Hills Polo Club Sport 9 Beverly Hills Polo Club',
        'Beverly',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon and Mandarin Orange',
        'Cedar, Vetiver and Patchouli',
        'Ambergris and Musk',
        'citrus,amber,musky,animalic,woody',
        'Beverly Hills Polo Club Sport 9byBeverly Hills Polo Clubis a Woody Aromatic fragrance for men.Beverly Hills Polo Club Sport 9was launched in 2018. Top notes are Bergamot, Lemon and Mandarin Orange; middle notes are Cedar, Vetiver and Patchouli; base notes are Ambergris and Musk.',
        3.65,
        17,
        NULL
      ),
(
        'Challenge-56612',
        'Challenge Beverly Hills Polo Club',
        'Challenge',
        'for women',
        NULL,
        NULL,
        'Chocolate, Pink Pepper and Mint',
        'Tuberose, Orange Blossom and Violet',
        'Patchouli, Vanilla, Musk and Tonka Bean',
        'warm spicy,vanilla,sweet,patchouli,white floral',
        'ChallengebyBeverly Hills Polo Clubis a Amber Floral fragrance for women.Challengewas launched in 2018. Top notes are Chocolate, Pink Pepper and Mint; middle notes are Tuberose, Orange Blossom and Violet; base notes are Patchouli, Vanilla, Musk and Tonka Bean.',
        3.25,
        4,
        NULL
      ),
(
        'Elegance-56611',
        'Elegance Beverly Hills Polo Club',
        'Elegance',
        'for women',
        NULL,
        NULL,
        'Black Currant, Orange and Bulgarian Rose',
        'Jasmine and Parma Violet',
        'Musk, Vanilla and Incense',
        'powdery,white floral,musky,violet,vanilla',
        'ElegancebyBeverly Hills Polo Clubis a Amber Floral fragrance for women.Elegancewas launched in 2018. Top notes are Black Currant, Orange and Bulgarian Rose; middle notes are Jasmine and Parma Violet; base notes are Musk, Vanilla and Incense.',
        3.33,
        9,
        NULL
      ),
(
        'Heritage-Oud-56614',
        'Heritage Oud Beverly Hills Polo Club',
        'Heritage',
        'for men',
        NULL,
        NULL,
        'Cardamom, Pink Pepper and Bergamot',
        'Cypress and Thyme',
        'Cade oil, Sandalwood, Amber and Vetiver',
        'aromatic,woody,fresh spicy,warm spicy',
        'Heritage OudbyBeverly Hills Polo Clubis a Amber Spicy fragrance for men.Heritage Oudwas launched in 2018. Top notes are Cardamom, Pink Pepper and Bergamot; middle notes are Cypress and Thyme; base notes are Cade oil, Sandalwood, Amber and Vetiver.',
        4,
        38,
        NULL
      ),
(
        'Mystique-56610',
        'Mystique Beverly Hills Polo Club',
        'Mystique',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Lemon Zest and Orange',
        'White Flowers, Tiare Flower and Neroli',
        'Patchouli and Oakmoss',
        'white floral,citrus',
        'MystiquebyBeverly Hills Polo Clubis a Floral fragrance for women.Mystiquewas launched in 2018. Top notes are Orange Blossom, Lemon Zest and Orange; middle notes are White Flowers, Tiare Flower and Neroli; base notes are Patchouli and Oakmoss.',
        3.59,
        34,
        NULL
      ),
(
        'Passion-56609',
        'Passion Beverly Hills Polo Club',
        'Passion',
        'for women',
        NULL,
        NULL,
        'Black Currant, Red Fruits and Litchi',
        'Peony, Rose and Sea Notes',
        'Musk, Patchouli and Sandalwood',
        'fruity,floral,rose,fresh,woody',
        'PassionbyBeverly Hills Polo Clubis a Chypre Floral fragrance for women.Passionwas launched in 2018. Top notes are Black Currant, Red Fruits and Litchi; middle notes are Peony, Rose and Sea Notes; base notes are Musk, Patchouli and Sandalwood.',
        2.95,
        20,
        NULL
      ),
(
        'Titan-56615',
        'Titan Beverly Hills Polo Club',
        'Titan',
        'for men',
        NULL,
        NULL,
        'Ginger, Nutmeg, Lemon and Grapefruit',
        'Pink Pepper, Mint and Jasmine',
        'Incense, Vetiver, Sandalwood and Patchouli',
        'warm spicy,woody,fresh spicy,aromatic,soft spicy',
        'TitanbyBeverly Hills Polo Clubis a Citrus Aromatic fragrance for men.Titanwas launched in 2018. Top notes are Ginger, Nutmeg, Lemon and Grapefruit; middle notes are Pink Pepper, Mint and Jasmine; base notes are Incense, Vetiver, Sandalwood and Patchouli.',
        3.9,
        49,
        NULL
      ),
(
        'Tour-56616',
        'Tour Beverly Hills Polo Club',
        'Tour',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot, Orange and Cardamom',
        'Fern, Floral Notes and Labdanum',
        'Oakmoss, Vetiver, Leather, Styrax, Amber and Vanilla',
        'citrus,aromatic,earthy,mossy,amber',
        'TourbyBeverly Hills Polo Clubis a Leather fragrance for men.Tourwas launched in 2018. Top notes are Lemon, Bergamot, Orange and Cardamom; middle notes are Fern, Floral Notes and Labdanum; base notes are Oakmoss, Vetiver, Leather, Styrax, Amber and Vanilla.',
        3.68,
        28,
        NULL
      ),
(
        'Trophy-56613',
        'Trophy Beverly Hills Polo Club',
        'Trophy',
        'for men',
        NULL,
        NULL,
        'Pineapple, Bergamot, Lavender and Lemon',
        'Apple, Rose and Geranium',
        'Oakmoss, Sandalwood and Tonka Bean',
        'fruity,mossy,fresh spicy,citrus,sweet',
        'TrophybyBeverly Hills Polo Clubis a Amber Fougere fragrance for men.Trophywas launched in 2018. Top notes are Pineapple, Bergamot, Lavender and Lemon; middle notes are Apple, Rose and Geranium; base notes are Oakmoss, Sandalwood and Tonka Bean.',
        3.4,
        42,
        NULL
      ),
(
        'Amazing-Love-6543',
        'Amazing Love Betty Barclay',
        'Amazing',
        'for women',
        NULL,
        NULL,
        'Lemon Verbena, Orange and Granny Smith apple',
        'Rose, Violet and African Orange Flower',
        'Patchouli, Vanilla and Woodsy Notes',
        'citrus,rose,woody,patchouli,white floral',
        'Amazing LovebyBetty Barclayis a Chypre Floral fragrance for women.Amazing Lovewas launched in 2009. Top notes are Lemon Verbena, Orange and Granny Smith apple; middle notes are Rose, Violet and African Orange Flower; base notes are Patchouli, Vanilla and Woodsy Notes.',
        3.93,
        14,
        NULL
      ),
(
        'Beautiful-5952',
        'Beautiful Betty Barclay',
        'Beautiful',
        'for women',
        NULL,
        NULL,
        'Pear, Mandarin Orange and Bergamot',
        'Jasmine, Gardenia and Freesia',
        'Amber and Sandalwood',
        'white floral,citrus,amber,woody,fruity',
        'BeautifulbyBetty Barclayis a Floral fragrance for women.Beautifulwas launched in 2009. Top notes are Pear, Mandarin Orange and Bergamot; middle notes are Jasmine, Gardenia and Freesia; base notes are Amber and Sandalwood.',
        3.89,
        46,
        NULL
      ),
(
        'Beautiful-Grace-11158',
        'Beautiful Grace Betty Barclay',
        'Beautiful',
        'for women',
        NULL,
        NULL,
        'Peach, Black Currant and Plum',
        'Praline, Freesia and Tiare Flower',
        'Vanille, Patchouli and Sandalwood',
        'fruity,sweet,woody,floral,vanilla',
        'Beautiful GracebyBetty Barclayis a Floral Fruity Gourmand fragrance for women.Beautiful Gracewas launched in 2011. Top notes are Peach, Black Currant and Plum; middle notes are Praline, Freesia and Tiare Flower; base notes are Vanille, Patchouli and Sandalwood.',
        4.06,
        18,
        NULL
      ),
(
        'Betty-Barclay-14474',
        'Betty Barclay Betty Barclay',
        'Betty',
        'for women',
        NULL,
        NULL,
        'Peach, Coriander, Bergamot, Mandarin Orange and Amalfi Lemon',
        'Tuberose, Ylang-Ylang, Carnation, Jasmine, Rose and Lily-of-the-Valley',
        'Patchouli, Sandalwood, Musk, Incense, Civetta, Amber, Benzoin, Tonka Bean and Vanille',
        'woody,white floral,warm spicy,amber,powdery',
        'Betty BarclaybyBetty Barclayis a Amber Floral fragrance for women.Betty Barclaywas launched in 1994. Top notes are Peach, Coriander, Bergamot, Mandarin Orange and Amalfi Lemon; middle notes are Tuberose, Ylang-Ylang, Carnation, Jasmine, Rose and Lily-of-the-Valley; base notes are Patchouli, Sandalwood, Musk, Incense, Civetta, Amber, Benzoin, Tonka Bean and Vanille.',
        3.79,
        38,
        NULL
      ),
(
        'Betty-Barclay-in-LOVE-1751',
        'Betty Barclay in LOVE Betty Barclay',
        'Betty',
        'for women',
        NULL,
        NULL,
        'Black Currant, White Peach and Pink Grapefruit',
        'Heliotrope, Honeysuckle and Freesia',
        'Sandalwood, Amber and Musk',
        'fruity,powdery,woody,floral,citrus',
        'Betty Barclay in LOVEbyBetty Barclayis a Floral Fruity fragrance for women.Betty Barclay in LOVEwas launched in 2007. Top notes are Black Currant, White Peach and Pink Grapefruit; middle notes are Heliotrope, Honeysuckle and Freesia; base notes are Sandalwood, Amber and Musk.',
        3.79,
        56,
        NULL
      ),
(
        'Chic-11764',
        'Chic Betty Barclay',
        'Chic',
        'for women',
        NULL,
        NULL,
        'Black Currant, Bergamot and Mandarin Orange',
        'Ylang-Ylang, Magnolia and Rose',
        'Vanille, Heliotrope and Sandalwood',
        'floral,citrus,woody,vanilla,powdery',
        'ChicbyBetty Barclayis a Floral fragrance for women.Chicwas launched in 2011. Top notes are Black Currant, Bergamot and Mandarin Orange; middle notes are Ylang-Ylang, Magnolia and Rose; base notes are Vanille, Heliotrope and Sandalwood.',
        3.61,
        69,
        NULL
      ),
(
        'Even-You-89515',
        'Even You Betty Barclay',
        'Even',
        'for women',
        NULL,
        NULL,
        'Bergamot, Neroli and Plum',
        'Freesia and Iris',
        'Vanilla, Vetiver and Tonka',
        'citrus,vanilla,floral,powdery,aromatic',
        'Even YoubyBetty Barclayis a Amber Floral fragrance for women. This is a new fragrance.Even Youwas launched in 2024. Top notes are Bergamot, Neroli and Plum; middle notes are Freesia and Iris; base notes are Vanilla, Vetiver and Tonka.',
        3.83,
        6,
        NULL
      ),
(
        'Precious-Moments-23675',
        'Precious Moments Betty Barclay',
        'Precious',
        'for women',
        NULL,
        NULL,
        'Black Currant, Raspberry and Green Leaves',
        'Peony and Freesia',
        'Caramel, Vanilla, Woody Notes and Musk',
        'fruity,floral,sweet,caramel,vanilla',
        'Precious MomentsbyBetty Barclayis a Floral fragrance for women.Precious Momentswas launched in 2014. Top notes are Black Currant, Raspberry and Green Leaves; middle notes are Peony and Freesia; base notes are Caramel, Vanilla, Woody Notes and Musk.',
        3.66,
        181,
        NULL
      ),
(
        'Pretty-Butterfly-36603',
        'Pretty Butterfly Betty Barclay',
        'Pretty',
        'for women',
        NULL,
        NULL,
        'Lemon, Passionfruit and Blackberry',
        'Lily-of-the-Valley, Taif Rose and Parma Violet',
        'Palisander Rosewood, Musk and Patchouli',
        'fresh,white floral,rose,citrus,fruity',
        'Pretty ButterflybyBetty Barclayis a Floral Woody Musk fragrance for women.Pretty Butterflywas launched in 2016. Top notes are Lemon, Passionfruit and Blackberry; middle notes are Lily-of-the-Valley, Taif Rose and Parma Violet; base notes are Palisander Rosewood, Musk and Patchouli.',
        3.91,
        67,
        NULL
      ),
(
        'Sheer-Delight-29729',
        'Sheer Delight Betty Barclay',
        'Sheer',
        'for women',
        NULL,
        NULL,
        'Italian Lemon, Mandarin Orange and Pear',
        'Peony, Orange Blossom and Lily-of-the-Valley',
        'Musk, Resins and Amber',
        'citrus,fresh,white floral,floral,amber',
        'Sheer DelightbyBetty Barclayis a Floral Fruity fragrance for women.Sheer Delightwas launched in 2015. Top notes are Italian Lemon, Mandarin Orange and Pear; middle notes are Peony, Orange Blossom and Lily-of-the-Valley; base notes are Musk, Resins and Amber.',
        3.26,
        39,
        NULL
      ),
(
        'Style-14271',
        'Style Betty Barclay',
        'Style',
        'for women',
        NULL,
        NULL,
        'Ylang-Ylang, Nutmeg, Magnolia and Red Berries',
        'Iris, Jasmine, Patchouli, Rose and Apricot',
        'Musk, Sandalwood, Virginia Cedar, Amber and Vanille',
        'woody,powdery,floral,patchouli,yellow floral',
        'StylebyBetty Barclayis a Floral Woody Musk fragrance for women.Stylewas launched in 2004. Top notes are Ylang-Ylang, Nutmeg, Magnolia and Red Berries; middle notes are Iris, Jasmine, Patchouli, Rose and Apricot; base notes are Musk, Sandalwood, Virginia Cedar, Amber and Vanille.',
        3,
        4,
        NULL
      ),
(
        'Style-by-Night-14272',
        'Style by Night Betty Barclay',
        'Style',
        'for women',
        NULL,
        NULL,
        'plum and Peach',
        'Jasmine and Violet Leaf',
        'Cashmere Wood and Musk',
        'musky,white floral,fruity,woody,ozonic',
        'Style by NightbyBetty Barclayis a Floral Woody Musk fragrance for women.Style by Nightwas launched in 2012. Top notes are plum and Peach; middle notes are Jasmine and Violet Leaf; base notes are Cashmere Wood and Musk.',
        3.78,
        83,
        NULL
      ),
(
        'Voice-14473',
        'Voice Betty Barclay',
        'Voice',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,woody,amber,rose,vanilla',
        'VoicebyBetty Barclayis a Amber Floral fragrance for women.Voicewas launched in 1995.',
        4.47,
        17,
        NULL
      ),
(
        'Beautiful-Eden-Eau-de-Parfum-48734',
        'Beautiful Eden Eau de Parfum Betty Barclay',
        'Beautiful',
        'for women',
        NULL,
        NULL,
        'Pear, Black Currant and Mandarin Orange',
        'Peony, Lily-of-the-Valley and Egyptian Jasmine',
        'Sandalwood, Cedar and Vanilla',
        'fresh,floral,fruity,white floral,rose',
        'Beautiful Eden Eau de ParfumbyBetty Barclayis a Floral Fruity fragrance for women.Beautiful Eden Eau de Parfumwas launched in 2018. Top notes are Pear, Black Currant and Mandarin Orange; middle notes are Peony, Lily-of-the-Valley and Egyptian Jasmine; base notes are Sandalwood, Cedar and Vanilla.',
        3.72,
        18,
        NULL
      ),
(
        'Beautiful-Eden-Eau-de-Toilette-48735',
        'Beautiful Eden Eau de Toilette Betty Barclay',
        'Beautiful',
        'for women',
        NULL,
        NULL,
        'Pear, Mandarin Orange and Black Currant',
        'Peony, Lily-of-the-Valley and Egyptian Jasmine',
        'Cedar, Vanilla and Sandalwood',
        'fresh,fruity,floral,woody,white floral',
        'Beautiful Eden Eau de ToilettebyBetty Barclayis a Floral Fruity fragrance for women.Beautiful Eden Eau de Toilettewas launched in 2018. Top notes are Pear, Mandarin Orange and Black Currant; middle notes are Peony, Lily-of-the-Valley and Egyptian Jasmine; base notes are Cedar, Vanilla and Sandalwood.',
        3.62,
        37,
        NULL
      ),
(
        'Brilliant-Woman-No-1-55993',
        'Brilliant Woman No 1 Betty Barclay',
        'Brilliant',
        'for women',
        NULL,
        NULL,
        'Red Apple and Mandarin Orange',
        'Jasmine, Gardenia and Musk',
        'Vanilla, Sandalwood and Cedar',
        'woody,white floral,vanilla,powdery,citrus',
        'Brilliant Woman No 1byBetty Barclayis a Floral Woody Musk fragrance for women.Brilliant Woman No 1was launched in 2019. Top notes are Red Apple and Mandarin Orange; middle notes are Jasmine, Gardenia and Musk; base notes are Vanilla, Sandalwood and Cedar.',
        4.25,
        4,
        NULL
      ),
(
        'Brilliant-Woman-No-2-55994',
        'Brilliant Woman No 2 Betty Barclay',
        'Brilliant',
        'for women',
        NULL,
        NULL,
        'Blackberry, Bergamot and Pear',
        'Dark Chocolate, Heliotrope and Sesame',
        'Benzoin, Sandalwood and Musk',
        'warm spicy,fruity,sweet,chocolate,powdery',
        'Brilliant Woman No 2byBetty Barclayis a Amber Vanilla fragrance for women.Brilliant Woman No 2was launched in 2019. Top notes are Blackberry, Bergamot and Pear; middle notes are Dark Chocolate, Heliotrope and Sesame; base notes are Benzoin, Sandalwood and Musk.',
        3.67,
        3,
        NULL
      ),
(
        'Brilliant-Woman-No-3-55995',
        'Brilliant Woman No 3 Betty Barclay',
        'Brilliant',
        'for women',
        NULL,
        NULL,
        'Bergamot, Pink Pepper, Apple and Raspberry',
        'Rose, Lily-of-the-Valley, Violet and Peach',
        'Amber and Musk',
        'fruity,powdery,rose,sweet,fresh',
        'Brilliant Woman No 3byBetty Barclayis a Floral Fruity fragrance for women.Brilliant Woman No 3was launched in 2019. Top notes are Bergamot, Pink Pepper, Apple and Raspberry; middle notes are Rose, Lily-of-the-Valley, Violet and Peach; base notes are Amber and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Betty-Barclay-Woman-2470',
        'Betty Barclay Woman Betty Barclay',
        'Betty',
        'for women',
        NULL,
        'Ursula Wandel',
        'Hiacynth, Peach, Bergamot and Cassia',
        'Lily, Jasmine and Iris',
        'Amber, Cedar, Tonka Bean and Sandalwood',
        'white floral,floral,green,fresh spicy,fruity',
        'Betty Barclay WomanbyBetty Barclayis a Floral Green fragrance for women.Betty Barclay Womanwas launched in 1999. The nose behind this fragrance is Ursula Wandel. Top notes are Hiacynth, Peach, Bergamot and Cassia; middle notes are Lily, Jasmine and Iris; base notes are Amber, Cedar, Tonka Bean and Sandalwood.',
        3.86,
        69,
        NULL
      ),
(
        'Betty-Barclay-Woman-No-1-3595',
        'Betty Barclay Woman No 1 Betty Barclay',
        'Betty',
        'for women',
        NULL,
        NULL,
        'Orange, Tangerine, Neroli and Red Berries',
        'Apricot, Peony and Jasmine',
        'Vanilla, Amber and Musk',
        'citrus,fruity,sweet,fresh,white floral',
        'Betty Barclay Woman No 1byBetty Barclayis a Floral Fruity fragrance for women.Betty Barclay Woman No 1was launched in 2008. Top notes are Orange, Tangerine, Neroli and Red Berries; middle notes are Apricot, Peony and Jasmine; base notes are Vanilla, Amber and Musk.',
        3.81,
        102,
        NULL
      ),
(
        'Betty-Barclay-Woman-No-2-2471',
        'Betty Barclay Woman No 2 Betty Barclay',
        'Betty',
        'for women',
        NULL,
        NULL,
        'Rose and Bergamot',
        'Violet, White Musk and Sandalwood',
        'Bourbon Vanilla, Amber and Cedar',
        'powdery,woody,violet,vanilla,musky',
        'Betty Barclay Woman No 2byBetty Barclayis a Amber fragrance for women.Betty Barclay Woman No 2was launched in 2000. Top notes are Rose and Bergamot; middle notes are Violet, White Musk and Sandalwood; base notes are Bourbon Vanilla, Amber and Cedar.',
        4.03,
        202,
        NULL
      ),
(
        'Betty-Barclay-Woman-No-3-2472',
        'Betty Barclay Woman No 3 Betty Barclay',
        'Betty',
        'for women',
        NULL,
        'Anne Flipo',
        'Cassia, Bergamot and Green Notes',
        'Rose and Jasmine',
        'Sandalwood and Vanilla',
        'rose,green,aromatic,woody,citrus',
        'Betty Barclay Woman No 3byBetty Barclayis a Floral Fruity fragrance for women.Betty Barclay Woman No 3was launched in 2000. The nose behind this fragrance is Anne Flipo. Top notes are Cassia, Bergamot and Green Notes; middle notes are Rose and Jasmine; base notes are Sandalwood and Vanilla.',
        3.76,
        102,
        NULL
      ),
(
        'Bohemian-Romance-Eau-de-Parfum-53226',
        'Bohemian Romance Eau de Parfum Betty Barclay',
        'Bohemian',
        'for women',
        NULL,
        'Fanny Bal',
        'Pear, Pink Pepper and Mandarin Orange',
        'Rose, Lily-of-the-Valley and Jasmine',
        'Cashmere Wood, Cedar and Musk',
        'rose,white floral,musky,woody,fruity',
        'Bohemian Romance Eau de ParfumbyBetty Barclayis a Floral Woody Musk fragrance for women.Bohemian Romance Eau de Parfumwas launched in 2019. The nose behind this fragrance is Fanny Bal. Top notes are Pear, Pink Pepper and Mandarin Orange; middle notes are Rose, Lily-of-the-Valley and Jasmine; base notes are Cashmere Wood, Cedar and Musk.',
        4,
        15,
        NULL
      ),
(
        'Bohemian-Romance-Eau-de-Toilette-53227',
        'Bohemian Romance Eau de Toilette Betty Barclay',
        'Bohemian',
        'for women',
        NULL,
        'Fanny Bal',
        'Pink Pepper, Mandarin Orange and Pear',
        'Rose, Lily-of-the-Valley and Jasmine',
        'Musk, Cashmere Wood and Cedar',
        'musky,white floral,woody,rose,citrus',
        'Bohemian Romance Eau de ToilettebyBetty Barclayis a Floral Woody Musk fragrance for women.Bohemian Romance Eau de Toilettewas launched in 2019. The nose behind this fragrance is Fanny Bal. Top notes are Pink Pepper, Mandarin Orange and Pear; middle notes are Rose, Lily-of-the-Valley and Jasmine; base notes are Musk, Cashmere Wood and Cedar.',
        3.9,
        41,
        NULL
      ),
(
        'Dream-Away-Eau-de-Parfum-67727',
        'Dream Away Eau de Parfum Betty Barclay',
        'Dream',
        'for women',
        NULL,
        NULL,
        'Artemisia, Mandarin Orange and Apple',
        'Violet, Jasmine and Peach',
        'White Musk, Vanilla and Patchouli',
        'powdery,violet,vanilla,musky,herbal',
        'Dream Away Eau de ParfumbyBetty Barclayis a Floral Fruity fragrance for women.Dream Away Eau de Parfumwas launched in 2021. Top notes are Artemisia, Mandarin Orange and Apple; middle notes are Violet, Jasmine and Peach; base notes are White Musk, Vanilla and Patchouli.',
        3.82,
        11,
        NULL
      ),
(
        'Dream-Away-Eau-de-Toilette-67726',
        'Dream Away Eau de Toilette Betty Barclay',
        'Dream',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Artemisia and Apple',
        'Jasmine, Peach and Violet',
        'White Musk, Vanilla and Patchouli',
        'citrus,fruity,herbal,powdery,aromatic',
        'Dream Away Eau de ToilettebyBetty Barclayis a Floral Fruity fragrance for women.Dream Away Eau de Toilettewas launched in 2021. Top notes are Mandarin Orange, Artemisia and Apple; middle notes are Jasmine, Peach and Violet; base notes are White Musk, Vanilla and Patchouli.',
        3.58,
        24,
        NULL
      ),
(
        'Rubin-2473',
        'Rubin Betty Barclay',
        'Rubin',
        'for women',
        NULL,
        NULL,
        'Neroli, Mandarin Orange, Bergamot and Bitter Orange',
        NULL,
        'Musk and Sandalwood',
        'citrus,musky,powdery,woody,white floral',
        'RubinbyBetty Barclayis a Citrus fragrance for women.Rubinwas launched in 2006. Top notes are Neroli, Mandarin Orange, Bergamot and Bitter Orange; base notes are Musk and Sandalwood.',
        3,
        6,
        NULL
      ),
(
        'Saphir-2474',
        'Saphir Betty Barclay',
        'Saphir',
        'for women',
        NULL,
        NULL,
        'Lime and Bergamot',
        'Orchid, Jasmine and Water Lily',
        'Amber, Musk and Vanilla',
        'citrus,floral,powdery,white floral,vanilla',
        'SaphirbyBetty Barclayis a Floral fragrance for women.Saphirwas launched in 2006. Top notes are Lime and Bergamot; middle notes are Orchid, Jasmine and Water Lily; base notes are Amber, Musk and Vanilla.',
        4,
        1,
        NULL
      ),
(
        'Smaragd-2475',
        'Smaragd Betty Barclay',
        'Smaragd',
        'for women',
        NULL,
        NULL,
        'Peach and Grapefruit',
        'Gardenia, Jasmine and Tuberose',
        'Musk, Sandalwood and Heliotrope',
        'white floral,powdery,tuberose,musky,animalic',
        'SmaragdbyBetty Barclayis a Floral Fruity fragrance for women.Smaragdwas launched in 2006. Top notes are Peach and Grapefruit; middle notes are Gardenia, Jasmine and Tuberose; base notes are Musk, Sandalwood and Heliotrope.',
        4,
        1,
        NULL
      ),
(
        'Happiness-82335',
        'Happiness Betty Barclay',
        'Happiness',
        'for women',
        NULL,
        NULL,
        'Pear, Apple and Black Currant',
        'Jasmine, Vanilla and Rose',
        'Musk and Amber',
        'fruity,fresh,white floral,sweet,green',
        'HappinessbyBetty Barclayis a Floral Fruity fragrance for women. This is a new fragrance.Happinesswas launched in 2023. Top notes are Pear, Apple and Black Currant; middle notes are Jasmine, Vanilla and Rose; base notes are Musk and Amber.',
        4.1,
        10,
        NULL
      ),
(
        'Oriental-Bloom-Eau-de-Parfum-62121',
        'Oriental Bloom Eau de Parfum Betty Barclay',
        'Oriental',
        'for women',
        NULL,
        'Nathalie Lorson',
        'Freesia, Pear and Jasmine',
        'Vanilla, Tonka Bean and Magnolia',
        'White Wood and Musk',
        'vanilla,floral,woody,sweet,powdery',
        'Oriental Bloom Eau de ParfumbyBetty Barclayis a Amber Floral fragrance for women.Oriental Bloom Eau de Parfumwas launched in 2020. The nose behind this fragrance is Nathalie Lorson. Top notes are Freesia, Pear and Jasmine; middle notes are Vanilla, Tonka Bean and Magnolia; base notes are White Wood and Musk.',
        3.83,
        23,
        NULL
      ),
(
        'Oriental-Bloom-Eau-de-Toilette-62120',
        'Oriental Bloom Eau de Toilette Betty Barclay',
        'Oriental',
        'for women',
        NULL,
        'Nathalie Lorson',
        'Pear, Freesia and Jasmine',
        'Tonka Bean, Vanilla and Magnolia',
        'Musk and White Wood',
        'vanilla,sweet,floral,fruity,musky',
        'Oriental Bloom Eau de ToilettebyBetty Barclayis a Amber Floral fragrance for women.Oriental Bloom Eau de Toilettewas launched in 2020. The nose behind this fragrance is Nathalie Lorson. Top notes are Pear, Freesia and Jasmine; middle notes are Tonka Bean, Vanilla and Magnolia; base notes are Musk and White Wood.',
        3.87,
        38,
        NULL
      ),
(
        'Pure-Pastel-Lemon-43471',
        'Pure Pastel Lemon Betty Barclay',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Lemon, Mandarin Orange and Green Apple',
        'Lily-of-the-Valley, Freesia and Violet Leaf',
        'Musk, Sandalwood and Amber',
        'citrus,musky,fresh,powdery,green',
        'Pure Pastel LemonbyBetty Barclayis a Floral Fruity fragrance for women.Pure Pastel Lemonwas launched in 2017. Top notes are Lemon, Mandarin Orange and Green Apple; middle notes are Lily-of-the-Valley, Freesia and Violet Leaf; base notes are Musk, Sandalwood and Amber.',
        3.4,
        82,
        NULL
      ),
(
        'Pure-Pastel-Mint-43472',
        'Pure Pastel Mint Betty Barclay',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Black Currant, Yuzu and Pink Pepper',
        'Tea Rose, Cyclamen and Ylang-Ylang',
        'Musk and Sandalwood',
        'floral,fruity,rose,musky,citrus',
        'Pure Pastel MintbyBetty Barclayis a Floral Woody Musk fragrance for women.Pure Pastel Mintwas launched in 2017. Top notes are Black Currant, Yuzu and Pink Pepper; middle notes are Tea Rose, Cyclamen and Ylang-Ylang; base notes are Musk and Sandalwood.',
        3.59,
        115,
        NULL
      ),
(
        'Pure-Pastel-Peach-50116',
        'Pure Pastel Peach Betty Barclay',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Peach, Passionfruit and Grapefruit',
        'Frangipani, Jasmine and Violet Leaf',
        'Vanilla, Cashmeran and Tonka Bean',
        'fruity,vanilla,sweet,tropical,powdery',
        'Pure Pastel PeachbyBetty Barclayis a Amber Floral fragrance for women.Pure Pastel Peachwas launched in 2018. Top notes are Peach, Passionfruit and Grapefruit; middle notes are Frangipani, Jasmine and Violet Leaf; base notes are Vanilla, Cashmeran and Tonka Bean.',
        3.59,
        29,
        NULL
      ),
(
        'Pure-Pastel-Rose-50117',
        'Pure Pastel Rose Betty Barclay',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Lilac, Violet Leaf and Ginger',
        'Rose, Peony and Flowers',
        'Cedar, Patchouli and Sandalwood',
        'floral,rose,fresh,woody',
        'Pure Pastel RosebyBetty Barclayis a Floral fragrance for women.Pure Pastel Rosewas launched in 2018. Top notes are Lilac, Violet Leaf and Ginger; middle notes are Rose, Peony and Flowers; base notes are Cedar, Patchouli and Sandalwood.',
        3.57,
        23,
        NULL
      ),
(
        'Pure-Style-8239',
        'Pure Style Betty Barclay',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Freesia, Bergamot and Peach',
        'Lily-of-the-Valley, Jasmine and Magnolia',
        'Musk, Virginia Cedar and Amber',
        'floral,white floral,citrus,musky,powdery',
        'Pure StylebyBetty Barclayis a Floral fragrance for women.Pure Stylewas launched in 2010. Top notes are Freesia, Bergamot and Peach; middle notes are Lily-of-the-Valley, Jasmine and Magnolia; base notes are Musk, Virginia Cedar and Amber.',
        3.73,
        164,
        NULL
      ),
(
        'Pure-Sun-65390',
        'Pure Sun Betty Barclay',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Diamond Orchid and Magnolia',
        'Neroli, Lotus and Apple Blossom',
        'Benzoin, Hinoki Wood and Sandalwood',
        'floral,woody,amber,aromatic,citrus',
        'Pure SunbyBetty Barclayis a Amber Floral fragrance for women.Pure Sunwas launched in 2021. Top notes are Diamond Orchid and Magnolia; middle notes are Neroli, Lotus and Apple Blossom; base notes are Benzoin, Hinoki Wood and Sandalwood.',
        3.75,
        32,
        NULL
      ),
(
        'Pure-Flower-Eau-de-Parfum-94969',
        'Pure Flower Eau de Parfum Betty Barclay',
        'Pure',
        'for women',
        NULL,
        'Mirella Pomina',
        'Aldehydes, Lavender and Reseda',
        'Peony, Vetiver and Rose',
        'Amber, Musk and Vanilla',
        'fresh,aldehydic,floral,lavender,amber',
        'Pure Flower Eau de ParfumbyBetty Barclayis a Floral Aldehyde fragrance for women. This is a new fragrance.Pure Flower Eau de Parfumwas launched in 2024. The nose behind this fragrance is Mirella Pomina. Top notes are Aldehydes, Lavender and Reseda; middle notes are Peony, Vetiver and Rose; base notes are Amber, Musk and Vanilla.',
        5,
        1,
        NULL
      ),
(
        'Pure-Flower-Eau-de-Toilette-94968',
        'Pure Flower Eau de Toilette Betty Barclay',
        'Pure',
        'for women',
        NULL,
        'Mirella Pomina',
        'Lavender, Aldehydes and Reseda',
        'Rose, Peony and Vetiver',
        'Musk, Amber and Vanilla',
        'lavender,aldehydic,musky,fresh spicy',
        'Pure Flower Eau de ToilettebyBetty Barclayis a Floral Aldehyde fragrance for women. This is a new fragrance.Pure Flower Eau de Toilettewas launched in 2024. The nose behind this fragrance is Mirella Pomina. Top notes are Lavender, Aldehydes and Reseda; middle notes are Rose, Peony and Vetiver; base notes are Musk, Amber and Vanilla.',
        2,
        1,
        NULL
      ),
(
        'Tender-Blossom-17670',
        'Tender Blossom Betty Barclay',
        'Tender',
        'for women',
        NULL,
        NULL,
        'Melon and Litchi',
        'Peony, Magnolia, Cyclamen and Freesia',
        'Musk, Sandalwood and Cedar',
        'floral,fresh,fruity,aquatic,ozonic',
        'Tender BlossombyBetty Barclayis a Floral fragrance for women.Tender Blossomwas launched in 2013. Top notes are Melon and Litchi; middle notes are Peony, Magnolia, Cyclamen and Freesia; base notes are Musk, Sandalwood and Cedar.',
        3.91,
        311,
        NULL
      ),
(
        'Tender-Love-Eau-de-Parfum-58978',
        'Tender Love Eau de Parfum Betty Barclay',
        'Tender',
        'for women',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Freesia and Jasmine',
        'Musk and Amber',
        'citrus,floral,musky,powdery,amber',
        'Tender Love Eau de ParfumbyBetty Barclayis a Floral Fruity fragrance for women.Tender Love Eau de Parfumwas launched in 2020. Top notes are Bergamot and Mandarin Orange; middle notes are Freesia and Jasmine; base notes are Musk and Amber.',
        4.17,
        6,
        NULL
      ),
(
        'Tender-Love-Eau-de-Toilette-58977',
        'Tender Love Eau de Toilette Betty Barclay',
        'Tender',
        'for women',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Freesia and Jasmine',
        'Musk and Amber',
        'citrus,floral,musky,white floral,powdery',
        'Tender Love Eau de ToilettebyBetty Barclayis a Floral Fruity fragrance for women.Tender Love Eau de Toilettewas launched in 2020. Top notes are Bergamot and Mandarin Orange; middle notes are Freesia and Jasmine; base notes are Musk and Amber.',
        3.86,
        21,
        NULL
      ),
(
        'Wild-Flower-Eau-de-Parfum-74572',
        'Wild Flower Eau de Parfum Betty Barclay',
        'Wild',
        'for women',
        NULL,
        NULL,
        'Lemon, Pink Pepper and Raspberry',
        'Jasmine, Rose and Peony',
        'Cedar, Tonka Bean and Vanilla',
        'rose,vanilla,sweet,floral,fresh',
        'Wild Flower Eau de ParfumbyBetty Barclayis a fragrance for women. This is a new fragrance.Wild Flower Eau de Parfumwas launched in 2022. Top notes are Lemon, Pink Pepper and Raspberry; middle notes are Jasmine, Rose and Peony; base notes are Cedar, Tonka Bean and Vanilla.',
        3.87,
        15,
        NULL
      ),
(
        'Wild-Flower-Eau-de-Toilette-74573',
        'Wild Flower Eau de Toilette Betty Barclay',
        'Wild',
        'for women',
        NULL,
        NULL,
        'Lemon, Raspberry and Pink Pepper',
        'Jasmine, Peony and Rose',
        'Cedar, Tonka Bean and Vanilla',
        'white floral,floral,fresh,rose,citrus',
        'Wild Flower Eau de ToilettebyBetty Barclayis a fragrance for women. This is a new fragrance.Wild Flower Eau de Toilettewas launched in 2022. Top notes are Lemon, Raspberry and Pink Pepper; middle notes are Jasmine, Peony and Rose; base notes are Cedar, Tonka Bean and Vanilla.',
        4,
        7,
        NULL
      ),
(
        '24-7-For-Her-28005',
        '24/7 For Her Bench.',
        '24/7',
        'for women',
        NULL,
        NULL,
        'Pear, Kumquat and Grapefruit',
        'Mimosa and Rose',
        'Sandalwood and Amber',
        'citrus,fruity,sweet,fresh,aromatic',
        '24/7 For HerbyBench.is a Floral fragrance for women.24/7 For Herwas launched in 2014. Top notes are Pear, Kumquat and Grapefruit; middle notes are Mimosa and Rose; base notes are Sandalwood and Amber.',
        3.16,
        19,
        NULL
      ),
(
        '24-7-For-Him-28006',
        '24/7 For Him Bench.',
        '24/7',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Bergamot and Pink Pepper',
        'Lavender, Patchouli and Jasmine',
        'Vanilla, Musk and Amber',
        'citrus,lavender,musky,vanilla,fresh spicy',
        '24/7 For HimbyBench.is a Woody Aromatic fragrance for men.24/7 For Himwas launched in 2014. Top notes are Grapefruit, Bergamot and Pink Pepper; middle notes are Lavender, Patchouli and Jasmine; base notes are Vanilla, Musk and Amber.',
        3.7,
        10,
        NULL
      ),
(
        'An-Urban-Original-2-for-Him-20190',
        'An Urban Original 2 for Him Bench.',
        'An',
        'for men',
        NULL,
        NULL,
        'Melon, Apple, Anise, Lemon, Bergamot and Violet',
        'Jasmine, Rose, Grapefruit, Lavender and Patchouli',
        'Vanilla, Musk, Amber and Sandalwood',
        'fruity,fresh,ozonic,aquatic,powdery',
        'An Urban Original 2 for HimbyBench.is a Aromatic fragrance for men.An Urban Original 2 for Himwas launched in 2013. Top notes are Melon, Apple, Anise, Lemon, Bergamot and Violet; middle notes are Jasmine, Rose, Grapefruit, Lavender and Patchouli; base notes are Vanilla, Musk, Amber and Sandalwood.',
        3.92,
        24,
        NULL
      ),
(
        'Bench-An-Urban-Original-2-for-Her-20191',
        'Bench An Urban Original 2 for Her Bench.',
        'Bench',
        'for women',
        NULL,
        NULL,
        'Apple, Bergamot and Mandarin Orange',
        'Orange Blossom, Magnolia, Jasmine and Lily',
        'Sandalwood and Musk',
        'citrus,white floral,fruity,woody,powdery',
        'Bench An Urban Original 2 for HerbyBench.is a Floral Fruity fragrance for women.Bench An Urban Original 2 for Herwas launched in 2013. Top notes are Apple, Bergamot and Mandarin Orange; middle notes are Orange Blossom, Magnolia, Jasmine and Lily; base notes are Sandalwood and Musk.',
        3.62,
        21,
        NULL
      ),
(
        'Bench-For-Her-59071',
        'Bench For Her Bench.',
        'Bench',
        'for women',
        NULL,
        NULL,
        'Bitter Orange',
        'Rose and Jasmine',
        'Almond, Sugar, Vanilla, Musk, Patchouli and Sandalwood',
        'sweet,vanilla,almond,powdery,nutty',
        'Bench For HerbyBench.is a Floral Fruity Gourmand fragrance for women.Bench For Herwas launched in 2017. Top note is Bitter Orange; middle notes are Rose and Jasmine; base notes are Almond, Sugar, Vanilla, Musk, Patchouli and Sandalwood.',
        3.88,
        17,
        NULL
      ),
(
        'Bench-For-Him-59072',
        'Bench For Him Bench.',
        'Bench',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Apple and Mint',
        'Jasmine, Rose and Lavender',
        'Musk, Moss, Sandalwood, Tonka Bean and Amber',
        'aromatic,citrus,green,amber,fresh spicy',
        'Bench For HimbyBench.is a Amber Fougere fragrance for men.Bench For Himwas launched in 2017. Top notes are Bergamot, Lemon, Apple and Mint; middle notes are Jasmine, Rose and Lavender; base notes are Musk, Moss, Sandalwood, Tonka Bean and Amber.',
        3,
        2,
        NULL
      ),
(
        'Bench-Identity-For-Her-81499',
        'Bench Identity For Her Bench.',
        'Bench',
        'for women',
        NULL,
        NULL,
        'Raspberry, Cherry and Plum',
        'Orchid, Freesia and Iris',
        'Vanilla, Amber and Musk',
        'fruity,sweet,cherry,floral,vanilla',
        'Bench Identity For HerbyBench.is a fragrance for women. This is a new fragrance.Bench Identity For Herwas launched in 2023. Top notes are Raspberry, Cherry and Plum; middle notes are Orchid, Freesia and Iris; base notes are Vanilla, Amber and Musk.',
        3.4,
        5,
        NULL
      ),
(
        'Bench-Motion-For-Her-59073',
        'Bench Motion For Her Bench.',
        'Bench',
        'for women',
        NULL,
        NULL,
        'Pear, Pink Pepper and Orange Blossom',
        'Coffee and Jasmine',
        'Vanilla, Patchouli and Cedar',
        'white floral,vanilla,sweet,coffee,warm spicy',
        'Bench Motion For HerbyBench.is a Floral Fruity Gourmand fragrance for women.Bench Motion For Herwas launched in 2019. Top notes are Pear, Pink Pepper and Orange Blossom; middle notes are Coffee and Jasmine; base notes are Vanilla, Patchouli and Cedar.',
        4.27,
        11,
        NULL
      ),
(
        'Bench-Motion-For-Him-59075',
        'Bench Motion For Him Bench.',
        'Bench',
        'for men',
        NULL,
        NULL,
        'Apple, Bergamot and Orange Blossom',
        'Cinnamon, Geranium, Cloves and Lavender',
        'Vanila, Sandalwood, Cedar and Vetiver',
        'fruity,citrus,fresh spicy,warm spicy,woody',
        'Bench Motion For HimbyBench.is a Woody Spicy fragrance for men.Bench Motion For Himwas launched in 2019. Top notes are Apple, Bergamot and Orange Blossom; middle notes are Cinnamon, Geranium, Cloves and Lavender; base notes are Vanila, Sandalwood, Cedar and Vetiver.',
        2.33,
        3,
        NULL
      ),
(
        'Sound-For-Her-59070',
        'Sound For Her Bench.',
        'Sound',
        'for women',
        NULL,
        NULL,
        'Black Currant, Pear, Orange Blossom and Bergamot',
        'Iris and Jasmine Sambac',
        'Praline, Vanilla, Patchouli, Tonka Bean and Musk',
        'sweet,vanilla,fruity,powdery,white floral',
        'Sound For HerbyBench.is a Amber Floral fragrance for women.Sound For Herwas launched in 2018. Top notes are Black Currant, Pear, Orange Blossom and Bergamot; middle notes are Iris and Jasmine Sambac; base notes are Praline, Vanilla, Patchouli, Tonka Bean and Musk.',
        3.93,
        14,
        NULL
      ),
(
        'Sound-For-Him-59068',
        'Sound For Him Bench.',
        'Sound',
        'for men',
        NULL,
        NULL,
        'Melon, Lemon, Lime, Apple, Grapefruit, Bergamot, Lavender and Fennel',
        'Jasmine, Freesia, Lily and Rose',
        'Sandalwood, Cedar, Vetiver, Tonka Bean and Vanilla',
        'citrus,fresh,fruity,aromatic,ozonic',
        'Sound For HimbyBench.is a Woody fragrance for men.Sound For Himwas launched in 2018. Top notes are Melon, Lemon, Lime, Apple, Grapefruit, Bergamot, Lavender and Fennel; middle notes are Jasmine, Freesia, Lily and Rose; base notes are Sandalwood, Cedar, Vetiver, Tonka Bean and Vanilla.',
        3.5,
        2,
        NULL
      ),
(
        'Urban-Jungle-For-Her-64052',
        'Urban Jungle For Her Bench.',
        'Urban',
        'for women',
        NULL,
        NULL,
        'Black Currant, Almond and Wild Berries',
        'Iris, Jasmine and Tuberose',
        'Tonka Bean, Vanilla, Cacao and Coffee',
        'fruity,white floral,vanilla,warm spicy,sweet',
        'Urban Jungle For HerbyBench.is a Amber Floral fragrance for women.Urban Jungle For Herwas launched in 2020. Top notes are Black Currant, Almond and Wild Berries; middle notes are Iris, Jasmine and Tuberose; base notes are Tonka Bean, Vanilla, Cacao and Coffee.',
        3.83,
        12,
        NULL
      ),
(
        'Urban-Jungle-For-Him-64051',
        'Urban Jungle For Him Bench.',
        'Urban',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Pink Pepper, Melon and Pineapple',
        'Rose Geranium and Lavender',
        'Patchouli, Suede, Leather and Amber',
        'citrus,leather,sweet,fruity,soft spicy',
        'Urban Jungle For HimbyBench.is a Chypre Fruity fragrance for men.Urban Jungle For Himwas launched in 2020. Top notes are Mandarin Orange, Pink Pepper, Melon and Pineapple; middle notes are Rose Geranium and Lavender; base notes are Patchouli, Suede, Leather and Amber.',
        3,
        2,
        NULL
      ),
(
        'Bench-24-Hour-Life-Remixed-for-Her-41039',
        'Bench 24 Hour Life Remixed for Her Bench.',
        'Bench',
        'for women',
        NULL,
        NULL,
        'Green Notes, Rose, Lemon and Bergamot',
        'Lily, Rose, Mimosa, Violet and Jasmine',
        'Amber, Musk, Sandalwood and Vanilla',
        'white floral,green,powdery,floral,citrus',
        'Bench 24 Hour Life Remixed for HerbyBench.is a Floral Woody Musk fragrance for women.Bench 24 Hour Life Remixed for Herwas launched in 2016. Top notes are Green Notes, Rose, Lemon and Bergamot; middle notes are Lily, Rose, Mimosa, Violet and Jasmine; base notes are Amber, Musk, Sandalwood and Vanilla.',
        3.92,
        13,
        NULL
      ),
(
        'Bench-24-Hour-Life-Remixed-for-Him-41038',
        'Bench 24 Hour Life Remixed for Him Bench.',
        'Bench',
        'for men',
        NULL,
        NULL,
        'Pineapple, Mandarin Orange, Pink Pepper and Melon',
        'Lavender and Geranium',
        'Patchouli, Amber, Suede and Leather',
        'patchouli,woody,warm spicy,earthy,fruity',
        'Bench 24 Hour Life Remixed for HimbyBench.is a Woody Aromatic fragrance for men.Bench 24 Hour Life Remixed for Himwas launched in 2016. Top notes are Pineapple, Mandarin Orange, Pink Pepper and Melon; middle notes are Lavender and Geranium; base notes are Patchouli, Amber, Suede and Leather.',
        2.75,
        4,
        NULL
      ),
(
        'Bohemia-Garnet-39052',
        'Bohemia Garnet Bella Bellissima',
        'Bohemia',
        'for women',
        NULL,
        NULL,
        'Pomegranate, Bergamot, Raspberry, Lemon and Orange',
        'Damask Rose, Saffron, Jasmine, Geranium and Orange Blossom',
        'Patchouli, Agarwood (Oud), Papyrus, Amber, Musk, Sandalwood and Vanilla',
        'rose,woody,warm spicy,citrus,fresh spicy',
        'Bohemia GarnetbyBella Bellissimais a Amber Floral fragrance for women.Bohemia Garnetwas launched in 2015. Top notes are Pomegranate, Bergamot, Raspberry, Lemon and Orange; middle notes are Damask Rose, Saffron, Jasmine, Geranium and Orange Blossom; base notes are Patchouli, Agarwood (Oud), Papyrus, Amber, Musk, Sandalwood and Vanilla.',
        4.57,
        7,
        NULL
      ),
(
        'Cashmere-Angelique-39054',
        'Cashmere Angelique Bella Bellissima',
        'Cashmere',
        'for women',
        NULL,
        NULL,
        'Angelica, Thyme and Mint',
        'Turkish Rose, Incense, Cinnamon and Black Pepper',
        'Sandalwood, Amber, Cashmere Wood, Patchouli and Musk',
        'amber,woody,musky,powdery,warm spicy',
        'Cashmere AngeliquebyBella Bellissimais a Chypre Floral fragrance for women.Cashmere Angeliquewas launched in 2015. Top notes are Angelica, Thyme and Mint; middle notes are Turkish Rose, Incense, Cinnamon and Black Pepper; base notes are Sandalwood, Amber, Cashmere Wood, Patchouli and Musk.',
        4.7,
        10,
        NULL
      ),
(
        'Cologne-Toujours-39051',
        'Cologne Toujours Bella Bellissima',
        'Cologne',
        'for men',
        NULL,
        NULL,
        'Bergamot, Pink Pepper and Mint',
        'Chamomile, Orange Blossom, Rose, Jasmine, Nutmeg, Rosemary and Fennel',
        'Pine needles',
        'aromatic,white floral,fresh spicy,green,woody',
        'Cologne ToujoursbyBella Bellissimais a Woody Aromatic fragrance for men.Cologne Toujourswas launched in 2015. Top notes are Bergamot, Pink Pepper and Mint; middle notes are Chamomile, Orange Blossom, Rose, Jasmine, Nutmeg, Rosemary and Fennel; base note is Pine needles.',
        4,
        2,
        NULL
      ),
(
        'Exquisite-Eau-de-Parfum-Intense-13121',
        'Exquisite Eau de Parfum Intense Bella Bellissima',
        'Exquisite',
        'for women',
        NULL,
        NULL,
        'Citruses',
        'Ylang-Ylang, Lily, Jasmine and Rose',
        'Sandalwood, Guaiac Wood and Musk',
        'woody,white floral,yellow floral,powdery,sweet',
        'Exquisite Eau de Parfum IntensebyBella Bellissimais a Floral Woody Musk fragrance for women. Top note is Citruses; middle notes are Ylang-Ylang, Lily, Jasmine and Rose; base notes are Sandalwood, Guaiac Wood and Musk.',
        4,
        6,
        NULL
      );
