
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Gekkou-Hanami-44400',
        'Gekkou Hanami DSH Perfumes',
        'Gekkou',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'citrus,floral,fresh spicy,fresh,aromatic',
        'Gekkou HanamibyDSH Perfumesis a Floral fragrance for women and men.Gekkou Hanamiwas launched in 2017. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        21,
        NULL
      ),
(
        'Gelsomino-Jasmine-Italian-Journey-No-5-6586',
        'Gelsomino (Jasmine: Italian Journey No. 5) DSH Perfumes',
        'Gelsomino',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bitter Orange, Bergamot and Violet',
        'Jasmine, Neroli and Dyer’s Greenweed',
        'Sandalwood, Beeswax, Vetiver, Oakmoss, Vanilla, Musk and Amber',
        'white floral,citrus,woody,powdery,floral',
        'Gelsomino (Jasmine: Italian Journey No. 5)byDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Bitter Orange, Bergamot and Violet; middle notes are Jasmine, Neroli and Dyer’s Greenweed; base notes are Sandalwood, Beeswax, Vetiver, Oakmoss, Vanilla, Musk and Amber.',
        4.75,
        8,
        NULL
      ),
(
        'Giardini-Segreti-Italian-Journey-No-3-6587',
        'Giardini Segreti (Italian Journey No. 3) DSH Perfumes',
        'Giardini',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Neroli, Bitter Orange, Honeysuckle, Galbanum and Bergamot',
        'Tuberose, Gardenia, Jasmine, Mimosa, Rose Geranium and Orris Root',
        'Musk, Galbanum, Amber and Ambergris',
        'white floral,citrus,tuberose,green,fresh spicy',
        'Giardini Segreti (Italian Journey No. 3)byDSH Perfumesis a Amber Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Neroli, Bitter Orange, Honeysuckle, Galbanum and Bergamot; middle notes are Tuberose, Gardenia, Jasmine, Mimosa, Rose Geranium and Orris Root; base notes are Musk, Galbanum, Amber and Ambergris.',
        4.82,
        11,
        NULL
      ),
(
        'Gingembre-Ginger-1-Natural-6588',
        'Gingembre (Ginger 1; Natural) DSH Perfumes',
        'Gingembre',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Clove, Star Anise, Nutmeg, Paprika, Mandarin Orange and Black Pepper',
        'Ginger, Benzoin, Osmanthus, Jasmine, Beeswax and Rose',
        'Rum, Patchouli, French labdanum, Tolu Balsam, Sandalwood, Oakmoss, Cacao and Ambrette (Musk Mallow)',
        'warm spicy,amber,woody,floral,fresh spicy',
        'Gingembre (Ginger 1; Natural)byDSH Perfumesis a Amber Spicy fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Clove, Star Anise, Nutmeg, Paprika, Mandarin Orange and Black Pepper; middle notes are Ginger, Benzoin, Osmanthus, Jasmine, Beeswax and Rose; base notes are Rum, Patchouli, French labdanum, Tolu Balsam, Sandalwood, Oakmoss, Cacao and Ambrette (Musk Mallow).',
        4.25,
        16,
        NULL
      ),
(
        'Green-Rhubarb-and-Cane-Sugar-76152',
        'Green Rhubarb and Cane Sugar DSH Perfumes',
        'Green',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Rhubarb, Lemon and Bergamot',
        'Green Accord, Pear, Mimosa, Sugar Cane, Bulgarian Rose, Cabreuva, Tunisian Neroli, Galbanum, Lime and Jasmine',
        'Australian Sandalwood, Ambrette (Musk Mallow), Olibanum and Virginia Cedar',
        'green,sweet,fruity,woody,aromatic',
        'Green Rhubarb and Cane SugarbyDSH Perfumesis a Aromatic Green fragrance for women and men. This is a new fragrance.Green Rhubarb and Cane Sugarwas launched in 2022. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Rhubarb, Lemon and Bergamot; middle notes are Green Accord, Pear, Mimosa, Sugar Cane, Bulgarian Rose, Cabreuva, Tunisian Neroli, Galbanum, Lime and Jasmine; base notes are Australian Sandalwood, Ambrette (Musk Mallow), Olibanum and Virginia Cedar.',
        4,
        3,
        NULL
      ),
(
        'Guimauve-de-Soie-20988',
        'Guimauve de Soie DSH Perfumes',
        'Guimauve',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Violet Leaf, Anise, Lemon and Bergamot',
        'Parma Violet, Orris Root, Heliotrope, Bitter Almond, Cacao, Bulgarian Rose and Mimosa',
        'Musk, Vanilla, Civet, Moss, Tonka Bean, Ambrette (Musk Mallow) and Australian Sandalwood',
        'powdery,violet,floral,vanilla,almond',
        'Guimauve de SoiebyDSH Perfumesis a fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Violet Leaf, Anise, Lemon and Bergamot; middle notes are Parma Violet, Orris Root, Heliotrope, Bitter Almond, Cacao, Bulgarian Rose and Mimosa; base notes are Musk, Vanilla, Civet, Moss, Tonka Bean, Ambrette (Musk Mallow) and Australian Sandalwood.',
        4.12,
        17,
        NULL
      ),
(
        'Gum-Tree-Cabin-64473',
        'Gum Tree Cabin DSH Perfumes',
        'Gum',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy,green,camphor',
        'Gum Tree CabinbyDSH Perfumesis a Aromatic Green fragrance for women and men.Gum Tree Cabinwas launched in 2020. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.09,
        11,
        NULL
      ),
(
        'Habibi-47660',
        'Habibi DSH Perfumes',
        'Habibi',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'white floral,honey,sweet,warm spicy,oud',
        'HabibibyDSH Perfumesis a Amber Woody fragrance for women and men.Habibiwas launched in 2017. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        14,
        NULL
      ),
(
        'Halfeti-76141',
        'Halfeti DSH Perfumes',
        'Halfeti',
        'for women and men',
        NULL,
        NULL,
        'Blackberry, Bergamot and Birch Tar',
        'Bulgarian Rose, Rose, Damask Rose, French Rose, Moroccan Rose, Turkish Rose, Cognac, Tobacco, black fig, Cassis, Copaiba balm, Egyptian Pelargonium, Galbanum, Jasmine, Rose Leaf, Incense, Leather, Papyrus and Saffron',
        'Olibanum, Cambodian Oud, Hyrax, Amber, Natural Musk, Indian Patchouli, Ambergris, Atlas Cedar, Australian Sandalwood, Oakmoss, Castoreum, Labdanum, Myrrh, Orris and Vetiver',
        'woody,amber,warm spicy,animalic,musky',
        'HalfetibyDSH Perfumesis a Floral Woody Musk fragrance for women and men. This is a new fragrance.Halfetiwas launched in 2022. Top notes are Blackberry, Bergamot and Birch Tar; middle notes are Bulgarian Rose, Rose, Damask Rose, French Rose, Moroccan Rose, Turkish Rose, Cognac, Tobacco, black fig, Cassis, Copaiba balm, Egyptian Pelargonium, Galbanum, Jasmine, Rose Leaf, Incense, Leather, Papyrus and Saffron; base notes are Olibanum, Cambodian Oud, Hyrax, Amber, Natural Musk, Indian Patchouli, Ambergris, Atlas Cedar, Australian Sandalwood, Oakmoss, Castoreum, Labdanum, Myrrh, Orris and Vetiver.',
        4,
        1,
        NULL
      ),
(
        'Halloween-21033',
        'Halloween DSH Perfumes',
        'Halloween',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,warm spicy,woody,soft spicy,anis',
        'HalloweenbyDSH Perfumesis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.29,
        7,
        NULL
      ),
(
        'Hand-of-Buddha-21043',
        'Hand of Buddha DSH Perfumes',
        'Hand',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'citrus,fresh,green',
        'Hand of BuddhabyDSH Perfumesis a Citrus fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3,
        7,
        NULL
      ),
(
        'Hanukah-Cannelle-Holiday-no-9-21026',
        'Hanukah Cannelle (Holiday no.9) DSH Perfumes',
        'Hanukah',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'honey,cinnamon,fruity,warm spicy,fresh',
        'Hanukah Cannelle (Holiday no.9)byDSH Perfumesis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.25,
        12,
        NULL
      ),
(
        'Hinoki-21010',
        'Hinoki DSH Perfumes',
        'Hinoki',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy',
        'HinokibyDSH Perfumesis a Woody Aromatic fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.75,
        8,
        NULL
      ),
(
        'Hippie-Chic-21020',
        'Hippie Chic DSH Perfumes',
        'Hippie',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'coconut,patchouli,warm spicy,sweet,tobacco',
        'Hippie ChicbyDSH Perfumesis a Amber fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.83,
        6,
        NULL
      ),
(
        'Il-Marinaio-da-Capri-The-Sailor-from-Capri-45785',
        'Il Marinaio da Capri (The Sailor from Capri) DSH Perfumes',
        'Il',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'citrus,white floral,aromatic,woody,green',
        'Il Marinaio da Capri (The Sailor from Capri)byDSH Perfumesis a Aromatic Aquatic fragrance for women and men.Il Marinaio da Capri (The Sailor from Capri)was launched in 2017. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.76,
        17,
        NULL
      ),
(
        'Indochine-Ginger-2-6589',
        'Indochine (Ginger 2) DSH Perfumes',
        'Indochine',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Grapefruit, Mandarin Orange, Bergamot, Basil, Amalfi Lemon, Petitgrain, Lemon Balm and Lime peel',
        'Ylang-Ylang, Jasmine, Ginger, Basil and Brazilian Rosewood',
        'Musk, Sandalwood and Honey',
        'citrus,fresh spicy,woody,aromatic,sweet',
        'Indochine (Ginger 2)byDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Grapefruit, Mandarin Orange, Bergamot, Basil, Amalfi Lemon, Petitgrain, Lemon Balm and Lime peel; middle notes are Ylang-Ylang, Jasmine, Ginger, Basil and Brazilian Rosewood; base notes are Musk, Sandalwood and Honey.',
        3,
        7,
        NULL
      ),
(
        'Indus-16641',
        'Indus DSH Perfumes',
        'Indus',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Cardamom, Cloves, Black Pepper, Cinnamon and Bergamot',
        'Beeswax, Honey, Black Tea, Ginger and Jasmine',
        'Vanilla, Milk, Amber, Patchouli, Musk and Tolu Balsam',
        'warm spicy,honey,beeswax,animalic,fresh spicy',
        'IndusbyDSH Perfumesis a Amber Vanilla fragrance for women and men.Induswas launched in 2012. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Cardamom, Cloves, Black Pepper, Cinnamon and Bergamot; middle notes are Beeswax, Honey, Black Tea, Ginger and Jasmine; base notes are Vanilla, Milk, Amber, Patchouli, Musk and Tolu Balsam.',
        4.15,
        20,
        NULL
      ),
(
        'Inner-Sanctum-21021',
        'Inner Sanctum DSH Perfumes',
        'Inner',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,mossy,oud,rose,smoky',
        'Inner SanctumbyDSH Perfumesis a Amber fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.41,
        17,
        NULL
      ),
(
        'Iris-Tuxedo-64312',
        'Iris Tuxedo DSH Perfumes',
        'Iris',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Plum and Black Currant',
        'Iris, Orris Root and Black Tea',
        'Myrrh, Musk, Ambrette (Musk Mallow) and Oakmoss',
        'fruity,iris,powdery,earthy,sweet',
        'Iris TuxedobyDSH Perfumesis a Floral Woody Musk fragrance for women and men.Iris Tuxedowas launched in 2020. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Plum and Black Currant; middle notes are Iris, Orris Root and Black Tea; base notes are Myrrh, Musk, Ambrette (Musk Mallow) and Oakmoss.',
        4.55,
        11,
        NULL
      ),
(
        'Ivory-21032',
        'Ivory DSH Perfumes',
        'Ivory',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,musky,woody,citrus,powdery',
        'IvorybyDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.5,
        2,
        NULL
      ),
(
        'Jitterbug-8386',
        'Jitterbug DSH Perfumes',
        'Jitterbug',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Pepper, Blackberry, Amalfi Lemon and Bergamot',
        'Clove, Benzoin, Jasmine and Rose',
        'French labdanum, Patchouli, Amber, Olibanum, Incense and Musk',
        'amber,warm spicy,balsamic,woody,fresh spicy',
        'JitterbugbyDSH Perfumesis a Amber Spicy fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Pepper, Blackberry, Amalfi Lemon and Bergamot; middle notes are Clove, Benzoin, Jasmine and Rose; base notes are French labdanum, Patchouli, Amber, Olibanum, Incense and Musk.',
        4.3,
        40,
        NULL
      ),
(
        'Jitterbug-for-Men-8387',
        'Jitterbug for Men DSH Perfumes',
        'Jitterbug',
        'for men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Pepper, Bergamot, Amalfi Lemon and Blackberry',
        'Clove, Benzoin, Rose and Jasmine',
        'Patchouli, Olibanum, Amber, Musk, French labdanum and Virginia Cedar',
        'warm spicy,amber,fresh spicy,woody,patchouli',
        'Jitterbug for MenbyDSH Perfumesis a Amber Woody fragrance for men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Pepper, Bergamot, Amalfi Lemon and Blackberry; middle notes are Clove, Benzoin, Rose and Jasmine; base notes are Patchouli, Olibanum, Amber, Musk, French labdanum and Virginia Cedar.',
        4.25,
        8,
        NULL
      ),
(
        'June-Bride-8410',
        'June Bride DSH Perfumes',
        'June',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bergamot, Amalfi Lemon and Violet',
        'Geranium and Rose',
        'Iris and Sandalwood',
        'powdery,woody,iris,rose,aromatic',
        'June BridebyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Bergamot, Amalfi Lemon and Violet; middle notes are Geranium and Rose; base notes are Iris and Sandalwood.',
        4,
        1,
        NULL
      ),
(
        'Kale-76149',
        'Kale DSH Perfumes',
        'Kale',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Green Leaves, Apple, Pine needles, Bergamot and Lemon',
        'Cypress, Egyptian Pelargonium, Jasmine, Neroli and Rose Petals',
        'Orris Root, Woody Notes, Violet Leaf, Vetiver and Australian Sandalwood',
        'green,woody,aromatic,citrus,iris',
        'KalebyDSH Perfumesis a Aromatic Green fragrance for women and men. This is a new fragrance.Kalewas launched in 2022. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Green Leaves, Apple, Pine needles, Bergamot and Lemon; middle notes are Cypress, Egyptian Pelargonium, Jasmine, Neroli and Rose Petals; base notes are Orris Root, Woody Notes, Violet Leaf, Vetiver and Australian Sandalwood.',
        4,
        2,
        NULL
      ),
(
        'Kaleidoscope-40572',
        'Kaleidoscope DSH Perfumes',
        'Kaleidoscope',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'citrus,aromatic',
        'KaleidoscopebyDSH Perfumesis a Floral Fruity Gourmand fragrance for women and men.Kaleidoscopewas launched in 2016. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.7,
        10,
        NULL
      ),
(
        'L-eau-Natural-8388',
        'L´eau (Natural) DSH Perfumes',
        'L´eau',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Petitgrain, Bergamot, Amalfi Lemon and Bitter Orange',
        'Neroli, Jasmine and Rose',
        'Sandalwood and Virginia Cedar',
        'citrus,white floral,woody,fresh,aromatic',
        'L´eau (Natural)byDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Petitgrain, Bergamot, Amalfi Lemon and Bitter Orange; middle notes are Neroli, Jasmine and Rose; base notes are Sandalwood and Virginia Cedar.',
        4.5,
        4,
        NULL
      ),
(
        'L-eau-d-Iris-8389',
        'L´eau d´Iris DSH Perfumes',
        'L´eau',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Iris, Violet and Bergamot',
        'Neroli and Orris Root',
        'Musk, Sandalwood and Benzoin',
        'powdery,iris,violet,woody,citrus',
        'L´eau d´IrisbyDSH Perfumesis a Amber Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Iris, Violet and Bergamot; middle notes are Neroli and Orris Root; base notes are Musk, Sandalwood and Benzoin.',
        3.95,
        22,
        NULL
      ),
(
        'L-Homme-6590',
        'L''Homme DSH Perfumes',
        'L''Homme',
        'for men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bitter Orange, Bergamot, Coriander and Lime (Linden) Blossom',
        'Neroli, Spices and Jasmine',
        'Amber, Musk, Virginia Cedar and Sandalwood',
        'citrus,amber,white floral,woody,fresh',
        'L''HommebyDSH Perfumesis a fragrance for men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Bitter Orange, Bergamot, Coriander and Lime (Linden) Blossom; middle notes are Neroli, Spices and Jasmine; base notes are Amber, Musk, Virginia Cedar and Sandalwood.',
        3.6,
        5,
        NULL
      ),
(
        'L-eau-20995',
        'L’eau DSH Perfumes',
        'L’eau',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'citrus,fresh,fresh spicy,white floral,green',
        'L’eaubyDSH Perfumesis a Citrus fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.83,
        6,
        NULL
      ),
(
        'L-eau-d-Iris-20994',
        'L’eau d’Iris DSH Perfumes',
        'L’eau',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'iris,powdery,anis,violet,earthy',
        'L’eau d’IrisbyDSH Perfumesis a Floral fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.2,
        5,
        NULL
      ),
(
        'La-Belle-Saison-37237',
        'La Belle Saison DSH Perfumes',
        'La',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'floral,honey,beeswax,anis,soft spicy',
        'La Belle SaisonbyDSH Perfumesis a Floral fragrance for women and men.La Belle Saisonwas launched in 2016. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.4,
        5,
        NULL
      ),
(
        'La-Fete-Nouvelle-21017',
        'La Fete Nouvelle DSH Perfumes',
        'La',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'almond,nutty,fruity,sweet',
        'La Fete NouvellebyDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.5,
        14,
        NULL
      ),
(
        'La-Plage-Sea-8390',
        'La Plage Sea DSH Perfumes',
        'La',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bergamot, Amalfi Lemon and Petitgrain',
        'Salt, Cucumber and Water Notes',
        'Sea water',
        'citrus,aquatic,aromatic,marine,salty',
        'La Plage SeabyDSH Perfumesis a Aromatic Aquatic fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Bergamot, Amalfi Lemon and Petitgrain; middle notes are Salt, Cucumber and Water Notes; base note is Sea water.',
        4.6,
        5,
        NULL
      ),
(
        'La-Reine-des-Fleurs-24130',
        'La Reine des Fleurs DSH Perfumes',
        'La',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Peach, Bergamot, Mandarin Orange and Jasmine',
        'Moroccan Rose, Turkish Rose, Orris Root and Rose Geranium',
        'Sandalwood, Patchouli, Vanilla, Tahitian Vanilla, Siam Benzoin, Moss, Peru Balsam, Civet and Tolu Balsam',
        'rose,woody,powdery,warm spicy,fruity',
        'La Reine des FleursbyDSH Perfumesis a Amber Floral fragrance for women and men.La Reine des Fleurswas launched in 2014. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Peach, Bergamot, Mandarin Orange and Jasmine; middle notes are Moroccan Rose, Turkish Rose, Orris Root and Rose Geranium; base notes are Sandalwood, Patchouli, Vanilla, Tahitian Vanilla, Siam Benzoin, Moss, Peru Balsam, Civet and Tolu Balsam.',
        4.53,
        15,
        NULL
      ),
(
        'La-Rose-Beatifique-71620',
        'La Rose Béatifique DSH Perfumes',
        'La',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'fruity,sweet,amber,rose,warm spicy',
        'La Rose BéatifiquebyDSH Perfumesis a fragrance for women and men.La Rose Béatifiquewas launched in 2021. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        1,
        NULL
      ),
(
        'la-Rose-Fleurette-Rose-No-2-6591',
        'la Rose Fleurette (Rose No. 2) DSH Perfumes',
        'la',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Apple Blossom, Bergamot and Violet',
        'Rose and Geranium',
        'Heliotrope, White Honey and Musk',
        'floral,rose,powdery,fresh spicy,honey',
        'la Rose Fleurette (Rose No. 2)byDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Apple Blossom, Bergamot and Violet; middle notes are Rose and Geranium; base notes are Heliotrope, White Honey and Musk.',
        4.5,
        4,
        NULL
      ),
(
        'La-Vie-en-Rose-20987',
        'La Vie en Rose DSH Perfumes',
        'La',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'violet,aldehydic,rose,powdery,fresh',
        'La Vie en RosebyDSH Perfumesis a Floral Aldehyde fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.17,
        6,
        NULL
      ),
(
        'Lautrec-21062',
        'Lautrec DSH Perfumes',
        'Lautrec',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Artemisia, Passionfruit, Wormwood and Bergamot',
        'Cognac, Ylang-Ylang, Orange Blossom, Moroccan Rose, Mimosa, Orris Root and Jasmine Sambac',
        'Amber, Tolu Balsam, Labdanum, Siam Benzoin, Civet, Moss, Vanilla, Caramel, Australian Sandalwood and Indian Patchouli',
        'amber,sweet,woody,powdery,warm spicy',
        'LautrecbyDSH Perfumesis a Amber Vanilla fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Artemisia, Passionfruit, Wormwood and Bergamot; middle notes are Cognac, Ylang-Ylang, Orange Blossom, Moroccan Rose, Mimosa, Orris Root and Jasmine Sambac; base notes are Amber, Tolu Balsam, Labdanum, Siam Benzoin, Civet, Moss, Vanilla, Caramel, Australian Sandalwood and Indian Patchouli.',
        4.2,
        10,
        NULL
      ),
(
        'Lavande-21046',
        'Lavande DSH Perfumes',
        'Lavande',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'green,lavender,amber,aromatic,fresh spicy',
        'LavandebyDSH Perfumesis a Aromatic Green fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        1,
        NULL
      ),
(
        'Le-Roi-Soleil-The-Perfumed-Court-Natural-6592',
        'Le Roi Soleil (The Perfumed Court; Natural) DSH Perfumes',
        'Le',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Rosemary, Orange, Bergamot, Amalfi Lemon and Lime',
        'Oregano, Clove, Lavender, Carnation, Jasmine and African Orange Flower',
        'Birch, Ambrette (Musk Mallow), Oakmoss, Amber, Olibanum and Leather',
        'aromatic,fresh spicy,citrus,leather,woody',
        'Le Roi Soleil (The Perfumed Court; Natural)byDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Rosemary, Orange, Bergamot, Amalfi Lemon and Lime; middle notes are Oregano, Clove, Lavender, Carnation, Jasmine and African Orange Flower; base notes are Birch, Ambrette (Musk Mallow), Oakmoss, Amber, Olibanum and Leather.',
        4,
        2,
        NULL
      ),
(
        'Le-Sazerac-71617',
        'Le Sazerac DSH Perfumes',
        'Le',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,amber,anis,powdery',
        'Le SazeracbyDSH Perfumesis a Amber Vanilla fragrance for women and men.Le Sazeracwas launched in 2021. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.09,
        11,
        NULL
      ),
(
        'Le-Serval-64047',
        'Le Serval DSH Perfumes',
        'Le',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'animalic,musky,honey,amber,floral',
        'Le ServalbyDSH Perfumesis a Amber Woody fragrance for women and men.Le Servalwas launched in 2020. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.14,
        28,
        NULL
      ),
(
        'Le-Smoking-20982',
        'Le Smoking DSH Perfumes',
        'Le',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'green,mossy,earthy,woody',
        'Le SmokingbyDSH Perfumesis a Chypre fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.32,
        25,
        NULL
      ),
(
        'Les-Petites-8391',
        'Les Petites DSH Perfumes',
        'Les',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Lime (Linden) Blossom, African Orange Flower and Rose',
        'Chamomile, Neroli and Mandarin Orange',
        'Sandalwood',
        'citrus,white floral,sweet,floral,yellow floral',
        'Les PetitesbyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Lime (Linden) Blossom, African Orange Flower and Rose; middle notes are Chamomile, Neroli and Mandarin Orange; base note is Sandalwood.',
        4,
        4,
        NULL
      ),
(
        'Lift-Off-21047',
        'Lift Off DSH Perfumes',
        'Lift',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'warm spicy,citrus,fresh spicy,herbal,aromatic',
        'Lift OffbyDSH Perfumesis a Aromatic Green fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.33,
        3,
        NULL
      ),
(
        'Ligne-Trapeze-20984',
        'Ligne Trapéze DSH Perfumes',
        'Ligne',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'floral,aldehydic,fresh,musky',
        'Ligne TrapézebyDSH Perfumesis a Floral Aldehyde fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.2,
        5,
        NULL
      ),
(
        'LiLi-8424',
        'LiLi DSH Perfumes',
        'LiLi',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Lime, Amalfi Lemon and Mimosa',
        'Lime (Linden) Blossom and Lily-of-the-Valley',
        'Sandalwood',
        'citrus,white floral,yellow floral,green,sweet',
        'LiLibyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Lime, Amalfi Lemon and Mimosa; middle notes are Lime (Linden) Blossom and Lily-of-the-Valley; base note is Sandalwood.',
        3.73,
        11,
        NULL
      ),
(
        'Little-Smile-21004',
        'Little Smile DSH Perfumes',
        'Little',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,citrus,almond',
        'Little SmilebyDSH Perfumesis a Citrus Gourmand fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.67,
        9,
        NULL
      ),
(
        'Luckyclover-21002',
        'Luckyclover DSH Perfumes',
        'Luckyclover',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'floral,green,honey,sweet,fresh',
        'LuckycloverbyDSH Perfumesis a Floral Green fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.6,
        5,
        NULL
      ),
(
        'Lumiere-Holiday-no-7-21024',
        'Lumiere (Holiday no.7) DSH Perfumes',
        'Lumiere',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'warm spicy,coffee,sweet,vanilla',
        'Lumiere (Holiday no.7)byDSH Perfumesis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.07,
        15,
        NULL
      ),
(
        'Ma-Folie-de-Noel-My-Christmas-Folly-Holiday-no-6-21031',
        'Ma Folie de Noel (My Christmas Folly; Holiday no.6) DSH Perfumes',
        'Ma',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,smoky,anis,soft spicy,balsamic',
        'Ma Folie de Noel (My Christmas Folly; Holiday no.6)byDSH Perfumesis a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.5,
        6,
        NULL
      ),
(
        'Ma-Plus-Belle-Histoire-d-Amour-20985',
        'Ma Plus Belle Histoire d’Amour DSH Perfumes',
        'Ma',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'floral',
        'Ma Plus Belle Histoire d’AmourbyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.8,
        5,
        NULL
      ),
(
        'Madonna-Lily-8392',
        'Madonna Lily DSH Perfumes',
        'Madonna',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Lily-of-the-Valley, Bergamot and Spices',
        'Lily, Ylang-Ylang and Narcissus',
        'Galbanum, Vanille and Violet Leaf',
        'white floral,green,yellow floral,fresh,sweet',
        'Madonna LilybyDSH Perfumesis a Amber Floral fragrance for women.Madonna Lilywas launched in 2008. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Lily-of-the-Valley, Bergamot and Spices; middle notes are Lily, Ylang-Ylang and Narcissus; base notes are Galbanum, Vanille and Violet Leaf.',
        4.67,
        6,
        NULL
      ),
(
        'Mahjoun-8425',
        'Mahjoun DSH Perfumes',
        'Mahjoun',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Almond, Lavender, Cardamom, Amalfi Lemon and Orange',
        'White Honey, Dates, Hazelnut, Fig, Nutmeg, Rose and African Orange Flower',
        'Cinnamon, Amber, Sandalwood, Myrhh, Clove, Olibanum and Virginia Cedar',
        'sweet,warm spicy,fruity,honey,nutty',
        'MahjounbyDSH Perfumesis a Amber Spicy fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Almond, Lavender, Cardamom, Amalfi Lemon and Orange; middle notes are White Honey, Dates, Hazelnut, Fig, Nutmeg, Rose and African Orange Flower; base notes are Cinnamon, Amber, Sandalwood, Myrhh, Clove, Olibanum and Virginia Cedar.',
        3.84,
        49,
        NULL
      ),
(
        'ManRoot-64049',
        'ManRoot DSH Perfumes',
        'ManRoot',
        'for men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'powdery,iris,earthy,woody,warm spicy',
        'ManRootbyDSH Perfumesis a Floral Woody Musk fragrance for men.ManRootwas launched in 2020. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.5,
        2,
        NULL
      ),
(
        'Marzipan-Holiday-no-5-21034',
        'Marzipan (Holiday no.5) DSH Perfumes',
        'Marzipan',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'almond,nutty,sweet,fruity',
        'Marzipan (Holiday no.5)byDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.76,
        17,
        NULL
      ),
(
        'Mata-Hari-10954',
        'Mata Hari DSH Perfumes',
        'Mata',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Fruity Notes, Orange, Neroli, Blood Orange, Coriander, Bergamot, Mandarin Orange, Tarragon and African Orange Flower',
        'Clove, Cinnamon, White Honey, Champaca, Jasmine, Tuberose, Orris Root, Lilac, Osmanthus, Nutmeg, Tagetes, Angelica, Rose, Black Currant and Orchid',
        'Myrhh, Leather, Musk, oak moss, Benzoin, Tobacco, French labdanum, Peru Balsam, Patchouli, Sandalwood, Cassis, Virginia Cedar, Ambrette (Musk Mallow), Vanille, Cumin, Tonka Bean and Vetiver',
        'floral,amber,warm spicy,sweet,woody',
        'Mata HaribyDSH Perfumesis a Chypre Fruity fragrance for women.Mata Hariwas launched in 2010. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Fruity Notes, Orange, Neroli, Blood Orange, Coriander, Bergamot, Mandarin Orange, Tarragon and African Orange Flower; middle notes are Clove, Cinnamon, White Honey, Champaca, Jasmine, Tuberose, Orris Root, Lilac, Osmanthus, Nutmeg, Tagetes, Angelica, Rose, Black Currant and Orchid; base notes are Myrhh, Leather, Musk, oak moss, Benzoin, Tobacco, French labdanum, Peru Balsam, Patchouli, Sandalwood, Cassis, Virginia Cedar, Ambrette (Musk Mallow), Vanille, Cumin, Tonka Bean and Vetiver.',
        4.41,
        44,
        NULL
      ),
(
        'Matsu-18762',
        'Matsu DSH Perfumes',
        'Matsu',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,citrus,fresh spicy,aromatic,musky',
        'MatsubyDSH Perfumesis a Woody Aromatic fragrance for women and men.Matsuwas launched in 2013. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.14,
        14,
        NULL
      ),
(
        'Memory-Desire-No-1-20989',
        'Memory & Desire No.1 DSH Perfumes',
        'Memory',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'floral,mossy,earthy,woody,aromatic',
        'Memory & Desire No.1byDSH Perfumesis a Chypre Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.43,
        7,
        NULL
      ),
(
        'Menthe-Moderne-8426',
        'Menthe Moderne DSH Perfumes',
        'Menthe',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Mint, Lime, Petitgrain and Bergamot',
        'Fir, Violet, Green Tea and Petitgrain',
        'Virginia Cedar',
        'green,aromatic,woody,fresh spicy,citrus',
        'Menthe ModernebyDSH Perfumesis a Citrus Aromatic fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Mint, Lime, Petitgrain and Bergamot; middle notes are Fir, Violet, Green Tea and Petitgrain; base note is Virginia Cedar.',
        3.33,
        12,
        NULL
      ),
(
        'Metropolis-25397',
        'Metropolis DSH Perfumes',
        'Metropolis',
        'for men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'aldehydic,woody,fresh spicy,aromatic,mossy',
        'MetropolisbyDSH Perfumesis a fragrance for men.Metropoliswas launched in 2014. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.78,
        9,
        NULL
      ),
(
        'Michelangelo-8427',
        'Michelangelo DSH Perfumes',
        'Michelangelo',
        'for men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Oregano, Pine, Clary Sage, Lemon, Bay Leaf and Bergamot',
        'Peru Balsam, Spices, French labdanum, Rose, Palmarosa and Olibanum',
        'oak moss, Vetyver, Virginia Cedar, Ambergris, Tobacco, Incense and Myrhh',
        'aromatic,woody,fresh spicy,mossy,earthy',
        'MichelangelobyDSH Perfumesis a Amber Woody fragrance for men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Oregano, Pine, Clary Sage, Lemon, Bay Leaf and Bergamot; middle notes are Peru Balsam, Spices, French labdanum, Rose, Palmarosa and Olibanum; base notes are oak moss, Vetyver, Virginia Cedar, Ambergris, Tobacco, Incense and Myrhh.',
        4.09,
        11,
        NULL
      ),
(
        'Mille-Fleurs-Bouquet-9977',
        'Mille-Fleurs Bouquet DSH Perfumes',
        'Mille-Fleurs',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Amalfi Lemon, Orange, Cassis and Lavender',
        'Jasmine, African Orange Flower, Geranium, Orris Root, Rose, Violet and Violet Leaf',
        'Vetyver, Amber and Vanille',
        'aromatic,citrus,white floral,powdery,fresh spicy',
        'Mille-Fleurs BouquetbyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Amalfi Lemon, Orange, Cassis and Lavender; middle notes are Jasmine, African Orange Flower, Geranium, Orris Root, Rose, Violet and Violet Leaf; base notes are Vetyver, Amber and Vanille.',
        NULL,
        NULL,
        NULL
      ),
(
        'Mimosa-8393',
        'Mimosa DSH Perfumes',
        'Mimosa',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Black locust, Lime (Linden) Blossom, Dyer’s Greenweed and Cassis',
        'Mimosa',
        'Orris Root, Sandalwood, Vanille and Tonka Bean',
        'yellow floral,sweet,powdery,white floral,honey',
        'MimosabyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Black locust, Lime (Linden) Blossom, Dyer’s Greenweed and Cassis; middle note is Mimosa; base notes are Orris Root, Sandalwood, Vanille and Tonka Bean.',
        3.78,
        9,
        NULL
      ),
(
        'Minuit-8428',
        'Minuit DSH Perfumes',
        'Minuit',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Cassis, Fir, Pimento, Hazelnut and Bergamot',
        'Carnation, Cloves, Cinnamon, Rose, Tuberose, Jasmine and Mimosa',
        'oak moss, Labdanum, Olibanum, Agarwood (Oud), Patchouli, Sandalwood and Vanilla Absolute',
        'warm spicy,woody,aromatic,floral,amber',
        'MinuitbyDSH Perfumesis a Chypre Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Cassis, Fir, Pimento, Hazelnut and Bergamot; middle notes are Carnation, Cloves, Cinnamon, Rose, Tuberose, Jasmine and Mimosa; base notes are oak moss, Labdanum, Olibanum, Agarwood (Oud), Patchouli, Sandalwood and Vanilla Absolute.',
        4.69,
        16,
        NULL
      ),
(
        'Mirabella-21065',
        'Mirabella DSH Perfumes',
        'Mirabella',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Fruity Notes, Spicy Notes, Plum and Bergamot',
        'Tuberose, Broom, Jasmine, Jasmine Sambac, Osmanthus, Orange Blossom, Ylang-Ylang, Rose, Damask Rose and Orris Root',
        'Beeswax, Oakmoss, Castoreum, Civet, Labdanum, Siam Benzoin, Australian Sandalwood, Leather, Indian Patchouli and Vanilla',
        'fruity,white floral,sweet,animalic,woody',
        'MirabellabyDSH Perfumesis a Chypre Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Fruity Notes, Spicy Notes, Plum and Bergamot; middle notes are Tuberose, Broom, Jasmine, Jasmine Sambac, Osmanthus, Orange Blossom, Ylang-Ylang, Rose, Damask Rose and Orris Root; base notes are Beeswax, Oakmoss, Castoreum, Civet, Labdanum, Siam Benzoin, Australian Sandalwood, Leather, Indian Patchouli and Vanilla.',
        4.36,
        22,
        NULL
      ),
(
        'Mother-of-the-Bride-8411',
        'Mother of the Bride DSH Perfumes',
        'Mother',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Spices',
        'Lily, Camelia, Carnation and Rose',
        'Amber',
        'floral,warm spicy,white floral,soft spicy,powdery',
        'Mother of the BridebyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top note is Spices; middle notes are Lily, Camelia, Carnation and Rose; base note is Amber.',
        3,
        5,
        NULL
      ),
(
        'Mountain-Sage-20999',
        'Mountain Sage DSH Perfumes',
        'Mountain',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'aromatic,herbal,soft spicy,musky',
        'Mountain SagebyDSH Perfumesis a Aromatic Green fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.5,
        2,
        NULL
      ),
(
        'Muguet-Cologne-47573',
        'Muguet Cologne DSH Perfumes',
        'Muguet',
        'for men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,citrus,fresh spicy,white floral',
        'Muguet ColognebyDSH Perfumesis a Floral Green fragrance for men.Muguet Colognewas launched in 2011. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        2,
        1,
        NULL
      ),
(
        'Muresque-76129',
        'Muresque DSH Perfumes',
        'Muresque',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Blackberry Blossom, Blackberry, Aldehydes, Bergamot and Blackberry leaf',
        'Ambrette (Musk Mallow), Balsam Fir, Bulgarian Rose, Damask Rose, Cassis, Jasmine, Violet and Pinot Noir grapes',
        'Labdanum, Atlas Cedar, Australian Sandalwood, Indian Patchouli, Oakmoss, Orris and Musk',
        'fruity,woody,floral,musky,aromatic',
        'MuresquebyDSH Perfumesis a Chypre Fruity fragrance for women and men. This is a new fragrance.Muresquewas launched in 2022. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Blackberry Blossom, Blackberry, Aldehydes, Bergamot and Blackberry leaf; middle notes are Ambrette (Musk Mallow), Balsam Fir, Bulgarian Rose, Damask Rose, Cassis, Jasmine, Violet and Pinot Noir grapes; base notes are Labdanum, Atlas Cedar, Australian Sandalwood, Indian Patchouli, Oakmoss, Orris and Musk.',
        4.67,
        3,
        NULL
      ),
(
        'Musc-al-Medina-42653',
        'Musc al Medina DSH Perfumes',
        'Musc',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,aromatic,warm spicy,fresh spicy,herbal',
        'Musc al MedinabyDSH Perfumesis a Aromatic fragrance for women and men.Musc al Medinawas launched in 2016. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.53,
        17,
        NULL
      ),
(
        'Mysore-Sandalwood-21028',
        'Mysore Sandalwood DSH Perfumes',
        'Mysore',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy',
        'Mysore SandalwoodbyDSH Perfumesis a Amber Woody fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.33,
        9,
        NULL
      ),
(
        'New-Hope-Is-Where-We-Dream-71626',
        'New Hope... Is Where We Dream DSH Perfumes',
        'New',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,honey,green,woody,white floral',
        'New Hope... Is Where We DreambyDSH Perfumesis a Floral Green fragrance for women and men.New Hope... Is Where We Dreamwas launched in 2021.',
        4.33,
        3,
        NULL
      ),
(
        'Noel-Enchante-Holiday-No-15-44541',
        'Noel Enchante (Holiday No. 15) DSH Perfumes',
        'Noel',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'white floral,amber,tuberose,warm spicy,green',
        'Noel Enchante (Holiday No. 15)byDSH Perfumesis a Chypre Floral fragrance for women and men.Noel Enchante (Holiday No. 15)was launched in 2015. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.21,
        14,
        NULL
      ),
(
        'Nourouz-8324',
        'Nourouz DSH Perfumes',
        'Nourouz',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Tamarind, Paprika and Pomegranate',
        'Iris, Osmanthus and Rose',
        'Tobacco, Opoponax and Vanille',
        'warm spicy,sweet,tobacco,woody,fruity',
        'NourouzbyDSH Perfumesis a Amber Spicy fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Tamarind, Paprika and Pomegranate; middle notes are Iris, Osmanthus and Rose; base notes are Tobacco, Opoponax and Vanille.',
        3.8,
        20,
        NULL
      ),
(
        'Nouveau-Gardenia-8394',
        'Nouveau Gardenia DSH Perfumes',
        'Nouveau',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bergamot and Mimosa',
        'Gardenia',
        'Musk and Sandalwood',
        'white floral,powdery,citrus,woody,yellow floral',
        'Nouveau GardeniabyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Bergamot and Mimosa; middle note is Gardenia; base notes are Musk and Sandalwood.',
        4,
        10,
        NULL
      ),
(
        'Onycha-42654',
        'Onycha DSH Perfumes',
        'Onycha',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,smoky,animalic,marine,balsamic',
        'OnychabyDSH Perfumesis a Amber fragrance for women and men.Onychawas launched in 2016. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.32,
        22,
        NULL
      ),
(
        'Open-Space-No-1-76124',
        'Open Space No. 1 DSH Perfumes',
        'Open',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,amber,green,citrus',
        'Open Space No. 1byDSH Perfumesis a Amber Woody fragrance for women and men. This is a new fragrance.Open Space No. 1was launched in 2022. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.5,
        4,
        NULL
      ),
(
        'Oude-Arabique-8430',
        'Oude Arabique DSH Perfumes',
        'Oude',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Tolu Balsam, Mastic or Lentisque and Resin',
        'Agarwood (Oud), Incense and Sandalwood',
        'Tolu Balsam, Woodsy Notes and Virginia Cedar',
        'amber,balsamic,warm spicy,woody,oud',
        'Oude ArabiquebyDSH Perfumesis a Amber Woody fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Tolu Balsam, Mastic or Lentisque and Resin; middle notes are Agarwood (Oud), Incense and Sandalwood; base notes are Tolu Balsam, Woodsy Notes and Virginia Cedar.',
        4.8,
        10,
        NULL
      ),
(
        'Padme-Lotus-8431',
        'Padme Lotus DSH Perfumes',
        'Padme',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Neroli, Blood Orange, Osmanthus and Tuberose',
        'Pink Lotus, Tagetes, White Lotus and Rose',
        'Violet Leaf, Vetyver and Sandalwood',
        'floral,woody,aromatic,ozonic,aquatic',
        'Padme LotusbyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Neroli, Blood Orange, Osmanthus and Tuberose; middle notes are Pink Lotus, Tagetes, White Lotus and Rose; base notes are Violet Leaf, Vetyver and Sandalwood.',
        4.44,
        9,
        NULL
      ),
(
        'Pamplemousse-6737',
        'Pamplemousse DSH Perfumes',
        'Pamplemousse',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Grapefruit, Bergamot and Mandarin Orange',
        'Pomelo, Amalfi Lemon and Neroli',
        'Tea and Sandalwood',
        'citrus,fresh spicy,aromatic',
        'PamplemoussebyDSH Perfumesis a Citrus fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Grapefruit, Bergamot and Mandarin Orange; middle notes are Pomelo, Amalfi Lemon and Neroli; base notes are Tea and Sandalwood.',
        3.85,
        40,
        NULL
      ),
(
        'Pandora-20990',
        'Pandora DSH Perfumes',
        'Pandora',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'mossy,floral,earthy,leather,soft spicy',
        'PandorabyDSH Perfumesis a Chypre Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.32,
        25,
        NULL
      ),
(
        'Paradise-Lost-Clarimonde-Perfume-Project-45038',
        'Paradise Lost (Clarimonde Perfume Project) DSH Perfumes',
        'Paradise',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Violet, Immortelle, Chamomile and Champaca',
        'Floral Notes, Lotus, Surf Wax and Orris',
        'Amber, Myrrh, Sweet Notes and Animal notes',
        'floral,sweet,herbal,amber,powdery',
        'Paradise Lost (Clarimonde Perfume Project)byDSH Perfumesis a Amber Floral fragrance for women and men.Paradise Lost (Clarimonde Perfume Project)was launched in 2011. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Violet, Immortelle, Chamomile and Champaca; middle notes are Floral Notes, Lotus, Surf Wax and Orris; base notes are Amber, Myrrh, Sweet Notes and Animal notes.',
        5,
        3,
        NULL
      ),
(
        'Parfum-de-Grasse-8417',
        'Parfum de Grasse DSH Perfumes',
        'Parfum',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bergamot, Neroli and Mimosa',
        'Jasmine, Carnation, Rose, Beeswax and Iris',
        'oak moss, Vetyver and Sandalwood',
        'woody,floral,citrus,earthy,aromatic',
        'Parfum de GrassebyDSH Perfumesis a Chypre Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Bergamot, Neroli and Mimosa; middle notes are Jasmine, Carnation, Rose, Beeswax and Iris; base notes are oak moss, Vetyver and Sandalwood.',
        4.09,
        22,
        NULL
      ),
(
        'Parfum-de-Luxe-8418',
        'Parfum de Luxe DSH Perfumes',
        'Parfum',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Violet, Bergamot, Clary Sage and Petitgrain',
        'White Honey, Rose, Iris, Tuberose, Ylang-Ylang and Geranium',
        'Amber, French labdanum, oak moss, Tobacco, Benzoin, Patchouli, Sandalwood and Vanille',
        'amber,woody,powdery,sweet,earthy',
        'Parfum de LuxebyDSH Perfumesis a Amber Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Violet, Bergamot, Clary Sage and Petitgrain; middle notes are White Honey, Rose, Iris, Tuberose, Ylang-Ylang and Geranium; base notes are Amber, French labdanum, oak moss, Tobacco, Benzoin, Patchouli, Sandalwood and Vanille.',
        4.23,
        26,
        NULL
      ),
(
        'Parma-Violet-21007',
        'Parma Violet DSH Perfumes',
        'Parma',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'powdery,ozonic,violet,aquatic,green',
        'Parma VioletbyDSH Perfumesis a Floral Green fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        5,
        NULL
      ),
(
        'Peony-25395',
        'Peony DSH Perfumes',
        'Peony',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'green,fresh,floral,rose',
        'PeonybyDSH Perfumesis a Floral Green fragrance for women.Peonywas launched in 2014. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.75,
        4,
        NULL
      ),
(
        'Pink-Gardenia-8432',
        'Pink Gardenia DSH Perfumes',
        'Pink',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Bergamot',
        'Gardenia and Tuberose',
        'Musk and Amber',
        'white floral,tuberose,musky,animalic,citrus',
        'Pink GardeniabyDSH Perfumesis a Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top note is Bergamot; middle notes are Gardenia and Tuberose; base notes are Musk and Amber.',
        3.8,
        5,
        NULL
      ),
(
        'Pomander-21056',
        'Pomander DSH Perfumes',
        'Pomander',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'citrus,warm spicy,sweet,woody',
        'PomanderbyDSH Perfumesis a fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.25,
        4,
        NULL
      ),
(
        'Pompeii-21048',
        'Pompeii DSH Perfumes',
        'Pompeii',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'white floral,citrus,fresh,floral,fresh spicy',
        'PompeiibyDSH Perfumesis a Floral fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.33,
        3,
        NULL
      ),
(
        'Poppy-45783',
        'Poppy DSH Perfumes',
        'Poppy',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,floral,sweet,powdery',
        'PoppybyDSH Perfumesis a Amber fragrance for women and men.Poppywas launched in 2017. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        3,
        NULL
      ),
(
        'Powder-21011',
        'Powder DSH Perfumes',
        'Powder',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        NULL,
        'PowderbyDSH Perfumesis a fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        3,
        NULL
      ),
(
        'Prana-8399',
        'Prana DSH Perfumes',
        'Prana',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        'Coriander, Amalfi Lemon, Nutmeg and Cardamom',
        'Champaca, Jasmine, Rose and Tuberose',
        'Myrhh, Olibanum, Sandalwood, Virginia Cedar, Patchouli and Agarwood (Oud)',
        'aromatic,woody,amber,warm spicy,fresh spicy',
        'PranabyDSH Perfumesis a Amber Floral fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Coriander, Amalfi Lemon, Nutmeg and Cardamom; middle notes are Champaca, Jasmine, Rose and Tuberose; base notes are Myrhh, Olibanum, Sandalwood, Virginia Cedar, Patchouli and Agarwood (Oud).',
        4.06,
        17,
        NULL
      ),
(
        'Pretty-Pink-20991',
        'Pretty & Pink DSH Perfumes',
        'Pretty',
        'for women',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'floral,fruity,sweet',
        'Pretty & PinkbyDSH Perfumesis a Floral Fruity fragrance for women. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.2,
        5,
        NULL
      ),
(
        'Prophecy-21001',
        'Prophecy DSH Perfumes',
        'Prophecy',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,smoky,balsamic,warm spicy',
        'ProphecybyDSH Perfumesis a Amber fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.33,
        9,
        NULL
      ),
(
        'Rain-71151',
        'Rain DSH Perfumes',
        'Rain',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Carnation, Neroli, Gardenia, Honeysuckle, Hyacinth, Lily-of-the-Valley and Iris',
        'Musk and Orris Root',
        'white floral,floral,iris,powdery,citrus',
        'RainbyDSH Perfumesis a Floral fragrance for women.Rainwas launched in 2018. Top note is Bergamot; middle notes are Carnation, Neroli, Gardenia, Honeysuckle, Hyacinth, Lily-of-the-Valley and Iris; base notes are Musk and Orris Root.',
        4,
        1,
        NULL
      ),
(
        'Raisin-d-Etre-71624',
        'Raisin d''Etre DSH Perfumes',
        'Raisin',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'amber,vanilla,woody,sweet,warm spicy',
        'Raisin d''EtrebyDSH Perfumesis a fragrance for women and men.Raisin d''Etrewas launched in 2021. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4,
        3,
        NULL
      ),
(
        'Re-Assess-71616',
        'Re-Assess DSH Perfumes',
        'Re-Assess',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'green,woody,aromatic,floral,fresh spicy',
        'Re-AssessbyDSH Perfumesis a Aromatic Green fragrance for women and men.Re-Assesswas launched in 2021. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        3.71,
        7,
        NULL
      ),
(
        'Refresh-21049',
        'Refresh DSH Perfumes',
        'Refresh',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        NULL,
        NULL,
        NULL,
        'green,aromatic,fresh spicy',
        'RefreshbyDSH Perfumesis a Aromatic Green fragrance for women and men. The nose behind this fragrance is Dawn Spencer Hurwitz.',
        4.5,
        2,
        NULL
      ),
(
        'Rendezvous-35870',
        'Rendezvous DSH Perfumes',
        'Rendezvous',
        'for women and men',
        NULL,
        'Dawn Spencer Hurwitz',
        'Aldehydes and White Pepper',
        'Gardenia, Jasmine and Orange Blossom',
        'Castoreum, Ambergris, Hyrax, Labdanum, Musk, Ambrette (Musk Mallow), Civet and Oakmoss',
        'musky,amber,animalic,white floral,leather',
        'RendezvousbyDSH Perfumesis a Aromatic fragrance for women and men.Rendezvouswas launched in 2016. The nose behind this fragrance is Dawn Spencer Hurwitz. Top notes are Aldehydes and White Pepper; middle notes are Gardenia, Jasmine and Orange Blossom; base notes are Castoreum, Ambergris, Hyrax, Labdanum, Musk, Ambrette (Musk Mallow), Civet and Oakmoss.',
        4.04,
        46,
        NULL
      );
