
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Aramis-Cool-118',
        'Aramis Cool Aramis',
        'Aramis',
        'for men',
        NULL,
        NULL,
        'Cognac, Bergamot and Mandarin Orange',
        'Rum and Juniper',
        'Sandalwood, Patchouli and Musk',
        'woody,citrus,warm spicy,rum,fresh spicy',
        'Aramis CoolbyAramisis a Woody Floral Musk fragrance for men.Aramis Coolwas launched in 2005. Top notes are Cognac, Bergamot and Mandarin Orange; middle notes are Rum and Juniper; base notes are Sandalwood, Patchouli and Musk.',
        3.79,
        24,
        NULL
      ),
(
        'Aramis-Cool-Blend-7839',
        'Aramis Cool Blend Aramis',
        'Aramis',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lime and Amalfi Lemon',
        'Jasmine, Sage, Cardamom and Cinnamon',
        'Sandalwood, Leather and Amber',
        'citrus,aromatic,warm spicy,woody,white floral',
        'Aramis Cool BlendbyAramisis a Aromatic Spicy fragrance for men.Aramis Cool Blendwas launched in 2010. Top notes are Bergamot, Lime and Amalfi Lemon; middle notes are Jasmine, Sage, Cardamom and Cinnamon; base notes are Sandalwood, Leather and Amber.',
        4.21,
        38,
        NULL
      ),
(
        'Aramis-Devin-3644',
        'Aramis Devin Aramis',
        'Aramis',
        'for men',
        NULL,
        'Bernard Chant',
        'Galbanum, Aldehydes, Artemisia, Lavender, Bergamot, Orange and Lemon',
        'Pine Tree Needles, Carnation, Cinnamon, Jasmine and Caraway',
        'Leather, Oakmoss, Labdanum, Patchouli, Musk, Cedar and Amber',
        'aromatic,woody,green,warm spicy,citrus',
        'Aramis DevinbyAramisis a Chypre fragrance for men.Aramis Devinwas launched in 1977. The nose behind this fragrance is Bernard Chant. Top notes are Galbanum, Aldehydes, Artemisia, Lavender, Bergamot, Orange and Lemon; middle notes are Pine Tree Needles, Carnation, Cinnamon, Jasmine and Caraway; base notes are Leather, Oakmoss, Labdanum, Patchouli, Musk, Cedar and Amber.',
        4.1,
        912,
        NULL
      ),
(
        'Aramis-Ice-119',
        'Aramis Ice Aramis',
        'Aramis',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,amber,lavender,aldehydic',
        'Aramis IcebyAramisis a Woody fragrance for men.Aramis Icewas launched in 2003.',
        3.94,
        18,
        NULL
      ),
(
        'Aramis-Life-120',
        'Aramis Life Aramis',
        'Aramis',
        'for men',
        NULL,
        'Raymond Matts',
        'Lime and Bergamot',
        'Violet Leaf, Cucumber, Cardamom and Mint',
        'Cedar, Leather, Sandalwood and Olive Tree',
        'woody,citrus,ozonic,green,aromatic',
        'Aramis LifebyAramisis a Citrus Aromatic fragrance for men.Aramis Lifewas launched in 2003. The nose behind this fragrance is Raymond Matts. Top notes are Lime and Bergamot; middle notes are Violet Leaf, Cucumber, Cardamom and Mint; base notes are Cedar, Leather, Sandalwood and Olive Tree.',
        3.93,
        198,
        NULL
      ),
(
        'Aramis-Life-My-Summer-121',
        'Aramis Life My Summer Aramis',
        'Aramis',
        'for men',
        NULL,
        'Raymond Matts',
        'Lime, Cucumber, Bergamot and Kumquat',
        'Saffron, Mint, Iris, Violet Leaf, Olive Tree and Cardamom',
        'Hazelnut, Leather, Cedar and Sandalwood',
        'woody,citrus,warm spicy,green,aromatic',
        'Aramis Life My SummerbyAramisis a Aromatic Spicy fragrance for men.Aramis Life My Summerwas launched in 2003. The nose behind this fragrance is Raymond Matts. Top notes are Lime, Cucumber, Bergamot and Kumquat; middle notes are Saffron, Mint, Iris, Violet Leaf, Olive Tree and Cardamom; base notes are Hazelnut, Leather, Cedar and Sandalwood.',
        4.04,
        26,
        NULL
      ),
(
        'Aramis-Modern-Leather-46397',
        'Aramis Modern Leather Aramis',
        'Aramis',
        'for men',
        NULL,
        NULL,
        'Basil and Thyme',
        'Geranium and Patchouli',
        'Leather and Oakmoss',
        'fresh spicy,aromatic,leather,mossy,herbal',
        'Aramis Modern LeatherbyAramisis a Leather fragrance for men.Aramis Modern Leatherwas launched in 2017. Top notes are Basil and Thyme; middle notes are Geranium and Patchouli; base notes are Leather and Oakmoss.',
        4.1,
        136,
        NULL
      ),
(
        'Aramis-Special-Blend-59125',
        'Aramis Special Blend Aramis',
        'Aramis',
        'for men',
        NULL,
        NULL,
        'Cinnamon, Clary Sage and Bergamot',
        'Whiskey and Cypriol Oil or Nagarmotha',
        'Virginian Cedar, Ambertonic, Cashmeran and Tonka Bean',
        'woody,whiskey,amber,warm spicy,cinnamon',
        'Aramis Special BlendbyAramisis a Woody Spicy fragrance for men.Aramis Special Blendwas launched in 2019. Top notes are Cinnamon, Clary Sage and Bergamot; middle notes are Whiskey and Cypriol Oil or Nagarmotha; base notes are Virginian Cedar, Ambertonic, Cashmeran and Tonka Bean.',
        4.2,
        93,
        NULL
      ),
(
        'Aramis-Vintage-Edition-34202',
        'Aramis Vintage Edition Aramis',
        'Aramis',
        'for men',
        NULL,
        NULL,
        'Gardenia, Myrrh, Aldehydes, Clover, Artemisia, Bergamot and Caraway',
        'Jasmine, Orris Root, Cardamom, Patchouli and Sage',
        'Coconut, Leather, Amber, Sandalwood, Musk, Vetiver and Oakmoss',
        'white floral,amber,aromatic,warm spicy,coconut',
        'Aramis Vintage EditionbyAramisis a fragrance for men.Aramis Vintage Editionwas launched during the 2000''s. Top notes are Gardenia, Myrrh, Aldehydes, Clover, Artemisia, Bergamot and Caraway; middle notes are Jasmine, Orris Root, Cardamom, Patchouli and Sage; base notes are Coconut, Leather, Amber, Sandalwood, Musk, Vetiver and Oakmoss.',
        4,
        1,
        NULL
      ),
(
        'Gentleman-16461',
        'Gentleman Aramis',
        'Gentleman',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,fresh spicy,fresh',
        'GentlemanbyAramisis a Aromatic Spicy fragrance for men.Gentlemanwas launched in 2012.',
        3.92,
        99,
        NULL
      ),
(
        'Gold-33984',
        'Gold Aramis',
        'Gold',
        'for men',
        NULL,
        'Bernard Chant',
        'Bergamot, Green Notes and Herbal Notes',
        'Cardamom, Sandalwood, Vetiver, Cloves and Patchouli',
        'Leather and Oakmoss',
        'woody,warm spicy,leather,earthy,aromatic',
        'GoldbyAramisis a Aromatic Green fragrance for men.Goldwas launched in 1966. The nose behind this fragrance is Bernard Chant. Top notes are Bergamot, Green Notes and Herbal Notes; middle notes are Cardamom, Sandalwood, Vetiver, Cloves and Patchouli; base notes are Leather and Oakmoss.',
        4.2,
        15,
        NULL
      ),
(
        'Havana-599',
        'Havana Aramis',
        'Havana',
        'for men',
        NULL,
        'Nathalie Feisthauer',
        'Mandarin Orange, Basil, Artemisia and Caraway',
        'Tobacco, Cinnamon, Fir and Carnation',
        'Oakmoss, Patchouli, Vetiver and Sandalwood',
        'woody,aromatic,warm spicy,fresh spicy,tobacco',
        'HavanabyAramisis a Amber Spicy fragrance for men.Havanawas launched in 1994. Havana was created by Nathalie Feisthauer and Xavier Renard. Top notes are Mandarin Orange, Basil, Artemisia and Caraway; middle notes are Tobacco, Cinnamon, Fir and Carnation; base notes are Oakmoss, Patchouli, Vetiver and Sandalwood.',
        4.22,
        1,
        NULL
      ),
(
        'Havana-Pour-Elle-558',
        'Havana Pour Elle Aramis',
        'Havana',
        'for women',
        NULL,
        'Carlos Benaim',
        'Melon, Peach, Mandarin Orange and Apple',
        'Heliotrope, Ylang-Ylang, Freesia and Rose',
        'Cedar, Honey, Tonka Bean and Vanilla',
        'vanilla,sweet,powdery,floral,fruity',
        'Havana Pour EllebyAramisis a Amber Floral fragrance for women.Havana Pour Ellewas launched in 1995. The nose behind this fragrance is Carlos Benaim. Top notes are Melon, Peach, Mandarin Orange and Apple; middle notes are Heliotrope, Ylang-Ylang, Freesia and Rose; base notes are Cedar, Honey, Tonka Bean and Vanilla.',
        4.06,
        278,
        NULL
      ),
(
        'Havana-Reserva-3788',
        'Havana Reserva Aramis',
        'Havana',
        'for men',
        NULL,
        'Edouard Fléchier',
        'Coriander, Citruses and Tangerine',
        'Spices, Cedar, Vanilla and Jasmine',
        'Tobacco, Leather, Sandalwood and Woodsy Notes',
        'woody,tobacco,leather,warm spicy,sweet',
        'Havana ReservabyAramisis a Woody Spicy fragrance for men.Havana Reservawas launched in 1996. The nose behind this fragrance is Edouard Flechier. Top notes are Coriander, Citruses and Tangerine; middle notes are Spices, Cedar, Vanilla and Jasmine; base notes are Tobacco, Leather, Sandalwood and Woodsy Notes.',
        4.5,
        201,
        NULL
      ),
(
        'Impeccable-10009',
        'Impeccable Aramis',
        'Impeccable',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,woody,aromatic,citrus,fresh',
        'ImpeccablebyAramisis a Woody Spicy fragrance for men.Impeccablewas launched in 2010.',
        4.13,
        77,
        NULL
      ),
(
        'JHL-6491',
        'JHL Aramis',
        'JHL',
        'for men',
        NULL,
        'Bernard Chant',
        'Aldehydes, Orange, Fruity Notes, Bergamot and Lemon',
        'Cinnamon, Carnation, Rose, Ylang-Ylang, Fir and Jasmine',
        'Benzoin, Sandalwood, Amber, Patchouli, Labdanum, Musk and Vanilla',
        'warm spicy,amber,woody,floral,cinnamon',
        'JHLbyAramisis a Amber fragrance for men.JHLwas launched in 1982. The nose behind this fragrance is Bernard Chant. Top notes are Aldehydes, Orange, Fruity Notes, Bergamot and Lemon; middle notes are Cinnamon, Carnation, Rose, Ylang-Ylang, Fir and Jasmine; base notes are Benzoin, Sandalwood, Amber, Patchouli, Labdanum, Musk and Vanilla.',
        4.41,
        275,
        NULL
      ),
(
        'New-West-Desert-Sensual-Nectar-59554',
        'New West Desert Sensual Nectar Aramis',
        'New',
        'for women',
        NULL,
        'Yves Tanguy',
        'Basil, Bergamot, Oregano and Thyme',
        'Calone, Hyacinth, Jasmine, Plum and Rose',
        'Pimento, Sandalwood, Oakmoss, Patchouli and Clove',
        'fresh spicy,warm spicy,fresh,aromatic,woody',
        'New West Desert Sensual NectarbyAramisis a Floral Aquatic fragrance for women.New West Desert Sensual Nectarwas launched in 1990. The nose behind this fragrance is Yves Tanguy. Top notes are Basil, Bergamot, Oregano and Thyme; middle notes are Calone, Hyacinth, Jasmine, Plum and Rose; base notes are Pimento, Sandalwood, Oakmoss, Patchouli and Clove.',
        4.73,
        15,
        NULL
      ),
(
        'New-West-for-Her-4857',
        'New West for Her Aramis',
        'New',
        'for women',
        NULL,
        'Yves Tanguy',
        'Watermelon, Peach, Bergamot, Plum and Violet',
        'Pine Tree Needles, Mint, Galbanum, Carnation, Cyclamen, Hiacynth, Lily, Jasmine and Rose',
        'Oakmoss, Leather, Cedar, Musk and Amber',
        'ozonic,aquatic,green,fruity,aromatic',
        'New West for HerbyAramisis a Floral Green fragrance for women.New West for Herwas launched in 1990. The nose behind this fragrance is Yves Tanguy. Top notes are Watermelon, Peach, Bergamot, Plum and Violet; middle notes are Pine Tree Needles, Mint, Galbanum, Carnation, Cyclamen, Hiacynth, Lily, Jasmine and Rose; base notes are Oakmoss, Leather, Cedar, Musk and Amber.',
        4.29,
        358,
        NULL
      ),
(
        'New-West-for-Him-4858',
        'New West for Him Aramis',
        'New',
        'for men',
        NULL,
        'Harry Fremont',
        'Sea Notes, Mint, Aldehydes, Bergamot, Lavender, Artemisia and Caraway',
        'Pine Tree, Juniper Berries, Bay Leaf, Watermelon, Geranium, Coriander and Jasmine',
        'Cedar, Oakmoss, Leather, Sandalwood, Patchouli, Musk and Amber',
        'aromatic,woody,fresh spicy,green',
        'New West for HimbyAramisis a Aromatic fragrance for men.New West for Himwas launched in 1988. The nose behind this fragrance is Harry Fremont. Top notes are Sea Notes, Mint, Aldehydes, Bergamot, Lavender, Artemisia and Caraway; middle notes are Pine Tree, Juniper Berries, Bay Leaf, Watermelon, Geranium, Coriander and Jasmine; base notes are Cedar, Oakmoss, Leather, Sandalwood, Patchouli, Musk and Amber.',
        4.17,
        546,
        NULL
      ),
(
        'Surface-5523',
        'Surface Aramis',
        'Surface',
        'for men',
        NULL,
        'Ilias Ermenidis',
        NULL,
        NULL,
        NULL,
        'green,aromatic,ozonic,fresh spicy,aquatic',
        'SurfacebyAramisis a Aromatic Fougere fragrance for men.Surfacewas launched in 2001. Surface was created by Ilias Ermenidis and Jean Claude Delville.',
        4.59,
        22,
        NULL
      ),
(
        'Tobacco-Reserve-50564',
        'Tobacco Reserve Aramis',
        'Tobacco',
        'for men',
        NULL,
        'Edouard Fléchier',
        'Clary Sage and Black Currant',
        'Tobacco Leaf, Nutmeg and Orris',
        'Tonka Bean and Oakmoss',
        'tobacco,sweet,aromatic,vanilla,earthy',
        'Tobacco ReservebyAramisis a Woody Aromatic fragrance for men.Tobacco Reservewas launched in 2018. The nose behind this fragrance is Edouard Fléchier. Top notes are Clary Sage and Black Currant; middle notes are Tobacco Leaf, Nutmeg and Orris; base notes are Tonka Bean and Oakmoss.',
        4.44,
        621,
        NULL
      ),
(
        'Tuscany-Forte-Per-Uomo-16822',
        'Tuscany Forte Per Uomo Aramis',
        'Tuscany',
        'for men',
        NULL,
        'Harry Fremont',
        'Palisander Rosewood, Lavender, Tarragon, Lemon and Bergamot',
        'Iris, Nutmeg, Star Anise, Carnation, Rose and Geranium',
        'Sandalwood, Oakmoss, Cedar, Musk, Tonka Bean and Amber',
        'woody,aromatic,powdery,fresh spicy,amber',
        'Tuscany Forte Per UomobyAramisis a Aromatic Fougere fragrance for men.Tuscany Forte Per Uomowas launched in 1996. The nose behind this fragrance is Harry Fremont. Top notes are Palisander Rosewood, Lavender, Tarragon, Lemon and Bergamot; middle notes are Iris, Nutmeg, Star Anise, Carnation, Rose and Geranium; base notes are Sandalwood, Oakmoss, Cedar, Musk, Tonka Bean and Amber.',
        4.51,
        43,
        NULL
      ),
(
        'Tuscany-Per-Donna-122',
        'Tuscany Per Donna Aramis',
        'Tuscany',
        'for women',
        NULL,
        'Kenneth Ruocco',
        'Plum, Peach, Hiacynth, Green Grass, Mandarin Orange, Grapefruit and Bergamot',
        'Carnation, Ylang-Ylang, Orange Blossom, Jasmine, Rose, Violet, Honeysuckle and Lily-of-the-Valley',
        'Sandalwood, Styrax, Amber, Vanilla, Musk and Cedar',
        'woody,white floral,fruity,floral,powdery',
        'Tuscany Per DonnabyAramisis a Amber Floral fragrance for women.Tuscany Per Donnawas launched in 1992. The nose behind this fragrance is Kenneth Ruocco. Top notes are Plum, Peach, Hiacynth, Green Grass, Mandarin Orange, Grapefruit and Bergamot; middle notes are Carnation, Ylang-Ylang, Orange Blossom, Jasmine, Rose, Violet, Honeysuckle and Lily-of-the-Valley; base notes are Sandalwood, Styrax, Amber, Vanilla, Musk and Cedar.',
        4.28,
        507,
        NULL
      ),
(
        'Tuscany-Per-Uomo-123',
        'Tuscany Per Uomo Aramis',
        'Tuscany',
        'for men',
        NULL,
        NULL,
        'Lemon, Lavender, Bergamot and Lime',
        'Anise, Caraway, Orange Blossom and Tarragon',
        'Leather, Oakmoss, Basil, Patchouli, Sandalwood, Cinnamon and Tonka Bean',
        'citrus,aromatic,fresh spicy,anis,woody',
        'Tuscany Per UomobyAramisis a Aromatic Fougere fragrance for men.Tuscany Per Uomowas launched in 1984. Top notes are Lemon, Lavender, Bergamot and Lime; middle notes are Anise, Caraway, Orange Blossom and Tarragon; base notes are Leather, Oakmoss, Basil, Patchouli, Sandalwood, Cinnamon and Tonka Bean.',
        4.31,
        1,
        NULL
      ),
(
        'Voyager-39608',
        'Voyager Aramis',
        'Voyager',
        'for men',
        NULL,
        NULL,
        'Ginger, Black Pepper and Juniper Berries',
        'Lavender, Nutmeg and Sage',
        'Tonka Bean',
        'fresh spicy,aromatic,warm spicy,lavender,vanilla',
        'VoyagerbyAramisis a Aromatic Spicy fragrance for men.Voyagerwas launched in 2016. Top notes are Ginger, Black Pepper and Juniper Berries; middle notes are Lavender, Nutmeg and Sage; base note is Tonka Bean.',
        3.84,
        49,
        NULL
      ),
(
        'Perfume-Calligraphy-15123',
        'Perfume Calligraphy Aramis',
        'Perfume',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Lemon and Cinnamon',
        'Rose, Saffron and Myrrh',
        'Agarwood (Oud), Amber, Patchouli and Musk',
        'warm spicy,amber,oud,rose,aromatic',
        'Perfume CalligraphybyAramisis a Amber Floral fragrance for women and men.Perfume Calligraphywas launched in 2012. Top notes are Cardamom, Lemon and Cinnamon; middle notes are Rose, Saffron and Myrrh; base notes are Agarwood (Oud), Amber, Patchouli and Musk.',
        4.24,
        311,
        NULL
      ),
(
        'Perfume-Calligraphy-Rose-18132',
        'Perfume Calligraphy Rose Aramis',
        'Perfume',
        'for women and men',
        NULL,
        'Trudi Loren',
        'Saffron, Oregano and Honeysuckle',
        'Turkish Rose, Myrrh, Styrax and Lavender',
        'Olibanum, Labdanum, Ambergris and Musk',
        'amber,rose,warm spicy,balsamic',
        'Perfume Calligraphy RosebyAramisis a Amber fragrance for women and men.Perfume Calligraphy Rosewas launched in 2013. The nose behind this fragrance is Trudi Loren. Top notes are Saffron, Oregano and Honeysuckle; middle notes are Turkish Rose, Myrrh, Styrax and Lavender; base notes are Olibanum, Labdanum, Ambergris and Musk.',
        4.19,
        1,
        NULL
      ),
(
        'Perfume-Calligraphy-Saffron-22961',
        'Perfume Calligraphy Saffron Aramis',
        'Perfume',
        'for women and men',
        NULL,
        NULL,
        'Marigold and Bergamot',
        'Saffron, Turkish Rose and Lavender',
        'Styrax, Tonka Bean and Vetiver',
        'warm spicy,aromatic,amber,balsamic,rose',
        'Perfume Calligraphy SaffronbyAramisis a Amber Spicy fragrance for women and men.Perfume Calligraphy Saffronwas launched in 2014. Top notes are Marigold and Bergamot; middle notes are Saffron, Turkish Rose and Lavender; base notes are Styrax, Tonka Bean and Vetiver.',
        4.25,
        428,
        NULL
      ),
(
        'Aura-82689',
        'Aura Arcadia',
        'Aura',
        'for women and men',
        NULL,
        NULL,
        'Guava and Pear',
        'Cherry Blossom and White Rose',
        'Amber and Musk',
        'fruity,floral,fresh,amber,musky',
        'AurabyArcadiais a Floral Fruity fragrance for women and men. This is a new fragrance.Aurawas launched in 2022. Top notes are Guava and Pear; middle notes are Cherry Blossom and White Rose; base notes are Amber and Musk.',
        5,
        1,
        NULL
      ),
(
        'Thunderous-82690',
        'Thunderous Arcadia',
        'Thunderous',
        'for women and men',
        NULL,
        NULL,
        'Violet Leaves, Cardamom and Grapefruit',
        'Lavender and Black Pepper',
        'Oakmoss, Sandalwood and Amber',
        'mossy,lavender,woody,aromatic,warm spicy',
        'ThunderousbyArcadiais a Aromatic Green fragrance for women and men. This is a new fragrance.Thunderouswas launched in 2022. Top notes are Violet Leaves, Cardamom and Grapefruit; middle notes are Lavender and Black Pepper; base notes are Oakmoss, Sandalwood and Amber.',
        4.17,
        6,
        NULL
      ),
(
        'No-1-Royal-Orchard-82602',
        'No.1 Royal Orchard Arcadia',
        'No.1',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Pineapple and Apple',
        'Patchouli, Rose, Jasmine and Nutmeg',
        'Musk, Oakmoss, Vanilla and Amber',
        'fruity,fresh spicy,powdery,earthy,sweet',
        'No.1 Royal OrchardbyArcadiais a Aromatic Fruity fragrance for women and men.No.1 Royal Orchardwas launched in 2017. Top notes are Bergamot, Pineapple and Apple; middle notes are Patchouli, Rose, Jasmine and Nutmeg; base notes are Musk, Oakmoss, Vanilla and Amber.',
        4.33,
        3,
        NULL
      ),
(
        'No-2-Splinter-82603',
        'No.2 Splinter Arcadia',
        'No.2',
        'for women and men',
        NULL,
        NULL,
        'Saffron',
        'Rose, Truffle and Floral bouquet',
        'Patchouli, Vanilla, Agarwood and Moss',
        'earthy,patchouli,warm spicy,woody,rose',
        'No.2 SplinterbyArcadiais a Woody Spicy fragrance for women and men.No.2 Splinterwas launched in 2017. Top note is Saffron; middle notes are Rose, Truffle and Floral bouquet; base notes are Patchouli, Vanilla, Agarwood and Moss.',
        3.3,
        10,
        NULL
      ),
(
        'No-3-Fumee-82604',
        'No.3 Fumee Arcadia',
        'No.3',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Grapefruit and Raspberry',
        'Rose, Violet and Saffron',
        'Amber, Myrrh, Musk, Orris Root and Vanilla',
        'powdery,citrus,amber,sweet,warm spicy',
        'No.3 FumeebyArcadiais a Amber Spicy fragrance for women and men.No.3 Fumeewas launched in 2017. Top notes are Bergamot, Grapefruit and Raspberry; middle notes are Rose, Violet and Saffron; base notes are Amber, Myrrh, Musk, Orris Root and Vanilla.',
        5,
        1,
        NULL
      ),
(
        'No-4-Hassaku-High-82605',
        'No.4 Hassaku High Arcadia',
        'No.4',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Mandarin Orange and Lilac',
        'White Flowers, Jasmine, Tuberose, Narcissus, Gardenia, Lily of the Valley, Iris, Orange Blossom and Violet',
        'Sandalwood, Vetiver and Musk',
        'white floral,citrus,powdery,woody,floral',
        'No.4 Hassaku HighbyArcadiais a Woody Floral Musk fragrance for women and men.No.4 Hassaku Highwas launched in 2017. Top notes are Bergamot, Mandarin Orange and Lilac; middle notes are White Flowers, Jasmine, Tuberose, Narcissus, Gardenia, Lily of the Valley, Iris, Orange Blossom and Violet; base notes are Sandalwood, Vetiver and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'No-5-Periwinkle-82610',
        'No.5 Periwinkle Arcadia',
        'No.5',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Rosemary',
        'Lavender, Pine Tree Needles, Jasmine and Rose',
        'Amber, Musk and Tonka Bean',
        'aromatic,woody,fresh spicy,amber,citrus',
        'No.5 PeriwinklebyArcadiais a Woody Aromatic fragrance for women and men.No.5 Periwinklewas launched in 2017. Top notes are Bergamot and Rosemary; middle notes are Lavender, Pine Tree Needles, Jasmine and Rose; base notes are Amber, Musk and Tonka Bean.',
        5,
        1,
        NULL
      ),
(
        'No-6-Milk-Musk-82606',
        'No.6 Milk Musk Arcadia',
        'No.6',
        'for women and men',
        NULL,
        NULL,
        'Orange, Blackberry and Amazon Lily',
        'Tiare Flower, Osmanthus and Patchouli',
        'Musk, Vanilla, Cashmere Wood, Sandalwood and Amber',
        'white floral,fruity,musky,powdery,sweet',
        'No.6 Milk MuskbyArcadiais a Floral Fruity Gourmand fragrance for women and men.No.6 Milk Muskwas launched in 2017. Top notes are Orange, Blackberry and Amazon Lily; middle notes are Tiare Flower, Osmanthus and Patchouli; base notes are Musk, Vanilla, Cashmere Wood, Sandalwood and Amber.',
        3.87,
        60,
        NULL
      ),
(
        'No-7-Rose-Pellets-82607',
        'No.7 Rose Pellets Arcadia',
        'No.7',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Rose, Geranium, Jasmine, Gardenia and Orange Blossom',
        'Sandalwood, Patchouli, Amber and Musk',
        'white floral,woody,citrus,rose,warm spicy',
        'No.7 Rose PelletsbyArcadiais a Amber Floral fragrance for women and men.No.7 Rose Pelletswas launched in 2017. Top note is Mandarin Orange; middle notes are Rose, Geranium, Jasmine, Gardenia and Orange Blossom; base notes are Sandalwood, Patchouli, Amber and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'No-8-Cerulean-Crystal-82608',
        'No.8 Cerulean Crystal Arcadia',
        'No.8',
        'for women and men',
        NULL,
        NULL,
        'Citruses, Quince, Black Currant, Pineapple, Honeydew Blossom, Lotus and Water Lily',
        'May Rose, Jasmine and Lily of the Valley',
        'Iris, Vetiver and Sandalwood',
        'floral,fruity,fresh,woody,white floral',
        'No.8 Cerulean CrystalbyArcadiais a Floral Fruity fragrance for women and men.No.8 Cerulean Crystalwas launched in 2017. Top notes are Citruses, Quince, Black Currant, Pineapple, Honeydew Blossom, Lotus and Water Lily; middle notes are May Rose, Jasmine and Lily of the Valley; base notes are Iris, Vetiver and Sandalwood.',
        3.67,
        12,
        NULL
      ),
(
        'No-9-Vanilla-Pod-82609',
        'No.9 Vanilla Pod Arcadia',
        'No.9',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange and Water Notes',
        'Saffron, Orris Root, Violet, Jasmine, Black Pepper, Rose and Cloves',
        'Leather, Balsamic Notes, Vanilla, Patchouli, Vetiver, Labdanum, Cedar, Amber and Sandalwood',
        'woody,leather,powdery,warm spicy,earthy',
        'No.9 Vanilla PodbyArcadiais a Amber Spicy fragrance for women and men.No.9 Vanilla Podwas launched in 2017. Top notes are Mandarin Orange and Water Notes; middle notes are Saffron, Orris Root, Violet, Jasmine, Black Pepper, Rose and Cloves; base notes are Leather, Balsamic Notes, Vanilla, Patchouli, Vetiver, Labdanum, Cedar, Amber and Sandalwood.',
        3.08,
        12,
        NULL
      ),
(
        'Devotion-82678',
        'Devotion Arcadia',
        'Devotion',
        'for women and men',
        NULL,
        NULL,
        'Amber',
        'Moss',
        'Woody Notes and Oud',
        'amber,woody,mossy,earthy,animalic',
        'DevotionbyArcadiais a Amber Woody fragrance for women and men. This is a new fragrance.Devotionwas launched in 2022. Top note is Amber; middle note is Moss; base notes are Woody Notes and Oud.',
        4.5,
        2,
        NULL
      ),
(
        'Eternal-82683',
        'Eternal Arcadia',
        'Eternal',
        'for women and men',
        NULL,
        NULL,
        'White Flowers and Pear',
        'Amber',
        'Ambergris, Oakmoss, Musk and Woody Notes',
        'amber,white floral,animalic,woody,mossy',
        'EternalbyArcadiais a Amber Floral fragrance for women and men. This is a new fragrance.Eternalwas launched in 2022. Top notes are White Flowers and Pear; middle note is Amber; base notes are Ambergris, Oakmoss, Musk and Woody Notes.',
        3,
        7,
        NULL
      ),
(
        'Sincere-82681',
        'Sincere Arcadia',
        'Sincere',
        'for women and men',
        NULL,
        NULL,
        'Musk and Guaiac Wood',
        'Cedar and Olibanum',
        'Woody Notes',
        'woody,amber,musky,powdery',
        'SincerebyArcadiais a Woody fragrance for women and men. This is a new fragrance.Sincerewas launched in 2022. Top notes are Musk and Guaiac Wood; middle notes are Cedar and Olibanum; base note is Woody Notes.',
        4.33,
        3,
        NULL
      ),
(
        'No-11-Jinx-82613',
        'No.11 Jinx Arcadia',
        'No.11',
        'for women and men',
        NULL,
        NULL,
        'Smoke, Rum, Woody Notes, Cedar Leaves, Sage and Myrtle',
        'Violet Leaves, Hedione and May Rose',
        'Incense, Tonka Bean, Amber, Musk, Cypriol Oil or Nagarmotha and Cambodian Oud',
        'amber,smoky,woody,ozonic,aromatic',
        'No.11 JinxbyArcadiais a Woody Spicy fragrance for women and men.No.11 Jinxwas launched in 2018. Top notes are Smoke, Rum, Woody Notes, Cedar Leaves, Sage and Myrtle; middle notes are Violet Leaves, Hedione and May Rose; base notes are Incense, Tonka Bean, Amber, Musk, Cypriol Oil or Nagarmotha and Cambodian Oud.',
        3.93,
        14,
        NULL
      ),
(
        'No-12-Pseudo-82614',
        'No.12 Pseudo Arcadia',
        'No.12',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Lemon and Orange',
        'Jasmine, Rose, Caramel and Coriander',
        'Amber, Patchouli, Vetiver and Tobacco',
        'citrus,aromatic,woody,sweet,tobacco',
        'No.12 PseudobyArcadiais a Chypre Floral fragrance for women and men.No.12 Pseudowas launched in 2018. Top notes are Bergamot, Lemon and Orange; middle notes are Jasmine, Rose, Caramel and Coriander; base notes are Amber, Patchouli, Vetiver and Tobacco.',
        4,
        1,
        NULL
      ),
(
        'No-13-Fever-82615',
        'No.13 Fever Arcadia',
        'No.13',
        'for women and men',
        NULL,
        NULL,
        'Juniper, Pepper, Bergamot and Lemon',
        'Pine Tree Needles, Incense and Orris',
        'Vanilla, Sandalwood and Amber',
        'fresh spicy,aromatic,woody,vanilla,powdery',
        'No.13 FeverbyArcadiais a Amber Spicy fragrance for women and men.No.13 Feverwas launched in 2018. Top notes are Juniper, Pepper, Bergamot and Lemon; middle notes are Pine Tree Needles, Incense and Orris; base notes are Vanilla, Sandalwood and Amber.',
        3.26,
        38,
        NULL
      ),
(
        'No-14-Obsidian-82616',
        'No.14 Obsidian Arcadia',
        'No.14',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes and Rose',
        'Ylang Ylang, Ambergris, Leather and Nutmeg',
        'Patchouli, Cedarwood, Vetiver, Vanilla and Musk',
        'woody,sweet,animalic,powdery,yellow floral',
        'No.14 ObsidianbyArcadiais a Amber Floral fragrance for women and men.No.14 Obsidianwas launched in 2018. Top notes are Fruity Notes and Rose; middle notes are Ylang Ylang, Ambergris, Leather and Nutmeg; base notes are Patchouli, Cedarwood, Vetiver, Vanilla and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'No-15-Hysteria-82617',
        'No.15 Hysteria Arcadia',
        'No.15',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Peach, Coconut, Black Currant and Pink Pepper',
        'Rose, Jasmine and Floral bouquet',
        'Musk, Amber, Vanilla, Sugar and Benzoin',
        'sweet,vanilla,amber,fruity,floral',
        'No.15 HysteriabyArcadiais a Floral Fruity Gourmand fragrance for women and men.No.15 Hysteriawas launched in 2018. Top notes are Mandarin Orange, Peach, Coconut, Black Currant and Pink Pepper; middle notes are Rose, Jasmine and Floral bouquet; base notes are Musk, Amber, Vanilla, Sugar and Benzoin.',
        NULL,
        NULL,
        NULL
      ),
(
        'No-16-Faded-82618',
        'No.16 Faded Arcadia',
        'No.16',
        'for women and men',
        NULL,
        NULL,
        'Coriander, Cardamom, Cinnamon and Brazilian Rosewood',
        'Sage, Leather, Rose and Hedione',
        'Patchouli, Incense, Cypriol Oil or Nagarmotha, Tobacco, Amber and Musk',
        'aromatic,warm spicy,woody,herbal,soft spicy',
        'No.16 FadedbyArcadiais a Woody Spicy fragrance for women and men.No.16 Fadedwas launched in 2018. Top notes are Coriander, Cardamom, Cinnamon and Brazilian Rosewood; middle notes are Sage, Leather, Rose and Hedione; base notes are Patchouli, Incense, Cypriol Oil or Nagarmotha, Tobacco, Amber and Musk.',
        4.33,
        3,
        NULL
      ),
(
        'No-17-Enigma-82619',
        'No.17 Enigma Arcadia',
        'No.17',
        'for women and men',
        NULL,
        NULL,
        'Black Pepper, Bergamot, Lavender, Absinthe and Cardamom',
        'Thyme, Orris, Frankincense and Rose',
        'Amber, Vetiver, Woody Notes, Moss, Vanilla and Musk',
        'fresh spicy,aromatic,amber,warm spicy',
        'No.17 EnigmabyArcadiais a Amber Fougere fragrance for women and men.No.17 Enigmawas launched in 2018. Top notes are Black Pepper, Bergamot, Lavender, Absinthe and Cardamom; middle notes are Thyme, Orris, Frankincense and Rose; base notes are Amber, Vetiver, Woody Notes, Moss, Vanilla and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'No-18-Bete-Noir-82620',
        'No.18 Bête Noir Arcadia',
        'No.18',
        'for women and men',
        NULL,
        NULL,
        'Hyacinth and Pineapple',
        'Iris, Jasmine and Pink Pepper',
        'Musk, Vetiver, Patchouli, Amber and Vanilla',
        'musky,powdery,earthy,sweet,woody',
        'No.18 Bête NoirbyArcadiais a Floral Green fragrance for women and men.No.18 Bête Noirwas launched in 2018. Top notes are Hyacinth and Pineapple; middle notes are Iris, Jasmine and Pink Pepper; base notes are Musk, Vetiver, Patchouli, Amber and Vanilla.',
        3,
        4,
        NULL
      ),
(
        'Infinity-82687',
        'Infinity Arcadia',
        'Infinity',
        'for women and men',
        NULL,
        NULL,
        'Pineapple, Pink Pepper and Rum',
        'Papyrus, Rose, Cedar, Lily of the Valley and Cinnamon',
        'Oud, Raspberry, Ambrocenide, Ambergris and Sandalwood',
        'woody,fruity,sweet,amber,oud',
        'InfinitybyArcadiais a Woody Spicy fragrance for women and men.Infinitywas launched in 2017. Top notes are Pineapple, Pink Pepper and Rum; middle notes are Papyrus, Rose, Cedar, Lily of the Valley and Cinnamon; base notes are Oud, Raspberry, Ambrocenide, Ambergris and Sandalwood.',
        2.4,
        5,
        NULL
      ),
(
        'Unity-82688',
        'Unity Arcadia',
        'Unity',
        'for women and men',
        NULL,
        NULL,
        'Apple and Olibanum',
        'Rose, Violet and Orris Root',
        'Sandalwood and Musk',
        'powdery,woody,rose,violet,amber',
        'UnitybyArcadiais a Floral Fruity fragrance for women and men.Unitywas launched in 2020. Top notes are Apple and Olibanum; middle notes are Rose, Violet and Orris Root; base notes are Sandalwood and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Auric-82686',
        'Auric Arcadia',
        'Auric',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes',
        'Musk and Pear',
        'Spicy Notes, Fruity Notes and Amber',
        'musky,powdery,floral,sweet,warm spicy',
        'AuricbyArcadiais a Floral Fruity fragrance for women and men.Auricwas launched in 2021. Top note is Floral Notes; middle notes are Musk and Pear; base notes are Spicy Notes, Fruity Notes and Amber.',
        3.85,
        20,
        NULL
      ),
(
        'Apples-Crave-Apples-58402',
        'Apples Crave Apples Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,green,sweet',
        'Apples Crave ApplesbyArcana Cravesis a Amber fragrance for women.Apples Crave Appleswas launched in 2015.',
        3.75,
        4,
        NULL
      ),
(
        'Apples-Crave-Cake-58399',
        'Apples Crave Cake Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,fresh',
        'Apples Crave CakebyArcana Cravesis a Amber fragrance for women.Apples Crave Cakewas launched in 2014.',
        3.78,
        9,
        NULL
      ),
(
        'Apples-Crave-Cider-57149',
        'Apples Crave Cider Arcana Craves',
        'Apples',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,fruity,fresh,green,honey',
        'Apples Crave CiderbyArcana Cravesis a Floral Fruity fragrance for women and men.',
        4.4,
        5,
        NULL
      ),
(
        'Apples-Crave-Flora-58403',
        'Apples Crave Flora Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,fruity,tuberose,citrus,green',
        'Apples Crave FlorabyArcana Cravesis a Floral fragrance for women.Apples Crave Florawas launched in 2014.',
        5,
        1,
        NULL
      ),
(
        'Apples-Crave-Frills-60314',
        'Apples Crave Frills Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,fruity,sweet,warm spicy,fresh',
        'Apples Crave FrillsbyArcana Cravesis a Floral fragrance for women.Apples Crave Frillswas launched in 2014.',
        4.5,
        2,
        NULL
      ),
(
        'Apples-Crave-Orchards-58410',
        'Apples Crave Orchards Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aquatic,woody,fruity,green,ozonic',
        'Apples Crave OrchardsbyArcana Cravesis a Amber fragrance for women.Apples Crave Orchardswas launched in 2014.',
        NULL,
        NULL,
        NULL
      ),
(
        'Apples-Crave-Peaches-58404',
        'Apples Crave Peaches Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,vanilla',
        'Apples Crave PeachesbyArcana Cravesis a Floral Fruity fragrance for women.Apples Crave Peacheswas launched in 2014.',
        4,
        1,
        NULL
      ),
(
        'Apples-Crave-Porches-60340',
        'Apples Crave Porches Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,floral,fresh,sweet,green',
        'Apples Crave PorchesbyArcana Cravesis a Floral Fruity fragrance for women.Apples Crave Porcheswas launched in 2016.',
        5,
        1,
        NULL
      ),
(
        'Apples-Crave-Red-Musk-60315',
        'Apples Crave Red Musk Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,musky,sweet,powdery,fresh',
        'Apples Crave Red MuskbyArcana Cravesis a Amber fragrance for women.Apples Crave Red Muskwas launched in 2015.',
        4.33,
        3,
        NULL
      ),
(
        'Apples-Crave-Resins-58405',
        'Apples Crave Resins Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,balsamic,smoky,warm spicy,citrus',
        'Apples Crave ResinsbyArcana Cravesis a Amber Spicy fragrance for women.Apples Crave Resinswas launched in 2014.',
        5,
        1,
        NULL
      ),
(
        'Apples-Crave-Snow-57151',
        'Apples Crave Snow Arcana Craves',
        'Apples',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh,vanilla,fruity,sweet,aquatic',
        'Apples Crave SnowbyArcana Cravesis a Aromatic fragrance for women and men.',
        3.5,
        4,
        NULL
      ),
(
        'Apples-Crave-Tea-58401',
        'Apples Crave Tea Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,green,musky,smoky',
        'Apples Crave TeabyArcana Cravesis a Aromatic Fruity fragrance for women.Apples Crave Teawas launched in 2014.',
        5,
        1,
        NULL
      ),
(
        'Apples-Crave-Terror-57152',
        'Apples Crave Terror Arcana Craves',
        'Apples',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,warm spicy,fruity,balsamic',
        'Apples Crave TerrorbyArcana Cravesis a Amber Spicy fragrance for women and men.',
        4.5,
        2,
        NULL
      ),
(
        'Apples-Crave-The-Tropics-60316',
        'Apples Crave The Tropics Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,fruity,tuberose,citrus,coconut',
        'Apples Crave The TropicsbyArcana Cravesis a Amber fragrance for women.Apples Crave The Tropicswas launched in 2014.',
        4.5,
        2,
        NULL
      ),
(
        'Apples-Crave-Ultraviolet-58400',
        'Apples Crave Ultraviolet Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,powdery,vanilla,violet',
        'Apples Crave UltravioletbyArcana Cravesis a Amber Floral fragrance for women.Apples Crave Ultravioletwas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        'Apples-Crave-Vanilla-58408',
        'Apples Crave Vanilla Arcana Craves',
        'Apples',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,amber,musky,vanilla,powdery',
        'Apples Crave VanillabyArcana Cravesis a Amber Vanilla fragrance for women.Apples Crave Vanillawas launched in 2014.',
        5,
        1,
        NULL
      ),
(
        'Blueberries-Crave-Caramel-60408',
        'Blueberries Crave Caramel Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,vanilla,caramel',
        'Blueberries Crave CaramelbyArcana Cravesis a Amber fragrance for women.Blueberries Crave Caramelwas launched in 2018.',
        5,
        1,
        NULL
      ),
(
        'Blueberries-Crave-Cocoa-60409',
        'Blueberries Crave Cocoa Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,cacao,fruity,warm spicy,chocolate',
        'Blueberries Crave CocoabyArcana Cravesis a Amber fragrance for women.Blueberries Crave Cocoawas launched in 2018.',
        4.5,
        6,
        NULL
      ),
(
        'Blueberries-Crave-Gingerbread-60403',
        'Blueberries Crave Gingerbread Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,fruity,fresh,citrus',
        'Blueberries Crave GingerbreadbyArcana Cravesis a Amber fragrance for women.Blueberries Crave Gingerbreadwas launched in 2018.',
        5,
        3,
        NULL
      ),
(
        'Blueberries-Crave-Home-60404',
        'Blueberries Crave Home Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,vanilla,savory',
        'Blueberries Crave HomebyArcana Cravesis a Amber Vanilla fragrance for women.Blueberries Crave Homewas launched in 2018.',
        4.36,
        11,
        NULL
      ),
(
        'Blueberries-Crave-Snow-57150',
        'Blueberries Crave Snow Arcana Craves',
        'Blueberries',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,fruity,fresh',
        'Blueberries Crave SnowbyArcana Cravesis a Amber fragrance for women and men.',
        4,
        4,
        NULL
      ),
(
        'Blueberries-Crave-Sunshine-60405',
        'Blueberries Crave Sunshine Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fruity,white floral,musky',
        'Blueberries Crave SunshinebyArcana Cravesis a fragrance for women.Blueberries Crave Sunshinewas launched in 2018.',
        5,
        1,
        NULL
      ),
(
        'Blueberries-Crave-Surf-60349',
        'Blueberries Crave Surf Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,sweet,white floral,coconut,fruity',
        'Blueberries Crave SurfbyArcana Cravesis a Amber fragrance for women.Blueberries Crave Surfwas launched in 2018.',
        4,
        3,
        NULL
      ),
(
        'Blueberries-Crave-Ultraviolet-60407',
        'Blueberries Crave Ultraviolet Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,vanilla',
        'Blueberries Crave UltravioletbyArcana Cravesis a Amber fragrance for women.Blueberries Crave Ultravioletwas launched in 2018.',
        4.33,
        3,
        NULL
      ),
(
        'Blueberries-Crave-Vanilla-60406',
        'Blueberries Crave Vanilla Arcana Craves',
        'Blueberries',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,soft spicy,sweet,amber,musky',
        'Blueberries Crave VanillabyArcana Cravesis a Amber Vanilla fragrance for women.Blueberries Crave Vanillawas launched in 2018.',
        3,
        2,
        NULL
      ),
(
        'Honey-Craves-Coffee-Shops-65514',
        'Honey Craves Coffee Shops Arcana Craves',
        'Honey',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'honey,sweet,floral',
        'Honey Craves Coffee ShopsbyArcana Cravesis a Aromatic fragrance for women.Honey Craves Coffee Shopswas launched in 2020.',
        4.29,
        7,
        NULL
      ),
(
        'Honey-Craves-Festivals-65520',
        'Honey Craves Festivals Arcana Craves',
        'Honey',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,woody,earthy,balsamic,aromatic',
        'Honey Craves FestivalsbyArcana Cravesis a Aromatic Fougere fragrance for women.Honey Craves Festivalswas launched in 2020.',
        3.33,
        3,
        NULL
      ),
(
        'Honey-Craves-Ice-Cream-Parlors-65516',
        'Honey Craves Ice Cream Parlors Arcana Craves',
        'Honey',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'honey,vanilla,sweet,floral,powdery',
        'Honey Craves Ice Cream ParlorsbyArcana Cravesis a Amber Vanilla fragrance for women.Honey Craves Ice Cream Parlorswas launched in 2020.',
        4,
        5,
        NULL
      ),
(
        'Honey-Craves-Moonlit-Paths-65519',
        'Honey Craves Moonlit Paths Arcana Craves',
        'Honey',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'earthy,honey,green,mossy,beeswax',
        'Honey Craves Moonlit PathsbyArcana Cravesis a Aromatic fragrance for women.Honey Craves Moonlit Pathswas launched in 2020.',
        5,
        1,
        NULL
      ),
(
        'Honey-Craves-Paradise-65517',
        'Honey Craves Paradise Arcana Craves',
        'Honey',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,tropical,fruity,coconut,honey',
        'Honey Craves ParadisebyArcana Cravesis a Floral Fruity Gourmand fragrance for women.Honey Craves Paradisewas launched in 2020.',
        4.67,
        3,
        NULL
      ),
(
        'Honey-Craves-Theater-65515',
        'Honey Craves Theater Arcana Craves',
        'Honey',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fresh,amber,sweet,powdery',
        'Honey Craves TheaterbyArcana Cravesis a Leather fragrance for women.Honey Craves Theaterwas launched in 2020.',
        NULL,
        NULL,
        NULL
      ),
(
        'Peaches-Crave-Beaches-60344',
        'Peaches Crave Beaches Arcana Craves',
        'Peaches',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,coconut,sweet,fresh spicy,musky',
        'Peaches Crave BeachesbyArcana Cravesis a Citrus fragrance for women.Peaches Crave Beacheswas launched in 2015.',
        4.38,
        8,
        NULL
      ),
(
        'Peaches-Crave-Black-Sand-60341',
        'Peaches Crave Black Sand Arcana Craves',
        'Peaches',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,coconut,sand,aromatic,woody',
        'Peaches Crave Black SandbyArcana Cravesis a Amber fragrance for women.Peaches Crave Black Sandwas launched in 2018.',
        4,
        3,
        NULL
      ),
(
        'Peaches-Crave-Chocolate-58407',
        'Peaches Crave Chocolate Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'cacao,warm spicy,sweet,chocolate,fruity',
        'Peaches Crave ChocolatebyArcana Cravesis a Amber Vanilla fragrance for women and men.Peaches Crave Chocolatewas launched in 2018.',
        5,
        4,
        NULL
      ),
(
        'Peaches-Crave-Dolci-58470',
        'Peaches Crave Dolci Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,powdery',
        'Peaches Crave DolcibyArcana Cravesis a Amber fragrance for women and men.Peaches Crave Dolciwas launched in 2015.',
        4.29,
        7,
        NULL
      ),
(
        'Peaches-Crave-Fire-58406',
        'Peaches Crave Fire Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,green,fruity,fresh',
        'Peaches Crave FirebyArcana Cravesis a Floral Fruity fragrance for women and men.Peaches Crave Firewas launched in 2017.',
        2.5,
        2,
        NULL
      ),
(
        'Peaches-Crave-Forests-60346',
        'Peaches Crave Forests Arcana Craves',
        'Peaches',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy,patchouli,smoky',
        'Peaches Crave ForestsbyArcana Cravesis a Amber Woody fragrance for women.Peaches Crave Forestswas launched in 2015.',
        3,
        3,
        NULL
      ),
(
        'Peaches-Crave-Gingerbread-60343',
        'Peaches Crave Gingerbread Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,warm spicy,fruity,almond,caramel',
        'Peaches Crave GingerbreadbyArcana Cravesis a Amber Vanilla fragrance for women and men.Peaches Crave Gingerbreadwas launched in 2015.',
        4.5,
        2,
        NULL
      ),
(
        'Peaches-Crave-Haint-60342',
        'Peaches Crave Haint Arcana Craves',
        'Peaches',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,sweet,powdery,fruity,vanilla',
        'Peaches Crave HaintbyArcana Cravesis a Amber Vanilla fragrance for women.Peaches Crave Haintwas launched in 2018.',
        4.17,
        6,
        NULL
      ),
(
        'Peaches-Crave-Mambo-58471',
        'Peaches Crave Mambo Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,tobacco,rum,vanilla,fruity',
        'Peaches Crave MambobyArcana Cravesis a Amber fragrance for women and men.Peaches Crave Mambowas launched in 2015.',
        4.75,
        4,
        NULL
      ),
(
        'Peaches-Crave-Paws-60347',
        'Peaches Crave Paws Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,aromatic,lactonic,musky,floral',
        'Peaches Crave PawsbyArcana Cravesis a Amber fragrance for women and men.Peaches Crave Pawswas launched in 2015.',
        5,
        1,
        NULL
      ),
(
        'Peaches-Crave-Pirates-58472',
        'Peaches Crave Pirates Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,powdery,coconut,honey',
        'Peaches Crave PiratesbyArcana Cravesis a Amber Spicy fragrance for women and men.Peaches Crave Pirateswas launched in 2015.',
        4.33,
        3,
        NULL
      ),
(
        'Peaches-Crave-Porches-60348',
        'Peaches Crave Porches Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh,aquatic,ozonic,tuberose,fruity',
        'Peaches Crave PorchesbyArcana Cravesis a Amber fragrance for women and men.Peaches Crave Porcheswas launched in 2016.',
        4,
        1,
        NULL
      ),
(
        'Peaches-Crave-the-Movies-65513',
        'Peaches Crave the Movies Arcana Craves',
        'Peaches',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,cherry,fruity,lactonic,soft spicy',
        'Peaches Crave the MoviesbyArcana Cravesis a Aromatic Fruity fragrance for women.Peaches Crave the Movieswas launched in 2020.',
        3.33,
        3,
        NULL
      ),
(
        'Peaches-Crave-Trance-58475',
        'Peaches Crave Trance Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,musky,fruity,powdery,vanilla',
        'Peaches Crave TrancebyArcana Cravesis a Amber fragrance for women and men.Peaches Crave Trancewas launched in 2015.',
        5,
        1,
        NULL
      ),
(
        'Peaches-Crave-True-Love-58474',
        'Peaches Crave True Love Arcana Craves',
        'Peaches',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,vanilla,aquatic,powdery',
        'Peaches Crave True LovebyArcana Cravesis a Amber Vanilla fragrance for women and men.Peaches Crave True Lovewas launched in 2015.',
        4.5,
        2,
        NULL
      ),
(
        'Peaches-Crave-Ultraviolet-60345',
        'Peaches Crave Ultraviolet Arcana Craves',
        'Peaches',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,powdery,fruity,vanilla,violet',
        'Peaches Crave UltravioletbyArcana Cravesis a Amber fragrance for women.Peaches Crave Ultravioletwas launched in 2018.',
        4,
        2,
        NULL
      );
