
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Sweet-Almond-Blossom-84606',
        'Sweet Almond Blossom Floral Street',
        'Sweet',
        'for women and men',
        NULL,
        'Jérôme Epinette',
        NULL,
        NULL,
        NULL,
        'vanilla,citrus,sweet,powdery,fruity',
        'Sweet Almond BlossombyFloral Streetis a Floral Green fragrance for women and men. This is a new fragrance.Sweet Almond Blossomwas launched in 2023. The nose behind this fragrance is Jérôme Epinette.',
        3.85,
        178,
        NULL
      ),
(
        'Wild-Vanilla-Orchid-47212',
        'Wild Vanilla Orchid Floral Street',
        'Wild',
        'for women and men',
        NULL,
        'Jérôme Epinette',
        'Vanilla Flower, Cassis and Citruses',
        'Bamboo, Flowers and Jasmine',
        'Vanilla Bean, Sandalwood, Orchid and Patchouli',
        'woody,vanilla,floral,powdery,aromatic',
        'Wild Vanilla OrchidbyFloral Streetis a Amber Floral fragrance for women and men.Wild Vanilla Orchidwas launched in 2017. The nose behind this fragrance is Jérôme Epinette. Top notes are Vanilla Flower, Cassis and Citruses; middle notes are Bamboo, Flowers and Jasmine; base notes are Vanilla Bean, Sandalwood, Orchid and Patchouli.',
        3.67,
        886,
        NULL
      ),
(
        'Wonderland-Peony-47211',
        'Wonderland Peony Floral Street',
        'Wonderland',
        'for women and men',
        NULL,
        'Jérôme Epinette',
        'Guava, Red Berries and Sicilian Lemon',
        'Peony, Raspberry Bloom and Violet',
        'Cotton Candy, Vanilla, Resins, Woody Notes, Cedar and Vetiver',
        'fruity,fresh,floral,sweet,woody',
        'Wonderland PeonybyFloral Streetis a Floral fragrance for women and men.Wonderland Peonywas launched in 2017. The nose behind this fragrance is Jérôme Epinette. Top notes are Guava, Red Berries and Sicilian Lemon; middle notes are Peony, Raspberry Bloom and Violet; base notes are Cotton Candy, Vanilla, Resins, Woody Notes, Cedar and Vetiver.',
        3.88,
        917,
        NULL
      ),
(
        'Ylang-Ylang-Espresso-47210',
        'Ylang-Ylang Espresso Floral Street',
        'Ylang-Ylang',
        'for women and men',
        NULL,
        'Jérôme Epinette',
        'Sichuan Pepper, Rose and Tangerine',
        'Ylang-Ylang, Patchouli, Tiramisu and Jasmine',
        'Coffee, Cacao, Whipped Cream and Guaiac Wood',
        'coffee,warm spicy,sweet,woody,yellow floral',
        'Ylang-Ylang EspressobyFloral Streetis a Amber Floral fragrance for women and men.Ylang-Ylang Espressowas launched in 2017. The nose behind this fragrance is Jérôme Epinette. Top notes are Sichuan Pepper, Rose and Tangerine; middle notes are Ylang-Ylang, Patchouli, Tiramisu and Jasmine; base notes are Coffee, Cacao, Whipped Cream and Guaiac Wood.',
        3.31,
        537,
        NULL
      ),
(
        'Friday-Night-79182',
        'Friday Night Floraïku',
        'Friday',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,powdery,warm spicy,musky',
        'Friday NightbyFloraïkuis a Woody fragrance for women and men.Friday Nightwas launched in 2021.',
        3.17,
        6,
        NULL
      ),
(
        'I-Am-Not-a-Flower-63337',
        'I Am Not a Flower Floraïku',
        'I',
        'for women and men',
        NULL,
        'Alienor Massenet',
        NULL,
        NULL,
        NULL,
        'oud,amber,warm spicy,woody,powdery',
        'I Am Not a FlowerbyFloraïkuis a Amber Woody fragrance for women and men.I Am Not a Flowerwas launched in 2018. The nose behind this fragrance is Alienor Massenet.',
        4.27,
        41,
        NULL
      ),
(
        'And-Your-Lips-76945',
        'And Your Lips Floraïku',
        'And',
        'for women and men',
        NULL,
        NULL,
        'Jujube Blossom, Bergamot, Mandarin Orange, Clary Sage and Lavender',
        'Turkish Rose, Egyptian Jasmine and Geranium',
        'Madagascar Vanilla, Tonka Bean, White Musk and Moss',
        'vanilla,rose,floral,sweet,citrus',
        'And Your LipsbyFloraïkuis a fragrance for women and men. This is a new fragrance.And Your Lipswas launched in 2022. Top notes are Jujube Blossom, Bergamot, Mandarin Orange, Clary Sage and Lavender; middle notes are Turkish Rose, Egyptian Jasmine and Geranium; base notes are Madagascar Vanilla, Tonka Bean, White Musk and Moss.',
        4.1,
        116,
        NULL
      ),
(
        'Boyish-88790',
        'Boyish Floraïku',
        'Boyish',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Bergamot and Pink Pepper',
        'Iris, Labdanum and Lily of the Valley',
        'Patchouli, Cedar, Olibanum, Amber and Haitian Vetiver',
        'citrus,woody,amber,aromatic,powdery',
        'BoyishbyFloraïkuis a fragrance for women and men. This is a new fragrance.Boyishwas launched in 2023. Top notes are Lemon, Bergamot and Pink Pepper; middle notes are Iris, Labdanum and Lily of the Valley; base notes are Patchouli, Cedar, Olibanum, Amber and Haitian Vetiver.',
        3.58,
        19,
        NULL
      ),
(
        'Cricket-Song-46163',
        'Cricket Song Floraïku',
        'Cricket',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Bergamot',
        'Magnolia',
        'Vetiver',
        'floral,citrus,aromatic,woody',
        'Cricket SongbyFloraïkuis a Floral Woody Musk fragrance for women and men.Cricket Songwas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top note is Bergamot; middle note is Magnolia; base note is Vetiver.',
        3.54,
        392,
        NULL
      ),
(
        'First-Dream-of-the-Year-46164',
        'First Dream of the Year Floraïku',
        'First',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Grapefruit',
        'Orange Blossom',
        'Iris',
        'citrus,white floral,iris,sweet,powdery',
        'First Dream of the YearbyFloraïkuis a Floral fragrance for women and men.First Dream of the Yearwas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top note is Grapefruit; middle note is Orange Blossom; base note is Iris.',
        3.66,
        347,
        NULL
      ),
(
        'Flowers-Turn-Purple-52149',
        'Flowers Turn Purple Floraïku',
        'Flowers',
        'for women and men',
        NULL,
        NULL,
        'Basil',
        'Lavender',
        'Amberwood',
        'lavender,fresh spicy,aromatic,amber,herbal',
        'Flowers Turn PurplebyFloraïkuis a Woody Aromatic fragrance for women and men.Flowers Turn Purplewas launched in 2018. Top note is Basil; middle note is Lavender; base note is Amberwood.',
        3.68,
        123,
        NULL
      ),
(
        'I-See-the-Clouds-Go-By-46162',
        'I See the Clouds Go By Floraïku',
        'I',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Cassis',
        'Cherry Blossom',
        'White Musk',
        'fruity,aromatic,fresh,floral,green',
        'I See the Clouds Go BybyFloraïkuis a Floral Fruity fragrance for women and men.I See the Clouds Go Bywas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top note is Cassis; middle note is Cherry Blossom; base note is White Musk.',
        3.93,
        494,
        NULL
      ),
(
        'Just-A-Rose-55768',
        'Just A Rose Floraïku',
        'Just',
        'for women and men',
        NULL,
        NULL,
        'Bergamot',
        'Rose',
        'Guaiac Wood',
        'rose,citrus,woody,floral,fresh spicy',
        'Just A RosebyFloraïkuis a Floral fragrance for women and men.Just A Rosewas launched in 2019. Top note is Bergamot; middle note is Rose; base note is Guaiac Wood.',
        3.93,
        151,
        NULL
      ),
(
        'This-July-Evening-61620',
        'This July Evening Floraïku',
        'This',
        'for women and men',
        NULL,
        'Miroslav Petkov',
        NULL,
        NULL,
        NULL,
        'vanilla,herbal,white floral,floral,powdery',
        'This July EveningbyFloraïkuis a Amber Floral fragrance for women and men.This July Eveningwas launched in 2020. The nose behind this fragrance is Miroslav Petkov.',
        3.48,
        143,
        NULL
      ),
(
        'Volcanic-Flowers-67606',
        'Volcanic Flowers Floraïku',
        'Volcanic',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,fresh spicy,woody,amber,aromatic',
        'Volcanic FlowersbyFloraïkuis a Amber Spicy fragrance for women and men.Volcanic Flowerswas launched in 2020. Volcanic Flowers was created by Alienor Massenet, Philippe Paparella-Paris and Symrise.',
        3.71,
        133,
        NULL
      ),
(
        'Young-at-Heart-65611',
        'Young at Heart Floraïku',
        'Young',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,fruity,floral,white floral',
        'Young at HeartbyFloraïkuis a Floral Fruity fragrance for women and men.Young at Heartwas launched in 2021.',
        3.51,
        174,
        NULL
      ),
(
        'Here-Comes-the-Light-79181',
        'Here Comes the Light Floraïku',
        'Here',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,leather,sweet,animalic,aromatic',
        'Here Comes the LightbyFloraïkuis a fragrance for women and men. This is a new fragrance.Here Comes the Lightwas launched in 2022.',
        4.33,
        6,
        NULL
      ),
(
        'I-Dream-of-Paris-70807',
        'I Dream of Paris Floraïku',
        'I',
        'for women and men',
        NULL,
        'Yann Vasnier',
        NULL,
        NULL,
        NULL,
        'fruity,rose,citrus,sweet,aromatic',
        'I Dream of ParisbyFloraïkuis a Woody fragrance for women and men.I Dream of Pariswas launched in 2021. The nose behind this fragrance is Yann Vasnier.',
        3.58,
        130,
        NULL
      ),
(
        'Surprise-58419',
        'Surprise Floraïku',
        'Surprise',
        'for women and men',
        NULL,
        NULL,
        'Dates',
        'Heliotrope',
        'Agarwood (Oud)',
        'oud,sweet,powdery,vanilla,fruity',
        'SurprisebyFloraïkuis a Amber Floral fragrance for women and men.Surprisewas launched in 2019. Top note is Dates; middle note is Heliotrope; base note is Agarwood (Oud).',
        3.45,
        11,
        NULL
      ),
(
        'What-A-Day-67062',
        'What A Day! Floraïku',
        'What',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Fruits, Nutmeg, Coriander, Bergamot and Black Pepper',
        'Pimento, Rose, Cedar, Saffron, Orris and Lily-of-the-Valley',
        'Vetiver, Leather, Geranium, Cinnamon and Vanilla',
        'warm spicy,aromatic,woody,rose,fresh spicy',
        'What A Day!byFloraïkuis a Woody Spicy fragrance for women and men.What A Day!was launched in 2021. Top notes are Cardamom, Fruits, Nutmeg, Coriander, Bergamot and Black Pepper; middle notes are Pimento, Rose, Cedar, Saffron, Orris and Lily-of-the-Valley; base notes are Vetiver, Leather, Geranium, Cinnamon and Vanilla.',
        3.64,
        14,
        NULL
      ),
(
        'Wind-In-My-Hand-49211',
        'Wind In My Hand Floraïku',
        'Wind',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Mate',
        'Incense',
        'amber,smoky,citrus,balsamic,warm spicy',
        'Wind In My HandbyFloraïkuis a Citrus Aromatic fragrance for women and men.Wind In My Handwas launched in 2018. Top note is Mandarin Orange; middle note is Mate; base note is Incense.',
        3.5,
        10,
        NULL
      ),
(
        'AO-66478',
        'AO Floraïku',
        'AO',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,violet,woody,amber',
        'AObyFloraïkuis a fragrance for women and men.',
        4.12,
        237,
        NULL
      ),
(
        'In-The-Dark-73175',
        'In The Dark Floraïku',
        'In',
        'for women and men',
        NULL,
        NULL,
        'Sicilian Lemon and Mint',
        'Turkish Rose and Nutmeg',
        'Incense, Patchouli and Musk',
        'rose,citrus,amber,aromatic,green',
        'In The DarkbyFloraïkuis a fragrance for women and men. Top notes are Sicilian Lemon and Mint; middle notes are Turkish Rose and Nutmeg; base notes are Incense, Patchouli and Musk.',
        4.02,
        140,
        NULL
      ),
(
        'In-The-Rain-48909',
        'In The Rain Floraïku',
        'In',
        'for women and men',
        NULL,
        'Sarah Burri',
        'Bergamot',
        'Cedar',
        'Woody Notes and Musk',
        'woody,citrus,musky,powdery',
        'In The RainbyFloraïkuis a Woody Aromatic fragrance for women and men.In The Rainwas launched in 2018. The nose behind this fragrance is Sarah Burri. Top note is Bergamot; middle note is Cedar; base notes are Woody Notes and Musk.',
        3.46,
        138,
        NULL
      ),
(
        'My-Love-Has-the-Colour-of-the-Night-46168',
        'My Love Has the Colour of the Night Floraïku',
        'My',
        'for women and men',
        NULL,
        'Sophie Labbé',
        'Guaiac Wood',
        'Patchouli',
        'Vetiver',
        'woody,patchouli,earthy,aromatic,warm spicy',
        'My Love Has the Colour of the NightbyFloraïkuis a Woody fragrance for women and men.My Love Has the Colour of the Nightwas launched in 2017. The nose behind this fragrance is Sophie Labbe. Top note is Guaiac Wood; middle note is Patchouli; base note is Vetiver.',
        3.64,
        341,
        NULL
      ),
(
        'My-Shadow-on-the-Wall-46169',
        'My Shadow on the Wall Floraïku',
        'My',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Violet Leaf',
        'Mimosa',
        'Sandalwood',
        'yellow floral,ozonic,powdery,aquatic,woody',
        'My Shadow on the WallbyFloraïkuis a Floral Green fragrance for women and men.My Shadow on the Wallwas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top note is Violet Leaf; middle note is Mimosa; base note is Sandalwood.',
        3.58,
        363,
        NULL
      ),
(
        'Sand-and-Skin-79180',
        'Sand and Skin Floraïku',
        'Sand',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,woody,powdery,yellow floral,amber',
        'Sand and SkinbyFloraïkuis a Amber Floral fragrance for women and men. This is a new fragrance.Sand and Skinwas launched in 2023.',
        3.98,
        179,
        NULL
      ),
(
        'Sound-of-a-Ricochet-46170',
        'Sound of a Ricochet Floraïku',
        'Sound',
        'for women and men',
        NULL,
        'Sophie Labbé',
        'Vanilla Absolute',
        'Tonka Bean',
        'Sandalwood',
        'vanilla,woody,powdery,sweet,warm spicy',
        'Sound of a RicochetbyFloraïkuis a Amber Vanilla fragrance for women and men.Sound of a Ricochetwas launched in 2017. The nose behind this fragrance is Sophie Labbe. Top note is Vanilla Absolute; middle note is Tonka Bean; base note is Sandalwood.',
        3.72,
        457,
        NULL
      ),
(
        'Golden-Eyes-69527',
        'Golden Eyes Floraïku',
        'Golden',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,aromatic,earthy,leather',
        'Golden EyesbyFloraïkuis a fragrance for women and men.Golden Eyeswas launched in 2021.',
        3.73,
        117,
        NULL
      ),
(
        'I-Am-Coming-Home-46167',
        'I Am Coming Home Floraïku',
        'I',
        'for women and men',
        NULL,
        'Sophie Labbé',
        'Ginger',
        'White Tea',
        'Cardamom',
        'warm spicy,fresh,green',
        'I Am Coming HomebyFloraïkuis a Aromatic Spicy fragrance for women and men.I Am Coming Homewas launched in 2017. The nose behind this fragrance is Sophie Labbe. Top note is Ginger; middle note is White Tea; base note is Cardamom.',
        4,
        513,
        NULL
      ),
(
        'Levitating-77999',
        'Levitating Floraïku',
        'Levitating',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Mandarin Orange and Angelica',
        'Black Tea, Mate and Cloves',
        'Bourbon Vanilla, Guaiac Wood and Virginia Cedar',
        'citrus,vanilla,green,woody,fresh spicy',
        'LevitatingbyFloraïkuis a fragrance for women and men. This is a new fragrance.Levitatingwas launched in 2022. Top notes are Bergamot, Mandarin Orange and Angelica; middle notes are Black Tea, Mate and Cloves; base notes are Bourbon Vanilla, Guaiac Wood and Virginia Cedar.',
        4.13,
        123,
        NULL
      ),
(
        'One-Umbrella-for-Two-46165',
        'One Umbrella for Two Floraïku',
        'One',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Black Currant and Cyclamen',
        'Tea and Rice',
        'Cedar and White Musk',
        'fruity,woody,green,soft spicy,floral',
        'One Umbrella for TwobyFloraïkuis a Aromatic Fruity fragrance for women and men.One Umbrella for Twowas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top notes are Black Currant and Cyclamen; middle notes are Tea and Rice; base notes are Cedar and White Musk.',
        4.07,
        1,
        NULL
      ),
(
        'The-Moon-and-I-46166',
        'The Moon and I Floraïku',
        'The',
        'for women and men',
        NULL,
        'Sophie Labbé',
        'Mate',
        'Tea',
        'Cedar',
        'green,aromatic,fresh,fresh spicy,woody',
        'The Moon and IbyFloraïkuis a Woody Aromatic fragrance for women and men.The Moon and Iwas launched in 2017. The nose behind this fragrance is Sophie Labbe. Top note is Mate; middle note is Tea; base note is Cedar.',
        3.8,
        434,
        NULL
      ),
(
        'The-Mountain-Standing-Still-56577',
        'The Mountain Standing Still Floraïku',
        'The',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,green,warm spicy,metallic,fresh',
        'The Mountain Standing StillbyFloraïkuis a Woody fragrance for women and men.The Mountain Standing Stillwas launched in 2018.',
        3.86,
        140,
        NULL
      ),
(
        'Between-Two-Trees-46172',
        'Between Two Trees Floraïku',
        'Between',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Grapefruit',
        'Mate',
        'Vetiver',
        'aromatic,citrus,woody,fresh spicy,earthy',
        'Between Two TreesbyFloraïkuis a Citrus Aromatic fragrance for women and men.Between Two Treeswas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top note is Grapefruit; middle note is Mate; base note is Vetiver.',
        4.02,
        569,
        NULL
      ),
(
        'Sleeping-on-the-Roof-46171',
        'Sleeping on the Roof Floraïku',
        'Sleeping',
        'for women and men',
        NULL,
        'Alienor Massenet',
        'Lily-of-the-Valley',
        'Orange Blossom',
        'Musk and Amber',
        'white floral,fresh,musky,green,soapy',
        'Sleeping on the RoofbyFloraïkuis a Floral fragrance for women and men.Sleeping on the Roofwas launched in 2017. The nose behind this fragrance is Alienor Massenet. Top note is Lily-of-the-Valley; middle note is Orange Blossom; base notes are Musk and Amber.',
        3.57,
        522,
        NULL
      ),
(
        'Aiyra-72996',
        'Aiyra Flora Pura',
        'Aiyra',
        'for women',
        NULL,
        'Juliana Tolotti',
        NULL,
        NULL,
        NULL,
        'sweet,fruity,woody,citrus,patchouli',
        'AiyrabyFlora Purais a Floral fragrance for women.Aiyrawas launched in 2021. The nose behind this fragrance is Juliana Tolotti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Allegra-Femme-73493',
        'Allegra Femme Flora Pura',
        'Allegra',
        'for women',
        NULL,
        'Edison Fujita',
        'Bergamot and Forest Fruits',
        'Tuberose and Egyptian Jasmine',
        'Vetiver, Sandalwood, Vanilla and Tonka Bean',
        'woody,white floral,vanilla,aromatic,citrus',
        'Allegra FemmebyFlora Purais a Amber Floral fragrance for women.Allegra Femmewas launched in 2016. The nose behind this fragrance is Edison Fujita. Top notes are Bergamot and Forest Fruits; middle notes are Tuberose and Egyptian Jasmine; base notes are Vetiver, Sandalwood, Vanilla and Tonka Bean.',
        3,
        1,
        NULL
      ),
(
        'Ambiance-81606',
        'Ambiance Flora Pura',
        'Ambiance',
        'for women',
        NULL,
        'Edison Fujita',
        'Cassis, Pear and Rhubarb',
        'Rose, Yellow Rose, Narcissus, Tuberose and Orange Blossom',
        'Hazelnut and Sandalwood',
        'green,fruity,woody,white floral,aromatic',
        'AmbiancebyFlora Purais a Floral Fruity fragrance for women.Ambiancewas launched in 2022. The nose behind this fragrance is Edison Fujita. Top notes are Cassis, Pear and Rhubarb; middle notes are Rose, Yellow Rose, Narcissus, Tuberose and Orange Blossom; base notes are Hazelnut and Sandalwood.',
        4.67,
        3,
        NULL
      ),
(
        'Anahi-73486',
        'Anahí Flora Pura',
        'Anahí',
        'for women',
        NULL,
        'Edison Fujita',
        'Pear, Bergamot and Sour Cherry',
        'Narcissus, Jasmine, Tuberose and Orange Blossom',
        'Musk, Amber, Vetiver, Vanilla, Patchouli and Caramel',
        'white floral,sweet,citrus,woody,aromatic',
        'AnahíbyFlora Purais a Amber Floral fragrance for women.Anahíwas launched in 2021. The nose behind this fragrance is Edison Fujita. Top notes are Pear, Bergamot and Sour Cherry; middle notes are Narcissus, Jasmine, Tuberose and Orange Blossom; base notes are Musk, Amber, Vetiver, Vanilla, Patchouli and Caramel.',
        5,
        1,
        NULL
      ),
(
        'Bamboo-Eau-de-Cologne-73334',
        'Bamboo Eau de Cologne Flora Pura',
        'Bamboo',
        'for women and men',
        NULL,
        'Alfredo Monteiro Filho',
        'Lemon, Sage, Lime, Lavender and Chamomile',
        'Clove, Cinnamon, Geranium, Ylang-Ylang and Lily-of-the-Valley',
        'Musk, Cedar, Vetiver, Sandalwood and Patchouli',
        'woody,aromatic,warm spicy,herbal,citrus',
        'Bamboo Eau de ColognebyFlora Purais a Woody Aromatic fragrance for women and men.Bamboo Eau de Colognewas launched in 2018. The nose behind this fragrance is Alfredo Monteiro Filho. Top notes are Lemon, Sage, Lime, Lavender and Chamomile; middle notes are Clove, Cinnamon, Geranium, Ylang-Ylang and Lily-of-the-Valley; base notes are Musk, Cedar, Vetiver, Sandalwood and Patchouli.',
        4,
        2,
        NULL
      ),
(
        'Belissima-73518',
        'Belíssima Flora Pura',
        'Belíssima',
        'for women',
        NULL,
        'Luciana Bergamasco',
        'Pear, Bergamot, Pink Pepper and Red Fruits',
        'Peony, Jasmine, Red Rose and Orange Blossom',
        'Musk, Amber, Vanilla, Woodsy Notes and Velvet',
        'white floral,musky,floral,sweet,rose',
        'BelíssimabyFlora Purais a Chypre Floral fragrance for women.Belíssimawas launched in 2013. The nose behind this fragrance is Luciana Bergamasco. Top notes are Pear, Bergamot, Pink Pepper and Red Fruits; middle notes are Peony, Jasmine, Red Rose and Orange Blossom; base notes are Musk, Amber, Vanilla, Woodsy Notes and Velvet.',
        NULL,
        NULL,
        NULL
      ),
(
        'Black-Jack-73487',
        'Black Jack Flora Pura',
        'Black',
        'for men',
        NULL,
        'Edison Fujita',
        'Lime, Bergamot and Black Pepper',
        'Sage, Cacao, Violet, Lavender and Lily-of-the-Valley',
        'Moss, Vanilla, Tonka Bean and Amberwood',
        'citrus,aromatic,fresh spicy,vanilla,amber',
        'Black JackbyFlora Purais a Amber Spicy fragrance for men.Black Jackwas launched in 2021. The nose behind this fragrance is Edison Fujita. Top notes are Lime, Bergamot and Black Pepper; middle notes are Sage, Cacao, Violet, Lavender and Lily-of-the-Valley; base notes are Moss, Vanilla, Tonka Bean and Amberwood.',
        5,
        1,
        NULL
      ),
(
        'Black-Pour-Homme-73494',
        'Black Pour Homme Flora Pura',
        'Black',
        'for men',
        NULL,
        'Edison Fujita',
        'Bergamot, Pink Pepper, elemi and Rosemary',
        'Violet Leaves, Cedar, Violet and Patchouli',
        'Vetiver, Musk and Oakmoss',
        'woody,aromatic,earthy,citrus,fresh spicy',
        'Black Pour HommebyFlora Purais a Woody Aromatic fragrance for men.Black Pour Hommewas launched in 2020. The nose behind this fragrance is Edison Fujita. Top notes are Bergamot, Pink Pepper, elemi and Rosemary; middle notes are Violet Leaves, Cedar, Violet and Patchouli; base notes are Vetiver, Musk and Oakmoss.',
        4.33,
        3,
        NULL
      ),
(
        'Dany-Woman-73331',
        'Dany Woman Flora Pura',
        'Dany',
        'for women',
        NULL,
        'Alfredo Monteiro Filho',
        'Tangerine, Raspberry, Pink Pepper and Apple',
        'Rose, Ylang-Ylang and Freesia',
        'Musk, Cedar, Vanilla and Patchouli',
        'sweet,fruity,woody,rose,musky',
        'Dany WomanbyFlora Purais a Chypre Floral fragrance for women.Dany Womanwas launched in 2019. The nose behind this fragrance is Alfredo Monteiro Filho. Top notes are Tangerine, Raspberry, Pink Pepper and Apple; middle notes are Rose, Ylang-Ylang and Freesia; base notes are Musk, Cedar, Vanilla and Patchouli.',
        4.75,
        4,
        NULL
      ),
(
        'Especial-Man-73489',
        'Especial Man Flora Pura',
        'Especial',
        'for men',
        NULL,
        'Edison Fujita',
        'Lime, Bergamot and Black Pepper',
        'Sage, Cacao, Violet, Lavender and Lily-of-the-Valley',
        'Moss, Vanilla, Tonka Bean and Amberwood',
        'citrus,aromatic,fresh spicy,vanilla,amber',
        'Especial ManbyFlora Purais a Amber Spicy fragrance for men.Especial Manwas launched in 2021. The nose behind this fragrance is Edison Fujita. Top notes are Lime, Bergamot and Black Pepper; middle notes are Sage, Cacao, Violet, Lavender and Lily-of-the-Valley; base notes are Moss, Vanilla, Tonka Bean and Amberwood.',
        4,
        3,
        NULL
      ),
(
        'Especial-Woman-73488',
        'Especial Woman Flora Pura',
        'Especial',
        'for women',
        NULL,
        'Edison Fujita',
        'Pear, Cassis and Bergamot',
        'Turkish Rose, Lily-of-the-Valley, Rose de Mai and Indian Jasmine',
        'Vanilla and White Musk',
        'white floral,rose,fresh,floral,green',
        'Especial WomanbyFlora Purais a Chypre Floral fragrance for women.Especial Womanwas launched in 2021. The nose behind this fragrance is Edison Fujita. Top notes are Pear, Cassis and Bergamot; middle notes are Turkish Rose, Lily-of-the-Valley, Rose de Mai and Indian Jasmine; base notes are Vanilla and White Musk.',
        5,
        1,
        NULL
      ),
(
        'Flor-de-Jurema-73517',
        'Flor de Jurema Flora Pura',
        'Flor',
        'for women',
        NULL,
        'Luciana Bergamasco',
        'Mate, Mint, Mandarin Orange and Sicilian Lemon',
        'Iris, Rose, Jasmine and Lily-of-the-Valley',
        'Oakmoss, Cedar, Vetiver and Musk',
        'aromatic,woody,earthy,green,mossy',
        'Flor de JuremabyFlora Purais a Citrus Aromatic fragrance for women.Flor de Juremawas launched in 2020. The nose behind this fragrance is Luciana Bergamasco. Top notes are Mate, Mint, Mandarin Orange and Sicilian Lemon; middle notes are Iris, Rose, Jasmine and Lily-of-the-Valley; base notes are Oakmoss, Cedar, Vetiver and Musk.',
        4,
        3,
        NULL
      ),
(
        'Flora-No-1-81605',
        'Flora Nº 1 Flora Pura',
        'Flora',
        'for women',
        NULL,
        NULL,
        'Citruses',
        'Rose and Ylang-Ylang',
        'Woody Notes, Vanilla and Tonka Bean',
        'vanilla,woody,sweet,citrus,rose',
        'Flora Nº 1byFlora Purais a Floral fragrance for women.Flora Nº 1was launched in 2022. Top note is Citruses; middle notes are Rose and Ylang-Ylang; base notes are Woody Notes, Vanilla and Tonka Bean.',
        3.67,
        3,
        NULL
      ),
(
        'Hera-73515',
        'Hera Flora Pura',
        'Hera',
        'for women',
        NULL,
        'Luciana Bergamasco',
        'Plum, Bergamot and Red Apple',
        'Iris, Rose, Jasmine and Lily-of-the-Valley',
        'Patchouli, Musk, Benzoin and Vanilla',
        'fruity,patchouli,musky,woody,powdery',
        'HerabyFlora Purais a Chypre Floral fragrance for women.Herawas launched in 2020. The nose behind this fragrance is Luciana Bergamasco. Top notes are Plum, Bergamot and Red Apple; middle notes are Iris, Rose, Jasmine and Lily-of-the-Valley; base notes are Patchouli, Musk, Benzoin and Vanilla.',
        4.75,
        4,
        NULL
      ),
(
        'Heros-73332',
        'Héros Flora Pura',
        'Héros',
        'for men',
        NULL,
        'Alfredo Monteiro Filho',
        'Cardamom and Nutmeg',
        'Musk',
        'Woodsy Notes, Spices, Aromatic Notes, Amber and Musk',
        'warm spicy,amber,fresh spicy,musky,woody',
        'HérosbyFlora Purais a Woody Spicy fragrance for men.Héroswas launched in 2021. The nose behind this fragrance is Alfredo Monteiro Filho. Top notes are Cardamom and Nutmeg; middle note is Musk; base notes are Woodsy Notes, Spices, Aromatic Notes, Amber and Musk.',
        5,
        2,
        NULL
      ),
(
        'Inaie-73516',
        'Inaiê Flora Pura',
        'Inaiê',
        'for women',
        NULL,
        'Luciana Bergamasco',
        'Anise, Lime, Ginger and Coriander',
        'Jasmine, Lavender and Green Notes',
        'Musk, Cedar, Coumarin, Ambergris and Sandalwood',
        'woody,aromatic,warm spicy,musky,sweet',
        'InaiêbyFlora Purais a Woody Aromatic fragrance for women.Inaiêwas launched in 2021. The nose behind this fragrance is Luciana Bergamasco. Top notes are Anise, Lime, Ginger and Coriander; middle notes are Jasmine, Lavender and Green Notes; base notes are Musk, Cedar, Coumarin, Ambergris and Sandalwood.',
        5,
        1,
        NULL
      ),
(
        'Lisianthus-79963',
        'Lisianthus Flora Pura',
        'Lisianthus',
        'for women',
        NULL,
        'Edison Fujita',
        'Tangerine and Bergamot',
        'Eustoma | Lisianthus, Grasse Rose and Jasmine Sambac',
        'Musk, Vetiver, Sandalwood and Patchouli',
        'citrus,white floral,rose,floral,fresh spicy',
        'LisianthusbyFlora Purais a Floral fragrance for women. This is a new fragrance.Lisianthuswas launched in 2022. The nose behind this fragrance is Edison Fujita. Top notes are Tangerine and Bergamot; middle notes are Eustoma | Lisianthus, Grasse Rose and Jasmine Sambac; base notes are Musk, Vetiver, Sandalwood and Patchouli.',
        4.5,
        2,
        NULL
      ),
(
        'Lorenzo-73335',
        'Lorenzo Flora Pura',
        'Lorenzo',
        'for men',
        NULL,
        'Alfredo Monteiro Filho',
        'Star Anise, Basil, Bergamot and Violet Leaf',
        'Jasmine, Nutmeg and Pink Pepper',
        'Musk, Vetiver and Patchouli',
        'fresh spicy,aromatic,soft spicy,woody,musky',
        'LorenzobyFlora Purais a Woody Spicy fragrance for men.Lorenzowas launched in 2017. The nose behind this fragrance is Alfredo Monteiro Filho. Top notes are Star Anise, Basil, Bergamot and Violet Leaf; middle notes are Jasmine, Nutmeg and Pink Pepper; base notes are Musk, Vetiver and Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Niara-72997',
        'Niara Flora Pura',
        'Niara',
        'for women',
        NULL,
        'Juliana Tolotti',
        NULL,
        NULL,
        NULL,
        'floral,oily',
        'NiarabyFlora Purais a Floral fragrance for women.Niarawas launched in 2021. The nose behind this fragrance is Juliana Tolotti.',
        NULL,
        NULL,
        NULL
      ),
(
        'Pink-73519',
        'Pink Flora Pura',
        'Pink',
        'for women',
        NULL,
        'Luciana Bergamasco',
        'Caramel and Lavender',
        'Iris, Jasmine and Lily-of-the-Valley',
        'Musk, Benzoin and Vanilla',
        'powdery,vanilla,amber,caramel,musky',
        'PinkbyFlora Purais a Amber fragrance for women.Pinkwas launched in 2020. The nose behind this fragrance is Luciana Bergamasco. Top notes are Caramel and Lavender; middle notes are Iris, Jasmine and Lily-of-the-Valley; base notes are Musk, Benzoin and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Reserva-Especial-1949-73484',
        'Reserva Especial 1949 Flora Pura',
        'Reserva',
        'for men',
        NULL,
        'Edison Fujita',
        'Lime, Apple, Pomelo and Lavender',
        'Juniper, Geranium, Cardamom and Nutmeg',
        'Vetiver, Musk and Tonka Bean',
        'aromatic,fresh spicy,woody,citrus,warm spicy',
        'Reserva Especial 1949byFlora Purais a Woody Spicy fragrance for men.Reserva Especial 1949was launched in 2018. The nose behind this fragrance is Edison Fujita. Top notes are Lime, Apple, Pomelo and Lavender; middle notes are Juniper, Geranium, Cardamom and Nutmeg; base notes are Vetiver, Musk and Tonka Bean.',
        4,
        3,
        NULL
      ),
(
        'Sultao-73482',
        'Sultão Flora Pura',
        'Sultão',
        'for men',
        NULL,
        'Edison Fujita',
        'Incense, Rose, Bergamot and Pink Pepper',
        'elemi, Nutmeg and Jasmine',
        'Musk, Amber and Patchouli',
        'amber,balsamic,fresh spicy,aromatic,smoky',
        'SultãobyFlora Purais a Amber Floral fragrance for men.Sultãowas launched in 2019. The nose behind this fragrance is Edison Fujita. Top notes are Incense, Rose, Bergamot and Pink Pepper; middle notes are elemi, Nutmeg and Jasmine; base notes are Musk, Amber and Patchouli.',
        4.33,
        3,
        NULL
      ),
(
        'Zafirah-73490',
        'Zafirah Flora Pura',
        'Zafirah',
        'for women',
        NULL,
        'Edison Fujita',
        'Pomelo, Peach and Mandarin Orange',
        'Honey, Orange Blossom, Jasmine and Gardenia',
        'Musk, Patchouli and Caramel',
        'sweet,white floral,honey,citrus,caramel',
        'ZafirahbyFlora Purais a Chypre Floral fragrance for women.Zafirahwas launched in 2020. The nose behind this fragrance is Edison Fujita. Top notes are Pomelo, Peach and Mandarin Orange; middle notes are Honey, Orange Blossom, Jasmine and Gardenia; base notes are Musk, Patchouli and Caramel.',
        4.25,
        4,
        NULL
      ),
(
        'Zelia-Boaventura-73483',
        'Zélia Boaventura Flora Pura',
        'Zélia',
        'for women',
        NULL,
        'Edison Fujita',
        'Mandarin Orange and Orange Blossom',
        'Rose, Honey and Jasmine',
        'Musk, Cedar and Patchouli',
        'white floral,rose,woody,citrus,floral',
        'Zélia BoaventurabyFlora Purais a Floral fragrance for women.Zélia Boaventurawas launched in 2018. The nose behind this fragrance is Edison Fujita. Top notes are Mandarin Orange and Orange Blossom; middle notes are Rose, Honey and Jasmine; base notes are Musk, Cedar and Patchouli.',
        4.67,
        3,
        NULL
      ),
(
        'Ziah-73333',
        'Ziah Flora Pura',
        'Ziah',
        'for men',
        NULL,
        'Alfredo Monteiro Filho',
        'Lime, Lavender, Artemisia and Sea Notes',
        'Leather, Cedar, Sandalwood and Lily-of-the-Valley',
        'Musk, Vetiver, Patchouli and Oakmoss',
        'woody,leather,aromatic,earthy,animalic',
        'ZiahbyFlora Purais a Leather fragrance for men.Ziahwas launched in 2013. The nose behind this fragrance is Alfredo Monteiro Filho. Top notes are Lime, Lavender, Artemisia and Sea Notes; middle notes are Leather, Cedar, Sandalwood and Lily-of-the-Valley; base notes are Musk, Vetiver, Patchouli and Oakmoss.',
        NULL,
        NULL,
        NULL
      ),
(
        'Alva-29856',
        'Alva Fleur de Sante',
        'Alva',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic',
        'AlvabyFleur de Santeis a Floral fragrance for women.',
        4.22,
        9,
        NULL
      ),
(
        'Be-Mine-29852',
        'Be Mine Fleur de Sante',
        'Be',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,musky,violet,white floral',
        'Be MinebyFleur de Santeis a Floral Woody Musk fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'Crystal-Glam-l-Amour-29847',
        'Crystal Glam l''Amour Fleur de Sante',
        'Crystal',
        'for women',
        NULL,
        NULL,
        'Raspberry',
        'Rose',
        'Amber',
        'rose,amber,fruity,sweet,floral',
        'Crystal Glam l''AmourbyFleur de Santeis a Floral Fruity fragrance for women. Top note is Raspberry; middle note is Rose; base note is Amber.',
        3.5,
        4,
        NULL
      ),
(
        'Dandy-Lady-36241',
        'Dandy Lady Fleur de Sante',
        'Dandy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,powdery,violet,sweet,floral',
        'Dandy LadybyFleur de Santeis a Floral Fruity fragrance for women.Dandy Ladywas launched in 2010.',
        5,
        2,
        NULL
      ),
(
        'Edge-29853',
        'Edge Fleur de Sante',
        'Edge',
        'for men',
        NULL,
        NULL,
        'Watery Notes, Grapefruit and Mandarin Orange',
        'Orange Blossom',
        'Ambergris',
        'citrus,amber,white floral,aquatic,animalic',
        'EdgebyFleur de Santeis a Woody Spicy fragrance for men. Top notes are Watery Notes, Grapefruit and Mandarin Orange; middle note is Orange Blossom; base note is Ambergris.',
        4,
        1,
        NULL
      ),
(
        'Energetic-Me-29855',
        'Energetic Me Fleur de Sante',
        'Energetic',
        'for women',
        NULL,
        NULL,
        'Lemon, Blueberry, Apple, Watermelon and Watery Notes',
        'Lotus and Violet',
        'Raspberry and Musk',
        'fruity,aquatic,fresh,ozonic,sweet',
        'Energetic MebyFleur de Santeis a Floral Fruity fragrance for women. Top notes are Lemon, Blueberry, Apple, Watermelon and Watery Notes; middle notes are Lotus and Violet; base notes are Raspberry and Musk.',
        4,
        2,
        NULL
      ),
(
        'Exuberance-29844',
        'Exuberance Fleur de Sante',
        'Exuberance',
        'for women',
        NULL,
        NULL,
        'Citruses and Black Currant',
        'Rose, Magnolia and Jasmine',
        'Woody Notes and Peach',
        'woody,floral,fruity,citrus,white floral',
        'ExuberancebyFleur de Santeis a Floral Fruity fragrance for women. Top notes are Citruses and Black Currant; middle notes are Rose, Magnolia and Jasmine; base notes are Woody Notes and Peach.',
        4.2,
        5,
        NULL
      ),
(
        'Fallen-Angel-36068',
        'Fallen Angel Fleur de Sante',
        'Fallen',
        'for women',
        NULL,
        NULL,
        'Lotus and White Hyacinth',
        'Rose and Lily',
        'Vanilla and Jasmine',
        'floral,white floral,rose,vanilla,green',
        'Fallen AngelbyFleur de Santeis a Floral fragrance for women.Fallen Angelwas launched during the 2000''s. Top notes are Lotus and White Hyacinth; middle notes are Rose and Lily; base notes are Vanilla and Jasmine.',
        4.38,
        8,
        NULL
      ),
(
        'Femme-29843',
        'Femme Fleur de Sante',
        'Femme',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley',
        'Jasmine',
        'White Musk',
        'white floral,musky,powdery,fresh',
        'FemmebyFleur de Santeis a Floral Woody Musk fragrance for women. Top note is Lily-of-the-Valley; middle note is Jasmine; base note is White Musk.',
        4.25,
        8,
        NULL
      ),
(
        'Fleur-Rose-29837',
        'Fleur Rose Fleur de Sante',
        'Fleur',
        'for women',
        NULL,
        NULL,
        'Black Currant, Lemon and Bergamot',
        'Ylang-Ylang and Jasmine',
        'Musk, Palisander Rosewood and Peach',
        'yellow floral,woody,sweet,citrus,white floral',
        'Fleur RosebyFleur de Santeis a Floral Woody Musk fragrance for women. Top notes are Black Currant, Lemon and Bergamot; middle notes are Ylang-Ylang and Jasmine; base notes are Musk, Palisander Rosewood and Peach.',
        4,
        4,
        NULL
      ),
(
        'Fleurette-29854',
        'Fleurette Fleur de Sante',
        'Fleurette',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral',
        'FleurettebyFleur de Santeis a Floral fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'Goddess-29836',
        'Goddess Fleur de Sante',
        'Goddess',
        'for women',
        NULL,
        NULL,
        'Tangerine',
        'Magnolia',
        'Sandalwood',
        'woody,floral,citrus,powdery,warm spicy',
        'GoddessbyFleur de Santeis a Floral Woody Musk fragrance for women. Top note is Tangerine; middle note is Magnolia; base note is Sandalwood.',
        3,
        4,
        NULL
      ),
(
        'Golden-Snow-Pearl-29851',
        'Golden Snow Pearl Fleur de Sante',
        'Golden',
        'for women',
        NULL,
        NULL,
        'Orange',
        'Violet and Jasmine',
        'Patchouli and Teak Wood',
        'woody,patchouli,white floral,violet,citrus',
        'Golden Snow PearlbyFleur de Santeis a Floral Woody Musk fragrance for women. Top note is Orange; middle notes are Violet and Jasmine; base notes are Patchouli and Teak Wood.',
        4,
        2,
        NULL
      ),
(
        'Graziella-29838',
        'Graziella Fleur de Sante',
        'Graziella',
        'for women',
        NULL,
        NULL,
        'Grapefruit',
        'Jasmine',
        'Amber',
        'amber,citrus,white floral,fresh spicy,animalic',
        'GraziellabyFleur de Santeis a Floral Woody Musk fragrance for women. Top note is Grapefruit; middle note is Jasmine; base note is Amber.',
        4,
        3,
        NULL
      ),
(
        'H-Pour-Homme-29860',
        'H Pour Homme Fleur de Sante',
        'H',
        'for men',
        NULL,
        NULL,
        'Lavender, Basil, Wormwood, Tarragon and Bergamot',
        'Geranium, Lily, Patchouli, Clover and Sandalwood',
        'Coumarin, Oakmoss and Musk',
        'aromatic,fresh spicy,woody,green,warm spicy',
        'H Pour HommebyFleur de Santeis a Aromatic fragrance for men. Top notes are Lavender, Basil, Wormwood, Tarragon and Bergamot; middle notes are Geranium, Lily, Patchouli, Clover and Sandalwood; base notes are Coumarin, Oakmoss and Musk.',
        5,
        1,
        NULL
      ),
(
        'Iced-Dreams-29857',
        'Iced Dreams Fleur de Sante',
        'Iced',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,woody,sweet',
        'Iced DreamsbyFleur de Santeis a Floral Fruity fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'L-Pour-Elle-29840',
        'L Pour Elle Fleur de Sante',
        'L',
        'for women',
        NULL,
        NULL,
        'Lime and Yuzu',
        'Rose',
        'Cedar and Sandalwood',
        'citrus,woody,rose,green,floral',
        'L Pour EllebyFleur de Santeis a Floral Woody Musk fragrance for women. Top notes are Lime and Yuzu; middle note is Rose; base notes are Cedar and Sandalwood.',
        4.19,
        16,
        NULL
      ),
(
        'L-pour-Elle-Nuit-Noire-35970',
        'L pour Elle Nuit Noire Fleur de Sante',
        'L',
        'for women',
        NULL,
        NULL,
        'Black Currant and Mandarin Orange',
        'Plum and Floral Notes',
        'Woody Notes, Amber and Musk',
        'fruity,woody,floral,amber,citrus',
        'L pour Elle Nuit NoirebyFleur de Santeis a Amber fragrance for women.L pour Elle Nuit Noirewas launched in 2009. Top notes are Black Currant and Mandarin Orange; middle notes are Plum and Floral Notes; base notes are Woody Notes, Amber and Musk.',
        4,
        3,
        NULL
      ),
(
        'Mystere-de-Nature-Fleur-29858',
        'Mystere de Nature Fleur Fleur de Sante',
        'Mystere',
        'for women',
        NULL,
        NULL,
        'Black Currant, Apple and Plum',
        'Rose, Jasmine and Lily-of-the-Valley',
        'Musk, Peach and Vanilla',
        'fruity,white floral,fresh,floral,green',
        'Mystere de Nature FleurbyFleur de Santeis a Floral fragrance for women. Top notes are Black Currant, Apple and Plum; middle notes are Rose, Jasmine and Lily-of-the-Valley; base notes are Musk, Peach and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Mystere-de-Nature-Fruit-29859',
        'Mystere de Nature Fruit Fleur de Sante',
        'Mystere',
        'for women',
        NULL,
        NULL,
        'Lemon, Bergamot and Orange',
        'Floral Notes and Black Currant Blossom',
        'Musk, Teak Wood and Cedar',
        'citrus,woody,floral,musky,aromatic',
        'Mystere de Nature FruitbyFleur de Santeis a Floral Fruity fragrance for women. Top notes are Lemon, Bergamot and Orange; middle notes are Floral Notes and Black Currant Blossom; base notes are Musk, Teak Wood and Cedar.',
        4,
        1,
        NULL
      ),
(
        'Passionate-Me-29841',
        'Passionate Me Fleur de Sante',
        'Passionate',
        'for women',
        NULL,
        NULL,
        'Big Strawberry, Tangerine and Raspberry',
        'Jasmine, Rose and Lily-of-the-Valley',
        'Praline, Musk and Patchouli',
        'sweet,fruity,white floral,citrus,rose',
        'Passionate MebyFleur de Santeis a Floral Fruity Gourmand fragrance for women. Top notes are Big Strawberry, Tangerine and Raspberry; middle notes are Jasmine, Rose and Lily-of-the-Valley; base notes are Praline, Musk and Patchouli.',
        4,
        1,
        NULL
      ),
(
        'Romantic-Me-29842',
        'Romantic Me Fleur de Sante',
        'Romantic',
        'for women',
        NULL,
        NULL,
        'Pear, Pineapple, Violet and Grapefruit',
        'Peony, Jasmine and Lily-of-the-Valley',
        'Cedar, Amber, Iris and White Musk',
        'fresh,powdery,white floral,floral,fruity',
        'Romantic MebyFleur de Santeis a Floral Fruity fragrance for women. Top notes are Pear, Pineapple, Violet and Grapefruit; middle notes are Peony, Jasmine and Lily-of-the-Valley; base notes are Cedar, Amber, Iris and White Musk.',
        4,
        1,
        NULL
      ),
(
        'Sensual-36069',
        'Sensual Fleur de Sante',
        'Sensual',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,tuberose,yellow floral,sweet',
        'SensualbyFleur de Santeis a Floral fragrance for women.Sensualwas launched in 2009.',
        5,
        2,
        NULL
      ),
(
        'Snow-Pearl-29849',
        'Snow Pearl Fleur de Sante',
        'Snow',
        'for women',
        NULL,
        NULL,
        'Ivy and Fruity Notes',
        'Floral Notes',
        'Coffee, Milk, White Musk and Sandalwood',
        'coffee,floral,musky,lactonic,warm spicy',
        'Snow PearlbyFleur de Santeis a Floral Fruity Gourmand fragrance for women. Top notes are Ivy and Fruity Notes; middle note is Floral Notes; base notes are Coffee, Milk, White Musk and Sandalwood.',
        4.36,
        14,
        NULL
      ),
(
        'Soiree-29839',
        'Soirée Fleur de Sante',
        'Soirée',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,balsamic,cinnamon,fruity',
        'SoiréebyFleur de Santeis a Amber Spicy fragrance for women.',
        4.33,
        6,
        NULL
      ),
(
        'Natures-Spring-Flurry-36243',
        'Natures Spring Flurry Fleur de Sante',
        'Natures',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,woody,marine,white floral,violet',
        'Natures Spring FlurrybyFleur de Santeis a Floral Aquatic fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Natures-Summer-Flurry-36242',
        'Natures Summer Flurry Fleur de Sante',
        'Natures',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,amber,woody,floral,fruity',
        'Natures Summer FlurrybyFleur de Santeis a Floral fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Natures-Winter-Flurry-36244',
        'Natures Winter Flurry Fleur de Sante',
        'Natures',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,floral,woody,vanilla',
        'Natures Winter FlurrybyFleur de Santeis a Chypre Fruity fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'B-Afric-85201',
        'B''Afric Flavia',
        'B''Afric',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Lemon and Black Currant',
        'Violet, Jasmine and Cyclamen',
        'Musk, Vetiver and Amber',
        'citrus,musky,powdery,aromatic,violet',
        'B''AfricbyFlaviais a fragrance for women and men. This is a new fragrance.B''Africwas launched in 2023. Top notes are Bergamot, Lemon and Black Currant; middle notes are Violet, Jasmine and Cyclamen; base notes are Musk, Vetiver and Amber.',
        4.1,
        31,
        NULL
      ),
(
        'Charming-Lady-85195',
        'Charming Lady Flavia',
        'Charming',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Bergamot, Orange and Mandarin Orange',
        'Ylang-Ylang, Turkish Rose and Jasmine',
        'Tonka Bean, Opoponax, Vanilla, Musk, Patchouli and Vetiver',
        'vanilla,sweet,amber,citrus,musky',
        'Charming LadybyFlaviais a fragrance for women. This is a new fragrance.Charming Ladywas launched in 2023. Top notes are Orange Blossom, Bergamot, Orange and Mandarin Orange; middle notes are Ylang-Ylang, Turkish Rose and Jasmine; base notes are Tonka Bean, Opoponax, Vanilla, Musk, Patchouli and Vetiver.',
        3.5,
        4,
        NULL
      ),
(
        'Fairy-Tale-85214',
        'Fairy Tale Flavia',
        'Fairy',
        'for women and men',
        NULL,
        NULL,
        'Spicy Notes, Woody Notes, Cognac and Sweet Notes',
        'Cinnamon and Tonka Bean',
        'Vanilla, Sandalwood and Praline',
        'warm spicy,woody,cinnamon,sweet,vanilla',
        'Fairy TalebyFlaviais a fragrance for women and men. Top notes are Spicy Notes, Woody Notes, Cognac and Sweet Notes; middle notes are Cinnamon and Tonka Bean; base notes are Vanilla, Sandalwood and Praline.',
        4.5,
        4,
        NULL
      ),
(
        'Fla-Via-Belle-85200',
        'Fla Via Belle Flavia',
        'Fla',
        'for women',
        NULL,
        NULL,
        'Black Currant and Pear',
        'Orange Blossom, Jasmine and Iris',
        'Tonka Bean, Patchouli and Vanilla',
        'white floral,fruity,vanilla,sweet,woody',
        'Fla Via BellebyFlaviais a fragrance for women. This is a new fragrance.Fla Via Bellewas launched in 2023. Top notes are Black Currant and Pear; middle notes are Orange Blossom, Jasmine and Iris; base notes are Tonka Bean, Patchouli and Vanilla.',
        3.5,
        4,
        NULL
      ),
(
        'Initial-85188',
        'Initial Flavia',
        'Initial',
        'for women and men',
        NULL,
        NULL,
        'Lavender, Nutmeg and Saffron',
        'Woodsy Notes',
        'Agarwood, Patchouli and Musk',
        'woody,oud,fresh spicy,lavender,warm spicy',
        'InitialbyFlaviais a Woody Chypre fragrance for women and men. Top notes are Lavender, Nutmeg and Saffron; middle note is Woodsy Notes; base notes are Agarwood, Patchouli and Musk.',
        3.58,
        31,
        NULL
      ),
(
        'Kiss-Me-for-Women-85198',
        'Kiss Me for Women Flavia',
        'Kiss',
        'for women',
        NULL,
        NULL,
        'Rose de Mai and Jasmine',
        'Tuberose and Narcissus',
        'Cedar, Woody Notes and Amber',
        'woody,white floral,amber,tuberose,animalic',
        'Kiss Me for WomenbyFlaviais a fragrance for women. This is a new fragrance.Kiss Me for Womenwas launched in 2023. Top notes are Rose de Mai and Jasmine; middle notes are Tuberose and Narcissus; base notes are Cedar, Woody Notes and Amber.',
        4.14,
        7,
        NULL
      ),
(
        'Koral-Pour-Homme-85191',
        'Koral Pour Homme Flavia',
        'Koral',
        'for men',
        NULL,
        NULL,
        'Passionfruit, Peach, Pear, Raspberry and Cassis',
        'White Flowers and Lily-of-the-Valley',
        'Vanilla, Sandalwood, Patchouli and Musk',
        'fruity,sweet,fresh,white floral,tropical',
        'Koral Pour HommebyFlaviais a fragrance for men. This is a new fragrance.Koral Pour Hommewas launched in 2023. Top notes are Passionfruit, Peach, Pear, Raspberry and Cassis; middle notes are White Flowers and Lily-of-the-Valley; base notes are Vanilla, Sandalwood, Patchouli and Musk.',
        3.8,
        44,
        NULL
      ),
(
        'L-Impression-85192',
        'L''Impression Flavia',
        'L''Impression',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Ginger and Bergamot',
        'Water Notes, Ambergris, Rosemary and Sage',
        'Ambergris, Labdanum and Amber',
        'citrus,amber,aromatic,aquatic,fresh spicy',
        'L''ImpressionbyFlaviais a fragrance for women and men. This is a new fragrance.L''Impressionwas launched in 2023. Top notes are Grapefruit, Ginger and Bergamot; middle notes are Water Notes, Ambergris, Rosemary and Sage; base notes are Ambergris, Labdanum and Amber.',
        4.22,
        55,
        NULL
      ),
(
        'Luxuria-Pour-Femme-85212',
        'Luxuria Pour Femme Flavia',
        'Luxuria',
        'for women',
        NULL,
        NULL,
        'Orange, Lemon and Pear',
        'Strawberry, Orchid, Rose and Passionfruit',
        'Patchouli, Vanilla and Praline',
        'sweet,fruity,patchouli,vanilla,citrus',
        'Luxuria Pour FemmebyFlaviais a fragrance for women. Top notes are Orange, Lemon and Pear; middle notes are Strawberry, Orchid, Rose and Passionfruit; base notes are Patchouli, Vanilla and Praline.',
        3.33,
        3,
        NULL
      ),
(
        'Marseille-France-Rouge-85221',
        'Marseille France Rouge Flavia',
        'Marseille',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon, Saffron, Incense, Nutmeg, Green Apple and White Pear',
        'Vanilla, Patchouli and Jasmine',
        'Tobacco, Amber, Guaiac Wood, Sandalwood, White Musk and Vetiver',
        'woody,warm spicy,amber,fruity,powdery',
        'Marseille France RougebyFlaviais a fragrance for women and men. Top notes are Cinnamon, Saffron, Incense, Nutmeg, Green Apple and White Pear; middle notes are Vanilla, Patchouli and Jasmine; base notes are Tobacco, Amber, Guaiac Wood, Sandalwood, White Musk and Vetiver.',
        4.33,
        9,
        NULL
      ),
(
        'Martine-Pour-Homme-85222',
        'Martine Pour Homme Flavia',
        'Martine',
        'for men',
        NULL,
        NULL,
        'Lavender, Ginger, Lemon and Mint',
        'Geranium, Cardamom and Apple',
        'Tonka Bean and Vetiver',
        'aromatic,warm spicy,fresh spicy,green,citrus',
        'Martine Pour HommebyFlaviais a fragrance for men. Top notes are Lavender, Ginger, Lemon and Mint; middle notes are Geranium, Cardamom and Apple; base notes are Tonka Bean and Vetiver.',
        5,
        1,
        NULL
      );
