
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Colour-Me-Pearl-23925',
        'Colour Me Pearl Milton Lloyd',
        'Colour',
        'for women',
        NULL,
        NULL,
        'Orange Blossom',
        'Jasmine and Patchouli',
        'Honey, Rose, Amber, Musk and Cedar',
        'white floral,woody,honey,sweet,rose',
        'Colour Me PearlbyMilton Lloydis a Floral Woody Musk fragrance for women. Top note is Orange Blossom; middle notes are Jasmine and Patchouli; base notes are Honey, Rose, Amber, Musk and Cedar.',
        3.97,
        31,
        NULL
      ),
(
        'Colour-Me-Pink-23921',
        'Colour Me Pink Milton Lloyd',
        'Colour',
        'for women',
        NULL,
        NULL,
        'Almond Blossom and White Rose',
        'Heliotrope, Lily and Geranium',
        'Vanilla and Musk',
        'floral,vanilla,rose,powdery,white floral',
        'Colour Me PinkbyMilton Lloydis a Floral fragrance for women. Top notes are Almond Blossom and White Rose; middle notes are Heliotrope, Lily and Geranium; base notes are Vanilla and Musk.',
        3.92,
        39,
        NULL
      ),
(
        'Colour-Me-Purple-23923',
        'Colour Me Purple Milton Lloyd',
        'Colour',
        'for women',
        NULL,
        NULL,
        'Watermelon and Bergamot',
        'Jasmine, Violet and Rose',
        'Patchouli, Oakmoss and Amber',
        'ozonic,aquatic,patchouli,woody,earthy',
        'Colour Me PurplebyMilton Lloydis a Chypre Floral fragrance for women. Top notes are Watermelon and Bergamot; middle notes are Jasmine, Violet and Rose; base notes are Patchouli, Oakmoss and Amber.',
        4.07,
        56,
        NULL
      ),
(
        'Colour-Me-Red-23922',
        'Colour Me Red Milton Lloyd',
        'Colour',
        'for women',
        NULL,
        NULL,
        'Freesia, Spicy Notes, Peony and Bergamot',
        'Red Berries, Carnation, Oakmoss, Violet and Jasmine',
        'Vetiver, Orris Root, Sandalwood and Vanilla',
        'floral,warm spicy,woody,fruity,fresh',
        'Colour Me RedbyMilton Lloydis a Chypre Floral fragrance for women. Top notes are Freesia, Spicy Notes, Peony and Bergamot; middle notes are Red Berries, Carnation, Oakmoss, Violet and Jasmine; base notes are Vetiver, Orris Root, Sandalwood and Vanilla.',
        3.58,
        31,
        NULL
      ),
(
        'Colour-Me-Silver-23920',
        'Colour Me Silver Milton Lloyd',
        'Colour',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Mandarin Orange and Melon',
        'Lavender, Thyme and Rosemary',
        'Patchouli, Tonka Bean, Musk and Vetiver',
        'citrus,aromatic,fresh spicy,woody,patchouli',
        'Colour Me SilverbyMilton Lloydis a Woody Aromatic fragrance for men. Top notes are Grapefruit, Mandarin Orange and Melon; middle notes are Lavender, Thyme and Rosemary; base notes are Patchouli, Tonka Bean, Musk and Vetiver.',
        4.07,
        70,
        NULL
      ),
(
        'Colour-Me-Sky-Blue-23924',
        'Colour Me Sky Blue Milton Lloyd',
        'Colour',
        'for women',
        NULL,
        NULL,
        'Freesia, Lemon, Peach and Cherry',
        'Lily-of-the-Valley, Rose and Jasmine',
        'Resins, Musk and Amber',
        'amber,floral,white floral,musky,rose',
        'Colour Me Sky BluebyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Freesia, Lemon, Peach and Cherry; middle notes are Lily-of-the-Valley, Rose and Jasmine; base notes are Resins, Musk and Amber.',
        3.68,
        31,
        NULL
      ),
(
        'Colour-Me-White-23963',
        'Colour Me White Milton Lloyd',
        'Colour',
        'for men',
        NULL,
        NULL,
        'Bergamot, Green Tea and Basil',
        'Sea Notes, Lemon and Cardamom',
        'Leather, Woody Notes, Vetiver, Amber and Musk',
        'aromatic,citrus,woody,marine,fresh spicy',
        'Colour Me WhitebyMilton Lloydis a Aromatic Fougere fragrance for men. Top notes are Bergamot, Green Tea and Basil; middle notes are Sea Notes, Lemon and Cardamom; base notes are Leather, Woody Notes, Vetiver, Amber and Musk.',
        4.2,
        60,
        NULL
      ),
(
        '331-Homme-23928',
        '331 Homme Milton Lloyd',
        '331',
        'for men',
        NULL,
        NULL,
        'Green Notes and Citruses',
        'Gardenia, Green Pepper, Ginger and Fruity Notes',
        'Musk, Sandalwood and Incense',
        'green,warm spicy,woody,citrus,white floral',
        '331 HommebyMilton Lloydis a Floral Woody Musk fragrance for men. Top notes are Green Notes and Citruses; middle notes are Gardenia, Green Pepper, Ginger and Fruity Notes; base notes are Musk, Sandalwood and Incense.',
        4.37,
        30,
        NULL
      ),
(
        'Aroma-di-Jean-23945',
        'Aroma di Jean Milton Lloyd',
        'Aroma',
        'for men',
        NULL,
        NULL,
        'Lemon, Green Notes, Bergamot and Watermelon',
        'Sea Notes, Water Lily and Violet',
        'Patchouli and Cedar',
        'citrus,aquatic,aromatic,marine,woody',
        'Aroma di JeanbyMilton Lloydis a Aromatic Aquatic fragrance for men. Top notes are Lemon, Green Notes, Bergamot and Watermelon; middle notes are Sea Notes, Water Lily and Violet; base notes are Patchouli and Cedar.',
        4.15,
        34,
        NULL
      ),
(
        'Calibre-Senses-for-Men-43003',
        'Calibre Senses for Men Milton Lloyd',
        'Calibre',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,violet,musky,woody,fresh spicy',
        'Calibre Senses for MenbyMilton Lloydis a Amber Spicy fragrance for men.',
        3.5,
        4,
        NULL
      ),
(
        'Chelsea-Flowers-23956',
        'Chelsea Flowers Milton Lloyd',
        'Chelsea',
        'for women',
        NULL,
        NULL,
        'Gardenia, Lily-of-the-Valley and Jasmine',
        'Powdery Notes and Fruity Notes',
        'Musk and Woody Notes',
        'white floral,powdery,musky,woody,fresh',
        'Chelsea FlowersbyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Gardenia, Lily-of-the-Valley and Jasmine; middle notes are Powdery Notes and Fruity Notes; base notes are Musk and Woody Notes.',
        4.08,
        12,
        NULL
      ),
(
        'Futurity-23967',
        'Futurity Milton Lloyd',
        'Futurity',
        'for women',
        NULL,
        NULL,
        'Freesia, Sage and Mandarin Orange',
        'Narcissus, Marigold, Rose, White Lily, Lily-of-the-Valley and Jasmine',
        'Sandalwood, Amber, Patchouli and Musk',
        'floral,aromatic,yellow floral,woody,balsamic',
        'FuturitybyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Freesia, Sage and Mandarin Orange; middle notes are Narcissus, Marigold, Rose, White Lily, Lily-of-the-Valley and Jasmine; base notes are Sandalwood, Amber, Patchouli and Musk.',
        3.9,
        10,
        NULL
      ),
(
        'Futurity-Pour-Homme-23968',
        'Futurity Pour Homme Milton Lloyd',
        'Futurity',
        'for men',
        NULL,
        NULL,
        'Green Notes',
        'Fruity Notes, Floral Notes and Spicy Notes',
        'Woody Notes and Amber',
        'amber,floral,fruity,green,woody',
        'Futurity Pour HommebyMilton Lloydis a Aromatic fragrance for men. Top note is Green Notes; middle notes are Fruity Notes, Floral Notes and Spicy Notes; base notes are Woody Notes and Amber.',
        3.4,
        10,
        NULL
      ),
(
        'Grasse-Experience-23969',
        'Grasse Experience Milton Lloyd',
        'Grasse',
        'for women',
        NULL,
        NULL,
        'Green Notes and Bergamot',
        'Chamomile, Rose, Geranium, Jasmine, Cloves and Cumin',
        'Patchouli, Musk, Vetiver and Castoreum',
        'fresh spicy,aromatic,woody,warm spicy,rose',
        'Grasse ExperiencebyMilton Lloydis a Chypre Floral fragrance for women. Top notes are Green Notes and Bergamot; middle notes are Chamomile, Rose, Geranium, Jasmine, Cloves and Cumin; base notes are Patchouli, Musk, Vetiver and Castoreum.',
        4.07,
        42,
        NULL
      ),
(
        'Henley-23971',
        'Henley Milton Lloyd',
        'Henley',
        'for men',
        NULL,
        NULL,
        'Bergamot, Cardamom, Galbanum and Black Pepper',
        'Lily, Jasmine, Nutmeg and Cloves',
        'Musk, Woody Notes and Moss',
        'fresh spicy,warm spicy,white floral,aromatic,woody',
        'HenleybyMilton Lloydis a Aromatic Spicy fragrance for men. Top notes are Bergamot, Cardamom, Galbanum and Black Pepper; middle notes are Lily, Jasmine, Nutmeg and Cloves; base notes are Musk, Woody Notes and Moss.',
        4.25,
        4,
        NULL
      ),
(
        'Jean-Yves-To-Go-23973',
        'Jean Yves To Go Milton Lloyd',
        'Jean',
        'for women',
        NULL,
        NULL,
        'Gardenia, Spicy Notes and Floral Notes',
        'Fruity Notes and Oakmoss',
        'Patchouli, Vanilla, Woody Notes and Sandalwood',
        'woody,patchouli,fruity,warm spicy,earthy',
        'Jean Yves To GobyMilton Lloydis a Chypre Fruity fragrance for women. Top notes are Gardenia, Spicy Notes and Floral Notes; middle notes are Fruity Notes and Oakmoss; base notes are Patchouli, Vanilla, Woody Notes and Sandalwood.',
        2.92,
        12,
        NULL
      ),
(
        'Joe-Boy-23974',
        'Joe Boy Milton Lloyd',
        'Joe',
        'for men',
        NULL,
        NULL,
        'Citruses, Apple and Cranberry',
        'Green Notes, Lavender, Mint and Floral Notes',
        'Woody Notes and Musk',
        'green,fruity,citrus,fresh,fresh spicy',
        'Joe BoybyMilton Lloydis a Woody Spicy fragrance for men. Top notes are Citruses, Apple and Cranberry; middle notes are Green Notes, Lavender, Mint and Floral Notes; base notes are Woody Notes and Musk.',
        3.67,
        3,
        NULL
      ),
(
        'Joe-Girl-23975',
        'Joe Girl Milton Lloyd',
        'Joe',
        'for women',
        NULL,
        NULL,
        'Watery Notes and Fruity Notes',
        'White Flowers and Green Notes',
        'Woody Notes and Musk',
        'aquatic,fruity,green,white floral,fresh',
        'Joe GirlbyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Watery Notes and Fruity Notes; middle notes are White Flowers and Green Notes; base notes are Woody Notes and Musk.',
        3.62,
        8,
        NULL
      ),
(
        'JoJo-23976',
        'JoJo Milton Lloyd',
        'JoJo',
        'for women',
        NULL,
        NULL,
        'Floral Notes, Fruity Notes, Apricot and Bergamot',
        'Powdery Notes, Marigold and Musk',
        'Oriental notes, Vanilla, Musk, Sandalwood and Woody Notes',
        'powdery,woody,warm spicy,floral,sweet',
        'JoJobyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Floral Notes, Fruity Notes, Apricot and Bergamot; middle notes are Powdery Notes, Marigold and Musk; base notes are Oriental notes, Vanilla, Musk, Sandalwood and Woody Notes.',
        3.97,
        31,
        NULL
      ),
(
        'Love-23983',
        'Love Milton Lloyd',
        'Love',
        'for women',
        NULL,
        NULL,
        'Water Lily, Citruses, Lotus and Yellow Narcissus',
        'Melon, Tuberose, Violet, Pineapple and Orange Blossom',
        'Mimosa, Woody Notes and Musk',
        'floral,fresh,powdery,yellow floral,aquatic',
        'LovebyMilton Lloydis a Floral fragrance for women. Top notes are Water Lily, Citruses, Lotus and Yellow Narcissus; middle notes are Melon, Tuberose, Violet, Pineapple and Orange Blossom; base notes are Mimosa, Woody Notes and Musk.',
        4,
        6,
        NULL
      ),
(
        'Love-You-23984',
        'Love You Milton Lloyd',
        'Love',
        'for women',
        NULL,
        NULL,
        'Fruity Notes, Geranium, Green Notes and Citruses',
        'White Flowers and Jasmine',
        'Musk and Woody Notes',
        'white floral,fruity,fresh spicy,musky,aromatic',
        'Love YoubyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Fruity Notes, Geranium, Green Notes and Citruses; middle notes are White Flowers and Jasmine; base notes are Musk and Woody Notes.',
        4.15,
        26,
        NULL
      ),
(
        'Loves-Me-Loves-Me-Not-23985',
        'Loves Me Loves Me Not Milton Lloyd',
        'Loves',
        'for women',
        NULL,
        NULL,
        'Green Notes, Big Strawberry, Blood Grapefruit and Violet Leaf',
        'Gardenia, Violet and Jasmine',
        'White Woods, Vanilla and Musk',
        'green,white floral,fruity,sweet,powdery',
        'Loves Me Loves Me NotbyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Green Notes, Big Strawberry, Blood Grapefruit and Violet Leaf; middle notes are Gardenia, Violet and Jasmine; base notes are White Woods, Vanilla and Musk.',
        4.12,
        17,
        NULL
      ),
(
        'Me-Too-23986',
        'Me Too Milton Lloyd',
        'Me',
        'for women',
        NULL,
        NULL,
        'Neroli, Orange and Bergamot',
        'Rose and Jasmine',
        'Oriental notes and Amber',
        'amber,citrus,warm spicy,white floral,fresh spicy',
        'Me ToobyMilton Lloydis a Amber Floral fragrance for women. Top notes are Neroli, Orange and Bergamot; middle notes are Rose and Jasmine; base notes are Oriental notes and Amber.',
        4.05,
        20,
        NULL
      ),
(
        'Me-Too-Homme-23987',
        'Me Too Homme Milton Lloyd',
        'Me',
        'for men',
        NULL,
        NULL,
        'Spicy Notes, Wild Berries, Bergamot, Lime, Lemon and Orange',
        'Lily, Tobacco, Hawthorn and Herbal Notes',
        'Vanilla, Precious Woods and Amber',
        'citrus,woody,vanilla,white floral,sweet',
        'Me Too HommebyMilton Lloydis a Amber Fougere fragrance for men. Top notes are Spicy Notes, Wild Berries, Bergamot, Lime, Lemon and Orange; middle notes are Lily, Tobacco, Hawthorn and Herbal Notes; base notes are Vanilla, Precious Woods and Amber.',
        4,
        23,
        NULL
      ),
(
        'Miss-Tutu-23989',
        'Miss Tutu Milton Lloyd',
        'Miss',
        'for women',
        NULL,
        NULL,
        'Fruity Notes, Watery Notes, Lily-of-the-Valley and Bergamot',
        'Jasmine, Rose and Vetiver',
        'Patchouli, Vanilla and Amber',
        'white floral,patchouli,woody,fresh,fruity',
        'Miss TutubyMilton Lloydis a Chypre Fruity fragrance for women. Top notes are Fruity Notes, Watery Notes, Lily-of-the-Valley and Bergamot; middle notes are Jasmine, Rose and Vetiver; base notes are Patchouli, Vanilla and Amber.',
        4.17,
        35,
        NULL
      ),
(
        'Papagayo-23995',
        'Papagayo Milton Lloyd',
        'Papagayo',
        'for women',
        NULL,
        NULL,
        'Carnation and Jasmine',
        'Spicy Notes, Ylang-Ylang, Rose and Geranium',
        'Moss, Vanilla, Musk, Vetiver, Amber and Sandalwood',
        'woody,warm spicy,aromatic,rose,powdery',
        'PapagayobyMilton Lloydis a Chypre Floral fragrance for women. Top notes are Carnation and Jasmine; middle notes are Spicy Notes, Ylang-Ylang, Rose and Geranium; base notes are Moss, Vanilla, Musk, Vetiver, Amber and Sandalwood.',
        4.2,
        15,
        NULL
      ),
(
        'Poker-23996',
        'Poker Milton Lloyd',
        'Poker',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Pineapple and Lemon',
        'Jasmine, Iris and Hyacinth',
        'Patchouli, White Musk, Vetiver and Amber',
        'sweet,musky,woody,earthy,patchouli',
        'PokerbyMilton Lloydis a Chypre Floral fragrance for women. Top notes are Pink Pepper, Pineapple and Lemon; middle notes are Jasmine, Iris and Hyacinth; base notes are Patchouli, White Musk, Vetiver and Amber.',
        3.96,
        28,
        NULL
      ),
(
        'Popcorn-Boys-23997',
        'Popcorn Boys Milton Lloyd',
        'Popcorn',
        'for men',
        NULL,
        NULL,
        'Apple and Herbal Notes',
        'Aldehydes, Pine Tree, Jasmine and Cedar',
        'Patchouli, White Musk and Vetiver',
        'woody,green,fresh,fruity,aromatic',
        'Popcorn BoysbyMilton Lloydis a Woody Aromatic fragrance for men. Top notes are Apple and Herbal Notes; middle notes are Aldehydes, Pine Tree, Jasmine and Cedar; base notes are Patchouli, White Musk and Vetiver.',
        3.38,
        13,
        NULL
      ),
(
        'Popcorn-Girls-23998',
        'Popcorn Girls Milton Lloyd',
        'Popcorn',
        'for women',
        NULL,
        NULL,
        'Blood Orange and Coriander',
        'Violet and Jasmine',
        'Vanilla and Sandalwood',
        'powdery,vanilla,woody,citrus,violet',
        'Popcorn GirlsbyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Blood Orange and Coriander; middle notes are Violet and Jasmine; base notes are Vanilla and Sandalwood.',
        4,
        8,
        NULL
      ),
(
        'Pure-Gold-23999',
        'Pure Gold Milton Lloyd',
        'Pure',
        'for men',
        NULL,
        NULL,
        'Blood Mandarin, Grapefruit and Peppermint',
        'Cinnamon, Spicy Notes and Rose',
        'Leather, Amber, Patchouli and White Woods',
        'warm spicy,citrus,amber,leather,cinnamon',
        'Pure GoldbyMilton Lloydis a Amber Fougere fragrance for men. Top notes are Blood Mandarin, Grapefruit and Peppermint; middle notes are Cinnamon, Spicy Notes and Rose; base notes are Leather, Amber, Patchouli and White Woods.',
        3.74,
        27,
        NULL
      ),
(
        'Pure-Gold-Ladies-24000',
        'Pure Gold Ladies Milton Lloyd',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Citruses, Neroli and Raspberry',
        'Jasmine, White Flowers, Lily and Rose',
        'White Honey, Patchouli and Musk',
        'white floral,honey,sweet,citrus,floral',
        'Pure Gold LadiesbyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Citruses, Neroli and Raspberry; middle notes are Jasmine, White Flowers, Lily and Rose; base notes are White Honey, Patchouli and Musk.',
        3.92,
        25,
        NULL
      ),
(
        'Red-Shoe-24001',
        'Red Shoe Milton Lloyd',
        'Red',
        'for women',
        NULL,
        NULL,
        'Pear and Green Notes',
        'Orchid and Rose',
        'Patchouli, Amber, Caramel and Sandalwood',
        'woody,sweet,patchouli,floral,amber',
        'Red ShoebyMilton Lloydis a Floral Fruity Gourmand fragrance for women. Top notes are Pear and Green Notes; middle notes are Orchid and Rose; base notes are Patchouli, Amber, Caramel and Sandalwood.',
        3.68,
        19,
        NULL
      ),
(
        'She-JYUK-24002',
        'She JYUK Milton Lloyd',
        'She',
        'for women',
        NULL,
        NULL,
        'Citruses and Cardamom',
        'Aldehydes and Jasmine',
        'Sandalwood, Amber and Musk',
        'fresh,citrus,aldehydic,warm spicy,powdery',
        'She JYUKbyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Citruses and Cardamom; middle notes are Aldehydes and Jasmine; base notes are Sandalwood, Amber and Musk.',
        3,
        7,
        NULL
      ),
(
        'Spirit-of-Heaven-24003',
        'Spirit of Heaven Milton Lloyd',
        'Spirit',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Cardamom and Bergamot',
        'Rose and Jasmine',
        'Praline, Patchouli and Vanilla',
        'sweet,warm spicy,patchouli,rose,vanilla',
        'Spirit of HeavenbyMilton Lloydis a Amber Vanilla fragrance for women. Top notes are Passionfruit, Cardamom and Bergamot; middle notes are Rose and Jasmine; base notes are Praline, Patchouli and Vanilla.',
        3.45,
        42,
        NULL
      ),
(
        'Spirit-of-Heaven-Homme-24004',
        'Spirit of Heaven Homme Milton Lloyd',
        'Spirit',
        'for men',
        NULL,
        NULL,
        'Pine Tree and Herbal Notes',
        'Caramel and Spicy Notes',
        'Vanilla, Amber, Musk and Woody Notes',
        'woody,caramel,sweet,vanilla,green',
        'Spirit of Heaven HommebyMilton Lloydis a Amber Woody fragrance for men. Top notes are Pine Tree and Herbal Notes; middle notes are Caramel and Spicy Notes; base notes are Vanilla, Amber, Musk and Woody Notes.',
        4.23,
        66,
        NULL
      ),
(
        'Spirit-of-Shadow-24005',
        'Spirit of Shadow Milton Lloyd',
        'Spirit',
        'for women',
        NULL,
        NULL,
        'Rose and Bergamot',
        'Peach, White Flowers, Hibiscus and Jasmine',
        'Vanilla, Musk and Sandalwood',
        'white floral,powdery,floral,rose,vanilla',
        'Spirit of ShadowbyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Rose and Bergamot; middle notes are Peach, White Flowers, Hibiscus and Jasmine; base notes are Vanilla, Musk and Sandalwood.',
        4.18,
        17,
        NULL
      ),
(
        'Stars-24006',
        'Stars Milton Lloyd',
        'Stars',
        'for women',
        NULL,
        NULL,
        'Orange Blossom and Citruses',
        'Jasmine, Rose, Violet and Spicy Notes',
        'White Amber, Sandalwood and Patchouli',
        'white floral,woody,amber,powdery,citrus',
        'StarsbyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Orange Blossom and Citruses; middle notes are Jasmine, Rose, Violet and Spicy Notes; base notes are White Amber, Sandalwood and Patchouli.',
        3.82,
        34,
        NULL
      ),
(
        'Success-24007',
        'Success Milton Lloyd',
        'Success',
        'for women',
        NULL,
        NULL,
        'Watermelon, Bergamot, Osmanthus and Cassis',
        'Sea Notes, Water Lily, Jasmine and Rose',
        'Musk, Amber and Woody Notes',
        'aquatic,floral,ozonic,aromatic,fruity',
        'SuccessbyMilton Lloydis a Floral Aquatic fragrance for women. Top notes are Watermelon, Bergamot, Osmanthus and Cassis; middle notes are Sea Notes, Water Lily, Jasmine and Rose; base notes are Musk, Amber and Woody Notes.',
        3.29,
        14,
        NULL
      ),
(
        'Success-Hommes-24008',
        'Success Hommes Milton Lloyd',
        'Success',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lime, Ginger, Nutmeg, Cardamom and Cloves',
        'Herbal Notes and Rosemary',
        'Vetiver, Musk and Cedar',
        'citrus,aromatic,fresh spicy,woody,green',
        'Success HommesbyMilton Lloydis a Aromatic Aquatic fragrance for men. Top notes are Bergamot, Lime, Ginger, Nutmeg, Cardamom and Cloves; middle notes are Herbal Notes and Rosemary; base notes are Vetiver, Musk and Cedar.',
        4,
        21,
        NULL
      ),
(
        'Summer-Flowers-24009',
        'Summer Flowers Milton Lloyd',
        'Summer',
        'for women',
        NULL,
        NULL,
        'Violet, Pepper, Aldehydes and Mandarin Orange',
        'Violet, Lily-of-the-Valley and Lilac',
        'Musk and Cedar',
        'fresh,powdery,floral,violet,musky',
        'Summer FlowersbyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Violet, Pepper, Aldehydes and Mandarin Orange; middle notes are Violet, Lily-of-the-Valley and Lilac; base notes are Musk and Cedar.',
        4.11,
        37,
        NULL
      ),
(
        'Summer-Sky-24010',
        'Summer Sky Milton Lloyd',
        'Summer',
        'for women',
        NULL,
        NULL,
        'Citruses, Bellflower and Apple',
        'Bamboo, Jasmine and White Rose',
        'Cedar, Amber and Musk',
        'woody,citrus,fresh,floral,white floral',
        'Summer SkybyMilton Lloydis a Floral Fruity fragrance for women. Top notes are Citruses, Bellflower and Apple; middle notes are Bamboo, Jasmine and White Rose; base notes are Cedar, Amber and Musk.',
        3.95,
        20,
        NULL
      ),
(
        'Summertime-24011',
        'Summertime Milton Lloyd',
        'Summertime',
        'for women',
        NULL,
        NULL,
        'Green Tea and Bergamot',
        'Freesia, Jasmine, Orchid and Rose',
        'Patchouli and Musk',
        'floral,patchouli,white floral,rose,musky',
        'SummertimebyMilton Lloydis a Floral Woody Musk fragrance for women. Top notes are Green Tea and Bergamot; middle notes are Freesia, Jasmine, Orchid and Rose; base notes are Patchouli and Musk.',
        4.1,
        49,
        NULL
      ),
(
        'The-Man-Cobalt-24015',
        'The Man Cobalt Milton Lloyd',
        'The',
        'for men',
        NULL,
        NULL,
        'Lavender, Bergamot and Lemon',
        'Violet and Cedar',
        'Leather, Musk and Moss',
        'powdery,violet,woody,citrus,leather',
        'The Man CobaltbyMilton Lloydis a Aromatic Fougere fragrance for men. Top notes are Lavender, Bergamot and Lemon; middle notes are Violet and Cedar; base notes are Leather, Musk and Moss.',
        4.47,
        83,
        NULL
      ),
(
        'Top-Gun-24016',
        'Top Gun Milton Lloyd',
        'Top',
        'for men',
        NULL,
        NULL,
        'Lavender, Mandarin Orange and Sage',
        'Oakmoss and Cedar',
        'Amber and Musk',
        'mossy,woody,musky,aromatic,earthy',
        'Top GunbyMilton Lloydis a Woody Aromatic fragrance for men. Top notes are Lavender, Mandarin Orange and Sage; middle notes are Oakmoss and Cedar; base notes are Amber and Musk.',
        4,
        12,
        NULL
      ),
(
        'Top-Gun-2-24017',
        'Top Gun 2 Milton Lloyd',
        'Top',
        'for men',
        NULL,
        NULL,
        'Citruses and Herbal Notes',
        'Spicy Notes, Plum and Floral Notes',
        'Vanilla, Woody Notes, Musk and Amber',
        'citrus,green,vanilla,woody,powdery',
        'Top Gun 2byMilton Lloydis a Amber Fougere fragrance for men. Top notes are Citruses and Herbal Notes; middle notes are Spicy Notes, Plum and Floral Notes; base notes are Vanilla, Woody Notes, Musk and Amber.',
        4.18,
        17,
        NULL
      ),
(
        'Tutu-Woman-24019',
        'Tutu Woman Milton Lloyd',
        'Tutu',
        'for women',
        NULL,
        NULL,
        'Orange, Bergamot and Lemon',
        'Cloves, Jasmine, Ylang-Ylang, Rose, Coriander, Pepper and Lily-of-the-Valley',
        'Woody Notes and Vanilla',
        'citrus,warm spicy,white floral,woody,fresh spicy',
        'Tutu WomanbyMilton Lloydis a Amber Spicy fragrance for women. Top notes are Orange, Bergamot and Lemon; middle notes are Cloves, Jasmine, Ylang-Ylang, Rose, Coriander, Pepper and Lily-of-the-Valley; base notes are Woody Notes and Vanilla.',
        4.3,
        40,
        NULL
      ),
(
        'No-10-by-Mojo-66632',
        'No 10 by Mojo Milton Lloyd',
        'No',
        'for men',
        NULL,
        NULL,
        'Aromatic Spices and Brazilian Rosewood',
        'Agarwood (Oud) and Cardamom',
        'Amber, Sandalwood, Tonka Bean and Vetiver',
        'warm spicy,woody,amber,oud,aromatic',
        'No 10 by MojobyMilton Lloydis a Woody Aromatic fragrance for men.No 10 by Mojowas launched in 2021. Top notes are Aromatic Spices and Brazilian Rosewood; middle notes are Agarwood (Oud) and Cardamom; base notes are Amber, Sandalwood, Tonka Bean and Vetiver.',
        4.06,
        89,
        NULL
      ),
(
        'No-12-by-Emilie-36401',
        'No 12 by Emilie Milton Lloyd',
        'No',
        'for women',
        NULL,
        NULL,
        'Ambrette (Musk Mallow), Orange Blossom and Apple',
        'Bulgarian Rose, Peony and Litchi',
        'Patchouli, Musk and Sandalwood',
        'floral,musky,rose,fresh,woody',
        'No 12 by EmiliebyMilton Lloydis a Chypre Floral fragrance for women.No 12 by Emiliewas launched in 2014. Top notes are Ambrette (Musk Mallow), Orange Blossom and Apple; middle notes are Bulgarian Rose, Peony and Litchi; base notes are Patchouli, Musk and Sandalwood.',
        5,
        2,
        NULL
      ),
(
        'No-3-by-Jean-Marie-36398',
        'No 3 by Jean-Marie Milton Lloyd',
        'No',
        'for men',
        NULL,
        NULL,
        'Incense, Grapefruit and Coriander',
        'Black Pepper, Cardamom and Nutmeg',
        'Vetiver, Patchouli and Amber',
        'fresh spicy,warm spicy,aromatic,amber,woody',
        'No 3 by Jean-MariebyMilton Lloydis a Woody Spicy fragrance for men.No 3 by Jean-Mariewas launched in 2014. Top notes are Incense, Grapefruit and Coriander; middle notes are Black Pepper, Cardamom and Nutmeg; base notes are Vetiver, Patchouli and Amber.',
        3.75,
        8,
        NULL
      ),
(
        'No-4-by-Natalie-36400',
        'No 4 by Natalie Milton Lloyd',
        'No',
        'for women',
        NULL,
        NULL,
        'Iris and Red Berries',
        'Floral Notes and Cedar',
        'Vanilla, Amber and Woodsy Notes',
        'woody,vanilla,powdery,iris,amber',
        'No 4 by NataliebyMilton Lloydis a Amber Floral fragrance for women.No 4 by Nataliewas launched in 2014. Top notes are Iris and Red Berries; middle notes are Floral Notes and Cedar; base notes are Vanilla, Amber and Woodsy Notes.',
        3.43,
        7,
        NULL
      ),
(
        'No-6-by-Raphael-36399',
        'No 6 by Raphael Milton Lloyd',
        'No',
        'for men',
        NULL,
        NULL,
        'Vetiver, Black Pepper, Mandarin Orange, Lemon and Mint',
        'Grapefruit, Cedar, Geranium, Nutmeg and Labdanum',
        'Incense, Cardamom, Precious Woods and Musk',
        'citrus,fresh spicy,aromatic,woody,warm spicy',
        'No 6 by RaphaelbyMilton Lloydis a Woody Aromatic fragrance for men.No 6 by Raphaelwas launched in 2014. Top notes are Vetiver, Black Pepper, Mandarin Orange, Lemon and Mint; middle notes are Grapefruit, Cedar, Geranium, Nutmeg and Labdanum; base notes are Incense, Cardamom, Precious Woods and Musk.',
        4.6,
        15,
        NULL
      ),
(
        'No-9-Victor-58565',
        'No. 9 Victor Milton Lloyd',
        'No.',
        'for men',
        NULL,
        NULL,
        'Fruity Notes and Citruses',
        'Woody Notes and Floral Notes',
        'Oakmoss, Musk and Vanilla',
        'fruity,citrus,woody,sweet,mossy',
        'No. 9 VictorbyMilton Lloydis a Citrus fragrance for men. Top notes are Fruity Notes and Citruses; middle notes are Woody Notes and Floral Notes; base notes are Oakmoss, Musk and Vanilla.',
        4.2,
        186,
        NULL
      ),
(
        'Absolute-Santal-51981',
        'Absolute Santal Mine Perfume Lab',
        'Absolute',
        'for women and men',
        NULL,
        NULL,
        'Sandalwood',
        'Sandalwood',
        'Sandalwood',
        'woody,powdery,warm spicy',
        'Absolute SantalbyMine Perfume Labis a Woody fragrance for women and men.Absolute Santalwas launched in 2016. Top note is Sandalwood; middle note is Sandalwood; base note is Sandalwood.',
        3.22,
        18,
        NULL
      ),
(
        'Absque-51898',
        'Absque Mine Perfume Lab',
        'Absque',
        'for women and men',
        NULL,
        NULL,
        'Citruses and Ozonic notes',
        'Amaretto and Floral Notes',
        'Musk and Cedar',
        'almond,fruity,floral,citrus,musky',
        'AbsquebyMine Perfume Labis a Aromatic fragrance for women and men.Absquewas launched in 2017. Top notes are Citruses and Ozonic notes; middle notes are Amaretto and Floral Notes; base notes are Musk and Cedar.',
        3.14,
        7,
        NULL
      ),
(
        'Acqua-di-Iris-Talco-52097',
        'Acqua di Iris & Talco Mine Perfume Lab',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Iris',
        'Powdery Notes and Tonka Bean',
        'powdery,iris,citrus,violet,earthy',
        'Acqua di Iris & TalcobyMine Perfume Labis a Floral fragrance for women and men.Acqua di Iris & Talcowas launched in 2016. Top note is Citruses; middle note is Iris; base notes are Powdery Notes and Tonka Bean.',
        3.25,
        8,
        NULL
      ),
(
        'Acqua-di-Talco-Panna-51990',
        'Acqua di Talco & Panna Mine Perfume Lab',
        'Acqua',
        'for women and men',
        NULL,
        NULL,
        'White Flowers',
        'Powdery Notes',
        'Tonka Bean, Iris and Vanilla',
        'vanilla,white floral,powdery,amber,iris',
        'Acqua di Talco & PannabyMine Perfume Labis a Amber Vanilla fragrance for women and men.Acqua di Talco & Pannawas launched in 2016. Top note is White Flowers; middle note is Powdery Notes; base notes are Tonka Bean, Iris and Vanilla.',
        3.73,
        11,
        NULL
      ),
(
        'Alleria-51901',
        'Alleria Mine Perfume Lab',
        'Alleria',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes',
        'Sea Notes',
        'Musk',
        'marine,aromatic,musky,salty,aquatic',
        'AlleriabyMine Perfume Labis a Aromatic Aquatic fragrance for women and men.Alleriawas launched in 2017. Top note is Sea Notes; middle note is Sea Notes; base note is Musk.',
        3.61,
        18,
        NULL
      ),
(
        'Amberstone-52094',
        'Amberstone Mine Perfume Lab',
        'Amberstone',
        'for women and men',
        NULL,
        NULL,
        'Amber',
        'Amber',
        'Amber',
        'amber',
        'AmberstonebyMine Perfume Labis a Amber fragrance for women and men.Amberstonewas launched in 2013. Top note is Amber; middle note is Amber; base note is Amber.',
        3.25,
        4,
        NULL
      ),
(
        'Ambre-Cafe-51987',
        'Ambre Cafe'' Mine Perfume Lab',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes',
        'Rose and Coffee',
        'White Musk, Amber and Vanilla',
        'musky,rose,amber,powdery,coffee',
        'Ambre Cafe''byMine Perfume Labis a fragrance for women and men.Ambre Cafe''was launched in 2018. Top note is Floral Notes; middle notes are Rose and Coffee; base notes are White Musk, Amber and Vanilla.',
        3.71,
        31,
        NULL
      ),
(
        'Arche-65975',
        'Arché Mine Perfume Lab',
        'Arché',
        'for women and men',
        NULL,
        NULL,
        'Violet',
        'Iris',
        'Leather, Virginia Cedar, Sandalwood, Papyrus and Amber',
        'woody,powdery,violet,leather,iris',
        'ArchébyMine Perfume Labis a fragrance for women and men.Archéwas launched in 2020. Top note is Violet; middle note is Iris; base notes are Leather, Virginia Cedar, Sandalwood, Papyrus and Amber.',
        3.97,
        29,
        NULL
      ),
(
        'Brise-d-Agadir-51899',
        'Brise d''Agadir Mine Perfume Lab',
        'Brise',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Grapefruit and Bergamot',
        'Cinnamon, Nutmeg, Paprika, Red Berries and Saffron',
        'Vanilla, Tobacco, Leather and Vetiver',
        'warm spicy,cinnamon,fresh spicy,sweet,citrus',
        'Brise d''AgadirbyMine Perfume Labis a Aromatic Spicy fragrance for women and men.Brise d''Agadirwas launched in 2015. Top notes are Pink Pepper, Grapefruit and Bergamot; middle notes are Cinnamon, Nutmeg, Paprika, Red Berries and Saffron; base notes are Vanilla, Tobacco, Leather and Vetiver.',
        3.55,
        20,
        NULL
      ),
(
        'Carme-76516',
        'Carme'' Mine Perfume Lab',
        'Carme''',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Bitter Almond and Mint',
        'Egyptian Jasmine, Tobacco Leaf and Cedar',
        'Ambergris, Musk and Woody Notes',
        'amber,animalic,tobacco,almond,white floral',
        'Carme''byMine Perfume Labis a fragrance for women and men. This is a new fragrance.Carme''was launched in 2022. Top notes are Saffron, Bitter Almond and Mint; middle notes are Egyptian Jasmine, Tobacco Leaf and Cedar; base notes are Ambergris, Musk and Woody Notes.',
        3.73,
        26,
        NULL
      ),
(
        'Carnal-Tuberosa-51905',
        'Carnal Tuberosa Mine Perfume Lab',
        'Carnal',
        'for women',
        NULL,
        NULL,
        'Tuberose',
        'Tuberose',
        'Tuberose',
        'tuberose,white floral,animalic,green',
        'Carnal TuberosabyMine Perfume Labis a Floral fragrance for women.Carnal Tuberosawas launched in 2015. Top note is Tuberose; middle note is Tuberose; base note is Tuberose.',
        3.04,
        23,
        NULL
      ),
(
        'Cedrum-Wood-51978',
        'Cedrum Wood Mine Perfume Lab',
        'Cedrum',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Lemon',
        'Red Fruits',
        'Vanilla, Cedar and Musk',
        'fruity,citrus,vanilla,powdery,sweet',
        'Cedrum WoodbyMine Perfume Labis a Woody fragrance for women and men.Cedrum Woodwas launched in 2016. Top notes are Bergamot and Lemon; middle note is Red Fruits; base notes are Vanilla, Cedar and Musk.',
        3.38,
        8,
        NULL
      ),
(
        'Chileme-51897',
        'Chileme Mine Perfume Lab',
        'Chileme',
        'for men',
        NULL,
        NULL,
        'Rosemary, Petitgrain and Citruses',
        'Jasmine and Lily-of-the-Valley',
        'Musk and Vetiver',
        'white floral,aromatic,musky,fresh spicy,woody',
        'ChilemebyMine Perfume Labis a Aromatic fragrance for men.Chilemewas launched in 2016. Top notes are Rosemary, Petitgrain and Citruses; middle notes are Jasmine and Lily-of-the-Valley; base notes are Musk and Vetiver.',
        3.5,
        4,
        NULL
      ),
(
        'Chypre-51984',
        'Chypre Mine Perfume Lab',
        'Chypre',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,mossy,aromatic,earthy,fresh spicy',
        'ChyprebyMine Perfume Labis a Chypre fragrance for women and men.Chyprewas launched in 2012.',
        2.91,
        11,
        NULL
      ),
(
        'Corium-51985',
        'Corium Mine Perfume Lab',
        'Corium',
        'for women and men',
        NULL,
        NULL,
        'Leather',
        'Leather',
        'Leather',
        'leather,animalic,smoky',
        'CoriumbyMine Perfume Labis a Leather fragrance for women and men.Coriumwas launched in 2012. Top note is Leather; middle note is Leather; base note is Leather.',
        3.8,
        15,
        NULL
      ),
(
        'Dark-Mahore-65972',
        'Dark Mahore'' Mine Perfume Lab',
        'Dark',
        'for women and men',
        NULL,
        NULL,
        'Black Pepper, Cardamom and Spices',
        'Jasmine and Ylang-Ylang',
        'Patchouli, Musk, Tobacco and Sandalwood',
        'woody,warm spicy,patchouli,musky,white floral',
        'Dark Mahore''byMine Perfume Labis a fragrance for women and men.Dark Mahore''was launched in 2019. Top notes are Black Pepper, Cardamom and Spices; middle notes are Jasmine and Ylang-Ylang; base notes are Patchouli, Musk, Tobacco and Sandalwood.',
        3.45,
        11,
        NULL
      ),
(
        'Deep-Rose-51902',
        'Deep Rose Mine Perfume Lab',
        'Deep',
        'for women',
        NULL,
        NULL,
        'Rose',
        'Rose',
        'Rose',
        'rose,floral',
        'Deep RosebyMine Perfume Labis a Floral fragrance for women.Deep Rosewas launched in 2012. Top note is Rose; middle note is Rose; base note is Rose.',
        3.17,
        6,
        NULL
      ),
(
        'Eternal-Cologne-83506',
        'Eternal Cologne Mine Perfume Lab',
        'Eternal',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Orange',
        'Sandalwood',
        'Patchouli',
        'citrus,fresh spicy,woody,aromatic,powdery',
        'Eternal ColognebyMine Perfume Labis a Citrus Aromatic fragrance for women and men. Top notes are Bergamot and Orange; middle note is Sandalwood; base note is Patchouli.',
        3.6,
        5,
        NULL
      ),
(
        'Fire-51982',
        'Fire Mine Perfume Lab',
        'Fire',
        'for men',
        NULL,
        NULL,
        'Lavender, Cedar and Bergamot',
        'Carnation, Nutmeg, Lily-of-the-Valley and Violet',
        'Amber, Vetiver and Leather',
        'fresh spicy,woody,aromatic,floral,lavender',
        'FirebyMine Perfume Labis a Woody Floral Musk fragrance for men.Firewas launched in 2014. Top notes are Lavender, Cedar and Bergamot; middle notes are Carnation, Nutmeg, Lily-of-the-Valley and Violet; base notes are Amber, Vetiver and Leather.',
        3.62,
        13,
        NULL
      ),
(
        'Fresia-Orientale-52058',
        'Fresia Orientale Mine Perfume Lab',
        'Fresia',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'White Flowers and Freesia',
        'Patchouli and Vanilla',
        'patchouli,vanilla,white floral,woody,warm spicy',
        'Fresia OrientalebyMine Perfume Labis a Amber Floral fragrance for women and men.Fresia Orientalewas launched in 2017. Top note is Citruses; middle notes are White Flowers and Freesia; base notes are Patchouli and Vanilla.',
        1.5,
        2,
        NULL
      ),
(
        'Fresiorientale-94853',
        'Fresiorientale Mine Perfume Lab',
        'Fresiorientale',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Bergamot and Lemon',
        'Lily of the Valley, Ylang Ylang, Jasmine and Rose',
        'Sandalwood, Vanilla, Cedar and Musk',
        'woody,citrus,white floral,powdery,musky',
        'FresiorientalebyMine Perfume Labis a fragrance for women and men. This is a new fragrance.Fresiorientalewas launched in 2024. Top notes are Pink Pepper, Bergamot and Lemon; middle notes are Lily of the Valley, Ylang Ylang, Jasmine and Rose; base notes are Sandalwood, Vanilla, Cedar and Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Good-Morning-Sir-51896',
        'Good Morning Sir Mine Perfume Lab',
        'Good',
        'for men',
        NULL,
        NULL,
        'Bergamot and Orange',
        'Orange Blossom',
        'Cedar, Spices, Patchouli and Vetiver',
        'citrus,woody,fresh spicy,white floral,aromatic',
        'Good Morning SirbyMine Perfume Labis a Citrus fragrance for men.Good Morning Sirwas launched in 2017. Top notes are Bergamot and Orange; middle note is Orange Blossom; base notes are Cedar, Spices, Patchouli and Vetiver.',
        3.89,
        18,
        NULL
      ),
(
        'Grace-51903',
        'Grace Mine Perfume Lab',
        'Grace',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley',
        'Lily-of-the-Valley',
        'Lily-of-the-Valley',
        'white floral,fresh,green,soapy',
        'GracebyMine Perfume Labis a Floral fragrance for women.Gracewas launched in 2017. Top note is Lily-of-the-Valley; middle note is Lily-of-the-Valley; base note is Lily-of-the-Valley.',
        3.78,
        9,
        NULL
      ),
(
        'Hope-51895',
        'Hope Mine Perfume Lab',
        'Hope',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes and Citruses',
        'Green Tea',
        'Musk',
        'marine,green,aromatic,fresh,citrus',
        'HopebyMine Perfume Labis a Citrus fragrance for women and men.Hopewas launched in 2017. Top notes are Sea Notes and Citruses; middle note is Green Tea; base note is Musk.',
        3.5,
        4,
        NULL
      ),
(
        'Hush-52095',
        'Hush Mine Perfume Lab',
        'Hush',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Floral Notes',
        'Powdery Notes, Iris and Vanilla',
        'powdery,iris,violet,floral',
        'HushbyMine Perfume Labis a Floral fragrance for women and men.Hushwas launched in 2017. Top note is Citruses; middle note is Floral Notes; base notes are Powdery Notes, Iris and Vanilla.',
        3.33,
        12,
        NULL
      ),
(
        'Jasmine-51904',
        'Jasmine Mine Perfume Lab',
        'Jasmine',
        'for women',
        NULL,
        NULL,
        'Jasmine',
        'Jasmine',
        'Jasmine',
        'white floral',
        'JasminebyMine Perfume Labis a Floral fragrance for women.Jasminewas launched in 2017. Top note is Jasmine; middle note is Jasmine; base note is Jasmine.',
        1.75,
        4,
        NULL
      ),
(
        'La-Mora-51907',
        'La Mora Mine Perfume Lab',
        'La',
        'for women and men',
        NULL,
        NULL,
        'Blackberry',
        'Blackberry',
        'Blackberry',
        'fruity,sweet,violet',
        'La MorabyMine Perfume Labis a Aromatic Fruity fragrance for women and men.La Morawas launched in 2013. Top note is Blackberry; middle note is Blackberry; base note is Blackberry.',
        4,
        2,
        NULL
      ),
(
        'Legni-Spezie-51977',
        'Legni & Spezie Mine Perfume Lab',
        'Legni',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Citruses',
        'Cedar and Oakmoss',
        'woody,mossy,earthy',
        'Legni & SpeziebyMine Perfume Labis a Aromatic Spicy fragrance for women and men.Legni & Speziewas launched in 2017. Top note is Citruses; middle note is Citruses; base notes are Cedar and Oakmoss.',
        3.33,
        3,
        NULL
      ),
(
        'Lo-Verte-51906',
        'Lo'' Verte Mine Perfume Lab',
        'Lo''',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Water Lily and Water Hyacinth',
        'Musk',
        'floral,aquatic,fresh',
        'Lo'' VertebyMine Perfume Labis a Aromatic Green fragrance for women and men.Lo'' Vertewas launched in 2016. Top note is Citruses; middle notes are Water Lily and Water Hyacinth; base note is Musk.',
        3.83,
        6,
        NULL
      ),
(
        'Martinique-65968',
        'Martinique Mine Perfume Lab',
        'Martinique',
        'for women and men',
        NULL,
        NULL,
        'Green Notes',
        'Rum and Tobacco',
        'Leather, Tonka Bean, Amber and Musk',
        'tobacco,leather,rum,sweet,animalic',
        'MartiniquebyMine Perfume Labis a fragrance for women and men.Martiniquewas launched in 2019. Top note is Green Notes; middle notes are Rum and Tobacco; base notes are Leather, Tonka Bean, Amber and Musk.',
        4.17,
        12,
        NULL
      ),
(
        'Melograno-51917',
        'Melograno Mine Perfume Lab',
        'Melograno',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Pomegranate and Spicy Notes',
        'Woody Notes',
        'woody,citrus,fresh spicy,fruity',
        'MelogranobyMine Perfume Labis a Woody Spicy fragrance for women and men.Melogranowas launched in 2017. Top note is Citruses; middle notes are Pomegranate and Spicy Notes; base note is Woody Notes.',
        3.67,
        3,
        NULL
      ),
(
        'Montego-Bay-65971',
        'Montego Bay Mine Perfume Lab',
        'Montego',
        'for women and men',
        NULL,
        NULL,
        'Rosemary, Bitter Orange and Petitgrain',
        'cannabis',
        'Cedar and Amber',
        'aromatic,woody,fresh spicy,citrus,cannabis',
        'Montego BaybyMine Perfume Labis a fragrance for women and men.Montego Baywas launched in 2019. Top notes are Rosemary, Bitter Orange and Petitgrain; middle note is cannabis; base notes are Cedar and Amber.',
        3.12,
        8,
        NULL
      ),
(
        'Mr-Vetiver-51979',
        'Mr. Vetiver Mine Perfume Lab',
        'Mr.',
        'for men',
        NULL,
        NULL,
        'Bergamot and Lemon',
        'Vetiver',
        'Woody Notes',
        'citrus,woody,aromatic,earthy,fresh spicy',
        'Mr. VetiverbyMine Perfume Labis a Woody fragrance for men.Mr. Vetiverwas launched in 2013. Top notes are Bergamot and Lemon; middle note is Vetiver; base note is Woody Notes.',
        4.11,
        9,
        NULL
      ),
(
        'Mu-ghet-to-94854',
        'Mu-ghet-to Mine Perfume Lab',
        'Mu-ghet-to',
        'for women and men',
        NULL,
        NULL,
        'Lemon',
        'Lily of the Valley, Ylang Ylang and Rose',
        'Musk',
        'musky,white floral,powdery,fresh,citrus',
        'Mu-ghet-tobyMine Perfume Labis a fragrance for women and men. This is a new fragrance.Mu-ghet-towas launched in 2024. Top note is Lemon; middle notes are Lily of the Valley, Ylang Ylang and Rose; base note is Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Muschio-Bianco-52098',
        'Muschio Bianco Mine Perfume Lab',
        'Muschio',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Jasmine and Rose',
        'Patchouli, Sandalwood and Musk',
        'woody,patchouli,warm spicy,powdery,balsamic',
        'Muschio BiancobyMine Perfume Labis a Floral Woody Musk fragrance for women and men.Muschio Biancowas launched in 2012. Top note is Citruses; middle notes are Jasmine and Rose; base notes are Patchouli, Sandalwood and Musk.',
        2,
        1,
        NULL
      ),
(
        'Narghile-52055',
        'Narghile'' Mine Perfume Lab',
        'Narghile''',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Egyptian Jasmine, Turkish Rose and Red Currant',
        'Tobacco, Honey, Peru Balsam, Vanilla and Amber',
        'sweet,tobacco,amber,honey,balsamic',
        'Narghile''byMine Perfume Labis a Amber fragrance for women and men.Narghile''was launched in 2018. Top note is Citruses; middle notes are Egyptian Jasmine, Turkish Rose and Red Currant; base notes are Tobacco, Honey, Peru Balsam, Vanilla and Amber.',
        4.29,
        28,
        NULL
      ),
(
        'Olla-51986',
        'Olla'' Mine Perfume Lab',
        'Olla''',
        'for women and men',
        NULL,
        NULL,
        'Milk',
        'Milk',
        'Milk',
        NULL,
        'Olla''byMine Perfume Labis a fragrance for women and men.Olla''was launched in 2017. Top note is Milk; middle note is Milk; base note is Milk.',
        3.76,
        45,
        NULL
      ),
(
        'Oud-52057',
        'Oud Mine Perfume Lab',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Agarwood (Oud)',
        'Agarwood (Oud)',
        'Agarwood (Oud)',
        'oud,fresh spicy',
        'OudbyMine Perfume Labis a Amber Woody fragrance for women and men.Oudwas launched in 2017. Top note is Agarwood (Oud); middle note is Agarwood (Oud); base note is Agarwood (Oud).',
        4.19,
        26,
        NULL
      ),
(
        'Patchouli-51980',
        'Patchouli Mine Perfume Lab',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Patchouli',
        'Patchouli',
        'Patchouli and Amber',
        'patchouli,woody,amber,warm spicy,earthy',
        'PatchoulibyMine Perfume Labis a Woody fragrance for women and men.Patchouliwas launched in 2013. Top note is Patchouli; middle note is Patchouli; base notes are Patchouli and Amber.',
        3.8,
        15,
        NULL
      ),
(
        'Philosophigue-51916',
        'Philosophigue Mine Perfume Lab',
        'Philosophigue',
        'for women and men',
        NULL,
        NULL,
        'Green Leaves',
        'Fig',
        'Musk',
        'green,fruity,sweet,musky,woody',
        'PhilosophiguebyMine Perfume Labis a Aromatic Fruity fragrance for women and men.Philosophiguewas launched in 2016. Top note is Green Leaves; middle note is Fig; base note is Musk.',
        3.52,
        27,
        NULL
      ),
(
        'Pippi-93569',
        'Pippi Mine Perfume Lab',
        'Pippi',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,musky,white floral,animalic',
        'PippibyMine Perfume Labis a fragrance for women and men. This is a new fragrance.Pippiwas launched in 2024.',
        4,
        1,
        NULL
      ),
(
        'Sahel-65970',
        'Sahel Mine Perfume Lab',
        'Sahel',
        'for women and men',
        NULL,
        NULL,
        'Tobacco',
        'Honey',
        'Agarwood (Oud), Amber, Sandalwood and Madagascar Vanilla',
        'oud,tobacco,sweet,honey,powdery',
        'SahelbyMine Perfume Labis a fragrance for women and men.Sahelwas launched in 2019. Top note is Tobacco; middle note is Honey; base notes are Agarwood (Oud), Amber, Sandalwood and Madagascar Vanilla.',
        3.69,
        13,
        NULL
      ),
(
        'Shamrock-65969',
        'Shamrock Mine Perfume Lab',
        'Shamrock',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Honey, Whiskey and Jasmine',
        'Vanilla and Sandalwood',
        'honey,citrus,vanilla,woody,sweet',
        'ShamrockbyMine Perfume Labis a fragrance for women and men.Shamrockwas launched in 2019. Top note is Citruses; middle notes are Honey, Whiskey and Jasmine; base notes are Vanilla and Sandalwood.',
        4.14,
        28,
        NULL
      ),
(
        'Sig-Pepper-51900',
        'Sig. Pepper Mine Perfume Lab',
        'Sig.',
        'for women and men',
        NULL,
        NULL,
        'Black Pepper, Pink Pepper and Lavender',
        'Pepper, Cardamom and Cinnamon',
        'Woody Notes and Musk',
        'warm spicy,fresh spicy,aromatic,soft spicy,cinnamon',
        'Sig. PepperbyMine Perfume Labis a Aromatic Spicy fragrance for women and men.Sig. Pepperwas launched in 2018. Top notes are Black Pepper, Pink Pepper and Lavender; middle notes are Pepper, Cardamom and Cinnamon; base notes are Woody Notes and Musk.',
        4,
        11,
        NULL
      ),
(
        'Southland-65976',
        'Southland Mine Perfume Lab',
        'Southland',
        'for women and men',
        NULL,
        NULL,
        'Orange and Grapefruit',
        'Flint',
        'Benzoin, Oak and Woody Notes',
        'citrus,amber,woody,warm spicy,fresh spicy',
        'SouthlandbyMine Perfume Labis a Woody fragrance for women and men.Southlandwas launched in 2020. Top notes are Orange and Grapefruit; middle note is Flint; base notes are Benzoin, Oak and Woody Notes.',
        4.2,
        10,
        NULL
      ),
(
        'St-Incense-52093',
        'St. Incense Mine Perfume Lab',
        'St.',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Incense',
        'Woody Notes, Musk and Vanilla',
        'amber,smoky,balsamic,woody,citrus',
        'St. IncensebyMine Perfume Labis a Amber fragrance for women and men.St. Incensewas launched in 2015. Top note is Citruses; middle note is Incense; base notes are Woody Notes, Musk and Vanilla.',
        3.87,
        31,
        NULL
      ),
(
        'Sun-51983',
        'Sun Mine Perfume Lab',
        'Sun',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Amalfi Lemon',
        'Orange Blossom, Red Fruits, Carnation and Lily-of-the-Valley',
        'Sandalwood, Patchouli, Amber and Musk',
        'citrus,white floral,woody,warm spicy,powdery',
        'SunbyMine Perfume Labis a Floral Woody Musk fragrance for women and men.Sunwas launched in 2014. Top notes are Bergamot and Amalfi Lemon; middle notes are Orange Blossom, Red Fruits, Carnation and Lily-of-the-Valley; base notes are Sandalwood, Patchouli, Amber and Musk.',
        3.43,
        7,
        NULL
      ),
(
        'Vaniglia-52054',
        'Vaniglia Mine Perfume Lab',
        'Vaniglia',
        'for women and men',
        NULL,
        NULL,
        'Vanilla',
        'Vanilla',
        'Vanilla',
        'vanilla,powdery,sweet',
        'VanigliabyMine Perfume Labis a Amber Vanilla fragrance for women and men.Vanigliawas launched in 2014. Top note is Vanilla; middle note is Vanilla; base note is Vanilla.',
        3.9,
        10,
        NULL
      );
