
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Sondos-84245',
        'Sondos Lattafa Perfumes',
        'Sondos',
        'for women and men',
        NULL,
        'Alex Lee',
        'Mandarin Orange and Saffron',
        'Tuberose, Peach Blossom and Rose',
        'Vanilla, Suede and Patchouli',
        'tuberose,vanilla,floral,white floral,citrus',
        'SondosbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Sondoswas launched in 2023. The nose behind this fragrance is Alex Lee. Top notes are Mandarin Orange and Saffron; middle notes are Tuberose, Peach Blossom and Rose; base notes are Vanilla, Suede and Patchouli.',
        3.96,
        107,
        NULL
      ),
(
        'Sumou-Platinum-82623',
        'Sumou Platinum Lattafa Perfumes',
        'Sumou',
        'for women and men',
        NULL,
        NULL,
        'Apple, Bergamot, Plum, Oakmoss and Lemon',
        'Mahogany, Cinnamon and Clove',
        'Sandalwood, Vanilla, Cedar and Vetiver',
        'woody,fruity,warm spicy,citrus,aromatic',
        'Sumou PlatinumbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Sumou Platinumwas launched in 2022. Top notes are Apple, Bergamot, Plum, Oakmoss and Lemon; middle notes are Mahogany, Cinnamon and Clove; base notes are Sandalwood, Vanilla, Cedar and Vetiver.',
        4.13,
        39,
        NULL
      ),
(
        'Suqraat-75471',
        'Suqraat Lattafa Perfumes',
        'Suqraat',
        'for men',
        NULL,
        NULL,
        'Bergamot and Ginger',
        'Lavender and Violet Leaf',
        'Musk, Sandalwood and Amber',
        'citrus,warm spicy,musky,powdery,fresh spicy',
        'SuqraatbyLattafa Perfumesis a Aromatic fragrance for men. This is a new fragrance.Suqraatwas launched in 2022. Top notes are Bergamot and Ginger; middle notes are Lavender and Violet Leaf; base notes are Musk, Sandalwood and Amber.',
        4.27,
        310,
        NULL
      ),
(
        'Sutoor-83691',
        'Sutoor Lattafa Perfumes',
        'Sutoor',
        'for women',
        NULL,
        NULL,
        'Peach, Cardamom, Blood Orange and Heliotrope',
        'Rum, Brandy, Davana and Jasmine',
        'Vanilla, Benzoin, Cashmere Wood, Sandalwood, Styrax, Vetiver, Patchouli, Tonka Bean and Labdanum',
        'woody,warm spicy,amber,vanilla,fruity',
        'SutoorbyLattafa Perfumesis a fragrance for women. This is a new fragrance.Sutoorwas launched in 2022. Top notes are Peach, Cardamom, Blood Orange and Heliotrope; middle notes are Rum, Brandy, Davana and Jasmine; base notes are Vanilla, Benzoin, Cashmere Wood, Sandalwood, Styrax, Vetiver, Patchouli, Tonka Bean and Labdanum.',
        3.94,
        147,
        NULL
      ),
(
        'Ta-weel-85095',
        'Ta''weel Lattafa Perfumes',
        'Ta''weel',
        'for women and men',
        NULL,
        NULL,
        'Ginger, Bergamot, Juniper and Nutmeg',
        'Orange Blossom and Lavender',
        'Ambroxan, Leather, Vetiver and Patchouli',
        'citrus,aromatic,fresh spicy,amber,warm spicy',
        'Ta''weelbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Ta''weelwas launched in 2023. Top notes are Ginger, Bergamot, Juniper and Nutmeg; middle notes are Orange Blossom and Lavender; base notes are Ambroxan, Leather, Vetiver and Patchouli.',
        3.97,
        128,
        NULL
      ),
(
        'Tamayuz-Lattafa-30865',
        'Tamayuz Lattafa Lattafa Perfumes',
        'Tamayuz',
        'for women and men',
        NULL,
        NULL,
        'Nutmeg, Violet Leaf and Bergamot',
        'Clary Sage, Geranium, Cardamom and Orange Blossom',
        'Vanilla, Tonka Bean, Sandalwood and Patchouli',
        'vanilla,aromatic,fresh spicy,warm spicy,woody',
        'Tamayuz LattafabyLattafa Perfumesis a Amber Fougere fragrance for women and men.Tamayuz Lattafawas launched in 2015. Top notes are Nutmeg, Violet Leaf and Bergamot; middle notes are Clary Sage, Geranium, Cardamom and Orange Blossom; base notes are Vanilla, Tonka Bean, Sandalwood and Patchouli.',
        4.29,
        7,
        NULL
      ),
(
        'Tamima-92643',
        'Tamima Lattafa Perfumes',
        'Tamima',
        'for women and men',
        NULL,
        NULL,
        'Red Currant, Kiwi, Rhubarb and Pink Pepper',
        'Watermelon, Cyclamen and Jasmine',
        'Cedar, Sandalwood, Woodsy Notes and Musk',
        'fruity,ozonic,aquatic,woody,fresh',
        'TamimabyLattafa Perfumesis a Woody Floral Musk fragrance for women and men. This is a new fragrance.Tamimawas launched in 2024. Top notes are Red Currant, Kiwi, Rhubarb and Pink Pepper; middle notes are Watermelon, Cyclamen and Jasmine; base notes are Cedar, Sandalwood, Woodsy Notes and Musk.',
        4.09,
        44,
        NULL
      ),
(
        'Thuraya-95135',
        'Thuraya Lattafa Perfumes',
        'Thuraya',
        'for women and men',
        NULL,
        NULL,
        'Geranium, Vanille, Woody Notes and Black Tea',
        'Lavender and Magnolia',
        'Red Berries, Tea and Cardamom',
        'fruity,sweet,aromatic,fresh,fresh spicy',
        'ThurayabyLattafa Perfumesis a fragrance for women and men. Top notes are Geranium, Vanille, Woody Notes and Black Tea; middle notes are Lavender and Magnolia; base notes are Red Berries, Tea and Cardamom.',
        5,
        2,
        NULL
      ),
(
        'Velvet-Oud-60262',
        'Velvet Oud Lattafa Perfumes',
        'Velvet',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'leather,amber,smoky,animalic,oud',
        'Velvet OudbyLattafa Perfumesis a Amber Woody fragrance for women and men.Velvet Oudwas launched in 2018.',
        4.17,
        1,
        NULL
      ),
(
        'Velvet-Rose-76867',
        'Velvet Rose Lattafa Perfumes',
        'Velvet',
        'for women and men',
        NULL,
        NULL,
        'Rose and Patchouli',
        'Musk and Labdanum',
        'Musk and Amber',
        'rose,amber,musky,patchouli,woody',
        'Velvet RosebyLattafa Perfumesis a fragrance for women and men. Top notes are Rose and Patchouli; middle notes are Musk and Labdanum; base notes are Musk and Amber.',
        3.9,
        155,
        NULL
      ),
(
        'Washwasha-25893',
        'Washwasha Lattafa Perfumes',
        'Washwasha',
        'for women',
        NULL,
        NULL,
        'Raspberry, Pink Pepper and Bitter Orange',
        'Tuberose, Jasmine, French orange flower, Osmanthus and Neroli',
        'Tonka Bean, Vanilla, Benzoin, Musk, Cashmirwood and Amber',
        'white floral,amber,sweet,fruity,vanilla',
        'WashwashabyLattafa Perfumesis a Amber Floral fragrance for women. Top notes are Raspberry, Pink Pepper and Bitter Orange; middle notes are Tuberose, Jasmine, French orange flower, Osmanthus and Neroli; base notes are Tonka Bean, Vanilla, Benzoin, Musk, Cashmirwood and Amber.',
        3.85,
        224,
        NULL
      ),
(
        '24-Carat-Pure-Gold-25821',
        '24 Carat Pure Gold Lattafa Perfumes',
        '24',
        'for women and men',
        NULL,
        NULL,
        'Agarwood (Oud), Saffron and Cinnamon',
        'Rose and Sandalwood',
        'Leather, Incense, Musk, Amber and Vanilla',
        'warm spicy,leather,oud,amber,smoky',
        '24 Carat Pure GoldbyLattafa Perfumesis a Amber Vanilla fragrance for women and men. Top notes are Agarwood (Oud), Saffron and Cinnamon; middle notes are Rose and Sandalwood; base notes are Leather, Incense, Musk, Amber and Vanilla.',
        3.78,
        183,
        NULL
      ),
(
        '24-Carat-White-Gold-25822',
        '24 Carat White Gold Lattafa Perfumes',
        '24',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom and Bergamot',
        'Lavender, Nutmeg, Geranium and Pink Pepper',
        'Vetiver, Agarwood (Oud) and Tonka Bean',
        'citrus,fresh spicy,aromatic,white floral,sweet',
        '24 Carat White GoldbyLattafa Perfumesis a Amber fragrance for women and men. Top notes are Orange Blossom and Bergamot; middle notes are Lavender, Nutmeg, Geranium and Pink Pepper; base notes are Vetiver, Agarwood (Oud) and Tonka Bean.',
        3.99,
        70,
        NULL
      ),
(
        'Ajayeb-Dubai-84223',
        'Ajayeb Dubai Lattafa Perfumes',
        'Ajayeb',
        'for women and men',
        NULL,
        NULL,
        'Pineapple and Saffron',
        'Coffee and Violet Leaves',
        'Butterscotch, Vanilla and Sandalwood',
        'sweet,warm spicy,coffee,lactonic,vanilla',
        'Ajayeb DubaibyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Ajayeb Dubaiwas launched in 2023. Top notes are Pineapple and Saffron; middle notes are Coffee and Violet Leaves; base notes are Butterscotch, Vanilla and Sandalwood.',
        3.92,
        285,
        NULL
      ),
(
        'Ajayeb-Dubai-Portrait-84222',
        'Ajayeb Dubai Portrait Lattafa Perfumes',
        'Ajayeb',
        'for women and men',
        NULL,
        NULL,
        'Orange and Lemon',
        'Mango, Osmanthus and Jasmine',
        'Oud, Sandalwood, Musk and Amber',
        'fruity,tropical,citrus,sweet,floral',
        'Ajayeb Dubai PortraitbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Ajayeb Dubai Portraitwas launched in 2023. Top notes are Orange and Lemon; middle notes are Mango, Osmanthus and Jasmine; base notes are Oud, Sandalwood, Musk and Amber.',
        4,
        456,
        NULL
      ),
(
        'Ajwad-75099',
        'Ajwad Lattafa Perfumes',
        'Ajwad',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes',
        'Rose and Jasmine',
        'Musk, Vanilla, Amber and Cedar',
        'fruity,rose,powdery,musky,sweet',
        'AjwadbyLattafa Perfumesis a Woody Aromatic fragrance for women and men.Ajwadwas launched in 2021. Top note is Fruity Notes; middle notes are Rose and Jasmine; base notes are Musk, Vanilla, Amber and Cedar.',
        3.84,
        799,
        NULL
      ),
(
        'Ajwad-Pink-to-Pink-89766',
        'Ajwad Pink to Pink Lattafa Perfumes',
        'Ajwad',
        'for women and men',
        NULL,
        NULL,
        'Guava, Pink Grapefruit, Litchi and Pink Pepper',
        'Rose, Peony and Magnolia',
        'Leather, Musk, Ambergris, Vanilla and Moss',
        'fruity,leather,tropical,citrus,animalic',
        'Ajwad Pink to PinkbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Ajwad Pink to Pinkwas launched in 2024. Top notes are Guava, Pink Grapefruit, Litchi and Pink Pepper; middle notes are Rose, Peony and Magnolia; base notes are Leather, Musk, Ambergris, Vanilla and Moss.',
        3.45,
        117,
        NULL
      ),
(
        'Al-Nashama-89762',
        'Al Nashama Lattafa Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Sage and Pink Pepper',
        'Plum, Jasmine and Black Pepper',
        'Saffiano Leather, Amber, Patchouli and Moss',
        'fruity,amber,sweet,fresh spicy,soft spicy',
        'Al NashamabyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Al Nashamawas launched in 2024. Top notes are Bergamot, Sage and Pink Pepper; middle notes are Plum, Jasmine and Black Pepper; base notes are Saffiano Leather, Amber, Patchouli and Moss.',
        4.48,
        173,
        NULL
      ),
(
        'Al-Nashama-Caprice-89764',
        'Al Nashama Caprice Lattafa Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Ginger, Bergamot and Lemon',
        'Lavender, Geranium and Mint',
        'Amber, Cedarwood, Patchouli and Vetiver',
        'warm spicy,aromatic,woody,lavender,fresh spicy',
        'Al Nashama CapricebyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Al Nashama Capricewas launched in 2024. Top notes are Cardamom, Ginger, Bergamot and Lemon; middle notes are Lavender, Geranium and Mint; base notes are Amber, Cedarwood, Patchouli and Vetiver.',
        4.55,
        424,
        NULL
      ),
(
        'Ameer-82794',
        'Ameer Lattafa Perfumes',
        'Ameer',
        'for women and men',
        NULL,
        NULL,
        'Apple, Pink Pepper and Rosemary',
        'Cloves and Floral Notes',
        'Oud, Patchouli, Labdanum, Cypress and Vetiver',
        'warm spicy,woody,oud,aromatic,fresh spicy',
        'AmeerbyLattafa Perfumesis a fragrance for women and men. Top notes are Apple, Pink Pepper and Rosemary; middle notes are Cloves and Floral Notes; base notes are Oud, Patchouli, Labdanum, Cypress and Vetiver.',
        4.3,
        202,
        NULL
      ),
(
        'Safeer-82795',
        'Safeer Lattafa Perfumes',
        'Safeer',
        'for women and men',
        NULL,
        NULL,
        'Artemisia and Bergamot',
        'Herbal Notes, Green Notes and Spicy Notes',
        'Guaiac Wood, Juniper, Nutty Notes, Patchouli, Frankincense, Cumin and Labdanum',
        'fresh spicy,woody,aromatic,green,herbal',
        'SafeerbyLattafa Perfumesis a fragrance for women and men. Top notes are Artemisia and Bergamot; middle notes are Herbal Notes, Green Notes and Spicy Notes; base notes are Guaiac Wood, Juniper, Nutty Notes, Patchouli, Frankincense, Cumin and Labdanum.',
        4.17,
        350,
        NULL
      ),
(
        'Wazeer-82796',
        'Wazeer Lattafa Perfumes',
        'Wazeer',
        'for women and men',
        NULL,
        NULL,
        'Mint, Orange, Bergamot and Juniper',
        'Chocolate, Caramel, Pear, Raspberry and Iris',
        'Amber, Vanilla, Sandalwood, Cedar, Musk and Vetiver',
        'sweet,woody,aromatic,citrus,powdery',
        'WazeerbyLattafa Perfumesis a fragrance for women and men. Top notes are Mint, Orange, Bergamot and Juniper; middle notes are Chocolate, Caramel, Pear, Raspberry and Iris; base notes are Amber, Vanilla, Sandalwood, Cedar, Musk and Vetiver.',
        4.04,
        225,
        NULL
      ),
(
        'Ana-Abiyedh-59149',
        'Ana Abiyedh Lattafa Perfumes',
        'Ana',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Orange',
        'Vanilla and Pear',
        'Musk and Amber',
        'musky,powdery,vanilla,citrus,sweet',
        'Ana AbiyedhbyLattafa Perfumesis a fragrance for women and men. Top notes are Bergamot and Orange; middle notes are Vanilla and Pear; base notes are Musk and Amber.',
        3.89,
        1,
        NULL
      ),
(
        'Ana-Abiyedh-Leather-82062',
        'Ana Abiyedh Leather Lattafa Perfumes',
        'Ana',
        'for women and men',
        NULL,
        NULL,
        'Juniper Berries, Cardamom, Pink Pepper and Raspberry',
        'Iris, Ginger and Rose',
        'Leather, White Musk and Amber',
        'leather,aromatic,animalic,warm spicy,fresh spicy',
        'Ana Abiyedh LeatherbyLattafa Perfumesis a Leather fragrance for women and men.Ana Abiyedh Leatherwas launched in 2017. Top notes are Juniper Berries, Cardamom, Pink Pepper and Raspberry; middle notes are Iris, Ginger and Rose; base notes are Leather, White Musk and Amber.',
        3.75,
        251,
        NULL
      ),
(
        'Ana-Abiyedh-Rouge-63062',
        'Ana Abiyedh Rouge Lattafa Perfumes',
        'Ana',
        'for women and men',
        NULL,
        NULL,
        'Nashi Pear, Kumquat and Bergamot',
        'Caramel and Geranium',
        'Ambergris, Musk and Oakmoss',
        'citrus,amber,fresh spicy,aromatic,caramel',
        'Ana Abiyedh RougebyLattafa Perfumesis a Woody Spicy fragrance for women and men.Ana Abiyedh Rougewas launched in 2016. Top notes are Nashi Pear, Kumquat and Bergamot; middle notes are Caramel and Geranium; base notes are Ambergris, Musk and Oakmoss.',
        4.04,
        1,
        NULL
      ),
(
        'Ana-Abyedh-Poudree-84590',
        'Ana Abyedh Poudrée Lattafa Perfumes',
        'Ana',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Rose and Jasmine',
        'Musk',
        'Vanilla, Tonka Bean, Cedar, Vetiver and Patchouli',
        'vanilla,musky,powdery,sweet,white floral',
        'Ana Abyedh PoudréebyLattafa Perfumesis a Floral fragrance for women. This is a new fragrance.Ana Abyedh Poudréewas launched in 2023. Top notes are Orange Blossom, Rose and Jasmine; middle note is Musk; base notes are Vanilla, Tonka Bean, Cedar, Vetiver and Patchouli.',
        4.16,
        367,
        NULL
      ),
(
        'Asad-72821',
        'Asad Lattafa Perfumes',
        'Asad',
        'for men',
        NULL,
        NULL,
        'Black Pepper, Tobacco and Pineapple',
        'Patchouli, Coffee and Iris',
        'Vanilla, Amber, Dry Wood, Benzoin and Labdanum',
        'amber,vanilla,fresh spicy,woody,warm spicy',
        'AsadbyLattafa Perfumesis a Amber fragrance for men.Asadwas launched in 2021. Top notes are Black Pepper, Tobacco and Pineapple; middle notes are Patchouli, Coffee and Iris; base notes are Vanilla, Amber, Dry Wood, Benzoin and Labdanum.',
        4.28,
        5,
        NULL
      ),
(
        'Asad-Zanzibar-90713',
        'Asad Zanzibar Lattafa Perfumes',
        'Asad',
        'for men',
        NULL,
        'Fanny Bal',
        'Lavender and Black Pepper',
        'Coconut Water, Iris and Salt',
        'Vanilla and Incense',
        'vanilla,iris,powdery,lavender,fresh spicy',
        'Asad ZanzibarbyLattafa Perfumesis a fragrance for men. This is a new fragrance.Asad Zanzibarwas launched in 2024. The nose behind this fragrance is Fanny Bal. Top notes are Lavender and Black Pepper; middle notes are Coconut Water, Iris and Salt; base notes are Vanilla and Incense.',
        3.78,
        700,
        NULL
      ),
(
        'Bade-e-Al-Oud-Amethyst-68214',
        'Bade''e Al Oud Amethyst Lattafa Perfumes',
        'Bade''e',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper and Bergamot',
        'Turkish Rose, Bulgarian Rose and Jasmine',
        'Agarwood (Oud), Amber and Vanilla',
        'rose,oud,amber,soft spicy,floral',
        'Bade''e Al Oud AmethystbyLattafa Perfumesis a Amber Vanilla fragrance for women and men.Bade''e Al Oud Amethystwas launched in 2021. Top notes are Pink Pepper and Bergamot; middle notes are Turkish Rose, Bulgarian Rose and Jasmine; base notes are Agarwood (Oud), Amber and Vanilla.',
        4.11,
        1,
        NULL
      ),
(
        'Bade-e-Al-Oud-Honor-Glory-84302',
        'Bade''e Al Oud Honor & Glory Lattafa Perfumes',
        'Bade''e',
        'for women and men',
        NULL,
        NULL,
        'Pineapple and Creme Brulee',
        'Cinnamon, Turmeric, Benzoin and Black Pepper',
        'Vanilla, Sandalwood, Cashmeran and Moss',
        'sweet,warm spicy,fruity,vanilla,woody',
        'Bade''e Al Oud Honor & GlorybyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Bade''e Al Oud Honor & Glorywas launched in 2023. Top notes are Pineapple and Creme Brulee; middle notes are Cinnamon, Turmeric, Benzoin and Black Pepper; base notes are Vanilla, Sandalwood, Cashmeran and Moss.',
        4.31,
        1,
        NULL
      ),
(
        'Bade-e-Al-Oud-Oud-for-Glory-64948',
        'Bade''e Al Oud Oud for Glory Lattafa Perfumes',
        'Bade''e',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Nutmeg and Lavender',
        'Agarwood (Oud) and Patchouli',
        'Agarwood (Oud), Patchouli and Musk',
        'oud,warm spicy,fresh spicy,patchouli,metallic',
        'Bade''e Al Oud Oud for GlorybyLattafa Perfumesis a Amber Woody fragrance for women and men.Bade''e Al Oud Oud for Glorywas launched in 2020. Top notes are Saffron, Nutmeg and Lavender; middle notes are Agarwood (Oud) and Patchouli; base notes are Agarwood (Oud), Patchouli and Musk.',
        4.19,
        4,
        NULL
      ),
(
        'Bade-e-Al-Oud-Sublime-83309',
        'Bade''e Al Oud Sublime Lattafa Perfumes',
        'Bade''e',
        'for women and men',
        NULL,
        NULL,
        'Apple, Litchi and Rose',
        'Plum and Jasmine',
        'Moss, Vanilla and Patchouli',
        'fruity,fresh,tropical,rose,mossy',
        'Bade''e Al Oud SublimebyLattafa Perfumesis a Woody Aromatic fragrance for women and men. This is a new fragrance.Bade''e Al Oud Sublimewas launched in 2023. Top notes are Apple, Litchi and Rose; middle notes are Plum and Jasmine; base notes are Moss, Vanilla and Patchouli.',
        4.33,
        744,
        NULL
      ),
(
        'Fakhar-Black-70465',
        'Fakhar Black Lattafa Perfumes',
        'Fakhar',
        'for men',
        NULL,
        NULL,
        'Apple, Bergamot and Ginger',
        'Lavender, Sage, Juniper Berries and Geranium',
        'Tonka Bean, Amberwood, Cedar and Vetiver',
        'aromatic,woody,fresh spicy,fruity,citrus',
        'Fakhar BlackbyLattafa Perfumesis a Amber fragrance for men. This is a new fragrance.Fakhar Blackwas launched in 2022. Top notes are Apple, Bergamot and Ginger; middle notes are Lavender, Sage, Juniper Berries and Geranium; base notes are Tonka Bean, Amberwood, Cedar and Vetiver.',
        4.28,
        2,
        NULL
      ),
(
        'Fakhar-Extrait-85092',
        'Fakhar Extrait Lattafa Perfumes',
        'Fakhar',
        'for women',
        NULL,
        NULL,
        'Grapefruit, Pink Pepper and Cardamom',
        'Tuberose, Solar Notes and Artemisia',
        'Amber, Cashmeran, Labdanum and Leather',
        'amber,tuberose,musky,white floral,citrus',
        'Fakhar ExtraitbyLattafa Perfumesis a fragrance for women. This is a new fragrance.Fakhar Extraitwas launched in 2023. Top notes are Grapefruit, Pink Pepper and Cardamom; middle notes are Tuberose, Solar Notes and Artemisia; base notes are Amber, Cashmeran, Labdanum and Leather.',
        4.38,
        196,
        NULL
      ),
(
        'Fakhar-Lattafa-30864',
        'Fakhar Lattafa Lattafa Perfumes',
        'Fakhar',
        'for women and men',
        NULL,
        NULL,
        'Peach, Pear, Apple, Black Currant and Orange',
        'Orange Blossom, Jasmine Sambac and Rose',
        'Sandalowood, Vanilla, Musk and Patchouli',
        'fruity,white floral,sweet,citrus,woody',
        'Fakhar LattafabyLattafa Perfumesis a Woody Floral Musk fragrance for women and men.Fakhar Lattafawas launched in 2015. Top notes are Peach, Pear, Apple, Black Currant and Orange; middle notes are Orange Blossom, Jasmine Sambac and Rose; base notes are Sandalowood, Vanilla, Musk and Patchouli.',
        4.04,
        50,
        NULL
      ),
(
        'Fakhar-Rose-70466',
        'Fakhar Rose Lattafa Perfumes',
        'Fakhar',
        'for women',
        NULL,
        NULL,
        'Fruits, Lily, Pomegranate and Aldehydes',
        'Tuberose, Jasmine, Gardenia, Honeysuckle, Rose, Ylang-Ylang and Peony',
        'Vanilla, White Musk, Ambroxan and Sandalwood',
        'white floral,tuberose,fruity,sweet,animalic',
        'Fakhar RosebyLattafa Perfumesis a Floral fragrance for women. This is a new fragrance.Fakhar Rosewas launched in 2022. Top notes are Fruits, Lily, Pomegranate and Aldehydes; middle notes are Tuberose, Jasmine, Gardenia, Honeysuckle, Rose, Ylang-Ylang and Peony; base notes are Vanilla, White Musk, Ambroxan and Sandalwood.',
        4.18,
        1,
        NULL
      ),
(
        'Hayaati-75902',
        'Hayaati Lattafa Perfumes',
        'Hayaati',
        'for women and men',
        NULL,
        NULL,
        'Apple and Bergamot',
        'Cinnamon and Woodsy Notes',
        'Musk and Vanilla',
        'fruity,cinnamon,musky,warm spicy,vanilla',
        'HayaatibyLattafa Perfumesis a Woody Aromatic fragrance for women and men.Hayaatiwas launched in 2020. Top notes are Apple and Bergamot; middle notes are Cinnamon and Woodsy Notes; base notes are Musk and Vanilla.',
        4.2,
        735,
        NULL
      ),
(
        'Hayaati-Al-Maleky-84306',
        'Hayaati Al Maleky Lattafa Perfumes',
        'Hayaati',
        'for women and men',
        NULL,
        NULL,
        'Nutmeg, Pink Pepper, Bergamot and Ginger',
        'Cedar, Woody Notes, Labdanum and Incense',
        'Musk, Ambergris and Amber',
        'musky,fresh spicy,woody,amber,powdery',
        'Hayaati Al MalekybyLattafa Perfumesis a Amber Spicy fragrance for women and men. This is a new fragrance.Hayaati Al Malekywas launched in 2022. Top notes are Nutmeg, Pink Pepper, Bergamot and Ginger; middle notes are Cedar, Woody Notes, Labdanum and Incense; base notes are Musk, Ambergris and Amber.',
        4.34,
        161,
        NULL
      ),
(
        'Hayaati-Florence-84769',
        'Hayaati Florence Lattafa Perfumes',
        'Hayaati',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,floral,musky,fresh',
        'Hayaati FlorencebyLattafa Perfumesis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Hayaati Florencewas launched in 2023.',
        4.41,
        139,
        NULL
      ),
(
        'Hayaati-Gold-Elixir-76589',
        'Hayaati Gold Elixir Lattafa Perfumes',
        'Hayaati',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Grapefruit and Cassis',
        'Leather, Peach and Saffron',
        'Vanilla, Amber, Musk and Vetiver',
        'leather,animalic,citrus,vanilla,powdery',
        'Hayaati Gold ElixirbyLattafa Perfumesis a fragrance for women and men. Top notes are Bergamot, Grapefruit and Cassis; middle notes are Leather, Peach and Saffron; base notes are Vanilla, Amber, Musk and Vetiver.',
        4.04,
        318,
        NULL
      ),
(
        'Khamrah-75805',
        'Khamrah Lattafa Perfumes',
        'Khamrah',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon, Nutmeg and Bergamot',
        'Dates, Praline, Tuberose and Mahonial',
        'Vanilla, Tonka Bean, Amberwood, Myrrh, Benzoin and Akigalawood',
        'sweet,warm spicy,vanilla,amber,cinnamon',
        'KhamrahbyLattafa Perfumesis a Aromatic Spicy fragrance for women and men. This is a new fragrance.Khamrahwas launched in 2022. Top notes are Cinnamon, Nutmeg and Bergamot; middle notes are Dates, Praline, Tuberose and Mahonial; base notes are Vanilla, Tonka Bean, Amberwood, Myrrh, Benzoin and Akigalawood.',
        4.39,
        9,
        NULL
      ),
(
        'Khamrah-Qahwa-88175',
        'Khamrah Qahwa Lattafa Perfumes',
        'Khamrah',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon, Cardamom and Ginger',
        'Praline, Candied Fruits and White Flowers',
        'Vanilla, Coffee, Tonka Bean, Benzoin and Musk',
        'warm spicy,sweet,vanilla,coffee,cinnamon',
        'Khamrah QahwabyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Khamrah Qahwawas launched in 2023. Top notes are Cinnamon, Cardamom and Ginger; middle notes are Praline, Candied Fruits and White Flowers; base notes are Vanilla, Coffee, Tonka Bean, Benzoin and Musk.',
        4.49,
        1,
        NULL
      ),
(
        'Emaan-85091',
        'Emaan Lattafa Perfumes',
        'Emaan',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Bergamot and Black Currant',
        'Tuberose, Jasmine and Marigold',
        'Vanilla, Musk, Patchouli and Cedarwood',
        'white floral,citrus,tuberose,animalic,fruity',
        'EmaanbyLattafa Perfumesis a Chypre Floral fragrance for women. This is a new fragrance.Emaanwas launched in 2022. Top notes are Orange Blossom, Bergamot and Black Currant; middle notes are Tuberose, Jasmine and Marigold; base notes are Vanilla, Musk, Patchouli and Cedarwood.',
        4.29,
        129,
        NULL
      ),
(
        'Haya-85031',
        'Haya Lattafa Perfumes',
        'Haya',
        'for women',
        NULL,
        NULL,
        'Champagne, Strawberry, Tangerine, Blood Orange and Rose',
        'Gardenia, Jasmine and Vanilla Orchid',
        'Amber, Sandalwood and Chestnut',
        'white floral,citrus,fruity,sweet,Champagne',
        'HayabyLattafa Perfumesis a fragrance for women. This is a new fragrance.Hayawas launched in 2022. Top notes are Champagne, Strawberry, Tangerine, Blood Orange and Rose; middle notes are Gardenia, Jasmine and Vanilla Orchid; base notes are Amber, Sandalwood and Chestnut.',
        4.2,
        285,
        NULL
      ),
(
        'Sakeena-85094',
        'Sakeena Lattafa Perfumes',
        'Sakeena',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Ozonic notes and Mandarin Orange',
        'Raspberry, Rose, Orange Blossom and Sea Salt',
        'Praline, Toffee, Vanilla and Musk',
        'sweet,fruity,rose,vanilla,tropical',
        'SakeenabyLattafa Perfumesis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Sakeenawas launched in 2022. Top notes are Passionfruit, Ozonic notes and Mandarin Orange; middle notes are Raspberry, Rose, Orange Blossom and Sea Salt; base notes are Praline, Toffee, Vanilla and Musk.',
        3.76,
        229,
        NULL
      ),
(
        'Lahdath-82379',
        'Lahdath Lattafa Perfumes',
        'Lahdath',
        'for women and men',
        NULL,
        NULL,
        'Rose and Lemon',
        'Rose and Caramel',
        'Vanilla, Musk and Cedarwood',
        'rose,vanilla,caramel,powdery,sweet',
        'LahdathbyLattafa Perfumesis a Floral Woody Musk fragrance for women and men. This is a new fragrance.Lahdathwas launched in 2022. Top notes are Rose and Lemon; middle notes are Rose and Caramel; base notes are Vanilla, Musk and Cedarwood.',
        4.11,
        91,
        NULL
      ),
(
        'Afaq-82812',
        'Afaq Lattafa Perfumes',
        'Afaq',
        'for women and men',
        NULL,
        NULL,
        'Cassis and Pear',
        'Tuberose and Jasmine',
        'Cashmeran and Sandalwood',
        'white floral,tuberose,fruity,green,woody',
        'AfaqbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Afaqwas launched in 2022. Top notes are Cassis and Pear; middle notes are Tuberose and Jasmine; base notes are Cashmeran and Sandalwood.',
        4.09,
        66,
        NULL
      ),
(
        'Affection-92183',
        'Affection Lattafa Perfumes',
        'Affection',
        'for women and men',
        NULL,
        NULL,
        'Pistachio, Hazelnut and Black Currant',
        'Lactones, Raspberry, Jasmine and Lily of the Valley',
        'Lactones, Vanilla and Tonka Bean',
        'vanilla,nutty,woody,sweet,fruity',
        'AffectionbyLattafa Perfumesis a Floral fragrance for women and men. This is a new fragrance.Affectionwas launched in 2024. Top notes are Pistachio, Hazelnut and Black Currant; middle notes are Lactones, Raspberry, Jasmine and Lily of the Valley; base notes are Lactones, Vanilla and Tonka Bean.',
        4.37,
        190,
        NULL
      ),
(
        'Al-Ameed-82471',
        'Al Ameed Lattafa Perfumes',
        'Al',
        'for men',
        NULL,
        NULL,
        'Clary Sage and Mandarin Orange',
        'Pineapple and Pepper',
        'Leather and Musk',
        'leather,fruity,aromatic,sweet,fresh spicy',
        'Al AmeedbyLattafa Perfumesis a Aromatic Spicy fragrance for men. This is a new fragrance.Al Ameedwas launched in 2022. Top notes are Clary Sage and Mandarin Orange; middle notes are Pineapple and Pepper; base notes are Leather and Musk.',
        4.09,
        92,
        NULL
      ),
(
        'Al-Areeq-Gold-82810',
        'Al Areeq Gold Lattafa Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Black Tea and Saffron',
        'Suede, Leather and Incense',
        'Vanilla, Amberwood and Musk',
        'leather,amber,vanilla,musky,smoky',
        'Al Areeq GoldbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Al Areeq Goldwas launched in 2022. Top notes are Black Tea and Saffron; middle notes are Suede, Leather and Incense; base notes are Vanilla, Amberwood and Musk.',
        4.23,
        84,
        NULL
      ),
(
        'Al-Areeq-Silver-82811',
        'Al Areeq Silver Lattafa Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Apple and Lavender',
        'Tobacco, Cypress, Oud and Jasmine',
        'Leather, Musk, Sandalwood and Vanilla',
        'leather,aromatic,woody,tobacco,warm spicy',
        'Al Areeq SilverbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Al Areeq Silverwas launched in 2022. Top notes are Cardamom, Apple and Lavender; middle notes are Tobacco, Cypress, Oud and Jasmine; base notes are Leather, Musk, Sandalwood and Vanilla.',
        3.98,
        94,
        NULL
      ),
(
        'Al-Qiam-Gold-82816',
        'Al Qiam Gold Lattafa Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Raspberry',
        'Leather and Patchouli',
        'Oud, Guaiac Wood, Benzoin, Amber and Vetiver',
        'leather,oud,warm spicy,woody,amber',
        'Al Qiam GoldbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Al Qiam Goldwas launched in 2022. Top notes are Saffron and Raspberry; middle notes are Leather and Patchouli; base notes are Oud, Guaiac Wood, Benzoin, Amber and Vetiver.',
        4.09,
        103,
        NULL
      ),
(
        'Al-Qiam-Silver-81763',
        'Al Qiam Silver Lattafa Perfumes',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit and Ginger',
        'Ambroxan and Sandalwood',
        'Vetiver and Musk',
        'citrus,amber,musky,warm spicy,aromatic',
        'Al Qiam SilverbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Al Qiam Silverwas launched in 2022. Top notes are Grapefruit and Ginger; middle notes are Ambroxan and Sandalwood; base notes are Vetiver and Musk.',
        4.4,
        311,
        NULL
      ),
(
        'Ansaam-Gold-82731',
        'Ansaam Gold Lattafa Perfumes',
        'Ansaam',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Pear',
        'Sweet Notes, Jasmine and Rose',
        'Vanilla, Musk and Raspberry',
        'sweet,fruity,musky,vanilla,citrus',
        'Ansaam GoldbyLattafa Perfumesis a Amber Floral fragrance for women. This is a new fragrance.Ansaam Goldwas launched in 2022. Top notes are Mandarin Orange and Pear; middle notes are Sweet Notes, Jasmine and Rose; base notes are Vanilla, Musk and Raspberry.',
        4.17,
        666,
        NULL
      ),
(
        'Ansaam-Silver-82788',
        'Ansaam Silver Lattafa Perfumes',
        'Ansaam',
        'for women and men',
        NULL,
        NULL,
        'Cardamom and Bergamot',
        'Davana and Lavender',
        'Vanilla, Amber and Patchouli',
        'vanilla,aromatic,warm spicy,amber,citrus',
        'Ansaam SilverbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Ansaam Silverwas launched in 2022. Top notes are Cardamom and Bergamot; middle notes are Davana and Lavender; base notes are Vanilla, Amber and Patchouli.',
        4.43,
        222,
        NULL
      ),
(
        'Art-of-Arabia-I-92423',
        'Art of Arabia I Lattafa Perfumes',
        'Art',
        'for men',
        NULL,
        NULL,
        'Bergamot and Mint',
        'Black Tea, Ginger and Lavender',
        'Ambroxan, Cinnamon and Frankincense',
        'green,citrus,fresh spicy,aromatic,amber',
        'Art of Arabia IbyLattafa Perfumesis a Citrus Aromatic fragrance for men. This is a new fragrance.Art of Arabia Iwas launched in 2023. Top notes are Bergamot and Mint; middle notes are Black Tea, Ginger and Lavender; base notes are Ambroxan, Cinnamon and Frankincense.',
        4.38,
        77,
        NULL
      ),
(
        'Art-of-Arabia-II-92424',
        'Art of Arabia II Lattafa Perfumes',
        'Art',
        'for women and men',
        NULL,
        NULL,
        'Heliotrope, Pink Pepper, Cardamom and Bergamot',
        'Jasmine, Lavender and Almond',
        'Agarwood (Oud), Guaiac Wood, Sandalwood and Vanilla',
        'woody,oud,powdery,white floral,vanilla',
        'Art of Arabia IIbyLattafa Perfumesis a Woody Spicy fragrance for women and men. This is a new fragrance.Art of Arabia IIwas launched in 2023. Top notes are Heliotrope, Pink Pepper, Cardamom and Bergamot; middle notes are Jasmine, Lavender and Almond; base notes are Agarwood (Oud), Guaiac Wood, Sandalwood and Vanilla.',
        3,
        6,
        NULL
      ),
(
        'Art-of-Arabia-III-92425',
        'Art of Arabia III Lattafa Perfumes',
        'Art',
        'for women and men',
        NULL,
        NULL,
        'Olibanum, Davana and Bergamot',
        'Dates, Tobacco, Sandalwood and Tuberose',
        'Myrrh, Vanilla, Patchouli, Tonka Bean and Labdanum',
        'sweet,amber,tobacco,warm spicy,balsamic',
        'Art of Arabia IIIbyLattafa Perfumesis a Aromatic Spicy fragrance for women and men. This is a new fragrance.Art of Arabia IIIwas launched in 2023. Top notes are Olibanum, Davana and Bergamot; middle notes are Dates, Tobacco, Sandalwood and Tuberose; base notes are Myrrh, Vanilla, Patchouli, Tonka Bean and Labdanum.',
        4.48,
        29,
        NULL
      ),
(
        'Awaan-84307',
        'Awaan Lattafa Perfumes',
        'Awaan',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Orange',
        'Orange Blossom and Jasmine',
        'Musk, Sandalwood and Patchouli',
        'citrus,white floral,woody,musky,powdery',
        'AwaanbyLattafa Perfumesis a Aromatic Fruity fragrance for women and men. This is a new fragrance.Awaanwas launched in 2022. Top notes are Bergamot and Orange; middle notes are Orange Blossom and Jasmine; base notes are Musk, Sandalwood and Patchouli.',
        4.07,
        137,
        NULL
      ),
(
        'Blue-Sapphire-82808',
        'Blue Sapphire Lattafa Perfumes',
        'Blue',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Mint and Apple',
        'Clary Sage, Marine notes and Geranium',
        'Patchouli and Cedarwood',
        'aromatic,green,fresh spicy,citrus,woody',
        'Blue SapphirebyLattafa Perfumesis a fragrance for women and men.Blue Sapphirewas launched in 2022. Top notes are Lemon, Mint and Apple; middle notes are Clary Sage, Marine notes and Geranium; base notes are Patchouli and Cedarwood.',
        4.14,
        81,
        NULL
      ),
(
        'Eternal-Oud-78155',
        'Eternal Oud Lattafa Perfumes',
        'Eternal',
        'for women and men',
        NULL,
        NULL,
        'Plum and Grapefruit',
        'Heliotrope and Orchid',
        'Amber, Benzoin, Vanilla, Labdanum, Tonka Bean and Agarwood (Oud)',
        'amber,vanilla,sweet,powdery,fruity',
        'Eternal OudbyLattafa Perfumesis a Amber fragrance for women and men. This is a new fragrance.Eternal Oudwas launched in 2022. Top notes are Plum and Grapefruit; middle notes are Heliotrope and Orchid; base notes are Amber, Benzoin, Vanilla, Labdanum, Tonka Bean and Agarwood (Oud).',
        4.24,
        1,
        NULL
      ),
(
        'Hala-82813',
        'Hala Lattafa Perfumes',
        'Hala',
        'for women and men',
        NULL,
        NULL,
        'Pepper and Nutmeg',
        'Cedarwood and Amber',
        'Incense and Labdanum',
        'amber,woody,fresh spicy,smoky,warm spicy',
        'HalabyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Halawas launched in 2022. Top notes are Pepper and Nutmeg; middle notes are Cedarwood and Amber; base notes are Incense and Labdanum.',
        4.21,
        100,
        NULL
      ),
(
        'Ishq-Al-Shuyukh-Gold-81121',
        'Ishq Al Shuyukh Gold Lattafa Perfumes',
        'Ishq',
        'for women and men',
        NULL,
        NULL,
        'Caramel and Saffron',
        'Suede, Leather and Tonka Bean',
        'Vanilla, Amber and Musk',
        'leather,vanilla,powdery,musky,caramel',
        'Ishq Al Shuyukh GoldbyLattafa Perfumesis a Amber Vanilla fragrance for women and men. This is a new fragrance.Ishq Al Shuyukh Goldwas launched in 2022. Top notes are Caramel and Saffron; middle notes are Suede, Leather and Tonka Bean; base notes are Vanilla, Amber and Musk.',
        4.28,
        587,
        NULL
      ),
(
        'Ishq-Al-Shuyukh-Silver-81099',
        'Ishq Al Shuyukh Silver Lattafa Perfumes',
        'Ishq',
        'for women and men',
        NULL,
        NULL,
        'Lemon and Bergamot',
        'Pineapple and Black Pepper',
        'Vanilla, Cedar, Amberwood and Patchouli',
        'sweet,fruity,vanilla,citrus,fresh spicy',
        'Ishq Al Shuyukh SilverbyLattafa Perfumesis a Amber fragrance for women and men. This is a new fragrance.Ishq Al Shuyukh Silverwas launched in 2022. Top notes are Lemon and Bergamot; middle notes are Pineapple and Black Pepper; base notes are Vanilla, Cedar, Amberwood and Patchouli.',
        4.57,
        253,
        NULL
      ),
(
        'La-African-Drummer-92182',
        'La African Drummer Lattafa Perfumes',
        'La',
        'for women and men',
        NULL,
        NULL,
        'Coconut and Bergamot',
        'Ylang-Ylang, Jasmine and Orange Blossom',
        'Musk, Ambroxan and Vanilla',
        'musky,white floral,sweet,yellow floral,coconut',
        'La African DrummerbyLattafa Perfumesis a Aromatic Spicy fragrance for women and men. This is a new fragrance.La African Drummerwas launched in 2024. Top notes are Coconut and Bergamot; middle notes are Ylang-Ylang, Jasmine and Orange Blossom; base notes are Musk, Ambroxan and Vanilla.',
        3.99,
        69,
        NULL
      ),
(
        'La-Collection-d-antiquites-1505-92037',
        'La Collection d''antiquités 1505 Lattafa Perfumes',
        'La',
        'for women and men',
        NULL,
        NULL,
        'Black Cherry and Saffron',
        'Frankincense, Osmanthus and Amyris',
        'Balsamic Notes, Guaiac Wood, Cypriol Oil or Nagarmotha and Styrax',
        'woody,amber,warm spicy,floral,fruity',
        'La Collection d''antiquités 1505byLattafa Perfumesis a Aromatic Fruity fragrance for women and men. This is a new fragrance.La Collection d''antiquités 1505was launched in 2023. Top notes are Black Cherry and Saffron; middle notes are Frankincense, Osmanthus and Amyris; base notes are Balsamic Notes, Guaiac Wood, Cypriol Oil or Nagarmotha and Styrax.',
        4.54,
        39,
        NULL
      ),
(
        'La-Collection-D-antiquites-1886-92028',
        'La Collection D''antiquités 1886 Lattafa Perfumes',
        'La',
        'for women and men',
        NULL,
        NULL,
        'Mate and Bergamot',
        'Orris, Bark, Cinnamon, Tonka and Jasmine',
        'White Chocolate, White Tobacco, White Musk, Vanilla and Patchouli',
        'white floral,sweet,powdery,woody,iris',
        'La Collection D''antiquités 1886byLattafa Perfumesis a Aromatic fragrance for women and men. This is a new fragrance.La Collection D''antiquités 1886was launched in 2023. Top notes are Mate and Bergamot; middle notes are Orris, Bark, Cinnamon, Tonka and Jasmine; base notes are White Chocolate, White Tobacco, White Musk, Vanilla and Patchouli.',
        4.08,
        24,
        NULL
      ),
(
        'La-Collection-D-antiquites-1910-92036',
        'La Collection D''antiquités 1910 Lattafa Perfumes',
        'La',
        'for women and men',
        NULL,
        NULL,
        'Rose, Apple and Davana',
        'Cedar and Osmanthus',
        'Tonka Bean, Vanilla and Patchouli',
        'vanilla,woody,fruity,rose,aromatic',
        'La Collection D''antiquités 1910byLattafa Perfumesis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.La Collection D''antiquités 1910was launched in 2023. Top notes are Rose, Apple and Davana; middle notes are Cedar and Osmanthus; base notes are Tonka Bean, Vanilla and Patchouli.',
        4.5,
        10,
        NULL
      ),
(
        'Maharjan-Gold-82798',
        'Maharjan Gold Lattafa Perfumes',
        'Maharjan',
        'for women and men',
        NULL,
        NULL,
        'Pepper and Lavender',
        'Incense, Tuberose and Jasmine',
        'Caramel, Cedarwood, Amber and Cashmeran',
        'amber,caramel,smoky,fresh spicy,woody',
        'Maharjan GoldbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Maharjan Goldwas launched in 2022. Top notes are Pepper and Lavender; middle notes are Incense, Tuberose and Jasmine; base notes are Caramel, Cedarwood, Amber and Cashmeran.',
        4.15,
        93,
        NULL
      ),
(
        'Maharjan-Silver-82799',
        'Maharjan Silver Lattafa Perfumes',
        'Maharjan',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Mandarin Orange',
        'Iris and Jasmine',
        'Musk, Vetiver and Birch',
        'citrus,woody,powdery,musky,aromatic',
        'Maharjan SilverbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Maharjan Silverwas launched in 2022. Top notes are Bergamot and Mandarin Orange; middle notes are Iris and Jasmine; base notes are Musk, Vetiver and Birch.',
        4.04,
        45,
        NULL
      ),
(
        'Masa-88636',
        'Masa Lattafa Perfumes',
        'Masa',
        'for women and men',
        NULL,
        NULL,
        'Mango, Saffron, Lemon and Pink Pepper',
        'Violet Leaf, Ginger, Osmanthus and Orange Blossom',
        'Mineral notes, Suede, Patchouli and Amber',
        'mineral,leather,warm spicy,fruity,tropical',
        'MasabyLattafa Perfumesis a Floral Fruity fragrance for women and men. This is a new fragrance.Masawas launched in 2023. Top notes are Mango, Saffron, Lemon and Pink Pepper; middle notes are Violet Leaf, Ginger, Osmanthus and Orange Blossom; base notes are Mineral notes, Suede, Patchouli and Amber.',
        4.06,
        246,
        NULL
      ),
(
        'Nebras-78560',
        'Nebras Lattafa Perfumes',
        'Nebras',
        'for women and men',
        NULL,
        NULL,
        'Red Berries and Mandarin Orange',
        'Vanilla, Cacao and Rose',
        'Sugar, Tonka Bean, Amber and Musk',
        'vanilla,sweet,cacao,warm spicy,amber',
        'NebrasbyLattafa Perfumesis a Amber Vanilla fragrance for women and men. This is a new fragrance.Nebraswas launched in 2022. Top notes are Red Berries and Mandarin Orange; middle notes are Vanilla, Cacao and Rose; base notes are Sugar, Tonka Bean, Amber and Musk.',
        4.31,
        1,
        NULL
      ),
(
        'Royal-Sapphire-82809',
        'Royal Sapphire Lattafa Perfumes',
        'Royal',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Mandarin Orange and Lemon',
        'Jasmine and Rose',
        'Ambergris, Musk and Vanilla',
        'citrus,amber,warm spicy,animalic,metallic',
        'Royal SapphirebyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Royal Sapphirewas launched in 2022. Top notes are Saffron, Mandarin Orange and Lemon; middle notes are Jasmine and Rose; base notes are Ambergris, Musk and Vanilla.',
        4.16,
        73,
        NULL
      ),
(
        'Shaheen-Gold-82814',
        'Shaheen Gold Lattafa Perfumes',
        'Shaheen',
        'for women and men',
        NULL,
        NULL,
        'Pineapple and Grapefruit',
        'Fig and Lavender',
        'Vanilla, Tonka and Patchouli',
        'sweet,fruity,vanilla,citrus,lavender',
        'Shaheen GoldbyLattafa Perfumesis a fragrance for women and men.Shaheen Goldwas launched in 2022. Top notes are Pineapple and Grapefruit; middle notes are Fig and Lavender; base notes are Vanilla, Tonka and Patchouli.',
        4.23,
        182,
        NULL
      ),
(
        'Shaheen-Silver-82815',
        'Shaheen Silver Lattafa Perfumes',
        'Shaheen',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Cassis',
        'Patchouli and Rose',
        'Oakmoss, Musk and Amber',
        'mossy,earthy,woody,citrus,patchouli',
        'Shaheen SilverbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Shaheen Silverwas launched in 2022. Top notes are Bergamot and Cassis; middle notes are Patchouli and Rose; base notes are Oakmoss, Musk and Amber.',
        4.16,
        120,
        NULL
      ),
(
        'Tharwah-Gold-82004',
        'Tharwah Gold Lattafa Perfumes',
        'Tharwah',
        'for women',
        NULL,
        NULL,
        'Lavender and Bergamot',
        'Orange Blossom and Egyptian Jasmine',
        'Vanilla, Amber and Vetiver',
        'white floral,citrus,vanilla,lavender,amber',
        'Tharwah GoldbyLattafa Perfumesis a Amber Floral fragrance for women. This is a new fragrance.Tharwah Goldwas launched in 2022. Top notes are Lavender and Bergamot; middle notes are Orange Blossom and Egyptian Jasmine; base notes are Vanilla, Amber and Vetiver.',
        4.48,
        276,
        NULL
      ),
(
        'Tharwah-Silver-82005',
        'Tharwah Silver Lattafa Perfumes',
        'Tharwah',
        'for men',
        NULL,
        NULL,
        'Mint and Bergamot',
        'Clary Sage and Lavender',
        'Musk, Vetiver and Cedar',
        'aromatic,green,fresh spicy,lavender,citrus',
        'Tharwah SilverbyLattafa Perfumesis a Woody Aquatic fragrance for men. This is a new fragrance.Tharwah Silverwas launched in 2022. Top notes are Mint and Bergamot; middle notes are Clary Sage and Lavender; base notes are Musk, Vetiver and Cedar.',
        4,
        84,
        NULL
      ),
(
        'Thouq-82693',
        'Thouq Lattafa Perfumes',
        'Thouq',
        'for women and men',
        NULL,
        NULL,
        'Litchi and Bergamot',
        'Rose and Incense',
        'Amber and Vetiver',
        'amber,rose,smoky,fruity,balsamic',
        'ThouqbyLattafa Perfumesis a Floral fragrance for women and men. This is a new fragrance.Thouqwas launched in 2022. Top notes are Litchi and Bergamot; middle notes are Rose and Incense; base notes are Amber and Vetiver.',
        4.06,
        68,
        NULL
      ),
(
        'Vintage-Radio-89454',
        'Vintage Radio Lattafa Perfumes',
        'Vintage',
        'for women and men',
        NULL,
        NULL,
        'Lavender, Bergamot and Sage',
        'Plum, Palo Santo and Black Pepper',
        'Sandalwood and Oud',
        'woody,fruity,aromatic,citrus,lavender',
        'Vintage RadiobyLattafa Perfumesis a Amber Woody fragrance for women and men. This is a new fragrance.Vintage Radiowas launched in 2023. Top notes are Lavender, Bergamot and Sage; middle notes are Plum, Palo Santo and Black Pepper; base notes are Sandalwood and Oud.',
        4.5,
        419,
        NULL
      ),
(
        'Wajood-80467',
        'Wajood Lattafa Perfumes',
        'Wajood',
        'for women and men',
        NULL,
        NULL,
        'Sea Notes and Pink Pepper',
        'Vetiver and Patchouli',
        'Sandalwood and Amber',
        'woody,aromatic,marine,earthy,warm spicy',
        'WajoodbyLattafa Perfumesis a Aromatic Aquatic fragrance for women and men. This is a new fragrance.Wajoodwas launched in 2022. Top notes are Sea Notes and Pink Pepper; middle notes are Vetiver and Patchouli; base notes are Sandalwood and Amber.',
        3.99,
        216,
        NULL
      ),
(
        'Winners-Trophy-Gold-82621',
        'Winners Trophy Gold Lattafa Perfumes',
        'Winners',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper',
        'Jasmine and Rose',
        'Musk, Patchouli and Vanilla',
        'musky,powdery,white floral,patchouli,rose',
        'Winners Trophy GoldbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Winners Trophy Goldwas launched in 2022. Top note is Pink Pepper; middle notes are Jasmine and Rose; base notes are Musk, Patchouli and Vanilla.',
        4.15,
        26,
        NULL
      ),
(
        'Winners-Trophy-Silver-82622',
        'Winners Trophy Silver Lattafa Perfumes',
        'Winners',
        'for women and men',
        NULL,
        NULL,
        'Olibanum and Orange',
        'Lavender and Vanilla',
        'Cedarwood and Vetiver',
        'amber,woody,fresh spicy,citrus,aromatic',
        'Winners Trophy SilverbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Winners Trophy Silverwas launched in 2022. Top notes are Olibanum and Orange; middle notes are Lavender and Vanilla; base notes are Cedarwood and Vetiver.',
        4.09,
        78,
        NULL
      ),
(
        'Maahir-64950',
        'Maahir Lattafa Perfumes',
        'Maahir',
        'for women and men',
        NULL,
        NULL,
        'Red Berries, Peach and Bergamot',
        'Jasmine, Peony and Red Lily',
        'Sandalwood, Vanilla Flower and Musk',
        'powdery,woody,vanilla,musky,fruity',
        'MaahirbyLattafa Perfumesis a Amber Floral fragrance for women and men.Maahirwas launched in 2020. Top notes are Red Berries, Peach and Bergamot; middle notes are Jasmine, Peony and Red Lily; base notes are Sandalwood, Vanilla Flower and Musk.',
        3.91,
        494,
        NULL
      ),
(
        'Maahir-Black-Edition-66564',
        'Maahir Black Edition Lattafa Perfumes',
        'Maahir',
        'for women and men',
        NULL,
        NULL,
        'Black Pepper, Pink Pepper and Saffron',
        'Labdanum, Cade oil, Gurjan balsam and Rhubarb',
        'Leather, Cedar, Guaiac Wood, Patchouli, Musk and Moss',
        'woody,fresh spicy,leather,aromatic,warm spicy',
        'Maahir Black EditionbyLattafa Perfumesis a Amber Spicy fragrance for women and men.Maahir Black Editionwas launched in 2019. Top notes are Black Pepper, Pink Pepper and Saffron; middle notes are Labdanum, Cade oil, Gurjan balsam and Rhubarb; base notes are Leather, Cedar, Guaiac Wood, Patchouli, Musk and Moss.',
        4.09,
        774,
        NULL
      ),
(
        'Maahir-Legacy-82727',
        'Maahir Legacy Lattafa Perfumes',
        'Maahir',
        'for men',
        NULL,
        NULL,
        'Lime, Mint, Grapefruit, Lavender and Pineapple',
        'juniper berry, Black Pepper, Rosemary, Geranium and Frankincense',
        'Ambroxan, Oakmoss, Tonka Bean, Vetiver and Cashmeran',
        'aromatic,fresh spicy,citrus,green,amber',
        'Maahir LegacybyLattafa Perfumesis a fragrance for men. Top notes are Lime, Mint, Grapefruit, Lavender and Pineapple; middle notes are juniper berry, Black Pepper, Rosemary, Geranium and Frankincense; base notes are Ambroxan, Oakmoss, Tonka Bean, Vetiver and Cashmeran.',
        4.27,
        1,
        NULL
      ),
(
        'Najdia-66011',
        'Najdia Lattafa Perfumes',
        'Najdia',
        'for women and men',
        NULL,
        NULL,
        'Lemon, Cinnamon, Apple, Lemongrass and Bergamot',
        'Watery Notes, Lavender, Cardamom and Rosemary',
        'Musk, Amber, Sandalwood, Cedar and Tobacco',
        'citrus,aromatic,warm spicy,aquatic,fresh spicy',
        'NajdiabyLattafa Perfumesis a Aromatic Aquatic fragrance for women and men.Najdiawas launched in 2020. Top notes are Lemon, Cinnamon, Apple, Lemongrass and Bergamot; middle notes are Watery Notes, Lavender, Cardamom and Rosemary; base notes are Musk, Amber, Sandalwood, Cedar and Tobacco.',
        4.09,
        907,
        NULL
      ),
(
        'Najdia-in-Gold-78617',
        'Najdia in Gold Lattafa Perfumes',
        'Najdia',
        'for women and men',
        NULL,
        NULL,
        'Bay Leaf, Grapefruit and Sea Notes',
        'Patchouli and Guaiac Wood',
        'Ambergris and Oakmoss',
        'woody,patchouli,amber,earthy,fresh spicy',
        'Najdia in GoldbyLattafa Perfumesis a Floral fragrance for women and men.Najdia in Goldwas launched in 2021. Top notes are Bay Leaf, Grapefruit and Sea Notes; middle notes are Patchouli and Guaiac Wood; base notes are Ambergris and Oakmoss.',
        3.69,
        26,
        NULL
      ),
(
        'Najdia-Tribute-72491',
        'Najdia Tribute Lattafa Perfumes',
        'Najdia',
        'for women and men',
        NULL,
        NULL,
        'Ginger, Apple, Mandarin Orange and Bergamot',
        'Violet Leaf, Guaiac Wood, Saffron and Cedar',
        'Leather, Ambergris, Agarwood (Oud) and Sandalwood',
        'leather,ozonic,woody,animalic,aquatic',
        'Najdia TributebyLattafa Perfumesis a Leather fragrance for women and men.Najdia Tributewas launched in 2021. Top notes are Ginger, Apple, Mandarin Orange and Bergamot; middle notes are Violet Leaf, Guaiac Wood, Saffron and Cedar; base notes are Leather, Ambergris, Agarwood (Oud) and Sandalwood.',
        3.99,
        139,
        NULL
      ),
(
        'Blue-Oud-70102',
        'Blue Oud Lattafa Perfumes',
        'Blue',
        'for women and men',
        NULL,
        NULL,
        'Agarwood (Oud), Black Pepper, Apple and Bergamot',
        'Fruits, Musk, Saffron, Sage and Jasmine',
        'Ambergris, Sandalwood and Guaiac Wood',
        'fruity,fresh spicy,oud,woody,warm spicy',
        'Blue OudbyLattafa Perfumesis a Amber Woody fragrance for women and men.Blue Oudwas launched in 2018. Top notes are Agarwood (Oud), Black Pepper, Apple and Bergamot; middle notes are Fruits, Musk, Saffron, Sage and Jasmine; base notes are Ambergris, Sandalwood and Guaiac Wood.',
        3.88,
        270,
        NULL
      ),
(
        'Opulent-Musk-67940',
        'Opulent Musk Lattafa Perfumes',
        'Opulent',
        'for women',
        NULL,
        NULL,
        'White Musk, Saffron and Lemon',
        'White Flowers and Jasmine',
        'White Musk, Cedar, Amber, Resin and Fir Resin',
        'musky,amber,woody,warm spicy,powdery',
        'Opulent MuskbyLattafa Perfumesis a Amber fragrance for women.Opulent Muskwas launched in 2019. Top notes are White Musk, Saffron and Lemon; middle notes are White Flowers and Jasmine; base notes are White Musk, Cedar, Amber, Resin and Fir Resin.',
        3.66,
        525,
        NULL
      ),
(
        'Opulent-Oud-66012',
        'Opulent Oud Lattafa Perfumes',
        'Opulent',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Cinnamon',
        'Agarwood (Oud) and Rose',
        'Agarwood (Oud), Amber and Cedarwood',
        'oud,warm spicy,amber,metallic,rose',
        'Opulent OudbyLattafa Perfumesis a Amber fragrance for women and men.Opulent Oudwas launched in 2018. Top notes are Saffron and Cinnamon; middle notes are Agarwood (Oud) and Rose; base notes are Agarwood (Oud), Amber and Cedarwood.',
        4.08,
        842,
        NULL
      ),
(
        'Opulent-Red-75180',
        'Opulent Red Lattafa Perfumes',
        'Opulent',
        'for women and men',
        NULL,
        NULL,
        'Blood Orange, Pear, Pink Pepper and Cardamom',
        'Tuberose, Jasmine, Heliotrope, Brazilian Rosewood and Cognac',
        'Agarwood (Oud), Vanilla, Amber, Sandalwood, Tonka Bean, Patchouli and Cashmeran',
        'woody,white floral,vanilla,powdery,amber',
        'Opulent RedbyLattafa Perfumesis a Floral Fruity fragrance for women and men. This is a new fragrance.Opulent Redwas launched in 2022. Top notes are Blood Orange, Pear, Pink Pepper and Cardamom; middle notes are Tuberose, Jasmine, Heliotrope, Brazilian Rosewood and Cognac; base notes are Agarwood (Oud), Vanilla, Amber, Sandalwood, Tonka Bean, Patchouli and Cashmeran.',
        3.67,
        504,
        NULL
      ),
(
        'Raghba-25807',
        'Raghba Lattafa Perfumes',
        'Raghba',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,oud,amber,powdery',
        'RaghbabyLattafa Perfumesis a Amber Vanilla fragrance for women and men.',
        3.93,
        3,
        NULL
      ),
(
        'Raghba-Classic-25878',
        'Raghba Classic Lattafa Perfumes',
        'Raghba',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,vanilla,balsamic,woody,warm spicy',
        'Raghba ClassicbyLattafa Perfumesis a Amber Spicy fragrance for women and men.',
        4.2,
        118,
        NULL
      ),
(
        'Raghba-For-Men-25820',
        'Raghba For Men Lattafa Perfumes',
        'Raghba',
        'for men',
        NULL,
        NULL,
        'Lemon Verbena, Iris and Lemon',
        'Violet Leaf',
        'Sandalwood, Ambergris, Leather and Cedar',
        'citrus,woody,powdery,iris,ozonic',
        'Raghba For MenbyLattafa Perfumesis a Amber Fougere fragrance for men. Top notes are Lemon Verbena, Iris and Lemon; middle note is Violet Leaf; base notes are Sandalwood, Ambergris, Leather and Cedar.',
        4.02,
        391,
        NULL
      ),
(
        'Raghba-Muski-32301',
        'Raghba Muski Lattafa Perfumes',
        'Raghba',
        'for women and men',
        NULL,
        NULL,
        'Musk and Lily-of-the-Valley',
        'Musk and Sugar',
        'Musk, Vanilla and Sandalwood',
        'vanilla,powdery,musky,sweet,woody',
        'Raghba MuskibyLattafa Perfumesis a Woody Floral Musk fragrance for women and men.Raghba Muskiwas launched in 2015. Top notes are Musk and Lily-of-the-Valley; middle notes are Musk and Sugar; base notes are Musk, Vanilla and Sandalwood.',
        4.33,
        69,
        NULL
      ),
(
        'Raghba-Wood-Intense-28713',
        'Raghba Wood Intense Lattafa Perfumes',
        'Raghba',
        'for men',
        NULL,
        NULL,
        'Caramel, Licorice, Guaiac Wood and Cedar',
        'Sugar, Agarwood (Oud), Sandalwood and Cashmere Wood',
        'Incense, Vanilla, Amber, Oakmoss and Musk',
        'woody,amber,sweet,balsamic,smoky',
        'Raghba Wood IntensebyLattafa Perfumesis a Amber Woody fragrance for men.Raghba Wood Intensewas launched in 2014. Top notes are Caramel, Licorice, Guaiac Wood and Cedar; middle notes are Sugar, Agarwood (Oud), Sandalwood and Cashmere Wood; base notes are Incense, Vanilla, Amber, Oakmoss and Musk.',
        4.14,
        1,
        NULL
      ),
(
        'Teriaq-89850',
        'Teriaq Lattafa Perfumes',
        'Teriaq',
        'for women and men',
        NULL,
        'Quentin Bisch',
        'Caramel, Bitter Almond, Pink Pepper and Apricot',
        'Honey, Rhubarb, White Flowers and Rose',
        'Leather, Vanilla, Musk, Vetiver and Labdanum',
        'sweet,caramel,honey,leather,fruity',
        'TeriaqbyLattafa Perfumesis a fragrance for women and men. This is a new fragrance.Teriaqwas launched in 2024. The nose behind this fragrance is Quentin Bisch. Top notes are Caramel, Bitter Almond, Pink Pepper and Apricot; middle notes are Honey, Rhubarb, White Flowers and Rose; base notes are Leather, Vanilla, Musk, Vetiver and Labdanum.',
        4,
        610,
        NULL
      ),
(
        'Musk-Candy-Rose-80260',
        'Musk Candy Rose Lattafa Perfumes',
        'Musk',
        'for women and men',
        NULL,
        NULL,
        'Rose and Citruses',
        'White Musk and Floral Notes',
        'Musk and Amber',
        'floral,rose,musky,powdery,amber',
        'Musk Candy RosebyLattafa Perfumesis a fragrance for women and men.Musk Candy Rosewas launched during the 2020''s. Top notes are Rose and Citruses; middle notes are White Musk and Floral Notes; base notes are Musk and Amber.',
        3.94,
        48,
        NULL
      ),
(
        'Musk-So-Poudree-80261',
        'Musk So Poudrée Lattafa Perfumes',
        'Musk',
        'for women and men',
        NULL,
        NULL,
        'Powdery Notes and Floral Notes',
        'Powdery Notes and Woody Notes',
        'Musk and Amber',
        'powdery,musky',
        'Musk So PoudréebyLattafa Perfumesis a fragrance for women and men.Musk So Poudréewas launched during the 2020''s. Top notes are Powdery Notes and Floral Notes; middle notes are Powdery Notes and Woody Notes; base notes are Musk and Amber.',
        3.95,
        60,
        NULL
      );
