
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Younique-35893',
        'Younique Ajmal',
        'Younique',
        'for women',
        NULL,
        NULL,
        'Floral Notes',
        'Floral Notes and Spicy Notes',
        'Agarwood (Oud) and Powdery Notes',
        'floral,oud,powdery,warm spicy',
        'YouniquebyAjmalis a Floral Woody Musk fragrance for women.Youniquewas launched in 2016. Top note is Floral Notes; middle notes are Floral Notes and Spicy Notes; base notes are Agarwood (Oud) and Powdery Notes.',
        4.12,
        33,
        NULL
      ),
(
        'Ajmal-II-26882',
        'Ajmal II Ajmal',
        'Ajmal',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,rose,floral,woody,powdery',
        'Ajmal IIbyAjmalis a Amber Floral fragrance for women and men.',
        4.08,
        26,
        NULL
      ),
(
        'Al-Janaan-32507',
        'Al Janaan Ajmal',
        'Al',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,powdery',
        'Al JanaanbyAjmalis a Floral Woody Musk fragrance for women and men.',
        4.29,
        31,
        NULL
      ),
(
        'Amaris-32508',
        'Amaris Ajmal',
        'Amaris',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,rose,aromatic,green',
        'AmarisbyAjmalis a Amber fragrance for women and men.',
        3.33,
        18,
        NULL
      ),
(
        'Aqamaar-32511',
        'Aqamaar Ajmal',
        'Aqamaar',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,warm spicy,vanilla,fresh spicy',
        'AqamaarbyAjmalis a Amber fragrance for women.',
        3.61,
        18,
        NULL
      ),
(
        'Believe-For-Her-15066',
        'Believe For Her Ajmal',
        'Believe',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,powdery,sweet,rose',
        'Believe For HerbyAjmalis a Floral Fruity fragrance for women.',
        4.15,
        27,
        NULL
      ),
(
        'Believe-For-Him-15067',
        'Believe For Him Ajmal',
        'Believe',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,floral,citrus,warm spicy,lavender',
        'Believe For HimbyAjmalis a Aromatic fragrance for men.',
        4.06,
        16,
        NULL
      ),
(
        'Believe-Forever-32513',
        'Believe Forever Ajmal',
        'Believe',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,fresh spicy,oud,amber',
        'Believe ForeverbyAjmalis a Woody Spicy fragrance for women and men.',
        3.84,
        31,
        NULL
      ),
(
        'Contempo-32510',
        'Contempo Ajmal',
        'Contempo',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,musky,floral,powdery,soft spicy',
        'ContempobyAjmalis a Floral Woody Musk fragrance for women.',
        4.12,
        17,
        NULL
      ),
(
        'Crescent-32509',
        'Crescent Ajmal',
        'Crescent',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,oud,powdery,musky',
        'CrescentbyAjmalis a Amber fragrance for women and men.',
        3,
        9,
        NULL
      ),
(
        'Regalo-32512',
        'Regalo Ajmal',
        'Regalo',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,fruity,fresh spicy,rose,sweet',
        'RegalobyAjmalis a Amber fragrance for women.Regalowas launched in 2015.',
        3.29,
        14,
        NULL
      ),
(
        'Relentless-15093',
        'Relentless Ajmal',
        'Relentless',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,warm spicy,woody,musky,rose',
        'RelentlessbyAjmalis a Woody Floral Musk fragrance for women and men.',
        4.25,
        16,
        NULL
      ),
(
        'Stature-32515',
        'Stature Ajmal',
        'Stature',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,floral,musky,soft spicy,fresh',
        'StaturebyAjmalis a Amber Floral fragrance for women and men.',
        4.4,
        15,
        NULL
      ),
(
        'Tempest-32516',
        'Tempest Ajmal',
        'Tempest',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,oud,tobacco,patchouli,rose',
        'TempestbyAjmalis a Amber fragrance for women and men.',
        4.24,
        25,
        NULL
      ),
(
        'Unveil-6925',
        'Unveil Ajmal',
        'Unveil',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,white floral,fresh spicy,woody,rose',
        'UnveilbyAjmalis a Floral Woody Musk fragrance for women.Unveilwas launched in 2007.',
        3.88,
        42,
        NULL
      ),
(
        'Aatifa-19425',
        'Aatifa Ajmal',
        'Aatifa',
        'for women and men',
        NULL,
        NULL,
        'Rose, Cumin and Nutmeg',
        'Woody Notes and Amber',
        'Musk and Amber',
        'fresh spicy,woody,musky,rose,amber',
        'AatifabyAjmalis a Floral Woody Musk fragrance for women and men.Aatifawas launched in 2014. Top notes are Rose, Cumin and Nutmeg; middle notes are Woody Notes and Amber; base notes are Musk and Amber.',
        4.02,
        93,
        NULL
      ),
(
        'Abia-26791',
        'Abia Ajmal',
        'Abia',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Bergamot and Lemon',
        'Violet, Cardamom and Artemisia',
        'Musk, Patchouli, Cedar, Guaiac Wood and Vetiver',
        'woody,musky,powdery,aromatic,warm spicy',
        'AbiabyAjmalis a Woody Floral Musk fragrance for women.Abiawas launched in 2014. Top notes are Pink Pepper, Bergamot and Lemon; middle notes are Violet, Cardamom and Artemisia; base notes are Musk, Patchouli, Cedar, Guaiac Wood and Vetiver.',
        4.28,
        40,
        NULL
      ),
(
        'Ahbab-14045',
        'Ahbab Ajmal',
        'Ahbab',
        'for women',
        NULL,
        'Nazir Ajmal',
        'Bergamot and Rose',
        'Virginia Cedar, Iris and Jasmine',
        'Musk',
        'woody,citrus,powdery,musky,rose',
        'AhbabbyAjmalis a Floral fragrance for women.Ahbabwas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal. Top notes are Bergamot and Rose; middle notes are Virginia Cedar, Iris and Jasmine; base note is Musk.',
        3.74,
        19,
        NULL
      ),
(
        'Al-Reda-35899',
        'Al Reda Ajmal',
        'Al',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,woody,amber,white floral,warm spicy',
        'Al RedabyAjmalis a Amber Floral fragrance for women and men.Al Redawas launched in 2015.',
        4.27,
        11,
        NULL
      ),
(
        'Alf-Lail-o-Lail-14046',
        'Alf Lail o Lail Ajmal',
        'Alf',
        'for women',
        NULL,
        'Nazir Ajmal',
        NULL,
        NULL,
        NULL,
        'woody,musky,floral,warm spicy,powdery',
        'Alf Lail o LailbyAjmalis a Floral Woody Musk fragrance for women.Alf Lail o Lailwas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal.',
        3.99,
        270,
        NULL
      ),
(
        'Areej-Al-Shouk-14048',
        'Areej Al Shouk Ajmal',
        'Areej',
        'for women',
        NULL,
        'Nazir Ajmal',
        NULL,
        NULL,
        NULL,
        'floral,musky,woody,warm spicy,powdery',
        'Areej Al ShoukbyAjmalis a Floral Woody Musk fragrance for women.Areej Al Shoukwas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal.',
        4.3,
        89,
        NULL
      ),
(
        'Asaateer-15049',
        'Asaateer Ajmal',
        'Asaateer',
        'for women',
        NULL,
        NULL,
        'Saffron, Cardamom and Pink Pepper',
        'White Flowers, Rose and Osmanthus',
        'Agarwood (Oud), Oakmoss, Vetiver and Sandalwood',
        'warm spicy,oud,white floral,earthy,woody',
        'AsaateerbyAjmalis a Amber Floral fragrance for women. Top notes are Saffron, Cardamom and Pink Pepper; middle notes are White Flowers, Rose and Osmanthus; base notes are Agarwood (Oud), Oakmoss, Vetiver and Sandalwood.',
        3.82,
        17,
        NULL
      ),
(
        'Asheem-14049',
        'Asheem Ajmal',
        'Asheem',
        'for women and men',
        NULL,
        'Nazir Ajmal',
        'Sandalwood and Amber',
        'Clary Sage',
        'Agarwood (Oud) and Musk',
        'oud,musky,powdery,aromatic,amber',
        'AsheembyAjmalis a Amber fragrance for women and men.Asheemwas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal. Top notes are Sandalwood and Amber; middle note is Clary Sage; base notes are Agarwood (Oud) and Musk.',
        4.24,
        34,
        NULL
      ),
(
        'Baaqa-14050',
        'Baaqa Ajmal',
        'Baaqa',
        'for women',
        NULL,
        'Nazir Ajmal',
        'Saffron, Mandarin Orange and Musk',
        'Floral Notes and Jasmine',
        'Agarwood (Oud), Sandalwood and Amber',
        'warm spicy,oud,floral,woody,amber',
        'BaaqabyAjmalis a Amber fragrance for women.Baaqawas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal. Top notes are Saffron, Mandarin Orange and Musk; middle notes are Floral Notes and Jasmine; base notes are Agarwood (Oud), Sandalwood and Amber.',
        3.47,
        57,
        NULL
      ),
(
        'Dahn-Al-Oudh-Moattaq-15069',
        'Dahn Al Oudh Moattaq Ajmal',
        'Dahn',
        'for women and men',
        NULL,
        NULL,
        'Rose, Woodsy Notes and Spices',
        'Agarwood (Oud) and Ambergris',
        'Musk and Powdery Notes',
        'oud,powdery,amber,musky,rose',
        'Dahn Al Oudh MoattaqbyAjmalis a Amber Spicy fragrance for women and men. Top notes are Rose, Woodsy Notes and Spices; middle notes are Agarwood (Oud) and Ambergris; base notes are Musk and Powdery Notes.',
        4.56,
        107,
        NULL
      ),
(
        'Ghair-1-15113',
        'Ghair 1 Ajmal',
        'Ghair',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,oud,powdery',
        'Ghair 1byAjmalis a Amber Woody fragrance for women and men.',
        4.57,
        7,
        NULL
      ),
(
        'Ghair-2-15114',
        'Ghair 2 Ajmal',
        'Ghair',
        'for women and men',
        NULL,
        NULL,
        'Cedar and Mandarin Orange',
        'Musk, Cedar, Spicy Notes and Sandalwood',
        'Musk, Ambergris and Sandalwood',
        'woody,musky,powdery,amber,animalic',
        'Ghair 2byAjmalis a Amber Woody fragrance for women and men. Top notes are Cedar and Mandarin Orange; middle notes are Musk, Cedar, Spicy Notes and Sandalwood; base notes are Musk, Ambergris and Sandalwood.',
        3.75,
        4,
        NULL
      ),
(
        'Ghair-3-15115',
        'Ghair 3 Ajmal',
        'Ghair',
        'for women',
        NULL,
        NULL,
        'Fruity Notes and Spicy Notes',
        'Fruity Notes, Spicy Notes and Woody Notes',
        'Spicy Notes, Woody Notes and Musk',
        'fruity,sweet,warm spicy,woody,musky',
        'Ghair 3byAjmalis a Woody Spicy fragrance for women. Top notes are Fruity Notes and Spicy Notes; middle notes are Fruity Notes, Spicy Notes and Woody Notes; base notes are Spicy Notes, Woody Notes and Musk.',
        4.33,
        12,
        NULL
      ),
(
        'Ghair-4-26884',
        'Ghair 4 Ajmal',
        'Ghair',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes and Citruses',
        'Spicy Notes and Musk',
        'Woody Notes',
        'woody,floral,citrus,warm spicy',
        'Ghair 4byAjmalis a Amber Floral fragrance for women and men.Ghair 4was launched in 2014. Top notes are Floral Notes and Citruses; middle notes are Spicy Notes and Musk; base note is Woody Notes.',
        4.33,
        3,
        NULL
      ),
(
        'Ghair-5-26883',
        'Ghair 5 Ajmal',
        'Ghair',
        'for women and men',
        NULL,
        NULL,
        'Cloves, Citruses, Cardamom and Ginger',
        'Sandalwood, Cedar and Amber',
        'Sandalwood, Cedar and Amber',
        'warm spicy,woody,powdery,amber,citrus',
        'Ghair 5byAjmalis a Woody Spicy fragrance for women and men.Ghair 5was launched in 2014. Top notes are Cloves, Citruses, Cardamom and Ginger; middle notes are Sandalwood, Cedar and Amber; base notes are Sandalwood, Cedar and Amber.',
        3.67,
        3,
        NULL
      ),
(
        'Haalih-15074',
        'Haalih Ajmal',
        'Haalih',
        'for women',
        NULL,
        NULL,
        'Cardamom, Brazilian Rosewood and Pink Pepper',
        'Agarwood (Oud), Labdanum and Fir',
        'Patchouli, Ambergris and Musk',
        'woody,warm spicy,amber,balsamic,oud',
        'HaalihbyAjmalis a Amber Woody fragrance for women. Top notes are Cardamom, Brazilian Rosewood and Pink Pepper; middle notes are Agarwood (Oud), Labdanum and Fir; base notes are Patchouli, Ambergris and Musk.',
        4.2,
        10,
        NULL
      ),
(
        'Haem-35225',
        'Haem Ajmal',
        'Haem',
        'for women and men',
        NULL,
        NULL,
        'Citruses',
        'Flowers and Amber',
        'Woodsy Notes and Musk',
        'floral,woody,citrus,amber,musky',
        'HaembyAjmalis a Amber Floral fragrance for women and men.Haemwas launched in 2015. Top note is Citruses; middle notes are Flowers and Amber; base notes are Woodsy Notes and Musk.',
        3.66,
        67,
        NULL
      ),
(
        'Hanaa-14027',
        'Hanaa Ajmal',
        'Hanaa',
        'for women and men',
        NULL,
        'Nazir Ajmal',
        'Rose, White Musk and Saffron',
        'Musk and Rose',
        'Amber, Agarwood (Oud), Sandalwood and Oakmoss',
        'floral,rose,musky,amber,oud',
        'HanaabyAjmalis a Floral Woody Musk fragrance for women and men.Hanaawas launched in 2011. The nose behind this fragrance is Nazir Ajmal. Top notes are Rose, White Musk and Saffron; middle notes are Musk and Rose; base notes are Amber, Agarwood (Oud), Sandalwood and Oakmoss.',
        4.56,
        9,
        NULL
      ),
(
        'Khallab-14037',
        'Khallab Ajmal',
        'Khallab',
        'for women and men',
        NULL,
        'Nazir Ajmal',
        NULL,
        NULL,
        NULL,
        'oud,citrus,woody,rose,warm spicy',
        'KhallabbyAjmalis a Amber fragrance for women and men.Khallabwas launched in 2011. The nose behind this fragrance is Nazir Ajmal.',
        4.25,
        130,
        NULL
      ),
(
        'Khawatir-15080',
        'Khawatir Ajmal',
        'Khawatir',
        'for women',
        NULL,
        NULL,
        'Rose and Litchi',
        'Woodsy Notes and Spices',
        'Saffron and Musk',
        'rose,warm spicy,woody,metallic,fruity',
        'KhawatirbyAjmalis a Floral Fruity fragrance for women.Khawatirwas launched in 2010. Top notes are Rose and Litchi; middle notes are Woodsy Notes and Spices; base notes are Saffron and Musk.',
        4,
        12,
        NULL
      ),
(
        'Lahadhaat-15081',
        'Lahadhaat Ajmal',
        'Lahadhaat',
        'for women and men',
        NULL,
        NULL,
        'Green Notes, Bergamot and Mandarin Orange',
        'Geranium, Rose, Cardamom, Pepper and Vanilla',
        'Ambergris, Sandalwood, Agarwood (Oud), Labdanum and Musk',
        'fresh spicy,amber,warm spicy,aromatic,citrus',
        'LahadhaatbyAjmalis a Floral Woody Musk fragrance for women and men. Top notes are Green Notes, Bergamot and Mandarin Orange; middle notes are Geranium, Rose, Cardamom, Pepper and Vanilla; base notes are Ambergris, Sandalwood, Agarwood (Oud), Labdanum and Musk.',
        4,
        15,
        NULL
      ),
(
        'Maraam-15082',
        'Maraam Ajmal',
        'Maraam',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,fruity,amber,tropical,animalic',
        'MaraambyAjmalis a Amber Floral fragrance for women.',
        4.08,
        79,
        NULL
      ),
(
        'Marah-19427',
        'Marah Ajmal',
        'Marah',
        'for women',
        NULL,
        NULL,
        'Bergamot, Ginger and Woody Notes',
        'Rose, Citruses and Herbal Notes',
        'Amber, Sandalwood and Vanilla',
        'citrus,woody,warm spicy,green,powdery',
        'MarahbyAjmalis a Aromatic Spicy fragrance for women. Top notes are Bergamot, Ginger and Woody Notes; middle notes are Rose, Citruses and Herbal Notes; base notes are Amber, Sandalwood and Vanilla.',
        5,
        1,
        NULL
      ),
(
        'Mawsouf-7036',
        'Mawsouf Ajmal',
        'Mawsouf',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,oud,rose,vanilla,powdery',
        'MawsoufbyAjmalis a Amber fragrance for women and men.',
        4.33,
        18,
        NULL
      ),
(
        'Misk-Al-Oudh-14038',
        'Misk Al Oudh Ajmal',
        'Misk',
        'for women and men',
        NULL,
        'Nazir Ajmal',
        NULL,
        NULL,
        NULL,
        'musky,oud,powdery',
        'Misk Al OudhbyAjmalis a Amber fragrance for women and men.Misk Al Oudhwas launched in 2011. The nose behind this fragrance is Nazir Ajmal.',
        3.44,
        18,
        NULL
      ),
(
        'Mizyaan-15083',
        'Mizyaan Ajmal',
        'Mizyaan',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,woody,amber,floral,warm spicy',
        'MizyaanbyAjmalis a Amber Floral fragrance for women and men.Mizyaanwas launched in 2009.',
        3.84,
        80,
        NULL
      ),
(
        'Muhja-15086',
        'Muhja Ajmal',
        'Muhja',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,musky,white floral,woody,powdery',
        'MuhjabyAjmalis a Amber Woody fragrance for women.',
        4.1,
        30,
        NULL
      ),
(
        'Mukhallat-Shams-15084',
        'Mukhallat Shams Ajmal',
        'Mukhallat',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,woody,musky,amber,floral',
        'Mukhallat ShamsbyAjmalis a Amber fragrance for women and men.',
        4.16,
        240,
        NULL
      ),
(
        'Mukhallat-Tharwaan-15085',
        'Mukhallat Tharwaan Ajmal',
        'Mukhallat',
        'for women and men',
        NULL,
        NULL,
        'Rose',
        'Ambergris and Sandalwood',
        'Agarwood (Oud), Saffron, Spices and Musk',
        'warm spicy,oud,amber,rose,woody',
        'Mukhallat TharwaanbyAjmalis a Amber fragrance for women and men. Top note is Rose; middle notes are Ambergris and Sandalwood; base notes are Agarwood (Oud), Saffron, Spices and Musk.',
        4.27,
        49,
        NULL
      ),
(
        'Ostoorah-25952',
        'Ostoorah Ajmal',
        'Ostoorah',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes',
        'Rose, Musk and Floral Notes',
        'Agarwood (Oud), Woody Notes and Amber',
        'floral,rose,oud,woody,musky',
        'OstoorahbyAjmalis a Amber Floral fragrance for women and men. Top note is Floral Notes; middle notes are Rose, Musk and Floral Notes; base notes are Agarwood (Oud), Woody Notes and Amber.',
        4.05,
        101,
        NULL
      ),
(
        'Ragheeb-15089',
        'Ragheeb Ajmal',
        'Ragheeb',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,warm spicy,rose,citrus,aromatic',
        'RagheebbyAjmalis a Amber Floral fragrance for women.Ragheebwas launched in 2008.',
        4.03,
        40,
        NULL
      ),
(
        'Rannan-15091',
        'Rannan Ajmal',
        'Rannan',
        'for women and men',
        NULL,
        NULL,
        'Black Currant, Tropical Fruits and Bergamot',
        'Saffron and Rose',
        'Patchouli, Agarwood (Oud), Ambergris and Vanilla',
        'fruity,patchouli,woody,tropical,oud',
        'RannanbyAjmalis a Amber fragrance for women and men. Top notes are Black Currant, Tropical Fruits and Bergamot; middle notes are Saffron and Rose; base notes are Patchouli, Agarwood (Oud), Ambergris and Vanilla.',
        3,
        2,
        NULL
      ),
(
        'Rouh-Al-Khaleej-15095',
        'Rouh Al Khaleej Ajmal',
        'Rouh',
        'for women and men',
        NULL,
        NULL,
        'Sea water and Spices',
        'Floral Notes and Ambergris',
        'Fruity Notes and Woodsy Notes',
        'floral,marine,fruity,aromatic,amber',
        'Rouh Al KhaleejbyAjmalis a Amber Fougere fragrance for women and men. Top notes are Sea water and Spices; middle notes are Floral Notes and Ambergris; base notes are Fruity Notes and Woodsy Notes.',
        3.98,
        51,
        NULL
      ),
(
        'Sajwaa-15100',
        'Sajwaa Ajmal',
        'Sajwaa',
        'for women',
        NULL,
        NULL,
        'Floral Notes, Bergamot, Mandarin Orange and Green Notes',
        'Geranium, Vanilla, Spices, Sandalwood and Cardamom',
        'Labdanum, Agarwood (Oud), Ambergris, Incense and Rose',
        'amber,fresh spicy,warm spicy,aromatic,rose',
        'SajwaabyAjmalis a Floral Woody Musk fragrance for women. Top notes are Floral Notes, Bergamot, Mandarin Orange and Green Notes; middle notes are Geranium, Vanilla, Spices, Sandalwood and Cardamom; base notes are Labdanum, Agarwood (Oud), Ambergris, Incense and Rose.',
        3.67,
        12,
        NULL
      ),
(
        'Shaghaf-35224',
        'Shaghaf Ajmal',
        'Shaghaf',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes',
        'Spices and Flowers',
        'Agarwood (Oud), Amber and Musk',
        'oud,floral,fruity,amber,musky',
        'ShaghafbyAjmalis a Woody Floral Musk fragrance for women and men.Shaghafwas launched in 2015. Top note is Fruity Notes; middle notes are Spices and Flowers; base notes are Agarwood (Oud), Amber and Musk.',
        3.79,
        76,
        NULL
      ),
(
        'Tanaaghom-18139',
        'Tanaaghom Ajmal',
        'Tanaaghom',
        'for women',
        NULL,
        NULL,
        'Carnation',
        'Rose and Pepper',
        'Sandalwood and Amber',
        'warm spicy,rose,floral,fresh spicy,woody',
        'TanaaghombyAjmalis a Amber Floral fragrance for women.Tanaaghomwas launched in 2012. Top note is Carnation; middle notes are Rose and Pepper; base notes are Sandalwood and Amber.',
        3.8,
        10,
        NULL
      ),
(
        'Teyf-19428',
        'Teyf Ajmal',
        'Teyf',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Plum',
        'Rose and Leather',
        'Sandalwood, Tonka Bean and Musk',
        'warm spicy,rose,leather,woody,powdery',
        'TeyfbyAjmalis a Floral Woody Musk fragrance for women and men. Top notes are Saffron and Plum; middle notes are Rose and Leather; base notes are Sandalwood, Tonka Bean and Musk.',
        3.92,
        12,
        NULL
      ),
(
        'Wisal-15109',
        'Wisal Ajmal',
        'Wisal',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral,warm spicy,musky,powdery',
        'WisalbyAjmalis a Floral fragrance for women.Wisalwas launched in 2010.',
        4.09,
        418,
        NULL
      ),
(
        'Wisal-Dhahab-35888',
        'Wisal Dhahab Ajmal',
        'Wisal',
        'for women and men',
        NULL,
        NULL,
        'Pear, Peach, Apple, Grapefruit and Mandarin Orange',
        'Rose, Orchid, Jasmine and Geranium',
        'Sandalwood, Musk, Patchouli and Cedar',
        'woody,rose,fruity,powdery,floral',
        'Wisal DhahabbyAjmalis a Floral Woody Musk fragrance for women and men.Wisal Dhahabwas launched in 2015. Top notes are Pear, Peach, Apple, Grapefruit and Mandarin Orange; middle notes are Rose, Orchid, Jasmine and Geranium; base notes are Sandalwood, Musk, Patchouli and Cedar.',
        4.14,
        257,
        NULL
      ),
(
        'Zahee-19426',
        'Zahee Ajmal',
        'Zahee',
        'for women and men',
        NULL,
        NULL,
        'Galbanum and Bergamot',
        'Patchouli, Rose and Jasmine',
        'Sandalwood, Vetiver and Musk',
        'woody,aromatic,green,earthy,patchouli',
        'ZaheebyAjmalis a Floral Woody Musk fragrance for women and men. Top notes are Galbanum and Bergamot; middle notes are Patchouli, Rose and Jasmine; base notes are Sandalwood, Vetiver and Musk.',
        3.77,
        82,
        NULL
      ),
(
        'Amber-Musc-30750',
        'Amber Musc Ajmal',
        'Amber',
        'for women and men',
        NULL,
        'Abdulla Ajmal',
        NULL,
        NULL,
        NULL,
        'musky,powdery,rose,woody,amber',
        'Amber MuscbyAjmalis a Amber Floral fragrance for women and men.Amber Muscwas launched in 2015. The nose behind this fragrance is Abdulla Ajmal.',
        3.89,
        164,
        NULL
      ),
(
        'Cashmere-Musk-55882',
        'Cashmere Musk Ajmal',
        'Cashmere',
        'for women and men',
        NULL,
        NULL,
        'Musk and Saffron',
        'Musk, Ylang-Ylang, Jasmine and Lily-of-the-Valley',
        'Musk, Cashmeran, Cedar and Patchouli',
        'woody,musky,powdery,warm spicy,yellow floral',
        'Cashmere MuskbyAjmalis a Woody Floral Musk fragrance for women and men.Cashmere Muskwas launched in 2019. Top notes are Musk and Saffron; middle notes are Musk, Ylang-Ylang, Jasmine and Lily-of-the-Valley; base notes are Musk, Cashmeran, Cedar and Patchouli.',
        4.09,
        67,
        NULL
      ),
(
        'Cuir-Musc-30752',
        'Cuir Musc Ajmal',
        'Cuir',
        'for women and men',
        NULL,
        'Abdulla Ajmal',
        NULL,
        NULL,
        NULL,
        'musky,fruity,sweet,leather,ozonic',
        'Cuir MuscbyAjmalis a Leather fragrance for women and men.Cuir Muscwas launched in 2015. The nose behind this fragrance is Abdulla Ajmal.',
        3.33,
        101,
        NULL
      ),
(
        'Violet-Musc-30751',
        'Violet Musc Ajmal',
        'Violet',
        'for women and men',
        NULL,
        'Abdulla Ajmal',
        NULL,
        NULL,
        NULL,
        'powdery,musky,violet,rose,floral',
        'Violet MuscbyAjmalis a Amber Floral fragrance for women and men.Violet Muscwas launched in 2015. The nose behind this fragrance is Abdulla Ajmal.',
        3.89,
        205,
        NULL
      ),
(
        'Amber-56388',
        'Amber Ajmal',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Pepper',
        'Rose, Palisander Rosewood and Jasmine',
        'Amber, Musk, Agarwood (Oud) and Sandalwood',
        'amber,woody,powdery,rose,musky',
        'AmberbyAjmalis a Amber Woody fragrance for women and men.Amberwas launched in 2019. Top notes are Bergamot and Pepper; middle notes are Rose, Palisander Rosewood and Jasmine; base notes are Amber, Musk, Agarwood (Oud) and Sandalwood.',
        4.37,
        43,
        NULL
      ),
(
        'Cashmere-Wood-56389',
        'Cashmere Wood Ajmal',
        'Cashmere',
        'for women and men',
        NULL,
        NULL,
        'Lavender and Mandarin Orange',
        'Orris, Cacao and Tonka Bean',
        'Cashmeran, Agarwood (Oud), Cedar, Patchouli and Amber',
        'woody,powdery,amber,oud,musky',
        'Cashmere WoodbyAjmalis a Floral Woody Musk fragrance for women and men.Cashmere Woodwas launched in 2019. Top notes are Lavender and Mandarin Orange; middle notes are Orris, Cacao and Tonka Bean; base notes are Cashmeran, Agarwood (Oud), Cedar, Patchouli and Amber.',
        4.58,
        52,
        NULL
      ),
(
        'Cuir-56390',
        'Cuir Ajmal',
        'Cuir',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Honeysuckle and Tiare Flower',
        'Agarwood (Oud) and Leather',
        'Agarwood (Oud) and Musk',
        'white floral,oud,leather,animalic,musky',
        'CuirbyAjmalis a Floral Woody Musk fragrance for women and men.Cuirwas launched in 2019. Top notes are Orange Blossom, Honeysuckle and Tiare Flower; middle notes are Agarwood (Oud) and Leather; base notes are Agarwood (Oud) and Musk.',
        4.78,
        9,
        NULL
      ),
(
        'Incense-56391',
        'Incense Ajmal',
        'Incense',
        'for women and men',
        NULL,
        NULL,
        'Frankincense and Bitter Orange',
        'Violet, Cypriol Oil or Nagarmotha, Rose and Guaiac Wood',
        'Oud, Leather, Moss and Amber',
        'amber,woody,earthy,oud,leather',
        'IncensebyAjmalis a Woody Spicy fragrance for women and men.Incensewas launched in 2019. Top notes are Frankincense and Bitter Orange; middle notes are Violet, Cypriol Oil or Nagarmotha, Rose and Guaiac Wood; base notes are Oud, Leather, Moss and Amber.',
        3.92,
        51,
        NULL
      ),
(
        'Musc-56392',
        'Musc Ajmal',
        'Musc',
        'for women and men',
        NULL,
        NULL,
        'Passionfruit, Apple and Bergamot',
        'Plum, Strawberry and Ginger',
        'Musk, Agarwood (Oud), Cedar and Vanilla',
        'fruity,musky,sweet,powdery,oud',
        'MuscbyAjmalis a Amber Woody fragrance for women and men.Muscwas launched in 2019. Top notes are Passionfruit, Apple and Bergamot; middle notes are Plum, Strawberry and Ginger; base notes are Musk, Agarwood (Oud), Cedar and Vanilla.',
        4.32,
        44,
        NULL
      ),
(
        'Patchouli-56393',
        'Patchouli Ajmal',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Palisander Rosewood, Cardamom, Nutmeg and Bergamot',
        'Patchouli, Cedar, Rose, Tonka Bean and Basil',
        'Agarwood (Oud), Sandalwood, Vanilla, Cedar, Musk and Vetiver',
        'woody,warm spicy,patchouli,aromatic,fresh spicy',
        'PatchoulibyAjmalis a Chypre fragrance for women and men.Patchouliwas launched in 2019. Top notes are Palisander Rosewood, Cardamom, Nutmeg and Bergamot; middle notes are Patchouli, Cedar, Rose, Tonka Bean and Basil; base notes are Agarwood (Oud), Sandalwood, Vanilla, Cedar, Musk and Vetiver.',
        4.22,
        51,
        NULL
      ),
(
        'Saffron-56394',
        'Saffron Ajmal',
        'Saffron',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Raspberry and Pineapple',
        'Rose and Davana',
        'Agarwood (Oud), Woody Notes, Amber, Cashmere Wood and Cypriol Oil or Nagarmotha',
        'rose,oud,woody,fruity,sweet',
        'SaffronbyAjmalis a Woody Spicy fragrance for women and men.Saffronwas launched in 2019. Top notes are Saffron, Raspberry and Pineapple; middle notes are Rose and Davana; base notes are Agarwood (Oud), Woody Notes, Amber, Cashmere Wood and Cypriol Oil or Nagarmotha.',
        4.36,
        45,
        NULL
      ),
(
        'Santal-56395',
        'Santal Ajmal',
        'Santal',
        'for women and men',
        NULL,
        NULL,
        'Nutmeg, Saffron and Ginger',
        'Gurjan balsam, Sandalwood and Cedar',
        'Agarwood (Oud), White Amber and Musk',
        'woody,oud,fresh spicy,powdery,warm spicy',
        'SantalbyAjmalis a Woody fragrance for women and men.Santalwas launched in 2019. Top notes are Nutmeg, Saffron and Ginger; middle notes are Gurjan balsam, Sandalwood and Cedar; base notes are Agarwood (Oud), White Amber and Musk.',
        4.34,
        50,
        NULL
      ),
(
        'Tonka-56396',
        'Tonka Ajmal',
        'Tonka',
        'for women and men',
        NULL,
        NULL,
        'Nutmeg, Cinnamon and Clary Sage',
        'White Amber and Cedar',
        'Tonka Bean, Agarwood (Oud), Tobacco and Cashmeran',
        'amber,woody,oud,vanilla,sweet',
        'TonkabyAjmalis a Amber fragrance for women and men.Tonkawas launched in 2019. Top notes are Nutmeg, Cinnamon and Clary Sage; middle notes are White Amber and Cedar; base notes are Tonka Bean, Agarwood (Oud), Tobacco and Cashmeran.',
        4.31,
        54,
        NULL
      ),
(
        'Vetiver-56397',
        'Vetiver Ajmal',
        'Vetiver',
        'for women and men',
        NULL,
        NULL,
        'Vetiver and Bergamot',
        'Cypress and Patchouli',
        'Agarwood (Oud), Sandalwood, Saffron and Musk',
        'woody,aromatic,earthy,warm spicy,oud',
        'VetiverbyAjmalis a Woody fragrance for women and men.Vetiverwas launched in 2019. Top notes are Vetiver and Bergamot; middle notes are Cypress and Patchouli; base notes are Agarwood (Oud), Sandalwood, Saffron and Musk.',
        4.14,
        28,
        NULL
      ),
(
        'Qafiya-1-41193',
        'Qafiya 1 Ajmal',
        'Qafiya',
        'for women and men',
        NULL,
        NULL,
        'Rose, Orange Blossom and Saffron',
        'Woody Notes and Amber',
        'Woody Notes, Musk and Patchouli',
        'woody,musky,rose,warm spicy,patchouli',
        'Qafiya 1byAjmalis a Amber Woody fragrance for women and men.Qafiya 1was launched in 2016. Top notes are Rose, Orange Blossom and Saffron; middle notes are Woody Notes and Amber; base notes are Woody Notes, Musk and Patchouli.',
        4.04,
        71,
        NULL
      ),
(
        'Qafiya-2-41194',
        'Qafiya 2 Ajmal',
        'Qafiya',
        'for women and men',
        NULL,
        NULL,
        'Coffee and Bergamot',
        'Spices and Orange Blossom',
        'Sandalwood and Moss',
        'warm spicy,woody,coffee,citrus,mossy',
        'Qafiya 2byAjmalis a Amber Floral fragrance for women and men.Qafiya 2was launched in 2016. Top notes are Coffee and Bergamot; middle notes are Spices and Orange Blossom; base notes are Sandalwood and Moss.',
        4.19,
        177,
        NULL
      ),
(
        'Qafiya-3-49546',
        'Qafiya 3 Ajmal',
        'Qafiya',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,woody,leather,violet,animalic',
        'Qafiya 3byAjmalis a Woody Spicy fragrance for women and men.Qafiya 3was launched in 2018.',
        4.15,
        20,
        NULL
      ),
(
        'Qafiya-4-49545',
        'Qafiya 4 Ajmal',
        'Qafiya',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,fruity,leather,musky',
        'Qafiya 4byAjmalis a Woody Spicy fragrance for women and men.Qafiya 4was launched in 2018.',
        3.8,
        20,
        NULL
      ),
(
        'Qafiya-Sport-51254',
        'Qafiya Sport Ajmal',
        'Qafiya',
        'for men',
        NULL,
        NULL,
        'Bergamot, Nutmeg and Violet',
        'Birch Tar, Cedar, Coffee and Damask Rose',
        'Sandalwood, Leather and Amber',
        'leather,woody,animalic,smoky,warm spicy',
        'Qafiya SportbyAjmalis a Woody Floral Musk fragrance for men.Qafiya Sportwas launched in 2018. Top notes are Bergamot, Nutmeg and Violet; middle notes are Birch Tar, Cedar, Coffee and Damask Rose; base notes are Sandalwood, Leather and Amber.',
        3.94,
        16,
        NULL
      ),
(
        'Qafiya-Year-Of-Zayed-64078',
        'Qafiya Year Of Zayed Ajmal',
        'Qafiya',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes and Spicy Notes',
        'Floral Notes',
        'Musk, Amber and Agarwood (Oud)',
        'floral,musky,amber,powdery,warm spicy',
        'Qafiya Year Of ZayedbyAjmalis a Floral fragrance for women and men.Qafiya Year Of Zayedwas launched in 2018. Top notes are Floral Notes and Spicy Notes; middle note is Floral Notes; base notes are Musk, Amber and Agarwood (Oud).',
        4.75,
        4,
        NULL
      ),
(
        'Primitive-Forests-77324',
        'Primitive Forests Ajmal',
        'Primitive',
        'for women and men',
        NULL,
        'Maxime Exler',
        'Orange, Sicilian Lemon and Green Notes',
        'Geranium, Ginger, Cardamom and Sea Notes',
        'Amber and Musk',
        'aromatic,citrus,warm spicy,fresh spicy,marine',
        'Primitive ForestsbyAjmalis a Aromatic Spicy fragrance for women and men.Primitive Forestswas launched in 2020. The nose behind this fragrance is Maxime Exler. Top notes are Orange, Sicilian Lemon and Green Notes; middle notes are Geranium, Ginger, Cardamom and Sea Notes; base notes are Amber and Musk.',
        4,
        1,
        NULL
      ),
(
        'Accord-Boise-14040',
        'Accord Boise Ajmal',
        'Accord',
        'for men',
        NULL,
        'Nazir Ajmal',
        'Coffee and Pepper',
        'Incense and Sage',
        'Patchouli and Ginger',
        'warm spicy,patchouli,coffee,amber,fresh spicy',
        'Accord BoisebyAjmalis a Amber Woody fragrance for men.Accord Boisewas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal. Top notes are Coffee and Pepper; middle notes are Incense and Sage; base notes are Patchouli and Ginger.',
        3.95,
        93,
        NULL
      ),
(
        'Accord-Violet-14041',
        'Accord Violet Ajmal',
        'Accord',
        'for women',
        NULL,
        'Nazir Ajmal',
        'Black Currant and Peach',
        'Violet, Clove and Jasmine',
        'Patchouli, Tuberose and Musk',
        'warm spicy,fruity,powdery,violet,white floral',
        'Accord VioletbyAjmalis a Floral Woody Musk fragrance for women.Accord Violetwas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal. Top notes are Black Currant and Peach; middle notes are Violet, Clove and Jasmine; base notes are Patchouli, Tuberose and Musk.',
        3.74,
        114,
        NULL
      ),
(
        'Ambre-Fruite-18134',
        'Ambre Fruite Ajmal',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit',
        'Black Pepper, Tonka Bean, Patchouli and Cinnamon',
        'Amber and Leather',
        'amber,fresh spicy,warm spicy,leather,citrus',
        'Ambre FruitebyAjmalis a Leather fragrance for women and men.Ambre Fruitewas launched in 2012. Top note is Grapefruit; middle notes are Black Pepper, Tonka Bean, Patchouli and Cinnamon; base notes are Amber and Leather.',
        3.9,
        60,
        NULL
      ),
(
        'Ambre-Pimente-18136',
        'Ambre Pimente Ajmal',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,warm spicy,powdery,musky',
        'Ambre PimentebyAjmalis a Amber Woody fragrance for women and men.Ambre Pimentewas launched in 2012.',
        3.95,
        456,
        NULL
      ),
(
        'Taaj-Al-Raas-19424',
        'Taaj Al Raas Ajmal',
        'Taaj',
        'for men',
        NULL,
        NULL,
        'Cumin, Olibanum and Saffron',
        'Patchouli, Guaiac Wood and Cedar',
        'Amber and Musk',
        'amber,woody,fresh spicy,warm spicy,musky',
        'Taaj Al RaasbyAjmalis a Amber Woody fragrance for men. Top notes are Cumin, Olibanum and Saffron; middle notes are Patchouli, Guaiac Wood and Cedar; base notes are Amber and Musk.',
        4.25,
        8,
        NULL
      ),
(
        'Zeyna-14042',
        'Zeyna Ajmal',
        'Zeyna',
        'for women',
        NULL,
        'Nazir Ajmal',
        'Floral Notes',
        'Spices and Rose',
        'Woodsy Notes and Musk',
        'floral,woody,warm spicy',
        'ZeynabyAjmalis a Floral Woody Musk fragrance for women.Zeynawas launched during the 2000''s. The nose behind this fragrance is Nazir Ajmal. Top note is Floral Notes; middle notes are Spices and Rose; base notes are Woodsy Notes and Musk.',
        4,
        2,
        NULL
      ),
(
        'Amber-Wood-26016',
        'Amber Wood Ajmal',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Apple, Lavender and White Pepper',
        'Cedar and Orris',
        'Amber, Woody Notes and Patchouli',
        'woody,warm spicy,amber,fresh spicy,aromatic',
        'Amber WoodbyAjmalis a Amber Woody fragrance for women and men.Amber Woodwas launched in 2014. Top notes are Cardamom, Apple, Lavender and White Pepper; middle notes are Cedar and Orris; base notes are Amber, Woody Notes and Patchouli.',
        4.19,
        837,
        NULL
      ),
(
        'Amber-Wood-Noir-61756',
        'Amber Wood Noir Ajmal',
        'Amber',
        'for women and men',
        NULL,
        NULL,
        'Aromatic Spices and Citruses',
        'Woodsy Notes and Floral Notes',
        'Woodsy Notes, Amber and Musk',
        'woody,amber,musky,citrus,powdery',
        'Amber Wood NoirbyAjmalis a Woody Floral Musk fragrance for women and men.Amber Wood Noirwas launched in 2020. Top notes are Aromatic Spices and Citruses; middle notes are Woodsy Notes and Floral Notes; base notes are Woodsy Notes, Amber and Musk.',
        4.21,
        76,
        NULL
      ),
(
        'Hatkora-Wood-26017',
        'Hatkora Wood Ajmal',
        'Hatkora',
        'for women and men',
        NULL,
        NULL,
        'Hatkora lemon, Lemon and Peach',
        'Saffron, Ginger, Lavender and Rose',
        'Agarwood (Oud), Sandalwood, Ambergris, Amber and Musk',
        'citrus,amber,warm spicy,oud,woody',
        'Hatkora WoodbyAjmalis a Amber Spicy fragrance for women and men.Hatkora Woodwas launched in 2014. Top notes are Hatkora lemon, Lemon and Peach; middle notes are Saffron, Ginger, Lavender and Rose; base notes are Agarwood (Oud), Sandalwood, Ambergris, Amber and Musk.',
        4.21,
        304,
        NULL
      ),
(
        'Incense-Wood-55883',
        'Incense Wood Ajmal',
        'Incense',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper, Saffron and Bergamot',
        'Cashmere Wood, Incense and Olibanum',
        'Vanilla, Patchouli and Musk',
        'amber,woody,musky,warm spicy,balsamic',
        'Incense WoodbyAjmalis a Amber Woody fragrance for women and men.Incense Woodwas launched in 2019. Top notes are Pink Pepper, Saffron and Bergamot; middle notes are Cashmere Wood, Incense and Olibanum; base notes are Vanilla, Patchouli and Musk.',
        4.21,
        90,
        NULL
      ),
(
        'Patchouli-Wood-42194',
        'Patchouli Wood Ajmal',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Woodsy Notes and Spices',
        'Floral Notes',
        'Agarwood (Oud), Patchouli and Woody Notes',
        'woody,oud,patchouli,warm spicy,floral',
        'Patchouli WoodbyAjmalis a Woody Spicy fragrance for women and men.Patchouli Woodwas launched in 2016. Top notes are Woodsy Notes and Spices; middle note is Floral Notes; base notes are Agarwood (Oud), Patchouli and Woody Notes.',
        3.69,
        86,
        NULL
      ),
(
        'Rose-Wood-35894',
        'Rose Wood Ajmal',
        'Rose',
        'for women and men',
        NULL,
        NULL,
        'Spicy Notes and Floral Notes',
        'Rose and Musk',
        'Agarwood (Oud), Woody Notes and Powdery Notes',
        'oud,powdery,woody,rose,floral',
        'Rose WoodbyAjmalis a Amber fragrance for women and men.Rose Woodwas launched in 2015. Top notes are Spicy Notes and Floral Notes; middle notes are Rose and Musk; base notes are Agarwood (Oud), Woody Notes and Powdery Notes.',
        4.16,
        203,
        NULL
      ),
(
        'Santal-Wood-26018',
        'Santal Wood Ajmal',
        'Santal',
        'for women and men',
        NULL,
        NULL,
        'Cumin, Cardamom and Marigold',
        'Rose, Cedar, Ginger and Jasmine',
        'Sandalwood, Agarwood (Oud) and Patchouli',
        'woody,warm spicy,fresh spicy,oud,aromatic',
        'Santal WoodbyAjmalis a Amber Woody fragrance for women and men.Santal Woodwas launched in 2014. Top notes are Cumin, Cardamom and Marigold; middle notes are Rose, Cedar, Ginger and Jasmine; base notes are Sandalwood, Agarwood (Oud) and Patchouli.',
        4.08,
        172,
        NULL
      ),
(
        'Watani-34301',
        'Watani Ajmal',
        'Watani',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,oud,amber,floral,woody',
        'WatanibyAjmalis a Amber Spicy fragrance for women and men.Wataniwas launched in 2014.',
        3.83,
        6,
        NULL
      ),
(
        'Watani-Abyad-34299',
        'Watani Abyad Ajmal',
        'Watani',
        'for women and men',
        NULL,
        'Abdulla Ajmal',
        NULL,
        NULL,
        NULL,
        'powdery,iris,musky,vanilla,violet',
        'Watani AbyadbyAjmalis a Amber Floral fragrance for women and men.Watani Abyadwas launched in 2014. The nose behind this fragrance is Abdulla Ajmal.',
        3.81,
        102,
        NULL
      ),
(
        'Watani-Ahmar-34298',
        'Watani Ahmar Ajmal',
        'Watani',
        'for women and men',
        NULL,
        'Abdulla Ajmal',
        NULL,
        NULL,
        NULL,
        'warm spicy,fruity,oud,citrus,sweet',
        'Watani AhmarbyAjmalis a Amber Spicy fragrance for women and men.Watani Ahmarwas launched during the 2014''s. The nose behind this fragrance is Abdulla Ajmal.',
        3.74,
        61,
        NULL
      ),
(
        'Watani-Akhdar-34300',
        'Watani Akhdar Ajmal',
        'Watani',
        'for women and men',
        NULL,
        'Abdulla Ajmal',
        NULL,
        NULL,
        NULL,
        'aromatic,woody,fresh spicy,oud,leather',
        'Watani AkhdarbyAjmalis a Aromatic Fougere fragrance for women and men.Watani Akhdarwas launched in 2014. The nose behind this fragrance is Abdulla Ajmal.',
        3.83,
        42,
        NULL
      ),
(
        '001-Royal-Velvet-26867',
        '001 Royal Velvet Ajmal',
        '001',
        'for women and men',
        NULL,
        NULL,
        'Citruses, Woody Notes and Bergamot',
        'Patchouli and Spicy Notes',
        'Musk and Vanilla',
        'musky,woody,citrus,patchouli,powdery',
        '001 Royal VelvetbyAjmalis a Woody Spicy fragrance for women and men.001 Royal Velvetwas launched in 2014. Top notes are Citruses, Woody Notes and Bergamot; middle notes are Patchouli and Spicy Notes; base notes are Musk and Vanilla.',
        4.67,
        3,
        NULL
      ),
(
        '002-Essential-Wood-26868',
        '002 Essential Wood Ajmal',
        '002',
        'for women and men',
        NULL,
        NULL,
        'Rose, Jasmine, Iris and Pink Pepper',
        'Agarwood (Oud)',
        'Woody Notes and Amber',
        'rose,oud,woody,white floral,amber',
        '002 Essential WoodbyAjmalis a Floral Woody Musk fragrance for women and men.002 Essential Woodwas launched in 2014. Top notes are Rose, Jasmine, Iris and Pink Pepper; middle note is Agarwood (Oud); base notes are Woody Notes and Amber.',
        4.88,
        8,
        NULL
      ),
(
        '003-Private-Collection-26869',
        '003 Private Collection Ajmal',
        '003',
        'for women and men',
        NULL,
        NULL,
        'elemi, Apple and Cardamom',
        'Rose',
        'Cedar, Musk, Vanilla and Amber',
        'aromatic,woody,balsamic,fruity,musky',
        '003 Private CollectionbyAjmalis a Floral Woody Musk fragrance for women and men.003 Private Collectionwas launched in 2014. Top notes are elemi, Apple and Cardamom; middle note is Rose; base notes are Cedar, Musk, Vanilla and Amber.',
        4.2,
        10,
        NULL
      ),
(
        '004-Sublime-Love-26870',
        '004 Sublime Love Ajmal',
        '004',
        'for women',
        NULL,
        NULL,
        'Black Currant',
        'Violet and Rose',
        'Musk, Cedar and Patchouli',
        'powdery,violet,woody,rose,fruity',
        '004 Sublime LovebyAjmalis a Floral Woody Musk fragrance for women.004 Sublime Lovewas launched in 2014. Top note is Black Currant; middle notes are Violet and Rose; base notes are Musk, Cedar and Patchouli.',
        4.06,
        18,
        NULL
      ),
(
        '005-Royal-Blue-26871',
        '005 Royal Blue Ajmal',
        '005',
        'for women and men',
        NULL,
        NULL,
        'Patchouli and Cedar',
        'Fruity Notes and Nutmeg',
        'Amber and Vanilla',
        'amber,vanilla,woody,fruity,powdery',
        '005 Royal BluebyAjmalis a Amber Woody fragrance for women and men.005 Royal Bluewas launched in 2014. Top notes are Patchouli and Cedar; middle notes are Fruity Notes and Nutmeg; base notes are Amber and Vanilla.',
        5,
        3,
        NULL
      ),
(
        '006-Just-Noir-26872',
        '006 Just Noir Ajmal',
        '006',
        'for women and men',
        NULL,
        NULL,
        'Cardamom and Rose',
        'Vetiver, Sandalwood and Cedar',
        'Amber and Cypriol Oil or Nagarmotha',
        'woody,amber,aromatic,warm spicy,earthy',
        '006 Just NoirbyAjmalis a Amber Woody fragrance for women and men.006 Just Noirwas launched in 2014. Top notes are Cardamom and Rose; middle notes are Vetiver, Sandalwood and Cedar; base notes are Amber and Cypriol Oil or Nagarmotha.',
        3,
        4,
        NULL
      ),
(
        '007-Royal-Patchouli-26873',
        '007 Royal Patchouli Ajmal',
        '007',
        'for women and men',
        NULL,
        NULL,
        'Ylang-Ylang, Jasmine, Neroli and Rose',
        'Patchouli',
        'Vanilla, Amber and Musk',
        'patchouli,woody,vanilla,amber,powdery',
        '007 Royal PatchoulibyAjmalis a Floral Woody Musk fragrance for women and men.007 Royal Patchouliwas launched in 2014. Top notes are Ylang-Ylang, Jasmine, Neroli and Rose; middle note is Patchouli; base notes are Vanilla, Amber and Musk.',
        4.42,
        59,
        NULL
      );
