
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Shiny-Creation-679',
        'Shiny Creation La Perla',
        'Shiny',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,rose,woody,vanilla,white floral',
        'Shiny CreationbyLa Perlais a Floral Fruity fragrance for women.',
        4.08,
        76,
        NULL
      ),
(
        'Charme-681',
        'Charme La Perla',
        'Charme',
        'for women',
        NULL,
        NULL,
        'Lotus and Bergamot',
        'Rose, Cedar and Jasmine',
        'Vanilla, Amber and Musk',
        'vanilla,powdery,amber,musky,floral',
        'CharmebyLa Perlais a Floral Woody Musk fragrance for women.Charmewas launched in 2006. Top notes are Lotus and Bergamot; middle notes are Rose, Cedar and Jasmine; base notes are Vanilla, Amber and Musk.',
        3.94,
        307,
        NULL
      ),
(
        'Charme-Lace-Collection-5984',
        'Charme Lace Collection La Perla',
        'Charme',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Apple Blossom, Bergamot and Melon',
        'Rose, Jasmine, Cyclamen and Lily',
        'Tonka Bean, Vanilla, Amber, Patchouli, Musk and Vetiver',
        'vanilla,amber,floral,citrus,white floral',
        'Charme Lace CollectionbyLa Perlais a Amber Floral fragrance for women.Charme Lace Collectionwas launched in 2009. Top notes are Mandarin Orange, Apple Blossom, Bergamot and Melon; middle notes are Rose, Jasmine, Cyclamen and Lily; base notes are Tonka Bean, Vanilla, Amber, Patchouli, Musk and Vetiver.',
        3.7,
        107,
        NULL
      ),
(
        'Divina-11778',
        'Divina La Perla',
        'Divina',
        'for women',
        NULL,
        NULL,
        'Big Strawberry, Champagne, Calabrian Mandarin and Pear',
        'Rose, Jasmine and African Orange Flower',
        'Vanille, Musk, Woodsy Notes and Amber',
        'fruity,sweet,citrus,white floral,Champagne',
        'DivinabyLa Perlais a Floral Fruity fragrance for women.Divinawas launched in 2011. Top notes are Big Strawberry, Champagne, Calabrian Mandarin and Pear; middle notes are Rose, Jasmine and African Orange Flower; base notes are Vanille, Musk, Woodsy Notes and Amber.',
        3.71,
        581,
        NULL
      ),
(
        'Divina-Eau-de-Parfum-17799',
        'Divina Eau de Parfum La Perla',
        'Divina',
        'for women',
        NULL,
        NULL,
        'Kir Royal',
        'Heliotrope and Orange Blossom',
        'Vanila and Sandalwood',
        'vanilla,powdery,fruity,aromatic,white floral',
        'Divina Eau de ParfumbyLa Perlais a Amber Floral fragrance for women.Divina Eau de Parfumwas launched in 2013. Top note is Kir Royal; middle notes are Heliotrope and Orange Blossom; base notes are Vanila and Sandalwood.',
        3.91,
        223,
        NULL
      ),
(
        'Divina-Gold-Edition-16727',
        'Divina Gold Edition La Perla',
        'Divina',
        'for women',
        NULL,
        NULL,
        'Champagne and Orange Blossom',
        'Caramel, Wild Strawberry and Exotic floral notes',
        'Amber',
        'sweet,caramel,fruity,white floral,amber',
        'Divina Gold EditionbyLa Perlais a Amber Floral fragrance for women.Divina Gold Editionwas launched in 2012. Top notes are Champagne and Orange Blossom; middle notes are Caramel, Wild Strawberry and Exotic floral notes; base note is Amber.',
        4.08,
        62,
        NULL
      ),
(
        'Divina-Silver-Edition-16869',
        'Divina Silver Edition La Perla',
        'Divina',
        'for women',
        NULL,
        NULL,
        'Wild Strawberry and Mandarin Orange',
        'Jasmine, Orange Blossom and Rose',
        'Musk, Vanilla and Amber',
        'white floral,citrus,sweet,fruity,musky',
        'Divina Silver EditionbyLa Perlais a Floral Fruity fragrance for women.Divina Silver Editionwas launched in 2012. Top notes are Wild Strawberry and Mandarin Orange; middle notes are Jasmine, Orange Blossom and Rose; base notes are Musk, Vanilla and Amber.',
        3.67,
        18,
        NULL
      ),
(
        'Grigioperla-2961',
        'Grigioperla La Perla',
        'Grigioperla',
        'for men',
        NULL,
        NULL,
        'Rosemary, Lavender, Basil, Coriander, Anise and Bergamot',
        'Clary Sage, Geranium and Carnation',
        'Oakmoss, Sandalwood, Leather, Amber, Cedar, Tonka Bean and Musk',
        'aromatic,fresh spicy,woody,soft spicy,herbal',
        'GrigioperlabyLa Perlais a Amber Fougere fragrance for men.Grigioperlawas launched in 1991. Top notes are Rosemary, Lavender, Basil, Coriander, Anise and Bergamot; middle notes are Clary Sage, Geranium and Carnation; base notes are Oakmoss, Sandalwood, Leather, Amber, Cedar, Tonka Bean and Musk.',
        4.04,
        133,
        NULL
      ),
(
        'Grigioperla-Attitude-2962',
        'Grigioperla Attitude La Perla',
        'Grigioperla',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Grigioperla AttitudebyLa Perlais a Aromatic fragrance for men.Grigioperla Attitudewas launched in 2006.',
        4,
        9,
        NULL
      ),
(
        'Grigioperla-Essence-7830',
        'Grigioperla Essence La Perla',
        'Grigioperla',
        'for men',
        NULL,
        'Pierre Bourdon',
        'Cypress, Pink Pepper and Bergamot',
        'Magnolia, Lavender and Jasmine',
        'Pine Tree, Thuja, Vetiver, Oakmoss and Cedar',
        'woody,aromatic,fresh spicy,earthy,floral',
        'Grigioperla EssencebyLa Perlais a Woody Aromatic fragrance for men.Grigioperla Essencewas launched in 2009. The nose behind this fragrance is Pierre Bourdon. Top notes are Cypress, Pink Pepper and Bergamot; middle notes are Magnolia, Lavender and Jasmine; base notes are Pine Tree, Thuja, Vetiver, Oakmoss and Cedar.',
        4.22,
        73,
        NULL
      ),
(
        'GrigioPerla-HEDO-2963',
        'GrigioPerla HEDO La Perla',
        'GrigioPerla',
        'for men',
        NULL,
        NULL,
        'Calabrian bergamot, Mandarin Orange and Sicilian Lemon',
        'Indian Pepper, Ginger and Orange Blossom',
        'Musk, Amber, Cashmere Wood and Cedar',
        'citrus,woody,musky,amber,fresh spicy',
        'GrigioPerla HEDObyLa Perlais a Aromatic Fougere fragrance for men.GrigioPerla HEDOwas launched in 2007. Top notes are Calabrian bergamot, Mandarin Orange and Sicilian Lemon; middle notes are Indian Pepper, Ginger and Orange Blossom; base notes are Musk, Amber, Cashmere Wood and Cedar.',
        3.98,
        54,
        NULL
      ),
(
        'GrigioPerla-Hedo-White-3877',
        'GrigioPerla Hedo White La Perla',
        'GrigioPerla',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot and Grapefruit',
        'Ginger and Cardamom',
        'Tonka Bean, Musk, Patchouli and Cedar',
        'citrus,warm spicy,aromatic,woody,musky',
        'GrigioPerla Hedo WhitebyLa Perlais a Woody Aromatic fragrance for men.GrigioPerla Hedo Whitewas launched in 2008. Top notes are Lemon, Bergamot and Grapefruit; middle notes are Ginger and Cardamom; base notes are Tonka Bean, Musk, Patchouli and Cedar.',
        4,
        18,
        NULL
      ),
(
        'Grigioperla-Nero-14226',
        'Grigioperla Nero La Perla',
        'Grigioperla',
        'for men',
        NULL,
        NULL,
        'Ginger and Grapefruit',
        'Artemisia and Basil',
        'Patchouli and Vetiver',
        'warm spicy,aromatic,woody,patchouli,earthy',
        'Grigioperla NerobyLa Perlais a Woody Aromatic fragrance for men.Grigioperla Nerowas launched in 2012. Top notes are Ginger and Grapefruit; middle notes are Artemisia and Basil; base notes are Patchouli and Vetiver.',
        4,
        16,
        NULL
      ),
(
        'Grigioperla-Uomo-49036',
        'Grigioperla Uomo La Perla',
        'Grigioperla',
        'for men',
        NULL,
        NULL,
        'Cypress, Anise and Pink Grapefruit',
        'Cedar, Heliotrope and Thyme',
        'Vanilla, Patchouli and Guaiac Wood',
        'woody,aromatic,vanilla,powdery,patchouli',
        'Grigioperla UomobyLa Perlais a Woody fragrance for men.Grigioperla Uomowas launched in 2014. Top notes are Cypress, Anise and Pink Grapefruit; middle notes are Cedar, Heliotrope and Thyme; base notes are Vanilla, Patchouli and Guaiac Wood.',
        4.12,
        8,
        NULL
      ),
(
        'Touch-Grigio-Perla-2324',
        'Touch Grigio Perla La Perla',
        'Touch',
        'for men',
        NULL,
        'Nathalie Feisthauer',
        'Cinnamon, Cardamom and Bergamot',
        'Jasmine and Cedar',
        'Vanilla, Musk, Amber and Tonka Bean',
        'vanilla,warm spicy,white floral,amber,powdery',
        'Touch Grigio PerlabyLa Perlais a Woody Spicy fragrance for men.Touch Grigio Perlawas launched in 2000. The nose behind this fragrance is Nathalie Feisthauer. Top notes are Cinnamon, Cardamom and Bergamot; middle notes are Jasmine and Cedar; base notes are Vanilla, Musk, Amber and Tonka Bean.',
        4.32,
        113,
        NULL
      ),
(
        'About-That-Night-67575',
        'About That Night La Perla',
        'About',
        'for women and men',
        NULL,
        'Dominique Preyssas',
        'Lavender, Tagetes, Citruses, Tangerine, Bergamot, Coriander and Lemon',
        'Orange Blossom, Jasmine, Iris, Osmanthus and Rose',
        'Tonka Bean, Musk, Patchouli, Sandalwood, Mexican Vanilla, Vetiver, Styrax, Benzoin, Oakmoss and Oak',
        'citrus,aromatic,sweet,woody,vanilla',
        'About That NightbyLa Perlais a Amber Fougere fragrance for women and men.About That Nightwas launched in 2021. The nose behind this fragrance is Dominique Preyssas. Top notes are Lavender, Tagetes, Citruses, Tangerine, Bergamot, Coriander and Lemon; middle notes are Orange Blossom, Jasmine, Iris, Osmanthus and Rose; base notes are Tonka Bean, Musk, Patchouli, Sandalwood, Mexican Vanilla, Vetiver, Styrax, Benzoin, Oakmoss and Oak.',
        3.72,
        97,
        NULL
      ),
(
        'Invisible-Touch-67569',
        'Invisible Touch La Perla',
        'Invisible',
        'for women and men',
        NULL,
        'Dora Baghriche',
        'Aldehydes, Pink Pepper and Bergamot',
        'Violet, Ylang-Ylang, Paradisone and Rose',
        'Benzoin, Ambroxan, Palisander Rosewood and Patchouli',
        'amber,aldehydic,fresh,violet,woody',
        'Invisible TouchbyLa Perlais a Floral fragrance for women and men.Invisible Touchwas launched in 2021. Invisible Touch was created by Dora Baghriche and Nicolas Bonneville. Top notes are Aldehydes, Pink Pepper and Bergamot; middle notes are Violet, Ylang-Ylang, Paradisone and Rose; base notes are Benzoin, Ambroxan, Palisander Rosewood and Patchouli.',
        3.91,
        129,
        NULL
      ),
(
        'Just-Give-Me-Roses-67576',
        'Just Give Me Roses La Perla',
        'Just',
        'for women and men',
        NULL,
        'Dominique Preyssas',
        'Pink Pepper, Saffron and Black Pepper',
        'Damask Rose, Turkish Rose and Bulgarian Rose',
        'Virginian Cedar, Musk, Amber, Vanilla and Tobacco',
        'rose,warm spicy,musky,woody,soft spicy',
        'Just Give Me RosesbyLa Perlais a Amber Floral fragrance for women and men.Just Give Me Roseswas launched in 2021. The nose behind this fragrance is Dominique Preyssas. Top notes are Pink Pepper, Saffron and Black Pepper; middle notes are Damask Rose, Turkish Rose and Bulgarian Rose; base notes are Virginian Cedar, Musk, Amber, Vanilla and Tobacco.',
        3.71,
        75,
        NULL
      ),
(
        'Let-The-Dance-Begin-67570',
        'Let The Dance Begin La Perla',
        'Let',
        'for women and men',
        NULL,
        'Dominique Preyssas',
        'Davana, Cardamom, Black Pepper, Pink Pepper, Citruses, Neroli, Bergamot and Orange',
        'Cinnamon, Caramel, Tuberose, Geranium, Damask Rose and Ylang-Ylang',
        'Cashmeran, Patchouli, Tonka Bean, Cedar and Sandalwood',
        'woody,warm spicy,aromatic,powdery,cinnamon',
        'Let The Dance BeginbyLa Perlais a Amber Floral fragrance for women and men.Let The Dance Beginwas launched in 2021. The nose behind this fragrance is Dominique Preyssas. Top notes are Davana, Cardamom, Black Pepper, Pink Pepper, Citruses, Neroli, Bergamot and Orange; middle notes are Cinnamon, Caramel, Tuberose, Geranium, Damask Rose and Ylang-Ylang; base notes are Cashmeran, Patchouli, Tonka Bean, Cedar and Sandalwood.',
        3.96,
        134,
        NULL
      ),
(
        'My-Day-67571',
        'My Day La Perla',
        'My',
        'for women and men',
        NULL,
        'Dominique Preyssas',
        'Carrot Seeds, Neroli, Calabrian bergamot, Pink Pepper and Tangerine',
        'Orris, Ylang-Ylang, Egyptian Jasmine, Tuberose, Star Anise, Lily and Osmanthus',
        'Iris, Cashmere Wood, Sandalwood, Tonka Bean, Cedar and Vetiver',
        'iris,woody,powdery,earthy,musky',
        'My DaybyLa Perlais a fragrance for women and men.My Daywas launched in 2021. The nose behind this fragrance is Dominique Preyssas. Top notes are Carrot Seeds, Neroli, Calabrian bergamot, Pink Pepper and Tangerine; middle notes are Orris, Ylang-Ylang, Egyptian Jasmine, Tuberose, Star Anise, Lily and Osmanthus; base notes are Iris, Cashmere Wood, Sandalwood, Tonka Bean, Cedar and Vetiver.',
        3.62,
        116,
        NULL
      ),
(
        'Once-Upon-A-Garden-67572',
        'Once Upon A Garden La Perla',
        'Once',
        'for women and men',
        NULL,
        'Caroline Dumur',
        'Mint, Pink Pepper and Mandarin Orange',
        'Sweet Pea, Rose and Raspberry Leaf',
        'Moss, Ambertonic and Patchouli',
        'floral,sweet,green,rose,aromatic',
        'Once Upon A GardenbyLa Perlais a Floral Green fragrance for women and men.Once Upon A Gardenwas launched in 2021. The nose behind this fragrance is Caroline Dumur. Top notes are Mint, Pink Pepper and Mandarin Orange; middle notes are Sweet Pea, Rose and Raspberry Leaf; base notes are Moss, Ambertonic and Patchouli.',
        3.83,
        151,
        NULL
      ),
(
        'Possibilities-67573',
        'Possibilities La Perla',
        'Possibilities',
        'for women and men',
        NULL,
        'Louise Turner',
        'Freesia, Black Currant and Pink Pepper',
        'Rose, Rose Water, Petalia and Orange Blossom',
        'Cashmere Wood, Mexican Vanilla, Akigalawood and Ambergris',
        'floral,rose,woody,fruity,soft spicy',
        'PossibilitiesbyLa Perlais a Floral Fruity fragrance for women and men.Possibilitieswas launched in 2021. The nose behind this fragrance is Louise Turner. Top notes are Freesia, Black Currant and Pink Pepper; middle notes are Rose, Rose Water, Petalia and Orange Blossom; base notes are Cashmere Wood, Mexican Vanilla, Akigalawood and Ambergris.',
        4.1,
        323,
        NULL
      ),
(
        'Villa-Sorrento-67574',
        'Villa Sorrento La Perla',
        'Villa',
        'for women and men',
        NULL,
        'Roxanne Kirkpatrick',
        'Grapefruit, Green Mandarin and Blood Orange',
        'Neroli and Citrus Leaves',
        'Musk, Ambergris and Woodsy Notes',
        'citrus,fresh spicy',
        'Villa SorrentobyLa Perlais a Citrus Aromatic fragrance for women and men.Villa Sorrentowas launched in 2021. The nose behind this fragrance is Roxanne Kirkpatrick. Top notes are Grapefruit, Green Mandarin and Blood Orange; middle notes are Neroli and Citrus Leaves; base notes are Musk, Ambergris and Woodsy Notes.',
        3.56,
        81,
        NULL
      ),
(
        'La-Perla-In-Rosa-14705',
        'La Perla In Rosa La Perla',
        'La',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Raspberry and Pear',
        'Rose, Cyclamen and Violet',
        'Patchouli, Sandalwood and Amber',
        'fruity,rose,sweet,woody,floral',
        'La Perla In RosabyLa Perlais a Chypre Fruity fragrance for women.La Perla In Rosawas launched in 2012. Top notes are Pink Pepper, Raspberry and Pear; middle notes are Rose, Cyclamen and Violet; base notes are Patchouli, Sandalwood and Amber.',
        3.68,
        321,
        NULL
      ),
(
        'La-Perla-In-Rosa-Eau-de-Parfum-24811',
        'La Perla In Rosa Eau de Parfum La Perla',
        'La',
        'for women',
        NULL,
        NULL,
        'Red Currant, Red Berries and Mandarin Orange',
        'Turkey Red Rose, Orris and Orange Blossom',
        'Praline, Vanilla and Patchouli',
        'sweet,fruity,rose,vanilla,patchouli',
        'La Perla In Rosa Eau de ParfumbyLa Perlais a Chypre Fruity fragrance for women.La Perla In Rosa Eau de Parfumwas launched in 2014. Top notes are Red Currant, Red Berries and Mandarin Orange; middle notes are Turkey Red Rose, Orris and Orange Blossom; base notes are Praline, Vanilla and Patchouli.',
        3.94,
        108,
        NULL
      ),
(
        'J-Aime-1549',
        'J''Aime La Perla',
        'J''Aime',
        'for women',
        NULL,
        'Francoise Caron',
        'Litchi, Pink Pepper and Bergamot',
        'Raspberry, Egyptian Jasmine and Water Lily',
        'Caramel, Amber, Patchouli and White Musk',
        'fruity,sweet,caramel,amber,fresh',
        'J''AimebyLa Perlais a Chypre Floral fragrance for women.J''Aimewas launched in 2007. The nose behind this fragrance is Francoise Caron. Top notes are Litchi, Pink Pepper and Bergamot; middle notes are Raspberry, Egyptian Jasmine and Water Lily; base notes are Caramel, Amber, Patchouli and White Musk.',
        3.74,
        1,
        NULL
      ),
(
        'J-Aime-Elixir-29395',
        'J''Aime Elixir La Perla',
        'J''Aime',
        'for women',
        NULL,
        NULL,
        'Black Pepper, Mandarin Orange and Bergamot',
        'Heliotrope, Rose and Orris',
        'Caramel, Moss and Musk',
        'caramel,powdery,fresh spicy,citrus,sweet',
        'J''Aime ElixirbyLa Perlais a Amber Floral fragrance for women.J''Aime Elixirwas launched in 2015. Top notes are Black Pepper, Mandarin Orange and Bergamot; middle notes are Heliotrope, Rose and Orris; base notes are Caramel, Moss and Musk.',
        3.82,
        126,
        NULL
      ),
(
        'J-Aime-Gold-Edition-24810',
        'J''Aime Gold Edition La Perla',
        'J''Aime',
        'for women',
        NULL,
        NULL,
        'Litchi, Bergamot and Pepper',
        'Raspberry, Egyptian Jasmine and Water Lily',
        'Caramel, Amber, Patchouli and Musk',
        'fruity,sweet,caramel,amber,white floral',
        'J''Aime Gold EditionbyLa Perlais a Floral Fruity Gourmand fragrance for women.J''Aime Gold Editionwas launched in 2014. Top notes are Litchi, Bergamot and Pepper; middle notes are Raspberry, Egyptian Jasmine and Water Lily; base notes are Caramel, Amber, Patchouli and Musk.',
        3.57,
        7,
        NULL
      ),
(
        'J-Aime-La-Nuit-4986',
        'J''Aime La Nuit La Perla',
        'J''Aime',
        'for women',
        NULL,
        'Emilie Bevierre-Coppermann',
        'Pear',
        'Orchid, Jasmine and Rose',
        'Amber and Cashmere Wood',
        'amber,floral,sweet,woody,white floral',
        'J''Aime La NuitbyLa Perlais a Floral Fruity fragrance for women.J''Aime La Nuitwas launched in 2008. The nose behind this fragrance is Emilie Bevierre-Coppermann. Top note is Pear; middle notes are Orchid, Jasmine and Rose; base notes are Amber and Cashmere Wood.',
        4.04,
        1,
        NULL
      ),
(
        'J-Aime-Les-Fleurs-4726',
        'J''Aime Les Fleurs La Perla',
        'J''Aime',
        'for women',
        NULL,
        NULL,
        'Freesia, Green Apple, Grapefruit and Violet Leaf',
        'Peony, Peach and Hawthorn',
        'Musk, Sandalwood and Amber',
        'floral,fruity,fresh,citrus,green',
        'J''Aime Les FleursbyLa Perlais a Floral fragrance for women.J''Aime Les Fleurswas launched in 2008. Top notes are Freesia, Green Apple, Grapefruit and Violet Leaf; middle notes are Peony, Peach and Hawthorn; base notes are Musk, Sandalwood and Amber.',
        3.48,
        358,
        NULL
      ),
(
        'J-Aime-Precious-Edition-5602',
        'J''Aime Precious Edition La Perla',
        'J''Aime',
        'for women',
        NULL,
        NULL,
        'Pear, Pink Pepper, Orange and Bergamot',
        'Tropical Fruit, Big Strawberry, Jasmine and Rose',
        'Vanilla, Tonka Bean, Nutmeg and Patchouli',
        'fruity,sweet,vanilla,tropical,fresh spicy',
        'J''Aime Precious EditionbyLa Perlais a Floral Fruity fragrance for women.J''Aime Precious Editionwas launched in 2009. Top notes are Pear, Pink Pepper, Orange and Bergamot; middle notes are Tropical Fruit, Big Strawberry, Jasmine and Rose; base notes are Vanilla, Tonka Bean, Nutmeg and Patchouli.',
        4.18,
        71,
        NULL
      ),
(
        'Just-Precious-18845',
        'Just Precious La Perla',
        'Just',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Mandarin Orange and Bergamot',
        'Ylang-Ylang, Jasmine, Tiare Flower and Peony',
        'Patchouli, Amber, Vanila and Sandalowood',
        'white floral,citrus,woody,sweet,yellow floral',
        'Just PreciousbyLa Perlais a Amber Floral fragrance for women.Just Preciouswas launched in 2013. Top notes are Orange Blossom, Mandarin Orange and Bergamot; middle notes are Ylang-Ylang, Jasmine, Tiare Flower and Peony; base notes are Patchouli, Amber, Vanila and Sandalowood.',
        3.73,
        315,
        NULL
      ),
(
        'Peony-Blossom-28042',
        'Peony Blossom La Perla',
        'Peony',
        'for women',
        NULL,
        'Firmenich',
        'Orange Blossom, Pear, White Peach and Black Currant',
        'Peony, Jasmine and Violet',
        'Patchouli, Musk and Vanilla',
        'white floral,floral,fresh,fruity,sweet',
        'Peony BlossombyLa Perlais a Floral Fruity fragrance for women.Peony Blossomwas launched in 2014. The nose behind this fragrance is Firmenich. Top notes are Orange Blossom, Pear, White Peach and Black Currant; middle notes are Peony, Jasmine and Violet; base notes are Patchouli, Musk and Vanilla.',
        3.77,
        112,
        NULL
      ),
(
        'La-Mia-Perla-45045',
        'La Mia Perla La Perla',
        'La',
        'for women',
        NULL,
        'Honorine Blanc',
        NULL,
        NULL,
        NULL,
        'musky,powdery,woody,iris,leather',
        'La Mia PerlabyLa Perlais a Amber Floral fragrance for women.La Mia Perlawas launched in 2017. The nose behind this fragrance is Honorine Blanc.',
        4.13,
        601,
        NULL
      ),
(
        'La-Mia-Perla-Nera-58394',
        'La Mia Perla Nera La Perla',
        'La',
        'for women',
        NULL,
        NULL,
        'Black Currant and Bergamot',
        'Jasmine and Pink Lily',
        'Patchouli, Sandalwood, Musk and Cashmere Wood',
        'woody,patchouli,musky,warm spicy,powdery',
        'La Mia Perla NerabyLa Perlais a Chypre Floral fragrance for women.La Mia Perla Nerawas launched in 2019. Top notes are Black Currant and Bergamot; middle notes are Jasmine and Pink Lily; base notes are Patchouli, Sandalwood, Musk and Cashmere Wood.',
        3.81,
        27,
        NULL
      ),
(
        'Contemporary-Tuberose-30423',
        'Contemporary Tuberose La Perla',
        'Contemporary',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Jasmine and Mandarin Orange',
        'Tuberose, Heliotrope and Amyl Salicylate',
        'Cashmeran, Tonka Bean and Cedar',
        'white floral,powdery,woody,vanilla,tuberose',
        'Contemporary TuberosebyLa Perlais a Floral fragrance for women.Contemporary Tuberosewas launched in 2015. Top notes are Orange Blossom, Jasmine and Mandarin Orange; middle notes are Tuberose, Heliotrope and Amyl Salicylate; base notes are Cashmeran, Tonka Bean and Cedar.',
        4.1,
        60,
        NULL
      ),
(
        'Lotus-Shadow-30422',
        'Lotus Shadow La Perla',
        'Lotus',
        'for women',
        NULL,
        NULL,
        'Lotus, Bergamot and Pink Pepper',
        'Green Tea, Rose and Osmanthus',
        'Musk, Sandalwood and Mate',
        'floral,musky,powdery,woody,citrus',
        'Lotus ShadowbyLa Perlais a Floral fragrance for women.Lotus Shadowwas launched in 2015. Top notes are Lotus, Bergamot and Pink Pepper; middle notes are Green Tea, Rose and Osmanthus; base notes are Musk, Sandalwood and Mate.',
        4.28,
        32,
        NULL
      ),
(
        'White-Iris-30425',
        'White Iris La Perla',
        'White',
        'for women',
        NULL,
        NULL,
        'Violet, Bergamot and Jasmine',
        'Heliotrope, Almond and Orris',
        'Vanila, Tonka Bean and Ambroxan',
        'powdery,vanilla,almond,floral,violet',
        'White IrisbyLa Perlais a Floral fragrance for women.White Iriswas launched in 2015. Top notes are Violet, Bergamot and Jasmine; middle notes are Heliotrope, Almond and Orris; base notes are Vanila, Tonka Bean and Ambroxan.',
        4.36,
        106,
        NULL
      ),
(
        'La-Perla-Luminous-75869',
        'La Perla Luminous La Perla',
        'La',
        'for women',
        NULL,
        'Louise Turner',
        'Ambrette (Musk Mallow)',
        'Jasmine Sambac and Sandalwood',
        'Cedar',
        'white floral,woody,floral,musky,powdery',
        'La Perla LuminousbyLa Perlais a Floral Woody Musk fragrance for women. This is a new fragrance.La Perla Luminouswas launched in 2022. The nose behind this fragrance is Louise Turner. Top note is Ambrette (Musk Mallow); middle notes are Jasmine Sambac and Sandalwood; base note is Cedar.',
        3.72,
        127,
        NULL
      ),
(
        'La-Perla-Signature-67577',
        'La Perla Signature La Perla',
        'La',
        'for women',
        NULL,
        'Louise Turner',
        'Violet Leaves, Citruses, Mandarin Orange and Neroli',
        'Jasmine Sambac and Nectarine',
        'Woodsy Notes, Vetiver and Cedar',
        'woody,citrus,white floral,ozonic,fresh',
        'La Perla SignaturebyLa Perlais a Floral fragrance for women.La Perla Signaturewas launched in 2021. The nose behind this fragrance is Louise Turner. Top notes are Violet Leaves, Citruses, Mandarin Orange and Neroli; middle notes are Jasmine Sambac and Nectarine; base notes are Woodsy Notes, Vetiver and Cedar.',
        4.15,
        189,
        NULL
      ),
(
        'Dark-Extacy-8994',
        'Dark Extacy La Perla',
        'Dark',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,chocolate,warm spicy,vanilla,soft spicy',
        'Dark ExtacybyLa Perlais a Amber Vanilla fragrance for women.Dark Extacywas launched in 2007.',
        4.25,
        161,
        NULL
      ),
(
        'Languid-Vanilla-8993',
        'Languid Vanilla La Perla',
        'Languid',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,powdery,musky,white floral',
        'Languid VanillabyLa Perlais a Amber Vanilla fragrance for women.Languid Vanillawas launched in 2007.',
        4.19,
        26,
        NULL
      ),
(
        'Ruby-Perlage-8992',
        'Ruby Perlage La Perla',
        'Ruby',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,powdery,sweet,white floral,cacao',
        'Ruby PerlagebyLa Perlais a Floral Fruity Gourmand fragrance for women.Ruby Perlagewas launched in 2007.',
        3.96,
        27,
        NULL
      ),
(
        'Adios-Pampamia-Hombre-36343',
        'Adios Pampamia Hombre La Martina',
        'Adios',
        'for men',
        NULL,
        NULL,
        'Pepper, Aldehydes and Incense',
        'Orange Blossom and Ylang-Ylang',
        'Tolu Balsam, Vanilla and Benzoin',
        'amber,warm spicy,vanilla,powdery,balsamic',
        'Adios Pampamia HombrebyLa Martinais a Aromatic fragrance for men.Adios Pampamia Hombrewas launched in 2011. Top notes are Pepper, Aldehydes and Incense; middle notes are Orange Blossom and Ylang-Ylang; base notes are Tolu Balsam, Vanilla and Benzoin.',
        3.59,
        29,
        NULL
      ),
(
        'Adios-Pampamia-Mujer-36344',
        'Adios Pampamia Mujer La Martina',
        'Adios',
        'for women',
        NULL,
        NULL,
        'Hazelnut, Pink Pepper and Green Notes',
        'Iris, Incense and Freesia',
        'Woody Notes, Vanilla and Amber',
        'woody,amber,iris,powdery,nutty',
        'Adios Pampamia MujerbyLa Martinais a Floral fragrance for women.Adios Pampamia Mujerwas launched in 2011. Top notes are Hazelnut, Pink Pepper and Green Notes; middle notes are Iris, Incense and Freesia; base notes are Woody Notes, Vanilla and Amber.',
        3.96,
        212,
        NULL
      ),
(
        'Bayres-Hombre-36348',
        'Bayres Hombre La Martina',
        'Bayres',
        'for men',
        NULL,
        NULL,
        'Coriander, Grapefruit, Bergamot, Rhubarb and Pink Pepper',
        'Magnolia, Jasmine, Geranium and Lily-of-the-Valley',
        'Vetiver, Teak Wood, Leather, Oakmoss, Thuja, Tonka Bean, Amber, Musk and Caramel',
        'aromatic,woody,earthy,citrus,leather',
        'Bayres HombrebyLa Martinais a Leather fragrance for men. Top notes are Coriander, Grapefruit, Bergamot, Rhubarb and Pink Pepper; middle notes are Magnolia, Jasmine, Geranium and Lily-of-the-Valley; base notes are Vetiver, Teak Wood, Leather, Oakmoss, Thuja, Tonka Bean, Amber, Musk and Caramel.',
        4.21,
        34,
        NULL
      ),
(
        'Bayres-Mujer-36339',
        'Bayres Mujer La Martina',
        'Bayres',
        'for women',
        NULL,
        'Michel Garnero',
        'Galbanum and Coconut',
        'Plum, Rose, Jasmine and Geranium',
        'Patchouli, Sandalwood, Amber and Vanilla',
        'fruity,rose,green,aromatic,sweet',
        'Bayres MujerbyLa Martinais a Chypre Floral fragrance for women.Bayres Mujerwas launched in 2007. The nose behind this fragrance is Michel Garnero. Top notes are Galbanum and Coconut; middle notes are Plum, Rose, Jasmine and Geranium; base notes are Patchouli, Sandalwood, Amber and Vanilla.',
        4.05,
        19,
        NULL
      ),
(
        'Cuero-36349',
        'Cuero La Martina',
        'Cuero',
        'for men',
        NULL,
        'Jean-Christophe Hérault',
        'Bergamot, Lavender and Lemon',
        'Patchouli, Styrax and Cedar',
        'Leather, Vanilla and Coumarin',
        'woody,citrus,vanilla,aromatic,leather',
        'CuerobyLa Martinais a Leather fragrance for men.Cuerowas launched in 2009. The nose behind this fragrance is Jean-Christophe Hérault. Top notes are Bergamot, Lavender and Lemon; middle notes are Patchouli, Styrax and Cedar; base notes are Leather, Vanilla and Coumarin.',
        4.05,
        55,
        NULL
      ),
(
        'Cuero-Mujer-36338',
        'Cuero Mujer La Martina',
        'Cuero',
        'for women',
        NULL,
        NULL,
        'White Peach, Green Notes, Pink Pepper, Bergamot and Lime',
        'Vetiver, Sandalwood, Rose, Jasmine Sambac and Lily-of-the-Valley',
        'White Musk, Tobacco Leaf and Amber',
        'musky,powdery,woody,sweet,green',
        'Cuero MujerbyLa Martinais a Floral Fruity fragrance for women.Cuero Mujerwas launched in 2010. Top notes are White Peach, Green Notes, Pink Pepper, Bergamot and Lime; middle notes are Vetiver, Sandalwood, Rose, Jasmine Sambac and Lily-of-the-Valley; base notes are White Musk, Tobacco Leaf and Amber.',
        4.06,
        51,
        NULL
      ),
(
        'La-Martina-Hombre-36340',
        'La Martina Hombre La Martina',
        'La',
        'for men',
        NULL,
        NULL,
        'Basil, Bergamot, Lemon and Mandarin Orange',
        'Thyme, Cardamom, Pepper and Cloves',
        'White Cedar Extract, Vetiver, Musk and Patchouli',
        'aromatic,fresh spicy,woody,warm spicy,citrus',
        'La Martina HombrebyLa Martinais a Woody Spicy fragrance for men.La Martina Hombrewas launched in 2008. Top notes are Basil, Bergamot, Lemon and Mandarin Orange; middle notes are Thyme, Cardamom, Pepper and Cloves; base notes are White Cedar Extract, Vetiver, Musk and Patchouli.',
        3.98,
        55,
        NULL
      ),
(
        'La-Martina-Mujer-36341',
        'La Martina Mujer La Martina',
        'La',
        'for women',
        NULL,
        NULL,
        'Clary Sage, Coriander and Citruses',
        'Gardenia, Ylang-Ylang, Carnation, Cloves, Rose and Violet',
        'Coconut, Musk and Vetiver',
        'white floral,yellow floral,aromatic,lactonic,sweet',
        'La Martina MujerbyLa Martinais a Aromatic Spicy fragrance for women.La Martina Mujerwas launched in 2006. Top notes are Clary Sage, Coriander and Citruses; middle notes are Gardenia, Ylang-Ylang, Carnation, Cloves, Rose and Violet; base notes are Coconut, Musk and Vetiver.',
        3.83,
        30,
        NULL
      ),
(
        'Maserati-36350',
        'Maserati La Martina',
        'Maserati',
        'for men',
        NULL,
        NULL,
        'Cypress, Bergamot and Mandarin Orange',
        'Sage, Daisy and Angelica',
        'Suede, Leather, Cedar and Vetiver',
        'woody,aromatic,leather,citrus,musky',
        'MaseratibyLa Martinais a Aromatic Fougere fragrance for men.Maseratiwas launched during the 2010''s. Top notes are Cypress, Bergamot and Mandarin Orange; middle notes are Sage, Daisy and Angelica; base notes are Suede, Leather, Cedar and Vetiver.',
        4.07,
        84,
        NULL
      ),
(
        'Maserati-Centennial-Polo-Tour-36352',
        'Maserati Centennial Polo Tour La Martina',
        'Maserati',
        'for men',
        NULL,
        'Maurizio Cerizza',
        'Bergamot, Nutmeg and Mandarin Orange',
        'Violet and Ivy',
        'Incense, Musk, Vetiver and Patchouli',
        'citrus,fresh spicy,woody,powdery,green',
        'Maserati Centennial Polo TourbyLa Martinais a Citrus Aromatic fragrance for men.Maserati Centennial Polo Tourwas launched in 2014. The nose behind this fragrance is Maurizio Cerizza. Top notes are Bergamot, Nutmeg and Mandarin Orange; middle notes are Violet and Ivy; base notes are Incense, Musk, Vetiver and Patchouli.',
        4.04,
        49,
        NULL
      ),
(
        'Maserati-Horse-Passion-36353',
        'Maserati Horse Passion La Martina',
        'Maserati',
        'for men',
        NULL,
        NULL,
        'Cardamom, White Pepper, Cinnamon, Ginger and Grapefruit',
        'Orange Blossom and Labdanum',
        'Musk, Leather, Cedar and Agarwood (Oud)',
        'warm spicy,musky,leather,woody,fresh spicy',
        'Maserati Horse PassionbyLa Martinais a Citrus Aromatic fragrance for men.Maserati Horse Passionwas launched in 2013. Top notes are Cardamom, White Pepper, Cinnamon, Ginger and Grapefruit; middle notes are Orange Blossom and Labdanum; base notes are Musk, Leather, Cedar and Agarwood (Oud).',
        4,
        11,
        NULL
      ),
(
        'Maserati-Pure-Code-47121',
        'Maserati Pure Code La Martina',
        'Maserati',
        'for women and men',
        NULL,
        'Paolo Cerizza',
        'Water Notes, Bergamot, Coriander, Sweet Orange and Tangerine',
        'Vetiver, Sandalwood, Black Pepper, Cedar and Patchouli',
        'White Musk, Vanilla and Ambergris',
        'citrus,aromatic,woody,aquatic,fresh spicy',
        'Maserati Pure CodebyLa Martinais a Woody fragrance for women and men.Maserati Pure Codewas launched in 2017. The nose behind this fragrance is Paolo Cerizza. Top notes are Water Notes, Bergamot, Coriander, Sweet Orange and Tangerine; middle notes are Vetiver, Sandalwood, Black Pepper, Cedar and Patchouli; base notes are White Musk, Vanilla and Ambergris.',
        3.53,
        17,
        NULL
      ),
(
        'Maserati-Pure-Code-Blue-52171',
        'Maserati Pure Code Blue La Martina',
        'Maserati',
        'for men',
        NULL,
        NULL,
        'Iced Lemon, Sea Notes and Aromatic Spices',
        'Apple, Piña Colada, Violet and Cedar',
        'Tonka Bean, Amber, Vetiver and Musk',
        'aromatic,woody,powdery,fruity,amber',
        'Maserati Pure Code BluebyLa Martinais a Aromatic Fruity fragrance for men.Maserati Pure Code Bluewas launched in 2018. Top notes are Iced Lemon, Sea Notes and Aromatic Spices; middle notes are Apple, Piña Colada, Violet and Cedar; base notes are Tonka Bean, Amber, Vetiver and Musk.',
        3,
        12,
        NULL
      ),
(
        'Pampamia-Noble-36342',
        'Pampamia Noble La Martina',
        'Pampamia',
        'for men',
        NULL,
        NULL,
        'Incense, Ylang-Ylang and Bergamot',
        'Iris, Violet and Lotus',
        'Amber, Cedar and Styrax',
        'amber,woody,powdery,iris,violet',
        'Pampamia NoblebyLa Martinais a Aromatic Green fragrance for men.Pampamia Noblewas launched in 2013. Top notes are Incense, Ylang-Ylang and Bergamot; middle notes are Iris, Violet and Lotus; base notes are Amber, Cedar and Styrax.',
        3.86,
        22,
        NULL
      ),
(
        'Quimera-Hombre-47123',
        'Quimera Hombre La Martina',
        'Quimera',
        'for men',
        NULL,
        NULL,
        'Sea Notes',
        'Citruses',
        'Patchouli',
        'citrus,patchouli,fresh,marine,woody',
        'Quimera HombrebyLa Martinais a Aromatic Aquatic fragrance for men.Quimera Hombrewas launched in 2017. Top note is Sea Notes; middle note is Citruses; base note is Patchouli.',
        3.33,
        9,
        NULL
      ),
(
        'Quimera-Mujer-47122',
        'Quimera Mujer La Martina',
        'Quimera',
        'for women',
        NULL,
        NULL,
        'Black Currant, Lemon and Tangerine',
        'Raspberry, Freesia and Lily-of-the-Valley',
        'Patchouli, Benzoin and Musk',
        'fruity,citrus,floral,sweet,woody',
        'Quimera MujerbyLa Martinais a Floral Fruity fragrance for women.Quimera Mujerwas launched in 2017. Top notes are Black Currant, Lemon and Tangerine; middle notes are Raspberry, Freesia and Lily-of-the-Valley; base notes are Patchouli, Benzoin and Musk.',
        4,
        14,
        NULL
      ),
(
        'Sueno-Hombre-36354',
        'Sueno Hombre La Martina',
        'Sueno',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Apple and Aldehydes',
        'Spruce, Cedar and Sea water',
        'Oakmoss, Tonka Bean, Amberwood and Patchouli',
        'woody,aromatic,citrus,green,amber',
        'Sueno HombrebyLa Martinais a Aromatic fragrance for men.Sueno Hombrewas launched in 2015. Top notes are Bergamot, Lemon, Apple and Aldehydes; middle notes are Spruce, Cedar and Sea water; base notes are Oakmoss, Tonka Bean, Amberwood and Patchouli.',
        4,
        12,
        NULL
      ),
(
        'Sueno-Mujer-36355',
        'Sueno Mujer La Martina',
        'Sueno',
        'for women',
        NULL,
        NULL,
        'Black Currant and Bergamot',
        'Iris and Rose',
        'Vanilla and Patchouli',
        'iris,woody,powdery,fruity,vanilla',
        'Sueno MujerbyLa Martinais a Floral Fruity fragrance for women.Sueno Mujerwas launched in 2015. Top notes are Black Currant and Bergamot; middle notes are Iris and Rose; base notes are Vanilla and Patchouli.',
        3.73,
        11,
        NULL
      ),
(
        'Suerte-41757',
        'Suerte La Martina',
        'Suerte',
        'for men',
        NULL,
        NULL,
        'Lavender and Lemon',
        'Cinnamon, Cloves, Tobacco Blossom and Myrrh',
        'White Amber, Benzoin, Guaiac Wood, Tonka Bean, Patchouli and Musk',
        'warm spicy,amber,cinnamon,white floral,woody',
        'SuertebyLa Martinais a Amber Fougere fragrance for men.Suertewas launched in 2016. Top notes are Lavender and Lemon; middle notes are Cinnamon, Cloves, Tobacco Blossom and Myrrh; base notes are White Amber, Benzoin, Guaiac Wood, Tonka Bean, Patchouli and Musk.',
        4.2,
        25,
        NULL
      ),
(
        'Te-Quiero-52172',
        'Te Quiero La Martina',
        'Te',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lavender and Nutmeg',
        'Orange Blossom, Amber and Patchouli',
        'Musk, Vetiver and Leather',
        'fresh spicy,citrus,woody,aromatic,animalic',
        'Te QuierobyLa Martinais a Aromatic Aquatic fragrance for men.Te Quierowas launched in 2018. Top notes are Bergamot, Lavender and Nutmeg; middle notes are Orange Blossom, Amber and Patchouli; base notes are Musk, Vetiver and Leather.',
        4.8,
        5,
        NULL
      ),
(
        'Te-Quiero-Woman-52173',
        'Te Quiero Woman La Martina',
        'Te',
        'for women',
        NULL,
        NULL,
        'Apple Blossom, Pear and Iced Lemon',
        'Freesia and Coconut',
        'Amber, Musk and Cedar',
        'floral,fruity,citrus,fresh,sweet',
        'Te Quiero WomanbyLa Martinais a Floral Fruity fragrance for women.Te Quiero Womanwas launched in 2018. Top notes are Apple Blossom, Pear and Iced Lemon; middle notes are Freesia and Coconut; base notes are Amber, Musk and Cedar.',
        4,
        1,
        NULL
      ),
(
        'Tierra-del-Fuego-36356',
        'Tierra del Fuego La Martina',
        'Tierra',
        'for men',
        NULL,
        NULL,
        'Pineapple, Black Currant, Bergamot and Apple',
        'Birch, Patchouli, Jasmine and Rose',
        'Oakmoss, Musk, Amber and Vanilla',
        'fruity,woody,sweet,leather,earthy',
        'Tierra del FuegobyLa Martinais a Floral Woody Musk fragrance for men.Tierra del Fuegowas launched in 2012. Top notes are Pineapple, Black Currant, Bergamot and Apple; middle notes are Birch, Patchouli, Jasmine and Rose; base notes are Oakmoss, Musk, Amber and Vanilla.',
        4.12,
        100,
        NULL
      ),
(
        'Alma-Colecion-Privada-Black-Rose-36345',
        'Alma Colecion Privada Black Rose La Martina',
        'Alma',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Hedione and Geranium',
        'Damask Rose',
        'Vanilla, Blackwood, Musk and Black Amber',
        'rose,vanilla,woody,musky,floral',
        'Alma Colecion Privada Black RosebyLa Martinais a Floral Woody Musk fragrance for women and men.Alma Colecion Privada Black Rosewas launched in 2014. The nose behind this fragrance is Maurizio Cerizza. Top notes are Hedione and Geranium; middle note is Damask Rose; base notes are Vanilla, Blackwood, Musk and Black Amber.',
        4.05,
        19,
        NULL
      ),
(
        'Alma-Colecion-Privada-Misterious-Oud-36346',
        'Alma Colecion Privada Misterious Oud La Martina',
        'Alma',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Pink Pepper, Elemi resin, Galbanum, Cinnamon and Bergamot',
        'Styrax and Labdanum',
        'Haitian Vetiver, Amyris, Guaiac Wood, Musk, Cashmeran, Vanilla and Amber',
        'aromatic,woody,musky,balsamic,green',
        'Alma Colecion Privada Misterious OudbyLa Martinais a Amber Woody fragrance for women and men.Alma Colecion Privada Misterious Oudwas launched in 2014. The nose behind this fragrance is Maurizio Cerizza. Top notes are Pink Pepper, Elemi resin, Galbanum, Cinnamon and Bergamot; middle notes are Styrax and Labdanum; base notes are Haitian Vetiver, Amyris, Guaiac Wood, Musk, Cashmeran, Vanilla and Amber.',
        4.28,
        18,
        NULL
      ),
(
        'Alma-Colecion-Privada-Secret-Wood-36347',
        'Alma Colecion Privada Secret Wood La Martina',
        'Alma',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon, Wormwood, Nutmeg, Cloves, Geranium and Bergamot',
        'Sandalwood, Vetiver, Haitian Vetiver, Cedar and Cashmeran',
        'Balsam Fir, Patchouli and Vanilla',
        'woody,fresh spicy,aromatic,warm spicy,powdery',
        'Alma Colecion Privada Secret WoodbyLa Martinais a Aromatic Green fragrance for women and men.Alma Colecion Privada Secret Woodwas launched in 2014. Top notes are Cinnamon, Wormwood, Nutmeg, Cloves, Geranium and Bergamot; middle notes are Sandalwood, Vetiver, Haitian Vetiver, Cedar and Cashmeran; base notes are Balsam Fir, Patchouli and Vanilla.',
        4.5,
        14,
        NULL
      ),
(
        'Alpha-Woods-70554',
        'Alpha Woods La Martina',
        'Alpha',
        'for women and men',
        NULL,
        'Mathilde Bijaoui',
        'Lime and Pink Pepper',
        'Violet Leaves',
        'Haitian Vetiver and Patchouli',
        'woody,citrus,aromatic,earthy,ozonic',
        'Alpha WoodsbyLa Martinais a Citrus Aromatic fragrance for women and men.Alpha Woodswas launched in 2020. The nose behind this fragrance is Mathilde Bijaoui. Top notes are Lime and Pink Pepper; middle note is Violet Leaves; base notes are Haitian Vetiver and Patchouli.',
        4.33,
        3,
        NULL
      ),
(
        'Blue-Gardenia-70555',
        'Blue Gardenia La Martina',
        'Blue',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Bergamot and Petitgrain Paraguay',
        'White Rose, Magnolia, Lily-of-the-Valley, Night Blooming Jasmine and Orange Blossom',
        'Cashmere Wood, Amber, Musk and Sandalwood',
        'white floral,floral,citrus,rose,fruity',
        'Blue GardeniabyLa Martinais a Floral Woody Musk fragrance for women and men.Blue Gardeniawas launched in 2020. The nose behind this fragrance is Luca Maffei. Top notes are Bergamot and Petitgrain Paraguay; middle notes are White Rose, Magnolia, Lily-of-the-Valley, Night Blooming Jasmine and Orange Blossom; base notes are Cashmere Wood, Amber, Musk and Sandalwood.',
        3.83,
        6,
        NULL
      ),
(
        'Nude-Amber-70557',
        'Nude Amber La Martina',
        'Nude',
        'for women and men',
        NULL,
        'Véronique Nyberg',
        'Lemon and Bergamot',
        'Lily-of-the-Valley, Peony and Orange Blossom',
        'Amberwood',
        'white floral,fresh,citrus,amber,floral',
        'Nude AmberbyLa Martinais a Amber Floral fragrance for women and men.Nude Amberwas launched in 2020. The nose behind this fragrance is Veronique Nyberg. Top notes are Lemon and Bergamot; middle notes are Lily-of-the-Valley, Peony and Orange Blossom; base note is Amberwood.',
        3.2,
        5,
        NULL
      ),
(
        'Solar-Musk-70556',
        'Solar Musk La Martina',
        'Solar',
        'for women and men',
        NULL,
        'Barbara Zoebelein',
        'Apple, Yuzu, Pink Pepper and Bergamot',
        'Sage, Geranium, Suede and Patchouli',
        'Birch, Moss and Sequoia',
        'woody,leather,mossy,smoky,fruity',
        'Solar MuskbyLa Martinais a Aromatic Fougere fragrance for women and men.Solar Muskwas launched in 2020. The nose behind this fragrance is Barbara Zoebelein. Top notes are Apple, Yuzu, Pink Pepper and Bergamot; middle notes are Sage, Geranium, Suede and Patchouli; base notes are Birch, Moss and Sequoia.',
        3.88,
        8,
        NULL
      ),
(
        'Addict-Angel-No-13-49170',
        'Addict Angel No. 13 LA CHANTEE',
        'Addict',
        'for women',
        NULL,
        NULL,
        'Bergamot, Black Currant, Grapefruit and Peach',
        'Jasmine, Plum, Rose, Orange Blossom and Musk',
        'Vanilla, Cedar, Patchouli and Geranium',
        'fruity,citrus,woody,white floral,vanilla',
        'Addict Angel No. 13byLA CHANTEEis a fragrance for women.Addict Angel No. 13was launched in 2017. Top notes are Bergamot, Black Currant, Grapefruit and Peach; middle notes are Jasmine, Plum, Rose, Orange Blossom and Musk; base notes are Vanilla, Cedar, Patchouli and Geranium.',
        5,
        1,
        NULL
      ),
(
        'Angel-Promise-No-6-49127',
        'Angel Promise No. 6 LA CHANTEE',
        'Angel',
        'for women',
        NULL,
        NULL,
        'Bergamot and Pear',
        'Ylang-Ylang, Rose, Violet and Lily-of-the-Valley',
        'Sandalwood and Musk',
        'woody,powdery,yellow floral,citrus,rose',
        'Angel Promise No. 6byLA CHANTEEis a fragrance for women.Angel Promise No. 6was launched in 2017. Top notes are Bergamot and Pear; middle notes are Ylang-Ylang, Rose, Violet and Lily-of-the-Valley; base notes are Sandalwood and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Attraction-No-15-49173',
        'Attraction No. 15 LA CHANTEE',
        'Attraction',
        'for men',
        NULL,
        NULL,
        'Orange, Tangerine, Lemon and Grapefruit',
        'Rose and Sea Notes',
        'Vetiver, Vanilla, Patchouli, Sandalwood and Musk',
        'citrus,woody,aromatic,sweet,vanilla',
        'Attraction No. 15byLA CHANTEEis a fragrance for men.Attraction No. 15was launched in 2017. Top notes are Orange, Tangerine, Lemon and Grapefruit; middle notes are Rose and Sea Notes; base notes are Vetiver, Vanilla, Patchouli, Sandalwood and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Back-to-20-No-24-49184',
        'Back to 20 No. 24 LA CHANTEE',
        'Back',
        'for women',
        NULL,
        NULL,
        'Tangerine and Pineapple',
        'Rose, Strawberry, Raspberry and Black Currant',
        'White Musk',
        'fruity,sweet,rose,citrus',
        'Back to 20 No. 24byLA CHANTEEis a fragrance for women.Back to 20 No. 24was launched in 2017. Top notes are Tangerine and Pineapple; middle notes are Rose, Strawberry, Raspberry and Black Currant; base note is White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Breeze-No-17-49176',
        'Breeze No. 17 LA CHANTEE',
        'Breeze',
        'for men',
        NULL,
        NULL,
        'Lemon, Orange and Tangerine',
        'Orange Blossom, Sage, Eucalyptus and Geranium',
        'Cedar, Patchouli, Sandalwood, Pine Tree and Musk',
        'citrus,woody,aromatic,white floral,sweet',
        'Breeze No. 17byLA CHANTEEis a fragrance for men.Breeze No. 17was launched in 2017. Top notes are Lemon, Orange and Tangerine; middle notes are Orange Blossom, Sage, Eucalyptus and Geranium; base notes are Cedar, Patchouli, Sandalwood, Pine Tree and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Cape-Town-No-19-49179',
        'Cape Town No. 19 LA CHANTEE',
        'Cape',
        'for women',
        NULL,
        NULL,
        'Bergamot, Grapefruit and Black Currant',
        'Rose, Ginger, Magnolia and Soybean',
        'White Musk',
        'citrus,fresh spicy,aromatic,floral,fruity',
        'Cape Town No. 19byLA CHANTEEis a fragrance for women.Cape Town No. 19was launched in 2017. Top notes are Bergamot, Grapefruit and Black Currant; middle notes are Rose, Ginger, Magnolia and Soybean; base note is White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ciel-No-18-49177',
        'Ciel No. 18 LA CHANTEE',
        'Ciel',
        'for men',
        NULL,
        NULL,
        'Lemon, Orange and Green Grass',
        'Lavender, Iris, Rose and Cypress',
        'Patchouli, Cedar, Musk and Amber',
        'woody,citrus,powdery,iris,lavender',
        'Ciel No. 18byLA CHANTEEis a fragrance for men.Ciel No. 18was launched in 2017. Top notes are Lemon, Orange and Green Grass; middle notes are Lavender, Iris, Rose and Cypress; base notes are Patchouli, Cedar, Musk and Amber.',
        5,
        1,
        NULL
      ),
(
        'Cool-No-23-49185',
        'Cool No. 23 LA CHANTEE',
        'Cool',
        'for men',
        NULL,
        NULL,
        'Mint, Orange and Ginger',
        'Sea Notes and Geranium',
        'White Musk, Vetiver and Oakmoss',
        'aromatic,citrus,green,fresh spicy,marine',
        'Cool No. 23byLA CHANTEEis a fragrance for men.Cool No. 23was launched in 2017. Top notes are Mint, Orange and Ginger; middle notes are Sea Notes and Geranium; base notes are White Musk, Vetiver and Oakmoss.',
        NULL,
        NULL,
        NULL
      ),
(
        'Deja-Vu-No-20-49180',
        'Déjà-Vu No. 20 LA CHANTEE',
        'Déjà-Vu',
        'for women',
        NULL,
        NULL,
        'Ginger and Lemon',
        'Rose',
        'Vetiver and White Musk',
        'rose,floral,warm spicy,aromatic,citrus',
        'Déjà-Vu No. 20byLA CHANTEEis a fragrance for women.Déjà-Vu No. 20was launched in 2017. Top notes are Ginger and Lemon; middle note is Rose; base notes are Vetiver and White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Desire-No-21-49182',
        'Desire No. 21 LA CHANTEE',
        'Desire',
        'for men',
        NULL,
        NULL,
        'Basil, Rosemary and Tarragon',
        'Apple',
        'Patchouli, Musk and Incense',
        'fresh spicy,aromatic,patchouli,green,woody',
        'Desire No. 21byLA CHANTEEis a fragrance for men.Desire No. 21was launched in 2017. Top notes are Basil, Rosemary and Tarragon; middle note is Apple; base notes are Patchouli, Musk and Incense.',
        NULL,
        NULL,
        NULL
      ),
(
        'East-London-No-16-49174',
        'East London No. 16 LA CHANTEE',
        'East',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Tangerine and Orange',
        'Orange Blossom, Geranium, Coriander and Tarragon',
        'Cedar, Sandalwood, Patchouli and Pine Tree',
        'citrus,woody,aromatic,fresh spicy',
        'East London No. 16byLA CHANTEEis a fragrance for men.East London No. 16was launched in 2017. Top notes are Bergamot, Lemon, Tangerine and Orange; middle notes are Orange Blossom, Geranium, Coriander and Tarragon; base notes are Cedar, Sandalwood, Patchouli and Pine Tree.',
        5,
        1,
        NULL
      ),
(
        'Enchantee-No-7-49128',
        'Enchantée No. 7 LA CHANTEE',
        'Enchantée',
        'for women',
        NULL,
        NULL,
        'Black Currant and Green Grass',
        'Iris, Rose, Violet and Jasmine',
        'White Musk',
        'powdery,violet,musky,fruity,iris',
        'Enchantée No. 7byLA CHANTEEis a fragrance for women.Enchantée No. 7was launched in 2017. Top notes are Black Currant and Green Grass; middle notes are Iris, Rose, Violet and Jasmine; base note is White Musk.',
        4,
        1,
        NULL
      ),
(
        'Enchanting-Gardenia-No-2-49121',
        'Enchanting Gardenia No. 2 LA CHANTEE',
        'Enchanting',
        'for women',
        NULL,
        NULL,
        'Black Currant, Peach and Grapefruit',
        'Plum, Gardenia, Rose, Jasmine and Lily-of-the-Valley',
        'Patchouli, Vanilla, Sandalwood, Amber and Musk',
        'fruity,white floral,woody,powdery,vanilla',
        'Enchanting Gardenia No. 2byLA CHANTEEis a fragrance for women.Enchanting Gardenia No. 2was launched in 2017. Top notes are Black Currant, Peach and Grapefruit; middle notes are Plum, Gardenia, Rose, Jasmine and Lily-of-the-Valley; base notes are Patchouli, Vanilla, Sandalwood, Amber and Musk.',
        5,
        1,
        NULL
      ),
(
        'Eternal-Love-No-3-49122',
        'Eternal Love No. 3 LA CHANTEE',
        'Eternal',
        'for women',
        NULL,
        NULL,
        'Bergamot',
        'Jasmine, Ylang-Ylang and Orange Blossom',
        'Sandalwood, Vanilla and Benzoin',
        'white floral,citrus,woody,vanilla,powdery',
        'Eternal Love No. 3byLA CHANTEEis a fragrance for women.Eternal Love No. 3was launched in 2017. Top note is Bergamot; middle notes are Jasmine, Ylang-Ylang and Orange Blossom; base notes are Sandalwood, Vanilla and Benzoin.',
        NULL,
        NULL,
        NULL
      ),
(
        'Exotic-Passion-No-25-49134',
        'Exotic Passion No. 25 LA CHANTEE',
        'Exotic',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Ginger and Soybean',
        'Jasmine',
        'Oolong tea',
        'citrus,aromatic,white floral,warm spicy,fresh spicy',
        'Exotic Passion No. 25byLA CHANTEEis a fragrance for women and men.Exotic Passion No. 25was launched in 2017. Top notes are Bergamot, Ginger and Soybean; middle note is Jasmine; base note is Oolong tea.',
        5,
        1,
        NULL
      ),
(
        'Fantasy-Forest-No-11-49133',
        'Fantasy Forest No. 11 LA CHANTEE',
        'Fantasy',
        'for women and men',
        NULL,
        NULL,
        'Orange, Grapefruit, Lemon, Tangerine and Bergamot',
        'Mint, Eucalyptus, Rose and Thyme',
        'Musk, Oakmoss, Patchouli and Sandalwood',
        'citrus,aromatic,woody,fresh spicy,green',
        'Fantasy Forest No. 11byLA CHANTEEis a fragrance for women and men.Fantasy Forest No. 11was launched in 2017. Top notes are Orange, Grapefruit, Lemon, Tangerine and Bergamot; middle notes are Mint, Eucalyptus, Rose and Thyme; base notes are Musk, Oakmoss, Patchouli and Sandalwood.',
        5,
        2,
        NULL
      ),
(
        'Firenze-No-8-49129',
        'Firenze No. 8 LA CHANTEE',
        'Firenze',
        'for women',
        NULL,
        NULL,
        'Orange, Lemon, Tangerine and Black Currant',
        'Rose',
        'Patchouli, Cedar and Musk',
        'citrus,woody,fruity,patchouli,rose',
        'Firenze No. 8byLA CHANTEEis a fragrance for women.Firenze No. 8was launched in 2017. Top notes are Orange, Lemon, Tangerine and Black Currant; middle note is Rose; base notes are Patchouli, Cedar and Musk.',
        5,
        1,
        NULL
      ),
(
        'Formosa-No-14-49171',
        'Formosa No. 14 LA CHANTEE',
        'Formosa',
        'for men',
        NULL,
        NULL,
        'Tangerine, Lemon and Green Grass',
        'Thyme, Mint, Basil and Wormwood',
        'Birch, Patchouli, Cedar, Sandalwood and Musk',
        'aromatic,woody,green,fresh spicy,citrus',
        'Formosa No. 14byLA CHANTEEis a fragrance for men.Formosa No. 14was launched in 2017. Top notes are Tangerine, Lemon and Green Grass; middle notes are Thyme, Mint, Basil and Wormwood; base notes are Birch, Patchouli, Cedar, Sandalwood and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Hug-Me-No-10-49132',
        'Hug Me No. 10 LA CHANTEE',
        'Hug',
        'for women',
        NULL,
        NULL,
        'Raspberry, Fig, Black Currant and Grapefruit',
        'Rose and Violet',
        'Pine Tree, Cedar and White Musk',
        'fruity,woody,sweet,rose,aromatic',
        'Hug Me No. 10byLA CHANTEEis a fragrance for women.Hug Me No. 10was launched in 2017. Top notes are Raspberry, Fig, Black Currant and Grapefruit; middle notes are Rose and Violet; base notes are Pine Tree, Cedar and White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Monte-Carlo-No-9-49131',
        'Monte Carlo No. 9 LA CHANTEE',
        'Monte',
        'for women',
        NULL,
        NULL,
        'Orange and Orange Blossom',
        'Gardenia, Jasmine, Rose and Ylang-Ylang',
        'Patchouli and White Musk',
        'white floral,citrus,patchouli,woody,sweet',
        'Monte Carlo No. 9byLA CHANTEEis a fragrance for women.Monte Carlo No. 9was launched in 2017. Top notes are Orange and Orange Blossom; middle notes are Gardenia, Jasmine, Rose and Ylang-Ylang; base notes are Patchouli and White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Provence-Rose-No-1-48812',
        'Provence Rose No. 1 LA CHANTEE',
        'Provence',
        'for women',
        NULL,
        NULL,
        'Sea Notes and Raspberry',
        'Rose, Iris and Peony',
        'White Musk, White Woods and Amber',
        'rose,marine,woody,powdery,floral',
        'Provence Rose No. 1byLA CHANTEEis a Floral fragrance for women.Provence Rose No. 1was launched in 2017. Top notes are Sea Notes and Raspberry; middle notes are Rose, Iris and Peony; base notes are White Musk, White Woods and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Revel-No-12-49135',
        'Revel No. 12 LA CHANTEE',
        'Revel',
        'for women',
        NULL,
        NULL,
        'Pink Pepper and Raspberry',
        'Rose, Gardenia and Magnolia',
        'White Musk',
        'rose,fruity,sweet,musky,soft spicy',
        'Revel No. 12byLA CHANTEEis a fragrance for women.Revel No. 12was launched in 2017. Top notes are Pink Pepper and Raspberry; middle notes are Rose, Gardenia and Magnolia; base note is White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Secret-Garden-No-5-49126',
        'Secret Garden No. 5 LA CHANTEE',
        'Secret',
        'for women',
        NULL,
        NULL,
        'Pear, Apple and Bergamot',
        'Jasmine, Rose and Ylang-Ylang',
        'Sandalwood, Vanilla and Musk',
        'fruity,white floral,fresh,powdery,sweet',
        'Secret Garden No. 5byLA CHANTEEis a fragrance for women.Secret Garden No. 5was launched in 2017. Top notes are Pear, Apple and Bergamot; middle notes are Jasmine, Rose and Ylang-Ylang; base notes are Sandalwood, Vanilla and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Spring-of-Paris-No-4-49123',
        'Spring of Paris No. 4 LA CHANTEE',
        'Spring',
        'for women',
        NULL,
        NULL,
        'Apple, Bergamot, Black Currant and Green Grass',
        'Rose, Jasmine and Ylang-Ylang',
        'Vanilla and Musk',
        'fruity,green,rose,fresh,floral',
        'Spring of Paris No. 4byLA CHANTEEis a fragrance for women.Spring of Paris No. 4was launched in 2017. Top notes are Apple, Bergamot, Black Currant and Green Grass; middle notes are Rose, Jasmine and Ylang-Ylang; base notes are Vanilla and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sweet-Heart-No-22-49183',
        'Sweet Heart No. 22 LA CHANTEE',
        'Sweet',
        'for women',
        NULL,
        NULL,
        'Bergamot, Pink Pepper and Orange',
        'Peach and Jasmine',
        'Patchouli, Caramel and Violet',
        'citrus,sweet,caramel,patchouli,woody',
        'Sweet Heart No. 22byLA CHANTEEis a fragrance for women.Sweet Heart No. 22was launched in 2017. Top notes are Bergamot, Pink Pepper and Orange; middle notes are Peach and Jasmine; base notes are Patchouli, Caramel and Violet.',
        NULL,
        NULL,
        NULL
      ),
(
        '3-Rosa-14003',
        '3 Rosa L''Erbolario',
        '3',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Angelica, Watery Notes and Coriander',
        'Rose, Hollyhock, White Lily, Jasmine Sambac, Karo Karounde and Ylang-Ylang',
        'Moss, Ambrette (Musk Mallow), Sandalwood, Virginia Cedar and Amber',
        'rose,soft spicy,musky,floral,white floral',
        '3 RosabyL''Erbolariois a Floral fragrance for women.3 Rosawas launched in 2011. Top notes are Pink Pepper, Angelica, Watery Notes and Coriander; middle notes are Rose, Hollyhock, White Lily, Jasmine Sambac, Karo Karounde and Ylang-Ylang; base notes are Moss, Ambrette (Musk Mallow), Sandalwood, Virginia Cedar and Amber.',
        3.82,
        259,
        NULL
      ),
(
        'Acacia-4451',
        'Acacia L''Erbolario',
        'Acacia',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,sweet,honey',
        'AcaciabyL''Erbolariois a Floral fragrance for women.',
        4.19,
        52,
        NULL
      ),
(
        'Accordo-Arancio-28195',
        'Accordo Arancio L''Erbolario',
        'Accordo',
        'for women and men',
        NULL,
        NULL,
        'Bitter Orange, Mandarin Orange, Lemon and Ylang-Ylang',
        'Petitgrain, Plum, Jasmine and Thyme',
        'Vanilla, Amber, Cedar and Patchouli',
        'citrus,woody,aromatic',
        'Accordo AranciobyL''Erbolariois a Citrus Gourmand fragrance for women and men.Accordo Aranciowas launched in 2014. Top notes are Bitter Orange, Mandarin Orange, Lemon and Ylang-Ylang; middle notes are Petitgrain, Plum, Jasmine and Thyme; base notes are Vanilla, Amber, Cedar and Patchouli.',
        3.89,
        280,
        NULL
      );
