
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Christian-Lacroix-360',
        'Christian Lacroix Christian Lacroix',
        'Christian',
        'for women',
        NULL,
        'Sophia Grojsman',
        'Tarragon, Carnation, Peach, Freesia and Brazilian Rosewood',
        'Heliotrope, Ylang-Ylang, Jasmine and Lily-of-the-Valley',
        'Benzoin, Vanilla, Tonka Bean and Sandalwood',
        'floral,vanilla,warm spicy,powdery,aromatic',
        'Christian LacroixbyChristian Lacroixis a Floral fragrance for women.Christian Lacroixwas launched in 1999. The nose behind this fragrance is Sophia Grojsman. Top notes are Tarragon, Carnation, Peach, Freesia and Brazilian Rosewood; middle notes are Heliotrope, Ylang-Ylang, Jasmine and Lily-of-the-Valley; base notes are Benzoin, Vanilla, Tonka Bean and Sandalwood.',
        4.13,
        564,
        NULL
      ),
(
        'Eau-Florale-361',
        'Eau Florale Christian Lacroix',
        'Eau',
        'for women',
        NULL,
        'Beatrice Piquet',
        'Tangerine, Violet Leaf and Bergamot',
        'Gardenia, Lily-of-the-Valley, Cyclamen and Tuberose',
        'Iris, Sandalwood and Cedar',
        'white floral,citrus,woody,fresh,floral',
        'Eau FloralebyChristian Lacroixis a Floral fragrance for women.Eau Floralewas launched in 2001. Eau Florale was created by Nathalie Lorson and Beatrice Piquet. Top notes are Tangerine, Violet Leaf and Bergamot; middle notes are Gardenia, Lily-of-the-Valley, Cyclamen and Tuberose; base notes are Iris, Sandalwood and Cedar.',
        4.22,
        197,
        NULL
      ),
(
        'Eau-Florale-Bleue-3475',
        'Eau Florale Bleue Christian Lacroix',
        'Eau',
        'for women',
        NULL,
        NULL,
        'Green Apple, Clementine, Mandarin Orange, Black Currant and Violet',
        'Gardenia, Cyclamen and Tuberose',
        'Cypress, Iris and Sandalwood',
        'fruity,woody,aromatic,fresh,white floral',
        'Eau Florale BleuebyChristian Lacroixis a Floral Fruity fragrance for women.Eau Florale Bleuewas launched in 2006. Top notes are Green Apple, Clementine, Mandarin Orange, Black Currant and Violet; middle notes are Gardenia, Cyclamen and Tuberose; base notes are Cypress, Iris and Sandalwood.',
        3.93,
        44,
        NULL
      ),
(
        'Noir-1017',
        'Noir Christian Lacroix',
        'Noir',
        'for men',
        NULL,
        'Pascal Gaurin',
        'Ginger, Saffron and Licorice',
        'Cardamom, Orris Root, Ambergris, Incense, Iris and Moss',
        'White Cedar Extract, Vetiver, Musk, Aromatic Notes and Driftwood',
        'warm spicy,woody,aromatic,powdery,earthy',
        'NoirbyChristian Lacroixis a Woody Aromatic fragrance for men. Noir was created by Pascal Gaurin and Yves Cassar. Top notes are Ginger, Saffron and Licorice; middle notes are Cardamom, Orris Root, Ambergris, Incense, Iris and Moss; base notes are White Cedar Extract, Vetiver, Musk, Aromatic Notes and Driftwood.',
        3.59,
        69,
        NULL
      ),
(
        'Rouge-1016',
        'Rouge Christian Lacroix',
        'Rouge',
        'for women',
        NULL,
        'Carlos Benaim',
        'White Pepper, Red Peony and Orange',
        'Lotus and Osmanthus',
        'Patchouli, Cashmere Wood and Musk',
        'floral,fresh spicy,woody,patchouli,warm spicy',
        'RougebyChristian Lacroixis a Chypre Floral fragrance for women.Rougewas launched in 2007. Rouge was created by Laurent Le Guernec and Carlos Benaim. Top notes are White Pepper, Red Peony and Orange; middle notes are Lotus and Osmanthus; base notes are Patchouli, Cashmere Wood and Musk.',
        3.64,
        321,
        NULL
      ),
(
        'Tumulte-362',
        'Tumulte Christian Lacroix',
        'Tumulte',
        'for women',
        NULL,
        'Francoise Caron',
        'Rose, Freesia and Mandarin Orange',
        'Rose, Heliotrope and Iris',
        'Tonka Bean, Patchouli and Musk',
        'rose,floral,vanilla,powdery,patchouli',
        'TumultebyChristian Lacroixis a Amber Floral fragrance for women.Tumultewas launched in 2005. The nose behind this fragrance is Francoise Caron. Top notes are Rose, Freesia and Mandarin Orange; middle notes are Rose, Heliotrope and Iris; base notes are Tonka Bean, Patchouli and Musk.',
        3.84,
        767,
        NULL
      ),
(
        'Tumulte-pour-Homme-363',
        'Tumulte pour Homme Christian Lacroix',
        'Tumulte',
        'for men',
        NULL,
        'Natalie Gracia-Cetto',
        'Juniper Berries, Bay Leaf and Plum',
        'Violet and Geranium',
        'Cedar, Sandalwood, Labdanum and Patchouli',
        'woody,aromatic,fresh spicy,powdery',
        'Tumulte pour HommebyChristian Lacroixis a Woody Spicy fragrance for men.Tumulte pour Hommewas launched in 2005. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Juniper Berries, Bay Leaf and Plum; middle notes are Violet and Geranium; base notes are Cedar, Sandalwood, Labdanum and Patchouli.',
        4.38,
        660,
        NULL
      ),
(
        '713-33035',
        '713 Chris Adams',
        '713',
        'for men',
        NULL,
        NULL,
        'Lemon, Cardamom and Anise',
        'Geranium and Cloves',
        'Patchouli, Sandalwood and Amber',
        'warm spicy,aromatic,woody,amber,citrus',
        '713byChris Adamsis a Citrus fragrance for men. Top notes are Lemon, Cardamom and Anise; middle notes are Geranium and Cloves; base notes are Patchouli, Sandalwood and Amber.',
        4.5,
        2,
        NULL
      ),
(
        'Ace-33036',
        'Ace Chris Adams',
        'Ace',
        'for men',
        NULL,
        NULL,
        'Plum, Bergamot and Grapefruit',
        'Jasmine and Rose',
        'Cedar, Amber, Vetiver and Musk',
        'woody,white floral,fruity,rose,citrus',
        'AcebyChris Adamsis a Woody Floral Musk fragrance for men. Top notes are Plum, Bergamot and Grapefruit; middle notes are Jasmine and Rose; base notes are Cedar, Amber, Vetiver and Musk.',
        4.44,
        9,
        NULL
      ),
(
        'Active-Man-33037',
        'Active Man Chris Adams',
        'Active',
        'for men',
        NULL,
        NULL,
        'Ozonic notes, Citruses and Bergamot',
        'Lavender, Floral Notes, Rose and Jasmine',
        'Sandalwood, Musk and Cedar',
        'ozonic,lavender,woody,citrus,floral',
        'Active ManbyChris Adamsis a Aromatic Fougere fragrance for men. Top notes are Ozonic notes, Citruses and Bergamot; middle notes are Lavender, Floral Notes, Rose and Jasmine; base notes are Sandalwood, Musk and Cedar.',
        3.78,
        41,
        NULL
      ),
(
        'Active-Woman-33038',
        'Active Woman Chris Adams',
        'Active',
        'for women',
        NULL,
        NULL,
        'Orange, Grapefruit and Bergamot',
        'Rose, Fruity Notes and Jasmine',
        'Patchouli, Sandalwood, Tonka Bean, White Musk and Vanilla Sugar',
        'citrus,woody,rose,patchouli,sweet',
        'Active WomanbyChris Adamsis a Floral Woody Musk fragrance for women. Top notes are Orange, Grapefruit and Bergamot; middle notes are Rose, Fruity Notes and Jasmine; base notes are Patchouli, Sandalwood, Tonka Bean, White Musk and Vanilla Sugar.',
        3.74,
        34,
        NULL
      ),
(
        'Belle-Noir-33039',
        'Belle Noir Chris Adams',
        'Belle',
        'for women',
        NULL,
        NULL,
        'Apricot and Pear',
        'Tuberose, Jasmine and Lily',
        'Sandalwood, Vanilla, Almond and Musk',
        'white floral,tuberose,powdery,fruity,woody',
        'Belle NoirbyChris Adamsis a Floral Woody Musk fragrance for women. Top notes are Apricot and Pear; middle notes are Tuberose, Jasmine and Lily; base notes are Sandalwood, Vanilla, Almond and Musk.',
        4.25,
        8,
        NULL
      ),
(
        'Belle-Violette-33040',
        'Belle Violette Chris Adams',
        'Belle',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Melon, Pink Peony and Lemon',
        'Jasmine, Rhubarb and Cacao',
        'Amber, Patchouli, Incense and Vanilla',
        'amber,fresh,floral,white floral,citrus',
        'Belle ViolettebyChris Adamsis a Amber fragrance for women. Top notes are Mandarin Orange, Melon, Pink Peony and Lemon; middle notes are Jasmine, Rhubarb and Cacao; base notes are Amber, Patchouli, Incense and Vanilla.',
        3.92,
        12,
        NULL
      ),
(
        'Black-Label-33041',
        'Black Label Chris Adams',
        'Black',
        'for men',
        NULL,
        NULL,
        'Bergamot, Mandarin Orange, Lemon, Pepper and Green Notes',
        'Rose and Lily-of-the-Valley',
        'Sandalwood, Oakmoss and Amber',
        'citrus,woody,fresh spicy,rose,green',
        'Black LabelbyChris Adamsis a Citrus fragrance for men. Top notes are Bergamot, Mandarin Orange, Lemon, Pepper and Green Notes; middle notes are Rose and Lily-of-the-Valley; base notes are Sandalwood, Oakmoss and Amber.',
        4.5,
        8,
        NULL
      ),
(
        'Black-Shadow-33042',
        'Black Shadow Chris Adams',
        'Black',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot and Basil',
        'Lavender, Geranium, Wormwood, Ylang-Ylang, Sage and Cinnamon',
        'Musk, Oakmoss and Coumarin',
        'aromatic,fresh spicy,citrus,herbal,lavender',
        'Black ShadowbyChris Adamsis a Citrus Aromatic fragrance for men. Top notes are Lemon, Bergamot and Basil; middle notes are Lavender, Geranium, Wormwood, Ylang-Ylang, Sage and Cinnamon; base notes are Musk, Oakmoss and Coumarin.',
        4.17,
        18,
        NULL
      ),
(
        'CA-Accord-33043',
        'CA Accord Chris Adams',
        'CA',
        'for men',
        NULL,
        NULL,
        'Rosemary, Grapefruit and Bergamot',
        'Lavender and Ginger',
        'Cedar, Vetiver and Sandalwood',
        'woody,aromatic,fresh spicy,citrus,warm spicy',
        'CA AccordbyChris Adamsis a Citrus Aromatic fragrance for men. Top notes are Rosemary, Grapefruit and Bergamot; middle notes are Lavender and Ginger; base notes are Cedar, Vetiver and Sandalwood.',
        4.75,
        4,
        NULL
      ),
(
        'CA-Man-33049',
        'CA Man Chris Adams',
        'CA',
        'for men',
        NULL,
        NULL,
        'Peach, Pineapple, Strawberry, Bergamot, Black Pepper, Nutmeg, Green Notes, Apple, Plum, Mint, Cardamom, Thyme, Lime, Lemon and Grapefruit',
        'Cinnamon, Rose, Freesia, Iris, Jasmine, Cyclamen and Gardenia',
        'Cedar, Sandalwood, Vanilla and White Musk',
        'fruity,fresh spicy,citrus,aromatic,sweet',
        'CA ManbyChris Adamsis a Woody Floral Musk fragrance for men. Top notes are Peach, Pineapple, Strawberry, Bergamot, Black Pepper, Nutmeg, Green Notes, Apple, Plum, Mint, Cardamom, Thyme, Lime, Lemon and Grapefruit; middle notes are Cinnamon, Rose, Freesia, Iris, Jasmine, Cyclamen and Gardenia; base notes are Cedar, Sandalwood, Vanilla and White Musk.',
        3.65,
        17,
        NULL
      ),
(
        'CA-Woman-33059',
        'CA Woman Chris Adams',
        'CA',
        'for women',
        NULL,
        NULL,
        'Plum, Apple, Pineapple, Melon, Herbal Notes, Passionfruit and White Peach',
        'Jasmine, Pepper, Peony and Rose',
        'Amber, Woody Notes, Iris, Sandalwood and White Musk',
        'fruity,sweet,fresh,amber,powdery',
        'CA WomanbyChris Adamsis a Floral Fruity fragrance for women. Top notes are Plum, Apple, Pineapple, Melon, Herbal Notes, Passionfruit and White Peach; middle notes are Jasmine, Pepper, Peony and Rose; base notes are Amber, Woody Notes, Iris, Sandalwood and White Musk.',
        3.33,
        3,
        NULL
      ),
(
        'Catch-Me-33060',
        'Catch Me Chris Adams',
        'Catch',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon and Basil',
        'Geranium, Ylang-Ylang, Lavender, Wormwood, Sage and Cinnamon',
        'Musk, Oakmoss and Coumarin',
        'aromatic,fresh spicy,citrus,herbal,warm spicy',
        'Catch MebyChris Adamsis a Aromatic fragrance for men. Top notes are Bergamot, Lemon and Basil; middle notes are Geranium, Ylang-Ylang, Lavender, Wormwood, Sage and Cinnamon; base notes are Musk, Oakmoss and Coumarin.',
        3.62,
        8,
        NULL
      ),
(
        'Choice-33061',
        'Choice Chris Adams',
        'Choice',
        'for women',
        NULL,
        NULL,
        'Cloves and Lemon',
        'Lily-of-the-Valley, Ylang-Ylang, Water Violet, Rose, Water Heliotrope, Jasmine, Water Lily and Watery Notes',
        'Musk',
        'white floral,warm spicy,powdery,fresh,floral',
        'ChoicebyChris Adamsis a Floral fragrance for women. Top notes are Cloves and Lemon; middle notes are Lily-of-the-Valley, Ylang-Ylang, Water Violet, Rose, Water Heliotrope, Jasmine, Water Lily and Watery Notes; base note is Musk.',
        3.67,
        6,
        NULL
      ),
(
        'Classic-pour-Femme-33044',
        'Classic pour Femme Chris Adams',
        'Classic',
        'for women',
        NULL,
        NULL,
        'Fruity Notes and Pear',
        'Rose, Water Lily and Peony',
        'Woody Notes and Musk',
        'floral,rose,fresh,woody,fruity',
        'Classic pour FemmebyChris Adamsis a Woody Floral Musk fragrance for women. Top notes are Fruity Notes and Pear; middle notes are Rose, Water Lily and Peony; base notes are Woody Notes and Musk.',
        3.29,
        7,
        NULL
      ),
(
        'Classic-pour-Homme-33045',
        'Classic pour Homme Chris Adams',
        'Classic',
        'for men',
        NULL,
        NULL,
        'Juniper, Citruses, Spicy Notes and Cloves',
        'Lavender, Sea Notes, Eucalyptus, Sage, Star Anise and Floral Notes',
        'Patchouli, White Musk, Cedar, Sandalwood and Tonka Bean',
        'woody,aromatic,warm spicy,powdery,musky',
        'Classic pour HommebyChris Adamsis a Woody Aromatic fragrance for men. Top notes are Juniper, Citruses, Spicy Notes and Cloves; middle notes are Lavender, Sea Notes, Eucalyptus, Sage, Star Anise and Floral Notes; base notes are Patchouli, White Musk, Cedar, Sandalwood and Tonka Bean.',
        3.79,
        24,
        NULL
      ),
(
        'Club-Ricco-33062',
        'Club Ricco Chris Adams',
        'Club',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Apple and Violet Leaf',
        'Cardamom, Geranium and Nutmeg',
        'Cedar, Amber and Musk',
        'fresh spicy,aromatic,warm spicy,woody,citrus',
        'Club RiccobyChris Adamsis a Woody Spicy fragrance for men. Top notes are Grapefruit, Apple and Violet Leaf; middle notes are Cardamom, Geranium and Nutmeg; base notes are Cedar, Amber and Musk.',
        3.33,
        3,
        NULL
      ),
(
        'Conspiracy-33063',
        'Conspiracy Chris Adams',
        'Conspiracy',
        'for women',
        NULL,
        NULL,
        'Peach, Bergamot and Mandarin Orange',
        'Lily, Tuberose, Rose and Carnation',
        'Vanilla, Sandalwood, Musk and Tonka Bean',
        'white floral,citrus,tuberose,vanilla,powdery',
        'ConspiracybyChris Adamsis a Floral Fruity fragrance for women. Top notes are Peach, Bergamot and Mandarin Orange; middle notes are Lily, Tuberose, Rose and Carnation; base notes are Vanilla, Sandalwood, Musk and Tonka Bean.',
        4.67,
        3,
        NULL
      ),
(
        'Dispute-for-Men-33067',
        'Dispute for Men Chris Adams',
        'Dispute',
        'for men',
        NULL,
        NULL,
        'Orange, Bergamot, Grapefruit and Herbal Notes',
        'Pineapple, Water Lily, Green Apple, Melon and Watermelon',
        'Patchouli Leaf, Cedar, Sandalwood, Vanilla, Benzoin and Musk',
        'citrus,sweet,fruity,woody,aquatic',
        'Dispute for MenbyChris Adamsis a Amber Fougere fragrance for men. Top notes are Orange, Bergamot, Grapefruit and Herbal Notes; middle notes are Pineapple, Water Lily, Green Apple, Melon and Watermelon; base notes are Patchouli Leaf, Cedar, Sandalwood, Vanilla, Benzoin and Musk.',
        3,
        2,
        NULL
      ),
(
        'Dispute-for-Women-33068',
        'Dispute for Women Chris Adams',
        'Dispute',
        'for women',
        NULL,
        NULL,
        'Citruses and Peony',
        'Osmanthus, Fruity Notes and Rose',
        'Sandalwood, Patchouli Leaf and Musk',
        'floral,fruity,fresh,citrus,rose',
        'Dispute for WomenbyChris Adamsis a Floral Fruity fragrance for women. Top notes are Citruses and Peony; middle notes are Osmanthus, Fruity Notes and Rose; base notes are Sandalwood, Patchouli Leaf and Musk.',
        4.25,
        4,
        NULL
      ),
(
        'Dolby-Man-33070',
        'Dolby Man Chris Adams',
        'Dolby',
        'for men',
        NULL,
        NULL,
        'Bergamot, Tropical Fruits, Wormwood and Basil',
        'Damask Rose, Cinnamon, Lavender and Geranium',
        'Amber, Sandalwood, Patchouli and Oakmoss',
        'fresh spicy,aromatic,warm spicy,citrus,woody',
        'Dolby ManbyChris Adamsis a Woody fragrance for men. Top notes are Bergamot, Tropical Fruits, Wormwood and Basil; middle notes are Damask Rose, Cinnamon, Lavender and Geranium; base notes are Amber, Sandalwood, Patchouli and Oakmoss.',
        3.96,
        24,
        NULL
      ),
(
        'Dolby-Woman-33071',
        'Dolby Woman Chris Adams',
        'Dolby',
        'for women',
        NULL,
        NULL,
        'Peach, Mignonette, Aldehydes, Black Currant, Melon and Pineapple',
        'Lotus, Orange Blossom, Ylang-Ylang, Jasmine, Geranium, Lily-of-the-Valley, Rose and Iris',
        'Honey, Cedar and White Musk',
        'sweet,floral,fruity,honey,white floral',
        'Dolby WomanbyChris Adamsis a Floral Fruity fragrance for women. Top notes are Peach, Mignonette, Aldehydes, Black Currant, Melon and Pineapple; middle notes are Lotus, Orange Blossom, Ylang-Ylang, Jasmine, Geranium, Lily-of-the-Valley, Rose and Iris; base notes are Honey, Cedar and White Musk.',
        4.5,
        4,
        NULL
      ),
(
        'Dreamz-Man-33046',
        'Dreamz Man Chris Adams',
        'Dreamz',
        'for men',
        NULL,
        NULL,
        'Lemon and Bergamot',
        'Jasmine',
        'Vetiver, Leather and Musk',
        'citrus,aromatic,fresh spicy,woody',
        'Dreamz ManbyChris Adamsis a Citrus fragrance for men. Top notes are Lemon and Bergamot; middle note is Jasmine; base notes are Vetiver, Leather and Musk.',
        4,
        22,
        NULL
      ),
(
        'Dreamz-Woman-33047',
        'Dreamz Woman Chris Adams',
        'Dreamz',
        'for women',
        NULL,
        NULL,
        'Neroli, Lemon and Raspberry',
        'Jasmine and Gardenia',
        'Honey and Patchouli',
        'honey,white floral,sweet,floral,citrus',
        'Dreamz WomanbyChris Adamsis a fragrance for women. Top notes are Neroli, Lemon and Raspberry; middle notes are Jasmine and Gardenia; base notes are Honey and Patchouli.',
        3.45,
        29,
        NULL
      ),
(
        'DVD-33064',
        'DVD Chris Adams',
        'DVD',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon, Tea, Pink Pepper, Cardamom and Coconut',
        'Coriander, Juniper, Cloves, Rose, Jasmine and Neroli',
        'Cedar, Sandalwood, Tonka Bean, Vanilla and Musk',
        'aromatic,woody,warm spicy,citrus,vanilla',
        'DVDbyChris Adamsis a Woody Aquatic fragrance for men. Top notes are Bergamot, Lemon, Tea, Pink Pepper, Cardamom and Coconut; middle notes are Coriander, Juniper, Cloves, Rose, Jasmine and Neroli; base notes are Cedar, Sandalwood, Tonka Bean, Vanilla and Musk.',
        4,
        2,
        NULL
      ),
(
        'DX-77-Man-33065',
        'DX 77 Man Chris Adams',
        'DX',
        'for men',
        NULL,
        NULL,
        'Apple, Citruses, Ginger, Bergamot, Galbanum and Melon',
        'Spicy Notes, Thyme, Mint, Lavender, Geranium, Nutmeg and Cloves',
        'Vetiver, Musk, Cinnamon, Sandalwood and Amber',
        'aromatic,warm spicy,fresh spicy,green,citrus',
        'DX 77 ManbyChris Adamsis a Woody Aromatic fragrance for men. Top notes are Apple, Citruses, Ginger, Bergamot, Galbanum and Melon; middle notes are Spicy Notes, Thyme, Mint, Lavender, Geranium, Nutmeg and Cloves; base notes are Vetiver, Musk, Cinnamon, Sandalwood and Amber.',
        3.42,
        12,
        NULL
      ),
(
        'DX-77-Woman-33066',
        'DX 77 Woman Chris Adams',
        'DX',
        'for men',
        NULL,
        NULL,
        'Passionfruit, Apple and Melon',
        'Magnolia',
        'Patchouli, Musk and Amber',
        'patchouli,woody,fruity,warm spicy,fresh',
        'DX 77 WomanbyChris Adamsis a Floral Fruity fragrance for men. Top notes are Passionfruit, Apple and Melon; middle note is Magnolia; base notes are Patchouli, Musk and Amber.',
        3,
        2,
        NULL
      ),
(
        'Fancy-33072',
        'Fancy Chris Adams',
        'Fancy',
        'for women',
        NULL,
        NULL,
        'Plum, Lemon, Pineapple, Apple Tree, Peach and Raspberry',
        'Ylang-Ylang, Rose, Violet, Jasmine and Orange Blossom',
        'Sandalwood, White Musk and Oakmoss',
        'fruity,sweet,woody,powdery,yellow floral',
        'FancybyChris Adamsis a Citrus Aromatic fragrance for women. Top notes are Plum, Lemon, Pineapple, Apple Tree, Peach and Raspberry; middle notes are Ylang-Ylang, Rose, Violet, Jasmine and Orange Blossom; base notes are Sandalwood, White Musk and Oakmoss.',
        3.62,
        13,
        NULL
      ),
(
        'Fiore-33073',
        'Fiore Chris Adams',
        'Fiore',
        'for women',
        NULL,
        NULL,
        'Orange and Mandarin Orange',
        'Ylang-Ylang, Rose and Jasmine',
        'Patchouli, Cedar and Musk',
        'citrus,woody,yellow floral,white floral,sweet',
        'FiorebyChris Adamsis a Woody Floral Musk fragrance for women. Top notes are Orange and Mandarin Orange; middle notes are Ylang-Ylang, Rose and Jasmine; base notes are Patchouli, Cedar and Musk.',
        5,
        1,
        NULL
      ),
(
        'First-Impression-Blue-33075',
        'First Impression Blue Chris Adams',
        'First',
        'for men',
        NULL,
        NULL,
        'Orange, Lemon, Mandarin Orange and Bergamot',
        'Lavender, Rose and Lily',
        'Vanilla, Sandalwood, Amber, Tonka Bean and Musk',
        'citrus,vanilla,lavender,powdery,amber',
        'First Impression BluebyChris Adamsis a Woody fragrance for men. Top notes are Orange, Lemon, Mandarin Orange and Bergamot; middle notes are Lavender, Rose and Lily; base notes are Vanilla, Sandalwood, Amber, Tonka Bean and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'First-Impression-Green-33076',
        'First Impression Green Chris Adams',
        'First',
        'for men',
        NULL,
        NULL,
        'Orange, Lemon and Mandarin Orange',
        'Apple and Pear',
        'Cedar, Patchouli, Amber, Oakmoss and Musk',
        'citrus,woody,fruity,earthy,amber',
        'First Impression GreenbyChris Adamsis a Woody fragrance for men. Top notes are Orange, Lemon and Mandarin Orange; middle notes are Apple and Pear; base notes are Cedar, Patchouli, Amber, Oakmoss and Musk.',
        4,
        1,
        NULL
      ),
(
        'Iconic-Men-33078',
        'Iconic Men Chris Adams',
        'Iconic',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lemon and Mandarin Orange',
        'Anise, Thyme and Geranium',
        'Musk, Patchouli, Tobacco and Cedar',
        'citrus,musky,aromatic,fresh spicy,powdery',
        'Iconic MenbyChris Adamsis a Chypre fragrance for men. Top notes are Bergamot, Lemon and Mandarin Orange; middle notes are Anise, Thyme and Geranium; base notes are Musk, Patchouli, Tobacco and Cedar.',
        4,
        4,
        NULL
      ),
(
        'Ink-Pink-33079',
        'Ink Pink Chris Adams',
        'Ink',
        'for women',
        NULL,
        NULL,
        'Bergamot, Fruity Notes, Caramel, Pineapple and White Peach',
        'Violet, Rose, Ylang-Ylang and Orange Blossom',
        'Musk, Patchouli, Tonka Bean and Sugar',
        'powdery,violet,musky,sweet,citrus',
        'Ink PinkbyChris Adamsis a Floral Fruity Gourmand fragrance for women. Top notes are Bergamot, Fruity Notes, Caramel, Pineapple and White Peach; middle notes are Violet, Rose, Ylang-Ylang and Orange Blossom; base notes are Musk, Patchouli, Tonka Bean and Sugar.',
        2.67,
        3,
        NULL
      ),
(
        'Intense-33080',
        'Intense Chris Adams',
        'Intense',
        'for women',
        NULL,
        NULL,
        'Bergamot, Apple, Lemon and Juniper Berries',
        'Floral Notes, Rose, Violet Leaf and Pine Tree',
        'Amber, Musk, Sandalwood and Cedar',
        'woody,aromatic,citrus,powdery,floral',
        'IntensebyChris Adamsis a Woody Aromatic fragrance for women. Top notes are Bergamot, Apple, Lemon and Juniper Berries; middle notes are Floral Notes, Rose, Violet Leaf and Pine Tree; base notes are Amber, Musk, Sandalwood and Cedar.',
        NULL,
        NULL,
        NULL
      ),
(
        'J-aime-33081',
        'J''aime Chris Adams',
        'J''aime',
        'for women',
        NULL,
        NULL,
        'Strawberry, Pink Pepper, Peach, Raspberry, Violet Leaf and Plum',
        'Orchid, Rose, Iris, Jasmine, Freesia, Lily and Ylang-Ylang',
        'Sandalwood, Amber, Musk, Benzoin, Incense and Cedar',
        'fruity,sweet,powdery,amber,woody',
        'J''aimebyChris Adamsis a Floral fragrance for women. Top notes are Strawberry, Pink Pepper, Peach, Raspberry, Violet Leaf and Plum; middle notes are Orchid, Rose, Iris, Jasmine, Freesia, Lily and Ylang-Ylang; base notes are Sandalwood, Amber, Musk, Benzoin, Incense and Cedar.',
        4.4,
        5,
        NULL
      ),
(
        'Kaotic-33082',
        'Kaotic Chris Adams',
        'Kaotic',
        'for men',
        NULL,
        NULL,
        'Lavender, Pepper, Citruses and Lemon',
        'Orange Blossom and Floral Notes',
        'Cedar and Patchouli',
        'citrus,fresh spicy,woody,white floral,lavender',
        'KaoticbyChris Adamsis a Aromatic fragrance for men. Top notes are Lavender, Pepper, Citruses and Lemon; middle notes are Orange Blossom and Floral Notes; base notes are Cedar and Patchouli.',
        2.67,
        3,
        NULL
      ),
(
        'Kaotic-Intense-33084',
        'Kaotic Intense Chris Adams',
        'Kaotic',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Orange, Cardamom and Pink Pepper',
        'Iris, Floral Notes, Vetiver and Cedar',
        'Sandalwood, Amber, Tonka Bean and Musk',
        'woody,powdery,iris,citrus,aromatic',
        'Kaotic IntensebyChris Adamsis a Woody Spicy fragrance for men. Top notes are Mandarin Orange, Orange, Cardamom and Pink Pepper; middle notes are Iris, Floral Notes, Vetiver and Cedar; base notes are Sandalwood, Amber, Tonka Bean and Musk.',
        2.67,
        3,
        NULL
      ),
(
        'Legend-Woman-33048',
        'Legend Woman Chris Adams',
        'Legend',
        'for women',
        NULL,
        NULL,
        'Citruses',
        'Orange, Rose and Jasmine',
        'Cedar, Vetiver, Patchouli and Vanilla',
        'citrus,woody,white floral,rose,vanilla',
        'Legend WomanbyChris Adamsis a Floral Woody Musk fragrance for women. Top note is Citruses; middle notes are Orange, Rose and Jasmine; base notes are Cedar, Vetiver, Patchouli and Vanilla.',
        4.33,
        3,
        NULL
      ),
(
        'Let-s-Imagine-33085',
        'Let''s Imagine Chris Adams',
        'Let''s',
        'for men',
        NULL,
        NULL,
        'Cinnamon',
        'Lavender',
        'Tonka Bean, Patchouli, Vanilla, Musk, Cedar and Sandalwood',
        'warm spicy,lavender,cinnamon,woody,vanilla',
        'Let''s ImaginebyChris Adamsis a Aromatic fragrance for men. Top note is Cinnamon; middle note is Lavender; base notes are Tonka Bean, Patchouli, Vanilla, Musk, Cedar and Sandalwood.',
        3.83,
        6,
        NULL
      ),
(
        'MP-Pour-Homme-33086',
        'MP Pour Homme Chris Adams',
        'MP',
        'for men',
        NULL,
        NULL,
        'Orange and Grapefruit',
        'Flint and Mineral notes',
        'Benzoin, Woody Notes and Moss',
        'amber,citrus,mineral,warm spicy,woody',
        'MP Pour HommebyChris Adamsis a Woody fragrance for men. Top notes are Orange and Grapefruit; middle notes are Flint and Mineral notes; base notes are Benzoin, Woody Notes and Moss.',
        4,
        3,
        NULL
      ),
(
        'New-Era-33087',
        'New Era Chris Adams',
        'New',
        'for women',
        NULL,
        NULL,
        'Rose and Raspberry',
        'Jasmine, Peony and Black Currant',
        'Cedar and Musk',
        'rose,floral,white floral,woody,fruity',
        'New ErabyChris Adamsis a Amber fragrance for women. Top notes are Rose and Raspberry; middle notes are Jasmine, Peony and Black Currant; base notes are Cedar and Musk.',
        4.67,
        3,
        NULL
      ),
(
        'New-Lifetime-Pour-Homme-57907',
        'New Lifetime Pour Homme Chris Adams',
        'New',
        'for men',
        NULL,
        NULL,
        'Bergamot, Italian Lemon, Lavender, Mandarin Orange and Watery Notes',
        'Orange Blossom and Jasmine',
        'Musk, Sandalwood, Praline and Patchouli',
        'citrus,white floral,woody,sweet,aromatic',
        'New Lifetime Pour HommebyChris Adamsis a Amber Fougere fragrance for men.New Lifetime Pour Hommewas launched in 2018. Top notes are Bergamot, Italian Lemon, Lavender, Mandarin Orange and Watery Notes; middle notes are Orange Blossom and Jasmine; base notes are Musk, Sandalwood, Praline and Patchouli.',
        5,
        2,
        NULL
      ),
(
        'Niche-for-Men-33088',
        'Niche for Men Chris Adams',
        'Niche',
        'for men',
        NULL,
        NULL,
        'Bergamot, Mandarin Orange, Mint and Bitter Orange',
        'Jasmine, Orange Blossom and Sea water',
        'White Musk, Woody Notes and Cedar',
        'citrus,woody,white floral,aromatic,green',
        'Niche for MenbyChris Adamsis a Woody fragrance for men. Top notes are Bergamot, Mandarin Orange, Mint and Bitter Orange; middle notes are Jasmine, Orange Blossom and Sea water; base notes are White Musk, Woody Notes and Cedar.',
        4,
        1,
        NULL
      ),
(
        'Niche-for-Women-33089',
        'Niche for Women Chris Adams',
        'Niche',
        'for women',
        NULL,
        NULL,
        'Bergamot, Bitter Orange, Mint and Mandarin Orange',
        'Sea Notes, Orange Blossom and Jasmine',
        'Amber, Woody Notes, Cedar and Musk',
        'citrus,woody,white floral,aromatic,green',
        'Niche for WomenbyChris Adamsis a Amber fragrance for women. Top notes are Bergamot, Bitter Orange, Mint and Mandarin Orange; middle notes are Sea Notes, Orange Blossom and Jasmine; base notes are Amber, Woody Notes, Cedar and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Pink-de-Pink-75147',
        'Pink de Pink Chris Adams',
        'Pink',
        'for women',
        NULL,
        NULL,
        'Grapefruit and Lemon',
        'Orange Blossom, Black Currant, Melon, Violet, Raspberry, Peach and Plum',
        'White Musk, Tonka Bean, Oakmoss, Cedar, Patchouli, Sugar and Vanilla',
        'fruity,sweet,citrus,woody,vanilla',
        'Pink de PinkbyChris Adamsis a Floral Fruity fragrance for women.Pink de Pinkwas launched in 2013. Top notes are Grapefruit and Lemon; middle notes are Orange Blossom, Black Currant, Melon, Violet, Raspberry, Peach and Plum; base notes are White Musk, Tonka Bean, Oakmoss, Cedar, Patchouli, Sugar and Vanilla.',
        4,
        1,
        NULL
      ),
(
        'Possessive-33090',
        'Possessive Chris Adams',
        'Possessive',
        'for women',
        NULL,
        NULL,
        'White Peach, Pineapple and Plum',
        'Lily-of-the-Valley, Rose and Jasmine',
        'White Musk',
        'fruity,white floral,sweet,rose,fresh',
        'PossessivebyChris Adamsis a Floral fragrance for women. Top notes are White Peach, Pineapple and Plum; middle notes are Lily-of-the-Valley, Rose and Jasmine; base note is White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Pure-Blue-33091',
        'Pure Blue Chris Adams',
        'Pure',
        'for men',
        NULL,
        NULL,
        'Bergamot, Cardamom and Mandarin Orange',
        'Iris and Green Tea',
        'Vetiver, Moss and Cedar',
        'iris,woody,earthy,powdery,citrus',
        'Pure BluebyChris Adamsis a Floral fragrance for men. Top notes are Bergamot, Cardamom and Mandarin Orange; middle notes are Iris and Green Tea; base notes are Vetiver, Moss and Cedar.',
        2,
        2,
        NULL
      ),
(
        'Pure-One-33092',
        'Pure One Chris Adams',
        'Pure',
        'for men',
        NULL,
        NULL,
        'Bergamot, Mandarin Orange, Pepper, Green Notes and Lemon',
        'Lily-of-the-Valley and Rose',
        'Sandalwood, Amber and Oakmoss',
        'citrus,green,fresh spicy,woody,rose',
        'Pure OnebyChris Adamsis a Citrus fragrance for men. Top notes are Bergamot, Mandarin Orange, Pepper, Green Notes and Lemon; middle notes are Lily-of-the-Valley and Rose; base notes are Sandalwood, Amber and Oakmoss.',
        NULL,
        NULL,
        NULL
      ),
(
        'Pure-Red-33093',
        'Pure Red Chris Adams',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Pear, Raspberry, Apple, White Peach, Lemon, Banana, Pineapple, Bergamot and Black Pepper',
        'Orange Blossom, Jasmine, Water Lily and Rose',
        'Vanilla, Tonka Bean, Patchouli and White Musk',
        'fruity,sweet,vanilla,fresh,citrus',
        'Pure RedbyChris Adamsis a Floral Fruity fragrance for women. Top notes are Pear, Raspberry, Apple, White Peach, Lemon, Banana, Pineapple, Bergamot and Black Pepper; middle notes are Orange Blossom, Jasmine, Water Lily and Rose; base notes are Vanilla, Tonka Bean, Patchouli and White Musk.',
        4.22,
        9,
        NULL
      ),
(
        'Salsa-33094',
        'Salsa Chris Adams',
        'Salsa',
        'for women',
        NULL,
        NULL,
        'Apple Tree, Wormwood, Lime, Lemon, Mandarin Orange, Plum and Black Currant',
        'Lilac, Freesia, Rose, Cyclamen, Iris, Orchid, Ylang-Ylang and Jasmine',
        'Cedar, Sandalwood, Benzoin, White Musk and Vanilla',
        'woody,floral,powdery,citrus,aromatic',
        'SalsabyChris Adamsis a Woody fragrance for women. Top notes are Apple Tree, Wormwood, Lime, Lemon, Mandarin Orange, Plum and Black Currant; middle notes are Lilac, Freesia, Rose, Cyclamen, Iris, Orchid, Ylang-Ylang and Jasmine; base notes are Cedar, Sandalwood, Benzoin, White Musk and Vanilla.',
        3.75,
        4,
        NULL
      ),
(
        'Saturn-33095',
        'Saturn Chris Adams',
        'Saturn',
        'for men',
        NULL,
        NULL,
        'Cardamom, Cinnamon, Citruses and Cloves',
        'Lily, Sage and Jasmine',
        'Patchouli, Vetiver, Cedar, Vanilla and White Musk',
        'warm spicy,aromatic,white floral,cinnamon,woody',
        'SaturnbyChris Adamsis a Woody fragrance for men. Top notes are Cardamom, Cinnamon, Citruses and Cloves; middle notes are Lily, Sage and Jasmine; base notes are Patchouli, Vetiver, Cedar, Vanilla and White Musk.',
        4,
        2,
        NULL
      ),
(
        'Silver-Shine-33096',
        'Silver Shine Chris Adams',
        'Silver',
        'for men',
        NULL,
        NULL,
        'Star Anise, Lemon, Bergamot and Apple',
        'Lavender and Violet',
        'Patchouli, Cedar, Vanilla, Tonka Bean and Musk',
        'citrus,powdery,woody,aromatic,vanilla',
        'Silver ShinebyChris Adamsis a Woody Aromatic fragrance for men. Top notes are Star Anise, Lemon, Bergamot and Apple; middle notes are Lavender and Violet; base notes are Patchouli, Cedar, Vanilla, Tonka Bean and Musk.',
        4,
        1,
        NULL
      ),
(
        'Strange-33097',
        'Strange Chris Adams',
        'Strange',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Kiwi, Rhubarb, Grapes, Orange Blossom and Mandarin Orange',
        'Watermelon, Cyclamen, Jasmine, Plum and Honeysuckle',
        'Citruses, Musk, Sandalwood, Amber and Vanilla',
        'fruity,white floral,citrus,sweet,powdery',
        'StrangebyChris Adamsis a Floral Fruity fragrance for women. Top notes are Pink Pepper, Kiwi, Rhubarb, Grapes, Orange Blossom and Mandarin Orange; middle notes are Watermelon, Cyclamen, Jasmine, Plum and Honeysuckle; base notes are Citruses, Musk, Sandalwood, Amber and Vanilla.',
        4,
        1,
        NULL
      ),
(
        'Stunner-Pour-Femme-33098',
        'Stunner Pour Femme Chris Adams',
        'Stunner',
        'for women',
        NULL,
        NULL,
        'Lily, Tuberose and Strawberry',
        'Jasmine, Pink Pepper and Tangerine',
        'Vanilla and Musk',
        'white floral,vanilla,tuberose,soft spicy,sweet',
        'Stunner Pour FemmebyChris Adamsis a Floral Fruity fragrance for women. Top notes are Lily, Tuberose and Strawberry; middle notes are Jasmine, Pink Pepper and Tangerine; base notes are Vanilla and Musk.',
        4,
        4,
        NULL
      ),
(
        'Stunner-Pour-Homme-33099',
        'Stunner Pour Homme Chris Adams',
        'Stunner',
        'for men',
        NULL,
        NULL,
        'Bergamot and Citruses',
        'Lavender and Pepper',
        'Musk, Sandalwood and Amber',
        'citrus,fresh spicy,aromatic,fresh',
        'Stunner Pour HommebyChris Adamsis a Amber Fougere fragrance for men. Top notes are Bergamot and Citruses; middle notes are Lavender and Pepper; base notes are Musk, Sandalwood and Amber.',
        4.33,
        6,
        NULL
      ),
(
        'True-Reflections-33100',
        'True Reflections Chris Adams',
        'True',
        'for women',
        NULL,
        NULL,
        'Lemon, Red Currant and Black Currant',
        'Rose, Raspberry and Pomegranate',
        'Violet, Cedar and Musk',
        'fruity,woody,rose,powdery,sweet',
        'True ReflectionsbyChris Adamsis a Floral fragrance for women. Top notes are Lemon, Red Currant and Black Currant; middle notes are Rose, Raspberry and Pomegranate; base notes are Violet, Cedar and Musk.',
        3.6,
        5,
        NULL
      ),
(
        'You-Are-Gorgeous-33101',
        'You Are Gorgeous Chris Adams',
        'You',
        'for women',
        NULL,
        NULL,
        'Lemon, Bergamot, Jasmine, Rose, Green Notes, White Peach, Black Currant and Cloves',
        'Rose, Sage, Cardamom, Cashmeran, Ylang-Ylang, Cedar, Jasmine, White Carnation, Lily, Orange Blossom and Violet',
        'Patchouli, Woody Notes, White Musk, Amber, Oakmoss, Vetiver, Leather and Sandalwood',
        'woody,warm spicy,aromatic,white floral,powdery',
        'You Are GorgeousbyChris Adamsis a Amber Woody fragrance for women. Top notes are Lemon, Bergamot, Jasmine, Rose, Green Notes, White Peach, Black Currant and Cloves; middle notes are Rose, Sage, Cardamom, Cashmeran, Ylang-Ylang, Cedar, Jasmine, White Carnation, Lily, Orange Blossom and Violet; base notes are Patchouli, Woody Notes, White Musk, Amber, Oakmoss, Vetiver, Leather and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Zest-Woman-33102',
        'Zest Woman Chris Adams',
        'Zest',
        'for women',
        NULL,
        NULL,
        'Bergamot, Coriander, Cassia and Violet',
        'Rose, Gardenia, Jasmine and Peony',
        'Cedar, Iris and White Musk',
        'aromatic,woody,white floral,rose,floral',
        'Zest WomanbyChris Adamsis a Floral fragrance for women. Top notes are Bergamot, Coriander, Cassia and Violet; middle notes are Rose, Gardenia, Jasmine and Peony; base notes are Cedar, Iris and White Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Black-Corduroy-Pour-Homme-77520',
        'Black Corduroy Pour Homme Chris Adams',
        'Black',
        'for men',
        NULL,
        NULL,
        'Bergamot, Cardamom, Pepper and Grapefruit',
        'Vetiver, Sandalwood, Lotus and Green Notes',
        'Musk, Sea Notes and Oakmoss',
        'aromatic,woody,citrus,warm spicy,fresh spicy',
        'Black Corduroy Pour HommebyChris Adamsis a Woody Spicy fragrance for men. This is a new fragrance.Black Corduroy Pour Hommewas launched in 2022. Top notes are Bergamot, Cardamom, Pepper and Grapefruit; middle notes are Vetiver, Sandalwood, Lotus and Green Notes; base notes are Musk, Sea Notes and Oakmoss.',
        NULL,
        NULL,
        NULL
      ),
(
        'Blue-Corduroy-Pour-Homme-77523',
        'Blue Corduroy Pour Homme Chris Adams',
        'Blue',
        'for men',
        NULL,
        NULL,
        'Woody Notes and Citruses',
        'Fruity Notes and Aromatic Notes',
        'Spicy Notes, Sea Notes, Amberwood and Musk',
        'woody,amber,citrus,fruity,marine',
        'Blue Corduroy Pour HommebyChris Adamsis a fragrance for men. This is a new fragrance.Blue Corduroy Pour Hommewas launched in 2022. Top notes are Woody Notes and Citruses; middle notes are Fruity Notes and Aromatic Notes; base notes are Spicy Notes, Sea Notes, Amberwood and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Bronze-Corduroy-Pour-Homme-77518',
        'Bronze Corduroy Pour Homme Chris Adams',
        'Bronze',
        'for men',
        NULL,
        NULL,
        'Wormwood, Cardamom, Mint, Bergamot, Eucalyptus, Thyme, Peppermint and Artemisia',
        'Cinnamon, Lavender, Olibanum, Orris, Jasmine, Geranium, Lily-of-the-Valley, Nutmeg and Cumin',
        'Amber, Sandalwood, Tonka Bean, Vanilla, Musk, Moss and White Woods',
        'fresh spicy,aromatic,woody,warm spicy,amber',
        'Bronze Corduroy Pour HommebyChris Adamsis a Amber Fougere fragrance for men. This is a new fragrance.Bronze Corduroy Pour Hommewas launched in 2022. Top notes are Wormwood, Cardamom, Mint, Bergamot, Eucalyptus, Thyme, Peppermint and Artemisia; middle notes are Cinnamon, Lavender, Olibanum, Orris, Jasmine, Geranium, Lily-of-the-Valley, Nutmeg and Cumin; base notes are Amber, Sandalwood, Tonka Bean, Vanilla, Musk, Moss and White Woods.',
        NULL,
        NULL,
        NULL
      ),
(
        'Green-Corduroy-Pour-Homme-77533',
        'Green Corduroy Pour Homme Chris Adams',
        'Green',
        'for men',
        NULL,
        NULL,
        'Apple, Lime, plum, Pineapple, Black Currant, Bergamot, Grapefruit, Melon, Raspberry, Pink Pepper and Black Pepper',
        'Lavender, Jasmine, Orchid, Rose, Geranium, Magnolia and Heliotrope',
        'Musk, Vetiver, Patchouli, Cedar, Sandalwood, Ambergris, Tonka Bean and Leather',
        'fruity,citrus,fresh spicy,sweet,woody',
        'Green Corduroy Pour HommebyChris Adamsis a Floral Fruity fragrance for men. This is a new fragrance.Green Corduroy Pour Hommewas launched in 2022. Top notes are Apple, Lime, plum, Pineapple, Black Currant, Bergamot, Grapefruit, Melon, Raspberry, Pink Pepper and Black Pepper; middle notes are Lavender, Jasmine, Orchid, Rose, Geranium, Magnolia and Heliotrope; base notes are Musk, Vetiver, Patchouli, Cedar, Sandalwood, Ambergris, Tonka Bean and Leather.',
        5,
        1,
        NULL
      ),
(
        'Grey-Corduroy-Pour-Homme-77530',
        'Grey Corduroy Pour Homme Chris Adams',
        'Grey',
        'for men',
        NULL,
        NULL,
        'Bergamot, Orange, Green Apple, Peach, Lemon and Jasmine',
        'Rose, Violet, Magnolia and Patchouli',
        'Amber, Sandalwood, Vanilla and Musk',
        'citrus,powdery,floral,woody,fruity',
        'Grey Corduroy Pour HommebyChris Adamsis a Amber Floral fragrance for men. This is a new fragrance.Grey Corduroy Pour Hommewas launched in 2022. Top notes are Bergamot, Orange, Green Apple, Peach, Lemon and Jasmine; middle notes are Rose, Violet, Magnolia and Patchouli; base notes are Amber, Sandalwood, Vanilla and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'White-Corduroy-Pour-Homme-77525',
        'White Corduroy Pour Homme Chris Adams',
        'White',
        'for men',
        NULL,
        NULL,
        'Bergamot, Lavender and Apple',
        'Sandalwood and Violet',
        'Amber, Patchouli and Musk',
        'powdery,woody,citrus,violet,amber',
        'White Corduroy Pour HommebyChris Adamsis a Woody Aromatic fragrance for men. This is a new fragrance.White Corduroy Pour Hommewas launched in 2022. Top notes are Bergamot, Lavender and Apple; middle notes are Sandalwood and Violet; base notes are Amber, Patchouli and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Blumine-Pour-Femme-77502',
        'Blumine Pour Femme Chris Adams',
        'Blumine',
        'for women',
        NULL,
        NULL,
        'Bergamot, Lemon, Black Currant, Peach and Raspberry',
        'Patchouli, Rose and Violet',
        'Sandalwood, Amber, White Musk and Toffee',
        'woody,citrus,patchouli,powdery,fruity',
        'Blumine Pour FemmebyChris Adamsis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Blumine Pour Femmewas launched in 2022. Top notes are Bergamot, Lemon, Black Currant, Peach and Raspberry; middle notes are Patchouli, Rose and Violet; base notes are Sandalwood, Amber, White Musk and Toffee.',
        4,
        2,
        NULL
      ),
(
        'Boss-Babe-Pour-Femme-77503',
        'Boss Babe Pour Femme Chris Adams',
        'Boss',
        'for women',
        NULL,
        NULL,
        'Lemon, Black Currant and Apple',
        'Lily-of-the-Valley, Jasmine and Rose',
        'Musk, Vanilla and Sea Notes',
        'white floral,fruity,fresh,aromatic,rose',
        'Boss Babe Pour FemmebyChris Adamsis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Boss Babe Pour Femmewas launched in 2022. Top notes are Lemon, Black Currant and Apple; middle notes are Lily-of-the-Valley, Jasmine and Rose; base notes are Musk, Vanilla and Sea Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'Gifted-Pour-Femme-77504',
        'Gifted Pour Femme Chris Adams',
        'Gifted',
        'for women',
        NULL,
        NULL,
        'Bergamot, Orange and Lemon',
        'Jasmine, Rose, Orris Root, Pink Pepper and Ylang-Ylang',
        'Musk, Amber, Patchouli, Vanilla, Sweet Notes and Coumarin',
        'citrus,sweet,woody,vanilla,powdery',
        'Gifted Pour FemmebyChris Adamsis a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Gifted Pour Femmewas launched in 2022. Top notes are Bergamot, Orange and Lemon; middle notes are Jasmine, Rose, Orris Root, Pink Pepper and Ylang-Ylang; base notes are Musk, Amber, Patchouli, Vanilla, Sweet Notes and Coumarin.',
        5,
        1,
        NULL
      ),
(
        'Let-s-Imagine-Pour-Femme-77511',
        'Let''s Imagine Pour Femme Chris Adams',
        'Let''s',
        'for women',
        NULL,
        NULL,
        'Bergamot, Black Currant and Orange Blossom',
        'Jasmine, Rose, Lily-of-the-Valley and Plum',
        'Cedar, Amber, Patchouli, Vanilla and Musk',
        'white floral,woody,fruity,citrus,floral',
        'Let''s Imagine Pour FemmebyChris Adamsis a Floral Woody Musk fragrance for women. This is a new fragrance.Let''s Imagine Pour Femmewas launched in 2022. Top notes are Bergamot, Black Currant and Orange Blossom; middle notes are Jasmine, Rose, Lily-of-the-Valley and Plum; base notes are Cedar, Amber, Patchouli, Vanilla and Musk.',
        3.5,
        2,
        NULL
      ),
(
        'Prize-Pour-Femme-77506',
        'Prize Pour Femme Chris Adams',
        'Prize',
        'for women',
        NULL,
        NULL,
        'Aldehydes, Strawberry, Spices, Peach, Bergamot and Orange',
        'Iris, Violet, Narcissus, Rose, Orris, Ylang-Ylang, Lily-of-the-Valley and Jasmine',
        'Sandalwood, Amber, Benzoin, Musk, Tonka Bean and Vetiver',
        'powdery,woody,amber,sweet,citrus',
        'Prize Pour FemmebyChris Adamsis a Floral Fruity fragrance for women. This is a new fragrance.Prize Pour Femmewas launched in 2022. Top notes are Aldehydes, Strawberry, Spices, Peach, Bergamot and Orange; middle notes are Iris, Violet, Narcissus, Rose, Orris, Ylang-Ylang, Lily-of-the-Valley and Jasmine; base notes are Sandalwood, Amber, Benzoin, Musk, Tonka Bean and Vetiver.',
        5,
        1,
        NULL
      ),
(
        'Rover-Pour-Homme-77516',
        'Rover Pour Homme Chris Adams',
        'Rover',
        'for men',
        NULL,
        NULL,
        'Bergamot and Grapefruit',
        'Thyme, Rose, Nutmeg, Iris, Violet and Tonka Bean',
        'Cedar, Sandalwood, Vetiver, Moss, Amber and Musk',
        'woody,powdery,aromatic,fresh spicy,citrus',
        'Rover Pour HommebyChris Adamsis a Citrus Aromatic fragrance for men. This is a new fragrance.Rover Pour Hommewas launched in 2022. Top notes are Bergamot and Grapefruit; middle notes are Thyme, Rose, Nutmeg, Iris, Violet and Tonka Bean; base notes are Cedar, Sandalwood, Vetiver, Moss, Amber and Musk.',
        4,
        1,
        NULL
      ),
(
        'Volante-Pour-Homme-77514',
        'Volante Pour Homme Chris Adams',
        'Volante',
        'for men',
        NULL,
        NULL,
        'Lavender, Bergamot and Rosemary',
        'Rhubarb, Geranium and Sea Notes',
        'White Amber, Balsam Fir and Tonka Bean',
        'aromatic,fresh spicy,amber,woody,citrus',
        'Volante Pour HommebyChris Adamsis a Aromatic Fougere fragrance for men. This is a new fragrance.Volante Pour Hommewas launched in 2022. Top notes are Lavender, Bergamot and Rosemary; middle notes are Rhubarb, Geranium and Sea Notes; base notes are White Amber, Balsam Fir and Tonka Bean.',
        NULL,
        NULL,
        NULL
      ),
(
        'Chouette-Vierge-0-Zero-92904',
        'Chouette Vierge 0 Zero Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Pineapple, Musk, Black Currant, Apple, Bergamot, Pear and White Pepper',
        'Myrrh, Birch, Rose, Patchouli, Lavender, Jasmine and Iris',
        'Ambergris, Oakmoss, Amyl Salicylate, Musk, Vanilla, Birch, Iso E Super and Amber',
        'fruity,amber,sweet,mossy,woody',
        'Chouette Vierge 0 ZerobyChouette Vierge Parfuméeis a Chypre Fruity fragrance for women and men. This is a new fragrance.Chouette Vierge 0 Zerowas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Pineapple, Musk, Black Currant, Apple, Bergamot, Pear and White Pepper; middle notes are Myrrh, Birch, Rose, Patchouli, Lavender, Jasmine and Iris; base notes are Ambergris, Oakmoss, Amyl Salicylate, Musk, Vanilla, Birch, Iso E Super and Amber.',
        5,
        3,
        NULL
      ),
(
        'Chouette-Vierge-No-1-92905',
        'Chouette Vierge No. 1 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Orange Peel, Bergamot, Lavender, Geranium, Cinnamon, Saffron, Nutmeg, Peach and Rose',
        'Tobacco, Gurjan balsam, Jasmine, Cacao, Rose and Oud',
        'Sandalwood, Tonka Bean, Patchouli, Ambergris, Vanilla, Leather and Musk',
        'warm spicy,fresh spicy,tobacco,sweet,woody',
        'Chouette Vierge No. 1byChouette Vierge Parfuméeis a Amber Woody fragrance for women and men. This is a new fragrance.Chouette Vierge No. 1was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Orange Peel, Bergamot, Lavender, Geranium, Cinnamon, Saffron, Nutmeg, Peach and Rose; middle notes are Tobacco, Gurjan balsam, Jasmine, Cacao, Rose and Oud; base notes are Sandalwood, Tonka Bean, Patchouli, Ambergris, Vanilla, Leather and Musk.',
        5,
        2,
        NULL
      ),
(
        'Chouette-Vierge-No-10-92914',
        'Chouette Vierge No. 10 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Orange Blossom, Bergamot and Neroli',
        'Lily of the Valley, Ylang Ylang, Jasmine, Neroli, Rose, Iris, Oud and Jasmine Sambac',
        'Pink Pepper, Marshmallow, Sandalwood, Tonka Bean, Orris Root, Patchouli, Ambergris, Cinnamon, Vanilla, Saffron, Vetiver, Cacao, Cumin, Musk and Guaiac Wood',
        'woody,white floral,warm spicy,powdery,sweet',
        'Chouette Vierge No. 10byChouette Vierge Parfuméeis a Amber Floral fragrance for women and men. This is a new fragrance.Chouette Vierge No. 10was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Orange Blossom, Bergamot and Neroli; middle notes are Lily of the Valley, Ylang Ylang, Jasmine, Neroli, Rose, Iris, Oud and Jasmine Sambac; base notes are Pink Pepper, Marshmallow, Sandalwood, Tonka Bean, Orris Root, Patchouli, Ambergris, Cinnamon, Vanilla, Saffron, Vetiver, Cacao, Cumin, Musk and Guaiac Wood.',
        5,
        1,
        NULL
      ),
(
        'Chouette-Vierge-No-11-92915',
        'Chouette Vierge No. 11 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Laurel Blossom, Red Berries and Strawberry',
        'Lily, Melon, Cedar and Mint',
        'Oakmoss, Ylang Ylang, Vetiver and Cedar',
        'fruity,sweet,woody,mossy,earthy',
        'Chouette Vierge No. 11byChouette Vierge Parfuméeis a Floral Fruity fragrance for women and men. This is a new fragrance.Chouette Vierge No. 11was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Laurel Blossom, Red Berries and Strawberry; middle notes are Lily, Melon, Cedar and Mint; base notes are Oakmoss, Ylang Ylang, Vetiver and Cedar.',
        5,
        3,
        NULL
      ),
(
        'Chouette-Vierge-No-2-92906',
        'Chouette Vierge No. 2 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Saffron, Olibanum, Rose, Bergamot, Lavender, Geranium, Freesia and Nutmeg',
        'Musk, Patchouli, Oud, Rose and Jasmine',
        'Saffron, Vetiver, Oud, Cedarwood, Sandalwood, Vanilla and Leather',
        'woody,warm spicy,fresh spicy,aromatic,musky',
        'Chouette Vierge No. 2byChouette Vierge Parfuméeis a Amber Woody fragrance for women and men. This is a new fragrance.Chouette Vierge No. 2was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Saffron, Olibanum, Rose, Bergamot, Lavender, Geranium, Freesia and Nutmeg; middle notes are Musk, Patchouli, Oud, Rose and Jasmine; base notes are Saffron, Vetiver, Oud, Cedarwood, Sandalwood, Vanilla and Leather.',
        5,
        2,
        NULL
      ),
(
        'Chouette-Vierge-No-3-92907',
        'Chouette Vierge No. 3 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Blood Orange, Bergamot, Nutmeg, Lemon and Pear',
        'Rose, Oud, Ylang-Ylang, Lavender and Iris',
        'Ambergris, Musk, Vetiver, Patchouli, Benzoin and Leather',
        'amber,citrus,musky,animalic,fresh spicy',
        'Chouette Vierge No. 3byChouette Vierge Parfuméeis a Amber Woody fragrance for women and men. This is a new fragrance.Chouette Vierge No. 3was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Blood Orange, Bergamot, Nutmeg, Lemon and Pear; middle notes are Rose, Oud, Ylang-Ylang, Lavender and Iris; base notes are Ambergris, Musk, Vetiver, Patchouli, Benzoin and Leather.',
        5,
        2,
        NULL
      ),
(
        'Chouette-Vierge-No-4-92908',
        'Chouette Vierge No. 4 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Leather, Ylang-Ylang, Bergamot and Lemon',
        'Dark Chocolate, Labdanum, Rum, Patchouli, Bourbon Vanilla, Amber, Coffee, Cypress and Caramel',
        'Patchouli, Madagascar Vanilla, Vetiver, Musk, Sandalwood and Heliotrope',
        'woody,amber,warm spicy,leather,powdery',
        'Chouette Vierge No. 4byChouette Vierge Parfuméeis a Amber Vanilla fragrance for women and men. This is a new fragrance.Chouette Vierge No. 4was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Leather, Ylang-Ylang, Bergamot and Lemon; middle notes are Dark Chocolate, Labdanum, Rum, Patchouli, Bourbon Vanilla, Amber, Coffee, Cypress and Caramel; base notes are Patchouli, Madagascar Vanilla, Vetiver, Musk, Sandalwood and Heliotrope.',
        5,
        3,
        NULL
      ),
(
        'Chouette-Vierge-No-5-92909',
        'Chouette Vierge No. 5 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Pink Pepper, Ozonic notes, Bergamot, Lavender, Sage and Mint',
        'Green Tea, Black Tea, Tea, Lapsang Souchong Tea, Orris Root, Osmanthus, Vanilla, Jasmine, Leather and Almond',
        'Mate, Tea, Rice, Cashmeran, Resin, Tonka, Leather and Amber',
        'aromatic,green,fresh spicy,amber,woody',
        'Chouette Vierge No. 5byChouette Vierge Parfuméeis a Leather fragrance for women and men. This is a new fragrance.Chouette Vierge No. 5was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Pink Pepper, Ozonic notes, Bergamot, Lavender, Sage and Mint; middle notes are Green Tea, Black Tea, Tea, Lapsang Souchong Tea, Orris Root, Osmanthus, Vanilla, Jasmine, Leather and Almond; base notes are Mate, Tea, Rice, Cashmeran, Resin, Tonka, Leather and Amber.',
        5,
        3,
        NULL
      ),
(
        'Chouette-Vierge-No-6-92910',
        'Chouette Vierge No. 6 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Grapes, Rum, Blackberry, Bergamot, Pepper, Nutmeg, Apple and Raspberry',
        'Saffron, Rose, Oud, Wormwood, Ylang-Ylang, Heliotrope, Jasmine, Clove and Licorice',
        'Oakmoss, Musk, Patchouli, Iris, Sandalwood, Cedarwood, Leather, Vetiver, Amber, Woody Notes, Cinnamon, Vanilla and Spices',
        'woody,warm spicy,powdery,earthy,fruity',
        'Chouette Vierge No. 6byChouette Vierge Parfuméeis a Amber Spicy fragrance for women and men. This is a new fragrance.Chouette Vierge No. 6was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Grapes, Rum, Blackberry, Bergamot, Pepper, Nutmeg, Apple and Raspberry; middle notes are Saffron, Rose, Oud, Wormwood, Ylang-Ylang, Heliotrope, Jasmine, Clove and Licorice; base notes are Oakmoss, Musk, Patchouli, Iris, Sandalwood, Cedarwood, Leather, Vetiver, Amber, Woody Notes, Cinnamon, Vanilla and Spices.',
        5,
        2,
        NULL
      ),
(
        'Chouette-Vierge-No-7-92911',
        'Chouette Vierge No. 7 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Raspberry, Bergamot, Tobacco, Violet, Amber and Honey',
        'Patchouli, Black Tea, Cardamom, Saffron, Nutmeg, Cherry and Iris',
        'Patchouli, Chamomile, Cedarwood, Vanilla, Tobacco, Almond and Oak',
        'woody,sweet,warm spicy,powdery,fresh spicy',
        'Chouette Vierge No. 7byChouette Vierge Parfuméeis a Amber Vanilla fragrance for women and men. This is a new fragrance.Chouette Vierge No. 7was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Raspberry, Bergamot, Tobacco, Violet, Amber and Honey; middle notes are Patchouli, Black Tea, Cardamom, Saffron, Nutmeg, Cherry and Iris; base notes are Patchouli, Chamomile, Cedarwood, Vanilla, Tobacco, Almond and Oak.',
        5,
        1,
        NULL
      ),
(
        'Chouette-Vierge-No-8-92912',
        'Chouette Vierge No. 8 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Pink Pepper, Ginger and Rum',
        'Black Pepper, Coriander, Cinnamon, Nutmeg, Cloves and Cherry',
        'Patchouli, Vanilla, Laurel Blossom and Woody Notes',
        'warm spicy,fresh spicy,woody,soft spicy,sweet',
        'Chouette Vierge No. 8byChouette Vierge Parfuméeis a Amber Spicy fragrance for women and men. This is a new fragrance.Chouette Vierge No. 8was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Pink Pepper, Ginger and Rum; middle notes are Black Pepper, Coriander, Cinnamon, Nutmeg, Cloves and Cherry; base notes are Patchouli, Vanilla, Laurel Blossom and Woody Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'Chouette-Vierge-No-9-92913',
        'Chouette Vierge No. 9 Chouette Vierge Parfumée',
        'Chouette',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Bitter Almond, Black Pepper, Black Cherry, Pine Tree, Bay Leaf, Nutmeg, Neroli and Liquor',
        'Turkish Rose, Ylang Ylang, Osmanthus, Geranium, Champaca, Cherry, Poppy, Plum and Jasmine Sambac',
        'Peru Balsam, Sandalwood, Tonka Bean, Patchouli, Cedarwood, Cinnamon, Vanilla, Benzoin, Leather, Vetiver, Cloves, Civet and Resin',
        'woody,fresh spicy,warm spicy,floral,amber',
        'Chouette Vierge No. 9byChouette Vierge Parfuméeis a Amber Floral fragrance for women and men. This is a new fragrance.Chouette Vierge No. 9was launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Bitter Almond, Black Pepper, Black Cherry, Pine Tree, Bay Leaf, Nutmeg, Neroli and Liquor; middle notes are Turkish Rose, Ylang Ylang, Osmanthus, Geranium, Champaca, Cherry, Poppy, Plum and Jasmine Sambac; base notes are Peru Balsam, Sandalwood, Tonka Bean, Patchouli, Cedarwood, Cinnamon, Vanilla, Benzoin, Leather, Vetiver, Cloves, Civet and Resin.',
        NULL,
        NULL,
        NULL
      ),
(
        'L-IAM-92917',
        'L'' IAM Chouette Vierge Parfumée',
        'L''',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Dark Chocolate and Orange',
        'Coffee, Cacao, Cognac, Tobacco and Almond',
        'Coffee, Dark Chocolate, Honey, Ambergris, Vanilla, Amber, Leather and Patchouli',
        'warm spicy,sweet,cacao,coffee,amber',
        'L'' IAMbyChouette Vierge Parfuméeis a Amber Vanilla fragrance for women and men. This is a new fragrance.L'' IAMwas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Dark Chocolate and Orange; middle notes are Coffee, Cacao, Cognac, Tobacco and Almond; base notes are Coffee, Dark Chocolate, Honey, Ambergris, Vanilla, Amber, Leather and Patchouli.',
        5,
        4,
        NULL
      ),
(
        'L-U-ARE-92916',
        'L'' U ARE Chouette Vierge Parfumée',
        'L''',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Coriander, Chocolate, Cumin and Spices',
        'Labdanum, Patchouli, Coffee, Lavender, Vanilla and Sandalwood',
        'Patchouli, Oakmoss, Vetiver, White Musk, Cedarwood and Amber',
        'woody,warm spicy,amber,earthy,aromatic',
        'L'' U AREbyChouette Vierge Parfuméeis a fragrance for women and men. This is a new fragrance.L'' U AREwas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Coriander, Chocolate, Cumin and Spices; middle notes are Labdanum, Patchouli, Coffee, Lavender, Vanilla and Sandalwood; base notes are Patchouli, Oakmoss, Vetiver, White Musk, Cedarwood and Amber.',
        5,
        2,
        NULL
      ),
(
        'Nebuleuse-de-L-abeille-92919',
        'Nébuleuse de L''abeille Chouette Vierge Parfumée',
        'Nébuleuse',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Beeswax, Incense, Myrrh, Ginger, Orange, Spices and Iris',
        'Opoponax, Heliotrope, Orange Blossom, Ambroxan, Mimosa and Broom',
        'Amberwood, Labdanum, Benzoin, Musk, Guaiac Wood, Bourbon Vanilla, Sandalwood, Tonka Bean and Cedarwood',
        'amber,woody,warm spicy,balsamic,powdery',
        'Nébuleuse de L''abeillebyChouette Vierge Parfuméeis a Amber Floral fragrance for women and men. This is a new fragrance.Nébuleuse de L''abeillewas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Beeswax, Incense, Myrrh, Ginger, Orange, Spices and Iris; middle notes are Opoponax, Heliotrope, Orange Blossom, Ambroxan, Mimosa and Broom; base notes are Amberwood, Labdanum, Benzoin, Musk, Guaiac Wood, Bourbon Vanilla, Sandalwood, Tonka Bean and Cedarwood.',
        5,
        3,
        NULL
      ),
(
        'Nebuleuse-du-Papillon-92918',
        'Nébuleuse du Papillon Chouette Vierge Parfumée',
        'Nébuleuse',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Red Wine, Amaretto, Chocolate and Citruses',
        'Narcissus, Immortelle, Lotus, Rose, Tuberose, Jasmine and Violet',
        'Civet, Castoreum, Musk, Tobacco, Patchouli, Sandalwood, Cinnamon, Amber and Honey',
        'musky,animalic,wine,powdery,leather',
        'Nébuleuse du PapillonbyChouette Vierge Parfuméeis a Amber Floral fragrance for women and men. This is a new fragrance.Nébuleuse du Papillonwas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Red Wine, Amaretto, Chocolate and Citruses; middle notes are Narcissus, Immortelle, Lotus, Rose, Tuberose, Jasmine and Violet; base notes are Civet, Castoreum, Musk, Tobacco, Patchouli, Sandalwood, Cinnamon, Amber and Honey.',
        5,
        3,
        NULL
      ),
(
        'Nebuleuse-du-sang-92920',
        'Nébuleuse du sang Chouette Vierge Parfumée',
        'Nébuleuse',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Pink Pepper, Incense, Peach, Lemon, Pear and Bergamot',
        'Bulgarian Rose, Ylang Ylang, Cedarwood, Jasmine and Iris',
        'Sandalwood, Tonka Bean, Patchouli, Ambergris, Opoponax, Vanilla, Benzoin, Leather, Vetiver, Civet and Musk',
        'amber,woody,powdery,sweet,balsamic',
        'Nébuleuse du sangbyChouette Vierge Parfuméeis a Amber Floral fragrance for women and men. This is a new fragrance.Nébuleuse du sangwas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Pink Pepper, Incense, Peach, Lemon, Pear and Bergamot; middle notes are Bulgarian Rose, Ylang Ylang, Cedarwood, Jasmine and Iris; base notes are Sandalwood, Tonka Bean, Patchouli, Ambergris, Opoponax, Vanilla, Benzoin, Leather, Vetiver, Civet and Musk.',
        4.5,
        4,
        NULL
      ),
(
        'Nebuleuse-Marine-Violet-92921',
        'Nébuleuse Marine Violet Chouette Vierge Parfumée',
        'Nébuleuse',
        'for women and men',
        NULL,
        'Hoang Nguyen',
        'Violet and Whipped Cream',
        'Hyrax, Musk, Patchouli and Orange Blossom',
        'Mushroom, Ambergris, Civet, Labdanum, Sandalwood and Birch',
        'musky,amber,animalic,powdery,earthy',
        'Nébuleuse Marine VioletbyChouette Vierge Parfuméeis a Amber Woody fragrance for women and men. This is a new fragrance.Nébuleuse Marine Violetwas launched in 2024. The nose behind this fragrance is Hoang Nguyen. Top notes are Violet and Whipped Cream; middle notes are Hyrax, Musk, Patchouli and Orange Blossom; base notes are Mushroom, Ambergris, Civet, Labdanum, Sandalwood and Birch.',
        5,
        3,
        NULL
      ),
(
        '1904-72729',
        '1904 Chatillon Lux Parfums',
        '1904',
        'for women and men',
        NULL,
        'Shawn Maher',
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,white floral,coffee,aromatic',
        '1904byChatillon Lux Parfumsis a fragrance for women and men.1904was launched in 2021. The nose behind this fragrance is Shawn Maher.',
        4,
        10,
        NULL
      ),
(
        'Admiral-58893',
        'Admiral Chatillon Lux Parfums',
        'Admiral',
        'for men',
        NULL,
        'Shawn Maher',
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,vanilla,herbal',
        'AdmiralbyChatillon Lux Parfumsis a fragrance for men.Admiralwas launched in 2019. The nose behind this fragrance is Shawn Maher.',
        3.89,
        27,
        NULL
      ),
(
        'Bon-Vivant-48695',
        'Bon Vivant Chatillon Lux Parfums',
        'Bon',
        'for women and men',
        NULL,
        'Shawn Maher',
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,fresh spicy,leather,woody',
        'Bon VivantbyChatillon Lux Parfumsis a fragrance for women and men.Bon Vivantwas launched in 2017. The nose behind this fragrance is Shawn Maher.',
        4.67,
        6,
        NULL
      ),
(
        'Confluence-66663',
        'Confluence Chatillon Lux Parfums',
        'Confluence',
        'for women and men',
        NULL,
        'Shawn Maher',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,fresh spicy,balsamic,conifer',
        'ConfluencebyChatillon Lux Parfumsis a fragrance for women and men.Confluencewas launched in 2021. The nose behind this fragrance is Shawn Maher.',
        4.68,
        25,
        NULL
      ),
(
        'Eau-de-Treget-51722',
        'Eau de Treget Chatillon Lux Parfums',
        'Eau',
        'for women and men',
        NULL,
        'Shawn Maher',
        NULL,
        NULL,
        NULL,
        'citrus,woody,earthy,white floral,mossy',
        'Eau de TregetbyChatillon Lux Parfumsis a Chypre fragrance for women and men.Eau de Tregetwas launched in 2018. The nose behind this fragrance is Shawn Maher.',
        4.29,
        7,
        NULL
      );
