
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Arabian-Oud-70360',
        'Arabian Oud Laverne',
        'Arabian',
        'for women and men',
        NULL,
        'Christian Provenzano',
        'Pimento Seeds and Coriander',
        'Lavender, Rose, Jasmine and Marigold',
        'Moss, Guaiac Wood, Saffron, Musk, Olibanum, Cypriol Oil or Nagarmotha, Agarwood (Oud), Patchouli and Maltol',
        'woody,warm spicy,aromatic,earthy,sweet',
        'Arabian OudbyLaverneis a Amber Woody fragrance for women and men.Arabian Oudwas launched in 2021. The nose behind this fragrance is Christian Provenzano. Top notes are Pimento Seeds and Coriander; middle notes are Lavender, Rose, Jasmine and Marigold; base notes are Moss, Guaiac Wood, Saffron, Musk, Olibanum, Cypriol Oil or Nagarmotha, Agarwood (Oud), Patchouli and Maltol.',
        2.94,
        16,
        NULL
      ),
(
        'Dark-Amber-70362',
        'Dark Amber Laverne',
        'Dark',
        'for women and men',
        NULL,
        NULL,
        'Honey and Incense',
        'Tonka Bean, Vetiver and Woody Notes',
        'Amber, Agarwood (Oud) and Leather',
        'amber,honey,sweet,vanilla,animalic',
        'Dark AmberbyLaverneis a Amber Woody fragrance for women and men.Dark Amberwas launched in 2021. Top notes are Honey and Incense; middle notes are Tonka Bean, Vetiver and Woody Notes; base notes are Amber, Agarwood (Oud) and Leather.',
        3.75,
        8,
        NULL
      ),
(
        'Over-Rose-72172',
        'Over Rose Laverne',
        'Over',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Egyptian Rose',
        'Orange Blossom and Exotic floral notes',
        'Amber, Vanilla and Chocolate',
        'citrus,floral,amber,white floral,vanilla',
        'Over RosebyLaverneis a Amber Floral fragrance for women.Over Rosewas launched in 2021. Top notes are Mandarin Orange and Egyptian Rose; middle notes are Orange Blossom and Exotic floral notes; base notes are Amber, Vanilla and Chocolate.',
        4.38,
        8,
        NULL
      ),
(
        'Tishreen-67353',
        'Tishreen Laverne',
        'Tishreen',
        'for women and men',
        NULL,
        NULL,
        'Laurels, Patchouli and Cinnamon',
        'Clove, Sandalwood, Myrrh and Resins',
        'Vanilla and Amber',
        'warm spicy,amber,woody,balsamic,cinnamon',
        'TishreenbyLaverneis a Amber Spicy fragrance for women and men.Tishreenwas launched in 2021. Top notes are Laurels, Patchouli and Cinnamon; middle notes are Clove, Sandalwood, Myrrh and Resins; base notes are Vanilla and Amber.',
        1,
        1,
        NULL
      ),
(
        'Always-Together-37296',
        'Always Together Laurelle London',
        'Always',
        'for women',
        NULL,
        NULL,
        'Litchi, Violet and Sea Notes',
        'Magnolia, Peony and Lotus',
        'Sandalwood and Musk',
        'floral,powdery,fresh,woody,fruity',
        'Always TogetherbyLaurelle Londonis a Floral Aquatic fragrance for women. Top notes are Litchi, Violet and Sea Notes; middle notes are Magnolia, Peony and Lotus; base notes are Sandalwood and Musk.',
        5,
        1,
        NULL
      ),
(
        'Butterfly-Kisses-37270',
        'Butterfly Kisses Laurelle London',
        'Butterfly',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Butterfly KissesbyLaurelle Londonis a fragrance for women.',
        3,
        2,
        NULL
      ),
(
        'City-Girl-London-37291',
        'City Girl London Laurelle London',
        'City',
        'for women',
        NULL,
        NULL,
        'Lemon and Lime',
        'Apple and Vanilla',
        'Cedar and Musk',
        'citrus,woody,vanilla,powdery,musky',
        'City Girl LondonbyLaurelle Londonis a Citrus Aromatic fragrance for women. Top notes are Lemon and Lime; middle notes are Apple and Vanilla; base notes are Cedar and Musk.',
        2,
        1,
        NULL
      ),
(
        'City-Girl-Milan-37294',
        'City Girl Milan Laurelle London',
        'City',
        'for women',
        NULL,
        NULL,
        'Pepper, Pear and Grapefruit',
        'Geranium and Rose',
        'Musk, Vanilla and Tonka Bean',
        'fresh spicy,aromatic,rose,warm spicy,vanilla',
        'City Girl MilanbyLaurelle Londonis a Amber Floral fragrance for women. Top notes are Pepper, Pear and Grapefruit; middle notes are Geranium and Rose; base notes are Musk, Vanilla and Tonka Bean.',
        NULL,
        NULL,
        NULL
      ),
(
        'City-Girl-New-York-37292',
        'City Girl New York Laurelle London',
        'City',
        'for women',
        NULL,
        NULL,
        'Red Litchi and Kiwi',
        'Floral Notes',
        'Musk and Sandalwood',
        'fruity,tropical,musky,powdery,floral',
        'City Girl New YorkbyLaurelle Londonis a Floral Fruity fragrance for women. Top notes are Red Litchi and Kiwi; middle note is Floral Notes; base notes are Musk and Sandalwood.',
        4,
        8,
        NULL
      ),
(
        'City-Girl-Paris-37293',
        'City Girl Paris Laurelle London',
        'City',
        'for women',
        NULL,
        NULL,
        'Honey and Orange Blossom',
        'Vanilla and Musk',
        'Cedar and Sandalwood',
        'honey,sweet,white floral,vanilla,powdery',
        'City Girl ParisbyLaurelle Londonis a Amber fragrance for women. Top notes are Honey and Orange Blossom; middle notes are Vanilla and Musk; base notes are Cedar and Sandalwood.',
        4,
        1,
        NULL
      ),
(
        'Closer-No-1-37258',
        'Closer No.1 Laurelle London',
        'Closer',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Closer No.1byLaurelle Londonis a fragrance for women.',
        1.75,
        4,
        NULL
      ),
(
        'Definitely-Maybe-37259',
        'Definitely Maybe Laurelle London',
        'Definitely',
        'for women',
        NULL,
        NULL,
        'Floral Notes',
        'Pomegranate and Yuzu',
        'Amber',
        'floral,amber,citrus,woody,fresh spicy',
        'Definitely MaybebyLaurelle Londonis a Floral fragrance for women. Top note is Floral Notes; middle notes are Pomegranate and Yuzu; base note is Amber.',
        3.62,
        13,
        NULL
      ),
(
        'Desire-Purple-37256',
        'Desire Purple Laurelle London',
        'Desire',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Desire PurplebyLaurelle Londonis a fragrance for women.',
        3.5,
        2,
        NULL
      ),
(
        'Disco-Pink-37290',
        'Disco Pink Laurelle London',
        'Disco',
        'for women',
        NULL,
        NULL,
        'Litchi and Kiwi',
        'Orchid and White Chocolate',
        'Vanilla, Musk and Woody Notes',
        'sweet,vanilla,floral,powdery,fruity',
        'Disco PinkbyLaurelle Londonis a Aromatic Fruity fragrance for women. Top notes are Litchi and Kiwi; middle notes are Orchid and White Chocolate; base notes are Vanilla, Musk and Woody Notes.',
        3,
        3,
        NULL
      ),
(
        'Disco-Purple-37289',
        'Disco Purple Laurelle London',
        'Disco',
        'for women',
        NULL,
        NULL,
        'Pear, Guava and Water Notes',
        'Violet, Lily and Freesia',
        'Sandalwood, White Amber and Musk',
        'fruity,aquatic,fresh,powdery,violet',
        'Disco PurplebyLaurelle Londonis a Floral Fruity fragrance for women. Top notes are Pear, Guava and Water Notes; middle notes are Violet, Lily and Freesia; base notes are Sandalwood, White Amber and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Disco-Silver-37230',
        'Disco Silver Laurelle London',
        'Disco',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Disco SilverbyLaurelle Londonis a fragrance for men.',
        5,
        1,
        NULL
      ),
(
        'Energize-37223',
        'Energize Laurelle London',
        'Energize',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'EnergizebyLaurelle Londonis a Aromatic fragrance for men.',
        2,
        1,
        NULL
      ),
(
        'Energize-Noir-37224',
        'Energize Noir Laurelle London',
        'Energize',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Energize NoirbyLaurelle Londonis a fragrance for men.',
        3.33,
        3,
        NULL
      ),
(
        'Eternal-Love-37265',
        'Eternal Love Laurelle London',
        'Eternal',
        'for women',
        NULL,
        NULL,
        'Orange, Bergamot and Grapefruit',
        'Rose and Italian Jasmine',
        'White Musk, Haitian Vetiver and Bourbon Vanilla',
        'citrus,musky,rose,powdery,fresh spicy',
        'Eternal LovebyLaurelle Londonis a Floral Woody Musk fragrance for women. Top notes are Orange, Bergamot and Grapefruit; middle notes are Rose and Italian Jasmine; base notes are White Musk, Haitian Vetiver and Bourbon Vanilla.',
        3,
        3,
        NULL
      ),
(
        'Executive-Man-Aqua-37221',
        'Executive Man Aqua Laurelle London',
        'Executive',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh,warm spicy',
        'Executive Man AquabyLaurelle Londonis a Aromatic Aquatic fragrance for men.',
        3.83,
        6,
        NULL
      ),
(
        'Executive-Man-Nevada-37222',
        'Executive Man Nevada Laurelle London',
        'Executive',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Executive Man NevadabyLaurelle Londonis a fragrance for men.',
        4,
        1,
        NULL
      ),
(
        'Flutter-37272',
        'Flutter Laurelle London',
        'Flutter',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet',
        'FlutterbyLaurelle Londonis a Floral Fruity fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Forever-Together-37295',
        'Forever Together Laurelle London',
        'Forever',
        'for women',
        NULL,
        NULL,
        'Apple and Pink Pepper',
        'Rose, Jasmine and White Tea',
        'Cedar, Amber and White Musk',
        'rose,white floral,green,fresh,fruity',
        'Forever TogetherbyLaurelle Londonis a Floral fragrance for women. Top notes are Apple and Pink Pepper; middle notes are Rose, Jasmine and White Tea; base notes are Cedar, Amber and White Musk.',
        4.67,
        3,
        NULL
      ),
(
        'Him-37130',
        'Him Laurelle London',
        'Him',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'HimbyLaurelle Londonis a Aromatic Spicy fragrance for men.Himwas launched in 2014.',
        4.29,
        7,
        NULL
      ),
(
        'If-Only-Black-37255',
        'If Only Black Laurelle London',
        'If',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'If Only BlackbyLaurelle Londonis a fragrance for women.',
        3,
        2,
        NULL
      ),
(
        'L-Pour-Femme-37260',
        'L Pour Femme Laurelle London',
        'L',
        'for women',
        NULL,
        NULL,
        'Pink Pepper',
        'Peach, Lilac and Incense',
        'Amber and Patchouli',
        'amber,soft spicy,patchouli,warm spicy,floral',
        'L Pour FemmebyLaurelle Londonis a Aromatic Fruity fragrance for women. Top note is Pink Pepper; middle notes are Peach, Lilac and Incense; base notes are Amber and Patchouli.',
        4,
        1,
        NULL
      ),
(
        'L-Pour-Homme-37225',
        'L Pour Homme Laurelle London',
        'L',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,woody,warm spicy',
        'L Pour HommebyLaurelle Londonis a Woody Spicy fragrance for men.',
        3.2,
        5,
        NULL
      ),
(
        'Lady-Butterfly-37262',
        'Lady Butterfly Laurelle London',
        'Lady',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,white floral,honey,sweet,citrus',
        'Lady ButterflybyLaurelle Londonis a Amber Floral fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Laurelle-Rose-37284',
        'Laurelle Rose Laurelle London',
        'Laurelle',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,rose',
        'Laurelle RosebyLaurelle Londonis a Floral fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Laurelle-Rouge-37276',
        'Laurelle Rouge Laurelle London',
        'Laurelle',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Laurelle RougebyLaurelle Londonis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Laurelle-Sport-37229',
        'Laurelle Sport Laurelle London',
        'Laurelle',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Laurelle SportbyLaurelle Londonis a Aromatic fragrance for men.',
        4.5,
        2,
        NULL
      ),
(
        'Les-Couleurs-No-1-37167',
        'Les Couleurs No.1 Laurelle London',
        'Les',
        'for men',
        NULL,
        NULL,
        'Labdanum and Patchouli',
        'Ginger, Nutmeg and Pink Pepper',
        'Sandalwood and Cedar',
        'woody,warm spicy,patchouli,amber,fresh spicy',
        'Les Couleurs No.1byLaurelle Londonis a Woody Aromatic fragrance for men.Les Couleurs No.1was launched in 2015. Top notes are Labdanum and Patchouli; middle notes are Ginger, Nutmeg and Pink Pepper; base notes are Sandalwood and Cedar.',
        3,
        2,
        NULL
      ),
(
        'Les-Couleurs-No-1-Cool-Mint-37158',
        'Les Couleurs No.1 Cool Mint Laurelle London',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,aromatic,fresh spicy',
        'Les Couleurs No.1 Cool MintbyLaurelle Londonis a Aromatic Green fragrance for women.Les Couleurs No.1 Cool Mintwas launched in 2013.',
        NULL,
        NULL,
        NULL
      ),
(
        'Les-Couleurs-No-2-37169',
        'Les Couleurs No.2 Laurelle London',
        'Les',
        'for men',
        NULL,
        NULL,
        'Grapefruit and Orange',
        'Jasmine and Bay Leaf',
        'Oak and Guaiac Wood',
        'citrus,fresh spicy,white floral,woody,aromatic',
        'Les Couleurs No.2byLaurelle Londonis a Woody Aromatic fragrance for men.Les Couleurs No.2was launched in 2015. Top notes are Grapefruit and Orange; middle notes are Jasmine and Bay Leaf; base notes are Oak and Guaiac Wood.',
        4.67,
        3,
        NULL
      ),
(
        'Les-Couleurs-No-2-Chocolate-Orange-37160',
        'Les Couleurs No.2 Chocolate Orange Laurelle London',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,chocolate,sweet,warm spicy,cacao',
        'Les Couleurs No.2 Chocolate OrangebyLaurelle Londonis a Citrus Gourmand fragrance for women.Les Couleurs No.2 Chocolate Orangewas launched in 2013.',
        NULL,
        NULL,
        NULL
      ),
(
        'Les-Couleurs-No-3-37170',
        'Les Couleurs No.3 Laurelle London',
        'Les',
        'for men',
        NULL,
        NULL,
        'Bergamot and Lemon Verbena',
        'Bulgarian Rose, Nutmeg and Clary Sage',
        'Amber and Vanilla',
        'citrus,fresh spicy,aromatic,amber,vanilla',
        'Les Couleurs No.3byLaurelle Londonis a Amber Fougere fragrance for men.Les Couleurs No.3was launched in 2015. Top notes are Bergamot and Lemon Verbena; middle notes are Bulgarian Rose, Nutmeg and Clary Sage; base notes are Amber and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Les-Couleurs-No-3-Cotton-Candy-37163',
        'Les Couleurs No.3 Cotton Candy Laurelle London',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Les Couleurs No.3 Cotton CandybyLaurelle Londonis a Amber Vanilla fragrance for women.Les Couleurs No.3 Cotton Candywas launched in 2013.',
        4.25,
        4,
        NULL
      ),
(
        'Les-Couleurs-No-4-37171',
        'Les Couleurs No.4 Laurelle London',
        'Les',
        'for men',
        NULL,
        NULL,
        'Blood Orange and Grapefruit',
        'Cinnamon and Mint',
        'Amber and Leather',
        'citrus,amber,cinnamon,warm spicy,leather',
        'Les Couleurs No.4byLaurelle Londonis a Aromatic Spicy fragrance for men.Les Couleurs No.4was launched in 2015. Top notes are Blood Orange and Grapefruit; middle notes are Cinnamon and Mint; base notes are Amber and Leather.',
        2,
        1,
        NULL
      ),
(
        'Les-Couleurs-No-4-Hot-Chocolate-37166',
        'Les Couleurs No.4 Hot Chocolate Laurelle London',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'chocolate,warm spicy,sweet,cacao',
        'Les Couleurs No.4 Hot ChocolatebyLaurelle Londonis a Amber Vanilla fragrance for women.Les Couleurs No.4 Hot Chocolatewas launched in 2013.',
        3,
        1,
        NULL
      ),
(
        'Locked-37153',
        'Locked Laurelle London',
        'Locked',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'LockedbyLaurelle Londonis a Aromatic fragrance for men.Lockedwas launched in 2013.',
        4,
        5,
        NULL
      ),
(
        'Loves-Me-Loves-Me-Not-37264',
        'Loves Me Loves Me Not Laurelle London',
        'Loves',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral',
        'Loves Me Loves Me NotbyLaurelle Londonis a Floral fragrance for women.',
        4,
        9,
        NULL
      ),
(
        'Momentum-37227',
        'Momentum Laurelle London',
        'Momentum',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy',
        'MomentumbyLaurelle Londonis a Amber Spicy fragrance for men.',
        3.33,
        3,
        NULL
      ),
(
        'Momentum-Gold-37228',
        'Momentum Gold Laurelle London',
        'Momentum',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fruity,warm spicy,fresh,sweet',
        'Momentum GoldbyLaurelle Londonis a Citrus Aromatic fragrance for men.Momentum Goldwas launched in 2013.',
        3.2,
        5,
        NULL
      ),
(
        'Papparazzo-37263',
        'Papparazzo Laurelle London',
        'Papparazzo',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'PapparazzobyLaurelle Londonis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Papped-37173',
        'Papped Laurelle London',
        'Papped',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'PappedbyLaurelle Londonis a fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Refresh-37254',
        'Refresh Laurelle London',
        'Refresh',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'RefreshbyLaurelle Londonis a Aromatic fragrance for men.',
        3.25,
        4,
        NULL
      ),
(
        'Refresh-Gold-37287',
        'Refresh Gold Laurelle London',
        'Refresh',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Refresh GoldbyLaurelle Londonis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Refresh-Pink-37253',
        'Refresh Pink Laurelle London',
        'Refresh',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Refresh PinkbyLaurelle Londonis a fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'Royal-Blue-37152',
        'Royal Blue Laurelle London',
        'Royal',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Royal BluebyLaurelle Londonis a Aromatic fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sexxy-Shoo-Black-Stiletto-37241',
        'Sexxy Shoo Black Stiletto Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange',
        'Rose',
        'Sandalwood and Pink Pepper',
        'rose,citrus,woody,soft spicy,powdery',
        'Sexxy Shoo Black StilettobyLaurelle Londonis a Floral fragrance for women. Top note is Mandarin Orange; middle note is Rose; base notes are Sandalwood and Pink Pepper.',
        3.33,
        9,
        NULL
      ),
(
        'Sexxy-Shoo-Jungle-37245',
        'Sexxy Shoo Jungle Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Saffron and Apricot',
        'Jasmine and Honey',
        'Woody Notes and Musk',
        'warm spicy,honey,white floral,woody,metallic',
        'Sexxy Shoo JunglebyLaurelle Londonis a Floral Woody Musk fragrance for women. Top notes are Saffron and Apricot; middle notes are Jasmine and Honey; base notes are Woody Notes and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sexxy-Shoo-Limited-Edition-Gold-37234',
        'Sexxy Shoo Limited Edition Gold Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,citrus,white floral,fresh spicy',
        'Sexxy Shoo Limited Edition GoldbyLaurelle Londonis a Floral Fruity fragrance for women.',
        5,
        1,
        NULL
      ),
(
        'Sexxy-Shoo-Little-Black-Shoo-37248',
        'Sexxy Shoo Little Black Shoo Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange',
        'Rose and Floral Notes',
        'Pink Pepper and Sandalwood',
        'rose,citrus,soft spicy,woody,floral',
        'Sexxy Shoo Little Black ShoobyLaurelle Londonis a Floral fragrance for women. Top note is Mandarin Orange; middle notes are Rose and Floral Notes; base notes are Pink Pepper and Sandalwood.',
        3,
        4,
        NULL
      ),
(
        'Sexxy-Shoo-Little-Red-Shoo-37250',
        'Sexxy Shoo Little Red Shoo Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Sexxy Shoo Little Red ShoobyLaurelle Londonis a fragrance for women.Sexxy Shoo Little Red Shoowas launched in 2014.',
        3,
        2,
        NULL
      ),
(
        'Sexxy-Shoo-Little-White-Shoo-37247',
        'Sexxy Shoo Little White Shoo Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Fruity Notes',
        'Floral Fruity Notes',
        'Patchouli and Vanilla',
        'fruity,patchouli,vanilla,sweet,woody',
        'Sexxy Shoo Little White ShoobyLaurelle Londonis a Chypre Fruity fragrance for women. Top note is Fruity Notes; middle note is Floral Fruity Notes; base notes are Patchouli and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sexxy-Shoo-Neon-Nights-Miami-Yellow-37244',
        'Sexxy Shoo Neon Nights Miami Yellow Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Pineapple, Papaya and Mandarin Orange',
        'Peach and Sweet Notes',
        'Coconut, Sandalwood and Musk',
        'sweet,fruity,tropical,powdery,woody',
        'Sexxy Shoo Neon Nights Miami YellowbyLaurelle Londonis a Aromatic Fruity fragrance for women. Top notes are Pineapple, Papaya and Mandarin Orange; middle notes are Peach and Sweet Notes; base notes are Coconut, Sandalwood and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sexxy-Shoo-Neon-Nights-Pink-37243',
        'Sexxy Shoo Neon Nights Pink Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Pear, Papaya and Pomegranate',
        'Freesia and Lily-of-the-Valley',
        'White Musk and Amber',
        'fruity,sweet,floral,amber,white floral',
        'Sexxy Shoo Neon Nights PinkbyLaurelle Londonis a Floral Fruity fragrance for women. Top notes are Pear, Papaya and Pomegranate; middle notes are Freesia and Lily-of-the-Valley; base notes are White Musk and Amber.',
        4,
        1,
        NULL
      ),
(
        'Sexxy-Shoo-Neon-Nights-Vegas-Orange-37242',
        'Sexxy Shoo Neon Nights Vegas Orange Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,coconut,citrus,powdery',
        'Sexxy Shoo Neon Nights Vegas OrangebyLaurelle Londonis a Aromatic Fruity fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Sexxy-Shoo-Pink-37233',
        'Sexxy Shoo Pink Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Sorbet, Mango Blossom, Peach and Passionfruit',
        'Vanilla Orchid, Honeysuckle and Magnolia',
        'Almond and Amber',
        'fruity,floral,sweet,tropical,almond',
        'Sexxy Shoo PinkbyLaurelle Londonis a Aromatic Fruity fragrance for women.Sexxy Shoo Pinkwas launched in 2012. Top notes are Sorbet, Mango Blossom, Peach and Passionfruit; middle notes are Vanilla Orchid, Honeysuckle and Magnolia; base notes are Almond and Amber.',
        3.5,
        6,
        NULL
      ),
(
        'Sexxy-Shoo-Purple-Stiletto-37246',
        'Sexxy Shoo Purple Stiletto Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fruity,sweet,soft spicy,aquatic',
        'Sexxy Shoo Purple StilettobyLaurelle Londonis a Aromatic Fruity fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sexxy-Shoo-Red-37232',
        'Sexxy Shoo Red Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Orange, Bergamot and Peach',
        'Rose and Jasmine',
        'Vanilla and Patchouli',
        'citrus,vanilla,patchouli,rose,woody',
        'Sexxy Shoo RedbyLaurelle Londonis a Floral Fruity fragrance for women.Sexxy Shoo Redwas launched in 2012. Top notes are Orange, Bergamot and Peach; middle notes are Rose and Jasmine; base notes are Vanilla and Patchouli.',
        2.67,
        3,
        NULL
      ),
(
        'Sexxy-Shoo-Silver-37235',
        'Sexxy Shoo Silver Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        'Orange Blossom',
        'Rose',
        'Amber',
        'rose,white floral,citrus,amber,floral',
        'Sexxy Shoo SilverbyLaurelle Londonis a Floral fragrance for women. Top note is Orange Blossom; middle note is Rose; base note is Amber.',
        2,
        1,
        NULL
      ),
(
        'Sexxy-Shoo-Wild-Stripes-37240',
        'Sexxy Shoo Wild Stripes Laurelle London',
        'Sexxy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,musky,patchouli,fresh,woody',
        'Sexxy Shoo Wild StripesbyLaurelle Londonis a Floral Woody Musk fragrance for women.',
        2,
        1,
        NULL
      ),
(
        'Sexy-Shoo-Little-Gold-Shoo-37249',
        'Sexy Shoo Little Gold Shoo Laurelle London',
        'Sexy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Sexy Shoo Little Gold ShoobyLaurelle Londonis a fragrance for women.',
        2.75,
        4,
        NULL
      ),
(
        'Sexy-Shoo-Little-Pink-Shoo-37251',
        'Sexy Shoo Little Pink Shoo Laurelle London',
        'Sexy',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Sexy Shoo Little Pink ShoobyLaurelle Londonis a fragrance for women.',
        2,
        1,
        NULL
      ),
(
        'Sphere-Pour-Femme-37268',
        'Sphere Pour Femme Laurelle London',
        'Sphere',
        'for women',
        NULL,
        NULL,
        'Orange Blossom',
        'Jasmine',
        'Patchouli and Honey',
        'white floral,honey,patchouli,sweet,woody',
        'Sphere Pour FemmebyLaurelle Londonis a Amber Floral fragrance for women. Top note is Orange Blossom; middle note is Jasmine; base notes are Patchouli and Honey.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sphere-Pour-Homme-37131',
        'Sphere Pour Homme Laurelle London',
        'Sphere',
        'for men',
        NULL,
        NULL,
        'Grapefruit, Blood Orange and Mint',
        'Cinnamon, Rose and Spices',
        'Patchouli, Leather, White Woods and Amber',
        'warm spicy,cinnamon,citrus,woody,patchouli',
        'Sphere Pour HommebyLaurelle Londonis a Woody Spicy fragrance for men.Sphere Pour Hommewas launched in 2015. Top notes are Grapefruit, Blood Orange and Mint; middle notes are Cinnamon, Rose and Spices; base notes are Patchouli, Leather, White Woods and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sphere-Sport-37267',
        'Sphere Sport Laurelle London',
        'Sphere',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,fruity,floral,sweet,white floral',
        'Sphere SportbyLaurelle Londonis a Floral Fruity fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sweet-Pink-37261',
        'Sweet Pink Laurelle London',
        'Sweet',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Sweet PinkbyLaurelle Londonis a fragrance for women.',
        4.5,
        2,
        NULL
      ),
(
        'The-Mortal-Instruments-City-of-Bones-Angelic-Power-37286',
        'The Mortal Instruments City of Bones Angelic Power Laurelle London',
        'The',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,white floral,powdery,musky,vanilla',
        'The Mortal Instruments City of Bones Angelic PowerbyLaurelle Londonis a Floral fragrance for women.The Mortal Instruments City of Bones Angelic Powerwas launched in 2013.',
        NULL,
        NULL,
        NULL
      ),
(
        'The-Mortal-Instruments-City-of-Bones-Strength-37285',
        'The Mortal Instruments City of Bones Strength Laurelle London',
        'The',
        'for women',
        NULL,
        NULL,
        'Apple Blossom, Dewberry and Raspberry',
        'Peach',
        'Musk and Vanilla',
        'fruity,musky,powdery,vanilla,floral',
        'The Mortal Instruments City of Bones StrengthbyLaurelle Londonis a Aromatic Fruity fragrance for women.The Mortal Instruments City of Bones Strengthwas launched in 2013. Top notes are Apple Blossom, Dewberry and Raspberry; middle note is Peach; base notes are Musk and Vanilla.',
        NULL,
        NULL,
        NULL
      ),
(
        'Thomas-Black-Tous-Les-Jours-37172',
        'Thomas Black Tous Les Jours Laurelle London',
        'Thomas',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,aromatic,woody,balsamic,sweet',
        'Thomas Black Tous Les JoursbyLaurelle Londonis a Aromatic fragrance for men.',
        4.5,
        8,
        NULL
      ),
(
        'Together-Forever-37231',
        'Together Forever Laurelle London',
        'Together',
        'for women',
        NULL,
        NULL,
        'Citruses and Pink Pepper',
        'Floral Notes',
        'Patchouli and Amber',
        'floral,citrus,patchouli,soft spicy,fresh',
        'Together ForeverbyLaurelle Londonis a Chypre Floral fragrance for women.Together Foreverwas launched in 2013. Top notes are Citruses and Pink Pepper; middle note is Floral Notes; base notes are Patchouli and Amber.',
        4.08,
        12,
        NULL
      ),
(
        'True-Love-37288',
        'True Love Laurelle London',
        'True',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'True LovebyLaurelle Londonis a fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Truly-Lovely-37252',
        'Truly Lovely Laurelle London',
        'Truly',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral',
        'Truly LovelybyLaurelle Londonis a Floral fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Urban-Man-Dignity-37151',
        'Urban Man Dignity Laurelle London',
        'Urban',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Urban Man DignitybyLaurelle Londonis a Aromatic fragrance for men.',
        4,
        1,
        NULL
      ),
(
        'Voice-Mail-37226',
        'Voice Mail Laurelle London',
        'Voice',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Voice MailbyLaurelle Londonis a fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Ambre-Passion-4305',
        'Ambre Passion Laura Mercier',
        'Ambre',
        'for women',
        NULL,
        'Frank Voelkl',
        'Labdanum, Vanilla and Geranium',
        'Amber, Tonka Bean and Patchouli',
        'Musk, Sandalwood and Cedar',
        'amber,woody,vanilla,powdery,musky',
        'Ambre PassionbyLaura Mercieris a Amber fragrance for women.Ambre Passionwas launched in 2005. The nose behind this fragrance is Frank Voelkl. Top notes are Labdanum, Vanilla and Geranium; middle notes are Amber, Tonka Bean and Patchouli; base notes are Musk, Sandalwood and Cedar.',
        4.37,
        160,
        NULL
      ),
(
        'Ambre-Passion-Elixir-10505',
        'Ambre Passion Elixir Laura Mercier',
        'Ambre',
        'for women',
        NULL,
        'Frank Voelkl',
        NULL,
        NULL,
        NULL,
        'rose,amber,warm spicy,fresh spicy,white floral',
        'Ambre Passion ElixirbyLaura Mercieris a Amber fragrance for women.Ambre Passion Elixirwas launched in 2010. The nose behind this fragrance is Frank Voelkl.',
        4.5,
        16,
        NULL
      ),
(
        'Eau-de-Lune-4304',
        'Eau de Lune Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        'Violet, White Flowers, Ylang-Ylang and Mandarin Orange',
        'Lily-of-the-Valley, Frangipani, White Peach, Orange Blossom and Rose',
        'Orris Root, Musk, Woodsy Notes and Amber',
        'white floral,powdery,floral,violet,citrus',
        'Eau de LunebyLaura Mercieris a Floral fragrance for women.Eau de Lunewas launched in 2002. Top notes are Violet, White Flowers, Ylang-Ylang and Mandarin Orange; middle notes are Lily-of-the-Valley, Frangipani, White Peach, Orange Blossom and Rose; base notes are Orris Root, Musk, Woodsy Notes and Amber.',
        3.82,
        125,
        NULL
      ),
(
        'Eau-Gourmande-Almond-Coconut-3437',
        'Eau Gourmande Almond Coconut Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,sweet,coconut,almond,nutty',
        'Eau Gourmande Almond CoconutbyLaura Mercieris a Amber Vanilla fragrance for women.Eau Gourmande Almond Coconutwas launched in 2006.',
        3.9,
        343,
        NULL
      ),
(
        'Eau-Gourmande-Ambre-Vanille-18364',
        'Eau Gourmande Ambre Vanille Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        'Orchid, Heliotrope and Tangerine',
        'Almond and Coconut',
        'Sandalwood',
        'almond,sweet,powdery,floral,coconut',
        'Eau Gourmande Ambre VanillebyLaura Mercieris a Amber Vanilla fragrance for women.Eau Gourmande Ambre Vanillewas launched in 2013. Top notes are Orchid, Heliotrope and Tangerine; middle notes are Almond and Coconut; base note is Sandalwood.',
        4.12,
        466,
        NULL
      ),
(
        'Eau-Gourmande-Creme-Brulee-3438',
        'Eau Gourmande Creme Brulee Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,caramel,lactonic,vanilla',
        'Eau Gourmande Creme BruleebyLaura Mercieris a Amber Vanilla fragrance for women.Eau Gourmande Creme Bruleewas launched in 2006.',
        3.73,
        231,
        NULL
      ),
(
        'Eau-Gourmande-Creme-de-Pistache-10147',
        'Eau Gourmande Creme de Pistache Laura Mercier',
        'Eau',
        'for women',
        NULL,
        'Calice Becker',
        NULL,
        NULL,
        NULL,
        'sweet,nutty,woody,vanilla,lactonic',
        'Eau Gourmande Creme de PistachebyLaura Mercieris a Floral Fruity Gourmand fragrance for women. The nose behind this fragrance is Calice Becker.',
        4,
        286,
        NULL
      ),
(
        'Eau-Gourmande-Fresh-Fig-12191',
        'Eau Gourmande Fresh Fig Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        'black fig, Fruity Notes and Citruses',
        'Apricot, Ylang-Ylang and Cassia',
        'Musk, Vanille and Sandalwood',
        'fruity,sweet,woody,powdery,musky',
        'Eau Gourmande Fresh FigbyLaura Mercieris a Floral Fruity fragrance for women.Eau Gourmande Fresh Figwas launched in 2011. Top notes are black fig, Fruity Notes and Citruses; middle notes are Apricot, Ylang-Ylang and Cassia; base notes are Musk, Vanille and Sandalwood.',
        3.74,
        170,
        NULL
      ),
(
        'Eau-Gourmande-Marrons-Glaces-3439',
        'Eau Gourmande Marrons Glaces Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,amber,floral,white floral',
        'Eau Gourmande Marrons GlacesbyLaura Mercieris a Floral Fruity Gourmand fragrance for women.Eau Gourmande Marrons Glaceswas launched in 2006.',
        4.08,
        40,
        NULL
      ),
(
        'Eau-Gourmande-Tarte-Au-Citron-3440',
        'Eau Gourmande Tarte Au Citron Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,vanilla,aromatic,woody',
        'Eau Gourmande Tarte Au CitronbyLaura Mercieris a Citrus Gourmand fragrance for women.Eau Gourmande Tarte Au Citronwas launched in 2006.',
        4.17,
        114,
        NULL
      ),
(
        'Eau-Gourmande-Vanille-Gourmande-3441',
        'Eau Gourmande Vanille Gourmande Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,vanilla,woody,floral,sweet',
        'Eau Gourmande Vanille GourmandebyLaura Mercieris a Amber Vanilla fragrance for women.Eau Gourmande Vanille Gourmandewas launched in 2006.',
        4.17,
        333,
        NULL
      ),
(
        'Eau-Gourmande-Violette-3435',
        'Eau Gourmande Violette Laura Mercier',
        'Eau',
        'for women',
        NULL,
        NULL,
        'Violet Leaf and Black Currant',
        'Mimosa and Peony',
        'Raspberry, Vetiver and Musk',
        'fruity,ozonic,aquatic,floral,green',
        'Eau Gourmande ViolettebyLaura Mercieris a Floral Fruity fragrance for women.Eau Gourmande Violettewas launched in 2008. Top notes are Violet Leaf and Black Currant; middle notes are Mimosa and Peony; base notes are Raspberry, Vetiver and Musk.',
        3.72,
        105,
        NULL
      ),
(
        'L-Heure-Magique-4303',
        'L''Heure Magique Laura Mercier',
        'L''Heure',
        'for women',
        NULL,
        'Cecile Krakower',
        'Bergamot and Jasmine',
        'White Rose, Geranium and Spicy Notes',
        'Musk, Amber and Sandalwood',
        'musky,powdery,rose,warm spicy,fresh spicy',
        'L''Heure MagiquebyLaura Mercieris a Floral Woody Musk fragrance for women.L''Heure Magiquewas launched in 2001. L''Heure Magique was created by James Bell and Cecile Krakower. Top notes are Bergamot and Jasmine; middle notes are White Rose, Geranium and Spicy Notes; base notes are Musk, Amber and Sandalwood.',
        4.18,
        133,
        NULL
      ),
(
        'Lumiere-D-Ambre-18363',
        'Lumiere D''Ambre Laura Mercier',
        'Lumiere',
        'for women',
        NULL,
        NULL,
        'Lotus, Pink Pepper and Mandarin Orange',
        'Vanilla Orchid, Rose and Jasmine',
        'Amber and Musk',
        'floral,amber,powdery,rose,musky',
        'Lumiere D''AmbrebyLaura Mercieris a Amber fragrance for women.Lumiere D''Ambrewas launched in 2013. Top notes are Lotus, Pink Pepper and Mandarin Orange; middle notes are Vanilla Orchid, Rose and Jasmine; base notes are Amber and Musk.',
        4.19,
        57,
        NULL
      ),
(
        'Minuit-Enchante-10168',
        'Minuit Enchante Laura Mercier',
        'Minuit',
        'for women',
        NULL,
        NULL,
        'Pepper, Clove, Ginger and Juniper',
        'Jasmine, Rose, Tuberose and Peach',
        'Sandalwood, Amber, Vanille, Guaiac Wood, Myrhh, Musk, Virginia Cedar, Benzoin, French labdanum and Agarwood (Oud)',
        'woody,warm spicy,amber,powdery,vanilla',
        'Minuit EnchantebyLaura Mercieris a Amber Woody fragrance for women. Top notes are Pepper, Clove, Ginger and Juniper; middle notes are Jasmine, Rose, Tuberose and Peach; base notes are Sandalwood, Amber, Vanille, Guaiac Wood, Myrhh, Musk, Virginia Cedar, Benzoin, French labdanum and Agarwood (Oud).',
        4.55,
        49,
        NULL
      ),
(
        'Neroli-Eau-de-Parfum-3436',
        'Neroli Eau de Parfum Laura Mercier',
        'Neroli',
        'for women',
        NULL,
        'Maurice Roucel',
        'Bitter Orange and Lemon Peel',
        'Neroli, Jasmine, Freesia and Peony',
        'Vanilla, Amber, Musk and Sandalwood',
        'citrus,white floral,floral,fresh,vanilla',
        'Neroli Eau de ParfumbyLaura Mercieris a Floral fragrance for women.Neroli Eau de Parfumwas launched in 2008. The nose behind this fragrance is Maurice Roucel. Top notes are Bitter Orange and Lemon Peel; middle notes are Neroli, Jasmine, Freesia and Peony; base notes are Vanilla, Amber, Musk and Sandalwood.',
        3.98,
        96,
        NULL
      ),
(
        'Nuits-Enchantees-4306',
        'Nuits Enchantees Laura Mercier',
        'Nuits',
        'for women',
        NULL,
        'James Krivda',
        'Cardamom and Mandarin Orange',
        'Guaiac Wood, Pimento, Tuberose, Rose, Ginger and Cedar',
        'Patchouli, Coffee, Bourbon Vanilla, Sandalwood, Amber, Musk, Vetiver and Cedar',
        'woody,warm spicy,powdery,patchouli,coffee',
        'Nuits EnchanteesbyLaura Mercieris a Amber fragrance for women.Nuits Enchanteeswas launched in 2008. The nose behind this fragrance is James Krivda. Top notes are Cardamom and Mandarin Orange; middle notes are Guaiac Wood, Pimento, Tuberose, Rose, Ginger and Cedar; base notes are Patchouli, Coffee, Bourbon Vanilla, Sandalwood, Amber, Musk, Vetiver and Cedar.',
        4.51,
        83,
        NULL
      ),
(
        'Tea-Menthe-Citron-38550',
        'Tea Menthe Citron Laura Mercier',
        'Tea',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,aromatic,warm spicy,fresh spicy,woody',
        'Tea Menthe CitronbyLaura Mercieris a Aromatic Spicy fragrance for women and men.Tea Menthe Citronwas launched in 2016.',
        4.47,
        51,
        NULL
      ),
(
        'Verbena-Infusion-25996',
        'Verbena Infusion Laura Mercier',
        'Verbena',
        'for women',
        NULL,
        NULL,
        'Grapefruit, Mint and Black Currant',
        'Verbena, Magnolia and Rose',
        'Cedar, Plum and White Amber',
        'citrus,aromatic,green,fresh spicy,fruity',
        'Verbena InfusionbyLaura Mercieris a Citrus Aromatic fragrance for women.Verbena Infusionwas launched in 2014. Top notes are Grapefruit, Mint and Black Currant; middle notes are Verbena, Magnolia and Rose; base notes are Cedar, Plum and White Amber.',
        4.43,
        56,
        NULL
      ),
(
        'Almond-Coconut-Eau-de-Parfum-82510',
        'Almond Coconut Eau de Parfum Laura Mercier',
        'Almond',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,almond,sweet,coconut,nutty',
        'Almond Coconut Eau de ParfumbyLaura Mercieris a Amber Vanilla fragrance for women and men. This is a new fragrance.Almond Coconut Eau de Parfumwas launched in 2022.',
        4.12,
        52,
        NULL
      ),
(
        'Ambre-Vanille-Eau-de-Parfum-82508',
        'Ambre Vanille Eau de Parfum Laura Mercier',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        'Orchid and Tangerine',
        'Brown sugar, Almond and Heliotrope',
        'Coconut and Sandalwood',
        'sweet,coconut,almond,powdery,floral',
        'Ambre Vanille Eau de ParfumbyLaura Mercieris a Amber Vanilla fragrance for women and men. This is a new fragrance.Ambre Vanille Eau de Parfumwas launched in 2022. Top notes are Orchid and Tangerine; middle notes are Brown sugar, Almond and Heliotrope; base notes are Coconut and Sandalwood.',
        4.12,
        58,
        NULL
      ),
(
        'Neroli-du-Sud-Eau-de-Parfum-82507',
        'Néroli du Sud Eau de Parfum Laura Mercier',
        'Néroli',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,lavender,aromatic,fresh spicy,herbal',
        'Néroli du Sud Eau de ParfumbyLaura Mercieris a fragrance for women and men. This is a new fragrance.Néroli du Sud Eau de Parfumwas launched in 2022.',
        3.67,
        15,
        NULL
      ),
(
        'Vanille-Eau-de-Parfum-82509',
        'Vanille Eau de Parfum Laura Mercier',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        'Vanilla and Vanilla Orchid',
        'Vanilla, Heliotrope, Daylily and Musk',
        'Bourbon Vanilla, Sandalwood and Amber',
        'powdery,vanilla,amber,floral,musky',
        'Vanille Eau de ParfumbyLaura Mercieris a Amber Vanilla fragrance for women and men. This is a new fragrance.Vanille Eau de Parfumwas launched in 2022. Top notes are Vanilla and Vanilla Orchid; middle notes are Vanilla, Heliotrope, Daylily and Musk; base notes are Bourbon Vanilla, Sandalwood and Amber.',
        3.92,
        26,
        NULL
      );
