
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Perpetua-61174',
        'Perpetua Fulton & Roark',
        'Perpetua',
        'for men',
        NULL,
        NULL,
        'Neroli and Lemon',
        'Amber and Jasmine',
        'Coumarin and Cedar',
        'woody,citrus,white floral,aromatic,amber',
        'PerpetuabyFulton & Roarkis a Woody Aquatic fragrance for men.Perpetuawas launched in 2020. Top notes are Neroli and Lemon; middle notes are Amber and Jasmine; base notes are Coumarin and Cedar.',
        3.67,
        6,
        NULL
      ),
(
        'Ramble-87067',
        'Ramble Fulton & Roark',
        'Ramble',
        'for women and men',
        NULL,
        'Clement Gavarry',
        'Pomelo, Black Pepper and Bamboo Leaf',
        'Balsam Fir, elemi and Lavender',
        'Oakmoss and Patchouli',
        'fresh spicy,woody,aromatic,earthy,citrus',
        'RamblebyFulton & Roarkis a Chypre fragrance for women and men.Ramblewas launched in 2021. The nose behind this fragrance is Clement Gavarry. Top notes are Pomelo, Black Pepper and Bamboo Leaf; middle notes are Balsam Fir, elemi and Lavender; base notes are Oakmoss and Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Shackleford-39939',
        'Shackleford Fulton & Roark',
        'Shackleford',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,powdery,warm spicy,animalic',
        'ShacklefordbyFulton & Roarkis a Amber Woody fragrance for men.Shacklefordwas launched in 2013.',
        3.83,
        6,
        NULL
      ),
(
        'Sterling-61175',
        'Sterling Fulton & Roark',
        'Sterling',
        'for men',
        NULL,
        NULL,
        'Bergamot and White Musk',
        'Tobacco and Amber',
        'Leather and Vanilla',
        'leather,vanilla,tobacco,sweet,animalic',
        'SterlingbyFulton & Roarkis a Amber fragrance for men.Sterlingwas launched in 2020. Top notes are Bergamot and White Musk; middle notes are Tobacco and Amber; base notes are Leather and Vanilla.',
        3.35,
        17,
        NULL
      ),
(
        'Thousand-Palms-89070',
        'Thousand Palms Fulton & Roark',
        'Thousand',
        'for women and men',
        NULL,
        NULL,
        'Green Pepper, Petitgrain and Pink Pepper',
        'Tuberose, Coriander and Mango',
        'Patchouli and Amberwood',
        'aromatic,woody,green,soft spicy,tuberose',
        'Thousand PalmsbyFulton & Roarkis a Aromatic Fruity fragrance for women and men. This is a new fragrance.Thousand Palmswas launched in 2023. Top notes are Green Pepper, Petitgrain and Pink Pepper; middle notes are Tuberose, Coriander and Mango; base notes are Patchouli and Amberwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Tybee-39940',
        'Tybee Fulton & Roark',
        'Tybee',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,woody,powdery',
        'TybeebyFulton & Roarkis a Woody Floral Musk fragrance for men.Tybeewas launched in 2013.',
        3.8,
        10,
        NULL
      ),
(
        'Acqua-by-Armand-Dupree-37056',
        'Acqua by Armand Dupree Fuller Cosmetics®',
        'Acqua',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh,warm spicy,aquatic,green',
        'Acqua by Armand DupreebyFuller Cosmetics®is a Aromatic Fougere fragrance for men.',
        3.56,
        9,
        NULL
      ),
(
        'Aquarelle-36951',
        'Aquarelle Fuller Cosmetics®',
        'Aquarelle',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,floral,musky',
        'AquarellebyFuller Cosmetics®is a Amber Floral fragrance for women.',
        3.33,
        3,
        NULL
      ),
(
        'Armand-Dupree-Clasica-37055',
        'Armand Dupree Clásica Fuller Cosmetics®',
        'Armand',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,green,woody,musky',
        'Armand Dupree ClásicabyFuller Cosmetics®is a Amber Woody fragrance for men.',
        3.1,
        10,
        NULL
      ),
(
        'Armand-Dupree-Glam-36959',
        'Armand Dupree Glam Fuller Cosmetics®',
        'Armand',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,musky',
        'Armand Dupree GlambyFuller Cosmetics®is a Amber Floral fragrance for women.',
        3.33,
        6,
        NULL
      ),
(
        'Azul-Life-37058',
        'Azul Life Fuller Cosmetics®',
        'Azul',
        'for women',
        NULL,
        NULL,
        'Citruses and Apple',
        'Geranium and Black Pepper',
        'Amber, Cedar and Vetiver',
        'citrus,fresh,woody,aromatic,fresh spicy',
        'Azul LifebyFuller Cosmetics®is a Aromatic fragrance for women. Top notes are Citruses and Apple; middle notes are Geranium and Black Pepper; base notes are Amber, Cedar and Vetiver.',
        4,
        2,
        NULL
      ),
(
        'BeeFun-36919',
        'BeeFun Fuller Cosmetics®',
        'BeeFun',
        'for women',
        NULL,
        NULL,
        'Peach, Tangerine and Raspberry',
        'Vanilla',
        'Sandalowood',
        'fruity,sweet,citrus,powdery,vanilla',
        'BeeFunbyFuller Cosmetics®is a Floral Green fragrance for women. Top notes are Peach, Tangerine and Raspberry; middle note is Vanilla; base note is Sandalowood.',
        4,
        2,
        NULL
      ),
(
        'Bleu-by-Armand-Dupree-37051',
        'Bleu by Armand Dupree Fuller Cosmetics®',
        'Bleu',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,woody',
        'Bleu by Armand DupreebyFuller Cosmetics®is a Woody Aromatic fragrance for men.',
        4,
        1,
        NULL
      ),
(
        'Colibri-Magic-36956',
        'Colibrí Magic Fuller Cosmetics®',
        'Colibrí',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,sweet',
        'Colibrí MagicbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        3.25,
        4,
        NULL
      ),
(
        'Corpus-37059',
        'Corpus Fuller Cosmetics®',
        'Corpus',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,woody',
        'CorpusbyFuller Cosmetics®is a Woody Aromatic fragrance for men.',
        4,
        1,
        NULL
      ),
(
        'EXCLUSIVE-37061',
        'EXCLUSIVE Fuller Cosmetics®',
        'EXCLUSIVE',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green',
        'EXCLUSIVEbyFuller Cosmetics®is a Aromatic Green fragrance for men.',
        4,
        2,
        NULL
      ),
(
        'Fashion-Chic-36954',
        'Fashion Chic Fuller Cosmetics®',
        'Fashion',
        'for women',
        NULL,
        NULL,
        'Ylang-Ylang, Jasmine and Damask Rose',
        'Red Apple and Apricot',
        'Cedar and Musk',
        'woody,fruity,sweet,musky,powdery',
        'Fashion ChicbyFuller Cosmetics®is a Floral Fruity fragrance for women. Top notes are Ylang-Ylang, Jasmine and Damask Rose; middle notes are Red Apple and Apricot; base notes are Cedar and Musk.',
        5,
        1,
        NULL
      ),
(
        'Floral-s-Secret-In-Green-36968',
        'Floral''s Secret (In Green) Fuller Cosmetics®',
        'Floral''s',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,green',
        'Floral''s Secret (In Green)byFuller Cosmetics®is a Floral Green fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Floral-s-Secret-In-Pink-36966',
        'Floral''s Secret (In Pink) Fuller Cosmetics®',
        'Floral''s',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,musky,woody,powdery',
        'Floral''s Secret (In Pink)byFuller Cosmetics®is a Floral Woody Musk fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Glenda-by-Fuller-36949',
        'Glenda by Fuller Fuller Cosmetics®',
        'Glenda',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,warm spicy,amber',
        'Glenda by FullerbyFuller Cosmetics®is a Amber Floral fragrance for women.',
        3.5,
        2,
        NULL
      ),
(
        'Hola-Bebe-36960',
        'Hola Bebé Fuller Cosmetics®',
        'Hola',
        'for women',
        NULL,
        NULL,
        'Strawberry, Peach and Apple',
        'Magnolia and Peony',
        'Vanilla and White Woods',
        'fruity,floral,fresh,sweet,vanilla',
        'Hola BebébyFuller Cosmetics®is a Amber Floral fragrance for women. Top notes are Strawberry, Peach and Apple; middle notes are Magnolia and Peony; base notes are Vanilla and White Woods.',
        3.75,
        4,
        NULL
      ),
(
        'Inciter-36930',
        'Inciter Fuller Cosmetics®',
        'Inciter',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,musky',
        'InciterbyFuller Cosmetics®is a Amber fragrance for women.',
        3.5,
        2,
        NULL
      ),
(
        'Lady-Love-36964',
        'Lady Love Fuller Cosmetics®',
        'Lady',
        'for women',
        NULL,
        NULL,
        'Floral Notes',
        'Fruity Notes',
        'Musk',
        'fruity,sweet,floral,musky',
        'Lady LovebyFuller Cosmetics®is a Floral Fruity fragrance for women. Top note is Floral Notes; middle note is Fruity Notes; base note is Musk.',
        4.5,
        2,
        NULL
      ),
(
        'Marco-Antonio-Solis-37054',
        'Marco Antonio Solis Fuller Cosmetics®',
        'Marco',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,warm spicy,green,fresh',
        'Marco Antonio SolisbyFuller Cosmetics®is a Amber Fougere fragrance for men.',
        2.83,
        6,
        NULL
      ),
(
        'Mysterious-Oriental-37052',
        'Mysterious Oriental Fuller Cosmetics®',
        'Mysterious',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,woody',
        'Mysterious OrientalbyFuller Cosmetics®is a Woody Aromatic fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Passion-by-Armand-Dupree-37057',
        'Passion by Armand Dupree Fuller Cosmetics®',
        'Passion',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,warm spicy,amber,sweet,woody',
        'Passion by Armand DupreebyFuller Cosmetics®is a Amber Woody fragrance for men.',
        5,
        2,
        NULL
      ),
(
        'Pink-36970',
        'Pink Fuller Cosmetics®',
        'Pink',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet',
        'PinkbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Rockin-Girl-36953',
        'Rockin Girl Fuller Cosmetics®',
        'Rockin',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity',
        'Rockin GirlbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        4.5,
        4,
        NULL
      ),
(
        'Scappare-Fly-37053',
        'Scappare Fly Fuller Cosmetics®',
        'Scappare',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        'Coumarin, Citruses, Herbal Notes, Spicy Notes and Lavender',
        'warm spicy,citrus,green,vanilla,aromatic',
        'Scappare FlybyFuller Cosmetics®is a Aromatic Fougere fragrance for men. base notes are Coumarin, Citruses, Herbal Notes, Spicy Notes and Lavender.',
        4.5,
        2,
        NULL
      ),
(
        'SCAPPARE-RED-37060',
        'SCAPPARE RED Fuller Cosmetics®',
        'SCAPPARE',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,green,woody,sweet',
        'SCAPPARE REDbyFuller Cosmetics®is a Woody Aromatic fragrance for men.',
        4,
        4,
        NULL
      ),
(
        'Sensual-Fresh-36948',
        'Sensual Fresh Fuller Cosmetics®',
        'Sensual',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green',
        'Sensual FreshbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        4.25,
        4,
        NULL
      ),
(
        'Sensual-Heart-36929',
        'Sensual Heart Fuller Cosmetics®',
        'Sensual',
        'for women',
        NULL,
        NULL,
        'Citruses and Raspberry',
        'Magnolia and Lily-of-the-Valley',
        'Vanilla Absolute, Cashmere Musk and Amber',
        'vanilla,floral,citrus,powdery,sweet',
        'Sensual HeartbyFuller Cosmetics®is a Amber Woody fragrance for women. Top notes are Citruses and Raspberry; middle notes are Magnolia and Lily-of-the-Valley; base notes are Vanilla Absolute, Cashmere Musk and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sensual-Intense-36928',
        'Sensual Intense Fuller Cosmetics®',
        'Sensual',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange, Guava and Caramel',
        'Freesia and Blue Lotus',
        'Violet and Vanilla Orchid',
        'floral,violet,caramel,citrus,powdery',
        'Sensual IntensebyFuller Cosmetics®is a Amber Floral fragrance for women. Top notes are Mandarin Orange, Guava and Caramel; middle notes are Freesia and Blue Lotus; base notes are Violet and Vanilla Orchid.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sophie-Rose-36922',
        'Sophie Rose Fuller Cosmetics®',
        'Sophie',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        'Sophie RosebyFuller Cosmetics®is a Floral Green fragrance for women.',
        4.2,
        5,
        NULL
      ),
(
        'Tender-Pink-36952',
        'Tender Pink Fuller Cosmetics®',
        'Tender',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,sweet',
        'Tender PinkbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        4.75,
        4,
        NULL
      ),
(
        'Violet-36957',
        'Violet Fuller Cosmetics®',
        'Violet',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,violet,powdery,sweet',
        'VioletbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Body-Mist-COOL-STAR-36965',
        'Body Mist COOL STAR Fuller Cosmetics®',
        'Body',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,musky,woody,powdery',
        'Body Mist COOL STARbyFuller Cosmetics®is a Floral Woody Musk fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Body-Mist-PEACE-CHIC-36955',
        'Body Mist PEACE CHIC Fuller Cosmetics®',
        'Body',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,sweet',
        'Body Mist PEACE CHICbyFuller Cosmetics®is a Floral Fruity fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Body-Mist-SEXY-KISS-36967',
        'Body Mist SEXY KISS Fuller Cosmetics®',
        'Body',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,sweet',
        'Body Mist SEXY KISSbyFuller Cosmetics®is a Floral Fruity Gourmand fragrance for women.',
        2,
        1,
        NULL
      ),
(
        'Cherry-Colorfun-36950',
        'Cherry Colorfun Fuller Cosmetics®',
        'Cherry',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,cherry,floral,sweet,warm spicy',
        'Cherry ColorfunbyFuller Cosmetics®is a Amber Floral fragrance for women.',
        5,
        1,
        NULL
      ),
(
        'Colonia-Azul-36926',
        'Colonia Azul Fuller Cosmetics®',
        'Colonia',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet',
        'Colonia AzulbyFuller Cosmetics®is a Floral Green fragrance for women.',
        4.4,
        5,
        NULL
      ),
(
        'Colonia-Morada-36963',
        'Colonia Morada Fuller Cosmetics®',
        'Colonia',
        'for women',
        NULL,
        NULL,
        'Tangerine and Pineapple',
        'Water Lily and Raspberry',
        'Peach and Amber',
        'citrus,fruity,sweet,floral,aquatic',
        'Colonia MoradabyFuller Cosmetics®is a Citrus fragrance for women. Top notes are Tangerine and Pineapple; middle notes are Water Lily and Raspberry; base notes are Peach and Amber.',
        4.33,
        6,
        NULL
      ),
(
        'Hello-Kitty-Navidad-36969',
        'Hello Kitty Navidad Fuller Cosmetics®',
        'Hello',
        'for women',
        NULL,
        NULL,
        'Peach, Green Apple and Pear',
        'Tiare Flower',
        'Coconut Milk and Vanilla',
        'fruity,sweet,vanilla,white floral,coconut',
        'Hello Kitty NavidadbyFuller Cosmetics®is a Amber Floral fragrance for women. Top notes are Peach, Green Apple and Pear; middle note is Tiare Flower; base notes are Coconut Milk and Vanilla.',
        4.29,
        14,
        NULL
      ),
(
        'Like-U-36961',
        'Like U Fuller Cosmetics®',
        'Like',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral',
        'Like UbyFuller Cosmetics®is a Floral fragrance for women.',
        4,
        2,
        NULL
      ),
(
        'Like-U-Bloom-36958',
        'Like U Bloom Fuller Cosmetics®',
        'Like',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,warm spicy,amber,sweet',
        'Like U BloombyFuller Cosmetics®is a Amber Floral fragrance for women.',
        4,
        1,
        NULL
      ),
(
        'Like-U-Clear-36924',
        'Like U Clear Fuller Cosmetics®',
        'Like',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green',
        'Like U ClearbyFuller Cosmetics®is a Floral Green fragrance for women.',
        3.75,
        4,
        NULL
      ),
(
        'Angel-Dust-73921',
        'Angel Dust Fugazzi',
        'Angel',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,powdery,woody,amber,fresh spicy',
        'Angel DustbyFugazziis a Woody fragrance for women and men.Angel Dustwas launched in 2021.',
        3.96,
        294,
        NULL
      ),
(
        'Cash-Flower-81519',
        'Cash Flower Fugazzi',
        'Cash',
        'for women and men',
        NULL,
        NULL,
        'Rose Petals and Rose',
        'Pepper and Cashmere Wood',
        'Musk, Sandalwood and Amber',
        'rose,musky,powdery,fresh spicy,floral',
        'Cash FlowerbyFugazziis a fragrance for women and men. This is a new fragrance.Cash Flowerwas launched in 2023. Top notes are Rose Petals and Rose; middle notes are Pepper and Cashmere Wood; base notes are Musk, Sandalwood and Amber.',
        3.52,
        42,
        NULL
      ),
(
        'Fugazzi-Parfum-1-59675',
        'Fugazzi Parfum 1 Fugazzi',
        'Fugazzi',
        'for women and men',
        NULL,
        NULL,
        'Black Currant, Citruses, Mandarin Orange and Peppermint',
        'Davana, Pink Pepper, Frankincense and Orange Blossom',
        'Patchouli, Sandalwood, Musk and Cedar',
        'woody,aromatic,citrus,green,fruity',
        'Fugazzi Parfum 1byFugazziis a Woody Spicy fragrance for women and men.Fugazzi Parfum 1was launched in 2018. Top notes are Black Currant, Citruses, Mandarin Orange and Peppermint; middle notes are Davana, Pink Pepper, Frankincense and Orange Blossom; base notes are Patchouli, Sandalwood, Musk and Cedar.',
        3.95,
        180,
        NULL
      ),
(
        'Fugazzi-Parfum-2-OUD-Of-Office-59676',
        'Fugazzi Parfum 2 OUD Of Office Fugazzi',
        'Fugazzi',
        'for women and men',
        NULL,
        NULL,
        'Watery Notes and Bergamot',
        'Floral Notes, Jasmine, Incense and Clover',
        'Leather, Musk, Moss, Vetiver, Sandalwood and Agarwood (Oud)',
        'floral,white floral,woody,aquatic,earthy',
        'Fugazzi Parfum 2 OUD Of OfficebyFugazziis a Woody Aromatic fragrance for women and men.Fugazzi Parfum 2 OUD Of Officewas launched in 2019. Top notes are Watery Notes and Bergamot; middle notes are Floral Notes, Jasmine, Incense and Clover; base notes are Leather, Musk, Moss, Vetiver, Sandalwood and Agarwood (Oud).',
        1.86,
        7,
        NULL
      ),
(
        'Fugazzi-Parfum-3-RestatHome-59677',
        'Fugazzi Parfum 3 Rest@Home Fugazzi',
        'Fugazzi',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, White Iris, Pink Pepper, Juniper Berries and Ginger',
        'Leather, Iris, Magnolia and Amber',
        'Cedar, Vetiver, Sandalwood and Tonka Bean',
        'woody,leather,aromatic,citrus,animalic',
        'Fugazzi Parfum 3 Rest@HomebyFugazziis a Amber Floral fragrance for women and men.Fugazzi Parfum 3 Rest@Homewas launched in 2019. Top notes are Bergamot, White Iris, Pink Pepper, Juniper Berries and Ginger; middle notes are Leather, Iris, Magnolia and Amber; base notes are Cedar, Vetiver, Sandalwood and Tonka Bean.',
        3,
        6,
        NULL
      ),
(
        'Fugazzi-Parfum-4-Workaholic-59678',
        'Fugazzi Parfum 4 Workaholic Fugazzi',
        'Fugazzi',
        'for women and men',
        NULL,
        NULL,
        'Floral Notes',
        'Coffee and Bulgarian Rose',
        'Vanilla, White Musk and Amber',
        'coffee,floral,warm spicy,vanilla,musky',
        'Fugazzi Parfum 4 WorkaholicbyFugazziis a Amber Spicy fragrance for women and men.Fugazzi Parfum 4 Workaholicwas launched in 2019. Top note is Floral Notes; middle notes are Coffee and Bulgarian Rose; base notes are Vanilla, White Musk and Amber.',
        3.51,
        150,
        NULL
      ),
(
        'Goudh-66537',
        'Goudh Fugazzi',
        'Goudh',
        'for women and men',
        NULL,
        NULL,
        'Methyl Pamplemousse, Jasmine Sambac, Lily-of-the-Valley and Mandarin Orange',
        'Black Currant, Bulgarian Rose, Leather, Musk, Patchouli and Ambergris',
        'Agarwood (Oud), Benzoin, Java vetiver oil and Sandalwood',
        'oud,citrus,woody,amber,white floral',
        'GoudhbyFugazziis a Floral Woody Musk fragrance for women and men.Goudhwas launched in 2020. Top notes are Methyl Pamplemousse, Jasmine Sambac, Lily-of-the-Valley and Mandarin Orange; middle notes are Black Currant, Bulgarian Rose, Leather, Musk, Patchouli and Ambergris; base notes are Agarwood (Oud), Benzoin, Java vetiver oil and Sandalwood.',
        3.71,
        108,
        NULL
      ),
(
        'In-Love-With-The-Cocos-66538',
        'In Love With The Cocos Fugazzi',
        'In',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Lemon Zest',
        'Coconut Water, Orange Blossom, Rose and Geranium',
        'Musk, Amber and Ambrette (Musk Mallow)',
        'citrus,white floral,musky,fresh spicy,rose',
        'In Love With The CocosbyFugazziis a Floral Fruity fragrance for women and men.In Love With The Cocoswas launched in 2020. Top notes are Bergamot and Lemon Zest; middle notes are Coconut Water, Orange Blossom, Rose and Geranium; base notes are Musk, Amber and Ambrette (Musk Mallow).',
        3.63,
        134,
        NULL
      ),
(
        'Mood-Swings-90485',
        'Mood Swings Fugazzi',
        'Mood',
        'for women and men',
        NULL,
        NULL,
        'Wild Berries, Saffron and Black Pepper',
        'Vanilla, Iris and Amber',
        'Agarwood (Oud), Cashmere Wood and Musk',
        'woody,powdery,fruity,vanilla,iris',
        'Mood SwingsbyFugazziis a Amber Woody fragrance for women and men. This is a new fragrance.Mood Swingswas launched in 2023. Top notes are Wild Berries, Saffron and Black Pepper; middle notes are Vanilla, Iris and Amber; base notes are Agarwood (Oud), Cashmere Wood and Musk.',
        3.37,
        27,
        NULL
      ),
(
        'NoCologne-81518',
        'NoCologne Fugazzi',
        'NoCologne',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Mandarin Orange, Calabrian bergamot and Lemon',
        'Ginger, Orange Blossom, Pink Pepper, Clary Sage and Mimosa',
        'Ambrette (Musk Mallow), Crystal Amber, Oakmoss and Vetiver',
        'citrus,aromatic,fresh spicy',
        'NoColognebyFugazziis a fragrance for women and men. This is a new fragrance.NoColognewas launched in 2023. Top notes are Grapefruit, Mandarin Orange, Calabrian bergamot and Lemon; middle notes are Ginger, Orange Blossom, Pink Pepper, Clary Sage and Mimosa; base notes are Ambrette (Musk Mallow), Crystal Amber, Oakmoss and Vetiver.',
        4,
        157,
        NULL
      ),
(
        'Orange-Crush-73920',
        'Orange Crush Fugazzi',
        'Orange',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,woody,musky,sweet',
        'Orange CrushbyFugazziis a Citrus fragrance for women and men. This is a new fragrance.Orange Crushwas launched in 2022.',
        3.93,
        174,
        NULL
      ),
(
        'Parfum-5-Thirsty-60692',
        'Parfum 5 Thirsty Fugazzi',
        'Parfum',
        'for women and men',
        NULL,
        NULL,
        'Bamboo, Apple, Galbanum and Bellflower',
        'Fig, Jasmine, Neroli and Rose',
        'Cedar, Musk and Amber',
        'woody,fruity,green,white floral,musky',
        'Parfum 5 ThirstybyFugazziis a Floral Fruity fragrance for women and men.Parfum 5 Thirstywas launched in 2020. Top notes are Bamboo, Apple, Galbanum and Bellflower; middle notes are Fig, Jasmine, Neroli and Rose; base notes are Cedar, Musk and Amber.',
        3.58,
        120,
        NULL
      ),
(
        'Saint-Remy-66535',
        'Saint Rémy Fugazzi',
        'Saint',
        'for women and men',
        NULL,
        NULL,
        'Juniper Berries, White Iris, Bergamot, Ginger and Pink Pepper',
        'Leather, Iris, Amber and Magnolia',
        'Vetiver, Cedar, Sandalwood and Tonka Bean',
        'woody,aromatic,fresh spicy,leather,powdery',
        'Saint RémybyFugazziis a Amber Floral fragrance for women and men.Saint Rémywas launched in 2019. Top notes are Juniper Berries, White Iris, Bergamot, Ginger and Pink Pepper; middle notes are Leather, Iris, Amber and Magnolia; base notes are Vetiver, Cedar, Sandalwood and Tonka Bean.',
        3.52,
        94,
        NULL
      ),
(
        'Santa-Monica-80382',
        'Santa Monica Fugazzi',
        'Santa',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Mandarin Orange and Bergamot',
        'White Amber, Neroli and White Tea',
        'Tonka Bean, Musk and Patchouli',
        'citrus,white floral,amber,sweet,vanilla',
        'Santa MonicabyFugazziis a Floral Woody Musk fragrance for women and men. This is a new fragrance.Santa Monicawas launched in 2022. Top notes are Orange Blossom, Mandarin Orange and Bergamot; middle notes are White Amber, Neroli and White Tea; base notes are Tonka Bean, Musk and Patchouli.',
        4,
        12,
        NULL
      ),
(
        'Sugardaddy-66510',
        'Sugardaddy Fugazzi',
        'Sugardaddy',
        'for women and men',
        NULL,
        NULL,
        'Tangerine and Bergamot',
        'Nutmeg, Black Currant, Cloves and Jasmine',
        'Cashmeran, Ambergris, Patchouli and Moss',
        'fresh spicy,fruity,citrus,warm spicy,woody',
        'SugardaddybyFugazziis a Amber Spicy fragrance for women and men.Sugardaddywas launched in 2021. Top notes are Tangerine and Bergamot; middle notes are Nutmeg, Black Currant, Cloves and Jasmine; base notes are Cashmeran, Ambergris, Patchouli and Moss.',
        3.88,
        199,
        NULL
      ),
(
        'FOUR-Cashmere-Comfort-80378',
        'FOUR Cashmere Comfort Fugazzi',
        'FOUR',
        'for women and men',
        NULL,
        NULL,
        'Calabrian bergamot and Damask Rose',
        'Atlas Cedar, Cardamom and Orris Root',
        'Black Amber, Leather, Cashmeran, Musk and Oak',
        'woody,powdery,musky,amber,animalic',
        'FOUR Cashmere ComfortbyFugazziis a Amber Woody fragrance for women and men. This is a new fragrance.FOUR Cashmere Comfortwas launched in 2022. Top notes are Calabrian bergamot and Damask Rose; middle notes are Atlas Cedar, Cardamom and Orris Root; base notes are Black Amber, Leather, Cashmeran, Musk and Oak.',
        4.25,
        4,
        NULL
      ),
(
        'FOUR-Lush-Linen-80381',
        'FOUR Lush Linen Fugazzi',
        'FOUR',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit and Pink Pepper',
        'Bay Leaf, Bulgarian Rose, Clearwood and Cotton Flower',
        'Moss, Wormwood, Violet and White Musk',
        'powdery,fresh spicy,woody,musky,aromatic',
        'FOUR Lush LinenbyFugazziis a Woody Aromatic fragrance for women and men. This is a new fragrance.FOUR Lush Linenwas launched in 2022. Top notes are Grapefruit and Pink Pepper; middle notes are Bay Leaf, Bulgarian Rose, Clearwood and Cotton Flower; base notes are Moss, Wormwood, Violet and White Musk.',
        4,
        1,
        NULL
      ),
(
        'FOUR-Smooth-Suede-80380',
        'FOUR Smooth Suede Fugazzi',
        'FOUR',
        'for women and men',
        NULL,
        NULL,
        'Calabrian bergamot, Lavender and Rosemary',
        'Basil, Cyclamen, Geranium, Palisander Rosewood and Suede',
        'Amber, Oak, Agarwood (Oud), Patchouli, Sandalwood and Tonka Bean',
        'woody,aromatic,fresh spicy,amber,warm spicy',
        'FOUR Smooth SuedebyFugazziis a Amber Woody fragrance for women and men. This is a new fragrance.FOUR Smooth Suedewas launched in 2022. Top notes are Calabrian bergamot, Lavender and Rosemary; middle notes are Basil, Cyclamen, Geranium, Palisander Rosewood and Suede; base notes are Amber, Oak, Agarwood (Oud), Patchouli, Sandalwood and Tonka Bean.',
        4.33,
        3,
        NULL
      ),
(
        'FOUR-Vibrant-Velvet-80379',
        'FOUR Vibrant Velvet Fugazzi',
        'FOUR',
        'for women and men',
        NULL,
        NULL,
        'Calabrian bergamot, Cardamom and Pink Pepper',
        'Clary Sage, Cotton Flower, Lily, Orris Root and Vetiver',
        'Amber, Musk, Sandalwood and Woody Notes',
        'woody,powdery,aromatic,soft spicy,warm spicy',
        'FOUR Vibrant VelvetbyFugazziis a Woody Spicy fragrance for women and men. This is a new fragrance.FOUR Vibrant Velvetwas launched in 2022. Top notes are Calabrian bergamot, Cardamom and Pink Pepper; middle notes are Clary Sage, Cotton Flower, Lily, Orris Root and Vetiver; base notes are Amber, Musk, Sandalwood and Woody Notes.',
        4,
        1,
        NULL
      ),
(
        'Agua-de-Gardenia-41055',
        'Agua de Gardenia Fueguia 1833',
        'Agua',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'yellow floral,sweet,white floral,green,honey',
        'Agua de GardeniabyFueguia 1833is a Floral Green fragrance for women and men.Agua de Gardeniawas launched in 2014. The nose behind this fragrance is Julian Bedel.',
        3.78,
        32,
        NULL
      ),
(
        'Cuentos-de-la-Selva-41558',
        'Cuentos de la Selva Fueguia 1833',
        'Cuentos',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'citrus,amber,fresh spicy,warm spicy,aromatic',
        'Cuentos de la SelvabyFueguia 1833is a Floral fragrance for women and men.Cuentos de la Selvawas launched in 2016. The nose behind this fragrance is Julian Bedel.',
        3.81,
        32,
        NULL
      ),
(
        'Ett-Hem-71712',
        'Ett Hem Fueguia 1833',
        'Ett',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Black Pepper',
        'Cedar',
        'Sandalwood',
        'woody,powdery,warm spicy,fresh spicy',
        'Ett HembyFueguia 1833is a Aromatic Spicy fragrance for women and men.Ett Hemwas launched in 2016. The nose behind this fragrance is Julian Bedel. Top note is Black Pepper; middle note is Cedar; base note is Sandalwood.',
        4.16,
        51,
        NULL
      ),
(
        'Oud-Malaysia-93262',
        'Oud Malaysia Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'musky,powdery',
        'Oud MalaysiabyFueguia 1833is a Woody Aromatic fragrance for women and men.Oud Malaysiawas launched in 2022. The nose behind this fragrance is Julian Bedel.',
        5,
        1,
        NULL
      ),
(
        'Halo-Lunar-67035',
        'Halo Lunar Fueguia 1833',
        'Halo',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Lavender',
        'Ambergris',
        'Sandalwood',
        'lavender,woody,amber,aromatic,animalic',
        'Halo LunarbyFueguia 1833is a Woody Aromatic fragrance for women and men.Halo Lunarwas launched in 2018. The nose behind this fragrance is Julian Bedel. Top note is Lavender; middle note is Ambergris; base note is Sandalwood.',
        3.74,
        19,
        NULL
      ),
(
        'Humo-de-Rubi-88779',
        'Humo de Rubí Fueguia 1833',
        'Humo',
        'for women and men',
        NULL,
        NULL,
        'Champaca',
        'Agarwood (Oud)',
        'Orchid',
        'floral,oud,sweet',
        'Humo de RubíbyFueguia 1833is a Floral fragrance for women and men. This is a new fragrance.Humo de Rubíwas launched in 2023. Top note is Champaca; middle note is Agarwood (Oud); base note is Orchid.',
        4.11,
        9,
        NULL
      ),
(
        'Luna-Roja-79404',
        'Luna Roja Fueguia 1833',
        'Luna',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'woody,fruity,sweet,rose,aromatic',
        'Luna RojabyFueguia 1833is a Woody fragrance for women and men.Luna Rojawas launched in 2017. The nose behind this fragrance is Julian Bedel.',
        4.22,
        49,
        NULL
      ),
(
        'Luz-Sin-Freno-67041',
        'Luz Sin Freno Fueguia 1833',
        'Luz',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'citrus,white floral,aromatic,fresh spicy,fresh',
        'Luz Sin FrenobyFueguia 1833is a Citrus fragrance for women and men.Luz Sin Frenowas launched in 2017. The nose behind this fragrance is Julian Bedel.',
        3.53,
        17,
        NULL
      ),
(
        'Amalia-Gourmand-18238',
        'Amalia Gourmand Fueguia 1833',
        'Amalia',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Jasmine',
        'Vanilla',
        'Dulce de leche',
        'white floral,vanilla,sweet,lactonic,powdery',
        'Amalia GourmandbyFueguia 1833is a Amber Vanilla fragrance for women and men. The nose behind this fragrance is Julian Bedel. Top note is Jasmine; middle note is Vanilla; base note is Dulce de leche.',
        3.92,
        158,
        NULL
      ),
(
        'Amalia-Primavera-18239',
        'Amalia Primavera Fueguia 1833',
        'Amalia',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Jasmine',
        'Jasmine',
        'Ambergris',
        'white floral,amber,animalic',
        'Amalia PrimaverabyFueguia 1833is a Floral fragrance for women and men.Amalia Primaverawas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Jasmine; middle note is Jasmine; base note is Ambergris.',
        4.03,
        88,
        NULL
      ),
(
        'Amalia-Verano-18240',
        'Amalia Verano Fueguia 1833',
        'Amalia',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Jasmine',
        'Tangerine',
        'Grapefruit',
        'citrus,white floral,fruity,sweet',
        'Amalia VeranobyFueguia 1833is a Citrus fragrance for women and men.Amalia Veranowas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Jasmine; middle note is Tangerine; base note is Grapefruit.',
        4.25,
        8,
        NULL
      ),
(
        'Ceniza-De-Coca-67430',
        'Ceniza De Coca Fueguia 1833',
        'Ceniza',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'amber,aromatic,balsamic,animalic,green',
        'Ceniza De CocabyFueguia 1833is a Leather fragrance for women and men.Ceniza De Cocawas launched in 2017. The nose behind this fragrance is Julian Bedel.',
        4,
        28,
        NULL
      ),
(
        'La-Luna-77155',
        'La Luna Fueguia 1833',
        'La',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'amber,balsamic,woody,warm spicy,aromatic',
        'La LunabyFueguia 1833is a Woody fragrance for women and men.La Lunawas launched in 2020. The nose behind this fragrance is Julian Bedel.',
        3.94,
        17,
        NULL
      ),
(
        'Los-Humos-Sagrados-65512',
        'Los Humos Sagrados Fueguia 1833',
        'Los',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'oud,aromatic,woody,herbal,citrus',
        'Los Humos SagradosbyFueguia 1833is a Woody fragrance for women and men.Los Humos Sagradoswas launched in 2017. The nose behind this fragrance is Julian Bedel.',
        3.96,
        48,
        NULL
      ),
(
        'Malon-75645',
        'Malón Fueguia 1833',
        'Malón',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'amber,musky,oud,woody,powdery',
        'MalónbyFueguia 1833is a fragrance for women and men. This is a new fragrance.Malónwas launched in 2022. The nose behind this fragrance is Julian Bedel.',
        3.6,
        10,
        NULL
      ),
(
        'Oud-Ambar-68222',
        'Oud Ambar Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'amber,oud,animalic,fresh spicy',
        'Oud AmbarbyFueguia 1833is a fragrance for women and men.Oud Ambarwas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        3.5,
        4,
        NULL
      ),
(
        'Oud-Jazmin-68211',
        'Oud Jazmín Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'oud,white floral',
        'Oud JazmínbyFueguia 1833is a Floral Woody Musk fragrance for women and men.Oud Jazmínwas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        3.83,
        6,
        NULL
      ),
(
        'Oud-Rosa-68223',
        'Oud Rosa Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'oud,rose,floral',
        'Oud RosabyFueguia 1833is a fragrance for women and men.Oud Rosawas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        3.75,
        4,
        NULL
      ),
(
        'Oud-Sandalo-68224',
        'Oud Sándalo Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'woody,oud,powdery,warm spicy,balsamic',
        'Oud SándalobyFueguia 1833is a fragrance for women and men.Oud Sándalowas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        3.75,
        4,
        NULL
      ),
(
        'Oud-Tabaco-68227',
        'Oud Tabaco Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'tobacco,oud,sweet',
        'Oud TabacobyFueguia 1833is a fragrance for women and men.Oud Tabacowas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        3.67,
        9,
        NULL
      ),
(
        'Oud-Te-68212',
        'Oud Té Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'oud,green,fresh,fresh spicy',
        'Oud TébyFueguia 1833is a fragrance for women and men.Oud Téwas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        4.17,
        6,
        NULL
      ),
(
        'Oud-Vainilla-68221',
        'Oud Vainilla Fueguia 1833',
        'Oud',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'oud,vanilla,powdery,fresh spicy,sweet',
        'Oud VainillabyFueguia 1833is a fragrance for women and men.Oud Vainillawas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        4.25,
        8,
        NULL
      ),
(
        'Dos-Gardenias-18241',
        'Dos Gardenias Fueguia 1833',
        'Dos',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Gardenia',
        'Tuberose',
        'Jasmine Sambac',
        'white floral',
        'Dos GardeniasbyFueguia 1833is a Floral fragrance for women and men.Dos Gardeniaswas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Gardenia; middle note is Tuberose; base note is Jasmine Sambac.',
        3.87,
        15,
        NULL
      ),
(
        'Flores-Negras-33913',
        'Flores Negras Fueguia 1833',
        'Flores',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Frangipani',
        'Dates',
        'Oily Notes and Damascone',
        'sweet,floral,tropical,fruity,oily',
        'Flores NegrasbyFueguia 1833is a Floral Fruity fragrance for women and men.Flores Negraswas launched in 2014. The nose behind this fragrance is Julian Bedel. Top note is Frangipani; middle note is Dates; base notes are Oily Notes and Damascone.',
        3.68,
        74,
        NULL
      ),
(
        'Fruta-Amarga-18242',
        'Fruta Amarga Fueguia 1833',
        'Fruta',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Mandarin Orange',
        'Vetiver',
        'Papyrus',
        'citrus,aromatic,earthy,woody',
        'Fruta AmargabyFueguia 1833is a Citrus fragrance for women and men.Fruta Amargawas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Mandarin Orange; middle note is Vetiver; base note is Papyrus.',
        2.75,
        4,
        NULL
      ),
(
        'Malena-18243',
        'Malena Fueguia 1833',
        'Malena',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Musk',
        'Cassis',
        'Magnolia',
        'aromatic,fruity,green,soft spicy,floral',
        'MalenabyFueguia 1833is a Floral Woody Musk fragrance for women and men.Malenawas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Musk; middle note is Cassis; base note is Magnolia.',
        3.97,
        163,
        NULL
      ),
(
        'Milonga-Verde-75478',
        'Milonga Verde Fueguia 1833',
        'Milonga',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'floral,woody,nutty,chocolate,sweet',
        'Milonga VerdebyFueguia 1833is a Woody Chypre fragrance for women and men. This is a new fragrance.Milonga Verdewas launched in 2022. The nose behind this fragrance is Julian Bedel.',
        3.92,
        53,
        NULL
      ),
(
        'Naranjo-en-Flor-18244',
        'Naranjo en Flor Fueguia 1833',
        'Naranjo',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Orange and Neroli',
        'Mimosa',
        'Petitgrain',
        'citrus,white floral,green,yellow floral,fresh spicy',
        'Naranjo en FlorbyFueguia 1833is a Citrus fragrance for women and men.Naranjo en Florwas launched in 2010. The nose behind this fragrance is Julian Bedel. Top notes are Orange and Neroli; middle note is Mimosa; base note is Petitgrain.',
        3.79,
        14,
        NULL
      ),
(
        'Paisaje-20828',
        'Paisaje Fueguia 1833',
        'Paisaje',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Eucalyptus',
        'Ginger',
        'Cardamom',
        'warm spicy,woody,camphor,aromatic',
        'PaisajebyFueguia 1833is a Woody Aromatic fragrance for women and men.Paisajewas launched in 2013. The nose behind this fragrance is Julian Bedel. Top note is Eucalyptus; middle note is Ginger; base note is Cardamom.',
        3.82,
        33,
        NULL
      ),
(
        'Paisaje-72414',
        'Paisaje Fueguia 1833',
        'Paisaje',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'warm spicy,aromatic,woody,camphor',
        'PaisajebyFueguia 1833is a Aromatic Green fragrance for women and men.Paisajewas launched in 2021. The nose behind this fragrance is Julian Bedel.',
        3.14,
        7,
        NULL
      ),
(
        'Tinta-Roja-18245',
        'Tinta Roja Fueguia 1833',
        'Tinta',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Vanilla',
        'Tuberose',
        'Gardenia',
        'white floral,tuberose,vanilla,animalic',
        'Tinta RojabyFueguia 1833is a Floral fragrance for women and men.Tinta Rojawas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Vanilla; middle note is Tuberose; base note is Gardenia.',
        4.13,
        95,
        NULL
      ),
(
        'Alhambra-65809',
        'Alhambra Fueguia 1833',
        'Alhambra',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'amber,animalic,rose',
        'AlhambrabyFueguia 1833is a Amber fragrance for women and men.Alhambrawas launched in 2018. The nose behind this fragrance is Julian Bedel.',
        4.31,
        35,
        NULL
      ),
(
        'Alma-93744',
        'Alma Fueguia 1833',
        'Alma',
        'for women and men',
        NULL,
        'Julian Bedel',
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,herbal,floral,white floral',
        'AlmabyFueguia 1833is a fragrance for women and men.Almawas launched in 2019. The nose behind this fragrance is Julian Bedel.',
        4.25,
        4,
        NULL
      ),
(
        'Ambar-de-los-Andes-40597',
        'Ambar de los Andes Fueguia 1833',
        'Ambar',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Jasmine',
        'Sandalwood',
        'Agarwood (Oud)',
        'woody,white floral,oud,powdery,warm spicy',
        'Ambar de los AndesbyFueguia 1833is a Woody fragrance for women and men.Ambar de los Andeswas launched in 2016. The nose behind this fragrance is Julian Bedel. Top note is Jasmine; middle note is Sandalwood; base note is Agarwood (Oud).',
        3.93,
        43,
        NULL
      ),
(
        'Beagle-18206',
        'Beagle Fueguia 1833',
        'Beagle',
        'for women and men',
        NULL,
        'Julian Bedel',
        'Oak',
        'Rum',
        'gunpowder',
        'woody,rum,smoky,aromatic',
        'BeaglebyFueguia 1833is a Woody fragrance for women and men.Beaglewas launched in 2010. The nose behind this fragrance is Julian Bedel. Top note is Oak; middle note is Rum; base note is gunpowder.',
        3.98,
        104,
        NULL
      );
