
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Escada-Collection-2001-1370',
        'Escada Collection 2001 Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        'Coca-Cola and Mandarin Orange',
        'Jasmine and Tuberose',
        'Tonka Bean, Sandalwood and Amber',
        'coca-cola,warm spicy,amber,citrus,woody',
        'Escada Collection 2001byEscadais a Floral fragrance for women.Escada Collection 2001was launched in 2001. Top notes are Coca-Cola and Mandarin Orange; middle notes are Jasmine and Tuberose; base notes are Tonka Bean, Sandalwood and Amber.',
        4.32,
        94,
        NULL
      ),
(
        'Escada-en-Fleurs-1375',
        'Escada en Fleurs Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        'Green Notes, Mandarin Orange, Bergamot and Aldehydes',
        'Freesia, Cyclamen, Rose and Orris Root',
        'Cedar, Sandalwood, Vanilla and Cinnamon',
        'floral,woody,citrus,green,powdery',
        'Escada en FleursbyEscadais a Floral fragrance for women.Escada en Fleurswas launched in 1997. Top notes are Green Notes, Mandarin Orange, Bergamot and Aldehydes; middle notes are Freesia, Cyclamen, Rose and Orris Root; base notes are Cedar, Sandalwood, Vanilla and Cinnamon.',
        3.73,
        117,
        NULL
      ),
(
        'Escada-Margaretha-Ley-1365',
        'Escada Margaretha Ley Escada',
        'Escada',
        'for women',
        NULL,
        'Michel Almairac',
        'Hyacinth, Peach, Coconut and Bergamot',
        'Ylang-Ylang, Jasmine, Clove, African Orange Flower and Iris',
        'Sandalwood, Vanille and Musk',
        'white floral,floral,sweet,woody,warm spicy',
        'Escada Margaretha LeybyEscadais a Amber Floral fragrance for women.Escada Margaretha Leywas launched in 1990. The nose behind this fragrance is Michel Almairac. Top notes are Hyacinth, Peach, Coconut and Bergamot; middle notes are Ylang-Ylang, Jasmine, Clove, African Orange Flower and Iris; base notes are Sandalwood, Vanille and Musk.',
        4.2,
        681,
        NULL
      ),
(
        'Escada-pour-Homme-1364',
        'Escada pour Homme Escada',
        'Escada',
        'for men',
        NULL,
        NULL,
        'Cognac, Orange, Lavender, Bergamot and Italian Lemon',
        'Cinnamon, Carnation, Cardamom, Nutmeg, Caraway, Juniper, Bay Leaf and Geranium',
        'Vanilla, Sandalwood, Patchouli, Tonka Bean and Musk',
        'warm spicy,woody,fresh spicy,aromatic,citrus',
        'Escada pour HommebyEscadais a Amber fragrance for men.Escada pour Hommewas launched in 1993. Top notes are Cognac, Orange, Lavender, Bergamot and Italian Lemon; middle notes are Cinnamon, Carnation, Cardamom, Nutmeg, Caraway, Juniper, Bay Leaf and Geranium; base notes are Vanilla, Sandalwood, Patchouli, Tonka Bean and Musk.',
        4.41,
        502,
        NULL
      ),
(
        'Escada-pour-Homme-Light-Silver-Edition-1363',
        'Escada pour Homme Light Silver Edition Escada',
        'Escada',
        'for men',
        NULL,
        NULL,
        'Green Apple, Mint and Grapefruit',
        'Lavender, Jasmine and Violet',
        'Vanilla, Oakmoss and Patchouli',
        'green,aromatic,fresh spicy,fruity,lavender',
        'Escada pour Homme Light Silver EditionbyEscadais a Woody fragrance for men.Escada pour Homme Light Silver Editionwas launched in 1997. Top notes are Green Apple, Mint and Grapefruit; middle notes are Lavender, Jasmine and Violet; base notes are Vanilla, Oakmoss and Patchouli.',
        4.15,
        97,
        NULL
      ),
(
        'Escada-S-1720',
        'Escada S Escada',
        'Escada',
        'for women',
        NULL,
        'Olivier Cresp',
        'Rose, Plum and Black Currant',
        'Almond Blossom, Rose, Pimento and Lily-of-the-Valley',
        'Hazelnut, Mahogany, Sandalwood and Musk',
        'woody,floral,fruity,sweet,rose',
        'Escada SbyEscadais a Floral Fruity fragrance for women.Escada Swas launched in 2007. The nose behind this fragrance is Olivier Cresp. Top notes are Rose, Plum and Black Currant; middle notes are Almond Blossom, Rose, Pimento and Lily-of-the-Valley; base notes are Hazelnut, Mahogany, Sandalwood and Musk.',
        3.97,
        819,
        NULL
      ),
(
        'Into-the-Blue-998',
        'Into the Blue Escada',
        'Into',
        'for women',
        NULL,
        'Richard Ibanez',
        'Green Grass, Green Leaves, Carambola (Star Fruit) and Marigold',
        'Watermelon, Blue Lotus and Peony',
        'Musk, Cedar, Woodsy Notes and Amber',
        'green,ozonic,aquatic,floral,fresh',
        'Into the BluebyEscadais a Floral Aquatic fragrance for women.Into the Bluewas launched in 2006. The nose behind this fragrance is Richard Ibanez. Top notes are Green Grass, Green Leaves, Carambola (Star Fruit) and Marigold; middle notes are Watermelon, Blue Lotus and Peony; base notes are Musk, Cedar, Woodsy Notes and Amber.',
        3.85,
        1,
        NULL
      ),
(
        'Celebrate-Life-51038',
        'Celebrate Life Escada',
        'Celebrate',
        'for women',
        NULL,
        NULL,
        'Pear, Litchi and Bitter Orange',
        'Amber, Orange Blossom and Rose',
        'Vanilla, Musk and Ambroxan',
        'fruity,vanilla,sweet,fresh,amber',
        'Celebrate LifebyEscadais a Amber Floral fragrance for women.Celebrate Lifewas launched in 2018. Top notes are Pear, Litchi and Bitter Orange; middle notes are Amber, Orange Blossom and Rose; base notes are Vanilla, Musk and Ambroxan.',
        3.68,
        198,
        NULL
      ),
(
        'Celebrate-N-O-W-46180',
        'Celebrate N.O.W. Escada',
        'Celebrate',
        'for women',
        NULL,
        NULL,
        'Ginger',
        'Magnolia',
        'Vanilla, Tonka Bean and Cinnamon',
        'vanilla,warm spicy,floral,cinnamon,citrus',
        'Celebrate N.O.W.byEscadais a Amber Floral fragrance for women.Celebrate N.O.W.was launched in 2017. Top note is Ginger; middle note is Magnolia; base notes are Vanilla, Tonka Bean and Cinnamon.',
        3.68,
        613,
        NULL
      ),
(
        'Escada-Magnetic-Beat-1366',
        'Escada Magnetic Beat Escada',
        'Escada',
        'for women',
        NULL,
        'Pierre Bourdon',
        'Black Currant, Violet, Cassia, Freesia, Basil and Green Leaves',
        'Almond Blossom, Iris, Jasmine and Lily-of-the-Valley',
        'Vanilla, Musk, Amber and Sandalwood',
        'floral,powdery,fruity,woody,green',
        'Escada Magnetic BeatbyEscadais a Floral Fruity fragrance for women.Escada Magnetic Beatwas launched in 2003. Escada Magnetic Beat was created by Pierre Bourdon and Steve DeMercado. Top notes are Black Currant, Violet, Cassia, Freesia, Basil and Green Leaves; middle notes are Almond Blossom, Iris, Jasmine and Lily-of-the-Valley; base notes are Vanilla, Musk, Amber and Sandalwood.',
        4.04,
        228,
        NULL
      ),
(
        'Escada-Magnetism-1036',
        'Escada Magnetism Escada',
        'Escada',
        'for women',
        NULL,
        'Pierre Bourdon',
        'Red Berries, Black Currant, Cassia, Litchi, Pineapple and Melon',
        'Green Leaves, Basil, Almond Blossom, Iris, Freesia, Heliotrope, Jasmine, Magnolia, Rose, Caraway and Lily-of-the-Valley',
        'Caramel, Vanilla, Patchouli, Benzoin, Sandalwood, Musk, Amber and Vetiver',
        'fruity,sweet,green,aromatic,fresh',
        'Escada MagnetismbyEscadais a Amber Vanilla fragrance for women.Escada Magnetismwas launched in 2003. Escada Magnetism was created by Steve DeMercado and Pierre Bourdon. Top notes are Red Berries, Black Currant, Cassia, Litchi, Pineapple and Melon; middle notes are Green Leaves, Basil, Almond Blossom, Iris, Freesia, Heliotrope, Jasmine, Magnolia, Rose, Caraway and Lily-of-the-Valley; base notes are Caramel, Vanilla, Patchouli, Benzoin, Sandalwood, Musk, Amber and Vetiver.',
        4.01,
        4,
        NULL
      ),
(
        'Escada-Magnetism-for-Men-1037',
        'Escada Magnetism for Men Escada',
        'Escada',
        'for men',
        NULL,
        'Michel Almairac',
        'Saffron and Woody Notes',
        'Leather, Sandalwood and Cedar',
        'Tolu Balsam, Amber and Musk',
        'amber,powdery,warm spicy,woody,leather',
        'Escada Magnetism for MenbyEscadais a Amber Woody fragrance for men.Escada Magnetism for Menwas launched in 2004. The nose behind this fragrance is Michel Almairac. Top notes are Saffron and Woody Notes; middle notes are Leather, Sandalwood and Cedar; base notes are Tolu Balsam, Amber and Musk.',
        4.34,
        992,
        NULL
      ),
(
        'Escada-Sentiment-1179',
        'Escada Sentiment Escada',
        'Escada',
        'for women',
        NULL,
        'Natalie Gracia-Cetto',
        'Iris, Black Currant, Red Currant, Magnolia and Green Mandarin',
        'White Peach, Hiacynth, Tuberose and Orris Root',
        'Heliotrope, Vanilla, Amber, Brazilian Rosewood and Sandalwood',
        'fruity,floral,powdery,iris,woody',
        'Escada SentimentbyEscadais a Floral Fruity fragrance for women.Escada Sentimentwas launched in 2000. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Iris, Black Currant, Red Currant, Magnolia and Green Mandarin; middle notes are White Peach, Hiacynth, Tuberose and Orris Root; base notes are Heliotrope, Vanilla, Amber, Brazilian Rosewood and Sandalwood.',
        3.92,
        1,
        NULL
      ),
(
        'Escada-Sentiment-pour-Homme-1180',
        'Escada Sentiment pour Homme Escada',
        'Escada',
        'for men',
        NULL,
        'Dominique Ropion',
        'Juniper Berries and Lime',
        'Pink Pepper and Nutmeg',
        'Sandalwood, Cedar and Vetiver',
        'woody,aromatic,fresh spicy,citrus,soft spicy',
        'Escada Sentiment pour HommebyEscadais a Woody Aromatic fragrance for men.Escada Sentiment pour Hommewas launched in 2002. Escada Sentiment pour Homme was created by Dominique Ropion and Laurent Bruyere. Top notes are Juniper Berries and Lime; middle notes are Pink Pepper and Nutmeg; base notes are Sandalwood, Cedar and Vetiver.',
        4.2,
        565,
        NULL
      ),
(
        'Escada-Sport-Country-Weekend-1358',
        'Escada Sport Country Weekend Escada',
        'Escada',
        'for women and men',
        NULL,
        'Ilias Ermenidis',
        'Marigold and Apple',
        'Bay Leaf, Mahogany, Cinnamon and Jasmine',
        'Cedar, Nutmeg and Cashmere Wood',
        'woody,fresh spicy,aromatic,balsamic,camphor',
        'Escada Sport Country WeekendbyEscadais a Woody Spicy fragrance for women and men.Escada Sport Country Weekendwas launched in 1996. The nose behind this fragrance is Ilias Ermenidis. Top notes are Marigold and Apple; middle notes are Bay Leaf, Mahogany, Cinnamon and Jasmine; base notes are Cedar, Nutmeg and Cashmere Wood.',
        4,
        221,
        NULL
      ),
(
        'Escada-Sport-Feeling-Free-1359',
        'Escada Sport Feeling Free Escada',
        'Escada',
        'for women and men',
        NULL,
        'Jean-Pierre Bethouart',
        'Lavender, Passion Flower and Bergamot',
        'Freesia, Hyacinth, White Lily and Rose',
        'Sandalwood, Myrrh and Amber',
        'floral,fresh spicy,rose,green,amber',
        'Escada Sport Feeling FreebyEscadais a Floral Green fragrance for women and men.Escada Sport Feeling Freewas launched in 1996. The nose behind this fragrance is Jean-Pierre Bethouart. Top notes are Lavender, Passion Flower and Bergamot; middle notes are Freesia, Hyacinth, White Lily and Rose; base notes are Sandalwood, Myrrh and Amber.',
        4.04,
        217,
        NULL
      ),
(
        'Escada-Sport-Sport-Spirit-1357',
        'Escada Sport Sport Spirit Escada',
        'Escada',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Lavender and Juniper',
        'Rosemary and Sage',
        'Geranium, Lemon and Grapefruit',
        'aromatic,fresh spicy,citrus,herbal,woody',
        'Escada Sport Sport SpiritbyEscadais a Citrus Aromatic fragrance for women and men.Escada Sport Sport Spiritwas launched in 1996. Top notes are Mandarin Orange, Lavender and Juniper; middle notes are Rosemary and Sage; base notes are Geranium, Lemon and Grapefruit.',
        3.64,
        113,
        NULL
      ),
(
        'Especially-Escada-12433',
        'Especially Escada Escada',
        'Especially',
        'for women',
        NULL,
        'Jean-Michel Duriez',
        'Pear and Ambrette (Musk Mallow)',
        'Rose, Water Notes and Ylang-Ylang',
        'Musk',
        'rose,aquatic,musky,floral,sweet',
        'Especially EscadabyEscadais a Floral fragrance for women.Especially Escadawas launched in 2011. The nose behind this fragrance is Jean-Michel Duriez. Top notes are Pear and Ambrette (Musk Mallow); middle notes are Rose, Water Notes and Ylang-Ylang; base note is Musk.',
        3.76,
        2,
        NULL
      ),
(
        'Especially-Escada-Delicate-Notes-15177',
        'Especially Escada Delicate Notes Escada',
        'Especially',
        'for women',
        NULL,
        'Jean-Michel Duriez',
        'Pear, Hamanasu or Japanese Rose and Grapefruit',
        'Rose, Ambrette (Musk Mallow) and Ylang-Ylang',
        'Musk and Woodsy Notes',
        'rose,musky,floral,citrus,fruity',
        'Especially Escada Delicate NotesbyEscadais a Floral fragrance for women.Especially Escada Delicate Noteswas launched in 2012. The nose behind this fragrance is Jean-Michel Duriez. Top notes are Pear, Hamanasu or Japanese Rose and Grapefruit; middle notes are Rose, Ambrette (Musk Mallow) and Ylang-Ylang; base notes are Musk and Woodsy Notes.',
        3.97,
        896,
        NULL
      ),
(
        'Especially-Escada-Elixir-18344',
        'Especially Escada Elixir Escada',
        'Especially',
        'for women',
        NULL,
        'Jean-Michel Duriez',
        'Pear, Grapefruit and Ambrette (Musk Mallow)',
        'Turkish Rose, Plum, Dried Plum and Ylang-Ylang',
        'Patchouli, White Musk, Cashmere Wood, Amber and Madagascar Vanilla',
        'rose,fruity,musky,sweet,woody',
        'Especially Escada ElixirbyEscadais a Amber Floral fragrance for women.Especially Escada Elixirwas launched in 2013. The nose behind this fragrance is Jean-Michel Duriez. Top notes are Pear, Grapefruit and Ambrette (Musk Mallow); middle notes are Turkish Rose, Plum, Dried Plum and Ylang-Ylang; base notes are Patchouli, White Musk, Cashmere Wood, Amber and Madagascar Vanilla.',
        3.62,
        782,
        NULL
      ),
(
        'Absolutely-Me-9452',
        'Absolutely Me Escada',
        'Absolutely',
        'for women',
        NULL,
        'Sonia Constant',
        'Raspberry, Rose and Pink Pepper',
        'Macarons, Rose, Hawthorn and Jasmine',
        'Vanille and White Musk',
        'sweet,fruity,vanilla,rose',
        'Absolutely MebyEscadais a Floral Fruity Gourmand fragrance for women.Absolutely Mewas launched in 2010. The nose behind this fragrance is Sonia Constant. Top notes are Raspberry, Rose and Pink Pepper; middle notes are Macarons, Rose, Hawthorn and Jasmine; base notes are Vanille and White Musk.',
        3.79,
        1,
        NULL
      ),
(
        'Desire-Me-6614',
        'Desire Me Escada',
        'Desire',
        'for women',
        NULL,
        'Loc Dong',
        'Citruses, Mandarin Orange and Clementine',
        'Green Notes, Peony, Orchid and Honeysuckle',
        'Coffee, Dark Chocolate, Sweet Notes and Custard',
        'sweet,warm spicy,coffee,chocolate,citrus',
        'Desire MebyEscadais a Floral Fruity Gourmand fragrance for women.Desire Mewas launched in 2009. The nose behind this fragrance is Loc Dong. Top notes are Citruses, Mandarin Orange and Clementine; middle notes are Green Notes, Peony, Orchid and Honeysuckle; base notes are Coffee, Dark Chocolate, Sweet Notes and Custard.',
        3.55,
        1,
        NULL
      ),
(
        'Incredible-Me-3861',
        'Incredible Me Escada',
        'Incredible',
        'for women',
        NULL,
        NULL,
        'Clementine',
        'Orchid and Peony',
        'Custard, Sweet Notes, Chocolate and Coffee',
        'sweet,lactonic,floral,warm spicy,chocolate',
        'Incredible MebyEscadais a Amber Floral fragrance for women.Incredible Mewas launched in 2008. Top note is Clementine; middle notes are Orchid and Peony; base notes are Custard, Sweet Notes, Chocolate and Coffee.',
        3.67,
        1,
        NULL
      ),
(
        'Joyful-25459',
        'Joyful Escada',
        'Joyful',
        'for women',
        NULL,
        NULL,
        'Melon, Black Currant and Mandarin Orange',
        'Peony, Magnolia, Nectarine and Violet Leaf',
        'Honey, Moss and Sandalwood',
        'floral,fresh,ozonic,fruity,aquatic',
        'JoyfulbyEscadais a Floral Fruity fragrance for women.Joyfulwas launched in 2014. Top notes are Melon, Black Currant and Mandarin Orange; middle notes are Peony, Magnolia, Nectarine and Violet Leaf; base notes are Honey, Moss and Sandalwood.',
        3.43,
        852,
        NULL
      ),
(
        'Joyful-Moments-31511',
        'Joyful Moments Escada',
        'Joyful',
        'for women',
        NULL,
        NULL,
        'Litchi, Black Currant and Mandarin Orange',
        'Pink Peony, Damask Rose and Violet Leaf',
        'Honey and Vanilla',
        'floral,rose,fresh,fruity,ozonic',
        'Joyful MomentsbyEscadais a Floral Fruity fragrance for women.Joyful Momentswas launched in 2015. Top notes are Litchi, Black Currant and Mandarin Orange; middle notes are Pink Peony, Damask Rose and Violet Leaf; base notes are Honey and Vanilla.',
        3.68,
        166,
        NULL
      ),
(
        'Candy-Love-62791',
        'Candy Love Escada',
        'Candy',
        'for women',
        NULL,
        'Amandine Clerc-Marie',
        'Candy Apple',
        'Rose',
        'Whipped Cream and Vanilla',
        'vanilla,sweet,fruity,lactonic,rose',
        'Candy LovebyEscadais a Floral Fruity Gourmand fragrance for women.Candy Lovewas launched in 2020. Candy Love was created by Amandine Clerc-Marie and Nicolas Beaulieu. Top note is Candy Apple; middle note is Rose; base notes are Whipped Cream and Vanilla.',
        4.02,
        926,
        NULL
      ),
(
        'Fairy-Love-68941',
        'Fairy Love Escada',
        'Fairy',
        'for women',
        NULL,
        'Natalie Gracia-Cetto',
        'Nashi Pear, Raspberry and Orange',
        'Jasmine',
        'Hazelnut',
        'fruity,sweet,nutty,white floral,citrus',
        'Fairy LovebyEscadais a Floral Fruity Gourmand fragrance for women.Fairy Lovewas launched in 2021. The nose behind this fragrance is Natalie Gracia-Cetto. Top notes are Nashi Pear, Raspberry and Orange; middle note is Jasmine; base note is Hazelnut.',
        3.46,
        425,
        NULL
      ),
(
        'Party-Love-84820',
        'Party Love Escada',
        'Party',
        'for women',
        NULL,
        'Nathalie Lorson',
        'Cherry',
        'Whipped Cream',
        'Cupcake and Vanilla',
        'sweet,vanilla,cherry,lactonic',
        'Party LovebyEscadais a Amber Vanilla fragrance for women. This is a new fragrance.Party Lovewas launched in 2023. The nose behind this fragrance is Nathalie Lorson. Top note is Cherry; middle note is Whipped Cream; base notes are Cupcake and Vanilla.',
        3.58,
        155,
        NULL
      ),
(
        'Show-Me-Love-76027',
        'Show Me Love Escada',
        'Show',
        'for women',
        NULL,
        'Alexandra Carlin',
        'Blueberry',
        'Jasmine',
        'Blueberry and Macarons',
        'sweet,fruity,almond,vanilla',
        'Show Me LovebyEscadais a Floral Fruity Gourmand fragrance for women. This is a new fragrance.Show Me Lovewas launched in 2022. The nose behind this fragrance is Alexandra Carlin. Top note is Blueberry; middle note is Jasmine; base notes are Blueberry and Macarons.',
        3.76,
        265,
        NULL
      ),
(
        'Agua-del-Sol-32741',
        'Agua del Sol Escada',
        'Agua',
        'for women',
        NULL,
        NULL,
        'Sorbet, Ice cream, Raspberry, Pear, Citruses, Mandarin Orange and Pink Pepper',
        'Fruity Notes, Apricot and Rose',
        'Tonka Bean, White Musk and Sandalwood',
        'fruity,sweet,citrus,vanilla,fresh',
        'Agua del SolbyEscadais a Floral Fruity fragrance for women.Agua del Solwas launched in 2016. Top notes are Sorbet, Ice cream, Raspberry, Pear, Citruses, Mandarin Orange and Pink Pepper; middle notes are Fruity Notes, Apricot and Rose; base notes are Tonka Bean, White Musk and Sandalwood.',
        3.95,
        1,
        NULL
      ),
(
        'Born-in-Paradise-22106',
        'Born in Paradise Escada',
        'Born',
        'for women',
        NULL,
        NULL,
        'Watermelon, Guava and Green Apple',
        'Coconut Milk and Pineapple',
        'Musk, Sandalwood and Cedar',
        'fruity,coconut,sweet,tropical,ozonic',
        'Born in ParadisebyEscadais a Floral Fruity fragrance for women.Born in Paradisewas launched in 2014. Top notes are Watermelon, Guava and Green Apple; middle notes are Coconut Milk and Pineapple; base notes are Musk, Sandalwood and Cedar.',
        3.82,
        1,
        NULL
      ),
(
        'Brisa-Cubana-88990',
        'Brisa Cubana Escada',
        'Brisa',
        'for women',
        NULL,
        NULL,
        'Lime and Mojito',
        'Mint',
        'Mariposa Lily',
        'citrus,green,aromatic,fresh spicy,fresh',
        'Brisa CubanabyEscadais a fragrance for women. This is a new fragrance.Brisa Cubanawas launched in 2024. Top notes are Lime and Mojito; middle note is Mint; base note is Mariposa Lily.',
        3.75,
        192,
        NULL
      ),
(
        'Cherry-In-Japan-70279',
        'Cherry In Japan Escada',
        'Cherry',
        'for women',
        NULL,
        'Honorine Blanc',
        'Cherry Blossom',
        'Jasmine',
        'Tonka Bean',
        'floral,fresh,vanilla,white floral,fruity',
        'Cherry In JapanbyEscadais a Floral fragrance for women.Cherry In Japanwas launched in 2021. The nose behind this fragrance is Honorine Blanc. Top note is Cherry Blossom; middle note is Jasmine; base note is Tonka Bean.',
        3.77,
        721,
        NULL
      ),
(
        'Cherry-in-the-Air-17129',
        'Cherry in the Air Escada',
        'Cherry',
        'for women',
        NULL,
        NULL,
        'Sour Cherry, Raspberry, Daim and Mandarin Orange',
        'Marshmallow, Vanilla, Gardenia and Orchid',
        'White Suede, Sandalwood, Musk and Oak',
        'sweet,cherry,fruity,powdery,nutty',
        'Cherry in the AirbyEscadais a Floral Fruity fragrance for women.Cherry in the Airwas launched in 2013. Top notes are Sour Cherry, Raspberry, Daim and Mandarin Orange; middle notes are Marshmallow, Vanilla, Gardenia and Orchid; base notes are White Suede, Sandalwood, Musk and Oak.',
        4.04,
        2,
        NULL
      ),
(
        'Chiffon-Sorbet-3868',
        'Chiffon Sorbet Escada',
        'Chiffon',
        'for women',
        NULL,
        'Anne Flipo',
        'Black Currant, Raspberry, Mango and Red Apple',
        'black fig, Plum, Rose, Violet and Jasmine',
        'Vanille, Musk, Sandalwood, Amber and Virginia Cedar',
        'fruity,sweet,woody,powdery',
        'Chiffon SorbetbyEscadais a Floral Fruity fragrance for women.Chiffon Sorbetwas launched in 1993. The nose behind this fragrance is Anne Flipo. Top notes are Black Currant, Raspberry, Mango and Red Apple; middle notes are black fig, Plum, Rose, Violet and Jasmine; base notes are Vanille, Musk, Sandalwood, Amber and Virginia Cedar.',
        3.76,
        91,
        NULL
      ),
(
        'Escada-Blue-Romance-1374',
        'Escada Blue Romance Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,floral,rose,white floral',
        'Escada Blue RomancebyEscadais a Floral Fruity fragrance for women.Escada Blue Romancewas launched in 1995.',
        4.15,
        60,
        NULL
      ),
(
        'Escada-Island-Kiss-2011-14011',
        'Escada Island Kiss 2011 Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        'Mango, Passion Flower and Orange',
        'Peach and Magnolia',
        'Red Berries, Musk and Woodsy Notes',
        'fruity,sweet,tropical,floral,citrus',
        'Escada Island Kiss 2011byEscadais a Floral Fruity fragrance for women.Escada Island Kiss 2011was launched in 2011. Top notes are Mango, Passion Flower and Orange; middle notes are Peach and Magnolia; base notes are Red Berries, Musk and Woodsy Notes.',
        3.95,
        917,
        NULL
      ),
(
        'Escada-Loving-Bouquet-1367',
        'Escada Loving Bouquet Escada',
        'Escada',
        'for women',
        NULL,
        'Annick Menardo',
        'Violet Leaf, Peach, Bergamot, Mandarin Orange and Lemon',
        'Violet, Iris, Tea, Lily-of-the-Valley, Orris Root, Jasmine and Rose',
        'Musk, Sandalwood and Cedar',
        'powdery,woody,violet,iris,white floral',
        'Escada Loving BouquetbyEscadais a Floral fragrance for women.Escada Loving Bouquetwas launched in 1999. The nose behind this fragrance is Annick Menardo. Top notes are Violet Leaf, Peach, Bergamot, Mandarin Orange and Lemon; middle notes are Violet, Iris, Tea, Lily-of-the-Valley, Orris Root, Jasmine and Rose; base notes are Musk, Sandalwood and Cedar.',
        4.16,
        187,
        NULL
      ),
(
        'Escada-Marine-Groove-7303',
        'Escada Marine Groove Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh,tropical,fruity,sweet,floral',
        'Escada Marine GroovebyEscadais a Floral Fruity fragrance for women.Escada Marine Groovewas launched in 2009.',
        3.91,
        1,
        NULL
      ),
(
        'Escada-Moon-Sparkle-1887',
        'Escada Moon Sparkle Escada',
        'Escada',
        'for women',
        NULL,
        'Aurélien Guichard',
        'Strawberry, Black Currant, Red Apple and Citruses',
        'Sweet Pea, Freesia, Jasmine and Rose',
        'Raspberry, Musk, Sandalwood and Amber',
        'fruity,sweet,floral',
        'Escada Moon SparklebyEscadais a Floral Fruity fragrance for women.Escada Moon Sparklewas launched in 2007. The nose behind this fragrance is Aurélien Guichard. Top notes are Strawberry, Black Currant, Red Apple and Citruses; middle notes are Sweet Pea, Freesia, Jasmine and Rose; base notes are Raspberry, Musk, Sandalwood and Amber.',
        4.23,
        2,
        NULL
      ),
(
        'Escada-Moon-Sparkle-pour-Homme-2208',
        'Escada Moon Sparkle pour Homme Escada',
        'Escada',
        'for men',
        NULL,
        NULL,
        'Ginger, Mandarin Orange, Pepper and Bergamot',
        'Vodka, Floral Notes and Violet',
        'Cedar and Vetiver',
        'citrus,fresh spicy,warm spicy,floral,vodka',
        'Escada Moon Sparkle pour HommebyEscadais a Woody Aromatic fragrance for men.Escada Moon Sparkle pour Hommewas launched in 2007. Top notes are Ginger, Mandarin Orange, Pepper and Bergamot; middle notes are Vodka, Floral Notes and Violet; base notes are Cedar and Vetiver.',
        3.9,
        272,
        NULL
      ),
(
        'Escada-Rockin-Rio-2011-14009',
        'Escada Rockin'' Rio 2011 Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        'Papaya, Pineapple, Tangerine and Coconut',
        'Peach, Piña Colada and Sugar Cane',
        'Musk and Sandalwood',
        'sweet,fruity,tropical,coconut,citrus',
        'Escada Rockin'' Rio 2011byEscadais a Floral Fruity fragrance for women.Escada Rockin'' Rio 2011was launched in 2011. Top notes are Papaya, Pineapple, Tangerine and Coconut; middle notes are Peach, Piña Colada and Sugar Cane; base notes are Musk and Sandalwood.',
        4.01,
        1,
        NULL
      ),
(
        'Escada-Sexy-Graffiti-2011-14010',
        'Escada Sexy Graffiti 2011 Escada',
        'Escada',
        'for women',
        NULL,
        NULL,
        'Raspberry, Strawberry, Grapefruit and Mint',
        'Peony, Lily-of-the-Valley and Violet',
        'Vanille, Cashmere Wood and Musk',
        'fruity,sweet,citrus,green',
        'Escada Sexy Graffiti 2011byEscadais a Floral Fruity fragrance for women.Escada Sexy Graffiti 2011was launched in 2011. Top notes are Raspberry, Strawberry, Grapefruit and Mint; middle notes are Peony, Lily-of-the-Valley and Violet; base notes are Vanille, Cashmere Wood and Musk.',
        4,
        873,
        NULL
      ),
(
        'Escada-Summer-Festival-64643',
        'Escada Summer Festival Escada',
        'Escada',
        'for women',
        NULL,
        'Amandine Clerc-Marie',
        'Ice and Cherry Blossom',
        'Green Mandarin and Jasmine Sambac',
        'Sandalwood',
        'fresh,floral,citrus,aquatic,fruity',
        'Escada Summer FestivalbyEscadais a Floral fragrance for women.Escada Summer Festivalwas launched in 2021. Escada Summer Festival was created by Amandine Clerc-Marie and Gabriela Chelariu. Top notes are Ice and Cherry Blossom; middle notes are Green Mandarin and Jasmine Sambac; base note is Sandalwood.',
        3.85,
        426,
        NULL
      ),
(
        'Fiesta-Carioca-41897',
        'Fiesta Carioca Escada',
        'Fiesta',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Raspberry and Violet Leaf',
        'Passion Flower, Jasmine and Orange Blossom',
        'Musk, Benzoin and Cedar',
        'fruity,sweet,tropical,floral,fresh',
        'Fiesta CariocabyEscadais a Floral Fruity fragrance for women.Fiesta Cariocawas launched in 2017. Top notes are Passionfruit, Raspberry and Violet Leaf; middle notes are Passion Flower, Jasmine and Orange Blossom; base notes are Musk, Benzoin and Cedar.',
        3.71,
        706,
        NULL
      ),
(
        'Flor-del-Sol-58398',
        'Flor del Sol Escada',
        'Flor',
        'for women',
        NULL,
        NULL,
        'Grenadine, Tequila and Orange',
        'Dahlia',
        'Sandalwood',
        'fruity,aromatic,sweet,citrus,alcohol',
        'Flor del SolbyEscadais a Floral Fruity fragrance for women.Flor del Solwas launched in 2020. Top notes are Grenadine, Tequila and Orange; middle note is Dahlia; base note is Sandalwood.',
        3.88,
        647,
        NULL
      ),
(
        'Ibiza-Hippie-1356',
        'Ibiza Hippie Escada',
        'Ibiza',
        'for women',
        NULL,
        'Michel Almairac',
        'Black Currant, Litchi, Cassia, Peach and Pear',
        'Cranberry, Freesia and Hiacynth',
        'Musk, Sandalwood and Amber',
        'fruity,floral,woody,green,soft spicy',
        'Ibiza HippiebyEscadais a Floral fragrance for women.Ibiza Hippiewas launched in 2003. Ibiza Hippie was created by Richard Ibanez and Michel Almairac. Top notes are Black Currant, Litchi, Cassia, Peach and Pear; middle notes are Cranberry, Freesia and Hiacynth; base notes are Musk, Sandalwood and Amber.',
        4.25,
        792,
        NULL
      ),
(
        'Island-Kiss-1355',
        'Island Kiss Escada',
        'Island',
        'for women',
        NULL,
        'Philippe Romano',
        'Mango, Passionfruit, Raspberry, Passion Flower, Orange, Magnolia and White Flowers',
        'White Peach, Red Berries, Hibiscus and Rose Hip',
        'Musk, Sandalwood and White Woods',
        'fruity,sweet,tropical,floral',
        'Island KissbyEscadais a Floral Fruity fragrance for women.Island Kisswas launched in 2004. The nose behind this fragrance is Philippe Romano. Top notes are Mango, Passionfruit, Raspberry, Passion Flower, Orange, Magnolia and White Flowers; middle notes are White Peach, Red Berries, Hibiscus and Rose Hip; base notes are Musk, Sandalwood and White Woods.',
        4,
        1,
        NULL
      ),
(
        'Jardin-de-Soleil-1354',
        'Jardin de Soleil Escada',
        'Jardin',
        'for women',
        NULL,
        'Sophie Labbé',
        'Gardenia, Tuberose, Peach, Raspberry and Neroli',
        'Hiacynth and Orange Blossom',
        'Oakmoss and Sandalwood',
        'white floral,fruity,green,floral,sweet',
        'Jardin de SoleilbyEscadais a Floral fragrance for women.Jardin de Soleilwas launched in 1996. The nose behind this fragrance is Sophie Labbe. Top notes are Gardenia, Tuberose, Peach, Raspberry and Neroli; middle notes are Hiacynth and Orange Blossom; base notes are Oakmoss and Sandalwood.',
        3.99,
        187,
        NULL
      ),
(
        'Lily-Chic-1353',
        'Lily Chic Escada',
        'Lily',
        'for women',
        NULL,
        'Francis Kurkdjian',
        'Green Apple and Pear',
        'Lily-of-the-Valley and Lemon Tree',
        'Lime, Grapefruit and Amber',
        'citrus,fresh,white floral,fruity,green',
        'Lily ChicbyEscadais a Floral Fruity fragrance for women.Lily Chicwas launched in 2000. The nose behind this fragrance is Francis Kurkdjian. Top notes are Green Apple and Pear; middle notes are Lily-of-the-Valley and Lemon Tree; base notes are Lime, Grapefruit and Amber.',
        3.99,
        287,
        NULL
      ),
(
        'Miami-Blossom-53054',
        'Miami Blossom Escada',
        'Miami',
        'for women',
        NULL,
        'Caroline Sabas',
        'Watermelon, Blueberry and Orange',
        'Pineapple, Tiare Flower, Jasmine and Tuberose',
        'Ambroxan, Musk and Sandalwood',
        'fruity,sweet,white floral,ozonic,tropical',
        'Miami BlossombyEscadais a Floral Fruity fragrance for women.Miami Blossomwas launched in 2019. The nose behind this fragrance is Caroline Sabas. Top notes are Watermelon, Blueberry and Orange; middle notes are Pineapple, Tiare Flower, Jasmine and Tuberose; base notes are Ambroxan, Musk and Sandalwood.',
        3.96,
        729,
        NULL
      ),
(
        'Nectar-de-Costa-Rica-88837',
        'Nectar de Costa Rica Escada',
        'Nectar',
        'for women',
        NULL,
        NULL,
        'Mango and Pineapple',
        'Orange Blossom and Jasmine',
        'Musk and Cedar',
        'fruity,tropical,sweet,white floral',
        'Nectar de Costa RicabyEscadais a Floral Fruity fragrance for women. This is a new fragrance.Nectar de Costa Ricawas launched in 2024. Top notes are Mango and Pineapple; middle notes are Orange Blossom and Jasmine; base notes are Musk and Cedar.',
        4.08,
        25,
        NULL
      ),
(
        'Ocean-Blue-1362',
        'Ocean Blue Escada',
        'Ocean',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,musky,rose,powdery,sweet',
        'Ocean BluebyEscadais a Floral Fruity fragrance for women.Ocean Bluewas launched in 1995.',
        4.19,
        89,
        NULL
      ),
(
        'Ocean-Lounge-4720',
        'Ocean Lounge Escada',
        'Ocean',
        'for women',
        NULL,
        NULL,
        'Big Strawberry, Litchi, Pear and Plum',
        'Violet, Mimosa and Jasmine',
        'Vanilla, Amber and Teak Wood',
        'fruity,sweet,fresh',
        'Ocean LoungebyEscadais a Floral Fruity fragrance for women.Ocean Loungewas launched in 2008. Top notes are Big Strawberry, Litchi, Pear and Plum; middle notes are Violet, Mimosa and Jasmine; base notes are Vanilla, Amber and Teak Wood.',
        3.79,
        1,
        NULL
      ),
(
        'Pacific-Paradise-834',
        'Pacific Paradise Escada',
        'Pacific',
        'for women',
        NULL,
        'Philippe Romano',
        'Banana, Coconut, Apple, Lime and Lemon',
        'Sugar Cane, Banana and Sunflower',
        'Musk, Sandalwood and Amber',
        'sweet,fruity,citrus,coconut,tropical',
        'Pacific ParadisebyEscadais a Floral Fruity fragrance for women.Pacific Paradisewas launched in 2006. The nose behind this fragrance is Philippe Romano. Top notes are Banana, Coconut, Apple, Lime and Lemon; middle notes are Sugar Cane, Banana and Sunflower; base notes are Musk, Sandalwood and Amber.',
        4.05,
        1,
        NULL
      ),
(
        'Que-Viva-Escada-11642',
        'Que Viva Escada Escada',
        'Que',
        'for women',
        NULL,
        NULL,
        'Passionfruit and Pineapple',
        'Red Apple, Floral Notes and Pear',
        'Woodsy Notes and Musk',
        'fruity,sweet,tropical,fresh,floral',
        'Que Viva EscadabyEscadais a Floral Fruity fragrance for women.Que Viva Escadawas launched in 1997. Top notes are Passionfruit and Pineapple; middle notes are Red Apple, Floral Notes and Pear; base notes are Woodsy Notes and Musk.',
        4.27,
        162,
        NULL
      ),
(
        'Rockin-Rio-1351',
        'Rockin'' Rio Escada',
        'Rockin''',
        'for women',
        NULL,
        'Philippe Romano',
        'Pineapple, Papaya and Mandarin Orange',
        'Peach and Sugar Cane',
        'Coconut, Sandalwood and Musk',
        'sweet,tropical,fruity,citrus,coconut',
        'Rockin'' RiobyEscadais a Floral Fruity fragrance for women.Rockin'' Riowas launched in 2005. The nose behind this fragrance is Philippe Romano. Top notes are Pineapple, Papaya and Mandarin Orange; middle notes are Peach and Sugar Cane; base notes are Coconut, Sandalwood and Musk.',
        3.99,
        1,
        NULL
      ),
(
        'Santorini-Sunrise-78425',
        'Santorini Sunrise Escada',
        'Santorini',
        'for women',
        NULL,
        'Benoist Lapouza',
        'Sorbet, Mandarin Orange and Bergamot',
        'Bougainvillea, Jasmine and Pink Pepper',
        'Earthy Notes',
        'citrus,sweet,fruity,earthy,floral',
        'Santorini SunrisebyEscadais a fragrance for women. This is a new fragrance.Santorini Sunrisewas launched in 2022. Santorini Sunrise was created by Mylène Alran and Benoist Lapouza. Top notes are Sorbet, Mandarin Orange and Bergamot; middle notes are Bougainvillea, Jasmine and Pink Pepper; base note is Earthy Notes.',
        3.86,
        436,
        NULL
      ),
(
        'Sexy-Graffiti-1352',
        'Sexy Graffiti Escada',
        'Sexy',
        'for women',
        NULL,
        'Dominique Ropion',
        'Raspberry, Black Currant, Strawberry, Pink Grapefruit and Cassia',
        'Violet, Red Peony, Lily-of-the-Valley and Lily',
        'Musk, Cashmere Wood and Vanilla',
        'fruity,sweet,woody',
        'Sexy GraffitibyEscadais a Floral Fruity fragrance for women.Sexy Graffitiwas launched in 2002. Sexy Graffiti was created by Dominique Ropion and Laurent Bruyere. Top notes are Raspberry, Black Currant, Strawberry, Pink Grapefruit and Cassia; middle notes are Violet, Red Peony, Lily-of-the-Valley and Lily; base notes are Musk, Cashmere Wood and Vanilla.',
        4.23,
        758,
        NULL
      ),
(
        'Sorbetto-Rosso-47255',
        'Sorbetto Rosso Escada',
        'Sorbetto',
        'for women',
        NULL,
        NULL,
        'Pear, Calone and Tangerine',
        'Watermelon, Watery Notes, Strawberry, Apple, Sea Salt, Tiare Flower, Hedione and Rose',
        'Praline, Musk and Amber',
        'aquatic,ozonic,fruity,sweet,fresh',
        'Sorbetto RossobyEscadais a Aromatic Fruity fragrance for women.Sorbetto Rossowas launched in 2018. Top notes are Pear, Calone and Tangerine; middle notes are Watermelon, Watery Notes, Strawberry, Apple, Sea Salt, Tiare Flower, Hedione and Rose; base notes are Praline, Musk and Amber.',
        3.94,
        1,
        NULL
      ),
(
        'Sunny-Frutti-1350',
        'Sunny Frutti Escada',
        'Sunny',
        'for women',
        NULL,
        'Dorothée Piot',
        'Banana, Pear, Pineapple, Lemon, Black Currant, Osmanthus and False Jasmine',
        'Freesia, Apricot, Cyclamen, Jasmine, Lily-of-the-Valley, Rose and Orris Root',
        'Cedar, Vanilla, Musk and Oakmoss',
        'fruity,sweet,floral,fresh,tropical',
        'Sunny FruttibyEscadais a Floral Fruity fragrance for women.Sunny Fruttiwas launched in 1998. The nose behind this fragrance is Dorothée Piot. Top notes are Banana, Pear, Pineapple, Lemon, Black Currant, Osmanthus and False Jasmine; middle notes are Freesia, Apricot, Cyclamen, Jasmine, Lily-of-the-Valley, Rose and Orris Root; base notes are Cedar, Vanilla, Musk and Oakmoss.',
        4.03,
        200,
        NULL
      ),
(
        'Sunset-Heat-835',
        'Sunset Heat Escada',
        'Sunset',
        'for women',
        NULL,
        NULL,
        'Mango, Papaya, Pineapple and Lemon',
        'Peach',
        'Coconut, Hibiscus and Sandalwood',
        'tropical,fruity,sweet',
        'Sunset HeatbyEscadais a Floral Fruity fragrance for women.Sunset Heatwas launched in 2007. Top notes are Mango, Papaya, Pineapple and Lemon; middle note is Peach; base notes are Coconut, Hibiscus and Sandalwood.',
        4.04,
        1,
        NULL
      ),
(
        'Sunset-Heat-for-Men-836',
        'Sunset Heat for Men Escada',
        'Sunset',
        'for men',
        NULL,
        'Jean-Louis Grauby',
        'Carambola (Star Fruit), Grapefruit and Lemon',
        'Green Leaves, Hibiscus and Lavender',
        'Musk and Amber',
        'citrus,fruity,tropical,green,musky',
        'Sunset Heat for MenbyEscadais a Woody Aquatic fragrance for men.Sunset Heat for Menwas launched in 2007. The nose behind this fragrance is Jean-Louis Grauby. Top notes are Carambola (Star Fruit), Grapefruit and Lemon; middle notes are Green Leaves, Hibiscus and Lavender; base notes are Musk and Amber.',
        4.18,
        230,
        NULL
      ),
(
        'Taj-Sunset-10611',
        'Taj Sunset Escada',
        'Taj',
        'for women',
        NULL,
        NULL,
        'Mango, Nectarine and Blood Orange',
        'Raspberry, Star apple, Water Lily and Lotus',
        'Coconut, Musk and Sandalwood',
        'fruity,sweet,tropical,citrus',
        'Taj SunsetbyEscadais a Floral Fruity fragrance for women.Taj Sunsetwas launched in 2011. Top notes are Mango, Nectarine and Blood Orange; middle notes are Raspberry, Star apple, Water Lily and Lotus; base notes are Coconut, Musk and Sandalwood.',
        4.17,
        3,
        NULL
      ),
(
        'Tender-Light-1349',
        'Tender Light Escada',
        'Tender',
        'for women',
        NULL,
        'Bertrand Duchaufour',
        'Orange Blossom, Peach, Bergamot and Lemon',
        'Tuberose, Hiacynth, Ylang-Ylang and Orchid',
        'Amber, Oakmoss, Sandalwood and Cedar',
        'white floral,floral,woody,citrus,sweet',
        'Tender LightbyEscadais a Floral fragrance for women.Tender Lightwas launched in 1999. The nose behind this fragrance is Bertrand Duchaufour. Top notes are Orange Blossom, Peach, Bergamot and Lemon; middle notes are Tuberose, Hiacynth, Ylang-Ylang and Orchid; base notes are Amber, Oakmoss, Sandalwood and Cedar.',
        3.94,
        67,
        NULL
      ),
(
        'Tropical-Punch-1348',
        'Tropical Punch Escada',
        'Tropical',
        'for women',
        NULL,
        'Philippe Romano',
        'Papaya, Pear and Pomegranate',
        'White Peach, Hibiscus, Freesia and Lily-of-the-Valley',
        'White Musk and Amber',
        'fruity,sweet,tropical,floral,woody',
        'Tropical PunchbyEscadais a Floral Fruity fragrance for women.Tropical Punchwas launched in 2001. The nose behind this fragrance is Philippe Romano. Top notes are Papaya, Pear and Pomegranate; middle notes are White Peach, Hibiscus, Freesia and Lily-of-the-Valley; base notes are White Musk and Amber.',
        4.18,
        511,
        NULL
      ),
(
        'Turquoise-Summer-28630',
        'Turquoise Summer Escada',
        'Turquoise',
        'for women',
        NULL,
        NULL,
        'Fruits, Big Strawberry, Pineapple, Raspberry, Black Currant, Rhubarb, Orange and Lemon',
        'Melon, Peach, Violet, Orange Blossom and Rose',
        'Milk, Caramel, Vanilla, Musk and Sandalwood',
        'fruity,sweet',
        'Turquoise SummerbyEscadais a Floral Fruity fragrance for women.Turquoise Summerwas launched in 2015. Top notes are Fruits, Big Strawberry, Pineapple, Raspberry, Black Currant, Rhubarb, Orange and Lemon; middle notes are Melon, Peach, Violet, Orange Blossom and Rose; base notes are Milk, Caramel, Vanilla, Musk and Sandalwood.',
        3.75,
        887,
        NULL
      ),
(
        'Un-Ete-En-Provence-11641',
        'Un Ete En Provence Escada',
        'Un',
        'for women',
        NULL,
        NULL,
        'Cherry, Nectarine, Red Apple, Pear and Pineapple',
        'Litchi, Peony, Watermelon, Lotus, Cyclamen and Jasmine',
        'Praline, Sandalwood, Amber and Virginia Cedar',
        'sweet,fruity,fresh,floral,aquatic',
        'Un Ete En ProvencebyEscadais a Floral Fruity Gourmand fragrance for women.Un Ete En Provencewas launched in 1994. Top notes are Cherry, Nectarine, Red Apple, Pear and Pineapple; middle notes are Litchi, Peony, Watermelon, Lotus, Cyclamen and Jasmine; base notes are Praline, Sandalwood, Amber and Virginia Cedar.',
        4.12,
        108,
        NULL
      ),
(
        'Escentric-01-846',
        'Escentric 01 Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,citrus,amber,soft spicy',
        'Escentric 01byEscentric Moleculesis a Woody Floral Musk fragrance for women and men.Escentric 01was launched in 2006. The nose behind this fragrance is Geza Schoen.',
        4.01,
        3,
        NULL
      ),
(
        'Escentric-01-Limited-Edition-39205',
        'Escentric 01 Limited Edition Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        'Iso E Super and Pink Pepper',
        'Iris',
        'Lime',
        'woody,musky,citrus,iris,amber',
        'Escentric 01 Limited EditionbyEscentric Moleculesis a fragrance for women and men.Escentric 01 Limited Editionwas launched in 2011. The nose behind this fragrance is Geza Schoen. Top notes are Iso E Super and Pink Pepper; middle note is Iris; base note is Lime.',
        4.15,
        68,
        NULL
      ),
(
        'Escentric-02-3607',
        'Escentric 02 Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'amber,musky,woody,iris,powdery',
        'Escentric 02byEscentric Moleculesis a Amber Floral fragrance for women and men.Escentric 02was launched in 2008. The nose behind this fragrance is Geza Schoen.',
        3.97,
        4,
        NULL
      ),
(
        'Escentric-03-10555',
        'Escentric 03 Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        'Lime, Ginger and Pepper',
        'Tea, Iris and Jasmine',
        'Vetiver, Virginia Cedar, Leather, Sandalwood and Musk',
        'woody,citrus,aromatic,warm spicy,fresh spicy',
        'Escentric 03byEscentric Moleculesis a Chypre fragrance for women and men.Escentric 03was launched in 2010. The nose behind this fragrance is Geza Schoen. Top notes are Lime, Ginger and Pepper; middle notes are Tea, Iris and Jasmine; base notes are Vetiver, Virginia Cedar, Leather, Sandalwood and Musk.',
        3.67,
        1,
        NULL
      ),
(
        'Escentric-04-42995',
        'Escentric 04 Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'aromatic,citrus,woody,fresh spicy,balsamic',
        'Escentric 04byEscentric Moleculesis a Woody fragrance for women and men.Escentric 04was launched in 2017. The nose behind this fragrance is Geza Schoen.',
        3.65,
        1,
        NULL
      ),
(
        'Escentric-05-58970',
        'Escentric 05 Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        'Juniper, Bergamot, Rosemary, Orange, Laurels, Fig Leaf, Basil and Fig',
        'Cypress, Hedione, Iris, Freesia and Jasmine',
        'Cashmeran, Iso E Super, Ambroxan, Musk, Mastic or Lentisque and Labdanum',
        'woody,aromatic,fresh spicy,musky,amber',
        'Escentric 05byEscentric Moleculesis a fragrance for women and men.Escentric 05was launched in 2020. The nose behind this fragrance is Geza Schoen. Top notes are Juniper, Bergamot, Rosemary, Orange, Laurels, Fig Leaf, Basil and Fig; middle notes are Cypress, Hedione, Iris, Freesia and Jasmine; base notes are Cashmeran, Iso E Super, Ambroxan, Musk, Mastic or Lentisque and Labdanum.',
        3.96,
        1,
        NULL
      ),
(
        'H01-83318',
        'H01 Escentric Molecules',
        'H01',
        'for women and men',
        NULL,
        'Geza Schoen',
        'Bergamot, Mandarin Orange, Orange Blossom and Lime',
        'Davana, Plum, Peach and Freesia',
        'Vetiver, Sandalwood, Iso E Super, Patchouli, Musk and Amber',
        'woody,citrus,aromatic,musky,powdery',
        'H01byEscentric Moleculesis a Woody Floral Musk fragrance for women and men. This is a new fragrance.H01was launched in 2023. The nose behind this fragrance is Geza Schoen. Top notes are Bergamot, Mandarin Orange, Orange Blossom and Lime; middle notes are Davana, Plum, Peach and Freesia; base notes are Vetiver, Sandalwood, Iso E Super, Patchouli, Musk and Amber.',
        3,
        22,
        NULL
      ),
(
        'Molecule-01-845',
        'Molecule 01 Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,amber,animalic',
        'Molecule 01byEscentric Moleculesis a Woody Floral Musk fragrance for women and men.Molecule 01was launched in 2006. The nose behind this fragrance is Geza Schoen.',
        4,
        8,
        NULL
      ),
(
        'Molecule-01-Limited-Edition-39204',
        'Molecule 01 Limited Edition Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,amber,animalic',
        'Molecule 01 Limited EditionbyEscentric Moleculesis a fragrance for women and men.Molecule 01 Limited Editionwas launched in 2016. The nose behind this fragrance is Geza Schoen.',
        4.03,
        39,
        NULL
      ),
(
        'Molecule-02-3606',
        'Molecule 02 Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'amber,musky',
        'Molecule 02byEscentric Moleculesis a Amber fragrance for women and men.Molecule 02was launched in 2008. The nose behind this fragrance is Geza Schoen.',
        3.95,
        4,
        NULL
      ),
(
        'Molecule-03-10556',
        'Molecule 03 Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'aromatic,woody,earthy,green',
        'Molecule 03byEscentric Moleculesis a fragrance for women and men.Molecule 03was launched in 2010. The nose behind this fragrance is Geza Schoen.',
        3.33,
        1,
        NULL
      ),
(
        'Molecule-04-44315',
        'Molecule 04 Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,powdery,warm spicy',
        'Molecule 04byEscentric Moleculesis a Woody fragrance for women and men.Molecule 04was launched in 2017. The nose behind this fragrance is Geza Schoen.',
        3.47,
        1,
        NULL
      ),
(
        'Molecule-05-58969',
        'Molecule 05 Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,powdery,amber',
        'Molecule 05byEscentric Moleculesis a Woody Aromatic fragrance for women and men.Molecule 05was launched in 2020. The nose behind this fragrance is Geza Schoen.',
        3.13,
        852,
        NULL
      ),
(
        'Escentric-01-Limited-Edition-15-Years-74183',
        'Escentric 01 Limited Edition 15 Years Escentric Molecules',
        'Escentric',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,iris,citrus,amber',
        'Escentric 01 Limited Edition 15 YearsbyEscentric Moleculesis a Woody fragrance for women and men.Escentric 01 Limited Edition 15 Yearswas launched in 2021. The nose behind this fragrance is Geza Schoen.',
        4.24,
        41,
        NULL
      ),
(
        'Molecule-01-Limited-Edition-15-Years-74182',
        'Molecule 01 Limited Edition 15 Years Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,amber,animalic',
        'Molecule 01 Limited Edition 15 YearsbyEscentric Moleculesis a Woody fragrance for women and men.Molecule 01 Limited Edition 15 Yearswas launched in 2021. The nose behind this fragrance is Geza Schoen.',
        4.32,
        25,
        NULL
      ),
(
        'Molecule-01-Black-Tea-79414',
        'Molecule 01 + Black Tea Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'green,woody,musky,amber,fresh',
        'Molecule 01 + Black TeabyEscentric Moleculesis a Aromatic fragrance for women and men. This is a new fragrance.Molecule 01 + Black Teawas launched in 2023. The nose behind this fragrance is Geza Schoen.',
        4.05,
        464,
        NULL
      ),
(
        'Molecule-01-Ginger-79413',
        'Molecule 01 + Ginger Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,musky,amber,fresh',
        'Molecule 01 + GingerbyEscentric Moleculesis a Aromatic Spicy fragrance for women and men. This is a new fragrance.Molecule 01 + Gingerwas launched in 2023. The nose behind this fragrance is Geza Schoen.',
        4.12,
        260,
        NULL
      ),
(
        'Molecule-01-Guaiac-Wood-79412',
        'Molecule 01 + Guaiac Wood Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,musky,amber',
        'Molecule 01 + Guaiac WoodbyEscentric Moleculesis a Woody fragrance for women and men. This is a new fragrance.Molecule 01 + Guaiac Woodwas launched in 2023. The nose behind this fragrance is Geza Schoen.',
        3.61,
        150,
        NULL
      ),
(
        'Molecule-01-Iris-66048',
        'Molecule 01 + Iris Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'iris,woody,powdery,musky,amber',
        'Molecule 01 + IrisbyEscentric Moleculesis a Woody fragrance for women and men.Molecule 01 + Iriswas launched in 2021. The nose behind this fragrance is Geza Schoen.',
        4.11,
        1,
        NULL
      ),
(
        'Molecule-01-Mandarin-66047',
        'Molecule 01 + Mandarin Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'citrus,woody,musky,amber',
        'Molecule 01 + MandarinbyEscentric Moleculesis a Citrus fragrance for women and men.Molecule 01 + Mandarinwas launched in 2021. The nose behind this fragrance is Geza Schoen.',
        4,
        1,
        NULL
      ),
(
        'Molecule-01-Patchouli-66049',
        'Molecule 01 + Patchouli Escentric Molecules',
        'Molecule',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'woody,patchouli,musky,warm spicy,amber',
        'Molecule 01 + PatchoulibyEscentric Moleculesis a Woody fragrance for women and men.Molecule 01 + Patchouliwas launched in 2021. The nose behind this fragrance is Geza Schoen.',
        3.97,
        738,
        NULL
      ),
(
        'Power-of-10-Limited-Edition-Escentric-02-56079',
        'Power of 10 Limited Edition Escentric 02 Escentric Molecules',
        'Power',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'amber,musky,iris,powdery,woody',
        'Power of 10 Limited Edition Escentric 02byEscentric Moleculesis a Amber Floral fragrance for women and men.Power of 10 Limited Edition Escentric 02was launched in 2018. The nose behind this fragrance is Geza Schoen.',
        3.72,
        36,
        NULL
      ),
(
        'Power-of-10-Limited-Edition-Molecule-02-56078',
        'Power of 10 Limited Edition Molecule 02 Escentric Molecules',
        'Power',
        'for women and men',
        NULL,
        'Geza Schoen',
        NULL,
        NULL,
        NULL,
        'amber,musky',
        'Power of 10 Limited Edition Molecule 02byEscentric Moleculesis a fragrance for women and men.Power of 10 Limited Edition Molecule 02was launched in 2018. The nose behind this fragrance is Geza Schoen.',
        4.07,
        28,
        NULL
      ),
(
        'Bois-Imperial-64338',
        'Bois Impérial Essential Parfums',
        'Bois',
        'for women and men',
        NULL,
        'Quentin Bisch',
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,aromatic,oud,amber',
        'Bois ImpérialbyEssential Parfumsis a Aromatic fragrance for women and men.Bois Impérialwas launched in 2020. The nose behind this fragrance is Quentin Bisch.',
        4.2,
        5,
        NULL
      ),
(
        'Divine-Vanille-57088',
        'Divine Vanille Essential Parfums',
        'Divine',
        'for women and men',
        NULL,
        'Olivier Pescheux',
        'Cinnamon, Black Pepper and Clary Sage',
        'Incense, Osmanthus and Pomarose',
        'Madagascar Vanilla, Tonka Bean, Siam Benzoin, Patchouli, Texas Cedar and Musk',
        'vanilla,warm spicy,amber,cinnamon,balsamic',
        'Divine VanillebyEssential Parfumsis a Amber Vanilla fragrance for women and men.Divine Vanillewas launched in 2019. The nose behind this fragrance is Olivier Pescheux. Top notes are Cinnamon, Black Pepper and Clary Sage; middle notes are Incense, Osmanthus and Pomarose; base notes are Madagascar Vanilla, Tonka Bean, Siam Benzoin, Patchouli, Texas Cedar and Musk.',
        4.05,
        1,
        NULL
      ),
(
        'Fig-Infusion-73092',
        'Fig Infusion Essential Parfums',
        'Fig',
        'for women and men',
        NULL,
        'Nathalie Lorson',
        NULL,
        NULL,
        NULL,
        'woody,fruity,citrus,sweet,green',
        'Fig InfusionbyEssential Parfumsis a fragrance for women and men. This is a new fragrance.Fig Infusionwas launched in 2022. The nose behind this fragrance is Nathalie Lorson.',
        3.87,
        1,
        NULL
      ),
(
        'Mon-Vetiver-50788',
        'Mon Vetiver Essential Parfums',
        'Mon',
        'for women and men',
        NULL,
        'Bruno Jovanovic',
        NULL,
        NULL,
        NULL,
        'aromatic,woody,citrus,fresh spicy,earthy',
        'Mon VetiverbyEssential Parfumsis a Woody Aromatic fragrance for women and men.Mon Vetiverwas launched in 2018. The nose behind this fragrance is Bruno Jovanovic.',
        3.74,
        782,
        NULL
      ),
(
        'Neroli-Botanica-90834',
        'Néroli Botanica Essential Parfums',
        'Néroli',
        'for women and men',
        NULL,
        'Anne Flipo',
        NULL,
        NULL,
        NULL,
        'white floral,aromatic,citrus,fresh,warm spicy',
        'Néroli BotanicabyEssential Parfumsis a Citrus fragrance for women and men. This is a new fragrance.Néroli Botanicawas launched in 2024. The nose behind this fragrance is Anne Flipo.',
        4.12,
        69,
        NULL
      ),
(
        'Nice-Bergamote-50789',
        'Nice Bergamote Essential Parfums',
        'Nice',
        'for women and men',
        NULL,
        'Antoine Maisondieu',
        NULL,
        NULL,
        NULL,
        'citrus,woody,white floral,fresh spicy,aromatic',
        'Nice BergamotebyEssential Parfumsis a Citrus Aromatic fragrance for women and men.Nice Bergamotewas launched in 2018. The nose behind this fragrance is Antoine Maisondieu.',
        3.98,
        1,
        NULL
      ),
(
        'Orange-X-Santal-50786',
        'Orange X Santal Essential Parfums',
        'Orange',
        'for women and men',
        NULL,
        'Natalie Gracia-Cetto',
        NULL,
        NULL,
        NULL,
        'woody,citrus,fresh spicy,aromatic,fresh',
        'Orange X SantalbyEssential Parfumsis a Citrus Aromatic fragrance for women and men.Orange X Santalwas launched in 2018. The nose behind this fragrance is Natalie Gracia-Cetto.',
        3.75,
        1,
        NULL
      ),
(
        'Patchouli-Mania-85144',
        'Patchouli Mania Essential Parfums',
        'Patchouli',
        'for women and men',
        NULL,
        'Fabrice Pellegrin',
        'Hazelnut, Davana and Coriander',
        'Cacao, Tea and Clearwood',
        'Patchouli, Vetiver and Cetalox',
        'woody,patchouli,warm spicy,aromatic,earthy',
        'Patchouli ManiabyEssential Parfumsis a Chypre fragrance for women and men. This is a new fragrance.Patchouli Maniawas launched in 2023. The nose behind this fragrance is Fabrice Pellegrin. Top notes are Hazelnut, Davana and Coriander; middle notes are Cacao, Tea and Clearwood; base notes are Patchouli, Vetiver and Cetalox.',
        3.79,
        375,
        NULL
      ),
(
        'Rose-Magnetic-50787',
        'Rose Magnetic Essential Parfums',
        'Rose',
        'for women and men',
        NULL,
        'Sophie Labbé',
        NULL,
        NULL,
        NULL,
        'rose,vanilla,citrus,fruity,tropical',
        'Rose MagneticbyEssential Parfumsis a Amber Floral fragrance for women and men.Rose Magneticwas launched in 2018. The nose behind this fragrance is Sophie Labbe.',
        3.92,
        961,
        NULL
      );
