
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Reef-06-89274',
        'Reef 06 Reef Perfumes',
        'Reef',
        'for women',
        NULL,
        NULL,
        'Rose',
        'Citruses',
        'Musk',
        'citrus,musky,rose,fresh,powdery',
        'Reef 06byReef Perfumesis a Amber Woody fragrance for women.Reef 06was launched in 2024. Top note is Rose; middle note is Citruses; base note is Musk.',
        4,
        1,
        NULL
      ),
(
        'Reef-10-89365',
        'Reef 10 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Jasmine',
        'Vanilla',
        'vanilla,citrus,white floral,powdery,sweet',
        'Reef 10byReef Perfumesis a fragrance for women and men. Top note is Mandarin Orange; middle note is Jasmine; base note is Vanilla.',
        4.5,
        2,
        NULL
      ),
(
        'Reef-11-89364',
        'Reef 11 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Pink Pepper',
        'Jasmine',
        'Sandalwood',
        'soft spicy,white floral,woody,powdery,musky',
        'Reef 11byReef Perfumesis a fragrance for women and men. Top note is Pink Pepper; middle note is Jasmine; base note is Sandalwood.',
        4.5,
        2,
        NULL
      ),
(
        'Reef-19-89363',
        'Reef 19 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Lily of the Valley',
        'Jasmine',
        'White Musk',
        'musky,powdery',
        'Reef 19byReef Perfumesis a fragrance for women and men. Top note is Lily of the Valley; middle note is Jasmine; base note is White Musk.',
        4.5,
        6,
        NULL
      ),
(
        'Reef-19-National-Day-89367',
        'Reef 19 National Day Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Lily of the Valley',
        'Jasmine',
        'White Musk',
        'white floral,musky,fresh,powdery,green',
        'Reef 19 National DaybyReef Perfumesis a fragrance for women and men. Top note is Lily of the Valley; middle note is Jasmine; base note is White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Reef-21-89362',
        'Reef 21 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Red Berries',
        'Cedar',
        'Patchouli',
        'woody,fruity,patchouli,sweet,warm spicy',
        'Reef 21byReef Perfumesis a fragrance for women and men. Top note is Red Berries; middle note is Cedar; base note is Patchouli.',
        4.17,
        6,
        NULL
      ),
(
        'Reef-27-89361',
        'Reef 27 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Lily of the Valley',
        'Taif Rose',
        'Olibanum',
        'rose,amber,white floral,fresh,fresh spicy',
        'Reef 27byReef Perfumesis a fragrance for women and men. Top note is Lily of the Valley; middle note is Taif Rose; base note is Olibanum.',
        5,
        1,
        NULL
      ),
(
        'Reef-29-89360',
        'Reef 29 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Saffron',
        'Iris',
        'Amber',
        'iris,powdery,warm spicy,violet,earthy',
        'Reef 29byReef Perfumesis a fragrance for women and men. Top note is Saffron; middle note is Iris; base note is Amber.',
        4.5,
        2,
        NULL
      ),
(
        'Reef-31-89359',
        'Reef 31 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Saffron',
        'Amber',
        'Vanilla',
        'vanilla,powdery,amber,warm spicy,sweet',
        'Reef 31byReef Perfumesis a fragrance for women and men. Top note is Saffron; middle note is Amber; base note is Vanilla.',
        4.43,
        7,
        NULL
      ),
(
        'Reef-33-89358',
        'Reef 33 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        'Indian Saffron',
        'Rosemary',
        'Agarwood (Oud)',
        'aromatic,fresh spicy,warm spicy,oud,metallic',
        'Reef 33byReef Perfumesis a fragrance for women and men. Top note is Indian Saffron; middle note is Rosemary; base note is Agarwood (Oud).',
        4.39,
        18,
        NULL
      ),
(
        'REEF-36-89276',
        'REEF 36 Reef Perfumes',
        'REEF',
        'for women',
        NULL,
        NULL,
        'Pear Blossom',
        'Ylang Ylang',
        'Amber',
        'amber,yellow floral,floral,sweet,woody',
        'REEF 36byReef Perfumesis a Amber Floral fragrance for women.REEF 36was launched in 2024. Top note is Pear Blossom; middle note is Ylang Ylang; base note is Amber.',
        5,
        2,
        NULL
      ),
(
        'Reef-43-89357',
        'Reef 43 Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        'Leather',
        'leather,animalic,smoky',
        'Reef 43byReef Perfumesis a fragrance for women and men. base note is Leather.',
        NULL,
        NULL,
        NULL
      ),
(
        'Reef-43-National-Day-89366',
        'Reef 43 National Day Reef Perfumes',
        'Reef',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        'Leather and Velvet',
        'leather,musky,animalic,powdery,smoky',
        'Reef 43 National DaybyReef Perfumesis a fragrance for women and men. base notes are Leather and Velvet.',
        NULL,
        NULL,
        NULL
      ),
(
        'REEF15-89273',
        'REEF15 Reef Perfumes',
        'REEF15',
        'for men',
        NULL,
        NULL,
        'Bergamot',
        NULL,
        'Oud',
        'citrus,oud,fresh spicy,aromatic',
        'REEF15byReef Perfumesis a Woody Spicy fragrance for men.REEF15was launched in 2024. Top note is Bergamot; base note is Oud.',
        4,
        3,
        NULL
      ),
(
        'Tuwaiq-Arabs-89272',
        'Tuwaiq Arabs Reef Perfumes',
        'Tuwaiq',
        'for women',
        NULL,
        NULL,
        'Magnolia',
        'Jasmine',
        'Vanilla',
        'floral,vanilla,white floral,citrus,powdery',
        'Tuwaiq ArabsbyReef Perfumesis a Floral fragrance for women.Tuwaiq Arabswas launched in 2024. Top note is Magnolia; middle note is Jasmine; base note is Vanilla.',
        4.2,
        5,
        NULL
      ),
(
        'Abaya-Arabs-88807',
        'Abaya Arabs Reef Perfumes',
        'Abaya',
        'for women and men',
        NULL,
        NULL,
        'Pineapple',
        'Leather',
        'Oud',
        'fruity,sweet,leather,oud,tropical',
        'Abaya ArabsbyReef Perfumesis a Chypre Fruity fragrance for women and men.Abaya Arabswas launched in 2021. Top note is Pineapple; middle note is Leather; base note is Oud.',
        4,
        9,
        NULL
      ),
(
        'Niche-1-89355',
        'Niche 1 Reef Perfumes',
        'Niche',
        'for women and men',
        NULL,
        NULL,
        'Saffron',
        'Caramel',
        'Leather',
        'leather,caramel,warm spicy,animalic,metallic',
        'Niche 1byReef Perfumesis a fragrance for women and men. Top note is Saffron; middle note is Caramel; base note is Leather.',
        3,
        1,
        NULL
      ),
(
        'Niche-2-89354',
        'Niche 2 Reef Perfumes',
        'Niche',
        'for women and men',
        NULL,
        NULL,
        'Marine notes',
        'Caramel',
        'Leather',
        'caramel,leather,marine,aromatic,animalic',
        'Niche 2byReef Perfumesis a fragrance for women and men. Top note is Marine notes; middle note is Caramel; base note is Leather.',
        5,
        1,
        NULL
      ),
(
        'Niche-3-89351',
        'Niche 3 Reef Perfumes',
        'Niche',
        'for women and men',
        NULL,
        NULL,
        'Cedar',
        'Saffron',
        'Patchouli',
        'woody,warm spicy,patchouli,earthy,metallic',
        'Niche 3byReef Perfumesis a fragrance for women and men. Top note is Cedar; middle note is Saffron; base note is Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Niche-4-89352',
        'Niche 4 Reef Perfumes',
        'Niche',
        'for women and men',
        NULL,
        NULL,
        'Red Apple',
        'Cinammon',
        'Amber',
        'amber,cinnamon,warm spicy,fruity,sweet',
        'Niche 4byReef Perfumesis a fragrance for women and men. Top note is Red Apple; middle note is Cinammon; base note is Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Niche-5-89353',
        'Niche 5 Reef Perfumes',
        'Niche',
        'for women and men',
        NULL,
        NULL,
        'Black Tea',
        'Patchouli',
        'White Musk',
        'musky,patchouli,green,woody,powdery',
        'Niche 5byReef Perfumesis a fragrance for women and men. Top note is Black Tea; middle note is Patchouli; base note is White Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Summer-Pink-88803',
        'Summer Pink Reef Perfumes',
        'Summer',
        'for women and men',
        NULL,
        NULL,
        'Pear',
        'Amber',
        'Sandalwood',
        'fruity,amber,sweet,aquatic,woody',
        'Summer PinkbyReef Perfumesis a Amber Floral fragrance for women and men. This is a new fragrance.Summer Pinkwas launched in 2023. Top note is Pear; middle note is Amber; base note is Sandalwood.',
        4,
        4,
        NULL
      ),
(
        'Summer-Tiffany-88802',
        'Summer Tiffany Reef Perfumes',
        'Summer',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Peach',
        'Musk',
        'musky,fruity,powdery,citrus,sweet',
        'Summer TiffanybyReef Perfumesis a Floral Fruity fragrance for women and men. This is a new fragrance.Summer Tiffanywas launched in 2023. Top note is Mandarin Orange; middle note is Peach; base note is Musk.',
        4.29,
        7,
        NULL
      ),
(
        'Summer-Yellow-88804',
        'Summer Yellow Reef Perfumes',
        'Summer',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom',
        'Black Currant',
        'Vanilla',
        'white floral,vanilla,fruity,citrus,sweet',
        'Summer YellowbyReef Perfumesis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Summer Yellowwas launched in 2023. Top note is Orange Blossom; middle note is Black Currant; base note is Vanilla.',
        4.91,
        11,
        NULL
      ),
(
        'Agar-Oud-90906',
        'Agar Oud Raydan',
        'Agar',
        'for women and men',
        NULL,
        NULL,
        'Indian Oud',
        'Indian Oud',
        'Indian Oud',
        'oud,fresh spicy',
        'Agar OudbyRaydanis a Woody fragrance for women and men.Agar Oudwas launched during the 2020''s. Top note is Indian Oud; middle note is Indian Oud; base note is Indian Oud.',
        NULL,
        NULL,
        NULL
      ),
(
        'Al-Luban-90702',
        'Al Luban Raydan',
        'Al',
        'for women and men',
        NULL,
        NULL,
        'Frankincense',
        'Frankincense',
        'Frankincense',
        'amber,fresh spicy,warm spicy,woody',
        'Al LubanbyRaydanis a Amber fragrance for women and men.Al Lubanwas launched during the 2010''s. Top note is Frankincense; middle note is Frankincense; base note is Frankincense.',
        5,
        1,
        NULL
      ),
(
        'Amberiya-90912',
        'Amberiya Raydan',
        'Amberiya',
        'for women and men',
        NULL,
        NULL,
        'Immortelle, Honey and Labdanum',
        'Cinnamon Leaf, Patchouli, Cedarwood, Geranium and Cypriol Oil or Nagarmotha',
        'White Musk, Labdanum, Vanilla and Amber',
        'woody,warm spicy,amber,sweet,musky',
        'AmberiyabyRaydanis a Amber Woody fragrance for women and men.Amberiyawas launched during the 2020''s. Top notes are Immortelle, Honey and Labdanum; middle notes are Cinnamon Leaf, Patchouli, Cedarwood, Geranium and Cypriol Oil or Nagarmotha; base notes are White Musk, Labdanum, Vanilla and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Aram-90909',
        'Aram Raydan',
        'Aram',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit, Bergamot, Orange and Black currant leaf',
        'Pineapple, Jasmine, Violet, Melon and Rose',
        'Patchouli and Cedar',
        'citrus,fruity,woody,fresh spicy,sweet',
        'ArambyRaydanis a Floral Fruity fragrance for women and men.Aramwas launched during the 2020''s. Top notes are Grapefruit, Bergamot, Orange and Black currant leaf; middle notes are Pineapple, Jasmine, Violet, Melon and Rose; base notes are Patchouli and Cedar.',
        NULL,
        NULL,
        NULL
      ),
(
        'Aynaz-90918',
        'Aynaz Raydan',
        'Aynaz',
        'for women and men',
        NULL,
        NULL,
        'Dried Fruits, Plum and Grapes',
        'Geranium and Lime',
        'Cashmere Wood',
        'fruity,sweet,woody,fresh spicy,citrus',
        'AynazbyRaydanis a Citrus Gourmand fragrance for women and men.Aynazwas launched during the 2010''s. Top notes are Dried Fruits, Plum and Grapes; middle notes are Geranium and Lime; base note is Cashmere Wood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Blue-Rose-90706',
        'Blue Rose Raydan',
        'Blue',
        'for women and men',
        NULL,
        NULL,
        'Water Notes and Lemon',
        'Rose and Sugar',
        'White Musk, Sugar, Vanilla and Cedar',
        'aquatic,rose,fresh,citrus,musky',
        'Blue RosebyRaydanis a Floral Aquatic fragrance for women and men.Blue Rosewas launched during the 2020''s. Top notes are Water Notes and Lemon; middle notes are Rose and Sugar; base notes are White Musk, Sugar, Vanilla and Cedar.',
        4,
        1,
        NULL
      ),
(
        'Braisem-90908',
        'Braisem Raydan',
        'Braisem',
        'for women and men',
        NULL,
        NULL,
        'Tangerine and Bergamot',
        'Orange Blossom and Cedarwood',
        'Tuberose, Jasmine and Musk',
        'white floral,citrus,woody,musky,tuberose',
        'BraisembyRaydanis a Floral Woody Musk fragrance for women and men.Braisemwas launched during the 2020''s. Top notes are Tangerine and Bergamot; middle notes are Orange Blossom and Cedarwood; base notes are Tuberose, Jasmine and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Forest-Cardamom-90913',
        'Forest Cardamom Raydan',
        'Forest',
        'for women and men',
        NULL,
        NULL,
        'Thyme and Sage',
        'Lavender and Cardamon',
        'Vanilla, Violet and Cedar',
        'aromatic,herbal,powdery,woody,lavender',
        'Forest CardamombyRaydanis a Aromatic Fougere fragrance for women and men.Forest Cardamomwas launched during the 2020''s. Top notes are Thyme and Sage; middle notes are Lavender and Cardamon; base notes are Vanilla, Violet and Cedar.',
        2,
        1,
        NULL
      ),
(
        'Lamar-90917',
        'Lamar Raydan',
        'Lamar',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Ylang-Ylang, Grapefruit and Clove',
        'Black Cherry, Cinnamon, Rose and Labdanum',
        'Tonka Bean, Vanilla, Amber and Musk',
        'amber,citrus,warm spicy,vanilla,sweet',
        'LamarbyRaydanis a Amber Spicy fragrance for women and men.Lamarwas launched during the 2010''s. Top notes are Mandarin Orange, Ylang-Ylang, Grapefruit and Clove; middle notes are Black Cherry, Cinnamon, Rose and Labdanum; base notes are Tonka Bean, Vanilla, Amber and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Lima-90705',
        'Lima Raydan',
        'Lima',
        'for women and men',
        NULL,
        NULL,
        'Frankincense, Pink Pepper and Myrrh',
        'Patchouli, Jasmine and Rose',
        'Amber, Moss, Musk and Earthy Notes',
        'amber,warm spicy,earthy,woody,mossy',
        'LimabyRaydanis a Amber Floral fragrance for women and men.Limawas launched during the 2010''s. Top notes are Frankincense, Pink Pepper and Myrrh; middle notes are Patchouli, Jasmine and Rose; base notes are Amber, Moss, Musk and Earthy Notes.',
        4.5,
        2,
        NULL
      ),
(
        'Maraya-90905',
        'Maraya Raydan',
        'Maraya',
        'for women and men',
        NULL,
        NULL,
        'Geranium, Bay Leaf, Neroli and Citruses',
        'Orange Blossom, Jasmine, Coconut, Peach, Lily, Iris and Heliotrope',
        'Vanilla, Cedar and Amber',
        'white floral,fresh spicy,powdery,citrus,vanilla',
        'MarayabyRaydanis a Amber Floral fragrance for women and men.Marayawas launched during the 2020''s. Top notes are Geranium, Bay Leaf, Neroli and Citruses; middle notes are Orange Blossom, Jasmine, Coconut, Peach, Lily, Iris and Heliotrope; base notes are Vanilla, Cedar and Amber.',
        5,
        1,
        NULL
      ),
(
        'Mouj-90914',
        'Mouj Raydan',
        'Mouj',
        'for women and men',
        NULL,
        NULL,
        'Jasmine, Cypress and Almond',
        'Tonka Bean, Amberwood and Cardamom',
        'Guaiac Wood, White Musk and Vanilla',
        'woody,vanilla,amber,warm spicy,aromatic',
        'MoujbyRaydanis a Woody Aromatic fragrance for women and men.Moujwas launched during the 2020''s. Top notes are Jasmine, Cypress and Almond; middle notes are Tonka Bean, Amberwood and Cardamom; base notes are Guaiac Wood, White Musk and Vanilla.',
        4.5,
        2,
        NULL
      ),
(
        'Mukha-90916',
        'Mukha Raydan',
        'Mukha',
        'for women and men',
        NULL,
        NULL,
        'Saffron and Tobacco',
        'Peru Balsam, Tolu Balsam and Labdanum',
        'Castoreum, Vanilla, Musk, Cypriol Oil or Nagarmotha and Patchouli',
        'amber,woody,balsamic,warm spicy,musky',
        'MukhabyRaydanis a Amber Spicy fragrance for women and men.Mukhawas launched during the 2010''s. Top notes are Saffron and Tobacco; middle notes are Peru Balsam, Tolu Balsam and Labdanum; base notes are Castoreum, Vanilla, Musk, Cypriol Oil or Nagarmotha and Patchouli.',
        5,
        1,
        NULL
      ),
(
        'Osara-90707',
        'Osara Raydan',
        'Osara',
        'for women and men',
        NULL,
        NULL,
        'Transparent Flowers, Blonde Woods and Geranium',
        'Amberwood, Saffron and Cypriol Oil or Nagarmotha',
        'Vanilla, Leather and Musk',
        'warm spicy,amber,vanilla,metallic,woody',
        'OsarabyRaydanis a Amber Woody fragrance for women and men.Osarawas launched during the 2010''s. Top notes are Transparent Flowers, Blonde Woods and Geranium; middle notes are Amberwood, Saffron and Cypriol Oil or Nagarmotha; base notes are Vanilla, Leather and Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Oud-Taifi-90708',
        'Oud Taifi Raydan',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Woody Notes, Cypriol Oil or Nagarmotha and Gurjan balsam',
        'Rose, Oud and Sandalwood',
        'Animal notes, Patchouli, Ambergris and Musk',
        'woody,rose,animalic,musky,oud',
        'Oud TaifibyRaydanis a Amber Woody fragrance for women and men.Oud Taifiwas launched during the 2010''s. Top notes are Woody Notes, Cypriol Oil or Nagarmotha and Gurjan balsam; middle notes are Rose, Oud and Sandalwood; base notes are Animal notes, Patchouli, Ambergris and Musk.',
        3,
        1,
        NULL
      ),
(
        'Queen-Rose-90911',
        'Queen Rose Raydan',
        'Queen',
        'for women and men',
        NULL,
        NULL,
        'Grapefruit and Tangerine',
        'Osmanthus, Peony and Rose',
        'White Musk and Patchouli',
        'floral,citrus,rose,fruity,patchouli',
        'Queen RosebyRaydanis a Floral fragrance for women and men.Queen Rosewas launched during the 2010''s. Top notes are Grapefruit and Tangerine; middle notes are Osmanthus, Peony and Rose; base notes are White Musk and Patchouli.',
        NULL,
        NULL,
        NULL
      ),
(
        'Renaissance-90704',
        'Renaissance Raydan',
        'Renaissance',
        'for women and men',
        NULL,
        NULL,
        'Heliotrope, Orange Blossom, Tuberose, Geranium, Cardamon, Basil and Citruses',
        'Orris, Cinnamon and Coconut',
        'Ambergris, Patchouli, Vanilla, Frankincense, Tonka Bean and Musk',
        'powdery,vanilla,white floral,animalic,almond',
        'RenaissancebyRaydanis a Floral Woody Musk fragrance for women and men.Renaissancewas launched during the 2020''s. Top notes are Heliotrope, Orange Blossom, Tuberose, Geranium, Cardamon, Basil and Citruses; middle notes are Orris, Cinnamon and Coconut; base notes are Ambergris, Patchouli, Vanilla, Frankincense, Tonka Bean and Musk.',
        5,
        1,
        NULL
      ),
(
        'Royal-Opera-90701',
        'Royal Opera Raydan',
        'Royal',
        'for women and men',
        NULL,
        NULL,
        'Oud',
        'Patchouli and Saffron',
        'Amber, Frankincense and Musk',
        'warm spicy,amber,oud,patchouli,woody',
        'Royal OperabyRaydanis a Amber Woody fragrance for women and men.Royal Operawas launched during the 2010''s. Top note is Oud; middle notes are Patchouli and Saffron; base notes are Amber, Frankincense and Musk.',
        4.8,
        5,
        NULL
      ),
(
        'Syagrus-90910',
        'Syagrus Raydan',
        'Syagrus',
        'for women and men',
        NULL,
        NULL,
        'Cinnamon, Clove and Orange Blossom',
        'Heliotrope, Patchouli and Incense',
        'Tolu Balsam, White Musk, Vanilla and Amber',
        'warm spicy,amber,powdery,vanilla,balsamic',
        'SyagrusbyRaydanis a Amber Spicy fragrance for women and men.Syagruswas launched during the 2020''s. Top notes are Cinnamon, Clove and Orange Blossom; middle notes are Heliotrope, Patchouli and Incense; base notes are Tolu Balsam, White Musk, Vanilla and Amber.',
        NULL,
        NULL,
        NULL
      ),
(
        'Symphony-XXIII-90703',
        'Symphony XXIII Raydan',
        'Symphony',
        'for women and men',
        NULL,
        NULL,
        'Oud',
        'Saffron and Jasmine',
        'Saffron and Jasmine',
        'oud,white floral,warm spicy,metallic,leather',
        'Symphony XXIIIbyRaydanis a Amber Woody fragrance for women and men.Symphony XXIIIwas launched during the 2010''s. Top note is Oud; middle notes are Saffron and Jasmine; base notes are Saffron and Jasmine.',
        3,
        1,
        NULL
      ),
(
        'Tyrus-90907',
        'Tyrus Raydan',
        'Tyrus',
        'for women and men',
        NULL,
        NULL,
        'Raspberry, Saffron and Thyme',
        'Frankincense and Jasmine',
        'Leather, Amber, Suede and Woody Notes',
        'leather,amber,woody,aromatic,warm spicy',
        'TyrusbyRaydanis a Amber Woody fragrance for women and men.Tyruswas launched during the 2020''s. Top notes are Raspberry, Saffron and Thyme; middle notes are Frankincense and Jasmine; base notes are Leather, Amber, Suede and Woody Notes.',
        NULL,
        NULL,
        NULL
      ),
(
        'Zabad-90915',
        'Zabad Raydan',
        'Zabad',
        'for women and men',
        NULL,
        NULL,
        'Geranium, Saffron, Orange, Civet and Rose',
        'Immortelle, Raspberry, Orange, Jasmine and Orange Cassia Tree',
        'Patchouli, Dry Wood, Cedar, Musk, Cypriol Oil or Nagarmotha and Sandalwood',
        'woody,warm spicy,musky,sweet,rose',
        'ZabadbyRaydanis a Floral Woody Musk fragrance for women and men.Zabadwas launched during the 2010''s. Top notes are Geranium, Saffron, Orange, Civet and Rose; middle notes are Immortelle, Raspberry, Orange, Jasmine and Orange Cassia Tree; base notes are Patchouli, Dry Wood, Cedar, Musk, Cypriol Oil or Nagarmotha and Sandalwood.',
        NULL,
        NULL,
        NULL
      ),
(
        'Zenah-90709',
        'Zenah Raydan',
        'Zenah',
        'for women and men',
        NULL,
        NULL,
        'Water Notes, Bergamot and Grass',
        'Orange Blossom, Tuberose and Jasmine',
        'Vetiver and Patchouli',
        'white floral,woody,citrus,green,fresh',
        'ZenahbyRaydanis a Woody Floral Musk fragrance for women and men.Zenahwas launched during the 2010''s. Top notes are Water Notes, Bergamot and Grass; middle notes are Orange Blossom, Tuberose and Jasmine; base notes are Vetiver and Patchouli.',
        NULL,
        NULL,
        NULL
      ),
(
        'Zuhoor-Al-Luban-90710',
        'Zuhoor Al Luban Raydan',
        'Zuhoor',
        'for women and men',
        NULL,
        NULL,
        'Green Leaves, Ylang Ylang and Magnolia',
        'Patchouli, Cedarwood, Tuberose and Jasmine',
        'Frankincense, Raspberry, Peach, Musk and Plum',
        'fruity,woody,sweet,white floral,floral',
        'Zuhoor Al LubanbyRaydanis a Floral Fruity fragrance for women and men.Zuhoor Al Lubanwas launched during the 2020''s. Top notes are Green Leaves, Ylang Ylang and Magnolia; middle notes are Patchouli, Cedarwood, Tuberose and Jasmine; base notes are Frankincense, Raspberry, Peach, Musk and Plum.',
        NULL,
        NULL,
        NULL
      ),
(
        'Birch-Bark-73805',
        'Birch Bark Ranger Station',
        'Birch',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Pine needles, Iris, Water Notes and Salt',
        'Sandalwood, Oak and Pine',
        'Cedar, Birch Tar and Smoke',
        'woody,smoky,leather,powdery,aromatic',
        'Birch BarkbyRanger Stationis a Woody Aromatic fragrance for women and men.Birch Barkwas launched in 2018. The nose behind this fragrance is Steve Soderholm. Top notes are Pine needles, Iris, Water Notes and Salt; middle notes are Sandalwood, Oak and Pine; base notes are Cedar, Birch Tar and Smoke.',
        4.33,
        6,
        NULL
      ),
(
        'Leather-Pine-73802',
        'Leather + Pine Ranger Station',
        'Leather',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Fresh Evergreen, Moss and Sea Notes',
        'Pine, Earthy Notes and Clove',
        'Leather, Ambroxan and Musk',
        'earthy,woody,aromatic,mossy,conifer',
        'Leather + PinebyRanger Stationis a Leather fragrance for women and men.Leather + Pinewas launched in 2018. The nose behind this fragrance is Steve Soderholm. Top notes are Fresh Evergreen, Moss and Sea Notes; middle notes are Pine, Earthy Notes and Clove; base notes are Leather, Ambroxan and Musk.',
        3.64,
        11,
        NULL
      ),
(
        'Oakmoss-73803',
        'Oakmoss Ranger Station',
        'Oakmoss',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Bergamot, Sage and Pine',
        'Violet, Earthy Notes and Cedar',
        'Moss, Red Amber and Tonka Bean',
        'woody,aromatic,earthy,citrus,mossy',
        'OakmossbyRanger Stationis a Aromatic Fougere fragrance for women and men.Oakmosswas launched in 2018. The nose behind this fragrance is Steve Soderholm. Top notes are Bergamot, Sage and Pine; middle notes are Violet, Earthy Notes and Cedar; base notes are Moss, Red Amber and Tonka Bean.',
        3.75,
        12,
        NULL
      ),
(
        'Oud-Wood-73801',
        'Oud Wood Ranger Station',
        'Oud',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Moss, Bergamot and Juniper',
        'Clove, Pepper and Iris',
        'Agarwood (Oud), Cedar and Palo Santo',
        'woody,fresh spicy,aromatic,citrus,warm spicy',
        'Oud WoodbyRanger Stationis a Woody Aromatic fragrance for women and men.Oud Woodwas launched in 2018. The nose behind this fragrance is Steve Soderholm. Top notes are Moss, Bergamot and Juniper; middle notes are Clove, Pepper and Iris; base notes are Agarwood (Oud), Cedar and Palo Santo.',
        3.5,
        8,
        NULL
      ),
(
        'Sandalwood-Bergamot-73800',
        'Sandalwood + Bergamot Ranger Station',
        'Sandalwood',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Citruses, Vetiver and White Musk',
        'Redwood, Cedar and Sandalwood',
        'Incense and Smoke',
        'woody,citrus,aromatic,smoky,powdery',
        'Sandalwood + BergamotbyRanger Stationis a Woody Aromatic fragrance for women and men.Sandalwood + Bergamotwas launched in 2020. The nose behind this fragrance is Steve Soderholm. Top notes are Citruses, Vetiver and White Musk; middle notes are Redwood, Cedar and Sandalwood; base notes are Incense and Smoke.',
        3.89,
        9,
        NULL
      ),
(
        'Santalum-73799',
        'Santalum Ranger Station',
        'Santalum',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Papyrus, Ambergris and Cedar',
        'Amyris, Clove and Cardamom',
        'Sandalwood, Amber and Musk',
        'woody,warm spicy,amber,powdery,aromatic',
        'SantalumbyRanger Stationis a Woody fragrance for women and men.Santalumwas launched in 2018. The nose behind this fragrance is Steve Soderholm. Top notes are Papyrus, Ambergris and Cedar; middle notes are Amyris, Clove and Cardamom; base notes are Sandalwood, Amber and Musk.',
        4.35,
        17,
        NULL
      ),
(
        'Tobacco-Musk-73804',
        'Tobacco + Musk Ranger Station',
        'Tobacco',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Cardamom, Star Anise and White Pepper',
        'Sandalwood, Teak Wood and Musk',
        'Tobacco, Clove and Amber',
        'warm spicy,soft spicy,amber,anis,tobacco',
        'Tobacco + MuskbyRanger Stationis a Aromatic fragrance for women and men.Tobacco + Muskwas launched in 2018. The nose behind this fragrance is Steve Soderholm. Top notes are Cardamom, Star Anise and White Pepper; middle notes are Sandalwood, Teak Wood and Musk; base notes are Tobacco, Clove and Amber.',
        4.5,
        18,
        NULL
      ),
(
        'Untitled-73811',
        'Untitled Ranger Station',
        'Untitled',
        'for women and men',
        NULL,
        'Steve Soderholm',
        NULL,
        NULL,
        NULL,
        'woody,smoky,powdery,citrus,musky',
        'UntitledbyRanger Stationis a Citrus Aromatic fragrance for women and men.Untitledwas launched in 2020. The nose behind this fragrance is Steve Soderholm.',
        4,
        1,
        NULL
      ),
(
        'Woodland-Rose-73807',
        'Woodland Rose Ranger Station',
        'Woodland',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Rose, Juniper and Raspberry',
        'Coumarin, Woodsy Notes, Lavender, Labdanum and Cedar',
        'Ambroxan, Amber and Palo Santo',
        'woody,amber,aromatic,sweet,rose',
        'Woodland RosebyRanger Stationis a Floral fragrance for women and men.Woodland Rosewas launched in 2020. The nose behind this fragrance is Steve Soderholm. Top notes are Rose, Juniper and Raspberry; middle notes are Coumarin, Woodsy Notes, Lavender, Labdanum and Cedar; base notes are Ambroxan, Amber and Palo Santo.',
        4,
        5,
        NULL
      ),
(
        'Yippee-Ki-Yay-73806',
        'Yippee Ki-Yay Ranger Station',
        'Yippee',
        'for women and men',
        NULL,
        'Steve Soderholm',
        'Iris and Rose',
        'Whiskey, Sandalwood and Amber',
        'Leather, Tobacco and Labdanum',
        'leather,woody,whiskey,tobacco,amber',
        'Yippee Ki-YaybyRanger Stationis a Amber Floral fragrance for women and men.Yippee Ki-Yaywas launched in 2020. The nose behind this fragrance is Steve Soderholm. Top notes are Iris and Rose; middle notes are Whiskey, Sandalwood and Amber; base notes are Leather, Tobacco and Labdanum.',
        3.78,
        9,
        NULL
      ),
(
        '2-Rance-11924',
        '2 Rance Rance 1795',
        '2',
        'for women and men',
        NULL,
        'Jeanne Sandra Rance',
        'Grapefruit, Pomelo, Caraway, Honeysuckle and Plum',
        'Geranium, Violet Leaf, Tea, Galbanum and Magnolia',
        'oak moss, Opoponax, Virginia Cedar and Nutmeg',
        'citrus,fresh spicy,aromatic,woody,white floral',
        '2 RancebyRance 1795is a Citrus Aromatic fragrance for women and men. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Grapefruit, Pomelo, Caraway, Honeysuckle and Plum; middle notes are Geranium, Violet Leaf, Tea, Galbanum and Magnolia; base notes are oak moss, Opoponax, Virginia Cedar and Nutmeg.',
        3.76,
        46,
        NULL
      ),
(
        'D-Erje-1930',
        'D''Erje Rance 1795',
        'D''Erje',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Ylang-Ylang, Lily-of-the-Valley, Violet Leaf, Neroli and Narcissus',
        'Jasmine, Passionfruit, Papaya, Tangerine, Rose and Angelica',
        'Iris, Musk, Palisander Rosewood, Bourbon Vanilla and Sandalwood',
        'white floral,sweet,tropical,yellow floral,fresh',
        'D''ErjebyRance 1795is a Floral Woody Musk fragrance for women. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Ylang-Ylang, Lily-of-the-Valley, Violet Leaf, Neroli and Narcissus; middle notes are Jasmine, Passionfruit, Papaya, Tangerine, Rose and Angelica; base notes are Iris, Musk, Palisander Rosewood, Bourbon Vanilla and Sandalwood.',
        3.91,
        151,
        NULL
      ),
(
        'Desiree-54976',
        'Desiree Rance 1795',
        'Desiree',
        'for women',
        NULL,
        NULL,
        'Rose de Mai, Grapefruit, Bergamot, Ginger, Mint, Juniper Berries and Lemon Zest',
        'Rose, Gardenia, Jasmine, Red Thyme, Myrtle and Angelica',
        'White Musk, Citrus Blossom, Cedar and Amber',
        'citrus,rose,aromatic,fresh spicy,white floral',
        'DesireebyRance 1795is a Citrus Aromatic fragrance for women.Desireewas launched in 2019. Top notes are Rose de Mai, Grapefruit, Bergamot, Ginger, Mint, Juniper Berries and Lemon Zest; middle notes are Rose, Gardenia, Jasmine, Red Thyme, Myrtle and Angelica; base notes are White Musk, Citrus Blossom, Cedar and Amber.',
        3.92,
        49,
        NULL
      ),
(
        'Eleonore-36889',
        'Eleonore Rance 1795',
        'Eleonore',
        'for women',
        NULL,
        'Maurizio Cerizza',
        'Myrhh, Peach, Hedione and Sicilian Lemon',
        'Tahitian Vanilla and Saffron',
        'Patchouli, Amber, Sandalwood, Incense, Tonka Bean and Musk',
        'amber,warm spicy,woody,balsamic,powdery',
        'EleonorebyRance 1795is a Amber Vanilla fragrance for women.Eleonorewas launched in 2016. The nose behind this fragrance is Maurizio Cerizza. Top notes are Myrhh, Peach, Hedione and Sicilian Lemon; middle notes are Tahitian Vanilla and Saffron; base notes are Patchouli, Amber, Sandalwood, Incense, Tonka Bean and Musk.',
        3.78,
        88,
        NULL
      ),
(
        'Elise-16886',
        'Elise Rance 1795',
        'Elise',
        'for women',
        NULL,
        'Christian Carbonnel',
        'Neroli, Mandarin Orange and Sea Notes',
        'Eucalyptus and White Rose',
        'Musk, Patchouli, Amber and Vanila',
        'citrus,woody,aromatic,musky,patchouli',
        'ElisebyRance 1795is a Chypre Floral fragrance for women.Elisewas launched in 2012. The nose behind this fragrance is Christian Carbonnel. Top notes are Neroli, Mandarin Orange and Sea Notes; middle notes are Eucalyptus and White Rose; base notes are Musk, Patchouli, Amber and Vanila.',
        3.77,
        260,
        NULL
      ),
(
        'Eugenie-1924',
        'Eugenie Rance 1795',
        'Eugenie',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'White Flowers, Melon, Lily-of-the-Valley, Mandarin Orange, Bergamot, Passionfruit, Black Currant and Ylang-Ylang',
        'Peach, Jasmine, Violet Leaf, Magnolia, Rose and Neroli',
        'Iris, Sandalwood, Vanille, oak moss, Amber and Vetiver',
        'white floral,fruity,citrus,floral,ozonic',
        'EugeniebyRance 1795is a Floral Fruity fragrance for women.Eugeniewas launched in 2006. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are White Flowers, Melon, Lily-of-the-Valley, Mandarin Orange, Bergamot, Passionfruit, Black Currant and Ylang-Ylang; middle notes are Peach, Jasmine, Violet Leaf, Magnolia, Rose and Neroli; base notes are Iris, Sandalwood, Vanille, oak moss, Amber and Vetiver.',
        3.77,
        426,
        NULL
      ),
(
        'Helene-10728',
        'Helene Rance 1795',
        'Helene',
        'for women',
        NULL,
        'Giovanni Rancé',
        'Neroli, Ylang-Ylang, Cardamom and Cinnamon',
        'Orange Blossom, Tonka Bean, Jasmine Sambac and Rose',
        'Heliotrope, Sandalwood, Musk, Iris and Benzoin',
        'powdery,white floral,warm spicy,vanilla,woody',
        'HelenebyRance 1795is a Floral Fruity fragrance for women.Helenewas launched in 2010. The nose behind this fragrance is Giovanni Rancé. Top notes are Neroli, Ylang-Ylang, Cardamom and Cinnamon; middle notes are Orange Blossom, Tonka Bean, Jasmine Sambac and Rose; base notes are Heliotrope, Sandalwood, Musk, Iris and Benzoin.',
        4,
        324,
        NULL
      ),
(
        'Hortense-29111',
        'Hortense Rance 1795',
        'Hortense',
        'for women',
        NULL,
        NULL,
        'Cardamom, Bergamot and Black Pepper',
        'Cinnamon, Rose and Incense',
        'Vanilla, Mahogany and Cedar',
        'warm spicy,woody,aromatic,fresh spicy,citrus',
        'HortensebyRance 1795is a Amber Floral fragrance for women.Hortensewas launched in 2015. Top notes are Cardamom, Bergamot and Black Pepper; middle notes are Cinnamon, Rose and Incense; base notes are Vanilla, Mahogany and Cedar.',
        4.1,
        199,
        NULL
      ),
(
        'Josephine-1929',
        'Josephine Rance 1795',
        'Josephine',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Hyacinth, Rose, Peony, Lilac, Hawthorn, Jasmine, Ylang-Ylang and Bergamot',
        'Iris, Geranium, Black Currant, Galbanum, Peach, Violet Leaf and Clove',
        'Vanille, Sandalwood, Musk, Ebony Wood and Amber',
        'floral,rose,fresh spicy,woody,green',
        'JosephinebyRance 1795is a Amber Floral fragrance for women.Josephinewas launched in 2005. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Hyacinth, Rose, Peony, Lilac, Hawthorn, Jasmine, Ylang-Ylang and Bergamot; middle notes are Iris, Geranium, Black Currant, Galbanum, Peach, Violet Leaf and Clove; base notes are Vanille, Sandalwood, Musk, Ebony Wood and Amber.',
        3.88,
        626,
        NULL
      ),
(
        'Laetitia-Millesime-5208',
        'Laetitia Millesime Rance 1795',
        'Laetitia',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Mandarin Orange, Orange Blossom and Bergamot',
        'Nutmeg, Rose, Magnolia and Wisteria',
        'Patchouli, Tolu Balsam, Vanilla and French labdanum',
        'amber,patchouli,warm spicy,powdery,balsamic',
        'Laetitia MillesimebyRance 1795is a fragrance for women.Laetitia Millesimewas launched in 2008. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Mandarin Orange, Orange Blossom and Bergamot; middle notes are Nutmeg, Rose, Magnolia and Wisteria; base notes are Patchouli, Tolu Balsam, Vanilla and French labdanum.',
        4.16,
        465,
        NULL
      ),
(
        'Mathilde-87956',
        'Mathilde Rance 1795',
        'Mathilde',
        'for women',
        NULL,
        NULL,
        'Lily of the Valley, Ylang-Ylang, Narcissus, Neroli and Violet Leaf',
        'Tangerine, Jasmine, Rose, Papaya, Passionfruit and Angelica Root',
        'Musk, Bourbon Vanilla, Sandalwood, Iris and Palisander Rosewood',
        'white floral,citrus,fresh,green,yellow floral',
        'MathildebyRance 1795is a Floral Fruity fragrance for women. This is a new fragrance.Mathildewas launched in 2023. Top notes are Lily of the Valley, Ylang-Ylang, Narcissus, Neroli and Violet Leaf; middle notes are Tangerine, Jasmine, Rose, Papaya, Passionfruit and Angelica Root; base notes are Musk, Bourbon Vanilla, Sandalwood, Iris and Palisander Rosewood.',
        3.9,
        10,
        NULL
      ),
(
        'Pauline-13451',
        'Pauline Rance 1795',
        'Pauline',
        'for women',
        NULL,
        NULL,
        'Cotton Flower, Orange and Ylang-Ylang',
        'Violet, Rose and Patchouli',
        'Tonka Bean, Benzoin and Virginia Cedar',
        'powdery,violet,floral,woody,rose',
        'PaulinebyRance 1795is a Floral fragrance for women.Paulinewas launched in 2011. Top notes are Cotton Flower, Orange and Ylang-Ylang; middle notes are Violet, Rose and Patchouli; base notes are Tonka Bean, Benzoin and Virginia Cedar.',
        4,
        232,
        NULL
      ),
(
        'Rance-Donna-11925',
        'Rance Donna Rance 1795',
        'Rance',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Violet, Tangerine, Peach and Bergamot',
        'African Orange Flower, Lily-of-the-Valley, Rose and Jasmine',
        'Iris, Geranium, Vanille and Sandalwood',
        'powdery,violet,white floral,citrus,fresh spicy',
        'Rance DonnabyRance 1795is a Floral fragrance for women. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Violet, Tangerine, Peach and Bergamot; middle notes are African Orange Flower, Lily-of-the-Valley, Rose and Jasmine; base notes are Iris, Geranium, Vanille and Sandalwood.',
        4.03,
        89,
        NULL
      ),
(
        'Rouge-1931',
        'Rouge Rance 1795',
        'Rouge',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Narcissus, Mandarin Orange and Lily-of-the-Valley',
        'Orchid, Jasmine, Rose and Freesia',
        'Patchouli, Bourbon Vanilla, Amber and Iris',
        'floral,patchouli,white floral,woody,powdery',
        'RougebyRance 1795is a Amber Floral fragrance for women. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Narcissus, Mandarin Orange and Lily-of-the-Valley; middle notes are Orchid, Jasmine, Rose and Freesia; base notes are Patchouli, Bourbon Vanilla, Amber and Iris.',
        3.86,
        58,
        NULL
      ),
(
        'Francois-Charles-3172',
        'Francois Charles Rance 1795',
        'Francois',
        'for men',
        NULL,
        'Giovanni Rancé',
        'Ginger, Cardamom, Bergamot, Bitter Orange, Lemon, Pineapple, Melon, Grapefruit, Tangerine, Cinnamon, Pink Pepper and Anise',
        'Lavender, Jasmine, Orange Blossom, Rose and Clary Sage',
        'Cedar, Iris, Musk, Amber, ebony tree, Vanilla, Caramel, Sandalwood, Vetiver, Labdanum and Patchouli',
        'woody,warm spicy,aromatic,citrus,powdery',
        'Francois CharlesbyRance 1795is a Leather fragrance for men.Francois Charleswas launched in 2007. The nose behind this fragrance is Giovanni Rancé. Top notes are Ginger, Cardamom, Bergamot, Bitter Orange, Lemon, Pineapple, Melon, Grapefruit, Tangerine, Cinnamon, Pink Pepper and Anise; middle notes are Lavender, Jasmine, Orange Blossom, Rose and Clary Sage; base notes are Cedar, Iris, Musk, Amber, ebony tree, Vanilla, Caramel, Sandalwood, Vetiver, Labdanum and Patchouli.',
        3.98,
        167,
        NULL
      ),
(
        'Heroique-29110',
        'Heroique Rance 1795',
        'Heroique',
        'for men',
        NULL,
        NULL,
        'Black Currant, Pineapple, Bergamot and Apple',
        'Birch, Patchouli, Jasmine and Rose',
        'Oakmoss, Teak Wood, Amber, White Musk and Vanilla',
        'fruity,woody,mossy,earthy,leather',
        'HeroiquebyRance 1795is a Woody Aromatic fragrance for men.Heroiquewas launched in 2015. Top notes are Black Currant, Pineapple, Bergamot and Apple; middle notes are Birch, Patchouli, Jasmine and Rose; base notes are Oakmoss, Teak Wood, Amber, White Musk and Vanilla.',
        4.08,
        111,
        NULL
      ),
(
        'L-Aigle-de-la-Victoire-18018',
        'L''Aigle de la Victoire Rance 1795',
        'L''Aigle',
        'for men',
        NULL,
        'Giovanni Rancé',
        'Calabrian bergamot and Grapefruit',
        'Birch Leaf and Raspberry',
        'Leather, Agarwood (Oud), Vetiver, Patchouli, Cedar, Sandalwood and Vanilla',
        'leather,woody,smoky,oud,aromatic',
        'L''Aigle de la VictoirebyRance 1795is a Leather fragrance for men.L''Aigle de la Victoirewas launched in 2013. The nose behind this fragrance is Giovanni Rancé. Top notes are Calabrian bergamot and Grapefruit; middle notes are Birch Leaf and Raspberry; base notes are Leather, Agarwood (Oud), Vetiver, Patchouli, Cedar, Sandalwood and Vanilla.',
        4.01,
        132,
        NULL
      ),
(
        'Le-Roi-Empereur-11896',
        'Le Roi Empereur Rance 1795',
        'Le',
        'for men',
        NULL,
        NULL,
        'African Orange Flower, Lavender and Anise',
        'Cardamom, Iris, Violet and Rose',
        'Cinnamon, Amber, Leather, Musk and Virginia Cedar',
        'warm spicy,powdery,white floral,cinnamon,lavender',
        'Le Roi EmpereurbyRance 1795is a Amber Spicy fragrance for men.Le Roi Empereurwas launched in 2011. Top notes are African Orange Flower, Lavender and Anise; middle notes are Cardamom, Iris, Violet and Rose; base notes are Cinnamon, Amber, Leather, Musk and Virginia Cedar.',
        4.02,
        128,
        NULL
      ),
(
        'Le-Vainqueur-1923',
        'Le Vainqueur Rance 1795',
        'Le',
        'for men',
        NULL,
        'Jeanne Sandra Rance',
        'Watermelon, Grapefruit, Ginger, Melon, Bergamot and Mandarin Orange',
        'Lavender, Geranium, Nutmeg, Jasmine and Lily-of-the-Valley',
        'Vetiver, Leather, Iris, Musk, Sandalwood and Amber',
        'citrus,ozonic,aquatic,fresh spicy,aromatic',
        'Le VainqueurbyRance 1795is a Woody Aromatic fragrance for men.Le Vainqueurwas launched in 2005. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Watermelon, Grapefruit, Ginger, Melon, Bergamot and Mandarin Orange; middle notes are Lavender, Geranium, Nutmeg, Jasmine and Lily-of-the-Valley; base notes are Vetiver, Leather, Iris, Musk, Sandalwood and Amber.',
        4.05,
        250,
        NULL
      ),
(
        'Sharisme-Insense-44492',
        'Sharisme Insense Rance 1795',
        'Sharisme',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,warm spicy,smoky,woody,balsamic',
        'Sharisme InsensebyRance 1795is a Woody Spicy fragrance for women and men.Sharisme Insensewas launched in 2017.',
        3.98,
        46,
        NULL
      ),
(
        'Triomphe-Millesime-6421',
        'Triomphe Millesime Rance 1795',
        'Triomphe',
        'for men',
        NULL,
        'Giovanni Rancé',
        'Bergamot, Cardamom, Bitter Orange and Tangerine',
        'Clary Sage, Tarragon and Cinnamon',
        'Patchouli, Benzoin, Incense, Vetiver, Leather, Guaiac Wood, Vanilla and Amber',
        'citrus,aromatic,warm spicy,amber,fresh spicy',
        'Triomphe MillesimebyRance 1795is a Aromatic Fougere fragrance for men.Triomphe Millesimewas launched in 2009. The nose behind this fragrance is Giovanni Rancé. Top notes are Bergamot, Cardamom, Bitter Orange and Tangerine; middle notes are Clary Sage, Tarragon and Cinnamon; base notes are Patchouli, Benzoin, Incense, Vetiver, Leather, Guaiac Wood, Vanilla and Amber.',
        3.98,
        144,
        NULL
      ),
(
        'Avant-le-Jour-16887',
        'Avant le Jour Rance 1795',
        'Avant',
        'for women',
        NULL,
        'Chris Maurice',
        'Violet, Mandarin Orange and Mint',
        'Iris, Guaiac Wood, Jasmine, Pomegranate Seed and Cedar',
        'Bourbon Vanilla, Benzoin, Olibanum and Amber',
        'powdery,amber,violet,woody,vanilla',
        'Avant le JourbyRance 1795is a Amber Floral fragrance for women.Avant le Jourwas launched in 2012. The nose behind this fragrance is Chris Maurice. Top notes are Violet, Mandarin Orange and Mint; middle notes are Iris, Guaiac Wood, Jasmine, Pomegranate Seed and Cedar; base notes are Bourbon Vanilla, Benzoin, Olibanum and Amber.',
        4.04,
        111,
        NULL
      ),
(
        'Jasmin-du-Malabar-13456',
        'Jasmin du Malabar Rance 1795',
        'Jasmin',
        'for women',
        NULL,
        'Christian Carbonnel',
        'Jasmine, Tangerine and Bergamot',
        'African Orange Flower',
        'Mimosa',
        'white floral,citrus,sweet,yellow floral,floral',
        'Jasmin du MalabarbyRance 1795is a Amber Floral fragrance for women.Jasmin du Malabarwas launched in 2011. The nose behind this fragrance is Christian Carbonnel. Top notes are Jasmine, Tangerine and Bergamot; middle note is African Orange Flower; base note is Mimosa.',
        3.96,
        122,
        NULL
      ),
(
        'Pres-de-Toi-13457',
        'Pres de Toi Rance 1795',
        'Pres',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Tangerine, African Orange Flower and Bergamot',
        'Rose, Jasmine and Magnolia',
        'Vanille, Tolu Balsam, Patchouli and Agarwood (Oud)',
        'citrus,white floral,sweet,vanilla,powdery',
        'Pres de ToibyRance 1795is a Amber Floral fragrance for women.Pres de Toiwas launched in 2011. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Tangerine, African Orange Flower and Bergamot; middle notes are Rose, Jasmine and Magnolia; base notes are Vanille, Tolu Balsam, Patchouli and Agarwood (Oud).',
        3.94,
        104,
        NULL
      ),
(
        'Rose-de-Rose-13455',
        'Rose de Rose Rance 1795',
        'Rose',
        'for women',
        NULL,
        'Christian Carbonnel',
        'Rose',
        'Ylang-Ylang, Jasmine and Tuberose',
        'Vanille and Sandalwood',
        'rose,vanilla,woody,white floral,yellow floral',
        'Rose de RosebyRance 1795is a Floral fragrance for women.Rose de Rosewas launched in 2011. The nose behind this fragrance is Christian Carbonnel. Top note is Rose; middle notes are Ylang-Ylang, Jasmine and Tuberose; base notes are Vanille and Sandalwood.',
        4,
        117,
        NULL
      ),
(
        'Sur-Mon-Coeur-16888',
        'Sur Mon Coeur Rance 1795',
        'Sur',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Ylang-Ylang and Grasse Rose',
        'Tuberose, Jasmine Sambac, Rhubarb and Pink Pepper',
        'Bourbon Vanilla, Amber, Benzoin and Tonka Bean',
        'white floral,amber,sweet,vanilla,tuberose',
        'Sur Mon CoeurbyRance 1795is a Amber Floral fragrance for women.Sur Mon Coeurwas launched in 2012. Top notes are Orange Blossom, Ylang-Ylang and Grasse Rose; middle notes are Tuberose, Jasmine Sambac, Rhubarb and Pink Pepper; base notes are Bourbon Vanilla, Amber, Benzoin and Tonka Bean.',
        3.95,
        84,
        NULL
      ),
(
        'Tubereuse-Amour-16889',
        'Tubereuse Amour Rance 1795',
        'Tubereuse',
        'for women',
        NULL,
        'Christian Carbonnel',
        'Bergamot, Violet Leaves, Lily-of-the-Valley and Neroli',
        'Indian Tuberose, Chinese Osmanthus and Turkish Rose',
        'Sandalwood, Iris, Musk and Patchouli',
        'white floral,tuberose,floral,woody,powdery',
        'Tubereuse AmourbyRance 1795is a Amber Floral fragrance for women.Tubereuse Amourwas launched in 2012. The nose behind this fragrance is Christian Carbonnel. Top notes are Bergamot, Violet Leaves, Lily-of-the-Valley and Neroli; middle notes are Indian Tuberose, Chinese Osmanthus and Turkish Rose; base notes are Sandalwood, Iris, Musk and Patchouli.',
        3.77,
        84,
        NULL
      ),
(
        'Rue-de-Soleil-49527',
        'Rue de Soleil Rance 1795',
        'Rue',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Orange, Lemon and Petitgrain Paraguay',
        'Lemon Verbena, Sage, Geranium and Litsea Cubeba',
        'Musk, White Woods and Amber',
        'citrus,aromatic,herbal,fresh spicy,musky',
        'Rue de SoleilbyRance 1795is a Citrus Aromatic fragrance for women and men.Rue de Soleilwas launched in 2018. The nose behind this fragrance is Luca Maffei. Top notes are Orange, Lemon and Petitgrain Paraguay; middle notes are Lemon Verbena, Sage, Geranium and Litsea Cubeba; base notes are Musk, White Woods and Amber.',
        3.88,
        26,
        NULL
      ),
(
        'Rue-Rance-Alchimie-du-Matin-49528',
        'Rue Rance Alchimie du Matin Rance 1795',
        'Rue',
        'for women and men',
        NULL,
        'Luca Maffei',
        NULL,
        NULL,
        NULL,
        'white floral,citrus,woody,lactonic,soft spicy',
        'Rue Rance Alchimie du MatinbyRance 1795is a Aromatic fragrance for women and men.Rue Rance Alchimie du Matinwas launched in 2018. The nose behind this fragrance is Luca Maffei.',
        4.33,
        27,
        NULL
      ),
(
        'Rue-Rance-Eau-de-France-1927',
        'Rue Rance Eau de France Rance 1795',
        'Rue',
        'for women and men',
        NULL,
        'Jeanne Sandra Rance',
        'Neroli, Lavender and Bergamot',
        'Violet Leaf, Gardenia and Ylang-Ylang',
        'Vetiver, Patchouli, Sandalwood and Musk',
        'woody,aromatic,citrus,white floral,earthy',
        'Rue Rance Eau de FrancebyRance 1795is a Woody Floral Musk fragrance for women and men. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Neroli, Lavender and Bergamot; middle notes are Violet Leaf, Gardenia and Ylang-Ylang; base notes are Vetiver, Patchouli, Sandalwood and Musk.',
        4.08,
        186,
        NULL
      ),
(
        'Rue-Rance-Eau-De-La-Couronne-6420',
        'Rue Rance Eau De La Couronne Rance 1795',
        'Rue',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Melon, Black Currant, Violet and Blood Orange',
        'Freesia, Granny Smith apple, Gardenia and Jasmine',
        'Mahogany, Iris, Musk and Amber',
        'fruity,floral,white floral,woody,fresh',
        'Rue Rance Eau De La CouronnebyRance 1795is a Amber Floral fragrance for women.Rue Rance Eau De La Couronnewas launched in 2009. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Melon, Black Currant, Violet and Blood Orange; middle notes are Freesia, Granny Smith apple, Gardenia and Jasmine; base notes are Mahogany, Iris, Musk and Amber.',
        3.86,
        162,
        NULL
      ),
(
        'Rue-Rance-Eau-de-Noblesse-11894',
        'Rue Rance Eau de Noblesse Rance 1795',
        'Rue',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Grapefruit, Bergamot and Rose',
        'Rhuburb, Coriander, Myrtle and Iris',
        'Palisander Rosewood, Musk, Virginia Cedar and Vanille',
        'citrus,aromatic,fresh spicy,woody,green',
        'Rue Rance Eau de NoblessebyRance 1795is a Amber Floral fragrance for women.Rue Rance Eau de Noblessewas launched in 2011. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Grapefruit, Bergamot and Rose; middle notes are Rhuburb, Coriander, Myrtle and Iris; base notes are Palisander Rosewood, Musk, Virginia Cedar and Vanille.',
        3.98,
        132,
        NULL
      ),
(
        'Rue-Rance-Eau-de-Zephyr-92769',
        'Rue Rance Eau de Zéphyr Rance 1795',
        'Rue',
        'for women and men',
        NULL,
        NULL,
        'Pomelo, Plum, Honeysuckle, Grapefruit and Cumin',
        'Violet Leaves, Geranium, Galbanum, Magnolia and Tea',
        'Virginia Cedar, Opoponax, Nutmeg and Oakmoss',
        'citrus,fresh spicy,fruity,green,ozonic',
        'Rue Rance Eau de ZéphyrbyRance 1795is a Citrus Aromatic fragrance for women and men. This is a new fragrance.Rue Rance Eau de Zéphyrwas launched in 2024. Top notes are Pomelo, Plum, Honeysuckle, Grapefruit and Cumin; middle notes are Violet Leaves, Geranium, Galbanum, Magnolia and Tea; base notes are Virginia Cedar, Opoponax, Nutmeg and Oakmoss.',
        5,
        1,
        NULL
      ),
(
        'Rue-Rance-Eau-Duc-De-Berry-6419',
        'Rue Rance Eau Duc De Berry Rance 1795',
        'Rue',
        'for men',
        NULL,
        'Jeanne Sandra Rance',
        'Bitter Orange, Coriander and Mandarin Orange',
        'Cardamom, Violet, Pepper and Rose',
        'Virginia Cedar, Nutmeg, Vetiver and oak moss',
        'citrus,aromatic,fresh spicy,warm spicy,woody',
        'Rue Rance Eau Duc De BerrybyRance 1795is a Woody Aromatic fragrance for men.Rue Rance Eau Duc De Berrywas launched in 2009. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Bitter Orange, Coriander and Mandarin Orange; middle notes are Cardamom, Violet, Pepper and Rose; base notes are Virginia Cedar, Nutmeg, Vetiver and oak moss.',
        4.08,
        60,
        NULL
      ),
(
        'Rue-Rance-Eau-Impire-1926',
        'Rue Rance Eau Impire Rance 1795',
        'Rue',
        'for women and men',
        NULL,
        'Jeanne Sandra Rance',
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,green,aromatic,floral',
        'Rue Rance Eau ImpirebyRance 1795is a Floral Woody Musk fragrance for women and men. The nose behind this fragrance is Jeanne Sandra Rance.',
        3.71,
        45,
        NULL
      ),
(
        'Rue-Rance-Eau-Royale-1928',
        'Rue Rance Eau Royale Rance 1795',
        'Rue',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic,white floral,woody',
        'Rue Rance Eau RoyalebyRance 1795is a Floral Woody Musk fragrance for women. The nose behind this fragrance is Jeanne Sandra Rance.',
        4,
        77,
        NULL
      ),
(
        'Rue-Rance-Eau-Sublime-1925',
        'Rue Rance Eau Sublime Rance 1795',
        'Rue',
        'for women',
        NULL,
        'Jeanne Sandra Rance',
        'Lime, Hyacinth, Mandarin Orange and Neroli',
        'Lilac, Myrtle and Lily-of-the-Valley',
        'Iris, Vanille and Musk',
        'citrus,floral,green,fresh spicy,powdery',
        'Rue Rance Eau SublimebyRance 1795is a Floral Woody Musk fragrance for women. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Lime, Hyacinth, Mandarin Orange and Neroli; middle notes are Lilac, Myrtle and Lily-of-the-Valley; base notes are Iris, Vanille and Musk.',
        3.88,
        195,
        NULL
      ),
(
        'Rue-Rance-Eau-Superbe-11895',
        'Rue Rance Eau Superbe Rance 1795',
        'Rue',
        'for men',
        NULL,
        'Jeanne Sandra Rance',
        'Mint, Mandarin Orange, Grapefruit and Petitgrain',
        'Cinnamon, Rose, Cardamom and Pepper',
        'Leather, Amber, Patchouli and Woodsy Notes',
        'warm spicy,citrus,leather,aromatic,cinnamon',
        'Rue Rance Eau SuperbebyRance 1795is a Woody Aromatic fragrance for men.Rue Rance Eau Superbewas launched in 2011. The nose behind this fragrance is Jeanne Sandra Rance. Top notes are Mint, Mandarin Orange, Grapefruit and Petitgrain; middle notes are Cinnamon, Rose, Cardamom and Pepper; base notes are Leather, Amber, Patchouli and Woodsy Notes.',
        3.91,
        54,
        NULL
      ),
(
        'Rue-Rance-Reve-d-Ete-43972',
        'Rue Rance Rêve d''Été Rance 1795',
        'Rue',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Fig Leaf, Coconut, Black Currant, Sicilian Lemon and Neroli',
        'Fig and Jasmine Sambac',
        'Fig Tree, Sandalwood, Incense, White Musk, Patchouli, Virginia Cedar, Amber and Tonka Bean',
        'woody,fruity,green,sweet,fresh',
        'Rue Rance Rêve d''ÉtébyRance 1795is a Aromatic Fruity fragrance for women and men.Rue Rance Rêve d''Étéwas launched in 2016. The nose behind this fragrance is Maurizio Cerizza. Top notes are Fig Leaf, Coconut, Black Currant, Sicilian Lemon and Neroli; middle notes are Fig and Jasmine Sambac; base notes are Fig Tree, Sandalwood, Incense, White Musk, Patchouli, Virginia Cedar, Amber and Tonka Bean.',
        3.89,
        66,
        NULL
      ),
(
        'Secrete-Euphorie-44320',
        'Secrète Euphorie Rance 1795',
        'Secrète',
        'for women and men',
        NULL,
        'Maurizio Cerizza',
        'Blood Orange, Rum, Artemisia, Pink Grapefruit and Lemon',
        'Osmanthus, Orange Blossom and Damask Rose',
        'Musk, Labdanum, Patchouli, Cashmeran, White Amber and Sandalwood',
        'citrus,woody,amber,musky,floral',
        'Secrète EuphoriebyRance 1795is a Floral Fruity fragrance for women and men.Secrète Euphoriewas launched in 2017. The nose behind this fragrance is Maurizio Cerizza. Top notes are Blood Orange, Rum, Artemisia, Pink Grapefruit and Lemon; middle notes are Osmanthus, Orange Blossom and Damask Rose; base notes are Musk, Labdanum, Patchouli, Cashmeran, White Amber and Sandalwood.',
        4.08,
        49,
        NULL
      ),
(
        'Agar-Musk-15504',
        'Agar Musk Ramon Monegal',
        'Agar',
        'for women and men',
        NULL,
        'Ramon Monegal',
        NULL,
        NULL,
        NULL,
        'oud,fresh spicy,aromatic,woody,musky',
        'Agar MuskbyRamon Monegalis a Amber Woody fragrance for women and men.Agar Muskwas launched in 2009. The nose behind this fragrance is Ramon Monegal.',
        4.07,
        229,
        NULL
      ),
(
        'Ambra-di-Luna-15496',
        'Ambra di Luna Ramon Monegal',
        'Ambra',
        'for women and men',
        NULL,
        'Ramon Monegal',
        NULL,
        NULL,
        NULL,
        'amber,woody,leather,smoky,musky',
        'Ambra di LunabyRamon Monegalis a Amber fragrance for women and men.Ambra di Lunawas launched in 2009. The nose behind this fragrance is Ramon Monegal.',
        4.2,
        158,
        NULL
      );
