
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Latino-Absoluto-39335',
        'Latino Absoluto Parfums Codibel',
        'Latino',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Latino AbsolutobyParfums Codibelis a fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Magic-Black-Man-39336',
        'Magic Black Man Parfums Codibel',
        'Magic',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Magic Black ManbyParfums Codibelis a fragrance for men.',
        5,
        1,
        NULL
      ),
(
        'Magic-Black-Woman-38881',
        'Magic Black Woman Parfums Codibel',
        'Magic',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Magic Black WomanbyParfums Codibelis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Paris-Dakar-Arenas-39320',
        'Paris - Dakar Arenas Parfums Codibel',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar ArenasbyParfums Codibelis a fragrance for men.',
        4.67,
        3,
        NULL
      ),
(
        'Paris-Dakar-Extreme-39323',
        'Paris - Dakar Extreme Parfums Codibel',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar ExtremebyParfums Codibelis a fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Paris-Dakar-Gran-Reserva-39322',
        'Paris - Dakar Gran Reserva Parfums Codibel',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar Gran ReservabyParfums Codibelis a fragrance for men.',
        4,
        1,
        NULL
      ),
(
        'Paris-Dakar-Motors-39325',
        'Paris - Dakar Motors Parfums Codibel',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar MotorsbyParfums Codibelis a fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Paris-Dakar-Pour-Femme-38836',
        'Paris - Dakar Pour Femme Parfums Codibel',
        'Paris',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar Pour FemmebyParfums Codibelis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Paris-Dakar-Pour-Homme-39319',
        'Paris - Dakar Pour Homme Parfums Codibel',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar Pour HommebyParfums Codibelis a fragrance for men.',
        4.5,
        4,
        NULL
      ),
(
        'Paris-Dakar-Rain-39321',
        'Paris - Dakar Rain Parfums Codibel',
        'Paris',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Paris - Dakar RainbyParfums Codibelis a fragrance for men.',
        NULL,
        NULL,
        NULL
      ),
(
        'Polvora-39327',
        'Polvora Parfums Codibel',
        'Polvora',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'PolvorabyParfums Codibelis a fragrance for men.',
        4,
        3,
        NULL
      ),
(
        'Rosas-Frescas-38876',
        'Rosas Frescas Parfums Codibel',
        'Rosas',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,earthy,musky,rose,floral',
        'Rosas FrescasbyParfums Codibelis a Chypre Floral fragrance for women.Rosas Frescaswas launched in 1983.',
        4,
        1,
        NULL
      ),
(
        'Venezia-Di-Codibel-38847',
        'Venezia Di Codibel Parfums Codibel',
        'Venezia',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Venezia Di CodibelbyParfums Codibelis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Venezia-di-Notte-38848',
        'Venezia di Notte Parfums Codibel',
        'Venezia',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Venezia di NottebyParfums Codibelis a fragrance for women.',
        NULL,
        NULL,
        NULL
      ),
(
        'Web-39328',
        'Web Parfums Codibel',
        'Web',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'WebbyParfums Codibelis a fragrance for men.',
        5,
        1,
        NULL
      ),
(
        'Rose-Litchi-87229',
        'Rose & Litchi Parfums Berdoues',
        'Rose',
        'for women',
        NULL,
        NULL,
        'Orange Blossom and Mandarin Orange',
        'Rose, Litchi and Black Currant',
        'Musk, Sandalwood and Cedar',
        'fruity,rose,woody,tropical,citrus',
        'Rose & LitchibyParfums Berdouesis a Floral Fruity fragrance for women. This is a new fragrance.Rose & Litchiwas launched in 2023. Top notes are Orange Blossom and Mandarin Orange; middle notes are Rose, Litchi and Black Currant; base notes are Musk, Sandalwood and Cedar.',
        3.83,
        6,
        NULL
      ),
(
        'Amande-Tonka-47038',
        'Amande & Tonka Parfums Berdoues',
        'Amande',
        'for women and men',
        NULL,
        NULL,
        'Mimosa and Hawthorn',
        'Almond',
        'Musk and Tonka Bean',
        'sweet,almond,floral,powdery,yellow floral',
        'Amande & TonkabyParfums Berdouesis a Floral Woody Musk fragrance for women and men.Amande & Tonkawas launched in 2017. Top notes are Mimosa and Hawthorn; middle note is Almond; base notes are Musk and Tonka Bean.',
        3.91,
        56,
        NULL
      ),
(
        'Avoine-Coquelicot-63321',
        'Avoine & Coquelicot Parfums Berdoues',
        'Avoine',
        'for women and men',
        NULL,
        NULL,
        'Oat',
        'Cardamom, Saffron and Poppy',
        'Musk',
        'warm spicy,musky,aromatic,savory,powdery',
        'Avoine & CoquelicotbyParfums Berdouesis a Floral fragrance for women and men.Avoine & Coquelicotwas launched in 2020. Top note is Oat; middle notes are Cardamom, Saffron and Poppy; base note is Musk.',
        3.95,
        19,
        NULL
      ),
(
        'Lierre-Bois-47040',
        'Lierre & Bois Parfums Berdoues',
        'Lierre',
        'for women and men',
        NULL,
        NULL,
        'Ivy',
        'Pink Pepper and Cardamom',
        'Iris, White Musk and Amber',
        'green,fresh,ozonic,iris,woody',
        'Lierre & BoisbyParfums Berdouesis a Aromatic Green fragrance for women and men.Lierre & Boiswas launched in 2017. Top note is Ivy; middle notes are Pink Pepper and Cardamom; base notes are Iris, White Musk and Amber.',
        4.14,
        35,
        NULL
      ),
(
        'Monoi-Coco-91494',
        'Monoï & Coco Parfums Berdoues',
        'Monoï',
        'for women and men',
        NULL,
        NULL,
        'Coconut, Bergamot and Lemon',
        'Tiare Flower and Frangipani',
        'Sandalwood, Vanilla and Musk',
        'coconut,marine,white floral,aromatic,tropical',
        'Monoï & CocobyParfums Berdouesis a fragrance for women and men. This is a new fragrance.Monoï & Cocowas launched in 2024. Top notes are Coconut, Bergamot and Lemon; middle notes are Tiare Flower and Frangipani; base notes are Sandalwood, Vanilla and Musk.',
        4.33,
        6,
        NULL
      ),
(
        'Monoi-Tiare-82102',
        'Monoï & Tiaré Parfums Berdoues',
        'Monoï',
        'for women and men',
        NULL,
        NULL,
        'Fruity Notes',
        'Frangipani, White Flowers and Coconut Milk',
        'Vanille, Sea Salt and Benzoin',
        'floral,tropical,white floral,vanilla,lactonic',
        'Monoï & TiarébyParfums Berdouesis a fragrance for women and men. This is a new fragrance.Monoï & Tiaréwas launched in 2023. Top note is Fruity Notes; middle notes are Frangipani, White Flowers and Coconut Milk; base notes are Vanille, Sea Salt and Benzoin.',
        4.27,
        15,
        NULL
      ),
(
        'Musc-Neroli-47037',
        'Musc & Neroli Parfums Berdoues',
        'Musc',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange',
        'Orange Blossom',
        'Musk and White Cedar Extract',
        'white floral,citrus,musky,powdery,sweet',
        'Musc & NerolibyParfums Berdouesis a Citrus Aromatic fragrance for women and men.Musc & Neroliwas launched in 2017. Top note is Mandarin Orange; middle note is Orange Blossom; base notes are Musk and White Cedar Extract.',
        3.84,
        50,
        NULL
      ),
(
        'Pivoine-Rhubarbe-47036',
        'Pivoine & Rhubarbe Parfums Berdoues',
        'Pivoine',
        'for women and men',
        NULL,
        NULL,
        'Rhubarb and Grapefruit',
        'Peony and Magnolia',
        'Amber',
        'floral,fresh,green,citrus,fruity',
        'Pivoine & RhubarbebyParfums Berdouesis a Floral Fruity fragrance for women and men.Pivoine & Rhubarbewas launched in 2017. Top notes are Rhubarb and Grapefruit; middle notes are Peony and Magnolia; base note is Amber.',
        3.71,
        63,
        NULL
      ),
(
        'Trefle-Vetiver-47039',
        'Trefle & Vetiver Parfums Berdoues',
        'Trefle',
        'for women and men',
        NULL,
        NULL,
        'Apple and Jasmine',
        'Clover',
        'Vetiver',
        'green,floral,aromatic,woody,earthy',
        'Trefle & VetiverbyParfums Berdouesis a Woody Aromatic fragrance for women and men.Trefle & Vetiverwas launched in 2017. Top notes are Apple and Jasmine; middle note is Clover; base note is Vetiver.',
        3.96,
        28,
        NULL
      ),
(
        'Ylang-Fleur-de-Sel-56275',
        'Ylang & Fleur de Sel Parfums Berdoues',
        'Ylang',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'marine,salty,yellow floral,aromatic,sweet',
        'Ylang & Fleur de SelbyParfums Berdouesis a Floral fragrance for women and men.Ylang & Fleur de Selwas launched in 2019.',
        4.21,
        24,
        NULL
      ),
(
        'L-Eau-54399',
        'L''Eau Parfums Berdoues',
        'L''Eau',
        'for women',
        NULL,
        NULL,
        'Pear and Black Currant',
        'Peony, Orange Blossom and Ylang-Ylang',
        'White Musk, Cedar and Tonka Bean',
        'fruity,floral,fresh,sweet,woody',
        'L''EaubyParfums Berdouesis a Floral Woody Musk fragrance for women.L''Eauwas launched in 2019. Top notes are Pear and Black Currant; middle notes are Peony, Orange Blossom and Ylang-Ylang; base notes are White Musk, Cedar and Tonka Bean.',
        4.31,
        13,
        NULL
      ),
(
        'Cardamomum-Vegetalis-8152',
        'Cardamomum Vegetalis Parfums Berdoues',
        'Cardamomum',
        'for women and men',
        NULL,
        NULL,
        'Cardamom and Bergamot',
        'Lavender and Rose',
        'Sandalwood and Patchouli',
        'warm spicy,aromatic,lavender,citrus,fresh spicy',
        'Cardamomum VegetalisbyParfums Berdouesis a Aromatic Spicy fragrance for women and men.Cardamomum Vegetaliswas launched in 1902. Top notes are Cardamom and Bergamot; middle notes are Lavender and Rose; base notes are Sandalwood and Patchouli.',
        3.81,
        21,
        NULL
      ),
(
        'Citrus-Hesperida-8148',
        'Citrus Hesperida Parfums Berdoues',
        'Citrus',
        'for women and men',
        NULL,
        NULL,
        'Citruses, Orange and Lemon',
        'African Orange Flower and Vetiver',
        'Sandalwood and Musk',
        'citrus,woody,white floral,fresh',
        'Citrus HesperidabyParfums Berdouesis a Citrus fragrance for women and men.Citrus Hesperidawas launched in 1902. Top notes are Citruses, Orange and Lemon; middle notes are African Orange Flower and Vetiver; base notes are Sandalwood and Musk.',
        3.55,
        11,
        NULL
      ),
(
        'Lavandula-Vera-8151',
        'Lavandula Vera Parfums Berdoues',
        'Lavandula',
        'for women',
        NULL,
        NULL,
        'Lavender',
        'Geranium and Rose',
        'Tonka Bean and Amber',
        'lavender,aromatic,fresh spicy,amber,herbal',
        'Lavandula VerabyParfums Berdouesis a Aromatic fragrance for women.Lavandula Verawas launched in 1902. Top note is Lavender; middle notes are Geranium and Rose; base notes are Tonka Bean and Amber.',
        4.11,
        9,
        NULL
      ),
(
        'Thea-Verde-8149',
        'Thea Verde Parfums Berdoues',
        'Thea',
        'for women and men',
        NULL,
        NULL,
        'Orange and Mint',
        'Tea and Neroli',
        'Amber and Musk',
        'green,citrus,amber,fresh spicy,aromatic',
        'Thea VerdebyParfums Berdouesis a Aromatic Green fragrance for women and men.Thea Verdewas launched in 1902. Top notes are Orange and Mint; middle notes are Tea and Neroli; base notes are Amber and Musk.',
        4,
        8,
        NULL
      ),
(
        'Vetivera-Herbacea-8153',
        'Vetivera Herbacea Parfums Berdoues',
        'Vetivera',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange and Cedar',
        'Vetiver and Neroli',
        'Tonka Bean and Musk',
        'woody,aromatic,citrus,earthy,green',
        'Vetivera HerbaceabyParfums Berdouesis a Citrus Aromatic fragrance for men. Top notes are Mandarin Orange and Cedar; middle notes are Vetiver and Neroli; base notes are Tonka Bean and Musk.',
        3.95,
        19,
        NULL
      ),
(
        'Viola-Odorata-8150',
        'Viola Odorata Parfums Berdoues',
        'Viola',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,violet,powdery,fresh,floral',
        'Viola OdoratabyParfums Berdouesis a Citrus fragrance for women.Viola Odoratawas launched in 1902.',
        4.07,
        15,
        NULL
      ),
(
        'Brume-de-Jasmin-11144',
        'Brume de Jasmin Parfums Berdoues',
        'Brume',
        'for women',
        NULL,
        NULL,
        'Apple and Lotus',
        'Jasmine, Magnolia and Leather',
        'Vanilla and Amber',
        'floral,white floral,fruity,fresh,vanilla',
        'Brume de JasminbyParfums Berdouesis a Floral fragrance for women.Brume de Jasminwas launched in 2010. Top notes are Apple and Lotus; middle notes are Jasmine, Magnolia and Leather; base notes are Vanilla and Amber.',
        4.09,
        22,
        NULL
      ),
(
        'Les-Contes-Bucoliques-Bal-de-Clochettes-11148',
        'Les Contes Bucoliques Bal de Clochettes Parfums Berdoues',
        'Les',
        'for women',
        NULL,
        NULL,
        'Lily-of-the-Valley, Green Notes and Aldehydes',
        'Jasmine and Cyclamen',
        'Musk, Orange Blossom and Rose',
        'white floral,fresh,green,floral',
        'Les Contes Bucoliques Bal de ClochettesbyParfums Berdouesis a Floral Aldehyde fragrance for women.Les Contes Bucoliques Bal de Clochetteswas launched in 2010. Top notes are Lily-of-the-Valley, Green Notes and Aldehydes; middle notes are Jasmine and Cyclamen; base notes are Musk, Orange Blossom and Rose.',
        4.08,
        25,
        NULL
      ),
(
        'Les-Contes-Bucoliques-Clair-de-Rose-11149',
        'Les Contes Bucoliques Clair de Rose Parfums Berdoues',
        'Les',
        'for women',
        NULL,
        NULL,
        'Grapefruit and Pink Pepper',
        'Peony, Rose and Vanilla',
        'White Musk, Peach Blossom and Vanilla',
        'floral,rose,musky,fresh,citrus',
        'Les Contes Bucoliques Clair de RosebyParfums Berdouesis a Floral fragrance for women.Les Contes Bucoliques Clair de Rosewas launched in 2010. Top notes are Grapefruit and Pink Pepper; middle notes are Peony, Rose and Vanilla; base notes are White Musk, Peach Blossom and Vanilla.',
        3.86,
        42,
        NULL
      ),
(
        'Les-Contes-Bucoliques-Danse-des-Nympheas-19508',
        'Les Contes Bucoliques Danse des Nymphéas Parfums Berdoues',
        'Les',
        'for women',
        NULL,
        NULL,
        'Lemon and Bitter Orange',
        'Sea water, Freesia and Jasmine',
        'White Musk and Amber',
        'citrus,marine,aromatic,floral,fresh',
        'Les Contes Bucoliques Danse des NymphéasbyParfums Berdouesis a Floral Aquatic fragrance for women. Top notes are Lemon and Bitter Orange; middle notes are Sea water, Freesia and Jasmine; base notes are White Musk and Amber.',
        3.93,
        14,
        NULL
      ),
(
        'Les-Contes-Bucoliques-Fleur-d-Oranger-15120',
        'Les Contes Bucoliques Fleur d''Oranger Parfums Berdoues',
        'Les',
        'for women',
        NULL,
        NULL,
        'Orange Blossom',
        'Water Notes and Floral Notes',
        'Vanilla and Musk',
        'white floral,aquatic,citrus,vanilla,sweet',
        'Les Contes Bucoliques Fleur d''OrangerbyParfums Berdouesis a Floral fragrance for women.Les Contes Bucoliques Fleur d''Orangerwas launched in 2012. Top note is Orange Blossom; middle notes are Water Notes and Floral Notes; base notes are Vanilla and Musk.',
        4.29,
        17,
        NULL
      ),
(
        'Les-Contes-Bucoliques-Fleur-de-Cerisier-19507',
        'Les Contes Bucoliques Fleur de Cerisier Parfums Berdoues',
        'Les',
        'for women',
        NULL,
        NULL,
        'Cherry Blossom, Cherry and Bergamot',
        'Lotus and Apple',
        'Vanilla, Sandalwood and White Musk',
        'floral,cherry,fruity,fresh,sweet',
        'Les Contes Bucoliques Fleur de CerisierbyParfums Berdouesis a Floral Fruity Gourmand fragrance for women. Top notes are Cherry Blossom, Cherry and Bergamot; middle notes are Lotus and Apple; base notes are Vanilla, Sandalwood and White Musk.',
        4.21,
        14,
        NULL
      ),
(
        'Violette-Cherie-5374',
        'Violette Cherie Parfums Berdoues',
        'Violette',
        'for women',
        NULL,
        NULL,
        'Violet, Lilac and Violet Leaf',
        'White Honey, Neroli and Mimosa',
        'Lily-of-the-Valley and Musk',
        'floral,fresh,violet,powdery,green',
        'Violette CheriebyParfums Berdouesis a Floral fragrance for women.Violette Cheriewas launched in 2008. Top notes are Violet, Lilac and Violet Leaf; middle notes are White Honey, Neroli and Mimosa; base notes are Lily-of-the-Valley and Musk.',
        4.33,
        55,
        NULL
      ),
(
        'Violette-Divine-8147',
        'Violette Divine Parfums Berdoues',
        'Violette',
        'for women',
        NULL,
        NULL,
        'Mandarin Orange and Violet Leaf',
        'Violet, White Tabacco and Virginia Cedar',
        'Sandalwood and Tuberose',
        'woody,powdery,violet,white floral,floral',
        'Violette DivinebyParfums Berdouesis a Floral fragrance for women. Top notes are Mandarin Orange and Violet Leaf; middle notes are Violet, White Tabacco and Virginia Cedar; base notes are Sandalwood and Tuberose.',
        4.07,
        146,
        NULL
      ),
(
        'Violettes-de-Toulouse-Eau-de-Parfum-4847',
        'Violettes de Toulouse Eau de Parfum Parfums Berdoues',
        'Violettes',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,violet,floral,fruity,woody',
        'Violettes de Toulouse Eau de ParfumbyParfums Berdouesis a Floral fragrance for women.',
        4.08,
        217,
        NULL
      ),
(
        'Violettes-de-Toulouse-Eau-de-Toilette-4848',
        'Violettes de Toulouse Eau de Toilette Parfums Berdoues',
        'Violettes',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,violet,ozonic,floral,iris',
        'Violettes de Toulouse Eau de ToilettebyParfums Berdouesis a Floral fragrance for women.Violettes de Toulouse Eau de Toilettewas launched in 1936.',
        4.22,
        165,
        NULL
      ),
(
        'Oud-Wa-Amber-56276',
        'Oud Wa Amber Parfums Berdoues',
        'Oud',
        'for women and men',
        NULL,
        'Charles Caruso',
        'Nutmeg',
        'Thailand Oud',
        'Spanish Labdanum',
        'oud,animalic,amber,fresh spicy',
        'Oud Wa AmberbyParfums Berdouesis a Amber Spicy fragrance for women and men.Oud Wa Amberwas launched in 2019. The nose behind this fragrance is Charles Caruso. Top note is Nutmeg; middle note is Thailand Oud; base note is Spanish Labdanum.',
        3.82,
        17,
        NULL
      ),
(
        'Oud-Wa-Vanillia-32657',
        'Oud Wa Vanillia Parfums Berdoues',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,oud,amber,powdery,sweet',
        'Oud Wa VanilliabyParfums Berdouesis a Amber Woody fragrance for women and men.Oud Wa Vanilliawas launched in 2016.',
        4.2,
        100,
        NULL
      ),
(
        'Oud-Wa-Ward-32655',
        'Oud Wa Ward Parfums Berdoues',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,oud,patchouli,floral',
        'Oud Wa WardbyParfums Berdouesis a Woody fragrance for women and men.Oud Wa Wardwas launched in 2016.',
        4.31,
        48,
        NULL
      ),
(
        'Arz-el-rab-31438',
        'Arz el-rab Parfums Berdoues',
        'Arz',
        'for women and men',
        NULL,
        'Cyrill Rolland',
        'Ginger',
        'Iris',
        'Cedar',
        'woody,warm spicy,iris,powdery,violet',
        'Arz el-rabbyParfums Berdouesis a Woody Spicy fragrance for women and men.Arz el-rabwas launched in 2015. The nose behind this fragrance is Cyrill Rolland. Top note is Ginger; middle note is Iris; base note is Cedar.',
        3.92,
        141,
        NULL
      ),
(
        'Assam-of-India-31436',
        'Assam of India Parfums Berdoues',
        'Assam',
        'for women and men',
        NULL,
        'Jennifer Riley',
        'Lemon',
        'Indian Tea',
        'Sandalwood',
        'citrus,green,fresh,aromatic,woody',
        'Assam of IndiabyParfums Berdouesis a Aromatic fragrance for women and men.Assam of Indiawas launched in 2015. The nose behind this fragrance is Jennifer Riley. Top note is Lemon; middle note is Indian Tea; base note is Sandalwood.',
        3.94,
        397,
        NULL
      ),
(
        'Azur-Riviera-53671',
        'Azur Riviera Parfums Berdoues',
        'Azur',
        'for women and men',
        NULL,
        'Jean-Marie Santantoni',
        'Algae',
        'Jasmine and Orange Blossom',
        'Sea Notes',
        'marine,white floral,aquatic,aromatic,salty',
        'Azur RivierabyParfums Berdouesis a Aromatic Aquatic fragrance for women and men.Azur Rivierawas launched in 2019. The nose behind this fragrance is Jean-Marie Santantoni. Top note is Algae; middle notes are Jasmine and Orange Blossom; base note is Sea Notes.',
        3.68,
        113,
        NULL
      ),
(
        'Dolce-Amalfi-74135',
        'Dolce Amalfi Parfums Berdoues',
        'Dolce',
        'for women and men',
        NULL,
        'Mylène Alran',
        'Italian Lemon',
        'Patchouli',
        'Virginian Cedar',
        'woody,citrus,patchouli,aromatic,warm spicy',
        'Dolce AmalfibyParfums Berdouesis a Woody Aromatic fragrance for women and men. This is a new fragrance.Dolce Amalfiwas launched in 2022. The nose behind this fragrance is Mylène Alran. Top note is Italian Lemon; middle note is Patchouli; base note is Virginian Cedar.',
        4.08,
        13,
        NULL
      ),
(
        'Guaria-Morada-59840',
        'Guaria Morada Parfums Berdoues',
        'Guaria',
        'for women and men',
        NULL,
        'Mylène Alran',
        'Brazilian Orange',
        'Amyris',
        'Patchouli',
        'woody,aromatic,citrus,balsamic,patchouli',
        'Guaria MoradabyParfums Berdouesis a Floral Fruity fragrance for women and men.Guaria Moradawas launched in 2020. The nose behind this fragrance is Mylène Alran. Top note is Brazilian Orange; middle note is Amyris; base note is Patchouli.',
        3.9,
        107,
        NULL
      ),
(
        'Hoja-de-Cuba-46912',
        'Hoja de Cuba Parfums Berdoues',
        'Hoja',
        'for women and men',
        NULL,
        NULL,
        'Allspice',
        'Haitian Vetiver',
        'Tobacco',
        'tobacco,fresh spicy,sweet,aromatic,woody',
        'Hoja de CubabyParfums Berdouesis a Amber fragrance for women and men.Hoja de Cubawas launched in 2017. Top note is Allspice; middle note is Haitian Vetiver; base note is Tobacco.',
        4.04,
        167,
        NULL
      ),
(
        'Maasai-Mara-43109',
        'Maasaï Mara Parfums Berdoues',
        'Maasaï',
        'for women and men',
        NULL,
        'Philippe Romano',
        'Bitter Orange and Chamomile',
        'Dried Fruits, Plum, Artemisia and Rose',
        'Cinnamon, Benzoin, Spanish Labdanum, Vanilla, Patchouli and Buchu or Agathosma',
        'fruity,warm spicy,cinnamon,amber,sweet',
        'Maasaï MarabyParfums Berdouesis a Aromatic fragrance for women and men.Maasaï Marawas launched in 2017. The nose behind this fragrance is Philippe Romano. Top notes are Bitter Orange and Chamomile; middle notes are Dried Fruits, Plum, Artemisia and Rose; base notes are Cinnamon, Benzoin, Spanish Labdanum, Vanilla, Patchouli and Buchu or Agathosma.',
        4.28,
        345,
        NULL
      ),
(
        'Matahari-Di-Bali-87706',
        'Matahari Di Bali Parfums Berdoues',
        'Matahari',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,warm spicy,aromatic,vanilla',
        'Matahari Di BalibyParfums Berdouesis a Citrus Aromatic fragrance for women and men. This is a new fragrance.Matahari Di Baliwas launched in 2023.',
        3.71,
        7,
        NULL
      ),
(
        'Oud-Al-Sahraa-31437',
        'Oud Al Sahraa Parfums Berdoues',
        'Oud',
        'for women and men',
        NULL,
        'Christian Vermorel',
        'Italian Mandarin',
        'Myrrh',
        'Agarwood (Oud)',
        'amber,oud,citrus,warm spicy,sweet',
        'Oud Al SahraabyParfums Berdouesis a Amber Woody fragrance for women and men.Oud Al Sahraawas launched in 2015. The nose behind this fragrance is Christian Vermorel. Top note is Italian Mandarin; middle note is Myrrh; base note is Agarwood (Oud).',
        4.01,
        185,
        NULL
      ),
(
        'Peng-Lai-48739',
        'Peng Lai Parfums Berdoues',
        'Peng',
        'for women',
        NULL,
        NULL,
        'Chinese Osmanthus, Mandarin Orange, Lemon and Bergamot',
        'Peach, Rose, Orange Blossom and Benzoin',
        'White Musk, Tonka Bean, Violet, Iso E Super and Vanilla',
        'fruity,citrus,floral,powdery,sweet',
        'Peng LaibyParfums Berdouesis a Amber Floral fragrance for women.Peng Laiwas launched in 2018. Top notes are Chinese Osmanthus, Mandarin Orange, Lemon and Bergamot; middle notes are Peach, Rose, Orange Blossom and Benzoin; base notes are White Musk, Tonka Bean, Violet, Iso E Super and Vanilla.',
        3.83,
        257,
        NULL
      ),
(
        'Russkaya-Kozha-41117',
        'Russkaya Kozha Parfums Berdoues',
        'Russkaya',
        'for women and men',
        NULL,
        'Flavien Laurandeau',
        NULL,
        NULL,
        NULL,
        'aromatic,warm spicy,leather,amber,fresh spicy',
        'Russkaya KozhabyParfums Berdouesis a Leather fragrance for women and men.Russkaya Kozhawas launched in 2016. The nose behind this fragrance is Flavien Laurandeau.',
        3.95,
        168,
        NULL
      ),
(
        'Scorza-di-Sicilia-31433',
        'Scorza di Sicilia Parfums Berdoues',
        'Scorza',
        'for women and men',
        NULL,
        'Sébastien Martin',
        'Citruses and Calabrian bergamot',
        'Virginian Cedar',
        'Vetiver',
        'citrus,woody,aromatic,fresh spicy,fresh',
        'Scorza di SiciliabyParfums Berdouesis a Woody Aromatic fragrance for women and men.Scorza di Siciliawas launched in 2015. The nose behind this fragrance is Sébastien Martin. Top notes are Citruses and Calabrian bergamot; middle note is Virginian Cedar; base note is Vetiver.',
        3.76,
        107,
        NULL
      ),
(
        'Selva-do-Brazil-31434',
        'Selva do Brazil Parfums Berdoues',
        'Selva',
        'for women and men',
        NULL,
        'Jennifer Riley',
        'Petitgrain Paraguay',
        'Tonka Bean',
        'Guaiac Wood',
        'woody,aromatic,citrus,green,vanilla',
        'Selva do BrazilbyParfums Berdouesis a Amber Woody fragrance for women and men.Selva do Brazilwas launched in 2015. The nose behind this fragrance is Jennifer Riley. Top note is Petitgrain Paraguay; middle note is Tonka Bean; base note is Guaiac Wood.',
        3.85,
        237,
        NULL
      ),
(
        'Somei-Yoshino-31435',
        'Somei Yoshino Parfums Berdoues',
        'Somei',
        'for women',
        NULL,
        'Angeline Poubeau Leporini',
        'Shiso',
        'Jasmine Sambac',
        'Patchouli',
        'white floral,aromatic,green,fresh spicy,patchouli',
        'Somei YoshinobyParfums Berdouesis a Chypre Floral fragrance for women.Somei Yoshinowas launched in 2015. The nose behind this fragrance is Angeline Poubeau Leporini. Top note is Shiso; middle note is Jasmine Sambac; base note is Patchouli.',
        3.44,
        241,
        NULL
      ),
(
        'Vanira-Moorea-38167',
        'Vanira Moorea Parfums Berdoues',
        'Vanira',
        'for women and men',
        NULL,
        'Alexandra Monet',
        NULL,
        NULL,
        NULL,
        'citrus,vanilla,sweet,aromatic,green',
        'Vanira MooreabyParfums Berdouesis a Aromatic Fruity fragrance for women and men.Vanira Mooreawas launched in 2016. The nose behind this fragrance is Alexandra Monet.',
        3.79,
        251,
        NULL
      ),
(
        'Bora-Bora-55131',
        'Bora-Bora Parfums Berdoues',
        'Bora-Bora',
        'for women and men',
        NULL,
        'Michèle Saramito',
        NULL,
        NULL,
        NULL,
        'coconut,white floral,citrus,sweet,lactonic',
        'Bora-BorabyParfums Berdouesis a Floral Fruity fragrance for women and men.Bora-Borawas launched in 2019. The nose behind this fragrance is Michèle Saramito.',
        3.93,
        15,
        NULL
      ),
(
        'Capri-55132',
        'Capri Parfums Berdoues',
        'Capri',
        'for women and men',
        NULL,
        'Flavien Laurandeau',
        'Bergamot',
        'Brazilian Orange',
        'Cedar',
        'citrus,fresh spicy',
        'CapribyParfums Berdouesis a Citrus fragrance for women and men.Capriwas launched in 2019. The nose behind this fragrance is Flavien Laurandeau. Top note is Bergamot; middle note is Brazilian Orange; base note is Cedar.',
        4.5,
        4,
        NULL
      ),
(
        'Koh-Phi-Phi-55133',
        'Koh Phi Phi Parfums Berdoues',
        'Koh',
        'for women and men',
        NULL,
        'Celine Perdriel',
        'Ylang-Ylang',
        'Tuberose',
        'Tahitian Vetiver',
        'tuberose,white floral,yellow floral,woody,aromatic',
        'Koh Phi PhibyParfums Berdouesis a Floral fragrance for women and men.Koh Phi Phiwas launched in 2019. The nose behind this fragrance is Celine Perdriel. Top note is Ylang-Ylang; middle note is Tuberose; base note is Tahitian Vetiver.',
        4.17,
        12,
        NULL
      ),
(
        'Bondi-Beach-60296',
        'Bondi Beach Parfums Berdoues',
        'Bondi',
        'for women and men',
        NULL,
        'Flavien Laurandeau',
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,white floral,aromatic,fresh',
        'Bondi BeachbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.Bondi Beachwas launched in 2020. The nose behind this fragrance is Flavien Laurandeau.',
        3.7,
        10,
        NULL
      ),
(
        'Calvi-Beach-60293',
        'Calvi Beach Parfums Berdoues',
        'Calvi',
        'for women and men',
        NULL,
        'Patrice Martin',
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic,green,herbal',
        'Calvi BeachbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.Calvi Beachwas launched in 2020. The nose behind this fragrance is Patrice Martin.',
        4.38,
        8,
        NULL
      ),
(
        'Sunrise-Beach-60295',
        'Sunrise Beach Parfums Berdoues',
        'Sunrise',
        'for women and men',
        NULL,
        'Sébastien Martin',
        NULL,
        NULL,
        NULL,
        'citrus,green,aromatic,balsamic',
        'Sunrise BeachbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.Sunrise Beachwas launched in 2020. The nose behind this fragrance is Sébastien Martin.',
        4.15,
        13,
        NULL
      ),
(
        'Venice-Beach-60294',
        'Venice Beach Parfums Berdoues',
        'Venice',
        'for women and men',
        NULL,
        'Celine Perdriel',
        NULL,
        NULL,
        NULL,
        'woody,aromatic,soft spicy,citrus,smoky',
        'Venice BeachbyParfums Berdouesis a Woody Aromatic fragrance for women and men.Venice Beachwas launched in 2020. The nose behind this fragrance is Celine Perdriel.',
        4.17,
        6,
        NULL
      ),
(
        '1902-Bergamote-Indigo-42143',
        '1902 Bergamote Indigo Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Black Currant and Rhubarb',
        'Jasmine, Orange Blossom and Lavender',
        'Musk, Amber and Woody Notes',
        'citrus,white floral,aromatic,fruity,woody',
        '1902 Bergamote IndigobyParfums Berdouesis a Citrus fragrance for women and men.1902 Bergamote Indigowas launched in 2016. Top notes are Bergamot, Black Currant and Rhubarb; middle notes are Jasmine, Orange Blossom and Lavender; base notes are Musk, Amber and Woody Notes.',
        4.33,
        3,
        NULL
      ),
(
        '1902-Bois-Ambre-42140',
        '1902 Bois Ambré Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Bergamot and Citron',
        'Patchouli, Cedar and Palisander Rosewood',
        'Musk, Tonka Bean, Amber and Tobacco',
        'woody,citrus,amber,sweet,musky',
        '1902 Bois AmbrébyParfums Berdouesis a Woody fragrance for women and men.1902 Bois Ambréwas launched in 2017. Top notes are Bergamot and Citron; middle notes are Patchouli, Cedar and Palisander Rosewood; base notes are Musk, Tonka Bean, Amber and Tobacco.',
        4,
        5,
        NULL
      ),
(
        '1902-Cedrat-48915',
        '1902 Cedrat Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Bergamot, Citron, Green Notes and Lavender',
        'Petitgrain Paraguay, Jasmine, Clary Sage, Hedione and Neroli',
        'Musk, Amber and Vanilla',
        'citrus,green,aromatic,white floral,floral',
        '1902 CedratbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.1902 Cedratwas launched in 2018. Top notes are Mandarin Orange, Bergamot, Citron, Green Notes and Lavender; middle notes are Petitgrain Paraguay, Jasmine, Clary Sage, Hedione and Neroli; base notes are Musk, Amber and Vanilla.',
        4.12,
        8,
        NULL
      ),
(
        '1902-Cedre-Blanc-53642',
        '1902 Cèdre Blanc Parfums Berdoues',
        '1902',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,white floral,fruity,sweet',
        '1902 Cèdre BlancbyParfums Berdouesis a fragrance for men.1902 Cèdre Blancwas launched in 2018.',
        3.72,
        18,
        NULL
      ),
(
        '1902-Citron-Caviar-66353',
        '1902 Citron Caviar Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Verbena, Bergamot and Lemon',
        'Orange Blossom, Ginger and Cardamom',
        'Vetiver, Amber and Musk',
        'citrus,amber,white floral,musky,aromatic',
        '1902 Citron CaviarbyParfums Berdouesis a Aromatic fragrance for women and men.1902 Citron Caviarwas launched in 2021. Top notes are Verbena, Bergamot and Lemon; middle notes are Orange Blossom, Ginger and Cardamom; base notes are Vetiver, Amber and Musk.',
        4.23,
        13,
        NULL
      ),
(
        '1902-Figue-Blanche-39129',
        '1902 Figue Blanche Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Fig, Bergamot and Ylang-Ylang',
        'Peach and Jasmine',
        'Cedar, White Musk and Vanilla',
        'fruity,sweet,woody,citrus,powdery',
        '1902 Figue BlanchebyParfums Berdouesis a Floral Fruity fragrance for women and men.1902 Figue Blanchewas launched in 2016. Top notes are Fig, Bergamot and Ylang-Ylang; middle notes are Peach and Jasmine; base notes are Cedar, White Musk and Vanilla.',
        4.31,
        111,
        NULL
      ),
(
        '1902-Fleur-d-Oranger-86148',
        '1902 Fleur d''Oranger Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Neroli and Petitgrain',
        'Orange Blossom',
        'White Musk',
        'white floral,citrus,musky,sweet,soapy',
        '1902 Fleur d''OrangerbyParfums Berdouesis a fragrance for women and men. Top notes are Neroli and Petitgrain; middle note is Orange Blossom; base note is White Musk.',
        4.56,
        9,
        NULL
      ),
(
        '1902-Gingembre-Vert-26650',
        '1902 Gingembre Vert Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,citrus,warm spicy,fresh',
        '1902 Gingembre VertbyParfums Berdouesis a Aromatic Green fragrance for women and men.',
        3.9,
        50,
        NULL
      ),
(
        '1902-Jasmin-91493',
        '1902 Jasmin Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,yellow floral,sweet,woody,floral',
        '1902 JasminbyParfums Berdouesis a fragrance for women and men. This is a new fragrance.1902 Jasminwas launched in 2024.',
        5,
        1,
        NULL
      ),
(
        '1902-Lavande-8585',
        '1902 Lavande Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lavender,aromatic,musky,fresh spicy,sweet',
        '1902 LavandebyParfums Berdouesis a Floral Green fragrance for women and men.',
        4.13,
        55,
        NULL
      ),
(
        '1902-Mandarine-Cuir-41056',
        '1902 Mandarine & Cuir Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Cardamom and Pink Pepper',
        'Mandarin Leaf and Floral Notes',
        'Leather, Musk and Vetiver',
        'citrus,aromatic,leather,musky,warm spicy',
        '1902 Mandarine & CuirbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.1902 Mandarine & Cuirwas launched in 2015. Top notes are Mandarin Orange, Cardamom and Pink Pepper; middle notes are Mandarin Leaf and Floral Notes; base notes are Leather, Musk and Vetiver.',
        4.1,
        39,
        NULL
      ),
(
        '1902-Naturelle-8580',
        '1902 Naturelle Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        'Bergamot, Amalfi Lemon, Lavender, Orange, Neroli, Geranium, Amber, Thyme, Rosemary, Tonka Bean and Rose',
        'citrus,aromatic,fresh spicy,amber,lavender',
        '1902 NaturellebyParfums Berdouesis a Citrus Aromatic fragrance for women and men. base notes are Bergamot, Amalfi Lemon, Lavender, Orange, Neroli, Geranium, Amber, Thyme, Rosemary, Tonka Bean and Rose.',
        4.2,
        71,
        NULL
      ),
(
        '1902-Orange-Fizz-59854',
        '1902 Orange Fizz Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'Orange, Clementine and Mandarin Orange',
        'Orange Blossom and Freesia',
        'White Musk and Amber',
        'citrus,sweet,white floral',
        '1902 Orange FizzbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.1902 Orange Fizzwas launched in 2020. Top notes are Orange, Clementine and Mandarin Orange; middle notes are Orange Blossom and Freesia; base notes are White Musk and Amber.',
        3.75,
        28,
        NULL
      ),
(
        '1902-Pamplemousse-26649',
        '1902 Pamplemousse Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,fresh',
        '1902 PamplemoussebyParfums Berdouesis a Citrus Aromatic fragrance for women and men.',
        3.61,
        28,
        NULL
      ),
(
        '1902-Rose-54400',
        '1902 Rose Parfums Berdoues',
        '1902',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,floral',
        '1902 RosebyParfums Berdouesis a Floral fragrance for women.1902 Rosewas launched in 2019.',
        4.25,
        24,
        NULL
      ),
(
        '1902-The-Blanc-48916',
        '1902 The Blanc Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        'White Tea, Bergamot and Violet Leaf',
        'Mate and Litsea Cubeba',
        'Musk and White Wood',
        'green,musky,citrus,fresh spicy,fresh',
        '1902 The BlancbyParfums Berdouesis a Aromatic Green fragrance for women and men.1902 The Blancwas launched in 2018. Top notes are White Tea, Bergamot and Violet Leaf; middle notes are Mate and Litsea Cubeba; base notes are Musk and White Wood.',
        4.25,
        8,
        NULL
      ),
(
        '1902-The-Vert-8581',
        '1902 The Vert Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,citrus,fresh spicy,aromatic,musky',
        '1902 The VertbyParfums Berdouesis a Citrus Aromatic fragrance for women and men.',
        3.8,
        44,
        NULL
      ),
(
        '1902-Tonique-8582',
        '1902 Tonique Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,woody,lavender',
        '1902 ToniquebyParfums Berdouesis a Woody Aromatic fragrance for women and men.',
        4.11,
        28,
        NULL
      ),
(
        '1902-Verveine-Yuzu-42141',
        '1902 Verveine Yuzu Parfums Berdoues',
        '1902',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,green,sweet,fresh spicy',
        '1902 Verveine YuzubyParfums Berdouesis a Citrus fragrance for men.1902 Verveine Yuzuwas launched in 2016.',
        4.03,
        36,
        NULL
      ),
(
        '1902-Vetiver-8583',
        '1902 Vetiver Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,herbal,citrus,fresh spicy',
        '1902 VetiverbyParfums Berdouesis a Woody Aromatic fragrance for women and men.',
        4.14,
        70,
        NULL
      ),
(
        '1902-Violette-8584',
        '1902 Violette Parfums Berdoues',
        '1902',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'violet,powdery,floral,fruity,sweet',
        '1902 ViolettebyParfums Berdouesis a Floral Fruity fragrance for women and men.',
        4.02,
        105,
        NULL
      ),
(
        'Baies-Fun-86946',
        'Baies & Fun Parfums Berdoues',
        'Baies',
        'for women and men',
        NULL,
        NULL,
        'Bergamot',
        'Pink Pepper',
        'Ylang Ylang',
        'citrus,yellow floral,sweet,soft spicy,fresh spicy',
        'Baies & FunbyParfums Berdouesis a fragrance for women and men. This is a new fragrance.Baies & Funwas launched in 2023. Top note is Bergamot; middle note is Pink Pepper; base note is Ylang Ylang.',
        NULL,
        NULL,
        NULL
      ),
(
        'Neroli-Peace-86949',
        'Néroli & Peace Parfums Berdoues',
        'Néroli',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom',
        'Neroli',
        'Musk',
        'white floral,citrus,musky,powdery,sweet',
        'Néroli & PeacebyParfums Berdouesis a fragrance for women and men. This is a new fragrance.Néroli & Peacewas launched in 2023. Top note is Orange Blossom; middle note is Neroli; base note is Musk.',
        NULL,
        NULL,
        NULL
      ),
(
        'Osmanthus-Love-86948',
        'Osmanthus & Love Parfums Berdoues',
        'Osmanthus',
        'for women and men',
        NULL,
        NULL,
        'Osmanthus',
        'Orange Blossom',
        'Vanilla',
        'floral,fruity,white floral,citrus,soft spicy',
        'Osmanthus & LovebyParfums Berdouesis a fragrance for women and men. This is a new fragrance.Osmanthus & Lovewas launched in 2023. Top note is Osmanthus; middle note is Orange Blossom; base note is Vanilla.',
        4,
        1,
        NULL
      ),
(
        'The-Vert-Free-86947',
        'Thé Vert & Free Parfums Berdoues',
        'Thé',
        'for women and men',
        NULL,
        NULL,
        'Green Tea',
        'Mint',
        'Sandalwood',
        'green,woody,aromatic,fresh spicy,powdery',
        'Thé Vert & FreebyParfums Berdouesis a fragrance for women and men. This is a new fragrance.Thé Vert & Freewas launched in 2023. Top note is Green Tea; middle note is Mint; base note is Sandalwood.',
        3,
        1,
        NULL
      ),
(
        'Violette-44298',
        'Violette Parfums Berdoues',
        'Violette',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,patchouli,woody,earthy',
        'ViolettebyParfums Berdouesis a Floral Woody Musk fragrance for women and men.Violettewas launched in 2017.',
        3.81,
        74,
        NULL
      ),
(
        'Eau-des-Alizes-19509',
        'Eau des Alizés Parfums Berdoues',
        'Eau',
        'for women',
        NULL,
        NULL,
        'Sea water, Lilac and Bergamot',
        'Frangipani and Rose',
        'White Musk, Tonka Bean and Vanilla',
        'floral,marine,aromatic,citrus,musky',
        'Eau des AlizésbyParfums Berdouesis a Floral Aquatic fragrance for women. Top notes are Sea water, Lilac and Bergamot; middle notes are Frangipani and Rose; base notes are White Musk, Tonka Bean and Vanilla.',
        3,
        3,
        NULL
      ),
(
        'Musc-Ylang-Ylang-19510',
        'Musc Ylang Ylang Parfums Berdoues',
        'Musc',
        'for women',
        NULL,
        NULL,
        'Coconut and Bergamot',
        'Ylang-Ylang, Sea water and Jasmine',
        'Vanilla, Musk and Woody Notes',
        'sweet,vanilla,coconut,yellow floral,woody',
        'Musc Ylang YlangbyParfums Berdouesis a Floral Aquatic fragrance for women. Top notes are Coconut and Bergamot; middle notes are Ylang-Ylang, Sea water and Jasmine; base notes are Vanilla, Musk and Woody Notes.',
        3.93,
        14,
        NULL
      ),
(
        'Vanille-Cacao-26647',
        'Vanille Cacao Parfums Berdoues',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,cacao,warm spicy,sweet,powdery',
        'Vanille CacaobyParfums Berdouesis a Amber Vanilla fragrance for women and men.',
        4.16,
        25,
        NULL
      ),
(
        'Vanille-Framboise-19513',
        'Vanille Framboise Parfums Berdoues',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,vanilla',
        'Vanille FramboisebyParfums Berdouesis a Amber Vanilla fragrance for women.',
        3.67,
        12,
        NULL
      ),
(
        'Vanille-Monoi-19514',
        'Vanille Monoï Parfums Berdoues',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,white floral,coconut,sweet,tropical',
        'Vanille MonoïbyParfums Berdouesis a Floral Fruity Gourmand fragrance for women.',
        4.12,
        17,
        NULL
      ),
(
        'Vanille-Neroli-26648',
        'Vanille Neroli Parfums Berdoues',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Citruses',
        'Orange Blossom',
        'Vanilla and Musk',
        'vanilla,powdery,white floral,sweet,citrus',
        'Vanille NerolibyParfums Berdouesis a Amber Floral fragrance for women. Top note is Citruses; middle note is Orange Blossom; base notes are Vanilla and Musk.',
        3.86,
        14,
        NULL
      ),
(
        'Vanille-Patchouli-19511',
        'Vanille Patchouli Parfums Berdoues',
        'Vanille',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,warm spicy,patchouli,chocolate,sweet',
        'Vanille PatchoulibyParfums Berdouesis a Amber Vanilla fragrance for women.',
        3.68,
        19,
        NULL
      );
