
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Vanille-Fruitee-6255',
        'Vanille Fruitée Molinard',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        'Carnation and Bergamot',
        'Vanilla, Orchid, Heliotrope, Raspberry and Solar Notes',
        'Vanilla Pod, White Musk, Benzoin and Sugar',
        'vanilla,sweet,caramel,powdery,floral',
        'Vanille FruitéebyMolinardis a Amber Vanilla fragrance for women and men.Vanille Fruitéewas launched in 1998. Top notes are Carnation and Bergamot; middle notes are Vanilla, Orchid, Heliotrope, Raspberry and Solar Notes; base notes are Vanilla Pod, White Musk, Benzoin and Sugar.',
        3.85,
        127,
        NULL
      ),
(
        'Ambre-Eau-de-Parfum-41894',
        'Ambre Eau de Parfum Molinard',
        'Ambre',
        'for women and men',
        NULL,
        NULL,
        'Lavender, Orange, Bergamot and Lemon',
        'Benzoin, Incense, Cloves and Geranium',
        'Vanilla, Patchouli and Musk',
        'warm spicy,amber,vanilla,balsamic,citrus',
        'Ambre Eau de ParfumbyMolinardis a Amber fragrance for women and men.Ambre Eau de Parfumwas launched in 2015. Top notes are Lavender, Orange, Bergamot and Lemon; middle notes are Benzoin, Incense, Cloves and Geranium; base notes are Vanilla, Patchouli and Musk.',
        4.18,
        405,
        NULL
      ),
(
        'Cuir-Eau-de-Parfum-36670',
        'Cuir Eau de Parfum Molinard',
        'Cuir',
        'for women and men',
        NULL,
        NULL,
        'Nutmeg, Lemon Verbena and Bergamot',
        'Saffron, Pepper, Lavender and Lily',
        'Leather, Agarwood (Oud), Amber, Musk, Sandalwood and Patchouli',
        'fresh spicy,leather,warm spicy,oud,animalic',
        'Cuir Eau de ParfumbyMolinardis a Leather fragrance for women and men.Cuir Eau de Parfumwas launched in 2015. Top notes are Nutmeg, Lemon Verbena and Bergamot; middle notes are Saffron, Pepper, Lavender and Lily; base notes are Leather, Agarwood (Oud), Amber, Musk, Sandalwood and Patchouli.',
        3.91,
        699,
        NULL
      ),
(
        'Figue-Eau-de-Parfum-41700',
        'Figue Eau de Parfum Molinard',
        'Figue',
        'for women and men',
        NULL,
        'Mathieu Nardin',
        'Fig, Lemon and Black Currant',
        'Green Leaves, Floral Notes and Jasmine Sambac',
        'Cedar, Musk and Amberwood',
        'fruity,woody,citrus,green,sweet',
        'Figue Eau de ParfumbyMolinardis a Floral Fruity fragrance for women and men.Figue Eau de Parfumwas launched in 2016. The nose behind this fragrance is Mathieu Nardin. Top notes are Fig, Lemon and Black Currant; middle notes are Green Leaves, Floral Notes and Jasmine Sambac; base notes are Cedar, Musk and Amberwood.',
        4.1,
        867,
        NULL
      ),
(
        'Fleur-d-Oranger-Eau-de-Parfum-44285',
        'Fleur d''Oranger Eau de Parfum Molinard',
        'Fleur',
        'for women and men',
        NULL,
        NULL,
        'Bergamot, Cypress, Lavender and Fig',
        'Neroli, Petitgrain, Jasmine and Rose',
        'Orange Blossom and Musk',
        'white floral,citrus,aromatic,fresh spicy,green',
        'Fleur d''Oranger Eau de ParfumbyMolinardis a fragrance for women and men.Fleur d''Oranger Eau de Parfumwas launched in 2017. Top notes are Bergamot, Cypress, Lavender and Fig; middle notes are Neroli, Petitgrain, Jasmine and Rose; base notes are Orange Blossom and Musk.',
        4.07,
        119,
        NULL
      ),
(
        'Iris-Eau-de-Parfum-91707',
        'Iris Eau de Parfum Molinard',
        'Iris',
        'for women and men',
        NULL,
        NULL,
        'Violet Leaf, Pink Pepper and Pear',
        'Iris and Rose',
        'Musk, Cashmere Wood and Cedar',
        'iris,powdery,musky,woody,violet',
        'Iris Eau de ParfumbyMolinardis a Floral Woody Musk fragrance for women and men. This is a new fragrance.Iris Eau de Parfumwas launched in 2024. Top notes are Violet Leaf, Pink Pepper and Pear; middle notes are Iris and Rose; base notes are Musk, Cashmere Wood and Cedar.',
        3.63,
        30,
        NULL
      ),
(
        'Jasmin-Eau-de-Parfum-31836',
        'Jasmin Eau de Parfum Molinard',
        'Jasmin',
        'for women',
        NULL,
        NULL,
        'Jasmine and Lemon',
        'Orange Blossom, Carnation and Rose',
        'White Musk and Sandalwood',
        'white floral,floral,citrus,warm spicy',
        'Jasmin Eau de ParfumbyMolinardis a Floral fragrance for women.Jasmin Eau de Parfumwas launched in 2015. Top notes are Jasmine and Lemon; middle notes are Orange Blossom, Carnation and Rose; base notes are White Musk and Sandalwood.',
        3.71,
        255,
        NULL
      ),
(
        'Lavande-Eau-de-Parfum-49704',
        'Lavande Eau de Parfum Molinard',
        'Lavande',
        'for women and men',
        NULL,
        NULL,
        'Lavender and Clary Sage',
        'Hedione',
        'Vanilla, Benzoin, Tonka Bean, Coumarin, Labdanum and Patchouli',
        'vanilla,aromatic,lavender,amber,warm spicy',
        'Lavande Eau de ParfumbyMolinardis a fragrance for women and men.Lavande Eau de Parfumwas launched in 2018. Top notes are Lavender and Clary Sage; middle note is Hedione; base notes are Vanilla, Benzoin, Tonka Bean, Coumarin, Labdanum and Patchouli.',
        4.01,
        416,
        NULL
      ),
(
        'Muguet-Eau-de-Parfum-44114',
        'Muguet Eau de Parfum Molinard',
        'Muguet',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,floral,fresh,green',
        'Muguet Eau de ParfumbyMolinardis a Floral fragrance for women and men.Muguet Eau de Parfumwas launched in 2015.',
        3.72,
        358,
        NULL
      ),
(
        'Musc-Eau-de-Parfum-31837',
        'Musc Eau de Parfum Molinard',
        'Musc',
        'for women and men',
        NULL,
        NULL,
        'Neroli and Bergamot',
        'Patchouli, Amber and Vanilla',
        'Opoponax, Musk and Benzoin',
        'amber,balsamic,patchouli,musky,warm spicy',
        'Musc Eau de ParfumbyMolinardis a Woody Floral Musk fragrance for women and men.Musc Eau de Parfumwas launched in 2015. Top notes are Neroli and Bergamot; middle notes are Patchouli, Amber and Vanilla; base notes are Opoponax, Musk and Benzoin.',
        3.75,
        346,
        NULL
      ),
(
        'Osmanthus-Eau-de-Parfum-64814',
        'Osmanthus Eau de Parfum Molinard',
        'Osmanthus',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Bergamot and Pink Pepper',
        'Osmanthus, Tuberose and Jasmine',
        'Apricot, White Musk and Iris',
        'fruity,floral,powdery,lactonic,musky',
        'Osmanthus Eau de ParfumbyMolinardis a Floral Fruity fragrance for women and men.Osmanthus Eau de Parfumwas launched in 2021. Top notes are Mandarin Orange, Bergamot and Pink Pepper; middle notes are Osmanthus, Tuberose and Jasmine; base notes are Apricot, White Musk and Iris.',
        4,
        431,
        NULL
      ),
(
        'Patchouli-Eau-de-Parfum-31838',
        'Patchouli Eau de Parfum Molinard',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Geranium, Neroli and Orange',
        'Patchouli',
        'Vanilla, Sandalwood and Musk',
        'patchouli,woody,warm spicy,fresh spicy,balsamic',
        'Patchouli Eau de ParfumbyMolinardis a Woody Chypre fragrance for women and men.Patchouli Eau de Parfumwas launched in 2015. Top notes are Geranium, Neroli and Orange; middle note is Patchouli; base notes are Vanilla, Sandalwood and Musk.',
        3.92,
        492,
        NULL
      ),
(
        'Rose-Eau-de-Parfum-42217',
        'Rose Eau de Parfum Molinard',
        'Rose',
        'for women and men',
        NULL,
        NULL,
        'Rose',
        'Geranium, Cloves, Chamomile and Violet',
        'Musk, Almond and Vanilla',
        'rose,warm spicy,fresh spicy,aromatic,floral',
        'Rose Eau de ParfumbyMolinardis a Floral fragrance for women and men.Rose Eau de Parfumwas launched in 2015. Top note is Rose; middle notes are Geranium, Cloves, Chamomile and Violet; base notes are Musk, Almond and Vanilla.',
        3.6,
        237,
        NULL
      ),
(
        'Santal-Insolent-64220',
        'Santal Insolent Molinard',
        'Santal',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, elemi and Pepper',
        'Sandalwood, Cedar and Incense',
        'Leather, Amber and Papyrus',
        'woody,warm spicy,leather,aromatic,powdery',
        'Santal InsolentbyMolinardis a Amber Spicy fragrance for women and men.Santal Insolentwas launched in 2020. Top notes are Cardamom, elemi and Pepper; middle notes are Sandalwood, Cedar and Incense; base notes are Leather, Amber and Papyrus.',
        3.81,
        118,
        NULL
      ),
(
        'Vanille-Eau-de-Parfum-44115',
        'Vanille Eau de Parfum Molinard',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,sweet',
        'Vanille Eau de ParfumbyMolinardis a Amber Vanilla fragrance for women and men.Vanille Eau de Parfumwas launched in 2015.',
        3.88,
        408,
        NULL
      ),
(
        'Vanille-Fruitee-Eau-de-Parfum-41895',
        'Vanille Fruitee Eau de Parfum Molinard',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        'Vanilla, Caramel and White Peach',
        'Orchid, Ylang-Ylang and Jasmine',
        'Grapes, Osmanthus and Citron',
        'sweet,fruity,vanilla,caramel,floral',
        'Vanille Fruitee Eau de ParfumbyMolinardis a Floral Fruity fragrance for women and men.Vanille Fruitee Eau de Parfumwas launched in 2015. Top notes are Vanilla, Caramel and White Peach; middle notes are Orchid, Ylang-Ylang and Jasmine; base notes are Grapes, Osmanthus and Citron.',
        3.94,
        501,
        NULL
      ),
(
        'Vanille-Patchouli-Eau-de-Parfum-42003',
        'Vanille Patchouli Eau de Parfum Molinard',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        'Patchouli and Sandalwood',
        'Vanilla and Benzoin',
        'White Musk',
        'vanilla,warm spicy,woody,patchouli,powdery',
        'Vanille Patchouli Eau de ParfumbyMolinardis a Amber Vanilla fragrance for women and men.Vanille Patchouli Eau de Parfumwas launched in 2015. Top notes are Patchouli and Sandalwood; middle notes are Vanilla and Benzoin; base note is White Musk.',
        4.04,
        520,
        NULL
      ),
(
        'Vetiver-69684',
        'Vétiver Molinard',
        'Vétiver',
        'for women and men',
        NULL,
        NULL,
        'Blood Orange, Grapefruit and Bergamot',
        'Amber, Iris, Lavender and Violet Leaf',
        'Haitian Vetiver and Java vetiver oil',
        'aromatic,woody,earthy,citrus,amber',
        'VétiverbyMolinardis a fragrance for women and men.Vétiverwas launched in 2021. Top notes are Blood Orange, Grapefruit and Bergamot; middle notes are Amber, Iris, Lavender and Violet Leaf; base notes are Haitian Vetiver and Java vetiver oil.',
        3.68,
        69,
        NULL
      ),
(
        'Violette-Eau-de-Parfum-40953',
        'Violette Eau de Parfum Molinard',
        'Violette',
        'for women and men',
        NULL,
        NULL,
        'Violet, Black Currant, Bergamot and Lemon',
        'Violet, Green Apple, Rose, Peach and Jasmine',
        'Violet Leaf, Iris and White Musk',
        'violet,powdery,fruity,ozonic,floral',
        'Violette Eau de ParfumbyMolinardis a Floral fragrance for women and men.Violette Eau de Parfumwas launched in 2016. Top notes are Violet, Black Currant, Bergamot and Lemon; middle notes are Violet, Green Apple, Rose, Peach and Jasmine; base notes are Violet Leaf, Iris and White Musk.',
        3.86,
        532,
        NULL
      ),
(
        'Ecoute-Moi-9318',
        'Écoute Moi Molinard',
        'Écoute',
        'for women',
        NULL,
        NULL,
        'Neroli, Bitter Orange, Mandarin Orange and Amalfi Lemon',
        'Marigold, Jasmine, Rose, Osmanthus, Ylang-Ylang and Tuberose',
        'African Orange Flower, Benzoin, Raspberry, Tonka Bean and Teak Wood',
        'citrus,white floral,sweet,floral,fruity',
        'Écoute MoibyMolinardis a Amber Floral fragrance for women.Écoute Moiwas launched in 2007. Top notes are Neroli, Bitter Orange, Mandarin Orange and Amalfi Lemon; middle notes are Marigold, Jasmine, Rose, Osmanthus, Ylang-Ylang and Tuberose; base notes are African Orange Flower, Benzoin, Raspberry, Tonka Bean and Teak Wood.',
        3.57,
        47,
        NULL
      ),
(
        'Mirea-9347',
        'Mirea Molinard',
        'Mirea',
        'for women',
        NULL,
        NULL,
        'Blackberry, Blueberry, Litchi and Melon',
        'Cassis, Basil, Iris, Big Strawberry, Jasmine and Amalfi Lemon',
        'Toffee, Vanilla, Sandalwood, Magnolia and Musk',
        'fruity,sweet,aromatic,powdery,green',
        'MireabyMolinardis a Floral Fruity fragrance for women.Mireawas launched in 2007. Top notes are Blackberry, Blueberry, Litchi and Melon; middle notes are Cassis, Basil, Iris, Big Strawberry, Jasmine and Amalfi Lemon; base notes are Toffee, Vanilla, Sandalwood, Magnolia and Musk.',
        3.79,
        57,
        NULL
      ),
(
        'Un-Air-31818',
        'Un Air Molinard',
        'Un',
        'for women',
        NULL,
        NULL,
        'Black Currant, Grapefruit, Bergamot and Mandarin Orange',
        'Rose, Jasmine, Osmanthus and Iris',
        'Vanilla, Vetiver, Oakmoss and Musk',
        'rose,white floral,floral,vanilla,fruity',
        'Un AirbyMolinardis a Floral fragrance for women.Un Airwas launched in 2007. Top notes are Black Currant, Grapefruit, Bergamot and Mandarin Orange; middle notes are Rose, Jasmine, Osmanthus and Iris; base notes are Vanilla, Vetiver, Oakmoss and Musk.',
        3.93,
        14,
        NULL
      ),
(
        'Vents-et-Marees-21481',
        'Vents et Marées Molinard',
        'Vents',
        'for women',
        NULL,
        NULL,
        'Tangerine, Clementine, Grapefruit and Black Currant',
        'Sea Notes, Freesia, Lily-of-the-Valley, Rose and Jasmine',
        'White Musk, Ambergris, Sandalwood, Vanilla and Tonka Bean',
        'citrus,floral,marine,white floral,aromatic',
        'Vents et MaréesbyMolinardis a Floral Aquatic fragrance for women.Vents et Maréeswas launched in 2007. Top notes are Tangerine, Clementine, Grapefruit and Black Currant; middle notes are Sea Notes, Freesia, Lily-of-the-Valley, Rose and Jasmine; base notes are White Musk, Ambergris, Sandalwood, Vanilla and Tonka Bean.',
        3.88,
        25,
        NULL
      ),
(
        'Les-Fleurs-Fleur-De-Figuer-6223',
        'Les Fleurs Fleur De Figuer Molinard',
        'Les',
        'for women',
        NULL,
        NULL,
        'Orange',
        'Fig Leaf and Galbanum',
        'Virginia Cedar',
        'green,fresh,woody,aromatic',
        'Les Fleurs Fleur De FiguerbyMolinardis a Floral fragrance for women.Les Fleurs Fleur De Figuerwas launched in 1999. Top note is Orange; middle notes are Fig Leaf and Galbanum; base note is Virginia Cedar.',
        4.2,
        90,
        NULL
      ),
(
        'Les-Fleurs-Jasmin-6238',
        'Les Fleurs Jasmin Molinard',
        'Les',
        'for women',
        NULL,
        NULL,
        'Green Notes and Water Notes',
        'Jasmine, Orange Blossom and Rose',
        'Musk',
        'white floral,musky,green',
        'Les Fleurs JasminbyMolinardis a Floral fragrance for women.Les Fleurs Jasminwas launched in 1994. Top notes are Green Notes and Water Notes; middle notes are Jasmine, Orange Blossom and Rose; base note is Musk.',
        4.22,
        63,
        NULL
      ),
(
        'Les-Fleurs-Mimosa-6240',
        'Les Fleurs Mimosa Molinard',
        'Les',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,yellow floral,floral,green,vanilla',
        'Les Fleurs MimosabyMolinardis a Floral Green fragrance for women.Les Fleurs Mimosawas launched in 1994.',
        3.76,
        34,
        NULL
      ),
(
        'Les-Fleurs-Rose-6250',
        'Les Fleurs Rose Molinard',
        'Les',
        'for women',
        NULL,
        NULL,
        'Tea Rose',
        'Rose and Cloves',
        'Woody Notes',
        'rose,woody,floral,warm spicy',
        'Les Fleurs RosebyMolinardis a Floral Green fragrance for women.Les Fleurs Rosewas launched in 1994. Top note is Tea Rose; middle notes are Rose and Cloves; base note is Woody Notes.',
        3.91,
        96,
        NULL
      ),
(
        'Les-Fleurs-Violette-6242',
        'Les Fleurs Violette Molinard',
        'Les',
        'for women',
        NULL,
        NULL,
        'Violet',
        'Iris, Violet Leaf, Jasmine and Rose',
        'Heliotrope and Musk',
        'powdery,violet,floral,iris,musky',
        'Les Fleurs ViolettebyMolinardis a Floral Woody Musk fragrance for women.Les Fleurs Violettewas launched in 1994. Top note is Violet; middle notes are Iris, Violet Leaf, Jasmine and Rose; base notes are Heliotrope and Musk.',
        3.94,
        148,
        NULL
      ),
(
        'Fleur-de-Figuier-3936',
        'Fleur de Figuier Molinard',
        'Fleur',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'green,fresh,aromatic,woody',
        'Fleur de FiguierbyMolinardis a Aromatic Green fragrance for women.Fleur de Figuierwas launched in 1999.',
        4.09,
        54,
        NULL
      ),
(
        'Lavande-6258',
        'Lavande Molinard',
        'Lavande',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'lavender,aromatic,fresh spicy',
        'LavandebyMolinardis a Aromatic Fougere fragrance for women and men.Lavandewas launched in 1999.',
        4,
        9,
        NULL
      ),
(
        'Lys-19168',
        'Lys Molinard',
        'Lys',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,citrus,vanilla,musky,powdery',
        'LysbyMolinardis a Floral fragrance for women.Lyswas launched in 1999.',
        3.25,
        8,
        NULL
      ),
(
        'Muguet-6261',
        'Muguet Molinard',
        'Muguet',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,fresh,green,soapy',
        'MuguetbyMolinardis a Floral Green fragrance for women.Muguetwas launched in 1999.',
        4.08,
        37,
        NULL
      ),
(
        'Violette-6260',
        'Violette Molinard',
        'Violette',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'violet,powdery,floral',
        'ViolettebyMolinardis a Floral Woody Musk fragrance for women.Violettewas launched in 1999.',
        4.05,
        19,
        NULL
      ),
(
        'Mure-6241',
        'Mure Molinard',
        'Mure',
        'for women',
        NULL,
        NULL,
        'Blackberry',
        'Amalfi Lemon, Bergamot, Neroli and Jasmine',
        'Musk and Vanille',
        'fruity,citrus,sweet,musky,vanilla',
        'MurebyMolinardis a Floral Fruity fragrance for women.Murewas launched in 1993. Top note is Blackberry; middle notes are Amalfi Lemon, Bergamot, Neroli and Jasmine; base notes are Musk and Vanille.',
        3.68,
        108,
        NULL
      ),
(
        'Orange-Cannelle-6243',
        'Orange Cannelle Molinard',
        'Orange',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,warm spicy,cinnamon,vanilla,amber',
        'Orange CannellebyMolinardis a Citrus Aromatic fragrance for women and men.Orange Cannellewas launched in 1993.',
        3.56,
        48,
        NULL
      ),
(
        'Peche-de-Vigne-6244',
        'Pêche de Vigne Molinard',
        'Pêche',
        'for women',
        NULL,
        NULL,
        'Black Currant and African Orange Flower',
        'Apricot, Osmanthus, Sage and Cardamom',
        'Benzoin, Vanilla and Musk',
        'fruity,soft spicy,aromatic,floral,powdery',
        'Pêche de VignebyMolinardis a Floral Fruity fragrance for women.Pêche de Vignewas launched in 1993. Top notes are Black Currant and African Orange Flower; middle notes are Apricot, Osmanthus, Sage and Cardamom; base notes are Benzoin, Vanilla and Musk.',
        3.83,
        29,
        NULL
      ),
(
        'Campus-31815',
        'Campus Molinard',
        'Campus',
        'for men',
        NULL,
        NULL,
        'Mandarin Orange, Green Apple, Pineapple and Lemon',
        'Lavender, Geranium, Sandalwood and Jasmine',
        'Patchouli, Cedar, Amberwood and Musk',
        'citrus,fruity,fresh spicy,aromatic,sweet',
        'CampusbyMolinardis a Woody Aromatic fragrance for men.Campuswas launched in 2015. Top notes are Mandarin Orange, Green Apple, Pineapple and Lemon; middle notes are Lavender, Geranium, Sandalwood and Jasmine; base notes are Patchouli, Cedar, Amberwood and Musk.',
        2.6,
        5,
        NULL
      ),
(
        'Madrigal-19370',
        'Madrigal Molinard',
        'Madrigal',
        'for men',
        NULL,
        NULL,
        'Tarragon and Lemon',
        'Mandarin Orange and Lavender',
        'Cedar and Patchouli',
        'citrus,aromatic,woody,lavender,anis',
        'MadrigalbyMolinardis a Woody Aromatic fragrance for men.Madrigalwas launched in 1935. Top notes are Tarragon and Lemon; middle notes are Mandarin Orange and Lavender; base notes are Cedar and Patchouli.',
        4.48,
        21,
        NULL
      ),
(
        'MM-19372',
        'MM Molinard',
        'MM',
        'for men',
        NULL,
        NULL,
        'Nutmeg, Lemon, Carnation and Neroli',
        'Teak Wood, Rose, Incense, Atlas Cedar and Patchouli',
        'Cedar, Sandalwood, Musk and Amber',
        'woody,rose,fresh spicy,floral,warm spicy',
        'MMbyMolinardis a Woody fragrance for men.MMwas launched in 2004. Top notes are Nutmeg, Lemon, Carnation and Neroli; middle notes are Teak Wood, Rose, Incense, Atlas Cedar and Patchouli; base notes are Cedar, Sandalwood, Musk and Amber.',
        4.1,
        10,
        NULL
      ),
(
        'Teck-19369',
        'Teck Molinard',
        'Teck',
        'for men',
        NULL,
        NULL,
        'Bitter Orange, Mint and Lemon',
        'Sandalwood, Cypress and Sage',
        'Vetiver and Patchouli',
        'woody,aromatic,citrus,green,earthy',
        'TeckbyMolinardis a Woody Aromatic fragrance for men.Teckwas launched in 1989. Top notes are Bitter Orange, Mint and Lemon; middle notes are Sandalwood, Cypress and Sage; base notes are Vetiver and Patchouli.',
        4.24,
        41,
        NULL
      ),
(
        'Chypre-d-Orient-4921',
        'Chypre d''Orient Molinard',
        'Chypre',
        'for women',
        NULL,
        NULL,
        'Galbanum, Bergamot, Mandarin Orange, Neroli and Jasmine',
        'Osmanthus, Iris, Jasmine and Rose',
        'Oakmoss, Patchouli, Amber and Musk',
        'citrus,earthy,floral,green,mossy',
        'Chypre d''OrientbyMolinardis a Chypre Floral fragrance for women.Chypre d''Orientwas launched in 2007. Top notes are Galbanum, Bergamot, Mandarin Orange, Neroli and Jasmine; middle notes are Osmanthus, Iris, Jasmine and Rose; base notes are Oakmoss, Patchouli, Amber and Musk.',
        4.11,
        193,
        NULL
      ),
(
        'Patchouli-6252',
        'Patchouli Molinard',
        'Patchouli',
        'for women and men',
        NULL,
        NULL,
        'Geranium, Orange and African Orange Flower',
        'Patchouli',
        'Sandalwood, Musk and Vanilla',
        'woody,patchouli,warm spicy,powdery,balsamic',
        'PatchoulibyMolinardis a Amber Woody fragrance for women and men.Patchouliwas launched in 1999. Top notes are Geranium, Orange and African Orange Flower; middle note is Patchouli; base notes are Sandalwood, Musk and Vanilla.',
        4.03,
        145,
        NULL
      ),
(
        'Vanille-6253',
        'Vanille Molinard',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Vanilla',
        'Vanilla',
        'Heliotrope and Vanilla',
        'vanilla,powdery,almond',
        'VanillebyMolinardis a Amber Vanilla fragrance for women.Vanillewas launched in 1993. Top note is Vanilla; middle note is Vanilla; base notes are Heliotrope and Vanilla.',
        4.03,
        219,
        NULL
      ),
(
        'Vanille-Fraicheur-6254',
        'Vanille Fraicheur Molinard',
        'Vanille',
        'for women',
        NULL,
        NULL,
        'Vanilla and Caramel',
        'Mint and Mandarin Orange',
        'Black Currant, Raspberry and Jasmine',
        'vanilla,green,aromatic,sweet,caramel',
        'Vanille FraicheurbyMolinardis a Amber Vanilla fragrance for women.Vanille Fraicheurwas launched in 1998. Top notes are Vanilla and Caramel; middle notes are Mint and Mandarin Orange; base notes are Black Currant, Raspberry and Jasmine.',
        3.78,
        18,
        NULL
      ),
(
        'Vanille-Marine-6256',
        'Vanille Marine Molinard',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        'Vanilla, Caramel and Clary Sage',
        'Juniper, Jasmine and Lily-of-the-Valley',
        'Sea Notes, Amber and Moss',
        'vanilla,aromatic,caramel,marine,sweet',
        'Vanille MarinebyMolinardis a Amber Fougere fragrance for women and men.Vanille Marinewas launched in 1998. Top notes are Vanilla, Caramel and Clary Sage; middle notes are Juniper, Jasmine and Lily-of-the-Valley; base notes are Sea Notes, Amber and Moss.',
        4.25,
        331,
        NULL
      ),
(
        'Chypre-Charnel-32714',
        'Chypre Charnel Molinard',
        'Chypre',
        'for women',
        NULL,
        NULL,
        'Peach, Bergamot, Orange and Lemon',
        'Bulgarian Rose, Iris Flower, Jasmine and White Flowers',
        'Oakmoss, Patchouli, Vetiver, Musk, Ambroxan, Benzoin and Vanilla',
        'earthy,citrus,woody,mossy,rose',
        'Chypre CharnelbyMolinardis a Chypre Floral fragrance for women.Chypre Charnelwas launched in 2015. Top notes are Peach, Bergamot, Orange and Lemon; middle notes are Bulgarian Rose, Iris Flower, Jasmine and White Flowers; base notes are Oakmoss, Patchouli, Vetiver, Musk, Ambroxan, Benzoin and Vanilla.',
        3.99,
        251,
        NULL
      ),
(
        'Heliotrope-37894',
        'Héliotrope Molinard',
        'Héliotrope',
        'for women and men',
        NULL,
        NULL,
        'Heliotrope, Ylang-Ylang, Bergamot and Neroli',
        'Heliotrope, Iris, Rose and Jasmine',
        'Musk and Tonka Bean',
        'powdery,vanilla,musky,citrus,floral',
        'HéliotropebyMolinardis a Floral fragrance for women and men.Héliotropewas launched in 2015. Top notes are Heliotrope, Ylang-Ylang, Bergamot and Neroli; middle notes are Heliotrope, Iris, Rose and Jasmine; base notes are Musk and Tonka Bean.',
        3.66,
        105,
        NULL
      ),
(
        'Oud-Magnetique-46664',
        'Oud Magnetique Molinard',
        'Oud',
        'for women and men',
        NULL,
        NULL,
        'Saffron, Bergamot, Nutmeg and Lemon',
        'Rose, Violet, Ylang-Ylang and Palisander Rosewood',
        'Agarwood (Oud), Leather, Amber and Vetiver',
        'woody,oud,leather,fresh spicy,amber',
        'Oud MagnetiquebyMolinardis a Woody fragrance for women and men.Oud Magnetiquewas launched in 2017. Top notes are Saffron, Bergamot, Nutmeg and Lemon; middle notes are Rose, Violet, Ylang-Ylang and Palisander Rosewood; base notes are Agarwood (Oud), Leather, Amber and Vetiver.',
        4.24,
        82,
        NULL
      ),
(
        'Patchouli-Intense-31839',
        'Patchouli Intense Molinard',
        'Patchouli',
        'for women',
        NULL,
        NULL,
        'Praline, Neroli and Jasmine',
        'Patchouli, Cashmeran and Tonka Bean',
        'Patchouli, Sandalwood and White Musk',
        'woody,patchouli,sweet,warm spicy,musky',
        'Patchouli IntensebyMolinardis a Amber Woody fragrance for women.Patchouli Intensewas launched in 2015. Top notes are Praline, Neroli and Jasmine; middle notes are Patchouli, Cashmeran and Tonka Bean; base notes are Patchouli, Sandalwood and White Musk.',
        4.17,
        226,
        NULL
      ),
(
        'Rose-Turkia-37893',
        'Rose Turkia Molinard',
        'Rose',
        'for women and men',
        NULL,
        NULL,
        'Red Rose',
        'Spices, Geranium and Precious Woods',
        'Honey and Musk',
        'rose,honey,floral,fresh spicy,warm spicy',
        'Rose TurkiabyMolinardis a Amber Floral fragrance for women and men.Rose Turkiawas launched in 2015. Top note is Red Rose; middle notes are Spices, Geranium and Precious Woods; base notes are Honey and Musk.',
        3.76,
        105,
        NULL
      ),
(
        'Tubereuse-Vertigineuse-32715',
        'Tubéreuse Vertigineuse Molinard',
        'Tubéreuse',
        'for women',
        NULL,
        NULL,
        'Peach Blossom and Coconut Blossom',
        'Tuberose, Jasmine and Rose Petals',
        'Amberwood, Sandalwood, White Musk and Cedar',
        'white floral,woody,tuberose,floral,amber',
        'Tubéreuse VertigineusebyMolinardis a Amber Floral fragrance for women.Tubéreuse Vertigineusewas launched in 2015. Top notes are Peach Blossom and Coconut Blossom; middle notes are Tuberose, Jasmine and Rose Petals; base notes are Amberwood, Sandalwood, White Musk and Cedar.',
        4.07,
        382,
        NULL
      ),
(
        'Molinard-de-Molinard-3933',
        'Molinard de Molinard Molinard',
        'Molinard',
        'for women',
        NULL,
        NULL,
        'Green Notes, Asafoetida, Black Currant, Cassis, Fruity Notes, Lemon and Bergamot',
        'Narcissus, Lily-of-the-Valley, Jasmine, Ylang-Ylang and Bulgarian Rose',
        'Vetiver, Labdanum, Incense, Musk, Amber and Patchouli',
        'green,fruity,aromatic,woody,yellow floral',
        'Molinard de MolinardbyMolinardis a Floral Fruity fragrance for women.Molinard de Molinardwas launched in 1979. Top notes are Green Notes, Asafoetida, Black Currant, Cassis, Fruity Notes, Lemon and Bergamot; middle notes are Narcissus, Lily-of-the-Valley, Jasmine, Ylang-Ylang and Bulgarian Rose; base notes are Vetiver, Labdanum, Incense, Musk, Amber and Patchouli.',
        3.96,
        495,
        NULL
      ),
(
        'Molinard-de-Molinard-47547',
        'Molinard de Molinard Molinard',
        'Molinard',
        'for women',
        NULL,
        NULL,
        'Galbanum, Tagetes, Fruity Notes, Cassis, Bergamot and Labdanum',
        'Narcissus, Ylang-Ylang, Incense, Jasmine and May Rose',
        'Vetiver, Patchouli and Amber',
        'aromatic,green,balsamic,yellow floral,woody',
        'Molinard de MolinardbyMolinardis a Floral Green fragrance for women.Molinard de Molinardwas launched in 2017. Top notes are Galbanum, Tagetes, Fruity Notes, Cassis, Bergamot and Labdanum; middle notes are Narcissus, Ylang-Ylang, Incense, Jasmine and May Rose; base notes are Vetiver, Patchouli and Amber.',
        3.9,
        198,
        NULL
      ),
(
        'Le-Reve-Nirmala-43334',
        'Le Rêve Nirmala Molinard',
        'Le',
        'for women',
        NULL,
        'Mathieu Nardin',
        'Candied Almond, Peach, Mandarin Orange, Magnolia and Bergamot',
        'Exotic Fruits, Orchid, Violet and Rose',
        'Chocolate, Vanilla, Praline, Patchouli and Sandalwood',
        'sweet,fruity,floral,powdery,warm spicy',
        'Le Rêve NirmalabyMolinardis a Floral Fruity Gourmand fragrance for women.Le Rêve Nirmalawas launched in 2017. The nose behind this fragrance is Mathieu Nardin. Top notes are Candied Almond, Peach, Mandarin Orange, Magnolia and Bergamot; middle notes are Exotic Fruits, Orchid, Violet and Rose; base notes are Chocolate, Vanilla, Praline, Patchouli and Sandalwood.',
        3.91,
        221,
        NULL
      ),
(
        'Nirmala-6228',
        'Nirmala Molinard',
        'Nirmala',
        'for women',
        NULL,
        NULL,
        'Mango, Passionfruit, Pomelo, Grapefruit and Mandarin Orange',
        'Exotic floral notes and Jasmine',
        'Vanilla, Tonka Bean, Musk, Sandalwood and Virginia Cedar',
        'tropical,sweet,fruity,citrus,vanilla',
        'NirmalabyMolinardis a Amber Woody fragrance for women.Nirmalawas launched in 1955. Top notes are Mango, Passionfruit, Pomelo, Grapefruit and Mandarin Orange; middle notes are Exotic floral notes and Jasmine; base notes are Vanilla, Tonka Bean, Musk, Sandalwood and Virginia Cedar.',
        4,
        467,
        NULL
      ),
(
        'Nirmala-43470',
        'Nirmala Molinard',
        'Nirmala',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Mandarin Orange and Grapefruit',
        'Mango, Hibiscus and Jasmine',
        'Vanilla, Tonka Bean, Sandalwood and Cedar',
        'tropical,fruity,sweet,vanilla,citrus',
        'NirmalabyMolinardis a Amber Floral fragrance for women.Nirmalawas launched in 2017. Top notes are Passionfruit, Mandarin Orange and Grapefruit; middle notes are Mango, Hibiscus and Jasmine; base notes are Vanilla, Tonka Bean, Sandalwood and Cedar.',
        3.86,
        680,
        NULL
      ),
(
        'Nirmala-Baccarat-Edition-2015-30955',
        'Nirmala Baccarat Edition 2015 Molinard',
        'Nirmala',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Mango, Pomelo, Grapefruit and Mandarin Orange',
        'Jasmine and Flowers',
        'Vanilla, Tonka Bean, Sandalwood, Musk and Cedar',
        'citrus,sweet,tropical,fruity,vanilla',
        'Nirmala Baccarat Edition 2015byMolinardis a Amber Floral fragrance for women.Nirmala Baccarat Edition 2015was launched in 2015. Top notes are Passionfruit, Mango, Pomelo, Grapefruit and Mandarin Orange; middle notes are Jasmine and Flowers; base notes are Vanilla, Tonka Bean, Sandalwood, Musk and Cedar.',
        4.39,
        36,
        NULL
      ),
(
        'Nirmala-Limited-Edition-16239',
        'Nirmala Limited Edition Molinard',
        'Nirmala',
        'for women',
        NULL,
        NULL,
        'Passionfruit, Grapefruit and Mandarin Orange',
        'Jasmine and Strelitzia',
        'Vanilla, Tonka Bean, Sandalwood and Cedar',
        'vanilla,tropical,citrus,sweet,fruity',
        'Nirmala Limited EditionbyMolinardis a Floral Fruity fragrance for women.Nirmala Limited Editionwas launched in 2011. Top notes are Passionfruit, Grapefruit and Mandarin Orange; middle notes are Jasmine and Strelitzia; base notes are Vanilla, Tonka Bean, Sandalwood and Cedar.',
        4.17,
        103,
        NULL
      ),
(
        'Black-Pepper-951',
        'Black Pepper Molton Brown',
        'Black',
        'for men',
        NULL,
        NULL,
        'Bergamot and Caraway',
        'Coriander, Violet Leaf and Ginger',
        'Patchouli and Oakmoss',
        'aromatic,citrus,earthy,warm spicy,patchouli',
        'Black PepperbyMolton Brownis a Woody Spicy fragrance for men.Black Pepperwas launched in 2007. Top notes are Bergamot and Caraway; middle notes are Coriander, Violet Leaf and Ginger; base notes are Patchouli and Oakmoss.',
        3.89,
        95,
        NULL
      ),
(
        'Bracing-Silverbirch-8892',
        'Bracing Silverbirch Molton Brown',
        'Bracing',
        'for men',
        NULL,
        NULL,
        'Nutmeg, Cardamom, Bergamot and Lemon',
        'Caraway and Jasmine',
        'Vetiver, Cedar and Incense',
        'woody,aromatic,fresh spicy,warm spicy,amber',
        'Bracing SilverbirchbyMolton Brownis a Woody Aromatic fragrance for men. Top notes are Nutmeg, Cardamom, Bergamot and Lemon; middle notes are Caraway and Jasmine; base notes are Vetiver, Cedar and Incense.',
        4.19,
        26,
        NULL
      ),
(
        'Caju-Lime-25480',
        'Caju & Lime Molton Brown',
        'Caju',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,green,fresh spicy,woody',
        'Caju & LimebyMolton Brownis a Citrus Aromatic fragrance for women and men.Caju & Limewas launched in 2014.',
        3.76,
        17,
        NULL
      ),
(
        'Celestial-Maracuja-9555',
        'Celestial Maracuja Molton Brown',
        'Celestial',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,yellow floral,sweet,woody',
        'Celestial MaracujabyMolton Brownis a Floral fragrance for women.',
        3.77,
        13,
        NULL
      ),
(
        'Cool-Buchu-952',
        'Cool Buchu Molton Brown',
        'Cool',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,aromatic,citrus,green,woody',
        'Cool BuchubyMolton Brownis a Aromatic Spicy fragrance for men.Cool Buchuwas launched in 2007.',
        3.68,
        25,
        NULL
      ),
(
        'Dark-Leather-Eau-de-Parfum-79590',
        'Dark Leather Eau de Parfum Molton Brown',
        'Dark',
        'for women and men',
        NULL,
        'Sylvie Fischer',
        'elemi',
        'Geranium and Lavender',
        'Leather',
        'leather,aromatic,animalic,fresh spicy,lavender',
        'Dark Leather Eau de ParfumbyMolton Brownis a Leather fragrance for women and men. This is a new fragrance.Dark Leather Eau de Parfumwas launched in 2023. The nose behind this fragrance is Sylvie Fischer. Top note is elemi; middle notes are Geranium and Lavender; base note is Leather.',
        3.15,
        13,
        NULL
      ),
(
        'Dark-Leather-Eau-de-Toilette-79591',
        'Dark Leather Eau de Toilette Molton Brown',
        'Dark',
        'for women and men',
        NULL,
        'Sylvie Fischer',
        'Black Tea',
        'Pine',
        'Leather',
        'leather,animalic,woody,smoky,aromatic',
        'Dark Leather Eau de ToilettebyMolton Brownis a Leather fragrance for women and men. This is a new fragrance.Dark Leather Eau de Toilettewas launched in 2023. The nose behind this fragrance is Sylvie Fischer. Top note is Black Tea; middle note is Pine; base note is Leather.',
        2.83,
        12,
        NULL
      ),
(
        'Fresh-Bushukan-Citrus-Splash-19275',
        'Fresh Bushukan Citrus Splash Molton Brown',
        'Fresh',
        'for men',
        NULL,
        NULL,
        'Bergamot, elemi and Clary Sage',
        'Tolu Balsam and Black Pepper',
        'Vetiver, Cedar and Patchouli',
        'aromatic,citrus,woody,fresh spicy,amber',
        'Fresh Bushukan Citrus SplashbyMolton Brownis a Citrus Aromatic fragrance for men. Top notes are Bergamot, elemi and Clary Sage; middle notes are Tolu Balsam and Black Pepper; base notes are Vetiver, Cedar and Patchouli.',
        4.23,
        13,
        NULL
      ),
(
        'Heavenly-Gingerlily-Eau-Fraiche-19276',
        'Heavenly Gingerlily Eau Fraîche Molton Brown',
        'Heavenly',
        'for women',
        NULL,
        NULL,
        'Ginger and Cardamom',
        'Tuberose and Jasmine',
        'Musk and Patchouli',
        'warm spicy,tuberose,white floral,musky,animalic',
        'Heavenly Gingerlily Eau FraîchebyMolton Brownis a Amber Floral fragrance for women. Top notes are Ginger and Cardamom; middle notes are Tuberose and Jasmine; base notes are Musk and Patchouli.',
        3.67,
        12,
        NULL
      ),
(
        'Intoxicating-Davana-Blossom-1690',
        'Intoxicating Davana Blossom Molton Brown',
        'Intoxicating',
        'for women',
        NULL,
        NULL,
        'Artemisia, Neroli and Bergamot',
        'Broom, Laburnum and Orange Blossom',
        'Jasmine and Tolu Balsam',
        'white floral,yellow floral,sweet,citrus,herbal',
        'Intoxicating Davana BlossombyMolton Brownis a Floral Fruity fragrance for women.Intoxicating Davana Blossomwas launched in 2007. Top notes are Artemisia, Neroli and Bergamot; middle notes are Broom, Laburnum and Orange Blossom; base notes are Jasmine and Tolu Balsam.',
        4.29,
        41,
        NULL
      ),
(
        'Paradisiac-Pink-Pepperpod-16873',
        'Paradisiac Pink Pepperpod Molton Brown',
        'Paradisiac',
        'for women',
        NULL,
        NULL,
        'Pink Pepper and Tangerine',
        'African Ginger and Labdanum',
        'Patchouli and Oakmoss',
        'patchouli,warm spicy,soft spicy,woody,citrus',
        'Paradisiac Pink PepperpodbyMolton Brownis a Woody Spicy fragrance for women.Paradisiac Pink Pepperpodwas launched in 2012. Top notes are Pink Pepper and Tangerine; middle notes are African Ginger and Labdanum; base notes are Patchouli and Oakmoss.',
        4.23,
        30,
        NULL
      ),
(
        'Vitalising-Vitamin-AB-C-Eau-Fraiche-19277',
        'Vitalising Vitamin AB+C Eau Fraîche Molton Brown',
        'Vitalising',
        'for women and men',
        NULL,
        NULL,
        'Mandarin Orange, Bitter Orange and Lemon',
        'Lemon Tree, Petitgrain, Fig Leaf and Neroli',
        'Cedar, White Musk and Patchouli',
        'citrus,woody,green,fresh',
        'Vitalising Vitamin AB+C Eau FraîchebyMolton Brownis a Citrus Aromatic fragrance for women and men. Top notes are Mandarin Orange, Bitter Orange and Lemon; middle notes are Lemon Tree, Petitgrain, Fig Leaf and Neroli; base notes are Cedar, White Musk and Patchouli.',
        4,
        9,
        NULL
      ),
(
        'Bushukan-Eau-de-Parfum-57723',
        'Bushukan Eau de Parfum Molton Brown',
        'Bushukan',
        'for women and men',
        NULL,
        'Nathalie Koobus',
        'Citron, Lemon, Bergamot, Pink Pepper and Black Pepper',
        'Hazelnut, Cedar, Clary Sage and Geranium',
        'Vetiver, Musk, Labdanum and Patchouli',
        'citrus,woody,aromatic,nutty',
        'Bushukan Eau de ParfumbyMolton Brownis a Woody Spicy fragrance for women and men.Bushukan Eau de Parfumwas launched in 2019. The nose behind this fragrance is Nathalie Koobus. Top notes are Citron, Lemon, Bergamot, Pink Pepper and Black Pepper; middle notes are Hazelnut, Cedar, Clary Sage and Geranium; base notes are Vetiver, Musk, Labdanum and Patchouli.',
        3.9,
        20,
        NULL
      ),
(
        'Coastal-Cypress-Sea-Fennel-Eau-de-Parfum-57720',
        'Coastal Cypress & Sea Fennel Eau de Parfum Molton Brown',
        'Coastal',
        'for women and men',
        NULL,
        'Carla Chabert',
        'Cardamom, Bergamot, Fig Leaf and Ginger',
        'Cypress, Sea Notes, Olibanum and Jasmine',
        'Leather, Vetiver, Cedar and Musk',
        'aromatic,woody,warm spicy,leather,fresh spicy',
        'Coastal Cypress & Sea Fennel Eau de ParfumbyMolton Brownis a Aromatic Aquatic fragrance for women and men.Coastal Cypress & Sea Fennel Eau de Parfumwas launched in 2019. The nose behind this fragrance is Carla Chabert. Top notes are Cardamom, Bergamot, Fig Leaf and Ginger; middle notes are Cypress, Sea Notes, Olibanum and Jasmine; base notes are Leather, Vetiver, Cedar and Musk.',
        4.17,
        101,
        NULL
      ),
(
        'Delicious-Rhubarb-Rose-Eau-de-Parfum-72465',
        'Delicious Rhubarb & Rose Eau de Parfum Molton Brown',
        'Delicious',
        'for women and men',
        NULL,
        'Vanessa Prudent',
        'Rhubarb, Raspberry, Grapefruit and Litchi',
        'Peony, Rose and Pink Pepper',
        'Musk, Vanilla and Cedar',
        'fruity,rose,floral,sweet,fresh',
        'Delicious Rhubarb & Rose Eau de ParfumbyMolton Brownis a Floral Fruity fragrance for women and men. This is a new fragrance.Delicious Rhubarb & Rose Eau de Parfumwas launched in 2022. The nose behind this fragrance is Vanessa Prudent. Top notes are Rhubarb, Raspberry, Grapefruit and Litchi; middle notes are Peony, Rose and Pink Pepper; base notes are Musk, Vanilla and Cedar.',
        3.95,
        58,
        NULL
      ),
(
        'Fiery-Pink-Pepper-Eau-de-Parfum-57718',
        'Fiery Pink Pepper Eau de Parfum Molton Brown',
        'Fiery',
        'for women and men',
        NULL,
        'Carla Chabert',
        'Pink Pepper, Ginger, Nutmeg and Tangerine',
        'Osmanthus, Lily-of-the-Valley, Jasmine and Labdanum',
        'Musk, Oakmoss, Cedar and Patchouli',
        'soft spicy,musky,warm spicy,citrus,sweet',
        'Fiery Pink Pepper Eau de ParfumbyMolton Brownis a Chypre Floral fragrance for women and men.Fiery Pink Pepper Eau de Parfumwas launched in 2019. The nose behind this fragrance is Carla Chabert. Top notes are Pink Pepper, Ginger, Nutmeg and Tangerine; middle notes are Osmanthus, Lily-of-the-Valley, Jasmine and Labdanum; base notes are Musk, Oakmoss, Cedar and Patchouli.',
        4.04,
        69,
        NULL
      ),
(
        'Flora-Luminare-Eau-de-Parfum-57717',
        'Flora Luminare Eau de Parfum Molton Brown',
        'Flora',
        'for women and men',
        NULL,
        'Maïa Lernout',
        'Bitter Almond, Mandarin Orange, Olibanum and Petitgrain',
        'Jasmine, Ylang-Ylang, Tiare Flower, Neroli and Rose',
        'Mate, Sandalwood, Cedar and Musk',
        'white floral,yellow floral,woody,sweet,citrus',
        'Flora Luminare Eau de ParfumbyMolton Brownis a Floral Woody Musk fragrance for women and men.Flora Luminare Eau de Parfumwas launched in 2019. The nose behind this fragrance is Maïa Lernout. Top notes are Bitter Almond, Mandarin Orange, Olibanum and Petitgrain; middle notes are Jasmine, Ylang-Ylang, Tiare Flower, Neroli and Rose; base notes are Mate, Sandalwood, Cedar and Musk.',
        4.14,
        36,
        NULL
      ),
(
        'Geranium-Nefertum-Eau-de-Parfum-57721',
        'Geranium Nefertum Eau de Parfum Molton Brown',
        'Geranium',
        'for women and men',
        NULL,
        'Carla Chabert',
        'Fig Leaf and Bergamot',
        'Geranium and Jasmine',
        'Sandalwood, Labdanum, Osmanthus, Oakmoss and Cedar',
        'woody,green,fresh,powdery,aromatic',
        'Geranium Nefertum Eau de ParfumbyMolton Brownis a Chypre fragrance for women and men.Geranium Nefertum Eau de Parfumwas launched in 2019. The nose behind this fragrance is Carla Chabert. Top notes are Fig Leaf and Bergamot; middle notes are Geranium and Jasmine; base notes are Sandalwood, Labdanum, Osmanthus, Oakmoss and Cedar.',
        4.35,
        26,
        NULL
      ),
(
        'Jasmine-Sun-Rose-Eau-de-Parfum-59435',
        'Jasmine & Sun Rose Eau de Parfum Molton Brown',
        'Jasmine',
        'for women and men',
        NULL,
        'Julie Pluchet',
        'Raspberry Leaf, Black Currant, Davana and Bergamot',
        'Rose, Jasmine and Labdanum',
        'Patchouli, Musk and Tonka Bean',
        'rose,fruity,musky,patchouli,sweet',
        'Jasmine & Sun Rose Eau de ParfumbyMolton Brownis a Chypre Floral fragrance for women and men.Jasmine & Sun Rose Eau de Parfumwas launched in 2020. The nose behind this fragrance is Julie Pluchet. Top notes are Raspberry Leaf, Black Currant, Davana and Bergamot; middle notes are Rose, Jasmine and Labdanum; base notes are Patchouli, Musk and Tonka Bean.',
        3.88,
        25,
        NULL
      ),
(
        'Labdanum-Dusk-Eau-de-Parfum-68671',
        'Labdanum Dusk Eau de Parfum Molton Brown',
        'Labdanum',
        'for women and men',
        NULL,
        'Nathalie Koobus',
        'Cedar Needles and Saffron',
        'Cedar, Leather and Cypriol Oil or Nagarmotha',
        'Labdanum, Agarwood (Oud), Patchouli, Tonka Bean and Vanilla',
        'woody,amber,leather,warm spicy,vanilla',
        'Labdanum Dusk Eau de ParfumbyMolton Brownis a Amber Woody fragrance for women and men.Labdanum Dusk Eau de Parfumwas launched in 2021. The nose behind this fragrance is Nathalie Koobus. Top notes are Cedar Needles and Saffron; middle notes are Cedar, Leather and Cypriol Oil or Nagarmotha; base notes are Labdanum, Agarwood (Oud), Patchouli, Tonka Bean and Vanilla.',
        4.56,
        41,
        NULL
      ),
(
        'Lily-Magnolia-Blossom-Eau-de-Parfum-68718',
        'Lily & Magnolia Blossom Eau de Parfum Molton Brown',
        'Lily',
        'for women and men',
        NULL,
        NULL,
        'White Tea, Magnolia and Green Mandarin',
        'Peony, Freesia and Lily-of-the-Valley',
        'White Musk, Ylang-Ylang and Sandalwood',
        'floral,fresh,green,citrus,musky',
        'Lily & Magnolia Blossom Eau de ParfumbyMolton Brownis a Floral fragrance for women and men.Lily & Magnolia Blossom Eau de Parfumwas launched in 2021. Top notes are White Tea, Magnolia and Green Mandarin; middle notes are Peony, Freesia and Lily-of-the-Valley; base notes are White Musk, Ylang-Ylang and Sandalwood.',
        4,
        16,
        NULL
      ),
(
        'Mesmerising-Oudh-Accord-Gold-Eau-de-Parfum-57725',
        'Mesmerising Oudh Accord & Gold Eau de Parfum Molton Brown',
        'Mesmerising',
        'for women and men',
        NULL,
        'Philippe Bousseton',
        'Davana, Black Pepper, Cardamom and Bergamot',
        'Saffron, Vanilla, Black Tea and Rose',
        'Tobacco, Agarwood (Oud), Styrax, Olibanum and Honey',
        'amber,tobacco,warm spicy,oud,sweet',
        'Mesmerising Oudh Accord & Gold Eau de ParfumbyMolton Brownis a Amber Woody fragrance for women and men.Mesmerising Oudh Accord & Gold Eau de Parfumwas launched in 2019. The nose behind this fragrance is Philippe Bousseton. Top notes are Davana, Black Pepper, Cardamom and Bergamot; middle notes are Saffron, Vanilla, Black Tea and Rose; base notes are Tobacco, Agarwood (Oud), Styrax, Olibanum and Honey.',
        3.96,
        85,
        NULL
      ),
(
        'Milk-Musk-Eau-de-Parfum-59436',
        'Milk Musk Eau de Parfum Molton Brown',
        'Milk',
        'for women and men',
        NULL,
        NULL,
        'Milk and Elemi resin',
        'Vanilla, Musk and Ambroxan',
        'Tonka Bean and Benzoin',
        'vanilla,amber,lactonic,musky,aromatic',
        'Milk Musk Eau de ParfumbyMolton Brownis a Amber fragrance for women and men.Milk Musk Eau de Parfumwas launched in 2020. Top notes are Milk and Elemi resin; middle notes are Vanilla, Musk and Ambroxan; base notes are Tonka Bean and Benzoin.',
        4.07,
        218,
        NULL
      ),
(
        'Neon-Amber-Eau-de-Parfum-68669',
        'Neon Amber Eau de Parfum Molton Brown',
        'Neon',
        'for women and men',
        NULL,
        'Jérôme di Marino',
        'Pink Pepper, Violet Leaves and Mandarin Orange',
        'Tonka Bean and Cedar Needles',
        'Cedar, Ambroxan and Labdanum',
        'amber,woody,vanilla,musky,sweet',
        'Neon Amber Eau de ParfumbyMolton Brownis a Amber Woody fragrance for women and men.Neon Amber Eau de Parfumwas launched in 2021. The nose behind this fragrance is Jérôme di Marino. Top notes are Pink Pepper, Violet Leaves and Mandarin Orange; middle notes are Tonka Bean and Cedar Needles; base notes are Cedar, Ambroxan and Labdanum.',
        3.9,
        50,
        NULL
      ),
(
        'Orange-Bergamot-Eau-de-Parfum-57727',
        'Orange & Bergamot Eau de Parfum Molton Brown',
        'Orange',
        'for women and men',
        NULL,
        'Beverley Bayne',
        'Petitgrain, Orange, Bergamot, Bitter Orange and Galbanum',
        'Neroli, Ylang-Ylang, Rose and Clove',
        'Musk, Vetiver, Sandalwood and Peru Balsam',
        'citrus,aromatic,fresh spicy,green,woody',
        'Orange & Bergamot Eau de ParfumbyMolton Brownis a Citrus fragrance for women and men.Orange & Bergamot Eau de Parfumwas launched in 2019. The nose behind this fragrance is Beverley Bayne. Top notes are Petitgrain, Orange, Bergamot, Bitter Orange and Galbanum; middle notes are Neroli, Ylang-Ylang, Rose and Clove; base notes are Musk, Vetiver, Sandalwood and Peru Balsam.',
        3.93,
        45,
        NULL
      ),
(
        'Re-charge-Black-Pepper-Eau-de-Parfum-57719',
        'Re-charge Black Pepper Eau de Parfum Molton Brown',
        'Re-charge',
        'for women and men',
        NULL,
        'Jacques Chabert',
        'Lavender, Bergamot, Cardamom and Coriander',
        'Black Pepper, Pink Pepper, Pimento and Amber',
        'Oakmoss, Cedar, Leather and Vetiver',
        'fresh spicy,aromatic,warm spicy,woody,lavender',
        'Re-charge Black Pepper Eau de ParfumbyMolton Brownis a Aromatic Spicy fragrance for women and men.Re-charge Black Pepper Eau de Parfumwas launched in 2019. The nose behind this fragrance is Jacques Chabert. Top notes are Lavender, Bergamot, Cardamom and Coriander; middle notes are Black Pepper, Pink Pepper, Pimento and Amber; base notes are Oakmoss, Cedar, Leather and Vetiver.',
        3.72,
        72,
        NULL
      ),
(
        'Rosa-Absolute-Eau-de-Parfum-57726',
        'Rosa Absolute Eau de Parfum Molton Brown',
        'Rosa',
        'for women and men',
        NULL,
        'Nathalie Koobus',
        'Black Currant, Bergamot and elemi',
        'Rose, Geranium and Violet Leaf',
        'Patchouli, Musk, Coffee, Labdanum and Orris',
        'rose,aromatic,floral,fruity,woody',
        'Rosa Absolute Eau de ParfumbyMolton Brownis a Amber Floral fragrance for women and men.Rosa Absolute Eau de Parfumwas launched in 2019. The nose behind this fragrance is Nathalie Koobus. Top notes are Black Currant, Bergamot and elemi; middle notes are Rose, Geranium and Violet Leaf; base notes are Patchouli, Musk, Coffee, Labdanum and Orris.',
        4.31,
        29,
        NULL
      ),
(
        'Rose-Dunes-73499',
        'Rose Dunes Molton Brown',
        'Rose',
        'for women and men',
        NULL,
        'Philippe Paparella-Paris',
        'Saffron, Violet Leaf, Ginger, Green Pepper, Bergamot and Cassis',
        'Rose, Raspberry, Geranium, Magnolia and Lily-of-the-Valley',
        'Agarwood (Oud), Patchouli, Leather, Musk, Vetiver and Sandalwood',
        'rose,warm spicy,oud,patchouli,woody',
        'Rose DunesbyMolton Brownis a Amber Floral fragrance for women and men. This is a new fragrance.Rose Duneswas launched in 2022. The nose behind this fragrance is Philippe Paparella-Paris. Top notes are Saffron, Violet Leaf, Ginger, Green Pepper, Bergamot and Cassis; middle notes are Rose, Raspberry, Geranium, Magnolia and Lily-of-the-Valley; base notes are Agarwood (Oud), Patchouli, Leather, Musk, Vetiver and Sandalwood.',
        4.26,
        70,
        NULL
      ),
(
        'Russian-Leather-Eau-de-Parfum-57724',
        'Russian Leather Eau de Parfum Molton Brown',
        'Russian',
        'for women and men',
        NULL,
        'Loic Bisceglie',
        'elemi, Bergamot and Black Pepper',
        'Siberian Pine, Birch, Geranium and Lavender',
        'Leather, Cade oil, Vetiver, Vanilla and Amber',
        'aromatic,woody,leather,fresh spicy,smoky',
        'Russian Leather Eau de ParfumbyMolton Brownis a Leather fragrance for women and men.Russian Leather Eau de Parfumwas launched in 2019. The nose behind this fragrance is Loic Bisceglie. Top notes are elemi, Bergamot and Black Pepper; middle notes are Siberian Pine, Birch, Geranium and Lavender; base notes are Leather, Cade oil, Vetiver, Vanilla and Amber.',
        3.89,
        47,
        NULL
      ),
(
        'Suede-Orris-Eau-de-Parfum-59434',
        'Suede Orris Eau de Parfum Molton Brown',
        'Suede',
        'for women and men',
        NULL,
        'Jérôme di Marino',
        'Black Pepper, Mandarin Orange and Olibanum',
        'Tuscan Iris, Rose and Jasmine',
        'Suede, Vanilla, Benzoin and Labdanum',
        'powdery,amber,iris,fresh spicy,leather',
        'Suede Orris Eau de ParfumbyMolton Brownis a Amber Floral fragrance for women and men.Suede Orris Eau de Parfumwas launched in 2020. The nose behind this fragrance is Jérôme di Marino. Top notes are Black Pepper, Mandarin Orange and Olibanum; middle notes are Tuscan Iris, Rose and Jasmine; base notes are Suede, Vanilla, Benzoin and Labdanum.',
        4.1,
        40,
        NULL
      ),
(
        'Sunlit-Clementine-Vetiver-Eau-de-Parfum-91914',
        'Sunlit Clementine & Vetiver Eau de Parfum Molton Brown',
        'Sunlit',
        'for women and men',
        NULL,
        'Julie Massé',
        'Mandarin Orange, Clementine and Lime',
        'Iris, Hazelnut and Fig',
        'Bourbon Vetiver, Moss and Suede',
        'citrus,earthy,woody,aromatic,sweet',
        'Sunlit Clementine & Vetiver Eau de ParfumbyMolton Brownis a fragrance for women and men. This is a new fragrance.Sunlit Clementine & Vetiver Eau de Parfumwas launched in 2024. The nose behind this fragrance is Julie Massé. Top notes are Mandarin Orange, Clementine and Lime; middle notes are Iris, Hazelnut and Fig; base notes are Bourbon Vetiver, Moss and Suede.',
        4.03,
        36,
        NULL
      ),
(
        'Tobacco-Absolute-Eau-de-Parfum-57722',
        'Tobacco Absolute Eau de Parfum Molton Brown',
        'Tobacco',
        'for women and men',
        NULL,
        'Elsa Chabert',
        'Ginger, Bergamot and White Wine',
        'Tobacco, Nutmeg, Orris, Cedar and Violet',
        'Peru Balsam and Patchouli',
        'tobacco,fresh spicy,woody,citrus,powdery',
        'Tobacco Absolute Eau de ParfumbyMolton Brownis a Woody Aromatic fragrance for women and men.Tobacco Absolute Eau de Parfumwas launched in 2019. The nose behind this fragrance is Elsa Chabert. Top notes are Ginger, Bergamot and White Wine; middle notes are Tobacco, Nutmeg, Orris, Cedar and Violet; base notes are Peru Balsam and Patchouli.',
        3.97,
        65,
        NULL
      ),
(
        'Wild-Mint-Lavandin-85351',
        'Wild Mint & Lavandin Molton Brown',
        'Wild',
        'for women and men',
        NULL,
        'Nathalie Koobus',
        'Mint',
        'Nutmeg and Orris Root',
        'Woody Notes and Tonka Bean',
        'fresh spicy,green,aromatic,woody,iris',
        'Wild Mint & LavandinbyMolton Brownis a fragrance for women and men. This is a new fragrance.Wild Mint & Lavandinwas launched in 2023. The nose behind this fragrance is Nathalie Koobus. Top note is Mint; middle notes are Nutmeg and Orris Root; base notes are Woody Notes and Tonka Bean.',
        4,
        38,
        NULL
      ),
(
        'Bizarre-Brandy-57800',
        'Bizarre Brandy Molton Brown',
        'Bizarre',
        'for women and men',
        NULL,
        'Karine Dubreuil-Sereni',
        'Cinnamon, Orange, Ginger and Cardamom',
        'Brandy, Coffee and Maple',
        'Tobacco, Incense and Cedar',
        'woody,warm spicy,tobacco,sweet,coffee',
        'Bizarre BrandybyMolton Brownis a Amber Spicy fragrance for women and men.Bizarre Brandywas launched in 2019. The nose behind this fragrance is Karine Dubreuil-Sereni. Top notes are Cinnamon, Orange, Ginger and Cardamom; middle notes are Brandy, Coffee and Maple; base notes are Tobacco, Incense and Cedar.',
        4.12,
        60,
        NULL
      ),
(
        'Blossoming-Honeysuckle-White-Tea-30153',
        'Blossoming Honeysuckle & White Tea Molton Brown',
        'Blossoming',
        'for women',
        NULL,
        'Shyamala Maisondieu',
        'Bergamot and Mandarin Orange',
        'Honeysuckle, Jasmine and White Tea',
        'Vanilla, Sandalwood and Heliotrope',
        'white floral,vanilla,powdery,citrus,fruity',
        'Blossoming Honeysuckle & White TeabyMolton Brownis a Floral fragrance for women.Blossoming Honeysuckle & White Teawas launched in 2015. The nose behind this fragrance is Shyamala Maisondieu. Top notes are Bergamot and Mandarin Orange; middle notes are Honeysuckle, Jasmine and White Tea; base notes are Vanilla, Sandalwood and Heliotrope.',
        4,
        29,
        NULL
      ),
(
        'Bushukan-36048',
        'Bushukan Molton Brown',
        'Bushukan',
        'for men',
        NULL,
        NULL,
        'Lemon, Bergamot and Basil',
        'Cedar and Thyme',
        'Vetiver, Tolu Balsam and Labdanum',
        'aromatic,citrus,woody,amber,fresh spicy',
        'BushukanbyMolton Brownis a Aromatic Fougere fragrance for men.Bushukanwas launched in 2015. Top notes are Lemon, Bergamot and Basil; middle notes are Cedar and Thyme; base notes are Vetiver, Tolu Balsam and Labdanum.',
        3.98,
        42,
        NULL
      ),
(
        'Coastal-Cypress-Sea-Fennel-45197',
        'Coastal Cypress & Sea Fennel Molton Brown',
        'Coastal',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Fig Leaf and Bergamot',
        'Sea Notes, Violet Leaf and Jasmine',
        'Cypress, Cedar and Musk',
        'aromatic,woody,marine,green,aquatic',
        'Coastal Cypress & Sea FennelbyMolton Brownis a Woody Aromatic fragrance for women and men.Coastal Cypress & Sea Fennelwas launched in 2017. Top notes are Cardamom, Fig Leaf and Bergamot; middle notes are Sea Notes, Violet Leaf and Jasmine; base notes are Cypress, Cedar and Musk.',
        4.05,
        151,
        NULL
      ),
(
        'Delicious-Rhubarb-Rose-72466',
        'Delicious Rhubarb & Rose Molton Brown',
        'Delicious',
        'for women and men',
        NULL,
        'Vanessa Prudent',
        'Yuzu, Grapefruit and Lemongrass',
        'Rhubarb Leaf, Rose and Mint',
        'Cotton Candy, Musk and Vanilla',
        'citrus,green,sweet,aromatic,fresh spicy',
        'Delicious Rhubarb & RosebyMolton Brownis a Floral fragrance for women and men. This is a new fragrance.Delicious Rhubarb & Rosewas launched in 2022. The nose behind this fragrance is Vanessa Prudent. Top notes are Yuzu, Grapefruit and Lemongrass; middle notes are Rhubarb Leaf, Rose and Mint; base notes are Cotton Candy, Musk and Vanilla.',
        3.97,
        37,
        NULL
      ),
(
        'Dewy-Lily-of-the-Valley-Star-Anise-36041',
        'Dewy Lily of the Valley & Star Anise Molton Brown',
        'Dewy',
        'for women',
        NULL,
        NULL,
        'Magnolia, Star Anise and Green Mandarin',
        'White Tea, Lily-of-the-Valley and Peony',
        'Ylang-Ylang, White Musk and Sandalwood',
        'floral,fresh,green,white floral,citrus',
        'Dewy Lily of the Valley & Star AnisebyMolton Brownis a Floral Woody Musk fragrance for women.Dewy Lily of the Valley & Star Anisewas launched in 2016. Top notes are Magnolia, Star Anise and Green Mandarin; middle notes are White Tea, Lily-of-the-Valley and Peony; base notes are Ylang-Ylang, White Musk and Sandalwood.',
        4.27,
        22,
        NULL
      ),
(
        'Fiery-Pink-Pepper-36042',
        'Fiery Pink Pepper Molton Brown',
        'Fiery',
        'for women',
        NULL,
        NULL,
        'Pink Pepper, Tangerine and elemi',
        'Nutmeg and Ginger',
        'Patchouli and Cedar',
        'citrus,woody,warm spicy,soft spicy,patchouli',
        'Fiery Pink PepperbyMolton Brownis a Aromatic Spicy fragrance for women.Fiery Pink Pepperwas launched in 2015. Top notes are Pink Pepper, Tangerine and elemi; middle notes are Nutmeg and Ginger; base notes are Patchouli and Cedar.',
        4.02,
        95,
        NULL
      ),
(
        'Flora-Luminare-57803',
        'Flora Luminare Molton Brown',
        'Flora',
        'for women and men',
        NULL,
        NULL,
        'Orange Blossom, Ylang-Ylang and Mandarin Orange',
        'Frangipani, Jasmine and Rose',
        'Musk, Vanilla and Cedar',
        'white floral,citrus,floral,yellow floral,sweet',
        'Flora LuminarebyMolton Brownis a Woody Floral Musk fragrance for women and men.Flora Luminarewas launched in 2019. Top notes are Orange Blossom, Ylang-Ylang and Mandarin Orange; middle notes are Frangipani, Jasmine and Rose; base notes are Musk, Vanilla and Cedar.',
        3.88,
        88,
        NULL
      ),
(
        'Geranium-Nefertum-57802',
        'Geranium Nefertum Molton Brown',
        'Geranium',
        'for women and men',
        NULL,
        NULL,
        'Fig Leaf and Bergamot',
        'Geranium and Jasmine',
        'Sandalwood, Labdanum and oak moss',
        'woody,green,fresh,fresh spicy,aromatic',
        'Geranium NefertumbyMolton Brownis a Woody Aromatic fragrance for women and men.Geranium Nefertumwas launched in 2019. Top notes are Fig Leaf and Bergamot; middle notes are Geranium and Jasmine; base notes are Sandalwood, Labdanum and oak moss.',
        4.13,
        52,
        NULL
      );
