
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Pure-Cali-39488',
        'Pure Cali Hollister',
        'Pure',
        'for women',
        NULL,
        NULL,
        'Pineapple',
        'Water Lily',
        'Cedar',
        'fruity,sweet,fresh,floral,woody',
        'Pure CalibyHollisteris a Floral Fruity fragrance for women. Top note is Pineapple; middle note is Water Lily; base note is Cedar.',
        4.03,
        40,
        NULL
      ),
(
        'Ryder-4311',
        'Ryder Hollister',
        'Ryder',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'RyderbyHollisteris a Floral Aquatic fragrance for women.',
        4.25,
        53,
        NULL
      ),
(
        'Sadie-15593',
        'Sadie Hollister',
        'Sadie',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh,floral,fruity,sweet,herbal',
        'SadiebyHollisteris a Floral Fruity fragrance for women.Sadiewas launched in 2011.',
        4.02,
        42,
        NULL
      ),
(
        'Skyler-39489',
        'Skyler Hollister',
        'Skyler',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,aquatic,floral,sweet,ozonic',
        'SkylerbyHollisteris a Floral Fruity fragrance for women.',
        4.5,
        6,
        NULL
      ),
(
        'Socal-4307',
        'Socal Hollister',
        'Socal',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'SocalbyHollisteris a Floral Fruity fragrance for women.',
        4,
        90,
        NULL
      ),
(
        'SoCal-Eau-de-Parfum-70474',
        'SoCal Eau de Parfum Hollister',
        'SoCal',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,floral,fruity,sweet',
        'SoCal Eau de ParfumbyHollisteris a Floral Fruity fragrance for women.SoCal Eau de Parfumwas launched in 2021.',
        3.75,
        20,
        NULL
      ),
(
        'Socal-for-Men-4308',
        'Socal for Men Hollister',
        'Socal',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'Socal for MenbyHollisteris a Amber Fougere fragrance for men.',
        4.25,
        520,
        NULL
      ),
(
        'Sol-Dreamer-44591',
        'Sol Dreamer Hollister',
        'Sol',
        'for women',
        NULL,
        NULL,
        'Passionfruit',
        'Jasmine',
        'Woody Notes',
        'tropical,fruity,white floral,sweet,fresh',
        'Sol DreamerbyHollisteris a Floral Fruity fragrance for women.Sol Dreamerwas launched in 2016. Top note is Passionfruit; middle note is Jasmine; base note is Woody Notes.',
        4,
        5,
        NULL
      ),
(
        'Wild-Chase-39483',
        'Wild Chase Hollister',
        'Wild',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet',
        'Wild ChasebyHollisteris a Aromatic Fruity fragrance for women.',
        3.78,
        9,
        NULL
      ),
(
        'Windswept-39485',
        'Windswept Hollister',
        'Windswept',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,musky,aquatic,fresh,powdery',
        'WindsweptbyHollisteris a Floral fragrance for women.',
        4,
        4,
        NULL
      ),
(
        'Addison-26608',
        'Addison Hollister',
        'Addison',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,fresh,musky,powdery',
        'AddisonbyHollisteris a Floral Fruity fragrance for women.Addisonwas launched in 2014.',
        4.26,
        31,
        NULL
      ),
(
        'Addison-Sunrise-26609',
        'Addison Sunrise Hollister',
        'Addison',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,white floral,tropical,woody',
        'Addison SunrisebyHollisteris a Floral Woody Musk fragrance for women.Addison Sunrisewas launched in 2014.',
        3.88,
        17,
        NULL
      ),
(
        'Hollister-Canyon-Escape-Man-61696',
        'Hollister Canyon Escape Man Hollister',
        'Hollister',
        'for men',
        NULL,
        NULL,
        'Bergamot, Black Pepper and Cardamom',
        'Vetiver, Juniper, Sage and Green Notes',
        'Patchouli, Amber and Oakmoss',
        'aromatic,fresh spicy,woody,citrus,warm spicy',
        'Hollister Canyon Escape ManbyHollisteris a Woody Spicy fragrance for men.Hollister Canyon Escape Manwas launched in 2020. Top notes are Bergamot, Black Pepper and Cardamom; middle notes are Vetiver, Juniper, Sage and Green Notes; base notes are Patchouli, Amber and Oakmoss.',
        3.77,
        124,
        NULL
      ),
(
        'Hollister-Canyon-Escape-Woman-61695',
        'Hollister Canyon Escape Woman Hollister',
        'Hollister',
        'for women',
        NULL,
        'Dominique Preyssas',
        'Mandarin Orange, Blood Orange and Cactus Juice',
        'Orange Blossom, Desert Rose, Solar Notes and Iris',
        'Musk, Sandalwood and Cedar',
        'citrus,white floral,floral,woody,powdery',
        'Hollister Canyon Escape WomanbyHollisteris a Floral Woody Musk fragrance for women.Hollister Canyon Escape Womanwas launched in 2020. The nose behind this fragrance is Dominique Preyssas. Top notes are Mandarin Orange, Blood Orange and Cactus Juice; middle notes are Orange Blossom, Desert Rose, Solar Notes and Iris; base notes are Musk, Sandalwood and Cedar.',
        4.04,
        195,
        NULL
      ),
(
        'Canyon-Rush-For-Her-92474',
        'Canyon Rush For Her Hollister',
        'Canyon',
        'for women',
        NULL,
        NULL,
        'Pear, Rhubarb, Apple, Peach and Bergamot',
        'Freesia, Violet and Jasmine',
        'Ambergris and Cedar',
        'fruity,green,sweet,floral,fresh',
        'Canyon Rush For HerbyHollisteris a Floral Fruity fragrance for women.Canyon Rush For Herwas launched in 2022. Top notes are Pear, Rhubarb, Apple, Peach and Bergamot; middle notes are Freesia, Violet and Jasmine; base notes are Ambergris and Cedar.',
        4.17,
        18,
        NULL
      ),
(
        'Canyon-Rush-For-Him-92475',
        'Canyon Rush For Him Hollister',
        'Canyon',
        'for men',
        NULL,
        NULL,
        'Black Pepper, Watermelon and Violet',
        'Geranium, Lavender, Magnolia and Bourbon Whiskey',
        'Ambergris, Patchouli and Cedar',
        'fresh spicy,amber,aromatic,warm spicy,ozonic',
        'Canyon Rush For HimbyHollisteris a Aromatic Fougere fragrance for men.Canyon Rush For Himwas launched in 2022. Top notes are Black Pepper, Watermelon and Violet; middle notes are Geranium, Lavender, Magnolia and Bourbon Whiskey; base notes are Ambergris, Patchouli and Cedar.',
        3.64,
        11,
        NULL
      ),
(
        'Canyon-Sky-For-Her-80094',
        'Canyon Sky For Her Hollister',
        'Canyon',
        'for women',
        NULL,
        'Linda Chinery',
        'Bergamot, Red Currant and Raspberry',
        'Peony, Orange Blossom and Heliotrope',
        'Praline, Musk and Sandalwood',
        'sweet,fruity,citrus,powdery,fresh',
        'Canyon Sky For HerbyHollisteris a fragrance for women. This is a new fragrance.Canyon Sky For Herwas launched in 2023. The nose behind this fragrance is Linda Chinery. Top notes are Bergamot, Red Currant and Raspberry; middle notes are Peony, Orange Blossom and Heliotrope; base notes are Praline, Musk and Sandalwood.',
        3.62,
        47,
        NULL
      ),
(
        'Canyon-Sky-For-Him-80095',
        'Canyon Sky For Him Hollister',
        'Canyon',
        'for men',
        NULL,
        'Catherine Selig',
        'Blood Orange, Sea Salt and Mandarin Orange',
        'Yuzu, Juniper and Geranium',
        'Sandalwood, Moss and Palo Santo',
        'citrus,fresh spicy,aromatic,woody,salty',
        'Canyon Sky For HimbyHollisteris a fragrance for men. This is a new fragrance.Canyon Sky For Himwas launched in 2023. The nose behind this fragrance is Catherine Selig. Top notes are Blood Orange, Sea Salt and Mandarin Orange; middle notes are Yuzu, Juniper and Geranium; base notes are Sandalwood, Moss and Palo Santo.',
        3.73,
        40,
        NULL
      ),
(
        'Festival-Nite-For-Her-54062',
        'Festival Nite For Her Hollister',
        'Festival',
        'for women',
        NULL,
        NULL,
        'Coconut, Mandarin Orange and Pink Freesia',
        'Black Currant, Orchid and Apple Blossom',
        'Marshmallow, Vanilla and Amber',
        'sweet,vanilla,fruity,powdery,coconut',
        'Festival Nite For HerbyHollisteris a Floral Fruity fragrance for women.Festival Nite For Herwas launched in 2019. Top notes are Coconut, Mandarin Orange and Pink Freesia; middle notes are Black Currant, Orchid and Apple Blossom; base notes are Marshmallow, Vanilla and Amber.',
        4.02,
        257,
        NULL
      ),
(
        'Festival-Nite-For-Him-54061',
        'Festival Nite For Him Hollister',
        'Festival',
        'for men',
        NULL,
        NULL,
        'Apple, Bergamot and Mandarin Leaf',
        'Ambroxan, Black Pepper and Ginger',
        'Tonka Bean, Sandalwood and Musk',
        'amber,fresh spicy,warm spicy,citrus,musky',
        'Festival Nite For HimbyHollisteris a Amber Fougere fragrance for men.Festival Nite For Himwas launched in 2019. Top notes are Apple, Bergamot and Mandarin Leaf; middle notes are Ambroxan, Black Pepper and Ginger; base notes are Tonka Bean, Sandalwood and Musk.',
        4.04,
        174,
        NULL
      ),
(
        'Festival-Party-Pour-Elle-59240',
        'Festival Party Pour Elle Hollister',
        'Festival',
        'for women',
        NULL,
        NULL,
        'Citron, Bergamot and Pink Pepper',
        'Magnolia and Rose',
        'White Amber, Bamboo and Musk',
        'citrus,floral,amber,rose,musky',
        'Festival Party Pour EllebyHollisteris a Floral Fruity fragrance for women.Festival Party Pour Ellewas launched in 2020. Top notes are Citron, Bergamot and Pink Pepper; middle notes are Magnolia and Rose; base notes are White Amber, Bamboo and Musk.',
        4.15,
        20,
        NULL
      ),
(
        'Festival-Party-Pour-Lui-59241',
        'Festival Party Pour Lui Hollister',
        'Festival',
        'for men',
        NULL,
        NULL,
        'Iced Lemon, Lavender and Pepper',
        'Mango, Sea Notes and Water Lily',
        'Guaiac Wood, Amber and Patchouli',
        'aromatic,tropical,marine,fruity,citrus',
        'Festival Party Pour LuibyHollisteris a Aromatic fragrance for men.Festival Party Pour Luiwas launched in 2020. Top notes are Iced Lemon, Lavender and Pepper; middle notes are Mango, Sea Notes and Water Lily; base notes are Guaiac Wood, Amber and Patchouli.',
        3.75,
        20,
        NULL
      ),
(
        'Festival-Vibes-For-Her-50038',
        'Festival Vibes For Her Hollister',
        'Festival',
        'for women',
        NULL,
        'Steve DeMercado',
        'Goji Berries, Quince and Bergamot',
        'Vanilla Orchid, Pink Peony, Osmanthus and Hibiscus',
        'Tonka Bean, Musk and Cashmere Wood',
        'floral,fruity,sweet,musky,fresh',
        'Festival Vibes For HerbyHollisteris a Floral Fruity fragrance for women.Festival Vibes For Herwas launched in 2018. The nose behind this fragrance is Steve DeMercado. Top notes are Goji Berries, Quince and Bergamot; middle notes are Vanilla Orchid, Pink Peony, Osmanthus and Hibiscus; base notes are Tonka Bean, Musk and Cashmere Wood.',
        3.62,
        126,
        NULL
      ),
(
        'Festival-Vibes-for-Him-50039',
        'Festival Vibes for Him Hollister',
        'Festival',
        'for men',
        NULL,
        NULL,
        'Sea Notes, Pineapple and Birch Leaf',
        'Green Notes, Woody Notes, Bay Leaf and Ginger',
        'Ambergris, Oakmoss and Tonka Bean',
        'amber,marine,woody,aromatic,sweet',
        'Festival Vibes for HimbyHollisteris a Aromatic Fougere fragrance for men.Festival Vibes for Himwas launched in 2018. Top notes are Sea Notes, Pineapple and Birch Leaf; middle notes are Green Notes, Woody Notes, Bay Leaf and Ginger; base notes are Ambergris, Oakmoss and Tonka Bean.',
        3.88,
        149,
        NULL
      ),
(
        'Gilly-Hicks-Girl-26612',
        'Gilly Hicks Girl Hollister',
        'Gilly',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,tropical,fresh',
        'Gilly Hicks GirlbyHollisteris a Floral Fruity fragrance for women.Gilly Hicks Girlwas launched in 2014.',
        4.2,
        10,
        NULL
      ),
(
        'Gilly-Hicks-Summer-Party-26611',
        'Gilly Hicks Summer Party Hollister',
        'Gilly',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,floral,fresh,tropical,aquatic',
        'Gilly Hicks Summer PartybyHollisteris a Floral Fruity fragrance for women.Gilly Hicks Summer Partywas launched in 2014.',
        4.25,
        4,
        NULL
      ),
(
        'Coconut-Lime-78101',
        'Coconut + Lime Hollister',
        'Coconut',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'coconut,citrus,sweet,lactonic,tropical',
        'Coconut + LimebyHollisteris a Citrus Aromatic fragrance for women.Coconut + Limewas launched in 2021.',
        3.64,
        11,
        NULL
      ),
(
        'Lemonade-Pink-Pepper-78100',
        'Lemonade + Pink Pepper Hollister',
        'Lemonade',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'soft spicy,citrus,sweet,musky,fresh',
        'Lemonade + Pink PepperbyHollisteris a Citrus fragrance for women.Lemonade + Pink Pepperwas launched in 2021.',
        3.67,
        6,
        NULL
      ),
(
        'Mandarin-Honey-78095',
        'Mandarin + Honey Hollister',
        'Mandarin',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus',
        'Mandarin + HoneybyHollisteris a Aromatic Fruity fragrance for women.Mandarin + Honeywas launched in 2021.',
        3.71,
        7,
        NULL
      ),
(
        'Mango-Hibiscus-78097',
        'Mango + Hibiscus Hollister',
        'Mango',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'tropical,fruity,sweet,floral,terpenic',
        'Mango + HibiscusbyHollisteris a Aromatic Fruity fragrance for women.Mango + Hibiscuswas launched in 2021.',
        4.11,
        9,
        NULL
      ),
(
        'Raspberry-Agave-78098',
        'Raspberry + Agave Hollister',
        'Raspberry',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,green,rose',
        'Raspberry + AgavebyHollisteris a Aromatic Fruity fragrance for women.Raspberry + Agavewas launched in 2021.',
        3.7,
        10,
        NULL
      ),
(
        'Strawberry-Acai-78096',
        'Strawberry + Acai Hollister',
        'Strawberry',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet',
        'Strawberry + AcaibyHollisteris a Floral Fruity fragrance for women.Strawberry + Acaiwas launched in 2021.',
        4.29,
        17,
        NULL
      ),
(
        'Watermelon-Mint-78099',
        'Watermelon + Mint Hollister',
        'Watermelon',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'ozonic,aquatic,green,aromatic',
        'Watermelon + MintbyHollisteris a Citrus Aromatic fragrance for women.Watermelon + Mintwas launched in 2021.',
        3.88,
        8,
        NULL
      ),
(
        'Free-Wave-For-Her-50776',
        'Free Wave For Her Hollister',
        'Free',
        'for women',
        NULL,
        'Gino Percontino',
        'Blackberry, Mandarin Orange and Agave nectar',
        'Water Lily, Apple Blossom and Orchid',
        'Ambroxan, Moss and Patchouli',
        'fruity,floral,sweet,citrus,fresh',
        'Free Wave For HerbyHollisteris a Chypre Fruity fragrance for women.Free Wave For Herwas launched in 2018. The nose behind this fragrance is Gino Percontino. Top notes are Blackberry, Mandarin Orange and Agave nectar; middle notes are Water Lily, Apple Blossom and Orchid; base notes are Ambroxan, Moss and Patchouli.',
        4.02,
        120,
        NULL
      ),
(
        'Free-Wave-For-Him-50778',
        'Free Wave For Him Hollister',
        'Free',
        'for men',
        NULL,
        'Gino Percontino',
        'Ginger, Lime and Pink Pepper',
        'Algae, White Iris and Moss',
        'Driftwood, Ambergris and Cedar',
        'woody,citrus,marine,warm spicy,iris',
        'Free Wave For HimbyHollisteris a Woody Spicy fragrance for men.Free Wave For Himwas launched in 2018. The nose behind this fragrance is Gino Percontino. Top notes are Ginger, Lime and Pink Pepper; middle notes are Algae, White Iris and Moss; base notes are Driftwood, Ambergris and Cedar.',
        3.88,
        125,
        NULL
      ),
(
        'Hollister-Wave-For-Her-38892',
        'Hollister Wave For Her Hollister',
        'Hollister',
        'for women',
        NULL,
        NULL,
        'Carambola (Star Fruit), Quince and Cassis',
        'Hibiscus, Orchid and Poppy',
        'Solar Notes, Sandalwood and Crystal Amber',
        'fruity,floral,sweet,tropical,fresh',
        'Hollister Wave For HerbyHollisteris a Floral Fruity fragrance for women.Hollister Wave For Herwas launched in 2016. Top notes are Carambola (Star Fruit), Quince and Cassis; middle notes are Hibiscus, Orchid and Poppy; base notes are Solar Notes, Sandalwood and Crystal Amber.',
        3.86,
        378,
        NULL
      ),
(
        'Hollister-Wave-For-Him-38891',
        'Hollister Wave For Him Hollister',
        'Hollister',
        'for men',
        NULL,
        NULL,
        'Yuzu, Bamboo Leaf and Grapefruit',
        'Lavender, Cypress and Neroli',
        'Driftwood, Salt, Musk and Tonka Bean',
        'citrus,woody,aromatic,fresh spicy,lavender',
        'Hollister Wave For HimbyHollisteris a Woody Aromatic fragrance for men.Hollister Wave For Himwas launched in 2016. Top notes are Yuzu, Bamboo Leaf and Grapefruit; middle notes are Lavender, Cypress and Neroli; base notes are Driftwood, Salt, Musk and Tonka Bean.',
        3.92,
        417,
        NULL
      ),
(
        'Hollister-Wave-X-For-Man-76763',
        'Hollister Wave X For Man Hollister',
        'Hollister',
        'for men',
        NULL,
        'Linda Chinery',
        'Watermelon, Grapefruit and Bergamot',
        'Cypress, Sage and Lavender',
        'Ambergris, Musk and Cedar',
        'aromatic,citrus,fresh spicy,amber,ozonic',
        'Hollister Wave X For ManbyHollisteris a fragrance for men. This is a new fragrance.Hollister Wave X For Manwas launched in 2022. The nose behind this fragrance is Linda Chinery. Top notes are Watermelon, Grapefruit and Bergamot; middle notes are Cypress, Sage and Lavender; base notes are Ambergris, Musk and Cedar.',
        3.91,
        33,
        NULL
      ),
(
        'Hollister-Wave-X-For-Woman-76762',
        'Hollister Wave X For Woman Hollister',
        'Hollister',
        'for women',
        NULL,
        'Yves Cassar',
        'Pineapple, Italian Lemon, Pear, Sea Notes and Mineral notes',
        'Plum Tree, Jasmine and Lime (Linden Blossom)',
        'Cedar, Sandalwood, White Amber and Musk',
        'woody,powdery,white floral,fruity',
        'Hollister Wave X For WomanbyHollisteris a fragrance for women. This is a new fragrance.Hollister Wave X For Womanwas launched in 2022. The nose behind this fragrance is Yves Cassar. Top notes are Pineapple, Italian Lemon, Pear, Sea Notes and Mineral notes; middle notes are Plum Tree, Jasmine and Lime (Linden Blossom); base notes are Cedar, Sandalwood, White Amber and Musk.',
        3.75,
        12,
        NULL
      ),
(
        'Wave-2-For-Her-44906',
        'Wave 2 For Her Hollister',
        'Wave',
        'for women',
        NULL,
        NULL,
        'Coconut Nectar, Peach and Mandarin Orange',
        'Tiare Flower, Water Lily and Pink Freesia',
        'Sand, Driftwood and Orchid',
        'sweet,white floral,fruity,coconut,floral',
        'Wave 2 For HerbyHollisteris a Floral Fruity fragrance for women.Wave 2 For Herwas launched in 2017. Top notes are Coconut Nectar, Peach and Mandarin Orange; middle notes are Tiare Flower, Water Lily and Pink Freesia; base notes are Sand, Driftwood and Orchid.',
        3.44,
        283,
        NULL
      ),
(
        'Wave-2-For-Him-44907',
        'Wave 2 For Him Hollister',
        'Wave',
        'for men',
        NULL,
        NULL,
        'Ozonic notes, Bergamot and White Pepper',
        'Lavender, Geranium and Sage',
        'Musk, Sandalwood and Woody Notes',
        'fresh spicy,aromatic,ozonic,woody,herbal',
        'Wave 2 For HimbyHollisteris a Aromatic Fougere fragrance for men.Wave 2 For Himwas launched in 2017. Top notes are Ozonic notes, Bergamot and White Pepper; middle notes are Lavender, Geranium and Sage; base notes are Musk, Sandalwood and Woody Notes.',
        3.83,
        210,
        NULL
      ),
(
        'Belle-de-Luxe-11663',
        'Belle de Luxe Hoity Toity',
        'Belle',
        'for women',
        NULL,
        NULL,
        'Pineapple and Apricot',
        'African Orange Flower and Lily',
        'Woodsy Notes and Musk',
        'white floral,fruity,sweet,musky,woody',
        'Belle de LuxebyHoity Toityis a Floral Fruity fragrance for women.Belle de Luxewas launched in 2004. Top notes are Pineapple and Apricot; middle notes are African Orange Flower and Lily; base notes are Woodsy Notes and Musk.',
        4,
        7,
        NULL
      ),
(
        'Bon-Bon-19956',
        'Bon Bon Hoity Toity',
        'Bon',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,citrus,floral,fresh',
        'Bon BonbyHoity Toityis a Floral Fruity Gourmand fragrance for women.',
        4.4,
        5,
        NULL
      ),
(
        'Cherie-11665',
        'Cherie Hoity Toity',
        'Cherie',
        'for women',
        NULL,
        NULL,
        'Fruity Notes',
        'Floral Notes',
        'Patchouli, Amber and Musk',
        'fruity,patchouli,floral,woody,sweet',
        'CheriebyHoity Toityis a Floral Fruity fragrance for women.Cheriewas launched in 2004. Top note is Fruity Notes; middle note is Floral Notes; base notes are Patchouli, Amber and Musk.',
        4.17,
        6,
        NULL
      ),
(
        'ChouChou-11670',
        'ChouChou! Hoity Toity',
        'ChouChou!',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,rose,powdery',
        'ChouChou!byHoity Toityis a Floral Fruity Gourmand fragrance for women.ChouChou!was launched in 2011.',
        3.57,
        7,
        NULL
      ),
(
        'Hoity-Toity-Original-11662',
        'Hoity Toity (Original) Hoity Toity',
        'Hoity',
        'for women',
        NULL,
        NULL,
        'Fruity Notes',
        'Floral Notes and White Honey',
        'Amber, Vanille and Woodsy Notes',
        'floral,sweet,amber,fruity,honey',
        'Hoity Toity (Original)byHoity Toityis a Floral Fruity fragrance for women.Hoity Toity (Original)was launched in 2004. Top note is Fruity Notes; middle notes are Floral Notes and White Honey; base notes are Amber, Vanille and Woodsy Notes.',
        4.22,
        9,
        NULL
      ),
(
        'La-Di-Da-11667',
        'La Di Da Hoity Toity',
        'La',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,fruity,sweet',
        'La Di DabyHoity Toityis a Floral Fruity fragrance for women.La Di Dawas launched in 2004.',
        NULL,
        NULL,
        NULL
      ),
(
        'La-Purrfect-19957',
        'La Purrfect Hoity Toity',
        'La',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,powdery,floral,vanilla,sweet',
        'La PurrfectbyHoity Toityis a Amber Vanilla fragrance for women.',
        4,
        5,
        NULL
      ),
(
        'Lola-11666',
        'Lola Hoity Toity',
        'Lola',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,fruity,woody,sweet,citrus',
        'LolabyHoity Toityis a Floral Fruity fragrance for women.Lolawas launched in 2004.',
        4.71,
        7,
        NULL
      ),
(
        'Mademoiselle-la-Pussycat-11669',
        'Mademoiselle la Pussycat Hoity Toity',
        'Mademoiselle',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,rose,citrus,patchouli,sweet',
        'Mademoiselle la PussycatbyHoity Toityis a Chypre Floral fragrance for women.Mademoiselle la Pussycatwas launched in 2009.',
        3.14,
        7,
        NULL
      ),
(
        'Miss-Priss-11664',
        'Miss Priss Hoity Toity',
        'Miss',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,amber,soft spicy,fruity,green',
        'Miss PrissbyHoity Toityis a Amber Floral fragrance for women.Miss Prisswas launched in 2004.',
        4.12,
        8,
        NULL
      ),
(
        'Ooh-La-Love-11668',
        'Ooh La Love Hoity Toity',
        'Ooh',
        'for women',
        NULL,
        NULL,
        'Red Apple, African Orange Flower, Orange and Pear',
        'Jasmine, Rose, Lily and Pineapple',
        'Heliotrope, Sandalwood, Amber and Vanille',
        'white floral,fruity,sweet,powdery,vanilla',
        'Ooh La LovebyHoity Toityis a Floral Fruity fragrance for women.Ooh La Lovewas launched in 2010. Top notes are Red Apple, African Orange Flower, Orange and Pear; middle notes are Jasmine, Rose, Lily and Pineapple; base notes are Heliotrope, Sandalwood, Amber and Vanille.',
        3.5,
        2,
        NULL
      ),
(
        '1889-Moulin-Rouge-7816',
        '1889 Moulin Rouge Histoires de Parfums',
        '1889',
        'for women',
        NULL,
        NULL,
        'Plum, Cinnamon and Tangerine',
        'Tincture of Rose and Wormwood',
        'Iris, Musk and Patchouli',
        'iris,powdery,fruity,earthy,rose',
        '1889 Moulin RougebyHistoires de Parfumsis a fragrance for women.1889 Moulin Rougewas launched in 2010. Top notes are Plum, Cinnamon and Tangerine; middle notes are Tincture of Rose and Wormwood; base notes are Iris, Musk and Patchouli.',
        4.05,
        1,
        NULL
      ),
(
        '1969-Parfum-de-Revolte-4492',
        '1969 Parfum de Revolte Histoires de Parfums',
        '1969',
        'for women',
        NULL,
        'Gerald Ghislain',
        'Peach',
        'Cardamom, Clove, Rose and White Flowers',
        'Mexican chocolate, Patchouli, Coffee and Musk',
        'warm spicy,rose,fruity,patchouli,sweet',
        '1969 Parfum de RevoltebyHistoires de Parfumsis a Amber Spicy fragrance for women.1969 Parfum de Revoltewas launched in 2001. The nose behind this fragrance is Gerald Ghislain. Top note is Peach; middle notes are Cardamom, Clove, Rose and White Flowers; base notes are Mexican chocolate, Patchouli, Coffee and Musk.',
        4.01,
        2,
        NULL
      ),
(
        'Ambre-114-4493',
        'Ambre 114 Histoires de Parfums',
        'Ambre',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Nutmeg and Thyme',
        'Patchouli, Sandalwood, Rose, Geranium, Cedar and Vetiver',
        'Amber, Vanilla, Benzoin, Tonka Bean and Musk',
        'amber,vanilla,woody,warm spicy,fresh spicy',
        'Ambre 114byHistoires de Parfumsis a Amber Spicy fragrance for women and men.Ambre 114was launched in 2001. Ambre 114 was created by Gerald Ghislain and Magali Senequier. Top notes are Nutmeg and Thyme; middle notes are Patchouli, Sandalwood, Rose, Geranium, Cedar and Vetiver; base notes are Amber, Vanilla, Benzoin, Tonka Bean and Musk.',
        4.24,
        2,
        NULL
      ),
(
        'Blanc-Violette-8591',
        'Blanc Violette Histoires de Parfums',
        'Blanc',
        'for women',
        NULL,
        NULL,
        'Violet, Iris and Bergamot',
        'Violet, Anise and Ylang-Ylang',
        'Violet, Powdery Notes, Rice, Musk, Sandalwood and Vanille',
        'powdery,violet,woody,iris,musky',
        'Blanc ViolettebyHistoires de Parfumsis a Floral Green fragrance for women.Blanc Violettewas launched during the 2000''s. Top notes are Violet, Iris and Bergamot; middle notes are Violet, Anise and Ylang-Ylang; base notes are Violet, Powdery Notes, Rice, Musk, Sandalwood and Vanille.',
        3.79,
        352,
        NULL
      ),
(
        'Encens-Roi-74821',
        'Encens Roi Histoires de Parfums',
        'Encens',
        'for women and men',
        NULL,
        NULL,
        'Olibanum, Peppertree and Chamomile',
        'Saffron, Atlas Cedar and Pimento',
        'Labdanum, Agarwood (Oud), Cacao and Vanilla',
        'amber,warm spicy,fresh spicy,woody,oud',
        'Encens RoibyHistoires de Parfumsis a Woody Spicy fragrance for women and men. This is a new fragrance.Encens Roiwas launched in 2022. Top notes are Olibanum, Peppertree and Chamomile; middle notes are Saffron, Atlas Cedar and Pimento; base notes are Labdanum, Agarwood (Oud), Cacao and Vanilla.',
        4.19,
        254,
        NULL
      ),
(
        'L-Olympia-Music-Hall-16242',
        'L''Olympia Music Hall Histoires de Parfums',
        'L''Olympia',
        'for women',
        NULL,
        'Gerald Ghislain',
        'Bergamot, Lemon, Mandarin Orange and Orange',
        'Lilac, Black Pepper, Peony, Saffron, Freesia, Rose and Red Berries',
        'Suede, Woody Notes, White Musk, Patchouli, Incense, Dark Chocolate, Licorice and Vanilla',
        'floral,woody,citrus,warm spicy,musky',
        'L''Olympia Music HallbyHistoires de Parfumsis a Amber Woody fragrance for women.L''Olympia Music Hallwas launched in 2012. The nose behind this fragrance is Gerald Ghislain. Top notes are Bergamot, Lemon, Mandarin Orange and Orange; middle notes are Lilac, Black Pepper, Peony, Saffron, Freesia, Rose and Red Berries; base notes are Suede, Woody Notes, White Musk, Patchouli, Incense, Dark Chocolate, Licorice and Vanilla.',
        3.84,
        274,
        NULL
      ),
(
        'Make-Perfume-Not-War-21385',
        'Make Perfume Not War Histoires de Parfums',
        'Make',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Orange, Mandarin Orange, Grapefruit, Lemon and Bergamot',
        'Lilac, Mango, Pineapple, Peach, Freesia and Cyclamen',
        'Tonka Bean, Vanilla, White Musk and White Woods',
        'citrus,sweet,fruity,floral,vanilla',
        'Make Perfume Not WarbyHistoires de Parfumsis a Aromatic Fruity fragrance for women and men.Make Perfume Not Warwas launched in 2013. The nose behind this fragrance is Gerald Ghislain. Top notes are Orange, Mandarin Orange, Grapefruit, Lemon and Bergamot; middle notes are Lilac, Mango, Pineapple, Peach, Freesia and Cyclamen; base notes are Tonka Bean, Vanilla, White Musk and White Woods.',
        3.64,
        36,
        NULL
      ),
(
        'Noir-Patchouli-8593',
        'Noir Patchouli Histoires de Parfums',
        'Noir',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Patchouli, Cardamom and Coriander',
        'Patchouli, Floral Notes and Juniper Berries',
        'Patchouli, Leather, Musk and Vanilla',
        'patchouli,warm spicy,aromatic,woody,leather',
        'Noir PatchoulibyHistoires de Parfumsis a Woody Aromatic fragrance for women and men.Noir Patchouliwas launched during the 2000''s. The nose behind this fragrance is Gérald Ghislain. Top notes are Patchouli, Cardamom and Coriander; middle notes are Patchouli, Floral Notes and Juniper Berries; base notes are Patchouli, Leather, Musk and Vanilla.',
        3.78,
        923,
        NULL
      ),
(
        'Tubereuse-1-La-Capricieuse-7801',
        'Tubereuse 1 La Capricieuse Histoires de Parfums',
        'Tubereuse',
        'for women',
        NULL,
        NULL,
        'Tuberose, Saffron, Bergamot and Sicilian Mandarin',
        'Iris, Tuberose and Ylang-Ylang',
        'Suede, Tuberose and Cacao',
        'iris,powdery,leather,tuberose,white floral',
        'Tubereuse 1 La CapricieusebyHistoires de Parfumsis a Amber Vanilla fragrance for women.Tubereuse 1 La Capricieusewas launched in 2010. Top notes are Tuberose, Saffron, Bergamot and Sicilian Mandarin; middle notes are Iris, Tuberose and Ylang-Ylang; base notes are Suede, Tuberose and Cacao.',
        3.8,
        440,
        NULL
      ),
(
        'Tubereuse-2-Virginale-7802',
        'Tubereuse 2 Virginale Histoires de Parfums',
        'Tubereuse',
        'for women',
        NULL,
        NULL,
        'Tuberose, Cherry and Tangerine',
        'Tuberose, Tiare Flower, Frangipani and Jasmine',
        'Tuberose, Vanille, Patchouli and Woodsy Notes',
        'white floral,tuberose,floral,sweet,cherry',
        'Tubereuse 2 VirginalebyHistoires de Parfumsis a Amber Floral fragrance for women.Tubereuse 2 Virginalewas launched in 2010. Top notes are Tuberose, Cherry and Tangerine; middle notes are Tuberose, Tiare Flower, Frangipani and Jasmine; base notes are Tuberose, Vanille, Patchouli and Woodsy Notes.',
        3.98,
        473,
        NULL
      ),
(
        'Tubereuse-3-Animale-7803',
        'Tubereuse 3 Animale Histoires de Parfums',
        'Tubereuse',
        'for women',
        NULL,
        NULL,
        'Tuberose, Kumquat and Neroli',
        'Tuberose, Plum and Grass',
        'Tuberose, Tobacco, Immortelle and Woodsy Notes',
        'sweet,tobacco,tuberose,white floral,fruity',
        'Tubereuse 3 AnimalebyHistoires de Parfumsis a Floral fragrance for women.Tubereuse 3 Animalewas launched in 2010. Top notes are Tuberose, Kumquat and Neroli; middle notes are Tuberose, Plum and Grass; base notes are Tuberose, Tobacco, Immortelle and Woodsy Notes.',
        4.15,
        857,
        NULL
      ),
(
        'Vert-Pivoine-8592',
        'Vert Pivoine Histoires de Parfums',
        'Vert',
        'for women',
        NULL,
        NULL,
        'Peony, Rose and Ivy',
        'Peony, Rose, Mimosa, Red Berries and Gardenia',
        'Peony, Musk, Virginia Cedar and Sandalwood',
        'floral,fresh,rose,woody,green',
        'Vert PivoinebyHistoires de Parfumsis a Floral fragrance for women. Top notes are Peony, Rose and Ivy; middle notes are Peony, Rose, Mimosa, Red Berries and Gardenia; base notes are Peony, Musk, Virginia Cedar and Sandalwood.',
        3.75,
        287,
        NULL
      ),
(
        '1472-La-Divina-Commedia-71225',
        '1472 La Divina Commedia Histoires de Parfums',
        '1472',
        'for women and men',
        NULL,
        NULL,
        'Ylang-Ylang, Artemisia and Solar Notes',
        'Jasmine, Olibanum and Cinnamon',
        'Rum, Benzoin and Amber',
        'amber,warm spicy,white floral,yellow floral,woody',
        '1472 La Divina CommediabyHistoires de Parfumsis a Floral fragrance for women and men.1472 La Divina Commediawas launched in 2021. Top notes are Ylang-Ylang, Artemisia and Solar Notes; middle notes are Jasmine, Olibanum and Cinnamon; base notes are Rum, Benzoin and Amber.',
        3.77,
        217,
        NULL
      ),
(
        '1725-4491',
        '1725 Histoires de Parfums',
        '1725',
        'for men',
        NULL,
        NULL,
        'Licorice, Citruses, Grapefruit and Bergamot',
        'Lavender and Star Anise',
        'Vanilla, Almond, Sandalwood, Amber and Cedar',
        'soft spicy,lavender,anis,citrus,powdery',
        '1725byHistoires de Parfumsis a Aromatic Fougere fragrance for men.1725was launched in 2001. Top notes are Licorice, Citruses, Grapefruit and Bergamot; middle notes are Lavender and Star Anise; base notes are Vanilla, Almond, Sandalwood, Amber and Cedar.',
        4.15,
        1,
        NULL
      ),
(
        '1740-Marquis-de-Sade-8590',
        '1740 Marquis de Sade Histoires de Parfums',
        '1740',
        'for men',
        NULL,
        NULL,
        'Artemisia and Bergamot',
        'Patchouli, Cardamom and Coriander',
        'Immortelle, Leather, French labdanum, Elemi resin, Birch, Vanilla and Virginia Cedar',
        'leather,herbal,warm spicy,aromatic,woody',
        '1740 Marquis de SadebyHistoires de Parfumsis a Amber Woody fragrance for men.1740 Marquis de Sadewas launched in 2000. Top notes are Artemisia and Bergamot; middle notes are Patchouli, Cardamom and Coriander; base notes are Immortelle, Leather, French labdanum, Elemi resin, Birch, Vanilla and Virginia Cedar.',
        4.21,
        3,
        NULL
      ),
(
        '1804-4486',
        '1804 Histoires de Parfums',
        '1804',
        'for women',
        NULL,
        NULL,
        'Pineapple, Peach and Tiare Flower',
        'Nutmeg, Cloves, Jasmine, Lily-of-the-Valley and Rose',
        'Patchouli, Vanilla, Benzoin, Musk and Sandalwood',
        'fruity,sweet,warm spicy,tropical,woody',
        '1804byHistoires de Parfumsis a Amber Floral fragrance for women.1804was launched in 2001. Top notes are Pineapple, Peach and Tiare Flower; middle notes are Nutmeg, Cloves, Jasmine, Lily-of-the-Valley and Rose; base notes are Patchouli, Vanilla, Benzoin, Musk and Sandalwood.',
        3.69,
        992,
        NULL
      ),
(
        '1826-4487',
        '1826 Histoires de Parfums',
        '1826',
        'for women',
        NULL,
        NULL,
        'Tangerine and Bergamot',
        'Violet, White Flowers, Cinnamon and Ginger',
        'Patchouli, Amber, Woody Notes, Incense, Musk and Vanilla',
        'warm spicy,woody,amber,patchouli,powdery',
        '1826byHistoires de Parfumsis a Amber fragrance for women.1826was launched in 2001. Top notes are Tangerine and Bergamot; middle notes are Violet, White Flowers, Cinnamon and Ginger; base notes are Patchouli, Amber, Woody Notes, Incense, Musk and Vanilla.',
        3.83,
        635,
        NULL
      ),
(
        '1828-4488',
        '1828 Histoires de Parfums',
        '1828',
        'for men',
        NULL,
        NULL,
        'Eucalyptus, Citruses, Grapefruit and Tangerine',
        'Nutmeg and Pepper',
        'Pine Tree, Cedar, Incense and Vetiver',
        'woody,citrus,fresh spicy,aromatic,camphor',
        '1828byHistoires de Parfumsis a Citrus Aromatic fragrance for men.1828was launched in 2001. Top notes are Eucalyptus, Citruses, Grapefruit and Tangerine; middle notes are Nutmeg and Pepper; base notes are Pine Tree, Cedar, Incense and Vetiver.',
        4.13,
        1,
        NULL
      ),
(
        '1873-4489',
        '1873 Histoires de Parfums',
        '1873',
        'for women',
        NULL,
        NULL,
        'Citruses, Grapefruit, Tangerine, Lime, Orange and Bergamot',
        'Orange Blossom, Lavender, Violet, Lily-of-the-Valley and Wildflowers',
        'Caramel, Vanilla and Musk',
        'citrus,sweet,white floral,fresh spicy,fresh',
        '1873byHistoires de Parfumsis a Citrus Gourmand fragrance for women.1873was launched in 2001. Top notes are Citruses, Grapefruit, Tangerine, Lime, Orange and Bergamot; middle notes are Orange Blossom, Lavender, Violet, Lily-of-the-Valley and Wildflowers; base notes are Caramel, Vanilla and Musk.',
        3.77,
        312,
        NULL
      ),
(
        '1876-4490',
        '1876 Histoires de Parfums',
        '1876',
        'for women',
        NULL,
        NULL,
        'Litchi, Orange and Bergamot',
        'Rose, Caraway, Iris, Carnation, Cinnamon and Violet',
        'Guaiac Wood, Vetiver, Sandalwood, Vanilla and Musk',
        'woody,powdery,warm spicy,floral,aromatic',
        '1876byHistoires de Parfumsis a Floral fragrance for women.1876was launched in 2001. Top notes are Litchi, Orange and Bergamot; middle notes are Rose, Caraway, Iris, Carnation, Cinnamon and Violet; base notes are Guaiac Wood, Vetiver, Sandalwood, Vanilla and Musk.',
        3.85,
        679,
        NULL
      ),
(
        '1899-Hemingway-18846',
        '1899 Hemingway Histoires de Parfums',
        '1899',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Juniper, Black Pepper and Bergamot',
        'Cinnamon, Iris and Orange Blossom',
        'Vanilla, Amber and Vetiver',
        'fresh spicy,aromatic,warm spicy,woody,cinnamon',
        '1899 HemingwaybyHistoires de Parfumsis a Amber Spicy fragrance for women and men.1899 Hemingwaywas launched in 2013. The nose behind this fragrance is Gerald Ghislain. Top notes are Juniper, Black Pepper and Bergamot; middle notes are Cinnamon, Iris and Orange Blossom; base notes are Vanilla, Amber and Vetiver.',
        4.29,
        2,
        NULL
      ),
(
        '7753-Unexpected-Mona-58667',
        '7753 Unexpected Mona Histoires de Parfums',
        '7753',
        'for women and men',
        NULL,
        NULL,
        'Ivy, Galbanum, Mandarin Orange, Bergamot and Pepper',
        'Tuberose, Pear, Cassis, Heliotrope and Orange Blossom',
        'Oakmoss, Vetiver, Sandalwood and Patchouli',
        'green,woody,white floral,aromatic,tuberose',
        '7753 Unexpected MonabyHistoires de Parfumsis a Amber Floral fragrance for women and men.7753 Unexpected Monawas launched in 2019. Top notes are Ivy, Galbanum, Mandarin Orange, Bergamot and Pepper; middle notes are Tuberose, Pear, Cassis, Heliotrope and Orange Blossom; base notes are Oakmoss, Vetiver, Sandalwood and Patchouli.',
        3.93,
        416,
        NULL
      ),
(
        'Ambrarem-13184',
        'Ambrarem Histoires de Parfums',
        'Ambrarem',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'elemi and Pink Pepper',
        'Agarwood (Oud), Iris and Saffron',
        'Amber, Castoreum, Vanille and Sandalwood',
        'leather,woody,amber,powdery,oud',
        'AmbrarembyHistoires de Parfumsis a Amber fragrance for women and men.Ambraremwas launched in 2011. The nose behind this fragrance is Gerald Ghislain. Top notes are elemi and Pink Pepper; middle notes are Agarwood (Oud), Iris and Saffron; base notes are Amber, Castoreum, Vanille and Sandalwood.',
        4.04,
        314,
        NULL
      ),
(
        'Fidelis-32290',
        'Fidelis Histoires de Parfums',
        'Fidelis',
        'for women and men',
        NULL,
        'Julien Rasquinet',
        'Coffee, Saffron, Cardamom and Cumin',
        'Raspberry and Rose',
        'Agarwood (Oud), Amber and Patchouli',
        'warm spicy,oud,coffee,fruity,rose',
        'FidelisbyHistoires de Parfumsis a Chypre Floral fragrance for women and men.Fideliswas launched in 2015. The nose behind this fragrance is Julien Rasquinet. Top notes are Coffee, Saffron, Cardamom and Cumin; middle notes are Raspberry and Rose; base notes are Agarwood (Oud), Amber and Patchouli.',
        4.1,
        799,
        NULL
      ),
(
        'Petroleum-13185',
        'Petroleum Histoires de Parfums',
        'Petroleum',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Agarwood (Oud), Aldehydes and Bergamot',
        'Amber and Rose',
        'Civetta, Leather, Patchouli and Musk',
        'animalic,musky,oud,amber,leather',
        'PetroleumbyHistoires de Parfumsis a Aromatic fragrance for women and men.Petroleumwas launched in 2011. The nose behind this fragrance is Gerald Ghislain. Top notes are Agarwood (Oud), Aldehydes and Bergamot; middle notes are Amber and Rose; base notes are Civetta, Leather, Patchouli and Musk.',
        3.91,
        315,
        NULL
      ),
(
        'Rosam-13186',
        'Rosam Histoires de Parfums',
        'Rosam',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Rose and Citruses',
        'Taif Rose, Saffron and Incense',
        'Agarwood (Oud), Patchouli, Sandalwood and Amber',
        'rose,warm spicy,oud,amber,woody',
        'RosambyHistoires de Parfumsis a Amber Floral fragrance for women and men.Rosamwas launched in 2011. The nose behind this fragrance is Gerald Ghislain. Top notes are Rose and Citruses; middle notes are Taif Rose, Saffron and Incense; base notes are Agarwood (Oud), Patchouli, Sandalwood and Amber.',
        3.91,
        344,
        NULL
      ),
(
        'Veni-16463',
        'Veni Histoires de Parfums',
        'Veni',
        'for women and men',
        NULL,
        NULL,
        'Cardamom, Cinnamon, Lavender and Galbanum',
        'Guaiac Wood, Saffron and Tagetes',
        'Ambergris, Caramel, Vanilla, Benzoin, Patchouli, Musk and Oakmoss',
        'warm spicy,aromatic,amber,balsamic,cinnamon',
        'VenibyHistoires de Parfumsis a Woody Spicy fragrance for women and men.Veniwas launched in 2012. Top notes are Cardamom, Cinnamon, Lavender and Galbanum; middle notes are Guaiac Wood, Saffron and Tagetes; base notes are Ambergris, Caramel, Vanilla, Benzoin, Patchouli, Musk and Oakmoss.',
        3.99,
        431,
        NULL
      ),
(
        'Vici-16465',
        'Vici Histoires de Parfums',
        'Vici',
        'for women and men',
        NULL,
        NULL,
        'Aldehydes, Angelica, Galbanum, Violet Leaf, Cardamom, Basil and Red Berries',
        'Incense, Celery Seeds, Osmanthus and Iris',
        'Musk, Cedar, Raspberry and Patchouli',
        'musky,amber,green,aromatic,powdery',
        'VicibyHistoires de Parfumsis a Woody Floral Musk fragrance for women and men.Viciwas launched in 2012. Top notes are Aldehydes, Angelica, Galbanum, Violet Leaf, Cardamom, Basil and Red Berries; middle notes are Incense, Celery Seeds, Osmanthus and Iris; base notes are Musk, Cedar, Raspberry and Patchouli.',
        3.71,
        136,
        NULL
      ),
(
        'Vidi-16464',
        'Vidi Histoires de Parfums',
        'Vidi',
        'for women and men',
        NULL,
        NULL,
        'Cardamom and Cucumber',
        'Saffron, Cyclamen and Rose',
        'Immortelle, Musk, Ambergris, Woody Notes and Vanilla',
        'warm spicy,aquatic,ozonic,herbal,musky',
        'VidibyHistoires de Parfumsis a Aromatic fragrance for women and men.Vidiwas launched in 2012. Top notes are Cardamom and Cucumber; middle notes are Saffron, Cyclamen and Rose; base notes are Immortelle, Musk, Ambergris, Woody Notes and Vanilla.',
        3.58,
        115,
        NULL
      ),
(
        'Irreverent-47466',
        'Irrévérent Histoires de Parfums',
        'Irrévérent',
        'for women and men',
        NULL,
        'Luca Maffei',
        'elemi, Lavender and Bergamot',
        'Styrax, Agarwood (Oud) and Coffee',
        'Amber, Patchouli and Sandalwood',
        'amber,aromatic,balsamic,woody,warm spicy',
        'IrrévérentbyHistoires de Parfumsis a Woody Chypre fragrance for women and men.Irrévérentwas launched in 2017. The nose behind this fragrance is Luca Maffei. Top notes are elemi, Lavender and Bergamot; middle notes are Styrax, Agarwood (Oud) and Coffee; base notes are Amber, Patchouli and Sandalwood.',
        4.07,
        332,
        NULL
      ),
(
        'Outrecuidant-47467',
        'Outrecuidant Histoires de Parfums',
        'Outrecuidant',
        'for women and men',
        NULL,
        'Fanny Bal',
        'Pineapple, Grapefruit and Cassis',
        'Cardamom, Saffron and Orange Blossom',
        'Patchouli, Leather, Labdanum, Cedar and Sandalwood',
        'warm spicy,woody,leather,patchouli,aromatic',
        'OutrecuidantbyHistoires de Parfumsis a Leather fragrance for women and men.Outrecuidantwas launched in 2017. Outrecuidant was created by Fanny Bal and Julien Rasquinet. Top notes are Pineapple, Grapefruit and Cassis; middle notes are Cardamom, Saffron and Orange Blossom; base notes are Patchouli, Leather, Labdanum, Cedar and Sandalwood.',
        3.75,
        376,
        NULL
      ),
(
        'Prolixe-47468',
        'Prolixe Histoires de Parfums',
        'Prolixe',
        'for women and men',
        NULL,
        'Julien Rasquinet',
        'Cardamom and Ginger',
        'Rose, Chamomile and Olibanum',
        'Patchouli, Tobacco and Agarwood (Oud)',
        'warm spicy,aromatic,patchouli,rose,tobacco',
        'ProlixebyHistoires de Parfumsis a Amber Woody fragrance for women and men.Prolixewas launched in 2017. The nose behind this fragrance is Julien Rasquinet. Top notes are Cardamom and Ginger; middle notes are Rose, Chamomile and Olibanum; base notes are Patchouli, Tobacco and Agarwood (Oud).',
        3.99,
        338,
        NULL
      ),
(
        '1831-Norma-Bellini-27035',
        '1831 Norma Bellini Histoires de Parfums',
        '1831',
        'for women',
        NULL,
        NULL,
        'Aldehydes and Pink Pepper',
        'Ylang-Ylang, Jasmine, Rose and Labdanum',
        'Benzoin, Musk, Praline, Vanilla and Patchouli',
        'amber,aldehydic,yellow floral,sweet,musky',
        '1831 Norma BellinibyHistoires de Parfumsis a Floral fragrance for women.1831 Norma Belliniwas launched in 2014. Top notes are Aldehydes and Pink Pepper; middle notes are Ylang-Ylang, Jasmine, Rose and Labdanum; base notes are Benzoin, Musk, Praline, Vanilla and Patchouli.',
        3.54,
        50,
        NULL
      ),
(
        '1831-Norma-Bellini-Absolu-EdP-35286',
        '1831 Norma Bellini Absolu EdP Histoires de Parfums',
        '1831',
        'for women',
        NULL,
        NULL,
        'Aldehydes and Pink Pepper',
        'Jasmine, Ylang-Ylang, Labdanum and Rose',
        'Benzoin, Musk, Praline, Vanilla and Patchouli',
        'aldehydic,amber,fresh,white floral,sweet',
        '1831 Norma Bellini Absolu EdPbyHistoires de Parfumsis a Floral Aldehyde fragrance for women.1831 Norma Bellini Absolu EdPwas launched in 2014. Top notes are Aldehydes and Pink Pepper; middle notes are Jasmine, Ylang-Ylang, Labdanum and Rose; base notes are Benzoin, Musk, Praline, Vanilla and Patchouli.',
        4.18,
        60,
        NULL
      ),
(
        '1875-Carmen-Bizet-27030',
        '1875 Carmen Bizet Histoires de Parfums',
        '1875',
        'for women',
        NULL,
        NULL,
        'Ginger, Artemisia and Lemon',
        'White Flowers and Saffron',
        'Patchouli, Guaiac Wood, Incense and Sandalwood',
        'warm spicy,woody,patchouli,herbal,balsamic',
        '1875 Carmen BizetbyHistoires de Parfumsis a Amber Floral fragrance for women.1875 Carmen Bizetwas launched in 2014. Top notes are Ginger, Artemisia and Lemon; middle notes are White Flowers and Saffron; base notes are Patchouli, Guaiac Wood, Incense and Sandalwood.',
        3.6,
        48,
        NULL
      ),
(
        '1875-Carmen-Bizet-Absolu-EdP-35287',
        '1875 Carmen Bizet Absolu EdP Histoires de Parfums',
        '1875',
        'for women',
        NULL,
        NULL,
        'Ginger, Artemisia and Lemon',
        'Saffron and White Flowers',
        'Guaiac Wood, Incense, Sandalwood and Patchouli',
        'warm spicy,woody,herbal,smoky,white floral',
        '1875 Carmen Bizet Absolu EdPbyHistoires de Parfumsis a Woody fragrance for women.1875 Carmen Bizet Absolu EdPwas launched in 2014. Top notes are Ginger, Artemisia and Lemon; middle notes are Saffron and White Flowers; base notes are Guaiac Wood, Incense, Sandalwood and Patchouli.',
        4.12,
        69,
        NULL
      ),
(
        '1890-La-Dame-de-Pique-Tchaikovsky-27033',
        '1890 La Dame de Pique Tchaikovsky Histoires de Parfums',
        '1890',
        'for women',
        NULL,
        NULL,
        'Orange Blossom, Coriander and Pepper',
        'Rose and Jasmine',
        'Incense, Leather, Patchouli, Amber and Musk',
        'amber,warm spicy,smoky,leather,patchouli',
        '1890 La Dame de Pique TchaikovskybyHistoires de Parfumsis a Floral Woody Musk fragrance for women.1890 La Dame de Pique Tchaikovskywas launched in 2014. Top notes are Orange Blossom, Coriander and Pepper; middle notes are Rose and Jasmine; base notes are Incense, Leather, Patchouli, Amber and Musk.',
        4.17,
        64,
        NULL
      ),
(
        '1890-La-Dame-de-Pique-Tchaikovsky-Absolu-EdP-35289',
        '1890 La Dame de Pique Tchaikovsky Absolu EdP Histoires de Parfums',
        '1890',
        'for women',
        NULL,
        NULL,
        'Coriander, Orange Blossom and Pepper',
        'Rose and Jasmine',
        'Amber, Leather, Incense, Patchouli and Musk',
        'amber,white floral,smoky,leather,animalic',
        '1890 La Dame de Pique Tchaikovsky Absolu EdPbyHistoires de Parfumsis a Leather fragrance for women.1890 La Dame de Pique Tchaikovsky Absolu EdPwas launched in 2014. Top notes are Coriander, Orange Blossom and Pepper; middle notes are Rose and Jasmine; base notes are Amber, Leather, Incense, Patchouli and Musk.',
        4.3,
        90,
        NULL
      ),
(
        '1904-Madame-Butterfly-Puccini-Absolu-EdP-35290',
        '1904 Madame Butterfly Puccini Absolu EdP Histoires de Parfums',
        '1904',
        'for women',
        NULL,
        NULL,
        'Neroli and Mandarin Orange',
        'Orris and Heliotrope',
        'Sandalwood, Cedar and Musk',
        'powdery,woody,iris,citrus,vanilla',
        '1904 Madame Butterfly Puccini Absolu EdPbyHistoires de Parfumsis a Floral fragrance for women.1904 Madame Butterfly Puccini Absolu EdPwas launched in 2014. Top notes are Neroli and Mandarin Orange; middle notes are Orris and Heliotrope; base notes are Sandalwood, Cedar and Musk.',
        4.11,
        141,
        NULL
      ),
(
        '1905-Madame-Butterfly-Puccini-27028',
        '1905 Madame Butterfly Puccini Histoires de Parfums',
        '1905',
        'for women',
        NULL,
        NULL,
        'Neroli and Mandarin Orange',
        'Iris and Heliotrope',
        'Musk, Cedar and Sandalwood',
        'powdery,iris,woody,violet,musky',
        '1905 Madame Butterfly PuccinibyHistoires de Parfumsis a Floral Woody Musk fragrance for women.1905 Madame Butterfly Pucciniwas launched in 2014. Top notes are Neroli and Mandarin Orange; middle notes are Iris and Heliotrope; base notes are Musk, Cedar and Sandalwood.',
        4.12,
        59,
        NULL
      ),
(
        '1926-Turandot-Puccini-27026',
        '1926 Turandot Puccini Histoires de Parfums',
        '1926',
        'for women',
        NULL,
        NULL,
        'Narcissus, Ginger, Orange Blossom and Pear',
        'Carnation, Patchouli and Jasmine',
        'Leather, Incense and Amber',
        'warm spicy,amber,leather,smoky,yellow floral',
        '1926 Turandot PuccinibyHistoires de Parfumsis a Amber fragrance for women.1926 Turandot Pucciniwas launched in 2014. Top notes are Narcissus, Ginger, Orange Blossom and Pear; middle notes are Carnation, Patchouli and Jasmine; base notes are Leather, Incense and Amber.',
        3.8,
        50,
        NULL
      ),
(
        '1926-Turandot-Puccini-Absolu-EdP-35291',
        '1926 Turandot Puccini Absolu EdP Histoires de Parfums',
        '1926',
        'for women',
        NULL,
        NULL,
        'Narcissus, Orange Blossom, Ginger and Pear',
        'Carnation, Patchouli and Jasmine',
        'Leather, Incense and Amber',
        'warm spicy,white floral,floral,amber,leather',
        '1926 Turandot Puccini Absolu EdPbyHistoires de Parfumsis a Floral fragrance for women.1926 Turandot Puccini Absolu EdPwas launched in 2014. Top notes are Narcissus, Orange Blossom, Ginger and Pear; middle notes are Carnation, Patchouli and Jasmine; base notes are Leather, Incense and Amber.',
        4.1,
        61,
        NULL
      ),
(
        'This-Is-Not-A-Blue-Bottle-32394',
        'This Is Not A Blue Bottle Histoires de Parfums',
        'This',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Aldehydes and Orange',
        'Honey and Geranium',
        'Musk, Patchouli and Amber',
        'aldehydic,musky,citrus,fresh spicy,patchouli',
        'This Is Not A Blue BottlebyHistoires de Parfumsis a Amber fragrance for women and men.This Is Not A Blue Bottlewas launched in 2015. This Is Not A Blue Bottle was created by Gerald Ghislain and Julien Rasquinet. Top notes are Aldehydes and Orange; middle notes are Honey and Geranium; base notes are Musk, Patchouli and Amber.',
        3.76,
        1,
        NULL
      ),
(
        'This-Is-Not-A-Blue-Bottle-1-2-43415',
        'This Is Not A Blue Bottle 1.2 Histoires de Parfums',
        'This',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Ivy and Pink Pepper',
        'Ylang-Ylang, Lilac and Lily-of-the-Valley',
        'Vanilla, White Musk and Sandalwood',
        'floral,fresh,yellow floral,sweet,green',
        'This Is Not A Blue Bottle 1.2byHistoires de Parfumsis a Floral Woody Musk fragrance for women and men.This Is Not A Blue Bottle 1.2was launched in 2017. The nose behind this fragrance is Luca Maffei. Top notes are Ivy and Pink Pepper; middle notes are Ylang-Ylang, Lilac and Lily-of-the-Valley; base notes are Vanilla, White Musk and Sandalwood.',
        4.01,
        831,
        NULL
      ),
(
        'This-Is-Not-A-Blue-Bottle-1-3-43416',
        'This Is Not A Blue Bottle 1.3 Histoires de Parfums',
        'This',
        'for women and men',
        NULL,
        'Julien Rasquinet',
        'Blood Orange',
        'Rose and Saffron',
        'Leather and Patchouli Leaf',
        'leather,warm spicy,rose,citrus,patchouli',
        'This Is Not A Blue Bottle 1.3byHistoires de Parfumsis a Leather fragrance for women and men.This Is Not A Blue Bottle 1.3was launched in 2017. The nose behind this fragrance is Julien Rasquinet. Top note is Blood Orange; middle notes are Rose and Saffron; base notes are Leather and Patchouli Leaf.',
        3.82,
        438,
        NULL
      ),
(
        'This-Is-Not-A-Blue-Bottle-1-4-48567',
        'This Is Not A Blue Bottle 1.4 Histoires de Parfums',
        'This',
        'for women and men',
        NULL,
        'Gerald Ghislain',
        'Lavender, Cardamom and Artemisia',
        'Ylang-Ylang, Benzoin and Tonka Bean',
        'Opoponax, Labdanum and Patchouli',
        'amber,warm spicy,aromatic,sweet,lavender',
        'This Is Not A Blue Bottle 1.4byHistoires de Parfumsis a Amber Spicy fragrance for women and men.This Is Not A Blue Bottle 1.4was launched in 2018. The nose behind this fragrance is Gerald Ghislain. Top notes are Lavender, Cardamom and Artemisia; middle notes are Ylang-Ylang, Benzoin and Tonka Bean; base notes are Opoponax, Labdanum and Patchouli.',
        3.7,
        235,
        NULL
      ),
(
        'This-is-Not-A-Blue-Bottle-1-5-48568',
        'This is Not A Blue Bottle 1.5 Histoires de Parfums',
        'This',
        'for women and men',
        NULL,
        'Luca Maffei',
        'Ozonic notes, Aldehydes and Citruses',
        'Floral Notes',
        'Musk, Ambroxan and Mineral notes',
        'musky,amber,ozonic,aldehydic,fresh',
        'This is Not A Blue Bottle 1.5byHistoires de Parfumsis a Floral Aldehyde fragrance for women and men.This is Not A Blue Bottle 1.5was launched in 2018. The nose behind this fragrance is Luca Maffei. Top notes are Ozonic notes, Aldehydes and Citruses; middle note is Floral Notes; base notes are Musk, Ambroxan and Mineral notes.',
        3.81,
        317,
        NULL
      ),
(
        'This-is-not-a-Blue-Bottle-1-6-60117',
        'This is not a Blue Bottle 1.6 Histoires de Parfums',
        'This',
        'for women and men',
        NULL,
        NULL,
        'Yuzu, Orange and Grapefruit',
        'Neroli, Orange Blossom, Jasmine, Lotus and Geranium',
        'White Musk, Vetiver and Vanilla',
        'citrus,white floral,fresh spicy,sweet,aromatic',
        'This is not a Blue Bottle 1.6byHistoires de Parfumsis a Floral Fruity fragrance for women and men.This is not a Blue Bottle 1.6was launched in 2020. Top notes are Yuzu, Orange and Grapefruit; middle notes are Neroli, Orange Blossom, Jasmine, Lotus and Geranium; base notes are White Musk, Vetiver and Vanilla.',
        3.84,
        297,
        NULL
      );
