
INSERT INTO fragrances (
  fragrantica_id, name, brand, gender, year, perfumer,
  top_notes, middle_notes, base_notes, main_accords,
  description, rating, votes, image_url
) VALUES
(
        'Sidecar-Cocktail-80894',
        'Sidecar Cocktail The Dua Brand',
        'Sidecar',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,woody',
        'Sidecar CocktailbyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Sidecar Cocktailwas launched in 2022.',
        4,
        1,
        NULL
      ),
(
        'Siski-Pour-Femme-80762',
        'Siski Pour Femme The Dua Brand',
        'Siski',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,powdery,violet,iris,fruity',
        'Siski Pour FemmebyThe Dua Brandis a Floral Fruity fragrance for women.Siski Pour Femmewas launched in 2021.',
        4.25,
        4,
        NULL
      ),
(
        'Soulmate-80739',
        'Soulmate The Dua Brand',
        'Soulmate',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,coffee,lactonic,warm spicy',
        'SoulmatebyThe Dua Brandis a fragrance for women and men.Soulmatewas launched in 2019.',
        4.5,
        2,
        NULL
      ),
(
        'Sour-Apple-Candy-80854',
        'Sour Apple Candy The Dua Brand',
        'Sour',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,green,aquatic,sweet',
        'Sour Apple CandybyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Sour Apple Candywas launched in 2022.',
        4,
        4,
        NULL
      ),
(
        'Spice-Vanille-80850',
        'Spice & Vanille The Dua Brand',
        'Spice',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,warm spicy,sweet,aromatic,amber',
        'Spice & VanillebyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Spice & Vanillewas launched in 2022.',
        2,
        1,
        NULL
      ),
(
        'Spring-Bloom-80769',
        'Spring Bloom The Dua Brand',
        'Spring',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,fresh,floral,sweet,rose',
        'Spring BloombyThe Dua Brandis a Floral Fruity fragrance for women and men. This is a new fragrance.Spring Bloomwas launched in 2022.',
        5,
        4,
        NULL
      ),
(
        'Strawberry-Peach-Swirl-80858',
        'Strawberry & Peach Swirl The Dua Brand',
        'Strawberry',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fruity,sweet,musky,vodka,powdery',
        'Strawberry & Peach SwirlbyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Strawberry & Peach Swirlwas launched in 2022.',
        3.67,
        3,
        NULL
      ),
(
        'Strawberry-Cream-Candy-80833',
        'Strawberry Cream Candy The Dua Brand',
        'Strawberry',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,musky,vanilla,powdery',
        'Strawberry Cream CandybyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Strawberry Cream Candywas launched in 2022.',
        4.2,
        5,
        NULL
      ),
(
        'Strawberry-Daiquiri-80874',
        'Strawberry Daiquiri The Dua Brand',
        'Strawberry',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,rum,musky',
        'Strawberry DaiquiribyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Strawberry Daiquiriwas launched in 2022.',
        3.86,
        7,
        NULL
      ),
(
        'Strawberry-Milkshake-80840',
        'Strawberry Milkshake The Dua Brand',
        'Strawberry',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,sweet,fruity,powdery,lactonic',
        'Strawberry MilkshakebyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Strawberry Milkshakewas launched in 2022.',
        3.56,
        9,
        NULL
      ),
(
        'Strive-80776',
        'Strive The Dua Brand',
        'Strive',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'rose,leather,citrus,mossy,animalic',
        'StrivebyThe Dua Brandis a Leather fragrance for women and men. This is a new fragrance.Strivewas launched in 2022.',
        5,
        1,
        NULL
      ),
(
        'Sugar-Of-Garden-80955',
        'Sugar Of Garden The Dua Brand',
        'Sugar',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,fresh spicy,aromatic,vanilla',
        'Sugar Of GardenbyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Sugar Of Gardenwas launched in 2023.',
        4.75,
        8,
        NULL
      ),
(
        'Taboo-80736',
        'Taboo The Dua Brand',
        'Taboo',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,warm spicy,powdery,woody,leather',
        'TaboobyThe Dua Brandis a fragrance for women and men.Taboowas launched in 2021.',
        4.5,
        4,
        NULL
      ),
(
        'Tartness-of-Vanilla-80755',
        'Tartness of Vanilla The Dua Brand',
        'Tartness',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,citrus,cacao,floral,warm spicy',
        'Tartness of VanillabyThe Dua Brandis a fragrance for women and men.Tartness of Vanillawas launched in 2020.',
        4.4,
        5,
        NULL
      ),
(
        'Thai-Iced-Tea-80835',
        'Thai Iced Tea The Dua Brand',
        'Thai',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,cinnamon,aromatic,green,soft spicy',
        'Thai Iced TeabyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Thai Iced Teawas launched in 2022.',
        2.92,
        12,
        NULL
      ),
(
        'The-Mohawk-Cocktail-80916',
        'The Mohawk Cocktail The Dua Brand',
        'The',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,whiskey,citrus,musky,smoky',
        'The Mohawk CocktailbyThe Dua Brandis a Citrus Aromatic fragrance for women and men. This is a new fragrance.The Mohawk Cocktailwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'The-Ruler-Of-Them-All-80796',
        'The Ruler Of Them All The Dua Brand',
        'The',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,animalic,leather,oud,musky',
        'The Ruler Of Them AllbyThe Dua Brandis a fragrance for women and men.The Ruler Of Them Allwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        'The-Yuzu-Scent-80897',
        'The Yuzu Scent The Dua Brand',
        'The',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,green,fresh spicy,musky',
        'The Yuzu ScentbyThe Dua Brandis a Citrus fragrance for women and men. This is a new fragrance.The Yuzu Scentwas launched in 2022.',
        3.33,
        3,
        NULL
      ),
(
        'Traditional-Charm-80898',
        'Traditional Charm The Dua Brand',
        'Traditional',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,citrus,musky,powdery',
        'Traditional CharmbyThe Dua Brandis a Woody Aromatic fragrance for women and men. This is a new fragrance.Traditional Charmwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Tres-Leches-80923',
        'Tres Leches The Dua Brand',
        'Tres',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'vanilla,powdery,amber,iris,sweet',
        'Tres LechesbyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Tres Lecheswas launched in 2022.',
        3.89,
        9,
        NULL
      ),
(
        'Triple-Chocolate-Cake-80929',
        'Triple Chocolate Cake The Dua Brand',
        'Triple',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,chocolate,lactonic,warm spicy',
        'Triple Chocolate CakebyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Triple Chocolate Cakewas launched in 2022.',
        4.67,
        3,
        NULL
      ),
(
        'Tropicalia-80735',
        'Tropicalia The Dua Brand',
        'Tropicalia',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,fresh spicy,fruity',
        'TropicaliabyThe Dua Brandis a Citrus Aromatic fragrance for women and men.Tropicaliawas launched in 2019.',
        3.29,
        7,
        NULL
      ),
(
        'Undeniable-80800',
        'Undeniable The Dua Brand',
        'Undeniable',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,aromatic,citrus,warm spicy',
        'UndeniablebyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Undeniablewas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Une-Rose-Pakistani-80738',
        'Une Rose Pakistani The Dua Brand',
        'Une',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,leather,musky,powdery,rose',
        'Une Rose PakistanibyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Une Rose Pakistaniwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Unicorn-Milkshake-80878',
        'Unicorn Milkshake The Dua Brand',
        'Unicorn',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,lactonic,powdery',
        'Unicorn MilkshakebyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Unicorn Milkshakewas launched in 2022.',
        2.37,
        19,
        NULL
      ),
(
        'Vanilla-Boba-Milk-Tea-80939',
        'Vanilla Boba Milk Tea The Dua Brand',
        'Vanilla',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,vanilla,green,sweet,fresh',
        'Vanilla Boba Milk TeabyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Vanilla Boba Milk Teawas launched in 2023.',
        2.88,
        8,
        NULL
      ),
(
        'Vanilla-Brandy-80903',
        'Vanilla Brandy The Dua Brand',
        'Vanilla',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,vanilla,woody,powdery,musky',
        'Vanilla BrandybyThe Dua Brandis a Amber Woody fragrance for women and men. This is a new fragrance.Vanilla Brandywas launched in 2022.',
        3.83,
        6,
        NULL
      ),
(
        'Vanilla-Cake-Lemon-80861',
        'Vanilla Cake & Lemon The Dua Brand',
        'Vanilla',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,vanilla',
        'Vanilla Cake & LemonbyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Vanilla Cake & Lemonwas launched in 2022.',
        2.6,
        5,
        NULL
      ),
(
        'Vanilla-Cake-Whiskey-80942',
        'Vanilla Cake Whiskey The Dua Brand',
        'Vanilla',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,caramel,vanilla,whiskey,lactonic',
        'Vanilla Cake WhiskeybyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Vanilla Cake Whiskeywas launched in 2023.',
        4.67,
        3,
        NULL
      ),
(
        'Vanillac-Fantasy-80891',
        'Vanillac Fantasy The Dua Brand',
        'Vanillac',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,vanilla,sweet,yellow floral',
        'Vanillac FantasybyThe Dua Brandis a Amber Floral fragrance for women and men. This is a new fragrance.Vanillac Fantasywas launched in 2022.',
        5,
        1,
        NULL
      ),
(
        'Vanille-de-Mexico-80838',
        'Vanille de Mexico The Dua Brand',
        'Vanille',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,aromatic,soft spicy,fresh spicy,fruity',
        'Vanille de MexicobyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.Vanille de Mexicowas launched in 2022.',
        3,
        2,
        NULL
      ),
(
        'Vanity-for-Her-80780',
        'Vanity for Her The Dua Brand',
        'Vanity',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,fruity,woody,vanilla,powdery',
        'Vanity for HerbyThe Dua Brandis a fragrance for women.Vanity for Herwas launched in 2021.',
        4.33,
        3,
        NULL
      ),
(
        'Vanity-for-Him-80781',
        'Vanity for Him The Dua Brand',
        'Vanity',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,woody,fruity,aromatic',
        'Vanity for HimbyThe Dua Brandis a fragrance for men.Vanity for Himwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Voluptuous-80774',
        'Voluptuous The Dua Brand',
        'Voluptuous',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,woody,warm spicy',
        'VoluptuousbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.Voluptuouswas launched in 2021.',
        4.5,
        2,
        NULL
      ),
(
        'Whipped-French-Vanilla-80930',
        'Whipped French Vanilla The Dua Brand',
        'Whipped',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,lactonic,powdery',
        'Whipped French VanillabyThe Dua Brandis a fragrance for women and men. This is a new fragrance.Whipped French Vanillawas launched in 2022.',
        4.38,
        8,
        NULL
      ),
(
        'Whipped-Lemonade-80928',
        'Whipped Lemonade The Dua Brand',
        'Whipped',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,sweet,vanilla,fresh,lactonic',
        'Whipped LemonadebyThe Dua Brandis a Citrus Gourmand fragrance for women and men. This is a new fragrance.Whipped Lemonadewas launched in 2022.',
        4.25,
        4,
        NULL
      ),
(
        'White-Hot-Chocolate-Rum-80834',
        'White Hot Chocolate & Rum The Dua Brand',
        'White',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,chocolate,rum,warm spicy,woody',
        'White Hot Chocolate & RumbyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.White Hot Chocolate & Rumwas launched in 2022.',
        4.4,
        5,
        NULL
      ),
(
        'White-Hot-Chocolate-Cacao-80940',
        'White Hot Chocolate Cacao The Dua Brand',
        'White',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'cinnamon,warm spicy,vanilla',
        'White Hot Chocolate CacaobyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.White Hot Chocolate Cacaowas launched in 2023.',
        4,
        4,
        NULL
      ),
(
        'Workout-Elixir-80931',
        'Workout Elixir The Dua Brand',
        'Workout',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,green,woody,aromatic,fresh',
        'Workout ElixirbyThe Dua Brandis a Citrus Aromatic fragrance for women and men. This is a new fragrance.Workout Elixirwas launched in 2022.',
        4.31,
        16,
        NULL
      ),
(
        'World-s-Best-Key-Lime-Pie-80871',
        'World’s Best Key Lime Pie The Dua Brand',
        'World’s',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,powdery',
        'World’s Best Key Lime PiebyThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men. This is a new fragrance.World’s Best Key Lime Piewas launched in 2022.',
        3.1,
        10,
        NULL
      ),
(
        'Your-Wish-is-My-Command-80753',
        'Your Wish is My Command! The Dua Brand',
        'Your',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,powdery,amber,vanilla,rose',
        'Your Wish is My Command!byThe Dua Brandis a Floral Fruity Gourmand fragrance for women and men.Your Wish is My Command!was launched in 2020.',
        4.25,
        4,
        NULL
      ),
(
        'Gracieuse-80792',
        'Gracieuse The Dua Brand',
        'Gracieuse',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,woody,citrus,musky,yellow floral',
        'GracieusebyThe Dua Brandis a Floral fragrance for women.Gracieusewas launched in 2021.',
        4,
        1,
        NULL
      ),
(
        'Moelleuse-80793',
        'Moelleuse The Dua Brand',
        'Moelleuse',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,powdery,warm spicy,sweet,aromatic',
        'MoelleusebyThe Dua Brandis a fragrance for women.Moelleusewas launched in 2021.',
        4.5,
        2,
        NULL
      ),
(
        'Mysterieux-80794',
        'Mysterieux The Dua Brand',
        'Mysterieux',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'leather,warm spicy,oud,fresh spicy,animalic',
        'MysterieuxbyThe Dua Brandis a fragrance for men.Mysterieuxwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        'Vigoureux-80795',
        'Vigoureux The Dua Brand',
        'Vigoureux',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,vanilla,citrus,warm spicy',
        'VigoureuxbyThe Dua Brandis a Citrus Aromatic fragrance for men.Vigoureuxwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        'Compliment-For-Her-80819',
        'Compliment For Her The Dua Brand',
        'Compliment',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,citrus,musky,fruity,floral',
        'Compliment For HerbyThe Dua Brandis a fragrance for women. This is a new fragrance.Compliment For Herwas launched in 2022.',
        4,
        5,
        NULL
      ),
(
        'Confidence-For-Her-80818',
        'Confidence For Her The Dua Brand',
        'Confidence',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fruity,floral,aquatic,fresh',
        'Confidence For HerbyThe Dua Brandis a Floral Aquatic fragrance for women. This is a new fragrance.Confidence For Herwas launched in 2022.',
        4,
        2,
        NULL
      ),
(
        'In-The-Club-For-Her-80816',
        'In The Club For Her The Dua Brand',
        'In',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,white floral,soft spicy,floral,fruity',
        'In The Club For HerbyThe Dua Brandis a fragrance for women. This is a new fragrance.In The Club For Herwas launched in 2022.',
        4,
        2,
        NULL
      ),
(
        'Romantic-For-Her-80814',
        'Romantic For Her The Dua Brand',
        'Romantic',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,woody,powdery,caramel',
        'Romantic For HerbyThe Dua Brandis a fragrance for women. This is a new fragrance.Romantic For Herwas launched in 2022.',
        3.71,
        7,
        NULL
      ),
(
        'Seduction-For-Her-80813',
        'Seduction For Her The Dua Brand',
        'Seduction',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,vanilla,rose,powdery,ozonic',
        'Seduction For HerbyThe Dua Brandis a fragrance for women. This is a new fragrance.Seduction For Herwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Adapt-85655',
        '#Adapt The Dua Brand',
        '#Adapt',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,sweet,earthy,powdery,aromatic',
        '#AdaptbyThe Dua Brandis a Amber fragrance for women and men.#Adaptwas launched in 2022.',
        4,
        1,
        NULL
      ),
(
        'Addicted-85656',
        '#Addicted The Dua Brand',
        '#Addicted',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,citrus,floral,white floral,warm spicy',
        '#AddictedbyThe Dua Brandis a Woody Spicy fragrance for men.#Addictedwas launched in 2021.',
        3.75,
        4,
        NULL
      ),
(
        'Attitude-85657',
        '#Attitude The Dua Brand',
        '#Attitude',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,amber,woody,aromatic,citrus',
        '#AttitudebyThe Dua Brandis a Amber fragrance for men.#Attitudewas launched in 2020.',
        4,
        2,
        NULL
      ),
(
        'BeachVibes-85658',
        '#BeachVibes The Dua Brand',
        '#BeachVibes',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,fresh spicy,green,woody',
        '#BeachVibesbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.#BeachVibeswas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Blessed-85659',
        '#Blessed The Dua Brand',
        '#Blessed',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,powdery,musky,woody,vanilla',
        '#BlessedbyThe Dua Brandis a Floral Woody Musk fragrance for women and men.#Blessedwas launched in 2020.',
        3.6,
        5,
        NULL
      ),
(
        'Bliss-85660',
        '#Bliss The Dua Brand',
        '#Bliss',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,white floral,woody,powdery,sweet',
        '#BlissbyThe Dua Brandis a Amber fragrance for women and men.#Blisswas launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'By-Accident-85661',
        '#By Accident The Dua Brand',
        '#By',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'sweet,vanilla,fresh spicy,amber,aromatic',
        '#By AccidentbyThe Dua Brandis a Aromatic fragrance for women and men.#By Accidentwas launched in 2020.',
        5,
        1,
        NULL
      ),
(
        'Candy-85662',
        '#Candy The Dua Brand',
        '#Candy',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,aromatic,green,leather,mossy',
        '#CandybyThe Dua Brandis a Aromatic fragrance for men.#Candywas launched in 2020.',
        4,
        2,
        NULL
      ),
(
        'Ego-85663',
        '#Ego The Dua Brand',
        '#Ego',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,leather,aromatic,floral',
        '#EgobyThe Dua Brandis a Leather fragrance for men.#Egowas launched in 2020.',
        2,
        2,
        NULL
      ),
(
        'Emotional-85664',
        '#Emotional The Dua Brand',
        '#Emotional',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic,fresh,floral',
        '#EmotionalbyThe Dua Brandis a Aromatic fragrance for men.#Emotionalwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Energetic-85665',
        '#Energetic The Dua Brand',
        '#Energetic',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,fresh spicy,aromatic,amber,musky',
        '#EnergeticbyThe Dua Brandis a Citrus fragrance for men.#Energeticwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'FierceAttar-85678',
        '#FierceAttar The Dua Brand',
        '#FierceAttar',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,citrus,white floral,fresh spicy',
        '#FierceAttarbyThe Dua Brandis a Citrus fragrance for men.#FierceAttarwas launched in 2021.',
        4.8,
        5,
        NULL
      ),
(
        'HisSummer2018-86742',
        '#HisSummer2018 The Dua Brand',
        '#HisSummer2018',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fruity,fresh spicy,woody,sweet',
        '#HisSummer2018byThe Dua Brandis a Aromatic fragrance for men.#HisSummer2018was launched in 2023.',
        NULL,
        NULL,
        NULL
      ),
(
        'Imagine-85679',
        '#Imagine The Dua Brand',
        '#Imagine',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,amber,fresh,fresh spicy,green',
        '#ImaginebyThe Dua Brandis a Leather fragrance for women and men.#Imaginewas launched in 2021.',
        5,
        10,
        NULL
      ),
(
        'Intensified-85680',
        '#Intensified The Dua Brand',
        '#Intensified',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,balsamic,earthy,patchouli',
        '#IntensifiedbyThe Dua Brandis a Woody Floral Musk fragrance for women and men.#Intensifiedwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'Kisses-85681',
        '#Kisses The Dua Brand',
        '#Kisses',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,musky,tuberose,woody,animalic',
        '#KissesbyThe Dua Brandis a Woody Floral Musk fragrance for women.#Kisseswas launched in 2021.',
        4.5,
        2,
        NULL
      ),
(
        'Lucky-85682',
        '#Lucky The Dua Brand',
        '#Lucky',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,aldehydic,earthy,white floral',
        '#LuckybyThe Dua Brandis a Floral Aldehyde fragrance for women and men.#Luckywas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        'LuminousFemme-85683',
        '#LuminousFemme The Dua Brand',
        '#LuminousFemme',
        'for women',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'patchouli,warm spicy,rose,woody,earthy',
        '#LuminousFemmebyThe Dua Brandis a Floral fragrance for women.#LuminousFemmewas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Magnetic-85684',
        '#Magnetic The Dua Brand',
        '#Magnetic',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'powdery,amber,woody,warm spicy,leather',
        '#MagneticbyThe Dua Brandis a Amber fragrance for men.#Magneticwas launched in 2020.',
        5,
        2,
        NULL
      ),
(
        'Mega-85685',
        '#Mega The Dua Brand',
        '#Mega',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,animalic,amber,floral,powdery',
        '#MegabyThe Dua Brandis a Floral Aquatic fragrance for women and men.#Megawas launched in 2021.',
        5,
        3,
        NULL
      ),
(
        'NoPerfume-85686',
        '#NoPerfume The Dua Brand',
        '#NoPerfume',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,musky',
        '#NoPerfumebyThe Dua Brandis a Woody Floral Musk fragrance for women and men.#NoPerfumewas launched in 2021.',
        3,
        2,
        NULL
      ),
(
        'Pleasure-85687',
        '#Pleasure The Dua Brand',
        '#Pleasure',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'warm spicy,woody,aromatic,citrus,white floral',
        '#PleasurebyThe Dua Brandis a Leather fragrance for women and men.#Pleasurewas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Sillage-85688',
        '#Sillage The Dua Brand',
        '#Sillage',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,woody,citrus,vanilla,sweet',
        '#SillagebyThe Dua Brandis a Woody Aromatic fragrance for women and men.#Sillagewas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        'Soapy-85689',
        '#Soapy The Dua Brand',
        '#Soapy',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,coconut,white floral,lavender,musky',
        '#SoapybyThe Dua Brandis a Floral fragrance for women and men.#Soapywas launched in 2021.',
        4.5,
        4,
        NULL
      ),
(
        'TheMeteore-85690',
        '#TheMeteore The Dua Brand',
        '#TheMeteore',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,fresh spicy,aromatic,warm spicy,woody',
        '#TheMeteorebyThe Dua Brandis a Citrus fragrance for women and men.#TheMeteorewas launched in 2021.',
        4.17,
        6,
        NULL
      ),
(
        'Throwback1995-85691',
        '#Throwback1995 The Dua Brand',
        '#Throwback1995',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,woody,green,herbal',
        '#Throwback1995byThe Dua Brandis a Aromatic Green fragrance for men.#Throwback1995was launched in 2021.',
        4,
        1,
        NULL
      ),
(
        'Vibrations-85692',
        '#Vibrations The Dua Brand',
        '#Vibrations',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'floral,sweet,honey,powdery,musky',
        '#VibrationsbyThe Dua Brandis a Floral fragrance for women and men.#Vibrationswas launched in 2022.',
        4.5,
        2,
        NULL
      ),
(
        'Youngego-85693',
        '#Youngego The Dua Brand',
        '#Youngego',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,woody,lavender,herbal',
        '#YoungegobyThe Dua Brandis a Woody Floral Musk fragrance for men.#Youngegowas launched in 2020.',
        4.33,
        3,
        NULL
      ),
(
        '1-Only-Luminous-85694',
        '1 & Only Luminous The Dua Brand',
        '1',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'fresh spicy,aromatic,amber,herbal,warm spicy',
        '1 & Only LuminousbyThe Dua Brandis a Amber fragrance for men.1 & Only Luminouswas launched in 2021.',
        3.56,
        9,
        NULL
      ),
(
        '1-And-Only-85695',
        '1 And Only The Dua Brand',
        '1',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,warm spicy,citrus,fresh spicy,amber',
        '1 And OnlybyThe Dua Brandis a Woody Spicy fragrance for men.1 And Onlywas launched in 2020.',
        5,
        3,
        NULL
      ),
(
        '10-Shades-of-Gaiac-85696',
        '10 Shades of Gaiac The Dua Brand',
        '10',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,musky,powdery,fresh spicy',
        '10 Shades of GaiacbyThe Dua Brandis a Woody fragrance for women and men.10 Shades of Gaiacwas launched in 2020.',
        4,
        1,
        NULL
      ),
(
        '100-Whispers-85697',
        '100 Whispers The Dua Brand',
        '100',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,woody,powdery,iris,vanilla',
        '100 WhispersbyThe Dua Brandis a Floral Fruity fragrance for women and men.100 Whisperswas launched in 2021.',
        4.67,
        6,
        NULL
      ),
(
        '18-Shades-of-Bigarade-85698',
        '18 Shades of Bigarade The Dua Brand',
        '18',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,citrus,woody,amber,musky',
        '18 Shades of BigaradebyThe Dua Brandis a Amber fragrance for women and men.18 Shades of Bigaradewas launched in 2020.',
        4,
        1,
        NULL
      ),
(
        '18-Shades-of-Labdanum-85699',
        '18 Shades of Labdanum The Dua Brand',
        '18',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,woody,amber,leather,vanilla',
        '18 Shades of LabdanumbyThe Dua Brandis a Amber fragrance for women and men.18 Shades of Labdanumwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        '19-Shades-of-Baie-85700',
        '19 Shades of Baie The Dua Brand',
        '19',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'musky,green,woody,amber,aromatic',
        '19 Shades of BaiebyThe Dua Brandis a Aromatic Green fragrance for women and men.19 Shades of Baiewas launched in 2020.',
        4,
        2,
        NULL
      ),
(
        '19-Shades-of-Benzoin-85701',
        '19 Shades of Benzoin The Dua Brand',
        '19',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,musky,powdery,warm spicy',
        '19 Shades of BenzoinbyThe Dua Brandis a Amber fragrance for women and men.19 Shades of Benzoinwas launched in 2018.',
        NULL,
        NULL,
        NULL
      ),
(
        '22-Shades-of-Bergamot-85702',
        '22 Shades of Bergamot The Dua Brand',
        '22',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,aromatic,powdery,white floral',
        '22 Shades of BergamotbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.22 Shades of Bergamotwas launched in 2017.',
        4.33,
        3,
        NULL
      ),
(
        '24-Shades-of-Patchouli-85703',
        '24 Shades of Patchouli The Dua Brand',
        '24',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,leather,patchouli,vanilla',
        '24 Shades of PatchoulibyThe Dua Brandis a Woody Chypre fragrance for women and men.24 Shades of Patchouliwas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        '24k-Oud-85704',
        '24k Oud The Dua Brand',
        '24k',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'oud,rose,woody,warm spicy,metallic',
        '24k OudbyThe Dua Brandis a Woody fragrance for women and men.24k Oudwas launched in 2022.',
        NULL,
        NULL,
        NULL
      ),
(
        '25-Shades-of-Another-Bergamot-85705',
        '25 Shades of Another Bergamot The Dua Brand',
        '25',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,amber,musky,aromatic',
        '25 Shades of Another BergamotbyThe Dua Brandis a Amber fragrance for women and men.25 Shades of Another Bergamotwas launched in 2021.',
        4,
        1,
        NULL
      ),
(
        '28-Shades-of-Citron-85706',
        '28 Shades of Citron The Dua Brand',
        '28',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,musky,white floral,woody,warm spicy',
        '28 Shades of CitronbyThe Dua Brandis a Citrus Aromatic fragrance for women and men.28 Shades of Citronwas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        '28-Shades-of-Tabacum-85707',
        '28 Shades of Tabacum The Dua Brand',
        '28',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,tobacco,rum,aromatic',
        '28 Shades of TabacumbyThe Dua Brandis a Woody Aromatic fragrance for women and men.28 Shades of Tabacumwas launched in 2019.',
        NULL,
        NULL,
        NULL
      ),
(
        '3-14-85708',
        '3.14 The Dua Brand',
        '3.14',
        'for men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'aromatic,fresh spicy,vanilla,anis,citrus',
        '3.14byThe Dua Brandis a Amber fragrance for men.3.14was launched in 2021.',
        3,
        1,
        NULL
      ),
(
        '30-Shades-of-Oak-Moss-85709',
        '30 Shades of Oak Moss The Dua Brand',
        '30',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,warm spicy,earthy,cinnamon,mossy',
        '30 Shades of Oak MossbyThe Dua Brandis a Chypre fragrance for women and men.30 Shades of Oak Mosswas launched in 2022.',
        5,
        1,
        NULL
      ),
(
        '31-Shades-of-Rosa-85710',
        '31 Shades of Rosa The Dua Brand',
        '31',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'amber,woody,fresh spicy,rose',
        '31 Shades of RosabyThe Dua Brandis a Woody Floral Musk fragrance for women and men.31 Shades of Rosawas launched in 2020.',
        4,
        3,
        NULL
      ),
(
        '33-Shades-of-Santal-85711',
        '33 Shades of Santal The Dua Brand',
        '33',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,powdery,violet,leather,warm spicy',
        '33 Shades of SantalbyThe Dua Brandis a Woody Aromatic fragrance for women and men.33 Shades of Santalwas launched in 2019.',
        3.5,
        2,
        NULL
      ),
(
        '37-Shades-of-Limette-85712',
        '37 Shades of Limette The Dua Brand',
        '37',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,aromatic,warm spicy,white floral,musky',
        '37 Shades of LimettebyThe Dua Brandis a Citrus Aromatic fragrance for women and men.37 Shades of Limettewas launched in 2021.',
        NULL,
        NULL,
        NULL
      ),
(
        '41-Shades-of-Lys-85713',
        '41 Shades of Lys The Dua Brand',
        '41',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'white floral,musky,tuberose,vanilla,woody',
        '41 Shades of LysbyThe Dua Brandis a Floral fragrance for women and men.41 Shades of Lyswas launched in 2021.',
        5,
        1,
        NULL
      ),
(
        '44-Shades-of-Vanilla-85714',
        '44 Shades of Vanilla The Dua Brand',
        '44',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'citrus,woody,aldehydic,vanilla,smoky',
        '44 Shades of VanillabyThe Dua Brandis a Floral Woody Musk fragrance for women and men.44 Shades of Vanillawas launched in 2017.',
        4.33,
        3,
        NULL
      ),
(
        '46-Shades-of-Vetiver-85715',
        '46 Shades of Vetiver The Dua Brand',
        '46',
        'for women and men',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'woody,amber,fresh spicy,warm spicy,aromatic',
        '46 Shades of VetiverbyThe Dua Brandis a Woody Chypre fragrance for women and men.46 Shades of Vetiverwas launched in 2021.',
        NULL,
        NULL,
        NULL
      );
